### ISSUE TITLE
popover结合tabs使用  连续切换3次，内容都是一样的，内容区会在切换到最后一个时候变宽

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#100]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
windows10  chrome67.0.3396.99  vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pjzqn5wx27)

### Steps to reproduce
建立一个popover，当中建个tabs切换，内容都是一样的，
依次点击tab1，2，3，会发现，当点击到第三个的时候内容区突然变宽了

### What is expected?
tab的内容如果是一样的话不应该变宽

### What is actually happening?
tab的内容都一样，但是内容区当切换到最后一个的时候会变宽

**Comment by tangjinzhou** [comment]
这个demo链接并没有复现你说的这个问题

**Comment by tangjinzhou** [comment]
参考[#9005](https://github.com/ant-design/ant-design/issues/9005)
