### ISSUE TITLE
upload上传组件设置fileList上传状态失效

### ISSUE THREAD

**Issue by leeJangWoo-cc** [vueComponent/ant-design-vue#1001]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
1.3.9

### Reproduction link
https://codesandbox.io/s/vue-antd-template-n4bo0?fontsize=14
(经过群主教育，附上复现链接)

### Steps to reproduce
循环一个上传图片的列表，当已上传列表值设置为  :fileList="fileList[index]" 时，点击上传新图片，状态一直在uploading

### What is expected?
改变状态，并带来正常上传页面效果

### What is actually happening?
状态值不更新

**Comment by leeJangWoo-cc** [comment]
继续：只要是出现在循环里面的上传就有这种情况，
将:fileList="fileList[index]"更改为:fileList="fileList“测试循环列表中的上传，出现uploading无法上传
将:fileList="fileList[index]"更改为:defaultFileList="fileList[index]"时发现，上传成功，但是页面切换（非页面刷新）时候dom无法刷新

**Comment by leeJangWoo-cc** [comment]
继续：发现关于默认值，文档描述
当我动态改变 defaultValue,defaultOpenKeys, initialValue等defaultXxxx的时候它并没有生效。 #
Input/Select 等的 defaultXxxx（例如 defaultValue）只有在组件第一次渲染的时候有效，此特性参考自React。
切记：第一次、第一次、第一次....
那么必须要用fileList来做上传列表的值，我已无能为力，救救孩子吧

**Comment by LiLixikun** [comment]
我也遇到同样的问题，当使用fileList 不会触发 status === done 状态 一直处于 uploading 无法上传，使用defaultFileList 可以上传，但是无法再次修改上传列表
