### ISSUE TITLE
循环一个upload上传组件出现的问题

### ISSUE THREAD

**Issue by leeJangWoo-cc** [vueComponent/ant-design-vue#1002]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
1.3.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-n4bo0?fontsize=14)

### Steps to reproduce
循环一个upload上传组件
上传图片的时候遇到上传的status一直是uploading

### What is expected?
上传图片的时候遇到上传的status一直是uploading

### What is actually happening?
上传新的图片的时候一直是uploading，我该怎么做呢

**Comment by wangxueliang** [comment]
![image](https://user-images.githubusercontent.com/4122593/61726221-e1bc4f80-ada3-11e9-8e69-e02bb5b9898d.png) demo没浮现你所描述的问题！！！
ps: demo写的有点问题，导致的问题就是上传成功了，列表没有更新

**Comment by leeJangWoo-cc** [comment]
原来要强制更新，受教了
我因为要在change事件里面做一些相关判断，
没写this.fileList[index] = fileList这行发现console.log(fileList)只会打印一次，这是正常的吗？
谢谢解答，万分感谢

> ![image](https://user-images.githubusercontent.com/4122593/61726221-e1bc4f80-ada3-11e9-8e69-e02bb5b9898d.png) demo没浮现你所描述的问题！！！
> ps: demo写的有点问题，导致的问题就是上传成功了，列表没有更新

**Comment by wangxueliang** [comment]
你添加了fileList,就是受控的，代码控制不多次执行，保持ant-design一样的逻辑

**Comment by tangjinzhou** [comment]
`this.fileList[index] = fileList` 并不会触发更新，所以要强制 
`this.fileList[index] = fileList; this.fileList = [...this.fileList];`  改成这样也可以  
这是 Vue 机制
