### ISSUE TITLE
How to set condition in :class in element <a-menu-item/>

### ISSUE THREAD

**Issue by CuongStf** [vueComponent/ant-design-vue#1009]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-nm31z)

### Steps to reproduce
When i set condition to render class in element <a-menu-item/>. But it just only render 0 and 1?

### What is expected?
How to set :class=['something'] in tag `<a-menu-item/>`

### What is actually happening?
Just only render 0 and 1

---
```
<a-menu-item
key="1"
:class="[`menuWrapper`, !isCollapse ? 'expand' : 'collapse']"
/>
```

**Comment by tangjinzhou** [comment]
You can use `[].join(' ')`.  We will fix it later.
https://codesandbox.io/s/vue-antd-template-7i6ce

**Comment by CuongStf** [comment]
Many thanks
