### ISSUE TITLE
Fixed left menu tab

### ISSUE THREAD

**Issue by yang131323** [vueComponent/ant-design-vue#101]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
The left menu bar is inconvenient to read the document as the page slides.

### What does the proposed API look like?
User-friendly

**Comment by tangjinzhou** [comment]
Optimized.
If you have a better idea, welcome  discuss and pr.
