### ISSUE TITLE
datePicker 添加默认渲染slot支持功能在1.3.13版本中无效

### ISSUE THREAD

**Issue by Sun79** [vueComponent/ant-design-vue#1010]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.13

### Environment
windows 10 x64, chrome 75.0.3770.142 x64, vue 2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-pkcxr?fontsize=14)

### Steps to reproduce
使用的是官方示例中的模板，但是无法正确生效。

### What is expected?
datePicker 添加默认渲染slot功能可以正常使用。

### What is actually happening?
datePicker 添加默认渲染slot支持功能在新版本中无效。

**Comment by tangjinzhou** [comment]
升级 vue 到 2.6+  或者 使用  slot-scope
