### ISSUE TITLE
能否给一个抽屉的 handle   基于 template 的例子嘛

### ISSUE THREAD

**Issue by greenhat616** [vueComponent/ant-design-vue#1011]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
handle 类型为 vnode, slot. 看官方例子用的是 jsx（vnode) ， 但还是不清楚怎么用 template 实现。
话说 `site/components/layout.vue` 连 handle 都没加就有了 `<div class="drawer-handle">` 块。。 能否为小弟解惑下， 这是啥骚操作

### What does the proposed API look like?
wsl 1.0, chrome 75. vue 2.6.x

**Comment by sendya** [comment]
```vue
<template slot="handle">
   123
</template>
```

**Comment by 1442916418** [comment]
请问！怎么解决这个问题！！！急！急！急！
谢谢！谢谢！

**Comment by 1442916418** [comment]
> * [x]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> handle 类型为 vnode, slot. 看官方例子用的是 jsx（vnode) ， 但还是不清楚怎么用 template 实现。
> 话说 `site/components/layout.vue` 连 handle 都没加就有了 `<div class="drawer-handle">` 块。。 能否为小弟解惑下， 这是啥骚操作
> 
> ### What does the proposed API look like?
> wsl 1.0, chrome 75. vue 2.6.x

请问你解决问题了吗?

应该怎么实现抽屉效果，请告知！谢谢！
