### ISSUE TITLE
daterange picker 弹出月份选择框不能同时选择同一月

### ISSUE THREAD

**Issue by chenqifa** [vueComponent/ant-design-vue#1012]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Vue版本

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/](https://vue.ant.design/components/date-picker-cn/)

### Steps to reproduce
daterange picker 弹出月份选择框不能同时选择同一月

### What is expected?
daterange picker 弹出月份选择框能够选同一月

### What is actually happening?
daterange picker 不能够选同一月

**Comment by xrkffgg** [comment]
不能选择一个月 正常吧，不然左边右边就一样了。。。。显示2个就是为了跨月选择的，如果想选一个月中的范围，直接在左边或者右边选就行了

**Comment by lronelove** [comment]
> 不能选择一个月 正常吧，不然左边右边就一样了。。。。显示2个就是为了跨月选择的，如果想选一个月中的范围，直接在左边或者右边选就行了
你可以试试，点击两次左边不行的，没办大自己单独用两个日期封装了一个
