### ISSUE TITLE
How to set default value when list in a-select is array of object?

### ISSUE THREAD

**Issue by CuongStf** [vueComponent/ant-design-vue#1013]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-helxq)

### Steps to reproduce
I can't set value default of a-select when list in a-select-item is object although set :key in v-for is a key in object

### What is expected?
Set default value in a-select

### What is actually happening?
can't not set defaultValue

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-antd-template-u4v0g
