### ISSUE TITLE
table：开启复选框当数据大于100不分页，同页面的input，switch组件明显出现卡顿

### ISSUE THREAD

**Issue by yezi12138** [vueComponent/ant-design-vue#1019]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
win10/vue2.5.22

### Reproduction link
[https://preview.pro.loacg.com/profile/advanced](https://preview.pro.loacg.com/profile/advanced)

### Steps to reproduce
高级详情页-操作日志一下：
1:  增加返回的数据量 > 100，并且表格不分页
2:  开启表格勾选功能
3：在表格上方添加input / switch组件，并且使用v-model绑定值 （不绑定则不会出现问题）
4：在input中输入文字

### What is expected?
表单的使用不卡顿

### What is actually happening?
表单的使用卡顿，input大约延迟2s，switch1s

**Comment by hulei2014** [comment]
遇到了同样的问题

**Comment by tangjinzhou** [comment]
每次input或switch 的改变都会导致整个table的刷新，还是建议使用分页

**Comment by beyern** [comment]
使用了:scroll="{x:2000}"后，卡顿特别明显。希望能解决一下。目前的方案就是自己控制滚动。但是无法使用列固定功能。

**Comment by tangjinzhou** [comment]
输入区域（input）、展示区域（table）可以分成两个单文件组件会有不错的性能提升

**Comment by Liu-Ya** [comment]
> 输入区域（input）、展示区域（table）可以分成两个单文件组件会有不错的性能提升

这样做起来实在很麻烦，这是一个bug吗？有没有计划修复？😂

**Comment by tangjinzhou** [comment]
ref #1049
