### ISSUE TITLE
Tooltip 在Avatar组件上不生效

### ISSUE THREAD

**Issue by iczer** [vueComponent/ant-design-vue#102]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
win10 chrome 版本 67.0.3396.99

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m34o78xm38)

### Steps to reproduce
```
<a-tooltip title="不会显示tip">
<a-avatar src="https://gw.alipayobjects.com/zos/rmsportal/ZiESqWwCXBRQoaPONSJe.png" size=large />
</a-tooltip>
```

### What is expected?
Tooltip 在Avatar组件上可以生效

### What is actually happening?
Tooltip 在Avatar组件上不生效

**Comment by tangjinzhou** [comment]
@wangxueliang 兼容下avatar对mouse事件的监听

下个版本修复，临时解决方案avatar外层加一层标签
如：https://codesandbox.io/s/rw5yv55rxm

**Comment by iczer** [comment]
感谢
