### ISSUE TITLE
How to use wrapperComponentRef on From

### ISSUE THREAD

**Issue by SimpleSunLight** [vueComponent/ant-design-vue#1025]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
wrapperComponentRef is not work

### What does the proposed API look like?
wrapperComponentRef ={(formRef) => this.formRef = fomRef}

**Comment by tangjinzhou** [comment]
`wrappedComponentRef` not `wrapperComponentRef `

**Comment by SimpleSunLight** [comment]
> `wrappedComponentRef` not `wrapperComponentRef `

sorry， i'm too careless
