### ISSUE TITLE
a-range-picker moment时间inValid date

### ISSUE THREAD

**Issue by gitspringcould** [vueComponent/ant-design-vue#1028]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
windows10,google75.0.3770.142,vue2.x

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
页面加载初始化时间，格式化为YYYY-MM-DD，调用组件a-range-picker设置默认值，页面显示invalid date

### What is expected?
通过moment(value,format)能够显示默认值

### What is actually happening?
官方文档要求的数据格式完全一致

**Comment by sendya** [comment]
请提供复现代码，可以使用 codesandbox

**Comment by gitspringcould** [comment]
谢谢，问题解决了




------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 下午2:48
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] a-range-picker moment时间inValid date (#1028)




请提供复现代码，可以使用 codesandbox

**Comment by wanghong2013** [comment]
怎么解决的啊

**Comment by gitspringcould** [comment]
在created中初始化时间




------------------ 原始邮件 ------------------
发件人: "wanghong2013"<notifications@github.com>;
发送时间: 2019年9月19日(星期四) 上午10:31
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] a-range-picker moment时间inValid date (#1028)




怎么解决的啊

**Comment by Crapulence** [comment]
遇到了同样的问题

**Comment by gitspringcould** [comment]
> 怎么解决的啊

按照官方文档将moment类型给到value中的参数
