### ISSUE TITLE
Modal in a Layout doesn't appear

### ISSUE THREAD

**Issue by SchroterQuentin** [vueComponent/ant-design-vue#103]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
Windows 10, firefox and chrome, vue 2.5.15, vue-antd-ui 1.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
Didn't succeed to reproduce but I think the error come from the rendering process which is called before some stuff are ready. I already had a similar issue in the past.

### What is expected?
I copy past the exemple with modal in my app and in an other clean app and when I click on the button to make the modal visible, the modal does not appear. And the button seems crashed.

### What is actually happening?
In the DOM Html where I should have the modal rendered, I juste have

```html
<div><!----></div>
```

---
There is nothing displayed on the console and in the vue-dev-tools the components are in a correct state but just not rendered. I'm quite certain that it's a problem of rendering stuff not ready to be rendered.

**Comment by tangjinzhou** [comment]
give me your code ?

**Comment by SchroterQuentin** [comment]
I did succeed to reproduce the bug and now I'm quite sure it's about my config on webpack.

Here is the reproductible exemple : https://github.com/SchroterQuentin/Vue-Antd

You will need the dotnet core sdk to build and run the app. When webpack build main.js in dev it's bugged and in prod it's not. If you could explain to me I would really apreciate that.

**Comment by tangjinzhou** [comment]
I think you should not use tree shaking  in DLL. This will cause some code to be lost.

[Using-Webpack-DLL](https://github.com/aurelia/webpack-plugin/wiki/Using-Webpack-DLL#why-would-i-use-it)

**Comment by SchroterQuentin** [comment]
I didn't know that, maybe for production purpose I'll remove it but for debug it help me build bundle really fast.
I did find a solution but I do not know why it's working. I just comment this line on my webpack.config.js file

```js
resolve: {
      extensions: ['.js', '.vue'],
      alias: isDevBuild ? {
        // 'vue$': 'vue/dist/vue',
      } : {
      }
},
```

Thanks for the help. Really appreciate yours quick answers.

**Comment by tangjinzhou** [comment]
@SchroterQuentin 
I think I know the cause of the problem.
You should ensure that your dll configuration file is consistent with the resolve.alias of the project configuration file.
E.g:
```
resolve: {
     alias: {
       'vue$': 'vue/dist/vue.esm.js',
     }
   },
```
