### ISSUE TITLE
Tag 选择与关闭事件重复触发

### ISSUE THREAD

**Issue by ZindexYG** [vueComponent/ant-design-vue#1031]
- [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Version

1.3.13

### Environment

vue：2.5.17

### Reproduction link

[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-bnre2?fontsize=14)

### Steps to reproduce

- 点击关闭 Icon 触发点击事件

### What is expected?

- 关闭与点击事件分离

### What is actually happening?

- 关闭与点击在同一个 div 内造成

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-d82xp
建议自行阻止冒泡
