### ISSUE TITLE
Select组件：当有placeholder的时候点击输入框不能触发focus事件，点击箭头可以 

### ISSUE THREAD

**Issue by tanxuewei** [vueComponent/ant-design-vue#1033]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome, vue 2

### Reproduction link
[https://vue.ant.design/components/select/](https://vue.ant.design/components/select/)

### Steps to reproduce
...

### What is expected?
Select组件：当有placeholder的时候 focus事件可以触发

### What is actually happening?
Select组件：当有placeholder的时候点击输入框不能触发focus事件，点击箭头可以

**Comment by YeahPotato** [comment]
I also encountered the same problem.
Version: 1.3.10
