### ISSUE TITLE
不能根据返回的数据设置单元格样式或者我用法不对有示例吗

### ISSUE THREAD

**Issue by chaegumi** [vueComponent/ant-design-vue#1035]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
单元格：通过给数据 data 设置字段 cellClassName 可以给任意一个单元格指定样式。

### What does the proposed API look like?
单元格：通过给数据 data 设置字段 cellClassName 可以给任意一个单元格指定样式。
customCell只会在表格加载的时候调用一次？我后数据返回之后，怎么再次触发这个函数

**Comment by sendya** [comment]
```vue
:customCell="(record, rowIndex) => {
  return {
     props: {
        // ...
     },
     class: { 'className': rowIndex === 'id' }
  }
}"
```

官方文档有说明  有这个 API ，并且也给出了 API 传递的参数

**Comment by klniu** [comment]
我这里也不生效，customHeaderCellss可以，customCell不生效，版本号：1.3.10

```js
        {
          title: '数量（个）',
          align: 'center',
          dataIndex: 'component',
          customCell: (r) => {
            return {
              style: {
                color: '#FF5733'
              }
            }
          },
          customHeaderCell: (r) => {
            return {
              style: {
                color: '#FF5733'
              }
            }
          }
        }
```

**Comment by chaegumi** [comment]
```javascript
    {
      title: '交易单号',
      dataIndex: 'trade_no',
      customCell: (record: any, rowIndex: any) => {
        return {
          class: [`${record.cellClassName}`, record.id]
        }
      }
    }
```

这样可以。
cellClassName和id是我处理结果集时加上去的
```javascript
_.set(this.tableData, [i, 'cellClassName'], 'demo-table-info-cell-red')
        _.set(this.tableData, [i, 'id'], `${this.tableData[i].id} `)
```
这边有个很奇怪的现象，单独class[`${record.cellClassName}`]是不行的，我一定要有个字段record.id

**Comment by klniu** [comment]
> ```js
>    {
>      title: '交易单号',
>      dataIndex: 'trade_no',
>      customCell: (record: any, rowIndex: any) => {
>        return {
>          class: [`${record.cellClassName}`, record.id]
>        }
>      }
>    }
> ```
> 
> 这样可以。
> cellClassName和id是我处理结果集时加上去的
> 
> ```js
> _.set(this.tableData, [i, 'cellClassName'], 'demo-table-info-cell-red')
>         _.set(this.tableData, [i, 'id'], `${this.tableData[i].id} `)
> ```
> 
> 这边有个很奇怪的现象，单独class[`${record.cellClassName}`]是不行的，我一定要有个字段record.id

class的是因为他的内容是 classname: boolean，像这样的
```
    class: {
      foo: true,
      bar: false
    }
```

**Comment by klniu** [comment]
最奇怪的是，class属性在customCell中好用，style不好用，在customHeaderCell中相反

**Comment by nongzhenli** [comment]
我也有这么一个需求：
使用 ` <a-table-column-group >` 来设置表头th合并。现在表头内容不确定，需要通过动态的for遍历出来，我尝试着加上 slot-scope ` <a-table-column-group slot-scope="specsValueId, scope" align="center">` 然后去遍历 里面的每个` a-table-column` 但是效果并没有实现，预想实现效果如下图：
![image](https://user-images.githubusercontent.com/19389294/77375458-79959180-6da8-11ea-8924-cf9f113347ec.png)

规格属性名是不写死的，所以我想通过for遍历，请求各位支招
