### ISSUE TITLE
table组件在template风格中 在<a-table-column sorter="true"> 排序失效，change事件中sorter.order 一直为ascend

### ISSUE THREAD

**Issue by fandepeng1993** [vueComponent/ant-design-vue#1039]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
mac

### Reproduction link
[https://codesandbox.io/s/vue-antd-template-liz94?fontsize=14](https://codesandbox.io/s/vue-antd-template-liz94?fontsize=14)

### Steps to reproduce
。。。。。

### What is expected?
解决table组件的tempalte风格服务器排序失效问题

### What is actually happening?
解决table组件的tempalte风格服务器排序失效问题

**Comment by fandepeng1993** [comment]
我已经解决

**Comment by zaozao1040** [comment]
> 我已经解决

请问是怎么解决的啊  我也遇到这个问题了  sorter="true"没有用

**Comment by fandepeng1993** [comment]
需要加key，每个tablecolum
---原始邮件---
发件人:"墙上的守夜人"<notifications@github.com>;
发送时间:2019年11月21日(星期四) 上午9:38
收件人:"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送人:"fandepeng1993"<270178123@qq.com>;"State change"<state_change@noreply.github.com>;
主题:Re: [vueComponent/ant-design-vue] table组件在template风格中 在<a-table-column sorter="true"> 排序失效，change事件中sorter.order 一直为ascend (#1039)

 
我已经解决
  
请问是怎么解决的啊  我也遇到这个问题了  sorter="true"没有用
 
&mdash;
