### ISSUE TITLE
table 选择框列可以选择固定在表格的最右侧吗？

### ISSUE THREAD

**Issue by catiscat** [vueComponent/ant-design-vue#1043]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用户不能自定义table选择列的位置

### What does the proposed API look like?
selectionPlacement: Boolean

**Comment by bey6** [comment]
Although it is slightly different, I also have the same requirement. I hope the checkbox column can be fixed:'fixed'.
`虽然稍有不同，不过我也有同样的需求，希望 checkbox 列可以 fixed: 'fixed'。`

It is recommended that the checkbox column can be configured in columns like the operation column.
`建议 checkbox 列可以像操作列一样在 columns 中配置。`
