### ISSUE TITLE
Menu - 让js控制节点展开或者监听defaultOpenKeys和defaultSelectedKeys变化而渲染Menu

### ISSUE THREAD

**Issue by crazyJiaLin** [vueComponent/ant-design-vue#1044]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
- 当使用menu作为导航的时候，我们的导航数据是由后台请求回来的，数据回来之后再去渲染menu，这时还需要根据当前路由来配置默认选中和默认展开项
- 所以希望能够给出使用js操作节点展开的功能
- 或者在menu渲染之后监听一下defaultOpenKeys和defaultSelectedKey这两个值的变化，
- 因为在请求数据后再设置defaultOpenKeys和defaultSelectedKeys是没有效果的，从而改变这两个值的时候Menu能够给出回应！

### What does the proposed API look like?
```javascript
$ref.openMenu(openKeys : Array)
$ref.selectMenu(selectKeys: Array)
```
如果有进展或者开发者们有其他解决办法可以email 我： [crazyjialin@foxmail.com](crazyjialin@foxmail.com)
非常感谢！

**Comment by sendya** [comment]
openKeys(.sync) | 当前展开的 SubMenu 菜单项 key 数组 | string[]
-- | -- | --
selectedKeys(v-model) | 当前选中的菜单项 key 数组 | string[]

监听 `onChange` 并处理数据绑定。
这些 API 在文档中均存在，请阅读官方文档

**Comment by crazyJiaLin** [comment]
尊敬的antd开发者：
    您好！ 非常感谢您帮我解决问题！！！antd功能真多！，就是有时候文档看的迷糊了。。。
    再次感谢，祝您一切顺利！




------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>;
发送时间: 2019年8月1日(星期四) 上午9:44
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "陈佳霖"<crazyjialin@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] Menu - 让js控制节点展开或者监听defaultOpenKeys和defaultSelectedKeys变化而渲染Menu (#1044)



   openKeys(.sync) 当前展开的 SubMenu 菜单项 key 数组 string[] 
    selectedKeys(v-model) 当前选中的菜单项 key 数组 string[] 
   
监听 onChange 并处理数据绑定。
 这些 API 在文档中均存在，请阅读官方文档

**Comment by sendya** [comment]
如果没问题就关了 issue

**Comment by crazyJiaLin** [comment]
好的，谢谢！
