### ISSUE TITLE
[BUG] DatePicker - Range Picker is not responsive when using "show-time"

### ISSUE THREAD

**Issue by flibustier** [vueComponent/ant-design-vue#1047]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Chrome

### Reproduction link
[https://vue.ant.design/components/date-picker/](https://vue.ant.design/components/date-picker/)

### Steps to reproduce
reduce window size to see range picker overflow due to `style="width: 350px"` when using the `show-time` option

You can see an example in the [documentation](https://vue.ant.design/components/date-picker/), at the "extra footer" option (reduce window width to see it)

### What is expected?
this inline css `style="width: 350px"` is creating bad behavior

### What is actually happening?
the range-picker is too large for small screen

<img width="735" alt="image" src="https://user-images.githubusercontent.com/9994935/62384173-f17d2600-b551-11e9-9c50-d8492e4e97a4.png">

**Comment by flibustier** [comment]
I fixed it for now using the following CSS rule :
```
.ant-calendar-picker {
  width: auto !important;
}
```
But it should be better to have the `width: 350px` inline rule to be removed from the library…

**Comment by flibustier** [comment]
It seems to come from line 324 to 326 in this file:
https://github.com/vueComponent/ant-design-vue/blame/b4d9bfd8d9586c1bd6a6f9b06302be23b719fe6f/components/date-picker/RangePicker.jsx

**Comment by youngsailor** [comment]
> I fixed it for now using the following CSS rule :
> 
> ```
> .ant-calendar-picker {
>   width: auto !important;
> }
> ```
> 
> But it should be better to have the `width: 350px` inline rule to be removed from the library…

good
