### ISSUE TITLE
日期选择器预设范围a-tag 颜色不能随自定义颜色更改

### ISSUE THREAD

**Issue by zhaiyy** [vueComponent/ant-design-vue#1050]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
与其他环境版本无关

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/68c212df65d47a9d43d38b72d90a249adbf4a25e/components/date-picker/RangePicker.jsx](https://github.com/vueComponent/ant-design-vue/blob/68c212df65d47a9d43d38b72d90a249adbf4a25e/components/date-picker/RangePicker.jsx)

### Steps to reproduce
全局设置颜色，日期预设范围不生效
```
....
const operations = Object.keys(ranges || {}).map(range => {
const value = ranges[range];
return (
<Tag
key={range}
prefixCls={tagPrefixCls}
color="blue" // 此处设置了默认值，且不可更改
onClick={() => this.handleRangeClick(value)}
onMouseenter={() => this.setState({ sHoverValue: value })}
onMouseleave={this.handleRangeMouseLeave}
>
{range}
</Tag>
);
....
```
相关源码颜色写死，不支持自定义

### What is expected?
tag 颜色随系统颜色更改

### What is actually happening?
tag 颜色不随系统颜色更改

**Comment by tangjinzhou** [comment]
可以先写 css 去覆盖颜色
