### ISSUE TITLE
希望增加React 版本的 Mentions提及 组件

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#1051]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
该组件 第三方实在没有特别合适的，奈何自身能力有限，希望vue 版本的 老哥们能同步支持过来。

 
![image](https://user-images.githubusercontent.com/2329528/62369483-53458c00-b562-11e9-8707-7b659a9bf06f.png)

**Comment by Amour1688** [comment]
v1.5
