### ISSUE TITLE
ant-design-vue TreeSelect冲突Conflict! value of node '2' (undefined) has already used by node '1'.

### ISSUE THREAD

**Issue by gitspringcould** [vueComponent/ant-design-vue#1059]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
windows10,google75.0.3770.142,vue2.x

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
ant-design-vue TreeSelect冲突Conflict! value of node '2' (undefined) has already used by node '1'.
数据格式如下：
createTime: "2019-08-05 09:14"
hasChildren: true
hasParent: true
id: "1"
key: "1"
parentId: "0"
text: "development"
title: "研发部"

### What is expected?
选中之后显示在输入框

### What is actually happening?
选中之后显示在输入框

**Comment by sendya** [comment]
可以用 codesandbox 提供一个复现用例吗？

**Comment by gitspringcould** [comment]
<template>
  <a-card :bordered="false" class="card-area">
    
    <div class="operator">
      <a-button type="primary" @click="userAdd">新增</a-button>
      <a-button type="danger" @click="userRemoveBatch">删除</a-button>
    </div>
    <a-table :loading="loading" :columns="columns" :rowKey="(record)=>record.id" :dataSource="dataSource"
             :pagination="pagination"
             :rowSelection="{selectedRowKeys: selectedRowKeys, onChange: onSelectChange}">
      <template slot="operation" slot-scope="text,record">
        <a-tag color="green" @click="userEdit">编辑</a-tag>
        <a-tag color="red" @click="userRemove(record.id)">删除</a-tag>
      </template>
    </a-table>
    <user-add :userAddVisible="userAddVisible" @close="addClose"></user-add>
    <user-edit :userEditVisible="userEditVisible" @close="editClose"></user-edit>
  </a-card>
</template>

<script>
    import UserAdd from "./components/UserAdd";
    import UserEdit from "./components/UserEdit";

    export default {
        name: "User",
        components: {
            UserAdd,
            UserEdit
        },
        data() {
            return {
                loading: false,
                advanced: false,
                dataSource: [],
                selectedRowKeys: [],
                userAddVisible: false,
                userEditVisible: false,
                pageNumber: 1,
                pageSize: 5,
                pagination: {
                    defaultPageSize: 5,
                    showTotal: total => `共 ${total} 条数据`,
                    showSizeChanger: true,
                    pageSizeOptions: ['5', '10', '15', '20'],
                    onShowSizeChange: (current, pageSize) => {
                        this.fetch(current, pageSize);
                    }
                }
            }
        },
        mounted() {
            this.fetch(this.pageNumber, this.pageSize);
        },
        methods: {
            onSearch(val) {
            },
            onSelectChange(selectedRowKeys) {
                this.selectedRowKeys = selectedRowKeys;
            },
            userAdd() {
                this.userAddVisible = true;
            },
            addClose() {
                this.userAddVisible = false;
            },
            editClose() {
                this.userEditVisible = false
            },
            userRemove(id) {
                let _this = this;
                this.$confirm({
                    title: '删除提醒',
                    content: '确定要删除此用户吗？',
                    onOk() {
                        _this.$post(`user/remove/${id}`, {}).then((res) => {
                            if (res.data.code === 200 || res.data.code === '200') {
                                _this.$message.success('删除用户成功');
                                _this.fetch(_this.pageNumber, _this.pageSize);
                            }
                        });
                    },
                    onCancel() {
                    }
                });
            },
            userRemoveBatch() {
                let _this = this;
                this.$confirm({
                    title: '删除提醒',
                    content: '确定要删除所选用户吗？',
                    onOk() {
                        _this.$post(`user/removeBatch`, {
                            ids: _this.selectedRowKeys.join(',')
                        }).then((res) => {
                            if (res.data.code === 200 || res.data.code === '200') {
                                _this.$message.success('删除用户成功');
                                _this.fetch(_this.pageNumber, _this.pageSize);
                            }
                        });
                    },
                    onCancel() {
                    }
                });
            },
            userEdit() {
                this.userEditVisible = true;
            },
            fetch(pageNumber, pageSize) {
                this.$get('user/page', {
                    pageNumber: pageNumber,
                    pageSize: pageSize
                }).then((res) => {
                    if (res.data.code === 200 || res.data.code === '200') {
                        this.dataSource = res.data.data.records;
                    }
                })
            },
        },
        computed: {
            columns() {
                return [{
                    title: '用户名',
                    dataIndex: 'username'
                }, {
                    title: '用户姓名',
                    dataIndex: 'nickname'
                }, {
                    title: '部门',
                    dataIndex: 'department.name'
                }, {
                    title: '角色',
                    dataIndex: 'sysRole.description'
                }, {
                    title: '创建时间',
                    dataIndex: 'createTime'
                }, {
                    title: '操作',
                    dataIndex: 'operation',
                    scopedSlots: {customRender: 'operation'}
                }]
            }
        }
    }
</script>

<style lang="less" scoped>
  @import "../../../../static/less/Common";
</style>



<template>
  <a-drawer
    title="新增菜单"
    :maskClosable="true"
    width=650
    placement="right"
    :closable="false"
    @close="onClose"
    :visible="userAddVisible"
    style="height: calc(100% - 55px);overflow: auto;padding-bottom: 53px;">
    <a-form :form="form">
      <a-form-item label="用户名："
                   :labelCol="{span: 5}"
                   :wrapperCol="{span: 18, offset: 1}">
        <a-input v-decorator="['username',{rules:[{required:true,message:'请输入用户名'}]}]"></a-input>
      </a-form-item>
      <a-form-item label="用户姓名："
                   :labelCol="{span: 5}"
                   :wrapperCol="{span: 18, offset: 1}">
        <a-input v-decorator="['nickname',{rules:[{required:true,message:'请输入用户姓名'}]}]"></a-input>
      </a-form-item>
      <a-form-item label="用户角色："
                   :labelCol="{span: 5}"
                   :wrapperCol="{span: 18, offset: 1}">
        <a-select :value="roleId" @change="roleChange">
          <a-select-option v-for="(item,index) in roleList" :key="index" :value="item.id">{{item.description}}
          </a-select-option>
        </a-select>
      </a-form-item>
      <a-form-item label="所属部门："
                   :labelCol="{span: 5}"
                   :wrapperCol="{span: 18, offset: 1}">
        <a-tree-select
          style="width: 300px"
          :dropdownStyle="{ maxHeight: '400px', overflow: 'auto' }"
          :treeData="deptList"
          @change="deptChange"
          treeDefaultExpandAll></a-tree-select>
      </a-form-item>
    </a-form>
    <div class="drawer-bootom-button">
      <a-button style="margin-right: .8rem" @click="onClose">取消</a-button>
      <a-button @click="handleSubmit" type="primary" :loading="loading">提交</a-button>
    </div>
  </a-drawer>
</template>

<script>
    export default {
        name: "UserAdd",
        props: {
            userAddVisible: {
                type: Boolean,
                default: false
            }
        },
        data() {
            return {
                loading: false,
                confirmLoading: false,
                form: this.$form.createForm(this),
                roleList: [],
                roleId: '',
                deptList: [],
                deptId: ''
            }
        },
        methods: {
            onClose() {
                this.$emit('close')
            },
            roleChange(value) {
                this.roleId = value;
            },
            deptChange(value) {
                this.deptId = value;
                console.log(value);
            },
            handleSubmit() {
                this.form.validateFields((err, value) => {
                    if (!err) {
                        this.$post('', {}).then((res) => {
                            if (res.data.code === 200 || res.data.code === '200') {

                            }
                        });
                    }
                });
            },
            getRoleList() {
                this.$get('role/list').then((res) => {
                    if (res.data.code === 200 || res.data.code === '200') {
                        this.roleList = res.data.data;
                        this.roleId = this.roleList[0].id;
                    }
                });
            },
            getDeptList() {
                this.$get('dept/treeList').then((res) => {
                    if (res.data.code === 200 || res.data.code === '200') {
                        this.deptList = res.data.data.children;
                        // this.deptId = this.deptList[0].id;
                    }
                });
            }
        },
        watch: {
            userAddVisible() {
                if (this.userAddVisible) {
                    this.getRoleList();
                    this.getDeptList();
                }
            }
        }
    }
</script>

<style scoped>

</style>

代码是这样写的
{
    "code": 200,
    "msg": "成功",
    "data": {
        "id": "0",
        "text": "root",
        "children": [
            {
                "id": "1",
                "key": "1",
                "title": "研发部",
                "text": "development",
                "children": [
                    {
                        "id": "2",
                        "key": "2",
                        "title": "测试部",
                        "text": "cs",
                        "parentId": "1",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-02 18:05"
                    },
                    {
                        "id": "3",
                        "key": "3",
                        "title": "111",
                        "text": "111",
                        "parentId": "1",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-05 10:09"
                    },
                    {
                        "id": "4",
                        "key": "4",
                        "title": "222",
                        "text": "222",
                        "parentId": "1",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-05 10:09"
                    },
                    {
                        "id": "6",
                        "key": "6",
                        "title": "333",
                        "text": "333",
                        "parentId": "1",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-05 10:10"
                    }
                ],
                "parentId": "0",
                "hasParent": true,
                "hasChildren": true,
                "createTime": "2019-08-05 09:14"
            },
            {
                "id": "5",
                "key": "5",
                "title": "3",
                "text": "333",
                "children": [
                    {
                        "id": "7",
                        "key": "7",
                        "title": "555",
                        "text": "555",
                        "parentId": "5",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-05 10:12"
                    },
                    {
                        "id": "8",
                        "key": "8",
                        "title": "666",
                        "text": "666",
                        "parentId": "5",
                        "hasParent": true,
                        "hasChildren": false,
                        "createTime": "2019-08-05 10:14"
                    }
                ],
                "parentId": "0",
                "hasParent": true,
                "hasChildren": true,
                "createTime": "2019-08-05 11:03"
            }
        ],
        "parentId": "",
        "hasParent": false,
        "hasChildren": true
    }
}
返回的数据格式是这样


------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午2:45
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] ant-design-vue TreeSelect冲突Conflict! value of node '2' (undefined) has already used by node '1'. (#1059)




可以用 codesandbox 提供一个复现用例吗？

**Comment by zkwolf** [comment]
其实提示的很明显了。。。。数据要求{key: '', value: '', label: ''}格式，你缺了value

**Comment by gitspringcould** [comment]
嗯嗯，这边已经改过了。谢谢



------------------ 原始邮件 ------------------
发件人: "zkwolf"<notifications@github.com>; 
发送时间: 2019年8月5日(星期一) 下午5:53
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>; 
抄送: "何某人"<1162487568@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vueComponent/ant-design-vue] ant-design-vue TreeSelect冲突Conflict! value of node '2' (undefined) has already used by node '1'. (#1059)




其实提示的很明显了。。。。数据要求{key: '', value: '', label: ''}格式，你缺了value
