### ISSUE TITLE
Select dynamic

### ISSUE THREAD

**Issue by SchroterQuentin** [vueComponent/ant-design-vue#106]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
Windows 10, firefox and chrome, vue 2.5.15, vue-antd-ui 1.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oxn3lr2n8z)

### Steps to reproduce
Set the options of the select after it was rendered made him in a state where he can't see new options

### What is expected?
It's expected than when you update your options in the data, they are updating on the select

### What is actually happening?
The select does nothing like on the demo

---
I needed to show a modal with inside a select with options. I load the data for the options of the select in the same time that I show the modal, without waiting to get the response for the server to display the modal.

**Comment by tangjinzhou** [comment]
Now you can use v-model like [this](https://codesandbox.io/s/9ylynvl38y).

The next version will solve this usage scenario without updating the problem.
