### ISSUE TITLE
A input number addonAfter not works

### ISSUE THREAD

**Issue by gustawdaniel** [vueComponent/ant-design-vue#1061]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
2.6.10

### Reproduction link
[https://vue.ant.design/components/input/](https://vue.ant.design/components/input/)

### Steps to reproduce
I trying to use

```
<a-input-number addonAfter="%"/>
```

But It don't works. But

```
<a-input addonAfter="%"/>
```

works great as docs

https://vue.ant.design/components/input/

describe.

### What is expected?

```
<a-input-number addonAfter="%"/>
```

should show % and require number

### What is actually happening?

```
<a-input-number addonAfter="%"/>
```

does not shows % so I need to choose between pure number input

```
<a-input-number/>
```

or input with addon

```
<a-input addonAfter="%"/>
```

**Comment by wangxueliang** [comment]
addonAfter not currently supported, you can refer to formatter
