### ISSUE TITLE
table的customRender和scopedSlots如何同时使用

### ISSUE THREAD

**Issue by liupei1995** [vueComponent/ant-design-vue#1063]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
window7,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-yvgln?fontsize=14)

### Steps to reproduce
同时设置customRender和scopedSlots

### What is expected?
自定义的单元格可以合并行

### What is actually happening?
合并了但自定义的效果没有了

**Comment by tanxuewei** [comment]
同问

**Comment by tangjinzhou** [comment]
这两个配置有点冲突，建议使用表格合并时，不要使用scopeSlots来定义 customRender，
可以参考 官网示例结合 JSX来实现 
https://vue.ant.design/components/table-cn/#components-table-demo-colspan-and-rowspan

**Comment by YamadaAoi** [comment]
> 这两个配置有点冲突，建议使用表格合并时，不要使用scopeSlots来定义 customRender，
> 可以参考 官网示例结合 JSX来实现
> https://vue.ant.design/components/table-cn/#components-table-demo-colspan-and-rowspan

我是用的是vue-cli3的ts版本，在data里直接写jsx会编译报错，请问ts里该如何写呢？
Type assertion using the '<>' syntax is forbidden. Use the 'as' syntax instead. (no-angle-bracket-type-assertion)tslint(1)

**Comment by jonnyshao** [comment]
@tangjinzhou 现在遇到一个问题，table需要合并单元格的同时td得插入我们自己的组件，从文档来看目前只能二选一，这种场景还有别的方式可以实现吗？谢谢！

**Comment by Siffre** [comment]
@jonnyshao hello,这个插入自己的组件你是怎么实现的呢？谢谢

**Comment by gitspringcould** [comment]
@jonnyshao 这边有实现好的示例吗？能不能提供给我们参考一下

**Comment by asunaCC** [comment]
hello，请问这个问题你有解决方法吗？遇到了相同的需求，前来取经

**Comment by gitspringcould** [comment]
目前官方也没有给出回复，所以也没有解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "AsunaCC"<notifications@github.com&gt;; 
发送时间: 2020年8月3日(星期一) 上午8:50
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "何某人"<1162487568@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] table的customRender和scopedSlots如何同时使用 (#1063)





 
hello，请问这个问题你有解决方法吗？遇到了相同的需求，前来取经

**Comment by Hucy** [comment]
@liupei1995 可以这么写 https://codesandbox.io/s/vue-antd-template-forked-o9mxb?file=/src/components/HelloWorld.vue

**Comment by gitspringcould** [comment]
> @liupei1995 可以这么写 https://codesandbox.io/s/vue-antd-template-forked-o9mxb?file=/src/components/HelloWorld.vue

![image](https://user-images.githubusercontent.com/39726088/95931632-45dd9000-0dfc-11eb-8f0a-ca17ed401b18.png)
wo'y我一开始也是这么写的，当时没有起作用

**Comment by xoptimal** [comment]
@Hucy  我这样写初始化是正常的, 但是我2个columns 在切换的时候, Children无效了, 也不再渲染,  只能对字符串起作用, 请问你有遇见过吗
