### ISSUE TITLE
How to use LocaleProvider in vuejs with typecript project?

### ISSUE THREAD

**Issue by frankcb298** [vueComponent/ant-design-vue#1065]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
My project is using Vuejs   typescript   ant-design-vue.
I want to use LocaleProvider to localize the UI controls follow this https://vue.ant.design/components/locale-provider/

### What is expected?
How to use LocaleProvider in ant-design-vue with typecript?

### What is actually happening?
When i use this component: a-locale-provider. This show below error:
[Vue warn]: Unknown custom element: <a-locale-provider> - did you register the component correctly? For recursive components, make sure to provide the "name" option

![image](https://user-images.githubusercontent.com/39110887/62595436-96a84d80-b908-11e9-89bf-2eba9fcc1b81.png)

**Comment by betgar** [comment]
```javascript
import zhCN from 'ant-design-vue/lib/locale-provider/zh_CN.js';
import 'moment/locale/zh-cn.js';

```

**Comment by frankcb298** [comment]
i will close in this issue. in my case. i just use <locale-provider> not <a-locale-provider>. it works
