### ISSUE TITLE
模态框width属性设置宽度无效

### ISSUE THREAD

**Issue by gitspringcould** [vueComponent/ant-design-vue#1068]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
windows10,google75.0.3770.142,vue2.x

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
模态框设置宽度大于默认的520，宽度会自动充满页面，审查元素是style绑定无效

### What is expected?
设置宽度，显示设定大小

### What is actually happening?
模态框设置宽度大于默认的520，宽度会自动充满页面，审查元素是style绑定无效

**Comment by sendya** [comment]
`应该不是宽度大于 520 自动充满页面` 而是当你的屏幕（显示区域）较小时，会自动充满页面。

如果我猜的不对，希望你能提供一个 codesandbox 的复现

**Comment by gitspringcould** [comment]
页面代码



审查元素





------------------ 原始邮件 ------------------
发件人: "言肆"<notifications@github.com>;
发送时间: 2019年8月8日(星期四) 下午2:53
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "何某人"<1162487568@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] 模态框width属性设置宽度无效 (#1068)




应该不是宽度大于 520 自动充满页面 而是当你的屏幕（显示区域）较小时，会自动充满页面。
 
如果我猜的不对，希望你能提供一个 codesandbox 的复现

**Comment by gitspringcould** [comment]
页面代码
审查元素

**Comment by gitspringcould** [comment]
页面代码<template>
  <a-modal title="人脸信息录入" width="588" :visible="takePhotoVisible"
           @ok="handleOk"
           :confirmLoading="confirmLoading"
           @cancel="handleCancel">
    <video id="videoCamera" :width="videoWidth" :height="videoHeight" autoplay></video>
    <canvas style="display:none;" id="canvasCamera" :width="videoWidth" :height="videoHeight"></canvas>
  </a-modal>
</template>
审查元素<div role="document" class="ant-modal"><div tabindex="0" style="width: 0px; height: 0px; overflow: hidden;">sentinelStart</div><div class="ant-modal-content"><button aria-label="Close" class="ant-modal-close"><span class="ant-modal-close-x"><i class="ant-modal-close-icon anticon anticon-close"><svg viewBox="64 64 896 896" data-icon="close" width="1em" height="1em" fill="currentColor" aria-hidden="true" focusable="false" class=""><path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 0 0 203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z"></path></svg></i></span></button><div class="ant-modal-header"><div id="rcDialogTitle0" class="ant-modal-title">人脸信息录入</div></div><div class="ant-modal-body"><video data-v-592bdb62="" id="videoCamera" width="540" height="410" autoplay="autoplay"></video> <canvas data-v-592bdb62="" id="canvasCamera" width="540" height="410" style="display: none;"></canvas></div><div class="ant-modal-footer"><div><button type="button" class="ant-btn ant-btn-default"><span>取 消</span></button><button type="button" class="ant-btn ant-btn-primary"><span>确 定</span></button></div></div></div><div tabindex="0" style="width: 0px; height: 0px; overflow: hidden;">sentinelEnd</div></div>

**Comment by sendya** [comment]
绑定数字需要使用 `:` 前缀进行绑定，如 `:width="500"` 具体可以查询 Vue 官方文档

**Comment by gitspringcould** [comment]
好的，可以了。谢谢

**Comment by sendya** [comment]
可以就把 issue 关闭了把 谢谢
