### ISSUE TITLE
TimePicker with default value are not see as filled by form

### ISSUE THREAD

**Issue by SchroterQuentin** [vueComponent/ant-design-vue#107]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
Windows 10, firefox and chrome, vue 2.5.15, vue-antd-ui 1.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9j142p200w)

### Steps to reproduce
Set default value to timepicker and submit form

### What is expected?
The form must said that everything is ok, the field is filled

### What is actually happening?
The form tell that there is something missing

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/ant-design-vue/components/form/#this.form.getFieldDecorator(id,-options)

After wrapped by getFieldDecorator, value(or other property defined by valuePropName) onChange(or other property defined by trigger) props will be added to form controls，the flow of form data will be handled by Form which will cause:
- You shouldn't use onChange to collect data, but you still can listen to onChange(and so on) events.
- You can not set value of form control via value defaultValue prop, and you should set default value with initialValue in getFieldDecorator instead.
- You shouldn't call v-model manually, please use this.form.setFieldsValue to change value programmatically.

**Comment by SchroterQuentin** [comment]
Thanks for the answer it's now working as expected. But I do not understand how I can have an object representing the form in real time ? If I can't use v-model ?

I try to use onChange event and get the data with form.getFieldValue but it give me the old value not the current one.
