### ISSUE TITLE
antd-vue组件tree的可搜索功能，使用a-directory-tree，搜索到的关键字在树列表上不红色展示

### ISSUE THREAD

**Issue by sandm1227** [vueComponent/ant-design-vue#1071]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
vue2.6.6

### Reproduction link
无
### Steps to reproduce
code：
![image](https://user-images.githubusercontent.com/25194203/62690046-8d011180-b9fe-11e9-893e-655d086d4752.png)

treeDataList是后端获取的。数据格式为：
![image](https://user-images.githubusercontent.com/25194203/62690210-e8cb9a80-b9fe-11e9-8a57-91f62fe71a7a.png)

![image](https://user-images.githubusercontent.com/25194203/62690070-9ab69700-b9fe-11e9-9c94-01d57a7f33bf.png)

### What is expected?
搜索到的关键字在树列表上红色展示，r如下图
![image](https://user-images.githubusercontent.com/25194203/62690398-3ba55200-b9ff-11e9-8cc6-b23d98d82d50.png)

### What is actually happening?
搜索到的关键字在树列表上没有红色展示

**Comment by wangxueliang** [comment]
希望你能提供一个 codesandbox 的复现

**Comment by wmo123** [comment]
![image](https://user-images.githubusercontent.com/47963460/82111753-db0b2880-9779-11ea-9869-5275707c0a0c.png)
图片上的slot-scope="text" 应该改为 slot-scope="{title}",因为你的treeDataList上是: "scopedSlots":{"title": "title"}@sandm1227

**Comment by NieShiyi** [comment]
我也有同样的问题，但是是按照官方写的例子，而且我的treeData数据中也有title，但是还是没有显示
