### ISSUE TITLE
cascader 组件，自定义 fieldNames 时，搜索展示 bug

### ISSUE THREAD

**Issue by gauseen** [vueComponent/ant-design-vue#1072]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
window 10, chrome  75.0.3770.142, vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-9q80s)

### Steps to reproduce
重现请看 https://codesandbox.io/embed/vue-antd-template-9q80s

### What is expected?
搜索时，展示 Zhejiang/Hangzhou/West Lake，由 / 分割开展示

### What is actually happening?
搜索时，展示 ZhejiangHangzhouWest Lake，没有用 / 分割开展示

**Comment by tangjinzhou** [comment]
fieldNames 定义  lable 和 value 时 暂不可使用同一值
