### ISSUE TITLE
select 为tag模式且存在值的时候，focus事件失效

### ISSUE THREAD

**Issue by YeahPotato** [vueComponent/ant-design-vue#1073]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
browser

### Reproduction link
[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-o84b0?fontsize=14)

### Steps to reproduce
输入a 失焦 添加a，再focus 无法触发focus事件，当select有值的时候都无法触发focus事件。

### What is expected?
不管什么时候，希望focus的时候，都可以触发focus事件。

### What is actually happening?
select 为tag模式且存在值的时候，focus事件失效。

**Comment by tangjinzhou** [comment]
已在 #999 这个issue 中解决，最近会发版本

**Comment by YeahPotato** [comment]
thx

**Comment by YeahPotato** [comment]
> 已在 #999 这个issue 中解决，最近会发版本

thx~
