### ISSUE TITLE
表单验证类型设置数字型，输入数字却无法通过验证

### ISSUE THREAD

**Issue by liuqz** [vueComponent/ant-design-vue#108]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ym7kkml7wx)

### Steps to reproduce
输入数量，验证不通过

### What is expected?
验证正常

### What is actually happening?
确实是数值类型，却不能通过验证

**Comment by tangjinzhou** [comment]
请使用a-input-number

**Comment by tangjinzhou** [comment]
使用自定义校验(validator)[https://vuecomponent.github.io/ant-design-vue/components/form-cn/#%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99]

或直接设置[max](https://vuecomponent.github.io/ant-design-vue/components/input-number-cn/#API)
