### ISSUE TITLE
Pagination 分页组件 total 类型为 String 报类型不匹配 

### ISSUE THREAD

**Issue by woodguoyu** [vueComponent/ant-design-vue#1084]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.14

### Environment
Google Chrome 已是最新版本 版本 76.0.3809.100（正式版本） （64 位）

### Reproduction link
[https://vue.ant.design/components/pagination-cn/#API](https://vue.ant.design/components/pagination-cn/#API)

### Steps to reproduce
无

### What is expected?
如果数据量较大，接口传过来的时类型为 int ，会丢失精度。希望Pagination 分页组件 total 支持 String。

### What is actually happening?
Pagination 分页组件 total 类型为 String 报类型不匹配

vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "total". Expected Number with value 4, got String with value "4".

**Comment by sendya** [comment]
int 有精度?

**Comment by woodguoyu** [comment]
抱歉表述错了，我是想表达：
JavaScript 无法处理 Java 的长整型 Long 导致精度丢失，具体表现为主键最后两位永远为 0，解决思路： Long 转为 String 返回

**Comment by sendya** [comment]
19 位的总数据量，我不认为这是合理的需求。 而且如果是 文本， JS 要如何计算分页？
