### ISSUE TITLE
组件库引入全局样式lib/style/index.css,会污染全局基础样式

### ISSUE THREAD

**Issue by lulinglm** [vueComponent/ant-design-vue#1086]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.14

### Environment
macos 10.14.6，chrome76.0.3809.100（正式版本），vue 2.6

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce

在chrome extension 插件开发中使用ant-design-vue组件库。
采用了按需加载的引入方式。
但是按需加载还是会引入ant-design-vue代码中style文件夹中的index.css。
该文件中包含全局的一些基本样式，会影响到正常界面的显示。
按需加载的时候能不能限制ant-design-vue样式的作用域。

ant-design-vue中style文件夹中的index.css文件截图
![image](https://user-images.githubusercontent.com/50210532/62989321-19398b80-be7a-11e9-956e-8d558a14b383.png)

百度页面样式覆盖截图：
![image](https://user-images.githubusercontent.com/50210532/62989472-b3013880-be7a-11e9-8be5-0929d0534740.png)

### What is expected?
引入lib/style/index.css 文件不污染全局样式

### What is actually happening?
开发的chrome extension 插件在浏览网页过程中，会影响网页的样式

---
https://github.com/vueComponent/ant-design-vue/issues/1085  被关闭的带图片的issue地址

**Comment by sendya** [comment]
ant-design-vue 在设计的时候就是用来开发一个完整的应用的，为了方便，我们覆盖了一些全局样式，现在还不能移除，想要了解更多请追踪这个 issue：https://github.com/ant-design/ant-design/issues/4331 ，或者参考这个教程 [How to avoid modifying global styles?](https://vue.ant.design/docs/vue/faq-cn/docs/react/customize-theme#How-to-avoid-modifying-global-styles-?)


https://vue.ant.design/docs/vue/faq/#ant-design-vue-override-my-global-styles!

**Comment by lulinglm** [comment]
How to avoid modifying global styles?

https://vue.ant.design/docs/vue/faq-cn/docs/react/customize-theme#How-to-avoid-modifying-global-styles-?

提示 404

**Comment by sendya** [comment]
https://ant.design/docs/react/customize-theme#How-to-avoid-modifying-global-styles?
