### ISSUE TITLE
Component Tree: How to prevent to expand

### ISSUE THREAD

**Issue by muei** [vueComponent/ant-design-vue#109]
`a-tree`
Prevent the expand event. If expand a node that the children is empty, the icon will be leaf, so if I want to expand again, I have no idea. So can you help me that how to prevent the expand, or reset the node state.

**Comment by tangjinzhou** [comment]
you can use `expandedKeys` and `expand` to control the expandedKeys of the tree
Example： https://codesandbox.io/s/1y5w98rz47

Maybe I didn't understand what you mean correctly.

**Comment by muei** [comment]
I means that the leaf node, I can't click again.
In your example, the node `parent 1-0` , I hope this is parent with empty children, but it's to be a leaf node. If is not a leaf node, so it can be click to expand again

**Comment by tangjinzhou** [comment]
I understand what you mean.
Maybe you can use `loadData` to achieve the effect you want.
Example： https://codesandbox.io/s/1y5w98rz47

**Comment by muei** [comment]
The is `reject()`, thank you!
