### ISSUE TITLE
菜单跨组件引用错误

### ISSUE THREAD

**Issue by jegooCN** [vueComponent/ant-design-vue#1092]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.14

### Environment
vue: 2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
1. 使用antd菜单组件SubMenu自定义一个MySubMenu组件

    <template>
      <a-sub-menu>
      	<span slot="title">测试</span>
      </a-sub-menu>
    </template>

2. 在另一个组件中使用antd菜单组件Menu创建一个菜单，引用MySubMenu组件

<template>
  <a-menu>
  	<my-sub-menu></my-sub-menu>
  </a-menu>
</template>

以上会导致a-sub-menu显示不成功
错误大致应该是Menu主菜单组件的数据传递不到MySubMenu中a-sub-menu中，导致a-sub-menu找不到parentMenu

### What is expected?
MySubMenu中a-sub-menu能正常显示

### What is actually happening?
MySubMenu中a-sub-menu能不能正常显示，报错

**Comment by sendya** [comment]
请参考文档案例
https://vue.ant.design/components/menu/#Single-file-recursive-menu
