### ISSUE TITLE
setFieldsValue 不能改变radioa.group的值

### ISSUE THREAD

**Issue by beFleeting** [vueComponent/ant-design-vue#1093]
Version
1.3.14

Environment
win10、google(75.0.3770.100)、Vue (2.6.10)

Reproduction link
[codesandbox](https://codesandbox.io/embed/vue-antd-template-eg5gg)

Steps to reproduce
点击改变按钮radiao.group 组选中第二个

What is expected?
点击改变选中第二个radio

What is actually happening?
无响应

**Comment by sendya** [comment]
```diff
<template>
  <a-form :form="form" layout="inline">
    <a-form-item label="名称">
      <a-input
        placeholder="请输入名称"
        size="large"
        v-decorator="['name',{rules: [{ required: true,message:'请输入名称'}]}]"
      />
    </a-form-item>
    <a-form-item label="计价方式">
      <a-radio-group
        name="type"
-        v-decorator="['text',{valuePropName: 'checked',rules:[{required:true,message:'请选择方式'}]}]"
+        v-decorator="['text',{rules:[{required:true,message:'请选择方式'}]}]"
      >
        <a-radio value="1">数</a-radio>
        <a-radio value="2">量</a-radio>
        <a-radio value="3">体</a-radio>
      </a-radio-group>
    </a-form-item>
    <a-button @click="change">改变</a-button>
  </a-form>
</template>
```

**Comment by beFleeting** [comment]
> ```diff
> <template>
>   <a-form :form="form" layout="inline">
>     <a-form-item label="名称">
>       <a-input
>         placeholder="请输入名称"
>         size="large"
>         v-decorator="['name',{rules: [{ required: true,message:'请输入名称'}]}]"
>       />
>     </a-form-item>
>     <a-form-item label="计价方式">
>       <a-radio-group
>         name="type"
> -        v-decorator="['text',{valuePropName: 'checked',rules:[{required:true,message:'请选择方式'}]}]"
> +        v-decorator="['text',{rules:[{required:true,message:'请选择方式'}]}]"
>       >
>         <a-radio value="1">数</a-radio>
>         <a-radio value="2">量</a-radio>
>         <a-radio value="3">体</a-radio>
>       </a-radio-group>
>     </a-form-item>
>     <a-button @click="change">改变</a-button>
>   </a-form>
> </template>
> ```

谢谢

**Comment by beFleeting** [comment]
@sendya 谢谢

**Comment by lizy0329** [comment]
> 谢谢

说谢谢的同时，还要说 Why
