### ISSUE TITLE
Upload上传问题，阻止自动上传后本地缩略图不能正确显示

### ISSUE THREAD

**Issue by jiafulu** [vueComponent/ant-design-vue#1099]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
"ant-design-vue": "1.3.13"，  "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-it2ox)

### Steps to reproduce
阻止自动提交后的问题
上传缩略图不显示，下一次次上传后显示上一次的图片，当前上传的不显示

### What is expected?
能正确显示缩略图

### What is actually happening?
缩略图不能及时显示

---
提供的例子实际上就是官方demo里面的那个照片墙，只是把action删除了用beforeUpload阻止了自动提交,然后就出问题了
最新版的vue和ant-design-vue也有这个问题

**Comment by wangxueliang** [comment]
https://codesandbox.io/s/vue-antd-template-nm0hj  看一下这个demo
你的用法有点问题？只有当上传成功，才能显示吧
![image](https://user-images.githubusercontent.com/4122593/63344061-1a8b1c80-c382-11e9-9c7f-aa33a613099f.png)
