### ISSUE TITLE
全局mixins中如果包含props会报错

### ISSUE THREAD

**Issue by qqcbqqkcel** [vueComponent/ant-design-vue#1100]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
win10，chrome70 ，vue2.6.10

### Reproduction link
[https://vuecomponent.github.io/issue-helper/?lang=zh](https://vuecomponent.github.io/issue-helper/?lang=zh)

### Steps to reproduce
import Vue from 'vue'
import router from './routes'
import Antd from 'ant-design-vue'
import 'ant-design-vue/dist/antd.css'
Vue.config.productionTip = false

Vue.use(Antd)

Vue.mixin({
props: {
xxxData: Object
},
computed: {
loginInfo() {
return '你好'
}
}
})

new Vue({
router,
render: h => h({ render: rv => rv('router-view') })
}).$mount('#app')

### What is expected?
全局mixin可以使用props

### What is actually happening?
删除下面代码就不会有问题。
props: {
xxxData: Object
}

**Comment by qqcbqqkcel** [comment]
props: {},
这样也会报错

**Comment by qqcbqqkcel** [comment]
我用了其他的组件中使用了全局props，希望是Bug，而非设计如此。

**Comment by qqcbqqkcel** [comment]
@tangjinzhou 
重现地址 https://codesandbox.io/s/vue-antd-template-7lb8n
点击日期框就会报错，有些组件不会报错。

已知出错的组件有：日期、日历、走马灯。

**Comment by tangjinzhou** [comment]
不要全局混入props，会影响到函数式组件的取值
