### ISSUE TITLE
在table 使用scopedSlots->customRender,在slot中使用a-switch，选择下一页a-switch的状态不变，跟第一页一样

### ISSUE THREAD

**Issue by pansusu** [vueComponent/ant-design-vue#1106]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
linux, all of browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
<span slot="red_color" slot-scope="text,record ,index">
<a-switch checkedChildren="是" unCheckedChildren="否" @change="toHightLight(record,'0',$event)" :defaultChecked="text=='0'?false:true"/>
</span>

### What is expected?
麻烦提供解决方案

### What is actually happening?
组件由缓存

**Comment by tangjinzhou** [comment]
没有复现链接  我真的没时间去重现问题  感谢理解  🙏
