### ISSUE TITLE
table组件 getCheckboxProps的disabled 可以动态设置么

### ISSUE THREAD

**Issue by pqhchan** [vueComponent/ant-design-vue#1113]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以动态控制每个tr的可选中状态

### What does the proposed API look like?
```js
const rowSelection = {
  getCheckboxProps: (record) => ({
    props: {
      disabled: record['isLocked'],
    }
  })
}
```

**Comment by glxe** [comment]
我也有这个需求，应该是新开一个API接口，比如 setCheckboxProps 这样的。

**Comment by zkwolf** [comment]
> 我也有这个需求，应该是新开一个API接口，比如 setCheckboxProps 这样的。

https://antdv.com/components/table-cn/#components-table-demo-selection 这个没法实现吗

**Comment by glxe** [comment]
> > 我也有这个需求，应该是新开一个API接口，比如 setCheckboxProps 这样的。
> 
> https://antdv.com/components/table-cn/#components-table-demo-selection 这个没法实现吗

我的需求是通过select组件对另外两个table实现联动控制，一开始看文档这个getCheckboxProps这个API 只说是设置默认属性配置，我就认为只是初始设置，不能动态更改，其实是可以的。

通过 [https://github.com/vueComponent/ant-design-vue/issues/935](url) 这个。

**Comment by JinLuhuan** [comment]
onChange中将tableData重新设置即可再次触发

**Comment by 60late** [comment]
> onChange中将tableData重新设置即可再次触发

thank u sir!
