### ISSUE TITLE
carousel不能autoplay

### ISSUE THREAD

**Issue by hkaikai** [vueComponent/ant-design-vue#1115]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
"ant-design-vue": "1.3.15",     "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vcs3i)

### Steps to reproduce
created或mounted里面的setInterval导致carousel不能autoplay

### What is expected?
autoplay属性生效

### What is actually happening?
配置了autoplay不能自动播放

**Comment by tangjinzhou** [comment]
拆分成两个组件 
https://codesandbox.io/s/vue-antd-template-5ll8j

**Comment by hkaikai** [comment]
谢谢，拆分成两个组件没问题，可是后续会修改成不用拆分两个嘛

**Comment by wdloading** [comment]
> 谢谢，拆分成两个组件没问题，可是后续会修改成不用拆分两个嘛

还有一种骚操作。
貌似是setInterval过短导致的，比如我之前定时器每3000毫秒执行一次，那么我的autoplaySpeed只要低于3000毫秒就能正常执行，一旦大于等于3000毫秒就不轮播了，于是我把setInterval改成了60000毫秒，现在我可以实现每5000毫秒轮播一次了

autoplaySpeed: 5000

this.timer = setInterval(() => {
      this.renderData()
    }, 60000)
