### ISSUE TITLE
带单元格编辑的表格功能扩展 

### ISSUE THREAD

**Issue by ykl124** [vueComponent/ant-design-vue#1122]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1. 表格的一行，不是每个单元格都需要编辑。
2. 需要编辑的类型不止input框，还有时间控件、下拉框等等，就像表单输入控件那样。

我知道有个题目类似的issue（https://github.com/vueComponent/ant-design-vue/issues/47），但是那个issue已经被关闭，我无法留言，解决方案链接404，作者也提到没有真正解决需求，所以这里再提一下。

### What does the proposed API look like?
类似rowSelection，可以增加 rowSelect，rowDatePicker等等

**Comment by tangjinzhou** [comment]
scopedSlots: { customRender: "x" }  结合 v-if 可以实现
