### ISSUE TITLE
form里面自定义组件只能有自定义规则吗？普通规则可以吗？

### ISSUE THREAD

**Issue by lengband** [vueComponent/ant-design-vue#1124]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
"ant-design-vue": "1.3.15", "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-x9hbo?fontsize=14)

### Steps to reproduce
rules: [{ validator: checkPrice }],  换成了rules: [{ required: true, message: '请填写' }] 后未生效

### What is expected?
普通表单规则可以用

### What is actually happening?
[{ required: true, message: '请填写' }] 未生效

**Comment by sendya** [comment]
这是你的表单值 

Object {price: Object}
```
price: {
  number: 0
  currency: "rmb"
}
```

`required` 用于校验是否有值，很明显你的表单是有值的， 这不是 `未生效`，而是 `设计如此`

**Comment by lengband** [comment]
3q
