### ISSUE TITLE
When modal is closing, it changes the visible value automatically 

### ISSUE THREAD

**Issue by PegasusZero** [vueComponent/ant-design-vue#1125]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
Windows 10 |  Chrome 76.0.3809.100 |  vue-cli 3.5.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-4jv5y?fontsize=14)

### Steps to reproduce
1) click "add" button
2) close modal

### What is expected?
no [Vue warn] should be shown

'Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "visible"'

**Comment by tangjinzhou** [comment]
You can not use v-model for prop's value (visible).

**Comment by zhenzhenChange** [comment]
我也想问这个问题，一般是为了抽离父子组件，父组件里面引用一个模态窗子组件。然后从父组件传递一个 `props` : `visible` 给模态窗来控制它的显示/隐藏，但在关闭（通过取消按钮/遮罩层/右上角 x 按钮关闭）的时候，会报 `props` 单向数据流不可逆改的错误。

我试过在模态窗子组件通过 `$emit` 或在父组件的 `props` 加上 `.sync` 修饰符调用父组件的方法来关闭，也会报这个错。

所以这个 `visible` 只能在模态窗组件上定义吗？然后在父组件通过 `$refs` 或者 `$children` 调用模态窗内部的方法来控制显示/隐藏？
