### ISSUE TITLE
the v-model in a-table didn't work as well as it in a-pagination

### ISSUE THREAD

**Issue by akino512** [vueComponent/ant-design-vue#1126]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
ubuntu 18.04,chrome 76.0.3809.100,vue 2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-7quf5)

### Steps to reproduce
In this example,I bound the v-model in a-table and the v-model in a-pagination to the same  variable "page".

### What is expected?
I expect that the two pagination would change synchronously no matter which side was clicked ,but it didn't.

### What is actually happening?
When I change "page" in a- table ,the "page" in a- pagination made a change  at the same time.
But when I change "page" in a- pagination, there is no any changes on a- table.

Is it a bug or just my fault?

---
简单地说，就是改变a-table 中分页的绑定值page，不会响应到页面上
而改变页面，确实会响应到变量page上。

**Comment by wangxueliang** [comment]
https://codesandbox.io/s/vue-antd-template-hs6j9

**Comment by akino512** [comment]
@wangxueliang 
Thank you very mach for your reply.
-
我想我懂如何去使用了。
百忙之中抽空来解答，不胜感激。
