### ISSUE TITLE
IE9下input框内placeholder值没有显示

### ISSUE THREAD

**Issue by caryYin** [vueComponent/ant-design-vue#113]
### Version
1.0.2

### Environment
IE9

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/input-cn/](https://vuecomponent.github.io/ant-design-vue/components/input-cn/)

### Steps to reproduce
https://vuecomponent.github.io/ant-design-vue/components/input-cn/

### What is expected?
placeholder值能显示，react的实现可以显示。https://ant.design/components/input-cn/
![image](https://user-images.githubusercontent.com/9817765/43890053-4b76bd3e-9bf8-11e8-88aa-bf74e49ccd55.png)

### What is actually happening?
placeholder值不能显示。
![image](https://user-images.githubusercontent.com/9817765/43889996-287d180a-9bf8-11e8-8e3e-8cb0ab7dd207.png)

**Comment by tangjinzhou** [comment]
请自行添加相关polyfill兼容
https://github.com/jamesallardice/Placeholders.js
https://cdnjs.com/libraries/placeholders/4.0.1

**Comment by caryyin** [comment]
非常感谢，已解决！`<a-input/>` 标签使用`:vlaue`时没有问题，但使用`v-model`，`placeholder`的值不会清除。
