### ISSUE TITLE
radio 选中样式中心圈在 windows 系统下偏左或偏右就是没在正中间

### ISSUE THREAD

**Issue by shuperry** [vueComponent/ant-design-vue#1133]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
vue 2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
使用 radio 即可

### What is expected?
radio 选中样式中心圈在 windows 系统下偏左或偏右就是没在正中央

### What is actually happening?
radio 选中样式中心圈在正中央

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/63818785-363f8580-c975-11e9-9e0a-d6a64a2ce7c2.png)

这是放大 700% 的单选，如果你看这个的样式不在正中央，那么去看别的组件库，例如 material design 等，均会显示不在正中央，这一般是由于电脑系统字体或者分辨率导致的。你可以在别的 PC 上尝试看看是否表现一致
