### ISSUE TITLE
表格多选框，在大数据情况下。选择和取消选择卡顿

### ISSUE THREAD

**Issue by xinzhexingzhe** [vueComponent/ant-design-vue#1138]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
windows

### Reproduction link
[https://pan.baidu.com/s/1qLsYWYrbfBV2pL0j_F4Dig  提取码: gupf ](https://pan.baidu.com/s/1qLsYWYrbfBV2pL0j_F4Dig  提取码: gupf )

### Steps to reproduce
在表格中填充50~100条数据。保证列有二十列左右

### What is expected?
希望，在表格大数据情况下，单选和取消选择以及全选，取消全选不再出现卡顿

### What is actually happening?
点击表格多选框，出现卡断。估计是表格内填充的数据过多

---
希望版本更新快点

**Comment by lianshuang** [comment]
同，还无解决方案，很难受~~~~
