### ISSUE TITLE
input输入框能不能加一个输入长度监控功能，就是ELementUI的input的show-word-limit属性

### ISSUE THREAD

**Issue by LiuYnag** [vueComponent/ant-design-vue#1139]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
希望在input上添加实时显示输入数据长度功能

### What does the proposed API look like?
功能与[ElementUI](https://element.eleme.cn/#/zh-CN/component/input)的input的属性show-word-limit是一样的

**Comment by Ifover** [comment]
这都2年过去了 还没加么
