### ISSUE TITLE
please update a feature is multiple selection of cascader components just  like element-ui

### ISSUE THREAD

**Issue by rawKylin** [vueComponent/ant-design-vue#1141]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
cascader can multiple-selection. demo address：https://element.eleme.cn/#/en-US/component/cascader#multiple-selection

### What does the proposed API look like?
Set props.multiple = true to use multiple selection.

**Comment by tangjinzhou** [comment]
you can use  TreeSelect.

**Comment by tangjinzhou** [comment]
ref #886
