### ISSUE TITLE
npm run dev , site/dev.js 中import Test 组件不存在

### ISSUE THREAD

**Issue by pengfeiWang** [vueComponent/ant-design-vue#1144]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.15

### Environment
mac os

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/site/dev.js#L15](https://github.com/vueComponent/ant-design-vue/blob/master/site/dev.js#L15)

### Steps to reproduce
查看 site/dev.js 15行, 导入的文件不存在

### What is expected?
期望仓库文件是正确的

### What is actually happening?
文件缺失

**Comment by sendya** [comment]
dev 用于提供组件开发的入口
请自行修改到要开发的组件路径

```
https://github.com/vueComponent/ant-design-vue/blob/master/site/dev.js#L15
```

**Comment by wenwen100** [comment]
给个例子？

**Comment by wenwen100** [comment]
已解决。‘../components/form/demo/index.vue’ 修改类似的。 浏览器地址再改成本地ip。
