### ISSUE TITLE
Cascader级联选择 需要支持多选

### ISSUE THREAD

**Issue by 975156298** [vueComponent/ant-design-vue#1145]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我需要筛选出某个市下面的其中几个县。故需要多选这个功能。

### What does the proposed API look like?
option.multiple  通过此参数进行控制

**Comment by tangjinzhou** [comment]
暂无计划，建议使用treeSelect组件替换

**Comment by 975156298** [comment]
好的，谢谢&nbsp;
------------------



黄祚敏
商道科技


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangjinzhou"<notifications@github.com&gt;; 
发送时间: 2019年9月6日(星期五) 下午3:39
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "975156298"<975156298@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] Cascader级联选择 需要支持多选 (#1145)




暂无计划，建议使用treeSelect组件替换
