### ISSUE TITLE
在TS创建的组件中，使用v-decorator 出现input文本框不能正常使用

### ISSUE THREAD

**Issue by wwwwwwwwwy** [vueComponent/ant-design-vue#1146]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
win10,Google Chrome版本 76.0.3809.132，vue 2.6.10

### Reproduction link
[https://github.com/wwwwwwwwwy/decorator](https://github.com/wwwwwwwwwy/decorator)

### Steps to reproduce
yarn install
yarn run serve
然后打开首页，有个文本框，鼠标点击，键盘输入无效。

### What is expected?
能正常输入信息

### What is actually happening?
能不能正常输入信息， 文本框一直为空。

**Comment by Jalery521** [comment]
我也遇到了同样的问题
Vue版本: 2.6.1, 环境: Win10, Chrome版本78.0.3904.97,Typescript版本:3.5.3

**Comment by taoqingqiu** [comment]
> export default class XXX extends Vue {
> form: any // 此处不能赋值
> beforeCreate () { // 使用beforeCreate后可输入可校验
> this.form = this.$form.createForm(this)
> }
> }

阁下牛逼。
