### ISSUE TITLE
树形控件中checked与halfChecked在checkStrictly=false时运用

### ISSUE THREAD

**Issue by lsixi** [vueComponent/ant-design-vue#1152]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
checkStrictly=true时,checkable状态下节点选择完全受控（父子节点选中状态不再关联）,此时不可能出现halfChecked的节点, 而checkStrictly=false时, 非常需要知道checked和halfChecked分别是什么

### What does the proposed API look like?
```js
<a-tree
checkable checkStrictly defaultExpandAll
:autoExpandParent="autoExpandParent"
v-model="checkedKeys"
:treeData="treeData"/>

// ...
console.log(checkedKeys)
```
- checkStrictly=ture,这个时候checkedKeys是一个对象,例如{checked: [17], halfChecked: []}, 此时halfChecked永远都是空的,
- checkStrictly=false(默认), 因为父子节点选中状态有关联, 此时halfChecked应该有值

**Comment by Hccake** [comment]
遇到同样的问题

**Comment by sammyke** [comment]
同求，设置true居然不给halfChecked，false倒给了返回值，是不是作者别有用意？还是返回错误？

**Comment by zkwolf** [comment]
其实halfcheck的key可以在onCheck事件里拿到

**Comment by jiyihui** [comment]
在不设置checkStrictly的时候，halfCheckedKeys 可以在Oncheck回调的第二个参数中拿到
示例代码：
    onCheck(checkedKeys: any, e) {
      this.halfCheckedKeys = e && e.halfCheckedKeys
      this.checkedKeys = checkedKeys
    },
