### ISSUE TITLE
请求添加折叠布局器(splitter)功能

### ISSUE THREAD

**Issue by chenchifeng** [vueComponent/ant-design-vue#1153]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
例如在两个栅格之间,添加一个分割线,然后这个分割线可以调整两个分栏之间的宽度,也可以把某一边的分栏隐藏掉,比现有的Grid更灵活.类似于miniui里面的[Splitter 分割器](http://www.miniui.com/docs/tutorial/splitter.html)

### What does the proposed API look like?
类似于miniui的[Splitter 分割器](http://www.miniui.com/docs/tutorial/splitter.html)
```html
<a-splitter style="width:350px;height:200px;">
  <div size="30%" :showCollapseButton="true">
     1
  </div>
  <div :showCollapseButton="true">
     2
  </div>
</a-splitter>
```

##### API

Name | Type | Description | Default
-|-|-|-
minSize | Number  | 最小尺寸 | 80
maxSize | Number | 最大尺寸 | 3000
size | Number/String|尺寸| -
showCollapseButton|Boolean|是否显示折叠图标|-
cls 	|String |	面板样式类 |-
style 	|String |	面板样式|-
visible 	|Boolean |	是否显示 	|-
expanded 	|Boolean |	是否折叠|-

**Comment by huoshidehua** [comment]
这个组建应该挺有用的

**Comment by huoshidehua** [comment]
可惜啊 antd react团队貌似没有意愿去加这个

**Comment by transtone** [comment]
> 可惜啊 antd react团队貌似没有意愿去加这个

都是独立的项目，该加就加，为什么非得看 antd react 团队的脸色？


这个组件 viewui 有，叫面板分割：
https://www.iviewui.com/components/split
https://github.com/view-design/ViewUI/tree/master/src/components/split
