### ISSUE TITLE
divider

### ISSUE THREAD

**Issue by cnlydia** [vueComponent/ant-design-vue#1154]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
VScode chrome  vue 2.9.6

### Reproduction link
[https://vue.ant.design/components/divider-cn/](https://vue.ant.design/components/divider-cn/)

### Steps to reproduce
<a-divider type="vertical" dashed/>

### What is expected?
vertical dashed divider

### What is actually happening?
just one point

**Comment by xrkffgg** [comment]
距离太短了吧
