### ISSUE TITLE
a-tab-pane绑定事件无效

### ISSUE THREAD

**Issue by jonnyshao** [vueComponent/ant-design-vue#1155]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
最新macos,chrome,vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-r6f61)

### Steps to reproduce
```javascript
<a-tabs>
<a-tab-pane
v-for="item of panes"
:key="item.key"
:tab="item.title"
@mousedown.native="onMousedown"
></a-tab-pane>
</a-tabs>
```

### What is expected?
绑定的事件生效

### What is actually happening?
无效

**Comment by wangxueliang** [comment]
https://codesandbox.io/s/vue-antd-template-6zkhz
