### ISSUE TITLE
carousel 设置fade=true，第一次进入无法看到内容，等autoplay-speed设置的时间后才可以看到

### ISSUE THREAD

**Issue by hkaikai** [vueComponent/ant-design-vue#1158]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
"ant-design-vue": "1.3.16",     "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-d9v5j)

### Steps to reproduce
carousel 设置fade=true

### What is expected?
希望一进来就加载第一个

### What is actually happening?
前3秒是白屏的

**Comment by Keleir** [comment]
@hkaikai unrelated question, I'm doubted Whether the `autoplay-spedd` parameter can control the auto play behavior. The official API [doc](https://vue.ant.design/components/carousel/) have no refrence about this attribute.

**Comment by hkaikai** [comment]
https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-slick/src/default-props.js#L3

**Comment by tangjinzhou** [comment]
你给的 Reproduction link 没问题啊

**Comment by hkaikai** [comment]
有大量数据和Carousel一同渲染时有这个问题，和[#1115](https://github.com/vueComponent/ant-design-vue/issues/1115)一样，单独抽离一个组件就没问题了

**Comment by hkaikai** [comment]
pauseOnDotsHover参数设置无效，Carousel没有这个props，导致鼠标悬停dot没有暂停自动播放
