### ISSUE TITLE
表格的数据为布尔值不显示也不报错

### ISSUE THREAD

**Issue by krisven** [vueComponent/ant-design-vue#1159]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
vue 2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-1dd54)

### Steps to reproduce
表格数据有布尔值即可复现

### What is expected?
能显示布尔值

### What is actually happening?
不支持布尔值？

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-8b1u4
手动转换成字符串
