### ISSUE TITLE
TreeSelect树选择设置treeNodeLabelProp属性无效

### ISSUE THREAD

**Issue by gjf450005950** [vueComponent/ant-design-vue#1161]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
"ant-design-vue": "1.3.16",  "vue": "^2.5.22", Chrome:版本 74.0.3729.108（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-0euix)

### Steps to reproduce
设置 treeNodeLabelProp 属性
```html
<a-tree-select style="width: 300px"
:treeData="treeData"
treeNodeLabelProp="yourCustomName">
</a-tree-select>
```

```javascript
const treeData = [
{
title: "Node1",
value: "0-0",
key: "0-0",
yourCustomName: "Node1",
children: [
{
title: "0-0-1",
value: "0-0-1",
key: "0-0-1",
yourCustomName: "Node1 > 0-0-1"
},
{
title: "Child Node2",
value: "0-0-2",
key: "0-0-2",
yourCustomName: "Node1 > Child Node2"
}
]
},
{
title: "Node2",
value: "0-1",
key: "0-1",
yourCustomName: "Node2"
}
];
export default {
data() {
return {
treeData
};
}
};
```

### What is expected?
选择后显示 yourCustomName 值

### What is actually happening?
选择后显示 value 值

**Comment by doghap** [comment]
我也发现这个问题了， 你有没有什么解决方案？

**Comment by gjf450005950** [comment]
没有，跟了下源码没看明白

**Comment by gjf450005950** [comment]
测试了下1.4.0-beta.0 版本，问题仍在。

**Comment by MarvinXu** [comment]
+1

**Comment by gjf450005950** [comment]
"ant-design-vue": "1.4.1", 问题仍在

**Comment by tangjinzhou** [comment]
暂时仅支持 title、label、value 属性

**Comment by iizhan** [comment]
![image](https://user-images.githubusercontent.com/63840516/82283144-1a2eb900-99c8-11ea-842d-4261c433a56c.png)
za在tree-select中临时调整不知可以否，该部分规范能否告知，我想支持修改

**Comment by luoyeshu0507** [comment]
v1.5 问题依然在
