### ISSUE TITLE
Can I implement infinite scroll in table? 

### ISSUE THREAD

**Issue by CuongStf** [vueComponent/ant-design-vue#1167]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I need apply vue-infinite-scroll package to table in ant? Possible i implement into table, isn't?

### What does the proposed API look like?
element package support append property to add infinite scroll in last row, how to do same with ant-table?

**Comment by enhezzz** [comment]
hi,guy,can you solve this problem??please you can hlep me
