### ISSUE TITLE
Add submit method in Form component to trigger submit manully instead of add submit button

### ISSUE THREAD

**Issue by TonyLuo** [vueComponent/ant-design-vue#1168]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I would like to submit the form data and trigger the data validation in modal dialog, but now I cannot find any method in form component which can help to do this.

### What does the proposed API look like?
this.form.submit()

**Comment by sendya** [comment]
this.form.validateFields()
