### ISSUE TITLE
select下拉框内容较多时内容展示不全

### ISSUE THREAD

**Issue by sff5201314** [vueComponent/ant-design-vue#1169]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
下拉框内容较多时内容展示完全，长度自动撑开

### What does the proposed API look like?
期望能够将下拉框的width属性改为min-width,不但保证了内容较短时与输入框同宽，同时也保证了内容较多时显示完全的问题。

**Comment by useryechen** [comment]
应该是select就不应该撑开父级盒子，react版本的就没问题，vue版本的会把父级盒子撑开，导致页面排版就有问题了 ,我把`.ant-form-item-control-wrapper`这个类名宽度层叠掉暂时可以解决，宽度设为`62%`刚好差不多

**Comment by dzcpy** [comment]
为什么这个问题是 wontfix？感觉很影响用户体验啊

**Comment by moriwang** [comment]
赞同，select 选单现在的长度被限制死了，这是不科学的。希望修复。
