### ISSUE TITLE
website style broken

### ISSUE THREAD

**Issue by afc163** [vueComponent/ant-design-vue#117]
### Environment
All browsers

### Reproduction link

[https://vuecomponent.github.io/ant-design-vue/docs/vue/introduce/](https://vuecomponent.github.io/ant-design-vue/docs/vue/introduce/)

### screenshot

<img width="840" alt="image" src="https://user-images.githubusercontent.com/507615/43904801-33b34a44-9c22-11e8-96cc-8b671f784542.png">

There are two borders.

**Comment by afc163** [comment]
<img width="273" alt="image" src="https://user-images.githubusercontent.com/507615/43905193-1f199ac4-9c23-11e8-82ef-c3b3d0d815d6.png">

The padding of code box is missing too.

**Comment by tangjinzhou** [comment]
done  😆

**Comment by afc163** [comment]
![image](https://user-images.githubusercontent.com/507615/43971097-712a6642-9d02-11e8-94da-c464fd0f13ce.png)

**Comment by tangjinzhou** [comment]
好眼力，已修复
初期没有规划好，后续会考虑使用bisheng来搞
