### ISSUE TITLE
input输入卡顿2-3秒（受当前页渲染数据多少影响）

### ISSUE THREAD

**Issue by gjf450005950** [vueComponent/ant-design-vue#1170]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
"ant-design-vue": "1.3.16",  "vue": "^2.5.22", Chrome:版本 74.0.3729.108（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-o2yy9)

### Steps to reproduce
表单与表格在同一个页面内,  快速输入数据（或者按住某个按键,连续输入）
页面内只有一个input一样卡。
### What is expected?
与表单无关的数据不影响表单

### What is actually happening?
当前页面内与表单无关的数据影响表单验证速度

**Comment by tangjinzhou** [comment]
这就为难我了   表单和表格写在一个文件内，任何变化都会导致双方都重新render，这是 vue 的渲染机制
或者你试试这个功能 https://github.com/vueComponent/ant-design-vue/issues/1049

**Comment by gjf450005950** [comment]
加了selfUpdate，还是一样的卡，没效果，除了独立成单独的组件，还有其他方案规避这个问题嘛？
