### ISSUE TITLE
Table支持斑马纹现实效果

### ISSUE THREAD

**Issue by belongwqz** [vueComponent/ant-design-vue#1174]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格增加斑马纹现实效果，使奇数行和偶数行的背景色有差别，避免视觉疲劳。

### What does the proposed API look like?
<a-table stripe  :columns="columns" :dataSource="data">

**Comment by sendya** [comment]
https://codesandbox.io/s/antd-table-rowclassname-94j0b

**Comment by belongwqz** [comment]
变通的做法是这样不错，但需要自己写样式，感觉如果能使用一个参数（如stripe）来控制（elementui和iviewui已支持）更方便。

**Comment by sendya** [comment]
Ant Design 的 API 设计上并没有这一块的功能点，所以目前并没从组件里直接去支持。
使用 `rowClassName` 没有任何难度，加两个样式就能控制了。

**Comment by belongwqz** [comment]
好吧，只能说不同设计有不同理念
