### ISSUE TITLE
布局组件最后几个示例中都是 404 错误

### ISSUE THREAD

**Issue by vajacn** [vueComponent/ant-design-vue#118]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
Chrome

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/layout-cn/](https://vuecomponent.github.io/ant-design-vue/components/layout-cn/)

### Steps to reproduce
打开页面，从「固定侧边栏」示例开始就是 404

### What is expected?
正常显示示例。

### What is actually happening?
提示 404

---
初步判断是修改项目名称造成的，iframe 中的错误地址：https://vuecomponent.github.io/ant-design/iframe/layout/#fixed-sider
将 ant-deisgn 改为 ant-design-vue 即可正常访问。

**Comment by tangjinzhou** [comment]
已修复 多谢反馈
