### ISSUE TITLE
affix容器变化，影响affix元素位置 的一个解决方案

### ISSUE THREAD

**Issue by Sotyoyo** [vueComponent/ant-design-vue#1181]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

### 问题：
[antd-vue #1](https://github.com/vueComponent/ant-design-vue/issues/1)
[antd #5642](https://github.com/ant-design/ant-design/issues/5642)
当元素affix后，绑定的target进行scroll，resize操作的时候，affix元素位置会重新计算，然而更多的父级容器的行为不能影响affix的位置重新计算
### 官方：
是已知问题，但是由于考虑到性能、使用场景，这个问题不需要修复
### 我的解决措施：
如果有一个数组props传入，使得affix受到数组内targets行为事件的影响，来重新计算位置？这样的话用户可以更高限度的减少未知预期的显示，例如传入页面layout内预期应当滚动的容器target和window的target，这样应该不会影响多少性能，且给使用者很好的体验。

### 我的伪代码实现：
（水平有限，如果写的不好，改就完事了，勿喷）

```javascript
// API 加一个 Property
// 需要监听触发更新的 dom 元素集合
targetsTosetListener: {
  type: Array,
  default: () => {
    return [];
  }
}

// 遍历这个targetsTosetListener，绑定上事件，然后affix响应位置变化
import addEventListener from '../_util/Dom/addEventListener';  // 这个文件在a-affix的源码里面

// methods
this.updateP = () => {
  const affix = this.$refs.affixP;
  affix.updatePosition({});
}

// mounted
this.targetsTosetListener.forEach(target => {
  this.eventHandlers['resize'] = addEventListener(target, "resize", this.debounceUpdateP)
  this.eventHandlers['scroll'] = addEventListener(target, "scroll", this.debounceUpdateP)
  // ...
}

// beforeDestroy
this.eventHandlers.forEach(handler => {
  if (handler && handler.remove) {
    handler.remove();
  }
});
```

**Comment by xiaodun** [comment]
我是这样解决的    [解决Antd Affix组件位置、宽度不随容器变化的问题](https://www.jianshu.com/p/ff311b8a5541)
