### ISSUE TITLE
Menu 电击下拉时会卡顿

### ISSUE THREAD

**Issue by valuebles** [vueComponent/ant-design-vue#1185]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
Google Chrome 76.0.3809.132  ，  Windows 10,

### Reproduction link
[https://vue.ant.design/components/menu/](https://vue.ant.design/components/menu/)

### Steps to reproduce
Menu组件 下拉时会卡顿

### What is expected?
希望Menu下拉时不会卡顿

### What is actually happening?
Carton when Menu toggles drop-down

**Comment by vvizden** [comment]
的确，总感觉卡卡的

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/issues/873
