### ISSUE TITLE
使用 dropdown 在外层包一层组件的话会报错

### ISSUE THREAD

**Issue by pengfeiWang** [vueComponent/ant-design-vue#1186]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
mac os

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-rvuwt)

### Steps to reproduce
重现连接中, 触发dropdown的 hover 会在控制台看到错误

### What is expected?
dropdown能够正常

### What is actually happening?
dropdown不能运行

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-template-lwl52

你的 Menu.Item 没有引入吧

**Comment by pengfeiWang** [comment]
没错, 是没引入 item
