### ISSUE TITLE
使用AutoComplete组件，当数据量过大时，组件卡顿严重，影响使用体验感受。

### ISSUE THREAD

**Issue by zhengsansan** [vueComponent/ant-design-vue#1187]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
Google Chrome  76.0.3809.132（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-lme9y)

### Steps to reproduce
1.项目里引用AutoComplete组件
2.数据源有上千条
3.点击组件时，数据弹出很慢，而且选择数据也会卡顿

### What is expected?
1.希望数据量大时，点击组件弹出数据快速
2.希望数据量大时，搜索数据不卡顿
3.希望数据量大时，选择某一项数据不会卡顿

### What is actually happening?
1.项目里引用AutoComplete组件
2.数据源有上千条
3.点击组件时，数据弹出很慢，而且选择数据也会卡顿

---
https://codesandbox.io/s/vue-antd-template-lme9y  的app组件里可以查看实例

**Comment by wangxueliang** [comment]
这个并不是组件问题，是vue框架性能问题，原生渲染也慢，建议优化业务逻辑，比如说展示前200条

**Comment by ht159357** [comment]
这和你渲染几百几千个listItem一样，dom过多都会影响性能的

**Comment by Kimi1020** [comment]
the same problem.  mark

**Comment by CookyG** [comment]
虚拟列表可以引入么？
