### ISSUE TITLE
modal组件的width属性bug

### ISSUE THREAD

**Issue by artiely** [vueComponent/ant-design-vue#119]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
任何环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/985lw8v1pw)

### Steps to reproduce
modal的width属性只有在大屏下才是生效的，小屏幕时会自动响应式宽度

### What is expected?
小屏幕时还是以设置的width为主

### What is actually happening?
modal的width属性只有在大屏下才是生效的，小屏幕时会自动响应式宽度，width属性无效

**Comment by tangjinzhou** [comment]
看antd是有意为之，是出于什么考虑 @afc163
是否有必要强制响应式

**Comment by tangjinzhou** [comment]
@artiely 暂且使用样式覆盖吧

**Comment by tangjinzhou** [comment]
很抱歉，目前样式会定期同步antd，为了后期方便维护，暂不会对样式做区别于antd的改动。
如有需要，可自行定义样式，感谢支持！
