### ISSUE TITLE
【BUG】自定义表单组件异常 ReferenceError: initialValue is not defined

### ISSUE THREAD

**Issue by chengyadong** [vueComponent/ant-design-vue#1190]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
macOS 10.14.5, Chrome 75.0.3770.100, Vue 2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-form/src/createBaseForm.jsx](https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-form/src/createBaseForm.jsx)

### Steps to reproduce
自定义表单组件使用 v-decorator 时 添加 initialValue 报错，组件渲染失败

### What is expected?
组件正常渲染

### What is actually happening?
提示 ReferenceError: initialValue is not defined，组件无法渲染

**Comment by sendya** [comment]
请提供复现，谢谢

**Comment by headMe** [comment]
value props不能设置默认值

**Comment by liudonghua123** [comment]
@sendya 我也遇到这个问题，原来这里的代码感觉有问题
initialValue 这里确实没有定义，如果v-decorator中有option，则就会执行到这里，然后报这个错，这是一个break bugs，希望能尽快修复

![image](https://user-images.githubusercontent.com/2276718/66539221-e3531380-eb59-11e9-9d2c-5dd483f9d6f0.png)

**Comment by tangjinzhou** [comment]
update to v1.4.1
