### ISSUE TITLE
【BUG】多选框组，v-model绑定后在勾选得值 有误

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#1191]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-behyz?fontsize=14)

在示例里，多选框组v-model绑定了3个，取消勾选其中一个在输出绑定值，理论应该显示剩2个值，实际仍然显示3个，在勾上却显示2个。

**Comment by sendya** [comment]
API **Checkbox Group**

参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
defaultValue | 默认选中的选项 | string[] | []
disabled | 整组失效 | boolean | false
options | 指定可选项，可以通过 slot="label" slot-scope="option" 定制label | string[] \| Array<{ label: string value: string disabled?: boolean, onChange?: function }> | []
value | 指定选中的选项 | string[] | []


事件名称 | 说明 | 回调参数
-- | -- | --
change | 变化时回调函数 | Function(checkedValue)

https://www.antdv.com/components/checkbox-cn/#Checkbox-Group

[![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)
](https://codesandbox.io/s/checked-bug-86z9n)

try it

**Comment by GlodenBoy** [comment]
> API **Checkbox Group**
> 
> 参数	说明	类型	默认值
> defaultValue	默认选中的选项	string[]	[]
> disabled	整组失效	boolean	false
> options	指定可选项，可以通过 slot="label" slot-scope="option" 定制label	string[] | Array<{ label: string value: string disabled?: boolean, onChange?: function }>	[]
> value	指定选中的选项	string[]	[]
> 事件名称	说明	回调参数
> change	变化时回调函数	Function(checkedValue)
> https://www.antdv.com/components/checkbox-cn/#Checkbox-Group
> 
> [![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667) ](https://codesandbox.io/s/checked-bug-86z9n)
> 
> try it

老哥，是意思无法使用v-model吗，我在示例里看到有v-model得用法 才使用得，但是发现绑定得值变化比较奇怪，用:value+change得方法的却可以，就是有点啰嗦，所以想直接使用v-model得方法。

**Comment by sendya** [comment]
我不是给你贴例子了？

**Comment by GlodenBoy** [comment]
> 我不是给你贴例子了？

sorry, 网速太渣没有刷出sanBox，是我得锅，多谢老哥。
