### ISSUE TITLE
table 中 columns 的 slots : { title: 'xxx' } 不生效

### ISSUE THREAD

**Issue by tanxuewei** [vueComponent/ant-design-vue#1197]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
chrome, vue 2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
table 中 columns 的 slots : { title: 'xxx' } 不生效

### What is expected?
table 中 columns 的 slots : { title: 'xxx' } 生效

### What is actually happening?
期待生效

**Comment by sendya** [comment]
请提供复现，谢谢

**Comment by marswong** [comment]
@tanxuewei 不要用 `slots`，用：

```js
scopedSlots: {
    title: 'customTitle',
},
```

**Comment by tanxuewei** [comment]
@sendya 场景就是想改变表格的每一列表头内容，文档里面是这样写得：When using columns, you can use this property to configure the properties that support the slot, such as slots: { filterIcon: 'XXX'}，但是我想改变title， slots : { title: 'xxx' }， 并没有生效

**Comment by sendya** [comment]
> @sendya 场景就是想改变表格的每一列表头内容，文档里面是这样写得：When using columns, you can use this property to configure the properties that support the slot, such as slots: { filterIcon: 'XXX'}，但是我想改变title， slots : { title: 'xxx' }， 并没有生效

https://vue.ant.design/components/table/#components-table-demo-basic-usage

```diff
  <a-table :columns="columns" :dataSource="data">
    <a slot="name" slot-scope="text" href="javascript:;">{{text}}</a>
++    <span slot="customTitle"><a-icon type="smile-o" /> Name</span>
    <span slot="tags" slot-scope="tags">
      <a-tag v-for="tag in tags" color="blue" :key="tag">{{tag}}</a-tag>
    </span>
    <span slot="action" slot-scope="text, record">
      <a href="javascript:;">Invite 一 {{record.name}}</a>
      <a-divider type="vertical" />
      <a href="javascript:;">Delete</a>
      <a-divider type="vertical" />
      <a href="javascript:;" class="ant-dropdown-link">
        More actions <a-icon type="down" />
      </a>
    </span>
  </a-table>
```

```diff
const columns = [{
  dataIndex: 'name',
  key: 'name',
  slots: { title: 'customTitle' },
++  scopedSlots: { customRender: 'name' },
}, {
  title: 'Age',
  dataIndex: 'age',
  key: 'age',
}, {
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
}, {
  title: 'Tags',
  key: 'tags',
  dataIndex: 'tags',
  scopedSlots: { customRender: 'tags' },
}, {
  title: 'Action',
  key: 'action',
  scopedSlots: { customRender: 'action' },
}];
```

**Comment by tanxuewei** [comment]
@sendya 不生效哈，我之前就这样写得

**Comment by tanxuewei** [comment]
https://github.com/sendya/ant-design-pro-vue/issues/102  和这个应该是一个问题，但是这个是ant-design-pro-vue这个项目

**Comment by sendya** [comment]
> @sendya 不生效哈，我之前就这样写得

不生效请提供复现

**Comment by tanxuewei** [comment]
1、列数据
columns: [{
        title: '名称',
        dataIndex: 'unitName',
        slots: { title: 'customTitle' }
      }]
2、模板
<a-table
      :columns="columns"
      :dataSource="list"
      :rowKey="record => record.unitId"
      :rowClassName="record => 'row-small'"
      :pagination="false"
      :defaultExpandAllRows="true"
      :expandedRowKeys="expandedRowKeys"
      @expand="changeExpand"
      size="middle">
      <span slot="customTitle">xxx</span>
    </a-table>
3、结果：标题还是‘名称’，并不是'xxx'

**Comment by sendya** [comment]
不是说了 `scopedSlots: { customRender: 'name' },` 吗？为什么还是 `slots`

**Comment by tanxuewei** [comment]
@sendya scopedSlots 这个是针对渲染的数据吧，我指的的是表头显示。。

**Comment by sendya** [comment]
那你提供复现把 codesandbox 。官网有提供复现用的模板

**Comment by tanxuewei** [comment]
@sendya 我知道了，根本原因就是我不应该写title，columns: [{
dataIndex: 'unitName',
slots: { title: 'customTitle' }
}]。。。这样就可以了，谢谢回复

**Comment by sendya** [comment]
这是我给你的没有问题的例子 https://codesandbox.io/s/vue-antd-template-50tzf

**Comment by herosPan** [comment]
使用slot时怎么动态获取title,而不是直接写成xxx

**Comment by xoptimal** [comment]
@sendya  设置表头, 一直报错警告, 这种该怎么解决呢 ???

[Vue warn]
Unknown custom element: <sapn> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

code
```
<sapn slot="priceTitle">售价
        <sapn :style="{color: 'red'}">*</sapn>
      </sapn>
      <sapn slot="disPriceTitle">折扣价
        <sapn :style="{color: 'red'}">*</sapn>
      </sapn>
   
```

**Comment by chaiwei** [comment]
> @sendya 设置表头, 一直报错警告, 这种该怎么解决呢 ???
> 
> [Vue warn]
> Unknown custom element: - did you register the component correctly? For recursive components, make sure to provide the "name" option.
> 
> code
> 
> ```
> <sapn slot="priceTitle">售价
>         <sapn :style="{color: 'red'}">*</sapn>
>       </sapn>
>       <sapn slot="disPriceTitle">折扣价
>         <sapn :style="{color: 'red'}">*</sapn>
>       </sapn>
>    
> ```

`sapn` 打错了吧? 应该是 `span`
