### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by artiely** [vueComponent/ant-design-vue#120]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
任何环境

### Reproduction link
[http://tangjinzhou.gitee.io/ant-design-vue/components/modal-cn/](http://tangjinzhou.gitee.io/ant-design-vue/components/modal-cn/)

### Steps to reproduce
modal组件的width属性只支持number文档上是string|number

### What is expected?
modal组件的width属性只支持number

### What is actually happening?
modal组件的width属性只支持number文档上是string|number

**Comment by tangjinzhou** [comment]
支持string的  字符串需要明确px 还是%
