### ISSUE TITLE
上传图片遮罩显示方式优化

### ISSUE THREAD

**Issue by MikuBlog** [vueComponent/ant-design-vue#1203]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我希望能够提供多种显示遮罩的方式，比如说click、hover等

### What does the proposed API look like?
类似element-ui的tips的显示方式

**Comment by tangjinzhou** [comment]
没明白

**Comment by MikuBlog** [comment]
@tangjinzhou 当鼠标移动至上传图片组件的图片上时，会显示灰色遮罩。我想能不能通过点击的方式显示遮罩，这样就不容易误触到预览和删除按键。

**Comment by tangjinzhou** [comment]
你可以自己写遮罩层和点击事件
