### ISSUE TITLE
a-table能不能在空数据文案中添加新的标签

### ISSUE THREAD

**Issue by Zuojiangtao** [vueComponent/ant-design-vue#1209]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
ant-design-vue1.3.9；现代浏览器和 IE9 及以上；vue2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/1208](https://github.com/vueComponent/ant-design-vue/issues/1208)

### Steps to reproduce
a-table无数据文案locale字段对象中只有一个emptyText来传入string

### What is expected?
期望可以无数据文案可以加入其它标签，如a标签和button等

### What is actually happening?
实际上没找到可以加入标签的字段或者方法

**Comment by kindredPP** [comment]
同问，ele有一个slot="empty"插槽，不知道antd有没有类似功能

**Comment by sendya** [comment]
目前最新的 beta 版 `config-provider` 有一个  `renderEmpty` 属性，可以传递自定义的 VNode 作为空状态


这是 Demo： https://codesandbox.io/s/vue-template-jt4to  你可以尝试一下
![image](https://user-images.githubusercontent.com/5404542/65672960-839a3a00-e07c-11e9-97d7-a55b809f74e9.png)

**Comment by Zuojiangtao** [comment]
好的，感谢。
