### ISSUE TITLE
Responsive navbar & drawer

### ISSUE THREAD

**Issue by mapsgeek** [vueComponent/ant-design-vue#121]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
add a responsive navigation bar like in bootstrap and a drawer to keep in sync with ant design for react

### What does the proposed API look like?
`<a-navbar theme="light" collapse='sm'>`
or something similar just a concept

**Comment by tangjinzhou** [comment]
Drawer is under development.
Navbar has no plans. Maybe you can use menu custom styles to achieve responsive purposes.

**Comment by mapsgeek** [comment]
@tangjinzhou is there any available example for achieving responsive navbar using the menu styles ?

**Comment by tangjinzhou** [comment]
please update to 1.1.0  add drawer
