### ISSUE TITLE
slider component aferChange event

### ISSUE THREAD

**Issue by Nancy2013** [vueComponent/ant-design-vue#1211]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.14

### Environment
browser version,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-wm0ey)

### Steps to reproduce
when I put a slider in a  modal component ,set the maskClosable of the modal  false，click the slider first and then click the mask of the modal,the afterChange event will be listened twice

### What is expected?
when click the mask of the modal,the afterChange will not be  listened.because I don't change the slider.

### What is actually happening?
the afterChange will be listened twice

**Comment by tangjinzhou** [comment]
1.4.0-beta.0 已修复
