### ISSUE TITLE
tabs在默认展开pane隐藏的状态下，非隐藏的pane没有展开内容

### ISSUE THREAD

**Issue by wx7614140** [vueComponent/ant-design-vue#1215]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
chrome,vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-dbofn)

### Steps to reproduce
创建a-tabs,defaultActiveKey=1，两个a-tab-pane,第一个a-tab-pane中v-if=false,key=1

### What is expected?
显示的pane默认展开第一个的内容

### What is actually happening?
显示的pane没有一个展示内容，需要点击才能展开内容

---
如果不是bug的话能否提供先实现

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-template-13ss3
