### ISSUE TITLE
当form 表单有 initialValue时，执行 resetFields 只能重置到默认状态 而不是清空

### ISSUE THREAD

**Issue by LiLixikun** [vueComponent/ant-design-vue#1218]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0

### Environment
nuxt 2.00

### Reproduction link
[https://vue.ant.design/components/form-cn/#API](https://vue.ant.design/components/form-cn/#API)

### Steps to reproduce
使用form 表单  给form-item 添加默认值 initialValue  执行resetFields   只能重置到默认状态 而不是清空。

### What is expected?
希望能像react antd 一样可以清空

### What is actually happening?
使用form 表单  给form-item 添加默认值 initialValue  执行resetFields   只能重置到默认状态 而不是清空。

**Comment by tangjinzhou** [comment]
react antd 也是重制到 initialValue

**Comment by 939347507** [comment]
不建议修改，目前默认的挺好的，既然设置了初始值，理所当然的应该重置到初始状态，这里初始状态就是有初始值的情况
