### ISSUE TITLE
the declared prop name is error when passed to component

### ISSUE THREAD

**Issue by semi-aurora** [vueComponent/ant-design-vue#1221]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
Vue2.6.10,antd vue 1.3.16/1.3.17-beta1

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/releases/tag/1.3.16](https://github.com/vueComponent/ant-design-vue/releases/tag/1.3.16)

### Steps to reproduce
```
<a-date-picker
placeholder="请选择日期和时间"
format="YYYY-MM-DD HH:mm:ss"
:disabledDate="disabledDate"
:disabledTime="disabledDateTime"
:showTime="{ minuteStep: 'minuteStep',secondStep:'30' }"
></a-date-picker>
```
```
[Vue tip]: Prop "disableddate" is passed to component <Anonymous>, but the declared prop name is "disabledDate". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "disabled-date" instead of "disabledDate".
...
same with showtime,disabledtime
```

### What is expected?
like demo https://vue.ant.design/components/date-picker-cn/

### What is actually happening?
showTime is not working

**Comment by sendya** [comment]
是非工程化开发吗（直接在 html 里写 vue 和 template ）？

**Comment by supine-win** [comment]
> 是非工程化开发吗（直接在 html 里写 vue 和 template ）？

是的
