### ISSUE TITLE
the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `[object Object]`. Error in render: "Error: Need at least a key or a value or a label (only for OptGroup) for [object Object]"

### ISSUE THREAD

**Issue by remember-5** [vueComponent/ant-design-vue#1233]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0-beta.0

### Environment
win10,chrome76.0.3809.100,vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-yv0hb)

### Steps to reproduce
非常抱歉，无法定位问题

### What is expected?
正常展示

### What is actually happening?
控制台报错the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `[object Object]`.
Error in render: "Error: Need at least a key or a value or a label (only for OptGroup) for [object Object]"

---
官网给的demo,亲测会报错，本人非前端，无法精准的定位到问题。

**Comment by chieh301** [comment]
+1

**Comment by wangjiahao0505** [comment]
@chieh301 换成1.3.6版本可以正常展示，老哥，建议你先降级版本用。

**Comment by zkwolf** [comment]
@tangjinzhou https://github.com/vueComponent/ant-design-vue/commit/c015c8d34c6d6654b4d4042c2dd1b4e00e3e784b 这个commit里对于props-utils.js的修改导致了这个问题，getSlots方法里有用到

**Comment by chieh301** [comment]
> @chieh301 换成1.3.6版本可以正常展示，老哥，建议你先降级版本用。

正常運行了，謝啦!

**Comment by wendesun** [comment]
+1

**Comment by z357904947** [comment]
官网的例子直接报错。。现在这个问题还在

**Comment by ibyteyou** [comment]
+1 bad bad
