### ISSUE TITLE
实现表格的自定义表头

### ISSUE THREAD

**Issue by xueyh121** [vueComponent/ant-design-vue#1235]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0-beta.0

### Environment
vue

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
不用复现

### What is expected?
实现需求

### What is actually happening?
无

**Comment by sendya** [comment]
如果是表头的事件/样式等 可以用下面的 api，如果是表头标题之类的 Table `customHeaderCell` 属性
```diff
<Table
  customRow={(record) => {
    return {
      props: {
        xxx...
      },
      on: {
        click: () => {},       // click row
        mouseenter: () => {},  // mouse enter row
        xxxx...
      },
    };
  )}
++  customHeaderRow={(column) => {
++    return {
++      on: {
++        click: () => {},        // click header row
++      },
++    };
  )}
/>
```

**Comment by xueyh121** [comment]
> 如果是表头的事件/样式等 可以用下面的 api，如果是表头标题之类的 Table `customHeaderCell` 属性
> 
> ```diff
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx...
>       },
>       on: {
>         click: () => {},       // click row
>         mouseenter: () => {},  // mouse enter row
>         xxxx...
>       },
>     };
>   )}
> ++  customHeaderRow={(column) => {
> ++    return {
> ++      on: {
> ++        click: () => {},        // click header row
> ++      },
> ++    };
>   )}
> />
> ```

好的，我去研究一下

**Comment by xueyh121** [comment]
> 如果是表头的事件/样式等 可以用下面的 api，如果是表头标题之类的 Table `customHeaderCell` 属性
> 
> ```diff
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx...
>       },
>       on: {
>         click: () => {},       // click row
>         mouseenter: () => {},  // mouse enter row
>         xxxx...
>       },
>     };
>   )}
> ++  customHeaderRow={(column) => {
> ++    return {
> ++      on: {
> ++        click: () => {},        // click header row
> ++      },
> ++    };
>   )}
> />
> ```

大佬，这我见过但是看不懂啊，我说的是columns[]里的title属性怎么动态，这个属性不是分为string和slot嘛，我想着是不是从这里可以入手

**Comment by lhldyf** [comment]
> 如果是表头的事件/样式等 可以用下面的 api，如果是表头标题之类的 Table `customHeaderCell` 属性
> 
> ```diff
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx...
>       },
>       on: {
>         click: () => {},       // click row
>         mouseenter: () => {},  // mouse enter row
>         xxxx...
>       },
>     };
>   )}
> ++  customHeaderRow={(column) => {
> ++    return {
> ++      on: {
> ++        click: () => {},        // click header row
> ++      },
> ++    };
>   )}
> />
> ```

你好，想要实现的是在展开/收起的那行的header中添加一个图标，看起来用这个customHeaderRow是能实现的，不过看API不是很看的明白，jsx的语法还不熟，看源码也没太看懂，问下大佬这个具体怎么用呢，props里能传什么参数呢？
```
  customHeaderRow: (
    column: any,
    index: number,
  ) => {
    props: object;
    attrs: object;
    on: object;
    class: object;
    style: object;
    nativeOn: object;
  };
```

@sendya

**Comment by lhldyf** [comment]
看到了手册的这个[vue.jsx链接](https://github.com/vuejs/babel-plugin-transform-vue-jsx) 
用domProps 是可以把表头内容给替换掉的，是否可以只替换展开/收起那一个列的，谢谢。

**Comment by JinPengGeng** [comment]
@lhldyf 给你举个例子，目前我的需求是table第一列为checkbox，但是由于需要合并行，所以不能使用native API 的rowSelection,自己实现了一个checkbox
title: () => {
            return (
              <a-checkbox
                indeterminate={this.indeterminate}
                checked={this.checkAll}
                onChange={this.onCheckAllChange}
              />
            )
          },

**Comment by JinPengGeng** [comment]
@lhldyf title 在定义columns时指定
columns: [
        {
          title: () => {
            return (
              <a-checkbox
                indeterminate={this.indeterminate}
                checked={this.checkAll}
                onChange={this.onCheckAllChange}
              />
            )
          },
          fixed: 'left',
          align: 'center',
          width: 50
       }
]
