### ISSUE TITLE
Table组件期望能类似element ui的table一样，当column内容过长时实现ellipse使用...显示

### ISSUE THREAD

**Issue by calebzhao** [vueComponent/ant-design-vue#1238]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前table的内容过长时会换行显示，样式完全错位

### What does the proposed API look like?
Table组件期望能类似element ui的table一样，当cell内容过长时使用...显示， 当鼠标移到cell上时使用tooltip显示完整内容，

ant design类似的issuse：ant-design/ant-design#5753

ant design的pull：ant-design/ant-design#17284

**Comment by QifanChan** [comment]
目前我们是手动做的。。

**Comment by 939347507** [comment]
> 目前我们是手动做的。。

虽然自己能做，但是太麻烦了，有很多属性要显示时，为了做这个效果还得一个个写slot, 搞tooltip，表格在管理系统中大量使用，像element-ui那样做成属性，超长内容只需要添加一个show-overflow-tooltip多好

**Comment by QifanChan** [comment]
是的是的，能解决更好啊

**Comment by sendya** [comment]
> > 目前我们是手动做的。。
> 
> 虽然自己能做，但是太麻烦了，有很多属性要显示时，为了做这个效果还得一个个写slot, 搞tooltip，表格在管理系统中大量使用，像element-ui那样做成属性，超长内容只需要添加一个show-overflow-tooltip多好

照这个 PR 给 vue antd 也来个 PR?
https://github.com/ant-design/ant-design/pull/17284

**Comment by QifanChan** [comment]
你不是提过了嘛

**Comment by 939347507** [comment]
> > > 目前我们是手动做的。。
> > 
> > 
> > 虽然自己能做，但是太麻烦了，有很多属性要显示时，为了做这个效果还得一个个写slot, 搞tooltip，表格在管理系统中大量使用，像element-ui那样做成属性，超长内容只需要添加一个show-overflow-tooltip多好
> 
> 照这个 PR 给 vue antd 也来个 PR?
> [ant-design/ant-design#17284](https://github.com/ant-design/ant-design/pull/17284)

有心无力，我做java后台开发的，vue这一套只是在项目中大量使用而已，并没有到源码的地方，时间精力不允许，项目中就是自己封装一些简单的组件自己使用而已，1个人搞1个项目那种，复杂界面花钱请第三方，简单界面自己搞

**Comment by QifanChan** [comment]
大家都是这样大家都是这样的，图个方便嘛

**Comment by jandy273003185** [comment]
:show-overflow-tooltip="true"
