### ISSUE TITLE
希望增加跟antd react 里面的几个新组件 Descriptions描述列表、 result结果、 Mentions提及

### ISSUE THREAD

**Issue by xiaofuliang** [vueComponent/ant-design-vue#1240]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
描述列表这个组件在很多查看详情页面时用到

### What does the proposed API look like?
https://ant.design/components/descriptions-cn/

**Comment by undoZen** [comment]
查到是已经在 feat-1.5.0 分支的，希望能尽快发布 https://github.com/vueComponent/ant-design-vue/pull/1251#issuecomment-560347572
