### ISSUE TITLE
在 Tree 组件中使用 showLine 属性，无法自定义图标

### ISSUE THREAD

**Issue by thrfox** [vueComponent/ant-design-vue#1243]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我查看了ant-design中的一个issues [#14562](https://github.com/ant-design/ant-design/issues/14562)，提供了SwicherIcon属性可用于自定义树形的icon，我查阅了文档没发现有相同的属性可用于配置该icon

### What does the proposed API look like?
希望能提供同样的属性自定义该icon

**Comment by huanlirui** [comment]
+1 我也有这个问题。无法设置自定义展开图标

**Comment by Evenssi** [comment]
同求这个问题
