### ISSUE TITLE
slider组件在绑定value之后，滑块无法移动

### ISSUE THREAD

**Issue by haojay5** [vueComponent/ant-design-vue#1245]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://ant-design-vue.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by sendya** [comment]
使用 `v-model` 谢谢
