### ISSUE TITLE
【Carousel 走马灯】在数据动态渲染的时候 每次加载页面完成后 首次显示的是 最后一个item的内容, 并且下面的slick-dots 没有actived状态

### ISSUE THREAD

**Issue by huaiguoguo** [vueComponent/ant-design-vue#1247]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.17

### Environment
win10 1903， chrome77.0.3865.90,   vue框架nuxt2.9.0,  antd-vue 1.3.17

### Reproduction link
[https://vue.ant.design/components/carousel-cn/#components-carousel-demo-custom-paging](https://vue.ant.design/components/carousel-cn/#components-carousel-demo-custom-paging)

### Steps to reproduce
在vue生命周期函数：mount中把接口返回数据动态赋给 Carousel

<a-carousel>
<div v-for="(child, index) in hangeQingList" :key="index" class="screen_list">
<div v-for="(item, child_index) in child" :key="child_index" class="item">
<span>{{item.name1}}</span>
<span>{{item.priceNormal}}</span>
<span v-if="item.limit == 1" style="color:#e4004b;"> {{item.limitFee}}</span>
<span v-if="item.limit == -1" style="color:#47b884;">{{item.limitFee}}</span>
<span>≈{{item.cny}} CNY</span>
</div>
</div>
</a-carousel>

### What is expected?
Carousel  在数据动态渲染的时候 每次加载页面完成后 首次显示的是 最后一个item的内容, 并且下面的slick-dots 没有actived状态

### What is actually happening?
在数据动态渲染的时候 每次加载页面完成后 首次显示的是 最后一个item的内容, 并且下面的slick-dots 没有actived状态

**Comment by WingLL** [comment]
遇到同样问题，请问  您后来解决了吗

**Comment by myxtype** [comment]
> 遇到同样问题，请问 您后来解决了吗

建议使用v-if，拿到数据时才渲染

**Comment by cnyet** [comment]
@myxtype  建议有效， @huaiguoguo initialSlide属性可以指定初始化时首先展示的索引，默认是0。
```
<a-carousel v-if="list.length" effect="fade" :initial-slide="1">
  <p v-for="item in list" :key="item.id">{{item.name}}</p>
</a-carousel>
```
