### ISSUE TITLE
TreeSelect 堆栈溢出问题

### ISSUE THREAD

**Issue by jinyaqiao1102** [vueComponent/ant-design-vue#1252]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
IE 11  vue 2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
用SelectTree加载全国的省市区县 堆栈溢出

### What is expected?
页面正常

### What is actually happening?
页面报错卡死

**Comment by LovelyGirl4** [comment]
我也遇到了同样的问题，部门树数据过大，导致整个页面的输入点击变得卡顿，请问您是怎么解决的

**Comment by tangjinzhou** [comment]
一个卡顿一个堆栈溢出   不是一个问题

**Comment by LovelyGirl4** [comment]
请问数据比较大，采用异步加载，搜索时获取匹配项的各个父节点展开(异步)，但是第一次搜索会为空（实际有值），第二次输入相同的搜索值可以。考虑应该是异步的问题，第一次搜索项和树title匹配时，搜索项相应的父节点展开还未完成，请问这样我该怎么处理比较好呀？

**Comment by lizhongyi** [comment]
表格的组件也是会出现栈溢出，带有复选框的那个组件，不知道是不是跟vue版本有关系，我的是2.5

**Comment by lichangchao15442** [comment]
请问有人解决了吗？数据量过大TreeSelect直接栈溢出
