### ISSUE TITLE
table里面排序功能在handleTableChange的时候，拿不到sorter参数

### ISSUE THREAD

**Issue by QifanChan** [vueComponent/ant-design-vue#1254]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0-beta.0

### Environment
win10，os

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
table排序的功能，第一下ascend，第二下descend，第三下拿不到sorter，更拿不到sorter.columnKey。所以第三下是没有任何作用的。并且，当有多列排序的时候，排序的样式不支持多列共同亮起。

### What is expected?
希望可以实现table排序去掉中间态，不能的话希望可以提供第三下的参数，以确定点击是哪一列；存在多列排序的时候，可以支持显示多列的排序样式。

### What is actually happening?
目前：执行排序的时候，点击操作在第三下的时候是一个空状态。其实是无效操作。并且在多列排序的时候，排序样式只active显示当前操作的列。不能显示出来其他列的状态

**Comment by tangjinzhou** [comment]
第三次是回到默认状态，多列排序，table组件是不支持的，只能自己更改原数据进行排序

**Comment by QifanChan** [comment]
> 进行
那能否确定是点击的哪一列，，即提供sorter
