### ISSUE TITLE
table布局问题，fixed:left的列合并的话会有布局问题

### ISSUE THREAD

**Issue by see311** [vueComponent/ant-design-vue#1260]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
vue 2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-6n7m5?fontsize=14&module=%2Fsrc%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
见重现链接

### What is expected?
布局正常

### What is actually happening?
布局不正常，fixed:left的列行合并有问题

**Comment by wangxueliang** [comment]
https://codesandbox.io/s/vue-template-f2135   感觉用的不太对

**Comment by see311** [comment]
@wangxueliang 我看例子就是删了colspan，但是总计这行需要合并4列，如果你把fixed：left的列删了可以看到下面原始表格的列合并是正常的

**Comment by see311** [comment]
@wangxueliang 
是我用的问题。。。别的列没有colspan=0
