### ISSUE TITLE
关于使用 iconfont.cn 无法自定义颜色的问题

### ISSUE THREAD

**Issue by YouziXR** [vueComponent/ant-design-vue#1262]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
项目使用了 iconfont.cn 的symbol模式，UI上传了图标，都只有一种颜色，但我想自己在代码中更换图标的颜色，类似官方文档中使用自定义图标时用:style="{color: 'hotpink'}"这样使用。请问有什么方法吗？

### What does the proposed API look like?
自定义上传到 iconfont.cn 的图标的颜色

**Comment by KeonaHu** [comment]
这个问题确实让使用iconfont.cn图标的功能性出现了折扣,希望能够解决!

**Comment by alleluya-young** [comment]
原来一年前就有这个问题吗? 请问现在有解决办法吗?
