### ISSUE TITLE
关于table绑定pagination后，无法触发pagination的onChange方法

### ISSUE THREAD

**Issue by useryechen** [vueComponent/ant-design-vue#1266]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.16

### Environment
OS: windown7         Browser: chrome 77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-qdh5o)

### Steps to reproduce
暂无

### What is expected?
table绑定的pagination的onChange函数可以生效，可以实现快速跳转

### What is actually happening?
目前无法通过快速跳转进行分页切换

**Comment by sendya** [comment]
![GIF](https://user-images.githubusercontent.com/5404542/66632846-f807d800-ec3b-11e9-97cc-6d979bb5e41d.gif)

没有任何问题，你是不是分页输入了 连回车都没敲？

**Comment by useryechen** [comment]
> ![GIF](https://user-images.githubusercontent.com/5404542/66632846-f807d800-ec3b-11e9-97cc-6d979bb5e41d.gif)
> 
> 没有任何问题，你是不是分页输入了 连回车都没敲？

谢谢，因为我之前使用`react`版本的开发过，`react`版本的失去焦点就可以触发，我以为这个不需要做回车操作

**Comment by sendya** [comment]
如果 react 确实提供了这个 feature，欢迎提供 PR 到 vue 版，或者等待 vue 版后期跟进该 feature

**Comment by useryechen** [comment]
> 如果 react 确实提供了这个 feature，欢迎提供 PR 到 vue 版，或者等待 vue 版后期跟进该 feature

好的
