### ISSUE TITLE
when use scroll with table, it have warning

### ISSUE THREAD

**Issue by zkwolf** [vueComponent/ant-design-vue#1267]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0-beta.0

### Environment
x

### Reproduction link
[https://z1b7h.csb.app/](https://z1b7h.csb.app/)

### Steps to reproduce
use a-table with scroll prop

### What is expected?
no warning

### What is actually happening?
Warning: Each record in dataSource of table should have a unique `key` prop, or set `rowKey` of Table to an unique primary key,

**Comment by tangjinzhou** [comment]
Each record in dataSource of table should have a unique key prop, or set rowKey of Table to an unique primary key

**Comment by zkwolf** [comment]
...warning我给复制错了，更新了一下，默认基础demo+ scroll

**Comment by Clago** [comment]
不能同时共用吗？现在table内嵌table还是会警告，但是页面显示暂时未发现问题。
