### ISSUE TITLE
table列表项可多选时，进行数据更新。选中的数据无法保留

### ISSUE THREAD

**Issue by jxgahxs** [vueComponent/ant-design-vue#1269]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当我使用table列表项可多选时，在选中数据后，分页或者搜索产生了数据更新。此时我已选中的数据已经不存在了。我想即使数据进行更新后，即rowSelection的onChange函数可以返回新选择的数据与之前选中的数据

### What does the proposed API look like?
是否可以像element-ui一样，在表格数据进行更新后，依然保证选中的数据不产生变化。当我在新数据源中选择时，返回的应该时之前选中的与此时选中的

**Comment by sendya** [comment]
自行将你保存在本地的 `selectedRowKeys` 变量跟 `onChange` 提供的 `selectedRowKeys` 不是就可以了?

**Comment by jxgahxs** [comment]
> 自行将您保存在本地的`selectedRowKeys`变量跟`onChange`提供的`selectedRowKeys`不是就可以了吗？
selectedRowKeys是可以保留的，但是我想保留对应的整行呢？

**Comment by sendya** [comment]
> selectedRowKeys是可以保留的，但是我想保留对应的整行呢？

`onChange` 事件中不是还有 `selectedRows`。 同理

**Comment by jxgahxs** [comment]
> > selectedRowKeys是可以保留的，但是我想保留对应的整行呢？
> 
> `onChange`事件中不是还有`selectedRows`。同理

如果我在第一页中选中了五条记录，然后翻页到第二页。此时在第二选中二条记录。onChange事件回调返回selectedRows只有两条。即使我把第一页的五条存在本地记录中。我再回到第一页取消其中到三条。此时应该是五条。但是onChange.selectedRows只有两条。如何能像element-ui那样。翻页之后选中数据还会保留之前调

**Comment by useryechen** [comment]
> > > selectedRowKeys是可以保留的，但是我想保留对应的整行呢？
> > 
> > 
> > `onChange`事件中不是还有`selectedRows`。同理
> 
> 如果我在第一页中选中了五条记录，然后翻页到第二页。此时在第二选中二条记录。onChange事件回调返回selectedRows只有两条。即使我把第一页的五条存在本地记录中。我再回到第一页取消其中到三条。此时应该是五条。但是onChange.selectedRows只有两条。如何能像element-ui那样。翻页之后选中数据还会保留之前调

`onChange`的时候`selectedRows`只会返回你当前页选中的行,你可以在`onChange`时，将本地存储的行数据赋值到`selectedRowkeys`

**Comment by whateveryoudo** [comment]
感觉官方可以处理下，selectedRowkeys是能够保留之前的，selectedRows只会记录当前页， 同样的功能，react版本是能够保留的

**Comment by yuzhewo** [comment]
你们讨论的这个问题我感觉很困惑，我现在的问题就是翻页或者重新请求数据，原来选中的id和item内容无法清空，现在的机制完全能够实现此问题讨论的需求，

> > 自行将您保存在本地的`selectedRowKeys`变量跟`onChange`提供的`selectedRowKeys`不是就可以了吗？
> > selectedRowKeys是可以保留的，但是我想保留对应的整行呢？

分页以后之前的记录是被保存的，但是在第二页选择后之前的选择会被onchange覆盖，无法跨页保存。

**Comment by yuzhewo** [comment]
我的版本^1.6.2测试结果是，数据刷新或者重新搜索时，之前的选择还会存在， 分页时候就会丢失或者被新选择覆盖。这个效果在逻辑上应该是不正确的。一般需求是刷新数据的时候清空选中，分页的时候保存才对。我现在用到搜索导出数据功能，只能通过this.$refs.table.clearSelected()手动清空选中，否则会把上次搜索结果选中的数据一起导出。

**Comment by sendya** [comment]
> 我的版本^1.6.2测试结果是，数据刷新或者重新搜索时，之前的选择还会存在， 分页时候就会丢失或者被新选择覆盖。这个效果在逻辑上应该是不正确的。一般需求是刷新数据的时候清空选中，分页的时候保存才对。我现在用到搜索导出数据功能，只能通过this.$refs.table.clearSelected()手动清空选中，否则会把上次搜索结果选中的数据一起导出。

a-table 还有 `this.$refs.table.clearSelected()` 这方法？ 我怎么不知道..
另外， `selectedRowkeys` 是你自己受控的，应该由你处理是否要清理数据，而不是等着组件帮你清理数据，子组件正常是不能去操作父组件的数据的
