### ISSUE TITLE
在切换路由时候菜单没有变化

### ISSUE THREAD

**Issue by showtan001** [vueComponent/ant-design-vue#1273]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
MAC Pro， chrome77.0.3865.120, vue 2.6.6, antd-vue 1.3.5

### Reproduction link
[https://vue.ant.design/components/menu-cn/](https://vue.ant.design/components/menu-cn/)

### Steps to reproduce
在子菜单页面里点击按钮切换到另一个子菜单页面的时候（this.$router.push({name:'order'});），导航菜单还停留在以前子菜单。

### What is expected?
在切换路由后，导航菜单也切换

### What is actually happening?
导航菜单没有变化

**Comment by sendya** [comment]
请自己监听路由变化，并更新 Menu 组件的 selectedKeys

**Comment by showtan001** [comment]
哦  谢谢
