### ISSUE TITLE
如何动态切换主题？和ant官网底部的切换主题颜色一样，还没找到解决方案

### ISSUE THREAD

**Issue by wwwjun** [vueComponent/ant-design-vue#1276]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
Windows10

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
无

### What is expected?
动态切换 设置好的主题 而不是只是设置一种

### What is actually happening?
没找到方法 还请赐教

---
多谢~

**Comment by wzy4072** [comment]
我见过，你可以参考下，需要动态编译的。
http://boot.jeecg.com/user/login
（账号密码有提示的）登录之后到右上角点击系统设置，里面有主题色 导航位置等动态设置的功能。

**Comment by wwwjun** [comment]
> 我见过，你可以参考下，需要动态编译的。
> http://boot.jeecg.com/user/login
> （账号密码有提示的）登录之后到右上角点击系统设置，里面有主题色 导航位置等动态设置的功能。

嗯嗯 想在项目源码上面去改动 但是不知如何下手 网上在脚手架层面动态配置的插件 再研究研究吧

**Comment by sendya** [comment]
https://github.com/hzsrc/webpack-theme-color-replacer

e.g https://github.com/sendya/ant-design-pro-vue/blob/master/config/plugin.config.js

**Comment by wwwjun** [comment]
> https://github.com/hzsrc/webpack-theme-color-replacer
> 
> e.g https://github.com/sendya/ant-design-pro-vue/blob/master/config/plugin.config.js

多谢 其实我是克隆的vue-ant-design源码，想在这上面改

**Comment by UchihaItachi6** [comment]
请问有这个链接的源码吗  http://boot.jeecg.com/user/login

**Comment by wzy4072** [comment]
Jeecg-Boot 是一款基于代码生成器的快速开发平台！采用前后端分离架构： SpringBoot 2.x，Ant Design&Vue，Mybatis-plus，Shiro，JWT。强大的代码生成器让前后端代码一键生成，无需写任何代码！！帮助Java项目解决70%的重复工作，让开发更多关注业务逻辑。既能快速提高开发效率，帮助公司节省成本，同时又不失灵活性。JeecgBoot还独创在线开发模式（No代码）：在线表单配置（表单设计器）、移动能力、流程配置（流程设计器）、报表配置、


https://github.com/zhangdaiscott/jeecg-boot 

不谢




wzy4072@163.com
 
发件人： UchihaItachi6
发送时间： 2020-01-16 09:57
收件人： vueComponent/ant-design-vue
抄送： wzy4072; Comment
主题： Re: [vueComponent/ant-design-vue] 如何动态切换主题？和ant官网底部的切换主题颜色一样，还没找到解决方案 (#1276)
请问有这个链接的源码吗 http://boot.jeecg.com/user/login
