### ISSUE TITLE
tag 预置颜色风格的扩展需求

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#1277]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/2329528/66797260-cbee9e80-ef3c-11e9-9c57-800442f7c6ac.png)

tag组件的颜色风格目前分2种，一种是预置的，一种是自定义的，2种风格完全不一样，预置的风格其实挺好，但是太少 无法扩展。

看了下tag样式那段的源码，知识面比较窄，不知是否可以提供一个预置风格的属性，可以不用去改CSS那么繁琐。

**Comment by GlodenBoy** [comment]
找到思路 暂时自己解决了，

提供思路供其他有需求的：

tag的是否默认风格是在 tag的组件里进行判断的，只判断了指定的颜色名字，
所以需要改，为了不破坏源码，新建了一个全局组件继承tag的组件，并且覆盖判断方法。

复制 生成默认样式的less函数代码，在自己的css里新建一个并且改成自己需要的颜色。

项目里tag组件改成自己的组件。用法一样，OK。

**Comment by tangjinzhou** [comment]
@GlodenBoy 不过有一定的风险，后续如果源码更改或删除了判断方法就会受到影响    建议直接写 style 覆盖样式

**Comment by GlodenBoy** [comment]
> @GlodenBoy 不过有一定的风险，后续如果源码更改或删除了判断方法就会受到影响 建议直接写 style 覆盖样式

老哥说的有道理，实际上复制出新css 想办法覆盖是最稳妥的解决办法
