### ISSUE TITLE
upload 号的样式问题

### ISSUE THREAD

**Issue by fonghehe** [vueComponent/ant-design-vue#1285]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
google

### Reproduction link
[https://vue.ant.design/components/upload-cn/](https://vue.ant.design/components/upload-cn/)

### Steps to reproduce
使用头像组件出现问题

### What is expected?
 号居中显示

### What is actually happening?
 号在组件顶部

**Comment by wangxueliang** [comment]
会尽快发版fix
