### ISSUE TITLE
Generate web-types for ant-design-vue package for rich code assist in IDE

### ISSUE THREAD

**Issue by piotrtomiak** [vueComponent/ant-design-vue#1286]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
This is a feature request to include [web-types](https://github.com/JetBrains/web-types) metadata information with `ant-design-vue` library to provide users of WebStorm (and possibly other IDEs in the future) with precise code completion, inspections and documentation for the components. There has already been 2 requests by users of `ant-design-package`: https://github.com/JetBrains/web-types/issues/13 and https://github.com/JetBrains/web-types/issues/11

### What does the proposed API look like?
The best solution would be to generate the file based on existing documentation JSONs during the build process and ship it with the library. This solution has been implemented in `quasar` and `bootstrap-vue` libraries and is being worked on in `vuetify`.

I can work on the transformation code itself, but it would be pretty difficult for me to hook into the build process in the correct place, so I need some help from your side, before I can create a PR for this. Additionally we can generate `web-types` for older versions of library and publish them to `@web-types/` scope so that consumers of older versions of library can also benefit from better code assist.

**Comment by rxliuli** [comment]
这对于 WebStorm 的代码提示相当重要，希望能添加支持。。。

**Comment by piotrtomiak** [comment]
Here is how code completion will look like with WebStorm 2019.3 and `bootstrap-vue` 2.1.0:

![web-types1](https://user-images.githubusercontent.com/4244523/67289568-1c3aa300-f4df-11e9-9521-5f4ae9f2e9e6.gif)

I think it's a really great help for developers to have such a support for your library.

**Comment by toleberdyyeva** [comment]
Is there any updates on that issue ?

**Comment by bigBron** [comment]
Is anyone following up on this issue?

**Comment by piotrtomiak** [comment]
@bigBron I am waiting for some help from the maintainers to start with.

**Comment by bigBron** [comment]
This is the web-types implementation of vuetify. 
https://github.com/vuetifyjs/vuetify/blob/c2734d3e7721ad794de84c89ce0486869580742c/packages/api-generator/src/index.js#L331-L461

**Comment by piotrtomiak** [comment]
@bigBron I've actually authored most of that code ;) What I need to know to start is how the documentation is generated? With this information I can plug-in to the build process and generate `web-types.json`
