### ISSUE TITLE
[需求]table组件的可伸缩列功能是否有排期

### ISSUE THREAD

**Issue by useryechen** [vueComponent/ant-design-vue#1288]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决列数据过多展示效果不佳

### What does the proposed API look like?
```
<a-table
:columns="columns"
:rowKey="record => record.login.uuid"
:dataSource="data"
:pagination="pagination"
:resizable="true"
@change="handleTableChange"
>
```

**Comment by hulei2014** [comment]
up up up

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/table/#components-table-demo-resizable-column
