### ISSUE TITLE
upload组件进度条丢失

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#1294]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
操作系统:mac  谷歌78  vue:2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/2wpk21kzvr)

### Steps to reproduce
官网的上传组件1.4.0上传进度条丢失,本地也一样

### What is expected?
上传有进度条

### What is actually happening?
上传没有进度条

**Comment by wangxueliang** [comment]
会尽快修复

**Comment by wangxueliang** [comment]
会尽快发版修复

**Comment by anncwb** [comment]
@wangxueliang upload的样式也有点问题,图片的加号 位置没有居中

**Comment by wangxueliang** [comment]
已发版
