### ISSUE TITLE
a-input v-decorator message

### ISSUE THREAD

**Issue by ibrahimsen** [vueComponent/ant-design-vue#1300]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
chrome, vue2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/1299](https://github.com/vueComponent/ant-design-vue/issues/1299)

### Steps to reproduce
How can I use i18n in v-decorator message property. {{ $('siginin.email')}} method not working.

`  v-decorator="[
'password',
{ rules: [{ required: true, message: '**Please input your Password!**'}] },
]" type="password" placeholder="**Password**"
`

### What is expected?
I want to use message or placeholder text with localization.

### What is actually happening?
$t('message') is not working.

**Comment by adjkldd** [comment]
here's a working example. 
https://codesandbox.io/s/vue-template-oo4uo?fontsize=14

**Comment by tangjinzhou** [comment]
when you change locale config, you should validate again.
