### ISSUE TITLE
a-input-password 组件所有的事件和双向绑定都没有效果

### ISSUE THREAD

**Issue by xiaohuwei** [vueComponent/ant-design-vue#1306]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
谷歌 MacOS

### Reproduction link
[https://vue.ant.design/components/input-cn/](https://vue.ant.design/components/input-cn/)

### Steps to reproduce
正常引用 全部失效

### What is expected?
得到解决

### What is actually happening?
业务无法进行！！！！

**Comment by sendya** [comment]
能提供一个复现吗？谢谢

**Comment by xiaohuwei** [comment]
```
<template>
  <div class="hello">
<a-input v-model="username" placeholder="Basic usage" />
<a-input-password  v-model="password" placeholder="input password" @change='change' />
 <a-button @click='login' type="primary">Login</a-button>
  </div>
</template>

<script>
    export default {
        name: 'HelloWorld',
        props: {
            msg: String
        },
        data() {
            return {
                username: '',
                password: ''
            }
        },
        methods:{
          login(){
           console.log(this.username,this.password)
          },
          change(){
            console.log(88888)
          }
        },
    }
</script>
<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
```
在线的组件都不能加载 直接给您代码吧

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-antd-template-r65mh   `password` 框确实有问题。

你可以先用 input 自己加 `suffix` 来实现 `input-password` 功能

**Comment by xiaohuwei** [comment]
好的 希望及早修复！！！😁

**Comment by hellodr333** [comment]
我也是碰到这个问题，想要一个密码框的效果，版本升级到了1.4.0，没想到，没法双向绑定，还没有解决这个问题么？
