### ISSUE TITLE
DatePicker在Mac Safari 12.X版本浏览器中点击选择时间时，时间选择弹框会自动关闭，请问是什么原因

### ISSUE THREAD

**Issue by luyukunluyukun** [vueComponent/ant-design-vue#1309]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.1

### Environment
Mac Safari 12.X

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/](https://vue.ant.design/components/date-picker-cn/)

### Steps to reproduce
在官网DataPicker即可复现

### What is expected?
不能在没有选择时间钱消失

### What is actually happening?
点击选择时间弹框自动关闭

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/67061761-e4a4c180-f193-11e9-88b7-218451cca04a.png)
没能复现你说的问题

**Comment by luyukunluyukun** [comment]
![image](https://user-images.githubusercontent.com/40846191/67062021-acea4980-f194-11e9-895b-40867ffc4e56.png)
![image](https://user-images.githubusercontent.com/40846191/67062041-c095b000-f194-11e9-9e74-fa78508cf290.png)
Safari 版本 12.1 (14607.1.40.1.4)
请点击我箭头所示位置button呢

**Comment by adjkldd** [comment]
@luyukunluyukun 我的没有问题哦
<img width="1165" alt="屏幕快照 2019-10-18 下午3 27 44" src="https://user-images.githubusercontent.com/4162413/67074661-25183580-f1bc-11e9-96ff-484341059cfa.png">

**Comment by luyukunluyukun** [comment]
@adjkldd 这个问题不一定会出现，就是不稳定，有时能用，有时又不能用

**Comment by tangjinzhou** [comment]
> @adjkldd 这个问题不一定会出现，就是不稳定，有时能用，有时又不能用

这就很尴尬了    12.0.2 (14606.3.4)版本 多次测试没能复现

可以尝试定位下问题，给我们提 PR ？ 😄

**Comment by meiseayoung** [comment]
@luyukunluyukun 问题解决了吗？我这儿也出现这个问题了

**Comment by meiseayoung** [comment]
@tangjinzhou 我发现antd react版本没有这个问题。react版本和vue版本有个不同点对这个问题产生了影响，react版本的是tabindex设置的值为-1，vue版本的tabindex值为0。我把-1改成0就可以了。
