### ISSUE TITLE
Scroll in drawer get lag on mobile

### ISSUE THREAD

**Issue by phongloihong** [vueComponent/ant-design-vue#1314]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.1

### Environment
Ios 13, chrome 77, Vue 2.6

### Reproduction link
[https://vue.ant.design/docs/vue/introduce](https://vue.ant.design/docs/vue/introduce)

### Steps to reproduce
Go to home page of vue ant design
https://vue.ant.design/docs/vue/introduce
Click to burrger button left side and scroll up or down to see issue happen.
I'm realise when focus to menu link and scroll you will get lag.

### What is expected?
Scroll should smooth event focus on menu link

### What is actually happening?
the scroll bar jumps up and down repeatedly making scrolling very difficult

**Comment by y2206310034** [comment]
Hello, I would like to ask if you have solved this problem
