### ISSUE TITLE
pagination快速跳转问题：输入页码，enter之后并没有跳转

### ISSUE THREAD

**Issue by Emily-Tang** [vueComponent/ant-design-vue#1316]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.1

### Environment
chrome77.0.3865.90   vue@2.5.22

### Reproduction link
[https://vue.ant.design/components/pagination-cn/](https://vue.ant.design/components/pagination-cn/)

### Steps to reproduce
输入快速跳转的页码，按enter键

### What is expected?
pagination跳转到相应页码

### What is actually happening?
enter之后并没有去触发change(页码改变的回调)事件

**Comment by sendya** [comment]
请提供复现，谢谢
