### ISSUE TITLE
IE9自定义Class未生效

### ISSUE THREAD

**Issue by caryyin** [vueComponent/ant-design-vue#132]
### Version
1.0.3

### Environment
IE9

### Reproduction link
[https://github.com/caryyin/star-demo/tree/master/star-ant-design-vue](https://github.com/caryyin/star-demo/tree/master/star-ant-design-vue)

### Steps to reproduce
启动后，访问 http://localhost:8080/ie9class

### What is expected?
在IE9浏览器下，字体显示红色并居中。
谷歌浏览器是OK的。
![image](https://user-images.githubusercontent.com/9817765/44202249-ffd60480-a17d-11e8-9b10-c6586c4fe458.png)

### What is actually happening?
在IE9浏览器下，字体非红色并居左。
![image](https://user-images.githubusercontent.com/9817765/44202225-ed5bcb00-a17d-11e8-92dc-4cc14c1ea80f.png)

**Comment by tangjinzhou** [comment]
如果你全量引入组件库css，会导致超出ie9能解析的css rule限制，后续添加的css也不会再生效，
具体限制规则可[查看stylesheet-limits-in-internet-explorer](https://blogs.msdn.microsoft.com/ieinternals/2011/05/14/stylesheet-limits-in-internet-explorer/)

你可以使用`按需加载` + [css-split-webpack-plugin](https://github.com/metalabdesign/css-split-webpack-plugin) 来分割减少css
