### ISSUE TITLE
An infinite update loop in a-table when "children" existed in data

### ISSUE THREAD

**Issue by LeeBangbang61** [vueComponent/ant-design-vue#1323]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
"vue": "2.6.10", "ant-design-vue": "1.4.3", "chrome": "77.0.3865.120"

### Reproduction link
[https://github.com/LeeBangbang61/learnVue](https://github.com/LeeBangbang61/learnVue)

### Steps to reproduce
Click thead to sort the table

### What is expected?
Sort success

### What is actually happening?
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <Table>
            <ATable>

**Comment by RYTON0305** [comment]
I also encountered this problem and hope to solve it.
