### ISSUE TITLE
空状态组件里面的图标能否默认保持跟列表这些组件一致，现在使用这组件，图片跟列表空状态不一致

### ISSUE THREAD

**Issue by xiaofuliang** [vueComponent/ant-design-vue#1328]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
保持一致

### What does the proposed API look like?
能否一致或者增加一个属性可以选择

**Comment by sendya** [comment]
renderEmpty | 自定义组件空状态。参考 空状态
-- | --

https://www.antdv.com/components/config-provider-cn/

**Comment by xiaofuliang** [comment]
能否提供一下类似react版本里面的 内置图片 
https://ant.design/components/empty-cn/   
![image](https://user-images.githubusercontent.com/23289722/67464934-cef13980-f676-11e9-8207-7b1f04f319d1.png)
![image](https://user-images.githubusercontent.com/23289722/67464968-dfa1af80-f676-11e9-8465-7009e58d270f.png)
Empty.PRESENTED_IMAGE_SIMPLE
Empty.PRESENTED_IMAGE_DEFAULT

**Comment by wkl007** [comment]
同样需要
