### ISSUE TITLE
浏览器里面直接引入构建后的文件不起效

### ISSUE THREAD

**Issue by nicewahson** [vueComponent/ant-design-vue#133]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
vue 2.x chrome68 windows7

### Reproduction link
[localhost:8080](localhost:8080)

### Steps to reproduce
引入antd.min.js antd.min.css 后new Vue({})

### What is expected?
表格正常显示

### What is actually happening?
页面空白 标签解析不了

**Comment by tangjinzhou** [comment]
麻烦给出复现链接

**Comment by vajacn** [comment]
有没有写：Vue.use(antd);

**Comment by nicewahson** [comment]
https://codepen.io/nicelj/pen/VBomZZ
发现table数据没有出来

**Comment by nicewahson** [comment]
好的 放弃了
