### ISSUE TITLE
Select选择器，设置了value值之后，无法正常选择其他选项！

### ISSUE THREAD

**Issue by 594100253** [vueComponent/ant-design-vue#1334]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
ant-design-vue：1.4.3，Vue：6.11.3，浏览器：Chrome：78.03904.70 64位

### Reproduction link
[https://vuecomponent.github.io/issue-helper/?lang=zh#repro-modal](https://vuecomponent.github.io/issue-helper/?lang=zh#repro-modal)

### Steps to reproduce
1

### What is expected?
设置value 属性之后，可以继续操作。

### What is actually happening?
1

---
Select 选择器，动态获取数据，通过value属性设置是否选中，之后就不能再继续操作了（无法选择其他选项，也无法清空）。

**Comment by tangjinzhou** [comment]
v-model="value"
