### ISSUE TITLE
Checkbox多选框能否新增 <a-checkbox-button value="a">Hangzhou</a-checkbox-button>

### ISSUE THREAD

**Issue by 13371911139** [vueComponent/ant-design-vue#1338]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1、可以像radio一样有按钮样式
2、多选按钮更加实用

### What does the proposed API look like?
<a-checkbox-group :options="plainOptions" v-model="checkedList" @change="onChange"  buttonStyle="solid" />
或者;
<a-checkbox-group :options="plainOptions" v-model="checkedList" @change="onChange"  buttonStyle="solid" >
<a-checkbox-button value="a">Hangzhou</a-checkbox-button>
<a-checkbox-button value="b">asdd</a-checkbox-button>
</a-checkbox-group :options="plainOptions" v-model="checkedList" @change="onChange"  buttonStyle="solid" >

**Comment by wangxueliang** [comment]
https://github.com/ant-design/ant-design/issues/16424
