### ISSUE TITLE
SubMenu.vue 模板问题

### ISSUE THREAD

**Issue by DinoRun** [vueComponent/ant-design-vue#1343]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
window

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/menu/demo/SubMenu.vue](https://github.com/vueComponent/ant-design-vue/blob/master/components/menu/demo/SubMenu.vue)

### Steps to reproduce
根据路由使用SubMenu.vue生成顶部菜单，点击父级菜单项，子级菜单会收起（隐藏），而使用SubMenu1.vue生成的菜单则不会有这样的问题，

### What is expected?
点击父级菜单项，子级菜单应该显示，而不是隐藏；

### What is actually happening?
点击父级菜单项，子级列表隐藏，这是不应该的；

**Comment by oraant** [comment]
确实会有这个bug，但是经过仔细测试，如果代码正确的话，这个代码只会使用SubMenu组件时，在移动端出现。
