### ISSUE TITLE
transformFile  in Upload component

### ISSUE THREAD

**Issue by aaalgo** [vueComponent/ant-design-vue#1344]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1. Substantially improve uploading speed when text files are compressed before uploading.  This can be achieved with transformFile.
2. Image processing before uploading.

### What does the proposed API look like?
https://ant.design/components/upload/

**Comment by veking** [comment]
使用 transformFile 添加水印不成功，经测试发现没有调用该方法。
==
"ant-design-vue": "^1.6.4",
![image](https://user-images.githubusercontent.com/10131151/88470525-df00b700-cf2f-11ea-96d2-10cdd8a120be.png)
![image](https://user-images.githubusercontent.com/10131151/88470529-fb045880-cf2f-11ea-83bb-7ffc13026384.png)

**Comment by ManfredHu** [comment]
文档用法有问题啊
