### ISSUE TITLE
运用select组件时，加上v-model默认为空，初始状态placeholder不展示

### ISSUE THREAD

**Issue by huangtingting7** [vueComponent/ant-design-vue#1346]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
1.4.0

### Reproduction link
[https://vue.ant.design/components/select-cn/](https://vue.ant.design/components/select-cn/)

### Steps to reproduce
运用select组件时，加上v-model，默认为null或者空值

### What is expected?
初始状态placeholder展示

### What is actually happening?
初始状态placeholder不展示

![image](https://user-images.githubusercontent.com/34705296/67649581-97370a00-f974-11e9-9b03-ce0fb297549d.png)

![image](https://user-images.githubusercontent.com/34705296/67649610-b9308c80-f974-11e9-9714-10e2c55e3f6c.png)

**Comment by tangjinzhou** [comment]
searchParam.settleNode 赋值为 undefined

**Comment by WuYiZhan** [comment]
用undefined

**Comment by wcg184** [comment]
input 用空字符串 '' 或 "" 或 null
select 用 undefined
date 用 null

在设置 defaultValue 或 initialValue 也是使用上述的赋值
