### ISSUE TITLE
进度条的内容format不支持标签，也没有slot，无法控制文本多行样式（单行可以）

### ISSUE THREAD

**Issue by WuYiZhan** [vueComponent/ant-design-vue#1348]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
浏览器

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
希望可以增加控制进度条文本功能

### What is expected?
希望可以增加控制进度条文本功能

### What is actually happening?
希望可以增加控制进度条文本功能

**Comment by ly12530** [comment]
我试试了试这个功能，没效果。版本 1.4.4

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/progress-cn/#components-progress-demo-custom-text-format

**Comment by ly12530** [comment]
我想要自定义颜色。我把这个例子代码复制过去的  颜色没变化
![image](https://user-images.githubusercontent.com/8308832/68109254-0f796e80-ff25-11e9-9c23-b9cf734688fb.png)
`    <a-progress type="circle" :percent="75">
      <template v-slot:format="percent">
        <span style="color: red">{{percent}}</span>
      </template>
    </a-progress>`

**Comment by tangjinzhou** [comment]
确认版本号 ant-design-vue 需要 1.4.4 ，v-slot需要vue 2.6以上支持 @ly12530

**Comment by ly12530** [comment]
谢谢  解决了。vue版本升级了 就可以了
