### ISSUE TITLE
table column appear bug

### ISSUE THREAD

**Issue by hzyyy** [vueComponent/ant-design-vue#1349]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
windows10， chrome 78, vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-4or3y)

### Steps to reproduce
This problem occurs when there are less than 4 columns
column 少量时，table的显示就会出现此问题
bug 的预览地址：https://4or3y.codesandbox.io/

### What is expected?
解决此问题

### What is actually happening?
table column 发生了bug

**Comment by hzyyy** [comment]
以及这个问题： [图片]

**Comment by hzyyy** [comment]
以及这个问题：
![3E8B~HSIN(`0G89}S{ME5~A](https://user-images.githubusercontent.com/33852158/67733452-5bb24380-fa39-11e9-8312-661a87f4e0e4.png)

**Comment by tangjinzhou** [comment]
留一列不设宽度以适应弹性布局

**Comment by hzyyy** [comment]
> 留一列不设宽度以适应弹性布局

有效，good

**Comment by hzyyy** [comment]
> 留一列不设宽度以适应弹性布局

我尝试了，在chrome 下不给宽度的列会适应弹性布局，但是在火狐浏览器中，由于这一列没有给宽度，会挤在一起。
