### ISSUE TITLE
RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份为同一个月的情况下，下拉列表展示的选中月份和真实选择的月份不一致

### ISSUE THREAD

**Issue by K-T-Lau** [vueComponent/ant-design-vue#135]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
window10和mac os,chrome、Firefox、IE和Safari浏览器环境下、Vue版本为2.5.0

### Reproduction link
[http://tangjinzhou.gitee.io/ant-design-vue/components/date-picker-cn/#components-date-picker-demo-controlled-panels](http://tangjinzhou.gitee.io/ant-design-vue/components/date-picker-cn/#components-date-picker-demo-controlled-panels)

### Steps to reproduce
如同官方示例的链接一致,RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份为同一个月的情况下，我展开下拉面板,下拉面板内的结束月份选择为实际选择的下一个月。例如我起始月份选择九月，结束月份同样选择该年的九月，,面板关闭再展开后,面板上展示的结束月份会被标记为十月

### What is expected?
在选择同一个月的情况下，我期望面板展示的月份和实际选择的月份保持一致

### What is actually happening?
实际上面板展示的结束月份为实际选择月份的下一个月

---
首先表达对贵团队的谢意，为开发者提供如此给力的UI框架。对于此issue，因为是在我自己的开发过程中发现的，私以为月份的RangePicker应该和日期（天）的RangePicker一样，日期（天）的RangePicker可以选择同一天，月份的RangePicker也应该可以选择同一个月。

**Comment by tangjinzhou** [comment]
please update to 1.1.0
