### ISSUE TITLE
wrong tooltip arrow direction

### ISSUE THREAD

**Issue by adjkldd** [vueComponent/ant-design-vue#1354]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
MacOS Mojave 10.14.4, Chrome 77.0.3865.90, Vue 2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-8ndwn?fontsize=14)

### Steps to reproduce
see reproduction link

### What is expected?
arrow points to left

### What is actually happening?
arrow points to right

**Comment by zkwolf** [comment]
For [doc](https://vue.ant.design/components/tooltip/#components-tooltip-demo-adjust-placement-automatically) said tootip will automatically adjust the placement, if you don't want, you can turn autoAdjustOverflow to false

**Comment by adjkldd** [comment]
Actually I need `autoAdjustOverflow`. But after auto adjusted overflow, the arrow points to wrong direction. Please see the reproduction link.
<img width="542" alt="屏幕快照 2019-10-29 下午3 26 46" src="https://user-images.githubusercontent.com/4162413/67746059-aabf9f00-fa60-11e9-9c80-4184547725da.png">

**Comment by tangjinzhou** [comment]
use `placement="right"`

**Comment by adjkldd** [comment]
Actually, I was testing Tooltip component with `autoAdjustOverflow`. But, it seems the arrow not auto adjusted. Below is the element-ui tooltip. It behaves correctly.

https://codesandbox.io/embed/vue-template-pp7t2?fontsize=14

**Comment by adjkldd** [comment]
I updated the reproduction code. Adding an h3 element, the arrow behaves correctly. Removing it, the arrow behaves incorrectly.
