### ISSUE TITLE
级联下拉选择组件增加多选支持 

### ISSUE THREAD

**Issue by jiangxiaoyuboy** [vueComponent/ant-design-vue#1355]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决下拉多选的功能，不用树形控件的原因是，其样式不符合项目需求，而级联的样式符合，所以建议加上级联下拉多选功能，谢谢

### What does the proposed API look like?
建议加上级联下拉多选功能

**Comment by MinMinEr** [comment]
同求
