### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event 

### ISSUE THREAD

**Issue by liudonghua123** [vueComponent/ant-design-vue#1356]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
Win 10 1903, Chrome 78,  vue ^2.6.10

### Reproduction link
[https://github.com/liudonghua123/antd-demo](https://github.com/liudonghua123/antd-demo)

### Steps to reproduce
1. vue create antd-demo
2. vue add ant-design
3. write a component mixed v-decorator and v-model like the following.
```vue
// FormDemo.vue
<template>
  <a-form :form="form">
    <a-form-item
      :label-col="formItemLayout.labelCol"
      :wrapper-col="formItemLayout.wrapperCol"
      label="Name"
    >
      <a-input
        v-decorator="[
          'username',
          { rules: [{ required: true, message: 'Please input your name' }] }
        ]"
        placeholder="Please input your name"
      />
    </a-form-item>
    <a-form-item
      :label-col="formItemLayout.labelCol"
      :wrapper-col="formItemLayout.wrapperCol"
      label="Nickname"
    >
      <a-input
        v-decorator="[
          'nickname',
          {
            rules: [
              { required: checkNick, message: 'Please input your nickname' }
            ]
          }
        ]"
        placeholder="Please input your nickname"
      />
    </a-form-item>
    <a-form-item
      :label-col="formTailLayout.labelCol"
      :wrapper-col="formTailLayout.wrapperCol"
    >
      <a-checkbox v-model="checkNick">
        Nickname is required
      </a-checkbox>
    </a-form-item>
    <a-form-item
      :label-col="formTailLayout.labelCol"
      :wrapper-col="formTailLayout.wrapperCol"
    >
      <a-button type="primary" @click="check">
        Check
      </a-button>
    </a-form-item>
  </a-form>
</template>

<script>
const formItemLayout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 8 }
};
const formTailLayout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 8, offset: 4 }
};
export default {
  data() {
    return {
      checkNick: false,
      formItemLayout,
      formTailLayout,
      form: this.$form.createForm(this, { name: "dynamic_rule" })
    };
  },
  methods: {
    check() {
      this.form.validateFields(err => {
        if (!err) {
          // console.info("success");
        }
      });
    },
  }
};
</script>

```
4. Use the component in App.vue
5. Click the checkbox in the browser page

### What is expected?
No warn or error shown in console

### What is actually happening?
![image](https://user-images.githubusercontent.com/2276718/67751369-f4fa4d80-fa6b-11e9-8fbe-28f9d816b8cf.png)

---
The callback in model is called twice, the first one the value argument was a event object, the the second one with the correct true/false value.

**Comment by sendya** [comment]
no problem
https://codesandbox.io/s/vue-antd-template-3db90

**Comment by liudonghua123** [comment]
Hi @sendya , I understand your answer, the key is change `v-model` to `checked` and `@change`, write the following code
```vue
        <a-checkbox
          :checked="checkNick"
          @change="e => checkNick = e.target.checked"
        >Nickname is required</a-checkbox>
```
instead of
```vue
      <a-checkbox v-model="checkNick">
        Nickname is required
      </a-checkbox>
```

However, that's just another way to skip the `v-model` in `a-checkbox` issue, I can also change `v-model` to `v-decorator` style. It does not fix the possible problem.

**Comment by sendya** [comment]
However,  `v-model` can work. pls review codesandbox demo.

and this is a bug in `vue 2.6.0-beta.1`

liudonghua <notifications@github.com> 于2019年10月30日周三 上午8:21写道：

**Comment by liudonghua123** [comment]
@sendya Hi, I tried you codesanbox example, it's seems ok, but when you download and run locally, you will see the same errors in console.

![image](https://user-images.githubusercontent.com/2276718/67822753-f2dfcf80-fafb-11e9-9cc0-d9c19070c6db.png)

**Comment by liudonghua123** [comment]
I can see the same problem in codesanbox now.
![image](https://user-images.githubusercontent.com/2276718/67823304-7ea62b80-fafd-11e9-9030-c9a3e9ed3678.png)

**Comment by sendya** [comment]
> I can see the same problem in codesanbox now.
> ![image](https://user-images.githubusercontent.com/2276718/67823304-7ea62b80-fafd-11e9-9030-c9a3e9ed3678.png)

**vue version `2.5.22`**

**Comment by sendya** [comment]
v-model $emit `input` is a bug in 2.6.0-beta.1 and latest
----
![image](https://user-images.githubusercontent.com/5404542/67823533-74386180-fafe-11e9-873e-b29ad01650fa.png)

**Comment by liudonghua123** [comment]
It's a bug existed from vue `2.6.0-beta.1` to the latest `2.6.10`?

**Comment by liudonghua123** [comment]
If I change `a-checkbox` to `input type="checkbox"`, this error disappeared.

**Comment by liudonghua123** [comment]
@sendya @tangjinzhou Does this issue fixed?

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/2e9b3000ac2ceea4688114094ce5bc2a7ecd430f  @liudonghua123
