### ISSUE TITLE
a-input输入框在IE11下的问题

### ISSUE THREAD

**Issue by xiaofuliang** [vueComponent/ant-design-vue#1358]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
antd-vue 1.4.3  vue 2.6.10  browser IE 11.0.20

### Reproduction link
[https://github.com/xiaofuliang/antd-demo/blob/master/src/App.vue](https://github.com/xiaofuliang/antd-demo/blob/master/src/App.vue)

### Steps to reproduce
a-input如果设置了placeholder属性并且是设置了validatorRules为required:true，进入当前页面时，会提示required必填的校验
a-input如果加了prefix,suffix，当加了prefix,从上面个Input按tab键切换下来需要按两次，加了suffix从这个Input按tab键切换到下个input需要按两次，（如果没有加，是可以按tab键正常切换到下个输入框的），加了prefix或者suffix任一一项，文本框输入会居中，不是左对齐了

### What is expected?
在IE11 a-input能正常跟chrome 里面一样

### What is actually happening?
在IE11 a-input 不正常

**Comment by Saint9** [comment]
更新到最新的版本1.4.4
```
<a-input
    placeholder="请输入手机号码"
    v-decorator="['note', { rules: [{ required: true, message: 'Please input your note!' }] }]"
  />
```
如果设置了placeholder，进入当前页面时，会提示required必填的校验

**Comment by tangjinzhou** [comment]
@Saint9 请分开提issue 谢谢
