### ISSUE TITLE
avatar组件会卡死chrome浏览器

### ISSUE THREAD

**Issue by liwei26** [vueComponent/ant-design-vue#136]
多个头像组件同时存在时会卡死chrome浏览器，可能也是问题里chrome打不开头像文档的原因

**Comment by tangjinzhou** [comment]
?  文档打不开？

**Comment by liwei26** [comment]
http://tangjinzhou.gitee.io/ant-design-vue/docs/vue/introduce-cn/  这个连接的头像文档，用chrome一直没打开过

**Comment by webees** [comment]
@liwei26 文档打不开，优先检查下本地网络状况，或者换个网嘛。github的服务器有时候确实会打不开。
