### ISSUE TITLE
Tree组件可优化的一个建议

### ISSUE THREAD

**Issue by 980963894** [vueComponent/ant-design-vue#1362]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
win10 Google Chrome@75 Vue@2.6

### Reproduction link
[https://antdv.com/components/tree-cn/](https://antdv.com/components/tree-cn/)

### Steps to reproduce
1. 点击Tree控件子节点在不全选的情况下 无法获取到子节点上面的父级ID

### What is expected?
点击Tree控件子节点在不全选的情况下 可以获取到子节点上面的父级ID

### What is actually happening?
点击Tree控件子节点在不全选的情况下 无法获取到子节点上面的父级ID

**Comment by zkwolf** [comment]
可以用onCheck获取半选的节点，组件直接支持感觉ant-design那边不太想做

**Comment by lizhongyi** [comment]
建议这个组件可以看看 eleme的组件可以 增加删除节点按钮的api

**Comment by lizhongyi** [comment]
组件库使用了 vue 的新特性slot-scope(2.5.0 新增), provide / inject(2.2.0 新增) ,2.6.0 已经废弃，我我说怎么无法生效
