### ISSUE TITLE
Table添加rowClick事件

### ISSUE THREAD

**Issue by yugiohliang** [vueComponent/ant-design-vue#1366]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当用户点击整行的时候，可以触发一些东西（例如弹出详情的窗口）

### What does the proposed API look like?
事件为：rowClick。
参数为：row（当前行的数据）, index（当前行的序号）

```html
<template>
  <a-table
    :columns="columns"
    :dataSource="data"
    @rowClick="handleRowClick"
  >
    ……
  </a-table>
</template>
```

```javascript
<script>
export default {
  ……
  methods: {
    handleRowClick (row, index) {
      console.info('当前点击行的数据', row)
      console.info('当前点击行的序号', index)
    }
  }
  ……
}
</script>
```

**Comment by sendya** [comment]
# customRow 用法
适用于 customRow customHeaderRow customCell customHeaderCell。遵循Vue jsx语法。

```
<Table
  customRow={(record) => {
    return {
      props: {
        xxx... //属性
      },
      on: { // 事件
        click: (event) => {},       // 点击行
        doubleclick: (event) => {},
        contextmenu: (event) => {},
        mouseenter: (event) => {},  // 鼠标移入行
        mouseleave: (event) => {}
      },

    };
  )}
  customHeaderRow={(column) => {
    return {
      on: {
        click: () => {},        // 点击表头行
      }
    };
  )}
/>
```

https://codesandbox.io/s/5k1z1o0zpl

**Comment by yugiohliang** [comment]
> 
> # customRow 用法
> 
> 适用于 customRow customHeaderRow customCell customHeaderCell。遵循Vue jsx语法。
> 
> ```
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx... //属性
>       },
>       on: { // 事件
>         click: (event) => {},       // 点击行
>         doubleclick: (event) => {},
>         contextmenu: (event) => {},
>         mouseenter: (event) => {},  // 鼠标移入行
>         mouseleave: (event) => {}
>       },
> 
>     };
>   )}
>   customHeaderRow={(column) => {
>     return {
>       on: {
>         click: () => {},        // 点击表头行
>       }
>     };
>   )}
> />
> ```
> 
> https://codesandbox.io/s/5k1z1o0zpl


nice

**Comment by KrishnaPG** [comment]
Just for a row click, this is a too complex solution.

**Comment by KrishnaPG** [comment]
Not sure if this is the right way to handle simple clicks, as it will create one function closure for every row. If there are hundreds of rows in the table, then you are essentially creating one `custom row` function closure for every row - too bad on memory.

While abstracting the functionality into simple modules, such as `custom rows` is good, one should also take care of how much additional memory and performance overhead one is adding due to that.

**Comment by jcomey** [comment]
这么基础的一个功能居然没有！！！

**Comment by jcomey** [comment]
单击行选择本行数据！！！

**Comment by incompletude** [comment]
I don't use JSX. Is there a way to achieve this without it?

**Comment by buqiyuan** [comment]
> # customRow 用法
> 适用于 customRow customHeaderRow customCell customHeaderCell。遵循Vue jsx语法。
> 
> ```
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx... //属性
>       },
>       on: { // 事件
>         click: (event) => {},       // 点击行
>         doubleclick: (event) => {},
>         contextmenu: (event) => {},
>         mouseenter: (event) => {},  // 鼠标移入行
>         mouseleave: (event) => {}
>       },
> 
>     };
>   )}
>   customHeaderRow={(column) => {
>     return {
>       on: {
>         click: () => {},        // 点击表头行
>       }
>     };
>   )}
> />
> ```
> 
> https://codesandbox.io/s/5k1z1o0zpl

![image](https://user-images.githubusercontent.com/39730999/91514898-86e81680-e91a-11ea-9dc3-f53e1157dbac.png)
你好，请问2.x后传入事件不生效了吗

**Comment by buqiyuan** [comment]
> # customRow 用法
> 适用于 customRow customHeaderRow customCell customHeaderCell。遵循Vue jsx语法。
> 
> ```
> <Table
>   customRow={(record) => {
>     return {
>       props: {
>         xxx... //属性
>       },
>       on: { // 事件
>         click: (event) => {},       // 点击行
>         doubleclick: (event) => {},
>         contextmenu: (event) => {},
>         mouseenter: (event) => {},  // 鼠标移入行
>         mouseleave: (event) => {}
>       },
> 
>     };
>   )}
>   customHeaderRow={(column) => {
>     return {
>       on: {
>         click: () => {},        // 点击表头行
>       }
>     };
>   )}
> />
> ```
> 
> https://codesandbox.io/s/5k1z1o0zpl

![image](https://user-images.githubusercontent.com/39730999/91515304-75533e80-e91b-11ea-8d4a-1b66f192d5a7.png)
![image](https://user-images.githubusercontent.com/39730999/91515379-9ddb3880-e91b-11ea-89d0-89a67f60b297.png)
