### ISSUE TITLE
Switch disabled state/style

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#137]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Switch 禁用状态样式建议更改为 not-allowed，现在没有反馈。

p.s. 现在使用的是 `pointer-events: none;`.

### What does the proposed API look like?
和现在保持一致。

**Comment by wangxueliang** [comment]
样式目前基本上和antd保持一致，方便升级，谢谢建议

**Comment by tangjinzhou** [comment]
@bq-hentai  如有需要，可自定义样式
