### ISSUE TITLE
关于tree的，动态加载时，图标没有加载出来

### ISSUE THREAD

**Issue by keiluo** [vueComponent/ant-design-vue#138]
https://codesandbox.io/s/lx4wymky37

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/xv72j8n0wq

**Comment by JasonGaoG** [comment]
请问props.dataRef 没有值是什么情况？　我看ａｐｉ里面的ｐｒｏｐｓ没有ｄａｔａＲｅｆ这个熟悉呢
