### ISSUE TITLE
rowSelection设置columnWidth无效

### ISSUE THREAD

**Issue by wangxuseek** [vueComponent/ant-design-vue#1380]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
vue2.0

### Reproduction link
[https://www.antdv.com/components/table-cn/#API](https://www.antdv.com/components/table-cn/#API)

### Steps to reproduce
rowSelection设置columnWidth无效

### What is expected?
可以设置宽度

### What is actually happening?
columnWidth: 34,

**Comment by liufushihai** [comment]
好像需要带上单位，我试了下，px 或者 % 单位有效果。

**Comment by tangjinzhou** [comment]
楼上正解

**Comment by wangxuseek** [comment]
> 楼上正解

设置这个属性有一个最小值，设置比最小值小就不生效？

**Comment by gaorubin1990** [comment]
带上单位也不行，报错Cannot read property 'width' of undefined
