### ISSUE TITLE
Modal custom icon theme

### ISSUE THREAD

**Issue by Zuojiangtao** [vueComponent/ant-design-vue#1386]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
ant-design-vue1.3.9；现代浏览器和 IE9 及以上；vue2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/1385](https://github.com/vueComponent/ant-design-vue/issues/1385)

### Steps to reproduce
1. icon主题更改为'filled';
2.实际上仍然是'outlined'

### What is expected?
Modal自定义图标主题能生效

### What is actually happening?
实际上并未生效

**Comment by Zuojiangtao** [comment]
这是代码：
----
````
      var _this = this
      this.$confirm({
        title: '确定删除该数据吗？',
        content: '删除的数据将无法恢复！',
        centered: true,
        icon: '<Icon type="question-circle" theme="filled">',
        onOk () {
          delIntent({ userId: '2', id: id })
            .then(res => {
              // console.log(res)
              _this.$message.success('删除成功')
              _this.getData()
            })
            .catch(err => {
              console.log(err)
              _this.$message.error('删除失败')
            })
        },
        onCancel () {
        }
      })
````

**Comment by tangjinzhou** [comment]
你这个icon的配置传递的是字符串，并不是 vNode

**Comment by Zuojiangtao** [comment]
> 你这个icon的配置传递的是字符串，并不是 vNode

![image](https://user-images.githubusercontent.com/22252182/68644652-aca15c00-0550-11ea-81d9-f941519a633a.png)

文档上可以传字符串啊

**Comment by sendya** [comment]
> > 你这个icon的配置传递的是字符串，并不是 vNode
> 
> ![image](https://user-images.githubusercontent.com/22252182/68644652-aca15c00-0550-11ea-81d9-f941519a633a.png)
> 
> 文档上可以传字符串啊

字符串是说 'question-circle' 这样的 icon 类型吧？

**Comment by Zuojiangtao** [comment]
> > > 你这个icon的配置传递的是字符串，并不是 vNode
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/22252182/68644652-aca15c00-0550-11ea-81d9-f941519a633a.png)
> > 文档上可以传字符串啊
> 
> 字符串是说 'question-circle' 这样的 icon 类型吧？

我找了一下，是ant-design的问题，看下https://github.com/ant-design/ant-design/issues/13918

**Comment by tangjinzhou** [comment]
```js
icon: '<Icon type="question-circle" theme="filled">'
```
你 这 是 个 字 符 串
