### ISSUE TITLE
IE11下input设置了placeholder，并且设置了required必填的校验，进入当前页面时会提示required的message

### ISSUE THREAD

**Issue by xiaofuliang** [vueComponent/ant-design-vue#1387]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
antd-vue 1.4.4  vue 2.6.10  browser IE 11.0.20

### Reproduction link
[https://github.com/xiaofuliang/antd-demo/blob/master/src/App.vue](https://github.com/xiaofuliang/antd-demo/blob/master/src/App.vue)

### Steps to reproduce
<a-input placeholder="请输入用户账号" v-decorator="[ 'username', {rules: [{required: true,message: '请输入用户账号!'}]}]" />

IE11下 进入页面时，会显示 【请输入用户账号！】红字

### What is expected?
跟其他浏览器一样正常

### What is actually happening?
。

**Comment by freshzxf** [comment]
遇到同样的问题，目前愚昧的处理下方式是：
`
setTimeout(() => {
  this.resetForm()
}, this.$isIe ? 200 : 0)
`
有更好更优雅处理方式的，希望分享下...
