### ISSUE TITLE
标签Tag删除的时候，后一个Tag自动变为display:none

### ISSUE THREAD

**Issue by vivian217** [vueComponent/ant-design-vue#1399]
在新增跟删除标签时发现，删除Tag的时候，删掉了对应的标签，但是后一个相邻的标签自动变为display:none，页面上显示效果为删掉了2个，点击DOM元素查看发现有一个为display:none，请问这个应该怎么解决？
<a-tag v-for="(tag,i) in tags" :key="i" closable:afterClose="()=>delTag(i)">{{tag.name}}</a-tag>

delTag(i){
   this.tags.splice(i,1)
}

**Comment by zkwolf** [comment]
拿tags的key绑定到key上试试？

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-antd-template-d7jc9
