### ISSUE TITLE
card组件不支持:style   动态style属性

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#140]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
windows10  chrome67.0.3396.99  vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q70y07l4xj)

### Steps to reproduce
建立两个a-card组件，设置:style="{marginTop:200}"  无法生效

### What is expected?
style属性可以生效，这个应该是原生就支持的

### What is actually happening?
不生效

**Comment by tangjinzhou** [comment]
:style="{marginTop:'200px'}"
