### ISSUE TITLE
Tabs组件是否能加一个配置项

### ISSUE THREAD

**Issue by 980963894** [vueComponent/ant-design-vue#1402]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在目前的ant Design Pro 模板中 开启了多页签的配置  在关闭页签的时候 并未实现真正意义上的关闭 类似于隐藏  数据都是缓存起来了  能不能在加入一个配置项 开启后 点关闭页签实现真正的关闭  重新打开后 会执行初始化的方法 刷新数据

### What does the proposed API look like?
在关闭页签的时候真正的关闭  重新打开后 会执行初始化的方法 刷新数据

**Comment by sendya** [comment]
你发错 repo 了，这里是 antd vue 组件库
