### ISSUE TITLE
想问下tabs内容滚动的问题 

### ISSUE THREAD

**Issue by flymzero** [vueComponent/ant-design-vue#1404]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用tabs组件，希望对应的tab-pane内的内容能自动滚动，但是现在的效果是tabs一起跟着滚动，冒昧的问下，这个有什么解决方案吗？谢谢

### What does the proposed API look like?
一个参数配置

**Comment by sendya** [comment]
tab-pane 内容去设置 css overflow

**Comment by flymzero** [comment]
我把内容高度设置为固定高度了
eg. {
max-height: calc(100vh - 30px - 30px - 55px);
  overflow-y: auto;
}

**Comment by hejinguo** [comment]
calc 大法好
