### ISSUE TITLE
table表列如何拉伸 

### ISSUE THREAD

**Issue by allenchenx** [vueComponent/ant-design-vue#1405]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
ant design vue 1.3.9

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/1330](https://github.com/vueComponent/ant-design-vue/issues/1330)

### Steps to reproduce
table表列如何拉伸

### What is expected?
table表列如何拉伸

### What is actually happening?
table表列如何拉伸

**Comment by sendya** [comment]
不懂你说的拉伸是什么？列宽拖动？如果是：
https://codesandbox.io/s/vue-antd-template-qrdre

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/table/#components-table-demo-resizable-column
