### ISSUE TITLE
table 表头分组， 表头和表身内容最后一列无法对齐

### ISSUE THREAD

**Issue by roland-luo** [vueComponent/ant-design-vue#1407]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以看官方demo

### What does the proposed API look like?
table组件style index.less
&-fixed-header &-scroll &-header {
overflow: scroll;
padding-bottom: 20px;
//滚动条隐藏
margin-bottom: -20px;
// 固定列时，表头和表身无法对齐
// margin-right: -20px;
// Workaround for additional scroll bar on the table header
// https://github.com/ant-design/ant-design/issues/6515#issuecomment-419634369
opacity: 0.9999;
}

**Comment by qiangyongjun918** [comment]
我也发现了，好奇怪，感觉好多组件都有问题，心累
