### ISSUE TITLE
求助各组件中字符串转Html的函数

### ISSUE THREAD

**Issue by liudaweidavi** [vueComponent/ant-design-vue#1408]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
很多组件的description配置参数中都有这些param： 	string | vueNode |function(h)   。第三个参数是否为html？还是某个工具类转的格式？新手不太会用，翻遍文档也没找到相关的说明内容。原需求就是在各种组件的description或类似配置中配置html格式的超链接等。谢谢解答

### What does the proposed API look like?
很多组件的description配置参数中都有这些param： 	string | vueNode |function(h)   。第三个参数是否为html？还是某个工具类转的格式？新手不太会用，翻遍文档也没找到相关的说明内容。原需求就是在各种组件的description或类似配置中配置html格式的超链接等。谢谢解答

**Comment by sendya** [comment]
https://vuejs.org/v2/guide/render-function.html
