### ISSUE TITLE
Form input not working, when used with vue class components

### ISSUE THREAD

**Issue by Tobjoern** [vueComponent/ant-design-vue#1411]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
Linux Mint 19.1, Chrome Version 77.0.3865.90 (Official Build) (64-bit), ^3.0.1

### Reproduction link
[https://github.com/Tobjoern/antd-input-bug-ts](https://github.com/Tobjoern/antd-input-bug-ts)

### Steps to reproduce
1. Create a typescript vue project with the class component syntax
2. Create a form with via fName = $form.createForm(this)
3. Attach the appropriate markup (for example a simple form with an input)

### What is expected?
One should be able to type in the input(s), but they are immediately reset, when a character is typed.

### What is actually happening?
One is not able to type in the input(s)

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/392
