### ISSUE TITLE
官方示例中「表格-筛选按钮」存在一个问题

### ISSUE THREAD

**Issue by m3ng9i** [vueComponent/ant-design-vue#1412]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
OS: Debian testing bullseye， Google Chrome: 版本 78.0.3904.97

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-customized-filter-panel](https://www.antdv.com/components/table-cn/#components-table-demo-customized-filter-panel)

### Steps to reproduce
在”ant design vue 版本1.4.4，表格-自定义筛选菜单“这一节（<https://www.antdv.com/components/table-cn/#components-table-demo-customized-filter-panel>），存在一个问题：

点击了筛选按钮（放大镜图标），然后输入一个搜索词，然后点击空白位置（没有点击搜索按钮），这时不应该发生筛选行为的，但是实际上已经对表格内容进行了筛选。没有在表格的文档里找到解决的办法，麻烦帮忙解答下这种情况怎么处理可以不自动筛选。

### What is expected?
在表格的筛选控件中输入了文字，点击了空白位置（而不是搜索按钮），不应该进行筛选

### What is actually happening?
在表格的筛选控件中输入了文字，点击了空白位置（而不是搜索按钮），发生了筛选行为

### 操作截图

![filterDropdown](https://user-images.githubusercontent.com/8485214/68726777-7b329a00-05fd-11ea-9e37-a277f2171ab2.gif)

**Comment by sendya** [comment]
```diff
<template>
  <a-table :dataSource="data" :columns="columns">
    <div
      slot="filterDropdown"
      slot-scope="{ setSelectedKeys, selectedKeys, confirm, clearFilters, column }"
      style="padding: 8px"
    >
      <a-input
        v-ant-ref="c => searchInput = c"
        :placeholder="`Search ${column.dataIndex}`"
        :value="selectedKeys[0]"
-        @change="e => setSelectedKeys(e.target.value ? [e.target.value] : [])"
        @pressEnter="() => handleSearch(selectedKeys, confirm)"
        style="width: 188px; margin-bottom: 8px; display: block;"
      />
      <a-button
        type="primary"
        @click="() => handleSearch(selectedKeys, confirm)"
        icon="search"
        size="small"
        style="width: 90px; margin-right: 8px"
        >Search</a-button
      >
      <a-button @click="() => handleReset(clearFilters)" size="small" style="width: 90px"
        >Reset</a-button
      >
    </div>
    ...
```

标红的那一行去掉即可，官方例示是用来演示一些功能点如何实现和使用的。并不一定会是每个人自己心中想象的一致。这种情况请自行进行修改即可

**Comment by m3ng9i** [comment]
> ```diff
> <template>
>   <a-table :dataSource="data" :columns="columns">
>     <div
>       slot="filterDropdown"
>       slot-scope="{ setSelectedKeys, selectedKeys, confirm, clearFilters, column }"
>       style="padding: 8px"
>     >
>       <a-input
>         v-ant-ref="c => searchInput = c"
>         :placeholder="`Search ${column.dataIndex}`"
>         :value="selectedKeys[0]"
> -        @change="e => setSelectedKeys(e.target.value ? [e.target.value] : [])"
>         @pressEnter="() => handleSearch(selectedKeys, confirm)"
>         style="width: 188px; margin-bottom: 8px; display: block;"
>       />
>       <a-button
>         type="primary"
>         @click="() => handleSearch(selectedKeys, confirm)"
>         icon="search"
>         size="small"
>         style="width: 90px; margin-right: 8px"
>         >Search</a-button
>       >
>       <a-button @click="() => handleReset(clearFilters)" size="small" style="width: 90px"
>         >Reset</a-button
>       >
>     </div>
>     ...
> ```
> 
> 标红的那一行去掉即可，官方例示是用来演示一些功能点如何实现和使用的。并不一定会是每个人自己心中想象的一致。这种情况请自行进行修改即可

我试过，去掉标红的行后，输入框无法输入文字了，输入文字时，输入框里面一直保持空白。

**Comment by sendya** [comment]
:value="selectedKeys[0]" 改成 v-model 即可。另外，你这 vue 的基础可能需要加强一下

**Comment by xzj5426** [comment]
> :value="selectedKeys[0]" 改成 v-model 即可。另外，你这 vue 的基础可能需要加强一下

官方示例的非自定义筛选也有这样的问题，我只勾选了筛选条件，未点击确定按钮，点击空白区域，表格也自动执行筛选的方法，有什么办法可以使，点击空白区域不执行筛选，而点击确定按钮才执行呢？
