### ISSUE TITLE
table组件在表格列配置较多出现滚动条时，在无数据的情况下  滚动条消失，无法看到后面的列

### ISSUE THREAD

**Issue by yanghu1015** [vueComponent/ant-design-vue#1414]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
谷歌浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-xdz5p)

### Steps to reproduce
https://codesandbox.io/s/vue-template-xdz5p

### What is expected?
在无数据时，table的横向滚动条也出现

### What is actually happening?
在无数据时，table的横向滚动条消失

**Comment by sendya** [comment]
react antd 有相同现象

**Comment by yanghu1015** [comment]
那可咋玩哟

**Comment by rongxingsun** [comment]
> 
> 
> react antd 有相同现象
这种现像react antd已经修复，antdv有打算修复嘛

**Comment by rongxingsun** [comment]
@sendya

**Comment by DHZHY** [comment]
使用自定义的列筛选功能后，空数据不能显示滚动条；自定义的列筛选功能也不能控制清除。有点难搞哦。

**Comment by iwGit** [comment]
你好，请问这个问题最后怎么解决了呀

**Comment by yanghu1015** [comment]
我没解决，。。。。最后做成无数据的情况下&nbsp; &nbsp;表头出现滚动条，很low




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "iwGit"<notifications@github.com&gt;; 
发送时间: 2020年11月10日(星期二) 晚上6:50
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "只为一人ゝ"<664209463@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] table组件在表格列配置较多出现滚动条时，在无数据的情况下  滚动条消失，无法看到后面的列 (#1414)





 
你好，请问这个问题最后怎么解决了呀

**Comment by arika163** [comment]
遇到了同样的问题，官方有计划解决一下吗？

**Comment by arika163** [comment]
各位大大，可以请教下最后的解决方案吗？

我尝试通过js去让滚动条出现，但是没有数据的时候似乎有定时器在运行，每间隔5秒会把滚动条重新拉回最左侧。这个bug在我们平台上带来了很严重的使用问题，不知道有没有可行方案？不在乎是否优雅，能work就可以了。

@sendya @tangjinzhou @yanghu1015 烦请各位大大指点一二
