### ISSUE TITLE
formItem的高度由于class ant-form-item-control设置的line-height导致大于input组件的实际高度

### ISSUE THREAD

**Issue by see311** [vueComponent/ant-design-vue#1418]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
chrome 78

### Reproduction link
[https://www.antdv.com/components/form-cn/#components-form-demo-coordinated-controls](https://www.antdv.com/components/form-cn/#components-form-demo-coordinated-controls)

### Steps to reproduce
官方网站的form例子就是这样的。
```css
.ant-form-item-control {
position: relative;
line-height: 40px;
zoom: 1;
}
```
而内部的input.ant-input实际高度也就32px

### What is expected?
.ant-form-item-control 的`line-height`与内部组件高度一致

### What is actually happening?
由于form-item的高度与其他default size的组件不一致，导致动态渲染的时候出现抖动
临时解决方法就是覆盖.ant-form-item-control的样式

**Comment by sendya** [comment]
form-item 的高度需要占用一个表单校验错误提示的高度

**Comment by see311** [comment]
@sendya 

> form-item 的高度需要占用一个表单校验错误提示的高度

![image](https://user-images.githubusercontent.com/22143374/68843812-b3bc9b80-0703-11ea-963f-14cd49db46a5.png)
但是这样的话就对不齐了

**Comment by sendya** [comment]
> @sendya
> 
> > form-item 的高度需要占用一个表单校验错误提示的高度
> 
> ![image](https://user-images.githubusercontent.com/22143374/68843812-b3bc9b80-0703-11ea-963f-14cd49db46a5.png)
> 但是这样的话就对不齐了

手动调整一下就好了，本来不在同一列上就有可能出现这种问题
