### ISSUE TITLE
为什么ts描述文件里面Input下的密码叫Passward

### ISSUE THREAD

**Issue by yeli19950109** [vueComponent/ant-design-vue#1424]
Version
1.4.4

Environment
typescript 3.7.2

Reproduction link
https://github.com/vueComponent/ant-design-vue

Steps to reproduce
import { Input } from 'ant-design-vue' @Component({ components: { AInputPassword: Input.Password, } }) export default class HomePage extends Vue {}

What is expected?
为什么ts描述文件里面Input下的密码叫Passward

What is actually happening?
为什么ts描述文件里面Input下的密码叫Passward

**Comment by tangjinzhou** [comment]
手滑了吧  尴尬
