### ISSUE TITLE
Cascader 级联搜索时不能输入空格

### ISSUE THREAD

**Issue by yurizhang** [vueComponent/ant-design-vue#1427]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
1.4.4

### Reproduction link
[https://www.antdv.com/components/cascader-cn/#components-cascader-demo-search](https://www.antdv.com/components/cascader-cn/#components-cascader-demo-search)

### Steps to reproduce
Cascader 级联搜索时不能输入空格,只要一输入空格就会把之间的输入内容清空

### What is expected?
允许输入空格， 比如 Jiang su

### What is actually happening?
Cascader 级联搜索时不能输入空格

**Comment by zkwolf** [comment]
指的是空格会触发滚动条？
