### ISSUE TITLE
ant-design-vue/lib/locale-provider/zh_CN 不支持ts

### ISSUE THREAD

**Issue by wenfangcao** [vueComponent/ant-design-vue#1428]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?

Could not find a declaration file for module 'ant-design-vue/lib/locale-provider/zh_CN'.
Try `npm install @types/ant-design-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'ant-desig
n-vue/lib/locale-provider/zh_CN';`

### What does the proposed API look like?
vue cli 3.0   typescript

**Comment by tangjinzhou** [comment]
可以先自行添加
```js
interface zhCN {
  [key: string]: any
}
declare module 'ant-design-vue/lib/locale-provider/zh_CN' {
  import zh from 'ant-design-vue/lib/locale-provider/zh_CN'
  const zh_CN: zhCN

  export default zh_CN
}
```
