### ISSUE TITLE
AutoComplete手动删除输入内容时无法删除最后的一个字符

### ISSUE THREAD

**Issue by peiili** [vueComponent/ant-design-vue#1429]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
win10,Firefox70.0.1;Chrome74.03

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn/](https://www.antdv.com/components/auto-complete-cn/)

### Steps to reproduce
在组件输入框输入值，因输入错误的时候没有点delete Icon，想手动将字符逐个删除。无法删除最后一个字符

### What is expected?
能够将输入框内容完全删除

### What is actually happening?
无法删除最后一个字符

---
偶发现象

**Comment by mx4g** [comment]
真的无法删除最后一个字符，太诡异了，怎么解决呢

**Comment by tangjinzhou** [comment]
update to 1.4.6
