### ISSUE TITLE
Carousel 走马灯

### ISSUE THREAD

**Issue by little3201** [vueComponent/ant-design-vue#1430]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
走马灯做全屏播放时，根据浏览器自动设置高度，无法设置，因为穿透原因，无法给邦定参数

### What does the proposed API look like?
走马灯

**Comment by little3201** [comment]
另外，如何设置不循环轮播

**Comment by xrkffgg** [comment]
默认就是不自动播放。
全屏高度可以用 css 设置 100vh
