### ISSUE TITLE
Table 组件文档的 change 事件回调参数说明不全

### ISSUE THREAD

**Issue by EmiyaYang** [vueComponent/ant-design-vue#1432]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
table 组件的 change 事件的回调函数参数不全。遗漏了最后一个也是最核心的包含变更后 dataSource 的参数对象，具体调用时可以打印出来，希望文档能补充完整，让使用者少走一些弯路。

[遗漏文档地址](https://www.antdv.com/components/table-cn/#%E4%BA%8B%E4%BB%B6)

![](https://img-blog.csdnimg.cn/20191119024315419.png)

### What does the proposed API look like?

**希望补充**： change ----> Function(pagination, filters, sorter, { currentDataSource })

**Comment by EmiyaYang** [comment]
@tangjinzhou handleChange事件有立即触发的方法吗？我这边希望能能拿到默认排序或筛选过后的数据。

**Comment by tangjinzhou** [comment]
欢迎pr 补充文档，
立即触发？不需要啊，数据驱动，理论上默认值都是你自己设置的

**Comment by EmiyaYang** [comment]
@tangjinzhou 感谢回复，稍后提 PR。
可能我的问题没有描述清楚。具体一点，如果对表格组件的 columns 数组项设置了 defaultSortOrder ，要怎么做才能拿到排序后的 dataSource？
