### ISSUE TITLE
使用主题定制时,将main.js中引入的css改为less后报错

### ISSUE THREAD

**Issue by Yhmonkey** [vueComponent/ant-design-vue#1434]
使用vue-cli2.x创建项目后,使用主题定制,按照官方文档报错:
Failed to compile with 1 errors                                                                         09:55:04

This dependency was not found:

* ant-design-vue/dist/antd.less in ./src/main.js
To install it, you can run: npm install --save ant-design-vue/dist/antd.less

下面是我的项目配置:
less:
 {
        test: /\.less$/,
        loader: "style-loader!css-loader!less-loader",
 },
main.js:

import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.less';
Vue.use(Antd);

package.json:
 "ant-design-vue": "^1.4.5",
    "less": "^2.7.2",
    "less-loader": "^4.1.0",
    "vue": "^2.5.2",

utils.js:
 less: generateLoaders('less',{
      modifyVars: {
          'primary-color': '#000',
          'link-color': '#1DA57A',
          'border-radius-base': '2px',
      },
      javascriptEnabled: true,
    }),

**Comment by tyf221578** [comment]
遇到了同样的问题，请问你解决了吗？如何解决的？
