### ISSUE TITLE
When Select is in multiple mode and already select option is disabled then selected option can't be removed from selected pills, remove icon doesn't show for pill with having option disabled.

### ISSUE THREAD

**Issue by sagarrabadiya** [vueComponent/ant-design-vue#1435]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
All Environments and all versions

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-1moyq)

### Steps to reproduce
Have select component having mode as multiple and set some value already selected and make some of those value's option as disabled, and you will see that disabled and already selected options can't be removed from selected list.

### What is expected?
The already selected options having disabled should be removable from already selected list, it shouldn't be removable only if the entire select is disabled instead of only some options.

### What is actually happening?
It doesn't allow to remove already selected value if the single option is disabled even if the entire select is not disabled.

**Comment by tangjinzhou** [comment]
you should filter disable value

**Comment by sagarrabadiya** [comment]
no if i filter disabled option then it doesn't show in selected list as well i need to show disabled value if its already selected but it also can be removed from selected values but can not be added again after its unselected.
