### ISSUE TITLE
autocomplete gets focus on second tab key

### ISSUE THREAD

**Issue by MatGhp** [vueComponent/ant-design-vue#1438]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
Chrome

### Reproduction link
[https://ibb.co/9wd7JRx](https://ibb.co/9wd7JRx)

### Steps to reproduce
https://ibb.co/9wd7JRx

### What is expected?
Remove tabindex="0" from outer div of autocomplete or set it to -1.

### What is actually happening?
Focus needs two time tab keys
Setting tabindex in div tag makes the div focusable and focusing input element inside the autocomplete component needs 2 times tab key.

**Comment by haivp3010** [comment]
A workaround would be setting `tabindex="-1"` on the `a-auto-complete` tag. But I think it would be better to make this default for the autocomplete component to avoid confusion
