### ISSUE TITLE
tab组件size属性的问题

### ISSUE THREAD

**Issue by artiely** [vueComponent/ant-design-vue#144]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
任何环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9qmo6mnnpw)

### Steps to reproduce
https://codesandbox.io/s/9qmo6mnnpw

### What is expected?
tab组件包含tab组件的时候，外层tab组件size为large时里面的可以为small，但是外层tab的size为small时里面的tab的size也为small且设置为large无效，这样似乎不合理

### What is actually happening?
tab组件包含tab组件的时候，外层tab组件size为large时里面的可以为small，但是外层tab的size为small时里面的tab的size也为small且设置为large无效，这样似乎不合理

**Comment by tangjinzhou** [comment]
这是css权重计算问题，后续会优化

**Comment by tangjinzhou** [comment]
please update to 1.1.0
