### ISSUE TITLE
collapse不能动态按需展开

### ISSUE THREAD

**Issue by hopechans** [vueComponent/ant-design-vue#1441]
### Version
1.4.1

### Environment
win10
chrome 78.0.3904.97（正式版本） （64 位）

### Reproduction link
nothing

### Steps to reproduce
一个简单的demo，一个静态的collapse，一个动态的collapse（for循环出来的）
1秒后动态设置activeKey=1，结果只有静态的collapse panel展开了。

![GIF](https://user-images.githubusercontent.com/16111288/69204599-4e90fc00-0b82-11ea-89b0-6ed51f9a1b6f.gif)

![微信截图_20191120104218](https://user-images.githubusercontent.com/16111288/69204689-a7609480-0b82-11ea-8bf7-2ff8e03f70af.png)

### What is expected?
希望两个collapse都能展开

### What is actually happening?
collapse不能动态按需展开

**Comment by sendya** [comment]
文本 1 和 数字(Number) 1 不是同一个值 也不是同一个类型，所以无法识别绑定
必要自行确认好值类型

**Comment by hopechans** [comment]
非常感谢，问题解决了。
