### ISSUE TITLE
treeselect 搜索问题

### ISSUE THREAD

**Issue by aleiliuwei** [vueComponent/ant-design-vue#1443]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
1.4.5

### Reproduction link
[https://www.antdv.com/components/tree-select-cn/](https://www.antdv.com/components/tree-select-cn/)

### Steps to reproduce
treeselect设置showsearch，无法搜索中文，另外英文的话貌似只能搜索非叶子节点

### What is expected?
treeselect设置showsearch支持中文

### What is actually happening?
treeselect设置showsearch支持中文

---
treeselect 的showsearch有bug，1.不支持中文，2 不支持叶子节点的搜索

**Comment by tangjinzhou** [comment]
没能复现

**Comment by aleiliuwei** [comment]
https://www.antdv.com/components/tree-select-cn/


a-tree-select
另外还有两个小问题，不知道能给解答下吗？
1.就是a-tree-select 如果是带复选框的是否也支持showSearch属性，目前的需求是需要搜索（单选，复选），我这中文确实不能搜索，看了下官网的例子也不可以搜子节点。
2. 我想修改下disable的背景色，能否给个建议在哪里找



aleiliuwei@163.com
 
发件人： tangjinzhou
发送时间： 2019-11-20 16:14
收件人： vueComponent/ant-design-vue
抄送： aleiliuwei; Author
主题： Re: [vueComponent/ant-design-vue] treeselect 搜索问题 (#1443)
没能复现

**Comment by tangjinzhou** [comment]
基于 https://codesandbox.io/s/2wpk21kzvr 给出复现demo吧  确实复现不了

**Comment by tangjinzhou** [comment]
<img width="418" alt="屏幕快照 2019-11-20 下午9 30 40" src="https://user-images.githubusercontent.com/6937879/69243012-11a62300-0bdd-11ea-8ecc-c89e3790d56e.png">

**Comment by aleiliuwei** [comment]
我知道了默认搜索的是value，我想应该默认搜索title，你输入的是leaf，正常的话用户一般会搜索title（my  leaf）



aleiliuwei@163.com
 
发件人： tangjinzhou
发送时间： 2019-11-20 21:31
收件人： vueComponent/ant-design-vue
抄送： aleiliuwei; Author
主题： Re: [vueComponent/ant-design-vue] treeselect 搜索问题 (#1443)
