### ISSUE TITLE
select组件在mode="tags"下设置:open="false"时，回车无效，只有失去焦点时才有效

### ISSUE THREAD

**Issue by tianxing0923** [vueComponent/ant-design-vue#1444]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
Windows 7 专业版，Chrome 78.0.3904.97（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vgzu0)

### Steps to reproduce
1. 页面加入select组件，设置mode为tags
2. 修改其中一个open属性为false

### What is expected?
设置:open="false"时，回车生效

### What is actually happening?
设置:open="false"时，回车无效

**Comment by tangjinzhou** [comment]
这是什么需求，好诡异
建议使用tag组件，如果一定要使用select，可以通过样式把弹窗隐藏掉

**Comment by glxe** [comment]
我也想要这个需求，但是不太想通过样式隐藏
