### ISSUE TITLE
Menu 导航菜单使用单文件方式递归生成菜单报错

### ISSUE THREAD

**Issue by nightmaring** [vueComponent/ant-design-vue#1450]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
操作系统：macOS10.13.6       
浏览器：Google Chrome（78.0.3904.97） 
Vue:2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-l5zhr)

### Steps to reproduce
打开二级菜单和点击二级菜单项时报错，之前使用1.3.8没问题

### What is expected?
不报错

### What is actually happening?
[Vue warn]: Error in v-on handler: "TypeError: Cannot read property '_normalized' of undefined"

**Comment by tangjinzhou** [comment]
先使用如下代码临时解决：
```js
handleClick(item) {
    if(item.key){
      this.$router.push(item.key);
    }
},
```
