### ISSUE TITLE
使用单文件递归渲染menu，只能渲染2级数据，一旦超过2级数据就会报TypeError: Cannot read property 'propsData' of undefined

### ISSUE THREAD

**Issue by qifengwangye** [vueComponent/ant-design-vue#1452]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.4

### Environment
chrome 77, vue 2.6.10

### Reproduction link
[https://segmentfault.com/q/1010000021072238](https://segmentfault.com/q/1010000021072238)

### Steps to reproduce
https://segmentfault.com/q/1010000021072238

### What is expected?
能正常渲染

### What is actually happening?
使用单文件递归渲染menu，只能渲染2级数据，一旦超过2级数据就会报TypeError: Cannot read property 'propsData' of undefined

**Comment by sendya** [comment]
请使用第一种 demo 方式，并且 第一种方式也标注了 推荐
