### ISSUE TITLE
a-select  使用中文输入法输入英文显示不全

### ISSUE THREAD

**Issue by 15822115472** [vueComponent/ant-design-vue#1458]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.6

### Environment
windows10   Google Chrome 版本 76.0.3809.132   vue3

### Reproduction link
[https://github.com/15822115472/wp.git](https://github.com/15822115472/wp.git)

### Steps to reproduce
<template>
<div class="upload">
<div style="margin-top: 20px;margin-left: 20px;">
测试搜索框
<a-select
mode="multiple"
labelInValue
:value="value"
placeholder="使用中文输入法输入英文显示不全"
style="width:200px"
:filterOption="false"
@search="fetchUser"
@change="handleChange"
:notFoundContent="fetching ? undefined : null"
@input="inputKeydownData"
>
<a-spin v-if="fetching" slot="notFoundContent" size="small" />
<a-select-option v-for="d in data" :key="d.value">{{
d.text
}}</a-select-option>
</a-select>
</div>
</div>
</template>
<script>
// import jsonp from 'fetch-jsonp';

export default {
data() {
this.lastFetchId = 0;
// this.fetchUser = debounce(this.fetchUser, 800);
return {
data: [],
value: [],
fetching: false
};
},
methods: {
inputKeydownData(val) {
console.log(val);
},
fetchUser(value) {
console.log("fetching user", value);
this.lastFetchId  = 1;
const fetchId = this.lastFetchId;
this.data = [];
this.fetching = true;
fetch("https://randomuser.me/api/?results=5")
.then(response => response.json())
.then(body => {
if (fetchId !== this.lastFetchId) {
// for fetch callback order
return;
}
const data = body.results.map(user => ({
text: `${user.name.first} ${user.name.last}`,
value: user.login.username
}));
this.data = data;
this.fetching = false;
});
},
handleChange(value) {
console.log("变化", value);
Object.assign(this, {
value,
data: [],
fetching: false
});
}
},
mounted() {
console.log("测试搜索框");
}
};
</script>

### What is expected?
a-select  使用中文输入法输入英文显示和直接使用英文效果一样

### What is actually happening?
a-select  使用中文输入法输入英文显示不全

---
大家好，有一个问题请教一下大家，在ui框架官网上（vue版本），a-select组件中（搜索用户），在使用中文输入法输入的时候会出现问题（输入项显示不全），令人费解的是此bug在本地开发的时候并不会出现，但是在（https://www.antdv.com/components/select-cn/）组件官网上和吗，已经上线的项目（域名访问）上会出现这个bug。
希望得到指导。

**Comment by zkwolf** [comment]
同时存在中文输入法输入时，placeholder不会消失

**Comment by tangjinzhou** [comment]
做了个中文输入没完成前不触发 change 的回调 尴尬😅

**Comment by tangjinzhou** [comment]
@15822115472 
临时解决方案
```css
.ant-select-selection--multiple .ant-select-search--inline .ant-select-search__field {
  width: 100% !important;
}
```

**Comment by 15822115472** [comment]
感谢您的回复：
&nbsp; &nbsp; &nbsp;Ant Design of vue
我们近期项目使了用这套强大的ui库，也荣幸的为&nbsp; Ant Design of vue的建设出一份力，希望 Ant Design of vue可以越来越完善。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tangjinzhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 晚上6:27
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"鲲鹏万里"<2955711728@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] a-select  使用中文输入法输入英文显示不全 (#1458)




做了个中文输入没完成前不触发 change 的回调 尴尬😅
