### ISSUE TITLE
Label栅格样式小屏时被覆盖，显示宽度100%

### ISSUE THREAD

**Issue by ideshun** [vueComponent/ant-design-vue#1459]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.6

### Environment
Windows 10 1909、Chrome 78.0.3904.108、Vue 3.11.0

### Reproduction link
[https://bd9ok.csb.app/](https://bd9ok.csb.app/)

### Steps to reproduce
Form Label 组件，horizontal模式，小屏状态显示宽度100%。

### What is expected?
horizontal模式左右显示，而不是label和input各占一行。

### What is actually happening?
.ant-form-item-label, .ant-form-item-control-wrapper 将 .ant-col-18 样式覆盖了。
@media (max-width: 575px)
.ant-form-item-label, .ant-form-item-control-wrapper {
display: block;
width: 100%;
}

.ant-col-18 {
display: block;
-webkit-box-sizing: border-box;
box-sizing: border-box;
width: 75%;
}

**Comment by MuBeiSAMA** [comment]
解决了吗

**Comment by MuBeiSAMA** [comment]
vue.config.js:
```js
module.exports = {
  css: { loaderOptions: { less: { modifyVars: { 'screen-sm': '1px' }, javascriptEnabled: true } } }
}
```

**Comment by Yaob1990** [comment]
> vue.config.js:
> 
> module.exports = {
>   css: { loaderOptions: { less: { modifyVars: { 'screen-sm': '1px' }, javascriptEnabled: true } } }
> }
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

和这个没啥关系吧，我试了，没啥用啊
