### ISSUE TITLE
$confirm中的content传入子组件时，子组件无法访问$store

### ISSUE THREAD

**Issue by 521707** [vueComponent/ant-design-vue#1464]
Reproduction link
谷歌

Steps to reproduce
引入的子组件均不可用访问。

What is expected?
在子组件中能正常访问$store

What is actually happening?

1
2

this.$confirm({
title: '增加员工',
content: , //此处的this中不存在$store
width: 650,
onOk() {
console.log('ok')
}
})

**Comment by cooperGao** [comment]
this指向问题
