### ISSUE TITLE
1.4.6 中的table组件BUG

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#1465]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.6

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### Reproduction link
暂无

### Steps to reproduce
因为之前用的都是1.3.x 的版本，升级之后发现样式和体验上有写问题。
问题1：
在全局配置下：
![image](https://user-images.githubusercontent.com/2329528/69536670-61a82f80-0fb9-11ea-948d-a5b1ea0607f6.png)

过滤在没有数据的时候默认被渲染为父级，所以层级错误。如图
![image](https://user-images.githubusercontent.com/2329528/69535246-7a631600-0fb6-11ea-92a0-0f3bcb785133.png)
这个下拉貌似没有配置选项。

问题2：
table的 loading的参数在1.4.x似乎没有体现效果，
表现为1：
先显示empty的空组建，然后在显示数据，没有过度。
表现2：
服务器筛选列表时，我设置了loading，同样看不到效果。

换回1.3.x没有这个问题

**Comment by wangxueliang** [comment]
问题1：ref https://github.com/ant-design/ant-design/issues/16882
问题2： 未复现，请提供最小复现链接

**Comment by wangxueliang** [comment]
loading效果demo  https://codesandbox.io/s/vue-antd-template-uob5t

**Comment by GlodenBoy** [comment]
> loading效果demo https://codesandbox.io/s/vue-antd-template-uob5t

多谢xueliang哥，问题1在table上覆盖全局配置解决，问题2经查明是写法的问题，只是不明白为什么在1.3.x版本没有出问题。
