### ISSUE TITLE
Column and header alignment breaks with fixed header (scroll.y)

### ISSUE THREAD

**Issue by funkindy** [vueComponent/ant-design-vue#1469]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.7

### Environment
Windows 10, Chrome 78, Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-pgptz)

### Steps to reproduce
1) Put the a-table to the component
2) set scroll.y to 'auto' or any other number

### What is expected?
Expecting the table header widths aligned with the column widths, as well as the working y scroll.

### What is actually happening?
Table header widths break in unpredictable manner:
![image](https://user-images.githubusercontent.com/17568549/69706353-58ce6f80-1119-11ea-8fe6-86e3813ab177.png)

---
"Playing" with column`s widths doesnt help. (Ive tried to left 1 ore more columns without withds set but doesnt help)

**Comment by leslieeilsel** [comment]
Specify the width of columns if header and cell do not align properly.

**Comment by funkindy** [comment]
@leslieeilsel I've mentioned in the issue that playing with column`s widths doesnt help unfortunately.

**Comment by leslieeilsel** [comment]
> @leslieeilsel I've mentioned in the issue that playing with column`s widths doesnt help unfortunately.
like this？
![](https://raw.githubusercontent.com/leslieeilsel/Pictures/master/images/20191210164356.jpg)

**Comment by funkindy** [comment]
@leslieeilsel Thanks. That helped. Ive did exactly the same thing but with lower values, e.g. 150/75. Now i see how it works, thanks. Looks like table header doesnt support overflow.
