### ISSUE TITLE
局部导入 Table 组件 Template 风格不显示列标题

### ISSUE THREAD

**Issue by fingnet** [vueComponent/ant-design-vue#147]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
所有环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5x1y629n4l)

### Steps to reproduce
https://codesandbox.io/s/5x1y629n4l

### What is expected?
列头已渲染，列标题为空。

### What is actually happening?
正确显示列标题

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/z3zxzzy4px

**Comment by tangjinzhou** [comment]
模板语法的使用方式可参考[demo](https://vuecomponent.github.io/ant-design-vue/components/table-cn/#components-table-demo-template-style-api)
