### ISSUE TITLE
1.4.7 的 menu click 事件不执行

### ISSUE THREAD

**Issue by xuekai-china** [vueComponent/ant-design-vue#1470]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.7

### Environment
mac10.15.1、谷歌最新、vue2.6.10

### Reproduction link
[http://www.xwbuilders.com:9018/soonspacejs/Demo/#/](http://www.xwbuilders.com:9018/soonspacejs/Demo/#/)

### Steps to reproduce
重现链接里的菜单本来是路由， 现在点不了

### What is expected?
请修复下，谢谢！

### What is actually happening?
menu-item 的 key 绑定了 router.path 来跳转路由， 上午还是好的，晚上更新 node_modules 后 menu 不能点击了。

---
我很确定是1.4.7的版本问题，因为我把本地的版本固定  "ant-design-vue": "1.4.5" 就是好的，而且我在更新记录里看到八小时前的更新版本里记录有修改 menu click 事件。如果需要我的项目最小源代码请留言，谢谢

**Comment by humour-picasso** [comment]
We also encountered the same problem. It was normal yesterday morning. I came back this morning and found that the menu cannot be opened.

**Comment by yurizhang** [comment]
第一层菜单 是OK的, 只要是用submenu菜单就都不可以!

我们是正式项目里使用,坑大了~

**Comment by tangjinzhou** [comment]
很抱歉，已经发布修复，可以升级 1.4.8 ，感谢反馈
