### ISSUE TITLE
Table use FIXED height (表格固定高度)

### ISSUE THREAD

**Issue by a272121742** [vueComponent/ant-design-vue#1471]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
很多情况下，表格在加载过程中，从会很小的矩形变化成大矩形再显示数据。又或者是`pageSize`为10的时候，最后一页只有2条数据时，表格会收缩成小矩形。我觉得表格可以增加一个固定高度的配置，这个配置会根据表格行（rows）来计算高度，无论你是用了`size="middle"`或者`size="small"`，都能固定显示`pageSize`所定义的行数。这样，不会因为数据量不够或者处于第一次加载时，表格忽高忽低，页面元素出现跳动。

### What does the proposed API look like?

```javascript
props: {
  fixed: {
    type: [Boolean, Number],
    default: false
  }
}
```

如果`fixed`为Boolean，自动计算fixed高度，例如：预计显示10行，但只有2行数据时，补齐8行。无论`size`配置何属性都会自动计算。

如果`fixed`为Number，则表示采用开发者定义的高度进行固定高度填充，例如，`:fixed="55"`，则表格行的总高度就是`pageSize * fixed`。

**Comment by sendya** [comment]
你可以尝试给表格父元素设置固定高度

**Comment by a272121742** [comment]
@sendya  但如果改变`pageSize`，或者改变了不同表格`size`，固定高度不就诟病了吗？

**Comment by tangjinzhou** [comment]
改变pagesize是同步改动 height 就可以了呀 

如果自动计算，每一行的高度并不知道，也会有新的问题
