### ISSUE TITLE
notification 的 message 是用 vueNode （直接写的div） 在其中使用img 的时候网络图片无法显示 但是我使用background-image可以显示本地图片

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#1474]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.7

### Environment
chrome最新版

### Reproduction link
[http://www.baidu.com/not-have-minimal](http://www.baidu.com/not-have-minimal)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/20763416/69787359-55111a80-11f7-11ea-9326-0cf4626a8d7a.png)

notification.warning({
message: '区域入侵'   '(2019 3yue 8 ri 14: 22: 35)',
description: <div class="not-wrap">
<div class="not-item-left">
<div class="nil-con">我是很长很长的标题1</div>
<div class="nil-con">我是很长很长的标题222222222</div>
</div>
<div class="not-item-right">
<img class="nir-img" scr="http://222.222.78.169:6027/image/pic?=d84i662e*6eei=t6-2m9d58--c7adf44ac8485icb1*=6d3i2s1*=idp9*=pd*88i0454es=-27z57cd5"/>
</div>
</div>
})

### What is expected?
如何可以在notification中的message中显示一张网络图片

### What is actually happening?
目前无法显示，仅仅可以显示background-imgage: '本地图片', background-imgage: '网络图片'  也是不可以的

**Comment by zkwolf** [comment]
你这src都没写对吧

**Comment by sendya** [comment]
scr 还行

**Comment by hugselina2019** [comment]
啊啊啊啊啊啊， 做项目做傻了
