### ISSUE TITLE
 v-decorator 不识别具名插槽里的组件，这是个BUG还是特性呢？

### ISSUE THREAD

**Issue by sjlei** [vueComponent/ant-design-vue#1480]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
Windows10、Chrome78.0.3904.108（正式版本） （64 位）、Vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v-decoratorjumingchacao-xrjnk)

### Steps to reproduce
见重现链接和截图

### What is expected?
在具名插槽里可以使用 v-decorator

### What is actually happening?
在具名插槽里 v-decorator 不识别组件

---

![image](https://user-images.githubusercontent.com/34293221/69847365-da590580-12b1-11ea-8f35-67d34fbf174d.png)
![image](https://user-images.githubusercontent.com/34293221/69847384-eb097b80-12b1-11ea-9cc5-1eac070a4f11.png)

**Comment by lizhongyi** [comment]
可能是VUE版本？我发现我的vue版本是2.6所以很多不兼容

**Comment by tangjinzhou** [comment]
form-item 和 v-decorator 之间不能跨作用域
可以用如下方式
```html
<comp-b>
      <template v-slot:test>
        <a-form-item label="用户名字">
          <a-input
            placeholder="请输入用户昵称"
            v-decorator="[ 'nickname',{rules: [{ required: true, message: '请输入用户昵称!' }]}]"
          />
        </a-form-item>
      </template>
    </comp-b>
```

**Comment by sjlei** [comment]
好吧，了解，谢谢~

**Comment by sjlei** [comment]
@tangjinzhou 但还是有问题，form还是识别不了，无论是取值还是赋值，都没有 nickname 这个字段，，不过既然不能跨作用域用，，那我就不这样写了，换种方式先解决了

**Comment by uniquejava** [comment]
解决了吗。 想把form-item中的子组件抽出成一个公共组件。 在公共组件中使用v-decorator不起作用了。

**Comment by hzyyy** [comment]
+ 1

**Comment by hzyyy** [comment]
我也有相同的需求；把formItem下的控件封装成一个公共组件。
