### ISSUE TITLE
a-input-password 组件无法使用foucs方法

### ISSUE THREAD

**Issue by GitHub-Leon** [vueComponent/ant-design-vue#1485]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
能够解决在输入错误验证后，快速聚焦，让用户能够快速二次录入

### What does the proposed API look like?
希望能如 a-input 组件那样，通过refs使用focus方法；
e.g：this.$refs.username.focus();

**Comment by wangxueliang** [comment]
https://codesandbox.io/s/vue-antd-template-uob5t

**Comment by dingdingtop** [comment]
同问，好像之前的是可以的，升级版本后就不起作用了
