### ISSUE TITLE
Access to column properties in column's customRender method

### ISSUE THREAD

**Issue by StenvL** [vueComponent/ant-design-vue#1487]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I'm implementing custom table component based on ant-design-vue table and want to create a common logic for grouping row in a table. The grouping header row looks like just a cell with a width equals to width of a table. I try achieve this effect by setting column customRender colspan property to value, equals to count of table columns, and other table columns colspan property setting to 0.

Also I have defined column render rules using scoped slots with the name of each column's dataIndex. So, the rule to render each columns content sounds like "if the record has property name "children" (or anything else defined in childrenColumnName prop in table), then render cell for group row, else render cell as it defined in scoped slot".

To achieve this effect I wrote this column.customRender callback:

```javascript
groupRowOtherCellRender(value, record, rowIndex) {
  if (record.children) {
    return {
      children: null,
      attrs: {
        colSpan: 0
      }
    };
  }

  // Don't know if it's correct to use that feature as it's not documented.
  return this.$scopedSlots[this.columns[***There must be current column index***].scopedSlots.customRender]({ text, record, index });
}
```
So, the issue I met is that I can't have access to column's properties, that is necessary to select the right scoped slot to render the cell.

The questions are:
1) I'm not sure if I choose the right way to implement the behavior I want to. Is there a better way to implement that?
2) Is it correct to use $scopedSlots property of table component as it's not documented?
3) Is it correct to pass a column of current cell to write column.customRender logic?

Thank you!

### What does the proposed API look like?
Consider question 3 in issue description section, I find easy to implement it by adding column param [here](https://github.com/vueComponent/ant-design-vue/blob/34343b2e8bd89d0e04ecb09121735de1035215d8/components/vc-table/src/TableCell.jsx#L70), but not sure that it wouldn't break some components functionality.

**Comment by tangjinzhou** [comment]
I can add it. No other side effects will occur.
