### ISSUE TITLE
官方文档一处引导的不严谨导致eslint报错

### ISSUE THREAD

**Issue by QiangGuZi** [vueComponent/ant-design-vue#1488]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
Win10 1903，Chrome 78，Vue CLI 3.11

### Reproduction link
[https://www.antdv.com/docs/vue/use-with-vue-cli-cn/](https://www.antdv.com/docs/vue/use-with-vue-cli-cn/)

### Steps to reproduce
按照重现拦截里的官网引导就会报错了
Failed to compile.

./src/App.vue
Module Error (from ./node_modules/eslint-loader/index.js):
error: The "HelloWorld" component has been registered but not used (vue/no-unused-components) at src\App.vue:14:5:
12 |   name: 'app',
13 |   components: {
> 14 |     HelloWorld
|     ^
15 |   }
16 | }
17 | </script>

1 error found.

### What is expected?
官网引导正常进行

### What is actually happening?
报错

---
官方引导文档中的

修改 src/App.vue的 template 内容。

<template>
<div id="app">
<img src="./assets/logo.png">
<a-button type="primary">Button></a-button>
</div>
</template>
...

修改为

<template>
<div id="app">
<img src="./assets/logo.png">
<a-button type="primary">Button></a-button>
<HelloWorld/>
</div>
</template>
...

这是一个无关紧要的问题，很好解决，但希望官网的引导教程还是不要出现这种东西。。

**Comment by QiangGuZi** [comment]
![image](https://user-images.githubusercontent.com/42662849/69901930-bfc28180-13c2-11ea-91a8-1647df805301.png)

**Comment by QiangGuZi** [comment]
要么提示用户将 `src/App.vue` 的tempplate内容替换成
`
<template>
  <div id="app">
    <img src="./assets/logo.png">
    <HelloWorld/>
    <a-button type="primary">Button></a-button>
  </div>
</template>
...
`

要么这里给出的代码就是完整 `src/App.vue`代码，删除掉自带导入的HelloWorld，避免eslint报错
![image](https://user-images.githubusercontent.com/42662849/69901957-33648e80-13c3-11ea-8cc3-16417fc6f461.png)

**Comment by QiangGuZi** [comment]
![image](https://user-images.githubusercontent.com/42662849/69901970-542ce400-13c3-11ea-8c4a-2335b35dc055.png)

**Comment by sendya** [comment]
你可以不开启 eslint。
另外，由于每个人创建 vue-cli 时，选用的配置不同。这是无法避免的问题，你也可以尝试由官方提供的项目初始化模板插件，进行创建项目。就可以得到和文档一致的体验，但还是不能保障用户从 cli3 升级到 cli4 所带来的问题。
不过稍微有经验的 vue 开发者，对于这种甚至都很熟练的 delete 了。
对于无 vue 开发经验的用户，我们是很不推荐直接上手框架。

如果认为引导有误认之处，也欢迎你 PR 进行修改
开源社区是大家一起发展才能更好

**Comment by QiangGuZi** [comment]
@sendya 收到
"你也可以尝试由官方提供的项目初始化模板插件，进行创建项目。"
我是使用vue cli 3.11 创建的项目，配置选用的default，默认会加载 eslint（经测试cli4.1.1同）
![image](https://user-images.githubusercontent.com/42662849/69910755-70746380-144b-11ea-951e-66f4ed77e64c.png)

好像没有得到和文档一样的体验。。。还是要用户手动关一下eslint或者文档当中提示用户手动选择配置不要选择eslint。。

提PR的话，没看到怎么给文档提PR🤣

刚刚还发现一个点，圈中的地方按照文档示意应该是 "css"，为true的话还需要开发者额外配置less等，体验与文档不一样🤣
![image](https://user-images.githubusercontent.com/42662849/69910914-5daf5e00-144e-11ea-8dfb-3c62586e557d.png)

**Comment by sendya** [comment]
cli3 是自动配置好的，除非你又是自己定义不选 less

**Comment by tangjinzhou** [comment]
配置会由于不同选项，导致配置会有所区别，可以考虑使用官方文档  另外欢迎PR 😄
