### ISSUE TITLE
when a-input use prefix, can not change input style

### ISSUE THREAD

**Issue by flymzero** [vueComponent/ant-design-vue#1490]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
System:     OS: macOS Mojave 10.14.6     CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz   Binaries:     Node: 10.14.2 - /usr/local/bin/node     Yarn: 1.13.0 - /usr/local/bin/yarn     npm: 6.12.0 - /usr/local/bin/npm   Browsers:     Chrome: 78.0.3904.108     Firefox: Not Found     Safari: 13.0.1   npmGlobalPackages:     @vue/cli: 3.12.0

### Steps to reproduce

```
<a-input id="jjj" placeholder="Basic usage">
<a-icon slot="prefix" type="search" />
</a-input>

#jjj{
border-radius: 16px;
border-color: #ffffff;
}
```

### What is expected?
can change input style

### What is actually happening?
can not change input style

**Comment by flymzero** [comment]
<a-input  id="jjj" placeholder="Basic usage">
     <a-icon slot="prefix" type="search" />
</a-input>

#jjj{
    border-radius: 16px;
    border-color: #ffffff;
}

**Comment by leslieeilsel** [comment]
I tried, it works!

![](https://raw.githubusercontent.com/leslieeilsel/Pictures/master/images/20191210171010.jpg)

**Comment by flymzero** [comment]
@leslieeilsel I find the problem is when i use <style scoped> 'a-input' can not change style, thanks

**Comment by flymzero** [comment]
i ues 
```
<style lang="less" scoped>
/deep/ #jjj{
    /*background-color: #000c17 !important;*/
    border-radius: 16px;
    border-color: #ffffff;
}
</style>
```
it is ok
