### ISSUE TITLE
图片上传的时候偶发的不显示图片

### ISSUE THREAD

**Issue by Thlq** [vueComponent/ant-design-vue#1491]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
windows

### Reproduction link
[https://www.antdv.com/docs/vue/introduce-cn/](https://www.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
图片上传的时候，多张图一个一个上传，在handleChange函数里面返回的file对象的thumbUrl字段偶发的返回伟空导致图片不显示

### What is expected?
正常显示图片

### What is actually happening?
如上

![image](https://user-images.githubusercontent.com/21211777/69948751-25318200-152b-11ea-8ff8-d38416f29f0b.png)

**Comment by tangjinzhou** [comment]
请提供重现demo
