### ISSUE TITLE
menu 组件在 edge 下使用报错 Error in nextTick: "TypeError: Unable to get property '$parent' of undefined or null reference"

### ISSUE THREAD

**Issue by imllz** [vueComponent/ant-design-vue#1492]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
windows10,Microsoft Edge 42.17134.1098.0,vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-9lvko)

### Steps to reproduce
* vue-cli3生成的模板
* 全量加载ant-design-vue组件
* 使用menu组件官方第一个demo例子
* 使用edge访问，菜单下拉无法展示
* 控制报错
```
[Vue warn]: Error in nextTick: "TypeError: Unable to get property '$parent' of undefined or null reference"

found in

---> Trigger>
SubMenu>
ConnectSubMenu>
ASubMenu>
DOMWrap>
SubPopupMenu>
ConnectSubPopupMenu>
ProxyConnectSubPopupMenu>
StoreProvider>
Menu>
AMenu>
App> at src/App.vue
Root>

TypeError: Unable to get property '$parent' of undefined or null reference

[Vue warn]: Error in nextTick: "TypeError: Unable to get property '_transitionClasses' of undefined or null reference"

TypeError: Unable to get property '_transitionClasses' of undefined or null reference
```

### What is expected?
二级菜单下拉展示正确

### What is actually happening?
二级菜单下拉无法展示

---
chrome 下正常

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/69974482-4fe9fd80-1560-11ea-821e-1861c9b32a7b.png)

不好意思没能复现，是否加 polyfills 看能否解决

**Comment by imllz** [comment]
@sendya 访问的时候不要打开控制台，然后基本上这个问题就能出现

**Comment by sendya** [comment]
好的，已复现

> @sendya 访问的时候不要打开控制台，然后基本上这个问题就能出现

**Comment by imllz** [comment]
@sendya 这个问题是什么原因导致的。如果是组件库本身的问题，我们应用这边目前有没什么可以规避的方法？

**Comment by ShiliangLuo** [comment]
我已经给这个问题搞死了。弄了几天还没定位问题在哪。关键是不打开控制台就会报错，打开就没有

**Comment by tangjinzhou** [comment]
生产模式又没这个问题 😓

**Comment by tangjinzhou** [comment]
update to 1.4.9
