### ISSUE TITLE
typescript form.createForm() 少个name类型 name是我加的

### ISSUE THREAD

**Issue by 5guang** [vueComponent/ant-design-vue#1495]
![image](https://user-images.githubusercontent.com/31607989/70017413-f9aba780-15bd-11ea-8fb8-6bcb5cc3fafd.png)

**Comment by 5guang** [comment]
`export interface IformCreateOption {
  name?: string;
  /**
   * Only supports the use of Form.create({})(CustomizedForm). declare props on form(like vue props)
   * @type object
   */
  props?: object;

  /**
   * Convert props to field value(e.g. reading the values from Redux store). And you must mark returned fields with Form.createFormField.
   * If you use $form.createForm to create a collector, you can map any data to the Field without being bound by the parent component.
   * @type Function
   */
  mapPropsToFields?: Function;

  /**
   * Default validate message. And its format is similar with newMessages's returned value
   * @type any
   */
  validateMessages?: any;

  /**
   * Specify a function that will be called when the value a Form.Item gets changed.
   * Usage example: saving the field's value to Redux store.
   * @type Function (Function(props, fields))
   */
  onFieldsChange?: (props: any, fields: any) => any;

  /**
   * A handler while value of any field is changed
   * @type Function
   */
  onValuesChange?: (props: any, fields: any) => void;
`

**Comment by EryouHao** [comment]
请问解决了吗？

**Comment by 5guang** [comment]
不用了 name可以不用要 如果你没有其他参数的话 就传个this就可以

在 2019-12-04 13:06:30，"Eryou Hao" <notifications@github.com> 写道：


请问解决了吗？
