### ISSUE TITLE
Table 表头固定后出现滚动条

### ISSUE THREAD

**Issue by Junzzzz** [vueComponent/ant-design-vue#1499]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
Chrome/78.0.3904.108

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-fixed-header](https://www.antdv.com/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce
- [Vue文档链接](https://www.antdv.com/components/table-cn/#components-table-demo-fixed-header)
- [React文档链接](https://ant.design/components/table-cn/#components-table-demo-fixed-header)
- id为：`#components-table-demo-fixed-header`
- 比较两个版本就可以看出来了

### What is expected?
- 去除~~丑陋的~~滚动条

### What is actually happening?
- 表头出现了~~丑陋的~~滚动条

**Comment by Junzzzz** [comment]
- Vue文档

![Vue.png](https://i.loli.net/2019/12/05/cMz9rLPeIkxCHFd.png)

- React文档

![React.png](https://i.loli.net/2019/12/05/7LTejaGUlWcFbhJ.png)

**Comment by nulIptr** [comment]
同发现这个问题，
`
.ant-table-fixed-header .ant-table-scroll .ant-table-header {
  overflow-y: hidden !important;
}
`
可以用上面的css强行消除，但是会导致横向滚动到右端的时候表头和表体错位一个滚动条的宽度，不需要横向滚动的可以这样搞一下。
之前我们的前端告诉我说官网就这样我还不信。。。有计划解决吗。。。

**Comment by zkwolf** [comment]
等版本同步吧

**Comment by celizi** [comment]
去掉数据少也显示滚动条 和校对表头表体错位问题


表格配置：tableheight 是页面动态计算的行高
:scroll="{ x: '100%',y: this.tableheight }"

在加载数据的回调内（需要延迟一丢丢即可）：
setTimeout(function(){
//修复头部滚动条
that.monitorBar();
},50)

修复头部与内容不对齐的方法（加载数据后，计算表格内容有无滚动条，动态变更头部样式进行对齐）
monitorBar(){
var table = this.$refs.bodyTable.querySelectorAll('.ant-table-body')[0];
var header = this.$refs.bodyTable.querySelectorAll('.ant-table-header')[0];
if(table.scrollHeight>table.clientHeight){
header.style="margin-bottom: -17px; padding-bottom: 0px; min-width: 17px; overflow: scroll;"
}else{
header.style="overflow:auto;"
}
}
其他样式：
配置表格滚动条自动
#bodyTable .ant-table-body {
overflow: auto !important;
}

如果对你有帮助，请点赞。
