### ISSUE TITLE
官方文档给的vue-cli 3.0配置按需加载那部分说明，无法实现，折腾了很久,目前vue-cli已升级到4.1.1了。

### ISSUE THREAD

**Issue by Mufenglee** [vueComponent/ant-design-vue#1500]
---antd-vue 版本1.4.8 
vue-cli 版本4.1.1

在网上查了，也有很多人反映，文档给的 按需加载 用那个插件不起作用，还请作者和各位同行 解答一下，谢谢了。

官方文档说明如下：（同事也试了，也？搞半天，是不是vue-cli升级到4.1.1了，antd-vue官方文档没更新所致？？）

使用 vue-cli 3 的小伙伴 #
修改babel.config.js文件，配置 babel-plugin-import

 module.exports = {
  presets: ["@vue/app"],
+  plugins: [
+    [
+      "import",
+      { libraryName: "ant-design-vue", libraryDirectory: "es", style: true }
+    ]
+  ]
};
然后移除前面在 src/main.js 里全量添加的 import 'ant-design-vue/dist/antd.css'; 样式代码，并且按下面的格式引入模块。

  // src/main.js
  import Vue from 'vue'
- import Button from 'ant-design-vue/lib/button';
+ import { Button } from 'ant-design-vue';
- import 'ant-design-vue/dist/antd.css'
  import App from './App'

  Vue.component(Button.name, Button)

  Vue.config.productionTip = false

  new Vue({
    render: h => h(App)
  }).$mount("#app");
最后重启 npm run serve 访问页面，antd 组件的 js 和 css 代码都会按需加载，你在控制台也不会看到这样的警告信息。关于按需加载的原理和其他方式可以阅读这里。

**Comment by JinPengGeng** [comment]
@Mufenglee 问题解决了吗，我这边也有这个问题，同样的样式文件在控制台中能清楚看到重复引用了两到三遍
