### ISSUE TITLE
a-table get row-index issue

### ISSUE THREAD

**Issue by amvicc** [vueComponent/ant-design-vue#1502]
I'm adding select component to table, and now i would like to get selected items, but if i add v-model to a-select all my selects select same value, another idea to get index of row and add to select Array, but idk how to get rowIndex in @change event. How can i get index of row or get for each a-select it's own v-model?

```
<a-table
        :columns="columns"
        :dataSource="data"
        :scroll="{ x: 'max-content' }"
        :pagination="{ pageSize: 9 }">
        <template slot="Client">
            <a-select v-model="selected" style="width: 200px" @change="handleChange">
               <a-select-option v-for="client in getProjects" :key="client" :value="client">
                  {{client}}
               </a-select-option>
            </a-select>
        </template>
</a-table>
```

**Comment by cmaa14** [comment]
add this one

<template slot="Client" slot-scope="text, record, index, column">

"index" - this is the row index
