### ISSUE TITLE
关于checkbox默认不全勾选，check all复选框状态没更改

### ISSUE THREAD

**Issue by jim888666** [vueComponent/ant-design-vue#1503]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.17

### Environment
vue2.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-j1q17)

### Steps to reproduce
链接有

### What is expected?
当所有checkbox默认全部勾选和不全勾选时，check all的indeterminate的状态能正常改变

### What is actually happening?
实际发生了，不全默认选中的时候，check all的indeterminate是打勾的

**Comment by sendya** [comment]
当设置 checkbox 初始默认值时，应当同时正确的设定 check all 选框值和 indeterminate 状态。

https://codesandbox.io/s/vue-antd-template-cgypk

**Comment by jim888666** [comment]
默认选中俩个的时候为啥还是打勾？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"言肆"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月4日(星期三) 凌晨1:17
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"我有我个性"<925079149@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] 关于checkbox默认不全勾选，check all复选框状态没更改 (#1503)




当设置 checkbox 初始默认值时，应当同时正确的设定 check all 选框值和 indeterminate 状态。
 
https://codesandbox.io/s/vue-antd-template-cgypk

**Comment by sendya** [comment]
> 默认选中俩个的时候为啥还是打勾？

因为你绑定了 `checkAll: true`，上面我不是描述过一次了吗?

当设置 checkbox 初始默认值时，应当同时 **正确** 的设定 check all 选框值和 indeterminate 状态。
