### ISSUE TITLE
在cli4中，按需引入后报错 Failed to resolve loader: less-loader

### ISSUE THREAD

**Issue by lessGameMoreStudy** [vueComponent/ant-design-vue#1505]
cli4的项目中，使用按需引入，运行项目报错 Failed to resolve loader: less-loader

**Comment by poorren** [comment]
> cli4的项目中，使用按需引入，运行项目报错 Failed to resolve loader: less-loader

I met same problem, and change style from true to css fix that. However, this would prevent less file when you want to change global theme. :(
