### ISSUE TITLE
AutoComplete 输入值时，placeholder 不会消失

### ISSUE THREAD

**Issue by akayhu** [vueComponent/ant-design-vue#1506]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
Chrome 版本 78.0.3904

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn/](https://www.antdv.com/components/auto-complete-cn/)

### Steps to reproduce
AutoComplete 输入注音文，placeholder 不会消失

### What is expected?
输入任何执会消失

### What is actually happening?
placeholder 不会消失

**Comment by akayhu** [comment]
![截圖 2019-12-04 上午11 54 31](https://user-images.githubusercontent.com/26111590/70111379-f501f480-168c-11ea-8ddc-330c283a07d7.png)

附圖

**Comment by tangjinzhou** [comment]
version ?

**Comment by akayhu** [comment]
"ant-design-vue": "^1.4.8"

而且這是你們官方範例就會有的問題

**Comment by tangjinzhou** [comment]
本周会发布

**Comment by qiaozhi520** [comment]
问题还是存在，1.4.10 官网示例依旧存在这个问题，用的是window 系统自带输入法

**Comment by qiaozhi520** [comment]
把placeholder 放在input 组件可解决这个问题
