### ISSUE TITLE
MonthPicker动态绑定时，改变data()中的值，时间选择框不改变，通过重新渲染组件才显示更新

### ISSUE THREAD

**Issue by YoungForRest** [vueComponent/ant-design-vue#1508]
```
<a-month-picker
         :open="openMonth"
         @change="dateChange"
         :value="chooseDate"
         ></a-month-picker>
```
我在其他组件的回调方法中改变chooseDate的值，a-month-picker的内容不改变
`
function(date){
       _this.chooseDate=moment(date);
}
`

**Comment by StephenKe** [comment]
> ```
> <a-month-picker
>          :open="openMonth"
>          @change="dateChange"
>          :value="chooseDate"
>          ></a-month-picker>
> ```
> 
> 我在其他组件的回调方法中改变chooseDate的值，a-month-picker的内容不改变
> `function(date){ _this.chooseDate=moment(date); }`

>我也碰到了一样的问题，这里应该是个bug，目前我是通过这种方式解决的，在你的基础改造吧：
> ```
> <a-month-picker
>          :open="openMonth"
>          @change="dateChange"
>          @openChange="handleDateOpenChange"
>          :value="chooseDate"
>          ></a-month-picker>
> ```

>`function(date){ _this.chooseDate=moment(date); this.openMonth=true;this.openMonth=false}`
>`handleDateOpenChange(val){this.openMonth=val}`

>核心思路：通过open属性手动触发视图更新，由于刷新速度很快所以在视图上是不会看到选择面板展开过程的
