### ISSUE TITLE
Switch组件 在自定义指令中对实例使用$on('input', callback)无效

### ISSUE THREAD

**Issue by Muscipular** [vueComponent/ant-design-vue#1509]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
Chrome 78; Win10x64; Vue v2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-ub4b0?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
-

### What is expected?
dynamic change 应该有输出

### What is actually happening?
dynamic change 没有输出

**Comment by tangjinzhou** [comment]
没觉得这个场景有必要支持，对于事件透传后，无法使用 $on 这个问题，或许可以给vue提issue来支持

**Comment by Muscipular** [comment]
看了下源码，Checkbox里面是有针对性处理的
https://github.com/vueComponent/ant-design-vue/blob/1b78a10ee6bea0445296e36d09123f5eddc7068d/components/checkbox/Checkbox.jsx#L67

**Comment by tangjinzhou** [comment]
没明白你是什么场景  需要这种使用方式，或许你可以说说你的场景，一起讨论下更合适的方案 ？

**Comment by Muscipular** [comment]
我目前想法是做一个可以双向绑定验证指令，在bind钩子时间里面订阅blur/change/input等事件以触发校验。
Input控件和Checkbox控件我大致试了下$on来绑定input/change事件并没问题，但是Switch控件$on对input/change事件并不起效。同时我也发现了缺少v-model/value绑定时value值始终为undefined，不知道是否有什么办法可以处理这种问题？

**Comment by tangjinzhou** [comment]
switch  v-model绑定的属性是 checked
