### ISSUE TITLE
Plugin for vue cli 4

### ISSUE THREAD

**Issue by arunrreddy** [vueComponent/ant-design-vue#1512]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Need a plugin for vue-cli 4 which supports babel-plugin-import. The current version doesn't support this feature. The components are loaded but the CSS is not being applied on the components. There are no errors while running locally while using ant-design-vue with babel-plugin-import, but the CSS isn't loading.

### What does the proposed API look like?
Need a plugin which supports babel-dynamic-import for dynamic component imports.

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout/blob/master/examples/src/core/antd/lazyload.js

https://github.com/vueComponent/pro-layout/blob/master/examples/babel.config.js

https://github.com/vueComponent/pro-layout/blob/master/examples/package.json#L29-L34
