### ISSUE TITLE
Closable Message

### ISSUE THREAD

**Issue by fuweichin** [vueComponent/ant-design-vue#1514]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I do see the message, but please do not block my view for 1.5 seconds or more or less, I want the message disappearing at once, so please give me a button to do that.

### What does the proposed API look like?
May be a boolean option 'cancelable' can add to API, if cancelable then a 'close' button will be added to top-right corner of the message box, and if I click on the button, as you see, close the box

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/70201444-a8ccb800-1751-11ea-8a09-d894b606f057.png)
