### ISSUE TITLE
a-popover内嵌套普通原生button标签时,若该button带有class,则报错

### ISSUE THREAD

**Issue by javaLuo** [vueComponent/ant-design-vue#1519]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
mac,chrome,最新vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-8hflx)
见src/App.vue和控制台输出

### Steps to reproduce
当在`<a-popover>`中嵌套一个普通`<button>`标签时，且该标签带有class: `<button class="test">`, 则报错

### What is expected?
别报错，我现在就想用原生的button，不想用a-button

### What is actually happening?
它报错了，undefined什么的

**Comment by tangjinzhou** [comment]
会尽快修复
临时解决方案  https://codesandbox.io/s/vue-antd-template-f20tr
