### ISSUE TITLE
Modal title 变化，同时 destroyOnClose 为 true，导致重复 mount 和 destroy

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#152]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
Win7/vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vq5mql2l77)

### Steps to reproduce
1、点击取消关闭弹窗
2、点击ok按钮打开弹窗，再点击取消关闭弹窗
3、看console日志

### What is expected?
不会重新执行mount和destroy

### What is actually happening?
重复Mount以及destroy。

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/44965051-43928180-af66-11e8-8146-530f2c9f5657.png)
destroyOnClose=true就是干这个事的啊

**Comment by bq-hentai** [comment]
请看 [栗子](https://codesandbox.io/s/vq5mql2l77) 并按照操作走。

**Comment by bq-hentai** [comment]
感谢回复 @tangjinzhou 。

请看 [栗子](https://codesandbox.io/s/vq5mql2l77) 并按照操作走。

开始初始打开页面，默认打开弹窗，会出现两个 mount，Console截图：
![image](https://user-images.githubusercontent.com/19964297/44970657-654f3100-af85-11e8-8952-142baa3f2c1f.png)

然后取消关闭弹窗，会有两个destroy（这个是beforeDestroy hook打印的，所以顺序和destroy相反），console截图：
![image](https://user-images.githubusercontent.com/19964297/44970729-a3e4eb80-af85-11e8-9c09-6a271c01d492.png)

再次打开弹窗，会有两个 mount，Console 截图：
![image](https://user-images.githubusercontent.com/19964297/44970760-b2cb9e00-af85-11e8-8e8d-cc5d7a7ac5a1.png)

最后点击确定，**应该是两个destroy**，但是并不是，多了mount 和 destroy，看截图：
![image](https://user-images.githubusercontent.com/19964297/44970807-dabb0180-af85-11e8-9664-446b28331d62.png)

另外，更直观的可以看 [这个栗子](https://codesandbox.io/s/00rw1vx91v)，直接点击打开和确定，然后看 Console。

**Comment by tangjinzhou** [comment]
please update to 1.1.0
