### ISSUE TITLE
a-table rowSelection 在设置type为radio后，无法重置

### ISSUE THREAD

**Issue by GitHub-Leon** [vueComponent/ant-design-vue#1520]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1.能在数据重新加载后，重置已选的radio状态；
2.提高用户体验；

### What does the proposed API look like?
希望能够像checkbox那样，数据在重新加载后，将radio状态进行重置；
目前的checkbox是将selectdRowKey设置为空数组达到重置已选择的checkbox状态；

**Comment by tangjinzhou** [comment]
radio 不能重置的  可以说这是html规范  建议使用 checkbox 自行处理逻辑，来达到单选的功能

**Comment by tangjinzhou** [comment]
https://ux.stackexchange.com/questions/13511/why-is-it-impossible-to-deselect-html-radio-inputs
