### ISSUE TITLE
Tooltip 组件作用在容器组件上时，且trigger为click的时候，点击时候会闪烁，无法正常点开

### ISSUE THREAD

**Issue by zuley** [vueComponent/ant-design-vue#1521]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
mac10.15.1 、谷歌78.0.3904.108、vue2.6

### Reproduction link
[https://www.antdv.com/components/tooltip-cn/](https://www.antdv.com/components/tooltip-cn/)

## 组件定义

```
const Item = {
  methods: {
    handleclick (event) {
      this.$emit('click')
    }
  },
  render (h) {
    return (
      <div on={{ click: this.handleclick }}>
        { this.$slots.default }
      </div>
    )
  }
}

const Item2 = {
  functional: true,
  render (h, ctx) {
    return (
      <Item><template slot="default">{ ctx.scopedSlots.default() }</template></Item>
    )
  }
}
```

## 使用

```
<a-tooltip trigger="click">
  <template slot="title">你站的越近，看到的就越少。</template>
  <Item2>惊天魔盗团</Item2>
</a-tooltip>
```

### What is expected?
正常使用

### What is actually happening?
闪烁，无法点开

**Comment by tangjinzhou** [comment]
你这个相当于触发了两次click，再包一层吧

```js
const Item2 = {
  functional: true,
  render (h, ctx) {
    return (
      <div><Item><template slot="default">{ ctx.scopedSlots.default() }</template></Item></div>
    )
  }
}
```

**Comment by zuley** [comment]
> 你这个相当于触发了两次click，再包一层吧
> 
> ```js
> const Item2 = {
>   functional: true,
>   render (h, ctx) {
>     return (
>       <div><Item><template slot="default">{ ctx.scopedSlots.default() }</template></Item></div>
>     )
>   }
> }
> ```

我现在临时方案就是这样，再包一层就可以了，但是这样只能是临时方案，应该看看能否在源头解决。
