### ISSUE TITLE
复选框选中问题（鼠标点击行自动勾选checkbox）

### ISSUE THREAD

**Issue by aleiliuwei** [vueComponent/ant-design-vue#1524]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
1.4.8

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-selection](https://www.antdv.com/components/table-cn/#components-table-demo-selection)

### Steps to reproduce
table 带复选框，用户希望鼠标选中行时自动勾选上前面的复选框

### What is expected?
鼠标点击行，自动勾选复选框，而不是必须点击复选框

### What is actually happening?
鼠标点击行，不自动勾选复选框

**Comment by wangxueliang** [comment]
customRow自己实现
