### ISSUE TITLE
dialog will cause double scrollbar

### ISSUE THREAD

**Issue by imic07** [vueComponent/ant-design-vue#1533]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
win10/chrome latest/vue 1.4.8

### Reproduction link
[https://www.antdv.com/components/modal-cn/](https://www.antdv.com/components/modal-cn/)

### Steps to reproduce
1. dialog's parent container must have a scrollbar-y .
2. use a-dialog open a new Dialog on parent container, the dialog must have enought height to make it cant fully display

### What is expected?
if dialog's height cant fully display  and parent container has scrollbar, then hide the parent container scrollbar, only show dialog's scrollbar.        when close the dialog, recovery the parent container's scrollbar

### What is actually happening?
antd-vue version 1.3.9 is correct, the lattest version is wrong
in 1.4.8, parent container's scrollbar still exists

---
i searched the source code, find dialog.js in version 1.4.8
```
getOpenCount: function getOpenCount() {
return null;
}

addScrollingEffect: function addScrollingEffect() {
var getOpenCount = this.getOpenCount;

var openCount = getOpenCount();
// have a bug ， openCount always return null, in version 1.3.9 ,have openCount   
if (openCount !== 1) {
return;
}


removeScrollingEffect: function removeScrollingEffect() {
var getOpenCount = this.getOpenCount;

var openCount = getOpenCount();
// have a bug ， openCount always return null, in version 1.3.9 ,have openCount --

if (openCount !== 0) {
return;
}
```

double scrollvar:
![image](https://user-images.githubusercontent.com/16321067/70506505-6e09bc00-1b65-11ea-95e8-ded5b3273b2b.png)

version 1.3.9 is correct :
![image](https://user-images.githubusercontent.com/16321067/70506570-9abdd380-1b65-11ea-8d50-70ad17b584ff.png)

version 1.4.8 have a bug:
![image](https://user-images.githubusercontent.com/16321067/70506648-ca6cdb80-1b65-11ea-882d-f7e1ba187840.png)

![image](https://user-images.githubusercontent.com/16321067/70506618-b7f2a200-1b65-11ea-927e-8cf1381d4b24.png)

**Comment by tangjinzhou** [comment]
重复 #1501
