### ISSUE TITLE
Missing typography component

### ISSUE THREAD

**Issue by Mikejonesab12** [vueComponent/ant-design-vue#1537]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.9

### Environment
Mac v10.15.1, Chrome v78.0.3904.108

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
The docs show no Typography component in the general section of the docs

### What is expected?
To see documentation about the Typography component like in the React and Angular versions of Ant Design.

### What is actually happening?
The docs show no Typography component in the general section of the docs

---
Both Ant Design Angular(https://ng.ant.design/components/typography/en) and Ant Design React(https://ant.design/components/typography/) have a typography component.

However, I see no such component for Vue in the docs or in the source code. Is this deliberate? Are there other ways for the same functionality?

**Comment by incompletude** [comment]
Any news on this?

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/pull/2052

**Comment by Yakoot** [comment]
any news?

**Comment by bowencool** [comment]
any news?

**Comment by incompletude** [comment]
nice action
ignore it and it will go away
