### ISSUE TITLE
form label's line-height not correct

### ISSUE THREAD

**Issue by imic07** [vueComponent/ant-design-vue#1538]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.9

### Environment
win10/chrome latest/vue 2.5

### Reproduction link
[https://www.antdv.com/components/form-cn/](https://www.antdv.com/components/form-cn/)

### Steps to reproduce
参看官方示例

### What is expected?
line-height set to 40px

### What is actually happening?
line-height set to 39px

![image](https://user-images.githubusercontent.com/16321067/70584114-eec6c780-1bfa-11ea-998d-2dfcddbd60d2.png)

---
css 样式中是39.9999px, 渲染后成了39px. 导致form表单样式对不齐
![image](https://user-images.githubusercontent.com/16321067/70584177-31889f80-1bfb-11ea-8cfe-bc182b871515.png)
![image](https://user-images.githubusercontent.com/16321067/70584188-3fd6bb80-1bfb-11ea-860a-cade46433b5b.png)

**Comment by sendya** [comment]
```vue
<style lang="less" scoped>
.cf /deep/ .ant-form-item-control {
  min-height: 40px;
}
</style>
```
https://bppu9.csb.app/

https://codesandbox.io/s/weathered-wood-bppu9?fontsize=14&hidenavigation=1&theme=dark

比较好奇为什么要这样用 form，如果只是为了实现 `DescriptionList` 不是应该直接 row + col 即可吗？

**Comment by imic07** [comment]
@sendya 
你这种还是没有解决label属性设置的是39.9999px,渲染后变成了39px的问题，,
![image](https://user-images.githubusercontent.com/16321067/70675743-010d3800-1cc5-11ea-92b1-0e01bc403a8a.png)       
这样用form很和理啊，因为wrapper里面可能一个input， textarea, 而且还需要校验。

**Comment by sendya** [comment]
可是你的 form 里就是普通的 空 dom 节点

**Comment by imic07** [comment]
这个有些要替换成input的。现在只是占位。

**Comment by sendya** [comment]
只要你替换成 Input 就不存在这种问题。放心用

**Comment by imic07** [comment]
。。。 只会部分使用input啊

**Comment by imic07** [comment]
比如像这个样
![image](https://user-images.githubusercontent.com/16321067/70676905-9827bf00-1cc8-11ea-9392-ae8a3f38b236.png)

**Comment by imic07** [comment]
@sendya 为啥有这么多的39.9999px而不是40px呢？把这些改了应该就正常了
![image](https://user-images.githubusercontent.com/16321067/70677318-d671ae00-1cc9-11ea-9d18-41e9bf932a04.png)
