### ISSUE TITLE
在electron-vue下modal无法使用

### ISSUE THREAD

**Issue by pengshba** [vueComponent/ant-design-vue#154]
按照官方的文档的写法使用后,点击没有任何效果,也不会报错,很尴尬
![lh 6zl tqrqu86ws_m8j](https://user-images.githubusercontent.com/29194619/44965121-9409df00-af66-11e8-8df5-46674adcb74d.png)

![pt8 t vj3j aw4ov r3sf](https://user-images.githubusercontent.com/29194619/44965116-8d7b6780-af66-11e8-88ce-a454d83b15c9.png)

**Comment by iczer** [comment]
最好给出复现链接，方便定位问题

**Comment by webees** [comment]
已测试，在electron-vue中大部分组件都无法正常使用

**Comment by webees** [comment]
调用modal不会报错，直接打印会显示TypeError: 'caller' and 'arguments' are restricted function properties and cannot be accessed in this context.

![tim 20180904145617](https://user-images.githubusercontent.com/5155291/45014931-b11bdc00-b052-11e8-828c-eb71b5a3d58f.png)
每执行this.$error()会插入两个div空节点。

**Comment by webees** [comment]
复现代码：

![_20180904145723](https://user-images.githubusercontent.com/5155291/45014976-dad50300-b052-11e8-88c2-b69298f4fbbf.png)

**Comment by iczer** [comment]
刚试了下，我这里是正常的，win10
![image](https://user-images.githubusercontent.com/13096697/45014915-a2352980-b052-11e8-87f9-049035564108.png)
```html
<template>
    <div>
        <a-button @click="open">click me</a-button>
    </div>
</template>
<script>
export default {
  name: 'Modal',
  methods: {
    open () {
      this.$success({
        title: 'hello',
        content: 'hello world'
      })
    }
  }
}
</script>
```

**Comment by webees** [comment]
@iczer 你关闭重新run dev一下呢，我也成功过一次。

**Comment by iczer** [comment]
重启确实不行了，等官方给适配吧

**Comment by tangjinzhou** [comment]
这里有个方案可以解决 #134 
或者使用按需加载也可以

**Comment by hefengxian** [comment]
@webees  改一下配置就可以了，这个锅不是 `ant-design-vue` 的，找到 `.electron-vue/webpack.renderer.config.js` 将 `ant-design-vue` 加入到白名单
```js
/**
 * List of node_modules to include in webpack bundle
 *
 * Required for specific packages like Vue UI libraries
 * that provide pure *.vue files that need compiling
 * https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals
 */
let whiteListedModules = ['vue', 'ant-design-vue']
```
Electron-Vue 有文档说明这个问题 [https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals](https://simulatedgreg.gitbooks.io/electron-vue/content/en/webpack-configurations.html#white-listing-externals)

**Comment by webees** [comment]
谢谢大神解答！
