### ISSUE TITLE
MonthPicker点击左右图标切换年份功能失效

### ISSUE THREAD

**Issue by lixueq** [vueComponent/ant-design-vue#1543]
**Version**

1.4.9

**Environment**

Vue.3.8.4

**Reproduction link**

https://www.antdv.com/components/date-picker-cn/

**Steps to reproduce**

在MonthPicker这个组件中，点击左右图标切换年份的时候，之前是可以的，今天发现无法切换了，然后看了一眼组件库，发现也不可以。

---
In the component of monthpicker, when you click the left and right icons to switch the year, it was OK before. Today, you find that you can't switch. Then you take a look at the component library and find that you can't either.

**What is expected?**

想了解这个功能是被取消了，还是说在优化！

---
Want to know if this function has been cancelled or is it optimizing!

**What is actually happening?**
暂无

**Comment by tangjinzhou** [comment]
update 1.4.10

**Comment by lixueq** [comment]
非常感谢

---
Thank you very much.
