### ISSUE TITLE
若表格组件中filters的value为number的时候，筛选选中项的checkbox不会被打勾

### ISSUE THREAD

**Issue by lumozx** [vueComponent/ant-design-vue#1544]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
macOS Catalina 10.15.1   Google Chrome 78.0.3904.108 Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-mendeleev-eg5f3)

### Steps to reproduce
1、打开链接
2、点击表格筛选按钮
3、点击筛选项

### What is expected?
checkbox被打勾

### What is actually happening?
文字有选中样式，可以通过change时间获取选择筛选选项，但筛选checkbox没有被打勾

**Comment by a941909105** [comment]
遇到同样问题,text=value 筛选选项效果才能正常显示,我的解决办法是在给filters基于text-value在加入newValue,在监听表格内容改变时将获取到的value值替换为newValue
