### ISSUE TITLE
table 中使用slot="expandIcon" slot-scope="props"   无效

### ISSUE THREAD

**Issue by DinoRun** [vueComponent/ant-design-vue#1546]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
window

### Reproduction link
[https://www.antdv.com/components/table-cn/#api](https://www.antdv.com/components/table-cn/#api)

### Steps to reproduce
<a-icon
slot="expandIcon"
slot-scope="props"
type="search"
/>

### What is expected?
使用插槽有效

### What is actually happening?
无法正常使用插槽

**Comment by sendya** [comment]
可以先这样用，slot 的我后续在测试看看
https://codesandbox.io/s/antd-table-expandicon-7m8sm

**Comment by DinoRun** [comment]
@sendya 谢谢！
