### ISSUE TITLE
 <a-locale-provider>

### ISSUE THREAD

**Issue by laravelup** [vueComponent/ant-design-vue#156]
<a-locale-provider :locale="zhCN">
        <router-view/>
    </a-locale-provider>

Unknown custom element: <a-locale-provider> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by tangjinzhou** [comment]
<a-locale-provider :locale="zhCN">
    <div><router-view/></div>
</a-locale-provider>

**Comment by laravelup** [comment]
@tangjinzhou 还是一样的

**Comment by tangjinzhou** [comment]
那就是你没注册  看文档吧
https://github.com/vueComponent/ant-design-vue/blob/master/site/components.js#L106

**Comment by laravelup** [comment]
@tangjinzhou 可以了，谢谢~
