### ISSUE TITLE
组件库没有使用初始化样式文件

### ISSUE THREAD

**Issue by 2017coding** [vueComponent/ant-design-vue#1569]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
vue2.6

### Reproduction link
[https://www.antdv.com/docs/vue/introduce/](https://www.antdv.com/docs/vue/introduce/)

### Steps to reproduce
组件库没有引用初始化样式文件，当我在项目中引用初始化样式文件时，组件样式出现显示问题

### What is expected?
我在使用ant design的时候，可以使用初始化样式文件

### What is actually happening?
我在使用ant design的时候，使用初始化样式文件，组件样式出现问题

**Comment by tangjinzhou** [comment]
没明白啥意思
