### ISSUE TITLE
Layout.Sider 组件无法应用 vue transition 过渡动画

### ISSUE THREAD

**Issue by iczer** [vueComponent/ant-design-vue#157]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
win10 chrome 版本 67.0.3396.99

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m34o78xm38)

### Steps to reproduce
```html
<a-layout>
    <transition>
      <a-layout-sider v-if="showSider"></a-layout-sider>
    </transition>
    <a-layout>
      <a-layout-content style="padding: 100px;">
          <a-button @click="toggle">click me</a-button>
      </a-layout-content>
    </a-layout>
</a-layout>
<script>
export default {
  name: "App",
  data () {
    return {
           showSider: true
       }
   },
   methods: {
    toggle () {
      this.showSider = !this.showSider
       }
   }
};
</script>
<style lang="css" scoped>
  .v-leave-active, .v-enter-active{
    transition: all .5s ease-in 0s
  }
  .v-leave-to, .v-enter{
    width: 0px;
  }
</style>
```

### What is expected?
Layout.Sider组件能够支持 vue 过渡动画

### What is actually happening?
Layout.Sider不支持 vue 过渡动画

**Comment by tangjinzhou** [comment]
这个和组件没有关系
https://codesandbox.io/s/6jyv3z81rk

**Comment by iczer** [comment]
width 动画没有生效
https://codesandbox.io/s/pwzxwxovqx

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/ojlr53kj49
width权重问题

**Comment by iczer** [comment]
感谢
