### ISSUE TITLE
a-range-picker配置了ranges（预设时间范围快捷选择）属性，选择预设的range之后点击clear图标清除时间范围之后，首次点击选择框之前选择的range会残留在日期选择框上

### ISSUE THREAD

**Issue by YupaiTS** [vueComponent/ant-design-vue#158]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
win10 17134.228，chrome 69.0.3497.81, vue 2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j7lk540m09)

### Steps to reproduce
1. 选择预设的range之后点击clear图标清除时间范围
2. 之后首次（只有这一次）点击选择框之前选择的range会残留在日期选择框上

### What is expected?
之前选择的range不残留在日期选择框上

### What is actually happening?
之前选择的range残留在了日期选择框上

**Comment by tangjinzhou** [comment]
please update to 1.1.0
