### ISSUE TITLE
form 表单添加disabled属性

### ISSUE THREAD

**Issue by zhouzhili** [vueComponent/ant-design-vue#1580]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以将表单内所有输入控件disabled掉，不用每一个input都单独的添加disabled属性

### What does the proposed API look like?
window10
chrome 79
vue Lastest

**Comment by sendya** [comment]
这个需求范围实在太少了，而且有概念冲突（比如 label 有表单元素，是不是也要禁用，禁用优先级等问题）。
你可以每个需要禁用的表单元素自行绑定同一个禁用变量即可

**Comment by zhouzhili** [comment]
好吧，如果一个form里面表单很多，一键禁止输入还是可以节省很多代码量的，elementUI的form就有这个属性，如果实在不行只能手动一个个的加上了。

**Comment by a1067111756** [comment]
可以在<a-form>标签添加disabled属性， 然后只对<a-form-item>下的表单生效，这个需求对于中后台管理系统很实用， 很多表单在查看时需要禁止用户编辑， 在添加和编辑情况下是可用的，太常见的需求了。恳请考虑这样需求，不然每个表单项去绑定使代码即不好管理也优雅。 现在自己的方案是做了一个指令实现也很繁琐

**Comment by wiredgril666** [comment]
啊、、那么整个表单禁用了，但是只有某一项不想禁用，还能用form整个禁用吗？有什么办法解决吗？虚心求教

**Comment by Rabbitzzc** [comment]
这个需求蛮重要的，可能得写一个自定义指令了

**Comment by Spacesless** [comment]
自定义指令怎么写呢，disabled属性是父组件通过props下发的，子组件修改不了

**Comment by wangi4myself** [comment]
自己尝试写了一个指令 递归了下面所有的带有disable的组件
npm 地址：https://www.npmjs.com/package/antd-vue-form-disable

**Comment by ikarosu** [comment]
可惜了，没有这个属性要手动设置几十个字段，为了这个属性只能单独装个element-plus了

**Comment by ricarduuu** [comment]
真的好实用的 太省代码了

**Comment by zbs-ha** [comment]
What a pity
