### ISSUE TITLE
自定义a-select-option的children后，下来列表的样式和选中不一样

### ISSUE THREAD

**Issue by lengband** [vueComponent/ant-design-vue#1587]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
"ant-design-vue": "1.4.9", "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-yimfb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
自定义a-select-option的children后，下来列表的样式和选中不一样

### What is expected?
自定义a-select-option的children后，下来列表的样式和选中一样

### What is actually happening?
自定义a-select-option的children后，下来列表的样式和选中不一样

**Comment by zkwolf** [comment]
没看出来哪不一样，详细说一下？

**Comment by lengband** [comment]
![](https://wp-bucket-1257997404.cos.ap-beijing.myqcloud.com/issue.png)

**Comment by lengband** [comment]
<img width="450" alt="issue" src="https://user-images.githubusercontent.com/26566045/71173067-c5fa9e00-229c-11ea-993f-2eb1b16e2e4f.png">
如图，已缓存在option中是左右布局，在select中是左布局

**Comment by lengband** [comment]
@zkwolf
