### ISSUE TITLE
table组件pagination配置项目不支持pagination组件的showSizeChange事件

### ISSUE THREAD

**Issue by woterwang** [vueComponent/ant-design-vue#1588]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
window7,chrome版本 78.0.3904.70（正式版本）,"vue": "^2.5.22",

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/table/Table.jsx](https://github.com/vueComponent/ant-design-vue/blob/master/components/table/Table.jsx)

### Steps to reproduce
1.引用Table组件
2.设置默认分页条数为50，假如现有共有5页
3.切换页码到第2页以后（假如这里切到第3页）
4.切换Pagesize为50条以下

现状：分页仍然显示第3页

### What is expected?
1.切换pagesize后可以回调到分页组件的 showSizeChange方法
2.或者当前页可以重置到第1页

### What is actually happening?
切换pagesize后当前页码没有变化

**Comment by wangkaiChen1118** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> 1.4.10
> 
> ### Environment
> window7,chrome版本 78.0.3904.70（正式版本）,"vue": "^2.5.22",
> 
> ### Reproduction link
> https://github.com/vueComponent/ant-design-vue/blob/master/components/table/Table.jsx
> 
> ### Steps to reproduce
> 1.引用Table组件
> 2.设置默认分页条数为50，假如现有共有5页
> 3.切换页码到第2页以后（假如这里切到第3页）
> 4.切换Pagesize为50条以下
> 
> 现状：分页仍然显示第3页
> 
> ### What is expected?
> 1.切换pagesize后可以回调到分页组件的 showSizeChange方法
> 2.或者当前页可以重置到第1页
> 
> ### What is actually happening?
> 切换pagesize后当前页码没有变化

插个眼，等待解决，我也遇到同样的问题了

**Comment by mx4g** [comment]
table组件pagination配置 ，showSizeChange 和 Change 都不触发回调，等待解决，谢谢！

**Comment by mx4g** [comment]
你可以这样写：
<a-table
          :pagination="pagination"
          @change="changePage"
          @showSizeChange="showSizeChange"   
   / >

**Comment by sendya** [comment]
https://codesandbox.io/embed/competent-cartwright-e51cf?fontsize=14&hidenavigation=1&theme=dark

**Comment by Glacier-Luo** [comment]
实际上方法名是onShowSizeChange，这谁能想到呢，官方文档写的是showSizeChange。

**Comment by WAGFS** [comment]
> 实际上方法名是onShowSizeChange，这谁能想到呢，官方文档写的是showSizeChange。

一开始想到可能会是这种写法，但是在使用的时候我只是前面加了一个on，’s‘没有大写导致触发不了，真是醉了。
