### ISSUE TITLE
浏览器引入无法使用

### ISSUE THREAD

**Issue by EmKs** [vueComponent/ant-design-vue#160]
同样以script和link方式分别引入iview、ele、antd的js和css文件,发现iview和ele的样式可以出现，但唯独antd无法正常显示
![default](https://user-images.githubusercontent.com/21976086/45096660-9bdaa680-b153-11e8-98ef-aded66851650.png)

**Comment by tangjinzhou** [comment]
`Vue.use(Antd)`

**Comment by EmKs** [comment]
@tangjinzhou 好了，因为其他两个Ui都没有这个步骤，所以不清楚问题在哪，感谢

**Comment by nicewahson** [comment]
这种方式的table数据不展示是啥原因？
