### ISSUE TITLE
table组件的 title slot 必须要用slot-scope才能展示，这应该是不必要的

### ISSUE THREAD

**Issue by xpuliapushi** [vueComponent/ant-design-vue#1605]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
1.4.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-8pkp0?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、页面添加a-table组件
2、a-table组件中使用 title插槽，不添加slot-scope

### What is expected?
title插槽应该不用slot-scope即可展示，类似modal组件

### What is actually happening?
title（即table的head）不展示

**Comment by tangjinzhou** [comment]
建议使用Vue 2.6 最新语法 v-slot，组件已经没有兼容的必要了
