### ISSUE TITLE
建议：重构readme、isuse标准化、优化logo、更改组织名称

### ISSUE THREAD

**Issue by zhangfugui727** [vueComponent/ant-design-vue#161]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?

- 重构readme（建议参照以下资源库）
[vue.js](https://github.com/vuejs/vue) | [ant-design](https://github.com/ant-design/ant-design)  | [element](https://github.com/ElemeFE/element)

1. - 让开发者更加快速的寻找到帮助。（快速入门、浏览器兼容、文档链接、公开antd同步日志）
2. - 增加赞助栏，即帮助投资人推广，也吸引更多人进行赞助。
3. - 增加贡献者栏，毕竟不是一个人，还需要吸引更多代码贡献者。

- isuse标准化
标准英语，吸引更多开发者，更加专业。
- 优化logo
专业、友好，且具有代表性，品牌投资。
- 更改组织名称
标准化组织，更加具有代表、标识，增加影响力，表示这个团队是活跃的，吸引更多开发者。

### What does the proposed API look like?
无

**Comment by usercao** [comment]
组织可以纳入VUE官方仓库下面，logo还是用antd的logo吧？

**Comment by vuchan** [comment]
这是一个被低估了的 Vue-Ant-Design UI Lib，从代码质量看上去比 element-ui 要高。

**Comment by yugasun** [comment]
求加入组织，能为组织做些微薄贡献。

**Comment by tangjinzhou** [comment]
> 求加入组织，能为组织做些微薄贡献。

@yugasun 可以直接pr哈   对于比较活跃的同学，会邀请加入组织的

**Comment by tangjinzhou** [comment]
https://vue.ant.design

**Comment by zhangfugui727** [comment]
> https://vue.ant.design

稳重的人确实值得称赞，1年多的努力就为了等一天，祝贺
