### ISSUE TITLE
Table vertical scroll props creates 2 table tags

### ISSUE THREAD

**Issue by jericopulvera** [vueComponent/ant-design-vue#1614]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Codesandbox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-2lhvt)

### Steps to reproduce
Visit the link and inspect element

### What is expected?
1 table tag only on scroll y

### What is actually happening?
2 table tags created

---
This is not really a bug but it causes conflict when using a scroll y prop with https://www.npmjs.com/package/xlsx package.

2 tables make it hard to implement a table to CSV conversion.

**Comment by tangjinzhou** [comment]
maybe you can find table by dom selector
