### ISSUE TITLE
评分的图标采用的是svg存在的隐患。

### ISSUE THREAD

**Issue by lezoinfo** [vueComponent/ant-design-vue#1617]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Linux、所有浏览器、nuxt/vue3.0

### Reproduction link
[https://www.antdv.com/components/rate-cn/](https://www.antdv.com/components/rate-cn/)

### Steps to reproduce
评分的图标采用的是svg的方式，直接保存在html中，当我使用40组评分组件的时候，仅该组件的大小就是200k ，对seo很不友好，望解决。

### What is expected?
使用样式实现。

### What is actually happening?
svg图片，保存在html中。

**Comment by tangjinzhou** [comment]
可以通过 v-slot:character 自定义图标

**Comment by dzcpy** [comment]
的确，从架构上来说所有可能重复的图标都不应该用内联svg
