### ISSUE TITLE
momentjs to date-fns

### ISSUE THREAD

**Issue by transtone** [vueComponent/ant-design-vue#162]
https://github.com/iczer/vue-antd-admin/issues/24

**Comment by transtone** [comment]
@tangjinzhou  直接关闭是不予考虑呢，还是不在现阶段的考虑范围之内，还是说因为人手的问题，盼回复。

**Comment by tangjinzhou** [comment]
请通过 issue helper 提issue或功能请求
https://vuecomponent.github.io/issue-helper/

为了后续方便跟进功能迭代，momentjs的是否替换，取决于react版antd，多谢建议
