### ISSUE TITLE
use <a /> elements for menu items

### ISSUE THREAD

**Issue by gdi2290** [vueComponent/ant-design-vue#164]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
A user should be able to right click and select open in new tab

### What does the proposed API look like?
Make use of Renderless Component so the user can choose to use a `<li>` or `<a>` using `<nuxt-link>` for menu items

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/45214034-f139c380-b2cb-11e8-8d1c-d91026415a0e.png)

**Comment by tangjinzhou** [comment]
you can use <a/> like this
```
<a-menu-item key="1">
     <a href="">Option 1</a>
</a-menu-item>
```

**Comment by gdi2290** [comment]
yeah that works but the the `<a>` element is only wrapping the text or anything in it. I'll just remove the padding from the `<li>` and style the `<a>` elements. That why the user can right click the full element size rather than just the text
