### ISSUE TITLE
a-radioGroup回显选中不了？

### ISSUE THREAD

**Issue by soho-smarthome** [vueComponent/ant-design-vue#1644]
I have searched the issues of this repository and believe that this is not a duplicate.
What problem does this feature solve?
a-radioGroup 回显选中不了？

What does the proposed API look like?
a-radioGroup 回显选中不了？

代码示例如下：
====a-form>
........
===a-form-item label="名称">
                <a-radio-group
                    v-decorator="['radioGroup', rule.radioGroup]"
                    @change="onRadioChange">
                     ==a-radio :style="radioStyle" :value="0">
                        =a-input-number v-model="model.param1" :min="0" :max="10000"/>
                        =span class="ant-form-text">AAAAAAAA</span>
                    ==/a-radio>
                    ==a-radio :style="radioStyle" :value="1">
                        =a-input-number  v-model="model.param2" :min="0" :max="100" />
                        =span class="ant-form-text">BBBBBBBBB</span>
                    ==/a-radio>
==/a-form-item>
===/a-form>
export default {
data() {
   radioType: '0',
   rule:{
        radioGroup: {
                    rules: [{ required: true, message: '请配置XXXXXX' }],
                    initialValue: this.radioType
                },
   }
}
}

**Comment by soho-smarthome** [comment]
<a-form-item label="名称">
                <a-radio-group
                    v-decorator="['radioGroup', rule.radioGroup]"
                    @change="onRadioChange">
                     <a-radio :style="radioStyle" :value="0">
                        <a-input-number v-model="model.param1" :min="0" :max="10000"/>
                        <span class="ant-form-text">AAAAAAAA</span>
                    </a-radio>
                    <a-radio :style="radioStyle" :value="1">
                        <a-input-number  v-model="model.param2" :min="0" :max="100" />
                        <span class="ant-form-text">BBBBBBBBB</span>
                    </a-radio>
</a-form-item>

**Comment by soho-smarthome** [comment]
‘
<a-form-item label="名称">
                <a-radio-group
                    v-decorator="['radioGroup', rule.radioGroup]"
                    @change="onRadioChange">
                     <a-radio :style="radioStyle" :value="0">
                        <a-input-number v-model="model.param1" :min="0" :max="10000"/>
                        AAAAAAAA
                    </a-radio>
                    <a-radio :style="radioStyle" :value="1">
                        <a-input-number  v-model="model.param2" :min="0" :max="100" />
                        BBBBBBBBB
                    </a-radio>
</a-form-item>
‘

**Comment by soho-smarthome** [comment]
`<a-form-item label="名称">
                <a-radio-group
                    v-decorator="['radioGroup', rule.radioGroup]"
                    @change="onRadioChange">
                     <a-radio :style="radioStyle" :value="0">
                        `<a-input-number` v-model="`model`.param1" :min="0" :max="10000"/>
                        <span class="ant-form-text">AAAAAAAA</span>
                    </a-radio>
                    <a-radio :style="radioStyle" :value="1">
                        <a-input-number  v-model="model.param2" :min="0" :max="100" />
                        <span class="ant-form-text">BBBBBBBBB</span>
                    </a-radio>
</a-form-item>`

**Comment by sendya** [comment]
不知道你说的不能回选 选中是否是我 demo 写的这样，如果不是，请提供复现
https://codesandbox.io/embed/proud-moon-qd6qu?fontsize=14&hidenavigation=1&theme=dark

**Comment by soho-smarthome** [comment]
> 不知道你说的不能回选 选中是否是我 demo 写的这样，如果不是，请提供复现
> https://codesandbox.io/embed/proud-moon-qd6qu?fontsize=14&hidenavigation=1&theme=dark

效果是类似的，我想问下，页面加载之后，不是设置了radioType=‘0’，默认没有选中，这个是什么原因？

**Comment by soho-smarthome** [comment]
难道是因为this.form.setFieldsValue({radioGroup: '1'})和this.form.setFieldsValue({radioGroup: 1})，这里不能用字符串，只能用number？

**Comment by sendya** [comment]
字符串和 number 能一样吗？你的 radio 值绑定是 number，却用 string 去设值，怎么可能选的上？

**Comment by soho-smarthome** [comment]
我试了下 在mounted()里面添加this.form.setFieldsValue({radioGroup: 1})，可以默认选中，但是我这边的代码其实是这样的：编辑页面里面有<a-steps>包含4个<a-step>，然后点击next()，在第4个step中，需要回显目前radioType的值为选中状态。
在list页面点击编辑时,代码为：
edit(record, index) {
            this.$refs.projectEdit.setFormValues(record)
            this.$refs.projectEdit.current = 0
            this.editIndex=index
            this.$refs.projectEdit.dealRule(record)
             this.projEditVisiable = true
        }
在setFormValues中，我通过如下：
this.form.setFieldsValue({radioGroup: 0})设置，并在next()方法中设置如下：
if(this.current == 2) {
     let fileds = ["xx", "yy"]
     let that = this
     that.form.validateFields(fileds, (err, values) => {
         if(!err) {
             //that.handleSwitch() 直接调用方法也没用
             that.form.setFieldsValue({radioGroup: 0}) //这里设置也没用
             that.current++
             return
         }
     }
   }

**Comment by sendya** [comment]
提供反馈能否直接提供 codesandbox 复现，或者至少贴代码用代码格式。

**Comment by soho-smarthome** [comment]
不好意思 操作不熟悉，第一次提问题单，弱弱的问下，:value="0"这个赋值给a-radio不是字符串吗？我在网上看到说initialValue的值要用字符串才能选中，所以这里radioType就用了字符串赋值。

**Comment by sendya** [comment]
`value="0"` 和 `:value="0"` 完全不相同。麻烦先学习  Vue 基础

**Comment by soho-smarthome** [comment]
(╯▽╰)，确实最近才开始的，有点菜，不好意思

**Comment by soho-smarthome** [comment]
`<a-radio-group
                    v-model="this.radioType"
                    v-decorator="['radioGroup', { rules: [{ required: true, message: '请配置XXXX' }], initialValue: 0 }]"
                    @change="onRadioChange">`
目前添加页面中的默认选中ok，initialValue: 0可以选中对应的:value="0"，编辑页面我这边还需要再确认。非常感谢@sendya

**Comment by soho-smarthome** [comment]
>你好，能不能帮我看下这个问题？
steps步骤条这边设置成功之后，再次打开时，step的数字1,2,3,4会出现空白的问题？
https://codesandbox.io/embed/charming-williams-jj482?fontsize=14&hidenavigation=1&theme=dark
