### ISSUE TITLE
表单中，不在页面显示的字段怎么获取或赋值？

### ISSUE THREAD

**Issue by mazhili0321** [vueComponent/ant-design-vue#1648]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.0

### Environment
windows10, chrome 79.0.3945.88, vue 2.6.10

### Steps to reproduce
1：使用模板语法，updateModuleForm: this.$form.createForm(this) 创建表单 。
2：现在我需要在updateModuleForm中放入id字段，但是id字段不在页面中显示，文档中没找到对应的方法？

### What is expected?
希望能给createForm所创建的表单赋不在页面中显示的字段以及对应的value

### What is actually happening?
没有找到给createForm创建的表单赋不在页面中显示的字段的办法

**Comment by sendya** [comment]
form-item 用 v-show 不显示，其他设定和正常表单一致

**Comment by mazhili0321** [comment]
> form-item 用 v-show 不显示，其他设定和正常表单一致

明白，谢谢！
