### ISSUE TITLE
希望分页器能和elementui 的分页一样  有一个layout属性,可以任意改变布局

### ISSUE THREAD

**Issue by jim888666** [vueComponent/ant-design-vue#1651]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
希望分页器能和elementui 的分页一样  有一个layout属性,可以任意改变布局

### What does the proposed API look like?
。。。。

**Comment by xiaolongGitHub1498** [comment]
同样也希望会加入这个功能

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/89245427-5c68ad80-d63b-11ea-941c-24e4a78ea7bb.png)
