### ISSUE TITLE
1.4.10版本 Table组件的可伸缩列拷贝示例代码执行报错

### ISSUE THREAD

**Issue by sixgay** [vueComponent/ant-design-vue#1659]
Module parse failed: Argument name clash (64:29)
File was processed with these loaders:
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/babel-loader/lib/index.js
 * ./node_modules/cache-loader/dist/cjs.js
 * ./node_modules/vue-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   name: "ResizeableTitle",
|   functional: true,
>   render: function render(h, h, props, children) {
|     var thDom = null;
|

**Comment by huangd-d** [comment]
我更新到1.4.10 按照示例使用也是出现这个问题，目前还是无法解决。

**Comment by sendya** [comment]
请提供复现。 请开新 issue 提问，不要在关闭的 issue 中进行讨论
