### ISSUE TITLE
a-dropdown中包裹<router-link>标签，组件会失效

### ISSUE THREAD

**Issue by mengera88** [vueComponent/ant-design-vue#1661]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
mac os sierra 10.12.6 chrome 79.0.3945.88  vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-nnf6l)

### Steps to reproduce
<a-dropdown placement="bottomRight">
<router-link to="/d">配置
<a-icon type="down"/>
</router-link>
<a-menu slot="overlay">
<a-menu-item class="item" :key="item.id" v-for="item in data">
<span>{{item.title}}</span>
</a-menu-item>
</a-menu>
</a-dropdown>

### What is expected?
成功渲染“配置”，并且hover至“配置”时，准确出现dropdown下拉框

### What is actually happening?
报错：
[Vue warn]: Error in render: "TypeError: Cannot read property 'resolve' of undefined"
TypeError: Cannot read property 'resolve' of undefined

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-qks3v

**Comment by tangjinzhou** [comment]
请正确注册vue-router

**Comment by mengera88** [comment]
> 请正确注册vue-router

sorry，忘记写上去了，我现在正确填写了router，为啥我这里还是不行呢，我看了你的链接是可以的。我这边不行 地址： https://codesandbox.io/s/vue-antd-template-nnf6l

**Comment by mengera88** [comment]
恩 我知道原因   a-dropdown标签下一定要写span标签作为一级子元素  如果直接写router-link标签就会不生效
