### ISSUE TITLE
uoload组件上传图片墙的时候，当图片超过一排，那个上传的框定位有问题

### ISSUE THREAD

**Issue by Thlq** [vueComponent/ant-design-vue#1662]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
windows

### Reproduction link
[https://www.antdv.com/components/upload-cn/](https://www.antdv.com/components/upload-cn/)

### Steps to reproduce
如上

### What is expected?
定位正常

### What is actually happening?
定位不正常

![image](https://user-images.githubusercontent.com/21211777/71461823-24b79e80-27ec-11ea-9a83-f774680ef10e.png)

**Comment by wangxueliang** [comment]
麻烦提供复现链接，谢谢

**Comment by donglinkai** [comment]
+1 ,
我有点怀疑你和我在做一个项目
