### ISSUE TITLE
有时点击通知Notification的右上侧的关闭按钮，可能会导致关闭整个页面

### ISSUE THREAD

**Issue by jacktanxd** [vueComponent/ant-design-vue#1664]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
win10,360浏览器，vue 2.5.22

### Reproduction link
[https://www.antdv.com/components/notification-cn/](https://www.antdv.com/components/notification-cn/)

### Steps to reproduce
1. this.$notification.open({
key: noticKey,
icon: <a-icon type="fire" style="color: red" />,
message: '新警情 ('   total   ')',
style: {
width: '300px'
},
duration: null,
placement: 'bottomLeft',
onClose: close,
description: descNode.$vnode
})
2. 点击通知关闭按钮
3. 可能会导致关闭整个页面

### What is expected?
通知对话框关闭

### What is actually happening?
整个页面关闭

**Comment by sendya** [comment]
无法进行合理场景测试，请提供 codesandbox 复现

**Comment by ChenLuoi** [comment]
`onClose: close`
此处bind的对象为window，实际调用了window.close()方法，导致界面非预期地关闭
