### ISSUE TITLE
当modal的mask属性为false的时候，最外层仍然有一个宽高100%的容器，是不是不太合理？

### ISSUE THREAD

**Issue by fullmoooooon** [vueComponent/ant-design-vue#1667]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当把modal的mask属性设置为false的时候，最外层还是有个宽高为100%的容器，

<div tabindex="-1" role="dialog" aria-labelledby="rcDialogTitle0" class="ant-modal-wrap ant-modal-centered">

从而导致无法点击弹窗后面的内容，

比如modal是通过点击一组button生成的，我希望点击不同的button显示不同的modal（或者说替换modal里的内容），但是不管mask设置为false还是true，最外层都有一个宽高100%的容器，导致在modal没关闭的情况下无法点击任何弹窗以外的内容。

### What does the proposed API look like?
mask为true的时候有这个宽高100%的遮罩层，当mask为false的时候去掉这个遮罩层是不是更合理，更灵活？

**Comment by tangjinzhou** [comment]
你可以使用css强制覆盖 100%    你这个交互还是比较非常规的，组件不会修改逻辑

**Comment by fullmoooooon** [comment]
> 你可以使用css强制覆盖 100% 你这个交互还是比较非常规的，组件不会修改逻辑

它这个100%是modal的最外层容器，强制覆盖modal不就显示不出来了
