### ISSUE TITLE
menu forceSubMenuRender 失效原因

### ISSUE THREAD

**Issue by edifierx666** [vueComponent/ant-design-vue#1668]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
谷歌79,vue 2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
menu forceSubMenuRender 属性无效

### What is expected?
forceSubMenuRender 生效

### What is actually happening?
forceSubMenuRender

![image](https://user-images.githubusercontent.com/39356752/71506633-b858a000-28bc-11ea-96bb-f9e2bcf71985.png)
subMenu props异常
![image](https://user-images.githubusercontent.com/39356752/71506645-ca3a4300-28bc-11ea-9757-6d7c16a40ccf.png)
暂时解决

**Comment by tangjinzhou** [comment]
方便的话 可以 PR 给我们

**Comment by edifierx666** [comment]
https://github.com/vueComponent/ant-design-vue/blob/1a6ba14d59dc104961aab0ec3b4df7ffc6381c0c/components/_util/proxyComponent.jsx#L12

我对源码不熟, 这一行改成  `props[k] = { ... tempProps[k], required: false };`  其他不知道会有什么影响

**Comment by edifierx666** [comment]
https://github.com/vueComponent/ant-design-vue/pull/1676
