### ISSUE TITLE
Progress v-solt:format 不支持 v-slot ant-design-vue 版本1.4.10 vue版本2.9.6

### ISSUE THREAD

**Issue by ZjHxq** [vueComponent/ant-design-vue#1679]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
vue 2.9.6

### Reproduction link
[https://www.antdv.com/components/progress-cn/](https://www.antdv.com/components/progress-cn/)

### Steps to reproduce
Progress v-solt:format 不支持 v-slot ant-design-vue 版本1.4.10 vue版本2.9.6

### What is expected?
Progress v-solt:format 不支持 v-slot ant-design-vue 版本1.4.10 vue版本2.9.6

### What is actually happening?
Progress v-solt:format 不支持 v-slot ant-design-vue 版本1.4.10 vue版本2.9.6

**Comment by sendya** [comment]
https://codesandbox.io/embed/elegant-sound-12n8z?fontsize=14&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark

vue2.6.10+ 没有你描述的问题，如果你确定有问题，请提供复现

**Comment by tangjinzhou** [comment]
@ZjHxq vue 并没有 2.9.6 版本

**Comment by ZjHxq** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"tangjinzhou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 晚上9:18
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"Angel~~~"<986864752@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] Progress v-solt:format 不支持 v-slot ant-design-vue 版本1.4.10 vue版本2.9.6 (#1679)




@ZjHxq vue 并没有 2.9.6 版本
