### ISSUE TITLE
Theme for light and dark theme ( 主题为明暗主题) ?

### ISSUE THREAD

**Issue by MisterJ936** [vueComponent/ant-design-vue#1689]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
This feature will help people to read properly. Specially people who are not good in a bright or white colored theme that might hurt eye. While dark theme can reduce those kind of things because dark theme are easy to read. And its really helpful for people who dont like to much light.

此功能将帮助人们正确阅读。特别是对明亮或白色主题不好的人可能会伤害眼睛。深色主题可以减少此类情况，因为深色主题易于阅读。对于那些不喜欢太多光线的人来说，它确实很有帮助。

### What does the proposed API look like?
Their can be a function like this.$ant.theme('dark'); or this.$ant.theme('light'); ,,, the most important is. Their should be an easy way to switch theme from light to dark theme and vise versa.

它们可以是这样的函数。$ ant.theme（'dark'）;或this。$ ant.theme（'light'）; ，，，最重要的是。它们应该是将主题从浅色主题转换为深色主题，反之亦然的简便方法。

**Comment by tangjinzhou** [comment]
You can switch the theme by customizing the less variable

**Comment by zhou881117** [comment]
how to change dark theme？
