### ISSUE TITLE
特么的简直就是个神坑，，<a-select-option>报错问题

### ISSUE THREAD

**Issue by Kavf** [vueComponent/ant-design-vue#1690]
<a-select-option>报错问题，可能是因为只引入注册了Select组件，其实还要引入注册 Option 组件，组件注册时要使用 components:{ASelectOption:Select.Option} ,官方文档找了个遍都没有提到这一点，谁能想到是在Select组件下面，真特么神坑。。。

**Comment by zkwolf** [comment]
并不需要，按需引入的话Vue.use(Select)会自动引入option

**Comment by Sdoy** [comment]
issues找文档也是真滴牛逼

**Comment by zyqwst** [comment]
> 并不需要，按需引入的话Vue.use(Select)会自动引入option

按需引入啊，用官方的这种方式试试看，直接在自己的组件中引入antd组件
import { Select } from 'ant-design-vue' 报错
```
vue.runtime.esm.js?17dc:619 [Vue warn]: Error in data(): "TypeError: Cannot read property 'children' of undefined"

found in

---> <Select>
       <ASelect>
         <JsonSchemaEditor> at packages/json-schema-editor/main.vue
           <App> at examples/App.vue
             <Root>
```

**Comment by li1164267803** [comment]
楼主的办法可以解决问题，亲测

**Comment by caixiaomao** [comment]
同被坑了 🤣
