### ISSUE TITLE
upload组件的disabled属性使用没有效果，不会隐藏删除按钮

### ISSUE THREAD

**Issue by donglinkai** [vueComponent/ant-design-vue#1692]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
chrome 版本 79.0.3945.88（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-gould-491bb?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce

````
<Upload
action="#"
@preview="handlePictureCardPreview"
listType="picture-card"
:fileList="fileList"
:multiple="true"
disabled
@change="fileChange"
:openFileDialogOnClick="false"
>
````

我试了下跟ant-design里面disabled效果不一样，antd可以隐藏这个按钮
### What is expected?
隐藏删除按钮

### What is actually happening?
disabled失效，无法隐藏删除按钮

**Comment by zzzttt1017** [comment]
+1

**Comment by tangjinzhou** [comment]
可以先自行添加
```css
.ant-upload-disabled {
   display: none;
}
```
