### ISSUE TITLE
:切换表单item组件如果加校验会报错:Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by curry-Yang** [vueComponent/ant-design-vue#1695]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome，vue2.5.21

### Reproduction link
[https://codepen.io/yanglu1019/pen/roObRO?editors=1111](https://codepen.io/yanglu1019/pen/roObRO?editors=1111)

### Steps to reproduce
切换表单后，再进行选择会报错

### What is expected?
正常切换选择

### What is actually happening?
报错

**Comment by molvqingtai** [comment]
同样的问题

**Comment by zkwolf** [comment]
用v-show试试？

**Comment by yanglu1019** [comment]
@tangjinzhou ,这个麻烦看下是否为bug

**Comment by EmiyaYang** [comment]
> 用v-show试试？

用 v-show 会加入验证的.

**Comment by tangjinzhou** [comment]
建议先用不同的 decoratorId 解决

**Comment by tangjinzhou** [comment]
vue 中组件 mount 先于 destroy 执行，如果是相同decoratorId，无法正确挂载，建议使用不同的decoratorId

**Comment by systameZ** [comment]
我在组件切换后，调用form对象的recoverClearedField(decoratorId)，貌似可以暂时解决这个报错
