### ISSUE TITLE
A way to use DatePicker without moment.js

### ISSUE THREAD

**Issue by vedmant** [vueComponent/ant-design-vue#1696]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
NA

### Reproduction link
[https://not-applicable.com](https://not-applicable.com)

### Steps to reproduce
Hi, I have a problem DatePicker, the issue is that it hard linked to require moment.js library, is there a way to remove moment.js dependency from DatePicker and use for example luxon or date-fns library?

### What is expected?
Should not depend on moment.js

### What is actually happening?
It depends on moment.js

**Comment by tangjinzhou** [comment]
that's not allowed
