### ISSUE TITLE
table组件，scroll设置y时，下拉滚动条出现的不合理

### ISSUE THREAD

**Issue by masterlirui** [vueComponent/ant-design-vue#1697]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Win10，Chrome79.0.3945(64位)，Vue(2.5.17)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-cs59w)

### Steps to reproduce
a-table设置 :scroll添加 y:400

### What is expected?
未超过y设置值不要展示滚动条占位符。

### What is actually happening?
给scroll.y设置值后，表格内容超过y设置的值出现滚动条占位符（正常）且可以正常下拉滚动。但是表格内容如果没有超过Y设置的值，右侧也会出现滚动条占位符

**Comment by chaplin0** [comment]
同问，而且表头也会出现滚动条占位

**Comment by tangjinzhou** [comment]
update to 1.5.x https://codesandbox.io/s/vue-antd-template-5vubm

**Comment by celizi** [comment]
你要固定表格宽度，保留一列（备注列）长度不设定

增加下面样式 去掉一直显示的滚动条
#body-table .ant-table-body{
overflow:auto !important;
}
#body-table .ant-table-header{
overflow:hidden !important;
margin-bottom: 0px !important;
}
然后出现横向滚动条超出问题，需要动态配置标题div的宽度为你的固定宽度+浏览器滚动条宽度（大于也可以，自动会对齐）
this.$refs.bodyTable.querySelectorAll('.ant-table-header .ant-table-fixed')[0].style = "width: "+1250 +"px"

**Comment by celizi** [comment]
![mao](https://user-images.githubusercontent.com/27724598/82792438-fffe4a80-9ea1-11ea-9008-eb402cb25ac3.gif)
