### ISSUE TITLE
Table 指定defaultExpandedRowKeys之后， 点击展开无响应

### ISSUE THREAD

**Issue by doghap** [vueComponent/ant-design-vue#1698]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Vue2.6

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
Table指定 defaultExpandedRowKeys

### What is expected?
初始化时展开defaultExpandedRowKeys提供的节点， 并不影响之后的展开操作

### What is actually happening?
指定之后无法展开其他节点

**Comment by sendya** [comment]
能否提供复现？我这边尝试没问题
