### ISSUE TITLE
【BUG】button组件的block属性设置无效

### ISSUE THREAD

**Issue by webees** [vueComponent/ant-design-vue#170]
ant-design-vue版本：最新
electron-vue版本：最新

代码如下：
`<a-button block>Default</a-button>`

效果如下：
![image](https://user-images.githubusercontent.com/5155291/45212029-6e623a00-b2c6-11e8-8997-8c3d7070a723.png)

期望结果：
![image](https://user-images.githubusercontent.com/5155291/45212083-9356ad00-b2c6-11e8-94c1-a19575abd11b.png)

有其他同学遇到这个问题吗？

**Comment by tangjinzhou** [comment]
1.1.0-beta.0版本才有的功能  
PS：请使用issue helper提交issue
