### ISSUE TITLE
upload 上传文件报错，上传不上去！

### ISSUE THREAD

**Issue by 1310111704** [vueComponent/ant-design-vue#1702]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Vue最新版本

### Reproduction link
[https://www.antdv.com/components/upload-cn/#api](https://www.antdv.com/components/upload-cn/#api)

### Steps to reproduce
upload 上传文件报错，上传不上去！

### What is expected?
upload 上传文件报错，上传不上去！

### What is actually happening?
upload 上传文件报错，上传不上去！

---
upload 上传文件报错，上传不上去！

**Comment by wangxueliang** [comment]
官网上传地址出了一些问题，请放心使用，抱歉
