### ISSUE TITLE
table组件 可伸缩列  复制代码 终端报错

### ISSUE THREAD

**Issue by huangd-d** [vueComponent/ant-design-vue#1703]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
vue:2.6.10  Chrome75

### Reproduction link
[https://github.com/huangd-d/ant-design-BUG](https://github.com/huangd-d/ant-design-BUG)

### Steps to reproduce
yarn => yarn serve  =>终端报错

### What is expected?
不报错

### What is actually happening?
文档例子直接复制，就报错

**Comment by wangxueliang** [comment]
vue-draggable-resizable 确少依赖

**Comment by wangxueliang** [comment]
目测缺少这个vue-draggable-resizable依赖  仔细看看哈

**Comment by huangd-d** [comment]
> 目测缺少这个vue-draggable-resizable依赖 仔细看看哈

你拉下代码  yarn add vue-draggable-resizable;  一样的结果

**Comment by wangxueliang** [comment]
https://www.antdv.com/docs/vue/getting-started-cn/   看文档完善的工程，组件都没注册

**Comment by huangd-d** [comment]
> https://www.antdv.com/docs/vue/getting-started-cn/ 看文档完善的工程，组件都没注册

谢谢你提醒， 但是我完整注册之后依然是同样结果。

**Comment by sendya** [comment]
请参考实例

https://codesandbox.io/embed/suspicious-hill-ibpht?fontsize=14&hidenavigation=1&theme=dark

**Comment by huangd-d** [comment]
各位大佬，巨佬麻烦官方文档修改好， 看我github 已修改好

**Comment by sendya** [comment]
不懂你在说什么修改过了，能否清楚描述一下？
另外项目 16 天没提交过代码了，从发布 demo 那天起没改过。

你可以看我写给你的 demo：https://codesandbox.io/embed/suspicious-hill-ibpht?fontsize=14&hidenavigation=1&theme=dark

这就是从官网文档 demo 复制来的

**Comment by huangd-d** [comment]
> 不懂你在说什么修改过了，能否清楚描述一下？
> 另外项目 16 天没提交过代码了，从发布 demo 那天起没改过。
> 
> 你可以看我写给你的 demo：https://codesandbox.io/embed/suspicious-hill-ibpht?fontsize=14&hidenavigation=1&theme=dark
> 
> 这就是从官网文档 demo 复制来的

看我 app.vue ResizeableTitle 函数参数。 你与官网对比下。

**Comment by sendya** [comment]
> 看我 app.vue ResizeableTitle 函数参数。 你与官网对比下。

这就是半小时前从官网复制过来的

**Comment by huangd-d** [comment]
> > 看我 app.vue ResizeableTitle 函数参数。 你与官网对比下。
> 
> 这就是半小时前从官网复制过来的

好吧，那我本地 安装的依赖包，那个 ResizeableTitle函数返回的参数和官网不一样的。我修改后本地就可以渲染出来了。
