### ISSUE TITLE
table组件设置scroll后会导致表格频繁的重新渲染

### ISSUE THREAD

**Issue by Xiu2017** [vueComponent/ant-design-vue#1705]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
系统版本：Windows 10 教育版 1909 ；浏览器版本：Chrome 79.0.3945.117（正式版本）（64 位）；Vue版本：2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-haslett-l8y42)

### Steps to reproduce
打开重现链接，在两个输入框中任意输入内容，“幸运数字”一列会随着变化，去掉table的scroll后，任意输入内容，“幸运数字”一列则不会改变。

### What is expected?
只有table使用到的相关变量改变，或者页面大小发生变化，才会导致表格重新渲染

### What is actually happening?
设置scroll后，当前Vue实例的任何变量发生变化，都会导致表格重新渲染

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/reverent-waterfall-vx8g2

**Comment by tangjinzhou** [comment]
把 scroll 的配置改成变量存储在data中

**Comment by Xiu2017** [comment]
十分感谢，但反复测试之后，发现设置了@change事件后也有这个问题：https://codesandbox.io/s/purple-dawn-pkb3x

**Comment by Xiu2017** [comment]
> 把滚动的配置改成变量存储在数据中

十分感谢，但反复测试之后，发现设置了@change事件后也有这个问题：https://codesandbox.io/s/purple-dawn-pkb3x
