### ISSUE TITLE
select组件中的popupScroll事件没有返回scrollTop或offsetHeight相关的数据

### ISSUE THREAD

**Issue by 663759994** [vueComponent/ant-design-vue#1708]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
macos，火狐：72.0.1，chrome：79.0.3945.117，VUE2.6.10

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
直接复制文档上的demo

### What is expected?
应该有返回scrollTop或offsetHeight相关的数据来给我判断是否到达了底部，来实现分页加载，。

### What is actually happening?
实际上返回来一些其他的东西，仔细查看来返回值，也并没有看到相关的字眼。这个在react上的版本似乎是有的

**Comment by wangxueliang** [comment]
有事件对象，自己获取啊......

**Comment by DiamondsZz** [comment]
@663759994   解决了吗

**Comment by DiamondsZz** [comment]
直接打印事件对象的target.scrollTop是有值的

在控制台里面查看事件对象的target.scrollTop却是0

很奇怪。。。

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/affectionate-davinci-g58pd?file=/src/App.vue

触发的频率可以自己优化
