### ISSUE TITLE
Slider with VNodes

### ISSUE THREAD

**Issue by SchroterQuentin** [vueComponent/ant-design-vue#171]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0-beta.0

### Environment
Windows 10, firefox and chrome, vue 2.5.15, vue-antd-ui 1.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4rmvl4l5v7)

### Steps to reproduce
Put VNodes in marks of slider does not render

### What is expected?
It's expected to render the VNodes

### What is actually happening?
Nothing is happening

**Comment by tangjinzhou** [comment]
你那是对象，不是VNode
参考：https://codesandbox.io/s/316m17m501

**Comment by SchroterQuentin** [comment]
Thanks for the answer, is there any way to do the same but with only javascript ?
I do not use this kind of syntax.

**Comment by tangjinzhou** [comment]
Temporarily not supported, the next version can be added to support `render` and `slot`

**Comment by SchroterQuentin** [comment]
Ok nice, thanks ! 
Which version will allow this behavior ? Can I help ?

**Comment by tangjinzhou** [comment]
You can submit any ideas as pull requests or as GitHub issues.

**Comment by tangjinzhou** [comment]
please update to 1.1.1
now support `function`
