### ISSUE TITLE
Tree组件中，treeNode配置scopedSlots: { icon: 'icon' }，无法获取icon插槽的slot-scope值

### ISSUE THREAD

**Issue by biterabbit** [vueComponent/ant-design-vue#1711]
Version
1.4.10

Environment
win10 1809，chrome 78 ，vue 2.5.2

Reproduction link
https://biterabbit.github.io/ant-design-vue-demo/dist/index.html#/

Steps to reproduce
Tree组件中，treeNode配置scopedSlots: { icon: 'icon' }

What is expected?
可以获取icon插槽的slot-scope值

What is actually happening?
无法获取icon插槽的slot-scope值，返回了一个方法而不是数据

需要定制tree的图标时，具体的图标在treeNode的数据上，但现在无法获取icon处的插槽参数。经过查看ant-design-vue源码，发现Tree.jsx文件在icon处配置错误，希望能尽快修复

**Comment by tangjinzhou** [comment]
没太懂你的意思   既然发现了问题，方便的话可以pr

**Comment by biterabbit** [comment]
这个问题我已经解决并提交到你们的仓库了，bug号1711，但这个issue还没关闭------------------ 原始邮件 ------------------
发件人: "tangjinzhou"<notifications@github.com>
发送时间: 2020年2月6日(星期四) 下午5:48
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "biterabbit"<1312335750@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] Tree组件中，treeNode配置scopedSlots: { icon: 'icon' }，无法获取icon插槽的slot-scope值 (#1711)



没太懂你的意思   既然发现了问题，方便的话可以pr
 
&mdash;

**Comment by tangjinzhou** [comment]
并没有看到你提交的 pr

**Comment by biterabbit** [comment]
提交几周前就被合并回去了，bug号1711------------------ 原始邮件 ------------------
发件人: "tangjinzhou"<notifications@github.com>
发送时间: 2020年2月7日(星期五) 上午10:04
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "biterabbit"<1312335750@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] Tree组件中，treeNode配置scopedSlots: { icon: 'icon' }，无法获取icon插槽的slot-scope值 (#1711)



并没有看到你提交的 pr
 
&mdash;

**Comment by xxbld** [comment]
@tangjinzhou 

请问tree 不支持全局的 scopedSlots吗？

```jsx
<Tree
    treeData={data}
    showLine={true}
    showIcon={true}
    scopedSlots={{
        title: (title: string) => {
            return (<div>{title}1</div>)
        }
    }}
/>
```
