### ISSUE TITLE
使用浏览器引入方式时，table 列的fixed属性渲染错误

### ISSUE THREAD

**Issue by weechang** [vueComponent/ant-design-vue#1715]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
window10 chrome79.0.3945.117   vue@2.6.10

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
```
<!DOCTYPE html>
<html lang="zh-cn">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@1.4.8/dist/antd.css"/>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.10/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/momentjs@1.1.17/moment.js"></script>
<script src="https://cdn.jsdelivr.net/npm/ant-design-vue@1.4.10/dist/antd.js"></script>
</head>
<body>
<div id="app" style="padding: 20px">
<a-table
:columns="columns"
:row-key="record => record.id"
:data-source="dataList">
</a-table>
</div>
<script>
let app = new Vue({
el: '#app',
data: function () {
return {
columns: [
{
title: '用户名',
dataIndex: 'username',
key: 'username'
},
{
title: '邮箱',
dataIndex: 'email',
key: 'email'
},
{
title: '操作',
dataIndex: 'action',
key: 'action',
fixed: 'right'
}
],
dataList: [
{
id: 1,
username: 'admin',
email: 'xxx@abc.com'
}
]
}
}
});
</script>
</body>
```

### What is expected?
fixed 属性列能正常展示

### What is actually happening?
fixed属性列有大片空格

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/72411912-04558100-37a7-11ea-84a0-e4b6c01eef88.png)
