### ISSUE TITLE
InputNumber 数字输入框 官方DEMO第一个演示，输入16个9，变成10000000000000000

### ISSUE THREAD

**Issue by ximan** [vueComponent/ant-design-vue#1717]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
无

### Reproduction link
[https://www.antdv.com/components/input-number-cn/](https://www.antdv.com/components/input-number-cn/)

### Steps to reproduce
1、打开https://www.antdv.com/components/input-number-cn/
2、在第一个案例的input框里删掉默认值3，一直输入9
3、输到第16位，变成10000000000000000

### What is expected?
由于此案例里有:max="10"，期望只能输入一个9，就无法输入

### What is actually happening?
可以一直输入

**Comment by sendya** [comment]
react input-number 有相同情况
https://ant.design/components/input-number/

https://codesandbox.io/s/condescending-colden-cudev

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/72436382-3d0f4d80-37db-11ea-9fbf-e2b7a3d30b78.png)
超js能够处理的数字限制了
