### ISSUE TITLE
表格table的宽度属性，，如果内容是全英文的的时候，width属性失效

### ISSUE THREAD

**Issue by dachengzima** [vueComponent/ant-design-vue#1718]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格table的宽度属性，，如果内容是全英文的的时候，width属性失效

### What does the proposed API look like?
可以支持英文和中文的情况下，宽度属性都生效

**Comment by sendya** [comment]
这是由于文字分词导致的，请先自行处理。
有关文字无法自动分词换行的问题，可以百度如何写强制换行的 css
