### ISSUE TITLE
Will the ant-design 4.0 merging work start soon? 

### ISSUE THREAD

**Issue by ngloom** [vueComponent/ant-design-vue#1719]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
There're some new features in ant design 4.0 ( summary row in data table etc..) and the current version came to v4.0-rc1, really hope to see the new feature in future ant-design-vue !

### What does the proposed API look like?
Should like the new features come out in Ant design 4.0.
Thanks for the hard working !

**Comment by dzcpy** [comment]
Any updates? ant-design 4.0 is out 🚀

**Comment by awprice** [comment]
I'm also interested in Ant Design 4.0 as well, especially the new dark theme/mode.

**Comment by binaryfire** [comment]
+1 for updating to v4.0. Any news on when this will happen?

**Comment by dzcpy** [comment]
For anyone interested, ant-design 4.0 update is planned
Here is the feature list of version 2.0, it's in Chinese though
https://github.com/vueComponent/ant-design-vue/issues/1911

**Comment by dzcpy** [comment]
Any updates? Is this feature goning to be implemented in 2.0?
