### ISSUE TITLE
table组件 可伸缩列 导致排序失效

### ISSUE THREAD

**Issue by 1158119024** [vueComponent/ant-design-vue#1720]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
vue 2.6.10  Chrome79

### Reproduction link
[https://github.com/1158119024/ant-design-BUG.git](https://github.com/1158119024/ant-design-BUG.git)

### Steps to reproduce
配置完可伸缩列 => sorter => 点击没有触发change事件 => 无排序

### What is expected?
触发事件，可排序

### What is actually happening?
没有触发change事件，排序无效

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/72408461-fb13e680-379d-11ea-9cbc-be78984ed628.png)

**Comment by 1158119024** [comment]
是vue/cli的原因吗，我都是3以上的版本，然后那个参数h不能写，一写就报重复的参数

**Comment by LittleAngelLittleStar** [comment]
配置完可伸缩列 => sorter => 点击没有触发change事件 => 无排序，请问您对于这个问题有好的解决方案了吗？

**Comment by zheng-qipeng** [comment]
> 是vue / cli的原因吗，我都是3以上的版本，然后那个参数h不能写，一写就报重复的参数

同样问题  前阵子提了issue #1870

**Comment by Vincent-X** [comment]
same question

**Comment by anncwb** [comment]
一样的问题

**Comment by jzkHook** [comment]
这个问题解决嘛？
