### ISSUE TITLE
使用v-decorator验证form中input为数字时，输入数字检验失败，提示错误信息。

### ISSUE THREAD

**Issue by nianlun** [vueComponent/ant-design-vue#1722]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
ant-design-vue: 1.4.10     vue: 2.5.11

### Reproduction link
[https://www.antdv.com/components/form-cn/#components-form-demo-dynamic-rules](https://www.antdv.com/components/form-cn/#components-form-demo-dynamic-rules)

### Steps to reproduce
使用v-decorator验证form中input为数字时，输入数字检验失败，提示错误信息。
`<a-input v-decorator="['weightValue',{rules: [{ required: true,type:'number',message: '货重为必填项'}]}]" />`

### What is expected?
输入数字检验失败，提示错误信息

### What is actually happening?
输入数字检验通过，输入除数字以外的字符检验失败，提示错误信息

**Comment by sendya** [comment]
请直接使用 input-number

**Comment by li-guojiang** [comment]
加前缀和后缀或前置/后置标签   input-number 支持吗？

**Comment by li-guojiang** [comment]
> 请直接使用 input-number
加前缀和后缀或前置/后置标签 input-number 支持吗？

**Comment by dzcpy** [comment]
建议可以直接提pull request
