### ISSUE TITLE
Menu 组件使用单文件方式递归生成菜单，select和click方法取不到title

### ISSUE THREAD

**Issue by youki666** [vueComponent/ant-design-vue#1723]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
macos  10.15

### Reproduction link
[https://github.com/youki666/ant-vue.git](https://github.com/youki666/ant-vue.git)

### Steps to reproduce
就是那个单文件递归菜单click和select方法取不到title

### What is expected?
希望点击菜单能得到该item的title值

### What is actually happening?
单文件递归的时候click事件title取不到

**Comment by sendya** [comment]
事件名称 | 说明 | 回调参数
-- | -- | --
click | 点击 MenuItem 调用此函数 | function({ item, key, keyPath })
deselect | 取消选中时调用，仅在 multiple 生效 | function({ item, key, selectedKeys })
openChange | SubMenu 展开/关闭的回调 | function(openKeys: string[])
select | 被选中时调用 | function({ item, key, selectedKeys })


文档说的 item 是 VueComponent Menu.Item 这个组件，并不是你的当前数组 item

**Comment by youki666** [comment]
那种单文件递归树生成的菜单如何点击获取数据呢，您能给点思路吗，我看它文档说使用单文件方式递归生成菜单，因组件内部会动态更改a-sub-menu的属性，如果拆分成单文件，无法将属性挂载到a-sub-menu上，需要自行声明属性并挂载。
