### ISSUE TITLE
全局化配置getPopupContainer不起作用

### ISSUE THREAD

**Issue by YoungHF** [vueComponent/ant-design-vue#1729]
Version
1.4.10

Environment
vue:2.6.10 Chrome75

Reproduction link
https://www.antdv.com/components/config-provider-cn/

Steps to reproduce
在a-config-provider中使用getPopupContainer这个API，将弹出框（Select, Tooltip, Menu 等等）渲染在父节点上，可是却不起作用

What is expected?
将弹出框（Select, Tooltip, Menu 等等）渲染在父节点上

What is actually happening?
使用了全局化配置getPopupContainer，可是弹出框仍然渲染在body上，滚动的时候位置不动，帮忙看下哪里出了问题？

![3831579072719_ pic_hd](https://user-images.githubusercontent.com/20768289/72413681-4bde0c00-37ab-11ea-9f71-56a0765ae3a2.jpg)
![5861579073308_ pic](https://user-images.githubusercontent.com/20768289/72413853-b2632a00-37ab-11ea-8233-640f33d0edf8.jpg)

**Comment by tangjinzhou** [comment]
a-config-provider 不是 a-locale-provider
