### ISSUE TITLE
文档可能有误

### ISSUE THREAD

**Issue by dengxiaozhen** [vueComponent/ant-design-vue#173]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0-beta.0

### Environment
Mac OS 10.13.6 ，chrome 69，Vue 2.9.6

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/form-cn/](https://vuecomponent.github.io/ant-design-vue/components/form-cn/)

### Steps to reproduce
在“表单”组件的登录框组件，demo 示例的源码是 react 的语法，并不是 vue 的语法

### What is expected?
希望修正下文档

### What is actually happening?
希望修正下文档

![image](https://user-images.githubusercontent.com/8529528/45251148-cefb8080-b373-11e8-8a6b-6793e089a8e7.png)

**Comment by tangjinzhou** [comment]
纠正一下，不是react语法，是jsx语法，vue也是支持的，而且我们推荐在vue中使用jsx语法，更加方便实现复杂的功能。
demo没有问题，如果你一定要使用template语法，可以参考form相关demo自行更改。

**Comment by dengxiaozhen** [comment]
@tangjinzhou 多谢大佬指点
