### ISSUE TITLE
Firefox浏览器，form表单输入中文输入法，第一次输入无法输入内容；之后可以输入内容

### ISSUE THREAD

**Issue by zkx1** [vueComponent/ant-design-vue#1736]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
windows10, Firefox 72.0.1, vue 2.6.10

### Reproduction link
[https://antdv.com/components/form-cn/](https://antdv.com/components/form-cn/)

### Steps to reproduce
1.切换输入法至中文状态
2.输入中文字符点击空格确认
3.输入框中没有内容
4.再次输入，输入框中正确输入内容

### What is expected?
可以正确输入内容

### What is actually happening?
不能正确输入

**Comment by AmmyXu** [comment]
这个问题解决了么？1.5.3版本还能复现

**Comment by tangjinzhou** [comment]
1.5.5
