### ISSUE TITLE
【BUG】把内容内嵌到 Spin 中，页面reload会导致嵌入的内容闪烁

### ISSUE THREAD

**Issue by webees** [vueComponent/ant-design-vue#174]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0-beta.0

### Environment
electron-vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w6o3ol64mk)

### Steps to reproduce
<a-spin :spinning="spinning">
<div class="spin-content">
可以点击‘切换’按钮，控制本区域的spin展示。
</div>
</a-spin>

### What is expected?
页面在reload时，嵌到 Spin 中的内容不会闪烁。

### What is actually happening?
【BUG】把内容内嵌到 Spin 中，页面reload会导致嵌入的内容闪烁。请不断刷新页面体验。

**Comment by adamchenwei** [comment]
I tried on Mac OS Chrome, it appears normal from the demo.
Maybe its environment or graphic specific?

**Comment by webees** [comment]
`<div class="ant-spin-container ant-spin-blur"> `标签在刷新后会变成`<div class="ant-spin-container ant-spin-blur fade-enter fade-enter-active">`，然后在大约200ms后恢复为`<div class="ant-spin-container ant-spin-blur"> `，这个过程使内容有闪烁。
请检查`  fade-enter fade-enter-active`

@adamchenwei Note that the "fade-enter fade-enter-active" change after refreshing. I think this is caused by this, refresh page should not have such a switch.

**Comment by webees** [comment]
威武！

**Comment by tangjinzhou** [comment]
please update to 1.1.0
