### ISSUE TITLE
使用treeData属性的directory-tree无法正确使用shift全选

### ISSUE THREAD

**Issue by ztail** [vueComponent/ant-design-vue#1744]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Current ant-design-vue version: 1.4.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-kpt0n)

### Steps to reproduce
```
var children = this.$slots['default'] || [];
```
如果使用treeData, default为undefined

### What is expected?
使用treeData属性的directory-tree可以使用shift全选

### What is actually happening?
使用treeData属性的directory-tree无法正确使用shift全选

**Comment by dzcpy** [comment]
建议如果改的话配一个选项，控制是否可以开启shift多选。我需要做的功能正好只允许单选，如果修复这个问题以后一下可以多选反而麻烦了
