### ISSUE TITLE
Unable to use most components?

### ISSUE THREAD

**Issue by Bubuchenko** [vueComponent/ant-design-vue#175]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
Windows 10, Chrome 69, Vue 2.2.2

### Reproduction link
[https://github.com/Bubuchenko/AntdTest](https://github.com/Bubuchenko/AntdTest)

### Steps to reproduce
1. Add a component (e.g. a-input) to a vue component
2. Open application/page with said component
3. See console [Vue warn]: Error in render function: "TypeError: Cannot read property 'change.value' of undefined"

### What is expected?
For the input component to be rendered / available in the DOM

### What is actually happening?
The input is not added to the dom nor visible, and an error is shown in the console.

**Comment by tangjinzhou** [comment]
please update vue to 2.5.0+

**Comment by Bubuchenko** [comment]
Update worked, thank you!
