### ISSUE TITLE
全局提示Message没有关闭按钮, 能否提供关闭按钮. 

### ISSUE THREAD

**Issue by little-yellow-bean** [vueComponent/ant-design-vue#1751]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以手动关闭Message

### What does the proposed API look like?
closeable = true

**Comment by tonyzheng1990** [comment]
请问这个计划实现吗？

**Comment by cshenger** [comment]
我也希望能有一个手动关闭的按钮选项，希望官方增加一下，谢谢了。

**Comment by jingping-ye** [comment]
同样遇到这种业务需求，希望可以像element-ui一样，支持关闭。
![image](https://user-images.githubusercontent.com/22724276/99024987-b82fc480-25a2-11eb-8265-de981bd0c070.png)

**Comment by tonyzheng121** [comment]
怎么就关了？

**Comment by little-yellow-bean** [comment]
对啊 咋关了呢

**Comment by SuperHaoHaoHao** [comment]
为什么这个需求就关了啊，很关键的 😭
