### ISSUE TITLE
Upload 组件 无法通过 :beforeUpload 来阻止文件列表更新

### ISSUE THREAD

**Issue by dzcpy** [vueComponent/ant-design-vue#1753]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
All browsers

### Reproduction link
https://codesandbox.io/s/distracted-herschel-gpv0g
### Steps to reproduce
1. 建立一个上传控件，设置 :beforeUpload 为一个固定返回 false 值的函数
2. 上传任意文件，激发 beforeUpload 之后，fileList 里还是把已经拒绝掉的文件加入了

### What is expected?
beforeUpload 被拒的文件不应加入 fileList

### What is actually happening?
无法拒绝特定类型的文件加入文件列表

**Comment by wangxueliang** [comment]
beforeUpload为false，是阻止默认的 Ajax
https://github.com/ant-design/ant-design/issues/15561

**Comment by dzcpy** [comment]
@wangxueliang 是阻止上传了，但是没阻止显示在列表里

**Comment by chongkeyubing** [comment]
我也遇到了这个问题，beforeUpload返回false，ajax是没执行，但是文件列表还是加入了这个文件
