### ISSUE TITLE
Invalid navigation menu onchange event （ <a-menu  @openChange="openchange"  mode="inline"> 在html引用JS开发环境无效）

### ISSUE THREAD

**Issue by itxstcom** [vueComponent/ant-design-vue#1755]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
chrome、 Notepad、html

### Reproduction link
[https://www.antdv.com/components/menu-cn/#api](https://www.antdv.com/components/menu-cn/#api)

### Steps to reproduce
<a-menu  @openChange="openchange"  mode="inline">在vscode node.js环境下是有效的，但是如果我是网页直接引用antd.js 网址就事件就无效，改成<a-menu  @open-change="openchange"  mode="inline"> 仍然无效。

vue.js:640 [Vue tip]: Event "openchange" is emitted in component <AMenu> but the handler is registered for "openChange". Note that HTML attributes are case-insensitive and you cannot use v-on to listen to camelCase events when using in-DOM templates. You should probably use "open-change" instead of "openChange".

### What is expected?
There should be no problem

### What is actually happening?
invalid

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/vue-dash-event
