### ISSUE TITLE
Hook event listener firing twice

### ISSUE THREAD

**Issue by ankology** [vueComponent/ant-design-vue#1756]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
Mapped in reproduction

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-ekjnl)

### Explanation
Just look at console, the hook will be fired twice. Looking the code from "a-switch" is passed down the $listeners, and because of that its fired twice, i think this happen in all the components that pass down $listeners, the "a-input" is not passing down nothing and works fine by example. In fact its not a really bug but looking at the point of view of a hook listener its correct to pass down the hook listeners along the first component? Thanks!

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/20ff3419e7278ac2168d97603d12f8e269a0fbf5
https://github.com/vueComponent/ant-design-vue/commit/594dc07dfff485a2e1abaea90e045a3cd1ac7996

fixed

**Comment by ankology** [comment]
That's it. Thank you!
