### ISSUE TITLE
Large size switch

### ISSUE THREAD

**Issue by emtiazzahid** [vueComponent/ant-design-vue#1757]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
i was trying to attach the switch in my price plan recurring type. yearly or monthly. there was a single switch and need to be highlighted.

### What does the proposed API look like?
currently the size of the Switch, options: default and small, can be new one is large

**Comment by tangjinzhou** [comment]
You can do it yourself by custom css.
