### ISSUE TITLE
trigger event when ctrl key up in tree

### ISSUE THREAD

**Issue by Lakmi15** [vueComponent/ant-design-vue#1760]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
currently, I'm using select method in tree component with multiple node select with ctrl key. but I'm looking event for ctrl key up in tree component.

```
async onTreeNodeSelectHandler(selectedKeys: any, event: any) {

    if (event.nativeEvent.ctrlKey === true){

}
```

inorder to fire this event I need to click on top of tree node. when I release ctrl key I want to do some logic without a click on other nodes.
are there any ways trigger ctrl key up event in tree component

### What does the proposed API look like?
better can add key up and down listener event capture keyword input.

**Comment by tangjinzhou** [comment]
You can try adding events to all tree node

**Comment by Lakmi15** [comment]
@tangjinzhou is this you mean here? 
`on: { click: () => {}}`
