### ISSUE TITLE
auto-complete 在输入中文时, placeholder 消失时机不对, 体验很不好

### ISSUE THREAD

**Issue by pengfeiWang** [vueComponent/ant-design-vue#1761]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
mac os

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn/](https://www.antdv.com/components/auto-complete-cn/)

### Steps to reproduce
输入中文, 在出现文字选取框时未选择文字 placeholder 并没有消失, 后来去查看 ant react, 他们这里处理的很好, 输入中文未选取文字时, placeholder 也能正常消失

### What is expected?
placeholder 正常消失

### What is actually happening?
placeholder 不正常

**Comment by tangjinzhou** [comment]
确认下版本？   1.4.10 已经修复了的

**Comment by pengfeiWang** [comment]
版本: 1.4.10

重新看了下官网的演示, 再次确认了下, 基础功能方面是没问题的

下边两个演示还是存在相同问题的

[查询模式 - 确定类目](https://www.antdv.com/components/auto-complete-cn/#components-auto-complete-demo-lookup-patterns---certain-category)


[查询模式 - 不确定类目](https://www.antdv.com/components/auto-complete-cn/#components-auto-complete-demo-lookup-patterns---uncertain-category)
