### ISSUE TITLE
暴露 icon 组件的内置 type 数组

### ISSUE THREAD

**Issue by EmiyaYang** [vueComponent/ant-design-vue#1769]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
暴露内置 iconTypeArr 数组, 便于开发者在使用自定义 SVG 图标时抹平 type 与 component 的差异.

```js
import { iconTypeArr } from 'ant-design-vue'

function sample (type) {
    return iconTypeArr.includes(type) 
              ? <a-icon type={type} />
              : <a-icon component={type} />
}
```

### What does the proposed API look like?
```js
import { iconTypeArr } from 'ant-design-vue'
```

**Comment by sendya** [comment]
https://github.com/ant-design/ant-design-icons/tree/master/packages/icons-vue/src/icons

或者自己整理
https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/IconSelector/icons.js
