### ISSUE TITLE
官方文档的部分链接无法打开

### ISSUE THREAD

**Issue by wuxi889** [vueComponent/ant-design-vue#1770]
http://vue.ant-design.cn/components/tabs-cn/
今天看文档时发现，除了 [http://vue.ant-design.cn/components/tabs-cn/](http://vue.ant-design.cn/components/tabs-cn/) 无法打开外，其它的都可以，希望修复一下。

**Comment by zkwolf** [comment]
去antdv.com吧

**Comment by sendya** [comment]
@wuxi889 建议自行查正， ant-design.cn 并是盗版网站并不是本项目所提供的站点。请认准 vue.ant.design 和 antdv.com 及其子域
