### ISSUE TITLE
建议给 input 的 clear 按钮增加一下事件

### ISSUE THREAD

**Issue by chenbont** [vueComponent/ant-design-vue#1772]
我输入了一个文本进行搜索后，我希望在不想搜索时点一下clear就能触发重新加载列表，现在没有一个 onClear 事件不太方便，建议增加一个。

**Comment by sendya** [comment]
清空有 change 事件吧

**Comment by chenbont** [comment]
change 事件能区别键盘输入还是点击clear吗？我希望在点了clear 清掉搜索条件重新加载列表，监听change 感觉也难区分出来。

**Comment by sendya** [comment]
vue 不是双向绑定吗？ change 的时候，判断值等于空就重载咯
