### ISSUE TITLE
vue ant table组件加载100多条数据，导致页面上的input框输入卡顿，大家有遇到过吗

### ISSUE THREAD

**Issue by murongqingsi** [vueComponent/ant-design-vue#1786]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
vue ant table组件加载100多条数据，导致页面上的input框输入卡顿，大家有遇到过吗

### What does the proposed API look like?
a-table

**Comment by sendya** [comment]
你好，有复现吗？
如果是和表单混用 不建议全部在同一个组件里，拆分组件会最大化减少卡顿

**Comment by murongqingsi** [comment]
可以复现
第一种情况   table和表单（表单中有input）在同一个页面，表单放在a-modal里面，表单加上校验，就会卡顿，不加校验，table数据多一点（100多）也会卡顿。体现为输入卡顿，长按backspace删除也卡顿；
基于第一种情况，将table,表单拆分成两个组件，父子组件引用，输入卡顿基本消失，但是长按backspace删除的卡顿还是存在。

**Comment by iamwjj** [comment]
确实有性能问题，表格加载100条数据就撑不住了。(难受

**Comment by enhezzz** [comment]
目前用的1.4.x，设计确实有点问题，表单会导致组件重新render...

**Comment by bobchen554** [comment]
@murongqingsi 从你的描述感觉貌似是vue的原因：
类似一下demo
https://codepen.io/karmiy/pen/pMWVOX

**Comment by youhongxing** [comment]
我也遇到过类似情况，不过没有用表单，input输入卡顿。我将v-model改为使用@input来手动修改，解决了这个问题。

**Comment by zangtian2** [comment]
+1 table 修改的插槽input 1s卡顿，打字也明显卡顿

**Comment by Amanda5293** [comment]
1.7.x版本，当input遇上table就有输入卡顿的问题

**Comment by w306621759** [comment]
我是点击按钮打开抽屉卡顿，就算抽屉里面什么都没有，也一样。按钮和table在同一个页面，抽屉是封装的。点击按钮时，会导致table 重新render。导致卡顿。

**Comment by heyouquan** [comment]
想问一下，最新版本解决了卡顿的问题了吗？

**Comment by tangjinzhou** [comment]
1.7.4 已修复
