### ISSUE TITLE
Indeterminate support for options in a checkbox group

### ISSUE THREAD

**Issue by wmjasonward** [vueComponent/ant-design-vue#1788]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
We have a use case where I need two checkbox groups that are related. Selecting one item in the first checkbox group, implies the inclusion of some items in the second checkbox group. The items in the second group haven't been explicitly selected, so I don't want to show them as checked. But, I do want to indicate that they are implicitly included so I'd like to use the 'indeterminate' state to represent this.

### What does the proposed API look like?
I'd like to be able to set { indeterminate: true } on the options for the checkbox group.

```javascript
const optionsWithIndeterminate = [
{ value: 'Apple' },
{ label: 'Pear', value: 'Pear' },
{ label: 'Orange', value: 'Orange', indeterminate: true },
];
```
It appears this could be implemented by adding the following line to `components/checkbox/Group.jsx` at approx line 83:
```
indeterminate={'indeterminate' in option ? option.indeterminate : false}
```
or, if it would also be desirable to add the `indeterminate` property to the entire Checkbox Group:
```
indeterminate={'indeterminate' in option ? option.indeterminate : props.indeterminate}
```

My work-around is to create a list of Checkboxes inside the CheckboxGroup, so this is really just a matter of convenience.

Thanks!

**Comment by tangjinzhou** [comment]
We should use `provide`. You can submit pr to add it.
