### ISSUE TITLE
How is upgrade going?

### ISSUE THREAD

**Issue by rafalolszewski94** [vueComponent/ant-design-vue#1796]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
-

### Reproduction link
-

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
-

---
Ant Design of React has a lot of changes comparing to Ant Design of Vue right now.

When we can expect upgraded version of ANTDV with new components and changes?

Is project https://github.com/vueComponent/ant-design-vue/projects/2 up to date?

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/tree/feat-1.5.0
