### ISSUE TITLE
树形控件连接线实例showLine最后一层的图标（默认是文件小图标）能自定义吗

### ISSUE THREAD

**Issue by WuYiZhan** [vueComponent/ant-design-vue#1798]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
浏览器

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
建议可以控制

### What is expected?
树形控件连接线实例showLine最后一层的图标建议可以控制

### What is actually happening?
树形控件连接线实例showLine最后一层的图标建议可以控制

**Comment by huanlirui** [comment]
+1 求解最后一层图标默认是file的icon怎么更改呢？

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/tree-cn/#components-tree-demo-tree-with-line

**Comment by huanlirui** [comment]
> https://www.antdv.com/components/tree-cn/#components-tree-demo-tree-with-line

感谢您的回复。我知道能够通过循环树节点单独用插槽来自定义每个图标。但是我期望能够有某个属性能一键修改。
目前 该组件 switcherIcon | 自定义树节点的展开/折叠图标  。该api仅能修改展开折叠的icon图标，不能修改到无子级节点的图标。

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/78092216-c6f5ac80-7401-11ea-8e11-adc9090bd91d.png)

这个示例不是 ？

**Comment by huanlirui** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/78092216-c6f5ac80-7401-11ea-8e11-adc9090bd91d.png)
> 
> 这个示例不是 ？

该事例通过手动循环遍历节点来单独设置插槽图标确实可以。想怎么搞都行，但是很多时候我不确定自己的树节点层级。我只能使用treedata来渲染时，怎么处理呢？
![image](https://user-images.githubusercontent.com/40491203/78096696-e2b28000-740c-11ea-9009-5ee10d4738b9.png)
![image](https://user-images.githubusercontent.com/40491203/78096776-18efff80-740d-11ea-9a20-a2552e2a1e23.png)
类似该例子，仅能修改折叠展开的图标。如果有一个属性能够替换默认图标不是更好吗？

**Comment by tangjinzhou** [comment]
tree-node 的子节点同样可以设置   不会提供属性配置，会和2.0 中的图标按需加载冲突

**Comment by huanlirui** [comment]
> 属性

您好。我没懂怎么通过treeData来配置 tree-node节点的展开收起默认图标，可以给一个demo吗。。。

**Comment by huanlirui** [comment]
> tree-node 的子节点同样可以设置 不会提供属性配置，会和2.0 中的图标按需加载冲突

您好。我没懂怎么通过treeData来配置 tree-node节点的展开收起默认图标，可以给一个demo吗。。。
