### ISSUE TITLE
vue版的table内的行数据不支持拖拽，react的支持，希望vue也支持

### ISSUE THREAD

**Issue by haixia1316** [vueComponent/ant-design-vue#1803]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
vue版的table内的行数据不支持拖拽，我们有拖拽的需求

### What does the proposed API look like?
vue版的table内的行数据可以拖拽

**Comment by tangjinzhou** [comment]
ref #1804
