### ISSUE TITLE
New params in Modal component cause TS error

### ISSUE THREAD

**Issue by Darkphooo** [vueComponent/ant-design-vue#1809]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
Windows 10 1909, Chrome 80.0, Vue 2.6.11

### Reproduction link
[https://imgchr.com/i/3nJXhq](https://imgchr.com/i/3nJXhq)

### Steps to reproduce
Develop a project in antdv@1.4.10, upgrade antdv to 1.4.11, TS will output error

### What is expected?
TS won't output error, or provide method to handle it

### What is actually happening?
A new params 'parentContext' caused this problem

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/pull/1784
