### ISSUE TITLE
表格不能展示数据

### ISSUE THREAD

**Issue by fasthold** [vueComponent/ant-design-vue#1813]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
Windows 10, Chrome 80.0.3987.116, Vue 2.6

### Reproduction link
[https://codepen.io/fasthold/pen/jOPVKMr?editors=0011](https://codepen.io/fasthold/pen/jOPVKMr?editors=0011)

### Steps to reproduce
依照官方文档 https://www.antdv.com/components/table-cn/#components-table-demo-size 进行表格测试

### What is expected?
展示正确的表格数据

### What is actually happening?
只显示表头，无表数据

**Comment by tangjinzhou** [comment]
如果直接写在html中请使用全小写，并且不要自闭合，这是vue规范
```html
<a-table :columns="tableColumns" :data-source="tableData"></a-table>
```
