### ISSUE TITLE
在nuxt环境中form.validateFields没有执行

### ISSUE THREAD

**Issue by kongling94** [vueComponent/ant-design-vue#1819]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
Nuxt2.0.0  MacOs10.14.6

### Reproduction link
[https://vue.ant.design/components/form-cn/](https://vue.ant.design/components/form-cn/)

### Steps to reproduce
```javascript
console.log(this.form)
this.form.validateFields((err, values) => {
console.log(err, values)
if (!err) {
// to do
}
})
```

### What is expected?
点击提交正常进行表单校验

### What is actually happening?
点击 提交的时候 表单数据在并没有执行验证，此时能打印form对象，但是validateFields方法没有执行操作。 自定义的验证已经使用callback返回，本地运行一切正常，但在nuxt打包部署线上之后就没有效果

**Comment by dzcpy** [comment]
你肯定哪里写错了，我用nuxt很长时间了没出过问题
