### ISSUE TITLE
Input search 非 enterbutton 下不能触发 search，和官网不符合。

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#182]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
Win7/vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/my7mpyp7p8)

### Steps to reproduce
1、点击搜索的图标
2、看是否弹出了 alert

### What is expected?
正常触发 search 事件。

### What is actually happening?
未触发。

---
- [antd vue input](https://tangjinzhou.gitee.io/ant-design-vue/components/input-cn/)
- [antd react input](https://ant.design/components/input/)

**Comment by tangjinzhou** [comment]
update to 1.1.0
