### ISSUE TITLE
增加官方引用的自定义的组件瞎咋方式

### ISSUE THREAD

**Issue by meatbuns82** [vueComponent/ant-design-vue#1822]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
ant-design-vue里抽屉里的信息预览抽屉里的 ./descriptionItem这个组件找不到，也没有提供入口，官方能否对一些自定义组件提供下载的方式或者入口?
另:求 ./descriptionItem的下载连接和地址，谢谢

### What does the proposed API look like?
import descriptionItem from './descriptionItem';

components: {
descriptionItem,
},

**Comment by zkwolf** [comment]
https://github.com/vueComponent/ant-design-vue/blob/master/components/drawer/demo/descriptionItem.vue

**Comment by meatbuns82** [comment]
谢谢回复，问题已经解决！
