### ISSUE TITLE
Failed to resolve directive: decorator

### ISSUE THREAD

**Issue by liusishan** [vueComponent/ant-design-vue#1829]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.1

### Environment
windows10、 chrome 80、vue 2.5.17

### Reproduction link
暂时没有
### Steps to reproduce
<a-input
v-decorator="[
'name',
{rules: [{ required: true, message: '请输入账户名称' }]}
]"
placeholder="简短好记得账户名称" name="name" v-model="addForm.name"/>

### What is expected?
在使用 v-decorator时完成表单校验

### What is actually happening?
出现上面的错误

---
就在input 中添加了  v-decorator 就报错了，查看 issue 134 并使用解决方案，然而并没有解决我的问题
import antInputDirective from 'ant-design-vue/es/_util/antInputDirective'
Vue.use(antInputDirective)

**Comment by sendya** [comment]
建议更新到最新版，以及在 main 中全局注册 Form
```
import { Form } from 'ant-design-vue';

Vue.use(Form);
```

**Comment by liusishan** [comment]
谢谢你，升级版本后我的问题解决了😄

**Comment by liusishan** [comment]
@sendya 谢谢你，升级版本后我的问题解决了😄
