### ISSUE TITLE
【BUG】Modal.method() 中centered设置无效

### ISSUE THREAD

**Issue by webees** [vueComponent/ant-design-vue#183]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0

### Environment
electron-vue及vue最新版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w6o3ol64mk)

### Steps to reproduce
https://codesandbox.io/s/w6o3ol64mk

### What is expected?
希望Modal.method()通过centered设置项进行垂直居中

### What is actually happening?
centered设置无效

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/j2m45l7r0v

```
<style lang="less">
.ant-confirm-centered {
  text-align: center;
  &:before {
    content: '';
    display: inline-block;
    height: 100%;
    vertical-align: middle;
    width: 0;
  }
  .ant-confirm {
    display: inline-block;
    vertical-align: middle;
    top: 0;
    text-align: left;
  }
}
</style>
```

**Comment by webees** [comment]
嗯……谢谢，这个倒是不需要，基本上所有vue文件中都用的scoped。毕竟有的不需要居中。我先加上centered等到起。

**Comment by tangjinzhou** [comment]
please update to 1.1.1
