### ISSUE TITLE
Modal 的 @ok 与 Modal.confirm 的 onOk 行为一致

### ISSUE THREAD

**Issue by chess99** [vueComponent/ant-design-vue#1830]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?  
Modal.confirm onOk 会自动触发一个按钮的 loading 效果, Modal 的 @ok 无此效果.  
Modal.confirm 的 footer 用了封装的 ActionButton 而 Modal 用的 Button.  

### What does the proposed API look like?
希望二者统一一下.  Modal 的 @ok 也触发按钮 loading 效果.

**Comment by sendya** [comment]
两者用途不一致，Modal 如需 loading 请使用 `confirmLoading` 属性控制
