### ISSUE TITLE
对话框Modal组件支持鼠标拖动标题部分移动对话框位置

### ISSUE THREAD

**Issue by gaorubin1990** [vueComponent/ant-design-vue#1838]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
给出支持对话框可拖动位置解决方案

### What does the proposed API look like?
集成可拖动组件demo

**Comment by vzhougm** [comment]
不可拖动确实太坑了吧😩

**Comment by liruisen** [comment]
I also hope that Modal components can support drag
