### ISSUE TITLE
递归实现 深层 Tree

### ISSUE THREAD

**Issue by icefee** [vueComponent/ant-design-vue#1839]
我想通过循环 <TreeNode 节点并结合递归组件，来构造一个树，发现组件内部对默认插槽做了校验。
会报错：Warning: Tree only accept TreeNode as children.
![image](https://user-images.githubusercontent.com/20411818/75642520-c3da9580-5c76-11ea-8248-1fcdd35fc5d6.png)

**Comment by Koomita** [comment]
我也遇到这个问题了，有模仿官方Menu的单递归例子https://github.com/vueComponent/ant-design-vue/blob/master/components/menu/demo/SubMenu1.vue来递归Tree，也是报`Warning: Tree only accept TreeNode as children.`

**Comment by icefee** [comment]
> 我也遇到这个问题了，有模仿官方Menu的单递归例子：
> 
> https://github.com/vueComponent/ant-design-vue/blob/master/components/menu/demo/SubMenu1.vue
> 
> 来递归Tree，也是报`Warning: Tree only accept TreeNode as children.`

我通过函数递归的方法解决了，代码如下
![image](https://user-images.githubusercontent.com/20411818/76138211-9def2f80-6080-11ea-83cf-ca2a259a2152.png)
