### ISSUE TITLE
Dropdown下拉菜单在浏览器resize后无法触发下拉

### ISSUE THREAD

**Issue by garyzc** [vueComponent/ant-design-vue#184]
Version
1.1.0

Environment
vue最新版本

Reproduction link

Steps to reproduce
改变浏览器大小就会不显示下拉
https://vuecomponent.github.io/ant-design-vue/components/dropdown-cn/#

What is expected?
希望Dropdown在浏览器缩放resize后能正常显示下拉内容

What is actually happening?
Dropdown在浏览器resize后不能显示下拉内容，resize前是可以正常显示下拉的

**Comment by tangjinzhou** [comment]
未能复现你说的问题

**Comment by garyzc** [comment]
> 未能复现你说的问题

我补一下详细的复现步骤如下：
Environment：
浏览器chrome版本 68.0.3440.106（正式版本） （64 位）
Steps to reproduce：
1、触发下拉（正常），把浏览器最大化
2、再触发下拉（正常），把浏览器还原
3、再触发下拉（无法触发）

**Comment by tangjinzhou** [comment]
please update to 1.1.1

**Comment by garyzc** [comment]
> please update to 1.1.1

非常感谢！
