### ISSUE TITLE
关于表格拖拽功能

### ISSUE THREAD

**Issue by cooperGao** [vueComponent/ant-design-vue#1840]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如果有涉及到表格的行拖拽排序需求时, 用ant-design-vue就无法实现了,这使得我必须用原生表格去做行拖拽功能,维护起来可能不是那么好, 但是我发现隔壁基于react的ant框架有这个功能, 那么ant-design-vue的表格组件是否可以加上这个功能呢?谢谢!

### What does the proposed API look like?
希望可以实现例如这个链接https://sortablejs.github.io/Vue.Draggable/#/table-example下的表格拖拽

**Comment by belongwqz** [comment]
好像有例子，但是何不集成进来呢？同类库好像都有了

**Comment by cooperGao** [comment]
> 好像有例子，但是何不集成进来呢？同类库好像都有了

当前组件库目前只看到有列宽拖拽的例子, 但是没有行拖拽

**Comment by tangjinzhou** [comment]
ref #1803
