### ISSUE TITLE
In the form set select initialValue，but select show option value not text

### ISSUE THREAD

**Issue by littlebaozi** [vueComponent/ant-design-vue#1841]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
ant-design-vue 1.4.11，vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-cannon-5srif?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
```javascript
<a-select v-decorator="['vefiry', {initialValue:0}]" placeholder="认证状态">
<a-select-option value="0" key="0">全部</a-select-option>
<a-select-option value="1" key="1">已认证</a-select-option>
<a-select-option value="2" key="2">未认证</a-select-option>
</a-select>
```

在表单中，使用v-decorator设置select的initialValue为0

### What is expected?
select显示“全部”

### What is actually happening?
select显示“0”

---
即使在mounted中使用setFieldsValue为“0”显示了“全部”，resetFields之后还是会显示0

**Comment by wesley6j** [comment]
两个类型不同的缘故: `initialValue` 是数字，a-select-option 里面的value是string。你试试这样：
```vue
<a-select v-decorator="['vefiry', {initialValue:'0'}]" placeholder="认证状态">
    <a-select-option value="0" key="0">全部</a-select-option>
    <a-select-option value="1" key="1">已认证</a-select-option>
    <a-select-option value="2" key="2">未认证</a-select-option>
</a-select>
```

**Comment by linziguan** [comment]
如果vefiry是数值类型，可以将value改成:value即可
```
<a-select v-decorator="['vefiry', {initialValue:0}]" placeholder="认证状态">
    <a-select-option :value="0" key="0">全部</a-select-option>
    <a-select-option :value="1" key="1">已认证</a-select-option>
    <a-select-option :value="2" key="2">未认证</a-select-option>
</a-select>
```
