### ISSUE TITLE
pagination 不一定需要 total

### ISSUE THREAD

**Issue by mouyong** [vueComponent/ant-design-vue#1842]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
后端为了前端的分页功能，额外多查询一次数据总数问题。

### What does the proposed API look like?
不需要 total 也能点击上一页、下一页，首页不可点上一页。输入页码可跳转其他页，无数据也没事。页面不可负值

**Comment by tangjinzhou** [comment]
total 传一个很大的值应该就可以满足了
