### ISSUE TITLE
关于select dropdownRender 点击拓展项时，select会失去光标，导致下拉列表自动收起

### ISSUE THREAD

**Issue by peamed** [vueComponent/ant-design-vue#1852]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.2

### Environment
window、Google-80.0.3987.132（正式版本） （64 位）、Vue-v1.4.2

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
按照提供的链接，即你们自己的文档例子中关于select dropdownRende

### What is expected?
点击拓展项不会自动关闭

### What is actually happening?
点击拓展项的输入框，可以保持不关闭状态

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-wmjlv
