### ISSUE TITLE
Method prop missing in Upload Component

### ISSUE THREAD

**Issue by mayank** [vueComponent/ant-design-vue#1858]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
In case uploading is required via PUT method, the only option is to write a customized request. There should be a method option available in the props of uploader so that user can specify the method.

### What does the proposed API look like?
```
<Upload method="PUT" />
```

**Comment by franzwilding** [comment]
A tmp fix for me is to import the default request so I dont have to rewrite it:

```
import defaultRequest from 'ant-design-vue/es/vc-upload/src/request';

...

customRequest(option) {
            option.method = 'PUT';
            return defaultRequest(option);
        },

```

**Comment by weislywang** [comment]
这都没人管么
