### ISSUE TITLE
使用SubMenu报错Cannot read property 'isRootMenu' of undefined"

### ISSUE THREAD

**Issue by saatana97** [vueComponent/ant-design-vue#1859]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
windows10  chrome80.0.3987.132  @vue/cli 4.0.5

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
自定义一个组件，通过传入数据是否有children来判断渲染a-menu-item还是a-sub-menu

### What is expected?
有children就正常渲染a-sub-menu，没有children就正常渲染a-menu-item

### What is actually happening?
渲染a-menu-item正常，渲染a-sub-menu时就会报错不能从undefined读取isRootMenu属性

---
国内大厂，用react思想做出来的vue组件库就离谱，form组件不能用v-model就离谱，表单校验只能通过自定义命令就离谱，偏偏SP经理还偏要用，服气

**Comment by sendya** [comment]
menu 问题和官方文档中的单文件递归类似，参考即可

具体链接 https://www.antdv.com/components/menu-cn/#components-menu-demo-single-file-recursive-menu

也可以看看一年前写的一个 demo，虽然过时，但也能用
https://codesandbox.io/s/znv4k5p2nm

----

提到的 form 问题，因为我们遵循单向数据流思想，所以没使用 v-model ，但这并不妨碍你使用 v-model 只不过数据收集功能，收集数据和校验均需您自行使用 `Form.Item` 对象组件的 `help` `extra` `validateStatus`  来进行错误和校验信息提示等。

另外，遵循单向数据流思想基于 antd vue 开发，比如 form。可以省区克隆对象和防止引用错乱等一系列新手问题。

**Comment by saatana97** [comment]
官方文档单文件递归的SubMenu代码文件在git上404了亲
Form表单如果只是单纯简单的使用的话单向数据流思想没啥大毛病，然而经理的需求是要做自动表单，手动拖拽布局，动态渲染提交数据，表单里面还能内嵌可编辑的Table，这实现起来就美滋滋了，如果用饿了么的话这些问题都不算问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "言肆"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 中午11:10
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "向文可"<1041367524@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] 使用SubMenu报错Cannot read property &#39;isRootMenu&#39; of undefined&quot; (#1859)




menu 问题和官方文档中的单文件递归类似，参考即可
 
具体链接 https://www.antdv.com/components/menu-cn/#components-menu-demo-single-file-recursive-menu
 
也可以看看一年前写的一个 demo，虽然过时，但也能用
 https://codesandbox.io/s/znv4k5p2nm
 
 
提到的 form 问题，因为我们遵循单向数据流思想，所以没使用 v-model ，但这并不妨碍你使用 v-model 只不过数据收集功能，收集数据和校验均需您自行使用 Form.Item 对象组件的 help extra validateStatus  来进行错误和校验信息提示等。
 
另外，遵循单向数据流思想基于 antd vue 开发，比如 form。可以省区克隆对象和防止引用错乱等一系列新手问题。

**Comment by sendya** [comment]
可编辑 table 什么的，也并非不行，也并非有难度。
https://codesandbox.io/s/table-form-edit-5ll5p

文档中也有提供动态表单demo。
如果觉得用着不舒服，也欢迎 PR。提供更好的解决方案

**Comment by sendya** [comment]
404的文件 https://codesandbox.io/embed/single-file-recursive-menu-o9klx?fontsize=14&hidenavigation=1&theme=dark

**Comment by saatana97** [comment]
我自定义的这个XMenuItem跟你发给我看得也差不多呢&nbsp; &nbsp;不同的是我是直接在自定义组件里进行了所有层级的菜单的渲染&nbsp; 而官方文档里面的demo是先只渲染submenu的子孙级菜单




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "言肆"<notifications@github.com&gt;; 
发送时间: 2020年3月10日(星期二) 中午12:13
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "向文可"<1041367524@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] 使用SubMenu报错Cannot read property &#39;isRootMenu&#39; of undefined&quot; (#1859)




404的文件 https://codesandbox.io/embed/single-file-recursive-menu-o9klx?fontsize=14&amp;hidenavigation=1&amp;theme=dark

**Comment by sendya** [comment]
推荐提供复现代码

**Comment by elantion** [comment]
参考递归的代码，但报错了
```
const SubMenu = {
  template: `
      <a-sub-menu :key="menuInfo.key" v-bind="$props" v-on="$listeners">
        <span slot="title">
          <a-icon type="mail" /><span>{{ menuInfo.title }}</span>
        </span>
        <template v-for="item in menuInfo.children">
          <a-menu-item v-if="!item.children" :key="item.key">
            <a-icon type="pie-chart" />
            <span>{{ item.title }}</span>
          </a-menu-item>
          <sub-menu v-else :key="item.key" :menu-info="item" />
        </template>
      </a-sub-menu>
    `,
  name: 'SubMenu',
  // must add isSubMenu: true
  isSubMenu: true,
  props: {
    ...Menu.SubMenu.props,
    // Cannot overlap with properties within Menu.SubMenu.props
    menuInfo: {
      type: Object,
      default: () => ({}),
    },
  },
};
```
以下是错误代码
```
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```
让人有点沮丧，真想进你们部们现场指导你们开发。。。

**Comment by elantion** [comment]
另外，```v-model```是vue的重要特性啊，为什么把react的单向流思想强行用到vue类的框架了？

**Comment by dlgchg** [comment]
> 另外，`v-model`是vue的重要特性啊，为什么把react的单向流思想强行用到vue类的框架了？

kpi产品

**Comment by saatana97** [comment]
哈哈哈哈说得对，react思想就硬搬到vue身上，毫无开发者体验




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "竹莫袅"<notifications@github.com&gt;; 
发送时间: 2020年8月11日(星期二) 中午11:03
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "向文可"<1041367524@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] 使用SubMenu报错Cannot read property &#39;isRootMenu&#39; of undefined&quot; (#1859)





  
另外，v-model是vue的重要特性啊，为什么把react的单向流思想强行用到vue类的框架了？
  
kpi产品

**Comment by tangjinzhou** [comment]
以提供  FormModel 组件

**Comment by jjandxa** [comment]
@saatana97 @dlgchg @elantion 哦？不会吧不会吧？难道你们都全用事件回调来传递数据流吧？不会你们项目只有一两个组件吧？不会你们连什么是状态管理，为什么要用单向数据流都不知道吧？？？不会吧不会吧？？？
![u=12243213,4112986781 fm=26 gp=0](https://user-images.githubusercontent.com/10411770/89864127-fd2c0f80-dbdd-11ea-8f07-a4b55be2495b.jpg)

**Comment by elantion** [comment]
当然知道为什么要用单向流啊，而且我项目也不止一两个组件。可是，我的项目用v-model确实更容易维护呀，少写了很多代码，逻辑也更新晰。<br>
另外，@jjandxa，请不要用这种奇怪的语气讨论问题，不介意弄点调皮的玩笑，但过分了就显得幼稚和无礼。<br>
Please respect and peace.

**Comment by dlgchg** [comment]
> 当然知道为什么要用单向流啊，而且我项目也不止一两个组件。可是，我的项目用v-model确实更容易维护呀，少写了很多代码，逻辑也更新晰。
> 
> 另外，@jjandxa，请不要用这种奇怪的语气讨论问题，不介意弄点调皮的玩笑，但过分了就显得幼稚和无礼。
> 
> Please respect and peace.

习惯就好, 总有以为自己很聪明的人
