### ISSUE TITLE
在按需加载的模式下，从文件递归生成菜单时出现：TypeError: Cannot read property 'propsData' of undefined 

### ISSUE THREAD

**Issue by JollyGo** [vueComponent/ant-design-vue#1860]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
macOS:10.15.3 ，Chrome： 80.0.3987.132，vue: 2.6.11

### Reproduction link
[https://github.com/JollyGo/vue-learn](https://github.com/JollyGo/vue-learn)

### Steps to reproduce
```
# git clone https://github.com/JollyGo/vue-learn
# yarn
# yarn run serve
```

### What is expected?
能够正常显示目录

### What is actually happening?
无显示,在Console中出现 TypeError: Cannot read property 'propsData' of undefined ，报错文件位置在.node_modules/ant-design-vue/es/vc-menu/SubPopupMenu.js

---
当使用Vue.use 加载Menu当时候就正常使用，在main.js中加载或者在SubMenu.vue中使用都可以正常使用

**Comment by Amour1688** [comment]
麻烦提供复现代码

**Comment by JollyGo** [comment]
放在这里了 https://github.com/JollyGo/vue-learn

> 麻烦提供复现代码

**Comment by xiezhyan** [comment]
有解决么， 我也遇到了同样的问题

**Comment by JollyGo** [comment]
> 有解决么， 我也遇到了同样的问题

使用在生产文件中使用 Vue.use(Menu)

**Comment by yuzhewo** [comment]
> > 有解决么， 我也遇到了同样的问题
> 
> 在生产文件中使用 Vue.use(Menu)

这一步已经操作，问题依然没有解决。

**Comment by EchoZw** [comment]
有人修复吗

**Comment by liuerwo** [comment]
解决了没？我也碰到了

**Comment by liuerwo** [comment]
问题被我解决了，建议官网上把案例代码标签改一下  别的地方都是用的a-sub-menu   这个地方用的是sub-menu，有点坑 哈哈哈哈

**Comment by xixinglong** [comment]
vue.dll.js:7 TypeError: Cannot read property 'propsData' of undefined
按需引入使用menu 菜单 functional  函数式组件   报错

**Comment by Raonet** [comment]
我也遇到了
- 用上面的方法在**main.js**中把调用方式从 Vue.component(Menu.name, Menu)改成了Vue.use(Menu)就正常使用了

**Comment by AngleMi** [comment]
> vue.dll.js:7 TypeError: Cannot read property 'propsData' of undefined
> 按需引入使用menu 菜单 functional 函数式组件 报错

请问解决了么？同样遇到

**Comment by Leocat81** [comment]
同样遇到了该错误，对于Menu组件，我只能使用全局注册的方式，才能避免该问题。

**Comment by xiangcaimogu** [comment]
Vue.component(Menu.name, Menu)
Vue.component(Menu.SubMenu.name, Menu.SubMenu)
Vue.component(Menu.Item.name, Menu.Item)
组件没有全部引入
