### ISSUE TITLE
popover位置异常

### ISSUE THREAD

**Issue by kuangyanit** [vueComponent/ant-design-vue#1862]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.8

### Environment
os: Mojave 10.14.6 (18G2022) 
chrome: 80.0.3987.132
vue: 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-popover-hggqs)

### Steps to reproduce
参见codesandbox

### What is expected?
popover位置正常

### What is actually happening?
在填写信息时，popover位置发生了变动

**Comment by tangjinzhou** [comment]
你这个场景更适合用modal组件  
popover的弹窗位置和触发点强相关的，填写信息的时候，你的重命名按钮已经消失了 
https://codesandbox.io/s/antd-popover-mhsm6
