### ISSUE TITLE
Modal右上角的x不能点关闭

### ISSUE THREAD

**Issue by yurizhang** [vueComponent/ant-design-vue#1863]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
vue2.6.10

### Steps to reproduce
Modal右上角的x不能点关闭

### What is expected?
点了可以关闭

### What is actually happening?
Modal右上角的x不能点关闭

<img width="492" alt="图片" src="https://user-images.githubusercontent.com/20555332/76479334-626cb080-6446-11ea-8122-413cb52441e8.png">

**Comment by yurizhang** [comment]
a-modal :visible="visibleModal" destroyOnClose title="Open XDR Console" @cancel="visibleModal=false">


我需要手动加上： @cancel="visibleModal=false"  这个才可以，以前的版本是不需要的。

**Comment by sendya** [comment]
请始用 `v-model`， 使用 `visible` 你就必须自己控制是否显示

**Comment by yurizhang** [comment]
之前的版本不是这样的吗？ 需要对之前的所有进行修改吗

**Comment by sendya** [comment]
之前版本也不是这样的，Vue 禁止子组件对父组件的值进行改变。所以不会有 `:value` 绑定的值被 Modal 改变

**Comment by lixianyu-icon** [comment]
vue2.0支持this.$emit('update:visible',false)方式修改父级值，vue3支持context.emit('update:visible', false)方式修改父级值。
我现在遇到的问题是点击确定可以关闭弹框，但是点击×和取消报错：
runtime-core.esm-bundler.js:217 Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'visible'
    at _createBlock.onUpdate:visible._cache.<computed>._cache.<computed> (Edit.vue:4)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at emit (runtime-core.esm-bundler.js:642)
    at Proxy.handleCancel (Modal.js:145)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at emit (runtime-core.esm-bundler.js:642)
    at Proxy.handleClick2 (button.js:140)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)

**Comment by lixianyu-icon** [comment]
> vue2.0支持this.$emit('update:visible',false)方式修改父级值，vue3支持context.emit('update:visible', false)方式修改父级值。
> 我现在遇到的问题是点击确定可以关闭弹框，但是点击×和取消报错：
> runtime-core.esm-bundler.js:217 Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'visible'
> at _createBlock.onUpdate:visible._cache.._cache. (Edit.vue:4)
> at callWithErrorHandling (runtime-core.esm-bundler.js:154)
> at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
> at emit (runtime-core.esm-bundler.js:642)
> at Proxy.handleCancel (Modal.js:145)
> at callWithErrorHandling (runtime-core.esm-bundler.js:154)
> at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
> at emit (runtime-core.esm-bundler.js:642)
> at Proxy.handleClick2 (button.js:140)
> at callWithErrorHandling (runtime-core.esm-bundler.js:154)

我总感觉是cancel回调的执行时机太晚了
