### ISSUE TITLE
table 列中设置宽度，英文情况下不能自动换行

### ISSUE THREAD

**Issue by AFTM7512** [vueComponent/ant-design-vue#1864]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当使用 table 组件时，有些列如果输入的是全英文，它不会自动换行，从而导致整个列表错位。

### What does the proposed API look like?
当 table 组件每一列设置了 width，不管是中文还是英文，它应该自动换行。

**Comment by yurizhang** [comment]
这个自己加个样式处理一下就可以了， break-word

**Comment by tangjinzhou** [comment]
关注下 1.5.0
