### ISSUE TITLE
表单数据回显，涉及到radio,同时界面又需要根据数据当做v-if条件判断时候，会导致回显渲染异常

### ISSUE THREAD

**Issue by alibababa888** [vueComponent/ant-design-vue#1867]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
任意支持浏览器，vue最新版

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
创建三组a-radio-group标签，
\<a-radio-group v-decorator="['a']"/>
\<a-radio :value="0"\>是\<a-radio/>
\<a-radio :value="1"\>否\</a-radio/>
\<a-radio-group/>
\<p v-if="form.getFieldValue('a')==0"/>展示a\<p/>
\<a-radio-group v-decorator="['b']"/>
\<a-radio :value="0"\>是\<a-radio/>
\<a-radio :value="1"\>否\</a-radio/>
\<a-radio-group/>
\<p v-if="form.getFieldValue('b')==0"/>展示b\<p/>
\<a-radio-group v-decorator="['c']"/>
\<a-radio :value="0"\>是\<a-radio/>
\<a-radio :value="1"\>否\</a-radio/>
\<a-radio-group/>
\<p v-if="form.getFieldValue('c')==0"/>展示c\<p/>
v-decorator绑定三个自定义属性a,b,c，界面上设置3个元素，通过v-if="form.getFieldValue('a')==0"控制是否展示，在页面初始化赋值，this.form.setFieldsValue({ a: 0, b: 0, c: 0 })

### What is expected?
应该是三个radio的是选项被选中，同时展示三个文本信息

### What is actually happening?
三个文本信息都正常展示，但是radio只会展示a，c,b不会正常回显

**Comment by sendya** [comment]
b, c 在 `v-if`  不成立状态下，完全不会渲染，这是由 vue 决定的，所以设置值无效。
你可以把 `v-if` 改为 `v-show`

**Comment by alibababa888** [comment]
> b, c 在 `v-if` 不成立状态下，完全不会渲染，这是由 vue 决定的，所以设置值无效。
> 你可以把 `v-if` 改为 `v-show`
我现在是让所有条件都成立，按道理来说，abc都是'是'选项被选中，并且三段文本 展示a，展示b，展示c都显示，结果是3个文本显示了，但是回显只会回显2个a和c，b不会回显

**Comment by sendya** [comment]
> 我现在是让所有条件都成立，按道理来说，abc都是'是'选项被选中，并且三段文本 展示a，展示b，展示c都显示，结果是3个文本显示了，但是回显只会回显2个a和c，b不会回显

你设置值时，表单并没有 b, c 两个表单元素

**Comment by sendya** [comment]
哦 我好像看错了是吧

**Comment by alibababa888** [comment]
> 哦 我好像看错了是吧

![image](https://user-images.githubusercontent.com/53844772/76495703-5d255b00-6472-11ea-8b0a-093f59fcce30.png)
这个是回显效果，一定是中间那项没法回显

**Comment by sendya** [comment]
https://jh3m9.csb.app/

**Comment by sendya** [comment]
你是想对非 form-item 组件进行动态的属性判断 渲染吗

**Comment by alibababa888** [comment]
> 你是想对非 form-item 组件进行动态的属性判断 渲染吗

对的，这是codesandbox 复现
![image](https://user-images.githubusercontent.com/53844772/76497024-2c92f080-6475-11ea-8cb7-0cfc871da707.png)

**Comment by alibababa888** [comment]
> https://jh3m9.csb.app/
> 
> 没有你说的问题，请提供 codesandbox 复现
> 
> 对了，请不要用 0 / 1 可能会被 js 转换为 false /true 也有可能 ，你排查一下是否这个问题

这个问题我之前考虑过，所以专门输出了值，并没有被转换掉

**Comment by sendya** [comment]
这问题好像只在 空的 form-item 上 v-if 出现的

**Comment by alibababa888** [comment]
> 这问题好像只在 空的 form-item 上 v-if 出现的

我项目做了非常多组类似于这种的结构，每组里面一个radio，然后根据radio值来v-if判断对应数据是否渲染，测试数据全部选项都是一个值，结果渲染回显radio是跳着渲染的，部分有选中，部分没选中

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/beautiful-bush-j914n   先添加key 解决吧

**Comment by alibababa888** [comment]
> https://codesandbox.io/s/beautiful-bush-j914n 先添加key 解决吧

好的，这个确实可以

**Comment by tangjinzhou** [comment]
1.5.0 新增 FormModel 组件，表单的另一种选择

**Comment by uniquejava** [comment]
这个是很常见的需求。~ 我也碰到过。 好难找到解决方案。

**Comment by axCodeInt** [comment]
v-decorator 是不是不能和setFieldsValue 配合使用呢？
提示
```console
warning.js?d96e:34 
Warning: You cannot set a form field before rendering a field associated with the value. You can use `getFieldDecorator(id, options)` instead `v-decorator="[id, options]"` to register it before render.
```
