### ISSUE TITLE
upload  beforeUpload钩子不执行

### ISSUE THREAD

**Issue by okwangyu** [vueComponent/ant-design-vue#187]
上传时验证token，但是这个钩子不执行

**Comment by okwangyu** [comment]
![image](https://user-images.githubusercontent.com/24237417/45475032-c5a45680-b76d-11e8-9f80-b7c027539c2d.png)
![image](https://user-images.githubusercontent.com/24237417/45475055-d48b0900-b76d-11e8-96a5-3c4e08adb531.png)
控制台上没有东西

**Comment by watsonhaw5566** [comment]
@okwangyu 我想问一下怎么在上传的时候加入token呢？我也遇到了这个需求，谢谢
