### ISSUE TITLE
可伸缩列 table 参数名称冲突

### ISSUE THREAD

**Issue by zheng-qipeng** [vueComponent/ant-design-vue#1870]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
Table Resizable column

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/zheng-qipeng/tableResizableColumn)

### Steps to reproduce
/* const ResizeableTitle = (h, props, children) => { */
const ResizeableTitle = (h1) => {
const props = h1.props
const children = h1.children
}

### What is expected?
const ResizeableTitle = (h1) => {
const props = h1.props
const children = h1.children
}

### What is actually happening?
const ResizeableTitle = (h, props, children) => {
}

---
Argument name clash

**Comment by tangjinzhou** [comment]
？

**Comment by zheng-qipeng** [comment]
> ？

1.4.11 版本  新增可拖拽调整表格列宽示例  示例代码有误

**Comment by tangjinzhou** [comment]
有啥误  没看出来

**Comment by herosPan** [comment]
ResizeableTitle 函数一执行 return 模板语法 就报错

**Comment by zheng-qipeng** [comment]
> ResizeableTitle 函数一执行 return 模板语法 就报错，是缺少依赖解析不了吗

不是，好像只是参数重复的错误
const ResizeableTitle = (h, props, children) => {}
改成
const ResizeableTitle = ({props, children}) => {}

**Comment by herosPan** [comment]
> > ResizeableTitle 函数一执行 return 模板语法 就报错，是缺少依赖解析不了吗
> 
> 不是，好像只是参数重复的错误
> const ResizeableTitle = (h, props, children) => {}
> 改成
> const ResizeableTitle = ({props, children}) => {}

https://codesandbox.io/s/competent-wildflower-ghr24?file=/src/App.vue   h参数是不能去掉的
