### ISSUE TITLE
列元素宽度不足以填充整个表格时，fixed:left的元素右边会出现留白

### ISSUE THREAD

**Issue by TioJS** [vueComponent/ant-design-vue#1872]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.6

### Environment
windows10,google chrome 80.0.3987.132,vue 2.6.10

### Reproduction link
none

### Steps to reproduce
一张足够宽的表， 并且内容不足以填充宽度，第一列fixed:left

### What is expected?
fixed:left的列宽度同样进行自动拉伸填充

### What is actually happening?
fixed:left的列没有自动拉伸，右侧出现留白

**Comment by sendya** [comment]
请提供复现，谢谢

**Comment by SpecialSupportSection** [comment]
下面是一个简单的复现代码：
`<template>
  <a-table
    style="width: 1366px"
    :columns="columns"
    :dataSource="dataSource"
  />
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'

@Component
export default class Example extends Vue {
  columns=[{
    title: 'column1',
    dataIndex: 'column1',
    fixed: 'left'
  }, {
    title: 'column2',
    dataIndex: 'column2'
  }, {
    title: 'column3',
    dataIndex: 'column3'
  }]
  dataSource=[
    {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }, {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }, {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }, {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }, {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }, {
      column1: '我的右边有留白',
      column2: '我是正常的',
      column3: '我是正常的'
    }
  ]
}
</script>

<style lang="less" scoped>

</style>
`
有时需要加入fixed:left来适应的左右scroll的情况，但如果此时用户将窗口放大（或者2k屏），表格变宽，表格宽度需要拉伸填充，此时，fixed:left会导致表格断层（即出现留白）

上面的代码用写死表格宽度的方式做了一个展示

**Comment by betgar** [comment]
https://www.antdv.com/components/table-cn/#%E5%9B%BA%E5%AE%9A%E5%A4%B4%E5%92%8C%E5%88%97

请尝试建议留一列（非固定列）不设宽度以适应弹性布局

**Comment by TioJS** [comment]
我的情况是所有列都不设宽度，srcoll属性传 `srcoll:{x:true}`时，希望一部分列fixed 之后表格仍可以自适应宽度，不产生留白。

分析了得到的dom结构后我发现ant-design-vue里面table列的fixed是通过对原有列添加`display:none;`，然后单独写一列进行绝对定位，来实现的。产生留白的原因应该是`display:none;`的列进行了宽度自适应拉伸，而绝对定位的元素无法做到。

以上是我对问题产生原因的分析，可能我的需求目前ant-design-vue还不能满足，目前已经更换了实现方案。

感谢官方的热心指点！

**Comment by rickding** [comment]
https://github.com/zhangdaiscott/jeecg-boot/issues/1624 JeecgBoot的前端页面遇到了这样的问题。

**Comment by ZengJun-cloud** [comment]
@arika163  请问有解决这个问吗？

**Comment by arika163** [comment]
> @arika163 请问有解决这个问题吗？

这是我现在用的方案：
tableLayout: auto
scroll:{ x: max-content }
固定宽度列 写width
伸缩列 写max-width和min-width

**Comment by ZengJun-cloud** [comment]
> > @arika163 请问有解决这个问题吗？
> 
> 这是我现在用的方案：
> tableLayout: auto
> scroll:{ x: max-content }
> 固定宽度列 写width
> 伸缩列 写max-width和min-width

没太懂这个方案的意思，有demo示例吗？
我这边是通过修改了fixed那一列的样式，去掉了border，但是表格会有一点奇怪。
