### ISSUE TITLE
Issue with layout-header and layout-sider on Universal mode

### ISSUE THREAD

**Issue by minhthien309** [vueComponent/ant-design-vue#1874]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.10

### Environment
Chrome: 80.0.3987.132, Nuxt: 2.0.0

### Reproduction link
[https://www.antdv.com/components/layout/#Custom-trigger](https://www.antdv.com/components/layout/#Custom-trigger)

### Steps to reproduce
I'm having an issue with layout header and layout sider when using Universal mode.
When page is loading, my layout was broken. But when the page loaded, it run normally

### What is expected?
![Image of Yaktocat](https://i.imgur.com/5JC3HKJ.png)

### What is actually happening?
![Image of Yaktocat](https://i.imgur.com/mHkErnt.png)

**Comment by tangjinzhou** [comment]
样式没有加载完成吧

**Comment by minhthien309** [comment]
> 样式没有加载完成吧
> 
> css is not loaded

do you have any solution?

**Comment by tangjinzhou** [comment]
may be you can import css at entry file.

**Comment by minhthien309** [comment]
> may be you can import css at entry file.

I'm using nuxtjs and my css are in css and plugins sector of nuxt.config.js. Is this load before page loaded?

**Comment by AshenBird** [comment]
这个错误我也出现了，实际上是webpack 热更新 的错误阻塞了渲染。
this mistake appear in my project too. actually,  error of webpack HMR blocked render.

> Uncaught (in promise) Error: Maximum recursive updates exceeded. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

目前观测到的触发条件有两条。
currently, i can find two condition。

1. LayoutAside 组件有 Layout 组件作为祖先组件
1. LayoutAside component has Layout component as ancestor

2. 在引用了 LayoutAside 组件的文件进行修改，发生热更新
2. change in the file which import LayoutAside component, trigger HMR
