### ISSUE TITLE
Multiple Upload Component Event onChange not working 

### ISSUE THREAD

**Issue by erwinyusrizal** [vueComponent/ant-design-vue#1876]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
windows, chrome, 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
```
<a-row :gutter="16" v-for="k in repairmentForm.getFieldValue('breakdowns')" :key="k">
    <a-col :span="24">
        <a-upload
        name="media"
        :action="formType == 'add' ? 'http://2c8bd77c.ngrok.io/v1/media/tmp' : 'http://2c8bd77c.ngrok.io/v1/media'"
        :data="uploadData"
        listType="picture-card"
        :fileList="breakdownMedias['breakdown_media_' + k]"
        :headers="uploadHeaders"
        :beforeUpload="(e) => handleBeforeUpload(e, 'breakdown', k)"
        @preview="handleUploaderPreview"
        @change="(e) => handleUploaderChange(e, 'breakdown', k)">
            <a-icon type="plus" />
            <div class="ant-upload-text">Upload</div>
        </a-upload>
        <a-modal :visible="preview.visible" :title="preview.title" :footer="null" @cancel="handleUploaderPreviewCancel">
            <img alt="example" style="width: 100%" :src="preview.image" />
        </a-modal>
    </a-col>
</a-row>


handleUploaderChange(info, module, key){
    const self = this;
    if(module == 'request'){
        self.requestMedias = info.fileList;
    }else{
        console.log(info)
        if(info.file.status == 'done'){
            self.breakdownMedias['breakdown_media_' + key] = info.fileList;
        }
    }
}
```

### What is expected?
The upload info.status has to be change also the uploading progress has be appeared too

### What is actually happening?
No upload progress/picture list, info.status always uploading

**Comment by CondiGao** [comment]
+1

**Comment by 15010682365** [comment]
Because the value of fileList is set？

**Comment by Robin-zero** [comment]
When 'if' appeared in the change callback, only the 'uploading' status appeared!
![image](https://user-images.githubusercontent.com/22169252/84642292-d4b1cd00-af2e-11ea-8e26-95942070a31a.png)

**Comment by blakelu** [comment]
+1

**Comment by ccrcw1314** [comment]
this situation only happend on 'fileList' bind with double dimensional array

**Comment by erwinyusrizal** [comment]
Any update on this issue ? @tangjinzhou
