### ISSUE TITLE
upload  @change="handleChange" 只执行一次

### ISSUE THREAD

**Issue by okwangyu** [vueComponent/ant-design-vue#188]
![image](https://user-images.githubusercontent.com/24237417/45476283-22554080-b771-11e8-8429-279122dac9b3.png)
按照文档是应该是2次以上

**Comment by wangxueliang** [comment]
是多次执行哈，再者你提的问题太简单了，无法定位问题

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/issue-helper/

**Comment by exculibar** [comment]
当指定了 fileList 属性之后，我碰到了同样的问题。
后来我把 fileList 属性换成 defaultFileList 就能正常触发了

**Comment by maroon1** [comment]
正如 @exculibar 所说的，确实存在这个问题，请开发团队重开这个 issue @tangjinzhou

**Comment by lk8888** [comment]
请问现在这个问题解决了吗？我现在页遇到了这个问题

**Comment by okwangyu** [comment]
加qq565318790



------------------ 原始邮件 ------------------
发件人: "lk8888"<notifications@github.com>; 
发送时间: 2019年9月17日(星期二) 下午4:26
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>; 
抄送: "565318790"<565318790@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vueComponent/ant-design-vue] upload  @change="handleChange" 只执行一次 (#188)




请问现在这个问题解决了吗？我现在页遇到了这个问题

**Comment by ljwrer** [comment]
you need to set your fileList while uploading
