### ISSUE TITLE
a-date-picker

### ISSUE THREAD

**Issue by perfectDefect** [vueComponent/ant-design-vue#1880]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue2.0

### Reproduction link
[http://ksyct.hljagri.org.cn/#/login](http://ksyct.hljagri.org.cn/#/login)

### Steps to reproduce
这个组件重置略费劲 用时间字符串还要用mont

### What is expected?
不用引mont直接传入时间格式字符串就可以使用 传入空可以清空

### What is actually happening?
多引用了个mont

**Comment by sendya** [comment]
清空请设置值为 undefined 即可，本组件需要利用 monent 进行计算时间差，以及每月天数，周六日计算。无法去除。
