### ISSUE TITLE
日期组件默认使用validateFields不会校验，而且会导致其他表单也不会

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#1882]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
win10，chrome80，vue 2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-http-w7wmi?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
直接点击提交按钮，自定义校验不会生效，而且如果存在其他表单元素也会失败

### What is expected?
点击validateFields会自动使用自定义校验的功能

### What is actually happening?
直接跳过，而且不会发生错误提示

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/elated-shannon-vc2w1

It caused by your validator with some error that callback can not be called. You can use async instead or use try...catch to catch the error:

```js
validator: async (rule, value) => {
  throw new Error('Something wrong!');
}

// or

validator(rule, value, callback) => {
  try {
    throw new Error('Something wrong!');
  } catch (err) {
    callback(err);
  }
}
```
