### ISSUE TITLE
ReferenceError: isAntBtn is not defined

### ISSUE THREAD

**Issue by jervainy** [vueComponent/ant-design-vue#1892]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
macOS Catalina 10.15.3   chrome 80.0.3987.132  vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-9c35w)

### Steps to reproduce
<a-popconfirm>
<a-button :disabled="true">xxxx</a-button>
</a-popconfirm>

### What is expected?
按钮有一个气泡确认框，当按钮不可用时气泡确认框点击后没有内容

### What is actually happening?
APopconfirm里使用AButton，将AButton的属性设置为true，会导致AButton直接从页面中消失

---
1.5.0-rc.3同样存在这样的问题

**Comment by tangjinzhou** [comment]
ref #1890
