### ISSUE TITLE
Form表单validateFields获取值为undefined

### ISSUE THREAD

**Issue by mustars** [vueComponent/ant-design-vue#1893]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
win10，ant 1.4.12、vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-l87wf)

### Steps to reproduce
在表单初值化后，直接validateFields获取表单内的值。比如为空的文本框，获取得到的值是undefined。在以前版本得到的值空字符。

### What is expected?
得到的值为空字符串

### What is actually happening?
得到的值为undefined

**Comment by tangjinzhou** [comment]
哪个版本得到的是空字符串 

如果都是空字符串并不科学，有些数组有些是对象有些是数字  不能一概而论
