### ISSUE TITLE
Icons bundle size

### ISSUE THREAD

**Issue by mapsgeek** [vueComponent/ant-design-vue#1896]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
windows, chrome, 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-3q4he)

### Steps to reproduce
Build any vuejs project with ant design

### What is expected?
icons should be imported on usage only

### What is actually happening?
the whole icons set is being imported into the bundle size

        

i don't even the <a-icon> component in my app
![image](https://user-images.githubusercontent.com/10188264/76943318-d5bf6800-6907-11ea-8358-d8c8f2da155f.png)

**Comment by sendya** [comment]
https://github.com/vueComponent/pro-layout/blob/master/examples/vue.config.js#L39-L43
https://github.com/vueComponent/pro-layout/blob/master/examples/src/core/antd/icons.js

在 main 引入需要的 icons ，来完成按需加载图标，还不懂就搜索 issue 列表，有案例

**Comment by mapsgeek** [comment]
thank you that works.
to clarify for anyone not getting this make a file icons.js
add the file to be resolve to your vue config

**Comment by ttodua** [comment]
Well, we are experiencing the same issue. I understand what we can do that by "resolves", however, there should be some simpler way (i.e. plugin option or whatever) to avoid loading of those icons , without needing from us to create separate templates/files (for resolving) to fix that issue.
