### ISSUE TITLE
CDN方式引入antd tree-select 等组件无法渲染

### ISSUE THREAD

**Issue by bug4j** [vueComponent/ant-design-vue#1898]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
window 10 1903 chrome 80

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-ganguly-m65x7)

### Steps to reproduce
官网示例都无法的带正常结果

### What is expected?
正常渲染组件

### What is actually happening?
正常渲染组件

**Comment by tangjinzhou** [comment]
你提供的示例没看出有什么问题啊
