### ISSUE TITLE
locale-provider 组件 在根节点使用时打包会把多国语言全部打包，导致文件过大

### ISSUE THREAD

**Issue by ruyangit** [vueComponent/ant-design-vue#190]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
只需要中英 或日文 切换，希望通过 指定的几门语言，打包时减少包体积

### What does the proposed API look like?
如题，能否指定两国语言，moment 也是载入了所有的多国语言。

**Comment by ruyangit** [comment]
ant-design-vue 开发的pro  source ：https://github.com/ruyangit/seed-workbench-ui.git

**Comment by ruyangit** [comment]
感谢！

**Comment by ruyangit** [comment]
https://ruyangit.gitee.io/seed-workbench-ui 推一下自己写的 admin @tangjinzhou

**Comment by tangjinzhou** [comment]
你可以提交PR，添加相关链接
https://github.com/vueComponent/ant-design-vue-pro/blob/master/README.md
