### ISSUE TITLE
Unknown custom element: <a-form-model> and <a-page-header>

### ISSUE THREAD

**Issue by arturcesarmelo** [vueComponent/ant-design-vue#1900]
**I KNOW THE REPOSITORY ISSUE RULES** 
but this is not a complex enough problem to demand an codepen. Some one may have face it and can tell me how to solve it.

I've follow the instructions from site.

Install the package into a Vue CLI project
`npm i --save ant-design-vue`

Full Imported into main.js according to the site instructions.
```js
import Vue from 'vue';
import Antd from 'ant-design-vue';
import App from './App';
import 'ant-design-vue/dist/antd.css';

Vue.config.productionTip = false;

Vue.use(Antd);
```

But while some components works great, the `<a-page-header>`  and `<a-form-model>` for example, does not works. In the console we can see the message bellow:

![Screen Shot 2020-03-18 at 18 29 20](https://user-images.githubusercontent.com/18191910/77009284-69178e00-6946-11ea-994d-2cabbc0d4f58.png)

Thank you, guys!

**Comment by top-dante** [comment]
So am I，Come here to ask about this problem, and find out that only you, brother, have the same problem

**Comment by tangjinzhou** [comment]
support from 1.5.0-rc.4

**Comment by vidyakin** [comment]
I have the same problem in existing project after upgrade ant-design from 1.4 to "^1.5.0-rc.6"
But in a new simple project with the same version "^1.5.0-rc.6" there is NO that problem!! 
What is it??

**Comment by dojoVader** [comment]
I noticed the same issue and these worked for me:
 components: {
    'a-form-model-item': FormModel.Item,
    'a-form-model': FormModel
  },
