### ISSUE TITLE
tree 树形组件 slot-scope selected 无效

### ISSUE THREAD

**Issue by webrtcn** [vueComponent/ant-design-vue#1901]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
os: macOS  vue: 2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/223](https://github.com/vueComponent/ant-design-vue/issues/223) 

https://codesandbox.io/s/naughty-shadow-jcfvw

### Steps to reproduce
官方网站 https://www.antdv.com/components/tree-cn/  自定义图标部分选中不能自动切换图标

```
<template slot="custom" slot-scope="{selected}">
<a-icon :type="selected ? 'frown':'frown-o'" />
</template>

```

selected = undefined

### What is expected?
selected 能正常获取到值

### What is actually happening?
selected 不能正常获取到值

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/1a61d1fa322578e5f2ca3ee8074930aa52faa332  
等 1.5.0-rc.5

**Comment by Flourad** [comment]
> [1a61d1f](https://github.com/vueComponent/ant-design-vue/commit/1a61d1fa322578e5f2ca3ee8074930aa52faa332)
> 等 1.5.0-rc.5

更新到最新版本 还是取不到selected
