### ISSUE TITLE
Ant design中的PageHeader在Vue中不能使用，在单独注册PageHeader组件时，发现Lib目录并没有这个组件

### ISSUE THREAD

**Issue by Riceonc** [vueComponent/ant-design-vue#1902]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
vue 2.6.11,chrome 79.0.3945.88, windows 10

### Reproduction link
[https://www.antdv.com/components/page-header-cn/](https://www.antdv.com/components/page-header-cn/)

### Steps to reproduce
在任意组件中引入<a-page-header/>都会报错

### What is expected?
引入<a-page-header/>可以使用，页面显示与官方文档一致

### What is actually happening?
浏览器报错显示组件未注册

**Comment by sendya** [comment]
更新到最新，这是最新版才提供的功能

**Comment by Riceonc** [comment]
> 更新到最新，这是最新版才提供的功能

更新到1.5.0-rc.3么？

**Comment by tangjinzhou** [comment]
看更新日志

**Comment by cdll** [comment]
same issue here~
