### ISSUE TITLE
Will Summary Row In Ant Design 4  Be Merged in Release 1.5 ?

### ISSUE THREAD

**Issue by ngloom** [vueComponent/ant-design-vue#1903]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Summary Row Is Important In Many Report System.

### What does the proposed API look like?
Just like the  Summary Row in https://ant.design/components/table

![image](https://user-images.githubusercontent.com/495831/77028584-243a3880-69d4-11ea-9a7d-1e84c19663f3.png)

**Comment by tangjinzhou** [comment]
no  
Support at least 2.0

**Comment by leslieeilsel** [comment]
> no
> Support at least 2.0

期待ing

**Comment by scoutrul** [comment]
I very needs this too!
