### ISSUE TITLE
在Tree组件中，使用scopedSlots放置checkbox组件，CheckBox无法选中

### ISSUE THREAD

**Issue by littlebaozi** [vueComponent/ant-design-vue#1904]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
ant-design-vue 1.4.12，vue 2.6.11, chrome  80.0.3987.132（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-p53s8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击slots中的自定义的checkbox

### What is expected?
checkbox能够点击选择

### What is actually happening?
checkbox点击无反应

**Comment by webrtcn** [comment]
我感觉咱们俩是同一个 BUG https://github.com/vueComponent/ant-design-vue/issues/1901

**Comment by tangjinzhou** [comment]
duplicate #1901

**Comment by littlebaozi** [comment]
目前使用table tree替代实现了功能。
[demo参考](https://codesandbox.io/s/vue-antd-tree-slots-checkbox-rbyc3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by tinynemo** [comment]
这个bug没解决呀，在title的slots中自定义的checkbox不能被check。见 @littlebaozi 的codesandbox示例。

**Comment by xi-qi** [comment]
没解决啊，我这还是不能选中，"version": "2.0.0",
