### ISSUE TITLE
template风格的table组件，只要设置sorter或者filter就会出现样式问题

### ISSUE THREAD

**Issue by nie55352177** [vueComponent/ant-design-vue#1906]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
windows10,google chrome 79.0.3945.130,vue 2.6.10

### Reproduction link
none

### Steps to reproduce
使用template风格的table，在任意列设置  :sorter="true" 或者 :filters="[{text:'test',value='1'}]"
都会导致样式出错
### What is expected?
修复样式错误

### What is actually happening?
修复样式错误

**Comment by nie55352177** [comment]
@tangjinzhou

**Comment by tangjinzhou** [comment]
ref #1914
