### ISSUE TITLE
table组件的Table中使用defaultExpandAllRows无效

### ISSUE THREAD

**Issue by 344797142** [vueComponent/ant-design-vue#191]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.3

### Environment
win7  谷歌 68.0.3440.106  vue3 用桥接技术使用的vue2命令

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/table-cn/](https://vuecomponent.github.io/ant-design-vue/components/table-cn/)

### Steps to reproduce
defaultExpandAllRows加上无效

### What is expected?
使用defaultExpandAllRows让所有行都展开

### What is actually happening?
加上没反应

**Comment by tangjinzhou** [comment]
并没有问题啊 
https://codesandbox.io/s/znnz3op8wp
如果你有问题，请提供复现bug的链接，谢谢

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/45584364-b99ecd00-b904-11e8-88db-2b3e6e360458.png)
PS：初始时
