### ISSUE TITLE
2.0 计划

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#1911]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
- [x] 1、~~按需加载icon~~   **2.0.0-beta.1**

- [ ] 2、rtl

- [x] 3、slot-scope 改成单参数 **2.0.0-beta.2**

- [x] 4、暗黑模式

- [ ] 5、antd 4.0 设计规范

- [x] 6、兼容 vue 3.x #1913 

- [x] 7、文档示例统一使用 v-model，简化 defaultXXX 的存在，降低理解成本 **2.0.0-beta.2**

- [x] 8、~~日期相关组件支持字符串形式的 value 属性~~  **1.5.4**

- [ ] 10、colorpicker 颜色选择器

- [ ] 11、ConfigProvider 支持 componentSize 用来支持全局切换组件大小 #1121 

### 需要您的支持

![image](https://user-images.githubusercontent.com/6937879/77142219-5e7e0580-6aba-11ea-8d4d-cddee4c8709f.png)

**Comment by anncwb** [comment]
占个楼,支持下

**Comment by artiely** [comment]
:sparkling_heart:
:thumbsup:

**Comment by zjh599245299** [comment]
加油 期待2.0版本

**Comment by wkl007** [comment]
支持支持！！！

**Comment by nabaonan** [comment]
期待~

**Comment by shungdawei** [comment]
666

**Comment by LiuSuY** [comment]
期待

**Comment by l619534951** [comment]
我还以为这个是ant design 的官方项目，没想到是个人项目，太不容易了，之前iview就维护了一个版本

**Comment by polichan** [comment]
支持

**Comment by jinan5694** [comment]
请问预计什么时间发布呢？

**Comment by tangjinzhou** [comment]
> 请问预计什么时间发布呢？

预计两周内会优先发布icon按需加载

**Comment by betgar** [comment]
期望能够使用day.js替换moment.js, 虽然有这个https://github.com/ant-design/antd-dayjs-webpack-plugin,因为文档没有提到任何和ant design vue相关信息,所以不放心,希望官方在2.0能够测试确认下是否可以可用,而且是否经过测试无问题

**Comment by zlab** [comment]
能否去掉npm postinstall广告？

**Comment by l619534951** [comment]
> 能否去掉npm postinstall广告？

这么大的项目个人维护本来就不容易，有点广告怎么了？

**Comment by tangjinzhou** [comment]
> 期望能够使用day.js替换moment.js, 虽然有这个[https://github.com/ant-design/antd-dayjs-webpack-plugin,因为文档没有提到任何和ant](https://github.com/ant-design/antd-dayjs-webpack-plugin,%E5%9B%A0%E4%B8%BA%E6%96%87%E6%A1%A3%E6%B2%A1%E6%9C%89%E6%8F%90%E5%88%B0%E4%BB%BB%E4%BD%95%E5%92%8Cant) design vue相关信息,所以不放心,希望官方在2.0能够测试确认下是否可以可用,而且是否经过测试无问题

你可以在 1.5版本中自测哦

**Comment by dargoner** [comment]
请考添加，4.1的紧凑主题

**Comment by aquanlerou** [comment]
期待2.0

**Comment by xrkffgg** [comment]
RTL 的这部分 有人做了吗？

**Comment by tangjinzhou** [comment]
> RTL 的这部分 有人做了吗?
> @tangjinzhou

还没有哦  稍后我会单独开 rtl 分支出来

**Comment by xrkffgg** [comment]
我在 ant-design 那边做了很多 RTL 方面的工作，比较熟，如果需要，这块我可以来帮忙~

**Comment by l619534951** [comment]
> 我在 ant-design 那边做了很多 RTL 方面的工作，比较熟，如果需要，这块我可以来帮忙~
> [ant-design/ant-design#22239](https://github.com/ant-design/ant-design/issues/22239)

牛笔牛笔，666666

**Comment by dargoner** [comment]
> 我在 ant-design 那边做了很多 RTL 方面的工作，比较熟，如果需要，这块我可以来帮忙~
> [ant-design/ant-design#22239](https://github.com/ant-design/ant-design/issues/22239)

大牛，请上坐

**Comment by tangjinzhou** [comment]
> 我在 ant-design 那边做了很多 RTL 方面的工作，比较熟，如果需要，这块我可以来帮忙~
> [ant-design/ant-design#22239](https://github.com/ant-design/ant-design/issues/22239)
@xrkffgg 
太需要了  我会在完成图标完成后，开分支出来

**Comment by ruibaby** [comment]
期待 color picker。

**Comment by ngloom** [comment]
加油加油， 期待Table Summary Row!

**Comment by tangjinzhou** [comment]
> 我在 ant-design 那边做了很多 RTL 方面的工作，比较熟，如果需要，这块我可以来帮忙~
> [ant-design/ant-design#22239](https://github.com/ant-design/ant-design/issues/22239)

  https://github.com/vueComponent/ant-design-vue/pull/new/feat-rtl

**Comment by xrkffgg** [comment]
@tangjinzhou OK

**Comment by dzcpy** [comment]
想请问下，大概多久能移植好antd 4?

**Comment by dzcpy** [comment]
另外 color-picker 我基于 vue-color 做了一个，如果需要的话可以贡献下代码

**Comment by dzcpy** [comment]
还有希望能把 babel-import 的集成问题能修复下

**Comment by baojie223** [comment]
需要用dayjs替换掉目前的moment吗，可以的话我想做一下

**Comment by tangjinzhou** [comment]
> 还有希望能把 babel-import 的集成问题能修复下。整个引用包太大，一个个的引用太麻烦了

@dzcpy 集成有啥问题

**Comment by tangjinzhou** [comment]
> 需要用dayjs替换掉目前的moment吗，可以的话我想做一下

不会替换，只做兼容

**Comment by wd4219** [comment]
> 需要用dayjs替换掉目前的moment吗，可以的话我想做一下

我在项目中使用了 antd的dayjs替换插件，preset: antd3 目前没发现问题，可以替换moment

**Comment by baojie223** [comment]
@tangjinzhou 第七个是要把代码里涉及到的$slots都改成$scopedSlots的形式吗，我正在做这个

**Comment by SnowyEvening** [comment]
@tangjinzhou 你好，请问关于第五条——antd 4.0 设计规范，这个计划将table的虚拟表格移植过来吗？

**Comment by tangjinzhou** [comment]
> @tangjinzhou 你好，请问关于第五条——antd 4.0 设计规范，这个计划将table的虚拟表格移植过来吗？

那是个示例，不是antd提供的功能，理论上现在的table就可以支持

**Comment by jinan5694** [comment]
> > @tangjinzhou 你好，请问关于第五条——antd 4.0 设计规范，这个计划将table的虚拟表格移植过来吗？
> 
> 那是个示例，不是antd提供的功能，理论上现在的table就可以支持

看了react的示例，components支持传递一个渲染对象。但是在我们的api中不能这样使用。
```jsx
    <Table
        {...props}
        className={classNames(className, 'virtual-table')}
        columns={mergedColumns}
        pagination={false}
        components={{
          body: renderVirtualList,
        }}
      />
```
下面是我的写法
```jsx
      tableComponents: {
        body: {
          render() {
            return <div>body</div>
          }
        }
      }
```
下面的写法可以渲染出test的row，但不符合我的预期。
```jsx
      tableComponents: {
        body: {
          row: {
            render() {
              return <div>test</div>
            }
          }
        }
      }
```
文档中没有详细的描述信息。请问这个api应该如何使用呢？

源码中的结构
```js
const createComponents = (components = {}) => {
  const bodyRow = components && components.body && components.body.row;
  return {
    ...components,
    body: {
      ...components.body,
      row: createBodyRow(bodyRow),
    },
  };
};
```

**Comment by FAKER-A** [comment]
select treeselelct 添加loading参数

**Comment by top-dante** [comment]
2.0试了一下 这个 a-icon怎么用

**Comment by rpdg** [comment]
希望 Form 组件api 能跟react版本的同步更新，目前react版本的Form使用起来简化了不少

**Comment by lifedre** [comment]
兼容vue 3.0加油

**Comment by dzcpy** [comment]
> 希望 Form 组件api 能跟react版本的同步更新，目前react版本的Form使用起来简化了不少

我反而觉得 model form 简化了很多，比 React 的那个另类的 async-validator 的 api 直观太多了

**Comment by DinoRun** [comment]
大佬，有select的虚拟滚动吗

**Comment by Vincent0700** [comment]
期待移植V4的暗黑主题

**Comment by HenryWong-fe** [comment]
期待table组件的sticky支持,使用fixed创建额外表格的方式来做固定头和固定列对表格性能的影响真的挺大的

**Comment by mark0325** [comment]
提个建议：2.0时 momentjs语言包可按需加载，或者移除momentjs，根据自己的需要引入momentjs

**Comment by yue-fei** [comment]
大表单渲染性能不好，4.0应该解决了

**Comment by xiongc** [comment]
> 期待table组件的sticky支持,使用fixed创建额外表格的方式来做固定头和固定列对表格性能的影响真的挺大的

顶一下

**Comment by 5dong** [comment]
是否可以增加表格列拖拽排序，就是替换列顺序，目前碰到这个报表需求 还没想好怎么实现

**Comment by zkwolf** [comment]
> 是否可以增加表格列拖拽排序，就是替换列顺序，目前碰到这个报表需求 还没想好怎么实现
> 虽然vue Draggableg有，但不知道怎么集成
> https://sortablejs.github.io/Vue.Draggable/#/table-column-example
> 大神能否给个思路 @tangjinzhou 谢谢！

https://codesandbox.io/s/draggable-table-e07sm 你可以看看自己完善一下

**Comment by isyoungxl** [comment]
能不能出一个时间段选择器~

**Comment by isyoungxl** [comment]
期望有一个嵌套的 Model对话框。Model嵌套Model

**Comment by jave-joe** [comment]
希望modal支持可拖拽。

**Comment by m01i0ng** [comment]
> 期待移植V4的暗黑主题

dark 暂时可以这么用：

提取 antd 的 `color` 文件夹和 `dark.less`，`dark.less` 头部修改为

![image](https://user-images.githubusercontent.com/19723234/86571488-110fa080-bfa4-11ea-9da9-32345fca20f1.png)

然后在引用全局样式时引用 `dark.less`

![image](https://user-images.githubusercontent.com/19723234/86571590-3d2b2180-bfa4-11ea-9e56-0d59958b73c0.png)

试过目前暂时没有什么大问题

**Comment by dzcpy** [comment]
@tangjinzhou 2.0 会解决这个问题啊？
https://github.com/ant-design/ant-design/issues/12011#issuecomment-588608270
目前 Icons 打包前来太大了

**Comment by sendya** [comment]
> @tangjinzhou 2.0 会解决这个问题啊？
> [ant-design/ant-design#12011 (comment)](https://github.com/ant-design/ant-design/issues/12011#issuecomment-588608270)
> 目前图标打包前来太大了，有5-6百K。只用一个图标也要打包所有图标

目前的所有版本均可以使用下面的方式解决 icons 全量引入的问题，另外 2.0 很早就重构了 icons，支持单图标引入，但同样的。你用任何图标，都需要手动引入

https://github.com/vueComponent/pro-layout/blob/master/examples/vue.config.js#L39-L43
https://github.com/vueComponent/pro-layout/blob/master/examples/src/core/antd/icons.js

**Comment by wkl007** [comment]
期望虚拟滚动！！！

**Comment by xiaofuliang** [comment]
期待有紧凑模式

**Comment by andyesfly** [comment]
能不能有个主题设计工具，或者主题整体替换的解决方案

**Comment by zhoufenfens** [comment]
级联选择器有计划支持multiple选项吗

**Comment by zhou881117** [comment]
暗黑模式 大概计划吗？

**Comment by dzcpy** [comment]
2.0 合并 antd 4 的改变了吗？

**Comment by wensonsmith** [comment]
Table 性能得优化啊， 加载 1000 条数据就卡屁了。 同样的情况 iview 和 element 都不卡顿。

**Comment by athrunsun** [comment]
> > @tangjinzhou 2.0 会解决这个问题啊？
> > [ant-design/ant-design#12011 (comment)](https://github.com/ant-design/ant-design/issues/12011#issuecomment-588608270)
> > 目前图标打包前来太大了，有5-6百K。只用一个图标也要打包所有图标
> 
> 目前的所有版本均可以使用下面的方式解决 icons 全量引入的问题，另外 2.0 很早就重构了 icons，支持单图标引入，但同样的。你用任何图标，都需要手动引入
> 
> https://github.com/vueComponent/pro-layout/blob/master/examples/vue.config.js#L39-L43
> https://github.com/vueComponent/pro-layout/blob/master/examples/src/core/antd/icons.js

意思是，把所有需要用到的图标集中到`src/core/antd/icons.js`中，然后在webpack打包时把`@ant-design/icons/lib/dist`这个import换成`./src/core/antd/icons.js`？

**Comment by dzcpy** [comment]
@athrunsun https://2x.antdv.com/docs/vue/migration-v2-cn/#图标升级

**Comment by 975914892** [comment]
table的合计功能会不会添加呢？自己试了下在footer里添加表格，会多出来一层边框，并且有横向滚动条的话两个table并不能联动；还试了每页最后一行push一条合计数据，但这两种情况有复选框的话都挺尴尬的

**Comment by dzcpy** [comment]
问下，2.0都已经beta5了，还会加antd4适配和暗黑theme吗？

**Comment by haichao0817** [comment]
希望优先暗黑主题

**Comment by tomgao365** [comment]
暗黑主题，估计要等ts重构结束才做

**Comment by ZhengXiaowei** [comment]
全局`componentSize`预计哪个beta版本会上

**Comment by dzcpy** [comment]
> 暗黑主题，估计要等ts重构结束才做

ts 重构大概什么时候能做好呢，有一个粗略的估计吗？

**Comment by dzcpy** [comment]
又 stale 了，想问下暗黑主题和升级 antd  4 有一个大概的计划吗？

**Comment by zkwolf** [comment]
dark theme的pr已经合并了，2.0下次发版应该就有了

**Comment by dargoner** [comment]
11、ConfigProvider 支持 componentSize 用来支持全局切换组件大小
这个实现了吗？

**Comment by zkwolf** [comment]
目前还没实现吧，我打算有时间就搞

**Comment by l619534951** [comment]
> 目前还没实现吧，我打算有时间就搞

大哥你好强呀

**Comment by xrkffgg** [comment]
> 目前还没实现吧，我打算有时间就搞

大哥你好强呀

**Comment by zkwolf** [comment]
> > 目前还没实现吧，我打算有时间就搞
> 
> 大哥你好强呀

哦不，潜台词是没时间（逃

**Comment by JinPengGeng** [comment]
table 性能可以优先解决吗？比如虚拟滚动。。。

**Comment by tangjinzhou** [comment]
暗黑已发布

**Comment by LuoHuacheng** [comment]
> 暗黑已发布

你好，请问RTL这部分现在可用吗？我看有人在做，有对应的分支与代码合并，但是网站上并没有完全体现出来。

**Comment by zkwolf** [comment]
RTL现在应该是不可用的，没合并进来

**Comment by wsxe9988** [comment]
多会能适配antd 4.0 设计规范呢

**Comment by songzhenze** [comment]
FormModel 表单大概什么时候能用呢？

**Comment by zkwolf** [comment]
2.0里formmodel是form的默认实现了

songzhenze ***@***.***> 于2021年4月2日周五 下午3:13写道：

**Comment by dzcpy** [comment]
已经跳车换 React 了，感觉 React 加入 Hooks 之后比 Vue 好用多了，不过 Nuxt 确实用着顺手，比 Next 强

**Comment by xiaofuliang** [comment]
@dzcpy react+hooks的脚手架能给份吗

**Comment by dzcpy** [comment]
@xiaofuliang https://github.com/SolidZORO/mkn
我拿这个改的

**Comment by ifu25** [comment]
table 支持合计
