### ISSUE TITLE
请问antv_demo不让fork是吗

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#1912]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome80

### Reproduction link
[https://github.com/tangjinzhou/ant-design-vue](https://github.com/tangjinzhou/ant-design-vue)

### Steps to reproduce
fork代码后没有demo

### What is expected?
fork代码后有demo

### What is actually happening?
fork代码后没有demo

**Comment by tangjinzhou** [comment]
是的   因组件库的健康持续发展，期望有一定的利益回报，目前的主要收入来源于官网广告，并且有一些私有化部署甚至是山寨网站，对团队收入有不小的冲击，望理解

很快我们会放出针对社区的开发环境，
如果有反馈官网的问题，建议通过提交issue的方式，我们会不定期给活跃贡献者开通文档管理权限

再次感谢关注！！！
