### ISSUE TITLE
Support Vue 3 & Vite from 2.0.0-beta.5

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#1913]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?

```bash
npm test -- ant-design-vue/components/button/__tests__/index.test.js --watch
```
##  beta

```bash
 npm i --save ant-design-vue@next
```

```js
// use
import { createApp } from 'vue';
import antd from 'ant-design-vue';
import 'ant-design-vue/components/style.js';
import App from './App.vue';
createApp(App).use(antd).mount('#app');
```

- [x] Affix
- [x] Anchor
- [x] AutoComplete
- [x] Alert
- [x] Avatar
- [x] BackTop
- [x] Badge
- [x] Breadcrumb
- [x] Button
- [x] Card
- [x] Cascader
- [x] Checkbox
- [x] Col
- [x] Divider
- [x] Dropdown
- [x] Icon
- [x] Input
- [x] InputNumber
- [x] Layout
- [x] ~~LocaleProvider~~ remove
- [x] message
- [x] Menu
- [x] Mentions
- [x] Modal
- [x] notification
- [x] Popconfirm
- [x] Popover
- [x] Progress
- [x] Radio
- [x] Rate
- [x] Row
- [x] Select
- [x] Spin
- [x] Statistic
- [x] Steps
- [x] Switch
- [x] Tabs
- [x] Tag
- [x] Timeline
- [x] Tooltip
- [x] Upload
- [x] Drawer
- [x] Skeleton
- [x] Comment
- [x] ConfigProvider
- [x] Empty
- [x] Result
- [x] Descriptions
- [x] PageHeader
- [x] Pagination
- [x] Collapse
- [x] Carousel
- [x] Calendar
- [x] DatePicker
- [x] TimePicker
- [x] Form、FormModel  we will merge them
- [x] Slider
- [x] Table
- [x] List
- [x] Transfer
- [x] Tree
- [x] TreeSelect

### 需要您的支持

![image](https://user-images.githubusercontent.com/6937879/77142219-5e7e0580-6aba-11ea-8d4d-cddee4c8709f.png)

**Comment by anhongpeng** [comment]
期待对 Vue3 的支持，加油加油~！

**Comment by wsz7777** [comment]
应该大部分是兼容的吧，jsx的结构上会发生变化？

**Comment by dinfer** [comment]
有什么进展么？

**Comment by xrkffgg** [comment]
- [ ] Spin https://github.com/vueComponent/ant-design-vue/pull/2351

**Comment by zkwolf** [comment]
- [ ] Divider #2357

**Comment by xrkffgg** [comment]
- [ ] https://github.com/vueComponent/ant-design-vue/pull/2360

**Comment by xrkffgg** [comment]
- [ ] Result https://github.com/vueComponent/ant-design-vue/pull/2362

**Comment by Amour1688** [comment]
- [x] Radio #2374

**Comment by thisisandy** [comment]
[x] Checkbox #2376

**Comment by sendya** [comment]
- [x] Descriptions #2385

**Comment by ununian** [comment]
- [x] Statistic  #2386

**Comment by tangjinzhou** [comment]
- [ ] Tooltip

**Comment by liulinboyi** [comment]
* [x]  BackTop #2415

**Comment by tangjinzhou** [comment]
@liulinboyi @thisisandy badge 组件有重复

**Comment by liulinboyi** [comment]
> * [x]   Checkbox #2376
> * [ ]   Badge
@thisisandy 
抱歉，按顺序就着手兼容了，没注意到，Badge这个组件你兼容了吗？谢谢！我刚做了一部分。

**Comment by xiaoxiangmoe** [comment]
完成 Vue 3 支持后，有计划使用 TS 重写吗？（有一说一，目前为止，Vue 的 JSX 的类型支持完爆模板）

**Comment by tangjinzhou** [comment]
> 完成 Vue 3 支持后，有计划使用 TS 重写吗？（有一说一，目前为止，Vue 的 JSX 的类型支持完爆模板）

@xiaoxiangmoe 会使用 ts 重构

**Comment by lifedre** [comment]
希望vue3.0版的table可以加一个可选的rowspan设置来多表头，一些场景目前的设计做不到。

**Comment by thisisandy** [comment]
> > * [x]    Checkbox #2376
> > * [ ]    Badge
> >   @thisisandy
> >   抱歉，按顺序就着手兼容了，没注意到，Badge这个组件你兼容了吗？谢谢！我刚做了一部分。

我调整了下做pagination了

**Comment by tangjinzhou** [comment]
@thisisandy pagination 有进展吗

**Comment by thisisandy** [comment]
[x] pagination #2541 
Known issues on JSX support:
1. Slot is currently not supported
2. The class(name) of the `pager` is not updated properly when the user clicks the prev and next button, reproducible on mid-size screen.
cc @tangjinzhou

**Comment by tomgao365** [comment]
看来月底就可以出版本了。😀

**Comment by muyoulongjingcha** [comment]
哎呀，都完成啦，期待版本发布😀

**Comment by zxbe** [comment]
怎么提交BuG？
[Node built-ins error](https://github.com/vitejs/vite/issues/640#issuecomment-665525421)

**Comment by Amour1688** [comment]
> 怎么提交BuG？
> [Node built-ins error](https://github.com/vitejs/vite/issues/640#issuecomment-665525421)

支持 Vue 3 的版本还没有发，所以你在 vite 上用的那个版本就算 `setTimeout` 解决了应该也是跑不起来了，近期会发布支持 Vue 3 的版本

**Comment by OBQun** [comment]
请问vue3的支持版本是否有确定的日期，或者，我怎么才能在现在的项目中提前使用支持Vue3的版本

**Comment by Yakoot** [comment]
> 请问vue3的支持版本是否有确定的日期，或者，我怎么才能在现在的项目中提前使用支持Vue3的版本

i've heard about start of the august

**Comment by 91651** [comment]
> > 请问vue3的支持版本是否有确定的日期，或者，我怎么才能在现在的项目中提前使用支持Vue3的版本
> 
> i've heard about start of the august

I'm waiting

**Comment by tangjinzhou** [comment]
@OBQun @zxbe @91651 
![image](https://user-images.githubusercontent.com/6937879/89001975-7732dd80-d32e-11ea-808f-a7aaa95233dc.png)

**Comment by OBQun** [comment]
> @OBQun @zxbe @91651
> ![image](https://user-images.githubusercontent.com/6937879/89001975-7732dd80-d32e-11ea-808f-a7aaa95233dc.png)

谢谢！！！

**Comment by OBQun** [comment]
`npm ERR! 请确认您有正确的访问权限并且仓库存在。
npm ERR! fatal: 无法克隆 'git@github.com:tangjinzhou/antdv-demo.git' 到子模组路径 '/home/****/.npm/_cacache/tmp/git-clone-eb2c5f58/antdv-demo'
npm ERR! 克隆 'antdv-demo' 失败。按计划重试
npm ERR! warning: 没有在 /tmp/pacote-git-template-tmp/git-clone-bfb392b8 中找到模版
npm ERR! ERROR: Repository not found.
npm ERR! fatal: 无法读取远程仓库。`

**Comment by xrkffgg** [comment]
@OBQun 由于某些原因，antdv-demo 不对外。

**Comment by OBQun** [comment]
> @OBQun 由于某些原因，antdv-demo 不对外。

 npm i --save git://github.com/vueComponent/ant-design-vue.git#feat-vue3

这条命令无法安装 有替代方案吗？

**Comment by jiabinbin** [comment]
> > @OBQun 由于某些原因，antdv-demo 不对外。
> 
> npm i --save git://github.com/vueComponent/ant-design-vue.git#feat-vue3
> 
> 这条命令无法安装 有替代方案吗？

npm i --save https://github.com/vueComponent/ant-design-vue.git#feat-vue3

**Comment by jiabinbin** [comment]
1. 使用vue-cli创建的项目

> @OBQun @zxbe @91651
> ![image](https://user-images.githubusercontent.com/6937879/89001975-7732dd80-d32e-11ea-808f-a7aaa95233dc.png)

使用了vue-cli创建的项止通过vue-cli-plugin-vue-next变更为v3项目之后
按 提示 install antdv，在vue.config.js中配置alias之，在main.js中使用之后。
yarn serve 报错 如下：
![image](https://user-images.githubusercontent.com/9244703/89026404-3e5d2d80-d35b-11ea-8c9a-b53c3e20b59d.png)

**Comment by 91651** [comment]
> > > @OBQun 由于某些原因，antdv-demo 不对外。
> > 
> > 
> > npm i --save git://github.com/vueComponent/ant-design-vue.git#feat-vue3
> > 这条命令无法安装 有替代方案吗？
> 
> npm i --save https://github.com/vueComponent/ant-design-vue.git#feat-vue3

npm i --save https://github.com/vueComponent/ant-design-vue.git#feat-vue3 这个命令和 npm i --save git://github.com/vueComponent/ant-design-vue.git#feat-vue3 一样错误。

**Comment by LadyChatterleyLover** [comment]
请问怎么在ts项目中引入呢？
![image](https://user-images.githubusercontent.com/35223515/89095292-10c9c000-d3ff-11ea-9cfc-8271f91dc1e2.png)

**Comment by buerxixi** [comment]
> @OBQun 由于某些原因，antdv-demo 不对外。

有没有具体的示例 展示如何使用antv-vue3

**Comment by OBQun** [comment]
> > @OBQun 由于某些原因，antdv-demo 不对外。
> 
> 有没有具体的示例 展示如何使用antv-vue3

我目前的做法是clone本项目 在examples文件夹下写自己的项目

**Comment by liihong** [comment]
> 1. 使用vue-cli创建的项目
> 
> > @OBQun @zxbe @91651
> > ![image](https://user-images.githubusercontent.com/6937879/89001975-7732dd80-d32e-11ea-808f-a7aaa95233dc.png)
> 
> 使用了vue-cli创建的项止通过vue-cli-plugin-vue-next变更为v3项目之后
> 按 提示 install antdv，在vue.config.js中配置alias之，在main.js中使用之后。
> yarn serve 报错 如下：
> ![image](https://user-images.githubusercontent.com/9244703/89026404-3e5d2d80-d35b-11ea-8c9a-b53c3e20b59d.png)

问题解决了吗？

**Comment by tangjinzhou** [comment]
ant-design-vue@2.0.0-beta.2

**Comment by CodeInn1024** [comment]
> 蚂蚁设计 - vue@2.0.0 - beta.2

vite 引入less报错
![image](https://user-images.githubusercontent.com/22464456/90309968-c2004800-df1f-11ea-9b14-90d955387a40.png)

**Comment by LadyChatterleyLover** [comment]
安装了ant-design-vue@2.0.0-beta.2 启动还是报错

**Comment by sendya** [comment]
> 安装了ant-design-vue@2.0.0-beta.2 启动还是报错

错呢？

**Comment by ifui** [comment]
When I use it, some errors:
```js
src/main.ts:9:8
TS2345: Argument of type 'typeof import("/Users/ifui/workspace/Vue/dev/antd-admin-vue/node_modules/ant-design-vue/types/ant-design-vue")' is not assignable to parameter of type 'Plugin_2'.
  Type 'typeof import("/Users/ifui/workspace/Vue/dev/antd-admin-vue/node_modules/ant-design-vue/types/ant-design-vue")' is not assignable to type '{ install: PluginInstallFunction; }'.
    Types of property 'install' are incompatible.
      Type '(vue: typeof import("/Users/ifui/workspace/Vue/dev/antd-admin-vue/node_modules/vue/dist/vue")) => void' is not assignable to type 'PluginInstallFunction'.
        Types of parameters 'vue' and 'app' are incompatible.
          Type 'App<any>' is missing the following properties from type 'typeof import("/Users/ifui/workspace/Vue/dev/antd-admin-vue/node_modules/vue/dist/vue")': compile, useCssModule, useCssVars, createApp, and 104 more.
```
This is my `main.ts`:
```js
import { createApp } from 'vue'
import antd from 'ant-design-vue'
import 'ant-design-vue/components/style.js'
import App from './App.vue'
import router from './router'
import store from './store'

createApp(App)
  .use(antd)   // here
  .use(router)
  .use(store)
  .mount('#app')
```
Have to defined any type for `antd`, like it
```js
createApp(App)
  .use(antd as any)
  .use(router)
  .use(store)
  .mount('#app')
```
So, if you are interesting to fix it    👍

**Comment by van-chin** [comment]
`
<a-icon type="left" />
`
没有显示图标，而提示了
`
Warning: [antdv: Icon] Empty Icon
`
是使用方式有变更么？

**Comment by LadyChatterleyLover** [comment]
> > 安装了ant-design-vue@2.0.0-beta.2 启动还是报错
> 
> 错呢？

![image](https://user-images.githubusercontent.com/35223515/90327003-f0366400-dfc1-11ea-833a-2070c054f5fd.png)
这个错

**Comment by Amour1688** [comment]
> `<a-icon type="left" />`
> 没有显示图标，而提示了
> `Warning: [antdv: Icon] Empty Icon`
> 是使用方式有变更么？
图标改为按需引入了，文档站点还没更新

```js
import { UserOutlined } from '@ant-design/icons-vue';

<UserOutlined />
```

**Comment by CodeInn1024** [comment]
vite使用报_extends is not a function
![image](https://user-images.githubusercontent.com/22464456/90362891-322fda80-e094-11ea-92f4-f3adcd2433dd.png)

**Comment by ifui** [comment]
> > `<a-icon type="left" />`
> > 没有显示图标，而提示了
> > `Warning: [antdv: Icon] Empty Icon`
> > 是使用方式有变更么？
> > 图标改为按需引入了，文档站点还没更新
> 
> ```js
> import { UserOutlined } from '@ant-design/icons-vue';
> 
> <UserOutlined />
> ```

https://github.com/ant-design/ant-design-icons/tree/master/packages/icons-vue

**Comment by Yakoot** [comment]
what about customRender table column? I have a column
```
            {
                title: 'Created',
                dataIndex: 'createdAt',
                width: 144,
                sorter: true,
                scopedSlots: {customRender: 'created'},
            },
```
and I'm trying to render it using
```
      <template #created="created" class="mailing-created">{{ formatDate(created) }}</template>
```
but it's not working

**Comment by Yakoot** [comment]
how can I access $message in my setup() function?

**Comment by Amour1688** [comment]
> how can I access $message in my setup() function?

```js
import { message } from 'ant-design-vue';

const App = {
  setup() {
    message.info('xxx')
    return () => <div>antd</div>
 }
}
```

**Comment by lubaijie** [comment]
在ts下报错

**Comment by uinio** [comment]
> 在ts下报错

ts 没问题 tsx 无法使用

**Comment by abelit** [comment]
Wish to support vue 3.0(vue-next) and typescript.

**Comment by Amour1688** [comment]
> Wish to support vue 3.0(vue-next) and typescript.

will be fixed in this week.

**Comment by HQDragon** [comment]
大大们好厉害，终于找到一个vue3可用的组件库了，pro也赶紧整起来，到时候release了喝咖啡

**Comment by ZhangNing-debug** [comment]
icon图标 我看改为按需引入了 那么我想使用iconfont图标 该怎么写?

**Comment by Siffre** [comment]
@Amour1688    具体什么日期呢？ 准备着手 electron + ts + vue3 + antd

**Comment by Amour1688** [comment]
> icon图标 我看改为按需引入了 那么我想使用iconfont图标 该怎么写?

https://2x.antdv.com/components/icon-cn/#components-icon-demo-use-iconfont.cn

**Comment by CarterLi** [comment]
![image](https://user-images.githubusercontent.com/6134068/90763021-8f3bc280-e318-11ea-82cf-f604511cf960.png)

建议不要扩展vue的prototype，这样无法摇树优化，还可能与其他库产生名字冲突

**Comment by sendya** [comment]
> ![image](https://user-images.githubusercontent.com/6134068/90763021-8f3bc280-e318-11ea-82cf-f604511cf960.png)
> 
> 建议不要扩展vue的prototype，这样无法摇树优化，还可能与其他库产生名字冲突

2.x 版本没有挂载 `prototype`，直接 import 之后可直接使用

**Comment by CarterLi** [comment]
> > ![image](https://user-images.githubusercontent.com/6134068/90763021-8f3bc280-e318-11ea-82cf-f604511cf960.png)
> > 建议不要扩展vue的prototype，这样无法摇树优化，还可能与其他库产生名字冲突
> 
> 2.x 版本没有挂载 `prototype`，直接 import 之后可直接使用

我用的是npmjs上最新的ant-design-vue@2.0.0-beta.2。后续版本改了就好

**Comment by buqiyuan** [comment]
> vite中使用2.0.0-beta.2版本出现:
> 
> ```
> ant-design-vue.js:1141 Uncaught TypeError: _extends is not a function
>     at omit (ant-design-vue.js:1141)
>     at wrapWithConnect (ant-design-vue.js:11264)
>     at ant-design-vue.js:17612
> ```
> 
> main.js:
> 
> ```
> import {createApp} from 'vue'
> import antd from 'ant-design-vue'
> import App from './App.vue'
> import './index.css'
> 
> createApp(App)
>   .use(antd)
>   .mount('#app')
> ```
> 
> 谁解决了可以说一下吗？

我用vite也是遇到这个问题，暂时先用vue-cli + vue3.0过渡一下吧

**Comment by nshusr** [comment]
> vite中使用2.0.0-beta.2版本出现:
> 
> ```
> ant-design-vue.js:1141 Uncaught TypeError: _extends is not a function
>     at omit (ant-design-vue.js:1141)
>     at wrapWithConnect (ant-design-vue.js:11264)
>     at ant-design-vue.js:17612
> ```
> 
> main.js:
> 
> ```
> import {createApp} from 'vue'
> import antd from 'ant-design-vue'
> import App from './App.vue'
> import './index.css'
> 
> createApp(App)
>   .use(antd)
>   .mount('#app')
> ```
> 
> 谁解决了可以说一下吗？

相同错误， @tangjinzhou 请教有没有解决方法

**Comment by sendya** [comment]
@buqiyuan @nshusr  vite 还是实验性库，请先使用 webpack

**Comment by CarterLi** [comment]
vue3里v-model默认绑定属性改成了modelValue，有计划把所有的value都替换成米得了value吗？鉴于antv现在已经是beta阶段，如果要的话是最后机会了

**Comment by zkwolf** [comment]
> vue3里v-model默认绑定属性改成了modelValue，有计划把所有的value都替换成modelValue吗？鉴于antv2现在已经是beta阶段，如果有计划要改的话是最后机会了

https://2x.antdv.com/docs/vue/migration-v2-cn/ 详见文档吧，改成了v-model:xxx这种形式

**Comment by abelit** [comment]
When start app by "yarn run serve" , error displaying like follow.     (  environment: "ant-design-vue": "^2.0.0-beta.3" , vue-next,typescript)
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/drawer/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/drawer/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/tree-select/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/tree-select/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/tree-select/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/list/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/list/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/list/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/layout/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/layout/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/layout/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/anchor/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/anchor/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/anchor/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/upload/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/upload/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/upload/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/tree/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/tree/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/tree/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/transfer/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/transfer/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/transfer/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

 error  in ./node_modules/ant-design-vue/components/input-number/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):


// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      Error in /home/abelit/Downloads/newapp/node_modules/ant-design-vue/components/style/color/bezierEasing.less (line 110, column 0)

 @ ./node_modules/ant-design-vue/components/input-number/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/components/input-number/style/index.js
 @ ./node_modules/ant-design-vue/components/style.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://10.46.100.220:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts

**Comment by sendya** [comment]
@abelit 关键字 less  lessOptions javascriptEnabled

**Comment by tangwenjie-123** [comment]
import { createApp } from 'vue'
import 'ant-design-vue/dist/antd.css';

const app = createApp();

import { 
    Card,
} from 'ant-design-vue'

app.use(Card);

已经按上述按需导入了，但是还是报错：


runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Failed to resolve component: a-card 
  at <Login onVnodeMounted=fn<onVnodeMounted> onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>

**Comment by van-chin** [comment]
感觉 在配合vite使用报错 Uncaught TypeError: _extends is not a function 的思路
`
ant-design-vue.js:1141 Uncaught TypeError: _extends is not a function
    at omit (ant-design-vue.js:1141)
    at wrapWithConnect (ant-design-vue.js:11282)
    at ant-design-vue.js:17630

`
`
function omit(obj, fields) {
  var shallowCopy = _extends({}, obj);
  for (var i = 0; i < fields.length; i++) {
    var key = fields[i];
    delete shallowCopy[key];
  }
  return shallowCopy;
}

`
是不是和@babel/runtime 有关系 乱猜的哈

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/91526337-fcadab80-e935-11ea-99d3-1f8dfae1ecbe.png)
![image](https://user-images.githubusercontent.com/39730999/91526717-d76d6d00-e936-11ea-8b6d-cb561b412241.png)


Table :customRow添加contextmenu事件没有触发，是我食用方法不对吗？
`version: vue: 3.0.0-rc.9   ant-design-vue": "^2.0.0-beta.3`

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/91526885-38954080-e937-11ea-88b0-59c1588829ae.png)

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/91527105-aa6d8a00-e937-11ea-8c85-e821454091da.png)

![image](https://user-images.githubusercontent.com/39730999/91527149-c2450e00-e937-11ea-8e12-6e0378009312.png)

**Comment by CarterLi** [comment]
a-modal 中 `destroyOnClose` 属性会导致 `afterClose` 回调调用两遍，感觉像是bug，是这样设计的吗？

**Comment by StephenSeraph** [comment]
有没有哪位壮士研究出来怎么在`vite`里面使用啊?
其他的依赖库都已经在vite里面跑起来了，就差这个，真是要了老命了 >. <

**Comment by wxs77577** [comment]
实测 `vite` 通过， 大写的赞:
```js
import antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

createApp(App).use(antd).mount('#app')
```

**Comment by StephenSeraph** [comment]
vite下面，组件按需引入时，CSS样式似乎没生效，我目前暂时改成了全部导入的。

**Comment by myh6666** [comment]
![image](https://user-images.githubusercontent.com/33438314/91925403-7fa07e80-ed07-11ea-9347-43ff7941e895.png)
为什么不能使用number[]作为<a-pagination />的pageSizeOptions呢？

**Comment by CarterLi** [comment]
在vite下面使用浏览器报错：`Uncaught (in promise) SyntaxError: The requested module '/@modules/lodash/isPlainObject.js' does not provide an export named 'default'`

![image](https://user-images.githubusercontent.com/6134068/91944271-63fd9e00-ed30-11ea-858f-a9582031c4b1.png)

建议把所有使用 lodash 的地方替换为 lodash-es

**Comment by Yakoot** [comment]
how to use confirmation modal dialog? 
this.$confirm doesn't work

**Comment by tangjinzhou** [comment]
If you have questions or suggestions, you can use the newly opened issue to discuss.
