### ISSUE TITLE
当表格列为tempate时，设置单独某列sorter=true，会影响表格正常效果和报错

### ISSUE THREAD

**Issue by cuteCloud** [vueComponent/ant-design-vue#1914]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
谷歌最新，vue2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-i66dz)

### Steps to reproduce
<a-table :dataSource="data" :scroll="{x:true}">
<a-table-column title="Age" :sorter="true" data-index="age" key="age"/>
<a-table-column title="Address" data-index="address" key="address"/>
<a-table-column title="Tags" data-index="tags" key="tags">
<template slot-scope="tags">
<span>
<a-tag v-for="tag in tags" color="blue" :key="tag">{{tag}}</a-tag>
</span>
</template>
</a-table-column>
</a-table>
当这种模式渲染表格，再某列设置了排序，鼠标移动到表格任何地方 ，都会激活整张表的选中，并且这个如果设置table的scroll={x:ture}的话 点击排序还会保Cannot read property 'scrollTop' of undefined的错 错误复现请看https://codesandbox.io/s/vue-antd-template-i66dz

### What is expected?
与antd design vue1.4.0x版本一致的表格体验  单独设置a-table-column的排序属性不会影响表格正常点击效果和不保错。1.5.0x以上目前都有这个bug

### What is actually happening?
sorter属性照成了一系列的连锁错误

**Comment by tangjinzhou** [comment]
update to 1.5.0-rc.6
