### ISSUE TITLE
The input-search  custom button can not work as before

### ISSUE THREAD

**Issue by qixiaodong** [vueComponent/ant-design-vue#1916]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.5

### Environment
chrome 76.0.3809.132

### Reproduction link
[https://www.antdv.com/components/input/](https://www.antdv.com/components/input/)

### Steps to reproduce
`<a-input-search placeholder="input search text" @search="onSearch" size="large">
<a-button slot="enterButton">Custom</a-button>
</a-input-search>`

### What is expected?
display the solt 's button in the input-search。

### What is actually happening?
no button display。

**Comment by tangjinzhou** [comment]
update to 1.5.0-rc.6
