### ISSUE TITLE
Property ":colon="false"" for Form and FormModel component is not working on version ^1.5.0

### ISSUE THREAD

**Issue by fbtwitter** [vueComponent/ant-design-vue#1922]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
windows 10, vue version 1.50-rc.4 and 1.5.0-rc.5 (above 1.5.0)

### Reproduction link
[https://www.antdv.com/components/form-model/](https://www.antdv.com/components/form-model/)

### Steps to reproduce
for the example purpose, i use the demo on form model like this :

```
<template>
<a-form-model
ref="ruleForm"
:model="form"
:rules="rules"
:label-col="labelCol"
:wrapper-col="wrapperCol"
:colon="false"
>

</a-form-model>
</template>
```

### What is expected?
What I expected is: the colon right beside the text label disappear.

### What is actually happening?
the colon still visible there, and I have to force it using CSS

**Comment by tangjinzhou** [comment]
I have no problem here. Can you provide reproduce demo

**Comment by fbtwitter** [comment]
@tangjinzhou thank you for your honest reply on my problem here,

I was tried figuring out again by using your playground. 
My problem here, my CSS file injected directly to the main folder. so it wasn't get updated to the latest ant design vue version.

your playground site helps me so well since I'm new here on framework. 
Thanks
