### ISSUE TITLE
表格复选框选择中全选与禁用状态存在一点冲突

### ISSUE THREAD

**Issue by dengrencai** [vueComponent/ant-design-vue#1923]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
谷歌

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
在表格的一页中既有可选元素又有禁用元素的时候，点击全选，禁用元素被选中而可选元素缺未被选中，最后结果的数量是可选元素的总数。可选元素与禁用元素交叉显示时会出现上述bug

### What is expected?
全选时输出的结果应该是全部的可选元素而不是既有可选元素又有禁选元素

### What is actually happening?
既有可选元素又有禁选元素

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/77414934-b4291980-6dfc-11ea-846c-7efd8c4fa0ef.png)
没能复现你的问题   如确认有问题，请基于这个[模板](https://codesandbox.io/s/2wpk21kzvr)提供可复现的示例

**Comment by wuchao999** [comment]
> ![图片](https://user-images.githubusercontent.com/6937879/77414934-b4291980-6dfc-11ea-846c-7efd8c4fa0ef.png)
> 没能复现你的问题如确认有问题，请根据这个[模板](https://codesandbox.io/s/2wpk21kzvr)提供可复现的示例

您好，项目中也是有这样的问题，并且在您提供的模板里也是出现了类似的问题。
假设dataSource里十条数据，前几条数据的disabled给出的判断是true，这时allSelect也被置为disabled了。如果将该数组反转，也就是不禁用的数据在前，禁用的在后，这时貌似是正确的。

`<template>
  <div style="margin: 24px">
    <p style="margin-bottom: 24px">
      Current ant-design-vue version: {{ version }}
      <br>You can change ant-design-vue version on the left panel (Dependencies
      section).
    </p>
    <a-date-picker :defaultValue="moment()"/>
    <a-table :rowSelection="rowSelection" :columns="columns" :dataSource="data"></a-table>
  </div>
</template>

<script>
import moment from "moment";
import { version } from "ant-design-vue";
export default {
  name: "App",
  data() {
    return {
      moment,
      version,
      columns: [
        {
          title: "角色名称",
          dataIndex: "roleName"
        }
      ],
      data: [
        {
          roleName: "超级管理员",
          defaultRole: 1
        },
        {
          roleName: "管理员",
          defaultRole: 1
        },
        {
          roleName: "普通用户",
          defaultRole: 0
        }
      ]
    };
  },
  computed: {
    rowSelection() {
      return {
        getCheckboxProps: record => ({
          props: {
            disabled: record.defaultRole === 1
          }
        })
      };
    }
  }
};
</script>

<style></style>
`

**Comment by tangjinzhou** [comment]
首先你如果希望尽快解决问题，请严格按照issue模板给出示例链接
@wuchao999 根据你的描述，目测是没有设置正确的key   这个issue我就关了
