### ISSUE TITLE
a-directory-tree组件无法进行选择操作

### ISSUE THREAD

**Issue by NO-MAP** [vueComponent/ant-design-vue#1927]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
Google Chrome80.0.3987.149  VUE2  @vue/cli 4.1.2

### Reproduction link
[https://www.antdv.com/components/tree-cn/](https://www.antdv.com/components/tree-cn/)

### Steps to reproduce
```
<template>
<a-directory-tree multiple defaultExpandAll @select="onSelect" @expand="onExpand">
<a-tree-node title="parent 0" key="0-0">
<a-tree-node title="leaf 0-0" key="0-0-0" isLeaf />
<a-tree-node title="leaf 0-1" key="0-0-1" isLeaf />
</a-tree-node>
<a-tree-node title="parent 1" key="0-1">
<a-tree-node title="leaf 1-0" key="0-1-0" isLeaf />
<a-tree-node title="leaf 1-1" key="0-1-1" isLeaf />
</a-tree-node>
</a-directory-tree>
</template>
<script>
export default {
methods: {
onSelect(keys, event) {
console.log('Trigger Select', keys, event);
},
onExpand() {
console.log('Trigger Expand');
},
},
};
</script>
```

### What is expected?
正常使用ctrl/shift进行选择操作

### What is actually happening?
控制台报错： Cannot read property 'ctrlKey' of undefined.
断点显示nativeEvent为undefined

**Comment by tangjinzhou** [comment]
update to 1.5.0-rc.6
