### ISSUE TITLE
Table组件设置纵向滚动后，点击页码控制台报错

### ISSUE THREAD

**Issue by zhensherlock** [vueComponent/ant-design-vue#1929]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
谷歌最新，vue2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-36rw4)

### Steps to reproduce
表格设置:scroll="{ y: 240 }"，点击页码，控制台报错
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'scrollTop' of undefined"

### What is expected?
点击页码不报错

### What is actually happening?
点击页码报错

**Comment by tangjinzhou** [comment]
update to 1.5.0-rc.6
