### ISSUE TITLE
Drawer breaks SSR content

### ISSUE THREAD

**Issue by mapsgeek** [vueComponent/ant-design-vue#1930]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
windows, chrome, 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-sinoussi-3xnxg)

### Steps to reproduce
using the Drawer component in nuxtjs SSR mode, look at view-source

### What is expected?
Content inside the Drawer to be server-side rendered

### What is actually happening?
all components inside drawer gets omitted from the server side generation

---
i'm not sure if that's the normal behaviour for a drawer or a bug or there's a work around this ?

**Comment by tangjinzhou** [comment]
please use  `Vue.use(Drawer);`

**Comment by mapsgeek** [comment]
@tangjinzhou this doesn't resolve the issue, i actually was using Vue.use() but switched to the component registration method as a try both lead to the same result
