### ISSUE TITLE
表格组件在换页的时候报错

### ISSUE THREAD

**Issue by kiteoath** [vueComponent/ant-design-vue#1931]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.4

### Environment
ant-design-vue@1.5.0-rc.5 vue@2.6.11

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header](https://www.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header)

### Steps to reproduce
数据超过1页的表格，在点击其他页码的时候控制台会报错

### What is expected?
换页不报错

### What is actually happening?
点击换页就会报错

![控制台报错信息](https://user-images.githubusercontent.com/16759385/77327470-40343600-6d56-11ea-805a-801eeaf3a357.png)

**Comment by tangjinzhou** [comment]
duplicate #1929
