### ISSUE TITLE
FormModel和modal对话框一起用的时候不能编辑值 (model初始化时为空对象，接收后台api时再赋属性，因为属性比较多)

### ISSUE THREAD

**Issue by 2261656355** [vueComponent/ant-design-vue#1935]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.6

### Environment
win10  chrome80  vue2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-fht2y)

### Steps to reproduce
您好，因为model的属性比较多，所以想接收api时给其赋值，打开编辑页的时候第一次不显示值，关闭后第二次才显示值，并且无法修改，目前找到的解决方法如下
1：vmData初始化时属性都加上。
2：使用vue.set给vmData赋值。
想请教下这种场景怎么解决啊，我用form和modal时用setFieldsValue({ ...res})可以正常操作，万分感谢。

### What is expected?
打开编辑页时，数据正常展示和编辑

### What is actually happening?
第一次打开时，数据不显示，第二次打开时，数据展示，但无法修改。

**Comment by tangjinzhou** [comment]
``` this.vmData = { ...this.vmData, goodsName: 1 } ```
https://codesandbox.io/s/vue-antd-template-5jurb

**Comment by tangjinzhou** [comment]
这是Vue 机制  和 组件库没有关系

**Comment by 2261656355** [comment]
谢谢啊，我用您给的扩展符对象解决了，十分感谢，开源不易。
