### ISSUE TITLE
组件库依赖的ismobilejs存在兼容性问题

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#1936]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
操作系统:mac  谷歌78  vue:2.6.10

### Reproduction link
[https://www.antdv.com/docs/vue/introduce-cn/](https://www.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
在项目中引用ant design vue 打包后在ie10等低版本浏览器不行,目前自己解决 配置alias : ismobilejs: 'node_modules/ismobilejs/dist/isMobile.min.js'  可以解决,

### What is expected?
在低版本浏览器不行

### What is actually happening?
在低版本浏览器可以运行

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/77386441-c0de4b00-6dc5-11ea-9d7f-4396a2f7fd63.png)

原因是ismobilejs 这个库package.json 的main指向了未经转码的入口

**Comment by tangjinzhou** [comment]
这个通过配置 babel  polifil 等可以解决的吧

**Comment by anncwb** [comment]
有配置 polyfill ,没引入antc的话可以兼容到ie9, 但是引入antv的话就不行了,需要用babel 单独includes: ismobilejs或者设置别名才行,可能是我的方式不对,但是试了几次都是这样

**Comment by mkanako** [comment]
ismobilejs的package.json里面

> "main": "cjs/index.js",
  "module": "esm/index.js"

所以require('ismobilejs')或是import ismobilejs from 'ismobilejs'
都会引入这两个文件之一，而这两个文件都包含const等关键字，并未经过babel转义，babel又默认忽略node_modules里面的文件，最终导致了这个问题

**Comment by mkanako** [comment]
@anncwb  1.4.12确实存在这个问题，但是1.5已经解决了 ，看这个文件components/vc-menu/util.js

但是老哥 @tangjinzhou 你这是把ismobilejs这个库的代码复制进来，以后要是这个库更新了，你不得手动复制更新，不麻烦吗😂

**Comment by tangjinzhou** [comment]
这个文件的更新频率很低

**Comment by bhabgs** [comment]
我也遇到了关于  ismobilejs 这个包的问题，我的打包环境为vite@2.0.1 + vue3.0
![image](https://user-images.githubusercontent.com/19221378/110585142-5a576600-81ab-11eb-8396-51dfd0ae6cfb.png)
