### ISSUE TITLE
table组件的expandIcon无效

### ISSUE THREAD

**Issue by HuangYongXuan** [vueComponent/ant-design-vue#1937]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.6

### Environment
系统：mac；浏览器：chrome 80.0.3987.149；vue:2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-8kyy8)

### Steps to reproduce
查看改展开icon是否变化

### What is expected?
修改展开菜单的icon样式

### What is actually happening?
没有变化

**Comment by tangjinzhou** [comment]
update to 1.5.0-rc.7

**Comment by BetwayM** [comment]
用Function(props):VNode方法；亲测可用
<script> export default { methods:{ customExpandIcon:function(props) { if (props.expandable) { //根节点 if (props.expanded) { //是否已经展开 //已经展开 return ( { props.onExpand(props.record, e); }} icon="caret-down" > ); } else { //未展开 return ( { props.onExpand(props.record, e); }} icon="caret-right" > ); } } else { //叶子节点，不显示按钮 return ; //占位 } } } }
