### ISSUE TITLE
Select active item bug

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#194]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.0

### Environment
Win7/vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/84wkyyznrj)

### Steps to reproduce
Click first/second/third/fourth item, check if is active.

### What is expected?
all situations go well.

### What is actually happening?
first/second/third is not right.

**Comment by tangjinzhou** [comment]
not use `''` and `null`
