### ISSUE TITLE
Carousel 走马灯 移动端不能往下滑动滚动页面

### ISSUE THREAD

**Issue by lixsh8** [vueComponent/ant-design-vue#1940]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.10

### Environment
ios 13

### Reproduction link
[https://www.antdv.com/components/carousel-cn/](https://www.antdv.com/components/carousel-cn/)

### Steps to reproduce
在移动端打开Carousel 走马灯，在组件上往下滑动

### What is expected?
能往下滚动页面

### What is actually happening?
Carousel 走马灯 这个组件在移动端水平滚动的时候。和页面的上下滚动事件冲突。在这个组件上触摸往下滑动不了页面。看不了下面的内容

**Comment by lixsh8** [comment]
有人看下吗？

**Comment by genaller** [comment]
> 有人看下吗？

你解决了吗

**Comment by xrkffgg** [comment]
https://antdv.com/docs/vue/faq-cn/#ant-design-vue-%E5%9C%A8%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%BD%93%E9%AA%8C%E4%B8%8D%E4%BD%B3%E3%80%82
