### ISSUE TITLE
could you use day.js instead of moment.js

### ISSUE THREAD

**Issue by blesstosam** [vueComponent/ant-design-vue#1945]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Dayjs has smaller size and use totally the same api of moment. I think it's cab be a improvement!
BTW, i can do this job if i have enough time!!!

### What does the proposed API look like?
none!

**Comment by tangjinzhou** [comment]
2.x 中会添加相关配置

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/antd-dayjs-webpack-plugin

**Comment by duckness** [comment]
For additional reference, Moment has been in [maintenance mode](https://momentjs.com/docs/#/-project-status/) since [3 months+ ago](https://github.com/moment/moment/pull/5719).

From my understanding, it seems that 2.x will support `dayjs` as default?

**Comment by zkwolf** [comment]
> For additional reference, Moment has been in [maintenance mode](https://momentjs.com/docs/#/-project-status/) since [3 months+ ago](https://github.com/moment/moment/pull/5719).
> 
> From my understanding, it seems that 2.x will support `dayjs` as default?

Unfortunately, 2.x doesn't support `dayjs` now.But you can use the plugin that mentioned above to replace moment with dayjs.

**Comment by ekoeryanto** [comment]
webpack, but what about rollup, vite 😄

**Comment by promiseMIMI** [comment]
> webpack, but what about rollup, vite 😄
> ends with fork when i need it, sorry

Solve it？
