### ISSUE TITLE
Drawer 渲染在当前 dom 里。自定义容器，查看 getContainer。设置getContainer后不生效，案例中也没有生效

### ISSUE THREAD

**Issue by dukechenyk** [vueComponent/ant-design-vue#1954]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.6

### Environment
win10，chrome 80.0.3987.116，vue 2.6.10

### Reproduction link
[https://www.antdv.com/components/drawer-cn/](https://www.antdv.com/components/drawer-cn/)

### Steps to reproduce
渲染在当前 dom 里。自定义容器，查看 getContainer。设置getContainer后不生效，案例中也没有生效

### What is expected?
渲染在当前 dom 里。自定义容器，查看 getContainer。设置getContainer后生效，可在案例中看到生效后的效果

### What is actually happening?
渲染在当前 dom 里。自定义容器，查看 getContainer。设置getContainer后不生效，案例中也没有生效

**Comment by sendya** [comment]
:getContainer="el => el.parentNode"

**Comment by dukechenyk** [comment]
> :getContainer="el => el.parentNode"

parentNode is undefined

**Comment by sendya** [comment]
那设置 false 即可

**Comment by dukechenyk** [comment]
> 那设置 false 即可

都有过尝试，但是都不做生效 设置了:getContainer="#***" 后还要修改css position: absolute; 左右浮动才能生效，抽屉的打开和关闭都会出现问题，会一直存在 *** dom下

**Comment by dukechenyk** [comment]
> 那设置 false 即可

https://www.antdv.com/components/drawer-cn/  这个页面上就是设置了false 我这边看到展开还是在body下的效果

**Comment by sendya** [comment]
https://codesandbox.io/s/elated-goldstine-zbg98

没问题，如有问题 请提供复现，不要贴个组件的地址

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/77605885-febbaa80-6f50-11ea-9eb2-d1822e1f27a2.png)
很明显节点是对的

**Comment by dukechenyk** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/77605885-febbaa80-6f50-11ea-9eb2-d1822e1f27a2.png)
> 很明显节点是对的

![image](https://user-images.githubusercontent.com/33365709/77606154-bf418e00-6f51-11ea-8fb9-b443a7a3f0a5.png)

我知道这个节点展示位置是正确的，但是官网上点了之后也会出现问题

**Comment by dukechenyk** [comment]
![image](https://user-images.githubusercontent.com/33365709/77606303-147d9f80-6f52-11ea-81b9-c670572c817d.png)

我知道这个节点的位置是正确的，但是出来的效果是和例子是不符合的，官网上组件的展现就是有问题啊

**Comment by baojie223** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/77605885-febbaa80-6f50-11ea-9eb2-d1822e1f27a2.png)
> 很明显节点是对的

你好，我目前也有这个问题，复现的话，你们的官网drawer示例“渲染在当前 DOM”本身就有问题的，你可以打开看一下。

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/77608253-9ae8b000-6f57-11ea-8feb-0d14e6ae2833.png)

不是在 dom 下？

**Comment by sendya** [comment]
你是说没渲染在父级 div 里是吗？

**Comment by baojie223** [comment]
> 你是说没渲染在父级 div 里是吗？

你看一下antdesign react版本官网的抽屉组件里的“渲染在当前dom”，和这个vue版本的，效果是不一样的。

**Comment by sendya** [comment]
知道了

**Comment by unhappy224** [comment]
看了下，好像是少了个position: 'absolute'

**Comment by sendya** [comment]
vue 的规范是 style 直接作用在元素上，不能往下传递，所以提供了别名的 api `wrapStyle`  请参考 demo 使用。

https://codesandbox.io/s/elated-goldstine-zbg98

后续会更新文档 demo

**Comment by StormSpirit22** [comment]
<a-drawer
        title="Basic Drawer"
        placement="left"
        :closable="false"
        @close="onClose"
        :visible="visible"
        :getContainer="false"
        :wrap-style="{ position: 'absolute' }"
        :mask="false"
      >
这样设置左边会留下一个
![image](https://user-images.githubusercontent.com/6985964/97857953-69c82d80-1d39-11eb-880e-7b584d7c9ef5.png)
请问这是bug吗？还有getContainer属性能否指定vue的ref？如果可以该怎么指定呢？谢谢

**Comment by StormSpirit22** [comment]
@sendya
