### ISSUE TITLE
Table组件添加可选择rowSelection后，数据较多时每次选中都会卡顿，有什么解决方案

### ISSUE THREAD

**Issue by chenhongtu** [vueComponent/ant-design-vue#1959]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
chrome 80 vue 2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-fog-iq1fw)

### Steps to reproduce
[codesandbox](https://codesandbox.io/s/quiet-fog-iq1fw)

### What is actually happening?

---
我需要一页显示几百条数据
Table组件添加可选择rowSelection后，数据较多时每次选中都会卡顿，是不是每次选择都会重新渲染整个表格？有什么解决方案？

**Comment by Joseph-Qiu** [comment]
同上！

**Comment by wry5560** [comment]
同上！

**Comment by Xiongwenger** [comment]
同上，而且会导致同一页的from表单卡顿。。

**Comment by acecoder1997** [comment]
是不是还会让 v-model的input组件变慢，出现防抖效果。。。。。，一去掉rowSelection就恢复速度，所输即所得。
