### ISSUE TITLE
back-top component cannot work

### ISSUE THREAD

**Issue by Rain120** [vueComponent/ant-design-vue#196]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.2

### Environment
antd 1.1.2 node 10.10.0 vue2.5.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
I had added the component at the App.vue, and I set the overflow property to auto，and the component cannot work. When I removed the property, it's work. And then, I review the code about the component of back-top, I found there was some style about overflow hidden, Is this property conflicting? And how to solve the problem?

### What is expected?
use the overflow property and the back-top component is work too

### What is actually happening?
the back-top component cannot work

![image](https://user-images.githubusercontent.com/20939839/45730754-316f3f00-bc06-11e8-9dd4-69f73a54613c.png)

![image](https://user-images.githubusercontent.com/20939839/45732321-5e275480-bc0e-11e8-8c35-b4870b9120d6.png)

**Comment by Rain120** [comment]
I got the way how to solve the problem, I found my code cannot had the sroll at body and the reset.css influence the component, Is that the result about the problem?

**Comment by tangjinzhou** [comment]
you can set target to change monitor DOM scrolling changes.
Target default is window，if you add `#app {overfolw:auto}`，window scrolling position is not change.
Maybe you can change target to `:target="()=>document.getElementById('app')"`.
https://vuecomponent.github.io/ant-design-vue/components/back-top/#API

**Comment by qifengwangye** [comment]
@tangjinzhou 采用了你的解决方法依然没有解决，我和提问者的情况是一样的，版本是1.3.2，无法提供在线代码，公司网络不允许
