### ISSUE TITLE
关于ant for vue cdn加载问题

### ISSUE THREAD

**Issue by bhabgs** [vueComponent/ant-design-vue#1966]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.12

### Environment
mac: 10.15.2、 chrome: 80.0.3987.132、Vue:2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/26](https://github.com/vueComponent/ant-design-vue/issues/26)

### Steps to reproduce
> 当我想通过cdn的方式加载 ant 的时候，我使用了 `<script src="https://unpkg.com/ant-design-vue@1.4.12/dist/antd.min.js"></script>` 在`public>index.html`.
### 在`vue.confif.js` 下配置如下
``` javascript
module.exports = {
// ...
configureWebpack: {
// ...
externals: {
vue: 'Vue',
'ant-design-vue': 'Ant',
'vue-router': 'VueRouter',
},
}
}
```
### 在`main.js `引入`ant-design-vue`
``` javascript
import Vue from 'vue';
import Ant from 'ant-design-vue';
console.log(Ant) // undefined
```

### What is expected?
希望得到一个cdn引入的较好方案

### What is actually happening?
cdn引入失败

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/commit/ae60814e83be694e3b99104e1dd90543a30c336b

**Comment by tangjinzhou** [comment]
vue 也要通过cdn方式加载，然后组件会自动注册

**Comment by bhabgs** [comment]
感谢
