### ISSUE TITLE
a-input-search add clear event

### ISSUE THREAD

**Issue by whu-luojian** [vueComponent/ant-design-vue#1967]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
as use a-input-search component, we need to trigger search event when user press enter or click search icon and clear icon.（使用input-search组件时，点击清除按钮不会触发search事件，导致需要按一下enter键才能触发搜索）

### What does the proposed API look like?
click clear icon will emit search event or clear event. （a-input-search组件点击清除按钮触发search事件或者input相关组件点击清除按钮触发clear事件）

**Comment by tangjinzhou** [comment]
change 事件已经可以满足这个需求，判断cahnge事件的回调参数 event 这个对象，可以区分是 回车、还是清除按钮

**Comment by sunyum** [comment]
> change 事件已经可以满足这个需求，判断cahnge事件的回调参数 event 这个对象，可以区分是 回车、还是清除按钮

请问搜索图标和清除图标同时存在的情况下，怎么区分？
