### ISSUE TITLE
v-model若绑定的是在created时添加的字段，无法修改

### ISSUE THREAD

**Issue by ZhongMingKun** [vueComponent/ant-design-vue#1968]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.6

### Environment
Vue@2.6.10

### Reproduction link
[https://gitee.com/ZMK_2017/a-form-model-bug.git](https://gitee.com/ZMK_2017/a-form-model-bug.git)

### Steps to reproduce
```html
<template>
  <div id="app">
    <a-form-model layout="inline" :model="model">
      <a-form-model-item label="input">
        <a-input v-model="model.name"></a-input>
      </a-form-model-item>
    </a-form-model>
  </div>
</template>

<script>
export default {
  name: 'App',
  data () {
    return {
      model: {}
    }
  },
  created() {
    this.model.name = '666'
  }
}
</script>
```

### What is expected?
可以修改v-model绑定的值

### What is actually happening?
不能修改v-model绑定的值

**Comment by sendya** [comment]
这是 Vue 的规范，不是组件问题。 你可以尝试直接在  data 中把值定义好，或者用 `$set` 将值设置进去，否则 Vue 无法响应动态新增的对象属性
