### ISSUE TITLE
FormModel未来会有a-date-picker控件时有类似form的normalize方法吗

### ISSUE THREAD

**Issue by 2261656355** [vueComponent/ant-design-vue#1978]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-date-picker对应的model为string类型，控件默认是moment类型，用form时，可以 normalize: v=>v?moment(v,'YYYY-MM-DD HH:mm:ss'):v

### What does the proposed API look like?
normalize: v=>v?moment(v,'YYYY-MM-DD HH:mm:ss'):v

**Comment by tangjinzhou** [comment]
2.0 之前还真不太好支持

**Comment by 2261656355** [comment]
好的，了解哈，谢谢。

**Comment by dzcpy** [comment]
FormModel要怎样normalize?
