### ISSUE TITLE
Tree component auto expand with no expanding icons

### ISSUE THREAD

**Issue by gdi2290** [vueComponent/ant-design-vue#198]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
We want to use the tree component that is auto expanded but we also don't want the user to expand the tree at all. We need a tree where we can add a valid/invalid icon next to all nodes (replace the expand icons for valid/invalid)

### What does the proposed API look like?
:expand="true"

TreeNode prop
valid
invalid

**Comment by tangjinzhou** [comment]
You can use like this
https://codesandbox.io/s/918yzy5yv4
```
<template>
  <a-tree
    :treeNodes="treeData"
    @expand="onExpand"
    :expandedKeys="expandedKeys"
  />
</template>
<script>
const treeData = [{
  title: 'parent 1',
  key: '0-0',
  class: 'expand-disabled',
  children: [
    { title: 'leaf', key: '0-0-0' },
    { title: 'leaf', key: '0-1-1' }],
}, {
  title: 'parent 1',
  key: '1-0',
  children: [
    { title: 'leaf', key: '1-0-0' },
    { title: 'leaf', key: '1-1-1' }],
}]

export default {
  data () {
    return {
      treeData,
      expandedKeys: [],
    }
  },
  methods: {
    onSelect (selectedKeys, info) {
      console.log('selected', selectedKeys, info)
    },
    onCheck (checkedKeys, info) {
      console.log('onCheck', checkedKeys, info)
    },
    onExpand (keys) {
      console.log(keys)
      this.expandedKeys = keys.filter(key => key !== '0-0')
    },
  },
}
</script>
<style>
.expand-disabled .ant-tree-switcher_close{
  color: #cccccc
}
</style>


```

**Comment by gdi2290** [comment]
How about an option to remove the expand element and have everything auto expanded. I still want to be able to click on the nodes, drag-n-drop, reorder so it can't be disabled

**Comment by tangjinzhou** [comment]
I don't fully understand what you mean.
But you can use `@expand="onExpand"  :expandedKeys="expandedKeys"` to control expanded nodes.

**Comment by gdi2290** [comment]
we ended up going with another ux. the only problem we had was being able to remove `ant-tree-switcher-noop` element
