### ISSUE TITLE
分页组件自定义上下页名称时样式错误

### ISSUE THREAD

**Issue by imic07** [vueComponent/ant-design-vue#1985]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
win10/chrome latest/vue 2.6

### Reproduction link
[https://antdv.com/components/pagination-cn/](https://antdv.com/components/pagination-cn/)

### Steps to reproduce
```
<a-pagination @change="onChange" :total="queryParam.total" :pageSize="queryParam.pageSize" :itemRender="itemRender" hideOnSinglePage/>

itemRender (current, type, originalElement) {
if (type === 'prev') {
return <a>上一页</a>
} else if (type === 'next') {
return <a>下一页</a>
}
return originalElement
},
```

### What is expected?
当点击到第一页时，上一页按钮灰掉

### What is actually happening?
当点击到第一页或者末尾页，上一页按钮或者下一页按钮不自动灰掉

![image](https://user-images.githubusercontent.com/16321067/77896428-ddd5bb00-72aa-11ea-87da-df6999854345.png)
调试发现a标签多了个data-v-xxx ，如果把它删除就会正常
![image](https://user-images.githubusercontent.com/16321067/77896387-c72f6400-72aa-11ea-9081-84539d19337d.png)

**Comment by tangjinzhou** [comment]
没能复现，理论上这是你自己定义了样式

**Comment by imic07** [comment]
在沙盒中确实没问题。我再找找原因
