### ISSUE TITLE
希望dropdown动态更新视图

### ISSUE THREAD

**Issue by hzh1990** [vueComponent/ant-design-vue#1986]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
比如在Dropdown显示时某项菜单倒计时5秒后从禁用状态变为可用状态

### What does the proposed API look like?
比如在Dropdown显示时某项菜单倒计时5秒后从禁用状态变为可用状态

**Comment by tangjinzhou** [comment]
改数据就好了
