### ISSUE TITLE
Tree node indent error

### ISSUE THREAD

**Issue by liudonghua123** [vueComponent/ant-design-vue#1997]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
Windows 10, Chrome 80, vue ^2.6.11

### Reproduction link
[https://www.antdv.com/components/tree-cn/#%E7%9B%AE%E5%BD%95](https://www.antdv.com/components/tree-cn/#%E7%9B%AE%E5%BD%95)

### Steps to reproduce
add the following snippets in template
```
<a-directory-tree multiple defaultExpandAll @select="onSelect" @expand="onExpand">
<a-tree-node title="p0" key="0-0">
<a-tree-node title="leaf 0-0" key="0-0-0" isLeaf />
<a-tree-node title="leaf 0-1" key="0-0-1" isLeaf />
</a-tree-node>
<a-tree-node title="parent 1" key="0-1">
<a-tree-node title="leaf 1-0" key="0-1-0" isLeaf />
<a-tree-node title="leaf 1-1" key="0-1-1" isLeaf />
</a-tree-node>
</a-directory-tree>
```

### What is expected?
与react版本的tree node的显示效果类似，子级会有一定的缩进

### What is actually happening?
所有节点不区分父子节点，没有缩进

**Comment by liudonghua123** [comment]
弄了好久，发现可以添加 
```css
li {
  text-align: left;
}
```
解决这个问题

**Comment by tangjinzhou** [comment]
官网并没问题啊

**Comment by liudonghua123** [comment]
嗯，官方没有这个问题，我是使用vue新建了一个空的项目，使用tree组件，发现是父容器中有text-align: center 的配置，子组件会继承，所以有这个问题。

![image](https://user-images.githubusercontent.com/2276718/78094718-cbbd5f00-7407-11ea-9ce7-30a1caf31944.png)
