### ISSUE TITLE
使用Form.create()修饰组件之后，组件的slots丢失

### ISSUE THREAD

**Issue by jiabinbin** [vueComponent/ant-design-vue#1998]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac Os catalina 10.15.4/ chrome 80.0.3987.149 (正式版本) （64 位）/  vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-qsobg)

### Steps to reproduce
参见重现链接
在components/search.js中
如果 使用 Form.create({})(Search) 则render时打印this.$slots对象为空
如果 不使用Form.cretae()则能正常打印this.$slots并渲染slots中的内容

### What is expected?
使用Form.create修饰时能正常的传递自定义的slots

### What is actually happening?
使用Form.create修饰时不能传递自定义slots

**Comment by tangjinzhou** [comment]
使用 createForm 吧
