### ISSUE TITLE
在关于table方面给个建议，希望作者看看

### ISSUE THREAD

**Issue by Huptzzz** [vueComponent/ant-design-vue#2012]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
建议在table上可以实现下复杂表的实现 如行表头合并 列表头合并，这样的话就可以实现复杂报表的功能 具体实现如https://github.com/zhjing1019/moreTreeTable

### What does the proposed API look like?
https://github.com/zhjing1019/moreTreeTable
![image](https://user-images.githubusercontent.com/54134961/78312605-eec24d00-7586-11ea-8b0e-26c0d6bb1c68.png)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/78314123-9772ab80-758b-11ea-9deb-dca455466499.png)
 这个不能满足吗？

**Comment by Huptzzz** [comment]
> ![image](https://user-images.githubusercontent.com/5404542/78314123-9772ab80-758b-11ea-9deb-dca455466499.png)
> 这个不能满足吗？
有时做的报表比较复杂，需要实现多向表头，横向纵向的树形结构表头，你可以看看https://github.com/zhjing1019/moreTreeTable这个例子，对于做复杂的报表挺有意义的
