### ISSUE TITLE
导航菜单动画有点卡顿可以解决下吗

### ISSUE THREAD

**Issue by wwji** [vueComponent/ant-design-vue#2018]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Steps to reproduce
点击导航菜单

### What is expected?
优化下

### What is actually happening?
动画卡顿

**Comment by tangjinzhou** [comment]
感觉还好啊  欢迎pr

**Comment by raindrop4steven** [comment]
一般客户电脑配置没有做开发的人员高，实际使用中菜单收缩真的很卡
