### ISSUE TITLE
Table children 渲染和数据不一致

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#202]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.3

### Environment
Win7/vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r46pxm0zjq)

### Steps to reproduce
点击更新，核对数据是否正确。

### What is expected?
和数据保持一致。

### What is actually happening?
和数据保持一致。

---
子集数据原先在列表中（但是是children），更新数据之后放到父级会有问题。

目前我的解决方案：在更新之前先赋值为空数组。

**Comment by tangjinzhou** [comment]
1.1.4
