### ISSUE TITLE
已经引入了整个antdv 但是报Unknown element: <a-transfer>的错误

### ISSUE THREAD

**Issue by summerzi** [vueComponent/ant-design-vue#2021]
我用了ant design pro vue 来搭建后台系统，看了代码就引入了ant 的所有组件。用其他组件都正常，但是用了 <a-transfer> 组件，就会报
‘Unknown custom element: <a-transfer> - did you register the component correctly? For recursive components, make sure to provide the "name" option.’的错误，在node_modules/ant-design-vue 下面是有Transfer的，现在想咨询下有可能是什么问题？谢谢

**Comment by magicpal** [comment]
请问问题解决了吗

**Comment by winyh** [comment]
单独引入：
import { Transfer } from 'ant-design-vue'

注册：
components: {
    ...,
    ATransfer: Transfer
  },
