### ISSUE TITLE
nuxt按需引入得到Cannot use import statement outside a module

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#2022]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
win10,chrome80 vue 2.6 

### Reproduction link
[https://ant-design-vue.gitee.io/issue-helper/暂无](https://ant-design-vue.gitee.io/issue-helper/暂无)

### Steps to reproduce
使用官方脚手架拉取模板，修改nuxt.config.js文件，添加plugins>ant-design-vue.js报错Cannot use import statement outside a module，全局引入是没有问题的，这个让我很费解。

## ant-design-vue.js
``` js
// 按需加载组件
import Vue from 'vue'
import { Menu, Icon, ConfigProvider, Layout } from 'ant-design-vue'

Vue.use(Menu)

Vue.use(Icon)
Vue.use(ConfigProvider)
Vue.use(Layout)

```
## nuxt.config.js
``` js
css: [
{ src: 'ant-design-vue/dist/antd.less', lang: 'less' },
'@/assets/style.less'
],
// ...
build: {
babel: {
plugins: [['import', { libraryName: 'ant-design-vue', style: 'css' }]]
},
loaders: {
less: {
javascriptEnabled: true
}
}
},
```

### What is expected?
期待正常按需加载

### What is actually happening?
Cannot use import statement outside a module

**Comment by bosens-China** [comment]
抱歉，链接地址就没添加，不过剪短的说明，应该足够了

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/234#issuecomment-433333431

**Comment by bosens-China** [comment]
@tangjinzhou 
谢谢，我晚上尝试下，可以方便问下关于ico组件，有一个加载阿里图标库的实例，我如果用nuxt这部分是不是不能让他在服务器渲染中呈现
