### ISSUE TITLE
Select slow at rendering list and selecting

### ISSUE THREAD

**Issue by ngajhede** [vueComponent/ant-design-vue#2025]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
MacOS, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-i8t7i)

### Steps to reproduce
Render list of ~750 items in a tag selector, and click the selector and select

### What is expected?
Quick response when openening and selecting value

### What is actually happening?
Slow response, lag when selecting

---
I've tried different ways of selecting, via methods, via v-model etc.
I use a different select component right now, but I would like to move everything to Ant Design.

**Comment by hoanphi2201** [comment]
@ngajhede 
Very slow when there is a large amount of data

**Comment by hoanphi2201** [comment]
@ngajhede  
This has also been fixed in ant design react v4

**Comment by hoanphi2201** [comment]
@antdvteam
Also serious problem is that it affects other components of the form.

**Comment by tangjinzhou** [comment]
2.0 resolved
