### ISSUE TITLE
antd input a-textarea scrollbar shake 

### ISSUE THREAD

**Issue by DMing-lin** [vueComponent/ant-design-vue#2027]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
win10 Google Chrome80 vue2.6

### Reproduction link
[https://www.antdv.com/components/input-cn/](https://www.antdv.com/components/input-cn/)

### Steps to reproduce
input a-textarea :autoSize maxRows scrollbar shake
input的文本域设置适应文本高度，当他超过最大行数时滚动条会闪烁抖动，1.5版本之前没有出现
<a-textarea
:autoSize="{ minRows: 1, maxRows: 4 }"
/>

### What is expected?
input的文本域可以正确设置适应文本高度属性，超过最大行数时滚动条不会会闪烁抖动

### What is actually happening?
input的文本域设置适应文本高度，当他超过最大行数时滚动条会闪烁抖动

---
目前官网的案例也有这个问题

**Comment by tangjinzhou** [comment]
1.5.1 ?

**Comment by microJ** [comment]
@DMing-lin 
我 1.5.0 发现了 #2005 这个问题，强制 <a-textarea style="overflow-y:auto" /> 解决了抖动。

**Comment by tangjinzhou** [comment]
升级 1.5.1 +  已经修复了

**Comment by DMing-lin** [comment]
好的，谢谢

tangjinzhou <notifications@github.com> 于2020年4月12日周日 下午2:58写道：
