### ISSUE TITLE
Table children 渲染报错 duplicate key

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#203]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.3

### Environment
Win7/vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4j8py60yo9)

### Steps to reproduce
点击更新，核对 console 是否有异常日志。

### What is expected?
没有异常日志，且界面不卡死。

### What is actually happening?
有异常日志，且卡死。

---
子集数据原先在列表中（但是是children），更新数据之后放到父级会有问题。应该和[这个](https://github.com/vueComponent/ant-design-vue/issues/202) 类似。

目前我的解决方案：在更新之前先赋值为空数组。

**Comment by tangjinzhou** [comment]
这个的确是有重复的key导致的

**Comment by tangjinzhou** [comment]
children中的key和父节点的key也不能重复，不然 selectedRowKeys 和 expandedRowKeys 无法扁平化方式使用。
你可以使用 :rowKey="record=>`${record.key}-${record.xxx}`"自定义key，或者预先处理key，保持唯一性

**Comment by bq-hentai** [comment]
好吧，我看如果我先重置为空数组就没问题。具体的代码逻辑之后看看

**Comment by tangjinzhou** [comment]
先重置为空数组依然也报重复key啊
