### ISSUE TITLE
tab 的tabClick事件 tab切换一次后再次切换回来 点击tab就不会触发了

### ISSUE THREAD

**Issue by ningstudy** [vueComponent/ant-design-vue#2030]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
1.5.0的版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-9wkce?file=/src/App.vue)

### Steps to reproduce
tab 的tabClick事件 tab切换一次后再次切换回来 点击tab就不会触发了

### What is expected?
tab 的tabClick事件 tab切换一次后再次切换回来 点击tab就不会触发了

### What is actually happening?
tab 的tabClick事件 tab切换一次后再次切换回来 点击tab就不会触发了

---
tab 的tabClick事件 tab切换一次后再次切换回来 点击tab就不会触发了

**Comment by sendya** [comment]
你好，框架大范围更新时，光靠几个开发人员，是无法做到全方位测试的，很容易出现这种漏掉的问题。欢迎测试并提供问题报告。这个问题已经记录，会尽快处理
另外也希望不要带着脾气对待开源项目，让人心生芥蒂

**Comment by ningstudy** [comment]
> 你好，框架大范围更新时，光靠几个开发人员，是无法做到全方位测试的，很容易出现这种漏掉的问题。欢迎测试并提供问题报告。这个问题已经记录，会尽快处理
> 另外也希望不要带着脾气对待开源项目，让人心生芥蒂
唉 框架更新的时候能在文档里说明一下有哪些更新吗，不然很容易出错

**Comment by ningstudy** [comment]
唉 框架更新的时候能在文档里说明一下有哪些更新吗，不然很容易出错
