### ISSUE TITLE
select,date-picker,month-picker,range-picker,week-picker 在自定义指令中绑定change 事件不生效

### ISSUE THREAD

**Issue by JinPengGeng** [vueComponent/ant-design-vue#2031]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0 及 1.5.1等以前版本，我只试到了1.4

### Environment
os: win10,   npm: 6.12.1  @vue/cli: 4.2.3, brower: chrome 78.0.3904.97（Official Build） （64 ビット）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-ecwpj?file=/src/App.vue)

### Steps to reproduce
参考 [重现链接](https://codesandbox.io/s/vue-antd-template-ecwpj?file=/src/App.vue)

### What is expected?
自定义指令绑定事件，正常生效

### What is actually happening?
自定义指令绑定事件，没有效果

---
场景：自定义指令实现所有 validation check统一管理，通过配置文件进行集成，同时绑定触发事件（change、blur...）和 触发参数

eg:  v-validate.change="'xxx'"

目前测试结果：
input 、checkbox，checkbox group 绑定正常
select、所有日期相关（date-picker）等绑定失败

临时解决方案：

node_modules\ant-design-vue\es\select\index.js

L119-L122 =>
```
// FIXME: fire change for select component
fireChange: function fireChange(value) {
    this.$emit('change', value);
},
```
L253-L257 =>
```
// FIXME: fire change for select component
// on: getListeners(this),
on:_extends({}, getListeners(this), {
    change: this.fireChange
}),
```
node_modules\ant-design-vue\es\date-picker\wrapPicker.js

L104-L107 =>
```
// FIXME: fire change for select component
fireChange: function fireChange(e) {
    this.$emit('change', arguments[0], arguments[1]);
},
```
L196-L197 =>
```
// FIXME: fire change for select component
change: this.fireChange,
```
希望作者大大能够官方提供事件穿透  ：）

**Comment by mx4g** [comment]
我从1.4.12 升级到1.5.1 ，发现Table 的列用 fixed: "left"会报异常，
异常：Cannot read property 'querySelectorAll' of null"

found in

---> <Table>
       <Table>
         <LocaleReceiver>
           <ASpin>
             <Table>
               <ATable>
                 <ACol>
                   <ARow>
                     <LoginUser> at src/views/User.vue
                       <ALocaleProvider>
                         <LocaleReceiver>
                           <AConfigProvider>
                             <App> at src/App.vue
                               <Root>

**Comment by JinPengGeng** [comment]
> 我从1.4.12 升级到1.5.1 ，发现Table 的列用 fixed: "left"会报异常，
> 异常：Cannot read property 'querySelectorAll' of null"

```
columns: [
        {
          title: () => {
            return (
              <a-checkbox
                indeterminate={this.indeterminate}
                checked={this.checkAll}
                onChange={this.onCheckAllChange}
              />
            )
          },
          fixed: 'left',
          align: 'center',
          width: 50,
          customRender: (text, row, index) => {
            const obj = {
              children: (
                <a-checkbox
                  checked={row.checked}
                  onChange={e => this.onCheckboxChange(row, e, index)}
                />
              ),
              attrs: {}
            }
            if (index % 12 === 0) {
              obj.attrs.rowSpan = 12
            } else {
              obj.attrs.rowSpan = 0
            }
            obj.class = 'column-top'
            return obj
          }
        }
]
```
@mx4g

**Comment by mx4g** [comment]
> > 我从1.4.12 升级到1.5.1 ，发现Table 的列用 fixed: "left"会报异常，
> > 异常：Cannot read property 'querySelectorAll' of null"
> 
> 我目前的使用方式，你可以参考一下，另外，定位你的问题，需要你把相关的code贴出来
> 
> ```
> columns: [
>         {
>           title: () => {
>             return (
>               <a-checkbox
>                 indeterminate={this.indeterminate}
>                 checked={this.checkAll}
>                 onChange={this.onCheckAllChange}
>               />
>             )
>           },
>           fixed: 'left',
>           align: 'center',
>           width: 50,
>           customRender: (text, row, index) => {
>             const obj = {
>               children: (
>                 <a-checkbox
>                   checked={row.checked}
>                   onChange={e => this.onCheckboxChange(row, e, index)}
>                 />
>               ),
>               attrs: {}
>             }
>             if (index % 12 === 0) {
>               obj.attrs.rowSpan = 12
>             } else {
>               obj.attrs.rowSpan = 0
>             }
>             obj.class = 'column-top'
>             return obj
>           }
>         }
> ]
> ```
> 
> @mx4g

> ```
>const columnsByPhone = [
>  {
>    title: "用户名",
>   dataIndex: "userName",
>   width: 100,
>   fixed: "left"
> },
>  {
>    title: "名字",
>    dataIndex: "nickname"
> },
>  {
>    title: "错误登录次数",
>    dataIndex: "loginErrorCount"
>  },
>  {
>    title: "错误登录时间",
>    dataIndex: "lastLoginErrorDate"
>  },
> {
>    title: "创建时间",
>    dataIndex: "createDate"
>  },
>  {
>    title: "更新时间",
>    dataIndex: "updateDate"
>  }
>];
> ```
@JinPengGeng  我这样写的，首列fixed: "left"去掉，就不报异常

**Comment by JinPengGeng** [comment]
@mx4g 
> h5 code

```
<a-table
            :columns="columns"
            :dataSource="data"
          >
```
> js code
```
columns: [
        {
          title: '用户名',
          dataIndex: 'userName',
          width: 100,
          fixed: 'left'
        },
        {
          title: '名字',
          dataIndex: 'nickname'
        },
        {
          title: '错误登录次数',
          dataIndex: 'loginErrorCount'
        },
        {
          title: '错误登录时间',
          dataIndex: 'lastLoginErrorDate'
        },
        {
          title: '创建时间',
          dataIndex: 'createDate'
        },
        {
          title: '更新时间',
          dataIndex: 'updateDate'
        }
      ],
      data: [
        {
          key: '1',
          userName: '小明',
          nickname: '001',
          loginErrorCount: 0,
          lastLoginErrorDate: new Date().getUTCMilliseconds(),
          createDate: new Date().getMilliseconds(),
          updateDate: new Date().getMilliseconds() + 123456
        },
        {
          key: '2',
          userName: '李莉',
          nickname: '002',
          loginErrorCount: 32,
          lastLoginErrorDate: new Date().getUTCMilliseconds(),
          createDate: new Date().getMilliseconds(),
          updateDate: new Date().getMilliseconds() + 123456
        },
        {
          key: '3',
          userName: '王小帅',
          nickname: '003',
          loginErrorCount: 54,
          lastLoginErrorDate: new Date().getUTCMilliseconds(),
          createDate: new Date().getMilliseconds(),
          updateDate: new Date().getMilliseconds() + 123456
        }
      ],
```
没有任何问题

**Comment by mx4g** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月8日(星期三) 中午12:38
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"东楼后座"<522293522@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] select,date-picker,month-picker,range-picker,week-picker 在自定义指令中绑定change 事件不生效 (#2031)





 
@mx4g
  
h5 code
  <a-table             :columns="columns"             :dataSource="data"           &gt;   
js code
  columns: [         {           title: '用户名',           dataIndex: 'userName',           width: 100,           fixed: 'left'         },         {           title: '名字',           dataIndex: 'nickname'         },         {           title: '错误登录次数',           dataIndex: 'loginErrorCount'         },         {           title: '错误登录时间',           dataIndex: 'lastLoginErrorDate'         },         {           title: '创建时间',           dataIndex: 'createDate'         },         {           title: '更新时间',           dataIndex: 'updateDate'         }       ],       data: [         {           key: '1',           userName: '小明',           nickname: '001',           loginErrorCount: 0,           lastLoginErrorDate: new Date().getUTCMilliseconds(),           createDate: new Date().getMilliseconds(),           updateDate: new Date().getMilliseconds() + 123456         },         {           key: '2',           userName: '李莉',           nickname: '002',           loginErrorCount: 32,           lastLoginErrorDate: new Date().getUTCMilliseconds(),           createDate: new Date().getMilliseconds(),           updateDate: new Date().getMilliseconds() + 123456         },         {           key: '3',           userName: '王小帅',           nickname: '003',           loginErrorCount: 54,           lastLoginErrorDate: new Date().getUTCMilliseconds(),           createDate: new Date().getMilliseconds(),           updateDate: new Date().getMilliseconds() + 123456         }       ],  
没有任何问题

**Comment by mx4g** [comment]
> @mx4g
> 
> > h5 code
> 
> ```
> <a-table
>             :columns="columns"
>             :dataSource="data"
>           >
> ```
> 
> > js code
> 
> ```
> columns: [
>         {
>           title: '用户名',
>           dataIndex: 'userName',
>           width: 100,
>           fixed: 'left'
>         },
>         {
>           title: '名字',
>           dataIndex: 'nickname'
>         },
>         {
>           title: '错误登录次数',
>           dataIndex: 'loginErrorCount'
>         },
>         {
>           title: '错误登录时间',
>           dataIndex: 'lastLoginErrorDate'
>         },
>         {
>           title: '创建时间',
>           dataIndex: 'createDate'
>         },
>         {
>           title: '更新时间',
>           dataIndex: 'updateDate'
>         }
>       ],
>       data: [
>         {
>           key: '1',
>           userName: '小明',
>           nickname: '001',
>           loginErrorCount: 0,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         },
>         {
>           key: '2',
>           userName: '李莉',
>           nickname: '002',
>           loginErrorCount: 32,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         },
>         {
>           key: '3',
>           userName: '王小帅',
>           nickname: '003',
>           loginErrorCount: 54,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         }
>       ],
> ```
> 
> 没有任何问题



因为我做了手机端自适应，用到了window.onresize方法 。
代码：
> ```
><template>
>  <a-table :columns="columns" :dataSource="data" :scroll="{ x: this.scrollX }">
>    <a slot="name" slot-scope="text">{{ text }}</a>
>  </a-table>
></template>
><script>
>const columns = [
> {
>    title: "Name",
>    dataIndex: "name",
>    key: "name",
>    scopedSlots: { customRender: "name" }
>  },
>  {
>    title: "Age",
>    dataIndex: "age",
>    key: "age",
>    width: 80
>  },
>  {
>    title: "Address",
>    dataIndex: "address",
>    key: "address 1",
>    ellipsis: true
>  },
>  {
>    title: "Long Column Long Column Long Column",
>    dataIndex: "address",
>    key: "address 2",
>    ellipsis: true
>  },
>  {
>    title: "Long Column Long Column",
>    dataIndex: "address",
>    key: "address 3",
>    ellipsis: true
>  },
>  {
>    title: "Long Column",
>    dataIndex: "address",
>    key: "address 4",
>    ellipsis: true
>  }
> ];
>
> const columnsByPhone = [
> {
>    title: "Name",
>    dataIndex: "name",
>    key: "name",
>    scopedSlots: { customRender: "name" },
>    width: 100,
>    fixed: "left"
>  },
>  {
>    title: "Age",
>    dataIndex: "age",
>    key: "age",
>    width: 80
>  },
>  {
>    title: "Address",
>    dataIndex: "address",
>    key: "address 1",
>    ellipsis: true
>  },
>  {
>    title: "Long Column Long Column Long Column",
>    dataIndex: "address",
>    key: "address 2",
>    ellipsis: true
>  },
>  {
>    title: "Long Column Long Column",
>    dataIndex: "address",
>    key: "address 3",
>    ellipsis: true
>  },
>  {
>    title: "Long Column",
>    dataIndex: "address",
>    key: "address 4",
>    ellipsis: true
>  }
> ];
>
> const data = [
>  {
>    key: "1",
>    name: "John Brown",
>    age: 32,
>    address: "New York No. 1 Lake Park, New York No. 1 Lake Park",
>    tags: ["nice", "developer"]
>  },
>  {
>    key: "2",
>    name: "Jim Green",
>    age: 42,
>    address: "London No. 2 Lake Park, London No. 2 Lake Park",
>    tags: ["loser"]
>  },
>  {
>    key: "3",
>    name: "Joe Black",
>    age: 32,
>    address: "Sidney No. 1 Lake Park, Sidney No. 1 Lake Park",
>    tags: ["cool", "teacher"]
>  }
> ];
>
> export default {
> data() {
>    return {
>      scrollX: 0,
>      scrollPhoneX: 900,
>      data,
>      columns
>    };
>  },
>  beforeMount() {
>   this.resize();
>    window.onresize = () => {
>      this.resize();
>    };
>  },
>  methods: {
>    resize() {
>      var _this = this;
>      _this.clientWidth = document.body.clientWidth;
>      if (this.clientWidth < 576) {
>        _this.btnNeedTip = false;
>        _this.scrollX = _this.scrollPhoneX;
>        _this.columns = columnsByPhone;
>      } else {
>        _this.btnNeedTip = true;
>        _this.scrollX = 0;
>        _this.columns = columns;
>      }
>    }
>  }
> };
></script>
> ```
你有邮箱吗？我可以把Demo发给你看看
![1 5 1版本点击切换会出现异常，1 4 12版本不会](https://user-images.githubusercontent.com/7499986/78755855-73a8ce80-79ac-11ea-82bf-35e900c63a91.jpg)

**Comment by mx4g** [comment]
> @mx4g
> 
> > h5 code
> 
> ```
> <a-table
>             :columns="columns"
>             :dataSource="data"
>           >
> ```
> 
> > js code
> 
> ```
> columns: [
>         {
>           title: '用户名',
>           dataIndex: 'userName',
>           width: 100,
>           fixed: 'left'
>         },
>         {
>           title: '名字',
>           dataIndex: 'nickname'
>         },
>         {
>           title: '错误登录次数',
>           dataIndex: 'loginErrorCount'
>         },
>         {
>           title: '错误登录时间',
>           dataIndex: 'lastLoginErrorDate'
>         },
>         {
>           title: '创建时间',
>           dataIndex: 'createDate'
>         },
>         {
>           title: '更新时间',
>           dataIndex: 'updateDate'
>         }
>       ],
>       data: [
>         {
>           key: '1',
>           userName: '小明',
>           nickname: '001',
>           loginErrorCount: 0,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         },
>         {
>           key: '2',
>           userName: '李莉',
>           nickname: '002',
>           loginErrorCount: 32,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         },
>         {
>           key: '3',
>           userName: '王小帅',
>           nickname: '003',
>           loginErrorCount: 54,
>           lastLoginErrorDate: new Date().getUTCMilliseconds(),
>           createDate: new Date().getMilliseconds(),
>           updateDate: new Date().getMilliseconds() + 123456
>         }
>       ],
> ```
> 
> 没有任何问题

之前1.4.12版本不会有这种问题，更新为1.5.1版本后点击切换会出现异常，

**Comment by mx4g** [comment]
@JinPengGeng 
[antd-demo.zip](https://github.com/vueComponent/ant-design-vue/files/4448883/antd-demo.zip)
太棒了，原来可以发文件。发给你看看

**Comment by tangjinzhou** [comment]
> 我从1.4.12 升级到1.5.1 ，发现Table 的列用 fixed: "left"会报异常，
> 异常：Cannot read property 'querySelectorAll' of null"

你可以新开issue 讨论这个问题，不同的问题不要在一个issue下讨论

**Comment by mx4g** [comment]
> > 我从1.4.12 升级到1.5.1 ，发现Table 的列用 fixed: "left"会报异常，
> > 异常：Cannot read property 'querySelectorAll' of null"
> 
> 你可以新开issue 讨论这个问题，不同的问题不要在一个issue下讨论
> 
> @mx4g

好的
