### ISSUE TITLE
1.5.1 table resize throw error 

### ISSUE THREAD

**Issue by mx4g** [vueComponent/ant-design-vue#2033]
vue/cli 4.0.5版本，浏览器切换手机模式，更换Table的列时，出现该问题。
我做了手机端自适应,用到了window.onresize方法 ,来切换列的配置。
之前是1.4.12版本不会出现该问题，换了1.5.1就出现了。
@tangjinzhou

![1 5 1版本点击切换会出现异常，1 4 12版本不会](https://user-images.githubusercontent.com/7499986/78757651-6ccf8b00-79af-11ea-91f2-65996570c187.jpg)

Demo：
[antd-demo.zip](https://github.com/vueComponent/ant-design-vue/files/4448968/antd-demo.zip)

**Comment by mx4g** [comment]
@JinPengGeng 
Demo：
[antd-demo.zip](https://github.com/vueComponent/ant-design-vue/files/4448961/antd-demo.zip)

![1 5 1版本点击切换会出现异常，1 4 12版本不会](https://user-images.githubusercontent.com/7499986/78757566-47db1800-79af-11ea-903d-5381eb3b0dfc.jpg)

**Comment by mx4g** [comment]
@tangjinzhou

**Comment by JinPengGeng** [comment]
@mx4g 
> 调查了三个小时，其中被浏览器坑了一半左右的时间

> 目前的解决方案
> node_modules/ant-design-vue/es/vc-table/src/Table.js
> L233 => 修正为
```
      var node = this.ref_bodyTable || this.ref_fixedColumnsBodyRight || this.ref_fixedColumnsBodyLeft

```
> L289 => 修正为
```
const bodyTable = this.ref_bodyTable || this.ref_fixedColumnsBodyRight || this.ref_fixedColumnsBodyLeft
      // var headRows = this.ref_headTable ? this.ref_headTable.querySelectorAll('thead') : this.ref_bodyTable.querySelectorAll('thead');
      // var bodyRows = this.ref_bodyTable.querySelectorAll('.' + prefixCls + '-row') || [];
      var headRows = this.ref_headTable ? this.ref_headTable.querySelectorAll('thead') : this.bodyTable.querySelectorAll('thead');
      var bodyRows = this.bodyTable.querySelectorAll('.' + prefixCls + '-row') || [];


```
> L276 => 不确定这里是否需要添加，还是需要作者大大点头确认才行，这里坑了我好长时间，现象很迷幻，保险起见还是添加移除事件吧 : (
```
handleWindowResize: function handleWindowResize() {
      this.syncFixedTableRowHeight();
      this.setScrollPositionClassName();
      
      if (this.resizeEvent) {
        this.resizeEvent.remove();
      }
      if (this.debouncedWindowResize) {
        this.debouncedWindowResize.cancel();
      }
    },
```
> 原因解释：
> 目前我所能调查到的是
> 在动态添加固定列时（从无到有的状态）
> 会触发一次Window的resize事件（不确定是否只执行一次，但代码中好像是，好像是，好像是，触发过就会一直绑定着resize的监听事件，直到组件销毁）
> 这时，重新确定行高（syncFixedTableRowHeight 方法）
> 但是，在方法体中，使用的是非固定列高度重新计算
> 由于状态已经由非固定列 => 转为固定列
> 计算方式应用错误，才会出现 querySelectorAll 异常错误
> 

> 在1.5.0版本更新时，官方更新了table
> 新增 tableLayout 属性，支持设置表格的 table-layout 布局，
> 并在固定表头/列下默认开启 tableLayout="fixed"，解决因为表格自动根据内容排版造成的列对齐问题。

> 个人觉得，应该是这个时间点产生的这个问题，不确定哈，没有比对更新记录
> 以上纯属个人想法，不代表正确
> 最后，希望能够获得作者大大的官方解决方案  @tangjinzhou ：）

**Comment by tangjinzhou** [comment]
具体原因这里  https://github.com/vueComponent/vue-ref/commit/828b32bc3d61a781adf7c8a74a29db62c87eb103

**Comment by tangjinzhou** [comment]
着急的话  业务代码里 添加 vue-ref 2.0.0 的依赖

**Comment by mx4g** [comment]
> 着急的话 业务代码里 添加 vue-ref 2.0.0 的依赖

好的，谢谢老大
