### ISSUE TITLE
如何修改icon的引用路径让在内网中能够展示正确的icon而不是一个方框

### ISSUE THREAD

**Issue by qifengwangye** [vueComponent/ant-design-vue#204]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.3

### Environment
ant-design-vue: 1.1.1; babel-plugin-import: 1.9.1; vue: 2.5.2

### Reproduction link
[https://git.coding.net/wangye84/vue-antd-admin-template.git](https://git.coding.net/wangye84/vue-antd-admin-template.git)

### Steps to reproduce
因为icon的url是一个cdn，在内网环境，所有的ant-design-vue组件的icon都显示的是一个方框。

### What is expected?
在内网环境中，能修改icon-url为本地的icon数据

### What is actually happening?
因为vue版本的样式文件是css，无法通过less来进行修改，导致无法修改icon-url

**Comment by tangjinzhou** [comment]
可以用less啊

**Comment by qifengwangye** [comment]
@tangjinzhou 可以请教下如何配置吗，我配置了没有作用

**Comment by tangjinzhou** [comment]
参考主题定制 https://vuecomponent.github.io/ant-design-vue/docs/vue/customize-theme-cn/
