### ISSUE TITLE
validator函数错误导致form表单校验卡主

### ISSUE THREAD

**Issue by zt8989** [vueComponent/ant-design-vue#2042]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
osx 10.14, chrome 80, vue 2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-voice-54jj8?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. input框输入字符
2. 点击submit

### What is expected?
报错

### What is actually happening?
表单卡主

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/78865162-b384ba00-7a6f-11ea-8bdf-f6172bc6b96a.png)

**Comment by zt8989** [comment]
故意这么写的

**Comment by tangjinzhou** [comment]
😓  自行try catch 包住吧
