### ISSUE TITLE
Vue form 和 FormModel 区别

### ISSUE THREAD

**Issue by Xiaohantx** [vueComponent/ant-design-vue#2043]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
没有看见文档说明Vue form 和 FormModel 区别第一次使用有点懵逼

### What does the proposed API look like?
希望文档能够说明下区别之处

**Comment by sendya** [comment]
从说明即可知道，是支持 `v-model` 方式使用的组件，具体直接看 API
