### ISSUE TITLE
table customCell没有生效

### ISSUE THREAD

**Issue by chenquan** [vueComponent/ant-design-vue#2050]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10 chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-table-customrow-kkjnj?file=/src/App.vue)

### Steps to reproduce
无

### What is expected?
触发点击事件

### What is actually happening?
没有触发点击事件

**Comment by zkwolf** [comment]
customCell是column的参数啊不是table的

**Comment by chenquan** [comment]
> customCell是column的参数啊不是table的

谢谢了哈,后面我也发现咯
