### ISSUE TITLE
Descriptions 描述列表 的 label 没显示出来

### ISSUE THREAD

**Issue by LiaoSWen** [vueComponent/ant-design-vue#2053]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
win10 chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-hofstadter-sncz5?file=/src/App.vue)

### Steps to reproduce
这啥啊，重现参考https://codesandbox.io/s/clever-hofstadter-sncz5?file=/src/App.vue

### What is expected?
列表内容完整显示出来

### What is actually happening?
列表标签label没显示

**Comment by zkwolf** [comment]
按需引入用Vue.use(Descriptions)

**Comment by LiaoSWen** [comment]
ok ,解决了，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zkwolf"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月10日(星期五) 下午3:54
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"不呆"<2101632031@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] Descriptions 描述列表 的 label 没显示出来 (#2053)





 
按需引入用Vue.use(Descriptions)
