### ISSUE TITLE
select 组件，当数据结构过深时，无法正常渲染。

### ISSUE THREAD

**Issue by hzyyy** [vueComponent/ant-design-vue#2060]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
macos， chrome 78, vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-3kjl2?file=/src/App.vue)

### Steps to reproduce
正常复现；

### What is expected?
正常渲染

### What is actually happening?
不能够正常渲染，需要使用$forceUpdate() 强行组件渲染；不太喜欢这种强硬方式，感觉不太友好。

---
暂时不考虑使用$forceUpdate()。

**Comment by tangjinzhou** [comment]
这是 vue 机制，你应该改变原始对象 
示例 ： https://codesandbox.io/s/vue-antd-template-n0bk7?file=/src/App.vue

**Comment by hzyyy** [comment]
感谢；
