### ISSUE TITLE
a-upload组件,当设置了fileList之后,接收不到file.status为done的change事件,只能接收到file.status为uploading的事件

### ISSUE THREAD

**Issue by DuShen666** [vueComponent/ant-design-vue#2061]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
vue3.1.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/upload/Upload.jsx](https://github.com/vueComponent/ant-design-vue/blob/master/components/upload/Upload.jsx)

### Steps to reproduce
由于`ant-design-vue/components/upload/Upload.jsx`中的如下代码段中:
```
onSuccess(response, file, xhr) {
//...
const targetItem = getFileItem(file, fileList);
// removed
if (!targetItem) {
return;
}
//...
}
```
以上代码段中,`fileList`中是永远不包含`file`的,所以无法接收到`file.status`为`done`的`change`事件

虽然可以在`customRequest`中将`file`手动push进`fileList`解决,但这应该不是antd预期的逻辑

### What is expected?
Upload组件当提供了fileList之后应该与不提供该属性时一样,能接收到file.status为done的change事件

### What is actually happening?
只能接收到file.status为uploading的change事件,导致无法判断文件上传是否完成.

---
另外[文档](https://www.antdv.com/components/upload-cn/#API)中`customRequest`是否应该提供一个范例,以免使用到该属性时还要去翻源码的实现逻辑.

**Comment by sendya** [comment]
你需要自己接收 change 事件的 `fileList: []`  并更新到组件的 fileList，来完成上传状态的扭转

**Comment by Robin-zero** [comment]
> 你需要自己接收 change 事件的 `fileList: []` 并更新到组件的 fileList，来完成上传状态的扭转

有没有代码示例？我用的官方的案例都不得行，案例地址：https://www.antdv.com/components/upload-cn/#components-upload-demo-complete-control-over-file-list

**Comment by blakelu** [comment]
如果用了 fileList 动态参数,在第一次捕捉到 uploading的时候就要执行
this.fileList = 参数 fileList，负责不会捕捉到done与其他状态

**Comment by hexuan-aurora** [comment]
> 更新到组件的 fileList，来完成上传状态的扭转

@sendya 在页面中更新 FileList 没问题，但关键是只能接收到上传图片的 uploading 的事件，且事件返回的 File 对象中并不包含 event 以及上传接口返回的 Response。

![](https://blog-1255677601.cossh.myqcloud.com/blog/2020-10-27-113521.jpg)

**Comment by ManfredHu** [comment]
同问……自定义上传确实没有例子。而且这里FormData上传的模式定死了
