### ISSUE TITLE
layout header support theme attribute will make the component more elegant

### ISSUE THREAD

**Issue by buildJava** [vueComponent/ant-design-vue#2062]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
With int ant design pro vue, we want to switch top menu layout theme to light, currently we use style to rewrite the background, however, the sider layout has attribute theme to make this transformer more elegant, just suggestions！wish this project much better!

### What does the proposed API look like?
support theme attribute on header layout

**Comment by enodr** [comment]
Hi, 

I second this feature request and would even like it to be extended to every components. It would be great to be able to pass a theme=dark property to any component.

Thanks

**Comment by chsword** [comment]
+1
