### ISSUE TITLE
Upload组件，当showUploadList = false，自定义渲染已上传列表，如何保留上传时的进度条

### ISSUE THREAD

**Issue by zhanyoulin456** [vueComponent/ant-design-vue#2072]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue-cli3

### Reproduction link
[https://www.antdv.com/components/upload-cn/#API](https://www.antdv.com/components/upload-cn/#API)

### Steps to reproduce
what?

### What is expected?
Upload组件，当showUploadList = false，自定义渲染已上传列表，如何保留上传时的进度条

### What is actually happening?
...

**Comment by Amour1688** [comment]
可以自己用 `Progress` 来实现
