### ISSUE TITLE
【Bug】tabBarGutter props not used

### ISSUE THREAD

**Issue by earlymeme** [vueComponent/ant-design-vue#2083]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.3

### Environment
latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tabs-tabbargutter-not-used-403l4)

### Steps to reproduce
just open codesandbox

### What is expected?
tabBarGutter生效，间隙为0

### What is actually happening?
间隙还是默认2px

**Comment by Amour1688** [comment]
有 `demo` 吗，或者提供代码也行
