### ISSUE TITLE
有没有可以测试ant-design-vue组件的WEB自动化测试工具推荐？

### ISSUE THREAD

**Issue by F12EN** [vueComponent/ant-design-vue#2086]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
macOS Mojave 10.14.6,Google Chrome 80.0.3987.149,vue 2.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
我们项目目前使用的的前端UI组件是ant-design-vue，首先感谢你们开源这么好的Vue组件，对我们有很有的帮助。
目前使用ant-design-vue组件开发速度很快，但在做业务测试时，我们尝试使用WEB自动化测试工具录制浏览器交互并生成测试脚本，并没有那么顺利，
我们尝试了selenium录制器 、国内多测测录制器、imacros，但这些工具在录制时要么识别不了Select 选择器里的选项，要么识别不了DatePicker时间选择器的选择操作😂。

### What is expected?
想请教你们开发与测试过程中，有没有可以测试ant-design-vue组件的WEB自动化测试工具推荐？或者关于测试（业务测试）ant-design-vue组件的最佳实践？

### What is actually happening?
WEB自动化测试工具识别不了Select 选择器和DatePicker时间选择器里的选项

**Comment by hxqcc** [comment]
请问找到解决方案了吗？
