### ISSUE TITLE
form放入drawer中，使用fieldDecoratorId绑定数据后，中文输入法会多出很多字母

### ISSUE THREAD

**Issue by Martin-Bai** [vueComponent/ant-design-vue#209]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.4

### Environment
win10，chrome:69.0.3497.100（正式版本） （64 位），vue@2.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xl5z1vnv7p)

### Steps to reproduce
form放入drawer中，formItem通过fieldDecoratorId绑定数据后，中文输入法下，输入框会多输入很多字母，但是如果form不放在drawer中，就可以正常使用

### What is expected?
可以正常使用中文输入法

### What is actually happening?
中文输入法下，输入框会多输入很多字母

**Comment by tangjinzhou** [comment]
please update to 1.1.6
