### ISSUE TITLE
Unknown custom element: <a-pagination> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### ISSUE THREAD

**Issue by temuiphone** [vueComponent/ant-design-vue#2095]
请问我直接使用，a-pagination 的分页组件的时候，为什么会报错。

Unknown custom element: <a-pagination> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

`[Vue warn]: Unknown custom element: <a-pagination> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <PaginationView> at src/views/customerManage/components/PaginationView.vue
       <Index> at src/views/customerManage/index.vue
         <PageView> at src/layouts/PageView.vue
           <RouteView> at src/layouts/RouteView.vue
             <Anonymous>
               <ALayoutContent>
                 <Anonymous>
                   <ALayout>
                     <Anonymous>
                       <ALayout>
                         <BasicLayout> at src/layouts/BasicLayout.vue
                           <ALocaleProvider>
                             <Anonymous>
                               <AConfigProvider>
                                 <App> at src/App.vue
                                   <Root>`

**Comment by xueyanisep** [comment]
我也遇到一样的问题了，我用的a-slider组件，也是同样报错，求问怎么解决的？

**Comment by noodv** [comment]
这么大的BUG，开发你们妈逼呢？写个vue-antdesign出来坑老子吗，草你妈，早知道老子用element了。
