### ISSUE TITLE
下拉框选择器（SELECT）的@change  和 @select 触发条件没有区别，选择同一条数据的时候select 不会触发

### ISSUE THREAD

**Issue by huoshidehua** [vueComponent/ant-design-vue#2096]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
windows chrome vue version 2.x

### Reproduction link
[http://47.103.92.187:8004/](http://47.103.92.187:8004/)

### Steps to reproduce
下拉框选择的时候 change 和 select 触发条件没区别

### What is expected?
怎么解决

### What is actually happening?
选择同一条下拉框 option的 时候无法触发@select

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/79427138-c3177c00-7ff6-11ea-9560-6b927193a5a7.png)

**Comment by huoshidehua** [comment]
在我 理解中 select事件 应该是 无论有没有改变值只要点击了 option 就会触发，而change 事件应该是选中 不一样的option 的时候触发，而我测试过程中 发现 单两次选择的option 一样的时候 在第二次选中时@select 不会触发

**Comment by tangjinzhou** [comment]
如果你需要不管有没有选中都触发事件，你应该选择 click 事件

**Comment by huoshidehua** [comment]
![image](https://user-images.githubusercontent.com/8519297/79430674-44294000-8004-11ea-9e00-611cef78d1f7.png)
不是“不管有没有选中”，而是前后两次选中的一样不一样

**Comment by wangjun521** [comment]
这个change事件基本都是需要你自己加下判断的 如果你选了之前选过的 那就return 一下  个人以为这个功能ui库应该完全没必要添加

**Comment by huoshidehua** [comment]
那就真不知道@select 有什么用了
