### ISSUE TITLE
Slider 滑动条垂直状态时 刻度与圆点未重合圆点与刻度未重合

### ISSUE THREAD

**Issue by PanStar** [vueComponent/ant-design-vue#2097]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Chrome 81.0.4044.92

### Reproduction link
[https://www.antdv.com/components/slider-cn/#components-slider-demo-vertical](https://www.antdv.com/components/slider-cn/#components-slider-demo-vertical)

### Steps to reproduce
[https://www.antdv.com/components/slider-cn/#components-slider-demo-vertical](https://www.antdv.com/components/slider-cn/#components-slider-demo-vertical)

### What is expected?
刻度与圆点重合，与水平时一样

### What is actually happening?
刻度与圆点未重合

**Comment by sendya** [comment]
ref #2098
