### ISSUE TITLE
表格table伸缩列宽度调整之后会超出整个表格宽度

### ISSUE THREAD

**Issue by rongxingsun** [vueComponent/ant-design-vue#2100]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
火狐浏览器

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
伸缩列拉长时超出表格宽度

### What is expected?
伸缩列时拉长列宽度表格出现横向滚动条

### What is actually happening?
火狐浏览器拉长列宽度时会超出表格宽度
![图片](https://user-images.githubusercontent.com/12825624/79452881-6d08ff80-801b-11ea-960c-5c14fe6fccda.png)

**Comment by celizi** [comment]
你要固定表格宽度，保留一列（备注列）长度不设定

增加下面样式  去掉一直显示的滚动条
	#body-table .ant-table-body{
		overflow:auto !important;
	}
	#body-table .ant-table-header{
		overflow:hidden !important;
		margin-bottom: 0px !important;
	}
然后出现横向滚动条超出问题，需要动态配置标题div的宽度为你的固定宽度+浏览器滚动条宽度（大于也可以，自动会对齐）
this.$refs.bodyTable.querySelectorAll('.ant-table-header .ant-table-fixed')[0].style = "width: "+1250 +"px"

**Comment by rongxingsun** [comment]
> 
> 
> 你要固定表格宽度，保留一列（备注列）长度不设定
> 
> 增加下面样式 去掉一直显示的滚动条
> #body-table .ant-table-body{
> overflow:auto !important;
> }
> #body-table .ant-table-header{
> overflow:hidden !important;
> margin-bottom: 0px !important;
> }
> 然后出现横向滚动条超出问题，需要动态配置标题div的宽度为你的固定宽度+浏览器滚动条宽度（大于也可以，自动会对齐）
> this.$refs.bodyTable.querySelectorAll('.ant-table-header .ant-table-fixed')[0].style = "width: "+1250 +"px"

没有效果，火狐浏览还是一样这个问题
