### ISSUE TITLE
tree select 组件的参数 showCheckedStrategy 值不起作用，选择SHOW_ALL还是显示子节点

### ISSUE THREAD

**Issue by glxe** [vueComponent/ant-design-vue#2113]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
mac chrome vue2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-5z9pl?file=/src/App.vue)

### Steps to reproduce
使用tree select 组件来选择地区，但是参数 showCheckedStrategy 值不起作用，选择SHOW_ALL还是只显示子节点

### What is expected?
showCheckedStrategy   选择对应的值却无效果

### What is actually happening?
showCheckedStrategy   选择对应的值却无效果

**Comment by jzyzxx** [comment]
我也遇到同样的问题

**Comment by glxe** [comment]
@jzyzxx   一直在等待回复呢

**Comment by xrkffgg** [comment]
https://antdv.com/components/tree-select-cn/#components-tree-select-demo-checkable

仔细看一下这个 🌰

**Comment by laura233** [comment]
我也遇到了同样的问题

**Comment by laura233** [comment]
@xrkffgg https://antdv.com/components/tree-select-cn/#components-tree-select-demo-checkable这里没有showCheckedStrategy使用的demo，设置showCheckedStrategy="SHOW_ALL"还是只显示子节点

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/91270743-b9273600-e7ab-11ea-9328-7585a12104af.png)

**Comment by laura233** [comment]
<template>
  <a-tree-select
    v-model="value"
    style="width: 100%"
    :tree-data="treeData"
    tree-checkable
    :show-checked-strategy="SHOW_ALL"
    search-placeholder="Please select"
  />
</template>

<script>
import { TreeSelect } from 'ant-design-vue';
const SHOW_ALL= TreeSelect.SHOW_ALL;

const treeData = [
  {
    title: 'Node1',
    value: '0-0',
    key: '0-0',
    children: [
      {
        title: 'Child Node1',
        value: '0-0-0',
        key: '0-0-0',
      },
    ],
  },
  {
    title: 'Node2',
    value: '0-1',
    key: '0-1',
    children: [
      {
        title: 'Child Node3',
        value: '0-1-0',
        key: '0-1-0',
        disabled: true,
      },
      {
        title: 'Child Node4',
        value: '0-1-1',
        key: '0-1-1',
      },
      {
        title: 'Child Node5',
        value: '0-1-2',
        key: '0-1-2',
      },
    ],
  },
];
export default {
  data() {
    return {
      value: ['0-0-0'],
      treeData,
      SHOW_ALL,
    };
  },
};
</script>

请问这样写有什么地方不对吗，效果还是只显示子节点 呢@xrkffgg

**Comment by laura233** [comment]
`import { TreeSelect } from 'ant-design-vue';`
`const SHOW_ALL = TreeSelect.SHOW_ALL;`
`<a-tree-select
      v-model="value"
      style="width: 100%"
      :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
      :tree-data="regionTree"
      @select="handleSelect"
      :show-checked-strategy="SHOW_ALL"
      placeholder="选择区域"
      tree-default-expand-all
    >`
`data: function () {
    return {
      regionTree: [],
      SHOW_ALL
    }
  },`

这样还是只显示子节点，请问还有什么地方有问题吗 @xrkffgg

**Comment by xrkffgg** [comment]
你用这个提供一个复现 https://codesandbox.io/s/vue-antd-template-5z9pl?file=/src/App.vue 我看看

**Comment by laura233** [comment]
您提供的demo已经是SHOW_ALL了，右边的下拉框不也是没展示父节点吗

**Comment by xrkffgg** [comment]
我是用的楼主的链接。其实这个  `show-checked-strategy` 是需要 `tree-checkable` 的。

**Comment by laura233** [comment]
好吧，我加tree-checkable试了下，展示的是当前选中节点及其下面所有的子节点，并不是选中节点及其父节点

**Comment by glxe** [comment]
这个玩意我试过很多次，可是并没有得要想要的结果。还是说这个SHOW_ALL本来就是这个效果呢？不是我们所理解的呢。

**Comment by buqiyuan** [comment]
![Uploading image.png…]()
自己动手丰衣足食

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/99926815-efaa2800-2d7d-11eb-8b01-c61f482dd634.png)
```
 // 选择节点
    const treeSelect = (value,node,extra) => {
      let currentNode = extra.triggerNode
      let str = ''
      while (currentNode.dataRef.pId != 0) {
        str += currentNode.title + ' / '
        currentNode = currentNode.vcTreeNode
      }
      str += currentNode.title
      treeSelectRef.value.$el.parentElement.querySelector('.ant-select-selection-selected-value').textContent = str.split(' / ').reverse().join(' / ')
    }
```
自己动手丰衣足食

**Comment by Mfweb** [comment]
至今未解决

**Comment by jinxinkai** [comment]
至今未解决 +1

**Comment by laravuel** [comment]
至今未解决 +1

**Comment by 948489458** [comment]
> treeSelectRef

是什么

**Comment by williamwang2013** [comment]
> 至今未解决 +1
我的问题类似，我已通过后台方式处理解决。
我的环境是react+ ant design 3.26.7，要实现给菜单树赋权的效果，用treeselect ,
  <TreeSelect
              style={{ width: '100%' }}
              dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
              treeData={roleTreeList}
              treeCheckable="true"
              showCheckedStrategy={SHOW_ALL}
              placeholder="请设置菜单权限"
              onChange={onTreeChange}
            />,
假设某个1级菜单目录-系统管理下，有3个子菜单，用户管理、角色管理、菜单管理，用treeselect赋权时，我只选了用户管理和角色管理2个子菜单，实际上的treeselect values中应该要包含父级菜单系统管理的id的，但是因为系统管理下的3个子菜单没有全部选中，即使 showCheckedStrategy={SHOW_ALL}，在获取treeselect value时是拿不到系统管理的key值的。
我通过后台来解决的，我的解决方式如下：
    1.前台没办法通过组件来拿到系统管理的key值，前台传值不变
    2.后台拿到前台传过来的所有key值，递归查找所有父节点后，跟前台传值做并集后做唯一值筛选。这样保证可以拿到所有前台漏掉的父节点值。入库时的数据不会有问题
    3.这样会导致一个新问题出现，就是由于系统管理父节点的值入库了，在treeselect上明明应该是只显示系统管理和用户管理、角色管理两个子菜单的，但是如果从库里面拿数据的话，系统管理的key默认也是选中的，会变成了系统管理下的3个子菜单都是选中的状态
    4. 第3步中的问题我是这么处理的，数据库中存入了系统管理的节点id,但是在treeselect绑定values值时，过滤掉这些父节点的key值，具体sql类似如下，我这里是角色赋权，在角色创建时指定角色有权限操作的菜单树。角色表上加一个字段menuCheckStrictly，默认为true。然后入库时父节点key值即使入库，再取数据库值绑定到treeselect时，由于角色menuCheckStrictly为true，会过滤掉这些父节点key值。
    
        select m.menu_id
		from sys_menu m
            left join sys_role_menu rm on m.menu_id = rm.menu_id
        where rm.role_id = #{roleId}
            <if test="menuCheckStrictly">
              and m.menu_id not in (select m.parent_id from sys_menu m inner join sys_role_menu rm on m.menu_id = rm.menu_id and rm.role_id = #{roleId})
            </if>
		order by m.parent_id, m.order_num
     整个操作，已经测试成功，基本达到我的要求。

**Comment by williamwang2013** [comment]
我的问题类似，我已通过后台方式处理解决。
我的环境是react+ ant design 3.26.7，要实现给菜单树赋权的效果，用treeselect ,
  <TreeSelect
              style={{ width: '100%' }}
              dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
              treeData={roleTreeList}
              treeCheckable="true"
              showCheckedStrategy={SHOW_ALL}
              placeholder="请设置菜单权限"
              onChange={onTreeChange}
            />,
假设某个1级菜单目录-系统管理下，有3个子菜单，用户管理、角色管理、菜单管理，用treeselect赋权时，我只选了用户管理和角色管理2个子菜单，实际上的treeselect values中应该要包含父级菜单系统管理的id的，但是因为系统管理下的3个子菜单没有全部选中，即使 showCheckedStrategy={SHOW_ALL}，在获取treeselect value时是拿不到系统管理的key值的。
我通过后台来解决的，我的解决方式如下：
    1.前台没办法通过组件来拿到系统管理的key值，前台传值不变
    2.后台拿到前台传过来的所有key值，递归查找所有父节点后，跟前台传值做并集后做唯一值筛选。这样保证可以拿到所有前台漏掉的父节点值。入库时的数据不会有问题
    3.这样会导致一个新问题出现，就是由于系统管理父节点的值入库了，在treeselect上明明应该是只显示系统管理和用户管理、角色管理两个子菜单的，但是如果从库里面拿数据的话，系统管理的key默认也是选中的，会变成了系统管理下的3个子菜单都是选中的状态
    4. 第3步中的问题我是这么处理的，数据库中存入了系统管理的节点id,但是在treeselect绑定values值时，过滤掉这些父节点的key值，具体sql类似如下，我这里是角色赋权，在角色创建时指定角色有权限操作的菜单树。角色表上加一个字段menuCheckStrictly，默认为true。然后入库时父节点key值即使入库，再取数据库值绑定到treeselect时，由于角色menuCheckStrictly为true，会过滤掉这些父节点key值。
    
        select m.menu_id
		from sys_menu m
            left join sys_role_menu rm on m.menu_id = rm.menu_id
        where rm.role_id = #{roleId}
            <if test="menuCheckStrictly">
              and m.menu_id not in (select m.parent_id from sys_menu m inner join sys_role_menu rm on m.menu_id = rm.menu_id and rm.role_id = #{roleId})
            </if>
		order by m.parent_id, m.order_num
     整个操作，已经测试成功，基本达到我的要求。

**Comment by huifang-jiang** [comment]
可设置**treeNodeLabelProp**属性
```
<template>
    <a-tree-select  :tree-data="treeData"  treeNodeLabelProp="**fullTitle**" />
</template>
<script>
export default {
     setup() {
         return {
              treeData: [
                   {
                      value: '1',
                      title: '1月',
                      fullTitle: '1月',
                      children: [
                         {
                            value: '1-1',
                            title: '1号',
                            **_fullTitle: '1月 / 1号',   // key值可自定义，内容自行拼接，选中框将展示此条数据_**
                         },
                         {
                            value: '1-1',
                            title: '2号',
                            fullTitle: '1月 / 2号',
                         }
                     ]
                  }
              ]
         }
     }
}
</script>
```
