### ISSUE TITLE
疫情期间网站很慢出来，一直loading然后就空白

### ISSUE THREAD

**Issue by geoffreylzf** [vueComponent/ant-design-vue#2114]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
offical site

### Reproduction link
[https://www.antdv.com/components/table/](https://www.antdv.com/components/table/)

### Steps to reproduce
official site

### What is expected?
load as usual

### What is actually happening?
website keep loading until show white page

**Comment by tangjinzhou** [comment]
现在依然？

**Comment by geoffreylzf** [comment]
现在好多了，第一次load要一分钟多，才出来，过后须要5秒左右
