### ISSUE TITLE
How to add to nuxt ?

### ISSUE THREAD

**Issue by mapsgeek** [vueComponent/ant-design-vue#212]
how can i use the library with nuxt ?

**Comment by wangxueliang** [comment]
submited pull request of create-nuxt-app [https://github.com/nuxt/create-nuxt-app/pull/110]

**Comment by axu6705** [comment]
@wangxueliang How to  importing components on demand in nuxt.

**Comment by wangxueliang** [comment]
Configuration is ok, check if you install babel-plugin-import?

**Comment by axu6705** [comment]
@wangxueliang 装了的
```js
"babel-plugin-import": "^1.11.0"
```

**Comment by mapsgeek** [comment]
@axu6705 yes as i remember, but not for the css , i stopped the transition to vue for a while since that post so i don't remember exactly, but you will have to fiddle around with the importing of individual components vs importing the whole library, i had to keep running webpack bundle analyzer to see which is a good importing.

this was mostly what i followed but sorry i can't remember to be more precious
https://vuecomponent.github.io/ant-design-vue/docs/vue/getting-started/#Import-on-Demand

**Comment by hagemann** [comment]
You should remove `style: true` and import .less files in the CSS section instead. It works. See @MaZhaolin’s comment: https://github.com/vueComponent/ant-design-vue/issues/234#issuecomment-433333431

**Comment by TariikHr** [comment]
@axu6705 did you found a solution for importing antd components on demand ?

**Comment by TariikHr** [comment]
@axu6705 did you found a solution for importing antd components on demand ?

**Comment by axu6705** [comment]
> @axu6705 did you found a solution for importing antd components on demand ?

No, I gave up, I use antd

**Comment by TariikHr** [comment]
@axu6705 Forgive my question...but antd isn't === Ant Design Vue ?? Because Nuxtjs When generate ant design vue as a plugin from the create-nuxt-app the plugin name is antd + Vue.use(Antd) How did you managed to use on demand antd please ?

**Comment by axu6705** [comment]
> @axu6705 Forgive my question...but antd isn't === Ant Design Vue ?? Because Nuxtjs When generate ant design vue as a plugin from the create-nuxt-app the plugin name is antd + Vue.use(Antd) How did you managed to use on demand antd please ?

I changed to react.
