### ISSUE TITLE
1.5.0版本以后的ant-demo的submodule获取不了和component里面的demo文件夹没有了

### ISSUE THREAD

**Issue by airkingZy** [vueComponent/ant-design-vue#2120]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1.5.0版本后，移除了site命令，增加了ant-demo的submodule，使用submodule会报错（ERROR: Repository not found.
fatal: Could not read from remote repository.
），获取仓库本地运行，发现component下以前的demo文件夹移除了，无法看到和以前版本（1.4.12）一样的页面实例和对应的md文档描述了。

### What does the proposed API look like?
能否提供一个可以本地运行的demo例，类似1.4.12版本和以前一样的site命令

**Comment by tangjinzhou** [comment]
以后仅提供线上版本示例
