### ISSUE TITLE
Inconsistent behavior when setting status or color in Badge

### ISSUE THREAD

**Issue by duckness** [vueComponent/ant-design-vue#2121]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues) of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.3

### Environment
Windows 10, Chrome 80.0.3987.163, Vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-d3cjv)

### Steps to reproduce
Set `dot` in `a-badge` without setting `color` or `status`.  
Now set `dot` and set `color` or `status`.

### What is expected?
1. Badge is in the same location
2. Badge disappears if `dot` is set to `false`

### What is actually happening?
1. Badge is slightly higher when `color` or `status` is set
2. Badge remains there even if `dot` is set to `false`

![SQsS3cIi7T](https://user-images.githubusercontent.com/6380270/79729685-5f58c000-8322-11ea-9e46-5d4ce2669b7b.gif)

**Comment by tangjinzhou** [comment]
I can solve the first problem;
But the second problem cannot be solved, the default value of dot is false, but you can use v-show to solve it
