### ISSUE TITLE
FormModel tsx语法糖双向绑定 validate内部获取不到this.model

### ISSUE THREAD

**Issue by easeava** [vueComponent/ant-design-vue#2122]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
macOS 10.15.5 、Chrome 81.0.4044.113、Vue 3.1.3

### Reproduction link
[https://github.com/easeava/antd-form-model/blob/master/src/App.tsx](https://github.com/easeava/antd-form-model/blob/master/src/App.tsx)

### Steps to reproduce
输入框输入姓名，触发validate验证表单,提示Warning: [antdv: FormModel] model is required for resetFields to work.

### What is expected?
输入框输入姓名触发验证通过

### What is actually happening?
tsx语法糖下触发validate可以通过验证

---
FormModel内props双向绑定model的命名修改成value,内部获取this.value验证规则通过

**Comment by tangjinzhou** [comment]
https://github.com/easeava/antd-form-model/pull/1/files

**Comment by easeava** [comment]
> https://github.com/easeava/antd-form-model/pull/1/files

尝试过这种写法,语法糖还是解析成双向绑定
`[Vue warn]: Invalid handler for event "input": got undefined`
