### ISSUE TITLE
可伸缩列不好用

### ISSUE THREAD

**Issue by woshixuyuguo** [vueComponent/ant-design-vue#2124]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
Chrome

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-resizable-column](https://www.antdv.com/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
复制代码

### What is expected?
可拖拽

### What is actually happening?
有问题

**Comment by tangjinzhou** [comment]
欢迎贡献一个好用的 😄
