### ISSUE TITLE
插槽form无法编辑

### ISSUE THREAD

**Issue by zhangshengbiao** [vueComponent/ant-design-vue#2125]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
Chrome  vue2.6x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-r4rre?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-r4rre?file=/src/App.vue

### What is expected?
插槽中使用v-slot表单可以编辑输入

### What is actually happening?
插槽中使用v-slot表单无法编辑，使用以前的则可以编辑，如使用vue版本2.5X则可以，2.6x则无法编辑。

**Comment by tangjinzhou** [comment]
可以使用 formModel 组件，在Vue2.6里，form组件不能通过插槽来使用
在 2.X大版本中会重构form解决该类问题
