### ISSUE TITLE
无法单独使用 Message 组件

### ISSUE THREAD

**Issue by falstack** [vueComponent/ant-design-vue#213]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
单独引入 Message 组件

### What does the proposed API look like?
目前存在的问题：
1. message 的首字母不是大写，很郁闷
2. message 要单独引入，若直接引入 style.css，会包含全局样式，如果引入 index.less，因为项目不支持 less 而报错，所以只能把 style.css 复制到项目里
3. 即使单独把 style 复制到项目里，也会因为没有引入 icon 而无法显示图标

**Comment by Martin-Bai** [comment]
可以使用
babel-plugin-import 插件，
然后使用
import { message } from 'ant-design-vue';
就可以在js中直接使用了

**Comment by falstack** [comment]
文档上说这个方式会引入基础样式，但是我并不想使用基础样式，因为不是一个新项目

![image](https://user-images.githubusercontent.com/16357724/46513542-988a2600-c88b-11e8-8a70-cd193b418d81.png)

**Comment by tangjinzhou** [comment]
import message from 'ant-design-vue/lib/message '
