### ISSUE TITLE
table控件如果一页数据数量超过300条下一页和选中操作都会卡顿至少1秒以上

### ISSUE THREAD

**Issue by wangfly6645** [vueComponent/ant-design-vue#2132]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
window7 ,Google Chrome版本 81.0.4044.113（正式版本）,vue2.5.15以上版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-tableceshiyongli-lrnze)

### Steps to reproduce
打开列表页面，选择分页300/page，然后点击第2页，或选中列表选项

### What is expected?
如果选择下一页，列表应该立即显示加载中状态；如果选中某行，应该立即显示成选中状态

### What is actually happening?
点击下一页则会先卡顿1到2秒中，然后再显示加载下一页数据，选中某一行也同样会先卡顿1到2秒

**Comment by wzohxia** [comment]
100条左右就已经有卡顿，还有select数据多了也一样会卡

**Comment by gerrardpan** [comment]
+1，200多条的时候全选至少会卡2秒左右，不知道什么时候能解决这个问题。好像antd react 4.0的有优化，不过没用过不知道什么情况

**Comment by hzyyy** [comment]
pageSize 也太多了吧

**Comment by w306621759** [comment]
哎，这些操作都会导致整个table重新render，所以会卡
我暂时把分页从table里分离出来了。分页点击不卡了，可是选中还是卡
