### ISSUE TITLE
textarea设置minRows拖动大小卡顿

### ISSUE THREAD

**Issue by bailihuiyue** [vueComponent/ant-design-vue#2134]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.3

### Environment
firefox 75.0 (64 位), win10 x64, ant版本1.5.3

### Reproduction link
[https://www.antdv.com/components/input-cn/](https://www.antdv.com/components/input-cn/)

### Steps to reproduce
<a-textarea
placeholder="Autosize height with minimum and maximum number of lines"
:autoSize="{ minRows: 2, maxRows: 6 }"
/>
1.按照官网的代码复制
2.这样设置之后拖动textarea右下角的大小图标,拖动不流畅,一次只能拖动几px,chrome下正常,官网也有这个bug

### What is expected?
正常拖动

### What is actually happening?
无法正常拖动大小

**Comment by freedomlang** [comment]
https://github.com/ant-design/ant-design/issues/22648
