### ISSUE TITLE
typescript tsx

### ISSUE THREAD

**Issue by ZhaoRd** [vueComponent/ant-design-vue#214]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用  vue cli 3.0  和  typescript，组件 table 的 customRender 不能使用！
报错信息：
Error in data(): "TypeError: Cannot read property '$createElement' of undefined"

### What does the proposed API look like?
```
{
title: '商品编号',
dataIndex: 'id',
key: 'id',
customRender: (text: any, row: any, index: any/**/) => {

return <a href=""></a>;

},
},
}
```

**Comment by YamadaAoi** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 使用 vue cli 3.0 和 typescript，组件 table 的 customRender 不能使用！
> 报错信息：
> Error in data(): "TypeError: Cannot read property '$createElement' of undefined"
> 
> ### What does the proposed API look like?
> ```
> {
> title: '商品编号',
> dataIndex: 'id',
> key: 'id',
> customRender: (text: any, row: any, index: any/**/) => {
> 
> return <a href=""></a>;
> 
> },
> },
> }
> ```

请问这个问题你解决了吗
