### ISSUE TITLE
1.5.3版本Table没有内容的列，表格线会断层

### ISSUE THREAD

**Issue by mx4g** [vueComponent/ant-design-vue#2146]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.3

### Environment
@vue/cli 4.0.5

        

Demo:
[antd-demo.zip](https://github.com/vueComponent/ant-design-vue/files/4526035/antd-demo.zip)
Pic:
![1 5 3版本Table没有内容的列，线会断层](https://user-images.githubusercontent.com/7499986/80163178-e69a8200-8607-11ea-9873-d56292438379.jpg)

没有内容的列，表格线会断层：
@tangjinzhou @JinPengGeng

**Comment by mx4g** [comment]
@tangjinzhou  @JinPengGeng

**Comment by wangxueliang** [comment]
你的环境是？我在mac上运行你的代码，没发现这个问题（chorme  safari ff）都没问题

**Comment by mx4g** [comment]
> 你的环境是？我在mac上运行你的代码，没发现这个问题（chorme safari ff）都没问题

我的是win10家庭版

**Comment by JinPengGeng** [comment]
![图片](https://user-images.githubusercontent.com/36217715/80669283-f8d06080-8ade-11ea-8829-18a54e9809b3.png)
 没有问题
![图片](https://user-images.githubusercontent.com/36217715/80670782-ce80a200-8ae2-11ea-89c2-1e8fe6d37ba7.png)

**Comment by mx4g** [comment]
> ![图片](https://user-images.githubusercontent.com/36217715/80669283-f8d06080-8ade-11ea-8829-18a54e9809b3.png)
> 没有问题
> ![图片](https://user-images.githubusercontent.com/36217715/80670782-ce80a200-8ae2-11ea-89c2-1e8fe6d37ba7.png)



你有没有配到这种情况，设置了固定的长度，会出现这种情况

![image](https://user-images.githubusercontent.com/7499986/81377513-39138c80-9138-11ea-8466-aca70fdfbe4f.png)

**Comment by JinPengGeng** [comment]
> > ![图片](https://user-images.githubusercontent.com/36217715/80669283-f8d06080-8ade-11ea-8829-18a54e9809b3.png)
> > 没有问题
> > ![图片](https://user-images.githubusercontent.com/36217715/80670782-ce80a200-8ae2-11ea-89c2-1e8fe6d37ba7.png)
> 
> 你有没有遇到这种情况，设置了固定的长度，会出现这种情况
> 
> ![image](https://user-images.githubusercontent.com/7499986/81377513-39138c80-9138-11ea-8466-aca70fdfbe4f.png)

之前好像碰到过一回，后来都改成横向滚动条了，就没问题了，或者可以设置文字显示缩略，我记得API有这个属性

**Comment by mx4g** [comment]
> > > ![图片](https://user-images.githubusercontent.com/36217715/80669283-f8d06080-8ade-11ea-8829-18a54e9809b3.png)
> > > 没有问题
> > > ![图片](https://user-images.githubusercontent.com/36217715/80670782-ce80a200-8ae2-11ea-89c2-1e8fe6d37ba7.png)
> > 
> > 
> > 你有没有遇到这种情况，设置了固定的长度，会出现这种情况
> > ![image](https://user-images.githubusercontent.com/7499986/81377513-39138c80-9138-11ea-8466-aca70fdfbe4f.png)
> 
> 之前好像碰到过一回，后来都改成横向滚动条了，就没问题了，或者可以设置文字显示缩略，我记得API有这个属性
好的，谢谢！

**Comment by mx4g** [comment]
> 你的环境是？我在mac上运行你的代码，没发现这个问题（chorme safari ff）都没问题

你好，请问怎么隐藏这个显示快呢？像elementUI是用show-message的属性，我在ant里面的文档里面找不到，请问该怎么做呢？
![image](https://user-images.githubusercontent.com/7499986/85495794-c9852e00-b60d-11ea-86a4-095e6271a4c6.png)
