### ISSUE TITLE
日期组件不支持绑定字符串类型的 value ？

### ISSUE THREAD

**Issue by liamwang** [vueComponent/ant-design-vue#2147]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
每次手动转换成 moment 对象来使用 v-model，太麻烦太不友好了。

### What does the proposed API look like?
应该像 element-ui 一样支持绑定字符串类型的 value。

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/commit/ed528e68b74da7eff8b8af7242197b05d5f8c5f9
