### ISSUE TITLE
dependencies：ismobilejs 打包问题

### ISSUE THREAD

**Issue by kouxin** [vueComponent/ant-design-vue#2149]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
import格式为es2015，vuecli默认打包未包含此文件，不兼容ie9

### What does the proposed API look like?
build报错

**Comment by tangjinzhou** [comment]
升级
