### ISSUE TITLE
Windows Firefox 使用搜狗输入法输入中文，第一次输入结果为空

### ISSUE THREAD

**Issue by AmmyXu** [vueComponent/ant-design-vue#2151]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
windows10,Firefox 75.0,vue2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-chatterjee-0cu2h?file=/src/App.vue)

### Steps to reproduce
1. vue-cli3生成的模板
2. 全量加载ant-design-vue组件
3. 在form表单组件官方第一个demo例子上加上tabs组件
4. windows10用firefox浏览器访问
5. 输入法切换成搜狗中文输入法（微软输入法没有问题）
6. 在input组件中输入中文
7. 第一次输入失败，输入框为空，再次输入成功

### What is expected?
在windows， firefox中使用搜狗输入法可以正确输入中文

### What is actually happening?
在windows， firefox中使用搜狗输入法第一次输入中文，输入框中结果为空

---
测试例子是基于antd@1.5.3版本

**Comment by tangjinzhou** [comment]
不加 tabs 也没问题  ？

**Comment by AmmyXu** [comment]
是的

**Comment by AmmyXu** [comment]
我们项目目前是基于antd@1.4.12版本，请问对于这个问题，在这个版本可以提供一个兼容方案么

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/80448956-71ed7d80-8950-11ea-91eb-5859ffe92d57.png)
![image](https://user-images.githubusercontent.com/6937879/80448967-79148b80-8950-11ea-844d-2b7fe43be831.png)
所以到底是哪个版本  升级下试试？ 没有破坏性更新，可以直接升级

**Comment by AmmyXu** [comment]
最新的版本也是有问题的，你们有解决方案了么？

**Comment by AmmyXu** [comment]
我们的项目是基于1.4.12版本的，发现问题之后，试过最新版本，也是有问题

我们是想问在不升级版本的前提下，在1.4.12版本下是否有什么兼容方案，因为升级需要一定的回归和测试成本

**Comment by AmmyXu** [comment]
上面提供的复现例子，是基于最新版本1.5.3

**Comment by jy-js** [comment]
![image](https://user-images.githubusercontent.com/12868934/80867027-8d47e800-8cc4-11ea-8612-533a60a28b31.png)
ScrollableTabBarNode.jsx 把updated钩子里的nextTick改成setTimeout可以fix, 猜测是firefox里事件顺序的问题，如果再细看是updated钩子触发的方法getScrollWH会去获取scrollWidth,触发了recalcuate style, 注释掉getScrollWH是正常了的。。
@tangjinzhou

**Comment by thorn929** [comment]
火狐版本问题，升级一下就好了

**Comment by AmmyXu** [comment]
Is this problem solved?
