### ISSUE TITLE
After modal opened, scroll bar vanish.

### ISSUE THREAD

**Issue by xhxhxhxh** [vueComponent/ant-design-vue#2162]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
none

### Reproduction link
[https://www.9mankid.com/home](https://www.9mankid.com/home)

### Steps to reproduce
After modal opened, scroll bar vanish.

### What is expected?
I hope the modal component add a property to set the body element style.

### What is actually happening?
After modal opened, modal component add a style ```position: relative; width: calc(100% - 17px); overflow: hidden;``` to  body element.
If my page have other elements which also have style ```position: fixed```, After modal opened, those element's position will change.

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/80678023-a72ed280-8aec-11ea-9817-20396a77dc27.png)
only find `overflow: hidden`

**Comment by xhxhxhxh** [comment]
![}2`99UV(E`VR0716Q91OW1I](https://user-images.githubusercontent.com/46396186/80678723-135e0600-8aee-11ea-974b-56fcd4c92a06.png)
find in Official website

**Comment by 421918285** [comment]
I also have this problem

**Comment by iczer** [comment]
+1
