### ISSUE TITLE
tabs组件异步加载时会默认选中第二项

### ISSUE THREAD

**Issue by TioJS** [vueComponent/ant-design-vue#2167]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
windows10@1909,chrome@81.0.4044.122,vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-cherry-qhd8n)

### Steps to reproduce
已提供沙盒复现：
https://codesandbox.io/s/vibrant-cherry-qhd8n

### What is expected?
按defaultActiveKey属性选中对应的tab

### What is actually happening?
选中了第二个tab

**Comment by AmmyXu** [comment]
![image](https://user-images.githubusercontent.com/29430746/80450005-1d97cd00-8953-11ea-85cc-0fe900b4a60e.png)
key要用string类型吧，key转成string就不会有问题了

**Comment by TioJS** [comment]
> ![image](https://user-images.githubusercontent.com/29430746/80450005-1d97cd00-8953-11ea-85cc-0fe900b4a60e.png)
> key要用string类型吧，key转成string就不会有问题了

确实是这个问题，感谢指正！
