### ISSUE TITLE
tree组件官方示例bug  Tree可搜索示例代码搜索问题

### ISSUE THREAD

**Issue by encountermm** [vueComponent/ant-design-vue#2168]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
win10 chrome vue2.6

### Reproduction link
[https://www.antdv.com/components/tree-cn/#components-tree-demo-searchable ](https://www.antdv.com/components/tree-cn/#components-tree-demo-searchable )

### Steps to reproduce
https://www.antdv.com/components/tree-cn/#components-tree-demo-searchable   Tree可搜索示例代码，由于key与title一致，所以不会出现问题

### What is expected?
generateList  方法汇总，title属性赋值为key，此处应该赋值为node.title
onChange 方法中，if (item.key.indexOf(value) > -1) {return getParentKey(item.key, gData);} 应该为if (item.title.indexOf(value) > -1) {return getParentKey(item.key, gData);}

### What is actually happening?
示例代码 属性写错了

**Comment by wmo123** [comment]
我也发现了,所以当title和key不同时,搜索功能就失效了

**Comment by wmo123** [comment]
@encountermm 我把这两处改完,搜索功能还是有问题,请问你可以正常实现搜索功能吗?
