### ISSUE TITLE
Cannot read property 'onKeyDown' of undefined when key pressed on Select

### ISSUE THREAD

**Issue by t-w-e-n** [vueComponent/ant-design-vue#217]
### Steps to reproduce
Type anything on Select with search enabled, multiple or tags mode.

### Reproduction link
https://vuecomponent.github.io/ant-design-vue/components/select/#components-select-demo-search-box

**Comment by Xzillion** [comment]
I encountered the same problem when I used component autocomplete

**Comment by Xzillion** [comment]
The  version 1.1.3 works fine

**Comment by tangjinzhou** [comment]
please update to 1.1.6
