### ISSUE TITLE
穿梭框是否可以使用 Tree 组件作为自定义渲染列表

### ISSUE THREAD

**Issue by wang4978** [vueComponent/ant-design-vue#2172]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
是否可以像react版本里的穿梭框一样使用 Tree 组件作为自定义渲染列表

### What does the proposed API look like?
是否可以像react版本里的穿梭框一样使用 Tree 组件作为自定义渲染列表

**Comment by wangxueliang** [comment]
支持，后续官网demo也会更新
https://codesandbox.io/s/vue-antd-template-2plk8
