### ISSUE TITLE
Empty Component Required Extra Param To Contorl Image View

### ISSUE THREAD

**Issue by kelein** [vueComponent/ant-design-vue#2173]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Simplify to use this compent via only `<a-empty />`, instead of doing extra more things.

Now behavior is too tedious，as following:

```
import { Empty } from 'ant-design-vue'

beforeCreate () {
this.simplify = Empty.PRESENTED_IMAGE_SIMPLE
},

<a-empty :image="simplify" />
```

#### When Use PRESENTED_IMAGE_SIMPLE image

`<a-empty type="simple"  />`

#### When Use Empty.PRESENTED_IMAGE_DEFAULT image

`<a-empty type="default" />`   or  `<a-empty />`

**Comment by tangjinzhou** [comment]
Now the way is more flexible.   you can set image any component
