### ISSUE TITLE
tree树组件的新增、编辑、删除功能

### ISSUE THREAD

**Issue by xuyan66** [vueComponent/ant-design-vue#2174]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
树组件不能动态修改，本身不就是问题吗

### What does the proposed API look like?
去看element ui 文档

**Comment by zly9** [comment]
异步树上可以做新增修改删除并且能够动态的展示，我在树节点select的时候，储存了当前的node,当新增成功后，我会把当前node.dataRef.children=[]置空，然后自己调用一次loadData方法，这可以理解为刷新当前节点，同理修改和删除后我们可以刷新一下父节点就可以了

**Comment by loneyao** [comment]
> node

请问这个新增的方法要怎么写。

**Comment by loneyao** [comment]
> 异步树上可以做新增修改删除并且能够动态的展示，我在树节点select的时候，储存了当前的node,当新增成功后，我会把当前node.dataRef.children=[]置空，然后自己调用一次loadData方法，这可以理解为刷新当前节点，同理修改和删除后我们可以刷新一下父节点就可以了

请问这个新增的方法要怎么写。
