### ISSUE TITLE
Table 设置sortDirections 排序图标不显示

### ISSUE THREAD

**Issue by qutz** [vueComponent/ant-design-vue#2175]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.3

### Environment
1.5.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-z3u6z?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-z3u6z?file=/src/App.vue

### What is expected?
设置sortDirections: ["desc", "asc"],显示排序图标

### What is actually happening?
排序图标不显示

**Comment by zkwolf** [comment]
['descend', 'ascend']
