### ISSUE TITLE
Rate 评分组件 半选模式下 2.6 只显示 2星

### ISSUE THREAD

**Issue by PanStar** [vueComponent/ant-design-vue#2176]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Chrome 81.0.4044.92

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rate-half-howig)

### Steps to reproduce
[https://codesandbox.io/s/rate-half-howig](https://codesandbox.io/s/rate-half-howig)

### What is expected?
when the value is 2.6, which show two and a half stars.

### What is actually happening?
when the value is 2.6, which show two stars.
But when the value is 2.5, which show two and a half stars.

**Comment by tangjinzhou** [comment]
你可以在业务层面去处理此类场景

**Comment by PanStar** [comment]
> 你可以在业务层面去处理此类场景

嗯嗯，好的
