### ISSUE TITLE
table-tree--table的树形数据展示错位问题

### ISSUE THREAD

**Issue by zhuqq1** [vueComponent/ant-design-vue#218]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.6

### Environment
chrome--ant-design-   vue 版本^2.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://wk0z88jq4l.codesandbox.io/)

### Steps to reproduce
在table的columns参数中设置widh;当折叠级别过多的时候引起错位;目测是看度计算引起的问题；

### What is expected?
当递归数据级别过多的时候不要错位---和现在引起错位的原因以及当时的思路(求科普)

### What is actually happening?
当级别过多的时候导致错位

---
修改.ant-table-row-spaced看不见变为display的时候有时候是可以的；有时候却不行；

        

![bug](https://user-images.githubusercontent.com/33542683/46846447-51171300-ce12-11e8-9a12-aed34d58a6d1.jpg
![table-tree](https://user-images.githubusercontent.com/33542683/46846472-61c78900-ce12-11e8-9284-9bc36e8f22df.jpg)
)

**Comment by zhuqq1** [comment]
![tabletree](https://user-images.githubusercontent.com/33542683/46846625-f29e6480-ce12-11e8-89fc-6f1a5956f694.jpg)

**Comment by zhuqq1** [comment]
![bug](https://user-images.githubusercontent.com/33542683/46846631-01851700-ce13-11e8-88f2-970b1a4f4d07.jpg)

**Comment by tangjinzhou** [comment]
宽度不够导致的，建议第一列不要设定宽度或给出足够的宽度，属性数据的展开icon会有一个paddingLeft属性

**Comment by zhuqq1** [comment]
> 宽度不够导致的，建议第一列不要设定宽度或给出足够的宽度，树形table的展开icon会有一个paddingLeft属性

这个不能作为解决方案啊；后台返回数据不可控；用户也可以拖放浏览器窗口大小；都会造成错位的问题；建议可以换行也不要错位啊

**Comment by tangjinzhou** [comment]
这不是换不换行的问题，你写死了宽度，paddingLeft会根据树的层级计算一个值，这个值已经超过你写死的值了。
就算换行，也是数据换行，现在数据有换行，没毛病。
既然数据不可控，首列不固定宽度，让其自适应有什么问题。
再有如果非要固定宽度，那你使用css把paddingLeft强制覆盖掉好了。
