### ISSUE TITLE
document error vue.config.js less options

### ISSUE THREAD

**Issue by yiptsangkin** [vueComponent/ant-design-vue#2180]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
mac chrome vue2.6.11 vue-cli3

### Reproduction link
[https://antdv.com/docs/vue/customize-theme-cn/](https://antdv.com/docs/vue/customize-theme-cn/)

### Steps to reproduce
from =================
// vue.config.js
module.exports = {
css: {
loaderOptions: {
less: {
modifyVars: {
'primary-color': '#1DA57A',
'link-color': '#1DA57A',
'border-radius-base': '2px',
},
javascriptEnabled: true,
},
},
},
};

to =============

module.exports = {
css: {
loaderOptions: {
less: {
lessOptions: {
modifyVars: {
'primary-color': '#1DA57A',
'link-color': '#1DA57A',
'border-radius-base': '2px',
},
javascriptEnabled: true,
}
},
},
},
};

### What is expected?
-

### What is actually happening?
-

**Comment by starkfire** [comment]
Happened to me after updating `less-loader`, but I was able to resolve it by downgrading to `less-loader@5.0.0` instead.

**Comment by starkfire** [comment]
Also had the same vue.config.js file, but had compile errors when I updated `less-loader` to `6.0.0`

```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        javascriptEnabled: true
      }
    }
  }
}
```

```
error  in ./node_modules/ant-design-vue/es/layout/style/index.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):
ValidationError: Invalid options object. Less Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'javascriptEnabled'. These properties are valid:
   object { lessOptions?, prependData?, appendData?, sourceMap? }
    at validate (D:\Users\acer\Desktop\GitHub\project_name\node_modules\schema-utils\dist\validate.js:88:11)
    at Object.lessLoader (D:\Users\acer\Desktop\GitHub\project_name\node_modules\less-loader\dist\index.js:24:28)

 @ ./node_modules/ant-design-vue/es/layout/style/index.less 4:14-207 14:3-18:5 15:22-215
 @ ./node_modules/ant-design-vue/es/layout/style/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.43.250:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

. . .
```

I was able to resolve it by downgrading `less-loader` back to `5.0.0` instead.

```
npm install --save-dev less-loader@5.0.0
```

Might be something to consider for PR https://github.com/vueComponent/ant-design-vue/pull/2150

**Comment by starkfire** [comment]
The same vue.config.js file gave me compile errors when I updated `less-loader` to version `6.0.0`:
```js
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        javascriptEnabled: true
      }
    }
  }
}
```
You can make this work either by downgrading `less-loader` back to `5.0.0`:
```
npm install --save-dev less-loader@5.0.0
```
or you can make this work with the latest version of `less-loader` (`6.0.0`) by moving less-specific options (e.g. `javascriptEnabled`) to `lessOptions` in your vue.config.js file (as indicated from less-loader's 6.0.0 [release notes](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0))
```js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        lessOptions: {
          javascriptEnabled: true
        }
      }
    }
  }
}
```

Might be something to consider for PR https://github.com/vueComponent/ant-design-vue/pull/2150

**Comment by yiptsangkin** [comment]
> The same vue.config.js file gave me compile errors when I updated `less-loader` to version `6.0.0`, which had breaking changes (see [6.0.0 release note](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0))
> 
> ```js
> // vue.config.js
> module.exports = {
>   css: {
>     loaderOptions: {
>       less: {
>         javascriptEnabled: true
>       }
>     }
>   }
> }
> ```
> 
> You can make this work either by downgrading `less-loader` back to `5.0.0`:
> 
> ```
> npm install --save-dev less-loader@5.0.0
> ```
> 
> or by making your vue config work with the latest version of `less-loader` (`6.0.0`) by moving less-specific options (e.g. `javascriptEnabled`) to `lessOptions`
> 
> ```js
> // vue.config.js
> module.exports = {
>   css: {
>     loaderOptions: {
>       less: {
>         lessOptions: {
>           javascriptEnabled: true
>         }
>       }
>     }
>   }
> }
> ```
> 
> Might be something to consider for PR #2150

you are right. buddy

**Comment by liujiaqi455** [comment]
> The same vue.config.js file gave me compile errors when I updated `less-loader` to version `6.0.0`, which had breaking changes (see [6.0.0 release note](https://github.com/webpack-contrib/less-loader/releases/tag/v6.0.0))
> 
> ```js
> // vue.config.js
> module.exports = {
>   css: {
>     loaderOptions: {
>       less: {
>         javascriptEnabled: true
>       }
>     }
>   }
> }
> ```
> 
> You can make this work either by downgrading `less-loader` back to `5.0.0`:
> 
> ```
> npm install --save-dev less-loader@5.0.0
> ```
> 
> or by making your vue config work with the latest version of `less-loader` (`6.0.0`) by moving less-specific options (e.g. `javascriptEnabled`) to `lessOptions`
> 
> ```js
> // vue.config.js
> module.exports = {
>   css: {
>     loaderOptions: {
>       less: {
>         lessOptions: {
>           javascriptEnabled: true
>         }
>       }
>     }
>   }
> }
> ```
> 
> Might be something to consider for PR #2150

yes,work,3q!
