### ISSUE TITLE
Cascader open showSearch，Search in the input box， Prompt wrong： Avoid using non-primitive value as key, use string/number value instead.  found in

### ISSUE THREAD

**Issue by xiaosheng222** [vueComponent/ant-design-vue#219]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.2

### Environment
"vue": "^2.5.17",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mjrpjr4ww9)

### Steps to reproduce
Cascader open showSearch，Search in the input box，

### What is expected?
normal search

### What is actually happening?
Prompt wrong： Avoid using non-primitive value as key, use string/number value instead.  found in

**Comment by xiaosheng222** [comment]
When searching, the item in the display box below has no key binding

**Comment by xiaosheng222** [comment]
When will the next version be released?

**Comment by tangjinzhou** [comment]
this weekend

**Comment by xiaosheng222** [comment]
> this weekend

Thanks
