### ISSUE TITLE
a-descriptions component bordered property exception

### ISSUE THREAD

**Issue by JackHat** [vueComponent/ant-design-vue#2191]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
os:windows10; browser:Version 81.0.4044.129 (Official Build) (64-bit); vue-version: ^2.6.11

### Reproduction link
[https://www.antdv.com/components/descriptions-cn/](https://www.antdv.com/components/descriptions-cn/)

### Steps to reproduce
```
<template>
<a-descriptions title="User Info" layout="vertical" :bordered=true size=small :column=3>
<a-descriptions-item label="UserName">
Zhou Maomao
</a-descriptions-item>
<a-descriptions-item label="Telephone">
1810000000
</a-descriptions-item>
<a-descriptions-item label="Live">
Hangzhou, Zhejiang
</a-descriptions-item>
<a-descriptions-item label="Address" :span=2>
No. 18, Wantang Road, Xihu District, Hangzhou, Zhejiang, China
</a-descriptions-item>
<a-descriptions-item label="Remark">
empty
</a-descriptions-item>
</a-descriptions>
</template>
```

重现步骤：先去掉bordered为true这个属性，样式正常。再加上这个属性，样式错位。
Reproduction step: first remove the attribute bordered to true. The style is normal. Plus this property, the pattern is misplaced.

### What is expected?
期望加上bordered为true这个属性，是在没加的样式基础上只增加边框，而不会发生错位。
It is expected to add the attribute "bordered" to true, which is to add only borders on the basis of no added styles without dislocation.

### What is actually happening?
在这段代码中，bordered为true这个属性加上之后，我这边的样式发生了错位。首行会展示4列，最后一列空白，第二行显示两列，第一列占三个单位，第二列占1个单位。所以，第一行有4列，且最后一列是空白的。
In this code, after the attribute bordered to true is added, my style is misplaced. The first row will display four columns, the last column is blank, the second row will display two columns, the first column occupies three units, and the second column occupies one unit. So, the first row has four columns, and the last column is blank.

---
我是在本地项目中遇到的这个问题。
I met this problem in my local project.

**Comment by zkwolf** [comment]
给个复现？

**Comment by JackHat** [comment]
![1](https://user-images.githubusercontent.com/32704080/80963031-c6a56280-8e40-11ea-8b63-da3eb03fe091.png)
![2](https://user-images.githubusercontent.com/32704080/80963037-c907bc80-8e40-11ea-9287-e361d60fb1d1.png)
```
<template>
  <a-descriptions title="User Info" layout="vertical" :bordered=true size=small :colon=true :column=3>
    <a-descriptions-item label="UserName">
      Zhou Maomao
    </a-descriptions-item>
    <a-descriptions-item label="Telephone">
      1810000000
    </a-descriptions-item>
    <a-descriptions-item label="Live">
      Hangzhou, Zhejiang
    </a-descriptions-item>
    <a-descriptions-item label="Address" :span=2>
      No. 18, Wantang Road, Xihu District, Hangzhou, Zhejiang, China
    </a-descriptions-item>
    <a-descriptions-item label="Remark">
      empty
    </a-descriptions-item>
  </a-descriptions>
</template>
<script>
export default {
    
}
</script>
<style scoped>
</style>
```
就是【:bordered=true】这个属性在加上的情况下，会发生错位。

**Comment by JackHat** [comment]
@zkwolf 上面贴了两张图片，好像加载不出来，不过代码的话都在这里了。你可以试一下，我不太清楚你这边是否可以重现，如果没问题，或是找到解决办法，还请告知一下，谢谢~

**Comment by zkwolf** [comment]
问题确认，这边ant design v4的时候重构给修复了，我得看看怎么同步一下修改

**Comment by JackHat** [comment]
好的
