### ISSUE TITLE
在tree标签中提供tree-node的插槽设置，能更方便完成树的增删改查

### ISSUE THREAD

**Issue by calmatery** [vueComponent/ant-design-vue#2193]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在tree-node中提供的scopedSlots必须要改变数据data才能够使用，建议在tree中提供tree-node的插槽配置，这样可以不改变数据源的情况下，直接进行插槽的修改；完成树的增删改查也将更加方便

### What does the proposed API look like?
`<a-tree :nodeScopedSlots='slot1'></a-tree>`

**Comment by loneyao** [comment]
楼主这个问题解决了吗？

**Comment by calmatery** [comment]
> 楼主这个问题解决了吗？

没有呢，这个要官方更新api才行，我看过源码了，目前不支持这样的写法
