### ISSUE TITLE
inputs with suffix or prefixs style and class attribute wont work properly

### ISSUE THREAD

**Issue by ARMS9** [vueComponent/ant-design-vue#2198]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
firefox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8phcz)

### Steps to reproduce
when trying to add class or style on a input its work fine. like this:
`<a-input class="border-0" />`
but when you add suffix or prefix attribute its not working. like this :
`<a-input suffix="goodbye" class="border-0" />`

### What is expected?
input with no border

### What is actually happening?
still have border. [the class (or style) wont working]

---
i think in this case there is a mask on input, and class and style changes the css of the input under mask .

**Comment by tangjinzhou** [comment]
you can use 
```
.border-0 input {
   ...
}
```
