### ISSUE TITLE
能否提供一下，有那些组件不兼容IE9，比如： layout

### ISSUE THREAD

**Issue by wxwebfeng** [vueComponent/ant-design-vue#2201]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
window 7 / IE9 / Vue ^2.6.11

### Reproduction link
[https://www.antdv.com/components/layout-cn/](https://www.antdv.com/components/layout-cn/)

### Steps to reproduce
layout 组件使用了flex布局，不兼容IE9 一下浏览器，这边看到框架兼容性是兼容ie9；

### What is expected?
能有一份 表说明组件兼容到几，或者能提供一下不兼容IE9的组件有那些；谢谢了

### What is actually happening?
有些组件不兼容IE9

**Comment by 862881015** [comment]
的确是不支持IE9
