### ISSUE TITLE
Warning: [antdv: LocaleProvider] `LocaleProvider` is deprecated. Please use `locale` with `ConfigProvider` instead

### ISSUE THREAD

**Issue by saynone** [vueComponent/ant-design-vue#2202]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
macOS10.15.4,chrome81.0.4044.129,Vue2.5.17

### Reproduction link
[https://v7nlo.csb.app/](https://v7nlo.csb.app/)

### Steps to reproduce
when I updated antdv to 1.5.4, the browser console show this warning :
Warning: [antdv: LocaleProvider] `LocaleProvider` is deprecated. Please use `locale` with `ConfigProvider` instead

### What is expected?
fix this bug as soon , or provide a solution

### What is actually happening?
a bug for localeProvider has found in the latest version(1.5.4)

**Comment by koukaicheng** [comment]
Localeprovider has been deprecated, please use configprovider component
<a-config-provider :locale="*****">  </a-config-provider>

**Comment by koukaicheng** [comment]
<a-config-provider :locale="locale"></a-config-provider>

**Comment by chenmohan123** [comment]
```
<a-locale-provider :locale="locale">
...
</a-locale-provider>

change to

<a-config-provider :locale="locale">
...
</a-config-provider>
```

**Comment by tangjinzhou** [comment]
https://translate.google.cn/#view=home&op=translate&sl=en&tl=zh-CN&text=Warning%3A%20%5Bantdv%3A%20LocaleProvider%5D%20%60LocaleProvider%60%20is%20deprecated.%20Please%20use%20%60locale%60%20with%20%60ConfigProvider%60%20instead

**Comment by uniquejava** [comment]
vue ui的bug吧。。。。 用的是这个该死的locale provider. 处处坑。

**Comment by sendya** [comment]
> vue ui的bug吧。。。。 用的是这个该死的locale provider. 处处坑。

学好英语或者用翻译 翻一下，就有答案了。

**Comment by dayuoba** [comment]
> > vue ui的bug吧。。。。 用的是这个该死的locale provider. 处处坑。
> 
> 学好英语或者用翻译 翻一下，就有答案了。

蚂蚁的官方仓库，全都是一副趾高气昂的样子，先学会尊重人再谈技术，如果你们的issues不为国人服务，请关掉issue功能

**Comment by willylee007** [comment]
同意楼上。 顺便提一下，官方文档该更新更新国际化这一部分了。

**Comment by jjandxa** [comment]
> 同意楼上。 顺便提一下，官方文档该更新更新国际化这一部分了。

不如提交 PR 帮助完善，不然就别说这种不过脑子的话

**Comment by jiyu93** [comment]
> > > vue ui的bug吧。。。。 用的是这个该死的locale provider. 处处坑。
> > 
> > 
> > 学好英语或者用翻译 翻一下，就有答案了。
> 
> 蚂蚁的官方仓库，全都是一副趾高气昂的样子，先学会尊重人再谈技术，如果你们的issues不为国人服务，请关掉issue功能

（”关掉！关掉！一定要关掉！再不关掉那些不为国人服务的issue，小孩哪有美好的未来，哪有美好的前程，国家哪有栋梁之材？“ —— 关掉姐 ）

我的天哪，就一句劝人认真看看英文的建议都能解读成这样……
首先，张口就来，先扣上个趾高气昂的帽子。
然后，指点江山，教别人要先学会怎样再来怎样。
最后，升华主题，抬高到国家层面，杠上开花。
老哥……您这杠精三板斧舞得也太熟练了吧。如果您真的在意国人，求求您别总是带着火药来破坏国人的讨论环境了。
我猜你主要是对”学好英语“这四个字感到不爽吧，但您好好说话不行吗？非要升级矛盾、制造对立。您怎么不看看原先那个老哥一口一个”该死“、”处处坑“呢？您再仔细对比对比您的发言和别人的发言，到底谁更接近”一副趾高气昂的样子“呢？

**Comment by dayuoba** [comment]
> > > > vue ui的bug吧。。。。 用的是这个该死的locale provider. 处处坑。
> > > 
> > > 
> > > 学好英语或者用翻译 翻一下，就有答案了。
> > 
> > 
> > 蚂蚁的官方仓库，全都是一副趾高气昂的样子，先学会尊重人再谈技术，如果你们的issues不为国人服务，请关掉issue功能
> 
> （”关掉！关掉！一定要关掉！再不关掉那些不为国人服务的issue，小孩哪有美好的未来，哪有美好的前程，国家哪有栋梁之材？“ —— 关掉姐 ）
> 
> 我的天哪，就一句劝人认真看看英文的建议都能解读成这样……
> 首先，张口就来，先扣上个趾高气昂的帽子。
> 然后，指点江山，教别人要先学会怎样再来怎样。
> 最后，升华主题，抬高到国家层面，杠上开花。
> 老哥……您这杠精三板斧舞得也太熟练了吧。如果您真的在意国人，求求您别总是带着火药来破坏国人的讨论环境了。
> 我猜你主要是对”学好英语“这四个字感到不爽吧，但您好好说话不行吗？非要升级矛盾、制造对立。您怎么不看看原先那个老哥一口一个”该死“、”处处坑“呢？您再仔细对比对比您的发言和别人的发言，到底谁更接近”一副趾高气昂的样子“呢？

我是带着火药来破坏国人的讨论环境的？官方仓库的人员给提问题的人直接丢一个 谷歌翻译的链接？你不能假设中国的开发者都是阿里级别的开发者吧？就算是中文文档，不允许开发者看不懂过来提问？丢一个谷歌翻译的链接，这是什么行为？

**Comment by jiyu93** [comment]
咳咳，首先给我前些天一上头就阴阳怪气说那么多话道个歉，您消消气。

平心而论，这个问题和阿里不阿里有什么关系呢？这个项目的主要贡献者好多根本不是阿里的人。这类问题在无数开源项目中都发生过。RTFM和STFW，这是个程序员的基本素养问题，推荐搜索《提问的智慧》。

一个写得很清楚很简单的Warning，提问者看都不看一眼，那Warning还有什么存在的意义。
人的精力是有限的，开源项目的开发者不是培训班的老师，如果人人都把每一个一查就懂的问题拿来问，还用不用干活了。

何况人家并没有不允许提问呀，丢链接是授人以渔，少废话是节约时间。
你觉得这就算趾高气昂，我个人以为，有点玻璃心了。

**Comment by dayuoba** [comment]
你的这些假设都不是不成立的
* 你怎么知道提问题的人没看过《提问的智慧》？
* 你怎么知道提问者看都没看一眼？
* 你怎么知道某个提问的人一定是前端背景的人
* 你怎么知道提问的人没学好英语就来提问了
你要不要去搜一下 回答的智慧呢？你要不要学好中文再来回答问题呢？
