### ISSUE TITLE
Chrome 下 input 组件输入英文再输入中文会出现抖动问题

### ISSUE THREAD

**Issue by alwayszb** [vueComponent/ant-design-vue#2204]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Ant Design Vue: v1.5.4
Chrome: Version 81.0.4044.129

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-bug-report-zno51?file=/src/App.vue)

### Steps to reproduce
Chrome下, 先输入英文, 再输入中文会出现抖动, 原因是输入英文时文字没有垂直居中

### What is expected?
输入英文时, 文字垂直居中, 再输入中文不出现文字抖动

### What is actually happening?
输入英文时文字没有垂直居中, 再输入中文会出现抖动

**Comment by zkwolf** [comment]
我这没有复现

**Comment by tangjinzhou** [comment]
没有复现

**Comment by alwayszb** [comment]
Sorry, 我本地是 MacOS, 问题出现比较明显
麻烦看下重现视频: https://www.loom.com/share/e092f04ef7df425cb8aca5a837c2765c

刚刚在 Windows 上也测试了下, 输入英文+中文后, 移动鼠标光标, 也有复现的情况, 不移动光标的时候不会抖动

**Comment by xrkffgg** [comment]
是因为 font-size * line-height 是个奇数

**Comment by xrkffgg** [comment]
### 方法一，增加下面样式

```css
.ant-input {
    padding-top: 5px;
}
```

### 方法二，增加下面样式

```css
.ant-input {
    height: auto;
    line-height: 1.5715
}
```

两种均可，仅选其一。
