### ISSUE TITLE
文档代码缺失

### ISSUE THREAD

**Issue by jerikchan** [vueComponent/ant-design-vue#2206]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
Ant Design Vue 1.5

### Reproduction link
[https://antdv.com/docs/vue/introduce-cn/](https://antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
1.5 版本以后源码 site 目录、各组件的 demo 目录与文档相关构建脚本被去掉了

### What is expected?
1.5 版本以后也可以构建文档 https://antdv.com/docs/vue/introduce-cn/

### What is actually happening?
1.5 版本以后无法构建文档

**Comment by tangjinzhou** [comment]
1.5 版本以后不在提供离线文档，请使用在线文档

**Comment by jerikchan** [comment]
Ant Design of React 是有提供文档的，可否说明下 antdv 不提供原因？

**Comment by sendya** [comment]
本项目由社区维护，却被一些人拿去做盗版文档镜像站且更新不及时，误导了许多的用户。并且我们也想保留为本项目提供广告赞助的服务商流量入口。没更好的解决办法之前，应该不会提供

**Comment by qingmang** [comment]
这。。。。

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2800
