### ISSUE TITLE
a-model 里面  a-input 删除中间文本光标跳走

### ISSUE THREAD

**Issue by RootHJY** [vueComponent/ant-design-vue#2207]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
vue^2.6.10   ant-design-vue^1.5.4 chrom81.0.4044.113

### Reproduction link
[https://roothjy.github.io/](https://roothjy.github.io/)

### Steps to reproduce
ant-design-vue^1.5.4  a-modal  弹框组件中创建一个a-form表单元素  创建一个<a-input  v-decorator="[ 'name'] >文本框元素
在文本框中输入文字  将鼠标移动到文本中间  删除文本 光标跳到最后

### What is expected?
光标不要跳到最后

### What is actually happening?
光标跳到最后

**Comment by zhikeye** [comment]
我也遇到了同样的问题，只要在a-model里的表单组件更新值后光标都会跳到最后，请问您是怎么解决这个问题的？

**Comment by zlf-1996** [comment]
1.5.5版本更新后，解决了这个问题
