### ISSUE TITLE
TreeSelect无法自定义字段名称 

### ISSUE THREAD

**Issue by song910210** [vueComponent/ant-design-vue#2209]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
请问现在TreeSelect可以替换字段吗 title value children这些。后台数据和这个结构不同，类似Tree组件的replaceFields属性

### What does the proposed API look like?
类似Tree组件的replaceFields属性

**Comment by polichan** [comment]
同问，请问有解决方案了吗？

**Comment by sadoreko** [comment]
+1, 目前是请后台添加 title value 等字段的……

**Comment by song910210** [comment]
> 同问，请问有解决方案了吗？
没有哦 没用这个了，自己用tree封装了个弹窗

**Comment by huoshidehua** [comment]
这个很关键啊 竟然没有这种功能？

**Comment by wengjq** [comment]
这个作者已经增加了相关功能了。
https://github.com/vueComponent/ant-design-vue/commit/4cc762d6cb5484a4bbe13893459e0173e0ce0be0

**Comment by Joey-996** [comment]
> 这个作者已经增加了相关功能了
> [。4cc762d](https://github.com/vueComponent/ant-design-vue/commit/4cc762d6cb5484a4bbe13893459e0173e0ce0be0)
看到文档写着有，但是实际用了，发现没有效果，是不是我写错了
```
 <a-tree-select  :treeData="menus"  :replace-fields="replaceFields" />

menus: [  
  { 
    name: '顶级菜单',
    key: '0',
    value: '顶级菜单'
  }
],
replaceFields: {
  title: 'name', 
  key: 'key', 
  value: 'value' 
}
```

**Comment by huoshidehua** [comment]
> > 这个作者已经增加了相关功能了
> 
> > [。4cc762d](https://github.com/vueComponent/ant-design-vue/commit/4cc762d6cb5484a4bbe13893459e0173e0ce0be0)
> 
> 看到文档写着有，但是实际用了，发现没有效果，是不是我写错了
> 
> ```
> 
>  <a-tree-select  :treeData="menus"  :replace-fields="replaceFields" />
> 
> 
> 
> menus: [  
> 
>   { 
> 
>     name: '顶级菜单',
> 
>     key: '0',
> 
>     value: '顶级菜单'
> 
>   }
> 
> ],
> 
> replaceFields: {
> 
>   title: 'name', 
> 
>   key: 'key', 
> 
>   value: 'value' 
> 
> }
> 
> ```


文档看看这个属性设置了没 treeDataSimpleMode

**Comment by wengjq** [comment]
@huoshidehua 1.6.1 这个版本的才有这个功能，可以检查下。
