### ISSUE TITLE
a-form-model使用jsx时候model无法绑定

### ISSUE THREAD

**Issue by qiaochao** [vueComponent/ant-design-vue#2213]
```
<a-form-model model={this.formData} rule={this.rule} class={formStyle.modalForm} ref="addForm" labelCol={{span: 6}} wrapperCol={{span: 14}}>
        <a-form-model-item has-feedback label="名称" prop="name" required>
          <a-input v-model={this.formData.name} type="text" autocomplete="off"/>
        </a-form-model-item>
        <a-form-model-item has-feedback label="地址" prop="address" required>
          <a-input v-model={this.formData.address} type="text" autocomplete="off"/>
        </a-form-model-item>
      </a-form-model>
```
我这样写jsx，但是会报错`vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid handler for event "input": got undefined`。并且使用validateField这些方法的时候，也告知没有绑定model

请问使用jsx的是后如何传model

**Comment by erguotou520** [comment]
遇到同样的问题

**Comment by erguotou520** [comment]
图中可以看到`layout`传递过去了，但是`model`没有（父组件传递的确实有值，因为在render写法下是能看到有值的），同时`$attrs.value=undefined`，但实际上我根本没传`value`，去掉父组件中的`model`参数就没有这个`$attrs`
![image](https://user-images.githubusercontent.com/7945757/81886651-d1de5800-95cf-11ea-977f-2b8f87a92743.png)

**Comment by JinPengGeng** [comment]
@erguotou520 @qiaochao  jsx中 不能直接写v-model，须使用vModel，改成驼峰就好了

**Comment by zhmxby** [comment]
@erguotou520 @qiaochao 
我也遇到了，搞了好久，可能是和babel-sugar-v-model插件冲突了（还没验证），暂时用这种方法解决了，
`
<a-form-model {...{
        props: {
          model: this.model
        }
      }}>
</a-form-model>
`

**Comment by erguotou520** [comment]
@zhmxby 我们没有用`babel-sugar-v-model`

**Comment by zhmxby** [comment]
babel-sugar-v-model 提供的就是在jsx里面写v-model的功能，vue-cli3自带的

**Comment by zhmxby** [comment]
@erguotou520  babel-sugar-v-model 提供的就是在jsx里面写v-model的功能，vue-cli3自带的

**Comment by san-wi** [comment]
如果是jsx写法
```
<a-form-model propModel={model}></a-form-model>
```

**Comment by erguotou520** [comment]
@zhmxby  你说的是 https://www.npmjs.com/package/@vue/babel-sugar-v-model 吧。现在都用vue3了，可以直接使用`v-model`
