### ISSUE TITLE
firefox - win10自带输入法中文模式，input组件第一次输入数字不显示

### ISSUE THREAD

**Issue by wang-ky** [vueComponent/ant-design-vue#2215]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
win10, firefox75, vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-v9njz)

### Steps to reproduce
切换输入法到windows自带输入法的中文输入模式，输入数字

### What is expected?
可正常显示

### What is actually happening?
第一次不显示，第二次正常

**Comment by wang-ky** [comment]
![image](https://user-images.githubusercontent.com/30018773/81387681-a845ac80-9149-11ea-9273-0e41f411bd7b.png)
antInputDirective.js文件，截图的第25行用setTimeout包一下就正常了。
此时每输一次数字都会触发compositionstart和compositionend，猜测问题原因和 [#2151](https://github.com/vueComponent/ant-design-vue/issues/2151#issuecomment-622962995) 类似，修改placeholder之后触发了回流，但是第一次之后就正常了，还是很奇怪

**Comment by wang-ky** [comment]
红框部分代码还可以参考issue #1458

**Comment by tangjinzhou** [comment]
很奇怪的 bug

**Comment by wang-ky** [comment]
目前项目在准备上线阶段，不适合升级版本，有兼容性的方法解决一下么 @tangjinzhou
