### ISSUE TITLE
ant-table-body-outer的margin-bottom样式应该随滚动条的高度进行适配

### ISSUE THREAD

**Issue by arika163** [vueComponent/ant-design-vue#2216]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
windows10@1909,chrome@81.0.4044.122,vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-silence-11c79?file=/src/App.vue)

### Steps to reproduce
请直接查看沙盒复现，已添加醒目样式
https://codesandbox.io/s/bold-silence-11c79?file=/src/App.vue

### What is expected?
ant-table-body-outer的margin-bottom值应该是 负的 滚动条高度（height）

### What is actually happening?
ant-table-body-outer的margin-bottom值 现在是 负的 滚动条宽度（width）
由于高度不一致，ant-table-body-outer挡住了一部分表格的滚动条，被挡住的部分无法响应点击

**Comment by TioJS** [comment]
@tangjinzhou
