### ISSUE TITLE
\node_modules\ant-design-vue\dist\/antd.css文件没了

### ISSUE THREAD

**Issue by RootHJY** [vueComponent/ant-design-vue#2219]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
ant-design-vuex@1.5.5

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
This dependency was not found:
* ant-design-vue/dist/antd.css in ./src/main.js

### What is expected?
\node_modules\ant-design-vue\dist   加上\node_modules\ant-design-vue\dist   ant.css；
兼容import 'ant-design-vue/dist/antd.css';写法

### What is actually happening?
\node_modules\ant-design-vue\dist   ant.css 不见啦

**Comment by p2ng** [comment]
快速解决固定为1.5.4版本。。。
在`package.json`调整`    "ant-design-vue": "1.5.4",`

**Comment by tangjinzhou** [comment]
已修复  1.5.6
