### ISSUE TITLE
Update icon set

### ISSUE THREAD

**Issue by sghgh1996** [vueComponent/ant-design-vue#222]
I used ant.design in my react projects. I started a vuejs project and I found this npm. I checked the icon set and I realized that it has less icons than the react ant.design. Can anyone add icon set or help me contribute and add them.

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/ant-design-icons/issues/3#issuecomment-429624109

**Comment by tangjinzhou** [comment]
please update to 1.2.1

**Comment by evolutionjay** [comment]
@tangjinzhou  升级之后， AIcon 组件用了 svg ，那么， text-shadow 怎么办？
