### ISSUE TITLE
1.5.5 版本style文件路径有误

### ISSUE THREAD

**Issue by webweifeng** [vueComponent/ant-design-vue#2220]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
任何环节

### Reproduction link
[https://www.antdv.com/docs/vue/introduce-cn/](https://www.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
import 'ant-design-vue/dist/antd.css'文件无法找到

### What is expected?
正常加载CSS文件

### What is actually happening?
文件无法找到

---
查看了dist文件夹没有antd.css文件

**Comment by tangjinzhou** [comment]
重复 #2219
