### ISSUE TITLE
Can't use router or vm parameter in notification

### ISSUE THREAD

**Issue by mathieutu** [vueComponent/ant-design-vue#2221]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-router-error-6jp34)

### Steps to reproduce
Add a router-link or anything that need access to the vue-app in description or message.

```js
notification.error({
  message: 'Problem',
  description: h => h('router-link', { props: { to: '/foo' } }, 'Go to /foo')
})
```

### What is expected?
The component should render and behave properly.

### What is actually happening?
```
[Vue warn]: Error in render: "TypeError: router is undefined

found in

---> <RouterLink>
<Anonymous>
<TransitionGroup>
<Anonymous>
<Root>
```

**Comment by dcdebug** [comment]
Hi , do you solove the Question ?

**Comment by mathieutu** [comment]
We'll keep that open, thx!

**Comment by tangjinzhou** [comment]
At v1.x,  notification.error will use new `new Vue`, not ` new Vue` at main.ts.  This will cause the router related api to not be found.
you can use `<a></a>`, or router.go some api to resloved this.
or you can use v2.x.
