### ISSUE TITLE
异步树,死循环问题.

### ISSUE THREAD

**Issue by meihangbo** [vueComponent/ant-design-vue#2227]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
win10   chrome 81.0.4044.138（正式版本）（64 位）  vue 2.6.11   ant-design-vue 1.5.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-zm9n2?file=/src/App.vue)

### Steps to reproduce
给树添加 loadedKeys,  load-data 返回如果是空数组,就会出现死循环;
由于需求页面上是动态树,当切换标签要改变树的数据,需要清除树的相关数据;

### What is expected?
怎样设置才能不出现死循环,谢谢!

### What is actually happening?
不添加 loadedKeys 是正常的, 反之返回空数组会出现死循环;

**Comment by wzohxia** [comment]
返回为空时  设置当前节点为叶节点
