### ISSUE TITLE
全局配置ConfigProvider设置了prefixCls，对modal组件不生效

### ISSUE THREAD

**Issue by mingtianyihou33** [vueComponent/ant-design-vue#2235]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
vue 2.6*

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
配置prefixCls，然后查看modal的class前缀

### What is expected?
希望前缀是全局配置的prefixCls值

### What is actually happening?
modal的class前缀依旧是ant

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/antdv-demo-q043g?file=/src/App.vue

**Comment by kimyLee** [comment]
I believe the issue has not be solved yet. @xrkffgg 's example only show the case of button, the same problem happended to me that when I set `prefixCls` and config `modifyVars: { 'ant-prefix': xxx }`,  all the element class name start with "xxx" but `modal confirm ` and `message`(still 'ant-modal'), is there any commit has solved this? @Amour1688

**Comment by chenji336** [comment]
I believe the issue has not be solved yet. @xrkffgg 's example only show the case of button, the same problem happended to me that when I set prefixCls and config modifyVars: { 'ant-prefix': xxx }, all the element class name start with "xxx" but modal confirm and message(still 'ant-modal'), is there any commit has solved this? @Amour1688

**Comment by kiinlam** [comment]
这坑我刚踩完。

```
import { message } from 'ant-design-vue'
message.config({ prefixCls: 'your-prefix-message' })
```

使用config方法来配置，该配置将替换掉`ant-message`，所以结尾必须保留`-message`。

比如：

`<ConfigProvider prefixCls="hello">`

将会生成`.hello-message`的样式类名，需配置为`message.config({ prefixCls: 'hello-message' })`

**Comment by le0l1** [comment]
+1 same problemn

**Comment by zxfishhack** [comment]
在main.js里面通过message.config配置prefixCls可以解决,但是此字段不在文档及接口定义上.
```
message.config({ prefixCls: `${antPrefix()}-message` });
```

**Comment by kimyLee** [comment]
您好，来信已收到，我会尽快给您回复。

**Comment by nailuox** [comment]
在confirm调用时配置parentContext和prefixCls
```
this.$confirm({
   parentContext: this,
   prefixCls: '${antPrefix()}-modal'
})
```

**Comment by mmzuo** [comment]
> 在confirm调用时配置parentContext和prefixCls
> 
> ```
> this.$confirm({
>    parentContext: this,
>    prefixCls: '${antPrefix()}-modal'
> })
> ```



> 在confirm调用时配置parentContext和prefixCls
> 
> ```
> this.$confirm({
>    parentContext: this,
>    prefixCls: '${antPrefix()}-modal'
> })
> ```
保存和取消按钮class 仍然是 ant-前缀，怎么解决的？
