### ISSUE TITLE
ie9 下页面打不开，报错matchMedia not present, legacy browsers require a polyfill？有什么解决方案吗

### ISSUE THREAD

**Issue by vueCcc** [vueComponent/ant-design-vue#2237]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
ie9

### Reproduction link
[https://www.antdv.com/docs/vue/sponsor-cn/](https://www.antdv.com/docs/vue/sponsor-cn/)

### Steps to reproduce
ie9 下页面打不开，报错matchMedia not present, legacy browsers require a polyfill？有什么解决方案吗

### What is expected?
ie9 可以正常打开页面

### What is actually happening?
ie9 下页面打不开，报错matchMedia not present, legacy browsers require a polyfill？有什么解决方案吗

**Comment by CYan596** [comment]
![image](https://user-images.githubusercontent.com/34957945/82970938-1a503980-a004-11ea-9c8c-63d492076e48.png)

**Comment by tangjinzhou** [comment]
https://github.com/paulirish/matchMedia.js
