### ISSUE TITLE
Missing "No data" image table locale "emptText" property is set.

### ISSUE THREAD

**Issue by arturcesarmelo** [vueComponent/ant-design-vue#2239]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
OSX Mojave, Firefox 75.0, Chrome 81.0.4044.129, Vue 2.6.11 and ant-design-vue 1.5.6;

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-turing-um65y?file=/src/App.vue)

### Steps to reproduce
Just see the https://codesandbox.io/s/crazy-turing-um65y?file=/src/App.vue

### What is expected?
When you change the "emptyText" of <a-table> component, i supose that just the text is expected to be changed.

### What is actually happening?
The image above "No Data" text is gone.

**Comment by roywuyy** [comment]
I also encountered this problem

**Comment by phiberber** [comment]
This thing is still happening, it looks really odd to have an `<Empty />` with the icon and on the side of it having a `<List />` that only has the text of it. Can this get some attention?

**Comment by zkwolf** [comment]
`No data` is the default value of the description prop of Empty component, you can bind emptyText with Empty component.
