### ISSUE TITLE
[feature request] moment.js 体积过大，能否换成体积更小的day.js 

### ISSUE THREAD

**Issue by 54yuri** [vueComponent/ant-design-vue#224]
antd.js 自带的moment.js 体积过大，能否换成体积更小的day.js , 号称压缩后只有2kb， 谢谢

**Comment by shanlh** [comment]
我在打包的时候忽略了：
configureWebpack: {
  plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
  ]
}

然后在main.js里自行 import 'moment/locale/zh-cn'

**Comment by bowencool** [comment]
> ^.
```
/^\.\/locale$/
```

**Comment by shanlh** [comment]
对，打出来的时候被不见了
`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/ant-design/issues/10437

**Comment by omarbk** [comment]
________________________________

**Comment by webees** [comment]
去除moment.js中多余的语言包就行了，需配置下webpack。

**Comment by dzcpy** [comment]
momentjs 真是麻烦。替换下也不怎么费事，webpack 我这边用插件也没搞定自动替换 dayjs 的功能
