### ISSUE TITLE
throw a warning when build the project

### ISSUE THREAD

**Issue by yiptsangkin** [vueComponent/ant-design-vue#2241]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
mac chrome vue2.6.11 vue-cli3

### Reproduction link
[https://github.com/yiptsangkin/near-admin-vue.git](https://github.com/yiptsangkin/near-admin-vue.git)

### Steps to reproduce
npm run build

### What is expected?
remove the warning

### What is actually happening?
chunk chunk-vendors [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/_css-loader@3.5.3@css-loader/dist/cjs.js??ref--10-oneOf-3-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--10-oneOf-3-2!./node_modules/_less-loader@6.0.0@less-loader/dist/cjs.js??ref--10-oneOf-3-3!./node_modules/_ant-design-vue@1.5.4@ant-design-vue/es/button/style/index.less
despite it was not able to fulfill desired ordering with these modules:
* css ./node_modules/_css-loader@3.5.3@css-loader/dist/cjs.js??ref--10-oneOf-3-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--10-oneOf-3-2!./node_modules/_less-loader@6.0.0@less-loader/dist/cjs.js??ref--10-oneOf-3-3!./node_modules/_ant-design-vue@1.5.4@ant-design-vue/es/input/style/index.less
- couldn't fulfill desired order of chunk group(s) manage
- while fulfilling desired order of chunk group(s) auth

---
this a multipage project, and i am not sure what's the problem, after i read some answers about this warning, and i try to adjust the Button and  the Input component's postion in auth.ts and manage.ts.But it wasn't work. thx a lot.

**Comment by tangjinzhou** [comment]
https://github.com/vuejs/vue-cli/issues/3771
