### ISSUE TITLE
1.4.4迁移到1.5.6，对话框Modal和抽屉Drawer中调用子组件出错。

### ISSUE THREAD

**Issue by xzz0839** [vueComponent/ant-design-vue#2244]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
Win10,Chrome81

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-rm0gc)

### Steps to reproduce
[https://codesandbox.io/s/vue-antd-template-rm0gc](https://codesandbox.io/s/vue-antd-template-rm0gc)
第一次点击按钮正常，再次点击按钮出错，1.5.3和之前的版本正常，1.5.4和之后的版本报错。Modal与Drawer有同样的问题。

### What is expected?
目前要包两层this.$nextTick才不报错

### What is actually happening?
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'setText' of undefined"
TypeError: Cannot read property 'setText' of undefined

**Comment by l619534951** [comment]
解决：https://codesandbox.io/s/vue-antd-template-75e72?file=/src/M1.vue

我的理解是是下面那个，不知道对不对。

this.$nextTick(() => {
  // 这里将在下一次dom渲染完毕后被执行，子组件不一定被渲染完毕。
})

await this.$nextTick()
// 这里将在当前组件所有dom（包括子组件）全部渲染完毕后被执行。

**Comment by tangjinzhou** [comment]
临时方案 destroyOnClose= false

**Comment by tangjinzhou** [comment]
fix at https://github.com/vueComponent/ant-design-vue/commit/529f81cb5418559b0ed6b2b607d2331397e465dd

**Comment by zhouyu1993** [comment]
[Vue warn]: Failed to resolve directive: ant-portal

**Comment by leaf1992** [comment]
> [Vue warn]: Failed to resolve directive: ant-portal
问题解决了吗
