### ISSUE TITLE
Edge issue with placeholders not hiding after select value

### ISSUE THREAD

**Issue by devmons** [vueComponent/ant-design-vue#2251]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
Egde 18  not working, Edge 80 working

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-select-edge-placeholder-issue-rdwsf?file=/src/App.vue)

### Steps to reproduce
fire select with placeholder on Edge 18, this llink to codesandbox : https://codesandbox.io/s/vue-select-edge-placeholder-issue-rdwsf?file=/src/App.vue not working on Edge 18, you need to copy this select from this reproduction and test on something that is working in Edge 18

### What is expected?
To placeholder disappear after selecting a value on Edge 18

### What is actually happening?
Placeholder is not disappearing

**Comment by tangjinzhou** [comment]
1.6.0 or 1.4.2  Can you tell me exactly?
You can try the latest version.
