### ISSUE TITLE
TreeSelect组件，怎么自定义数组显示？

### ISSUE THREAD

**Issue by noecs** [vueComponent/ant-design-vue#2253]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
macOS Sierra, Chrome, vue-antd-pro:2.1.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-jdob2?file=/src/App.vue)

### Steps to reproduce
# TreeSelect
使用自定义的数组该怎么正常显示？
数据格式例如:
```
[
        {
          id: 2,
          name: "测试",
          children: [
            {
              id: 3,
              name: "测试内",
              children: []
            }
          ]
        },
        {
          id: 4,
          name: "测试2",
          children: [
            {
              id: 5,
              name: "测试内3",
              children: []
            }
          ]
        }
]
```

### What is expected?
我期望它能够在下拉框中显示name值，并且在选择的时候修改this.data为选择的name对应ID值，

### What is actually happening?
实际中，树状下拉框不显示name，只显示了`---`。

**Comment by edenleung** [comment]
你还没配置 `title` 、`value` 值

```
<template>
  <div style="margin: 24px">
    <a-tree-select
      v-model="value"
      style="width: 100%"
      :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
      :tree-data="tree"
      placeholder="Please select"
      tree-default-expand-all
    >
      <span slot="name" slot-scope="{ name, id }" style="color: #08c">{{ name }}</span>
    </a-tree-select>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      value: 2,
      tree: [
        {
          id: 2,
          title: "测试",
          value: 2,
          children: [
            {
              id: 3,
              title: "测试内",
              value: 3,
              children: []
            }
          ]
        },
        {
          id: 4,
          title: "测试2",
          value: 4,
          children: [
            {
              id: 5,
              title: "测试内3",
              value: 5,
              children: []
            }
          ]
        }
      ]
    };
  }
};
</script>

<style></style>
`
```

**Comment by noecs** [comment]
@edenleung 这个`title`,`value`不支持自定义吗？

**Comment by tangjinzhou** [comment]
下个版本支持

**Comment by buildJava** [comment]
treeNodeFilterProp, treeNodeLabelProp是这两个字段吗，升级到1.6.1版本的api，
![image](https://user-images.githubusercontent.com/18717339/82977152-956d1c00-a013-11ea-8f6b-d823edd5ff37.png)
![image](https://user-images.githubusercontent.com/18717339/82977198-b6ce0800-a013-11ea-883d-d4ef24fac3b2.png)
不生效呢

**Comment by buildJava** [comment]
通过配置replaceFields生效，但是有个问题比如选中后是显示在框中的内容是通过value配置的，真实情况下一般显示是title,返回的值是key或者id,怎么实现，建议采用和select一致的方法，回写的值是label或者title，返回的值是key或者value

**Comment by buildJava** [comment]
通过配置replaceFields: { title: 'deptName', key: 'id', value: 'id' }生效了，那么想问下reeNodeFilterProp, treeNodeLabelProp这两个字段的作用是什么

**Comment by Quantriple** [comment]
> 通过配置replaceFields: { title: 'deptName', key: 'id', value: 'id' }生效了，那么想问下reeNodeFilterProp, treeNodeLabelProp这两个字段的作用是什么

哥们，replaceFields: 这个生效了吗，我这边没有生效。。。版本升级到了1.6.1
