### ISSUE TITLE
Drawer 使用 v-if 条件销毁时控制台报错

### ISSUE THREAD

**Issue by fyunli** [vueComponent/ant-design-vue#2254]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
版本 81.0.4044.122

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/holy-brook-ih7h3?file=/src/components/HelloWorld.vue)

### Steps to reproduce
点击 "Open Drawer" 然后点击 "Disable Drawer"

### What is expected?
控制台不报错

### What is actually happening?
![](http://fyunli-ipic.oss-cn-shenzhen.aliyuncs.com/snipshot/kghb3.png)

**Comment by top-dante** [comment]
同样遇上问题 以前版本没有 更新1.5.5就有了
