### ISSUE TITLE
Select 中的option 不支持多个div

### ISSUE THREAD

**Issue by a304885433** [vueComponent/ant-design-vue#2255]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
select下拉框选项，默认会有描述字段。其中option写法为 <a-select-option> <div>{{ item.name }} </div> <div> {{item.desp}}</div> </a-select-option> react版本是支持的。
参见react code。
https://codesandbox.io/s/jibenshiyong-ant-design-demo-8t064?file=/index.js:264-447

### What does the proposed API look like?
react ant 是支持的
<Select defaultValue="lucy" style={{ width: 120 }} onChange={handleChange}>
<Option value="jack">

<div>1111</div>
<div>22222</div>
</Option>

**Comment by tangjinzhou** [comment]
Vue 2.x 不支持  要等升级3.x版  你可以自己外面套一层标签

**Comment by a304885433** [comment]
收到，谢谢老师
