### ISSUE TITLE
inputNumber pressEnter失效

### ISSUE THREAD

**Issue by lcw2012** [vueComponent/ant-design-vue#2257]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
vue 2.6.10

### Reproduction link
[http://localhost:8080/#/asn?funApi=%2Fgeneric%2Fimpl%3Fmenu%3DVASN&userUid=20&funcUid=18](http://localhost:8080/#/asn?funApi=%2Fgeneric%2Fimpl%3Fmenu%3DVASN&userUid=20&funcUid=18)

### Steps to reproduce
a-input-number pressEnter事件 失效

### What is expected?
pressEnter事件 有效

### What is actually happening?
无

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/antdv-demo-tux68?file=/src/App.vue
