### ISSUE TITLE
表格伸缩列的建议

### ISSUE THREAD

**Issue by liu0122** [vueComponent/ant-design-vue#2260]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1、当前的表格伸缩列的官方demo中需要使用者自己使用vue-draggable-resizable来重新渲染table的components，建议可以像element ui 那样直接设置border属性即可。
2、在声明column数组是必须设置width属性，要不然伸缩列不会生效。

### What does the proposed API look like?
可以像element ui 那样直接设置border属性即可。

**Comment by tangjinzhou** [comment]
感谢建议
