### ISSUE TITLE
Failed to resolve directive: ant-portal

### ISSUE THREAD

**Issue by mark0325** [vueComponent/ant-design-vue#2261]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
win10，Microsoft Edge 81.0.416.72  ，vue 2.6.11

### Reproduction link
[https://github.com/mark0325/antv-test](https://github.com/mark0325/antv-test)

### Steps to reproduce
点击test按钮，弹出抽屉窗口

### What is expected?
加载全部组件不报错，按需加载控制台报错

### What is actually happening?
控制台  报错 Failed to resolve directive: ant-portal

**Comment by tangjinzhou** [comment]
使用 vue.use(xxx) 的形式注册组件

**Comment by Axiuxiuxiu** [comment]
[Vue warn]: Failed to resolve directive: ant-portal

**Comment by darekmeco** [comment]
I confirm @1.6.1 too
Warn appears when a-modal's v-modal is set to true.

**Comment by darekmeco** [comment]
Vue.use(Modal) helps, but why I need this ? And why only for modal ?

**Comment by rpdg** [comment]
same problem @1.6.2

**Comment by miaoxiaoy** [comment]
same problem @1.6.4
抽屉窗口弹出时, 没有在页面最外层的body处挂载抽屉(getContainer API ,默认值是body), 如果页面使用到了Layout布局, 会挂载到子组件上, 如果子组件的区域只是一小块(没有占满整个浏览器), 那么这个抽屉弹出源方向的那侧就会显示空白

**Comment by miaoxiaoy** [comment]
> Vue.use(Modal) helps, but why I need this ? And why only for modal ?

The Drawer has same problem, not only Modal

**Comment by Glacier-Luo** [comment]
其实就是在按需引入的常用写法中没有调用到Vue.use所执行的自定义指令，最多就在引入部分加两行代码就能解决
```
import Vue from 'vue'
Modal.install(Vue)
```
---
不懂为什么官方对这种问题的回答都讳莫如深，一脸厌恶的样子
`https://cloud.tencent.com/developer/article/1644077`
[查问题时看到的文章](https://cloud.tencent.com/developer/article/1644077)
![image](https://user-images.githubusercontent.com/30594509/104923998-ce5d6500-59d7-11eb-83e1-57cdd02d1935.png)
![image](https://user-images.githubusercontent.com/30594509/104924010-d1585580-59d7-11eb-8df2-30c5e91031ea.png)

**Comment by PachVerb** [comment]
...
