### ISSUE TITLE
select组件 search事件在触发blur事件之前会返回空值

### ISSUE THREAD

**Issue by qiaozhi520** [vueComponent/ant-design-vue#2262]
### Version
1.6.0

### Environment
vue 2.6.10 ,Chrome浏览器, mac

### Reproduction link
https://www.antdv.com/components/select-cn/

### Steps to reproduce
1.select组件，打开showSearch，mode='default',绑定search事件，autoClearSearchValue也设置了false
2.输入值后，点击空白处触发blur事件之前还会触发一次search事件，并且传出值为空

### What is expected?
我们有一个既可以下拉选择也可自定义值的搜索需求，在1.4版本的时候组件是可以满足的，但是之后的版本就不行了，会自动清除掉输入的值，并触发search事件，不知道是特意这么设计的还是bug，现在因为这一机制，组件无法使用

What is actually happening?
这个问题在1.4.*的版本是没有，1.5.0到1.6.0 都有这个问题

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/82291125-faed5700-99da-11ea-8aa8-2c2b62f36f16.png)

### CodeSanbox Link
https://codesandbox.io/s/antdv-demo-select-tux68

没发现有啥问题啊

**Comment by qiaozhi520** [comment]
> ![image](https://user-images.githubusercontent.com/29775873/82291125-faed5700-99da-11ea-8aa8-2c2b62f36f16.png)
> 
> ### CodeSanbox Link
> https://codesandbox.io/s/antdv-demo-select-tux68
> 
> 没发现有啥问题啊

#在触发blur事件前会触发search事件，并返回一个空值，这是你们特意处理的吗？1.4之前是没有这个机制的，这机制会影响判空处理

**Comment by xrkffgg** [comment]
返回空值？是不是因为你传入的值 没有查到？

**Comment by qiaozhi520** [comment]
> 返回空值？是不是因为你传入的值 没有查到？

#在组件里随便输入一段文字，不选择任何内容，然后在外部点击一下，这次点击会触发一次search事件，search事件会返回一个空值，这一机制是bug还是有意为之？因为auto-complete组件不能满足需求，所以使用select做替代，但1.4之后就用不了了

**Comment by xrkffgg** [comment]
对的啊，是会触发 search，因为开启了 show-search ，就会去用你输入的匹配下了选项中的内容，如果没查到，就会返回空

https://github.com/vueComponent/ant-design-vue/blob/4cc762d6cb5484a4bbe13893459e0173e0ce0be0/components/vc-select/Select.jsx#L920

**Comment by UgineHuang** [comment]
同遇到这样的问题，我的版本是1.6.2 。
现在是在组件里随便输入一段文字，不选择任何内容，然后在外部点击一下，会先触发blur事件，然后再触发了search事件，这次的search事件里value为空字符串，就导致与现有业务冲突了。不是太理解这一机制的意义

**Comment by kaokei** [comment]
@qiaozhi520 请问最后你是怎么解决这个问题的呢？我这边也遇到这个问题了。

@xrkffgg 目前的实现机制导致不能支持特定的场景。我这边的场景是用户输入了内容之后，如果可以查询到数据，然后用户可以选择查询到的数据。如果查询不到数据，那么就使用用户输入的数据。

我查看了源代码，现在是在失去焦点是，会自动清空searchText.

[参考这里的代码](https://github.com/vueComponent/ant-design-vue/blob/fc0589c48f71f0280fec9ad6064046c40b1a59a9/components/vc-select/generate.tsx#L820)

而且这里的`{ immediate: true }`会导致placeholder失效。

**Comment by kaokei** [comment]
我这边打算利用input和dropdown来实现一个满足我需求的组件了。
