### ISSUE TITLE
升级1.6后，Drawer打开后，点击链接进行路由跳转时，报TypeError: Cannot read property 'removeChild' of null

### ISSUE THREAD

**Issue by xhubert** [vueComponent/ant-design-vue#2263]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
Macos/Chrome/Vue2.5.17/vue-router

### Reproduction link
[https://bfhrt.csb.app/#/](https://bfhrt.csb.app/#/)

### Steps to reproduce
1. Home页面点击open按钮，打开drawer；
2. 关闭drawer后，点击Go to About链接；（控制台抛异常）

### What is expected?
修复bug

### What is actually happening?
container.parent取值为null。

**Comment by jianchen2580** [comment]
+1

**Comment by tangjinzhou** [comment]
重复 #2252
