### ISSUE TITLE
menu 导航菜单因宽度不够出现的省略号内点击menu-item会触发2次click

### ISSUE THREAD

**Issue by snakeninja110** [vueComponent/ant-design-vue#2266]
Version
1.5.0+

Environment
win10 Chrome 81.0.4044

Reproduction link
[https://codesandbox.io/s/menu-test-0pngm?file=/src/App.vue](https://codesandbox.io/s/menu-test-0pngm?file=/src/App.vue)

Steps to reproduce
缩小窗口至menu出现省略号，此时点击被折叠的menu-item

What is expected?
只触发一次click事件

What is actually happening?
触发了2次click，一次为当前点击项的
又触发了一次list[0]项的click事件

**Comment by jiangmingwen** [comment]
你可以试试，@click.stop

**Comment by zhedream** [comment]
> 你可以试试，@click.stop

并不行呢,  prevent 也不行
$event.stopPropagation is not a function

**Comment by zhedream** [comment]
已修复: https://github.com/vueComponent/ant-design-vue/releases/tag/1.6.1
