### ISSUE TITLE
Can't resolve 'ant-design-vue/es/tree-node'

### ISSUE THREAD

**Issue by ArchieHurry** [vueComponent/ant-design-vue#2267]
import { Tree, TreeNode } from 'ant-design-vue'
按需引入不了TreeNode

**Comment by lvreninfo** [comment]
`<script>
import { Tree } from 'ant-design-vue'
export default {
  components: {
    [Tree.name]: Tree,
    [Tree.TreeNode.name]: Tree.TreeNode
  }
}
</script>`

**Comment by lvreninfo** [comment]
import { Tree } from 'ant-design-vue'
components: {
    [Tree.name]: Tree,
    [Tree.TreeNode.name]: Tree.TreeNode
}
