### ISSUE TITLE
Portal 销毁前钩子方法报错

### ISSUE THREAD

**Issue by mark0325** [vueComponent/ant-design-vue#2272]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
win10，Microsoft Edge 81.0.416.72  ，vue 2.6.11

### Reproduction link
[https://github.com/mark0325/antv-test](https://github.com/mark0325/antv-test)

### Steps to reproduce
Drawer组件展示后，切换页面路由

### What is actually happening?
Portal.js中 removeContainer 方法报错，this._container.parentNode 是 null

**Comment by yundmb** [comment]
我也发现了，刚升级到1.6.0，我还一直在查我的代码哪里写的不对。。。

**Comment by xzz0839** [comment]
确实有这个问题。
[https://codesandbox.io/s/vue-antd-template-rm0gc](https://codesandbox.io/s/vue-antd-template-rm0gc)
点击“对话框”按钮>>点击“抽屉”按钮>>关闭抽屉>>关闭对话框>>报错。
Modal  :destroyOnClose="true"改false时不报错。

**Comment by tangjinzhou** [comment]
重复 #2263

**Comment by Etienne-Leveque** [comment]
Has this issue been already solved and if so, will it be shipped in a coming release? I face the same issue with Ant version 1.6.0.

**Comment by yundmb** [comment]
> Has this issue been already solved and if so, will it be shipped in a coming release? I face the same issue with Ant version 1.6.0.

There is no fix now, it will be fixed in the next version
