### ISSUE TITLE
select组件设置成可搜索时 ，不能以显示的值搜索，需要用到key才能搜索 

### ISSUE THREAD

**Issue by km-iconfont** [vueComponent/ant-design-vue#2277]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
select组件设置成可搜索时 ，不能以显示的值搜索，需要用到key才能搜索。
希望可以优化一下，让交互体验更好，不用在做特殊处理

### What does the proposed API look like?
用户体验第一位（性能、效率）；还有就是学习成本要低

**Comment by mynetfan** [comment]
`optionFilterProp`属性可控制需要搜索什么，参见[API](https://www.antdv.com/components/select-cn/#API)

**Comment by enjkvbej** [comment]
@mynetfan optionFilterProp设置为options里的属性‘label’ 然而没有作用会报错
```
function filterOption(input, option) {
      return option.props.label.toLowerCase().indexOf(input.toLowerCase()) >= 0;  // option.props只有value 获取不到label
}
```
