### ISSUE TITLE
a-table同时使用树形数据展示和sorter，children有数据时，点击表头死循环卡死

### ISSUE THREAD

**Issue by peinkid** [vueComponent/ant-design-vue#2282]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-xv3id?file=/src/App.vue)

### Steps to reproduce
help

### What is expected?
不出现死循环

### What is actually happening?
死循环

**Comment by tangjinzhou** [comment]
重复 #2281

**Comment by peinkid** [comment]
> 重复 #2281

重复是因为上次好像描述不规范被github关闭，这个问题实际上没有解决呢，请看一下谢谢
