### ISSUE TITLE
modal的style中设置top无效

### ISSUE THREAD

**Issue by linziguan** [vueComponent/ant-design-vue#2285]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win 10,chrome 70内核、vue 2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-3g2le?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在modal组件中设置style，里面设置top，当model显示时，没有显示在指定位置

### What is expected?
显示在top的指定位置

### What is actually happening?
没有显示在指定位置

**Comment by tangjinzhou** [comment]
使用 :wrapStyle="{ top: '20px' }" 替代

**Comment by linziguan** [comment]
试了，也没生效：
`https://codesandbox.io/s/vue-antd-template-3g2le?fontsize=14&hidenavigation=1&theme=dark`

**Comment by linziguan** [comment]
收到，感谢！求发小版本！
