### ISSUE TITLE
InputNumber在绑定了v-model后,无法重新输入新值

### ISSUE THREAD

**Issue by sunweizhe** [vueComponent/ant-design-vue#229]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.6

### Environment
Windows10 vue2.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-input-number/src/index.js](https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-input-number/src/index.js)

### Steps to reproduce
1.外部定时刷新数据 data1
2.设置InputNumber 的v-model=data1
3.change事件里经过运算更新data1(更新过程有1秒延时)
3.键盘更改InputNumber值时,由于change事件会导致输入2位数时,后一位输入不了

### What is expected?
暴露失去焦点这个事件,失去焦点后回调数值变化

### What is actually happening?
输入错误

**Comment by llabbss** [comment]
请问该issue有解决吗？我们也遇到相同问题， @tangjinzhou 给出的示例已经换成了datepick组件，无法查看正确的示例方案
