### ISSUE TITLE
ant  tree可搜索的树

### ISSUE THREAD

**Issue by nepenthedream** [vueComponent/ant-design-vue#2291]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我有上万条数据,多层结构树,搜索的时候递归比对让电脑cpu飙升卡死了,能用什么办法解决

### What does the proposed API look like?
如何在对大量数据进行搜索的时候不卡死

**Comment by hzyyy** [comment]
有个官方案例是针对这种业务场景的；不要一次性加载全部树数据，点击到某个树节点时，才请求这个树节点下的对应数据。

**Comment by nepenthedream** [comment]
你没发现你们官方搜索树的代码是先把树遍历成一层&nbsp;&nbsp;
const dataList = []; const generateList = data =&gt; {   for (let i = 0; i < data.length; i++) {     const node = data[i];     const key = node.key;     dataList.push({ key, title: key });     if (node.children) {       generateList(node.children);     }   } };
得出 dataList 这个所有树节点的数组
然后 去递归对比树节点是否含有这个传入的值
const getParentKey = (key, tree) =&gt; {   let parentKey;   for (let i = 0; i < tree.length; i++) {     const node = tree[i];     if (node.children) {       if (node.children.some(item =&gt; item.key === key)) {         parentKey = node.key;       } else if (getParentKey(key, node.children)) {         parentKey = getParentKey(key, node.children);       }     }   }   return parentKey; };


既然你已经得出了  dataList 这个所有树节点的数组
为什么不能用  includes() 这个方法去查找dataList这个数组  
如果dataList下标的titie包含有传入的值 那么取key值
还要去递归树结构呢????????










------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"He ZhangYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 中午11:31
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"Ten years like a dream"<2274366384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] ant  tree可搜索的树 (#2291)





 
有个官方案例是针对这种业务场景的；不要一次性加载全部树数据，点击到某个树节点时，才请求这个树节点下的对应数据。

**Comment by hzyyy** [comment]
呀，我不是官方人员，我只是一名普通的开发者。只不过看到你的issue，回答了下而已。

**Comment by nepenthedream** [comment]
好吧&nbsp; 你可以试试 他每次搜索递归的次数&nbsp; 一千多条数据会递归一千万次&nbsp; &nbsp;这逻辑感觉有点傻&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"He ZhangYu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月10日(星期三) 中午1:39
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"Ten years like a dream"<2274366384@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] ant  tree可搜索的树 (#2291)





 
呀，我不是官方人员，我只是一名普通的开发者。只不过看到你的issue，回答了下而已。

**Comment by davidduwei** [comment]
还不如用ztree，性能应该比这个好很多

**Comment by nepenthedream** [comment]
指定框架，要是能用其他的我还纠结这个干嘛------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;david&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年6月16日(星期二) 下午5:49
收件人:&nbsp;&quot;vueComponent/ant-design-vue&quot;<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;&quot;wsy&quot;<2274366384@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] ant  tree可搜索的树 (#2291)
