### ISSUE TITLE
请考虑在Table组件上，增加分页跳转前后，保存选中行的功能

### ISSUE THREAD

**Issue by tocz9es** [vueComponent/ant-design-vue#2299]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有功能需要收集 Table 选中行（有分页），再次输出到新Table中进行汇总。期间觉得 Table 组件可以增加分页跳转前后，保存选中行的功能。

目前 Table 组件在进行分页跳转前，需要通过其他操作变相保存行数据。否则在分页跳转后，会丢失之前选择的行数据。
该功能类似于 element Table 组件中的 reserve-selection 参数。

### What does the proposed API look like?
```
<a-table :reserve-selection="selections"></a-table>

data() {
return { selections: [] }
}

```

**Comment by Robin-zero** [comment]
+1

**Comment by sendya** [comment]
在你页面内部 data 下，存放你要的选中行即可。不需要由组件提供
