### ISSUE TITLE
a-table使用树形数据展示结合sorter排序，点击表头会出现死循环警告-----上次该issue被系统关闭了，并未实际解决

### ISSUE THREAD

**Issue by peinkid** [vueComponent/ant-design-vue#2300]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.5

### Environment
https://codesandbox.io/s/vue-antd-template-hhi0d

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-hhi0d)

### Steps to reproduce
死循环

### What is expected?
不死循环

### What is actually happening?
死循环

**Comment by tangjinzhou** [comment]
升级到 1.6.1
