### ISSUE TITLE
your webist use google ad will show pron pic

### ISSUE THREAD

**Issue by macheteHot** [vueComponent/ant-design-vue#2308]
你们的网站介入广告  会显示 15+ 广告

**Comment by sendya** [comment]
google 会为每一个用户生成唯一的广告id，你看见的广告都是根据你的访问习惯和偏好推荐的。

**Comment by jjandxa** [comment]
google 会为每一个用户生成唯一的广告id，你看见的广告都是根据你的访问习惯和偏好推荐的。
