### ISSUE TITLE
Option for custom rendering selected option

### ISSUE THREAD

**Issue by theonelucas** [vueComponent/ant-design-vue#2310]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Current I'm using the `a-select` component and I'm adding one image to the beginning of each option. When the user selects something, the image   text of the selected option is rendered to the select component. However, I want to render only the image, without the text. Currently the select component has the `optionLabelProp` that allows me to define what string to render when an option is selected, however it only allows me to pass a string value, and in my case I want to render an image. I carefully read the entire documentation and didn't find anything related to this, but I did notice that the react ant implementation already has this feature, so I would like to ask what is the current status of this feature in vuejs, if it is being worked on, in the backlog, or none at all, thanks.

### What does the proposed API look like?
This can easily be done with a slot template inside the `a-select-option`, where it would define how that option would be rendered in case it was selected, something like:

```
<a-select-option>
<template slot="selected">
{{ option.label }}
</template>
</a-select-option>
```

**Comment by mynetfan** [comment]
You mean like this? 
[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-5bo77?fontsize=14&hidenavigation=1&theme=dark)

**Comment by theonelucas** [comment]
That works, and that's how I'm currently working around it, but by doing that we are adding to the DOM `a*n` elements unnecessarily, where `a` is the `selected-show` element and `n` is the number of options.

**Comment by mynetfan** [comment]
Aha，I found a way like this:
[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-5bo77?fontsize=14&hidenavigation=1&theme=dark)
No css, but with the prop `optionLabelProp`

**Comment by theonelucas** [comment]
> Aha，I found a way like this:
> [![Edit Vue Antd Template](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/vue-antd-template-5bo77?fontsize=14&hidenavigation=1&theme=dark)
> No css, but with the prop `optionLabelProp`

The `optionLabelProp` can only take a string property, therefore we can't render any html with it.

**Comment by mynetfan** [comment]
> > Aha，I found a way like this:
> > [![Edit Vue Antd Template](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/vue-antd-template-5bo77?fontsize=14&hidenavigation=1&theme=dark)
> > No css, but with the prop `optionLabelProp`
> 
> The `optionLabelProp` can only take a string property, therefore we can't render any html with it.

`optionLabelProp`  is the name of property, and we can set the property as string or any other types,such as VNode. Please read the code of the example, the `title` and `label` of options is VNode.
