### ISSUE TITLE
寻找antd Icon组件的用法 ，期待回复，谢谢

### ISSUE THREAD

**Issue by marol1210** [vueComponent/ant-design-vue#2315]
无法正常使用a-icon组件

源代码：
> <ul>
>      <li v-for="menu of menus"><a-icon type="{{icon_type}}">{{menu.name}} </li>
> </ul> 

问题：
[antdv: Icon] Make sure that you provide correct `viewBox` prop (default `0 0 1024 1024`) to the icon.

**Comment by zkwolf** [comment]
你这icon_type是啥？你想:type="icon_type"?

**Comment by marol1210** [comment]
> 你这icon_type是啥？你想:type="icon_type"?

<ul>
     <li v-for="menu of menus"><a-icon type="home"> {{menu.name}} </li>
</ul>
