### ISSUE TITLE
寻找a-icon组件的用法.  Component use issue:  Icon，not work;  How the method of use 

### ISSUE THREAD

**Issue by marol1210** [vueComponent/ant-design-vue#2316]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
imac , microsoft  edge

### Reproduction link
[https://cdnjs.cloudflare.com/ajax/libs/ant-design-vue/1.5.3/antd.js](https://cdnjs.cloudflare.com/ajax/libs/ant-design-vue/1.5.3/antd.js)

### Steps to reproduce
1. include in page
https://cdnjs.cloudflare.com/ajax/libs/ant-design-vue/1.5.3/antd.js
https://cdnjs.cloudflare.com/ajax/libs/ant-design-vue/1.5.3/antd.min.css

2. Vue use
<templated id="vue_first">
<a-card title="报表统计">
<ul>
<li v-for="menu of menus"><a-icon type="{{icon_type}}">{{menu.name}} </li>
</ul>
</a-card>
</templated>

3. Consequent:
browser console show :
Warning: [antdv: Icon] Make sure that you provide correct `viewBox` prop (default `0 0 1024 1024`) to the icon

### What is expected?
use normal

### What is actually happening?
browser console show :
Warning: [antdv: Icon] Make sure that you provide correct `viewBox` prop (default `0 0 1024 1024`) to the icon

**Comment by tangjinzhou** [comment]
提供有效的复现示例

**Comment by marol1210** [comment]
@tangjinzhou 

感谢.
  
是我的问题，标签`<a-icon>`应该是个空标签；


![image](https://user-images.githubusercontent.com/7519301/83382244-4826eb00-a415-11ea-99fa-fd261c2d3252.png)
