### ISSUE TITLE
异步加载select值，内容显示异常

### ISSUE THREAD

**Issue by TioJS** [vueComponent/ant-design-vue#2317]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
windows10@1909,chrome@81.0.4044.122,vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-cdn-vptyy?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/boring-cdn-vptyy
尝试选中一个值

### What is expected?
正常显示

### What is actually happening?
选中对象的key出现一会后才显示期望显示的内容

**Comment by TioJS** [comment]
@tangjinzhou 官方可以帮忙确认一下吗0.0我感觉是个bug

**Comment by sendya** [comment]
@TioJS 你的 handleDropdown 会在点的时候又执行一次， select option 全部又会重新渲染。不存在组件 bug

**Comment by TioJS** [comment]
感谢官方指正！
