### ISSUE TITLE
Website not loading

### ISSUE THREAD

**Issue by incompletude** [vueComponent/ant-design-vue#2319]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
Browser

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
Enter the website.

### What is expected?
To load the website.

### What is actually happening?
Not loading.

**Comment by vietanhbui** [comment]
somtimes at night
