### ISSUE TITLE
分页可以点击两个

### ISSUE THREAD

**Issue by ankeji** [vueComponent/ant-design-vue#2321]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
只有截图

### Reproduction link
[https://www.antdv.com/components/pagination-cn/](https://www.antdv.com/components/pagination-cn/)

### Steps to reproduce
按着ctrl点击，悬浮

### What is expected?
只有截图

### What is actually happening?
连个截图都不能上传怎样能说的明白呢

![image](https://user-images.githubusercontent.com/48073752/83218512-a0a18280-a1a0-11ea-85bc-33e8c21015a0.png)
![image](https://user-images.githubusercontent.com/48073752/83218513-a13a1900-a1a0-11ea-8857-c4eff8de8a4a.png)
![image](https://user-images.githubusercontent.com/48073752/83218514-a1d2af80-a1a0-11ea-8508-8c2495d4a0d8.png)
![image](https://user-images.githubusercontent.com/48073752/83218516-a26b4600-a1a0-11ea-9021-e6745969e210.png)
![image](https://user-images.githubusercontent.com/48073752/83218517-a26b4600-a1a0-11ea-8e80-4cc384cec35e.png)
![image](https://user-images.githubusercontent.com/48073752/83218518-a303dc80-a1a0-11ea-8a25-c0252d0a0274.png)

**Comment by tangjinzhou** [comment]
这是 focus 状态
