### ISSUE TITLE
Select displays empty option labels with incorrect height

### ISSUE THREAD

**Issue by rathga** [vueComponent/ant-design-vue#2326]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
All

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-xv9tk?file=/src/App.vue)

### Steps to reproduce
Create an <a-select> with an <a-select-option> with a value that has an empty string.

### What is expected?
The dropdown should show the label for the empty option with the same height as all other options.

### What is actually happening?
The height of the empty option is minimal, and it is hard to see.

---
Adding a non-breaking space corrects the behaviour.  This should be done automatically.

**Comment by tangjinzhou** [comment]
you can custom css 
```css
.ant-select-dropdown-menu-item {
  min-height: 32px;
}
```

**Comment by rathga** [comment]
Sorry, Why was the issue closed? If this is the fix should it not be incorporated in a pull request so people do not need to use a workaround?
