### ISSUE TITLE
Table, slot=expandIcon And prop=expandIconColumnIndex not working

### ISSUE THREAD

**Issue by MiceLiD** [vueComponent/ant-design-vue#2328]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://ant-design-vue.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by BetwayM** [comment]
用Function(props):VNode方法；亲测可用
<a-table
:expandIcon="props => customExpandIcon(props)"
  />
<script>
export default {
methods:{
 customExpandIcon:function(props) {
      if (props.expandable) {
        //根节点
        if (props.expanded) {
          //是否已经展开
          //已经展开
          return (
            <a-button
              shape="circle"
              type="white"
              onClick={e => {
                props.onExpand(props.record, e);
              }}
              icon="caret-down"
            ></a-button>
          );
        } else {
          //未展开
          return (
            <a-button
              shape="circle"
              type="white"
              onClick={e => {
                props.onExpand(props.record, e);
              }}
              icon="caret-right"
            ></a-button>
          );
        }
      } else {
        //叶子节点，不显示按钮
        return <a-icon style="margin-left:32px;" />; //占位
      }
    }
}
}
