### ISSUE TITLE
Could you make a-tree-menu component?

### ISSUE THREAD

**Issue by suwanuo** [vueComponent/ant-design-vue#2329]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Loop through the navigation tree menu

### What does the proposed API look like?
:menuData

const menuData =[
{
key: '1',
title: 'Option 1',
},
{
key: '2',
title: 'Navigation 2',
children: [
{
key: '2.1',
title: 'Navigation 3',
children: [{ key: '2.1.1', title: 'Option 2.1.1' }],
},
],
},
]

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/tree/#ReplaceFields
