### ISSUE TITLE
tree组件无法渲染tree数据节点

### ISSUE THREAD

**Issue by qifengwangye** [vueComponent/ant-design-vue#233]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.6

### Environment
ant-design-vue: 1.1.1; babel-plugin-import: 1.9.1; vue: 2.5.2

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/tree-cn/](https://vuecomponent.github.io/ant-design-vue/components/tree-cn/)

### Steps to reproduce
使用tree组件的时候，DOM节点渲染成为：
<ul role="tree-node" unselectable="on" class="ant-tree" treedata="[object Object]"></ul>
treedata是正确的Array格式数据。
查看源码在tree的index.js文件中貌似没有发现treedata接口，请问是否是bug，或者是我使用错误？

### What is expected?
能正确的展示出树状数据节点

### What is actually happening?
未能正确的展示出树状数据节点

---
项目十分紧急，请尽快帮忙查看一下，谢谢支持

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/47485219-462b9c00-d870-11e8-83b7-33dffb5ed9d1.png)
