### ISSUE TITLE
adaptiveHeight 注释

### ISSUE THREAD

**Issue by fenglingcong** [vueComponent/ant-design-vue#2332]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
vue

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-slick/src/default-props.js#L3](https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-slick/src/default-props.js#L3)

### Steps to reproduce
打开链接即可看到

### What is expected?
adaptiveHeight 建议注释为“自适应高度”

### What is actually happening?
adaptiveHeight 自适应高度

**Comment by tangjinzhou** [comment]
所以，什么问题？

**Comment by fenglingcong** [comment]
自定义高度  建议改为 自适应高度  更好理解
