### ISSUE TITLE
select value值相同时出现bug

### ISSUE THREAD

**Issue by dafeixiong0v0** [vueComponent/ant-design-vue#2337]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
Vue 2.X

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-frog-2rm6e?file=/src/App.vue)

### Steps to reproduce
<a-select placeholder="" v-model="form.dName" mode="tags" style="width: 200px">
<a-select-option v-for="item in [{id:1,val:'张三'},{id:2,val:'张三'},{id:3,val:'李四'}]" :key="item.id" :label="item.val" :value="item.id">
{{item.val}}
</a-select-option>
</a-select>

### What is expected?
解决当value的值出现相同时防止出错

### What is actually happening?
app.js:315089 [Vue warn]: Duplicate keys detected: '张三'. This may cause an update error.

found in

---> <Select>
<ASelect>

**Comment by yangy9593** [comment]
你写的有问题。你两个Select的value都是张三，当然会选中两个，你可以把id作为value，或者修改list中val的值。
