### ISSUE TITLE
dropdown点击弹出菜单后菜单自动隐藏但没有触发visibleChange事件

### ISSUE THREAD

**Issue by mkanako** [vueComponent/ant-design-vue#2342]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
Chrome last version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vuy6m)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-vuy6m
就官网的例子，点击弹出菜单后菜单自动隐藏但没有触发visibleChange事件

### What is expected?
这算是bug还是预期行为

### What is actually happening?
这算是bug还是预期行为

**Comment by fearclear** [comment]
预期行为，参见<https://github.com/ant-design/ant-design/issues/4994>

**Comment by mkanako** [comment]
@fearclear 原来如此，谢了
