### ISSUE TITLE
ES6方式引用moment报错

### ISSUE THREAD

**Issue by usherwong** [vueComponent/ant-design-vue#2344]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
mac 10.14.6 ,vue version: 2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/new?template=----please-use-new-issue-ant-design-vue---.md](https://github.com/vueComponent/ant-design-vue/issues/new?template=----please-use-new-issue-ant-design-vue---.md)

### Steps to reproduce
ES6方式引用moment报错
import * as moment from 'moment'
应该改成 import moment from 'moment/src/moment'
否则会报错
client:135 ./node_modules/ant-design-vue/es/calendar/index.js 28:11-26
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 8:56-71
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 18:31-46
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 31:31-46

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 34:58-73
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/lingmao/LIMO/node_modules/ant-design-vue/node_modules/moment/src/lib/locale'

### What is expected?
正常引用moment

### What is actually happening?
报错
client:135 ./node_modules/ant-design-vue/es/calendar/index.js 28:11-26
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 8:56-71
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 18:31-46
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 31:31-46

client:135 ./node_modules/ant-design-vue/es/_util/moment-util.js 34:58-73
"export 'isMoment' (imported as 'moment') was not found in 'moment'

client:135 ./node_modules/ant-design-vue/node_modules/moment/src/lib/locale/locales.js
Module not found: Error: Can't resolve './locale' in '/Users/lingmao/LIMO/node_modules/ant-design-vue/node_modules/moment/src/lib/locale'

**Comment by hzyyy** [comment]
试试：
import moment from 'moment';
