### ISSUE TITLE
DatePicker 日期选择框 不能设置弹出日期选择面板的类型

### ISSUE THREAD

**Issue by Bourne115** [vueComponent/ant-design-vue#235]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我在项目中有个需求是 用户只按月份 或者 按年份 查询  然而 日期选择框 不能定义 我要使用什么类型的选择面板

### What does the proposed API look like?
Vue版本

**Comment by Bourne115** [comment]
我在项目中有个需求是 用户只按月份 或者 按年份 查询 然而 日期选择框 不能定义 我要使用什么类型的选择面板

**Comment by tangjinzhou** [comment]
目测Select组件可以满足你的需求
