### ISSUE TITLE
颜色选择器

### ISSUE THREAD

**Issue by hj2252796369** [vueComponent/ant-design-vue#2353]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在使用AntUi时，发现需要使用到颜色选择器。但是官方没有提供，使用其他基于vue开发的颜色选择器，和官方提供的样式有冲突，所以希望官方能够开发新功能

### What does the proposed API look like?
自己选择颜色和透明度

**Comment by LOUSANPANG** [comment]
+1

**Comment by tangjinzhou** [comment]
ref #2305
