### ISSUE TITLE
Upload上传文件 promise方式不生效

### ISSUE THREAD

**Issue by bigarmy2020** [vueComponent/ant-design-vue#2358]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
os: 10.15.5, chrome: 83.0.4103.61, vue: 2.6.11

### Reproduction link
[https://github.com/bigarmy2020/upload-demo](https://github.com/bigarmy2020/upload-demo)

### Steps to reproduce
```js
<a-upload-dragger
:name="name"
:action="uploadAction"
:headers="headers"
:data="{ biz: bizPath }"
:disabled="disabled"
:multiple="isMultiple"
:file-list="fileList"
:default-value="fileList"
:class="{ 'has-error': hasError }"
:beforeUpload="innerBeforeUpload"
@preview="handlePreview"
@change="handleChange"
>

innerBeforeUpload(file) {
return new Promise((resolve, reject) => {
this.$message.error('上传图片格式不对!');
return reject(false);
});
},
```

![结果地址](https://user-images.githubusercontent.com/65111062/83715084-27ea6c80-a65f-11ea-9cd9-1764f0a2271e.png)

### What is expected?
期望reject 能阻止上传

### What is actually happening?
BeforeUpload 用 promise写死 未能成功阻止

**Comment by workwsl** [comment]
我这边是reject 可以阻止上传，但是 return resolve(true) 的时候，选择多张图片时，只上传最后一张。
