### ISSUE TITLE
第一次点击 a-dropdown 时，a-menu slot="overlay" 位置错位

### ISSUE THREAD

**Issue by mxue12138** [vueComponent/ant-design-vue#2359]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
操作系统：macOS Mojave 10.14.6。浏览器：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36。Vue：2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-qlnjt)

### Steps to reproduce
第一次点击菜单时位置会错位，但是之后点击位置就正常了，，，每次刷新后第一次点击都会这样错误

### What is expected?
期望下拉菜单显示在正确的位置

### What is actually happening?
实际显示的位置错位，一般错位在右侧

**Comment by nooldey** [comment]
https://codesandbox.io/s/antd-vue-w0i9g?file=/src/App.vue

类似问题：
初始化设置placement=bottomCenter;
首次展开，menu位置在相对title居中，正常；
第二次展开，menu位置在相对title左侧，错位；
