### ISSUE TITLE
Table: Fully Customizable Column Header Box ?

### ISSUE THREAD

**Issue by kaankucukx** [vueComponent/ant-design-vue#2367]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I want to access every property defined for column object, but below workaround don't let me access anything or I don't know how to access it.
```javascript
<span slot="customTitle" slot-scope="{ some }">{{ some }} Name
<Component :is="'a-input'" /> // I want to switch between components dynamcly with the given `column.someProperty.bla.bla`
</span>
```

Whit this approach I can display any component/data on the header to extend the usability of the table.

### What does the proposed API look like?
I have no other than documentation of antd-vue. Yet, I can say that the documentation is week regarding scope props vs.

**Comment by kaankucukx** [comment]
Is there a way to access column props on header cells ?

**Comment by kaankucukx** [comment]
found a way to manage columns with **slot: {title: blaBla}**

**Comment by CHOMNANP** [comment]
Hi @kaankucukx, can you share a snip of code that you manage to customize the header of the table?
