### ISSUE TITLE
Spin 组件的 wrapperClassName 属性问题

### ISSUE THREAD

**Issue by jihainan** [vueComponent/ant-design-vue#2375]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
chrome81、vue2.5.22

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/releases/tag/1.5.4](https://github.com/vueComponent/ant-design-vue/releases/tag/1.5.4)

### Steps to reproduce
使用 wrapperClassName 属性仅定义了外层容器的类名，内部还有一层类名叫做 ant-spin-container 的容器，如果通过 wrapperClassName 属性定义的类名来声明样式，无法保证内层的 ant-spin-container 容器中的内容与声明的样式保持一直。简单来说，就是无法定义类名为 ant-spin-container 的容器的样式。

### What is expected?
提供接口定义类名为 ant-spin-container 的容器的样式。

### What is actually happening?
无法定义类名为 ant-spin-container 的容器的样式，导致Spin组件包裹的内容显示的样式有问题，尤其是内容的高度。

**Comment by sendya** [comment]
css `.classname >>> .ant-spin-container {  }`
less / scss `.classname /deep/ .ant-spin-container {  }`

**Comment by jihainan** [comment]
> css `.classname >>> .ant-spin-container { }`
> less / scss `.classname /deep/ .ant-spin-container { }`

谢谢，这样确实是可以的，只是觉得这样用起来不是太方便

**Comment by ccccc996** [comment]
这个组件可以修改背景色吗，这个背景色默认的是白色+透明度，需求是黑色+透明度怎么调整呀
