### ISSUE TITLE
1.6.2 modal 添加getContainer失效

### ISSUE THREAD

**Issue by dothin** [vueComponent/ant-design-vue#2378]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
谷歌最新版，VUE2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-leftpad-j3ef9?file=/src/components/HelloWorld.vue)

### Steps to reproduce
modal添加:get-container="() => document.body"后报错
Property or method "document" is not defined on the instance but referenced during render.

### What is expected?
可以指定get-container="() => document.getElementById('test')"

### What is actually happening?
Property or method "document" is not defined on the instance but referenced during render.

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/restless-bush-4yd27
