### ISSUE TITLE
Progress 进度条的API里的strokeColor参数使用了不生效！

### ISSUE THREAD

**Issue by zhumumu1992** [vueComponent/ant-design-vue#238]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
macOS Mojave 10.14，Google Chrome 70.0.3538.77，vue:2.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqzjw9nn9x)

### Steps to reproduce
<a-progress type="circle" :percent="75" strokeColor="#4dc600"/>

### What is expected?
请帮忙测试下是我使用方法错了，还是antD vue的bug，如果是bug请尽快修复，谢谢。

### What is actually happening?
Progress 进度条的API里的strokeColor参数使用了不生效！
element的Progress组件的color属性用起来是正常的。

**Comment by tangjinzhou** [comment]
可以先使用css覆盖完成功能，
后续我们会修复

**Comment by zhumumu1992** [comment]
> 可以先使用CSS覆盖完成功能，
> 后续我们会修复
好的，蟹蟹😋

**Comment by chenjiajing23** [comment]
进度条成功的颜色希望可以动态更改successPercent 想storeColor一样
