### ISSUE TITLE
Select 组件 dropdownRender 中无法使用 input，点击后就隐藏

### ISSUE THREAD

**Issue by callcter** [vueComponent/ant-design-vue#2380]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
vue 2.6.11

### Reproduction link
[https://www.antdv.com/components/select-cn/#API](https://www.antdv.com/components/select-cn/#API)

### Steps to reproduce
dropdownRender 中使用 input

### What is expected?
与 Ant-Design React 版本表现一致

### What is actually happening?
点击输入框，弹出的选择框隐藏

**Comment by mynetfan** [comment]
https://www.antdv.com/components/dropdown-cn/#components-dropdown-demo-the-way-of-hiding-menu.
