### ISSUE TITLE
自定义组件的prop设置了default导致warning： please use `option.initialValue` to set default value.

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue#2387]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.0

### Environment
windows10,google chrome 79.0.3945.130,vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-qjid8?file=/src/App.vue)

### Steps to reproduce
在输入框中输入

### What is expected?
无任何警告

### What is actually happening?
Warning: CustomInput `default value` can not collect,  please use `option.initialValue` to set default value.

---
https://github.com/vueComponent/ant-design-vue/issues/1076 看issue是修复过了，但还是有warning

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/84100868-53929b80-aa3f-11ea-8893-b7aad676cacf.png)
