### ISSUE TITLE
表格中带input框复制代码到项目中报错

### ISSUE THREAD

**Issue by lihanyi010203** [vueComponent/ant-design-vue#2388]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
node版本12.16.3  谷歌浏览器83.0.4103.97（正式版本） （64 位）  vue版本2.6.11

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
可编辑单元格的带表格编辑功能  把代码直接复制到项目中  直接报错

vue.runtime.esm.js?2b0e:619 [Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <EditableCell>
<TableCell>
<BodyRow>
<TableRow>
<ConnectTableRow>
<ProxyConnectTableRow>
<ExpandableRow>
<ConnectExpandableRow>
<ProxyConnectExpandableRow>
<BaseTable>
<ConnectBaseTable>
<ProxyConnectBaseTable>
<BodyTable>
<ExpandableTable>
<ConnectExpandableTable>
<ProxyConnectExpandableTable>
<StoreProvider>
<Table>
<Table>
<LocaleReceiver>
<ASpin>
<Table>
<ATable>
<Anonymous>
<Index> at src/views/basicBataMaintenance/index.vue
<Anonymous>
<ALayoutContent>
<Anonymous>
<ALayout>
<Anonymous>
<ALayout>
<Index> at src/views/index.vue
<ALocaleProvider>
<LocaleReceiver>
<AConfigProvider>
<App> at src/App.vue
<Root>

### What is expected?
不错报 可以使用就可以

### What is actually happening?
报错

**Comment by sendya** [comment]
请提供复现，谢谢

**Comment by tangjinzhou** [comment]
https://github.com/vuejs/vue-cli/issues/2754
