### ISSUE TITLE
Modal 频繁报 Failed to resolve directive: ant-portal

### ISSUE THREAD

**Issue by tangtaoshadow** [vueComponent/ant-design-vue#2394]
## 求问：打开modal或关闭modal时都报出这个warning
```bash
vue.runtime.esm.js?2b0e:619 [Vue warn]: Failed to resolve directive: ant-portal
(found in <Anonymous>)
```
## modal打开方式
```js
modal.info({
  title: '修改的标题',
  content: '修改的内容',
});
```

## 还有弹出modal时有动画 关闭时立即关闭，没有动画，不知道是什么原因，🙏🙏

**Comment by jiaxin-MXX** [comment]
在main.js里面写Vue.use(Modal)应该就不会报ant-portal错误了

**Comment by hqzh** [comment]
其实就是在按需引入的常用写法中没有调用到Vue.use所执行的自定义指令，最多就在引入部分加两行代码就能解决

import Vue from 'vue'
Modal.install(Vue)
