### ISSUE TITLE
浏览器引用antd.js（v1.6.2），使用“Slider滑动输入条”的afterChange事件无效

### ISSUE THREAD

**Issue by FeiJerry** [vueComponent/ant-design-vue#2397]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
Vue.js v2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/2396](https://github.com/vueComponent/ant-design-vue/issues/2396)

### Steps to reproduce
```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./js/Vue/vue.js"></script>
    <script src="./js/antd/antd.js"></script>
    <link rel="stylesheet" href="./css/antd/antd.css">
    <style scoped>
        .code-box-demo .ant-slider {
            margin-bottom: 16px;
        }
    </style>
</head>

<body>
    <div id="app">
        <template>
            <div class="code-box-demo">
                <a-slider :default-value="30" @change="onChange" @afterChange="onAfterChange" />
            </div>
        </template>
    </div>

</body>
<script>
    var app = new Vue({
        el: '#app',
        data() {
            return {
                disabled: false,
            };
        },
        methods: {
            onChange(value) {
                console.log('change: ', value);
            },
            onAfterChange(value) {
                console.log('afterChange: ', value);
            },
        },
    });
</script>

</html>

```
### What is expected?
onAfterChange有效执行。

### What is actually happening?
Event "afterchange" is emitted in component <CreateSlider> but the handler is registered for "afterChange".

---
在vue.js(v2.6.11)中
var lowerCaseEvent = event.toLowerCase();
if (lowerCaseEvent !== event && vm._events[lowerCaseEvent]) { ****}
将afterChange事件过滤了。JSON.stringify(vm._events)=="{"change":[null],"afterchange":[null]}"

**Comment by tangjinzhou** [comment]
html中不支持大写，
可以使用 https://github.com/vueComponent/vue-dash-event 兼容
