### ISSUE TITLE
a-form-item包裹a-row时，获取不到表单值

### ISSUE THREAD

**Issue by dongnaebi** [vueComponent/ant-design-vue#240]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
all new

### Reproduction link
[http://sorry.com](http://sorry.com)

### Steps to reproduce
```html
<a-form-item fieldDecoratorId="verifyCode" :fieldDecoratorOptions="{rules: [{ required: true, message: '请输入短信验证码', whitespace: true}]}">
  <a-row>
    <a-col :span="16">
      <a-input size="large" placeholder="短信验证码">
        <a-icon slot="prefix" type="code-o" />
      </a-input>
    </a-col>
    <a-col :span="8">
      <a-button size="large" class="margin-left" :disabled="sendText!='获取验证码'&&sendText!='重新获取'" @click="sendCode">{{sendText}}</a-button>
    </a-col>
  </a-row>
</a-form-item>
```
```javascript
console.log(this.form.getFieldValue('verifyCode')) // undefined
```
并且表单非空验证也通不过

### What is expected?
可以获取到值

### What is actually happening?
试了其他元素，input被div和a-card包裹时，都能正常获取到，1.1.6也存在这个问题

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/ant-design-vue/components/form-cn/#autoFormCreate
![image](https://user-images.githubusercontent.com/6937879/47695258-27e0ea00-dc3c-11e8-8507-4b41e913332a.png)
另外：为啥还要用a-row a-col包裹，本身form-item就可以满足这些布局需求

**Comment by dongnaebi** [comment]
thx
