### ISSUE TITLE
formModel中一个表单控件包含两个字段时，prop属性绑定？

### ISSUE THREAD

**Issue by UgineHuang** [vueComponent/ant-design-vue#2403]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
一个表单控件包含两个字段，如组合输入框，对应input为表单对象的一个变量，前缀slot里的select也是表单对象的一个变量。那对应包含这个控件的
a-form-model-item的prop属性应该如何绑定，才能让两个字段都被form-model纳入。现状：只绑定其中一个，另一个是会被忽略的
<a-input
v-model="formData[item.field[0]]"
>
<a-select
slot="addonBefore"
v-model="formData[item.field[1]]"
>
<a-select-option :value="1">
按名称搜索
</a-select-option>
<a-select-option :value="2">
按ID搜索
</a-select-option>
</a-select>
<a-icon slot="prefix" type="search" />
</a-input>

### What is expected?
让两个字段都被form-model纳入，可以触发校验和重置等方法

### What is actually happening?
只绑定其中一个，另一个是会被忽略的

**Comment by jinan5694** [comment]
文档里写了
