### ISSUE TITLE
Descriptions Style Error

### ISSUE THREAD

**Issue by lavecoral** [vueComponent/ant-design-vue#2404]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
Firefox 76.0.1 (64 位） Vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-l3xyr?file=/src/App.vue)

### Steps to reproduce
Step1: a-descriptions does not set bordered
Step2:  a-descriptions-item has span set and the value is 2. And the a-descriptions-item will not be the first column when there are multiple columns
Step 3: drag the browser and adjust the browser resolution to two columns in the description list

第1步 a-descriptions不设置 bordered
第2步 a-descriptions-item 设置了span，值为2。且该 a-descriptions-item 在多列时不会是第一列
第3步： 拖拽浏览器，将浏览器分辨率调整到描述列表为两列时

### What is expected?
Columns 1 and 2 are the same width

两列时，列的宽度相等

### What is actually happening?
The width of columns 1 and 2 are not equal

第1列和第2列的宽度不相等

**Comment by lavecoral** [comment]
Step 3: drag the browser and adjust the browser resolution to two columns in the description list

第3步： 拖拽浏览器，将浏览器分辨率调整到描述列表为两列时

**Comment by ununian** [comment]
![image](https://user-images.githubusercontent.com/4506072/84476165-57812080-acc0-11ea-852d-62fb5dbb0814.png)
我这里没办法复现

**Comment by lavecoral** [comment]
补充复现的结果：
```
  <a-descriptions title="User Info">
    <a-descriptions-item label="Product">Cloud Database</a-descriptions-item>
    <a-descriptions-item label="Billing Mode">Prepaid</a-descriptions-item>
    <a-descriptions-item label="Automatic Renewal">YES</a-descriptions-item>
    <a-descriptions-item label="Usage Time" :span="2">2019-04-24 18:00:00</a-descriptions-item>
    <a-descriptions-item label="Order time">2018-04-24 18:00:00</a-descriptions-item>
    <a-descriptions-item label="Status">
      <a-badge status="processing" text="Running"/>
    </a-descriptions-item>
  </a-descriptions>
```
三列： 
![图片](https://user-images.githubusercontent.com/2811324/84493149-e189b300-acd9-11ea-8508-e7b97d2c76c5.png)

浏览器宽度减小，变为两列时

![图片](https://user-images.githubusercontent.com/2811324/84493216-ff571800-acd9-11ea-9ad2-1ff4fb8d21c4.png)
![图片](https://user-images.githubusercontent.com/2811324/84493282-16960580-acda-11ea-9185-7339d88548ab.png)
![图片](https://user-images.githubusercontent.com/2811324/84493301-20b80400-acda-11ea-8af2-e9e6e7b8fa59.png)

**Comment by lavecoral** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/4506072/84476165-57812080-acc0-11ea-852d-62fb5dbb0814.png)
> 我这里没办法复现

您不觉得两列的宽度不对吗？

**Comment by ununian** [comment]
你不是设置了time那行要夸2格吗？
