### ISSUE TITLE
Drawer 第二次打开时 maskStyle 样式被清除

### ISSUE THREAD

**Issue by PanStar** [vueComponent/ant-design-vue#2407]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
Chrome 81.0.4044.92

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdv-drawer-maskstyle-mj2j2)

### Steps to reproduce
[https://codesandbox.io/s/antdv-drawer-maskstyle-mj2j2](https://codesandbox.io/s/antdv-drawer-maskstyle-mj2j2)

第一次打开，样式正常
第二次打开，遮罩样式中的 left 和 width 被清除了

### What is expected?
It's normal when depend by ant-design-vue@1.6.2

### What is actually happening?
It is not work when depend by ant-design-vue@1.6.2.
But, it's normal in ant-design-vue@1.4.12.

**Comment by ununian** [comment]
我试了下是1.5出来的bug
应该是下面这个代码的问题

https://github.com/vueComponent/ant-design-vue/blob/5108f67c11edbc3ae3e26091d7b9eaabf82d0516/components/vc-drawer/src/Drawer.js#L171-L177

我不是很清楚这段代码的作用
