### ISSUE TITLE
同一组件样式没有统一

### ISSUE THREAD

**Issue by seafronthu** [vueComponent/ant-design-vue#2413]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
版本 83.0.4103.61（正式版本） （64 位）

### Reproduction link
[https://www.antdv.com/components/form-model-cn/#components-form-model-demo-validation](https://www.antdv.com/components/form-model-cn/#components-form-model-demo-validation)
[https://www.antdv.com/components/checkbox-cn/#components-checkbox-demo-checkbox-group](https://www.antdv.com/components/checkbox-cn/#components-checkbox-demo-checkbox-group)

### Steps to reproduce
```
// Checkbox
.ant-checkbox-wrapper .ant-checkbox-wrapper {
margin-left: 8px;
}
```
```
//FormModel -> Checkbox
ant-checkbox-group-item .ant-checkbox-group-item {
margin-left: 0;
}
.ant-checkbox-wrapper .ant-checkbox-wrapper {
margin-left: 8px;
}
.ant-checkbox-group-item {
display: inline-block;
margin-right: 8px;
}
```

### What is expected?
我在FormModel使用checkbox组件的时候出现与单独使用checkbox样式统一

### What is actually happening?
我在FormModel使用checkbox组件的时候出现与单独使用checkbox样式不同一

**Comment by xrkffgg** [comment]
没明白有啥问题？哪里不一样？
