### ISSUE TITLE
使用v-for渲染的菜单key值问题与默认选中问题

### ISSUE THREAD

**Issue by skytot** [vueComponent/ant-design-vue#242]
使用v-for 渲染菜单
```
<a-menu theme="dark" :defaultSelectedKeys="defaultKey" mode="inline">
            <a-menu-item :key="item.key" v-for="item in menus" v-if="item.leaf">
                <router-link :to="item.path" :data-keys="item.key">
                    <a-icon :type="item.meta.icon" />{{item.meta.title}}</router-link>
            </a-menu-item>
            <a-sub-menu :key="item.key" v-for="item in menus" v-if="!item.leaf">
                <span slot="title">
                    <a-icon :type="item.meta.icon" /><span>{{item.name}}</span></span>
                <a-menu-item :key="itm.Key" v-for="itm in item.children">
                    <router-link :to="itm.path">
                        {{itm.name}}
                    </router-link>
                </a-menu-item>
            </a-sub-menu>
        </a-menu>
```
默认选中通过计算赋值到defaultKey；

在页面按f5刷新后，无法正确赋值二级菜单的默认选中

使用插件查看组件的默认key值

![tim 20181031171220](https://user-images.githubusercontent.com/22675843/47777647-2690e980-dd30-11e8-88f3-cd48d3b38f8a.png)

如上图，key为“__vlist_2_1__ ”模式而非上级菜单的形如“2”的字符串模式；

是否我想默认选中菜单的子菜单只能通过字符串组合成类似“__vlist_2_1__”的结构并且把对应的菜单的key赋值defaultOpenKeys默认展开？

建议：key为“1”与“1-1”格式

**Comment by zzc5464** [comment]
这个问题解决了吗。。
a-menu 无法动态设置 defaultSelectedKeys

**Comment by qianduanwuzi** [comment]
> 这个问题解决了吗。。
>\

**Comment by qianduanwuzi** [comment]
@zzc5464 a-menu 无法动态设置 defaultSelectedKeys这问题解决了嘛

**Comment by tangjinzhou** [comment]
@zzc5464 @qianduanwuzi https://vue.ant.design/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by mars-ou** [comment]
`:defaultSelectedKeys="defaultKey"`里面绑定的是数组，里面的项是String，而你`:key="item.key"`绑定的是key应该是Number，所以你`:key="item.key"`可以改成`:key="item.key" + ''`
