### ISSUE TITLE
使用 cascader 出错

### ISSUE THREAD

**Issue by HealingW** [vueComponent/ant-design-vue#2428]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
macos 10.15.4,gooogle chorme 83.0.4103.97, vue 2.6.11

### Reproduction link
[https://www.antdv.com/components/cascader-cn/](https://www.antdv.com/components/cascader-cn/)

### Steps to reproduce
<template>
<a-cascader :options="options" placeholder="Please select" @change="onChange" />
</template>
<script>
export default {
data () {
return {
options: [
{
value: 'zhejiang',
label: 'Zhejiang',
children: [
{
value: 'hangzhou',
label: 'Hangzhou',
children: [
{
value: 'xihu',
label: 'West Lake'
}
]
}
]
},
{
value: 'jiangsu',
label: 'Jiangsu',
children: [
{
value: 'nanjing',
label: 'Nanjing',
children: [
{
value: 'zhonghuamen',
label: 'Zhong Hua Men'
}
]
}
]
}
]
}
},
methods: {
onChange (value) {
console.log(value)
}
}
}
</script>

### What is expected?
[Vue warn]: Unknown custom element: <a-cascader> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

### What is actually happening?
啥都没有

**Comment by tangjinzhou** [comment]
提供有效的复现demo

**Comment by HealingW** [comment]
粘贴的 template 标签内容未显示。开发环境如上，直接粘贴级联选择框的 demo，在网页上无法显示，控制台提示没有组件的实例，我直接 引入 ant-design-vue/lib/cascader 这个组件也无法正常显示。

**Comment by guodh1** [comment]
@HealingW 请问解决了吗，我也遇到一样的错误
