### ISSUE TITLE
无法直接获取select组件当前选项？？？？

### ISSUE THREAD

**Issue by CodeMan-P** [vueComponent/ant-design-vue#2437]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
无法直接获取select组件当前选项？？？？

### What does the proposed API look like?
无法直接获取select组件当前选项？？？？

**Comment by JamesChen111** [comment]
我也遇到了这个问题，你解决了吗？

**Comment by CodeMan-P** [comment]
没有，注册change事件获取吧。

**Comment by sendya** [comment]
v-model / :value 任意一个的绑定值均是你当前项， vue 是数据驱动框架

**Comment by CodeMan-P** [comment]
刚又看了下这个问题，v-model可以获取当前选项。
“value(v-model) | 指定当前选中的条目”
之前翻文档没看到这句呀，是最近更新了吗。
