### ISSUE TITLE
table 中使用树形数据的展示 通过 slot 自定义展开图标 expandIcon 不起作用

### ISSUE THREAD

**Issue by 296604153** [vueComponent/ant-design-vue#2443]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
window 10， Chrome 79.0.3945.88，Vue ^2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-3e370?file=/src/App.vue)

### Steps to reproduce
增加 expandIcon  slot 后无效果

### What is expected?
提供了 codesandbox页面 复现问题

### What is actually happening?
bug

**Comment by BetwayM** [comment]
用Function(props):VNode方法；亲测可用
<a-table
:expandIcon="props => customExpandIcon(props)"
  >
<script>
export default {
methods:{
 customExpandIcon:function(props) {
      if (props.expandable) {
        //根节点
        if (props.expanded) {
          //是否已经展开
          //已经展开
          return (
            <a-button
              shape="circle"
              type="white"
              onClick={e => {
                props.onExpand(props.record, e);
              }}
              icon="caret-down"
            ></a-button>
          );
        } else {
          //未展开
          return (
            <a-button
              shape="circle"
              type="white"
              onClick={e => {
                props.onExpand(props.record, e);
              }}
              icon="caret-right"
            ></a-button>
          );
        }
      } else {
        //叶子节点，不显示按钮
        return <a-icon style="margin-left:32px;" />; //占位
      }
    }
}
}
//希望帮到你，哈哈

**Comment by zhuyunzhang** [comment]
1.6.1 版本中 expandIcon方法删除了，我并没有找到，之前的老版本是可以用的，可以试试1.3.17版本，请问在新版本中有什么好的方法可以实现table 自定义展开图标嘛？

**Comment by 296604153** [comment]
@BetwayM 谢谢 我试试
