### ISSUE TITLE
Collapse 设置 extra slot 按钮后，点击事件与折叠面板的panel header 点击事件重合，即使加入了preventDefault也会冒泡出去

### ISSUE THREAD

**Issue by bhabgs** [vueComponent/ant-design-vue#2444]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
mac: 10.14.6、 chrome: 80.0.3987.132、Vue:2.6.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
Collapse 设置 extra slot 按钮后，点击事件与折叠面板的panel header 点击事件重合，即使加入了preventDefault也会冒泡出去。
![img](http://public-1251206464.file.myqcloud.com/pub/1592366624418014.png)

### What is expected?
希望事件冒泡能够被 panel 上的 preventDefault 解决。

### What is actually happening?
目前情况是：
**如图**
> 使用阻止冒泡，也会被触发折叠面板的开合。
![img](http://public-1251206464.file.myqcloud.com/pub/1592366624418014.png)

**Comment by ibwei** [comment]
同样有这个需求，这样就可以解决。
```js
 e.preventDefault()
 e.stopPropagation()
 return false
```
