### ISSUE TITLE
table表格的datasource中包含一个key字段，这个key的值有重复，遇到了这个问题：Duplicate keys detected: 

### ISSUE THREAD

**Issue by haibin2017** [vueComponent/ant-design-vue#245]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.6

### Environment
Chrome 70.0.3538.77, Vue 2.5.17

### What is expected?
希望数据源中可以有key字段，并且key字段不影响控件自身的key逻辑

### What is actually happening?
Duplicate keys detected:

---
我的数据源是这样的：
[
{
"id": "fe823aac-4169-43d2-a760-4b358af4e1b9",
"createdTime": null,
"creator": null,
"modifiedTime": null,
"modifier": null,
"name": "陈列区8",
"nameMap": {},
"storeId": "4fd09b7c-0460-4774-929b-0f3d22db96f9",
"display": 1,
"serviceType": 0,
"relaySn": "guest",
"relayHost": "relay011.yunding360.com",
"relayPort": 10082,
"key": "A123456789"
},
{
"id": "fe823aac-4169-43d2-a760-4b358af4e1b9",
"createdTime": null,
"creator": null,
"modifiedTime": null,
"modifier": null,
"name": "陈列区8",
"nameMap": {},
"storeId": "4fd09b7c-0460-4774-929b-0f3d22db96f9",
"display": 1,
"serviceType": 0,
"relaySn": "guest",
"relayHost": "relay011.yunding360.com",
"relayPort": 10082,
"key": "A123456789"
}
]

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/47911428-5971e380-ded0-11e8-897d-bb0f8fba89d7.png)
你可以更改为其它字段

**Comment by haibin2017** [comment]
@tangjinzhou 谢谢，详细看了下文档，已解决<a-table :columns="columns" rowKey="uuid" :dataSource="data" :scroll="{ x: 2300 }"  :pagination="false">

在 Table 中，dataSource 和 columns 里的数据值都需要指定 key 值。对于 dataSource 默认将每列数据的 key 属性作为唯一的标识。
如果你的数据没有这个属性，务必使用 rowKey 来指定数据列的主键。若没有指定，控制台会出现缺少key的提示，表格组件也会出现各类奇怪的错误。

**Comment by haibin2017** [comment]
`<a-table :columns="columns" rowKey="uuid" :dataSource="data" :scroll="{ x: 2300 }"  :pagination="false">`
