### ISSUE TITLE
Use modularized antd in nuxtjs

### ISSUE THREAD

**Issue by mapsgeek** [vueComponent/ant-design-vue#246]
importing ant-design-vue works fine using plugins by importing either all the library
`import Antd from 'ant-design-vue';`
or
`import Button from 'ant-design-vue/lib/button';`  which will import a a single component but this import is global to all pages
what i have been trying to do is to import certain components in certain pages only to take advantage of lazy loading
i tried 
` <script>
import Button from 'ant-design-vue/lib/button';
export default {
  components: {
    Button
  }
}
</script>`
in the specific page i want but it doesn't work with an error that component isn't registered

**Comment by tangjinzhou** [comment]
How are you using it in the template?

**Comment by mapsgeek** [comment]
here's what i do
```
<template>
  <section class="container">
      <div>
        <a-button type="primary">Primary</a-button>
        <a-button>Default</a-button>
        <a-button type="dashed">Dashed</a-button>
        <a-button type="danger">Danger</a-button>
      </div>
  </section>
</template>

<script>
import Button from 'ant-design-vue/lib/button';

export default {
  components: {
     Button
  }
}
</script>
```

**Comment by tangjinzhou** [comment]
If you use 
```
export default {
  components: {
     Button
  }
}
```
you should use it like
`<Button type="primary">Primary</Button>`

You can use default name by 
```
export default {
  components: {
     [Button.name]: Button
  }
}
```

**Comment by mapsgeek** [comment]
thank you for making it clear, i also tried to use  babel-plugin-import so it import style file automatically, instead of me defining each single style file like this for every component 
`  css: ['ant-design-vue/lib/button/style/css']`
i created a .bablerc and put 
```
{
    "plugins": [
        [
            "import",
            {
                "libraryName": "ant-design-vue",
                "libraryDirectory": "es",
                "style": "true"
            }
        ]
    ]
}
```
as in documentation but i don't know what should i add to the nuxt.config, build object

**Comment by JasonGaoG** [comment]
when i user antd in nuxt2,  i got  'TypeError: 对象不支持“remove”属性或方法' error,  seems it is caused in a (react.element). anyone has idea?

**Comment by hagemann** [comment]
@mapsgeek Nuxt doesn’t read the .babelrc file. Instead, you have to place the snippet into the `build` option inside _nuxt.config.js_ like so:
```
export default {
  ...

  css: [
    { src: 'ant-design-vue/dist/antd.less', lang: 'less' },
  ],
  plugins: [
    { src: '@/plugins/antd.js' },
  ],
  build: {
    babel: {
      plugins: [ // Must exclude "style: true"
        ['import', { libraryName: 'ant-design-vue' }, 'ant-design-vue'],
      ],
    },
    loaders: {
      less: {
        javascriptEnabled: true,
        modifyVars: {
          'font-size-base': '15px', // Example overwrite
        },
      },
    },
  },

  ...

}
```
Ensure that you `npm i sass sass-loader` and `npm i -D babel-plugin-import` for the above code to work. The _antd.js_ plugin can look like this: https://github.com/vueComponent/ant-design-vue/blob/master/site/components.js

**Comment by loganpowell** [comment]
>   css: [
>     { src: 'ant-design-vue/dist/antd.less', lang: 'less' },
>   ],
>   plugins: [
>     { src: '@/plugins/antd.js' },
>   ],
>   build: {
>     babel: {
>       plugins: [ // Must exclude "style: true"
>         ['import', { libraryName: 'ant-design-vue' }, 'ant-design-vue'],
>       ],
>     },
>     loaders: {
>       less: {
>         javascriptEnabled: true,
>         modifyVars: {
>           'font-size-base': '15px', // Example overwrite
>         },
>       },
>     },
>   },

Do you mean `npm i less less-loader`?

**Comment by hagemann** [comment]
> Do you mean `npm i less less-loader`?
@loganpowell Oops, I amended my reply. Thanks!
