### ISSUE TITLE
想问一下 package.json 不进行格式化的原因

### ISSUE THREAD

**Issue by yiliang114** [vueComponent/ant-design-vue#2464]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1( 另外，issues helper 的版本好像不可选)

### Environment
all

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/package.json](https://github.com/vueComponent/ant-design-vue/blob/master/package.json)

### Steps to reproduce
直接打开链接即可

### What is expected?
json 文件缩进格式暂未统一

### What is actually happening?
package.json 中的格式感觉是 1 比较好~

---
这里看到 eslintignore 和 prettierignore 中都忽略了 pkg 文件的检查，想了解一下是出于什么考虑？

**Comment by tangjinzhou** [comment]
印象中是 和 编辑器的某些插件冲突了   导致每次都不符合规范，由于时间问题，就忘记了这茬  一直沿用到现在
