### ISSUE TITLE
Documentation site is very slow

### ISSUE THREAD

**Issue by ceyhunkerti** [vueComponent/ant-design-vue#2467]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
ubuntu, chrome

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
go to [https://www.antdv.com/](https://www.antdv.com)

### What is expected?
fast

### What is actually happening?
slow

**Comment by ceyhunkerti** [comment]
Not opening at all

**Comment by MedLabs** [comment]
yes I confirm, it's slow and sometimes it takes time to render when scrolling down.
