### ISSUE TITLE
嵌套子表格 固定列同时使用时子表格样式错乱，好像多了一个table

### ISSUE THREAD

**Issue by Ryan2128** [vueComponent/ant-design-vue#2470]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
10, 83.0.4103.106, 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vx8el?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
显示及样式正确

### What is expected?
去掉多余table，样式显示正确

### What is actually happening?
flexed-left的那个表格渲染了子表格的内容

**Comment by tangjinzhou** [comment]
嵌套子表格 和 固定列  现在版本无法一起使用
