### ISSUE TITLE
Input使用allow-clear时，希望hover时再显示clear图标

### ISSUE THREAD

**Issue by lanrenbulan** [vueComponent/ant-design-vue#2476]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
与select组件的clear保持一致

### What does the proposed API look like?
input组件在allow-clear的情况下，clear图标在hover时才显示

**Comment by tangjinzhou** [comment]
antd 规范如此，你可以自行使用 css 覆盖样式
