### ISSUE TITLE
Very poor perfomance of table   input element in same component

### ISSUE THREAD

**Issue by ircop** [vueComponent/ant-design-vue#248]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
Various OSs and browsers

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/71xlo27mpj)

### Steps to reproduce
Try to type something in top input box. If your PC is not very hi-end, you will see lags while typing.

### What is expected?
Normal, usually behaviour without any lags

### What is actually happening?
Text input is lagging.

---
Looks like table is re-rendered on each keyup or something like this...
When I have replaced table element to one from element-io, everything becomes fine.

**Comment by tangjinzhou** [comment]
This demo, I did not find the input box has a lagging phenomenon.
