### ISSUE TITLE
希望AModal的dialogClass属性能同时兼容object和string两种类型，感谢

### ISSUE THREAD

**Issue by sjlei** [vueComponent/ant-design-vue#2481]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如下这种使用方式，动态控制类名
``` js
dialogClass: {
    'class-a': true,
    'class-b': false,
}
```

### What does the proposed API look like?
``` js
dialogClass: {
    type: [String, Object, Array], // vue 还支持一种数组形式的class，这个加了最好，不加也行
    default: ()=>({})
}
```

<https://github.com/vueComponent/ant-design-vue/commit/889e145ed0ee0fdf98e13da99e2eee351e492727>

**Comment by tangjinzhou** [comment]
可以使用这个库  https://github.com/JedWatson/classnames
