### ISSUE TITLE
table fixed  bordered   样式问题 

### ISSUE THREAD

**Issue by SCWR** [vueComponent/ant-design-vue#2490]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
win10  chrome83 vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/a-table-bordered-hois2?file=/src/App.vue)

### Steps to reproduce
请看示例
如果存在一个fixed 列 , 同时不设置 width 时   bordered 设置为true 时 会出现样式问题 
多一条线导致莫名多出一个空列 (实际不存在) 现象
真实原因 是没设置width  导致浮动的table 与真实的table 没有对齐

### What is expected?
样式正确

### What is actually happening?
样式不正确

---
希望在下个版本能修复 辛苦了

**Comment by Amour1688** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns

参考下 antd 的 demo
