### ISSUE TITLE
layout-sider 默认展开收起bug

### ISSUE THREAD

**Issue by qq1119094779** [vueComponent/ant-design-vue#2492]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.5

### Environment
"vue": "^2.6.11"  mac  chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/2491](https://github.com/vueComponent/ant-design-vue/issues/2491)

### Steps to reproduce
产生原因： 默认是slider展开的，当屏幕小于993的时候silder是收起来的
使用defaultCollapsed 也是不可以的 因为我自定义了展开收起按钮

### What is expected?
期望样式正常展示，

### What is actually happening?
默认sider展开的 在手机上收起。 样式错乱
默认收起的 在pc上展开 元素未被删除。排版错乱

**Comment by sendya** [comment]
请使用 codesandbox https://codesandbox.io/s/2wpk21kzvr 提供复现
