### ISSUE TITLE
table在template 风格的 API 下列排序失效

### ISSUE THREAD

**Issue by mark0325** [vueComponent/ant-design-vue#2501]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
win10、Microsoft Edge 83.0.478.56

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-3vlyj?file=/src/components/HelloWorld.vue)

### Steps to reproduce
点击列排序

### What is expected?
正常排序

### What is actually happening?
总是升序排序

**Comment by ZxcSoft** [comment]
template模式下, 必须加key. data-index设置无效.
```
<a-table-column
          title="executeTime"
          data-index="executeTime"
          key="executeTime"
          :sorter="true"
        >
</a-table-column>
```

**Comment by mark0325** [comment]
> template模式下, 必须加key. data-index设置无效.
> 
> ```
> <a-table-column
>           title="executeTime"
>           data-index="executeTime"
>           key="executeTime"
>           :sorter="true"
>         >
> </a-table-column>
> ```

thank you
