### ISSUE TITLE
table数据量大,组件销毁卡顿问题 

### ISSUE THREAD

**Issue by zsodur** [vueComponent/ant-design-vue#2508]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
无

### Reproduction link
[https://github.com/zsodur/ant-table-bug](https://github.com/zsodur/ant-table-bug)

### Steps to reproduce
1. 获取数据(1000条)，渲染table
2. 使用 v-if 清除table

### What is expected?
table在短时间内清除

### What is actually happening?
页面完全卡死，电脑cpu占用100%，大约10s后恢复，table在被清除

**Comment by zsodur** [comment]
复现demo: https://zsodur.github.io/ant-table-bug/

**Comment by taojunnan** [comment]
请问解决了吗

**Comment by TaoHuaXia** [comment]
同样遇到这个问题，树形表格在销毁的时候页面完全卡死，甚至页面崩溃

**Comment by TaoHuaXia** [comment]
使用的版本是2.0.0-rc2

**Comment by tangjinzhou** [comment]
2.0.1 已优化

**Comment by 763292853** [comment]
1开头的版本还解决这个问题吗？

**Comment by 763292853** [comment]
vue2的项目用不了2.0.1的版本呀

**Comment by SignDawn** [comment]
做个分页吧，和产品经理 battle

**Comment by 763292853** [comment]
感谢您给我发来的邮件，我会尽快给你回复的。                                          世界杰出华商协会李少鹏
