### ISSUE TITLE
表格的selectedRows

### ISSUE THREAD

**Issue by yi8wen8san8bu8zhi** [vueComponent/ant-design-vue#2511]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格第一页勾选几个数据,切换到第二页继续勾选,第一页勾选的数据就会丢失

### What does the proposed API look like?
可以和selectedRowKeys一样持续保存选中项

**Comment by sendya** [comment]
这个请自己在 data 下保存你需要的值即可
