### ISSUE TITLE
Input组件maxLength和原生属性冲突

### ISSUE THREAD

**Issue by wang-ky** [vueComponent/ant-design-vue#2516]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
win10, chrome83, vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/test-v9njz)

### Steps to reproduce
输入框输入指定位数

### What is expected?
生效

### What is actually happening?
不生效

**Comment by wang-ky** [comment]
maxlength是原生input就支持的属性，在组件支持maxLength之前，实际项目中一直是使用的原生的方式

尤其组件对这个props也没有其他逻辑，直接在渲染的时候传给了attr，建议还是不要这个了吧

**Comment by tangjinzhou** [comment]
maxLength 删了会有破坏性更新 不删也可以直接maxlength   不影响使用

**Comment by wang-ky** [comment]
> maxLength 删了会有破坏性更新 不删也可以直接maxlength 不影响使用

目前最新版本`<a-input maxlength="5" />`不生效，影响使用了, @tangjinzhou
