### ISSUE TITLE
Vuedraggable、Carousel组件打包后不兼容 ie浏览器

### ISSUE THREAD

**Issue by wxwebfeng** [vueComponent/ant-design-vue#2518]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
window 10 / IE11 / Vue ^2.6.11

### Reproduction link
[https://www.antdv.com/components/layout-cn/](https://www.antdv.com/components/layout-cn/)

### Steps to reproduce
1.在本地运行是能展示；
2.打包后发布到服务器；
3.轮播组件 slot 未加载数据(轮播内容)

### What is expected?
1.期待能兼容ie

### What is actually happening?
没有加载slot（轮播内容）

**Comment by sendya** [comment]
能提供复现吗？

**Comment by wxwebfeng** [comment]
@sendya 不好意思，是我们这边的问题，组件引用顺序问题！感觉很奇怪，Number 会被修改掉(只有在ie浏览器，而且是打包后),
Number.toString(): function(t){var e=arguments.length<1?0:t,n=this;return n instanceof O&&(x?h((function(){b.valueOf.call(n)})):c(n)!=m)?u(new y(w(e)),n,O):w(e)}; // 该函数 prototype —> Number; 

Carousel props 初始参数 那里Number类型数据就会为undefined;

ant-design-vue —> lib —> _util —> utils.js 中 var getType = exports.getType = function getType(fn) { var type = fn !== null && fn !== undefined ? fn.type ? fn.type : fn : null; var match = type && type.toString().match(FN_MATCH_REGEXP); return match && match[1]; }; // 造成 match[1] 为undefined 所以赋值default: undefined, 走马灯出错

如果 Carousel 组件 先于 Vuedraggable 引入 就不会 造成 Number 修改问题；

**Comment by Iffyyy** [comment]
我们也遇到相同问题，整体架构用qiankun搭建的，打包后，carousel组件的slot内容未渲染，但是访问单个项目carousel组件能正常显示。也不知道可能是引入哪个组件出的问题，不知道怎么解决
