### ISSUE TITLE
Input.Search的enterButton参数能否有更好的兼容自定义组件

### ISSUE THREAD

**Issue by ConquerStars** [vueComponent/ant-design-vue#2519]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决自定义组件(button的封装) 使用enterButton参数时，重复嵌套一层button导致样式问题

### What does the proposed API look like?
我发现使用了ant-design自带的a-button不会出现嵌套button标签，而使用其他标签，包括自定义组件标签，会导致强行嵌套一层button标签，即使自定义标签名称为a-button。能否识别 在使用slot="enterButton"时的自定义组件是a-button封装(<template><a-button>btn封装</a-button></template>)的情况，减少嵌套重复button标签导致样式问题。

**Comment by xrkffgg** [comment]
没明白啥意思，给个例子 看看。

**Comment by ConquerStars** [comment]
> 没明白啥意思，给个例子 看看。

https://codesandbox.io/s/magical-shadow-1ftjx?file=/src/components/CaptchaBtn.vue

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/boring-http-123he?file=/src/App.vue

把你例子中 CaptchaBtn 挪到外层就正常了。。。可见是你的自定义组件写法的原因。

**Comment by ConquerStars** [comment]
> https://codesandbox.io/s/boring-http-123he?file=/src/App.vue
> 
> 把你例子中 CaptchaBtn 挪到外层就正常了。。。可见是你的自定义组件写法的原因。

嗯，我是想复用我的 CaptchaBtn 组件，因为挺多页面要用到。按照你现在的写法的话，只能是在a-input-search外封装一层了
