### ISSUE TITLE
a-menu-item等添加可否添加path/to等属性?

### ISSUE THREAD

**Issue by ShiraGawaAnri** [vueComponent/ant-design-vue#2522]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
添加相关属性后可使得点击menu直接移动到相应的路由
或者新增一个形如 <a slot="link"> 的插槽也可

### What does the proposed API look like?
`<a-menu type="route">
<a-menu-item (key|to|path)="/index" title="HomePage" />
</a-menu>`

**Comment by sendya** [comment]
```
<a-menu-item>
 <router-link :to="">MenuName</router-link>
</a-menu-item>
```
