### ISSUE TITLE
日期组件内部能否做到全部中文化？

### ISSUE THREAD

**Issue by wwmin** [vueComponent/ant-design-vue#2527]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决了对英文不懂的人对日期控件的使用

### What does the proposed API look like?
locale语法自动化切换

**Comment by xrkffgg** [comment]
https://antdv.com/components/date-picker-cn/#%E5%9B%BD%E9%99%85%E5%8C%96%E9%85%8D%E7%BD%AE

**Comment by wwmin** [comment]
月份和星期几 那些都没有汉化，有没有全部的汉化方案？

**Comment by zkwolf** [comment]
![image](https://user-images.githubusercontent.com/8555127/86728353-f6e6c880-c05e-11ea-83f0-2c80d7191e7e.png)
指定一下moment的locale其他的就都是中文了

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/86728679-3ca39100-c05f-11ea-9c5f-b1f789558e27.png)

**Comment by wwmin** [comment]
@xrkffgg 你有没有自己试过？ 这种方式我试过，没有效果，如果是我哪设置的不对，望指出。。。
@zkwolf 您说的方式我也试过了， 代码如下，都没有效果
```
  <a-date-picker :defaultValue="moment('2020-07-08','YYYY-MMk-DD')" :locale="locale"></a-date-picker>
```
``` 
import locale from 'ant-design-vue/es/date-picker/locale/zh_CN';
import moment from "moment";
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
```
```
data(){
      moment,
      locale,
}
```

![image](https://user-images.githubusercontent.com/7775200/86867140-e12bde80-c104-11ea-8ba8-32e119ccb1ff.png)

**Comment by xrkffgg** [comment]
## Link
- https://codesandbox.io/s/jolly-cray-fvcs8?file=/src/App.vue

## Preview

![image](https://user-images.githubusercontent.com/29775873/86867631-bf7f2700-c105-11ea-99bd-08831f049604.png)

**Comment by xrkffgg** [comment]
emmm 我没试过，我会这么告诉你？

**Comment by wwmin** [comment]
@xrkffgg 非常感谢您的回答，在我的代码里用到了全局汉化方案
```
       <a-config-provider :locale="locale">
         <router-view></router-view>
        </a-config-provider>
```
```
  import locale from 'ant-design-vue/es/date-picker/locale/zh_CN';
```
```
    data() {
      return {
        locale
      }
    }
```
我发现了问题所在， 当我用这个代码包裹路由时，就出现了不能汉化的问题，我这个config-provider组件的用法不对吗？😓

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/86877351-4ab5e800-c119-11ea-9c98-575adbc9466d.png)

这。。。

**Comment by xrkffgg** [comment]
官网中写的很清楚，直接按照这个步骤就行了呀。。。。

- https://www.antdv.com/components/locale-provider-cn/#%E4%BD%BF%E7%94%A8

**Comment by sendya** [comment]
新手入门建议直接用 config-provider 包裹 App

**Comment by wwmin** [comment]
> 官网中写的很清楚，直接按照这个步骤就行了呀。。。。
> 
> * https://www.antdv.com/components/locale-provider-cn/#%E4%BD%BF%E7%94%A8

谢谢您的回答，localProvider这个组件已不推荐使用
![image](https://user-images.githubusercontent.com/7775200/86881875-d3d11d00-c121-11ea-927a-14da345dd7f4.png)

**Comment by wwmin** [comment]
@xrkffgg 谢谢您的耐心回答，我的边做了一个最小化demo，确实是全部汉化了，但是我的项目里没有实现，估计哪个地方有问题，我自己再找找问题所在。
再次感谢。

**Comment by afc163** [comment]
@wwmin 检查一下是不是有两个版本的 moment。

**Comment by yanqi2020** [comment]
ant-design-vue 更新到1.6.3版本以上
组件引入这两个就好了
import moment from "moment";
import "moment/locale/zh-cn";

**Comment by yexiaodong** [comment]
还需要执行：npm install moment --save  安装moment插件吗

**Comment by yxh410** [comment]
请问你解决了吗？我也有这样的问题

**Comment by Tocurd** [comment]
我也有这个问题

**Comment by PantongWu** [comment]
https://www.antdv.com/components/locale-provider-cn/#%E4%BD%BF%E7%94%A8
即使是文档中
![image](https://user-images.githubusercontent.com/21765389/98329814-09d0d000-2034-11eb-9145-4f57c945a874.png)
这也是无法正常显示月份跟星期的啊

**Comment by tangjinzhou** [comment]
项目工程中安装下  npm i moment

**Comment by PantongWu** [comment]
我目前指定过 moment 2.24 以及最新的 2.29 都没有什么效果 专门查了下 moment/locale/zh-cn两个版本的源码 似乎没有什么变化 ,目前没有找到太好的解决的办法
Calendar组件 月份选择框还有一个问题见下图
![image](https://user-images.githubusercontent.com/21765389/98331148-eeb38f80-2036-11eb-9131-63516a33409b.png)

**Comment by betgar** [comment]
我遇到的工程中moment存在多个版本，引起的这个问题：
1. ant-design-vue自身的package.json依赖里面有moment 2.21版本
2. 工程中的package.json 是moment.js 2.24版本
3. yarn remove moment ant-design-vue (npm un moment ant-design-vue)
4. yarn add ant-design-vue@1.7.x (npm i ant-design-vue@1.7.x)（记着安装自己之前依赖的版本）

**Comment by yanwenjia** [comment]
遇到同样得问题

**Comment by any86** [comment]
这个日期在vue3+vite下出现了同样的问题, 上面说的方法都用了, 月份就是不汉化,  直接复制粘贴的官方例子.

![image](https://user-images.githubusercontent.com/8264787/120949290-ca5b9500-c776-11eb-9207-19fe4b41288a.png)


```html

<template>
  <a-config-provider :locale="zh_CN">
    <a-date-picker v-model="v"></a-date-picker>
  </a-config-provider>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import zh_CN from 'ant-design-vue/lib/locale-provider/zh_CN';
import moment from 'moment';
import 'moment/locale/zh-cn';

moment.locale('zh-cn');
export default defineComponent({
  setup() {
    return { zh_CN, v: null };
  },
});
</script>

```

**Comment by any86** [comment]
在上一个例子,还是官网的, 依旧不生效
```html
<template>
  <a-date-picker v-model:value="value" :locale="locale" />
</template>
<script>
  import locale from 'ant-design-vue/es/date-picker/locale/zh_CN';
  import { defineComponent } from 'vue';
  export default defineComponent({
    setup() {
      return {
        locale,
        value: null,
      };
    },
  });
</script>
```

**Comment by any86** [comment]
# 临时解决方法:

```javascript
import 'moment/locale/zh-cn';
```
把这行替换成下面的代码:
```javascript
moment.locale('zh-cn', {
  months:
    '\u4E00\u6708_\u4E8C\u6708_\u4E09\u6708_\u56DB\u6708_\u4E94\u6708_\u516D\u6708_\u4E03\u6708_\u516B\u6708_\u4E5D\u6708_\u5341\u6708_\u5341\u4E00\u6708_\u5341\u4E8C\u6708'.split(
      '_'
    ),
  monthsShort:
    '1\u6708_2\u6708_3\u6708_4\u6708_5\u6708_6\u6708_7\u6708_8\u6708_9\u6708_10\u6708_11\u6708_12\u6708'.split('_'),
  weekdays:
    '\u661F\u671F\u65E5_\u661F\u671F\u4E00_\u661F\u671F\u4E8C_\u661F\u671F\u4E09_\u661F\u671F\u56DB_\u661F\u671F\u4E94_\u661F\u671F\u516D'.split(
      '_'
    ),
  weekdaysShort: '\u5468\u65E5_\u5468\u4E00_\u5468\u4E8C_\u5468\u4E09_\u5468\u56DB_\u5468\u4E94_\u5468\u516D'.split(
    '_'
  ),
  weekdaysMin: '\u65E5_\u4E00_\u4E8C_\u4E09_\u56DB_\u4E94_\u516D'.split('_'),
  longDateFormat: {
    LT: 'HH:mm',
    LTS: 'HH:mm:ss',
    L: 'YYYY/MM/DD',
    LL: 'YYYY\u5E74M\u6708D\u65E5',
    LLL: 'YYYY\u5E74M\u6708D\u65E5Ah\u70B9mm\u5206',
    LLLL: 'YYYY\u5E74M\u6708D\u65E5ddddAh\u70B9mm\u5206',
    l: 'YYYY/M/D',
    ll: 'YYYY\u5E74M\u6708D\u65E5',
    lll: 'YYYY\u5E74M\u6708D\u65E5 HH:mm',
    llll: 'YYYY\u5E74M\u6708D\u65E5dddd HH:mm',
  },
  meridiemParse: /凌晨|早上|上午|中午|下午|晚上/,
  meridiemHour: function (hour, meridiem) {
    if (hour === 12) {
      hour = 0;
    }
    if (meridiem === '\u51CC\u6668' || meridiem === '\u65E9\u4E0A' || meridiem === '\u4E0A\u5348') {
      return hour;
    } else if (meridiem === '\u4E0B\u5348' || meridiem === '\u665A\u4E0A') {
      return hour + 12;
    } else {
      return hour >= 11 ? hour : hour + 12;
    }
  },
  meridiem: function (hour, minute, isLower) {
    var hm = hour * 100 + minute;
    if (hm < 600) {
      return '\u51CC\u6668';
    } else if (hm < 900) {
      return '\u65E9\u4E0A';
    } else if (hm < 1130) {
      return '\u4E0A\u5348';
    } else if (hm < 1230) {
      return '\u4E2D\u5348';
    } else if (hm < 1800) {
      return '\u4E0B\u5348';
    } else {
      return '\u665A\u4E0A';
    }
  },
  calendar: {
    sameDay: '[\u4ECA\u5929]LT',
    nextDay: '[\u660E\u5929]LT',
    nextWeek: function (now) {
      if (now.week() !== this.week()) {
        return '[\u4E0B]dddLT';
      } else {
        return '[\u672C]dddLT';
      }
    },
    lastDay: '[\u6628\u5929]LT',
    lastWeek: function (now) {
      if (this.week() !== now.week()) {
        return '[\u4E0A]dddLT';
      } else {
        return '[\u672C]dddLT';
      }
    },
    sameElse: 'L',
  },
  dayOfMonthOrdinalParse: /\d{1,2}(日|月|周)/,
  ordinal: function (number, period) {
    switch (period) {
      case 'd':
      case 'D':
      case 'DDD':
        return number + '\u65E5';
      case 'M':
        return number + '\u6708';
      case 'w':
      case 'W':
        return number + '\u5468';
      default:
        return number;
    }
  },
  relativeTime: {
    future: '%s\u540E',
    past: '%s\u524D',
    s: '\u51E0\u79D2',
    ss: '%d \u79D2',
    m: '1 \u5206\u949F',
    mm: '%d \u5206\u949F',
    h: '1 \u5C0F\u65F6',
    hh: '%d \u5C0F\u65F6',
    d: '1 \u5929',
    dd: '%d \u5929',
    M: '1 \u4E2A\u6708',
    MM: '%d \u4E2A\u6708',
    y: '1 \u5E74',
    yy: '%d \u5E74',
  },
  week: {
    dow: 1,
    doy: 4,
  },
});
```

**Comment by qiuyaofan** [comment]
#3029 
import 'moment/locale/zh-cn' 换成import 'moment/dist/locale/zh-cn' 就可以

**Comment by zmmiffy** [comment]
当组件只有一个时间选择器是 日期和月份是可以正常汉化。

**Comment by kshiw** [comment]
上面所有代码层面方式都试过无效 - -
受到启发，干掉package.json的moment，rimraf node_modules && npm i  
正常显示中文，又可以上班摸鱼了~
ant version：1.7.8

**Comment by just-wkj** [comment]
亲测有效 
 版本:1.6.2

**Comment by blusewang** [comment]
哎！我全试了，都不行！
快疯了！

**Comment by yc-rakuen** [comment]
antv3.2.4+vite也遇到了这个问题。
3.x版本用的dayjs，增加导入
import 'dayjs/locale/zh-cn'
可以解决

**Comment by blusewang** [comment]
> 哎！我全试了，都不行！ 快疯了！

我的问题其实是我看着ant v2的文档，操作着ant v3的库！🤣

**Comment by ZHFeng-Plus** [comment]
antv3.2.6 升级dayjs: 1.11.9 搞定

**Comment by lidaxia1998** [comment]
> antv3.2.6 升级dayjs: 1.11.9 搞定
antd-vue 4.0  升级dayjs: 1.11.9 也搞定了  感谢老哥

**Comment by Erdrian** [comment]
> #3029 import 'moment/locale/zh-cn' 换成import 'moment/dist/locale/zh-cn' 就可以

vite + vue2.7 + antdv 1.7.8  使用此办法可以生效
