### ISSUE TITLE
there did NOT exist "vc-calendar" component

### ISSUE THREAD

**Issue by Echo-minn** [vueComponent/ant-design-vue#2529]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
windows10, Vue@2.6.1, chrome latest version

### Reproduction link
[https://www.antdv.com/components/calendar-cn/](https://www.antdv.com/components/calendar-cn/)

### Steps to reproduce
i used 'npm install ant-design-vue --save' and install atdv successfully
but when i import some component and run my project, some errors happened in 【node_modules/ant-design-vue/es/date-picker/locale/en_US.js】
in this file, it 'import CalendarLocale from '../../vc-calendar/src/locale/en_US';
however, in the whole ant-design-vue directory, i can not found a directory named 'vc-calendar'
i tried to install it by 'npm i vc-calendar' but failed

### What is expected?
run my project successfully

### What is actually happening?
ERROR  Failed to compile with 1 errors                                                                                                   14:09:42

This relative module was not found:

* ../../vc-calendar/src/locale/en_US in ./node_modules/ant-design-vue/es/date-picker/locale/en_US.js

because you import an unexist file 'vc-calendar'

**Comment by xrkffgg** [comment]
I didn't find any problems, please provide a reproduction. Like: https://codesandbox.io/s/jolly-cray-fvcs8?file=/src/App.vue
Or you can try 
```sh
rm -rf node_modules package-lock.json yarn.lock
npm install
```
