### ISSUE TITLE
通过浏览器引入时，range-picker会报错："TypeError: Cannot read property 'default' of undefined"

### ISSUE THREAD

**Issue by yanglu1019** [vueComponent/ant-design-vue#253]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
chrome 70.0.3538.77   vue:2.5.17

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
浏览器script引入

`<div id="wrapper">
<a-date-picker/>
</div>
<script>
Vue.component(antd.DatePicker.name, antd.DatePicker)
let wrapper = new Vue({
el: '#wrapper'
});
</script>`

### What is expected?
显示日期组件

### What is actually happening?
无显示，并在控制台报错："TypeError: Cannot read property 'default' of undefined"

---
浏览器引入，导航栏组件隐藏时也会报错

**Comment by tangjinzhou** [comment]
参考https://codepen.io/tangjinzhou/pen/xQZJPd提供一个复现链接

**Comment by yanglu1019** [comment]
是moment.js引入顺序的问题，已经找到原因
