### ISSUE TITLE
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

### ISSUE THREAD

**Issue by wyw-code** [vueComponent/ant-design-vue#2535]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

### Reproduction link
[https://www.java8.site](https://www.java8.site)

### Steps to reproduce
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

### What is expected?
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

### What is actually happening?
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

---
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标失效

**Comment by wyw-code** [comment]
treeselect 可勾选和后缀图标冲突， 增加tree-checkable之后后缀图标就没有了。

**Comment by xrkffgg** [comment]
It's by design.

**Comment by cielzhao** [comment]
> It's by design.

treeselect支持多选的时候没有后缀图标，也不能自定义添加，为什么不能多加个属性或者支持一下呢？
