### ISSUE TITLE
table集成 vue-draggable-resizable 实现可伸缩列除了action外，其他column全都设置了宽度，action这一列设置了fixed：right且屏幕大到无滚动条时出现两个action

### ISSUE THREAD

**Issue by superqueengirl** [vueComponent/ant-design-vue#2540]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
ant-design-vue 1.6.3 and (vue-draggable-resizable 2.1.0 or 2.2.0)

### Reproduction link
[http://Examples of copying official documents can be reproduced.com](http://Examples of copying official documents can be reproduced.com)

### Steps to reproduce
table集成vue-draggable-resizable,实践中发现都要设置宽度，如果留一列不设置宽度用来自适应的话，该列就不能拖拽。但是数据过多的话想把最后一列操作列固定在最右边，最后一列使用fixed后无论该列有没有设置width,屏幕大道无滚动条时会出现2列操作列，其中一列压在了另一列的上面，另一列露出了一部分。屏幕小到出现滚动条时是正常的。

### What is expected?
希望集成vue-draggable-resizable且最后一列操作列想设置fixed时不出现两列操作列。万分感谢，谢谢，谢谢！

### What is actually happening?
集成vue-draggable-resizable且最后一列操作列设置fixed时出现两列操作列且宽度不同都能被看到。万分感谢，谢谢，谢谢！

**Comment by jim888666** [comment]
我也遇到这个问题了，有大神解决？

**Comment by 498755303** [comment]
这问题最终如何解决了

**Comment by songxianling** [comment]
我也遇到了相同的问题；暂时还无法升级3版本；想问有人解决这个问题了吗？一列fixed固定很有用
