### ISSUE TITLE
Drawer：同时设置不显示遮罩层和宽度百分比时不出弹框

### ISSUE THREAD

**Issue by nilRoot** [vueComponent/ant-design-vue#2543]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
ant-design-vue 1.5.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-lu8j2?file=/src/App.vue)

### Steps to reproduce
当设置不显示遮罩层:mask="false"时，同时设置宽度为百分比width:"50%"，不出弹框，drawer 高度为0；

### What is expected?
可以解决

### What is actually happening?
可以解决

**Comment by xrkffgg** [comment]
Try `width="50vw"`

**Comment by nilRoot** [comment]
> 50vw

3q~
