### ISSUE TITLE
Tooltip在表格中无法设置位置偏移

### ISSUE THREAD

**Issue by nshusr** [vueComponent/ant-design-vue#2544]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
Chrome Release  Vue Release

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-er84b?file=/src/App.vue)

### Steps to reproduce
创建表格，添加a-tooltip 或 a-popover

### What is expected?
表格中偏移设置后不影响左右滑动遮挡进入表格元素

### What is actually happening?
被展示的tooltip遮挡

---
希望添加offset属性来偏移展示的tooltip位置

**Comment by xrkffgg** [comment]
你可以试一下 `overlayStyle`

**Comment by nshusr** [comment]
并没有效果，依旧偏移没有生效，可以看
https://codesandbox.io/s/vue-antd-template-er84b?file=/src/App.vue

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/87134415-403b5000-c2cb-11ea-8dda-55f298f13d3e.png)

`overlayStyle` 接受的是一个 object，更改写法后，可以看到 style 上已经加上

**Comment by nshusr** [comment]
@xrkffgg  指上面看效果，并没有实际偏移！
https://codesandbox.io/s/vue-antd-template-er84b?file=/src/App.vue

![image](https://user-images.githubusercontent.com/45023042/87540130-b677f200-c6d1-11ea-9e63-0e3e0c06e82f.png)

**Comment by sendya** [comment]
a-tooltip 设计上用来针对一个元素或操作 进行说明，并且是用来替代浏览器自带 `title`  属性功能，所以该功能必须很强性要求指引到对应的元素上。只能改动显示的方向，不能随意改动指向位置。按照你的需求 `a-tooltip`  并不适合你的想法使用，你可能更需要直接用 label 等元素再 table 之外显示，然后根据当前 hover 项进行更新文本内容

**Comment by xrkffgg** [comment]
> 没有实际偏移！

检查你设置的 style

**Comment by nshusr** [comment]
@sendya @xrkffgg  有没有方法实现移出包裹元素就直接隐藏，而不是经过tooltip时还在显示，这才是原生`title`的效果，现在就是因为经过时`tooltip`还在显示影响了经过其他表格，谢谢大佬们
