### ISSUE TITLE
当滚动列的行高变化时，固定列的行高不会同步变化 fixed column height would not change when scroll column height change 固定列

### ISSUE THREAD

**Issue by liuzhuoling2011** [vueComponent/ant-design-vue#2549]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
antd vue:	1.6.3  System: win10  Browser: chrome, version: 72.0.3626.96

### Reproduction link
[https://github.com/ant-design/ant-design/issues/14859](https://github.com/ant-design/ant-design/issues/14859)

### Steps to reproduce
在input内输入任意值
enter some values

### What is expected?
无论是固定列高度变化还是滚动列高度变化，固定列高度和滚动列高度一致
fixed column height is the same as the scroll column height

### What is actually happening?
固定列或者滚动列有任一方高度在运行中变化时，另一方高度不会变化
fixed column height is different from the scroll column height

---
https://github.com/ant-design/ant-design/issues/14859
React 版本貌似升级V4就解决问题了

**Comment by Stevenlike** [comment]
遇到了同样的问题，并且没有提供重新渲染布局的方法
