### ISSUE TITLE
fieldDecoratorId和v-model

### ISSUE THREAD

**Issue by juhuanyan** [vueComponent/ant-design-vue#255]
表单中在a-form-item设置fieldDecoratorId时，a-input再用v-model绑定默认值时，默认值设置无效

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/ant-design-vue/components/form-cn/#this.form.getFieldDecorator(id,-options)
请详细阅读文档，建议使用按需加载，会有相关提示输出在控制台
