### ISSUE TITLE
目前table组件，rowClassName貌似只为body增加了class，希望能够支持表头的th也有一个class

### ISSUE THREAD

**Issue by yiptsangkin** [vueComponent/ant-design-vue#2551]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
mac chrome vue2.6.11 vue-cli3

### Reproduction link
[https://antdv.com/components/table-cn/](https://antdv.com/components/table-cn/)

### Steps to reproduce
#

### What is expected?
期望rowClassName也同时为表头增加class

### What is actually happening?
实际没有

**Comment by xrkffgg** [comment]
Try `onHeaderRow `
