### ISSUE TITLE
Website Not Loading

### ISSUE THREAD

**Issue by nikohosn** [vueComponent/ant-design-vue#2556]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
Chrome, Safari

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
Navigate to the website

### What is expected?
To load the website.

### What is actually happening?
Not loading.

**Comment by xrkffgg** [comment]
- It's normal. You can check your web.

![image](https://user-images.githubusercontent.com/29775873/87369033-0eb7d280-c5b2-11ea-8197-27e9bbdb5b63.png)
