### ISSUE TITLE
Dropdown 弹窗的宽度显示异常

### ISSUE THREAD

**Issue by Y450150** [vueComponent/ant-design-vue#2559]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
http://gzdxda.vicp.io:9912/，任何一个环境都可以复现，账号：15813374073   密码：123456

### Reproduction link
[http://gzdxda.vicp.io:9912/](http://gzdxda.vicp.io:9912/)

### Steps to reproduce
下拉菜单平分父级元素的宽度自适应，当宽度从小变大后再变小，弹窗的宽度显示异常

### What is expected?
下拉菜单弹窗的宽度能与菜单宽度一致

### What is actually happening?
下拉菜单弹窗的宽度只能变大，不能缩小

**Comment by xrkffgg** [comment]
可使用： https://codesandbox.io/s/vue-antd-template-e22bh?file=/src/App.vue  提供复现。

**Comment by Y450150** [comment]
谢谢，已经还原复选问题场景，请使用 https://codesandbox.io/s/vue-antd-template-e22bh?file=/src/App.vue 查看

**Comment by Y450150** [comment]
> 可使用： https://codesandbox.io/s/vue-antd-template-e22bh?file=/src/App.vue 提供复现。
谢谢，已经还原复选问题场景，请使用 https://codesandbox.io/s/vue-antd-template-e22bh?file=/src/App.vue 查看

**Comment by xrkffgg** [comment]
### 1. 弹窗错位
更新 ant-design-vue 版本，使用 1.6.3 正常。

### 2. DropDown  宽度
v-for 中 key 一样，导致不会重新渲染 DOM，将 key 变成唯一即可。

### 具体查看：
https://codesandbox.io/s/blissful-austin-e56hz?file=/src/App.vue

**Comment by Y450150** [comment]
> ### 1. 弹窗错位
> 更新 ant-design-vue 版本，使用 1.6.3 正常。
> 
> ### 2. DropDown 宽度
> v-for 中 key 一样，导致不会重新渲染 DOM，将 key 变成唯一即可。
> 
> ### 具体查看：
> https://codesandbox.io/s/blissful-austin-e56hz?file=/src/App.vue

多谢，已解决，打扰了
