### ISSUE TITLE
cascader 能否可以多选？

### ISSUE THREAD

**Issue by myzhoulang** [vueComponent/ant-design-vue#256]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
select 组件对于小数据可以实现 但是对于多级分组的的实现就没有那么好了，

### What does the proposed API look like?
将 `v-model` 设为 `[[1,2,3], [1,2,4]]`

**Comment by tangjinzhou** [comment]
cascader不支持多选的

你可以参考这个分组 https://vuecomponent.github.io/ant-design-vue/components/select-cn/#components-select-demo-option-group

**Comment by xianshenglu** [comment]
tree-select 最接近了

https://vuecomponent.github.io/ant-design-vue/components/tree-select-cn/
