### ISSUE TITLE
文档 typo 错误

### ISSUE THREAD

**Issue by yiliang114** [vueComponent/ant-design-vue#2561]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
all

### Reproduction link
[https://antdv.com/components/table-cn/#components-table-demo-filter-and-sorter](https://antdv.com/components/table-cn/#components-table-demo-filter-and-sorter)

### Steps to reproduce
open url

### What is expected?
```
filterIcon	自定义 filter 图标。
```

### What is actually happening?
```
filterIcon	自定义 fiter 图标。
```

额。。。 没找到在哪里提修改文档的 pr 。 antv-demo 这个是文档么？

**Comment by xrkffgg** [comment]
感谢反馈！😘
