### ISSUE TITLE
新版本ColorPicker没暴露给外部使用

### ISSUE THREAD

**Issue by Ucdit** [vueComponent/ant-design-vue#2564]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
无

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
我

### What is expected?
希望ColorPicker能提供给使用者使用

### What is actually happening?
ColorPicker没暴露给使用者使用

**Comment by cydiacen** [comment]
ColorPicker还存在一些问题,少侠莫慌. 
一切以文档为准
