### ISSUE TITLE
Support for Vetur tag attribute supplement

### ISSUE THREAD

**Issue by baojie223** [vueComponent/ant-design-vue#2566]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
When i use vue sfc, I want to know what attributes the component have, so I want to add Vetur support.Do you think it's necessary?

### What does the proposed API look like?
"a-row/align": {
"description": "flex 布局下的垂直对齐方式：top middle bottom, default: top",
"type": "*string*"
},

**Comment by baojie223** [comment]
@tangjinzhou

**Comment by woshiguabi** [comment]
Very interesting.
I can help to do some work on this.

**Comment by xrkffgg** [comment]
PR welcome
