### ISSUE TITLE
Input-Search 输入框搜索组件 加入 Input api > allowClear,布局会错乱

### ISSUE THREAD

**Issue by wxwebfeng** [vueComponent/ant-design-vue#2568]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0-rc.6

### Environment
window 10 / IE11 / Vue ^2.6.11

### Reproduction link
[https://www.antdv.com/components/input-cn/](https://www.antdv.com/components/input-cn/)

### Steps to reproduce
<a-input-search placeholder="input search text" allow-clear enter-button @search="onSearch"/>
加入属性参数 allow-clear
出现布局错乱

### What is expected?
不会影响搜索按钮样式

### What is actually happening?
影响到搜索按钮样式

---
无

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/angry-bird-x8v89?file=/src/App.vue

未发现布局错乱。
