### ISSUE TITLE
anchor component can not jump to target when page refresh

### ISSUE THREAD

**Issue by JesseEisen** [vueComponent/ant-design-vue#2569]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
MacOS 10.15.5、Google Chrome 版本 83.0.4103.116（正式版本） （64 位）

### Reproduction link
[https://www.antdv.com/components/anchor-cn/#components-anchor-demo-basic](https://www.antdv.com/components/anchor-cn/#components-anchor-demo-basic)

### Steps to reproduce
Click the [anchor_cn](https://www.antdv.com/components/anchor-cn/)  page's example **Baisc demo with target**.

### What is expected?
Do the same thing as [antd react](https://3x.ant.design/components/anchor-cn/#components-anchor-demo-static) do

### What is actually happening?
The new page still display as normal, not jump

**Comment by xrkffgg** [comment]
没明白啥意思

**Comment by JesseEisen** [comment]
> 没明白啥意思

我想说的是：访问带有锚点的URL，页面加载后不会跳到指定锚点处。
