### ISSUE TITLE
select组件使用 dropdownRender 对下拉菜单进行自由扩展添加input组件时，input无法聚焦输入

### ISSUE THREAD

**Issue by Ben199011** [vueComponent/ant-design-vue#2571]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Mac系统，Google Chrome版本83.0.4103.116，Vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-rain-5zw66?file=/src/App.vue)

### Steps to reproduce
无

### What is expected?
input输入框可以聚焦输入

### What is actually happening?
input输入框无法聚焦输入

**Comment by AllenForward** [comment]
这个issue好像到现在还没修复.

**Comment by shiyuanzheng** [comment]
有什么解决方案吗

**Comment by shiyuanzheng** [comment]
@tangjinzhou 这个bug有在修复吗

**Comment by zhedream** [comment]
> 有什么解决方案吗

我也遇到了这个问题
加一个 click 事件, 手动 聚焦一下
```html
<a-input
 v-model.trim="search_text"
  placeholder="请输入搜索关键字"
  style="width: 85%"
  @change="onSearch"
  @click="e=>e.target.focus()"
 />
```

**Comment by xuhuanghuang** [comment]
这个bug 会修复吗

**Comment by xuhuanghuang** [comment]
> > 有什么解决方案吗
> 
> 我也遇到了这个问题
> 加一个 click 事件, 手动 聚焦一下
> 
> ```
> <a-input
>  v-model.trim="search_text"
>   placeholder="请输入搜索关键字"
>   style="width: 85%"
>   @change="onSearch"
>   @click="e=>e.target.focus()"
>  />
> ```

下拉面板会隐藏， 要手动控制面板

**Comment by boluomuma** [comment]
react版本同样有问题,啊哈哈...

**Comment by Robinbiao** [comment]
现在还没修复吗？

**Comment by jaycethanks** [comment]
类似的issue 问题都没有解决 全部被close 掉了

**Comment by jaycethanks** [comment]
> 类似的issue 问题都没有解决 全部被close 掉了

@tangjinzhou

**Comment by jaycethanks** [comment]
@Ben-Ben-B
请问 你这个问题解决了嘛

**Comment by Ben-Ben-B** [comment]
> @Ben-Ben-B 请问 你这个问题解决了嘛

没有，之前用e.stopPropagation()，禁止冒泡啥的，没用，还是有问题的，现在这个需求已经砍掉了，所以不管这个了

**Comment by jaycethanks** [comment]
> ```
> @click="e=>e.target.focus()"
> ```

哦哦

**Comment by Ben-Ben-B** [comment]
> @Ben-Ben-B 请问 你这个问题解决了嘛

没有，之前用e.stopPropagation()，禁止冒泡啥的，没用，还是有问题的，现在这个需求已经砍掉了，所以不管这个了 @jaycethanks

**Comment by jaycethanks** [comment]
> 哦哦

**Comment by yaowangmx** [comment]
有没有人解决了的呢？
