### ISSUE TITLE
input element can not focus

### ISSUE THREAD

**Issue by nghialamngoc** [vueComponent/ant-design-vue#2574]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-bjpcj?file=/src/components/HelloWorld.vue&fbclid=IwAR34PiSYZ6oW3QRZ0U6EEs1yd8SUHGNjGqsh82pxDoWyDmA2mpKW1LOYzY0)

### Steps to reproduce
press one first item in cascade dropdown you can see an input element but you can focus on this

### What is expected?
input element can focus

### What is actually happening?
the input element can not focus

**Comment by tangjinzhou** [comment]
I think you should change the component. Even if you can focus, there will still be other problems
