### ISSUE TITLE
手机端table样式demo不自适应

### ISSUE THREAD

**Issue by fu827707013** [vueComponent/ant-design-vue#2578]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
手机端table显示问题

### What does the proposed API look like?
element并入蚂蚁后，现在elementui似乎已经没维护了，不知道是否放弃了element，主攻ant，
本人之前手机端UI选择，就是鉴于ant表格样式异常，才选择element的，希望ant能做的刚好，更完善
https://element.eleme.cn/#/zh-CN/component/table

**Comment by xrkffgg** [comment]
https://antdv.com/docs/vue/faq-cn/#ant-design-vue-%E5%9C%A8%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%BD%93%E9%AA%8C%E4%B8%8D%E4%BD%B3%E3%80%82
