### ISSUE TITLE
侧边导航栏收起时报错

### ISSUE THREAD

**Issue by yanglu1019** [vueComponent/ant-design-vue#258]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
chrome 70.0.3538.77   vue:2.5.17

### Reproduction link
[https://codepen.io/curryYang/pen/dQGjLK?editors=1111](https://codepen.io/curryYang/pen/dQGjLK?editors=1111)

### Steps to reproduce
https://codepen.io/curryYang/pen/dQGjLK?editors=1111

### What is expected?
可以正常收起展开

### What is actually happening?
展开时正常，收起报错

---
https://codepen.io/curryYang/pen/dQGjLK?editors=1111

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/48302702-befe4980-e53a-11e8-8758-ec33e2b4f1ce.png)
若使用驼峰传参便全部使用驼峰，你这个一般驼峰一般短横线的不支持
