### ISSUE TITLE
手风琴折叠面板默认展开无效？怎么会有这么明显的bug

### ISSUE THREAD

**Issue by cyt68** [vueComponent/ant-design-vue#2585]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
手风琴折叠面板默认展开无效？

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
手风琴折叠面板默认展开无效？

### What is expected?
手风琴折叠面板默认展开无效？

### What is actually happening?
手风琴折叠面板默认展开无效？

---
手风琴折叠面板默认展开无效？

**Comment by tangjinzhou** [comment]
没能复现  请提供有效复现示例

**Comment by cyt68** [comment]
折叠面板使用accordion为true，defaultActiveKey就无效了啊

**Comment by cyt68** [comment]
> 没能复现 请提供有效复现示例

折叠面板使用accordion为true，defaultActiveKey就无效了啊

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by cyt68** [comment]
> https://www.antdv.com/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

这里面没有我说这个问题

**Comment by cyt68** [comment]
> https://www.antdv.com/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82



> 没能复现 请提供有效复现示例

建议处理一下，现在只有用普通的折叠面板模拟手风琴，而且这样bug真的太明显了

**Comment by tangjinzhou** [comment]
我依然不明白你说的啥问题   请提供符合规范的issue以及复现示例

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/condescending-mirzakhani-sxn8d?file=/src/App.vue 

没发现你说的问题

**Comment by cyt68** [comment]
> https://codesandbox.io/s/condescending-mirzakhani-sxn8d?file=/src/App.vue
> 
> 没发现你说的问题

神奇了，我这同样的写法就会有问题

**Comment by cyt68** [comment]
> https://codesandbox.io/s/condescending-mirzakhani-sxn8d?file=/src/App.vue
> 
> 没发现你说的问题

找到问题了，a-collapse-panel的key值不能是数字只能是字符串，a-collapse的activeKey又可以是数字。。。

**Comment by cyt68** [comment]
> 我依然不明白你说的啥问题 请提供符合规范的issue以及复现示例

找到问题了，a-collapse-panel的key值不能是数字只能是字符串，a-collapse的activeKey又可以是数字。。。都必须设置为字符串否则就无法触发默认状态。。。虽然是值类型传的不对，但是1和‘1’这种如果是后端传来的不一定都回去转化，还是麻烦处理兼容下吧。。。
