### ISSUE TITLE
Table 当Http请求数据时， defaultExpandAllRows=true 展开子列表无效果

### ISSUE THREAD

**Issue by mx4g** [vueComponent/ant-design-vue#2587]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
@vue/cli 4.0.5

### Reproduction link
[http://47.105.96.22/pension/#/user/login](http://47.105.96.22/pension/#/user/login)

### Steps to reproduce
做了一个可以展开的Table，但 Http请求数据时， defaultExpandAllRows=true 展开子列表无效果，静态数据就有效果，这个Bug怎么解决。

### What is expected?
希望能解决这个问题，这个功能太需要了

### What is actually happening?
Table 当Http请求数据时， defaultExpandAllRows=true 展开子列表无效果

**Comment by mx4g** [comment]
@tangjinzhou

**Comment by mx4g** [comment]
![image](https://user-images.githubusercontent.com/7499986/88025928-a5166600-cb67-11ea-86de-93aaabb92d7f.png)

**Comment by labike** [comment]
:default-expand-all-rows="defaultExpandAllRows"

data () {
    defaultExpandAllRows: true
}

**Comment by labike** [comment]
加个判断 v-if="!loading"

在请求数据之前将loading=“true"

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

或者使用  expandedRowKeys

**Comment by mx4g** [comment]
> expandedRowKeys

设置了expandedRowKeys
，只可以展开，不能收缩回去
![image](https://user-images.githubusercontent.com/7499986/88246091-00f9ff80-cccc-11ea-8aa6-c169a400869a.png)
