### ISSUE TITLE
table文档中可拖拽，在遇到配置了rowSelection报错col is undefined

### ISSUE THREAD

**Issue by WangChenlin520** [vueComponent/ant-design-vue#2588]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
2.6

### Steps to reproduce
col is undefined

### What is expected?
自动略过复选

### What is actually happening?
col is undefined

**Comment by labike** [comment]
@WangChenlin520 尽量贴代码
