### ISSUE TITLE
upload.js组件remove方法问题

### ISSUE THREAD

**Issue by luoyang125024608** [vueComponent/ant-design-vue#259]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
any

### Reproduction link
[https://tangjinzhou.gitee.io/ant-design-vue/components/upload-cn/](https://tangjinzhou.gitee.io/ant-design-vue/components/upload-cn/)

### Steps to reproduce
```javascript
/* this.$emit('remove', file) , return value is this , not Boolean or Promise */
handleRemove: function handleRemove(file) {
var _this2 = this;

Promise.resolve(this.$emit('remove', file)).then(function (ret) {
// Prevent removing file
if (ret === false) {
return;
}

var removedFileList = (0, _utils.removeFileItem)(file, _this2.sFileList);
if (removedFileList) {
_this2.onChange({
file: file,
fileList: removedFileList
});
}
});
},

```

### What is expected?
ret : Boolean or Promise

### What is actually happening?
ret : this === Component

**Comment by tangjinzhou** [comment]
@wangxueliang $emit的返回值是this，这是vue的特性，改用回调方式吧
