### ISSUE TITLE
a-input组件type为textarea时pressEnter事件会触发2次

### ISSUE THREAD

**Issue by Aiwass-wj** [vueComponent/ant-design-vue#2590]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.1

### Environment
UA：Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36        
Vue版本：2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-btwjx?file=/src/App.vue)

### Steps to reproduce
在type为textarea的a-input组件中按下一次回车按键

### What is expected?
pressEnter事件会只触发1次

### What is actually happening?
pressEnter事件会触发了2次

**Comment by labike** [comment]
type="textarea"时, ant design vue内部是用<input />将<textare />包裹了一层, 所以回车触发的事件应该是
```
<textarea /> --> pressEnter
<input /> --> pressEnter
<input /> --> keyDown
<textarea /> ---> keyDown
```
<Textarea />里是这样的
```
handleKeyDown(e) {
    if (e.keyCode === 13) {
        this.$emit('pressEnter', e);
    }
    this.$emit('keydown', e);
},
```
同时<Input />内部在渲染时做了判断
```
if (this.$props.type === 'textarea') {
      const textareaProps = {
        props: this.$props,
        attrs: this.$attrs,
        on: {
          ...getListeners(this),
          input: this.handleChange,
          keydown: this.handleKeyDown,
          change: noop,
        },
      };
      return <TextArea {...textareaProps} ref="input" />;
    }
```
例外官网文档里也介绍了用`Input.TextArea`代替`type="textarea"`

注: 可以在vuedevtools调试看一下
