### ISSUE TITLE
table里面的设置 column.ellipsis 让单元格内容根据宽度自动省略 显示的内容能否跟react版本的一致使用Tooltip展示，现在用的是原生的title,不方便复制

### ISSUE THREAD

**Issue by xiaofuliang** [vueComponent/ant-design-vue#2591]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用Tooltip 显示可以方便复制，使用原生的title不方便查看以及复制

### What does the proposed API look like?
无

**Comment by xrkffgg** [comment]
https://ant.design/components/table-cn/#components-table-demo-ellipsis

我看了下 react 版本的官方 Demo ，并没有发现使用 Tooltip 啊

**Comment by xiaofuliang** [comment]
@xrkffgg 看错了不好意思，他只是增加了一个ellipsis {showTitle:Boolean}的一个支持，还是自己在render里面返回的Tooltip
