### ISSUE TITLE
IE11环境下Input组件清空异常

### ISSUE THREAD

**Issue by hy08** [vueComponent/ant-design-vue#2592]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
browser: IE11 ant-design-vue: 1.6.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-vue-demo-fu9qs?file=/src/App.vue)

### Steps to reproduce
基础的Input组件，声明allowClear属性，chrome删除正常，ie11报错：Error in v-on handler: "TypeError: strict 模式下不允许分配到只读属性"

### What is expected?
ie可以正常删除

### What is actually happening?
Error in v-on handler: "TypeError: strict 模式下不允许分配到只读属性"

**Comment by labike** [comment]
这是严格模式下导致的

首先这是发生在event上的, 在<Input />源码内部是这样实现点击清除图标清除输入内容的

```
function resolveOnChange(target, e, onChange) {
  if (onChange) {
    var event = e;
    if (e.type === 'click') {
      // click clear icon
      //event = Object.create(e);
      Object.defineProperty(event, 'target', {
        writable: true
      });
      Object.defineProperty(event, 'currentTarget', {
        writable: true
      });
      event.target = target;
      event.currentTarget = target;
      var originalInputValue = target.value;
      // change target ref value cause e.target.value should be '' when clear input
      target.value = '';
      onChange(event);
      // reset target ref value
      target.value = originalInputValue;
      return;
    }
    onChange(event);
  }
}
```
可以看到这里对event的target进行了劫持并修改了writeable, target属性中有个configureable属性,该属性默认为false表示对象上的属性是只读的, 在严格模式下修改是会报`typeError '

**Comment by wayne950921** [comment]
想问这个问题解决了吗

**Comment by hy08** [comment]
> 想问这个问题解决了吗

我放弃在IE11中使用清除功能了

**Comment by liuqingchao** [comment]
请问此问题有解决计划吗？

**Comment by sanmaozhao** [comment]
遇到了同样的问题
