### ISSUE TITLE
采用CDN引用ant-design-vue，Menu导航菜单采用垂直菜单样式时图标不显示和引用图标的菜单项也不显示。

### ISSUE THREAD

**Issue by triumphtang** [vueComponent/ant-design-vue#2594]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vs2017的MVC项目，采用CDN方式引入， Menu导航菜单中的图标显示不正常。

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr?file=/src/main.js)

### Steps to reproduce
<span slot="title"><a-icon type="mail" /><span>Navigation One</span></span>，菜单项不能显示，删除“<a-icon type="mail" />”后菜单项正常显示。

### What is expected?
希望解决这个问题，谢谢！

### What is actually happening?
采用CDN引用ant-design-vue，Menu导航菜单采用垂直菜单样式时图标不显示和引用图标的菜单项也不显示。
提示错误“[antd: Icon] Make sure that you provide correct `viewBox` prop“

**Comment by sendya** [comment]
请提供一个最小复现的代码仓库或在线运行仓库

**Comment by triumphtang** [comment]
<a-menu mode="inline" :inline-collapsed="isCollapse" class="menulist">
    <a-sub-menu v-for="(item, index1) in sidemenu" :key="item.GroupId">
        <span slot="title"><a-icon type="appstore" /><span>{{item.GroupName}}</span></span>

        <a-sub-menu v-for="(item, index2) in item.ChildGroupItem" :key="item.GroupId" :title="item.GroupName">
            <a-menu-item v-for="(item, index3) in item.Items" :key="item.PrivilegeId" v-on:click="menuclick(item)">{{item.Name}}</a-menu-item>
        </a-sub-menu>
    </a-sub-menu>
</a-menu>
