### ISSUE TITLE
Table ellipsis和fixed 同时使用 ellipsis不生效

### ISSUE THREAD

**Issue by minteliuwm** [vueComponent/ant-design-vue#2598]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
chrome 84.0.4147.89  macOS 10.15.5 Vue 2.6.10

### Reproduction link
[https://github.com/ant-design/ant-design/issues/19946](https://github.com/ant-design/ant-design/issues/19946)

### Steps to reproduce
ellipsis和fixed 同时使用 ellipsis不生效

### What is expected?
ellipsis和fixed 同时使用 ellipsis 生效

### What is actually happening?
ellipsis和fixed 同时使用 ellipsis不生效

**Comment by zkwolf** [comment]
Fixed in v1.7.0
