### ISSUE TITLE
table组件固定高度

### ISSUE THREAD

**Issue by naolz** [vueComponent/ant-design-vue#2600]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用户在使用table表格时，数据只有一条的时候，分页就在表头下面，分页的组件根据表格数据撑下去的，当然设置了srcoll 的值，当数据量多的时候，只是出现了滚动条，并不是一开始表格就是设置的高度，百度上大家也遇到了类似的问题。

### What does the proposed API look like?
可传入表格的高度，：tableHeight="300",直接可传入表格高度，当然需要监听这个值是否改变，因为要随着浏览器的高度而改变，当然是用人员，也需要做处理；

**Comment by zkwolf** [comment]
直接用style控制就可以吧
