### ISSUE TITLE
按钮禁用颜色能否不要一刀切的全部为一个颜色，很不友好

### ISSUE THREAD

**Issue by zxiaozhou** [vueComponent/ant-design-vue#2604]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
1.6.4

### Reproduction link
[https://preview.pro.antdv.com/user/login(登录按钮)](https://preview.pro.antdv.com/user/login(登录按钮))

### Steps to reproduce
按钮的禁用颜色全是一刀切，我按钮type不管是primary还是其他，禁用的颜色都是白色，很难看

### What is expected?
我按钮如果是primary或者其他，我只是希望在原来基础上改变一点颜色，然后鼠标变成禁用样式，现在只能设置一个颜色。

### What is actually happening?
禁用不应该去修改主背景色，如果不好做其实就价格禁用样式就可以了。。没必要一刀切。

### 这是element的禁用颜色
![image](https://user-images.githubusercontent.com/62740686/88473918-990a1a00-cf54-11ea-8c4c-f42f9c2f5395.png)

**Comment by sendya** [comment]
ant design 为了兼顾大部分人，包括色弱用户，所设计的。  
如上你提供的样式，对用户体验来说也不友好，颜色淡一点并不能代表是禁用，但是强调色灰白一定可以

![image](https://user-images.githubusercontent.com/5404542/88474172-b213ca80-cf56-11ea-9394-79ec3173eb26.png)

如果认为还是觉得不适，可以通过 less 变量进行动态替换，或者前往蚂蚁金服antd 官方库发 issue 给出你的意见
