### ISSUE TITLE
Select 多选 没有 后缀图标，我觉得这是个bug，期待尽快修复！

### ISSUE THREAD

**Issue by DavidBye** [vueComponent/ant-design-vue#2609]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
1.6.4

### Reproduction link
[https://antdv.com/components/select-cn/](https://antdv.com/components/select-cn/)

### Steps to reproduce
Select 多选 没有 后缀图标

### What is expected?
Select 多选 加上slot 的 后缀图标

### What is actually happening?
Select 多选 加上slot 的 后缀图标

**Comment by xrkffgg** [comment]
That's the design. And `ant-design` is not support this too.

**Comment by DavidBye** [comment]
> That's the design. And `ant-design` is not support this too.

I think this design is right, but if has suffix icon multiselect and singleselect may be in step, hope that you will consider this proposal very much. Thank you.

**Comment by DavidBye** [comment]
![image](https://user-images.githubusercontent.com/15842231/89261804-466de380-d661-11ea-92a6-2b27b0c8dcaa.png)
你看iview的实现
