### ISSUE TITLE
select mode="multiple"  suffixIcon  not work

### ISSUE THREAD

**Issue by cnbizhh** [vueComponent/ant-design-vue#2610]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
Google Chrome 版本 81.0.4044.122（正式版本） （64 位）  vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-k29bj?file=/src/App.vue:586-592)

### Steps to reproduce
select mode="multiple"  suffixIcon  not work

### What is expected?
icon show

### What is actually happening?
not work

**Comment by cnbizhh** [comment]
repeat

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2609
