### ISSUE TITLE
form在ie11下不渲染表单

### ISSUE THREAD

**Issue by Lizifengli** [vueComponent/ant-design-vue#2611]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10，ie11，vue/cli4.4.6

### Reproduction link
[https://gitee.com/shaozhip/antDemo.git](https://gitee.com/shaozhip/antDemo.git)

### Steps to reproduce
直接按照官网步骤创建项目然后min.jsn.js里引入项目并初始化，把官网上的form的demo复制到app.vue

### What is expected?
可以在ie11下渲染

### What is actually happening?
只渲染了按钮没渲染input

**Comment by labike** [comment]
https://antdv.com/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7

yarn add babel-polyfill-D

main.js: import babel-polyfill'
