### ISSUE TITLE
Table的data-source为网络请求时defaultExpandAllRows/defaultExpandedRowKeys属性失效

### ISSUE THREAD

**Issue by faithcoco** [vueComponent/ant-design-vue#2612]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
1.6.4

### Reproduction link
[https://antdv.com/components/table-cn/](https://antdv.com/components/table-cn/)

### Steps to reproduce

<a-table :columns="columns" :data-source="list" defaultExpandAllRows> </a-table>
created() {
getclassificationGoodsList().then((res) => {
this.list = res.result
console.log('data-->', JSON.stringify(res.result))

})
},

### What is expected?
列表默认展开

### What is actually happening?
属性并没有运行

**Comment by labike** [comment]
https://github.com/vueComponent/ant-design-vue/issues/2587
参考官网远程加载数据

**Comment by zieru** [comment]
i have this issue, the best way is using key and update the key after load
```
<template>
.....
<a-table
              :key="dataserahouts.key"
.....
/>
</template>

methods: {
forceRerender () {
        this.dataserahouts.key += 1
      },
}

```
