### ISSUE TITLE
tabs组件和树组件在ie11显示不出来，麻烦看一下（另外管网地址在ie11都打不开）

### ISSUE THREAD

**Issue by cyt68** [vueComponent/ant-design-vue#2613]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
ie11

### Reproduction link
[https://www.antdv.com/components/tabs-cn/](https://www.antdv.com/components/tabs-cn/)

### Steps to reproduce
tabs组件和树组件在ie11显示不出来

### What is expected?
tabs组件和树组件在ie11显示不出来

### What is actually happening?
tabs组件和树组件在ie11显示不出来

**Comment by labike** [comment]
https://antdv.com/docs/vue/getting-started-cn/#兼容性

**Comment by cyt68** [comment]
> [https://antdv.com/docs/vue/getting-started-cn/#兼容性](https://antdv.com/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7)

官网在ie打不开咋回事呢

**Comment by labike** [comment]
SCRIPT1002: 语法错误
2dc7c4ab.async.js (2,1079240)
换主流浏览器

**Comment by cyt68** [comment]
> SCRIPT1002: 语法错误
> 2dc7c4ab.async.js (2,1079240)
> 换主流浏览器

。。。好吧

**Comment by labike** [comment]
@cyt68 这个应该是官网部署的问题不影响组件的使用
