### ISSUE TITLE
Menu的字菜单a-menu-item 能否横向排列 个数可定义

### ISSUE THREAD

**Issue by huoshidehua** [vueComponent/ant-design-vue#2614]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有时候子菜单很多再加上分组，整个菜单就变的很长

### What does the proposed API look like?
加一个 horizontal | vertical 属性，加一个 col 表示横向情况下需要几列 类似如下效果
![Image](https://raw.githubusercontent.com/huoshidehua/docfile/master/%E6%A8%AA%E5%90%91%E8%8F%9C%E5%8D%95.jpg)

**Comment by xrkffgg** [comment]
可以尝试使用 Dropdown 自定义样式一下

**Comment by huoshidehua** [comment]
这就给close了

**Comment by xrkffgg** [comment]
UI 是通用组件，而且我们的设计遵从 Ant-Design 的设计规范。你可以去 ant-design 提个 issue，如果他们添加了，后续我们也会添加。
