### ISSUE TITLE
TreeSelect组件特定情况滚动条上下跳的问题

### ISSUE THREAD

**Issue by zhuojun1024** [vueComponent/ant-design-vue#2615]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
系统版本：Windows 10 教育版 1909 ；浏览器版本：版本 84.0.4147.89（正式版本） （64 位）；Vue版本：2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-wind-lu180?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
页面加载完成，首次点击选择框，滚动条会在最底部，第二次点击时，滚动条跳到了顶部，第三次点击时，滚动条跳到了底部，以此反复。去掉showSearch后滚动条正常。

### What is expected?
滚动条在顶部或者所选项在视野内

### What is actually happening?
滚动条会上下乱跳

---
只有根节点被选中，并且设置了下拉框最大高度，并且选项较多出现了滚动条，并且设置了showSearch，才会出现的情况

**Comment by xrkffgg** [comment]
神奇

**Comment by xrkffgg** [comment]
其实原因是，当 value 为父节点时，domNode 为 父节点 和子节点的 整个元素，这样在计算的时候，出现问题。将 domNode 改为父节点的根元素即可。

**Comment by xrkffgg** [comment]
Will be fixed in https://github.com/vueComponent/ant-design-vue/tree/feat-vue3
