### ISSUE TITLE
switch asynchronous

### ISSUE THREAD

**Issue by jiujiezongheti** [vueComponent/ant-design-vue#2616]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
When using the switch, sometimes need to use the scene, for example: click the switch to ask whether it needs to be turned on or off

### What does the proposed API look like?
Problems that can be applied to descriptions

**Comment by xrkffgg** [comment]
`ant-design-vue` is based on`ant-design`, you can go https://github.com/ant-design/ant-design/issues to present your ideas.
