### ISSUE TITLE
Property 'split' invalid in nested list

### ISSUE THREAD

**Issue by lsvih** [vueComponent/ant-design-vue#2618]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
All the environmental, I guess

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-f7l4z) [Link](https://codesandbox.io/s/vue-antd-template-f7l4z)

### Steps to reproduce
codesandbox gave a reproducible example.

### What is expected?
The child list should not be split while parent list be split.

### What is actually happening?
Both child and parent list are split.

---
The `border-bottom` style of list item is controlled by `.ant-list-split .ant-list-item` selector.

It works in non-nest list while `split` property set as `false`. But if only setting `split` as `false` in child list, the parent list still has '.ant-list-split' class, which caused `border-bottom` style appear.

**Comment by xrkffgg** [comment]
加个 style 直接覆盖就行了

**Comment by lsvih** [comment]
@xrkffgg 我就是这么做的哈哈。不过还是提了个 issue，因为这个问题是客观存在的。我能想到的解决方案代价有点大，所以就不提 PR 了，等各位大神解决 🤦

**Comment by xrkffgg** [comment]
classname + classname + classname 列举出所有情况可以解决，但觉得麻烦，直接 style 更简单。
毕竟感觉这种使用场景很少。List  套 List
