### ISSUE TITLE
tabs组件在切换tab时出现tab内容DOM重新渲染的问题

### ISSUE THREAD

**Issue by rochzp** [vueComponent/ant-design-vue#2620]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
macOS 10.15.5, chrome 84.0.4147.89

### Reproduction link
[https://www.antdv.com/components/tabs-cn/](https://www.antdv.com/components/tabs-cn/)
基本用法

### Steps to reproduce
使用chrome 控制查看DOM元素，点击切换tab
![QQ20200729-162439-HD](https://user-images.githubusercontent.com/18065807/88778696-69a91680-d1bb-11ea-8d91-c58cf8ce0f26.gif)

### What is expected?
切换tab时，不出现DOM重新渲染变化，只是隐藏

### What is actually happening?
DOM重新渲染，发生变化

**Comment by zoux** [comment]
你可以根据当前激活的 tab 绑定值，自己用容器+v-show/v-if 去自由控制隐藏/重渲染，而不是放在tab-pane中吧？

**Comment by rochzp** [comment]
> 你可以根据当前激活的 tab 绑定值，自己用容器+v-show/v-if 去自由控制隐藏/重渲染，而不是放在tab-pane中吧？
目前暂时的解决办法是控制自己的容器去处理。如果不放在tab-pane中，那么tab-pane的作用是啥？如果是显示tab用的，直接用属性传递数据就好了啊，就没有必要的tab-pane组件了。并且在ant design react版本中不会出现重新渲染。

**Comment by SCWR** [comment]
+1

**Comment by happydoop** [comment]
不只是重新渲染的问题，当某个tab内容过多时（如某个tab中有10个 handsontable 实例），此时切换tab会变得 **非常** 卡顿，通过性能分析，发现tabs会频繁调用 js 中的 getComputedStyle 方法导致不断reflow：

![源码截图](https://user-images.githubusercontent.com/74850387/105783985-c80c5180-5fb2-11eb-9743-50014fcf6944.png)

光是这一个函数调用就用了437.6ms！

**Comment by rochzp** [comment]
希望vue3的ant design vue 2.0 版本有所改进吧



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "happydoop"<notifications@github.com&gt;; 
发送时间: 2021年1月26日(星期二) 上午8:48
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "酷儿"<838144786@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] tabs组件在切换tab时出现tab内容DOM重新渲染的问题 (#2620)





 
不只是重新渲染的问题，当某个tab内容过多时（如某个tab中有10个 handsontable 实例），此时切换tab会变得 非常 卡顿，通过性能分析，发现tabs会频繁调用 js 中的 getComputedStyle 方法导致不断reflow：
 

 
光是这一个函数调用就用了437.6ms！

**Comment by rochzp** [comment]
antdv2 自己通过v-show/v-if 去控制解决，antdv3已经解决了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月29日(星期五) 上午9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] tabs组件在切换tab时出现tab内容DOM重新渲染的问题 (#2620)





 
楼主最后解决这个问题了吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by rochzp** [comment]
> 楼主最后解决这个问题了吗？

antdv2 自己通过v-show/v-if 去控制解决，antdv3已经解决了

**Comment by luoyonglan** [comment]
完蛋，我们用的是2版本
