### ISSUE TITLE
ant design  是否会考虑选择替换为dayjs 

### ISSUE THREAD

**Issue by jahnli** [vueComponent/ant-design-vue#2622]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
考虑到包的大小，你可以用自定义日期库替换 Moment。 ， 目前的方案Moment ，俩者使用作者有何见解

### What does the proposed API look like?
win10

**Comment by sendya** [comment]
后续会跟进 react antd 的方案 https://ant.design/docs/react/replace-moment-cn 但不会移除 moment

**Comment by nickolboy** [comment]
装个antd-dayjs-webpack-plugin就好了

**Comment by iamkun** [comment]
我是 Day.js 和 antd-dayjs-webpack-plugin 的作者，如果有需要，很乐意提供帮助

**Comment by xqdoo00o** [comment]
moment.js 是维护状态了，https://momentjs.com/docs/#/-project-status/
https://github.com/ant-design/ant-design/issues/26759

**Comment by xiaoxiangmoe** [comment]
ng-zorro-antd 现在使用 date-fns 了

**Comment by athrunsun** [comment]
即使有antd-dayjs-webpack-plugin，我还是想问一下，有没有改掉mutable写法的打算？比如[`lastMonth1.add(0 - lastMonthDiffDay, 'days')`](https://github.com/vueComponent/ant-design-vue/blob/06b7e33cc0a76670e669d36ee2d16428ea9ae79f/components/vc-calendar/src/date/DateTBody.jsx#L82)和[`current.add(passed, 'days')`](https://github.com/vueComponent/ant-design-vue/blob/06b7e33cc0a76670e669d36ee2d16428ea9ae79f/components/vc-calendar/src/date/DateTBody.jsx#L89)？

按照现在的写法，用antd-dayjs-webpack-plugin的时候必须用`antdv3`这个preset，它包含有`badMutable`这个插件，可以把dayjs变成mutable的，以完全兼容momentjs的mutable写法。但我觉得这样的话就**没有达到使用dayjs的全部目的了**——bundle size是减小了，却还是要用mutable的写法、要注意小心避免这种写法在不经意的时候修改了不想修改的dayjs实例。

**Comment by dzcpy** [comment]
@athrunsun 不知道有尝试 ant design vue 2.x 吗？不加 antdv3 能正常工作吗？

还是希望作者能考虑下彻底转换成 dayjs，moment 已经不怎么维护了

**Comment by athrunsun** [comment]
@dzcpy 尝试过了，必须用antdv3 preset才行。

**Comment by tangjinzhou** [comment]
3.0 版本会进行更换   2.0已经 release 了，不适合加入破坏性的改动

**Comment by es3154** [comment]
> 我是 Day.js 和 antd-dayjs-webpack-plugin 的作者，如果有需要，很乐意提供支持

请问下，我在其他地方引用了moment， antd-dayjs-webpack-plugin 是否可以替换掉

**Comment by StarFishing** [comment]
> 我是 Day.js 和 antd-dayjs-webpack-plugin 的作者，如果有需要，很乐意提供支持

有个valueformat支持问题，已在antd-dayjs-webpack-plugin 提issue
