### ISSUE TITLE
Modal 对话框设置:maskClosable="false"没有效果

### ISSUE THREAD

**Issue by mildspark** [vueComponent/ant-design-vue#2623]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
chrome 84.0.4147.89 32位

### Reproduction link
[https://w5mpp.csb.app/](https://w5mpp.csb.app/)

### Steps to reproduce
设置a-modal 的属性 :maskClosable="false"，点击按钮打开modal

### What is expected?
希望点击遮罩层的时候不会关闭modal

### What is actually happening?
点击遮罩层的时候modal会关闭

**Comment by xrkffgg** [comment]
请使用  https://codesandbox.io/s/vue-antd-template-e22bh 提交复现。

**Comment by labike** [comment]
@mildspark 
```
:maskClosable="maskClosable"

data () {
    return{
        maskClosable: false
    } 
}
```

**Comment by mildspark** [comment]
https://codesandbox.io/s/wandering-grass-w5mpp

**Comment by labike** [comment]
@mildspark https://codesandbox.io/s/compassionate-fast-1size?file=/src/main.js

**Comment by mildspark** [comment]
感谢大家的指点，但是我这问题是发生在传统的浏览器引入js的html的开发，不是用vue-cli的开发。

`<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@1.6.4/dist/antd.css">
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.11/dist/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ant-design-vue@1.6.4/dist/antd-with-locales.js"></script>
    <title>Title</title>
</head>
<body>
    <div id="vm-content">

            <div>
                <a-button type="primary" @click="showModal">
                    Open Modal
                </a-button>
                <a-modal v-model="visible" title="Basic Modal" :mask="true" :maskClosable="maskClosable" @ok="handleOk">
                    <p>Some contents...</p>
                    <p>Some contents...</p>
                    <p>Some contents...</p>
                </a-modal>
            </div>

    </div>
</body>

<script>

    new Vue({
        el: '#vm-content',
        data: {
            visible: false,
            maskClosable: false
        },
        methods: {
            showModal() {
                this.visible = true;
            },
            handleOk(e) {
                console.log(e);
                this.visible = false;
            },
        },
    });
    </script>
</html>`

**Comment by labike** [comment]
@mildspark 究其原因是组件实例并不是modal，所以modal上没有这些属性, 而这些属性在`el: "#vm-content"`这个组件的实例上

**Comment by mildspark** [comment]
@labike 所以目前这种传统开发方式就没办法了？
