### ISSUE TITLE
Button type added other color

### ISSUE THREAD

**Issue by vciloglu** [vueComponent/ant-design-vue#2627]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
There are very few color options in the buttons. I want more than one color option.

### What does the proposed API look like?
nuxt

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/1825
