### ISSUE TITLE
Safari浏览器下Menu组件切换报错：ReferenceError: Can't find variable: objectInnerText onDocClick

### ISSUE THREAD

**Issue by wu-weichao** [vueComponent/ant-design-vue#2628]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
Vue 2.6.11  Safari 13.1.1

### Steps to reproduce
点击菜单报错
ReferenceError: Can't find variable: objectInnerText    onDocClick
onDocClick一script.js:48

**Comment by xrkffgg** [comment]
13.1.2 点击官网Demo 无法复现

**Comment by wwc543198585** [comment]
你指的是示例代码吗？
