### ISSUE TITLE
如何去掉 a-form-item 的 label标签的冒号

### ISSUE THREAD

**Issue by hegphegp** [vueComponent/ant-design-vue#2630]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

* 如何去掉 a-form-item 的 label标签的冒号
![image](https://user-images.githubusercontent.com/26202719/88933038-7445d780-d2b1-11ea-9060-b55b4ce03606.png)

### What problem does this feature solve?
```
<a-form-item label="Activity name">
    <a-input v-model="form.name" placeholder=""/>
</a-form-item>
```

**Comment by mildspark** [comment]
文档上有，form的参数有colon | 配置 Form.Item 的 colon 的默认值 (只有在属性 layout 为 horizontal 时有效)
Form.Item上也有这个属性

**Comment by xrkffgg** [comment]
配置 `:colon="false"` 即可。
