### ISSUE TITLE
官方文档——自定义icon文档错误

### ISSUE THREAD

**Issue by suerssk** [vueComponent/ant-design-vue#2633]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
ant-design-vue 1.6.4

### Environment
Windows 7, Chrome 84.0.4147.89（正式版本）, vue 2.6.10 / vue 2.6.11

### Reproduction link
[https://github.com/suerssk/ant-design-vue-icon-demo](https://github.com/suerssk/ant-design-vue-icon-demo)

### Steps to reproduce
依据[官方文档](https://www.antdv.com/components/icon-cn/#components-icon-demo-custom-icon)的自定义图标用法，作为组件使用

### What is expected?
模板语法实现自定义图标

### What is actually happening?
使用 jsx语法及 render 函数可以实现；但是官方文档的 `template` 用法，直接会报错——模板编译器不可用（建议更新一下官方文档）

**Comment by lihqi** [comment]
vue-svg-loader 不香嘛？

**Comment by suerssk** [comment]
> vue-svg-loader 不香嘛？

我就是看文档的写法错了，尝试用 jsx 语法写了一下，没有去找其他的库 [/手动捂脸]

**Comment by sendya** [comment]
https://cn.vuejs.org/v2/guide/installation.html#%E8%BF%90%E8%A1%8C%E6%97%B6-%E7%BC%96%E8%AF%91%E5%99%A8-vs-%E5%8F%AA%E5%8C%85%E5%90%AB%E8%BF%90%E8%A1%8C%E6%97%B6
