### ISSUE TITLE
Documentation website doesn't work on VPN

### ISSUE THREAD

**Issue by yonas-g** [vueComponent/ant-design-vue#2635]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
browser version

### Steps to reproduce
Website issue while on VPN

### What is expected?
allow website on VPM

### What is actually happening?
website not working

**Comment by xrkffgg** [comment]
Website is normal, you should check your web.
