### ISSUE TITLE
www.antdv.com/docs/vue/introduce/ site can't display on safari

### ISSUE THREAD

**Issue by qixiaodong** [vueComponent/ant-design-vue#2636]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
safari5.1.7

### Reproduction link
[https://www.antdv.com/docs/vue/introduce/](https://www.antdv.com/docs/vue/introduce/)

### Steps to reproduce
open https://www.antdv.com/docs/vue/introduce/

### What is expected?
display content

### What is actually happening?
no display

![QQ截图20200803082156](https://user-images.githubusercontent.com/24423288/89135867-0d4f4980-d563-11ea-9eef-1aaecced475b.png)

**Comment by xrkffgg** [comment]
You should update your safari version.
