### ISSUE TITLE
Modal.method() 换行显示信息

### ISSUE THREAD

**Issue by Duzx5517** [vueComponent/ant-design-vue#2638]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Modal.method()显示一些信息。有些信息是从后台返回的，返回的信息中有换行符，可以根据换行符换行。

### What does the proposed API look like?
后台返回数据是字符串，可以将字符串在 modal.method 用html方式显示

**Comment by labike** [comment]
文档中content返回类型可以为string/vnode/function(h)
例如:
```
export default {
  methods: {
    info() {
      const h = this.$createElement;
      this.$info({
        title: 'This is a notification message',
        content: h('div', {}, [
          h('p', 'some messages...some messages...'),
          h('p', 'some messages...some messages...'),
        ]),
        onOk() {},
      });
    },

    success() {
      this.$success({
        title: 'This is a success message',
        // JSX support
        content: (
          <div>
            <p>some messages...some messages...</p>
            <p>some messages...some messages...</p>
          </div>
        ),
      });
    },
```

**Comment by lihqi** [comment]
你需要的是[v-html](https://cn.vuejs.org/v2/api/#v-html)？

**Comment by Duzx5517** [comment]
> 你需要的是[v-html](https://cn.vuejs.org/v2/api/#v-html)？

是的。
或者为Modal.method() 增加局部样式，根据换行符换行显示
 Modal.method() 现有的方法 无法将后台返回的信息按要求显示

**Comment by zy017** [comment]
> > 你需要的是[v-html](https://cn.vuejs.org/v2/api/#v-html)？
> 
> 是的。
> 或者为Modal.method() 增加局部样式，根据换行符换行显示
> Modal.method() 现有的方法 无法将后台返回的信息按要求显示
> 
> 返回的信息 "xxxxxxxxxxxxx \n xxxxxxxxxxx \n xxxxxxxxxxx" 或 "<p> xxxxxxxx </p> <p>xxxxxxxxxxxx</p>"

可以这样实现
```js
this.$info({
  title: 'title',
  content: (
    <div domPropsInnerHTML={ htmlString } />
  ),
  onOk() {},
})
```
htmlString 是代表 html字符串的变量
