### ISSUE TITLE
a-alert组件配合v-show失效

### ISSUE THREAD

**Issue by silite** [vueComponent/ant-design-vue#2640]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10 every, chrome 84.0.4147.105 x64, vue 2. 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-kv4ym?file=/src/App.vue)

### Steps to reproduce
如沙箱类似代码。

### What is expected?
可随意切换是否显示。

### What is actually happening?
第二次切换时v-alert所渲染的DOM元素消失，变为注释标签。

**Comment by xrkffgg** [comment]
Alert 组件设计就是这样的。你可以尝试其他组件或者自己 div 一个。
