### ISSUE TITLE
MonthCalendar 本地化异常

### ISSUE THREAD

**Issue by oushiran** [vueComponent/ant-design-vue#2646]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
win10 chrome

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
官网示例，随便打开一个 RangerPicker或者一个DatePicker
在日期选择的时候，展示的是 2020年 Aug
**Aug** 没有本地化。
点击 **Aug** 展开的 **MonthCalendar** 也没有本地化

### What is expected?
本地化后应该展示 2020年8月，
MonthCalender 里面也应该是 一月到十二月

### What is actually happening?
RangerPicker 和 DatePicker 顶部的日期展示是2020年**Aug**，
MonthCalender 里面也应该是 Jan 到 Dec

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2527
