### ISSUE TITLE
Input currency format

### ISSUE THREAD

**Issue by vciloglu** [vueComponent/ant-design-vue#2647]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I use a-form-model. I have a money entry in my inputs. I want it to display this entry as a decimal.

### What does the proposed API look like?
https://vuejs-tips.github.io/v-money/

**Comment by labike** [comment]
may be you can ues <a-input-number />

**Comment by vciloglu** [comment]
can be used for single input. but not useful for input group.

In my form there is a currency select next to input and this input contains a validation rule.

a-input-number does not contain any slots.

**Comment by labike** [comment]
@vciloglu demo running codesandbox, i need environment.
