### ISSUE TITLE
Alert警告组件的按钮在ios移动端浏览器样式异常

### ISSUE THREAD

**Issue by Bean19940228** [vueComponent/ant-design-vue#2652]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
ios 13.5.1, Safari, 2.6

### Reproduction link
[https://www.antdv.com/components/alert-cn/](https://www.antdv.com/components/alert-cn/)

### Steps to reproduce
官网在ios移动端打开时, Alert组件的按钮样式异常

### What is expected?
好看的样式

### What is actually happening?
奇怪的样式

**Comment by xrkffgg** [comment]
https://www.antdv.com/docs/vue/faq-cn/#ant-design-vue-%E5%9C%A8%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%BD%93%E9%AA%8C%E4%B8%8D%E4%BD%B3%E3%80%82
