### ISSUE TITLE
@simonwep/pickr  这个包在npm中消失了  https://registry.npmjs.org/@simonwep/pickr 

### ISSUE THREAD

**Issue by lingxiaoyi** [vueComponent/ant-design-vue#2655]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
最新的

### Environment
windows

### Reproduction link
[https://registry.npmjs.org/@simonwep/pickr](https://registry.npmjs.org/@simonwep/pickr)

### Steps to reproduce
npm i

### What is expected?
@simonwep/pickr  这个包在npm中消失了  https://registry.npmjs.org/@simonwep/pickr

### What is actually happening?
@simonwep/pickr  这个包在npm中消失了  https://registry.npmjs.org/@simonwep/pickr
但是在cnpm中还在存在的 https://registry.npm.taobao.org/@simonwep/pickr
然后项目依赖这个包  我想知道为什么npm中删除了

**Comment by lingxiaoyi** [comment]
我项目依赖这个包安装.导致我现在上线打包出问题了

**Comment by lingxiaoyi** [comment]
现在又有了  搞毛线呢

**Comment by sendya** [comment]
不是你的网络不稳定，就是 npmjs 不稳定，这种情况我们这边没办法处理

https://www.npmjs.com/package/@simonwep/pickr

**Comment by lingxiaoyi** [comment]
我严重怀疑是这个库的作者上传新版本导致的  我看了下现在版本升级到1.7.2了,上传新版本把旧版本删了?

**Comment by lingxiaoyi** [comment]
我网络没问题的  其他包全安装成功了  唯独提示这个没有 害我解决这问题一个小时多

**Comment by lingxiaoyi** [comment]
尝试了N多次  才发现是这个库导致的

**Comment by sendya** [comment]
npm 库在推送超过 10 分钟后，均不能撤回，所以你的猜测也不可能

**Comment by lingxiaoyi** [comment]
好  你说什么都对,毕竟已经出现了

**Comment by sendya** [comment]
如果你觉得有问题 了，可以找这个 pickr 库作者反馈
