### ISSUE TITLE
a-input-number 当初始的 v-model 小于 min 时 显示值和实际值不符

### ISSUE THREAD

**Issue by viruscamp** [vueComponent/ant-design-vue#2657]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
ant-design-vue: 1.6.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-vwyjj)

### Steps to reproduce
```html
<a-input-number v-model="x" :min="10"/>
<div>x={{x}}</div>
<a-button @click="x=8">set x=8</a-button>
```
x的初始值 为9 而a-input-number显示的是10 显示值和实际值不一致

当修改过 a-input-number 的值后 比如改成 7 这时 x=10 显示 10 显示值和实际值一致了

点击 x=8 的button 又变成 显示值和实际值不一致

ant-design-vue: 1.4.12 时 显示值和实际值始终保持一致 但可能与最小值不符 不符合 min 条件

### What is expected?
一定要保持 显示值和实际值一致
1. 要么像 1.4.12 一样不修正
2. 要么显示成最小值 10 的同时 修正 v-model

### What is actually happening?
显示值和实际值不一致

**Comment by xrkffgg** [comment]
`:min="10"`

你改成 7 后，点其他地方看看

**Comment by viruscamp** [comment]
通过 a-input-number 改的 不管时点上下还是输入 都没问题的

我宁愿像 1.4.12 一样值不符合 min 条件 也不希望显示值和实际值不同

**Comment by xrkffgg** [comment]
输入后 根据 min max 进行调整，这是预期的。

**Comment by viruscamp** [comment]
当值 不是 a-input-number 改的时候 实际值并没有根据 min max 调整 但是显示值调整了 这就导致了显示值和实际值不同

**Comment by xrkffgg** [comment]
我觉得这种情况，需要自己来判断处理一下。通用组件不可能满足所有定制需求。

**Comment by viruscamp** [comment]
我有一个后台数据
```json
{ num: 3, text: '' }
```
显示为
```html
<a-input-number v-model="num" :min="10" />
<a-input v-model="text" />
```
我看见 数字 num 是 10 我认为没有问题 填了 text 提交

但最终后台接到的数据 num=3

**Comment by viruscamp** [comment]
我觉得应该改成 1.4.12 的那种方式保证实际值与显示值一致

再加上一个功能 当实际值不满足 min max 条件时 显示错误样式

**Comment by xrkffgg** [comment]
我认为你在定义组件 min=“10” 时候就是想让这个组件里的内容最小为 10。
如果是我来做这个，我会在拿到数据后，判断数据是否满足，如果不满足，就修改成 10。

组件无法满足所有的业务逻辑的。

**Comment by viruscamp** [comment]
业务逻辑应该那样做是一件事

组件在碰到矛盾时应该怎么做更好是另一件事
1. 1.4.12 的方式 不满足 min 或 max 条件 能保证显示值与实际值一致
2. 1.6.4. 的方式 看起来是满足 min 或 max 条件 但显示值与实际值不一致 实际值还是不合条件
3. 我建议的方式 保证显示值与实际值一致 但值不满足 min 或 max 条件时 显示错误样式

**Comment by xrkffgg** [comment]
PR welcome
