### ISSUE TITLE
Tree 树形控件 数据量大渲染组件非常慢

### ISSUE THREAD

**Issue by wzp20180518** [vueComponent/ant-design-vue#2658]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Tree树形控件，为整个集团所有员工配置权限，数据量在20万条左右，渲染时间大概30秒左右，而且渲染完之后页面出现假死状态，所有的功能都无法点击卡死

### What does the proposed API look like?
希望对 Tree树形控件 渲染机制进行优化，感谢

**Comment by Amour1688** [comment]
下个版本应该会优化的

**Comment by zhangkai0804** [comment]
@Amour1688 Tree树形控件，数据量大渲染慢，现在优化了么？
