### ISSUE TITLE
table 表格scopedSlots指定属性后，可以通过slot-scope获得哪些数据没有写在文档中

### ISSUE THREAD

**Issue by yanglu1019** [vueComponent/ant-design-vue#266]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
chrome 70.0.3538.77   vue:2.5.17

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/table-cn/#API]

### Steps to reproduce
scopedSlots: {
filterDropdown: 'filterDropdown'
}
slot="filterDropdown" slot-scope="props"
其中props包括哪些

### What is expected?
在文档中体现可获得的属性

### What is actually happening?
在文档中体现可获得的属性

**Comment by tangjinzhou** [comment]
欢迎PR
