### ISSUE TITLE
select 是否可以添加阻止值变化事件

### ISSUE THREAD

**Issue by xuejiaomeng** [vueComponent/ant-design-vue#2661]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue 2.5.17 ,Chrome浏览器, mac

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
select在选择时，添加验证失败，没有办法阻止数据变化，change不支持stop

### What is expected?
select在选择时，添加验证失败，阻止数据变化，即有个beforeChange方法，来添加逻辑处理，可以人为的不触发change事件

### What is actually happening?
在change方法前面添加验证，没法阻止数据变化

**Comment by xuejiaomeng** [comment]
已找到替用方案

**Comment by 0131LWG** [comment]
请问是用什么方案替代的我也遇到相似的问题，点击后需要验证后才进行选择的需求
