### ISSUE TITLE
ts项目中怎样使用antdesign?

### ISSUE THREAD

**Issue by wgf4242** [vueComponent/ant-design-vue#2664]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue 3.0rc1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
main.ts
```
import Vue from 'vue';
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';
Vue.config.productionTip = false;

Vue.use(Antd);
```

### What is expected?
不报错

### What is actually happening?

Property 'config' does not exist on type 'typeof import("node_modules/vue/dist/vue")'.
Property 'use' does not exist on type 'typeof import("node_modules/vue/dist/vue")'.

**Comment by abelit** [comment]
when ant-design-vue  support vue 3.0 (vue-next)?
