### ISSUE TITLE
Modal组件不显示遮罩，点击空白处仍然可以触发cancel事件

### ISSUE THREAD

**Issue by hzyhbk** [vueComponent/ant-design-vue#2667]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
Mac OS 10.15.4  Vue@2.6.11 Antd1.6.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-hill-dx4vd)

### Steps to reproduce
1.点击按钮，展示弹框
2. 点击空白处弹框被关闭

### What is expected?
点击空白处不触发cancel事件

### What is actually happening?
点击空白处触发了cancel事件

**Comment by xrkffgg** [comment]
`maskClosable` ?

**Comment by hzyhbk** [comment]
我的问题点不在于实现点击空白处不关闭弹框，而是组件`cancel`事件的触发逻辑有问题。设置`maskClosable`的前提不应该是`mask`为`true`吗？当我设置`mask`为`false`的时候，`mask`都不存在了，点击空白处竟然还能触发`cancel`事件，不是很诡异吗？
