### ISSUE TITLE
Support header slot for `Collapse.Panel`

### ISSUE THREAD

**Issue by kenrose** [vueComponent/ant-design-vue#267]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
In using [Collapse](https://vuecomponent.github.io/ant-design-vue/components/collapse/), I can only set a title on a panel `header` as a string.  For my use case, I want to show both a title *and* some text on the right side of the header.

### What does the proposed API look like?
The `Collapse.Panel` `header` allows `slot` in addition to `string`.

Example:

```html
<a-collapse v-model="activeKey">
  <a-collapse-panel key="1">

    <template slot="header">
      <div>Title</div>
      <div style="float: right;">Right hand content</div>
    </template>

    <p>Some content for the panel itself</p>
  </a-collapse-panel>
</a-collapse>
```

It looks like the `header` parameter just [makes a slot anyways](https://github.com/vueComponent/ant-design-vue/blob/master/components/collapse/CollapsePanel.jsx#L27), so I hope this is straightforward to implement.

**Comment by tangjinzhou** [comment]
I have already supported it, I am sorry that it is not stated in the document.
You can try it.

**Comment by kenrose** [comment]
You're right! `getComponentFromProp` returns either a slot or a prop.  Thank you.
