### ISSUE TITLE
FormModel: Submit form by pressing Enter key

### ISSUE THREAD

**Issue by xeno** [vueComponent/ant-design-vue#2670]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Default HTML behavior is to trigger a submit on a form when the Enter key is pressed in any input element, or when pressing a submit button. Ant seems to disable this functionality, causing accessibility issues. Submitting this as a feature request since it would be an update to the codebase to re-enable a feature.

### What does the proposed API look like?
No API

**Comment by sendya** [comment]
```diff
-- <a-form-model :rules="rules" :model="model">
++ <a-form-model :rules="rules" :model="model" @submit="onSubmit">
...
-- <a-button type="primary" @click="onSubmit">
++ <a-button type="primary" html-type="submit">
  Create
</a-button>
```

`html-type="submit"`
