### ISSUE TITLE
使用组件添加prop（object）时，如果传入为new Class而不是object，则会报prop验证不通过警告

### ISSUE THREAD

**Issue by iamllitog** [vueComponent/ant-design-vue#2671]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
所有环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-vcm5m?file=/src/App.vue)

### Steps to reproduce
table中pagination的prop使用class new出来而不使用object则会报prop验证失败

### What is expected?
class new出来的prop不报错

### What is actually happening?
[Vue warn]: Invalid prop: custom validator check failed for prop "pagination".
class new出来的prop类型错误

---
[Vue warn]: Invalid prop: custom validator check failed for prop "pagination".

**Comment by tangjinzhou** [comment]
请使用 object

**Comment by iamllitog** [comment]
个人认为如果从方便开发的角度来说更应该用复用性更高的class应该是情理之中，是这样的验证没有办法来做吗？是Vue自身的问题还是UI框架Prop验证的问题呢？
