### ISSUE TITLE
无法使用antd-scss-theme-plugin支持scss自定义主题

### ISSUE THREAD

**Issue by Spencer17x** [vueComponent/ant-design-vue#2672]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue2.6.11，@vue/cli 4.4.6

### Reproduction link
[https://intoli.com/blog/antd-scss-theme-plugin/](https://intoli.com/blog/antd-scss-theme-plugin/)

### Steps to reproduce
babel.config.js：
plugins: [
[
'import',
{ libraryName: 'ant-design-vue', libraryDirectory: 'es', style: 'css' },
],
],

vue.config.js：
configureWebpack: {
plugins: [
new AntdScssThemePlugin('./src/style/theme.scss'),
],
},

无效

### What is expected?
theme.scss可以自定义主题

### What is actually happening?
无效

**Comment by tangjinzhou** [comment]
不清楚这个插件，你可以去插件issue区反馈

**Comment by BoringDays** [comment]
然而不用这个插件也无法在scss环境下支持自定义主题，官方能否尽快提供一个demo？我看好多人都陆续研究过这个问题但是无果
