### ISSUE TITLE
Ainput pressEnter 事件在模板语法中无法监听 

### ISSUE THREAD

**Issue by yanglu1019** [vueComponent/ant-design-vue#268]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
chrome 70.0.3538.77   vue:2.5.17

### Reproduction link
[https://codepen.io/curryYang/pen/aQZeXE](https://codepen.io/curryYang/pen/aQZeXE)

### Steps to reproduce
vue 模板中v-on:press-enter 会转换为全小写，无法监听pressEnter驼峰式命名事件

### What is expected?
希望把类似事件名改为全小写

### What is actually happening?
希望把类似事件名改为全小写

**Comment by tangjinzhou** [comment]
只有 DOM 模板会有此类问题，单文件模板不会，建议使用单文件模板

**Comment by yanglu1019** [comment]
能否做下兼容处理呢，现在项目中没有使用构建工具，只能用dom模板的开发方式
