### ISSUE TITLE
Upload等很多组件介绍打不开

### ISSUE THREAD

**Issue by Helloworldpp** [vueComponent/ant-design-vue#269]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
Google Chrome

### Reproduction link
[https://tangjinzhou.gitee.io/ant-design-vue/components/upload/](https://tangjinzhou.gitee.io/ant-design-vue/components/upload/)

### Steps to reproduce
官网的upload打不开

### What is expected?
打开

### What is actually happening?
一直加载

**Comment by tangjinzhou** [comment]
如遇国内镜像打不开情况，可以清空缓存强刷页面
或者使用https://vuecomponent.github.io/ant-design-vue
