### ISSUE TITLE
如何设置modal dialog的高度？文档缺失

### ISSUE THREAD

**Issue by shi-yan** [vueComponent/ant-design-vue#2703]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
linux

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
<a-modal :closable="false" v-model="visible" :footer="null" width="80%"  >

文档中提及　bodyStyle	Body style for modal body element. Such as height, padding etc.

https://www.antdv.com/components/modal/

但是这个似乎没用，文档中也无例子

后发现　设置　height="80%" 是可以的，但是文档中丝毫无提及。

### What is expected?
文档中应提供bodyStyle的实用范例。如果height是官方支持的方法，文档中应该提及

### What is actually happening?
文档和实际api不符合

**Comment by xrkffgg** [comment]
Try `80vh`

**Comment by femaimi9527** [comment]
I've try to set the height of  css property for the a-modal like value  in 80% ,and i found that it does't work for me
