### ISSUE TITLE
表单存在v-if 导致无法回显赋值的问题

### ISSUE THREAD

**Issue by HalcyonDaysssss** [vueComponent/ant-design-vue#2706]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
mac

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-forked-ot2lm)

### Steps to reproduce
https://codesandbox.io/s/vue-template-forked-ot2lm

### What is expected?
通过v-if判断的同时能回显datepicker值，如果使用v-show新增表单会导致校验不通过

### What is actually happening?
表单存在v-if 判断导致无法回显

**Comment by zkwolf** [comment]
required 可以绑定form.getFieldValue('shippingDate') === 2啊
