### ISSUE TITLE
carousel autoplay 动态改变轮播失效

### ISSUE THREAD

**Issue by tks-007** [vueComponent/ant-design-vue#2708]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac chrom

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr?file=/src/main.js)

### Steps to reproduce
切换autoplay值轮播失效

### What is expected?
autoplay值改变轮播正常播放

### What is actually happening?
autoplay值改变轮播不正常

---
链接内容为空

**Comment by xrkffgg** [comment]
链接看不了

**Comment by gitspringcould** [comment]
> 链接看不了

后来解决了吗

**Comment by xrkffgg** [comment]
官网的例子我看是正常的

**Comment by gitspringcould** [comment]
> 官网的例子我看是正常的

是的啊，我看着也正常，但是本地就是不对

**Comment by gitspringcould** [comment]
> > 官网的例子我看是正常的
> 
> 是的啊，我看着也正常，但是本地就是不对


人家说拆成两个组件 我还没有试

**Comment by xrkffgg** [comment]
请使用 https://codesandbox.io/s/2wpk21kzvr?file=/src/main.js 提供复现。
