### ISSUE TITLE
owSelections preserved the selections even when pagination changed

### ISSUE THREAD

**Issue by bug4j** [vueComponent/ant-design-vue#2709]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
window 10, antd-v1.4.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-ev3bg?file=/src/App.vue)

### Steps to reproduce
1. select some row;
2. change to another page by click the page num in the pagination tool;

### What is expected?
no rows will select when pagination changed;
btw,do we have api to select row via javascript ? i couldn't find any ones which can do the trick;

### What is actually happening?
while i use rowSelection option to enable row select, first i select some rows, then i change the page num , that's where magic thing happend, i still have some rows selected , the selected row indexes seems to be preserved even table data has changed ,which is not what i want;

---
do we have api to select row via javascript ? i couldn't find any ones which can do the trick;

**Comment by tangjinzhou** [comment]
please give a key
