### ISSUE TITLE
按需引入Carousel组件，没有效果

### ISSUE THREAD

**Issue by shanlh** [vueComponent/ant-design-vue#271]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
macOS Mojave 10.14.1; Chrome 70.0.3538.77; Vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v8j37m6km3)

### Steps to reproduce
https://codesandbox.io/s/v8j37m6km3
如上按需引用Carousel组件

### What is expected?
可以正常render

### What is actually happening?
没有正常render

---
我是在nuxt中按需加载发现的问题，在CodeSandbox中也能复现：

经过问题排查，在/components/carousel/index.jsx中找到：
```
const SlickCarousel = require('../vc-slick/src').default
```
发现赋值SlickCarousel成了undefined，导致不能正常render。
如果 ```import SlickCarousel from '../vc-slick/src'``` 这样写好像可以，但不确定会不会因为import在打包过程中将代码提前，引起注释中提到的[matchMedia not present, legacy browsers require a polyfill](https://github.com/ant-design/ant-design/issues/6560)问题。

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/babel-plugin-import
you can set `libraryDirectory` to `es`.

**Comment by tangjinzhou** [comment]
lib下组件问题将在下个版本修复

**Comment by shanlh** [comment]
好的谢谢！在nuxt中暂时用plugin引入es的carousel解决了

**Comment by tangjinzhou** [comment]
1.1.9已修复

**Comment by shanlh** [comment]
好了，谢谢！
