### ISSUE TITLE
Typescript中怎样调用FormModel的resetFields方法？

### ISSUE THREAD

**Issue by wgf4242** [vueComponent/ant-design-vue#2712]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
win10x64, "vue": "^2.6.11",

### Steps to reproduce
1.不会初始化赋值
2.希望能提示自定义的接口，比如下面的record

```ts
<a-form-model layout="inline" :model="formInline">


import {record} from "@/_models/models";
import {FormModel} from 'ant-design-vue'

formInline: FormModel & recrod = {}}; // 报错
```
怎么做呢？

### What is expected?
。。。

### What is actually happening?
不会初始化赋值
TS2322: Type '{}' is not assignable to type 'FormModel & record'.

**Comment by bruin-suen** [comment]
```js

<a-form-model ref="formModel" layout="inline" :model="formInline">

import { Ref } from 'vue-property-decorator'
import { FormModel } from 'ant-design-vue'

@Ref('formModel') refFormModel !: FormModel

created (): void {
  this.refFormModel.resetFields()
}

```
