### ISSUE TITLE
cmd: git submodule update ,  clone of  git@github.com:tangjinzhou/antdv-demo.git into submodule path '$path/antdv-demo' failed

### ISSUE THREAD

**Issue by sfyr111** [vueComponent/ant-design-vue#2714]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
pwd: ~/ant-design-vue
cmd: git submodule update

### What is expected?
clone of  git@github.com:tangjinzhou/antdv-demo.git into submodule path '$path/antdv-demo' success

### What is actually happening?
clone of  git@github.com:tangjinzhou/antdv-demo.git into submodule path '$path/antdv-demo' failed

**Comment by tangjinzhou** [comment]
antdv-demo is private project
