### ISSUE TITLE
select 使用中文输入法输入时没有清空内容

### ISSUE THREAD

**Issue by jerry000lin** [vueComponent/ant-design-vue#2715]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
any

### Reproduction link
[https://www.antdv.com/components/select-cn/#components-select-demo-select-with-search-field](https://www.antdv.com/components/select-cn/#components-select-demo-select-with-search-field)

### Steps to reproduce
select 在中文输入法输入内容时，没有清空数据，导致重叠显示

![image](https://user-images.githubusercontent.com/37827614/90598935-8bc80e80-e226-11ea-905a-ad07bb952d72.png)

### What is expected?
使用composition api ， 清空与输入框重叠的内容

### What is actually happening?
select 在中文输入法输入内容时，没有清空数据，导致重叠显示
react 版本中没有这个问题，对比发现没有使用 composition api 导致

**Comment by xrkffgg** [comment]
Have fixed in 2.0.
- https://2x.antdv.com/components/select-cn/

**Comment by AmmyXu** [comment]
@xrkffgg 请问，1.7.2版本计划什么时候修复这个问题

**Comment by xrkffgg** [comment]
> @xrkffgg 请问，1.7.2版本计划什么时候修复这个问题

@tangjinzhou
