### ISSUE TITLE
select下拉框value重复时错误显示不一致

### ISSUE THREAD

**Issue by peinkid** [vueComponent/ant-design-vue#2719]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
https://codesandbox.io/s/elegant-kapitsa-4ne39?file=/src/components/HelloWorld2.vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-kapitsa-4ne39?file=/src/components/HelloWorld2.vue)

### Steps to reproduce
先使用arr数据，控制发现重复value,报TypeError: Cannot read property 'key' of undefined
再使用brr数据，控制台不报错
请问这个原理是什么，怎么处理的

### What is expected?
能提供此现象的原理以及统一处理

### What is actually happening?
重复value但现象不一致

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/90618750-fa1aca00-e242-11ea-8c24-e8362a5bc648.png)
brr 也一样报错

**Comment by peinkid** [comment]
你好，key重复的错都会报，但TypeError: Cannot read property 'key' of undefined 这个错误为什么只有arr会报




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 下午5:40
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"破晓兔"<1611851246@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] select下拉框value重复时错误显示不一致 (#2719)





 

 brr 也一样报错
