### ISSUE TITLE
a-table 可伸缩列性能问题

### ISSUE THREAD

**Issue by Godlike-meteor** [vueComponent/ant-design-vue#2723]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
每次拖动可伸缩列按照文档中的例子会重新渲染<th></th>并且没有节流（可以理解为了动画连贯性），数据量增加就会变得非常卡，求问能不能直接支持可伸缩列而不使用 vue-draggable-resizable 这种形式

### What does the proposed API look like?
```
<a-table :drag="true" />
```

**Comment by liuqingchao** [comment]
对啊，要不要这么复杂？

**Comment by eryuanzhige** [comment]
按照官网写法，问题很多，不知道为啥，期待更新，<a-table :drag="true" />

**Comment by eryuanzhige** [comment]
按照官网写法，问题很多，不知道为啥，期待更新
`<a-table :drag="true" />`
