### ISSUE TITLE
动态导入组件，打包时，包变的超级大

### ISSUE THREAD

**Issue by xuejiaomeng** [vueComponent/ant-design-vue#2727]
-  [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

        
        
### Version
1.6.4

### Environment
vue 2.5.17 ,Chrome浏览器, mac

### Reproduction link
[https://webpack.js.org/api/module-methods/#import](https://webpack.js.org/api/module-methods/#import)

### Steps to reproduce
在添加路由前处理，
const componentPath ='/views/dashboard/Workplace'
data['component'] =()=>import(`@${componentPath}`)
组件动态导入成功了，但是打包的时候由原来的3M变成了44M
![image](https://user-images.githubusercontent.com/31272127/90709073-f2ecce00-e2cd-11ea-8327-b9e154b0949e.png)

### What is expected?
打包后还是3M，在路由上能动态加载组件

### What is actually happening?
组件动态导入成功了，但是打包的时候由原来的3M变成了44M

**Comment by sendya** [comment]
这跟组件库没什么关系，是 webpack 对 import 的处理原理导致的，
如果你有了解动态导入的实现原理。应当主动避免直接完全动态路径，而至少指定到特定层级。比如 `@/views/${componentPath}` 这样 webpack 就只会把 `@/views` 目录下的所有文件进行动态打包加载
