### ISSUE TITLE
Modal组件不能通过style调整位置

### ISSUE THREAD

**Issue by qingfengmengge** [vueComponent/ant-design-vue#2732]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10 google

### Reproduction link
[https://www.antdv.com/components/modal/](https://www.antdv.com/components/modal/)

### Steps to reproduce
打开   https://www.antdv.com/components/modal/
查看  Display a modal dialog at 20px to Top的效果

### What is expected?
能调整位置

### What is actually happening?
不能

**Comment by xrkffgg** [comment]
has fixed in https://github.com/vueComponent/ant-design-vue/tree/feat-vue3
