### ISSUE TITLE
全屏查看图片

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#2739]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
是否有全屏查看图片的相关api

### What does the proposed API look like?
就像upload中预览图片的功能，没有发现有单独的方法，最好可以支持滚轮
放大缩小

**Comment by ununian** [comment]
可以用v-viewer

**Comment by wkl007** [comment]
可以跟Ant Design@4.6.0一样，新增一个Image组件

**Comment by date-convert** [comment]
> 这个属于你自己的业务了吧

这个需求我相信百分之八十的项目都会需要，所以希望可以整合到ant design 中

**Comment by xiaofuliang** [comment]
希望有一个，用其它的感觉不好用

**Comment by ChenWeihua123** [comment]
新增一个Image组件还是可以的,用到的地方还是不少的 不过自己封装一个用也简单， ant design 当时没有时候 ，我自己封装了一个React版本的，也能满足需求

**Comment by chsword** [comment]
#3235 
在此 pr 中实现了此功能
