### ISSUE TITLE
日期选择框如何将后台传的值设为自定义日期格式？

### ISSUE THREAD

**Issue by yzwluffy** [vueComponent/ant-design-vue#274]
日期选择框：https://vuecomponent.github.io/ant-design-vue/components/date-picker-cn/#components-date-picker-demo-date-format

**Comment by tangjinzhou** [comment]
这和后台有什么关系

**Comment by yzwluffy** [comment]
后台返回的时间字段，添加到日期选择框里面的默认值里面去（http://pimrtwoc7.bkt.clouddn.com/date-picker.png）

**Comment by tangjinzhou** [comment]
默认值只在第一次有效 更改默认值不会起作用  你可以使用v-model或value

**Comment by yzwluffy** [comment]
看了api里面v-model的用法，报错：http://pimrtwoc7.bkt.clouddn.com/error.png

**Comment by wangxueliang** [comment]
type不对啊，目前api接受moment类型（http://momentjs.com/）
