### ISSUE TITLE
IE11下DatePicker 打开后会从浏览器左上角闪现

### ISSUE THREAD

**Issue by Cpanmac** [vueComponent/ant-design-vue#2744]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
window 10 IE11 vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
使用DatePicker

### What is expected?
IE11环境

### What is actually happening?
IE11下DatePicker 打开后会从浏览器左上角闪现

**Comment by xrkffgg** [comment]
试试这个 https://github.com/ant-design/ant-design/issues/21039

**Comment by db46rt00ors** [comment]
有解决方案吗？我这也遇见这个问题了

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/1833
