### ISSUE TITLE
Modal组件设置百分比的高度

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#2746]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
某种情况下希望Modal占页面高度的90%

### What does the proposed API look like?
1

**Comment by ununian** [comment]
用 vh 不能解决嘛

**Comment by date-convert** [comment]
> 用 vh 不能解决嘛

解决了，谢谢
