### ISSUE TITLE
排序输出的对象为空

### ISSUE THREAD

**Issue by whlong789** [vueComponent/ant-design-vue#2753]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
const columns = [
{
title: "企业名称",
dataIndex: "companyName",
key: "companyName",
sorter: true,
width: "35%",
scopedSlots: {
customRender: "companyName",
},
}
]

handleTable(pagination, sorter) {
this.current = pagination.current;
this.pagination.current = pagination.current;

console.log(sorter);    //输出的对象为空
},

### What does the proposed API look like?
{order: "descend", field: "companyName", columnKey: "companyName"}

**Comment by xrkffgg** [comment]
请使用 https://codesandbox.io/s/vue-antd-template-e22bh 提供复现。

**Comment by whlong789** [comment]
> 请使用 https://codesandbox.io/s/vue-antd-template-e22bh 提供复现。

https://codesandbox.io/s/crazy-kepler-37r15?file=/src/App.vue

**Comment by whlong789** [comment]
> > 请使用 https://codesandbox.io/s/vue-antd-template-e22bh 提供复现。
> 
> https://codesandbox.io/s/crazy-kepler-37r15?file=/src/App.vue

https://37r15.csb.app/

**Comment by xrkffgg** [comment]
https://antdv.com/components/table-cn/#components-table-demo-reset-filters-and-sorters

我看这个例子 有 console.log 输出呀

**Comment by whlong789** [comment]
> https://antdv.com/components/table-cn/#components-table-demo-reset-filters-and-sorters
> 
> 我看这个例子 有 console.log 输出呀
管网是有输出,  但不知道为啥我的输出的对象为空

**Comment by whlong789** [comment]
是否有别的设置,官网没有说清楚
