### ISSUE TITLE
Drawer有多张4M以上图片时，滚动有卡顿

### ISSUE THREAD

**Issue by CLJLewis** [vueComponent/ant-design-vue#2759]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
win10系统、Google Chrome版本 81.0.4044.129、vue2.5.17

### Reproduction link
[https://obvh9.csb.app/](https://obvh9.csb.app/)

### Steps to reproduce
进入页面，点击“open”按钮，右侧出现Drawer，上面有多张4M以上的图片，滚动鼠标，Drawer出现卡顿，不流畅

### What is expected?
在滚动鼠标时，Drawer可以流畅滚动

### What is actually happening?
在滚动鼠标时，Drawer不可以流畅滚动

**Comment by xrkffgg** [comment]
加个
```css
.ant-drawer-body { 
    position: absolute;
}
```

**Comment by CLJLewis** [comment]
> 加个
> 
> ```css
> 。ant-drawer-body { 
>      位置：绝对；
> }
> ```

好的 谢谢 已修复

**Comment by CLJLewis** [comment]
> ```css
> drawer
> ```

请问这是什么原理？ 以后版本是否会修复，这样我们以后就不用修改这样式，相信会有很多开发遇到这问题

**Comment by xrkffgg** [comment]
有新的支持 vue3 版本的已经发布了哦，可以多关注关注。
