### ISSUE TITLE
Tabs 有多组时，设置activeKey 无法去掉tabs的title下面的下划线

### ISSUE THREAD

**Issue by shushi1010** [vueComponent/ant-design-vue#276]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
macOS Mojave, Chrome70.0.3538.102,Vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vm3pw8yp2y)

### Steps to reproduce
同一个Vue组件里放多个tabs组件，设置activeKey切换tab，另一个tab组件标题下的下划线无法隐藏

### What is expected?
通过设置activeKey切换tab，tab标题下的下划线应该同步，即激活的tab标题下显示下划线

### What is actually happening?
多个tabs组件同步切换问题

**Comment by tangjinzhou** [comment]
这和组件同步没关系，为何会设置一个不存在的key的需求(activeKey = 'null')？

**Comment by shushi1010** [comment]
您看下腾讯云首页，https://cloud.tencent.com/  我想利用tabs实现“了解我们的云产品”这部分

**Comment by shushi1010** [comment]
> 这和组件同步没关系，为何会设置一个不存在的key的需求(activeKey = 'null')？

您看下腾讯云首页，https://cloud.tencent.com/ 我想利用tabs实现“了解我们的云产品”这部分

**Comment by tangjinzhou** [comment]
你这个是业务的问题
建议你使用一个tab  + 自定义tab下的内容
