### ISSUE TITLE
table组件数据含有children的情况

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#2762]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格分级展示数据

### What does the proposed API look like?
我发现当table组件data-source数据含有children属性是也会存在expend的情况 但是没有找到关于这个属性的更多详情介绍；比如当children：[] 数组长度为0也会出现可展开的加号图标、或者 想要默认展开。如何解决这个问题

**Comment by Y450150** [comment]
delete children，默认展开官网配置项里面有，但是会发生点击+号或者-号都无法展开、或者收起的操作，这是个BUG

**Comment by Y450150** [comment]
expandedRowKeys这个属性是控制展开行状态的

**Comment by date-convert** [comment]
> expandedRowKeys这个属性是控制展开行状态的

我想要实现children：[]数组长度为0时没有图标 并且把加减号改为箭头图标，请问有实现方法吗
