### ISSUE TITLE
请问 2.0 之后的版本是不是不支持 v-decorator 指令来处理表单了？

### ISSUE THREAD

**Issue by ffx0s** [vueComponent/ant-design-vue#2770]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
想把项目升级到 2.0，但是由于项目中有很多表单是用 v-decorator 处理的，看了下官网没有找到相关的文档说明。

### What does the proposed API look like?
"vue": "^3.0.0-0",
"ant-design-vue": "^2.0.0-beta.3",

**Comment by sendya** [comment]
请参考 https://2x.antdv.com/docs/vue/migration-v2-cn/

**Comment by ffx0s** [comment]
@sendya 好的，谢谢
