### ISSUE TITLE
Cannot show tooltip for column of a table when has ellipsis

### ISSUE THREAD

**Issue by Kimi1020** [vueComponent/ant-design-vue#2775]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10, chrome, 1.6.5

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
set ellipsis to true to show the part of the column name, but no tooltip for column name

### What is expected?
Show tooltip like cell when has ellipsis

### What is actually happening?
No tooltip for part column name when has ellipsis

**Comment by tianyu94** [comment]
Me too, version: 1.6.2

**Comment by pinkhide27** [comment]
Me 2, version: 1.6.5
