### ISSUE TITLE
table树形数据支持动态加载么

### ISSUE THREAD

**Issue by wou101771** [vueComponent/ant-design-vue#2778]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
这个功能可以加载大量数据

### What does the proposed API look like?
load(tree, treeNode, resolve) {
setTimeout(() => {
resolve([
{
id: 31,
date: '2016-05-01',
name: '王小虎',
address: '上海市普陀区金沙江路 1519 弄'
}, {
id: 32,
date: '2016-05-01',
name: '王小虎',
address: '上海市普陀区金沙江路 1519 弄'
}
])
}, 1000)
}

**Comment by tangjinzhou** [comment]
支持
