### ISSUE TITLE
Notification通知提示框关闭时会触发onClick事件

### ISSUE THREAD

**Issue by CfortWang** [vueComponent/ant-design-vue#2779]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
64位win7, chrome[ 85.0.4183.83（正式版本） （64 位）]， vue[6.7.0]

### Reproduction link
[https://www.antdv.com/components/notification-cn/](https://www.antdv.com/components/notification-cn/)

### Steps to reproduce
this.$message.open({
    message: '新消息',
    description: '测试消息提醒',
    icon: <a-icon type="sound"/>,
    class: 'notice',
    key: '111',
    onClick: () => {
        console.log(123)
    },
    onClose: e => {
        console.log(e)
        // e.stopPropagation()
    }
})
点击关闭按钮控制台同时打印undefined和123

### What is expected?
阻止Notification通知提示框onClose事件的冒泡

### What is actually happening?
在点击关闭图标时，同时触发了onClick和onClose事件（旧版本无法自定义关闭图标，所以只能使用内置事件）

**Comment by tangjinzhou** [comment]
升到 1.6.5 呗
