### ISSUE TITLE
grid with navbar

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [vueComponent/ant-design-vue#278]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
elementary os, firefox 63.0.3, vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24002q42vn)

### Steps to reproduce
to reproduce this: just put 2 or 3... `a-menu-item` between `a-col`

### What is expected?
having Home, About, Contact menu items on the left of the Navbar,
and having the avatar item on the right of the navbar
and all of them in a same horizontal line using flex

### What is actually happening?
we have Home, about, contact menu items on a same column
avatar item is not on the right

---
if we inspect elements we can see that the class of menu items become undefined :
`<li role="menuitem" class="undefined-item"><a href="/" rel="noopener noreferrer">Home</a></li>`

**Comment by tangjinzhou** [comment]
The subcomponent of the menu must be a menuItem. You cannot insert col or other components between them.
