### ISSUE TITLE
按需加载组件，在开发版本下能够正常显示，但是编译后的生产版本有异常

### ISSUE THREAD

**Issue by macycle** [vueComponent/ant-design-vue#2781]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Vue version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-9i1i4?file=/src/App.vue)

### Steps to reproduce
在development里面，样式能够如预期一样显示，但是production模式下，样式会闪烁。

### What is expected?
在生产模式下，样式也能够显示正常

### What is actually happening?
在development里面，样式能够如预期一样显示，但是production模式下，样式会闪烁。

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/babel-plugin-import/issues/423

**Comment by macycle** [comment]
> ref [ant-design/babel-plugin-import#423](https://github.com/ant-design/babel-plugin-import/issues/423)
您好，有这样设置了，在本地预览的时候是正常的，现在问题解决了，是webpack的问题。

**Comment by xiaofuliang** [comment]
@macycle 请问如何解决的
