### ISSUE TITLE
建议提供全局配置关闭无障碍特性

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue#2782]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在自动化快照测试中，由于页面的aria-control标签的值是变化，导致快照测试失败

### What does the proposed API look like?
提供全局配置，关闭这个特性

**Comment by tangjinzhou** [comment]
设置环境变量即可  process.env.NODE_ENV = 'test'
