### ISSUE TITLE
tabs的tab设置过渡动画、内容取消动画，tab下面的滑动线会没有过渡效果

### ISSUE THREAD

**Issue by Y450150** [vueComponent/ant-design-vue#2785]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
无

### Reproduction link
[https://www.antdv.com/components/tabs-cn/#API](https://www.antdv.com/components/tabs-cn/#API)

### Steps to reproduce
<a-tabs :animated="{inkBar:true, tabPane:false}"> 设置这个属性
[a,aaa,b,bbbbb], 如这四个tab栏，切换到aaa时，由短直接变长，无动画

### What is expected?
增加tab标签下面的滑动条过渡动画效果

### What is actually happening?
目前设置animated="{inkBar:true, tabPane:false}这个属性后，tab下面滑动条在标签内容长度不一致情况下，会出现无动画下过，即由短直接变长、由长直接变短

**Comment by tangjinzhou** [comment]
无法复现  请提供可运行的复现demo

**Comment by Y450150** [comment]
> 无法复现 请提供可运行的复现demo

是因为浏览器性能原因，多谢回复
