### ISSUE TITLE
无法找到最新的离线版官网文档，可以提供antdv官方文档的离线版吗？

### ISSUE THREAD

**Issue by zhuolyang** [vueComponent/ant-design-vue#2786]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
很多时候要做内网开发，无法访问antdv官网，能否提供官网文档的离线版？非常感谢

### What does the proposed API look like?
很多时候要做内网开发，无法访问antdv官网，能否提供官网文档的离线版？非常感谢

**Comment by tangjinzhou** [comment]
很抱歉，暂时不再提供离线文档，
近期我们会针对企业客户提供离线文档功能，敬请期待
