### ISSUE TITLE
希望新增color-picker组件

### ISSUE THREAD

**Issue by ZhengXiaowei** [vueComponent/ant-design-vue#2787]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
新增组件color-picker，我看issue，是已经处在合并阶段了吗？近期是否会增加？

### What does the proposed API look like?
新组件

**Comment by Alpha0723** [comment]
同样需要这个组件，源码里面这个组件的代码已经在components里面了，但是没有在index里面import和export出来。同样期待这个组件。

**Comment by dcdlove** [comment]
支持

**Comment by sky124380729** [comment]
希望新增

**Comment by yiwo18** [comment]
两年了还没加入。源码里面却有color-picker代码，用不了

**Comment by dcdlove** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by CCherry07** [comment]
#https://github.com/vueComponent/ant-design-vue/pull/6722
