### ISSUE TITLE
组件的空参数不一致

### ISSUE THREAD

**Issue by axetroy** [vueComponent/ant-design-vue#2789]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
xxx

### Reproduction link
[https://example.com](https://example.com)

### Steps to reproduce

一些组件的空参数不一致，很容易导致混乱，例如 table 的 pagination 要传 `false` 才不显示翻页

但是 modal 的 `footer` 要传入 `null` 才不现实底部按钮

这着实是迷幻操作

### What is expected?
xxx

### What is actually happening?
xxx

**Comment by Gitpingping** [comment]
select的option如果为空，会即显示placeholder又显示为空的选项

**Comment by tansentcn** [comment]
神奇的是时间类选择的空是null，输入框、选择框需要用undefined

**Comment by axetroy** [comment]
UP. remove stale
