### ISSUE TITLE
Modal的okButtonProps和cancelButtonProps，类型定义和文档有点问题

### ISSUE THREAD

**Issue by TioJS** [vueComponent/ant-design-vue#2790]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
windows10@1909,chrome@81.0.4044.122,vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-water-fnwgp?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/ancient-water-fnwgp?file=/src/App.vue

### What is expected?
见复现注释

### What is actually happening?
文档上$confirm的okButtonProps和cancelButtonProps的类型是ButtonProps，实际使用时要传{props: ButtonProps, on: {}}才有效果
而且TypeScript下的类型提示也有问题，提示为
Type '{ props: { loading: true; }; }' is not assignable to type 'Button'.
Object literal may only specify known properties, but 'props' does not exist in type 'Button'. Did you mean to write '$props'?Vetur(2322)

**Comment by tangjinzhou** [comment]
来个 pr ？

**Comment by Aspark1996** [comment]
附议。确实有这个问题
