### ISSUE TITLE
Tabs标签页下加input输入完成后tab页消失

### ISSUE THREAD

**Issue by lubaijie** [vueComponent/ant-design-vue#2792]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
     

### Environment
vue3.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
<template>
<div>
<a-tabs @change="callback">
<a-tab-pane key="1" tab="Tab 1">
<a-input v-model:value="value" />
</a-tab-pane>
<a-tab-pane key="2" tab="Tab 2" force-render>
Content of Tab Pane 2
</a-tab-pane>
<a-tab-pane key="3" tab="Tab 3">
Content of Tab Pane 3
</a-tab-pane>
</a-tabs>
</div>
</template>
<script>
export default {
data() {
return {
value: ''
};
},
methods: {
callback(key) {
console.log(key);
},
},
};
</script>

当input输入完成，失去焦点后，tab页面消失

**Comment by tangjinzhou** [comment]
请提供复现链接
