### ISSUE TITLE
table在rowSelection fixed与row expand同时使用时， layout不对

### ISSUE THREAD

**Issue by haiboyan** [vueComponent/ant-design-vue#2795]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
win10, chrome 84

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-table-expico-forked-bbhpz?file=/src/components/HelloWorld.vue)

### Steps to reproduce
运行以下代码， 然后展开任意一列
<template>
<a-table :columns="columns" :data-source="data" :rowSelection="rowSelection">
<a slot="action" slot-scope="text" href="javascript:;">Delete</a>
<p slot="expandedRowRender" slot-scope="record" style="margin: 0">
{{ record.description }}
</p>
</a-table>
</template>
<script>
const columns = [
{ title: 'Name', dataIndex: 'name', key: 'name' },
{ title: 'Age', dataIndex: 'age', key: 'age' },
{ title: 'Address', dataIndex: 'address', key: 'address' },
{ title: 'Action', dataIndex: '', key: 'x', scopedSlots: { customRender: 'action' } },
];

const data = [
{
key: 1,
name: 'John Brown',
age: 32,
address: 'New York No. 1 Lake Park',
description: 'My name is John Brown, I am 32 years old, living in New York No. 1 Lake Park.',
},
{
key: 2,
name: 'Jim Green',
age: 42,
address: 'London No. 1 Lake Park',
description: 'My name is Jim Green, I am 42 years old, living in London No. 1 Lake Park.',
},
{
key: 3,
name: 'Joe Black',
age: 32,
address: 'Sidney No. 1 Lake Park',
description: 'My name is Joe Black, I am 32 years old, living in Sidney No. 1 Lake Park.',
},
];

export default {
data() {
return {
data,
columns,
rowSelection:{fixed:true,selectedRowKeys:[],type:'checkbox'}
};
},
};
</script>

### What is expected?
两者可以联合正常使用

### What is actually happening?
layout错乱， 在table fixed area也渲染了expandedRowRender slot的内容

**Comment by tangjinzhou** [comment]
fixed 和 expand 不能一起使用
