### ISSUE TITLE
定制主题，想配置全局字体为12，但是webpack中配置font-size-base无效

### ISSUE THREAD

**Issue by tanxuewei** [vueComponent/ant-design-vue#2796]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
mac, vue2,webpack4.x

### Reproduction link
[https://www.antdv.com/docs/vue/customize-theme-cn](https://www.antdv.com/docs/vue/customize-theme-cn)

### Steps to reproduce
1、配置webpack
module: {
rules: [
{
test: /\.(le|c)ss$/,
use: [
isProd ? MiniCssExtractPlugin.loader : 'style-loader',
'css-loader',
{
loader: 'less-loader',
options: {
lessOptions: {
modifyVars: {
'primary-color': '#1DA57A',
'font-size-base': '12px',
},
javascriptEnabled: true,
}
}
}
]
}
]
2、.babelrc
["import", { "libraryName": "ant-design-vue", "style": true }],

### What is expected?
全局字体为12px

### What is actually happening?
全局字体依然是14px

**Comment by sendya** [comment]
请提供你如何使用 antd 的引入代码

**Comment by tanxuewei** [comment]
> 请提供你如何使用 antd 的引入代码

import {
  Table,
  Select,
  Form,
  Card,
  DatePicker,
  LocaleProvider,
  Input,
  Upload,
  Button,
  Icon,
  InputNumber,
  Modal,
  Menu,
  Tag,
  Row,
  Col,
  Layout,
  Dropdown,
  Tooltip,
  Steps,
  Spin,
  Breadcrumb,
  Divider,
  List,
  Tabs,
  Message,
  Radio,
  Checkbox,
  Popconfirm,
  Alert,
  Switch,
  Popover
} from 'ant-design-vue';

Vue.use(Table)
Vue.use(Select)
Vue.use(Form)
Vue.use(Card)
Vue.use(DatePicker)
Vue.use(LocaleProvider)
Vue.use(Input)
Vue.use(Upload)
Vue.use(Button)
Vue.use(Icon)
Vue.use(InputNumber)
Vue.use(Modal)
Vue.use(Menu)
Vue.use(Tag)
Vue.use(Row)
Vue.use(Col)
Vue.use(Layout)
Vue.use(Dropdown)
Vue.use(Tooltip)
Vue.use(Steps)
Vue.use(Spin)
Vue.use(Breadcrumb)
Vue.use(Divider)
Vue.use(List)
Vue.use(Tabs)
Vue.use(Message)
Vue.use(Radio)
Vue.use(Checkbox)
Vue.use(Popconfirm)
Vue.use(Alert)
Vue.use(Switch)
Vue.use(Popover)
