### ISSUE TITLE
请问antdv的文档示例代码有放在github上吗？是否是antdv-demo @ b890776这个文件夹，打开时404呢

### ISSUE THREAD

**Issue by cyt68** [vueComponent/ant-design-vue#2800]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
请问antdv的文档示例代码有放在github上吗？是否是antdv-demo @ b890776这个文件夹，打开时404呢

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
请问antdv的文档示例代码有放在github上吗？是否是antdv-demo @ b890776这个文件夹，打开时404呢

### What is expected?
文档示例工程下载到本地运行

### What is actually happening?
请问antdv的文档示例代码有放在github上吗？是否是antdv-demo @ b890776这个文件夹，打开时404呢

**Comment by tangjinzhou** [comment]
这是私有仓库  不对外开放

**Comment by cyt68** [comment]
> 这是私有仓库 不对外开放

行吧，好多组件库示例代码也是开放的勒

**Comment by bluemiaomiao** [comment]
Build CHM docs file please!
