### ISSUE TITLE
动态创建的mapPropsToFields返回对象更新时不会生效

### ISSUE THREAD

**Issue by jiabinbin** [vueComponent/ant-design-vue#2802]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
mac Os catalina 10.15.4/ chrome 84.0.4147.125 (正式版本) （64 位）/  vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-quwok?file=/src/App.vue)

### Steps to reproduce
参见 重现链接 ChildForm 组件created生命周期中

### What is expected?
Form表单的值随父级改变而改变，跟react版本效果一致：(链接为对标想用antdv实现的功能的react版实现)
https://codesandbox.io/s/focused-sky-xkl7h?file=/index.js

### What is actually happening?
每回修改值之后，form值不会更新

---
Form表单共用时，比如新增和修改是同一个Form组件时

**Comment by sendya** [comment]
https://codesandbox.io/s/vue-antd-template-forked-2h8z9

**Comment by jiabinbin** [comment]
emmm 是我搞错了api~:(
