### ISSUE TITLE
How to automatically import corresponding component styles when importing components locally in vite?

### ISSUE THREAD

**Issue by guangzan** [vueComponent/ant-design-vue#2803]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
win chrome vue all the latest version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr?file=/src/main.js)

### Steps to reproduce
question

### What is expected?
Ability to import styles automatically in vite .

### What is actually happening?
Cant't  import styles automatically in vite .

**Comment by shunichio** [comment]
同问。

**Comment by BoBoooooo** [comment]
同问。

**Comment by zch233** [comment]
同问。

**Comment by hezechang** [comment]
同问，能不能解决啊
