### ISSUE TITLE
请问antdv2.x，也就是支持vue3的官方文档，将在大概什么时候完善

### ISSUE THREAD

**Issue by H-Sven** [vueComponent/ant-design-vue#2806]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在官网文档在一些组件上，还是vue2的语法，会在何时使用vue3示例

### What does the proposed API look like?
现在官网文档在一些组件上，还是vue2的语法，会在何时使用vue3示例

**Comment by tangjinzhou** [comment]
https://v3.vuejs.org/
