### ISSUE TITLE
steps组件设置 labelPlacement="vertical" 不生效

### ISSUE THREAD

**Issue by Tommychou** [vueComponent/ant-design-vue#281]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
mac 10.12.5 chrome 0.0.3538.102 vue 2.5.13

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4jrw852750)

### Steps to reproduce
不生效

### What is expected?
生效

### What is actually happening?
不生效

**Comment by tangjinzhou** [comment]
下个版本修复
临时解决方案：添加class="ant-steps-label-vertical"

`<a-steps labelPlacement="vertical" class="ant-steps-label-vertical">...</a-steps>`

**Comment by tangjinzhou** [comment]
1.1.10已修复
