### ISSUE TITLE
异步 a-tree , checkedKeys 没有及时更新

### ISSUE THREAD

**Issue by stackcc** [vueComponent/ant-design-vue#2815]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
父子关联的异步 a-tree , 如果父级选中，子集会默认全部选中，但是 checkedKeys 没有及时更新
在选中地址联动过程中，直接选择省，希望能在加载 市列表的时候 checkedKeys  及时更新， 或者提供一个 手动触发 onCheck 的方法

### What does the proposed API look like?
```
<a-tree  v-model="skuEditAddress" checkable :tree-data="list" :load-data="loadAddressDataById" @check="checkAddress"/>
<script>
// 选中区域 -- 保存 选中   半选中 ids
checkAddress(checkedKeys, e) {
const self = this
this.checkAddressTotal = [...checkedKeys, ...e.halfCheckedKeys]
// 异步请求下级地址  v-model=skuEditAddress
// 希望请求结束后自动更新
this.loadAddressDataById(e.node)
}
</script>
```

**Comment by tangjinzhou** [comment]
请提供完整的 复现 demo
