### ISSUE TITLE
Table同时使用sorter和rowSelection循环报错

### ISSUE THREAD

**Issue by OBQun** [vueComponent/ant-design-vue#2821]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue3.0.0-rc.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-night-nyo2l)

### Steps to reproduce
``` html
<a-table :row-selection="rowSelection" >
<a-table-column :sorter="(a,b)=>a-b"/>
</a-table>
```

### What is expected?
选中状态 && 排序

### What is actually happening?
控制台循环报错 浏览器卡死
```log
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
```

**Comment by EakerZT** [comment]
我单独用 row-selection 都不行

**Comment by tangjinzhou** [comment]
row-selection 是个对象

**Comment by EakerZT** [comment]
是真的有问题
我这边环境是 vue3 ts antdv2beta6
模板里面是这样
          <a-table
            :rowKey="tableUser.key"
            :loading="tableUser.loading"
            :dataSource="tableUser.data"
            :columns="tableUser.columns"
            :row-selection="tableUser.rowSelection"
          />
定义是这样
    const tableUser = reactive({
      loading: false,
      key: 'userCode',
      data: [],
      columns: [
        {
          dataIndex: 'userCode',
          title: '工号'
        },
        {
          dataIndex: 'nickname',
          title: '名称'
        },
        {
          dataIndex: 'username',
          title: '账号'
        }
      ],
      rowSelection: {
        selectedRowKeys: [],
        onChange (e: any) {
          console.log(e)
        }
      }
    })
不加:row-selection="tableUser.rowSelection"没问题 一加就出问题vue报错
 [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

**Comment by OBQun** [comment]
> row-selection 是个对象

@tangjinzhou 抱歉，我在sandBox里写错了。但在项目中是正确配置的row-selection，也设置了column.key以及row-key，这个问题依然存在， 可以麻烦你确认一下吗

**Comment by ChenWeihua123** [comment]
同样的问题 只要设置了 rowSelection 就会出现几百个 Vue warn 请问大佬如何解决的

**Comment by ChenWeihua123** [comment]
@OBQun 我升级 vue@3.0.0 ant@2.0.0.beta10 问题解决了
