### ISSUE TITLE
radio无法识别值

### ISSUE THREAD

**Issue by Duzx5517** [vueComponent/ant-design-vue#2823]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome win10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-7x9zh)

### Steps to reproduce
</div>
<div :style="{ marginTop: '16px' }">
<a-radio-group :defaultValue="ravalue" buttonStyle="solid">
<a-radio-button value="1">Hangzhou</a-radio-button>
<a-radio-button value="2" disabled>Shanghai</a-radio-button>
<a-radio-button value="3">Beijing</a-radio-button>
<a-radio-button value="4">Chengdu</a-radio-button>
</a-radio-group>
</div>

data() {
return {
ravalue: 1
};
},

### What is expected?
当data的值为数字是，radio 无法识别

### What is actually happening?
只有将数字转为字符串，radio才可以识别

**Comment by xrkffgg** [comment]
```
:value="1" // 数字

value="1"  // 字符串
```

**Comment by Duzx5517** [comment]
谢谢
