### ISSUE TITLE
closable option is inavailable when i use modal with instruction way

### ISSUE THREAD

**Issue by enhezzz** [vueComponent/ant-design-vue#2824]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
win10,chrome 79.0.3945.117, vue^2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-sky-kzd65?file=/src/components/HelloWorld.vue:200-208)

### Steps to reproduce
In reproduction repo, click a link with 'popModal' text

### What is expected?
close (x) button on top right of modal dialog

### What is actually happening?
dont show

**Comment by enhezzz** [comment]
ok,i find some differences betweencomponent style and instruction style,  for example : modal header lose a dividor line...
I hope have a consistent style

**Comment by tangjinzhou** [comment]
you can custom css to override antdv.css.
```css
.ant-modal-confirm .ant-modal-close {
   display: block;
}
```

**Comment by disovi** [comment]
@tangjinzhou than there is a conflict with the documentation, in documentation of modal option closable is available https://antdv.com/components/modal/#Modal.method()
