### ISSUE TITLE
need support use radio component in tree slot

### ISSUE THREAD

**Issue by Alexaa123** [vueComponent/ant-design-vue#2828]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue version: vue3, antdesign-version: 2.0.0-beta.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-hs823?file=/src/components/HelloWorld.vue)

### Steps to reproduce
```
<a-tree
:show-line="true"
:tree-data="state.coreTreeConfigData"
>
<template v-slot:radio="{title, value}">
<span @click="changeValue(title, value)">{{title}}</span>
<a-button type="primary" @click="changeValue(title, value)">增加</a-button>
<a-radio-group class="ml-3" @change="changeValue(title, value)">
<a-radio :value="true">开启</a-radio>
<a-radio :value="false">关闭</a-radio>
</a-radio-group>
</template>
</a-tree>
```
i can not click radio and change the radio status. it seems like that the click cannot accepted by radio

### What is expected?
when i click the radio in the tree slot , the status of radio should change ,but it not change
and i also test the checkbox in the tree slot , i found it cannot change too
### What is actually happening?
i cannot change the radio status in  tree component slots

---
hope can solve this problem quickly

**Comment by tangjinzhou** [comment]
If you want to solve the problem quickly, you should provide effective recurring examples
