### ISSUE TITLE
选择器隐藏下拉框时，不能按回车键添加

### ISSUE THREAD

**Issue by CLJLewis** [vueComponent/ant-design-vue#2830]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
系统： win10，谷歌浏览器，vue:   2.15.17

### Reproduction link
[https://hrugo.csb.app/](https://hrugo.csb.app/)

### Steps to reproduce
选择器有标签展示，因为需求不需要下拉框，所以设置:open='false'，输入文本后，按 回车键 应该能正常添加， 现在设置后，不能正常添加

### What is expected?
无下拉框， 按 回车键 能正常添加文本

### What is actually happening?
在无下拉框情况下， 按 回车键 不能添加文本

**Comment by tangjinzhou** [comment]
你这种需求 建议通过css 隐藏弹窗 而不是通过 open false
