### ISSUE TITLE
select组件设置了dropdownMatchSelectWidth为false，但是选择完选项后，dropdown menu依旧会变得跟下拉同宽

### ISSUE THREAD

**Issue by yiptsangkin** [vueComponent/ant-design-vue#2833]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
mac chrome vue2.6.11 vue-cli3

### Reproduction link
[https://antdv.com/components/select-cn/](https://antdv.com/components/select-cn/)

### Steps to reproduce
select组件设置了dropdownMatchSelectWidth为false，但是选择完选项后，dropdown menu依旧会变得跟下拉同宽，查看了下，dropdown menu的style从min-width变成了width，是这个导致的。

### What is expected?
依旧不一样宽。

### What is actually happening?
变成了同宽

**Comment by yiptsangkin** [comment]
换了另外一种实现方式

**Comment by niceue** [comment]
v2.1.4 也出现此问题

**Comment by chenjiaj** [comment]
> 换了另外一种实现方式

请问另外一种实现方式是什么呀，怎么实现的呢

**Comment by yiptsangkin** [comment]
> > 换了另外一种实现方式
> 
> 请问另外一种实现方式是什么呀，怎么实现的呢

参考下我的开源项目里面的NMultiSelect组件
https://github.com/yiptsangkin/near-admin-vue/tree/master/src/core/component

**Comment by chenjiaj** [comment]
> > > 换了另外一种实现方式
> > 
> > 
> > 请问另外一种实现方式是什么呀，怎么实现的呢
> 
> 参考下我的开源项目里面的NMultiSelect组件
> https://github.com/yiptsangkin/near-admin-vue/tree/master/src/core/component
好的 谢谢
