### ISSUE TITLE
nuxt现在可支持2.0版本吗

### ISSUE THREAD

**Issue by itsxt** [vueComponent/ant-design-vue#2836]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
项目刚立项开发，使用的是nuxt2.14 antdv1.6.2。现在能否升级至2.0版本呢

### What does the proposed API look like?
nuxt

**Comment by sendya** [comment]
你要看 nuxt 是否支持 vue3

**Comment by itsxt** [comment]
> 你要看 nuxt 是否支持 vue3
