### ISSUE TITLE
upload组件的method属性失效

### ISSUE THREAD

**Issue by Y450150** [vueComponent/ant-design-vue#2837]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
https://codesandbox.io/s/quirky-sky-6v4n1?file=/src/App.vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-sky-6v4n1?file=/src/App.vue)

### Steps to reproduce
点击上传就行，任意改method的请求类型，都是不生效，一直是post

### What is expected?
method属性能生效，能正常修改请求的类型

### What is actually happening?
upload组件method改变请求类型的功能失效

**Comment by ybqboy** [comment]
这问题解决了吗？1.7.2上仍然可以重现
