### ISSUE TITLE
树型选择控件 treeDefaultExpandedKeys问题

### ISSUE THREAD

**Issue by Tommychou** [vueComponent/ant-design-vue#284]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.8

### Environment
mac 10.12.5 chrome 0.0.3538.102 vue 2.5.13

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1rrvm9o347)

### Steps to reproduce
链接里有

### What is expected?
异步数据根目录默认展开

### What is actually happening?
没有展开 报错

**Comment by tangjinzhou** [comment]
#275

**Comment by tangjinzhou** [comment]
1.1.10已修复
