### ISSUE TITLE
vue程序执行npm run build报错

### ISSUE THREAD

**Issue by victor2016** [vueComponent/ant-design-vue#2842]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
执行npm run build的时候，报了一个ant design的错误

### What does the proposed API look like?
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|       return {
|         emptyText: (
>           <Empty style="{height:250px;}" image={Empty.PRESENTED_IMAGE_SIMPLE}>
|             <span slot="description">暂无数据</span>
|           </Empty>

**Comment by tangjinzhou** [comment]
？
