### ISSUE TITLE
can we add loading icon for auocomplate with search icon input

### ISSUE THREAD

**Issue by Kimi1020** [vueComponent/ant-design-vue#2843]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
win10, chrome, 1.6.5

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn/](https://www.antdv.com/components/auto-complete-cn/)

### Steps to reproduce
1. 使用使用autocomplete 组件并且带查询icon的那个input
2. 加了防抖，每停止输入1500ms触发一个ajax call去后台搜索查询 可能的结果
3. 在查询的时候，如果速度慢的话，是否可以把input的search icon变成loading icon

### What is expected?
使用autocomplete 组件并且带查询icon的那个input， 是不是可以加一个ajax后台查询的时候，提供一个借口 比如loading，右边的icon就从search变成了loading icon

### What is actually happening?
查询的时候如果卡顿了，就会出现假死， 好久以后才弹出

**Comment by tangjinzhou** [comment]
你可以参考这个示例自定义输入框和图标   https://www.antdv.com/components/auto-complete-cn/#components-auto-complete-demo-lookup-patterns---uncertain-category

![image](https://user-images.githubusercontent.com/6937879/93975470-14981400-fdaa-11ea-9100-b5a32c92ee04.png)
