### ISSUE TITLE
树形数据Table children数组长度为0 也会添加展开按钮

### ISSUE THREAD

**Issue by Devifish** [vueComponent/ant-design-vue#2847]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.8

### Environment
浏览器：Edge 85     Vue: 3.0-RC10

### Reproduction link
https://cloud.devifish.cn/system/menu (admin/123456)

### Steps to reproduce
树形数据Table children数组长度为0 也会添加展开按钮

### What is expected?
children数组长度为0 不添加展开按钮

### What is actually happening?
children数组长度为0 会添加展开按钮

**Comment by tangjinzhou** [comment]
你可以自行判断children长度，来控制是否显示，组件内部不做处理，主要原因是，有一些需求是点击展开的时候，异步请求数据来添加children

**Comment by Devifish** [comment]
> 你可以自行判断children长度，来控制是否显示，组件内部不做处理，主要原因是，有一些需求是点击展开的时候，异步请求数据来添加children

并没有相关的API能够控制   是否显示展开图片， 只能通过递归数据delete children实现

**Comment by ycc3000** [comment]
UP
请问在哪里可以插入判断？

**Comment by Devifish** [comment]
> UP
> 
> 请问在哪里可以插入判断？

没有相关api, 内部是判断数据的children字段实现   你可以递归数据delete该字段
