### ISSUE TITLE
how to static modal

### ISSUE THREAD

**Issue by vciloglu** [vueComponent/ant-design-vue#2848]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
In some cases it is much more advantageous to be fixed where it is located in modal html codes. for example, in a fullscreen map property, the modal cannot be displayed because it is rendered outside. However, bootstrap adds static property to modal properties to eliminate this situation. It would be really cool to add this feature

### What does the proposed API look like?
https://bootstrap-vue.org/docs/components/modal (read inside properties "static")

**Comment by tangjinzhou** [comment]
you can use `forceRender` and `getContainer ` like:
```html
<a-modal forceRender :getContainer="trigger => trigger.parentNode">
```
