### ISSUE TITLE
关于table的合计功能

### ISSUE THREAD

**Issue by 975914892** [vueComponent/ant-design-vue#2850]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
table的合计功能有没有什么好的方案，自己试了下在footer里添加表格，会多出来一层边框，并且有横向滚动条的话两个table并不能联动；还试了每页最后一行push一条合计数据，但这两种情况有复选框的话都挺尴尬的。antd能后续添加一个属性来开关合计功能最好~~

### What does the proposed API look like?
win10，谷歌最新，火狐最新，antd1.6.5，antd pro 3.0

**Comment by leslieeilsel** [comment]
table 组件也许有更好的选择。https://github.com/x-extends/vxe-table

**Comment by 975914892** [comment]
> table组件也许有更好的选择[。https://github.com/x-extends/vxe-table](https://github.com/x-extends/vxe-table)

这个着实是有点牛批
