### ISSUE TITLE
2.0.0-beta.9全局引入出错

### ISSUE THREAD

**Issue by liminga** [vueComponent/ant-design-vue#2859]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue2.0

### Reproduction link
[https://github.com/liminga/antd2-test](https://github.com/liminga/antd2-test)

### Steps to reproduce
2. 创建一个项目 #
使用命令行进行初始化。

$ vue create antd-demo
并配置项目。

若安装缓慢报错，可尝试用 cnpm 或别的镜像源自行安装：rm -rf node_modules && cnpm install。

3. 使用组件 #
$ npm i --save ant-design-vue@next
完整引入

import { createApp } from 'vue';
import Antd from 'ant-design-vue';
import App from './App';
import 'ant-design-vue/dist/antd.css';

const app = createApp();
app.config.productionTip = false;

app.use(Antd);

### What is expected?
能正常使用

### What is actually happening?
报错了main.js?56d7:12 Uncaught TypeError: Object(...) is not a function
at eval (main.js?56d7:12)
at Module../src/main.js (app.js:13966)
at __webpack_require__ (app.js:833)
at fn (app.js:130)
at Object.1 (app.js:14040)
at __webpack_require__ (app.js:833)
at app.js:971
at app.js:974

---
创建初始化项目

**Comment by John60676** [comment]
ant-design-vue 2.0是  vue 3.x 的组件库
vue 2.x 用[这个链接的](https://www.antdv.com/docs/vue/getting-started-cn/#3.-%E4%BD%BF%E7%94%A8%E7%BB%84%E4%BB%B6)

**Comment by liminga** [comment]
收到，谢谢回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John60676"<notifications@github.com&gt;; 
发送时间: 2020年9月18日(星期五) 上午9:58
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "爱拼才会赢"<1282501454@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] 2.0.0-beta.9全局引入出错 (#2859)





 
ant-design-vue 2.0是  vue 3.x 的组件库
 vue 2.x 用这个链接的
