### ISSUE TITLE
各组件类型问题

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#2861]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
beta9

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
各组件类型基本都有问题，比Tooltip，我没有传title，而是通过slot传递 就会报类型错误，必须传title，其他组件类似，有slot的大部分这样。
还有一种 比如 Select，提示OnBlur 等等必传。  在jsx上面开发

### What is expected?
修复组件类型报错

### What is actually happening?
组件类型报错

**Comment by anncwb** [comment]
还有在vite内开发 ，控制台警告很多

**Comment by tangjinzhou** [comment]
不同问题，请分开提issue  谢谢
