### ISSUE TITLE
MenuItem use key prop will receive  Vue Warn

### ISSUE THREAD

**Issue by 1ncounter** [vueComponent/ant-design-vue#2864]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
Vue version: 3.0.0-beta.14

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
a-menu-item use key prop equal string eq: home, will be receive a Vue warn.

### What is expected?
will be no warning

### What is actually happening?
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

**Comment by John60676** [comment]
please provide minimal reproduction

**Comment by 1ncounter** [comment]
> please provide minimal reproduction

Vue version is 3.0.0-rc.12

https://codesandbox.io/s/vue-antd-issues-demo-9bp0s?file=/src/App.vue

**Comment by John60676** [comment]
I can't reproduce your problem

**Comment by 1ncounter** [comment]
> I can't reproduce your problem

emmm...i update my vue version to 3.0.0, it is no warning...

**Comment by 1ncounter** [comment]
[Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

**Comment by 1ncounter** [comment]
@tangjinzhou

**Comment by 1ncounter** [comment]
> [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.
vue-cli 4.5.6 在使用menu或者pagination 只要关于key作为prop传入，渲染或者重新渲染的时候都会出现。

runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead.

__emit | @ | BaseMixin.js?b488:62
-- | -- | --
  | handleChange | @ | Pagination.js?f8cb:294
  | __emit | @ | BaseMixin.js?b488:62
  | handleClick | @ | Pager.js?0c57:26

callWithErrorHandling | @ | runtime-core.esm-bundler.js?5c40:154
-- | -- | --
  | callWithAsyncErrorHandling | @ | runtime-core.esm-bundler.js?5c40:163
  | invoker | @ | runtime-dom.esm-bundler.js?830f:292
