### ISSUE TITLE
请考虑Button type支持更多的类型

### ISSUE THREAD

**Issue by Silentdoer** [vueComponent/ant-design-vue#2866]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前Button实体背景颜色只支持蓝色和红色两种背景颜色，但是希望能够支持绿色、黄色等可以代表warn、trace之类的等级，或者支持一个属性来自定义背景颜色。

### What does the proposed API look like?
type = "warn"

**Comment by tangjinzhou** [comment]
style="background: red"
