### ISSUE TITLE
标签页组件两个问题

### ISSUE THREAD

**Issue by k-fire** [vueComponent/ant-design-vue#2870]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.9

### Environment
@vue/cli 4.5.6  nodejs 14.11

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
1.使用默认的vue模板，引入ui
2.添加标签页组件，标签页1设置可用，标签2不可用

### What is expected?
标签页1可用
标签页2不可用

### What is actually happening?
标签页1可用
标签页2可用， 在点击标签2再点击标签页1后，标签页2不可用
另外，出现 “[Vue warn]: setup() return property "_isActived" should not start with "$" or "_" which are reserved prefixes for Vue internals. ”

**Comment by xrkffgg** [comment]
请使用 https://codesandbox.io/s/vue-antd-template-e22bh 提供复现

**Comment by k-fire** [comment]
沙盒不会使，我弄了个demo
https://github.com/k-fire/bug

**Comment by k-fire** [comment]
![demo](https://s1.ax1x.com/2020/09/20/w7u5Oe.gif)

**Comment by liwuxi** [comment]
This problem has been fixed #2865
