### ISSUE TITLE
2x版本页面错乱，css没有加载

### ISSUE THREAD

**Issue by lijun4639** [vueComponent/ant-design-vue#2873]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue

### Reproduction link
[https://2x.antdv.com/docs/vue/introduce-cn/](https://2x.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
页面打开错乱

### What is expected?
正常显示

### What is actually happening?
显示错乱

**Comment by xrkffgg** [comment]
我这是正常的啊。

**Comment by tangjinzhou** [comment]
已修复
