### ISSUE TITLE
希望 treeSelect 组件增加点击父节点 title 直接展开子节点功能

### ISSUE THREAD

**Issue by qiaozhi520** [vueComponent/ant-design-vue#2879]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
点击三角展开树太麻烦，希望能增加点击父节点title直接展开子节点功能，而且客户都有这个要求，这个功能在tree组件上自己定义很方便，但是在treeSelect上特别麻烦，当节点添加selectable=false时，点击节点不会返回任何事情，selectable为true 时又会触发选中使下拉框收起

### What does the proposed API look like?
添加上个值 ，可以点击title直接展开树

**Comment by bhh123** [comment]
+1

**Comment by lin88555** [comment]
+1
