### ISSUE TITLE
表单中一个form-item使用 v-if 动态展示不同form组件，输入的时候报错

### ISSUE THREAD

**Issue by myzhoulang** [vueComponent/ant-design-vue#288]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.9

### Environment
window10, 所有浏览器， vue: 2.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y0ow5lnz69)

### Steps to reproduce
选择级联选择器中另一个值， 另一个form-item 中的form组件动态切换， 这时候输入值触发了报错

### What is expected?
能正常运行

### What is actually happening?
控制器报错 值改变不了

**Comment by myzhoulang** [comment]
> 给出可运行的demo 谢谢

现在可以运行 ，之前因为CodeSandbox 自动格式导致了 不能运行，麻烦帮忙看下

**Comment by yuchenbo** [comment]
@tangjinzhou 我这里也有这种情况出现，看了下楼上的demo ,情况雷同

**Comment by tangjinzhou** [comment]
不要用同一个id 控制不同的组件，如果一定要控制不同组件，建议参考[demo](https://vuecomponent.github.io/ant-design-vue/components/form-cn/#components-form-demo-customized-form-controls)  将其封装成一个组件
