### ISSUE TITLE
select value type support boolean

### ISSUE THREAD

**Issue by miniai** [vueComponent/ant-design-vue#2881]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
some scene need select value to be boolean

### What does the proposed API look like?
var SelectValue = PropTypes.oneOfType([PropTypes.string, PropTypes.bool, PropTypes.number, PropTypes.arrayOf(PropTypes.oneOfType([Value, PropTypes.string, PropTypes.number])), Value]);

**Comment by tangjinzhou** [comment]
you can use String(true)
