### ISSUE TITLE
AInputSearch cannot get value success when type Chinese and press Enter

### ISSUE THREAD

**Issue by miyukoarc** [vueComponent/ant-design-vue#2885]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
"ant-design-vue": "^2.0.0-beta.9","vue": "^3.0.0-rc.1",

### Reproduction link
[https://2x.antdv.com/components/input-cn/](https://2x.antdv.com/components/input-cn/)

### Steps to reproduce
```
<template>
Here is dashboard!
<AButton @click="routerPush('/app/home')">Enter</AButton>
<a-input-search v-model:value="val" placeholder="input search text" @search="onSearch" />
</template>

<script>
import { ref } from 'vue'
import { useRouterTo } from '../hooks/useRouterTo.js'
export default {
setup() {
const val = ref('')

function onSearch() {
console.log(val.value)
}

const { routerPush } = useRouterTo()
return {
routerPush,
onSearch,
val,
}
},
}
</script>
```

### What is expected?
Type numbers or letters in English input methods can get value succes. But in Chinese input method cannot.

### What is actually happening?
First press get empty, second press can get value.

---
Original Input perform good.

**Comment by John60676** [comment]
it will be fixed in the next version

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/commit/7ea8de4b7ee78affae03d2f07fbd49bbaa068ff3
