### ISSUE TITLE
使用ConfigProvider组件引起Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lizhongzhen11** [vueComponent/ant-design-vue#2887]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue3,vue-cli 4.5.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-6stji?file=/src/main.js)

### Steps to reproduce
使用vue-cli 4.5.6搭建环境，选择vue3，然后照着官方文档引入ant-design-vue，一开始正常，直到引入ConfigProvider组件，发现浏览器报栈溢出，把它去掉刷新还是报栈溢出：
```js
// main.js
import { createApp } from 'vue'
import App from './App.vue'
import {
ConfigProvider,
Button,
} from 'ant-design-vue';

createApp(App).provide(ConfigProvider).use(Button).mount('#app')


// App.vue
<template>
<a-config-provider :locale="locale">
<App />
</a-config-provider>
</template>

<script>
import zhCN from 'ant-design-vue/es/locale/zh_CN';

export default {
name: 'App',
data() {
return {
locale: zhCN,
};
},
}
</script>
```

<img src="https://s1.ax1x.com/2020/09/23/wj1IjH.png">

最可怕的是把 ant-design-vue 卸载后，相关配置删掉，再启动还报这个错误！是不是使用 ConfigProvider 这个组件后不管成功失败都会修改环境代码？

### What is expected?
正常运行

### What is actually happening?
Maximum call stack size exceeded

**Comment by sendya** [comment]
1.
```diff
-- createApp(App).provide(ConfigProvider).use(Button).mount('#app')
++ createApp(App).use(ConfigProvider).use(Button).mount('#app')
```

2. 不可能改环境代码

**Comment by lizhongzhen11** [comment]
@sendya 
我一开始就用的 `use`，也报这个错，然后看文档说 **ConfigProvider 使用 Vue 的 provide / inject 特性，只需在应用外围包裹一次即可全局生效。** 改用 `provide`，可还是不行。

奇怪的是为何我把 ant-design-vue 卸载掉，相关内容删掉，为何启动还报这个错呢？

**Comment by sendya** [comment]
为何还报错就要问你自己了，环境在你那边 也不再我们这。
你可以自己过一遍流程，有没有重启之类的

**Comment by lizhongzhen11** [comment]
<img src="https://s1.ax1x.com/2020/09/23/wjYgf0.gif">

**Comment by sendya** [comment]
App 引入 App ? 看不懂你的操作

**Comment by lizhongzhen11** [comment]
卧槽，我SB了，无脑复制粘贴官方文档内容，没意识到内部又引入了 <App>，丢脸啊。。。

**Comment by whwhz** [comment]
老哥怎么解决的, 我整体antd引入也有这个问题
