### ISSUE TITLE
setup 内如何使用 this.$confirm() 这样的全局方法？

### ISSUE THREAD

**Issue by Edge00** [vueComponent/ant-design-vue#2889]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
vue3 的 `setup` 内不能访问实例
如果我想要在 `setup` 以及自己封装的 hooks 里面使用 `$confirm` 应该如何使用呢？
或者说应该提供 `const result = await useConfirm('确定执行吗？')` 这样的 `useConfirm` hooks 呢？

### What does the proposed API look like?
```js
import { useConfirm } from 'ant-design-vue/vue-use';
const result = await useConfirm('确定执行吗？')
```

**Comment by tangjinzhou** [comment]
```js
import { Modal } from 'ant-design-vue'
const confirm = Modal.confirm
```

**Comment by xl495** [comment]
> ```js
> import { Modal } from 'ant-design-vue'
> const confirm = Modal.confirm
> ```

这是哪里要用到就要引入吗?

**Comment by Edge00** [comment]
> 这是哪里要用到就要引入吗?

看起来是的
