### ISSUE TITLE
input-number 组件最大值没有大于 Number.MAX_VALUE 缺被格式化成了另一个值

### ISSUE THREAD

**Issue by axetroy** [vueComponent/ant-design-vue#2891]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
1.6.5

### Reproduction link
[https://example.com](https://example.com)

### Steps to reproduce
给 input-number 组件输入一个大的整数 `1234567890987654321` ，这个值与 `Number.MAX_VALUE` 还相差甚远

结果在组件 blur 时被格式化成了 `1234567890987654400`

### What is expected?
1.6.5

### What is actually happening?
1.6.5

**Comment by tangjinzhou** [comment]
https://segmentfault.com/a/1190000009599204
