### ISSUE TITLE
vue-cli4 Import bug

### ISSUE THREAD

**Issue by a1344899122** [vueComponent/ant-design-vue#2892]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
vue-cli4 2.0.0-beta.9

### Reproduction link
[https://2x.antdv.com/docs/vue/getting-started-cn/](https://2x.antdv.com/docs/vue/getting-started-cn/)

### Steps to reproduce
import Vue from 'vue'
import App from './App.vue'
import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';
vue.use(Antd)
Vue.config.productionTip = false
new Vue({
router,
render: h => h(App),
}).$mount('#app')

### What is expected?
repair

### What is actually happening?
Project error report

 warning  in ./node_modules/ant-design-vue/es/vc-tree-select/src/Select.js

"export 'mergeProps' was not found in 'vue'

 warning  in ./node_modules/ant-design-vue/es/vc-tabs/src/ScrollableInkTabBar.js

"export 'mergeProps' was not found in 'vue'

---
no

**Comment by tangjinzhou** [comment]
please use vue3.0

**Comment by tangjinzhou** [comment]
not vue-cli
