### ISSUE TITLE
在cli4中，按需引入后报错 Failed to resolve loader: less-loader

### ISSUE THREAD

**Issue by zhaozhe0831** [vueComponent/ant-design-vue#2894]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6

### Environment
vue 2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
使用vue-cli 4 建立项目，安装 ant-design-vue，按需加载，无法正常引入

### What is expected?
可以正常使用

### What is actually happening?
不能正常使用

这个问题之前有人提过，已经持续很久了

安装 less-loader 后，报错如下

![image](https://user-images.githubusercontent.com/12945873/94095378-32ba4e80-fe54-11ea-8aaf-9bc1a9700cc5.png)

**Comment by tangjinzhou** [comment]
npm i --save less

**Comment by zhaozhe0831** [comment]
安装 less 后，需要在vue.config.js中添加如下配置。即可正常运行

![image](https://user-images.githubusercontent.com/12945873/94096375-8463d880-fe56-11ea-8e61-b27e468378f6.png)
