### ISSUE TITLE
能否在 Select 组件中提供清空选项的回调，如 v-on:clear

### ISSUE THREAD

**Issue by yyj08070631** [vueComponent/ant-design-vue#2895]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前 Select 组件的清空操作缺少一个监听，这个建议是希望事件监听能覆盖控件的所有操作，从而在某些场景下避免使用 v-on:change

### What does the proposed API look like?
@clear | 清空选中项回调 | function

**Comment by tangjinzhou** [comment]
你可以通过 @change 来判断是否是点击的清空按钮

**Comment by yyj08070631** [comment]
> 你可以通过 @change 来判断是否是点击的清空按钮

你好，我这边重新尝试了一下，发现 `@change` 提供的参数是如文档所述的 `function(value, option:Option/Array<Option>)` 结构，但是在这些参数里好像没有找到能判断是否为清空操作的信息，想问下代码上具体是如何操作呢？

**Comment by alleluya-young** [comment]
> > 你可以通过 @change 来判断是否是点击的清空按钮
> 
> 你好，我这边重新尝试了一下，发现 `@change` 提供的参数是如文档所述的 `function(value, option:Option/Array<Option>)` 结构，但是在这些参数里好像没有找到能判断是否为清空操作的信息，想问下代码上具体是如何操作呢？

@yyj08070631 你好 我看select api里有allowClear 这个参数, 你有用么? 是不是加上也没用的?

**Comment by yyj08070631** [comment]
> > > 你可以通过 @change 来判断是否是点击的清空按钮
> > 
> > 
> > 你好，我这边重新尝试了一下，发现 `@change` 提供的参数是如文档所述的 `function(value, option:Option/Array<Option>)` 结构，但是在这些参数里好像没有找到能判断是否为清空操作的信息，想问下代码上具体是如何操作呢？
> 
> @yyj08070631 你好 我看select api里有allowClear 这个参数, 你有用么? 是不是加上也没用的?

@alleluya-young 肯定有的，不然也用不了清除选中功能😂，配置 allowClear 后可以开放清除选中的功能，但我这个 issue 的意思是可能需要一个类似 v-on:clear 这样的回调，监听点击清除的事件。

**Comment by tangjinzhou** [comment]
我们会在 2.0 版本上添加该功能

**Comment by tangjinzhou** [comment]
现在你可以 自定义 clearIcon 来达到你的目的

**Comment by tangjinzhou** [comment]
```html
<template v-slot:clearIcon>
<CloseCircleFilled class="ant-clear-icon" @click="handleClear" />
</template>
```

**Comment by yyj08070631** [comment]
@tangjinzhou
好的，这目前可以解决我的问题。
另外想问下，1.x 是不计划发新版本了吗 😂，因为我看了下 2.x 好像是不支持 vue2 的，所以项目还在 vue2 的孩子后续还想用你们家产品的话，要怎么操作呢？是继续用 1.x，但是无法享受新迭代，还是说后续 2.x 有兼容 vue2 的计划？

**Comment by czbczb** [comment]
@tangjinzhou 请问清空时是设置为‘’么？
mode=multiple时不起作用的，有遇到么？

**Comment by oseaweed** [comment]
> ```
> <template v-slot:clearIcon>
> <CloseCircleFilled class="ant-clear-icon" @click="handleClear" />
> </template>
> ```

点击之后直接清空了 click方法没有执行

**Comment by alleluya-young** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
