### ISSUE TITLE
表格组件在IE11下的异常抖动问题

### ISSUE THREAD

**Issue by sgshy1995** [vueComponent/ant-design-vue#2896]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.5

### Environment
windows 10 , IE11 , Vue 2.6.10

### Reproduction link
[https://preview.pro.antdv.com/list/table-list](https://preview.pro.antdv.com/list/table-list)

### Steps to reproduce
表格每列给定宽度 width，表格指定横向滚动属性 :scroll="{x:true}"，最后一列固定 fixed:"right"。在列数足够多以出现滚动条且最后一列固定。表格的最后列为操作列，有下拉框、文字提示框tooltip等在表格上。

### What is expected?
Chrome FireFox 等浏览器无问题

### What is actually happening?
IE11 下，在此情况下，hover表格中的元素出现文字提示、hover操作列中的a标签出现下拉框，都会随机导致表格类似于刷新数据一样的抖动，且监听表格宽度、表格中各种子元素的宽度，都没有变化。只有在有横向下拉框时，在IE下有此情况发生。

---
本地克隆 ant design vue Pro (Admin)，使用列表页——查询表格，按照上述情况稍做修改，在IE11下hover“描述”列，即可看到抖动。

**Comment by sgshy1995** [comment]
目前发现是同一行内，不同的位置hover，出现下拉框或者文字提示框等，只会第一次抖，不会重复抖动；跨行时，鼠标移动较快时，也不会重复抖动；鼠标移出表格，再移入某一行，hover那些带有其他组件的表格元素，就会抖动。以上情况也只在有固定列和横向滚动框的IE浏览器中可见。

**Comment by tangjinzhou** [comment]
请填写正确的组件库版本
