### ISSUE TITLE
DatePicker 宽度默认属性

### ISSUE THREAD

**Issue by chenzezhang** [vueComponent/ant-design-vue#290]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.9

### Environment
2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/03167y53ow)

### Steps to reproduce
<a-date-picker placeholder="开始" showTime format="YYYY-MM-DD HH:mm:ss"></a-date-picker>

### What is expected?
可以正常运行，希望可以增加修改默认宽的属性

### What is actually happening?
缺少修改默认宽的属性

**Comment by tangjinzhou** [comment]
使用style="width: xxx"

**Comment by chenzezhang** [comment]
这样会不会不美观，有没有类似 增加class的呢？

**Comment by chenzezhang** [comment]
![image](https://user-images.githubusercontent.com/22005939/49635679-7ce1fe00-fa3b-11e8-8644-cb66516b8bab.png)

**Comment by chenzezhang** [comment]
额，好吧，显得我zz

**Comment by tangjinzhou** [comment]
如果问题解决了，可以关闭issue 谢谢

**Comment by chenzezhang** [comment]
好的




| |
xiaozhang
|
|
邮箱：yu521shao@163.com
|

Signature is customized by Netease Mail Master

在2018年12月07日 20:32，tangjinzhou 写道：

如果问题解决了，可以关闭issue 谢谢

**Comment by afc163** [comment]
...
