### ISSUE TITLE
DatePicker组件的panelChange事件无法触发

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#2901]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue2.0

### Reproduction link
[http://no.com](http://no.com)  (there is no link)

### Steps to reproduce
1、 使用datePicker
<a-date-picker
style="width: 100%;"
:default-value="pickerDefault"
@change="onPickerChange"
@openChange="handleOpenChange"
:mode="panelMode"
@panelChange="handlePanelChange"/>
2、在methods中输出
handleOpenChange (status) {
console.log('open change status:', status)
},
handlePanelChange (value, mode) {
console.log('panel change value mode:', value, mode)
},
3、data中设置
panelMode: 'date',
4、在页面中打开关闭面板可以正确触发 handleOpenChange

5、在页面中切换月份 年份 以及各种操作 无法触发  handlePanelChange

### What is expected?
5、可以正确触发 handlePanelChange ，

### What is actually happening?
5、无法正确触发handlePanelChange事件

---
有一个业务场景，需要在面板特殊设置显示某几天的样式，所以打开面板前需要设置当前月， 每次切换 年份、月份 都需要去调用函数 设置样式，所以确切需要pannelChange这个回调

**Comment by hugselina2019** [comment]
版本是1.6.4

**Comment by tangjinzhou** [comment]
提供正确的  Reproduction link

**Comment by wyt1128** [comment]
vue.js : 2.6.12
ant-design-vue :1.7.2
moment.js :2.29.1

DatePicker 日期选择框

浏览器引入的方式
panelChange事件 不能正常触发

npm方式引入
panelChange事件 可以正常触发

http://jsrun.net/rkaKp/edit

**Comment by wyt1128** [comment]
> vue.js : 2.6.12
> ant-design-vue :1.7.2
> moment.js :2.29.1
> 
> DatePicker 日期选择框
> 
> 浏览器引入的方式
> panelChange事件 不能正常触发
> 
> npm方式引入
> panelChange事件 可以正常触发
> 
> Reproduction link   http://jsrun.net/rkaKp/edit

> 希望能解决一下.


> 提供正确的 Reproduction link
