### ISSUE TITLE
ATable component cannot set customRow to trigger row click

### ISSUE THREAD

**Issue by miyukoarc** [vueComponent/ant-design-vue#2903]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
"ant-design-vue": "^2.0.0-beta.10","vue": "^3.0.0-rc.1",

### Reproduction link
[https://2x.antdv.com/components/table-cn/#Table-](https://2x.antdv.com/components/table-cn/#Table-)

### Steps to reproduce
```
<template>
  <ATable :data-source="state.list" rowKey="id" :customRow="customRow">
  <ATableColumn key="date" title="date" data-index="date" />
</ATable>
</template>

<script>
import { reactive } from 'vue'
export default {
name: 'CustomExample',
setup() {
const state = reactive({
list: [
{
id: 1,
date: '第一天',
},
{
id: 2,
date: '第二天',
},
],
})

function customRow(record, index) {
return {
on: {
click: (e) => {
console.log(e, record, index)
},
},
}
}

return {
state,
customRow,
}
}
}
</script>

```

### What is expected?
It can set customRow to trigger row click event

### What is actually happening?
cannot trigger row click event

**Comment by linziguan** [comment]
发生同样的情况，求解

**Comment by linziguan** [comment]
`customRow: record => {
        return {
          click: event => {
            console.log(event, record);
          }
        };
      }`
看了源码，发现这样可行。

**Comment by ibwei** [comment]
> customRow: record => { return { click: event => { console.log(event, record); } }; }

原来是要去掉 on 呀,不了解 jsx 的 on,哈哈哈
