### ISSUE TITLE
ConfigProvider全局设置国际化对modal里content形式设置上的组件不起作用

### ISSUE THREAD

**Issue by five131415** [vueComponent/ant-design-vue#2905]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
ConfigProvider全局设置国际化对modal里content形式设置上的组件不起作用

### Reproduction link
[https://www.antdv.com/components/config-provider-cn/](https://www.antdv.com/components/config-provider-cn/)

### Steps to reproduce
ConfigProvider全局设置国际化对modal里content形式设置上的组件不起作用

### What is expected?
您好，请问如何配置全局设置国际化对modal里content形式设置上的组件也起作用呢

### What is actually happening?
您好，请问如何配置全局设置国际化对modal里content形式设置上的组件也起作用呢

**Comment by John60676** [comment]
提供一下重现代码

**Comment by five131415** [comment]
您好，类似这种形式的弹窗，里面使用带国际化的组件的时候，全局配置的国际化就不好使了
this.$confirm({
        title: 'Do you Want to delete these items?',
        content: h => <a-pagination show-size-changer />,
        onOk() {
          console.log('OK');
        },
        onCancel() {
          console.log('Cancel');
        },
        class: 'test',
      });

**Comment by five131415** [comment]
您好，这种类型弹窗里面的支持国际化的组件，虽然全局配置了国际化，但是在这类组件上好像不起作用。
this.$confirm({
        title: 'Do you Want to delete these items?',
        content: h => <a-pagination show-size-changer />,
        onOk() {
          console.log('OK');
        },
        onCancel() {
          console.log('Cancel');
        },
        class: 'test',
      });

**Comment by five131415** [comment]
您好，这种类型弹窗里面的支持国际化的组件，虽然全局配置了国际化，但是在这类组件上好像不起作用。
`this.$confirm({
        title: 'Do you Want to delete these items?',
        content: h => <a-pagination show-size-changer />,
        onOk() {
          console.log('OK');
        },
        onCancel() {
          console.log('Cancel');
        },
        class: 'test',
      });`

**Comment by John60676** [comment]
使用 [Model.method](https://1x.antdv.com/components/modal-cn/#Modal.method()) 的`parentContext` 指定弹窗的父级上下文

**Comment by five131415** [comment]
您好，
`var that = this
      this.$confirm({
        title: 'Do you Want to delete these items?',
        content: h => <a-pagination show-size-changer />,
        parentContext: that
      })`
我这样使用的，但是该分页组件还是英文状态，请问是我使用的方式不对吗，麻烦您啦

**Comment by John60676** [comment]
https://codesandbox.io/s/vue-antd-template-forked-sgs4m?file=/src/App.vue

**Comment by five131415** [comment]
好的 谢谢您
