### ISSUE TITLE
我们在使用ant design vue，用到table组件的时候，业务场景需要通过列里面的数值来让不同的td显示不同的背景色

### ISSUE THREAD

**Issue by Anniezandr** [vueComponent/ant-design-vue#2906]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
希望table组件自定义单元格的样式

### What does the proposed API look like?
浏览器版本号
版本 85.0.4183.83（正式版本） （64 位）

Vue 版本号
"vue": "^2.6.11",

组件库版本号
"ant-design-vue": "1.6.4",

**Comment by xrkffgg** [comment]
Try `rowClassName`.
