### ISSUE TITLE
Modal组件高度设置

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#2909]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我发现Modal组件只有宽度属性width，需要固定Modal组件内容高度的情况是否可以添加height属性设置

### What does the proposed API look like?
<a-modal
title="my modal"
:width="700"
:height="400"
v-model="visible"
:footer="null"
>
</a-modal>

**Comment by tangjinzhou** [comment]
try  dialogStyle bodyStyle

**Comment by date-convert** [comment]
> try dialogStyle bodyStyle

但是 bodyStyle只是设置body的样式  无法控制整个modal，例如我需要设置modal占整个窗口的80%高度 无法实现

**Comment by femaimi9527** [comment]
确实是不能控制modal的高度，如果设置了高度，则在a-modal里面的内容比较多的情况下，会导致内容超出a-modal的范围，跑到外面去
