### ISSUE TITLE
Using select-option in form layout="inline", there is a problem with the option display, and the content cannot be displayed completely

### ISSUE THREAD

**Issue by gsdukbh** [vueComponent/ant-design-vue#2911]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
"ant-design-vue": "^1.6.5",windows10 2004 , chrome  85.0.4183.102

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-vaughan-nfbgh)

### Steps to reproduce
```html
<a-form layout="inline">
<a-form-item label="设备类型">
<a-select>
<a-select-option :value="undefined"> 请选择 </a-select-option>
</a-select>
</a-form-item>
</a-form>
```

如以上使用，会出现https://codesandbox.io/s/loving-vaughan-nfbgh?file=/src/App.vue ，选项会被压缩在一个小心的宽度内。

### What is expected?
希望能够和在使用input 组件一样的宽度

### What is actually happening?
被压缩在非常小的宽度，非常的疑惑,.

**Comment by John60676** [comment]
你可以自己使用 css 去控制，例如设置一个宽度
https://codesandbox.io/s/practical-neumann-2h8lx?file=/src/App.vue:90-130

**Comment by gsdukbh** [comment]
> 你可以自己使用css去控制，例如设置一个宽度
> https://codesandbox.io/s/practical-neumann-2h8lx?file=/src/App.vue:90-130
的确可以这样做，但我想在使用select的时候，不需要额外的设置，就能和input 一样的宽度。我并不想每个input和select都去设置他的宽度。
