### ISSUE TITLE
Select组件值问题 出现警告 造成卡顿 警告内容太多。造成控制台卡顿浏览器卡死

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#2912]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vite jsx

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
在jsx内使用Select组件时候，采用  options传递下拉值，会报警告
警告出现的时机是点击后下拉出来报的
```
// 传这样会报警告
options: [
{
label: '选项1',
value: '1',
},
{
label: '选项2',
value: '2',
},
],
```

// 传这样会则不会需要加key属性，但是以前的写法是不用的。2.0改了吗 xuyao
options: [
{
label: '选项1',
value: '1',
key: '1',
},
{
label: '选项2',
value: '2',
key: '2',
},
],
```

// 主要的警告信息
```
[VueTypes warn]: oneOfType - value "null" should be of type "String or Number"
runtime-dom.esm-bundler-23302e7d.js:1180 [Vue warn]: Invalid prop: custom validator check failed for prop "selectedKeys".
```


### What is expected?
删除警告

### What is actually happening?
出现警告 造成卡顿 警告内容太多。造成控制台卡顿



        

<!-- generated by issue-helper. DO NOT REMOVE -->

**Comment by anncwb** [comment]
希望这个早点解决 不然都要多加一个key才可以 
```
文档内 key不是必传 

options | options 数据，如果设置则不需要手动构造 selectOption 节点 | array<{value, label, [disabled, key, title]}>



```

**Comment by heuaxa** [comment]
是的，我用template写法也遇到了。
```vue
<a-select v-model:value="modelRef.systemId" :options="enumOptions"></a-select>
```
必须要传key才可以消除警告。目前是通过自己创建组件解决的。
主要代码如下：
```vue
<a-select v-model:value="modelRef.method">
  <a-select-option
    v-for="option in enumOptions"
    :key="option.value"
    :value="option.value"
  >
     {{ option.label }}
  </a-select-option>
</a-select>
```
希望尽快修复。
