### ISSUE TITLE
Tree组件选择取消node问题

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#2915]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
<a-tree>组件点击某个node会选中、再次点击会取消选中；现在需要禁止取消事件，即总存在一个选中项、再次点击取消事件不生效

### What does the proposed API look like?
---

**Comment by zkwolf** [comment]
你可以自己想办法先控制一下数据实现这个需求
