### ISSUE TITLE
Refactor with TypeScript 🔥

### ISSUE THREAD

**Issue by Amour1688** [vueComponent/ant-design-vue#2919]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

It is recommended that the number of components claimed at a time should not exceed 3, if there is no progress for a long time, it will be cancelled.

建议单次认领组件数量不超过3个，如长时间没有进度，会进行释放。
每个PR，提交一个组件，多个组件分开提。
vc 开头的组件暂时不需要改动

PR 前请务必阅读，[如何优雅地在github上贡献代码](https://segmentfault.com/a/1190000000736629)

### What problem does this feature solve?

Embrace TypeScript in `next` branch

- [ ] Affix @zzzz-Z
- [ ] Alert @anncwb
- [ ] Anchor @thisisandy
- [ ] AutoComplete
- [ ] Avatar @zzzz-Z
- [ ] BackTop @anncwb
- [ ] Badge  @thisisandy
- [ ] Breadcrumb @anncwb
- [ ] Button  @thisisandy
- [ ] Calendar
- [ ] Card  @thisisandy
- [ ] Carousel
- [ ] Cascader
- [ ] Checkbox
- [x] Col @Amour1688 
- [ ] Collapse @shmilybaozi 
- [ ] Comment @zzzz-Z
- [x] ConfigProvider @Amour1688 
- [ ] DatePicker
- [ ] Descriptions @yandixuan
- [x] Divider @John60676 
- [ ] Drawer
- [ ] Dropdown @John60676
- [x] Empty @Amour1688 
- [ ] Form  @tangjinzhou 
- [ ] Icon @John60676
- [ ] Input @John60676
- [ ] InputNumber @John60676
- [ ] Layout @John60676
- [ ] List  @tangjinzhou 
- [ ] Mentions
- [ ] Menu
- [ ] Modal
- [ ] PageHeader
- [ ] Pagination
- [ ] Popconfirm
- [ ] Popover
- [ ] Progress @Xutaotaotao
- [ ] Radio
- [ ] Rate
- [ ] Result @anncwb
- [x] Row @Amour1688 
- [x] Select @tangjinzhou 
- [ ] Skeleton
- [ ] Slider
- [ ] Spin @anncwb
- [ ] Statistic @ununian
- [ ] Steps @yandixuan
- [ ] Switch
- [ ] Table
- [ ] Tabs
- [x] Tag @Amour1688 
- [ ] TimePicker
- [ ] Timeline
- [ ] Tooltip
- [ ] Transfer
- [ ] Tree  @tangjinzhou 
- [ ] TreeSelect  @tangjinzhou 
- [ ] Upload @Minitiai
- [ ] message @John60676
- [ ] notification

**Comment by thisisandy** [comment]
[] Anchor
[] Badge
[] Button
[] Card

**Comment by John60676** [comment]
- [ ] Divider
 - [ ] Dropdown
 - [ ] Icon
 - [ ] Input
 - [ ] InputNumber
 - [ ] Layout
 - [ ] message

**Comment by anncwb** [comment]
- [ ] Breadcrumb
- [ ] Drawer
- [ ] Modal
- [ ]  BackTop
- [ ] Alert
- [ ] Avatar
- [ ] Result
- [ ] Spin
- [ ] Empty

**Comment by anncwb** [comment]
可以在原来的基础上扩展吗，或者有没有别的要求？

**Comment by ununian** [comment]
- [ ] Statistic
- [ ] Tag

**Comment by Amour1688** [comment]
> * [ ]  Statistic
> * [ ]  Tag

Tag 已经改过了

**Comment by ununian** [comment]
> > * [ ]   Statistic
> > * [ ]   Tag
> 
> Tag 已经改过了

ok，那我换一个，刚刚没看到

**Comment by zzzz-Z** [comment]
- [ ] Affix
- [ ] AutoComplete
- [ ] Avatar
- [ ] Col
- [ ] Comment
- [ ] Descriptions
- [ ] Input
- [ ] Rate
- [ ] Row
- [ ] Radio

**Comment by Minitiai** [comment]
- [ ] Countdown
- [ ] Switch

**Comment by tengfei8382** [comment]
- [ ] Descriptions

**Comment by shmilybaozi** [comment]
- [ ] Collapse

**Comment by sendya** [comment]
- [ ] Checkbox
- [ ] Col
- [ ] Collapse
- [ ] Comment

**Comment by yandixuan** [comment]
- [ ] Steps

**Comment by Xutaotaotao** [comment]
- [ ] Progress

**Comment by xrkffgg** [comment]
给大佬们打 call

**Comment by tangjinzhou** [comment]
@tengfei8382  Descriptions 重复

**Comment by hzgotb** [comment]
-[ ] Radio

**Comment by tangjinzhou** [comment]
我要关闭这个 issue 了，如果大家要参与，请做好严格的测试，跑通官网示例是最基本要求
   有明显问题的pr 我会直接关闭
