### ISSUE TITLE
table with column slot record value error

### ISSUE THREAD

**Issue by yandixuan** [vueComponent/ant-design-vue#2921]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
System: OS: Windows 10 10.0.18362   Browsers: Chrome: 81.0.4044.129  Node: 12.13.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-qddvq?file=/src/App.vue)

### Steps to reproduce
in this case,
1. click flush button for replace tableData
2. move mouse to  opreation dropdown click print button to see what the console actually prints

### What is expected?
record should change

### What is actually happening?
record value lost reactive

---
i just use simple slot just like
```
<a-table-column align="center" width="8%" title="">
<template v-slot="{record}"
<a-button @click="handleClick(record)">print</a-button>
</template>
</a-table-column>
```
it's ok.......

**Comment by tangjinzhou** [comment]
this is  vue bug https://github.com/vuejs/vue-next/issues/2618
Now you can use `<button @click="showValue(record)" data-record-name="{{record.name}}">打印</button>` to solve it  before vue reslove it.
