### ISSUE TITLE
使用typescrpt时，按需引入Space 组件会报错。

### ISSUE THREAD

**Issue by fangyang921017** [vueComponent/ant-design-vue#2923]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
window10 chrome85, vue2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silent-water-dryh9?file=/src/main.ts)

### Steps to reproduce
import { Space } from 'ant-design-vue'

### What is expected?
能够正常导出，并不报错

### What is actually happening?
能够正常导出，但报错：模块 ""../../../node_modules/ant-design-vue/types"" 没有导出的成员 "Space"。

**Comment by kkjj-kj** [comment]
直接使用a-space 报未注册组件 递归组件需要使用name属性  
在空白页面不是递归组件 直接调用报错
