### ISSUE TITLE
Table 在设置 rowSelection 为 true 时，且初始数据为空时存在性能问题

### ISSUE THREAD

**Issue by kagawagao** [vueComponent/ant-design-vue#2925]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
- vue: `3.0.0`
- ant-design-vue: `2.0.0-beta.10`

### Reproduction link
[https://github.com/kagawagao/antdv-vue-demo](https://github.com/kagawagao/antdv-vue-demo)

### Steps to reproduce
启动服务
加载数据
看耗时

### What is expected?
无性能问题

### What is actually happening?
加载数据很慢

**Comment by crossui** [comment]
1.6.5版本也有这样的问题  第一次渲染很快 （50条数据） 选中某条渲染很慢
