### ISSUE TITLE
在electron项目开发中，采用require的方式引入ant-design-vue 2.x版本，提示lodash引入方式报错

### ISSUE THREAD

**Issue by devie2020** [vueComponent/ant-design-vue#2939]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
开发、生产

### Reproduction link
[https://2x.antdv.com/docs/vue/introduce-cn/](https://2x.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
1. 进入electron的项目
2. 安装ant-design-vue@next
3. 运行项目
4. 报错lodash的引入方式出错，不支持requre

### What is expected?
期望可以使用require的方式引入

### What is actually happening?
提示使用 import的方式，然后项目中require引入方式不可更改

**Comment by l619534951** [comment]
1.x版本没问题，2.x版本不行

**Comment by chengaomin** [comment]
+1 遇到一样的问题

**Comment by l619534951** [comment]
> +1 遇到一样的问题

可以用esm解决，好像是es-loadash的问题

**Comment by chengaomin** [comment]
有没有一个可以正常运行起来的electron+ant-design-vue模板啊 @l619534951

**Comment by zkwolf** [comment]
electron也不强制require吧
