### ISSUE TITLE
rules的options.trigger的值为blur时,无法输入任何字符

### ISSUE THREAD

**Issue by xiangnanscu** [vueComponent/ant-design-vue#294]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.10

### Environment
mac os   chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rjkz5z4r54)

### Steps to reproduce
随便按几个字符

### What is expected?
输入框应该出现相应字符

### What is actually happening?
输入框空白

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/49706620-e3e0fc00-fc61-11e8-8894-08deeb71261b.png)
我想你需要的应该是 validateTrigger，
至于trigger，大部分情况下应该没有改变的需求，除非是你自己定义的组件。

**Comment by hilads** [comment]
我也遇到了 这个问题 原来是我把blur 写成了 onBlur  罪过罪过
