### ISSUE TITLE
Table rows sorting using drag drop

### ISSUE THREAD

**Issue by rahultailwal** [vueComponent/ant-design-vue#2941]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
2

### Reproduction link
[https://www.antdv.com/components/table/](https://www.antdv.com/components/table/)

### Steps to reproduce
I am using Ant Design Vue for my Vue.js project. In the native Ant Design, we have sorting using row drag drop within the table (https://ant.design/components/table/#components-table-demo-drag-sorting) but its not available in Ant Design Vue.

https://www.antdv.com/components/table/

Is there a way to include that feature in Ant Design Vue also or if this is already there then any documentation for it?

I tried to use Sortable/Vue.Draggable but its not supporting it. https://github.com/SortableJS/Vue.Draggable

### What is expected?
https://ant.design/components/table/#components-table-demo-drag-sorting
Similar to this is required.

### What is actually happening?
No drag/drop sorting available

**Comment by zkwolf** [comment]
https://codesandbox.io/s/draggable-table-e07sm?file=/src/App.vue 
you can refer to this demo

**Comment by rahultailwal** [comment]
thanks @zkwolf , it looks like the move event in the custom Wrapper is not working and that is important to know what happened in the App.vue file. I tried to add some console in the function. any idea?

**Comment by zkwolf** [comment]
I fixed this, you can test the demo.

BTW, I find the it can't work together with rowKey now.

**Comment by rahultailwal** [comment]
Thanks, it looks working. I have nested tables so will do some more tests with it as I am getting some issues might be due to data or might be due to the wrapper. I will update you.

**Comment by zkwolf** [comment]
umm.....It seems that the demo is incorrent, the dataSource will update when move the row, so something unexpected will happen.You can see the latest demo.

**Comment by rahultailwal** [comment]
Yes, I am seeing that if I go to next page the data is also not updating. I dont know whether that is the right approach to have drag drop with ant design vue or not. What do you think?

**Comment by zkwolf** [comment]
The data is not updated because there
![image](https://user-images.githubusercontent.com/8555127/96748101-afacf980-13fb-11eb-8a79-21ee7e34e2b8.png)
 left `this`. 
This codesandbox seems base on a issue reproduction and I only test the drag and drop logic.

**Comment by rahultailwal** [comment]
But as it have many issues so we cant use it for drag drop and drag drop is a required feature to have in the table. Any other approach?

**Comment by zkwolf** [comment]
I think it is the only way that if you want to use Vue.Draggable to realize this feature.Or you can try use the original drag and drop api of HTML5? Or any other idea?

**Comment by rahultailwal** [comment]
do you have any example of original drag drop html api with ant design vue table?

**Comment by Timo534** [comment]
> https://codesandbox.io/s/draggable-table-e07sm?file=/src/App.vue
> you can refer to this demo

适配Vue3版的VueDraggable使用item slot instead of default显示元素，请问还能做到兼容吗？
