### ISSUE TITLE
Visible in dropdown not working

### ISSUE THREAD

**Issue by natuan62** [vueComponent/ant-design-vue#2947]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
Windows 10, chrome 86, vue 3.0

### Reproduction link
[https://2x.antdv.com/components/dropdown/#The-way-of-hiding-menu.](https://2x.antdv.com/components/dropdown/#The-way-of-hiding-menu.)

### Steps to reproduce
Test in link https://2x.antdv.com/components/dropdown/#The-way-of-hiding-menu.

### What is expected?
Dropdown still visible with item key = 1, 2

### What is actually happening?
Dropdown close with item key = 1,2

**Comment by sendya** [comment]
try `v-model:visible="visible"`

**Comment by tangjinzhou** [comment]
demo error
