### ISSUE TITLE
beta版本 怎么配合按钮加载插件使用

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#2956]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
windows 10,chrome:86 vue 3.0

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
直接按照文档描述在babel配置文件
``` js
module.exports = {
presets: [
'@vue/cli-plugin-babel/preset',
],
// plugins: [
//   [
//     'import',
//     { libraryName: 'ant-design-vue', libraryDirectory: 'es', style: true },
//   ],
// ],
};
```
会提示antd不存在
// main.js
``` js
import antd from 'ant-design-vue';
import 'ant-design-vue/components/style';

export default (vm) => {
vm.use(antd);
};
```

### What is expected?
期待按需加载正常工作

### What is actually happening?
报错

**Comment by sendya** [comment]
配了按需就不用 也不能用  import antd from 'ant-design-vue' 了。
应该按需引入对应需要的组件！
import { Button } from 'ant-design-vue'

文档不是有 demo 吗？

**Comment by bosens-China** [comment]
解决了改用require就可以了
不能用import来引入

**Comment by bosens-China** [comment]
> 配了按需就不用 也不能用 import antd from 'ant-design-vue' 了。
> 应该按需引入对应需要的组件！
> import { Button } from 'ant-design-vue'
> 
> 文档不是有 demo 吗？

我记得在之前版本，只需要配置babel的`import`插件，全局导入一次就不需要按需来引入，就是你上面的这种写法了，现在必须显示的引入么？
