### ISSUE TITLE
[Nuxt + Ant Design] On the first page load Layout and Sider rendering is too slow when use target: 'server'

### ISSUE THREAD

**Issue by Bac3Phi** [vueComponent/ant-design-vue#2958]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
"nuxt": "^2.14.0", "ant-design-vue": "^1.6.4",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/morning-forest-q0lw2?file=/pages/index.vue:1187-1195)

### Steps to reproduce
As you can see. On the first page load a-layout-content rendering is too slow. when I use `nuxt.config.js`

```mode:" universal ", target:" server ".```

I think this error is caused by page loading too many stylesheets from ant-design.
Any solution to improve it? Thank you guys

### What is expected?
I want to improve speed on target: 'server'

### What is actually happening?
You can see my screenshot via https://i.gyazo.com/8f19993b84ce32c19fc92980f0fe4d12.gif

**Comment by TariqueNasrullah** [comment]
Having the same issue. Did you fixed it? I'm using the nuxt's default config.

**Comment by Bac3Phi** [comment]
> Having the same issue. Did you fixed it? I'm using the nuxt's default config.
Sorry for late comment
In your `<a-layout>` just need add attribute `:hasSider=true`. 
It will auto fill blank your content when reload.
More information you can read Layout API https://www.antdv.com/components/layout/#Layout
