### ISSUE TITLE
table customrow 文章描述错误

### ISSUE THREAD

**Issue by Luooooooo** [vueComponent/ant-design-vue#2961]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
table customrow 使用说明，文档描述错误

### What does the proposed API look like?
文档描述错误
```
customRow={(record) => {
return {
props: {
xxx... //属性
},
on: { // 事件
click: (event) => {},       // 点击行
dblclick: (event) => {},
contextmenu: (event) => {},
mouseenter: (event) => {},  // 鼠标移入行
mouseleave: (event) => {}
},

};
```
应是
```
customRow={record => {
return {
onclick() {
console.log(record);
},
onmouseenter:()=>  console.log(record) // 鼠标移入行
};
```

**Comment by celizi** [comment]
对的 文档需要增加            前往 codepen.io 运行此示例

**Comment by Luooooooo** [comment]
> 对的 文档需要增加 前往 codepen.io 运行此示例

请问文档怎么贡献，我没找到库

**Comment by zkwolf** [comment]
已更新文档
