### ISSUE TITLE
Combination with requirejs

### ISSUE THREAD

**Issue by mirshahreza** [vueComponent/ant-design-vue#2963]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue-browser version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/requirejs-vue3-antv-71ypt)

### Steps to reproduce
this sandbox contains a sample that shows the problem
https://codesandbox.io/s/requirejs-vue3-antv-71ypt

### What is expected?
I expected render antd components

### What is actually happening?
But it does not show the component

**Comment by tangjinzhou** [comment]
first, beta.10 just support vue3
second, beta.10 should register by youself
like app.use(antdv)

**Comment by mirshahreza** [comment]
This sample uses vue3
How can I app.use in browser mode?
