### ISSUE TITLE
Menu 组件样式问题

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#2966]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
window 10， chrome,  Vue3.0.0

### Reproduction link
[https://2x.antdv.com/components/menu-cn/](https://2x.antdv.com/components/menu-cn/)

### Steps to reproduce
Menu 组件在 浅色（light）模式下，菜单缩起后（collapsed）将鼠标移入，展示悬浮标题

### What is expected?
menu在浅色模式下，悬浮标题也应该是浅色的，主题应该一致

### What is actually happening?
浅色模式下，展示的悬浮标题是深色模式的，不协调

**Comment by xrkffgg** [comment]
看了下 ant-design 也是这样的交互设计

**Comment by xrkffgg** [comment]
可以自行覆盖 css

**Comment by yangss3** [comment]
> 
> 
> 看了下 ant-design 也是这样的交互设计

![图片](https://user-images.githubusercontent.com/64787128/95729023-d27a3800-0cae-11eb-9a9b-14d41e5979ab.png)
![图片](https://user-images.githubusercontent.com/64787128/95729068-e0c85400-0cae-11eb-9e02-5b9319cd10f5.png)

这个设计真的很不协调，我不认为是有意这样设计的，可能是疏漏。

**Comment by xrkffgg** [comment]
你可以去 ant-design 中提一下
其实改起来也简单，扩展一下 Tooltip 的属性就行
你看一下现有的 Tooltip 就是只有黑色背景的，但是可以通过 className 和 style 进行自定义。

如果官方设计规范不更改，你可以通过 css 进行自定义。

**Comment by tangjinzhou** [comment]
我先关闭了，如果 antd 修改规范，我们会跟进
