### ISSUE TITLE
table在loading为true，data-source为空数组，empty同时显示

### ISSUE THREAD

**Issue by as0026** [vueComponent/ant-design-vue#2967]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
chrome、火狐等浏览器

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
a-table在初次加载数据时，loading为true，data-source为空数组，此时在Spin加载中之下empty显示，

### What is expected?
预期就是希望在spin加载中，table中的empty不显示

### What is actually happening?
目前1.6.5版本的情况是，在spin加载中，table的empty也显示“无数据”文字，给用户造成疑惑。

**Comment by tangjinzhou** [comment]
你可以把 data-source 改成 undefined
