### ISSUE TITLE
服务端渲染的情况下，Table组件tr标签的样式属性设置错误

### ISSUE THREAD

**Issue by Xzillion** [vueComponent/ant-design-vue#297]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.10

### Environment
win10/vue2.5.17

### Reproduction link
[https://www.mytoken.io/](https://www.mytoken.io/)

### Steps to reproduce
1.在服务端渲染的项目中使用ant-design-vue；
2.查看渲染出来的table组件节点，发现tbody下面tr标签的样式被设置为style="height:null"

### What is expected?
增加空值判断或者允许设置height属性

### What is actually happening?
未对空值属性进行判断

**Comment by tangjinzhou** [comment]
ref https://github.com/nuxt/nuxt.js/issues/4652

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/vue/issues/9231

**Comment by tangjinzhou** [comment]
等待vue官方2.6版本解决 https://github.com/vuejs/vue/projects/4#card-16086136
