### ISSUE TITLE
在Table中使用InputNumber时无法响应输入

### ISSUE THREAD

**Issue by sundadong** [vueComponent/ant-design-vue#2970]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Chrome86

### Reproduction link
[https://www.antdv.com/components/input-number-cn/](https://www.antdv.com/components/input-number-cn/)

### Steps to reproduce
在Table中使用inputNumber时，更改值输入框内不能响应

### What is expected?
在Table中使用inputNumber时，输入数字会自动响应到输入框中

### What is actually happening?
在Table中使用inputNumber时，更改值输入框内不能响应

**Comment by tangjinzhou** [comment]
提供 复现 链接后可重新打开

**Comment by sundadong** [comment]
复现链接：https://codesandbox.io/s/black-sun-rket2
