### ISSUE TITLE
ReadOnly option doesn't work for a-input-number

### ISSUE THREAD

**Issue by RuslanTau** [vueComponent/ant-design-vue#2971]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
macOS 10.15, Chrome 86.0.864240, ant-design-vue 1.6.2, nuxt 2.13.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-26qpt?file=/src/App.vue)

### Steps to reproduce
Create a-input-number, set his "readonly" property to true and try to change input value.

### What is expected?
Input value became unmutable.

### What is actually happening?
Input value still mutable.

**Comment by tangjinzhou** [comment]
you can try disable

**Comment by haroonth** [comment]
It worked with `readOnly`

**Comment by RuslanTau** [comment]
> It worked with `readOnly`
> I try it in `<a-input>`



> you can try disable

Yes, I try disable and it works, but the input styles changed to disabled too. 
Because of this, I have to copy/paste fix styles for each a-input-number in my app.

**Comment by RuslanTau** [comment]
> It worked with `readOnly`
> I try it in `<a-input>`

It work for `<a-input>`, but doesnt work for `<a-input-number>`
