### ISSUE TITLE
modal中设置auto-size的textarea的高度在首次打开和二次打开modal时不一致

### ISSUE THREAD

**Issue by NoTalk-ly** [vueComponent/ant-design-vue#2974]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
chrome: 85.0.4183.121 OS: Mac OS 10.15.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-textarea-within-modal-bug-oer73)

### Steps to reproduce
codesandbox即可复现

### What is expected?
期望无论哪次打开弹窗 textarea高度都一致为3行(当前例子中)

### What is actually happening?
点击按钮打开弹窗，textarea 此时高度为3行
点击弹窗cancel按钮关闭弹窗后再打开弹窗，此时textarea高度变成了2行

**Comment by NoTalk-ly** [comment]
有人能回复下吗？随时可以协助复现该bug。

**Comment by John60676** [comment]
临时方案：在把 `v-if` 放到 `a-modal` 外面
https://codesandbox.io/s/vue-antd-template-textarea-within-modal-bug-forked-ss5sj?file=/src/App.vue
