### ISSUE TITLE
tree树形控件 选中效果设置

### ISSUE THREAD

**Issue by YiXingYuFeng** [vueComponent/ant-design-vue#2976]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue

### Reproduction link
[https://www.antdv.com/components/tree-cn/](https://www.antdv.com/components/tree-cn/)

### Steps to reproduce
设置节点选中的后效果，字体大小颜色背景色，节点的icon的选中效果

### What is expected?
希望开放此等支持

### What is actually happening?
设置节点选中的后效果，字体大小颜色背景色，节点的icon的选中效果

**Comment by xrkffgg** [comment]
可以自行覆盖 css

**Comment by YiXingYuFeng** [comment]
选中后的节点的图标也可以通过css的方式处理吗

**Comment by YiXingYuFeng** [comment]
查看官方的demo后才找到如何修改节点选中后的图标样式，但是文档上并没有说明（这个操作真的很文档），但愿文档后期补充进来，拜退
