### ISSUE TITLE
clone 之后 如何在本地运行起来了呢

### ISSUE THREAD

**Issue by van-chin** [vueComponent/ant-design-vue#2978]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
node v12.18.3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
1. git clone https://github.com/vueComponent/ant-design-vue.git
2. 安装依赖
3.yarn dev
经过上面之后提示

ERROR in ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2!./node_modules/vue-loader/dist??ref--12-0!./examples/App.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve '../antdv-demo/docs/input/demo/basic.md' in '/path/to/ant-design-vue/examples'
@ ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2!./node_modules/vue-loader/dist??ref--12-0!./examples/App.vue?vue&type=script&lang=js) 1:0-58 4:10-14
@ ./examples/App.vue?vue&type=script&lang=js
@ ./examples/App.vue
@ ./examples/index.js
Child html-webpack-plugin for "index.html":
1 asset
Entrypoint undefined = index.html
[./node_modules/html-webpack-plugin/lib/loader.js!./examples/index.html] 1.23 KiB {0} [built]
[./node_modules/lodash/lodash.js] 530 KiB {0} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 905 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

### What is expected?
希望可以在本地运行起来，自己可以调试组件

### What is actually happening?
ERROR in ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2!./node_modules/vue-loader/dist??ref--12-0!./examples/App.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve '../antdv-demo/docs/input/demo/basic.md' in '/path/to/ant-design-vue/examples'
@ ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--2!./node_modules/vue-loader/dist??ref--12-0!./examples/App.vue?vue&type=script&lang=js) 1:0-58 4:10-14
@ ./examples/App.vue?vue&type=script&lang=js
@ ./examples/App.vue
@ ./examples/index.js
Child html-webpack-plugin for "index.html":
1 asset
Entrypoint undefined = index.html
[./node_modules/html-webpack-plugin/lib/loader.js!./examples/index.html] 1.23 KiB {0} [built]
[./node_modules/lodash/lodash.js] 530 KiB {0} [built]
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 905 bytes {0} [built]
[./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 552 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by John60676** [comment]
你要自己移除 examples/App.vue 里面 与[这行](https://github.com/vueComponent/ant-design-vue/blob/feat-vue3/examples/App.vue#L7)相关的代码

**Comment by van-chin** [comment]
@John60676 谢谢
