### ISSUE TITLE
Layout.Sider组件ts types缺少回调函数的定义

### ISSUE THREAD

**Issue by AllenForward** [vueComponent/ant-design-vue#2983]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
Chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/feat-vue3/types/layout/layout-sider.d.ts](https://github.com/vueComponent/ant-design-vue/blob/feat-vue3/types/layout/layout-sider.d.ts)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue/blob/feat-vue3/types/layout/layout-sider.d.ts

### What is expected?
add collapse?: (collapsed: boolean, type: CollapseType) => void or onCollapse?: (collapsed: boolean, type: CollapseType) => void

### What is actually happening?
属性“onCollapse”在类型“IntrinsicAttributes & HTMLAttributes & LayoutSiderProps”上不存在。

**Comment by Amour1688** [comment]
下个版本修复
