### ISSUE TITLE
Base border radius is not working

### ISSUE THREAD

**Issue by Yakoot** [vueComponent/ant-design-vue#2984]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
OS: Manjaro 20.1.1 Mikah, Vivaldi	3.3.2022.47 (Stable channel) (64-bit), vue 3.0

### Reproduction link
[https://2x.antdv.com/components/form/#components-form-demo-form-layout](https://2x.antdv.com/components/form/#components-form-demo-form-layout)

### Steps to reproduce
just open docs for antdv 1 and 2 and compare

### What is expected?
https://www.antdv.com/components/form/
here it works, you can see border radius on each field

### What is actually happening?
https://2x.antdv.com/components/form/
here it doesn't work

**Comment by tangjinzhou** [comment]
I donnot know what is you mean

**Comment by Yakoot** [comment]
hm, it looks ok now
