### ISSUE TITLE
使用modal 的afterClose的事件和destroyOnClose属性，想在关闭弹出框时候，销毁modal的内容但是没有起作

### ISSUE THREAD

**Issue by yixiyimeng** [vueComponent/ant-design-vue#299]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.10

### Environment
win7 谷歌 vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1kwyzjzzj)

### Steps to reproduce
1， 打开弹出框，裁剪图片
2，关闭弹出框，上传上传的图片和裁剪都再，

### What is expected?
希望使用afterClose 事件将img的src清空

### What is actually happening?
afterClose事件没有反应

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/21rwzw3zx0
`:afterClose="afterClose"`
not
`@afterClose="afterClose()"`
