### ISSUE TITLE
Support header slot for `Collapse.Panel`  in ant-design-vue2.0.0-beta.10 based on vue3

### ISSUE THREAD

**Issue by Alexaa123** [vueComponent/ant-design-vue#2990]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue version: vue3, antdesign-version: 2.0.0-beta.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-hs823?file=/src/components/HelloWorld.vue)

### Steps to reproduce
```
<a-collapse-panel key="1">
<template v-slot:header>222</template>
<a-collapse-panel>
```

### What is expected?
i hope collapse-panel's head is 222, but it has a bug

### What is actually happening?
there has a false, it apperas in chrome: 'Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object'

---
it's an obvious bug, i hope it can be fixed as quickly as possible

**Comment by jaycaoln** [comment]
+1

**Comment by jaycaoln** [comment]
v-slot:header  doesn't  work
