### ISSUE TITLE
a-select设置了allowClear后，点击清除按钮会把绑定的属性从对象中删除

### ISSUE THREAD

**Issue by samulle** [vueComponent/ant-design-vue#2993]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Windows10，chrome85.0.4183.83,vue2.6.10

### Steps to reproduce
``<a-select
v-model="data[index].queryType"
allow-clear
placeholder="请选择">
<a-select-option value="=">=</a-select-option>
<a-select-option value="!=">!=</a-select-option>
</a-select>``
数据回显默认选中一个选项，然后点击清除按钮会把data对象中的queryType属性给删除。

### What is expected?
点击清除按钮只删除绑定属性的值，不需要删除绑定的属性。

### What is actually happening?
因为属性丢失，导致数据保存失败。

**Comment by l619534951** [comment]
清除数据一般都是将数据改为void 0，数据保存失败这个我觉得是你前端或者后台的问题，不是框架问题，两个解决办法：
第一种：前端拦截ajax请求，将其中void 0的数据改为null。
第二种：后台更改，根据你的实际需要来改。

**Comment by samulle** [comment]
@l619534951 你可能没有看明白我得意思。现在得问题是绑定得属性直接删除了。比如`form:{id:null,sex:‘男’}`我定义这个对象，然后<a-select v-model="form.sex" allow-clear placeholder="请选择"><a-select-option value="男">男</a-select-option> <a-select-option value="!=">!=</a-select-option> </a-select>，然后我点清除按钮的时候，form的sex属性就没有了，直接变成`form:{id:null}`。我是觉得这样不合理，可以把sex属性的值清空，但是没有必要把sex这个属性从对象中直接给删掉。我用其他的组件都是把属性的值置空，而不是删除；所以我怀疑是不是一个bug。

**Comment by tangjinzhou** [comment]
请提供有效的复现链接
