### ISSUE TITLE
Module '"ant-design-vue/types"' has no exported member 'Icon'

### ISSUE THREAD

**Issue by Linkontoask** [vueComponent/ant-design-vue#2994]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
"ant-design-vue": "^2.0.0-beta.10"

### Reproduction link
[https://antdv.com/components/icon-cn/#%E4%BD%BF%E7%94%A8-iconfont.cn](https://antdv.com/components/icon-cn/#%E4%BD%BF%E7%94%A8-iconfont.cn)

### Steps to reproduce
import { Icon } from 'ant-design-vue'

### What is expected?
Normal

### What is actually happening?

```
Module '"../../../../node_modules/ant-design-vue/types"' has no exported member 'Icon'. Did you mean to use 'import Icon from "../../../../node_modules/ant-design-vue/types"' instead?
```

**Comment by John60676** [comment]
2.x 不再内置 Icon 组件，请使用 @ant-design/icons-vue
https://2x.antdv.com/components/icon-cn/#API
