### ISSUE TITLE
icon can not use in vite

### ISSUE THREAD

**Issue by yexiaodong** [vueComponent/ant-design-vue#3000]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vite:1.0.0-rc.4 ,vue:3.0.1

### Reproduction link
[https://2x.antdv.com/components/icon-cn/#components-icon-demo-basic](https://2x.antdv.com/components/icon-cn/#components-icon-demo-basic)

### Steps to reproduce
import {
UserOutlined
} from '@ant-design/icons-vue';

### What is expected?
can work

### What is actually happening?
white screen  and not error info

**Comment by huang858563** [comment]
All the icons are loaded？

**Comment by yexiaodong** [comment]
it work, 
 optimizeDeps: {
        include: [
            '@ant-design/icons-vue',
        ],
    },

**Comment by cjx913** [comment]
![image](https://user-images.githubusercontent.com/32391362/98441802-9914db00-213b-11eb-9487-5d56ed231d7b.png)
这个问题怎么处理

**Comment by cjx913** [comment]
> ![image](https://user-images.githubusercontent.com/32391362/98441802-9914db00-213b-11eb-9487-5d56ed231d7b.png)
> 这个问题怎么处理

全部图标下载了
![image](https://user-images.githubusercontent.com/32391362/98441826-c5305c00-213b-11eb-95fc-1115c9b708b8.png)

**Comment by willylee007** [comment]
> > ![image](https://user-images.githubusercontent.com/32391362/98441802-9914db00-213b-11eb-9487-5d56ed231d7b.png)
> > 这个问题怎么处理
> 
> 全部图标下载了
> ![image](https://user-images.githubusercontent.com/32391362/98441826-c5305c00-213b-11eb-95fc-1115c9b708b8.png)

vite项目根目录下新建vite.config.js,
`
module.export = {
  optimizeDeps: {
        include: ['@ant-design/colors','@ant-design/icons-vue',],
    },   
}
`

**Comment by cjx913** [comment]
> > > ![image](https://user-images.githubusercontent.com/32391362/98441802-9914db00-213b-11eb-9487-5d56ed231d7b.png)
> > > 这个问题怎么处理
> > 
> > 
> > 全部图标下载了
> > ![image](https://user-images.githubusercontent.com/32391362/98441826-c5305c00-213b-11eb-95fc-1115c9b708b8.png)
> 
> vite项目根目录下新建vite.config.js,
> `module.export = { optimizeDeps: { include: ['@ant-design/colors','@ant-design/icons-vue',], }, }`

多谢，我用export default可以了  module.export =   应该是export default

**Comment by elewen** [comment]
> All the icons are loaded？



> > > ![image](https://user-images.githubusercontent.com/32391362/98441802-9914db00-213b-11eb-9487-5d56ed231d7b.png)
> > > 这个问题怎么处理
> > 
> > 
> > 全部图标下载了
> > ![image](https://user-images.githubusercontent.com/32391362/98441826-c5305c00-213b-11eb-95fc-1115c9b708b8.png)
> 
> vite项目根目录下新建vite.config.js,
> `module.export = { optimizeDeps: { include: ['@ant-design/colors','@ant-design/icons-vue',], }, }`

完美！！！
