### ISSUE TITLE
为啥react modal支持拖动 vue的不行 是咱们vue的开发团队不如react的吗

### ISSUE THREAD

**Issue by Blizzard-liu** [vueComponent/ant-design-vue#3001]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue3

### Reproduction link
[https://2x.antdv.com/components/modal-cn/](https://2x.antdv.com/components/modal-cn/)

### Steps to reproduce
为啥react modal支持拖动 vue的不行 是咱们vue的开发团队不如react的吗

### What is expected?
为啥react modal支持拖动 vue的不行 是咱们vue的开发团队不如react的吗

### What is actually happening?
为啥react modal支持拖动 vue的不行 是咱们vue的开发团队不如react的吗

**Comment by Blizzard-liu** [comment]
老铁们 顶起来

**Comment by xrkffgg** [comment]
react 版本是通过引入 `react-draggable` 插件实现的。

vue 版本也可以通过引入插件来实现。
