### ISSUE TITLE
DatePicker not working when using`v-bind="$props"` to pass props from parent component

### ISSUE THREAD

**Issue by iHearty** [vueComponent/ant-design-vue#3003]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
nodejs v12.16.2, antdv 1.6.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-q2tpq?file=/src/components/MyDatePicker.vue:0-329)

### Steps to reproduce
when remove v-bind="$props", the wrap component is ok

### What is expected?
wrapped DatePicker work correctly

### What is actually happening?
Cannot open picker pane

**Comment by tangjinzhou** [comment]
because $props have open prop.
component is controller by open prop.

**Comment by tangjinzhou** [comment]
or use it like this  https://codesandbox.io/s/vue-antd-template-forked-0npfb?file=/src/App.vue
