### ISSUE TITLE
Table标签在设置了横向滚动后，如果此时没有数据，“暂无数据”提示信息展示在了滚动条的下方

### ISSUE THREAD

**Issue by TY-LIU** [vueComponent/ant-design-vue#3006]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
WIN10 chrome 85.0.4183.121 (正式版本) （64 位）

### Reproduction link
[https://github.com/ant-design/ant-design/issues/10490](https://github.com/ant-design/ant-design/issues/10490)

### Steps to reproduce
Table标签在设置了横向滚动后，如果此时没有数据，“暂无数据”提示信息展示在了滚动条的下方。展示效果不太合理。
[![BSYJMD.png](https://s1.ax1x.com/2020/10/20/BSYJMD.png)](https://imgchr.com/i/BSYJMD)
ant-react  这个问题已经解决，希望vue版本能同步过来

### What is expected?
提示信息展示在滚动条的上方

### What is actually happening?
提示信息展示在了滚动条的下方。展示效果不太合理。

**Comment by anming-john** [comment]
这个库是没人维护了？ 提供都没人理？

**Comment by JokerAn** [comment]
Scrolling horizontally to the far right of the table table will also get stuck
横向滚动到最右侧table表格还会卡死

**Comment by whateveryoudo** [comment]
临时解决办法:  修改ant-table-empty  的overflow-x:hidden 是否可行

**Comment by eyon-org** [comment]
这个问题现在解决了吗
