### ISSUE TITLE
文档图片丢失

### ISSUE THREAD

**Issue by lsky-walt** [vueComponent/ant-design-vue#3008]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
chrome 86

### Reproduction link
[https://antdv.com/docs/vue/download-cn/](https://antdv.com/docs/vue/download-cn/)

### Steps to reproduce
entry https://antdv.com/docs/vue/download-cn/
![image](https://user-images.githubusercontent.com/20224722/96564459-c5d09200-12f5-11eb-93a1-550d55dafa7f.png)

### What is expected?
show image

### What is actually happening?
image 404

**Comment by tangjinzhou** [comment]
已安排
