### ISSUE TITLE
vuecli3  slot-scope写法 eslint不通过

### ISSUE THREAD

**Issue by 724493602** [vueComponent/ant-design-vue#301]
```
  <span slot="action" slot-scope="x, y">
          <a href="javascript:;">Invite 一 {{ y.id }}</a>
   </span>
```
eslint报错:
error: Parsing error: Unexpected token ',' (vue/no-parsing-error)

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/eslint-plugin-vue/issues/722

**Comment by hedanto** [comment]
目前有解决方案？

**Comment by tangjinzhou** [comment]
> ```
> <span slot="action" slot-scope="{x,y}">
>           <a href="javascript:;">Invite 一 {{ y.id }}</a>
>    </span>
> ```
> 
> 好像这么写就不会报错，但是，下面的不认。。

你这么写是不对的

**Comment by tangjinzhou** [comment]
> 目前有解决方案？

@hedanto 关注这个issue，https://github.com/vuejs/eslint-plugin-vue/issues/722  官方已经在解决了，等待发布状态

暂时先把这个lint规则关掉，不影响使用

**Comment by mcdnf** [comment]
> > 目前有解决方案？
> 
> @hedanto 关注这个issue，[vuejs/eslint-plugin-vue#722](https://github.com/vuejs/eslint-plugin-vue/issues/722) 官方已经在解决了，等待发布状态
> 
> 暂时先把这个lint规则关掉，不影响使用

这条规则怎么关闭？ 
![image](https://user-images.githubusercontent.com/12785299/52923215-9966b480-3361-11e9-96f2-9807b0fe3aa1.png)
这样还是会报
![image](https://user-images.githubusercontent.com/12785299/52923237-aedbde80-3361-11e9-9757-dada49b99bef.png)

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/vetur/issues/1117

**Comment by tangjinzhou** [comment]
vuejs/eslint-plugin-vue已经解决，使用vscode的用户依然会有红线报错，那是vetur插件的问题，不影响打包和lint校验，耐心等待插件更新

**Comment by tangjinzhou** [comment]
vscode设置
`"vetur.validation.template": false,`
关掉vetur的lint校验
