### ISSUE TITLE
a-form-item的label如何设置，文字超出后自动换行？

### ISSUE THREAD

**Issue by hegphegp** [vueComponent/ant-design-vue#3012]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-form-item的label如何设置，文字超出后自动换行？

### What does the proposed API look like?
a-form-item的label如何设置，文字超出后自动换行？

**Comment by xiaofuliang** [comment]
同求，Descriptions 描述列表也是一样，文字超出格式都错乱了，不会自动换行

**Comment by tangjinzhou** [comment]
覆盖 css 即可
