### ISSUE TITLE
select选择器在多选且选项项目多到产生动作条，将滚动条滚动任意距离会自动回到顶部

### ISSUE THREAD

**Issue by apple006** [vueComponent/ant-design-vue#3014]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
vue: 2.5.22 google浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-18dk0?file=/src/App.vue)

### Steps to reproduce
下拉框多选会自动回到顶部

### What is expected?
下拉列表不自动滚动到顶部

### What is actually happening?
下拉列表会滚动到顶部

---
在Google浏览器有问题

**Comment by tangjinzhou** [comment]
1.6.5 没能复现

**Comment by luotingv1** [comment]
我也遇到了 你楼主解决了

**Comment by luotingv1** [comment]
> 1.6.5 没能复现
 <a-select
      style="width: 100%"
      placeholder="Tags Mode"
  
    >
        <a-select-option :value="null">请选择</a-select-option>
      <a-select-option v-for="i in 25" :key="(i + 9).toString(36) + i">{{
        (i + 9).toString(36) + i
      }}</a-select-option>
    </a-select>
