### ISSUE TITLE
Alert组件的X显出原形了

### ISSUE THREAD

**Issue by DiamondBug** [vueComponent/ant-design-vue#3016]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

### Reproduction link
[https://www.antdv.com/components/alert-cn/](https://www.antdv.com/components/alert-cn/)

### Steps to reproduce
打开官网就行了，没步骤，环境中的Chrome，打开官网的Alert组件，X变成了最原始的IE样式

### What is expected?
x

### What is actually happening?
x

**Comment by DiamondBug** [comment]
![Snipaste](https://user-images.githubusercontent.com/26474155/96683918-5fa74600-13ad-11eb-8725-f109e99feb74.png)
Sorry, I miss the screenshot.

**Comment by tangjinzhou** [comment]
样式没加载全吧  刷新试试

**Comment by DiamondBug** [comment]
肯定不是刷新问题啦，我又不是初学者。
顺便看了一眼Network，你们有两个请求无响应。
https://cdn.carbonads.com/carbon.js?serve=CK7DL2JW&placement=antdvcom
https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
这两个请求无响应，closed吧，我纯粹提醒一下你们而已。
