### ISSUE TITLE
tsx a-table scopedSlots: { customRender: 'action'} 无效

### ISSUE THREAD

**Issue by wj5576081** [vueComponent/ant-design-vue#302]
### tableColumns: any[] = [
      {title: '用户名称', dataIndex: 'name', align: 'center'},
      {title: '邮箱', dataIndex: 'email', align: 'center'},
      {title: '真实姓名', dataIndex: 'nick', align: 'center'},
      {title: '操作', align: 'center', scopedSlots: { customRender: 'action'}}
    ];
### render(h: CreateElement) {
      return(
        <div class="user-content">
         <a-table bordered  loading={this.loading}  columns={this.tableColumns} dataSource={this.tableData}>
            <a-button  slot="action" slot-scope="text, record">编辑</a-button>
          </a-table>
      </div>
      )
    }

**Comment by tangjinzhou** [comment]
JSX就不要用slot-scope了  直接function
`{title: '操作', align: 'center', customRender: (text, record)=><a-button />}`
![image](https://user-images.githubusercontent.com/6937879/49857233-01ae8c80-fe2d-11e8-894b-eec7b18afa6d.png)

**Comment by wj5576081** [comment]
@tangjinzhou 
直接function就报错了，[Vue warn]: Error in render: "TypeError: h is not a function"
###  {title: '操作', align: 'center', customRender: (text, record) => <a-button>编辑</a-button>}

**Comment by wj5576081** [comment]
已解决
`tableColumns: any[] = [
      {title: '用户名称', dataIndex: 'name', align: 'center'},
      {title: '邮箱', dataIndex: 'email', align: 'center'},
      {title: '真实姓名', dataIndex: 'nick', align: 'center'},
      {title: '操作', align: 'center', scopedSlots: { customRender: 'action' }}
    ];
`
`  <a-table
            bordered
            rowKey={record => record.uid}
            loading={this.loading}
            pagination={{...this.pagination}}
            columns={this.tableColumns}
            dataSource={this.tableData}
            scopedSlots={{action: props => <a-button>编辑</a-button>}}>
          </a-table>`

**Comment by tangjinzhou** [comment]
那你添加个  const h = this.$createElement
如果你的代码在methods, render等中，jsx插件默认会添加这行代码

**Comment by SongJuXin** [comment]
> @tangjinzhou 这种方案也可以，谢谢，已解决
> 
> ### tableColumns: any[] = [
> ```
>   {title: '用户名称', dataIndex: 'name', align: 'center'},
>   {title: '邮箱', dataIndex: 'email', align: 'center'},
>   {title: '真实姓名', dataIndex: 'nick', align: 'center'},
>   {title: '操作', align: 'center', customRender: (text, record) => {
>     const h: any = this.$createElement;
>     return <a-button>编辑</a-button>;
>     }}
> ];
> ```

`const h= this.$createElement;`这种方式，如何绑定事件呢。

**Comment by mseaspring** [comment]
我用{title: '操作', align: 'center', customRender: (text, record) => {
    const h: any = this.$createElement;
    return <a-button>编辑</a-button>;
    }} 这种方式怎么报错那？

**Comment by nongzhenli** [comment]
> @tangjinzhou 这种方案也可以，谢谢，已解决
> 
> ### tableColumns: any[] = [
> ```
>   {title: '用户名称', dataIndex: 'name', align: 'center'},
>   {title: '邮箱', dataIndex: 'email', align: 'center'},
>   {title: '真实姓名', dataIndex: 'nick', align: 'center'},
>   {title: '操作', align: 'center', customRender: (text, record) => {
>     const h: any = this.$createElement;
>     return <a-button>编辑</a-button>;
>     }}
> ];
> ```

你好，请教下！这里的 `const h ... `貌似没有被调用到呀，起到什么作用呢？

**Comment by bhabgs** [comment]
> JSX就不要用slot-scope了 直接function
> `{title: '操作', align: 'center', customRender: (text, record)=><a-button />}`
> ![image](https://user-images.githubusercontent.com/6937879/49857233-01ae8c80-fe2d-11e8-894b-eec7b18afa6d.png)

我在使用`customRender`时，提示我 `creteElement undefined`; 即使加上 `const h: any = this.$createElement;` 也是错误的。带`customRender` 有并且需要返回JSX.Element 格式的`customRender` 需要使用类上的方法进行绑定。
``` ts
private columns(): any[] {
        [
          ...,
          {
             title: '***',
             dataIndex: 'alert_time',
             customRender: (text: string, record: any) => {
                return <a>{text}</a>;
             },
           }
        ]
      },
```

**Comment by beijinaqie** [comment]
> 我用{title: '操作', align: 'center', customRender: (text, record) => {
> const h: any = this.$createElement;
> return 编辑;
> }} 这种方式怎么报错那？

同样报错，貌似不支持tsx语法？有没有解决方案或者更新版本中解决了这个问题

**Comment by SongJuXin** [comment]
> > 我用{title: '操作', align: 'center', customRender: (text, record) => {
> > const h: any = this.$createElement;
> > return 编辑;
> > }} 这种方式怎么报错那？
> 
> 同样报错，貌似不支持tsx语法？有没有解决方案或者更新版本中解决了这个问题

如果仅仅是不支持ts，看懂这段代码的意思，改成js的不就行了。
即` const h: any = this.$createElement;`改成`cosnt h=this.$createElement`。

**Comment by beijinaqie** [comment]
> > > 我用{title: '操作', align: 'center', customRender: (text, record) => {
> > > const h: any = this.$createElement;
> > > return 编辑;
> > > }} 这种方式怎么报错那？
> > 
> > 
> > 同样报错，貌似不支持tsx语法？有没有解决方案或者更新版本中解决了这个问题
> 
> 如果仅仅是不支持ts，看懂这段代码的意思，改成js的不就行了。
> 即` const h: any = this.$createElement;`改成`cosnt h=this.$createElement`。

不是ts的问题，而是就算加上这个cosnt h=this.$createElement，依然会报错$createElement undefined

**Comment by luckyxutao** [comment]
customRender里jsx 怎么能得到 vue实例呢？
