### ISSUE TITLE
notification组件使用报错

### ISSUE THREAD

**Issue by LiuZeng520** [vueComponent/ant-design-vue#3020]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
win10，谷歌浏览器85.0.4181.9（正式版本），@vue/cli 4.5.3

### Reproduction link
[https://www.antdv.com/components/notification-cn/](https://www.antdv.com/components/notification-cn/)

### Steps to reproduce
<template>
<div>
<a-button @click="() => openNotificationWithIcon('success')">
Success
</a-button>
<a-button @click="() => openNotificationWithIcon('info')">
Info
</a-button>
<a-button @click="() => openNotificationWithIcon('warning')">
Warning
</a-button>
<a-button @click="() => openNotificationWithIcon('error')">
Error
</a-button>
</div>
</template>
<script>
export default {
methods: {
openNotificationWithIcon(type) {
this.$notification[type]({
message: 'Notification Title',
description:
'This is the content of the notification. This is the content of the notification. This is the content of the notification.',
});
},
},
};
</script>

### What is expected?
点击"Info"按钮，弹出一个通知提醒框

### What is actually happening?
console报错
TypeError: Cannot read property 'info' of undefined

**Comment by LiuZeng520** [comment]
**Steps to reproduce**
`<template>`
`  <div>`
`    <a-button @click="() => openNotificationWithIcon('success')">`
`      Success`
`    </a-button>`
`    <a-button @click="() => openNotificationWithIcon('info')">`
`      Info`
`    </a-button>`
`    <a-button @click="() => openNotificationWithIcon('warning')">`
`      Warning`
`    </a-button>`
`    <a-button @click="() => openNotificationWithIcon('error')">`
`      Error`
`    </a-button>`
`  </div>`
`</template>`
`<script>`
`export default {`
`  methods: {`
`    openNotificationWithIcon(type) {`
`      this.$notification[type]({`
`        message: 'Notification Title',`
`        description:`
`          'This is the content of the notification. This is the content of the notification. This is the content of the notification.',`
`      });`
`    },`
`  },`
`};`
`</script>`


代码如上，会生成Success Info Warning Error 四个按钮，我期望点击"Info"时，出现：
![image](https://user-images.githubusercontent.com/43592564/96841672-a7e26900-147e-11eb-85b4-63ac2dba496f.png)
然而，却出现：
![image](https://user-images.githubusercontent.com/43592564/96841766-c47ea100-147e-11eb-8aa9-5af5678a9b77.png)

**Comment by John60676** [comment]
用你提供的代码无法重现你遇到的问题
https://codesandbox.io/s/vue-antd-template-forked-fgy9l?file=/src/App.vue

**Comment by LiuZeng520** [comment]
明白了，谢谢你，你是这样子做的：
`import Antd from "ant-design-vue";`
我的问题已解决，我现在是这样子做的：
`import notification from 'ant-design-vue';`
`Vue.prototype.$notification = notification`
参考 https://element.eleme.cn/#/zh-CN/component/quickstart
