### ISSUE TITLE
a-tabs Tinymce富文本编辑器 切换tab后富文本编辑器不可编辑且内容也不显示

### ISSUE THREAD

**Issue by ppnoHZ** [vueComponent/ant-design-vue#3025]
之前有人提过这问题，但是由于格式不对，没有解决。
        
        
### Version
1.4.12

### Environment
window,chrome 86.0.4240.75,vue2.5.17,ant-desigin-vue1.4.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-fqp93)

### Steps to reproduce
集成富文本编辑器 tinymce,再第一个tab里展示，并输入些东西，然后切换到第二个tab，富文本编辑器里的内容没有了，且无法获取焦点.
猜测原因是因为这个编辑使用了一个 iframe.在切换回第一个tab的时候，没有重新渲染 iframe里的东西。编辑器的关键代码就在这个iframe里。导致数据丢失和无法获取焦点。例子见连接：https://codesandbox.io/s/vue-antd-template-forked-fqp93

### What is expected?
正确展示之前填写的内容并且可以编辑

### What is actually happening?
无法正确展示之前输入的结果

**Comment by ppnoHZ** [comment]
切换tab前的浏览器里的html
![image](https://user-images.githubusercontent.com/8656782/96859950-b8054300-1494-11eb-848a-39f16ad7e522.png)
切换回tab之后浏览器的html
![image](https://user-images.githubusercontent.com/8656782/96860142-fa2e8480-1494-11eb-92b3-0c039ce0adbb.png)

**Comment by chenbingchang** [comment]
我也遇到了同样的问题！

**Comment by ppnoHZ** [comment]
@chenbingchang 

> 原因：组件没有重新初始化导致的，参考：https://www.coder.work/article/941688
> 解决方法：tinymc-vue的初始化方法我没有找到，所以利用vue组件的key机制来使组件重新初始化。每次进入路由时改变tinymc-vue组件的key，我用的是当前的时间戳字符串

我用的 v-show 在切换的时候隐藏，切换回来在显示，这样就不会有问题。如果路由跳转了，在我的应用场景里是可以正常显示的。

**Comment by tangjinzhou** [comment]
这个和 tabs 组件没什么关系  

vue在iframe里 本身也有一些问题  https://github.com/vuejs/vue/issues/9473

**Comment by triangle959** [comment]
遇到类似的问题，切回第一个tab时看到iframe的位置和实际tinymce不一样
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/34617914/185307392-e060360c-ca8d-41d3-bebc-25cb0ada4df7.png">
