### ISSUE TITLE
使用vite时，日期选择框汉化失败

### ISSUE THREAD

**Issue by yexiaodong** [vueComponent/ant-design-vue#3029]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vite:1.0.0-rc.4 ,vue:3.0.1

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn/](https://2x.antdv.com/components/date-picker-cn/)

### Steps to reproduce
import moment from "moment"
import "moment/locale/zh-cn"

### What is expected?
正常汉化

### What is actually happening?
错误提示： [Vue warn]: TypeError: Cannot read property 'moment' of undefined

**Comment by brmyfun** [comment]
我这边是这样的
`<template>
  
  <a-config-provider :locale="locale">
    <router-view />
  </a-config-provider>
</template>
<script>
import locale from "ant-design-vue/es/locale/zh_CN";
import moment from "moment";
import "moment/locale/zh-cn";
moment.locale("zh-cn");
export default {
  name: "App",
  data() {
    return {
      locale,
      moment,
    };
  },
};
</script>
`

版本是`2.0.0-beta.13`
报错也是`[Vue warn]: TypeError: Cannot read property 'moment' of undefined`

**Comment by chaorenluo** [comment]
我这边也是月份无法汉化

**Comment by chaorenluo** [comment]
找到解决方案了
import moment from 'moment';

const default_zh = (moment: any) => {
  const zhCn: any = moment.defineLocale('zh-cn', {
    months: '一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月'.split('_'),
    monthsShort: '1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月'.split('_'),
    weekdays: '星期日_星期一_星期二_星期三_星期四_星期五_星期六'.split('_'),
    weekdaysShort: '周日_周一_周二_周三_周四_周五_周六'.split('_'),
    weekdaysMin: '日_一_二_三_四_五_六'.split('_'),
    longDateFormat: {
      LT: 'HH:mm',
      LTS: 'HH:mm:ss',
      L: 'YYYY/MM/DD',
      LL: 'YYYY年M月D日',
      LLL: 'YYYY年M月D日Ah点mm分',
      LLLL: 'YYYY年M月D日ddddAh点mm分',
      l: 'YYYY/M/D',
      ll: 'YYYY年M月D日',
      lll: 'YYYY年M月D日 HH:mm',
      llll: 'YYYY年M月D日dddd HH:mm',
    },
    meridiemParse: /凌晨|早上|上午|中午|下午|晚上/,
    meridiemHour: function (hour: number, meridiem: number) {
      if (hour === 12) {
        hour = 0;
      }
      // @ts-ignore
      if (meridiem === '凌晨' || meridiem === '早上' || meridiem === '上午') {
        return hour;
      } else {
        // @ts-ignore
        if (meridiem === '下午' || meridiem === '晚上') {
          return hour + 12;
        } else {
          // '中午'
          return hour >= 11 ? hour : hour + 12;
        }
      }
    },
    meridiem: function (hour: number, minute: number) {
      const hm = hour * 100 + minute;
      if (hm < 600) {
        return '凌晨';
      } else if (hm < 900) {
        return '早上';
      } else if (hm < 1130) {
        return '上午';
      } else if (hm < 1230) {
        return '中午';
      } else if (hm < 1800) {
        return '下午';
      } else {
        return '晚上';
      }
    },
    calendar: {
      sameDay: '[今天]LT',
      nextDay: '[明天]LT',
      // @ts-ignore
      nextWeek: function (now) {
        // @ts-ignore
        if (now.week() !== this.week()) {
          return '[下]dddLT';
        } else {
          return '[本]dddLT';
        }
      },
      lastDay: '[昨天]LT',
      // @ts-ignore
      lastWeek: function (now) {
        // @ts-ignore
        if (this.week() !== now.week()) {
          return '[上]dddLT';
        } else {
          return '[本]dddLT';
        }
      },
      sameElse: 'L',
    },
    dayOfMonthOrdinalParse: /\d{1,2}(日|月|周)/,
    // @ts-ignore
    ordinal: function (number, period) {
      switch (period) {
        case 'd':
        case 'D':
        case 'DDD':
          return number + '日';
        case 'M':
          return number + '月';
        case 'w':
        case 'W':
          return number + '周';
        default:
          return number;
      }
    },
    relativeTime: {
      future: '%s后',
      past: '%s前',
      s: '几秒',
      ss: '%d 秒',
      m: '1 分钟',
      mm: '%d 分钟',
      h: '1 小时',
      hh: '%d 小时',
      d: '1 天',
      dd: '%d 天',
      w: '1 周',
      ww: '%d 周',
      M: '1 个月',
      MM: '%d 个月',
      y: '1 年',
      yy: '%d 年',
    },
    week: {
      // GB/T 7408-1994《数据元和交换格式·信息交换·日期和时间表示法》与ISO 8601:1988等效
      dow: 1, // Monday is the first day of the week.
      doy: 4, // The week that contains Jan 4th is the first week of the year.
    },
  } as any);
  return zhCn;
};

export function setupMonent() {
  default_zh(moment);
}

**Comment by chaorenluo** [comment]
初始化一下moment 成中文就可以了

**Comment by Ttou** [comment]
@brmyfun 导入 dist 目录下的语言文件试试
`import 'moment/dist/locale/zh-cn'`

**Comment by elewen** [comment]
> @brmyfun 导入 dist 目录下的语言文件试试
> `import 'moment/dist/locale/zh-cn'`

> import 'moment/src/locale/zh-cn';

**Comment by any86** [comment]
确实可以了
