### ISSUE TITLE
menu菜单组件递归后选中子菜单，父级菜单不选中(After the menu menu component recursively selects the submenu, the parent menu is not selected)

### ISSUE THREAD

**Issue by yunlongduan** [vueComponent/ant-design-vue#3032]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
win10 1909、Microsoft Edge( 86.0.622.48 (64 位))、 "vue": "^3.0.0",

### Reproduction link
[https://github.com/yunlongduan/test](https://github.com/yunlongduan/test)

### Steps to reproduce
递归菜单(Recursive menu)

### What is expected?
子菜单选中父级菜单应该选中，像官网那样(Child menu selected parent menu should be selected, like the official website)

### What is actually happening?
递归菜单设置子菜单选中，但是父菜单不选中(Recursive menu Settings submenu selected, but the parent menu is not selected)

**Comment by John60676** [comment]
既然使用了 selectedKeys 就要自己管理 selectedKeys 的值，如果想要菜单控制，请使用 v-model 传递 selectedKeys

**Comment by yunlongduan** [comment]
多谢回复，遗憾的是二着都无法解决现在的问题

**Comment by John60676** [comment]
把 VMenuItem 改成渲染函数，不要做成组件

**Comment by yunlongduan** [comment]
方便问一下这样做的目的或原因吗

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/96965573-f8b99680-153e-11eb-8510-fde5580a1b03.png)

sub-menu
![image](https://user-images.githubusercontent.com/5404542/96965600-01aa6800-153f-11eb-8e32-1e5c8bd86e44.png)

**Comment by yunlongduan** [comment]
多谢大佬们，这样可以有效解决目前问题，那么bug单我先关闭了

**Comment by yunlongduan** [comment]
刚刚又尝试了一下下面的方法，在菜单大于2级时依旧会出现这种情况，我有时间在尝试一下渲染函数的方式，菜单这里还是存在问题的，我觉得

**Comment by John60676** [comment]
这个问题能用渲染函数解决，先关闭了

**Comment by sendya** [comment]
https://codesandbox.io/s/busy-gould-0ohwo?file=/src/App.vue
实测无任何问题

![image](https://user-images.githubusercontent.com/5404542/97673428-bb1cb680-1ac6-11eb-8547-9e9d347e1ef7.png)

**Comment by yunlongduan** [comment]
@sendya 菜单主题采用默认问题依在
