### ISSUE TITLE
提3点建议

### ISSUE THREAD

**Issue by Layczm** [vueComponent/ant-design-vue#3033]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
1. 尽量接纳社区，开放文档，现在看到只有2-3个人维护。element-plus现在依靠社区发展很快，且质量挺好(重点)，
2. 这个时间点最好能接纳社区建议，看到issue目前好像都没人来修复,不然有很大一部分人会开始回流到element-plus。这阶段是选择vue3ui阶段的时间点。
3. 只是建议，没别的意思。只是只希望ant-design-vue发展得更好。

### What is expected?
rt

### What is actually happening?
rt

**Comment by tangjinzhou** [comment]
感谢建议   我们会考虑
