### ISSUE TITLE
jsx写的组件报错ReferenceError: h is not defined

### ISSUE THREAD

**Issue by alz8888** [vueComponent/ant-design-vue#3035]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
vuecli及插件都是最新版本

### Reproduction link
无

### Steps to reproduce
通过jsx写组件，render方法若不加h参数，就会报错，但我方法体内根本不用h。前几天是正常的，最近不知道什么原因就开始报错。我去看了官方的pro体验版，也没有写h，但不报错。求助！

### What is expected?
render方法不要强制h参数

### What is actually happening?
render方法不写h参数报错，写了h参数后，部分同事编译又报错。

---
Any additional comments? (optional)

**Comment by alz8888** [comment]
最郁闷的是前几天还完全正常，后来更新了插件版本（具体哪个插件导致也不清楚，目前我的所有插件都是最新版本）就这样开始报错了。

**Comment by uinio** [comment]
https://github.com/vuejs/jsx-next/issues/5
