### ISSUE TITLE
Ant Design Vue会污染Vue原生fade动画的bug

### ISSUE THREAD

**Issue by xiaoyaoseng** [vueComponent/ant-design-vue#3040]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Vue: 2.5.2, Chrome, Win10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/long-field-o542q?file=/src/App.vue)

### Steps to reproduce
初始化一个全新AntDV项目，当在页面上加上transition的fade时，因为调用了antdv库，动画失效，必须加上以下css才可以。直接参考重现链接里的内容
.fade-enter.fade-enter-active,
.fade-appear.fade-appear-active {
-webkit-animation-name: none;
animation-name: none;
}

.fade-leave.fade-leave-active {
-webkit-animation-name: none;
animation-name: none;
}

### What is expected?
正确使用vue的原生动画

### What is actually happening?
无法正确使用vue的原生动画

**Comment by shanyuhai123** [comment]
**解决方案只需要你将 `fade` 修改为 `fade1` 或其他名称。**
感觉这也算不上污染原生，不过个人同样认为 `antdv` 没有加前缀 `ant` 是不太好，容易和其他 CSS 动画库造成冲突。
估计 `antdv` 在 v1 版本是不会修改这个问题了，毕竟说不定有些人利用了这个实现了某些功能。
