### ISSUE TITLE
form表单labelCol属性的文档没写全

### ISSUE THREAD

**Issue by vhkdiy** [vueComponent/ant-design-vue#3042]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
windows10、chrome  86.0.4240.111、vue 2.6.11

### Reproduction link
[https://www.antdv.com/components/form-cn/](https://www.antdv.com/components/form-cn/)

### Steps to reproduce
1. 文档里 form 表单的 labelCol 属性只写了 {span: 3, offset: 12} 的用法，和参考 Grid Col 的属性参数，并没有说可以设置 style 属性和用法。
```
:labelCol="{ style: 'width: 100px' }"
```

### What is expected?
文档明确告知可以使用哪些属性

### What is actually happening?
form表单labelCol属性的文档没写全

---
最终在/form/FormItem.jsx 源码里找到了 labelCol 属性的接收参数，才知道正确用法。
```
const {
class: labelColClass,
style: labelColStyle,
id: labelColId,
on,
...restProps
} = mergedLabelCol;
```

**Comment by deajax** [comment]
我晕，还有这种写法？感谢感谢，受教了。

**Comment by uniquejava** [comment]
学习了， 我按照文档中的 指定span特不方便， 我想给label固定的宽度值。 这下学会了。。。学会了。。
