### ISSUE TITLE
Collapse折叠面板如何禁止slot head 的点击事件

### ISSUE THREAD

**Issue by kagaricyan** [vueComponent/ant-design-vue#3051]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前组件点击整个head打开/关闭面板。我想要仅点击左侧图标控制打开/关闭. 我的head部分有自定义文字，并且用了<a-popover trigger="click">，这样点击的时候我只想展示popover提示，并不想打开面板

### What does the proposed API look like?
提供一个属性判断是否仅点击图标控制打开关闭面板

**Comment by sendya** [comment]
不用 v-model，直接 activeKey + change 事件，自行控制即可，不想被打开，就不更新 activeKey。

**Comment by kagaricyan** [comment]
> 不用 v-model，直接 activeKey + change 事件，自行控制即可，不想被打开，就不更新 activeKey。

下面代码无效，点击仍然会打开key为1的面板
```
<a-collapse :active-key="activeKey" @change="activeKey='-1'">
    <a-collapse-panel key="1">
        ...
    </a-collapse-panel>
</a-collapse>
```

**Comment by ibwei** [comment]
在事件中加入一下代码，即可不触发默认展开/折叠面板的行为
``` 
e.preventDefault()
e.stopPropagation()
return false
```

**Comment by kagaricyan** [comment]
> 在事件中加入一下代码，即可不触发默认展开/折叠面板的行为
> 
> ```
> e.preventDefault()
> e.stopPropagation()
> return false
> ```

多谢
