### ISSUE TITLE
slot="tabBarExtraContent"报错

### ISSUE THREAD

**Issue by wangyl96** [vueComponent/ant-design-vue#3055]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue3

### Reproduction link
[https://www.antdv.com/components/tabs-cn/](https://www.antdv.com/components/tabs-cn/)

### Steps to reproduce
使用该功能 slot报错
<a-button slot="tabBarExtraContent">       Extra Action     </a-button>

### What is expected?
如何解决

### What is actually happening?
报错

**Comment by tangjinzhou** [comment]
请严格按照 issuehelped 提供复现示例
