### ISSUE TITLE
LocaleProvider 国际化引入名称和文档不一样，且包裹路由后， DatePicker并未汉化

### ISSUE THREAD

**Issue by lostimever** [vueComponent/ant-design-vue#3056]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
Vue3.0 typescript

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-fpgkl)

### Steps to reproduce
在App.vue 中使用 <a-config-provider></a-config-provider> 包裹路由<router-view />，DatePicker并未汉化

### What is expected?
被包裹的组件汉化

### What is actually happening?
被包裹的组件并未被汉化，
且提示Could not find a declaration file for module 'ant-design-vue/es/date-picker/locale/zh_CN'. 'E:/svn/***/app/node_modules/ant-design-vue/es/date-picker/locale/zh_CN.js' implicitly has an 'any' type.

```
<template>
  <a-config-provider :locale="locale">
    <router-view />
  </a-config-provider>
</template>
```
```
<script lang="ts">
  import { Vue } from 'vue-class-component'
  import zhCN from 'ant-design-vue/es/date-picker/locale/zh_CN'
  export default class App extends Vue {
    locale = zhCN
  }
</script>
```

**Comment by sendya** [comment]
不是 'ant-design-vue/es/date-picker/locale/zh_CN' 这个路径，请重新确认一下

**Comment by tangjinzhou** [comment]
add 
```js
import 'moment/locale/zh-cn';

moment.locale('zh-cn');
```

**Comment by codesyofo** [comment]
> 不是 'ant-design-vue/es/date-picker/locale/zh_CN' 这个路径，请重新确认一下
> 
> https://antdv.com/components/config-provider-cn/#components-config-provider-demo-locale



> 不是 'ant-design-vue/es/date-picker/locale/zh_CN' 这个路径，请重新确认一下
> 
> https://antdv.com/components/config-provider-cn/#components-config-provider-demo-locale

你给的这个链接，选择示例的中文选项后，那几个日期表单组件也还有英文（周一到周日，月份没有国际化），和日历组件的效果不一样

**Comment by lostimever** [comment]
> > 不是 'ant-design-vue/es/date-picker/locale/zh_CN' 这个路径，请重新确认一下
> > https://antdv.com/components/config-provider-cn/#components-config-provider-demo-locale
> 
> 你给的这个链接，选择示例的中文选项后，那几个日期表单组件也还有英文（周一到周日，月份没有国际化），和日历组件的效果不一样


改成这样就可以了

```html
<template>
  <a-config-provider :locale="locale">
    <router-view />
  </a-config-provider>
</template>
```
```typescript
import { Options, Vue } from 'vue-class-component'
import zhCN from 'ant-design-vue/es/locale/zh_CN'
import moment from 'moment'
moment.locale('zh-cn')

/**@Options({
  provide() {
    return {
      locale: zhCN,
    }
  },
*/
})
export default class App extends Vue {
  public locale = zhCN
}
```
