### ISSUE TITLE
dropdown菜单增加最大高度和滚动条

### ISSUE THREAD

**Issue by lchrennew** [vueComponent/ant-design-vue#3057]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
下拉菜单中的项过多，一屏难以完全展示，希望能设置最大高度，并自动展示滚动条

### What does the proposed API look like?
```html
<a-dropdown>
<div class="handler">Hover me</div>
<template #overlay>
<a-menu :max-height="200">...</a-menu>
</template>
</a-dropdown>
```

**Comment by wwhyes** [comment]
@lchrennew 我发不了issue，关于menu有一个问题在你这提一下！<a-menu-divider>的样式丢失了
![QQ图片20201104154042](https://user-images.githubusercontent.com/8612580/98082708-2645fe80-1eb4-11eb-86d5-c18de3ed4c3b.png)

**Comment by lchrennew** [comment]
多谢wwhyes！


图1

图2

我用Dropdown做了一个下拉导航（图1），因为内容太多（图2），导致无法全部显示。
希望此处能有滚动条，或者更牛的解决方案！

**Comment by lchrennew** [comment]
> @lchrennew 我发不了issue，关于menu有一个问题在你这提一下！`<a-menu-divider>` 的样式丢失了
> ![QQ图片20201104154042](https://user-images.githubusercontent.com/8612580/98082708-2645fe80-1eb4-11eb-86d5-c18de3ed4c3b.png)

你可以从这里发：
https://vuecomponent.github.io/issue-helper/?lang=zh

**Comment by lchrennew** [comment]
这个能解决吗？
