### ISSUE TITLE
Open Modal, extra style element won't be removed.

### ISSUE THREAD

**Issue by bq-hentai** [vueComponent/ant-design-vue#306]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.10

### Environment
Win7/vue 2.5

### Reproduction link
[https://tangjinzhou.gitee.io/ant-design-vue/components/modal/](https://tangjinzhou.gitee.io/ant-design-vue/components/modal/)

### Steps to reproduce
open modal and repeat, then inspect dom.

### What is expected?
extra style will be removed.

### What is actually happening?
not remove.

**Comment by tangjinzhou** [comment]
There should only one style that could not be removed.
