### ISSUE TITLE
Upload组件 change事件，永远只返回一种状态Uploading,一直无法获取done成功回调。

### ISSUE THREAD

**Issue by xiaomiaogu** [vueComponent/ant-design-vue#3061]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
win10,谷歌浏览器最新版、vue3.0

### Reproduction link
[http://www.xx.com](http://www.xx.com)

### Steps to reproduce
Upload组件 change事件，永远只返回一种状态Uploading,一直无法获取done成功回调。

### What is expected?
Upload组件 change事件，永远只返回一种状态Uploading,一直无法获取done成功回调。

### What is actually happening?
Upload组件 change事件，永远只返回一种状态Uploading,一直无法获取done成功回调。

**Comment by hzyyy** [comment]
this.fileList = [ ...info.fileList ]

**Comment by TheNovemberRain** [comment]
要真正理解官网例子里所说的“**完全控制的上传列表**”是什么意思。
看源码可知，在upload内部子组件提交start、success、error事件下时，都会更新fileList，然后才向用户的自定义组件提交change事件。
换言之，在接收到**每一个**change事件时，**都必须更新自定义组件的fileList**，否则在除了upload内部start以外的事件，都会因为fileList为空而停止提交change事件。
