### ISSUE TITLE
使用浏览器引入，使用Select组件的popupScroll事件，发现一直没有触发 

### ISSUE THREAD

**Issue by ruanpang** [vueComponent/ant-design-vue#3065]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.0

### Environment
Chrome  86.0.4240.111（正式版本） (x86_64), Vue 2.6.12

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/releases/tag/1.7.0](https://github.com/vueComponent/ant-design-vue/releases/tag/1.7.0)

### Steps to reproduce
https://codepen.io/ruanpang/pen/rNLdePN?editors=1111

### What is expected?
滚动的时候，触发popupScroll方法

### What is actually happening?
滚动的时候没有触发。

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/vue-dash-event

**Comment by ruanpang** [comment]
我在示例中也引入了vue-dash-event，但是依然无效，所以很头大。搜索引擎也没有找到相对应的答案。
![image](https://user-images.githubusercontent.com/19522975/97669331-dbe10e00-1abe-11eb-84b5-578ea52efcb2.png)

**Comment by ruanpang** [comment]
> https://github.com/vueComponent/vue-dash-event



> https://github.com/vueComponent/vue-dash-event



> https://github.com/vueComponent/vue-dash-event

我在示例中也引入了vue-dash-event，但是依然无效，所以很头大。搜索引擎也没有找到相对应的答案。
![image](https://user-images.githubusercontent.com/19522975/97669441-13e85100-1abf-11eb-82af-ea5ff07e3148.png)

**Comment by ruanpang** [comment]
> https://github.com/vueComponent/vue-dash-event

大佬求教啊。我解决不了啊。求指教，求指教，求指教

**Comment by MuYs** [comment]
。。。绑定事件的时候要加括号    @popup-scroll="popupCountryList"    ----->   @popup-scroll="popupCountryList()"

**Comment by MuYs** [comment]
@popup-scroll="popupCountryList"  ---> @popupScroll="popupCountryList"

**Comment by ruanpang** [comment]
浏览器引入的方式使用无效，很蛋疼的啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月25日(星期一) 下午4:19
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"be with you"<656817717@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] 使用浏览器引入，使用Select组件的popupScroll事件，发现一直没有触发  (#3065)





 
@popup-scroll="popupCountryList"  ---&gt; @popupScroll="popupCountryList"
