### ISSUE TITLE
Broken styles after upgrading to beta 11

### ISSUE THREAD

**Issue by Yakoot** [vueComponent/ant-design-vue#3069]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.11

### Environment
OS: Manjaro 20.1.1 Mikah, Vivaldi	3.3.2022.47 (Stable channel) (64-bit), vue 3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-noyce-nwd73)

### Steps to reproduce
just open codesandbox, beta 10 works fine, beta 11 displays all elements without styles

### What is expected?
styles

### What is actually happening?
no styles

**Comment by anncwb** [comment]
The same problem. It can be solved by introducing the less file, the css file does not work

**Comment by Yakoot** [comment]
can you provide me with your setup of less loader? it will help me save my time)

**Comment by anncwb** [comment]
```
// before
import 'ant-design-vue/dist/antd.css'
// after
import 'ant-design-vue/dist/antd.less';
```

**Comment by Yakoot** [comment]
nothing special in vue config? I'm using scss in my project

**Comment by anncwb** [comment]
Sorry, I did not use scss. Should wait for the next version update to resolve

**Comment by Yakoot** [comment]
works fine with
import 'ant-design-vue/dist/antd.less';

**Comment by van-chin** [comment]
npm 上的beta.11 样式问题还没有修复 要一个版本才更新么？
