### ISSUE TITLE
滚动条组件

### ISSUE THREAD

**Issue by x251025116** [vueComponent/ant-design-vue#3071]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有没有一个优化滚动条的组件呢 ？原生的滚动条实在是太难看了，很多项目里面都没有办法用，其他方面我觉得是比element好一些， 只是滚动条方面希望加个组件，谢谢

### What does the proposed API look like?
我希望是有个组件，在这个组件里面写内容，超出了容器大小的话就会出现滚动条，滚动条不要用原生的

**Comment by dcdlove** [comment]
原来有人提在我之前了

**Comment by gameruleCEO** [comment]
滚动条样式可以自定义呀

**Comment by atdow** [comment]
这个问题相当大，如果不能解决，在ui要求高一点的项目中直接放弃这个库。虽然自己使用了第三方的库在原来的组件里面增加了自定义滚动条，但是带来的问题也很大，希望作者可以重视这个问题。
