### ISSUE TITLE
ant-design-vue   TS，封装 antdv 的组件时，继承原组件的 props，无法获得类型提示

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#3072]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.11

### Environment
window 10， chrome,  Vue3.0.2

### Reproduction link
[https://2x.antdv.com](https://2x.antdv.com)

### Steps to reproduce
在 antdv 组件的基础上封装自己的组件

![图片](https://user-images.githubusercontent.com/64787128/97769654-d55aa100-1b67-11eb-9bd2-40e8eb962b4c.png)

### What is expected?
继承组件能获得原组件props的类型提示

### What is actually happening?
继承原组件的props之后无法获得类型提示

**Comment by Amour1688** [comment]
You can try this way temporarily.

```tsx
export default defineComponent({
  mixins: [Button],
  // ...
})
```

**Comment by yangss3** [comment]
> 
> 
> You can try this way temporarily.
> 
> ```tsx
> export default defineComponent({
>   mixins: [Button],
>   // ...
> })
> ```

我又换回JS了，你们继续加油
