### ISSUE TITLE
antv  + TS，单个导入组件，用 app.use 全局注册，提示找不到 install 方法

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#3076]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.11

### Environment
Vue3.0.2

### Reproduction link
[https://2x.antdv.com/](https://2x.antdv.com/)

### Steps to reproduce
按需引入组件，使用 app.use 全局注册

### What is expected?
能正常注册

### What is actually happening?
按需引入组件，使用 app.use 全局注册时，提示找不到 install 方法

![image](https://user-images.githubusercontent.com/64787128/97775756-24232d80-1b9e-11eb-9bd2-19b7751ddb5a.png)

**Comment by wxk6b1203** [comment]
日前能做的是，全局引入，去除babel-plugin-import。等待下一次发版。。。
```ts
import { createApp } from 'vue'
import App from './App.vue'
import store from "@/store/store";
import router from "@/router";
import Antd from 'ant-design-vue'
import i18n from '@/i18n'
import 'ant-design-vue/dist/antd.less'

let app = createApp(App)

app.use(store)
app.use(router)
app.use(Antd)

app.use(i18n)

app.mount('#app')
```
