### ISSUE TITLE
希望有BootBox类似的功能，目前少了Prompt的功能。

### ISSUE THREAD

**Issue by herbert888** [vueComponent/ant-design-vue#3083]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
this.$Prompt，这样一个功能，可以快捷的创建数据，而不需要增加< a-modal />
![image](https://user-images.githubusercontent.com/65747360/97821969-411b4600-1cef-11eb-925b-3dafcc6b8b83.png)

### What does the proposed API look like?
http://bootboxjs.com/documentation.html#bb-dialog
https://element.eleme.cn/#/zh-CN/component/message-box

**Comment by falstack** [comment]
这就没人管就关了？？？

**Comment by sendya** [comment]
https://codesandbox.io/s/friendly-forest-mdnhd?file=/src/App.vue

![image](https://user-images.githubusercontent.com/5404542/114354931-7468d780-9ba1-11eb-99f6-7786f722ad44.png)
