### ISSUE TITLE
Upload 组件中的showUploadList是否可以添加点击选中事件的功能

### ISSUE THREAD

**Issue by fatetoper** [vueComponent/ant-design-vue#3086]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
点击showUploadList的图片可以选中（添加个边框颜色），再次点击选中取消选中。点击同时触发点击事件，把选中的item数据对象传到外部。

### What does the proposed API look like?
@select="handleSelect"

**Comment by tangjinzhou** [comment]
添加 itemRender 来自定义列表更加通用
