### ISSUE TITLE
日期选择器默认格式问题

### ISSUE THREAD

**Issue by tracy2zhang** [vueComponent/ant-design-vue#3091]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
vue3.0.2

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn/](https://2x.antdv.com/components/date-picker-cn/)

### Steps to reproduce
使用datepicker或rangepicker组件，不传format属性，使用默认的format

### What is expected?
显示格式为YYYY-MM-DD

### What is actually happening?
显示格式为YYYY-Wo

---
1. 可以通过手动设置format为YYYY-MM-DD是没问题的，但是最好还是默认YYYY-MM-DD这种常用格式，而且这样也跟文档一致
2. 此问题好像是2.0.0-beta11开始有的

**Comment by bowencool** [comment]
官方文档就复现了
![image](https://user-images.githubusercontent.com/20217146/97962084-698a6980-1def-11eb-8c6b-4432e904bb11.png)
