### ISSUE TITLE
所有列宽度固定，滚动列表头内容折行时，固定列表头高度不对齐，产生错位

### ISSUE THREAD

**Issue by BettYuan** [vueComponent/ant-design-vue#3092]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
Chrome 86.0.4240.111（正式版本） (x86_64)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-fqw9w?file=/src/App.vue)

### Steps to reproduce
1、滚动列不折行，展示没问题
2、滚动列折行，展示错位

### What is expected?
希望固定列能和滚动宽度自适应

### What is actually happening?
展示错位

**Comment by BettYuan** [comment]
固定表头没有children的时候没有问题，但是嵌套子表头的情况我们使用情况也蛮多的

**Comment by vzhougm** [comment]
有个类似的问题

![table 错位](https://img-blog.csdnimg.cn/20201109165344642.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L0dNaW5nWmhvdQ==,size_16,color_FFFFFF,t_70#pic_center)
