### ISSUE TITLE
菜单组件和下拉组件展开收起效果有些僵硬，希望可以改善一下动画效果

### ISSUE THREAD

**Issue by qq2316693281** [vueComponent/ant-design-vue#3095]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
所有

### Reproduction link
[https://2x.antdv.com/docs/vue/changelog-cn/](https://2x.antdv.com/docs/vue/changelog-cn/)

### Steps to reproduce
https://2x.antdv.com/docs/vue/changelog-cn/

### What is expected?
可以不那么僵硬

### What is actually happening?
非常不灵敏

**Comment by tangjinzhou** [comment]
2.0 版本体验还行啊

**Comment by hinadong** [comment]
@tangjinzhou 不如Element UI的流畅，Ant Design React 官方也是不太流畅，尤其是当页面有大量渲染的时候卡顿，对比一下Element UI 和Ant Design React 就明显可以感觉出来
