### ISSUE TITLE
select的optionFilterProp与optionLabelProp这两个属性值为children时，展示与预期不符

### ISSUE THREAD

**Issue by tracy2zhang** [vueComponent/ant-design-vue#3099]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
vue3.0.2, chrome86.0.4240.111

### Reproduction link
[https://stackblitz.com/edit/vue-5zzqvx?file=src%2Fcomponents%2FHelloWorld.vue](https://stackblitz.com/edit/vue-5zzqvx?file=src%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
1. select设置optionFilterProp为children，设置多选或单选支持搜索，并在输入框中输入文字查询
2. select设置optionLabelProp为默认值或手动设置为children，并且子元素增加一些自定义的内容（比如emojj等），并给予初始值，然后切换选项
3. select设置单选，点击选择器
4. select设置多选，点击选择器，输入文字搜索（随便输入就行，无所谓能不能搜出内容），然后点击别处使菜单关闭

### What is expected?
1. 显示过滤后的选项
2. 选择器框中展示新的选中项
3. 下拉菜单展开，并且选择器为focused状态
4. 选择框focused状态消失

### What is actually happening?
1. 显示为空
2. 绑定的value变化，但是选择器中展示的选项不变，并且option中出现重复的项
3. 下拉菜单展开，但是有时会出现选择器不在focused的状态，尤其是首次点开（多选从没出现过这种问题）
4. 选择框focused状态仍然存在，需要再次点开并关闭才会消失

**Comment by tangjinzhou** [comment]
你这是几个问题？

**Comment by tracy2zhang** [comment]
> 你这是几个问题？看的我有点蒙

四个问题，序号对应

**Comment by tangjinzhou** [comment]
😓   分开提好不好   看着晕

**Comment by tracy2zhang** [comment]
抱歉哈，我看都是select相关的问题，而且我写到同一个demo里了，所以就统一提成一个了😛
