### ISSUE TITLE
日历组件使用moment.js汉化报错[2.0.0-beta.13]

### ISSUE THREAD

**Issue by brmyfun** [vueComponent/ant-design-vue#3101]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
vue 3.0.2  
ant-design-vue 2.0.0-beta.13
moment 2.29.1

### Environment
windows 10
chrome
vue 3.0.2  
ant-design-vue 2.0.0-beta.13
moment 2.29.1

### Reproduction link

官方链接
[https://2x.antdv.com/components/calendar-cn/](https://2x.antdv.com/components/calendar-cn/)

### Steps to reproduce
`App.vue`

```javascript
<template>
  <!-- <router-view /> -->
  <a-config-provider :locale="locale">
    <router-view />
  </a-config-provider>
</template>
<script>
import locale from "ant-design-vue/es/locale/zh_CN";
import moment from "moment";
import "moment/locale/zh-cn";
moment.locale("zh-cn");
export default {
  name: "App",
  data() {
    return {
      locale,
      moment,
    };
  },
};
</script>
```

`Calendar.vue`

```javascript
<template>
  <a-row>
    <a-col :span="12">
      <div
        :style="{
          border: '1px solid #d9d9d9',
          borderRadius: '4px',
          marginLeft: '12px',
        }"
      >
        <a-calendar
          v-model:value="value"
          :fullscreen="false"
          @panelChange="onPanelChange"
        />
      </div>
    </a-col>
    <a-col :span="12"></a-col>
  </a-row>
</template>
<script>
export default {
  name: "Calendar",
  data() {
    return {
      value: "",
    };
  },
  methods: {
    onPanelChange(value, mode) {
      console.log(value, mode);
    },
  },
};
</script>
```

### What is expected?
全局汉化日历组件

### What is actually happening?
实际报错
```
zh-cn.js:11 Uncaught TypeError: Cannot read property 'moment' of undefined
at zh-cn.js:11
at zh-cn.js:12
```

如果是这样的话
```
<template>
  <!-- <router-view /> -->
  <a-config-provider :locale="locale">
    <router-view />
  </a-config-provider>
</template>
<script>
import locale from "ant-design-vue/es/locale/zh_CN";
// import moment from "moment";
// import "moment/locale/zh-cn";
// moment.locale("zh-cn");
export default {
  name: "App",
  data() {
    return {
      locale,
      // moment,
    };
  },
};
</script>
```

确实不会报错，但是只有部分被汉化，就像[官方教程](https://2x.antdv.com/components/calendar-cn)一样
只有头部的年月被汉化，日期区域无法汉化

**Comment by tangjinzhou** [comment]
vite ?

**Comment by brmyfun** [comment]
> vite ?

是vite
版本是rc-9

**Comment by Tocurd** [comment]
在vite.config.ts中加入
`
optimizeDeps: {
		include: ['moment/locale/zh-cn']
	},
`

**Comment by brmyfun** [comment]
> 在vite.config.ts中加入
> `optimizeDeps: { include: ['moment/locale/zh-cn'] },`

好的，我试一下

**Comment by brmyfun** [comment]
> moment/locale/zh-cn
这样确实不会报错，但是月份和星期仍然没有被汉化

**Comment by tangjinzhou** [comment]
please use  
```js
import 'moment/dist/locale/zh-cn';
```
instead
```js
import 'moment/locale/zh-cn';
```

**Comment by ydfzgyj** [comment]
> please use
> 
> ```js
> import 'moment/dist/locale/zh-cn';
> ```
> 
> instead
> 
> ```js
> import 'moment/locale/zh-cn';
> ```

这样只有带默认值的选择框才会汉化，默认为空的仍然汉化失败

**Comment by tangjinzhou** [comment]
> > please use
> > ```js
> > import 'moment/dist/locale/zh-cn';
> > ```
> > 
> > 
> > instead
> > ```js
> > import 'moment/locale/zh-cn';
> > ```
> 
> 这样只有带默认值的选择框才会汉化，默认为空的仍然汉化失败

没懂  给个复现吧

**Comment by ydfzgyj** [comment]
@tangjinzhou 
![p1](https://user-images.githubusercontent.com/1191515/98232169-4bac3880-1f98-11eb-9bea-45b1eb5fa481.jpg)
![p2](https://user-images.githubusercontent.com/1191515/98232183-5070ec80-1f98-11eb-9b95-c522a6df1f47.jpg)
图一是默认值为空，图二是默认有值
貌似不用 vite 就不会出现这个情况，大概还是引用了多个 moment？但同一个组件怎么会这样还是不太理解

**Comment by tangjinzhou** [comment]
神奇的vite
在工程目录下安装一次moment就可以了 
 npm install moment
