### ISSUE TITLE
table customRow 属性中事件不触发

### ISSUE THREAD

**Issue by wzohxia** [vueComponent/ant-design-vue#3103]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
vite rc9 vue3.0.2  Chrome86.0.4240.75

### Reproduction link
[https://2x.antdv.com/components/table-cn/](https://2x.antdv.com/components/table-cn/)

### Steps to reproduce
```
<template>
<a-table :columns="columns" :data-source="source" :customRow="test"></a-table>
</template>

<script>
import { reactive, toRef, defineComponent, toRefs } from 'vue'
export default defineComponent({
name: 'App',
setup() {
const info = reactive({
columns: [
{ dataIndex: 'name', key: 'name' },
{ title: 'Age', dataIndex: 'age', key: 'age' },
{ title: 'Address', dataIndex: 'address', key: 'address' }
],
source: [
{ key: '1',name: 'John Brown',age: 32,address: 'New York No. 1 Lake Park' },
{ key: '2',name: 'Jim Green',age: 42,address: 'London No. 1 Lake Park' },
{ key: '3',name: 'Joe Black',age: 32,address: 'Sidney No. 1 Lake Park' }
],
})

const test = (record) => {
return {
on: {
click: (event) => { console.log(1)  },
dblclick: (event) => { console.log(1)  },
contextmenu: (event) => { console.log(1)  },
mouseenter: (event) =>  { console.log(1)  },
mouseleave: (event) =>  { console.log(1)  },
},
}
}

return { ...toRefs(info), test }
},
})
</script>
```

### What is expected?
属性事件触发

### What is actually happening?
table中customRow 属性中事件不触发

**Comment by tangjinzhou** [comment]
因vue3版本的调整，2.0组件库不再支持 on: { click }
你可以直接使用 onClick 驼峰格式

**Comment by wzohxia** [comment]
> 因vue3版本的调整，2.0组件库不再支持 on: { click }
> 你可以直接使用 onClick 驼峰格式

const test = (record) => {
      return {
        onClick: () => {
          console.log(123)
        },
      }
    }

一样无法触发
