### ISSUE TITLE
Table.install 缺少 typescript 类型，导致不能独立 import 和 use

### ISSUE THREAD

**Issue by niceue** [vueComponent/ant-design-vue#3104]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
win10, Chrome 78, vue3.0.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/e39b43bbc2329ed78d2f8283c19c93d20da0c76f/components/table/index.tsx#L90](https://github.com/vueComponent/ant-design-vue/blob/e39b43bbc2329ed78d2f8283c19c93d20da0c76f/components/table/index.tsx#L90)

### Steps to reproduce
```typescript
import {  App } from 'vue'
import { Table } from 'ant-design-vue'

export default function install(app: App) {
app.use(Table)
}
```

### What is expected?
ok

### What is actually happening?
typescript error

**Comment by Amour1688** [comment]
https://github.com/vueComponent/ant-design-vue/commit/d4e7b59f235362b23ab0b0ab037f81159c4bf5ee
