### ISSUE TITLE
多个 a-checkbox-group 的v-model 绑定同一个数据源时，勾选不同的a-checkbox-group中项会将v-model 绑定的数据源中已有数据清空，导致无法共同使用同一个v-model的数据源

### ISSUE THREAD

**Issue by ZhaoAndQian** [vueComponent/ant-design-vue#3108]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.0

### Environment
1.7.0

### Reproduction link
[https://www.antdv.com/components/checkbox-cn/](https://www.antdv.com/components/checkbox-cn/)

### Steps to reproduce

`<template>`
`<div>`
`分组一`
`<br/>`
`<a-checkbox-group :options="options" v-model="value"/>`
`<br />`
`分组二`
`<br/>`
`<a-checkbox-group :options="options1" v-model="value"/>`
`<br />`
`</div>`
`</template>`
`<script>`
`const options = [`
`{ label: 'Apple', value: 'Apple' },`
`{ label: 'Orange', value: 'Orange' },`
`];`
`const options1 = [`
`{ label: 'Pear', value: 'Pear' },`
`{ label: 'Banana', value: 'Banana' },`
`];`
`export default {`
  `  data() {`
    `return {`
      `options,`
      `options1,`
      `value: []`
    `};`
  `}`
`}`
`</script>`

### What is expected?
checkbox-group 选中项不要直接将选中项覆盖掉v-model中已有数据

### What is actually happening?
勾选不同的a-checkbox-group中项会将v-model 绑定的数据源中已有数据清空，导致多个a-checkbox-group无法共同使用同一个v-model的数据源

**Comment by tangjinzhou** [comment]
预期行为
之前的行为算是bug 😅
