### ISSUE TITLE
Tabs 标签页，文档未更新，无法使用

### ISSUE THREAD

**Issue by yundou147** [vueComponent/ant-design-vue#3109]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
3.0

### Reproduction link
[https://2x.antdv.com/components/tabs-cn/](https://2x.antdv.com/components/tabs-cn/)

### Steps to reproduce
Tabs 标签页无法使用

### What is expected?
Tabs 标签页无法使用

### What is actually happening?
Tabs 标签页无法使用

**Comment by yenkos** [comment]
同样无法正常使用，但是a-tabs在我的项目另一个组件里是正常的，就很奇怪

**Comment by yenkos** [comment]
我推测是animated的问题，设置为false后可以正常显示。

**Comment by tangjinzhou** [comment]
提供复现demo
