### ISSUE TITLE
1.1.10之后使用template来实现表单的疑问

### ISSUE THREAD

**Issue by yzhang226** [vueComponent/ant-design-vue#311]
在尝试使用过了使用template画表单，从直觉上看，没有原有的jsx方面。
有两个方面 -
1. 语法提示，由于在template的中，看起来不方便
2. 组织组件，内部的校验和验证，不方便。

**Comment by tangjinzhou** [comment]
你可以继续使用jsx 并不影响

**Comment by yzhang226** [comment]
> 你可以继续使用jsx 并不影响

在网站上的文档，已经不能看到1.1.9的历史文档。
我是认为，作者想推出这种开发模式。后面大方向就是使用template。

**Comment by tangjinzhou** [comment]
大方向还是跟着vu官方推荐走  但jsx 也只是语法糖  只是没有了demo  可以自行根据规则修改  我想对于熟悉jsx 和template的开发者 并不会有太大影响

**Comment by yzhang226** [comment]
> 大方向还是跟着vu官方推荐走 但jsx 也只是语法糖 只是没有了demo 可以自行根据规则修改 我想对于熟悉jsx 和template的开发者 并不会有太大影响

能开放历史文档嘛？没有文档，看着好累😫
万分感谢

**Comment by tangjinzhou** [comment]
git clone ....
git checkout 1.1.9
npm i
npm start

**Comment by yzhang226** [comment]
> git clone ....
> git checkout 1.1.9
> npm i
> npm start

好吧，看起来目前只能这样了。
如果能有历史文档还是很棒的，例如antd官网就会有历史文档。
历史文档，对于重大变更还是很有帮助的。
期待antd-vue越来越好
