### ISSUE TITLE
Menu单文件递归二级菜单无法渲染

### ISSUE THREAD

**Issue by hibjs** [vueComponent/ant-design-vue#3110]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
Microsoft Edge（版本 86.0.622.58 (官方内部版本) (64 位)）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-river-nv9zp?file=/src/components/Sidebar.vue)

### Steps to reproduce
Menu单文件递归二级菜单无法渲染

### What is expected?
Menu单文件递归二级菜单无法渲染

### What is actually happening?
Menu单文件递归可以正常生成菜单

**Comment by hibjs** [comment]
控制台显示组件再运行时无法渲染

**Comment by John60676** [comment]
参考这个issue的解决方案 #3032

**Comment by tangjinzhou** [comment]
[Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js".

**Comment by tangjinzhou** [comment]
打开浏览器控制台，查看提示，复制到任何搜索网站，均可得到更详细的方案
