### ISSUE TITLE
modal组件通过Modal.confirm()打开，如何触发onOK()后，阻止modal关闭

### ISSUE THREAD

**Issue by lany1721** [vueComponent/ant-design-vue#3111]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
onOK()方法体用于表单验证跟提交。希望验证不通过的时候modal 不会关闭。
验证不通过提前return也会关闭，返回promise.reject也会关闭。
想请教是否能手动控制它关闭或者显示？

### What does the proposed API look like?
通过method打开也可以有一个visible属性

**Comment by ajuner** [comment]
你可以通过在onOk方法中返回一个Promise达到你要求的效果
https://antdv.com/components/modal-cn/#%E7%A1%AE%E8%AE%A4%E5%AF%B9%E8%AF%9D%E6%A1%86(promise)
 ```
onOk(){
    return new Promise((resolve, reject)=>{
        reject()
    })
}
```

**Comment by lany1721** [comment]
> 你可以通过在onOk方法中返回一个Promise达到你要求的效果
> https://antdv.com/components/modal-cn/#%E7%A1%AE%E8%AE%A4%E5%AF%B9%E8%AF%9D%E6%A1%86(promise)
> 
> ```
> onOk(){
>    return new Promise((resolve, reject)=>{
>        reject()
>    })
> }
> ```

感谢，发现问题了，原来是调用validateFields时候没有return，所以直接被关闭了。

**Comment by lany1721** [comment]
虽然阻止了modal关闭，但是发现form组件跟Modal.$confirm结合一起用问题好多。已经改为在template里面modal组件了。要是官方有form组件跟Modal.$confirm结合的例子可以参考就好了
