### ISSUE TITLE
a-form-model在portal-vue中输入异常

### ISSUE THREAD

**Issue by WeiJianZhou** [vueComponent/ant-design-vue#3113]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.0

### Environment
vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-zxr5j?file=/src/App.vue)

### Steps to reproduce
1.a-form-model设置rules，经过portal-vue传送到其他dom上；
2.聚焦表单组件（例如a-input），在字符串中间位置开始输入新的字符；

### What is expected?
光标位置不变

### What is actually happening?
光标位置跳到字符串最后面

**Comment by HomyeeKing** [comment]
为什么我这里没有FormModel
![image](https://user-images.githubusercontent.com/49113249/98433542-035d5980-2103-11eb-818d-a942043456ef.png)

**Comment by tangjinzhou** [comment]
> 为什么我这里没有FormModel
> ![image](https://user-images.githubusercontent.com/49113249/98433542-035d5980-2103-11eb-818d-a942043456ef.png)

2.x 已经移除
