### ISSUE TITLE
a-input-number能否支持maxLength？

### ISSUE THREAD

**Issue by zomixi** [vueComponent/ant-design-vue#3114]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-input-number不支持maxLength属性

### What does the proposed API look like?

`<a-inut-number :maxLength="10" />`

**Comment by tianyuan233** [comment]
通过 max 属性就可以间接限制长度吧
比如 max = 999 就等同于 maxLength=3

**Comment by tangjinzhou** [comment]
2.0 support maxlength
