### ISSUE TITLE
Modal style has no effect

### ISSUE THREAD

**Issue by SinBirb** [vueComponent/ant-design-vue#3115]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.1

### Environment
Firefox Nightly

### Reproduction link
[https://www.antdv.com/components/modal/](https://www.antdv.com/components/modal/)

### Steps to reproduce
Click button "Display a modal dialog at 20px to Top"

### What is expected?
a modal with top margin of 20px

### What is actually happening?
Modal doesn't have the correct position. The style is applied to the modal-root which doesn't have any effect.

        

Edit: sorry, wrong version. We use the latest stable: 1.7.1

**Comment by tangjinzhou** [comment]
please use 
```
:dialog-style="{ top: '20px' }"
```
instead of 
```
style="top:20px"
```

this is docs error.

**Comment by SinBirb** [comment]
Thank you, it works.
