### ISSUE TITLE
DatePicker 无法完全汉化

### ISSUE THREAD

**Issue by Tocurd** [vueComponent/ant-design-vue#3118]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
vue  3.0.2 
vite   1.0.0-rc.9 
ant-design-vue   2.0.0-beta.13

### Reproduction link
[https://2x.antdv.com/components/config-provider-cn/](https://2x.antdv.com/components/config-provider-cn/)

### Steps to reproduce
已经完全按照官网文档来写书写代码，可日期部分还是英文。官方示例也是这样

`
import moment from "moment"
import "moment/locale/zh-cn"
moment.locale('zh-cn')

import { ConfigProvider } from 'ant-design-vue'
import zh_CN from 'ant-design-vue/es/locale/zh_CN'
<a-config-provider locale={zh_CN}>
    <RouterView />
</a-config-provider>
`

### What is expected?
全部汉化

### What is actually happening?
全部汉化

**Comment by tangjinzhou** [comment]
#3101

**Comment by Tocurd** [comment]
> #3101

官网示例的日期时间选择器 也是没有汉化的。不是vite.config的问题

**Comment by wcldyx** [comment]
ant-design-vue版本：2.1.2 
我按官网示例，还是有部分没汉化，有大佬解决了的吗
