### ISSUE TITLE
Carousel items do not register click in mobile devices

### ISSUE THREAD

**Issue by alokrajkishore** [vueComponent/ant-design-vue#3119]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Mac OS, Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-forest-ft2ym?file=/src/App.vue)

### Steps to reproduce
1. Open the view from the codesandbox in a new window.
2. Open dev tools and click on any image, a console messaged is logged in the dev tools.
3. Change to mobile or iPad view, click on any image, console message is not logged in the dev tools. However, clicking below the image does log the message.

### What is expected?
When an image is clicked in mobile or iPad view, the event is registered and a console message is logged.

### What is actually happening?
It seems like clicking on the image is somehow being ignored on smaller devices. On desktop everything works as expected.

---
Similar issue was created here almost a year ago https://github.com/vueComponent/ant-design-vue/issues/1329, but it was closed automatically.

**Comment by tangjinzhou** [comment]
you can use div backgroundImage instead of img dom

**Comment by alokrajkishore** [comment]
@tangjinzhou Thanks, that worked.

**Comment by ankeji** [comment]
同样的问题，正在查找原因

**Comment by kaguya3222** [comment]
Why is this closed? @tangjinzhou offered a workaround, it's not a pure solution, what If we want robots to index our images or want screenreader to read `alt` of our images?
