### ISSUE TITLE
drawer 设置 get-container false, placement left后左边会留白，另外get-container可以指定某个ref吗

### ISSUE THREAD

**Issue by StormSpirit22** [vueComponent/ant-design-vue#3122]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
mac os, chrome latest, vue 2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-goldstine-zbg98)

### Steps to reproduce
https://codesandbox.io/s/elated-goldstine-zbg98
将placement改为left就会出现留白

### What is expected?
左边不出现留白

### What is actually happening?
左边出现留白

**Comment by StormSpirit22** [comment]
另外我想将drawer设置成基于父组件menu的，把get-container设置成false，还是不行，不知道能不能设置成基于某个ref？

**Comment by tangjinzhou** [comment]
:get-container="()=>someRef"

**Comment by tangjinzhou** [comment]
这个留白是你样式里面的 padding: '48px',
