### ISSUE TITLE
collapse-panel 的 header 属性当使用插槽的时候触发了错误

### ISSUE THREAD

**Issue by ibwei** [vueComponent/ant-design-vue#3123]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
macOS10,chrome,3.0 

### Reproduction link
[https://github.com/ibwei/vue3-ts-base/blob/master/src/views/test/Test.vue](https://github.com/ibwei/vue3-ts-base/blob/master/src/views/test/Test.vue)

### Steps to reproduce
```js
<a-collapse-panel
v-for="(g, key, index) of cloudRoleList"
:key="`${index}`"
:style="customStyle"
>
<template v-slot:header>
<div class="kk">llll</div>
</template>
</a-collapse-panel>
```

是我写法的问题吗？

### What is expected?
kk 出现表折叠面板的表头

### What is actually happening?
触发了错误

**Comment by tangjinzhou** [comment]
没能复现问题

```html
<template>
  <a-collapse v-model:activeKey="activeKey">
    <a-collapse-panel key="1">
      <template v-slot:header>
        <div class="kk">
          llll
        </div>
      </template>
      <p>{{ text }}</p>
    </a-collapse-panel>
  </a-collapse>
</template>
<script>
export default {
  data() {
    return {
      text: `A dog is a type of domesticated animal.Known for its loyalty and faithfulness,it can be found as a welcome guest in many households across the world.`,
      activeKey: ['1'],
    };
  },
  watch: {
    activeKey(key) {
      console.log(key);
    },
  },
};
</script>

```
