### ISSUE TITLE
The default import of the beta.13 version will prompt you to load babel-plugin-import

### ISSUE THREAD

**Issue by Linkontoask** [vueComponent/ant-design-vue#3125]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
any

### Reproduction link
[https://2x.antdv.com/docs/vue/getting-started-cn/#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD](https://2x.antdv.com/docs/vue/getting-started-cn/#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD)

### Steps to reproduce
```
import Antd from 'ant-design-vue'
import 'ant-design-vue/dist/antd.min.css'

export default Antd
```

### What is expected?
![](https://zos.alipayobjects.com/rmsportal/GHIRszVcmjccgZRakJDQ.png)

### What is actually happening?
As shown

**Comment by tangjinzhou** [comment]
?  
this is a tip only at development envirment
