### ISSUE TITLE
Select组件单选模式v-model="stringValue"，在stringValue=空字符串的时候无法显示placeholder

### ISSUE THREAD

**Issue by kagaricyan** [vueComponent/ant-design-vue#3129]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10 chrome85 vue2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-xxll2?file=/src/App.vue)

### Steps to reproduce
<a-select>组件绑定string类型数据，在string为空字符串时不显示placeholder内容

### What is expected?
stringValue=''的时候显示placeholder

### What is actually happening?
stringValue=[]的时候才显示placeholder。

---
以为是mode属性没设置的问题，但是参照文档也只能设置mode=default，还是无效

**Comment by tangjinzhou** [comment]
please use value: undefined,
