### ISSUE TITLE
日期插件中文无法使用

### ISSUE THREAD

**Issue by PantongWu** [vueComponent/ant-design-vue#3132]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
电脑系统: Mac 10.15.7、浏览器版本: Chrome 86.0.4240.183、Vue版本: 3.0.2

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn/](https://2x.antdv.com/components/date-picker-cn/)

### Steps to reproduce
<a-config-provider :locale="zh_CN" :getPopupContainer="getPopupContainer">
    <main :class="{ 'aside-collapsed': isCollapse }">
    <a-range-picker v-model:value="value" @change="onChange" />
</main>
</a-config-provider>

import zh_CN from 'ant-design-vue/es/locale/zh_CN'
import moment from 'moment'
import 'moment/locale/zh-cn'

moment.locale('zh-cn')
export default {
setup() {
const value = ref([])
return {
value, zh_CN
}
}
}

### What is expected?
日期组件 月份星期显示中文

### What is actually happening?
日期组件 月份星期 依然显示英文 中文国际化无法生效

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2527

**Comment by PantongWu** [comment]
https://www.antdv.com/components/locale-provider-cn/#%E4%BD%BF%E7%94%A8
即使是文档中
![image](https://user-images.githubusercontent.com/21765389/98329814-09d0d000-2034-11eb-9145-4f57c945a874.png)
这也是无法正常显示月份跟星期的啊

**Comment by any86** [comment]
# 临时解决方法

![image](https://user-images.githubusercontent.com/8264787/120954220-4b1f8e80-c781-11eb-9f85-4113f8540fe6.png)


## 吐槽
同样的代码我放到`codesandbox.io`就好事, 但是放到本地就不行, 我怀疑是多语言包引入不成功的问题, 具体是不是vit的bug我也不想研究, 建议官方研究下吧.

这么多人都提这个问题, 而且都1年了还没解决, 或者给出解决方法也行啊. 现在就ant支持vue3, 但是很多地方用的都让人怀疑人生, 比如ul/p等元素有默认样式...

## 解决
```javascript
import 'moment/locale/zh-cn';
```
把这行替换成下面的代码, 这段代码就是moment语言包中的代码, 我删减了部分, 所以这只是一个**应急方案**, 因为你全局切换语言的时候, 日期也不会变别的语言, 不知道还有没有其他bug:
```javascript
moment.locale('zh-cn', {
  months:
    '\u4E00\u6708_\u4E8C\u6708_\u4E09\u6708_\u56DB\u6708_\u4E94\u6708_\u516D\u6708_\u4E03\u6708_\u516B\u6708_\u4E5D\u6708_\u5341\u6708_\u5341\u4E00\u6708_\u5341\u4E8C\u6708'.split(
      '_'
    ),
  monthsShort:
    '1\u6708_2\u6708_3\u6708_4\u6708_5\u6708_6\u6708_7\u6708_8\u6708_9\u6708_10\u6708_11\u6708_12\u6708'.split('_'),
  weekdays:
    '\u661F\u671F\u65E5_\u661F\u671F\u4E00_\u661F\u671F\u4E8C_\u661F\u671F\u4E09_\u661F\u671F\u56DB_\u661F\u671F\u4E94_\u661F\u671F\u516D'.split(
      '_'
    ),
  weekdaysShort: '\u5468\u65E5_\u5468\u4E00_\u5468\u4E8C_\u5468\u4E09_\u5468\u56DB_\u5468\u4E94_\u5468\u516D'.split(
    '_'
  ),
  weekdaysMin: '\u65E5_\u4E00_\u4E8C_\u4E09_\u56DB_\u4E94_\u516D'.split('_'),
  longDateFormat: {
    LT: 'HH:mm',
    LTS: 'HH:mm:ss',
    L: 'YYYY/MM/DD',
    LL: 'YYYY\u5E74M\u6708D\u65E5',
    LLL: 'YYYY\u5E74M\u6708D\u65E5Ah\u70B9mm\u5206',
    LLLL: 'YYYY\u5E74M\u6708D\u65E5ddddAh\u70B9mm\u5206',
    l: 'YYYY/M/D',
    ll: 'YYYY\u5E74M\u6708D\u65E5',
    lll: 'YYYY\u5E74M\u6708D\u65E5 HH:mm',
    llll: 'YYYY\u5E74M\u6708D\u65E5dddd HH:mm',
  },
  meridiemParse: /凌晨|早上|上午|中午|下午|晚上/,

  meridiem: function (hour, minute, isLower) {
    var hm = hour * 100 + minute;
    if (hm < 600) {
      return '\u51CC\u6668';
    } else if (hm < 900) {
      return '\u65E9\u4E0A';
    } else if (hm < 1130) {
      return '\u4E0A\u5348';
    } else if (hm < 1230) {
      return '\u4E2D\u5348';
    } else if (hm < 1800) {
      return '\u4E0B\u5348';
    } else {
      return '\u665A\u4E0A';
    }
  },
  calendar: {
    sameDay: '[\u4ECA\u5929]LT',
    nextDay: '[\u660E\u5929]LT',
   
    lastDay: '[\u6628\u5929]LT',
  
    sameElse: 'L',
  },
  dayOfMonthOrdinalParse: /\d{1,2}(日|月|周)/,

  relativeTime: {
    future: '%s\u540E',
    past: '%s\u524D',
    s: '\u51E0\u79D2',
    ss: '%d \u79D2',
    m: '1 \u5206\u949F',
    mm: '%d \u5206\u949F',
    h: '1 \u5C0F\u65F6',
    hh: '%d \u5C0F\u65F6',
    d: '1 \u5929',
    dd: '%d \u5929',
    M: '1 \u4E2A\u6708',
    MM: '%d \u4E2A\u6708',
    y: '1 \u5E74',
    yy: '%d \u5E74',
  },
  week: {
    dow: 1,
    doy: 4,
  },
});
```

**Comment by qiuyaofan** [comment]
#3029 
import 'moment/locale/zh-cn' 换成import 'moment/dist/locale/zh-cn' 就可以
