### ISSUE TITLE
同1.x版本#2916一样问题  表格头部 开启 fixed: "left", 再开启 ellipsis: true, 没有自动省略，而是自动撑开

### ISSUE THREAD

**Issue by wzohxia** [vueComponent/ant-design-vue#3137]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.13

### Environment
vite rc9 vue3.0.2  Chrome86.0.4240.75

### Reproduction link
[https://2x.antdv.com/components/table-cn/](https://2x.antdv.com/components/table-cn/)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue/issues/2916#issue-709698718

### What is expected?
期望 fixed: "left" ，ellipsis: true同时开启时能够自动省略

### What is actually happening?
表格每列给定宽度 width，第一列给了 fixed: "left" ，所有的列开启了ellipsis: true, 第一列没有自动省略 其它列正常 ；第一列浮动的 会自动撑开 超出设定的宽度

**Comment by tangjinzhou** [comment]
确认下版本？
beta.13 应该已经修复了的  
如果依然有问题，请提供复现demo
