### ISSUE TITLE
Modal.info/Modal.success/Modal.error/Modal.warning/Modal.confirm 不支持 dialogClass

### ISSUE THREAD

**Issue by xiongjiaojiao** [vueComponent/ant-design-vue#3142]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
方便给 ant-modal 直接传类名操作

### What does the proposed API look like?
ConfirmDialog支持传dialogClass

**Comment by tangjinzhou** [comment]
可以直接使用 class 即可。
在2.x中 dialogClass 也会被去掉
