### ISSUE TITLE
Select can not be searched under big data

### ISSUE THREAD

**Issue by djkloop** [vueComponent/ant-design-vue#3144]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.15

### Environment
OSX 10.14.6 / Microsoft Edge  86.0.622.63 / Vue 3.0.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-sound-42v5u?file=/src/App.vue)

### Steps to reproduce
```js

/// 搜索有问题
/// https://codesandbox.io/s/weathered-sound-42v5u?file=/src/App.vue

```

### What is expected?
Virtual list search can search correctly

### What is actually happening?
Virtual list search cannot search correctly

**Comment by tracy2zhang** [comment]
我也遇到了这个问题，长列表在刚点开的时候，很多比较靠后的数据是搜索不到的，但是如果一直往下滚动，然后在搜，就可以搜索的到了，感觉可能跟加了虚拟列表有关
