### ISSUE TITLE
穿梭框能实现双击就选择吗（不用点中间的按钮）

### ISSUE THREAD

**Issue by cyt68** [vueComponent/ant-design-vue#3149]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
穿梭框能实现双击就选择吗（不用点中间的按钮）

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
穿梭框能实现双击就选择吗（不用点中间的按钮）

### What is expected?
穿梭框能实现双击就选择吗（不用点中间的按钮）

### What is actually happening?
穿梭框能实现双击就选择吗（不用点中间的按钮）

**Comment by tangjinzhou** [comment]
你可以添加 双击 事件 并更改数据源
