### ISSUE TITLE
更新到最新版本后datepicker组件的预设范围的按钮会重复渲染两次。官网上的也有问题。

### ISSUE THREAD

**Issue by lilifan1598** [vueComponent/ant-design-vue#315]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.1

### Environment
chrome 69

### Reproduction link
[https://tangjinzhou.gitee.io/ant-design-vue/components/date-picker-cn/#components-date-picker-demo-presetted-ranges](https://tangjinzhou.gitee.io/ant-design-vue/components/date-picker-cn/#components-date-picker-demo-presetted-ranges)

### Steps to reproduce
组件显示有问题，官网组件文档显示有问题

### What is expected?
能尽快弄好

### What is actually happening?
能尽快弄好

![image](https://user-images.githubusercontent.com/39824392/50145474-a547e300-02ec-11e9-8b27-3d1c73c162ba.png)

**Comment by tangjinzhou** [comment]
please update to 1.2.2

**Comment by lilifan1598** [comment]
> please update to 1.2.2

辛苦啦！非常感谢！！！
