### ISSUE TITLE
table 表格嵌套 子表格整行编辑  input框无法显示

### ISSUE THREAD

**Issue by huangdabao321** [vueComponent/ant-design-vue#3151]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
chrome@84.0.4147.105  win@10  antdv@1.6.2  vue@2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-wilson-1g44q?file=/src/App.vue)

### Steps to reproduce
1.展开表格
2.编辑子表格

### What is expected?
编辑行处于 可以编辑状态  a-input 显示

### What is actually happening?
无法编辑

**Comment by ajuner** [comment]
在innerColumns添加scopedSlots
{
          title: "操作",
          dataIndex: "action",
          scopedSlots: { customRender: "action" }
}

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/objective-forest-4tp19

**Comment by huangdabao321** [comment]
非常感谢 二位大佬
