### ISSUE TITLE
select组件带搜索功能，在chrome浏览器里切换焦点异常

### ISSUE THREAD

**Issue by apeWang** [vueComponent/ant-design-vue#3154]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.15

### Environment
macOS Catalina 版本10.15.2       chrome 版本 83.0.4103.97

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
在chrome游览中, Select 选择器——代码演示下——搜索框（搜索和远程数据结合）示例里，下拉选择完成后，此时使用Tab键来切换焦点，需要按二次Tab键焦点才移动下一个输入框内;在Firefox中，使用Tab键来切换焦点，只需要按一次

### What is expected?
在chrome游览中, Select 选择器——代码演示下——搜索框（搜索和远程数据结合）示例里，下拉选择完成后，此时使用Tab键来切换焦点，只需要按一次Tab键焦点才移动下一个输入框内

### What is actually happening?
在chrome游览中, Select 选择器——代码演示下——搜索框（搜索和远程数据结合）示例里，下拉选择完成后，此时使用Tab键来切换焦点，只需要按二次Tab键焦点才移动下一个输入框内

**Comment by tangjinzhou** [comment]
2.0.0-beta.15 未能复现你的问题，请确认版本并提供复现示例
