### ISSUE TITLE
in TSX, card component's actions slots won't work

### ISSUE THREAD

**Issue by ZhangShiy** [vueComponent/ant-design-vue#3156]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.15

### Environment
vue: 3.0.2

### Reproduction link
[https://2x.antdv.com](https://2x.antdv.com)

### Steps to reproduce
```jsx
                  <Card
                    v-slots={{
                      actions: () => (
                        <span class="ant-card-actions">
                          <SettingOutlined key="setting" />
                          <EditOutlined key="edit" />
                          <LogoutOutlined key="logout" onClick={logout} />
                        </span>
                      ),
                      cover: () => (
                        <img alt="user" style="margin: 10px; width: 280px" src={userCover} />
                      )
                    }}
                  >
                    <Card.Meta title={user.name} description={user.content} />
```
![image](https://user-images.githubusercontent.com/46205888/98786870-b5659000-2439-11eb-83ad-1972f9daca90.png)

### What is actually happening?
actions 插槽没有正常显示

**Comment by zkwolf** [comment]
https://2x.antdv.com/components/card-cn/#components-card-demo-support-more-content-configuration 参考文档吧，actions要求是个array

可以这样
```
actions: () => (
            <>
              <SettingOutlined key="setting" />
              <EditOutlined key="edit" />
            </>
          )
```
