### ISSUE TITLE
Collapse change 事件传入参数有误

### ISSUE THREAD

**Issue by StoneMoe** [vueComponent/ant-design-vue#3158]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
macos, chrome latest, vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-4o3pu)

### Steps to reproduce
See minimal reproduction

### What is expected?
The `key` parameter of `@change` event handler should be the value of which panel user just click, not the whole activeKey(v-model) array.
And the documentation say so.

### What is actually happening?
key == activeKey

---
No way to know what panel user just click currently.

**Comment by StoneMoe** [comment]
除了无法得知用户正在点击的是哪个panel之外，也无法知道用户是正在展开还是正在收起panel，只能自己做workaround

**Comment by tangjinzhou** [comment]
v-model 本身会改变 activeKey，而且 activeKey 是个引用类型，为了 change 事件能够有机会控制最终activeKey的值，我们统一把change事件放置在 v-model 之后执行
你可以通过 watch：{ actvieKey (val, oldVal ){}}   来达到你的预期效果

**Comment by StoneMoe** [comment]
> v-model 本身会改变 activeKey，而且 activeKey 是个引用类型，为了 change 事件能够有机会控制最终activeKey的值，我们统一把change事件放置在 v-model 之后执行
> 你可以通过 watch：{ actvieKey (val, oldVal ){}} 来达到你的预期效果

明白了，感谢答疑。
考虑到向前兼容，这一设计是否合理先按下不表
但这部分的文档我认为确实还有改进的空间
