### ISSUE TITLE
Icon Component included global styles

### ISSUE THREAD

**Issue by sk0x0y** [vueComponent/ant-design-vue#316]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.1

### Environment
OS: Windwos 10 RS5, Browser: Whale ( chromium based ), Vue: 2.5.17

### Steps to reproduce
When using "Icon" component

### What is expected?
Using partially is my needs.
I could apply button only via import "ant-design-vue/lib/button/style/index.less

If already has methods in ant-design-vue,
I want to know that ways.

### What is actually happening?
In "Icon" case, i couldn't apply that style independently.
( I tried import "ant-design-vue/lib/icon" , import "ant-design-vue/lib/icon/style, import "ant-design-vue/lib/icon/style/css" )

---
Thanks for provide ant design.

**Comment by tangjinzhou** [comment]
https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo

**Comment by sk0x0y** [comment]
> https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo

Thanks for replay, so, is it accepted issue?

**Comment by tangjinzhou** [comment]
This is only a temporary solution, and we will explore better solutions in the future. If you have a better idea, you can PR.

**Comment by papakay** [comment]
@tangjinzhou please how do i use the information in the link in a nuxt application. Thank you.
