### ISSUE TITLE
请问ant design vue 的国际化不支持印尼语吗？

### ISSUE THREAD

**Issue by pwyGouxiong** [vueComponent/ant-design-vue#3160]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我们用的ant design vue 做国际化时发现ant design vue文档里所支持的语种不包括印度语，但是发现ant design react的文档里有支持，请问ant design vue 的国际化不支持印尼语吗

### What does the proposed API look like?
期望支持印度语

**Comment by BoringDays** [comment]
印度十几种官方语言，印尼又是另一个国家，你得先确认需要支持的是印地语还是泰米尔语还是乌尔都语还是哪种语言才行
