### ISSUE TITLE
为什么 List.Item.Meta 的名称 AListItemMeta 是 displayName 而其它组件均是name

### ISSUE THREAD

**Issue by chsword** [vueComponent/ant-design-vue#3167]
### What problem does this feature solve?
命名一致性的问题

### What does the proposed API look like?
components/list/index.tsx
```ts
List.install = function(app: App) {
app.component(List.name, List);
app.component(List.Item.name, List.Item);
app.component(List.Item.Meta.displayName /*为何此处命名特殊*/ , List.Item.Meta);
return app;
};
```

**Comment by zkwolf** [comment]
https://github.com/vuejs/vue-next/blob/288c764e5279ccef63e0ef304d4250f5ad935a46/packages/runtime-core/src/component.ts#L112

大概是因为这个吧，函数式组件类型就这么写的

**Comment by Amour1688** [comment]
不能更改函数的 `name` 属性
