### ISSUE TITLE
menu样式错乱，submenu 丢失 rootPrefixCls

### ISSUE THREAD

**Issue by sososoyoung** [vueComponent/ant-design-vue#3180]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vue3 v3.0.0

### Reproduction link
![](https://user-images.githubusercontent.com/17797610/99178493-970bd700-274e-11eb-95ec-3afd474a49d0.png)
[https://github.com/vueComponent/ant-design-vue/pull/3179](https://github.com/vueComponent/ant-design-vue/pull/3179)

### PR
https://github.com/vueComponent/ant-design-vue/pull/3179

### Update
更新到 vue v3.0.2后解决

**Comment by tangjinzhou** [comment]
给个复现示例吧

**Comment by tangjinzhou** [comment]
vue升级到 3.0.2 试试先

**Comment by sososoyoung** [comment]
> vue升级到 3.0.2 试试先

升级后可以了，请问是Vue的什么问题呢？有相关关键字或 issues么？

**Comment by ajuner** [comment]
> > vue升级到 3.0.2 试试先
> 
> 升级后可以了，请问是Vue的什么问题呢？有相关关键字或 issues么？

看看是不是这个https://github.com/vuejs/vue-next/issues/1412

**Comment by sososoyoung** [comment]
> > > vue升级到 3.0.2 试试先
> > 
> > 
> > 升级后可以了，请问是Vue的什么问题呢？有相关关键字或 issues么？
> 
> 看看是不是这个[vuejs/vue-next#1412](https://github.com/vuejs/vue-next/issues/1412)

26 Jun 就merge了，3.0.0就包含这个了

**Comment by sososoyoung** [comment]
猜测原因应该是这里https://github.com/vueComponent/ant-design-vue/blob/8da63a6a24fabd39f6dab4bcb44c4d91134938cf/components/vc-menu/SubMenu.jsx#L566 `injectExtraPropsKey` 没按预期获取到 `rootPrefixCls`

**Comment by sososoyoung** [comment]
close 了，我看package.json 依赖的vue版本已经是 `^3.0.2` 了 https://github.com/vueComponent/ant-design-vue/blob/8da63a6a24fabd39f6dab4bcb44c4d91134938cf/package.json#L66
