### ISSUE TITLE
请问 antdv-demo 是私人项目么？贡献代码本地调试依赖这个。或者有其他建议么

### ISSUE THREAD

**Issue by sososoyoung** [vueComponent/ant-design-vue#3181]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
想贡献代码时， 本地调试时 submodule `antdv-demo` 下载不了，现在好像是个人的非公开项目？
看到https://github.com/vueComponent/ant-design-vue/issues/2800 了，是私人项目，没有公开计划。。。。

请问有计划开源或者其他本地调试方案么？总不能老是盲写代码吧

**Comment by ajuner** [comment]
我调试都在example下调试的。。

**Comment by sososoyoung** [comment]
> 我调试都在example下调试的。。

每次都重新写demo？

**Comment by ajuner** [comment]
一般我按自己需要来写

**Comment by sososoyoung** [comment]
> 一般我按自己需要来写

好吧，后面的人要是想改，没有测试用例，有没有问题就看老天爷了，哎，这真的是个开源项目么？

**Comment by sososoyoung** [comment]
最近连着遇到几个低级bug, 用着心累啊

**Comment by sososoyoung** [comment]
@tangjinzhou 大佬有什么提交代码后回测的建议么？

**Comment by ajuner** [comment]
那就多多支援吧~~

**Comment by zkwolf** [comment]
本地调试用dev自己改example就可以啊，我也是这么搞

**Comment by tangjinzhou** [comment]
demo 只是跑快照  本身意义不是很大，test下有单测，这个不影响啊
