### ISSUE TITLE
Notify组件传入top选项无效

### ISSUE THREAD

**Issue by lizhancheng** [vueComponent/ant-design-vue#3182]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
chrome88 Vue 2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-heu2p?file=/src/App.vue)

### Steps to reproduce
```javascript
this.$notification.open({
top: 450,
message: "test1",
description: "test23",
duration: null,
});
```

### What is expected?
距离顶部450像素

### What is actually happening?
没有生效

**Comment by zkwolf** [comment]
top接受string类型，应该是450px

**Comment by ajuner** [comment]
> top接受string类型，应该是450px

文档中的类型是传入number，可以改下或者也支持下~

**Comment by xrkffgg** [comment]
看了下代码是有支持 number 类型的，但是好像没生效，应确认下

**Comment by xrkffgg** [comment]
同时 中英文 这个描述 不一致，文档也需修复下

**Comment by tangjinzhou** [comment]
@xrkffgg 2.x 也同步修复下吧

**Comment by lizhancheng** [comment]
貌似传入450px也不生效吧 @xrkffgg @zkwolf

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/99223294-37313100-281f-11eb-99f9-edcb67d04257.png)

**Comment by lizhancheng** [comment]
![image](https://user-images.githubusercontent.com/8544620/99224602-998b3100-2821-11eb-9d95-8727c83f9464.png)
这真的好尴尬😅，我这边居然没有这样的效果

**Comment by lizhancheng** [comment]
我知道了，是我没按保存导致的，忽略上面…
