### ISSUE TITLE
form 多重object  rules验证失败

### ISSUE THREAD

**Issue by wzohxia** [vueComponent/ant-design-vue#3186]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
ant-design-vue 2.0.0-rc.1

### Environment
vue3.0.2  Chrome86.0.4240.75

### Reproduction link
[https://2x.antdv.com/components/form-cn/](https://2x.antdv.com/components/form-cn/)

### Steps to reproduce
```
<template>
  <a-form :model="form" :rules="rules">
    <a-form-item label="测试" name="users.test">
      <a-input v-model:value="form.users.test" />
    </a-form-item>
  </a-form>
</template>

<script>
import { reactive, defineComponent, toRefs } from 'vue'
export default defineComponent({
  name: 'App',
  setup() {
    const info = reactive({
      form: { users: { test: '' } },
      rules: {
        'users.test': {
          required: true,
          message: '测试不能为空',
          type: 'string',
        },
      },
    })

    return {
      ...toRefs(info),
    }
  },
})
</script>

```
![image](https://user-images.githubusercontent.com/22089141/99210298-6be1c000-2800-11eb-91eb-25d5fc6370c8.png)
![image](https://user-images.githubusercontent.com/22089141/99210315-7603be80-2800-11eb-9fd6-1d96617f4d76.png)

### What is expected?
form验证结果正确

### What is actually happening?
form验证结果无法消除

**Comment by tangjinzhou** [comment]
<template>
  <a-form :model="form">
    <a-form-item label="测试" :name="['users','test']" :rules="rules['users.test']">
      <a-input v-model:value="form.users.test" />
    </a-form-item>
  </a-form>
</template>

<script>
import { reactive, defineComponent, toRefs } from 'vue'
export default defineComponent({
  name: 'App',
  setup() {
    const info = reactive({
      form: { users: { test: '' } },
      rules: {
        'users.test': {
          required: true,
          message: '测试不能为空',
          type: 'string',
        },
      },
    })

    return {
      ...toRefs(info),
    }
  },
})
</script>

**Comment by tangjinzhou** [comment]
从 2.0 之后我们不再支持 点 的形式来连接字段   而是使用数组

**Comment by sososoyoung** [comment]
@tangjinzhou 帮忙把文档https://2x.antdv.com/components/form-cn/#Form.Item也更新下吧，我上次看也觉得应该改成支持array了（我以前是用react版本的），但是文档还是只有 string，容易误导，源码看确实已经支持了 https://github.com/vueComponent/ant-design-vue/blob/8da63a6a24fabd39f6dab4bcb44c4d91134938cf/components/form/FormItem.tsx#L82
