### ISSUE TITLE
Custom validate form don't need invoke callback anymore

### ISSUE THREAD

**Issue by HomyeeKing** [vueComponent/ant-design-vue#3189]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Vue3

### Reproduction link
[http://asd.com](http://asd.com)

### Steps to reproduce
{validator:fn}
(rule,value,callback)

### What is expected?
invoke callback to show message

### What is actually happening?
console warning : callback is deprecated

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/99398872-e1907d80-291f-11eb-8e0e-be28a8555bca.png)
https://2x.antdv.com/docs/vue/migration-v2-cn/#2.0-%E6%9C%89%E5%93%AA%E4%BA%9B%E4%B8%8D%E5%85%BC%E5%AE%B9%E7%9A%84%E5%8F%98%E5%8C%96
