### ISSUE TITLE
1.2.1 版本menu仍然有折叠闪动问题

### ISSUE THREAD

**Issue by wry5560** [vueComponent/ant-design-vue#319]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.1

### Environment
win64 chrome70.0.3538.110  Vue 2.5.21

### Reproduction link
[ https://github.com/sendya/ant-design-pro-vue]( https://github.com/sendya/ant-design-pro-vue)

### Steps to reproduce
使用ant-design-pro-vue时出现，ant-design-vue近期更新后，该地址项目折叠按钮失效，在GlobleHeader.vue内将 click.native方法改成click可以生效，但相继会出现折叠闪动的问题

### What is expected?
fix the bug

### What is actually happening?
折叠menu时闪动

**Comment by tangjinzhou** [comment]
1. menu闪动1.2.1已修复，如有问题，请提供复现demo
2. pro问题可以去pro 提issue
3. 多个问题请分开提issue

**Comment by sendya** [comment]
你可以到这个 repo 来提是 pro 这边的问题： https://github.com/sendya/ant-design-pro-vue/issues
