### ISSUE TITLE
Vue 3 icons

### ISSUE THREAD

**Issue by AkhmedovSH** [vueComponent/ant-design-vue#3190]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
in ant desing version 1.x ICONS API We have type
and most people save nav items in other file and show them with for loop
<a-icon type="dynamic value from for loop">
now i can not use like this when my icon like component

### What does the proposed API look like?
API #
Property|Description|Type|Default
type|Type of the ant design|icon|string	-

**Comment by sendya** [comment]
<component :is="yourIcon" />

**Comment by weizaily** [comment]
像这样使用的话<component :is="yourIcon" />，相应的icon组件也要相应的import并注入。当使用的icon多的话该怎么解决

**Comment by weizaily** [comment]
> `<component :is="yourIcon" />`
像这样使用的话，相应的icon组件也要相应的导入并注入。当使用的icon多的话该怎么解决

**Comment by ajuner** [comment]
> > `<component :is="yourIcon" />`
> > 像这样使用的话，相应的icon组件也要相应的导入并注入。当使用的icon多的话该怎么解决

https://www.antdv.com/components/icon-cn/#SVG-%E5%9B%BE%E6%A0%87
![image](https://user-images.githubusercontent.com/53512912/99340030-2be31180-28c2-11eb-93cf-feff9fdb0436.png)
看看这里有个说明

**Comment by tangjinzhou** [comment]
不在意体积的化 可以全量导入

**Comment by wwwjun** [comment]
> 不在意体积的化 可以全量导入

老哥，请教下，我分析包的时候发现直接全部引入了icons，然后按照网上的方法写了个空的icons.js` exoport {};`
然后配置了webpack：
`config.resolve.alias.set('@ant-design/icons/lib/dist$', resolve(__dirname,'./src/util/ant-icons.js')); // 优化引入 没生效`

不知道是不是vue封装的原因，我看官网推荐的只是分开打包，并没有去掉的一个插件
[⚠️ 1.2.0 之后我们全量引入了所有图标，导致 ant-design-vue 默认的包体积有一定增加，我们会在不远的未来增加新的 API 来实现图标的按需使用，更多相关讨论可关注：#12011。在此之前，你可以通过来自社区同学的 webpack 插件将图标文件拆分。](https://www.antdv.com/components/icon-cn/#components-icon-demo-two-tone-icon-and-colorful-icon)
