### ISSUE TITLE
请问在WebStorm中如何获得代码提示？

### ISSUE THREAD

**Issue by l619534951** [vueComponent/ant-design-vue#3191]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
其实现在用的是IDEA，在准备从iview迁移到ant-design-vue，准备开始的时候发现没有代码提示...

### What does the proposed API look like?
可否在构建的时候生成web-types.json 用来支持webstorm的代码提示

**Comment by sendya** [comment]
欢迎 PR

**Comment by l619534951** [comment]
> 欢迎 PR

哈哈，试一下一晚上，实在不会这方面的，只会用用...先放弃这个想法吧

**Comment by l619534951** [comment]
临时解决方案[https://github.com/l619534951/ant-design-vue-web-types](url)

**Comment by l619534951** [comment]
临时解决方案[https://github.com/l619534951/ant-design-vue-web-types](url)

**Comment by l619534951** [comment]
> 欢迎 PR
已经发起PR了，第一次发PR不知道对不对，有时间麻烦看一下。

**Comment by InsHomePgup** [comment]
所以你们解决了嘛？每次commit的时候都会提示。。warning

**Comment by zkwolf** [comment]
最新版里加了web-types.json的打包 https://unpkg.com/browse/ant-design-vue@2.1.2/vetur/web-types.json

**Comment by rmlzy** [comment]
mark

**Comment by ToPoGK** [comment]
> 最新版里加了web-types.json的打包 https://unpkg.com/browse/ant-design-vue@2.1.2/vetur/web-types.json

里面还是缺少一些标签a-layout-header，a-layout-header，a-layout-content，a-layout-footer，a-row,a-col,a-descriptions-item ,可能还有其他的，能不能补齐啊， 谢谢!
