### ISSUE TITLE
table希望增加属性表格

### ISSUE THREAD

**Issue by KeithGis** [vueComponent/ant-design-vue#3195]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Propertygrid可以解决表头在左边，右边展示对应的信息，可以参考https://www.jeasyui.net/plugins/184.html

### What does the proposed API look like?
win10 、主流浏览器、vue2.0

**Comment by tangjinzhou** [comment]
没看懂  😓

**Comment by KeithGis** [comment]
你好，我的意思是表头不是在上方，而是展示成一列，我阐述的也许有问题，你可以看一下https://www.jeasyui.net/plugins/184.html&nbsp;&nbsp;&nbsp;,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月17日(星期二) 晚上10:02
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"梁若鹏"<1045660598@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] table希望增加属性表格 (#3195)





 
没看懂  �9�5
