### ISSUE TITLE
一些修改组件内属性后，页面更新后报错TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by wzohxia** [vueComponent/ant-design-vue#3196]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vite rc9 vue3.0.2  Chrome86.0.4240.75

### Reproduction link
[https://2x.antdv.com/components/form-cn/](https://2x.antdv.com/components/form-cn/)

### Steps to reproduce
```
<template>
  <a-form :model="form">
    <a-form-item label="测试" name="test">
      <a-input 
      allow-clear 
      v-model:value="form.test" />
    </a-form-item>
  </a-form>
</template>

<script>
import { reactive, defineComponent, toRefs } from 'vue'
export default defineComponent({
  name: 'App',
  setup() {
    const info = reactive({
      form: { test: '' },
    })

    return {
      ...toRefs(info),
    }
  },
})
</script>
```
1.保存运行之后
2.删除allow-clear 保存
![image](https://user-images.githubusercontent.com/22089141/99358790-fe5d8e80-28e8-11eb-998b-b64573809614.png)

试过tree  table也有这样的报错

### What is expected?
是否我这边设置的问题？

### What is actually happening?
不出现这种报错

**Comment by anncwb** [comment]
这个vue3.0.3发布就修复了

**Comment by anncwb** [comment]
或者让作者提前改下这个组件的问题应该也可以 https://github.com/vitejs/vite/issues/1021
