### ISSUE TITLE
ant design vue2.0如何遍历使用icon

### ISSUE THREAD

**Issue by wanlum** [vueComponent/ant-design-vue#3198]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.15

### Environment
safari

### Reproduction link
[https://2x.antdv.com/components/icon-cn/](https://2x.antdv.com/components/icon-cn/)

### Steps to reproduce
侧边栏 导航 图标想通过遍历来添加不同的图标

### What is expected?
侧边栏 导航 图标想通过遍历来添加不同的图标

### What is actually happening?
侧栏 导航 图标 想通过遍历添加不同的图标
<div class="icons-list">
<HomeOutlined />
<SettingFilled />
<SmileOutlined />
<SyncOutlined spin />
<SmileOutlined :rotate="180" />
<LoadingOutlined />
</div> 无法遍历组件

**Comment by tangjinzhou** [comment]
ref #3190

**Comment by mjw-git** [comment]
咋做丫

**Comment by wanlum** [comment]
我使用的是判断做的，特别不好，作者不认真@tangjingzhou

**Comment by mjw-git** [comment]
> 我使用的是判断做的，特别不好，作者不认真@tangjingzhou

结局了，给你的那篇issue #3190里有方法，使用component标签
