### ISSUE TITLE
a-textarea Component Custom className is not supported

### ISSUE THREAD

**Issue by Leconomy** [vueComponent/ant-design-vue#3199]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
<a-textarea
className='outview'
class='out'
id='output'
v-model:value='output'
/>
className  is invalid

### What does the proposed API look like?
<a-textarea
className='outview'
id='output'
v-model:value='output'
/>
so, I can set className。

**Comment by tangjinzhou** [comment]
Version


Environment


Reproduction link


Steps to reproduce


What is expected?


What is actually happening?
