### ISSUE TITLE
a-input如何设置 readonly

### ISSUE THREAD

**Issue by chenxianfei** [vueComponent/ant-design-vue#3201]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-input 设置为只读。 disabale 样式是灰色不想用这个设置。。怎么设置原生input的readonly

### What does the proposed API look like?
提供readonly

**Comment by ajuner** [comment]
<template>
  <a-input :readonly="true" placeholder="Basic usage" />
</template>
虽然是可以的但个人不建议使用，文档也没有这个方法，还是用disabled吧

**Comment by tangjinzhou** [comment]
readonly="readonly"   readonly是原生属性，要遵循html 语法 

<a-input :readonly="readonly" placeholder="Basic usage" />
