### ISSUE TITLE
select在大数据并且optionFilterProp设为children情况下搜索不出来的问题

### ISSUE THREAD

**Issue by tracy2zhang** [vueComponent/ant-design-vue#3204]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vue3.0.2

### Reproduction link
[https://stackblitz.com/edit/vue-bwvnid?file=src%2Fcomponents%2FHelloWorld.vue](https://stackblitz.com/edit/vue-bwvnid?file=src%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
给select大数据选项，optionFilterProp设为children，并搜索比较靠后的选项

### What is expected?
可以搜出指定的选项

### What is actually happening?
无数据

---
问题同  #3144 
fix了之后只在默认情况（optionFilterProp为value）下有效

**Comment by tangjinzhou** [comment]
我想要添加一个限制了 optionFilterProp 不能为 children了，因为懒加载，无法拿到真实未渲染的数据，你可以设置其他的值，参考： 
```html
<div>
    <a-select
      v-model:value="value"
      mode="multiple"
      style="width: 200px"
      placeholder="Please select"
      option-filter-prop="label"
      @change="handleChange"
    >
      <a-select-option v-for="(item, index) in options" :key="item.value" :label="item.label" :value="item.value">
        {{ item.label }}
      </a-select-option>
    </a-select>
  </div>
```
