### ISSUE TITLE
customRow 中 onClickSelf 没有触发

### ISSUE THREAD

**Issue by bowencool** [vueComponent/ant-design-vue#3207]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
"vue": "^3.0.2",      "ant-design-vue": "^2.0.0-rc.1",
chrome 86.0.4240.198

### Reproduction link
[https://2x.antdv.com/components/table-cn/](https://2x.antdv.com/components/table-cn/)

### Steps to reproduce
``` js
export function customRow(record) {
    return {
      onClickSelf() {
         ...
      },
    };
  }
```

### What is expected?
像onClick一样触发

### What is actually happening?
不会触发

**Comment by tangjinzhou** [comment]
你不能在 customRow 中配置修饰符事件，你可以使用 
onClick: withModifiers(handleClick, ["self"])

**Comment by tangjinzhou** [comment]
或者 
onClick: (e){
if(e. currentTarget === e.target) {

}
}
