### ISSUE TITLE
table tree  filter 无效

### ISSUE THREAD

**Issue by Litttle-butterfly** [vueComponent/ant-design-vue#3209]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue:2.6.10

### Reproduction link
[https://segmentfault.com/q/1010000018845381?utm_source=sf-similar-question](https://segmentfault.com/q/1010000018845381?utm_source=sf-similar-question)

### Steps to reproduce
table tree 中过滤某个字段的值 页面table列没消失

### What is expected?
消失呗还能咋

### What is actually happening?
你说呢

**Comment by tangjinzhou** [comment]
提供有效的复现示例
