### ISSUE TITLE
为什么把/docs删掉？

### ISSUE THREAD

**Issue by aoping** [vueComponent/ant-design-vue#3214]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
无

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/package.json](https://github.com/vueComponent/ant-design-vue/blob/master/package.json)

### Steps to reproduce
无

### What is expected?
文档可以在源码里看到

### What is actually happening?
/docs目录被删除了

**Comment by wensonsmith** [comment]
这个问题我在 QQ 群问过

因为好多人把文档编译了放自己的网站上

antdv 去掉 docs 以后， 网站流量大， 广告也能赚点。 

开源很辛苦，赚的越多维护越好

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/vueComponent/ant-design-vue/issues/2800
