### ISSUE TITLE
select组件  自定义 后缀图标 不好点击之前版本会弹出下拉框,select组件加上label-in-value属性后浏览器崩溃

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue#3217]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
none

### Steps to reproduce
官网可以复现

### What is expected?
希望恢复之前功能

### What is actually happening?
select组件  自定义 后缀图标 不好点击之前版本会弹出下拉框

**Comment by tangjinzhou** [comment]
@xrkffgg https://github.com/ant-design/ant-design/issues/27479  没解决啊 ？

**Comment by xrkffgg** [comment]
我看 https://github.com/ant-design/ant-design/pull/23274 修复了呀

4.1.4 已经起作用了

https://codesandbox.io/s/tags-ant-design-demo-forked-lnyrs

**Comment by zkwolf** [comment]
后来可能给改丢了

**Comment by xrkffgg** [comment]
嗯，是挂了

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/27917#issuecomment-732807580

可能这是预期的。
