### ISSUE TITLE
date-picker   当设置valueFormat 为 "x"  mode为date时 返回的时间戳能否只有日期 不带时间

### ISSUE THREAD

**Issue by wzohxia** [vueComponent/ant-design-vue#3218]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有些场景的时间戳只需日期不带时间，这样比较的时候不需要进行先格式化后处理

### What does the proposed API look like?
返回值不带时间

**Comment by zkwolf** [comment]
你想要不包含时间的话valueFormat设成YYYY-MM-DD不就可以了吗

**Comment by wzohxia** [comment]
> 你想要不包含时间的话valueFormat设成YYYY-MM-DD不就可以了吗

后端需要传回时间戳格式

**Comment by zkwolf** [comment]
那就让后端去改吧，时间戳本来就是秒数啊
