### ISSUE TITLE
Icon component bind the class array, the bound class be the array subscript number

### ISSUE THREAD

**Issue by sendya** [vueComponent/ant-design-vue#322]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.1

### Environment
Windwos 10，Chrome71，Vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wy0vy4wj4w?module=%2Fsrc%2FApp.vue)

### Steps to reproduce
Icon 组件绑定 class 数组，被绑定的 class 变为数组下标数字。绑定 class 类对象时，无异常

### What is expected?
bind array class

### What is actually happening?
Class bind to subscript number

---
Icon 组件绑定 class 数组时，被绑定的 class 变为数组下标数字
![20181219225034](https://user-images.githubusercontent.com/5404542/50227481-c984ec00-03e0-11e9-949f-e5f652fc5820.png)

**Comment by tangjinzhou** [comment]
1.2.3 已修复
