### ISSUE TITLE
table small size should not has border

### ISSUE THREAD

**Issue by zhou881117** [vueComponent/ant-design-vue#3221]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
1.7.2

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-bordered](https://ant.design/components/table-cn/#components-table-demo-bordered)

### Steps to reproduce
table size:small  border:false

### What is expected?
not have border

### What is actually happening?
have border

**Comment by tangjinzhou** [comment]
这个small 样式 1.x 版本不再单独更新

**Comment by tangjinzhou** [comment]
这是一个破坏性更新

**Comment by zhou881117** [comment]
2.0 is ok?
