### ISSUE TITLE
Modal 弹出后会导致页面上滑（scrollTop 变成 0）

### ISSUE THREAD

**Issue by Calerme** [vueComponent/ant-design-vue#3226]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
windows10,Chrome,2.x

### Steps to reproduce
页面是可滚动的，但一调用  Modal 就会使页面滚动到顶部

### What is expected?
Fix it.

### What is actually happening?
Modal 导致页面返回顶部。

**Comment by John60676** [comment]
麻烦提供个可重现的demo
