### ISSUE TITLE
table fixed在缩放中行高会错位

### ISSUE THREAD

**Issue by zmmiffy** [vueComponent/ant-design-vue#3228]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.0

### Environment
Mac, chrome 87.0.4280.67, Vue 2.6.10

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
缩放页面

### What is expected?
自适应行高

### What is actually happening?
高度不会按照缩放计算

**Comment by tangjinzhou** [comment]
1.x 不再解决这个问题  2.x 后期会在高版本浏览器中解决
因为要用到到ie不兼容的特性
