### ISSUE TITLE
Tree树形控件设置checkStrictly=false时，如父节点为选中状态将会自动选中所有子节点

### ISSUE THREAD

**Issue by TengChongChong** [vueComponent/ant-design-vue#3229]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Tree树形控件设置checkStrictly=false时，如父节点为选中状态将会自动选中所有子节点，但是checkedKeys还是设置checkStrictly=false之前的选中状态，并不是checkStrictly=false时父节点选中自动选中子节点后的数据。有什么办法获取自动选中后的数据吗？

**Comment by ajuner** [comment]
是哪个版本的问题呀
2.x的话试试v-model:checkedKeys="checkedKeys"

**Comment by tangjinzhou** [comment]
所以这是个 feature 还是 bug ？  按照规范提交issue吧
