### ISSUE TITLE
Customising themes has no effect

### ISSUE THREAD

**Issue by TheFrogDaddy** [vueComponent/ant-design-vue#323]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.2

### Environment
Vue CLI-3

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/docs/vue/customize-theme/](https://vuecomponent.github.io/ant-design-vue/docs/vue/customize-theme/)

### Steps to reproduce
Add the following to vue.config.js

```
// vue.config.js
module.exports = {
  css: {
    loaderOptions: {
      less: {
        modifyVars: {
          'primary-color': '#1DA57A',
          'link-color': '#1DA57A',
          'border-radius-base': '2px',
        },
        javascriptEnabled: true
      }
    }
  }
}
```

### What is expected?
Change in theming

### What is actually happening?
Nothing at all

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/ant-design-vue/docs/vue/customize-theme/#Not-working?
![image](https://user-images.githubusercontent.com/6937879/50261108-02a37780-0446-11e9-8a84-e133d8c11507.png)

**Comment by sk0x0y** [comment]
Just install babel-plugin-import
