### ISSUE TITLE
In server-side rendering scenarios, using Icon components will report errors

### ISSUE THREAD

**Issue by duan602728596** [vueComponent/ant-design-vue#3230]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
antd-vue@>=2

### Reproduction link
[https://github.com/duan602728596/antd-vue-ssr-bug](https://github.com/duan602728596/antd-vue-ssr-bug)

### Steps to reproduce
* Run `npm run start`
* Open `http://127.0.0.1:5050/`
* The console will output
```
UnhandledPromiseRejectionWarning: ReferenceError: document is not defined
at insertCss (webpack-internal:///./node_modules/@ant-design/icons-vue/es/insert-css.js:26:73)
```

### What is expected?
When the Icon component is executed on the node side of ssr, there is no error.

### What is actually happening?
When the Icon component is executed on the node side of ssr, an error is reported because the document variable is not judged.

---
Wrong location: https://github.com/ant-design/ant-design-icons/blob/master/packages/icons-vue/src/utils.ts#L156

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/ant-design-icons/commit/99d24ba88efd694f92b0ed3c71d398fd70f39b84
