### ISSUE TITLE
rc1版本的menu菜单收缩和展开也太卡了

### ISSUE THREAD

**Issue by TothingWay** [vueComponent/ant-design-vue#3231]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
MacOS 10.15.7

### Reproduction link
[https://github.com/anncwb/vue-vben-admin/blob/main/CHANGELOG.zh_CN.md](https://github.com/anncwb/vue-vben-admin/blob/main/CHANGELOG.zh_CN.md)

### Steps to reproduce
1.后端返回路由列表，使用menu组件动态渲染菜单
2.打开chrome控制台，点击收缩，看到在body创建了很多menu-item相关组件
3.点击展开，会等待body中所有menu-item相关组件移除后再展开
4.收缩展开存在严重卡顿

这里链接是是v-ben-admin更新日志，其中提到这个卡顿，且降级了antd到beta15版本

### What is expected?
期望和收缩展开流畅不卡顿

### What is actually happening?
期望和收缩展开卡顿

**Comment by hj2060** [comment]
同样遇到了这个问题 横向导航子菜单在收缩的时候会有虚影 背景非白色时非常明显  1.x 版本就没有这个问题
