### ISSUE TITLE
input 组件 allowClear 时 focus 事件不能触发

### ISSUE THREAD

**Issue by 285858315** [vueComponent/ant-design-vue#3232]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l89o8)

### Steps to reproduce
https://codesandbox.io/s/l89o8

### What is expected?
触发 focus

### What is actually happening?
input 组件 allowClear 时 focus 事件不能触发

**Comment by John60676** [comment]
把 native 修饰符去掉就可以了
