### ISSUE TITLE
range-picker "allowClear" attributes do not work?

### ISSUE THREAD

**Issue by felixzhaoq** [vueComponent/ant-design-vue#3234]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
system：macos，browser：chrome86.0.4240.193，vue：2.6.11

### Reproduction link
[https://github.com/felixzhaoq/antd-bug/blob/main/datePickerBug.html](https://github.com/felixzhaoq/antd-bug/blob/main/datePickerBug.html)

### Steps to reproduce
range-picker of code：
<a-range-picker
:allowClear="false"
format="YYYY-MM-DD" />
1、select a date range
2、Move the mouse to the right of the text box
3、"clear" button shows

### What is expected?
"allowClear" attributes work properly

### What is actually happening?
"allowClear" attributes don't seem to work properly, and someone asked the same question in 2018, and latest version has same problem
If possible, please reply in Chinese. My English is terrible
如果有可能请用中文回复，俺的英文实在糟糕

**Comment by tangjinzhou** [comment]
如果在 html 中直接写 vue 模板，是不可以出现大写的  :allow-clear 试试
以及如果使用带有驼峰的事件，你需要安装 https://github.com/vueComponent/vue-dash-event
