### ISSUE TITLE
Upload应该可以限制文件数量

### ISSUE THREAD

**Issue by bowencool** [vueComponent/ant-design-vue#324]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
新选择的文件与已存在列表里的文件的个数总和超出限制，brforeUpload返回false，文件仍然会被添加进列表。

### What does the proposed API look like?
组件内部提供api，限制个数

**Comment by wangxueliang** [comment]
可以使用 fileList 对列表进行完全控制啊
ps: 希望能提供你遇到的问题demo(https://codesandbox.io/s/2wpk21kzvr)，更有利于定位问题

**Comment by bowencool** [comment]
虽然已经做好了，但还是觉得不够易用，所以就来提了个issue

**Comment by bowencool** [comment]
顺带一提，还有file.size同理

**Comment by bowencool** [comment]
``` js
   beforeUpload(file, fileList) {
      if (file.size > SIZE_LIMIT) {
        this.$message.warning('请选择小于3M的图片');
        return false;
      }
      return true;
    },
    handleChange({ fileList, file, event }) {
      if (file.size > SIZE_LIMIT) {
        return;
      }
      const newList = [...fileList];
      if (fileList.length > COUNT_LIMIT) {
        newList.length = COUNT_LIMIT;
        this.$message.warning(`最多${COUNT_LIMIT}张图`);
      }
      this.fileList = newList;
    },
```
![image](https://user-images.githubusercontent.com/20217146/50508346-77b52380-0abc-11e9-870f-93363bd89182.png)
这里去重就很难受了。。。

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/50510155-94088e80-0ac3-11e9-876f-950ae67fdd2d.png)
