### ISSUE TITLE
typescript error with template inline function params

### ISSUE THREAD

**Issue by weishijun14** [vueComponent/ant-design-vue#3247]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
macos chrome@lateset vue@3 typescript@3.9

### Steps to reproduce
```jsx
<div class="tag" :key="tag" v-for="tag in mapTags(text)">
  <a-checkable-tag
    @change="checked => handleSelectTags(tag, checked)" // Parameter 'checked' implicitly has an 'any' type.ts(7006)
  > 
  <a>
    {{ tag }}
  </a>
  </a-checkable-tag>
</div>
```

### What is expected?
```javascript
@change="checked => handleSelectTags(tag, checked)"
```
checked 不会有错误提示

### What is actually happening?
checked 参数 有ts 错误提示： Parameter 'checked' implicitly has an 'any' type.ts(7006)

**Comment by ajuner** [comment]
@weishijun14 
检查一下你的方法handleSelectTags是不是已经给传入的变量声明类型了
handleSelectTags(tag: string, checked: boolean)
另外你有装什么typescript编辑器的插件吗

**Comment by weishijun14** [comment]
@ajuner 
```javascript
const handleSelectTags = (tag: string, checked: boolean) => {
    if (checked) {
      ChartsData();
      }
    } else {
     
    }
  };
```

vscode extension : tslint v1.2.3

**Comment by ajuner** [comment]
![image](https://user-images.githubusercontent.com/53512912/100213120-3730df80-2f49-11eb-9453-ad87bb58df0c.png)
同个版本并未出现问题
提供个复现代码吧~

**Comment by ajuner** [comment]
问了下大佬，这个是template里的问题，跟库没关系

**Comment by weishijun14** [comment]
@ajuner 
我不知道是不是我编辑的问题。
按道理说 应该是像你那样正常。
但是我新建了一个vue3项目用vue cli.
还是一样报错。
![image](https://user-images.githubusercontent.com/20705423/100300835-d13c6a80-2fd1-11eb-93ac-869f352259df.png)

**Comment by weishijun14** [comment]
fix by remove this extension .....

You can close this issue , thx!

![image](https://user-images.githubusercontent.com/20705423/100301751-cbe01f80-2fd3-11eb-80c4-14f92d1e00c4.png)
