### ISSUE TITLE
DatePicker 组件点击清除值后，时间界面变回英文

### ISSUE THREAD

**Issue by qiaozhi520** [vueComponent/ant-design-vue#3248]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.3

### Environment
生产环境

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
使用datePicker 组件，allowClear=true，有value 值时，时间界面是中文，点击清除，时间界面变为英文，已全局配置  locale-provider，而且只有这个时间组件有问题，其他时间组件暂时没有发现这个问题

### What is expected?
正确显示配置语言

### What is actually happening?
没有正确显示

**Comment by qiaozhi520** [comment]
> Hello @qiaozhi520. Please provide a online reproduction by forking this [link](https://codesandbox.io/s/2wpk21kzvr) or a minimal GitHub repository.Make sure to choose the correct version.
> 
> 你好 @qiaozhi520, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://codesandbox.io/s/2wpk21kzvr) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

我发现这个bug产生的原因是  LocaleProvider 组件在router 组件 外造成的，我把LocaleProvider 组件放到router 组件里面后就可以了

**Comment by qiaozhi520** [comment]
![image](https://user-images.githubusercontent.com/37104175/100173869-55292080-2f06-11eb-8710-1e0e9bb83316.png)
我错了，我改了后好了一瞬间，然后其他地方的时间组件都出现问题了，再改回来，发现没有任何作用，这个汉化有些看不太懂

**Comment by qiaozhi520** [comment]
![image](https://user-images.githubusercontent.com/37104175/100175578-a4bd1b80-2f09-11eb-9f1d-d248fb4dbc4c.png)
![image](https://user-images.githubusercontent.com/37104175/100175591-a981cf80-2f09-11eb-9019-4bc1bb091610.png)
官方的文档也有这样的问题，有中文有英文

**Comment by xrkffgg** [comment]
https://github.com/vueComponent/ant-design-vue/issues/2527#issuecomment-655243284

**Comment by qiaozhi520** [comment]
最后找到原因是有其他引用的组件将moment 强制设置成了英文
