### ISSUE TITLE
input-number 设置 min 或者 precision 参数后，会在输入过程中不停格式化成错误的值

### ISSUE THREAD

**Issue by niceue** [vueComponent/ant-design-vue#3249]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
win10, Chrome 78, vue3.0.2

### Reproduction link
[https://2x.antdv.com/components/input-number-cn/#小数](https://2x.antdv.com/components/input-number-cn/#小数)

### Steps to reproduce
官网案例：小数
输入数字1

### What is expected?
输入框不应该格式化，而应该还是 1

### What is actually happening?
输入框的值格式化成了 1.0

**Comment by tangjinzhou** [comment]
应该只是 文档 有问题，具体使用没问题的

**Comment by niceue** [comment]
> 应该只是 文档 有问题，具体使用没问题的

不是的，是启动开发模式没问题，构建过后的就有问题。

我发现是因为 https://github.com/vueComponent/ant-design-vue/blob/next/components/vc-input-number/src/index.js#L280 这里的
```javascript
this.setState({
    focused: true,
});
```
没有生效，导致 onChange 里面 this.inputting 状态没生效，然后导致后面一直不停格式化。应该是 focus 事件的时机问题

**Comment by niceue** [comment]
开发模式无法重现这个问题，必须是构建后

**Comment by niceue** [comment]
@tangjinzhou 这个确实是Bug呀，而且还挺严重，用户不可能在开发模式用

**Comment by niceue** [comment]
目前临时这样修复了一下
![image](https://user-images.githubusercontent.com/1498854/100406944-1203b480-30a2-11eb-9645-025d2b62ebae.png)
