### ISSUE TITLE
customRender 无法渲染jsx  在vue3中   

### ISSUE THREAD

**Issue by noenif** [vueComponent/ant-design-vue#3251]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vue3    typescript

### Reproduction link
[https://antdv.com/components/table-cn/#%E8%A1%A8%E6%A0%BC%E8%A1%8C/%E5%88%97%E5%90%88%E5%B9%B6 无法实现效果](https://antdv.com/components/table-cn/#%E8%A1%A8%E6%A0%BC%E8%A1%8C/%E5%88%97%E5%90%88%E5%B9%B6 无法实现效果)

### Steps to reproduce
在vue3中,typescript 环境中,使用

### What is expected?
正常使用

### What is actually happening?
Invalid VNode type: undefined (undefined)
at <TableCell prefixCls="ant-table-row

**Comment by noenif** [comment]
他会返回两种问题,一种在我配置tsjson后,他直接报错
![image](https://user-images.githubusercontent.com/25174520/100025078-0ce50200-2e23-11eb-84e3-14dc723ad861.png)

另一种,我重启了一份vue3 的基础配置
![image](https://user-images.githubusercontent.com/25174520/100024982-da3b0980-2e22-11eb-98d0-e9c1b99a3a72.png)
![image](https://user-images.githubusercontent.com/25174520/100024989-de672700-2e22-11eb-8f56-4497fb6dbb60.png)

**Comment by John60676** [comment]
**JSX** 没配置对。如果对配置不熟悉的话，请使用 [vue-cli](https://v3.vuejs.org/guide/installation.html#cli) 搭建项目 **JSX** 没配置对。如果对配置不熟悉的话，请使用 [vue-cli](https://v3.vuejs.org/guide/installation.html#cli) 搭建项目
