### ISSUE TITLE
Layout组件无法正常显示

### ISSUE THREAD

**Issue by Mango0110** [vueComponent/ant-design-vue#3252]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
vue: ^3.0.0

### Reproduction link
[https://2x.antdv.com/components/layout-cn/](https://2x.antdv.com/components/layout-cn/)

### Steps to reproduce
使用官网案例（Layout组件：顶部-侧边布局-通栏 ）即可复现

### What is expected?
正常使用

### What is actually happening?
无法正常显示

---
会退版本到2.0.0-beta.13 可以正常使用

**Comment by Mango0110** [comment]
已解决

**Comment by Aimer-Fan** [comment]
> 已解决

你好，麻烦问下是怎么解决的。我最近也碰到这个问题了。我在 codesandbox 上复现了这个问题。https://codesandbox.io/embed/affectionate-chandrasekhar-djneh?fontsize=14&hidenavigation=1&theme=dark
