### ISSUE TITLE
The customRow property in A-table is not triggered

### ISSUE THREAD

**Issue by Stars-Star** [vueComponent/ant-design-vue#3253]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.1

### Environment
win10，firefox83.0，vue3.0.2，vue-cli4.5.8，ts3.9.3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/](https://github.com/vueComponent/ant-design-vue/)

### Steps to reproduce
```
<a-table
:row-selection="rowSelection"
:columns="columns"
:data-source="tabledata"
:rowKey="record => record.name"
:customRow="rowClick"
bordered
>
</a-table>

methods: {
rowClick(record, index){
return {
on: {
click: () => {
console.log('点击行内容record'   record);
console.log('序号索引index'   index);
}
}
}
},
}

```
### What is expected?
To work normally, click to get row data.

### What is actually happening?
Property not fired, unable to get data

---
Click the row and check the box to get the row data.This function is commonly used. Can it be encapsulated?

**Comment by Stars-Star** [comment]
It's settled. Sorry to bother you

**Comment by tangjinzhou** [comment]
use onClick instead on: {click}

**Comment by Stars-Star** [comment]
> 使用onClick代替：{click}

好的，非常感谢

**Comment by cs64188** [comment]
麻烦更新下2.x文档，感谢
