### ISSUE TITLE
级联选择组件，怎么将后台返回的地址字段渲染到页面？

### ISSUE THREAD

**Issue by EJairwin** [vueComponent/ant-design-vue#326]
级联选择组件：https://vuecomponent.github.io/ant-design-vue/components/cascader-cn/

相关代码截图：
http://pk2ej6olv.bkt.clouddn.com/test1.png
http://pk2ej6olv.bkt.clouddn.com/test2.png
http://pk2ej6olv.bkt.clouddn.com/tets3.png

**Comment by hilads** [comment]
你好 遇到了 同样的 问题 请问你 解决了？

**Comment by EJairwin** [comment]
> 你好 遇到了 同样的 问题 请问你 解决了？

解决了

**Comment by hilads** [comment]
@EJairwin  你的级联选择用的动态加载？  我先在遇到的问题是 页面表单回显设置 默认值 效果如下
![image](https://user-images.githubusercontent.com/46804595/57443879-98b72d80-7281-11e9-8438-824399e95a95.png)

**Comment by EJairwin** [comment]
> @EJairwin 你的级联选择用的动态加载？ 我先在遇到的问题是 页面表单回显设置 默认值 效果如下
> ![image](https://user-images.githubusercontent.com/46804595/57443879-98b72d80-7281-11e9-8438-824399e95a95.png)

目前不是，json格式的数据
![image](https://user-images.githubusercontent.com/32570960/57504599-ade69780-7327-11e9-831e-63bb57cee498.png)
有2个函数用于回显

**Comment by hilads** [comment]
@EJairwin  对 就是这样的 第一级省 是给死的  后面的 动态加载。我卡在回显的时候了，给表单传值 只能显示出省  你用的哪两个函数 回显的  loadData() ?  能发出来？

**Comment by EJairwin** [comment]
> @EJairwin 对 就是这样的 第一级省 是给死的 后面的 动态加载。我卡在回显的时候了，给表单传值 只能显示出省 你用的哪两个函数 回显的 loadData() ? 能发出来？

@hilads 我当时是省市区都没有回显，那个json也是放在本地的。好像是一个函数吧，自己弄的，不知道和你的情况是否类似
`export function areaCodeToCodes (code) {
  let codes = []
  codes.push(code.substring(0, 2) + '0000')
  codes.push(code.substring(0, 4) + '00')
  codes.push(code)
  return codes
}`

**Comment by hilads** [comment]
> > @EJairwin 对 就是这样的 第一级省 是给死的 后面的 动态加载。我卡在回显的时候了，给表单传值 只能显示出省 你用的哪两个函数 回显的 loadData() ? 能发出来？
> 
> @hilads 我当时是省市区都没有回显，那个json也是放在本地的。好像是一个函数吧，自己弄的，不知道和你的情况是否类似
> `export function areaCodeToCodes (code) { let codes = [] codes.push(code.substring(0, 2) + '0000') codes.push(code.substring(0, 4) + '00') codes.push(code) return codes }`

额 完全 跟我的不一样    areaCodeToCodes  自己定义的函数？ 能不能 把这个页面 发我一份 我联系上下文看看  1356074096@qq.com  多谢了

**Comment by EJairwin** [comment]
> > > @EJairwin 对 就是这样的 第一级省 是给死的 后面的 动态加载。我卡在回显的时候了，给表单传值 只能显示出省 你用的哪两个函数 回显的 loadData() ? 能发出来？
> > 
> > 
> > @hilads 我当时是省市区都没有回显，那个json也是放在本地的。好像是一个函数吧，自己弄的，不知道和你的情况是否类似
> > `export function areaCodeToCodes (code) { let codes = [] codes.push(code.substring(0, 2) + '0000') codes.push(code.substring(0, 4) + '00') codes.push(code) return codes }`
> 
> 额 完全 跟我的不一样 areaCodeToCodes 自己定义的函数？ 能不能 把这个页面 发我一份 我联系上下文看看 [1356074096@qq.com](mailto:1356074096@qq.com) 多谢了

@hilads   注意查收

**Comment by hilads** [comment]
> > > > @EJairwin 对 就是这样的 第一级省 是给死的 后面的 动态加载。我卡在回显的时候了，给表单传值 只能显示出省 你用的哪两个函数 回显的 loadData() ? 能发出来？
> > > 
> > > 
> > > @hilads 我当时是省市区都没有回显，那个json也是放在本地的。好像是一个函数吧，自己弄的，不知道和你的情况是否类似
> > > `export function areaCodeToCodes (code) { let codes = [] codes.push(code.substring(0, 2) + '0000') codes.push(code.substring(0, 4) + '00') codes.push(code) return codes }`
> > 
> > 
> > 额 完全 跟我的不一样 areaCodeToCodes 自己定义的函数？ 能不能 把这个页面 发我一份 我联系上下文看看 [1356074096@qq.com](mailto:1356074096@qq.com) 多谢了
> 
> @hilads 注意查收
好的 多谢了
