### ISSUE TITLE
浏览器引入antd-with-locales.min.js汉化不起作用antd.locales无内容

### ISSUE THREAD

**Issue by shaoming01** [vueComponent/ant-design-vue#3260]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
antd rc2，vue 3.0.3

### Steps to reproduce
1，浏览器引入antd-with-locales.min.js和vue.global.js
2，加入日期组件

### What is expected?
日期组件显示中文

### What is actually happening?
日期组件无法显示中文，antd.locales变量为空

beata10版本是OK的，更新到RC版本不行了。

**Comment by sendya** [comment]
引入之前先引入 moment.js 试试

**Comment by shaoming01** [comment]
正常引入了moment.js，之前的antd beta10版本都是OK的，更新到RC2不行了。
出问题的汉化是antd部分的中文，不仅是日期

**Comment by shaoming01** [comment]
> 引入之前先引入 moment.js 试试

正常引入了moment.js，之前的antd beta10版本都是OK的，更新到RC2不行了。
出问题的汉化是antd部分的中文，不仅是日期

**Comment by eMeab** [comment]
https://github.com/vueComponent/ant-design-vue/issues/3684 然后自己打包一份.
