### ISSUE TITLE
change demos from kebab-case to PascalCase

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vueComponent/ant-design-vue#3261]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

see https://vuejs.org/v2/style-guide/index.html#Component-name-casing-in-templates-strongly-recommended
 
> In most projects, component names should always be PascalCase in single-file components
> ...
> using kebab-case everywhere is also acceptable

It seems that it will be great if we change demo codes from from kebab-case to PascalCase

**Comment by tangjinzhou** [comment]
we will keep use kebab-case
```html
<!-- Everywhere -->
<my-component></my-component>
```

**Comment by xiaoxiangmoe** [comment]
@tangjinzhou Which should I use in jsx? Button or AButton? ( by `import { Button as AButton } from 'ant-design-vue'` )
