### ISSUE TITLE
提供 A 开头的组件名

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vueComponent/ant-design-vue#3264]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

现在的组件名都不带 prefix，比如 Button 组件等。我希望组件库能导出带 prefix 的组件名，比如 AButton。这样子我们在开发者工具中以及 jsx 中，以及 template 中，都可以用同样的组件名。

---

开发者工具：
![image](https://user-images.githubusercontent.com/8111351/100409897-0915e180-30a8-11eb-8230-64ae9ffb81c6.png)
模板或者 JSX
![image](https://user-images.githubusercontent.com/8111351/100409929-2480ec80-30a8-11eb-8917-e84698526eb2.png)
现在的 import
![image](https://user-images.githubusercontent.com/8111351/100409940-2ba7fa80-30a8-11eb-940d-f0743932a31a.png)

**Comment by tangjinzhou** [comment]
Button.name 就是 AButton 
直接 use(Button) 即可

**Comment by xiaoxiangmoe** [comment]
我的意思是：

因为 Button.name 就是 AButton,
antd 应该  `export {Button, Button as AButton}`
