### ISSUE TITLE
table同时使用列宽拉伸和排序时，拉伸列宽会触发排序事件

### ISSUE THREAD

**Issue by hjtjiajia** [vueComponent/ant-design-vue#3268]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
基于react的ant框架有这个功能，但vue版本没有，导致每次列宽拉伸时都触发排序事件，那么ant-design-vue的表格组件是否可以加上这个功能呢?谢谢!

### What does the proposed API look like?
希望列宽拉伸时不触发排序事件

**Comment by JokerAn** [comment]
Scrolling horizontally to the far right of the table table will also get stuck
横向滚动到最右侧table表格还会卡死
