### ISSUE TITLE
IconTwoTone的twoToneColor不生效

### ISSUE THREAD

**Issue by athenadorer** [vueComponent/ant-design-vue#3270]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
Windows10家庭中文版 x64 v1909 18363.1198; Chromium 78.0.3904.108; Vue@3.0.3

### Reproduction link
[https://2x.antdv.com/components/icon-cn/#components-icon-demo-two-tone-icon-and-colorful-icon](https://2x.antdv.com/components/icon-cn/#components-icon-demo-two-tone-icon-and-colorful-icon)

### Steps to reproduce
```<CheckCircleTwoTone two-tone-color="#52c41a" />```

### What is expected?
图标主要颜色变为指定颜色

### What is actually happening?
图标主要颜色是默认颜色

---
path.anticon的two-tone-color属性为"#52c41a"，path.anticon > svg > path中的fill属性仍然是默认值。
除了twoToneColor属性，其他参数(如rotate)可以正常生效。
通过Icon.setTwoToneColor(colorString)设置颜色可以正常生效。

**Comment by John60676** [comment]
使用**CamelCase**传参
`<CheckCircleTwoTone twoToneColor="#52c41a" />`
