### ISSUE TITLE
在使用自定义滚动条的场景下，页面出现滚动条时，且滚动条宽度小于13px时，弹窗组件弹出页面右侧会出现白边

### ISSUE THREAD

**Issue by linxiaowang** [vueComponent/ant-design-vue#3272]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
"vue": "^2.6.11",     "ant-design-vue": "^1.6.2",

### Reproduction link
[https://2x.antdv.com/components/modal-cn/](https://2x.antdv.com/components/modal-cn/)

### What is expected?
在使用自定义滚动条的场景下，页面出现滚动条时，且滚动条宽度小于13px时，弹窗组件弹出页面白边不出现

### What is actually happening?
在使用自定义滚动条的场景下，页面出现滚动条时，且滚动条宽度小于13px时，弹窗组件弹出页面右侧会出现白边，页面会抖动

**Comment by ly616187030** [comment]
请问解决了吗？我页遇到这样的问题了
