### ISSUE TITLE
文本域（a-textarea）内联class、style被吞

### ISSUE THREAD

**Issue by Small-Shu** [vueComponent/ant-design-vue#3273]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/input-cn/#components-input-demo-textarea](https://2x.antdv.com/components/input-cn/#components-input-demo-textarea)

### Steps to reproduce
``` html
<template>
<!-- 1.当前textarea宽度不为45% -->
<a-textarea class="w-45" v-model:value="value" />
<!-- 2.当前textarea宽度不为45% -->
<a-textarea v-model:value="value" style="width: 45%" />
<!-- 3.通过文档级的css进行渲染为45% -->
<a-textarea v-model:value="value" />
</template>
```

``` javascript
<script>
export default {
data() {
return {
value: "",
};
},
};
</script>
```

``` css
<style lang="scss" scoped>
.w-45 {
width: 45%;
}

textarea:nth-child(3) {
width: 45%;
}
</style>
```

### What is expected?
解决内联class和style被吞服问题。

### What is actually happening?
解决内联class和style被吞服问题。

**Comment by zkwolf** [comment]
下个版本修复
