### ISSUE TITLE
提供 A 开头的组件名的导出

### ISSUE THREAD

**Issue by xiaoxiangmoe** [vueComponent/ant-design-vue#3276]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

现在的组件只导出了 Button 等不带 prefix 的。我希望组件库能导出带 prefix 的组件名，比如 AButton。

现在组件库：
```js
export {Button}
```
见： https://github.com/vueComponent/ant-design-vue/blob/67942e4ff437cb9182694202545cc55c2929bd58/components/index.ts#L245

我希望：

```js
export {Button, Button as AButton};
```

相关 issue：
https://github.com/vueComponent/ant-design-vue/issues/3264

**Comment by Amour1688** [comment]
这样做的理由是啥

**Comment by xiaoxiangmoe** [comment]
这样做的好处是：
我们在开发者工具中以及 jsx 中，以及 template 中，都可以用同样的组件名。

开发者工具：
![image](https://user-images.githubusercontent.com/8111351/100409897-0915e180-30a8-11eb-8230-64ae9ffb81c6.png)
模板或者 JSX
![image](https://user-images.githubusercontent.com/8111351/100409929-2480ec80-30a8-11eb-8917-e84698526eb2.png)

**Comment by Amour1688** [comment]
那其实你自己也可以 as 一下

**Comment by xiaoxiangmoe** [comment]
@Amour1688 如果自己 as，就会导致没法用 IDE 的 auto import。如果 ant-design-vue 能写一下，我写 ABu 就会自动帮忙 auto import 并且补全

**Comment by xiaoxiangmoe** [comment]
@Amour1688 请问我能提一个 PR 吗？这样子 export 的 component 的 标识符 和 name 就能相同了

**Comment by sendya** [comment]
// my-component.js
import { Button, Input } from 'ant-design-vue'

export {  Button as AButton, Input as AInput }

**Comment by sendya** [comment]
组件名包含打算改成 AButton 这样的 导出名，**不然在 JSX 中实在太丑了**。
vue 也没规定 template 的 component name 名字一定要跟导出名相同
