### ISSUE TITLE
Modal transition bug

### ISSUE THREAD

**Issue by oleksii-shaposhnikov** [vueComponent/ant-design-vue#3277]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-monad-6rvyz?file=/src/App.vue)

### Steps to reproduce
1. Open the modal by clicking on "modal" btn
2. See that no transition (animation) appears

### What is expected?
The animation (as in the docs) appeats

### What is actually happening?
The animation is not working for the modal component when importing as `import Modal from "ant-design-vue/lib/modal/style.css"`

**Comment by HomyeeKing** [comment]
样式没引入

**Comment by oleksii-shaposhnikov** [comment]
> 样式没引入

```
import Modal from "ant-design-vue/lib/modal";
import "ant-design-vue/lib/modal/style/index.css";
```

Is that not enough?

**Comment by John60676** [comment]
you can install `babel-plugin-import`, it will automatically import stylesheets
https://2x.antdv.com/docs/vue/introduce/#Use-modularized-antd

**Comment by HomyeeKing** [comment]
@oleksii-shaposhnikov  [read carefully from start, U will find out 🧐](https://2x.antdv.com/docs/vue/getting-started/)

btw, can't u find that your  modal has no style

![image](https://user-images.githubusercontent.com/49113249/100742230-6b0e7800-3415-11eb-8578-f6670caade90.png)
![image](https://user-images.githubusercontent.com/49113249/100742264-7792d080-3415-11eb-9fbd-8e5aeba9e8f7.png)
