### ISSUE TITLE
Tree使用reactive声明的expandedKeys无法展开

### ISSUE THREAD

**Issue by Atlas-lili** [vueComponent/ant-design-vue#3278]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/tree-cn/](https://2x.antdv.com/components/tree-cn/)

### Steps to reproduce
```
<template>
<a-tree
:tree-data="treeData"
v-model:expanded-keys="expandedKeys"></a-tree>
</template>
```

```
<script lang="ts">
import { defineComponent, reactive } from 'vue';
const TREEDATA = [{
key: '1',
title: '1',
children: [{
key: '1-1',
title: '1-1',
children: []
}, {
key: '1-2',
title: '1-2',
children: []
}]
}];
export default defineComponent({
setup() {
const treeData = reactive(TREEDATA);
const expandedKeys = reactive(['1']);
return {
treeData,
expandedKeys
}
}
});
</script>
```

### What is expected?
期望使用reactive生成expandedKeys可以与树的展开/收缩同步。

### What is actually happening?
页面上的树会以expandedKeys做默认展开，但是无法进行展开/收缩操作（点击无响应）。

---
```const expandedKeys = reactive(['1']);```换为```const expandedKeys = ref(['1']);```就可以正常进行展开/收缩操作了，但是数组数据应使用```reactive```包装吧。

**Comment by ajuner** [comment]
reactive返回的是对象的响应式副本，这个方法会把数组转成对象

**Comment by Atlas-lili** [comment]
> 转
expandedKeys不应该使用```reactive```生成的数组响应式副本？

**Comment by ajuner** [comment]
我个人认为是不应该的
毕竟是拿数组去做遍历而不是对象
