### ISSUE TITLE
menuitem按需加载，类名为undefined-item

### ISSUE THREAD

**Issue by shifeng1993** [vueComponent/ant-design-vue#3279]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
macos11.0.1, chrome87,vue3.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
1. 按需加载引入menu，import {Menu} from 'ant-design-vue';
2. app.use(Menu);
3. 在template内新增一个menu 嵌套menuitem
4. 浏览器dom中，menuitem的classname 为 ‘undefined-item’;

### What is expected?
正常显示ant-menu-item

### What is actually happening?
显示undefined-item

        
<img width="1676" alt="antdv-bug" src="https://user-images.githubusercontent.com/20181287/100540131-4e880980-3276-11eb-933e-7c6fcbbb97df.png">

**Comment by redsanjin-1** [comment]
相同问题，查看 [3256](https://github.com/vueComponent/ant-design-vue/issues/3256)

**Comment by wu007kun** [comment]
同样的问题。我是完整引入的，在一个空白页面中把示例代码完整复制过来，ant-menu下所有元素的类名开头都是undefined

**Comment by junhuafly** [comment]
我在使用render 渲染这个Menu 以及MenuItem,SubMenu 时 也是出现这问题，在渲染MenuItem这个组件下样式出现undefined-item,实际上应该是ant-menu-item

**Comment by zkwolf** [comment]
给个复现demo？

**Comment by ajuner** [comment]
vue升级到 3.0.2+ 试试

**Comment by wu007kun** [comment]
> vue升级到 3.0.2+ 试试

解决
