### ISSUE TITLE
项目使用babel-plugin-import没有起到按需加载样式的效果

### ISSUE THREAD

**Issue by carmel** [vueComponent/ant-design-vue#3281]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
macos 10.15.6 ，node v14.15.1 ,vue :3.0.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3280](https://github.com/vueComponent/ant-design-vue/issues/3280)

### Steps to reproduce
package.json
![package.json](https://user-images.githubusercontent.com/36031579/100549001-57470280-32ab-11eb-994e-68752582852e.png)
babel配置
![](https://user-images.githubusercontent.com/36031579/100549010-6332c480-32ab-11eb-9ffa-cd68ab190041.png)
vite.config
![](https://user-images.githubusercontent.com/36031579/100549026-7cd40c00-32ab-11eb-9752-30b5c68210fb.png)
页面代码
![](https://user-images.githubusercontent.com/36031579/100549051-9f662500-32ab-11eb-9f01-dba03b30da74.png)
页面效果
![](https://user-images.githubusercontent.com/36031579/100549061-aee56e00-32ab-11eb-9647-eddcb6d5f06a.png)
官网指导链接：https://2x.antdv.com/docs/vue/getting-started-cn/
![](https://user-images.githubusercontent.com/36031579/100549151-2e733d00-32ac-11eb-8e09-40b9220fcabd.png)

### What is expected?
https://github.com/vueComponent/ant-design-vue/issues/3280

### What is actually happening?
https://github.com/vueComponent/ant-design-vue/issues/3280

**Comment by zkwolf** [comment]
vite就不支持babel吧 https://github.com/vitejs/vite/issues/491

**Comment by carmel** [comment]
谢谢，明白了。但还遇到一个问题，我在项目main.js中并没有一次加载antd-vue所有组件：

![image](https://user-images.githubusercontent.com/36031579/100948861-bfb01100-3543-11eb-93a9-dd3e817fbbbd.png)

而是在一个vue-component中引入了一个Button：
![image](https://user-images.githubusercontent.com/36031579/100948925-e9693800-3543-11eb-90c8-91871a041b1f.png)

但项目起来后，浏览器console中打印了如下信息：

> You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
(anonymous) @ ant-design-vue.js:79490
请问，是我做错了什么吗？

**Comment by wingsico** [comment]
may be you can try it: [vite-babel-plugin](https://www.npmjs.com/package/vite-babel-plugin)

**Comment by zch233** [comment]
@carmel 我也遇到了，解决了吗？

**Comment by carmel** [comment]
> @carmel 我也遇到了，解决了吗？

没有解决呐，`issue closed`状态时作者可能不会有通知的

**Comment by zkwolf** [comment]
@carmel 你上面那个问题也不算误报吧，没有用babel-import-plugin的话就没有按需加载效果了，自然就有提示

**Comment by zch233** [comment]
@zkwolf 老哥，vite 怎么配置，

**Comment by psaren** [comment]
@zch233 
try to use [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp) for vite 2.x
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import vitePluginImp from 'vite-plugin-imp'

export default defineConfig({
  plugins: [
    vue(), 
    vitePluginImp({
      libList: [
        {
          libName: 'ant-design-vue',
          style(name) {
            return `ant-design-vue/es/${name}/style/index.css`
          }
        },
      ]
    })
  ]
})

```

**Comment by qiuquanwu** [comment]
https://blog.csdn.net/qq_38494372/article/details/112913555

**Comment by morelearn1990** [comment]
> @zch233
> try to use [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp) for vite 2.x
> 
> ```js
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> import vitePluginImp from 'vite-plugin-imp'
> 
> export default defineConfig({
>   plugins: [
>     vue(), 
>     vitePluginImp({
>       libList: [
>         {
>           libName: 'ant-design-vue',
>           style(name) {
>             return `ant-design-vue/es/${name}/style/index.css`
>           }
>         },
>       ]
>     })
>   ]
> })
> ```

vitePluginImp 没法解决驼峰命名的组件，会将驼峰命名转换为小写会找不到对应的组件文件夹，比如
import { ConfigProvider } from "ant-design-vue";
会将 ConfigProvider 转换为 configprovider 但是真实文件夹是 config-provider 会导入报错

**Comment by morelearn1990** [comment]
> https://blog.csdn.net/qq_38494372/article/details/112913555

按照文中的配置
```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import styleImport from "vite-plugin-style-import";

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        vue(),
        styleImport({
            libs: [
                {
                    libraryName: "ant-design-vue",
                    esModule: true,
                    resolveStyle: (name) => {
                        return `ant-design-vue/es/${name}/style/index.less`;
                    },
                },
            ],
        }),
    ],
    css: {
        preprocessorOptions: {
            less: {
                modifyVars: {
                    "primary-color": "#1DA57A",
                    "link-color": "#1DA57A",
                    "border-radius-base": "2px",
                },
                javascriptEnabled: true,
            },
        },
    },
});

```

再配合 less 的 modifyVars 还能解决 ant-design-vue 的主题定制的问题

**Comment by psaren** [comment]
> > @zch233
> > try to use [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp) for vite 2.x
> > ```js
> > import { defineConfig } from 'vite'
> > import vue from '@vitejs/plugin-vue'
> > import vitePluginImp from 'vite-plugin-imp'
> > 
> > export default defineConfig({
> >   plugins: [
> >     vue(), 
> >     vitePluginImp({
> >       libList: [
> >         {
> >           libName: 'ant-design-vue',
> >           style(name) {
> >             return `ant-design-vue/es/${name}/style/index.css`
> >           }
> >         },
> >       ]
> >     })
> >   ]
> > })
> > ```
> 
> vitePluginImp 没法解决驼峰命名的组件，会将驼峰命名转换为小写会找不到对应的组件文件夹，比如
> import { ConfigProvider } from "ant-design-vue";
> 会将 ConfigProvider 转换为 configprovider 但是真实文件夹是 config-provider 会导入报错


@morelearn1990 update [vite-plugin-imp](https://www.npmjs.com/package/vite-plugin-imp) to v2.0.4 !

**Comment by maixing** [comment]
有可能less版本高的问题，我的配置，现在可以实现按需加载

vue.config.js配置
module.exports = {
    css: {
        loaderOptions: {
          less: {
            javascriptEnabled: true
          }
        }
}
babel.config.js配置
plugins: [
    [
      'import',
      {
        libraryName: "ant-design-vue",
        libraryDirectory: "es",
        style: true
      }
    ]
  ],

**Comment by JinPengGeng** [comment]
借楼问一下，有做IE11兼容吗？ 能给个例子啥的吗

**Comment by zkwolf** [comment]
vue3现在也不兼容ie11吧

**Comment by JinPengGeng** [comment]
antd-vue 文档说的可是最低兼容IE11，但是没有使用Vite来做兼容的例子。。。。

**Comment by joker77877** [comment]
> vite就不支持babel吧 [vitejs/vite#491](https://github.com/vitejs/vite/issues/491)

vite是支持babel的，rollup的babel插件
