### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by oimmc** [vueComponent/ant-design-vue#3282]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
mac vue3.0 chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
<a-select v-model:value="'1'" size="large" placeholder="请选择" @change="Change">

Unable to preventDefault inside passive event listener invocation.

### What is expected?
no error

### What is actually happening?
Unable to preventDefault inside passive event listener invocation.

**Comment by white-007** [comment]
I have the same problem as you, vuejs version 3.0.3

**Comment by jinghuiyiwang** [comment]
same here

**Comment by hdtopku** [comment]
same problem with me

**Comment by white-007** [comment]
Hi, I noticed that the error was caused by the introduction of the 'default-passive-events' library, not the ant-disgn-vue problem，I have updated the online link of codesandbox.

**Comment by tangjinzhou** [comment]
ref #142
