### ISSUE TITLE
TimePicker component's trigger input doesn't watch for changes / doesn't call modal

### ISSUE THREAD

**Issue by a1tern4tive** [vueComponent/ant-design-vue#3283]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
Chrome 86, Vue 2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-hxtq2?file=/src/App.vue)

### Steps to reproduce
1. Focus with tab button or select input's value with mouse (click and select text and up mouse key outside of input) and try to change the value.
2. After that trigger TimePicker's modal by clicking on input.

### What is expected?
I expected that trigger input (which was selected by focus or mouse) will call the modal with Hours/Minutes/Seconds or will listen to changes.

### What is actually happening?
By clicking on trigger value it will change to defaultValue if it was defined or to value was chosen before.

---
For example React version (https://ant.design/components/time-picker) works well.

**Comment by Waserman** [comment]
The problem is that you are unable to change the value of the `TimePicker`?
Do you work with `dayjs` or `moment`?

**Comment by microboat** [comment]
同样的问题，当TimePicker的值是手动输入，而不是从下拉框中选择时，不会触发change事件。
