### ISSUE TITLE
获取table中选中行的长度 

### ISSUE THREAD

**Issue by Stars-Star** [vueComponent/ant-design-vue#3284]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
获取table选中行的长度，判断长度值。

### What does the proposed API look like?
this.$refs.selectedRowKeys.length

**Comment by zkwolf** [comment]
可以自己定义一个selectedRowKeys在onChange的时候赋值就行，参考

https://antdv.com/components/table-cn/#%E9%80%89%E6%8B%A9%E5%92%8C%E6%93%8D%E4%BD%9C

**Comment by Stars-Star** [comment]
> 可以自己定义一个selectedRowKeys在onChange的时候赋值就行，参考
> 
> https://antdv.com/components/table-cn/#%E9%80%89%E6%8B%A9%E5%92%8C%E6%93%8D%E4%BD%9C

我尝试着在computed中写了如下内容 ：
computed: {
    rowSelection() {
 return {
 // 在model层改变当前页，传给后台更新当前页数据.
 onChange: (selectedRowKeys, selectedRows) => {
  this.selectedRowKeys = selectedRowKeys;
  console.log(`selectedRowKeys------: ${this.selectedRowKeys}`);
  this.$message.success(JSON.stringify(selectedRows));
 },
 getCheckboxProps: record => ({
  props:{
   defaultChecked: record.name=== this.tabledata[0].name
  },
  name: record.name,
  }),
  };
     },
},
在methods中写了如下内容：
editShowModal(){
if (this.$refs.selectedRowKeys.length === 0) {
        this.$message.warning('请至少选择一条要编辑的数据');
        return false;
     } else {
 this.editvisible = true;
     }
},
但是，我不知道该如何整才能在editShowModal获取onChange中的selectedRowKeys，或是在onChange中获取editShowModal中的内容。
