### ISSUE TITLE
switch只支持true和false，实际场景会是数字1，2或者0。希望和iview类似，能属性里直接支持转化

### ISSUE THREAD

**Issue by mengguagua** [vueComponent/ant-design-vue#3288]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
节省代码，更快速开发

### What does the proposed API look like?
true-value	选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用	String, Number, Boolean	true
false-value	没有选中时的值，当使用类似 1 和 0 来判断是否选中时会很有用	String, Number, Boolean	false

**Comment by Amour1688** [comment]
针对属性的类型设计，我们稍微会比较严谨， switch 作为开关，有 true 和 false 更加严谨，其他的业务逻辑应当自己实现
