### ISSUE TITLE
select组件在手机上体验糟糕：多个option想要滑动进行选择，只能通过右侧的滚动条才行

### ISSUE THREAD

**Issue by xjchenhao** [vueComponent/ant-design-vue#3290]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
ios、安卓

### Reproduction link
[https://2x.antdv.com/components/select-cn/](https://2x.antdv.com/components/select-cn/)

### Steps to reproduce
直接打开官方文档就可以测试哦。

### What is expected?
option的列表上捕捉手指滑动事件。

### What is actually happening?
只能通过右侧的滚动条才行。

**Comment by ajuner** [comment]
https://antdv.com/docs/vue/faq-cn/#ant-design-vue-%E5%9C%A8%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%BD%93%E9%AA%8C%E4%B8%8D%E4%BD%B3%E3%80%82

**Comment by xjchenhao** [comment]
ok,我就是看到提个醒。
