### ISSUE TITLE
数字输入框bug

### ISSUE THREAD

**Issue by duxinyuan1517** [vueComponent/ant-design-vue#3293]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
vue cli

### Reproduction link
[https://www.baidu.com?whatIWantToSay=没有链接，官方组件就是一个有bug的](https://www.baidu.com?whatIWantToSay=没有链接，官方组件就是一个有bug的)

### Steps to reproduce
数字输入框在输入小数点的时候会出现两个小数点

### What is expected?
正常使用

### What is actually happening?
正常使用

**Comment by tangjinzhou** [comment]
ref #3249

**Comment by duxinyuan1517** [comment]
抱歉，那个问题是我一次偶然遇到的，后面刷新页面之后也没有出现过，在之前的操作中，并没有直接去操作html和css，因此可能是一个偶发性的bug，如果后面我再次遇到，会研究一下出现的原因和情况，及时反馈给你们。
Thanks for your answer
