### ISSUE TITLE
Component emitted event "update:visible" but it is neither declared in the emits option nor as an "onUpdate:visible" prop.

### ISSUE THREAD

**Issue by wwj007176** [vueComponent/ant-design-vue#3294]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue3.0.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
使用下拉菜单的时候 就会出现警告

### What is expected?
不出现警告

### What is actually happening?
onVisibleChange	@	Dropdown.js?05a8:89

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/pull/3237 已经修复，等待发布
