### ISSUE TITLE
notification 带icon时，methods不同的定义出现问题

### ISSUE THREAD

**Issue by caiyl1314** [vueComponent/ant-design-vue#3295]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue：2.5.17，win10，chrome：86.0.4240.75(64 位)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-s8jpk?file=/src/App.vue)

### Steps to reproduce
分别点击“Open the notification box1”和“Open the notification box2”

### What is expected?
效果一致，先alert出对应按钮，然后弹出带图标的通知

### What is actually happening?
1、按钮1，先alert出对应按钮，然后弹出带图标的通知
2、按钮2，先alert出对应按钮，然后console报错index.js:27 ReferenceError: h is not defined （如果notification 的config中不包含icon属性则能正常显示）

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-7vd80?file=/src/App.vue

use h=><a-icon>
