### ISSUE TITLE
设置全局getPopupContainer，table 固定最右边列，里面的popconfirm 宽度不对

### ISSUE THREAD

**Issue by Kunkka0229** [vueComponent/ant-design-vue#3297]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
antd 1.7.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-dskgg?file=/src/App.vuehttps://codesandbox.io/s/vue-antd-template-forked-dskgg?file=/src/App.vue)

### Steps to reproduce
设置全局getPopupContainer，table 固定最右边列，里面的popconfirm 宽度不对

### What is expected?
设置全局getPopupContainer，table 固定最右边列，里面的popconfirm 宽度不对

### What is actually happening?
设置全局getPopupContainer，table 固定最右边列，里面的popconfirm 宽度不对

**Comment by Kunkka0229** [comment]
https://codesandbox.io/s/vue-antd-template-forked-dskgg?file=/src/App.vue

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-jdt71?file=/src/App.vue
添加css 
```css
.ant-table-fixed-right {
overflow: unset;
}
```
and
:overlayStyle="{ width: '200px' }"
