### ISSUE TITLE
input-number 在使用formatter、parser在谷歌浏览器输入4位数字后会重复出现多位数

### ISSUE THREAD

**Issue by smallchicken** [vueComponent/ant-design-vue#3298]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
window10， Chrome

### Reproduction link
[https://www.antdv.com/components/input-number-cn/](https://www.antdv.com/components/input-number-cn/)

### Steps to reproduce
当使用a-input-number的:formatter时, 将输入法切换为微软 中文, 在符号后面输入数字时会回填两个相同的数字
例如官方formatter的方法, :输入1234，会自动变成1,2344

### What is expected?
正常输出输入的数字

### What is actually happening?
输入1234，会自动变成1,2344，之后没输入一位都补出2位数

**Comment by smallchicken** [comment]
只要符合window10的电脑，输入法用默认微软中文的，官方demo就可以100%浮现这个问题。
![image](https://user-images.githubusercontent.com/21360019/100972619-09185480-3574-11eb-88a3-32a14113328f.png)

**Comment by codesyofo** [comment]
> Hello @smallchicken. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository.Make sure to choose the correct version.
> 
> 你好 @smallchicken, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

目前在win10输入法是中文时，antdv [1.x](https://www.antdv.com/components/input-number-cn/#components-input-number-demo-formatter) 和 [2.x](https://2x.antdv.com/components/input-number-cn/#components-input-number-demo-formatter) 都会出现双击现象，英文没有

**Comment by zkwolf** [comment]
win10我没复现出来

**Comment by jimole775** [comment]
win10 + chrome-v87.0.4280.88 + 微软中文输入法可以复现
