### ISSUE TITLE
请问如何在less中引入当前主题色呢？

### ISSUE THREAD

**Issue by xx6822** [vueComponent/ant-design-vue#330]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
尝试在less中引入当前主题色来定义一些组件的样式，但是失败了

### What does the proposed API look like?
import 'xxx.less';

button {
color:  @primary-color;
border:  1px solid @primary-color;
}

**Comment by tangjinzhou** [comment]
信息过少，无法提供帮助。
对于less的使用可以查看官方文档，
如果是定制主题，组件文档中有详细的定制主题教程。
