### ISSUE TITLE
2.x: form组件使用 useForm 无法校验表单

### ISSUE THREAD

**Issue by wuazhu** [vueComponent/ant-design-vue#3304]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
node> 10, chrome>87, vue@3.0.3

### Reproduction link
[https://2x.antdv.com/components/form-cn/#useForm-%E5%9F%BA%E6%9C%AC%E8%A1%A8%E5%8D%95](https://2x.antdv.com/components/form-cn/#useForm-%E5%9F%BA%E6%9C%AC%E8%A1%A8%E5%8D%95)

### Steps to reproduce
直接扒官网实例放入代码中, 控制台显示校验错误, 并且报错, 但是界面没有校验错误提示

### What is expected?
界面提示

### What is actually happening?
没有提示

**Comment by gee1k** [comment]
一样

**Comment by tangjinzhou** [comment]
删除 node_modules 及 lock 文件  重新安装

**Comment by wuazhu** [comment]
@tangjinzhou 
> 删除 node_modules 及 lock 文件 重新安装


**当 input blur 的时候无法自动完成校验**
> 操作步骤: 所有输入框不输入的状态下点击提交,  显示错误, 这时候在去填写, 无法自动完成校验, 错误并未去除
```js
const checkFans = (rule, value) => {
    if (!value) {
      return Promise.reject('请输入粉丝数')
    }
    if (!validateFans(value)) {
      return Promise.reject('粉丝数格式必须为数字')
    } else {
      return Promise.resolve()
    }
  }
const registryFormRules = reactive({
   wx: [{ validator: checkFans, required: true, trigger: 'blur' }],
})
```
