### ISSUE TITLE
a-input

### ISSUE THREAD

**Issue by hi-emil** [vueComponent/ant-design-vue#3307]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
vue

### Reproduction link
[https://www.antdv.com/components/input-cn/](https://www.antdv.com/components/input-cn/)

### Steps to reproduce
a-input 有历史记录 ，下滑滚动条时历史记录与输入框 分开  跟随滚动条往下滚动了

### What is expected?
历史记录 应该跟输入框紧贴

### What is actually happening?
a-input 有历史记录 ，下滑滚动条时历史记录与输入框 分开  跟随滚动条往下滚动了

**Comment by tangjinzhou** [comment]
这是 浏览器的锅吧

**Comment by xrkffgg** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by hi-emil** [comment]
a-select 和 时间选择器 都有api方法固定 ，就它没有



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangjinzhou"<notifications@github.com&gt;; 
发送时间: 2020年12月4日(星期五) 中午1:44
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "℡Hi"<1191547257@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] a-input (#3307)





 
这是 浏览器的锅吧
