### ISSUE TITLE
Form validate验证通过，不执行then，只执行catch

### ISSUE THREAD

**Issue by geeklibin** [vueComponent/ant-design-vue#3309]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
windows10 专业版，Chrome版本 87.0.4280.88（正式版本） （64 位），Vue3.0.0

### Steps to reproduce
使用validate验证表单。校验完成不执行then，仅执行catch:
catch中打印error的结果
```
{
errorFields: []
outOfDate: true
values: {old_pswd: "123123", new_pswd: "123123", confirm_pswd: "123123"}
}
```

### What is expected?
根据文档所说，验证校验通过应该执行then，而不是catch

### What is actually happening?
使用validate验证表单。校验完成不执行then，仅执行catch:
catch中打印error的结果
```
{
errorFields: []
outOfDate: true
values: {old_pswd: "123123", new_pswd: "123123", confirm_pswd: "123123"}
}
```

**Comment by hulibin** [comment]
> Hello @hulibin. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository.Make sure to choose the correct version.
> 
> 你好 @hulibin, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

在线实例：https://codesandbox.io/s/gracious-butterfly-1ltvg?file=/src/App.vue

**Comment by sendya** [comment]
你可以使用 @finish 和 @finishFailed 事件来得知是否校验成功/失败
@submit 是指表单提交时数据**校验成功**事件，是可以和 @finish， @finishFailed 搭配使用
不需要在内部执行表单校验
你可以按照 demo [表单校验](https://2x.antdv.com/components/form-cn/#components-form-demo-validation) 编写代码，或者 useForm 形式使用 form
或者看看 https://codesandbox.io/s/proud-firefly-o8eus?file=/src/App.vue

**Comment by geeklibin** [comment]
可以的，谢谢。使用@finish事件和@finishFailed事件、 或useForm没有问题，但是文档上写的submit是【数据验证成功后回调事件】，文档案例中也是如此。https://2x.antdv.com/components/form-cn/。
![image](https://user-images.githubusercontent.com/9034445/101320416-af2ecc00-389e-11eb-89e3-6649f53e4043.png)

**Comment by DMQ** [comment]
遇到一样的问题，不解决一下吗？

**Comment by Laev** [comment]
使用过程中useForm与ref方式，useForm 在字段验证符合验证结果后会出现走入catch中的情况，而ref方式则正常
