### ISSUE TITLE
a-collapse-panel在自定义组件中时，无法展开。查看元素内容已经渲染。

### ISSUE THREAD

**Issue by sscfaith** [vueComponent/ant-design-vue#3310]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
macos chrome 2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-dawn-o9cfb?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/trusting-dawn-o9cfb?file=/src/App.vue

### What is expected?
可以展开

### What is actually happening?
无法展开

**Comment by sscfaith** [comment]
内容已渲染，但无法展开
![image](https://user-images.githubusercontent.com/23066241/101126013-8ce64580-3635-11eb-97f5-0bbd8ad43d55.png)

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/dawn-dream-yzzoy?file=/src/App.vue
a-collapse-panel 不可以和 a-collapse 分开写

**Comment by sscfaith** [comment]
我知道合在一起可以，但就是有这个需求。有时候a-collapse-panel是动态的，就需要放在组件里。关键是审查元素他渲染了内容，那么为什么无法展开。

**Comment by sscfaith** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-turing-ut4hb?file=/src/App.vue)
还有这种情况的，没有别的解决方案吗？

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/runtime-dawn-ft2mh?file=/src/App.vue
试试这种
