### ISSUE TITLE
希望select组件支持tags插槽

### ISSUE THREAD

**Issue by Rock-zhang1** [vueComponent/ant-design-vue#3313]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
需求是tags显示用户头像和用户名，目前只支持label，用tagRander函数的话，事件、样式等都需要开发者自己写。。。

### What does the proposed API look like?
@ant-design-vue：2.0.0-rc.1

**Comment by Rock-zhang1** [comment]
label属性支持html渲染也可

**Comment by kshiw** [comment]
加个一
希望支持value-key的形式
希望出tags插槽
because：
后端一次性返回了5000多条订单数据必须用dropdownRender + RecycleScroller + 自制select-option-item 否则卡的飞起  
他们今天说加个需求多选 我以为很好解决的  然后我整了一天了  value绑定array-object数据  点击tag点击就无响应了 也没对应的事件可以调用
最后 只能自己强行写个input search + dropdown - -

**Comment by kshiw** [comment]
### `directives: {
      deselect: {
        bind: function(el, binding, vnode) {
          let vm = vnode.context

          // 事件委托
          let func = (e) => {
            if (e.target && findNodeClassName(e.target, 'select-selection__choice__remove', 'SPAN')) {
              let find = findNodeClassName(e.target, 'select-selection__choice')
              if (find) {
                let index = getIndex(find, find.parentElement)
                let {prop, options, optionsFields} = binding.value
                let del = vm.form[prop].splice(index, 1)
                for(let i of options) {
                  if (del[0][optionsFields.value] === i[optionsFields.value]) {
                    i.flag = false
                    break
                  }
                }
                vm.$forceUpdate()
              }
            }
          }
          el.addEventListener("click", func, true);
          vm.$once('hook:beforeDestroy', () => {
            el.removeEventListener("click", func, true);
          })

          // 查找类名包含的dom
          function findNodeClassName(target, name, tag = 'LI') {
            if (target) {
              let className = typeof target['className'] === 'string' ? target['className'] : ''
              if (className.indexOf(name) >= 0 && target.tagName === tag) {
                return target
              } else {
                return findNodeClassName(target.parentElement, name, tag)
              }
            }
            return null
          }

          // 获取下标
          function getIndex(current, obj){ 
            for (var i = 0, length = obj.children.length; i<length; i++) { 
              if (obj.children[i] === current) { 
                return i; 
              } 
            }
          }
        }
      }
    }`
