### ISSUE TITLE
菜单水平模式错误

### ISSUE THREAD

**Issue by anncwb** [vueComponent/ant-design-vue#3316]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

![image](https://user-images.githubusercontent.com/28132598/101234933-cc2c9900-36fe-11eb-9cff-86441206b960.png)

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/issues/3262
