### ISSUE TITLE
a-radio-group在a-form-item中产生额外换行问题

### ISSUE THREAD

**Issue by Small-Shu** [vueComponent/ant-design-vue#3319]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/radio-cn/#components-radio-demo-radio-style](https://2x.antdv.com/components/radio-cn/#components-radio-demo-radio-style)

### Steps to reproduce
``` html
<template>
<a-form layout="vertical">
<a-form-item>
<a-input
placeholder="这是一个输入框，底部的间隔为正常状态，a-radio-group在特殊情况会有占用两行的情况"
/>
</a-form-item>

<a-form-item>
<a-radio-group class="w-100">
<a-radio-button :value="1" class="w-50 text-center">
one select
</a-radio-button>
<a-radio-button :value="2" class="w-50 text-center">
底部的间隔占用了两行
</a-radio-button>
</a-radio-group>
</a-form-item>

<a-form-item>
<a-radio-group class="w-100">
<a-radio-button :value="1" class="w-50 text-center">
AAAAAAAAAAAAAAAA
</a-radio-button>
<a-radio-button :value="2" class="w-50 text-center">
BBBBBBBBBBBBBBBB
</a-radio-button>
</a-radio-group>
</a-form-item>

<a-form-item>
<a-radio-group class="w-100">
<a-radio-button :value="1" class="w-50 text-center">
one select
</a-radio-button>
<a-radio-button :value="2" class="w-50 text-center">
底部的间隔占用了两行
</a-radio-button>
</a-radio-group>
</a-form-item>

<a-form-item>
<a-radio-group class="w-100">
<a-radio-button :value="1" class="w-50 text-center">
one select
</a-radio-button>
<a-radio-button :value="2" class="w-50 text-center">
底部的间隔占用了两行
</a-radio-button>
</a-radio-group>
</a-form-item>

<a-form-item>
<a-button type="primary" block>submit</a-button>
</a-form-item>
</a-form>
</template>
```

```scss
<style scoped>
.w-100 {
width: 100%;
}
.w-50 {
width: 50%;
}
.text-center {
text-align: center;
}
</style>
```

### What is expected?
解决a-radio-group在a-form-item中占用多行，导致间隔过高的问题

### What is actually happening?
解决a-radio-group在a-form-item中占用多行，导致间隔过高的问题

---
解决a-radio-group在a-form-item中占用多行，导致间隔过高的问题

**Comment by John60676** [comment]
https://codesandbox.io/s/admiring-cloud-pr2rn?file=/src/App.vue
未能复现你的问题，请提供一个复现例子

**Comment by Small-Shu** [comment]
> https://codesandbox.io/s/admiring-cloud-pr2rn?file=/src/App.vue
> 未能复现你的问题，请提供一个复现例子

请尝试将CSS添加进去，我已经在上面连接进行了修改。

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/101566439-f5ed0500-3a09-11eb-9606-480a14125a44.png)
这不是一样的间隔吗

**Comment by Small-Shu** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/101566439-f5ed0500-3a09-11eb-9606-480a14125a44.png)
> 这不是一样的间隔吗

![image](https://user-images.githubusercontent.com/37906203/101707277-e16e4280-3ac5-11eb-8f30-179e17fd8b1a.png)
我不知道你是如何实现的，你可以查看：https://codesandbox.io/s/condescending-ganguly-z3re5 里面的代码来复现我的问题。

**Comment by John60676** [comment]
临时方案：
`.ant-form-item-control-wrapper` 给这个类一个 `width: 100%`  的样式

**Comment by Small-Shu** [comment]
这个多久可以更新进去。。
