### ISSUE TITLE
哇。老哥怎么还塞彩蛋啊！！！

### ISSUE THREAD

**Issue by xxbld** [vueComponent/ant-design-vue#332]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.2

### Environment
111

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q956jn5wvw)

### Steps to reproduce
111

### What is expected?
111

### What is actually happening?
111

![image](https://user-images.githubusercontent.com/13309211/50408090-b5495080-081f-11e9-9ea3-267d5e8561f6.png)

**Comment by dsonet** [comment]
It's from antd.

**Comment by tangjinzhou** [comment]
#334
