### ISSUE TITLE
Notification->Open the notification box 不能正常显示

### ISSUE THREAD

**Issue by zhaoqiFreeman** [vueComponent/ant-design-vue#3324]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
macos 10.14.6，Google Chrome版本 87.0.4280.88（正式版本） (x86_64)，"vue": "^3.0.0",

### Reproduction link
[https://2x.antdv.com/components/notification-cn/](https://2x.antdv.com/components/notification-cn/)

### Steps to reproduce
Notification->Open the notification box

### What is expected?
Notification正常使用

### What is actually happening?
Notification->Open the notification box 不可正常使用

### 问题截图

![image](https://user-images.githubusercontent.com/28887001/101330304-68949e00-38ad-11eb-9c18-0736474a0316.png)

**Comment by John60676** [comment]
这个应该只是文档问题，现在不支持渲染函数了。可以直接传 JSX 进去
https://codesandbox.io/s/epic-noyce-q7s5l?file=/src/App.vue
codesandbox 上面会有点问题，里面的例子复制一下自己的 vue 环境里面跑就行了

**Comment by zhaoqiFreeman** [comment]
谢谢大佬及时回复帮助解决问题！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 上午10:19
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"赵芪"<1144010101@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] Notification-&gt;Open the notification box 不能正常显示 (#3324)





 
这个应该只是文档问题，现在不支持渲染函数了。可以直接传 JSX 进去
 https://codesandbox.io/s/epic-noyce-q7s5l?file=/src/App.vue
 codesandbox 上面会有点问题，里面的例子复制一下自己的 vue 环境里面跑就行了

**Comment by tangjinzhou** [comment]
@John60676 文档 PR 掉吧

**Comment by zhaoqiFreeman** [comment]
弱弱的问一句 RP啥意思



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tangjinzhou"<notifications@github.com&gt;; 
发送时间: 2020年12月9日(星期三) 上午10:37
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "赵芪"<1144010101@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] Notification-&gt;Open the notification box 不能正常显示 (#3324)





 
@John60676 文档 PR 掉吧
