### ISSUE TITLE
a-table的sort功能无法正确排序

### ISSUE THREAD

**Issue by Dzxwind** [vueComponent/ant-design-vue#3327]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
win10 Chorme87.0.4280.88 vue2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-buck-fs8eq?file=/src/App.vue)

### Steps to reproduce
点击表格上的排序按钮，表格无法排序

### What is expected?
表格能够排序

### What is actually happening?
表格无法排序

---
sortOrder属性有问题

**Comment by tangjinzhou** [comment]
添加  filteredValue: null, 临时解决

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/solitary-field-x819q

**Comment by Dzxwind** [comment]
> 添加 filteredValue: null, 临时解决
好的，谢谢。但是这其实加了一个无关的属性，还是希望能修复的。。  
很喜欢ant design！加油！干饭人！

**Comment by JokerAn** [comment]
Scrolling horizontally to the far right of the table table will also get stuck
横向滚动到最右侧table表格还会卡死
