### ISSUE TITLE
出现父组件layout已经加载成功，但是子组件并未放到layout-content标签内？

### ISSUE THREAD

**Issue by GeorGeWzw** [vueComponent/ant-design-vue#3336]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
您好，我这边出现父组件layout已经加载成功，但是子组件并未放到layout的content内，导致获取子组件内某个元素的宽度不准确？

### Reproduction link
[https://github.com/DestinyCore/DestinyCore.Flow.Design](https://github.com/DestinyCore/DestinyCore.Flow.Design)

### Steps to reproduce
您好，我这边出现父组件layout已经加载成功，但是子组件并未放到layout的content内，导致获取子组件内某个元素的宽度不准确？

### What is expected?
希望在父组件加载完成之后将子组件默认放入layout-content内

### What is actually happening?
您好，我这边出现父组件layout已经加载成功，但是子组件并未放到layout的content内，导致获取子组件内某个元素的宽度不准确？

**Comment by GeorGeWzw** [comment]
![image](https://user-images.githubusercontent.com/46982191/101605112-c3a8cb00-3a3c-11eb-9f73-e24b9c8905e1.png)

**Comment by John60676** [comment]
你可以在读取 dom 时加个 `nextTick` ，应该就能解决你的问题

**Comment by tangjinzhou** [comment]
这是 Vue 机制，mounted 时不承诺子组件已经挂载DOM
