### ISSUE TITLE
select选择器组件中 无法实现 popupScroll 功能

### ISSUE THREAD

**Issue by CheeChanChu** [vueComponent/ant-design-vue#3337]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
vue版本：3.0.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-curie-dbdmq?file=/src/App.vue:0-915)

### Steps to reproduce
<template>
<div id="app" style="padding: 24px">
<div>
<a-select
style="width: 100%"
placeholder="Tags Mode"
@popupScroll="scrollChange"
@change="handleChange"
>
<a-select-option v-for="i in 25" :key="(i   9).toString(36)   i">{{
(i   9).toString(36)   i
}}</a-select-option>
</a-select>
</div>
</div>
</template>

<script>
import moment from "moment";
import { version } from "ant-design-vue";

export default {
name: "App",
data() {
return {
moment,
version,
console: console,
};
},
methods: {
handleChange(value) {
console.log(`selected ${value}`);
},
scrollChange(e) {
// 无法进入这个函数功能，打印也无效
let h = e.target;
if (h.scrollHeight - h.scrollTop <= h.clientHeight) {
this.$message.error("臣妾做不到啊");
}
},
},
};
</script>

<style></style>

### What is expected?
能实现该功能

### What is actually happening?
无法进入该函数功能

**Comment by zkwolf** [comment]
你的repo好像是可以的啊

**Comment by CheeChanChu** [comment]
> 你的repo好像是可以的啊

不行，scrollChange这个函数没有触发，打印也没用。

**Comment by CheeChanChu** [comment]
> 你的repo好像是可以的啊

如过antd的版本是1.72版本的话，popupScroll这个功能就可以实现，但是2.0x之后的都不行了。

**Comment by zkwolf** [comment]
升级到2.x最新版本试试，我试了没问题的

**Comment by CheeChanChu** [comment]
> 升级到2.x最新版本试试，我试了没问题的

知道我的问题在哪了。再select选择器用了这个:not-found-content="null"  影响了使用popupScroll 功能

**Comment by bambibren** [comment]
> > 升级到2.x最新版本试试，我试了没问题的
> 
> 知道我的问题在哪了。再select选择器用了这个:not-found-content="null" 影响了使用popupScroll 功能

问题解决了吗？我也遇到触发不了popupScroll，但是是偶现，鼠标划着划着会划不动，也出发不了popupScroll(并没有使用not-found-content)
