### ISSUE TITLE
能否将基于 vue2 的老版本独立分支并由社区维护

### ISSUE THREAD

**Issue by nuochong** [vueComponent/ant-design-vue#3343]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
很多项目都是基于 vue2 老版本的，切换肯定需要时间，在这个时间老版本出现 BUG 无法进行修复提交

### What does the proposed API look like?
将老版本独立

**Comment by sendya** [comment]
代码都在这里，为何 无法进行修复提交？

**Comment by nuochong** [comment]
> 代码都在这里，为何 无法进行修复提交？

现在的 master 分支 是否为老版本最新的分支

**Comment by tangjinzhou** [comment]
vue 2 版本会一直持续修复 bug 的  目前在master 分支，可以直接 pr 到 master 分支

**Comment by nuochong** [comment]
了解了，钢材看了下，我从官网入口进入默认为next分支，以为老版本被覆盖了Q@Q
