### ISSUE TITLE
选择器下拉框支持级联选择或者级联选择的输入框支持tag标签显示

### ISSUE THREAD

**Issue by CLJLewis** [vueComponent/ant-design-vue#3345]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
正开发一个教育类项目，需要通过输入框获取焦点或者输入匹配形式，下拉框级联选择方式选择教材版本/年级/章节等，如“人教版/一年级数学/加减法”，并以一个tag显示在输入框中，输入框可同时存在多个tag

### What does the proposed API look like?
跟我们现在选择器（Select） 和 级联选择（Cascader）API 相结合

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/102000836-85eebf80-3d26-11eb-9aaa-ce0cf7b89cd4.png)
Cascader  提供了 displayRender 可满足你的需求
