### ISSUE TITLE
vue ant design slider 小数点不能拉满

### ISSUE THREAD

**Issue by reng99** [vueComponent/ant-design-vue#3346]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
prod

### Reproduction link
[https://vuecomponent.github.io/](https://vuecomponent.github.io/)

### Steps to reproduce
-

### What is expected?
vue ant design slider 小数点拉满

### What is actually happening?
vue ant design slider 小数点不能拉满

![image](https://user-images.githubusercontent.com/22773901/101880265-93446680-3bcd-11eb-8272-9d762d3f54dd.png)

**Comment by tangjinzhou** [comment]
什么叫拉满

**Comment by reng99** [comment]
咦，没上传到图片成功？再上传一次
![demo](https://user-images.githubusercontent.com/22773901/102044971-e9561b80-3e12-11eb-823b-88d112047f52.png)

就像上图所示，我最大值是0.7，但是我拖动滚动，拖动不了到0.7（拖动的间隔step我设置为0.1）。

ps: 拖动间隔step为1的时候，没有这种问题
