### ISSUE TITLE
need a The largest BigTable

### ISSUE THREAD

**Issue by cheermen** [vueComponent/ant-design-vue#3348]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Solve the big data table jam problem

### What does the proposed API look like?
{bigSource:true}

**Comment by JokerAn** [comment]
Scrolling horizontally to the far right of the table table will also get stuck
横向滚动到最右侧table表格还会卡死
