### ISSUE TITLE
<a-modal>里加表单，在多选框中，选择一个后，不关闭多选的list，滚动整个modal，多选的list不跟着滚动，导致select框和list分开

### ISSUE THREAD

**Issue by zwygithub** [vueComponent/ant-design-vue#3353]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
"@antv/data-set": "^0.10.2",     "ant-design-vue": "^1.5.2",

### Reproduction link
[https://www.npmjs.com/package/vue-antd-pro](https://www.npmjs.com/package/vue-antd-pro)

### Steps to reproduce
<a-modal>里加表单，在多选框中，选择一个后，不关闭多选的list，滚动整个modal，多选的list不跟着滚动，导致select框和list分开

### What is expected?
跟着滚动

### What is actually happening?
<a-modal>里加表单，在多选框中，选择一个后，不关闭多选的list，滚动整个modal，多选的list不跟着滚动，导致select框和list分开

**Comment by zkwolf** [comment]
設置一下getPopupContainer 

https://antdv.com/docs/vue/faq-cn/#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F

**Comment by zwygithub** [comment]
xiexie,已解决；我有去尝试a-tree-select加 :getPopupContainer="trigger => trigger.parentNode"后，此问题也解决，但是由于我设置treeDefaultExpandAll=true，发现与:getPopupContainer="trigger => trigger.parentNode"一起使用后，默认展开所有树节点就不管用了
