### ISSUE TITLE
menu菜单收缩bug

### ISSUE THREAD

**Issue by carmel** [vueComponent/ant-design-vue#3354]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
macos 10.15.6； chrome Version 87.0.4280.88；vue 3.0.2

### Reproduction link
[https://2x.antdv.com/components/menu-cn/](https://2x.antdv.com/components/menu-cn/)
1. `layout-sider collapsed`状态时，最开始使用鼠标hover菜单，后继续将`layout-sider`置成`not collapsed`状态时，则二级菜单不会出现在一级菜单下面。
2. `layout-sider collapsed`状态时，将`layout-sider`置成`not collapsed`状态时，二级菜单会出现在一级菜单下面，但此时鼠标hover菜单无效果。

### Steps to reproduce
```vue
<a-menu
theme="dark"
mode="inline"
:inline-collapsed="collapsed"
>
<template
v-for="item in menu"
:key="item.Id"
>
<a-menu-item
v-if="item.Children.length===0"
:key="item.Id"
>
<router-link :to="item.Path">
{{ item.Name }}
</router-link>
</a-menu-item>
<sub-menu
v-else
:key="item.Id"
:menu="item"
/>
</template>
</a-menu>
```

自定义的sub-menu：
```vue
<a-sub-menu
:key="menu.Id"
v-bind="$attrs"
>
<template #title>
<a-icon
:name="menu.Icon"
/>
<span>{{ menu.Name }}</span>
</template>
<template
v-for="item in menu.Children"
:key="item.Id"
>
<a-menu-item
v-if="item.Children.length===0"
:key="item.Id"
>
<router-link :to="item.Path">
{{ item.Name }}
</router-link>
</a-menu-item>
<sub-menu
v-else
:key="item.Id"
:menu="item"
/>
</template>
</a-sub-menu>
```

### What is expected?
如官方例子：https://2x.antdv.com/components/menu-cn/

### What is actually happening?
菜单收缩不正常

![Dec-11-2020 21-25-56](https://user-images.githubusercontent.com/36031579/101908811-99e7d380-3bf7-11eb-9316-2bfac3a19e4e.gif)

       
ps：想问下各位大神，这框架能用在生产环境吗？

**Comment by ZhangShiy** [comment]
"@vue/babel-plugin-jsx": "^1.0.0-rc.3"，v-model={[selectKey.value, 'selectedKeys']}
"@vue/babel-plugin-jsx": "^1.0.0-rc.4"，v-model={[selectKey.value, 'selectedKeys']}  或者 v-models={[[selectKey.value, 'selectedKeys']]} 均存在无法选定问题

**Comment by carmel** [comment]
@ZhangShiy 没有用`babel-plugin-jsx`。

**Comment by carmel** [comment]
将menu改成下面的形式：
```vue
<a-menu
        theme="dark"
        mode="inline"
        :inline-collapsed="collapsed"
      >
        <custom-menu-item
          :menu-list="menu"
        />
      </a-menu>
```

`custom-menu-item`如下：

```vue
<template>
  <template
    v-for="menu in menuList"
    :key="menu.Id"
  >
    <a-menu-item
      v-if="menu.Children.length===0"
      :key="menu.Id"
    >
      <router-link :to="menu.Path">
        {{ menu.Name }}
      </router-link>
    </a-menu-item>
    <a-sub-menu
      v-else
      :key="menu.Id"
      v-bind="$attrs"
    >
      <template #title>
        <a-icon
          :name="menu.Icon"
        />
        <span>{{ menu.Name }}</span>
      </template>
      <menu-item
        :key="menu.Id"
        :menu-list="menu.Children"
      />
    </a-sub-menu>
  </template>
</template>

```

结果点一下子菜单全部选中了：

![image](https://user-images.githubusercontent.com/36031579/101925843-50a27e80-3c0d-11eb-911a-1cc774231e2b.png)

![image](https://user-images.githubusercontent.com/36031579/101925875-5a2be680-3c0d-11eb-9e53-f7009b09130a.png)

**Comment by xushanpei** [comment]
**更新到 rc.4 版本菜单样式不生效**

![image](https://user-images.githubusercontent.com/35324963/101970536-f4b81400-3c65-11eb-850d-e5776ebdf08a.png)

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/sharp-wilson-6esli   
查看这个示例，并没能复现你说的问题
如果你不能定位问题，要提供复现示例，方便我们排查问题

**Comment by xushanpei** [comment]
出现了同样的问题,不知道怎么解决,要么菜单样式错乱,要么点击展开后不能收缩,菜单收起状态的时候二级菜单直接打不开

**Comment by carmel** [comment]
@tangjinzhou 你好，这是[复现链接](https://codesandbox.io/s/peaceful-robinson-vc5hr?file=/src/App.vue)

**Comment by tangjinzhou** [comment]
1. 单文件递归组件有点坑，对结构要求严格， menu 的子组件不能是自定义组件，你可以参考这个 https://codesandbox.io/s/hungry-stallman-gi1u3?file=/src/App.vue 来改动你的结构
2. vue 3.0.2 版本没问题，对于更高版本下个版本会先兼容一下，根本问题要等 vue 来修复

3、即将重构 menu，来解决 1 的问题

**Comment by carmel** [comment]
谢谢，有个疑问：这里的菜单组件不是通过树状结构数据递归出来了嘛，还是递归出来DOM节点无法区分？如果是vue的问题是不是可以呼叫下尤大 😆

**Comment by carmel** [comment]
@tangjinzhou 新改的能发布到npm上嚒？

**Comment by carmel** [comment]
The  repository is immature and not recommended!
