### ISSUE TITLE
a-table  scroll { x: number | true, y: number } 纵向滚动值y应该可以设置百分比，这样能够高度自适应容器

### ISSUE THREAD

**Issue by lifanmvc** [vueComponent/ant-design-vue#3357]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格在父div中，div 高度自适应的情况下，y 应该可以设置 100%，表格高度能够自适应。

### What does the proposed API look like?
参考 elelmentui 的表格的固定表头，高度控制，它的设计就挺好。

**Comment by deajax** [comment]
表示同意

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/102489866-0a379e80-40a9-11eb-9381-c78b99fc6904.png)


支持的哦，直接写即可

下面是 demo
```
    <a-table
      :columns="columns"
      :data-source="data"
      :pagination="{ pageSize: 50 }"
      :scroll="{ y: `calc(100vh - 50px)` }"
    />
```
