### ISSUE TITLE
表格标题加粗

### ISSUE THREAD

**Issue by pangjiancongl** [vueComponent/ant-design-vue#3358]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格标题只支持英文加粗，而中文是没有加粗效果的

### What does the proposed API look like?
通过属性给表格标题实现加粗效果

**Comment by xrkffgg** [comment]
建议直接通过 css
