### ISSUE TITLE
在babel.config.js里面配置了按需加载，那么在组件内部如何访问全局提示this.$message.success()？

### ISSUE THREAD

**Issue by zhangguanpeng** [vueComponent/ant-design-vue#336]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://tangjinzhou.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by zdxweb** [comment]
message配置maxCount为什么不会自动关闭
