### ISSUE TITLE
树形控件 Tree 节点加载完毕时触发事件 load无效？

### ISSUE THREAD

**Issue by lcy198910** [vueComponent/ant-design-vue#3360]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
后台管理系统中，组织机构； 左右布局页面，左侧部门树，右侧用户表格；首次进入页面，当左侧部门树加载完成时，需要根据左侧默认选中树的节点id查询右侧表格的用户

### What does the proposed API look like?
Tree 节点加载完毕时触发事件 load无效？

**Comment by dmyz** [comment]
一样

**Comment by miqilin21** [comment]
我也是
