### ISSUE TITLE
vue-cli4使用babel-plugin-impor没效果

### ISSUE THREAD

**Issue by hurenzhan** [vueComponent/ant-design-vue#3361]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
vue:  3.0.0

### Reproduction link
[https://github.com/hurenzhan/cloud-chain/tree/main](https://github.com/hurenzhan/cloud-chain/tree/main)

### Steps to reproduce
我照官网说的安装了babel-plugin-impor，然后配置了.babelrc，引用组件还报You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

### What is expected?
#3361

### What is actually happening?
#3361

**Comment by sendya** [comment]
配置在这个文件，谢谢 https://github.com/hurenzhan/cloud-chain/blob/main/babel.config.js
具体可以查看 vue-cli 官方文档 https://cli.vuejs.org/config/#babel

**Comment by hurenzhan** [comment]
> 配置在这个文件，谢谢https://github.com/hurenzhan/cloud-chain/blob/main/babel.config.js
> 具体可以查看vue-cli官方文档[https://cli.vuejs.org/config/#巴别塔](https://cli.vuejs.org/config/#babel)

请问antd要怎么配呢，官方文档似乎没看见

**Comment by cyt68** [comment]
> 配置在这个文件，谢谢 https://github.com/hurenzhan/cloud-chain/blob/main/babel.config.js
> 具体可以查看 vue-cli 官方文档 https://cli.vuejs.org/config/#babel

配置了也无效
