### ISSUE TITLE
sub-menu组件popupClassName属性不生效

### ISSUE THREAD

**Issue by jiabinbin** [vueComponent/ant-design-vue#3362]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
mac Os BigSur 11.0.1/ chrome 87.0.4280.88（正式版本） (x86_64)/  vue 3.0.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-williams-zpkh5?file=/src/SubMenu.vue)

### Steps to reproduce
sub-menu设置popupClassName后，对应的样式没有生效。

### What is expected?
popupClassName能正常生效

### What is actually happening?
简单的调试了一下，发现在组件内部，合并后的popupClassName为popupClassName: "ant-menu-dark test-class"
但实际在页面上并没有加载test-class样式。只有ant-menu-dark样式

**Comment by jiabinbin** [comment]
补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~

**Comment by chad-bin** [comment]
> 补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~

确实 拆成单文件后折叠动画没了。我还以为我写错了

**Comment by jiabinbin** [comment]
> > 补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~
> 
> 确实 拆成单文件后折叠动画没了。我还以为我写错了

动画的之前有人提过issue,回复说是快重构menu组件了，详见
https://github.com/vueComponent/ant-design-vue/issues/3354

**Comment by jiabinbin** [comment]
> > 补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~
> 
> 确实 拆成单文件后折叠动画没了。我还以为我写错了
动画的见这个issue，刚刚过了一次发了有说这个问题。说是快重构了。
https://github.com/vueComponent/ant-design-vue/issues/3354

**Comment by jiabinbin** [comment]
我就是回复下点错了点了关闭了， 抱歉

**Comment by tangjinzhou** [comment]
> > > 补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~
> > 
> > 
> > 确实 拆成单文件后折叠动画没了。我还以为我写错了
> 
> 动画的之前有人提过issue,回复说是快重构menu组件了，详见
> #3354

动画和这个issue 没关系

动画问题 尝试降级 vue 到 3.0.3  试试

**Comment by jiabinbin** [comment]
> > > > 补充：在案例中，拆成单文件后，菜单的展开和收缩时的动画好也没有了~
> > > 
> > > 
> > > 确实 拆成单文件后折叠动画没了。我还以为我写错了
> > 
> > 
> > 动画的之前有人提过issue,回复说是快重构menu组件了，详见
> > #3354
> 
> 动画和这个issue 没关系
> 
> 动画问题 尝试降级 vue 到 3.0.3 试试

行，我回头试试，哪个sub-menu的popupClassName能麻烦帮忙确认下么？如果确认是我自己的问题我好关下这个issue

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/102298518-3b6e7c80-3f8c-11eb-93e7-32a886752b7a.png)
已经生效，只是background 的权重低了

试试这个
```css
.test-class .ant-menu-sub{
  background: red;
}
```

**Comment by jiabinbin** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/102298518-3b6e7c80-3f8c-11eb-93e7-32a886752b7a.png)
> 已经生效，只是background 的权重低了
> 
> 试试这个
> 
> ```css
> .test-class .ant-menu-sub{
>   background: red;
> }
> ```

可能是单文件的原因，我这边测试还是没有把class渲染到dom上 （ 。问题我先关掉了，我再多看看

**Comment by TimRChen** [comment]
我这边也出现了同样的问题

![截屏2020-12-18 下午3 51 44](https://user-images.githubusercontent.com/22197215/102589150-897caf00-4149-11eb-8b56-30c799cdf8ee.png)
