### ISSUE TITLE
嵌套子表格中无法通过 #operation="{text}" 拿到 text 数据

### ISSUE THREAD

**Issue by mschenyu** [vueComponent/ant-design-vue#3367]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.10

### Environment
macOS10.14.5 、chrome 、vue: "^3.0.0",

### Reproduction link
[https://2x.antdv.com/components/table-cn/#components-table-demo-nested-tables](https://2x.antdv.com/components/table-cn/#components-table-demo-nested-tables)

### Steps to reproduce
运行官方文档中的嵌套子表格示例代码( https://2x.antdv.com/components/table-cn/#components-table-demo-nested-tables )，打印嵌套子表格中的行数据 "text"  ，值为undefined。

### What is expected?
通过 #operation="{text}"  能正常拿到子表格的行数据

### What is actually happening?
undefined

![image](https://user-images.githubusercontent.com/36450302/102073630-8bd7c400-3e3e-11eb-9439-f4ca701dd801.png)
![image](https://user-images.githubusercontent.com/36450302/102073759-b7f34500-3e3e-11eb-9ea0-17af1d8a422c.png)

**Comment by ajuner** [comment]
innerColumns = [
...
{
    title: 'Action',
   ~~dataIndex: 'operation',~~
    key: 'operation',
    slots: { customRender: 'operation' },
  },
