### ISSUE TITLE
ant-layout-content 样式问题

### ISSUE THREAD

**Issue by chuanHH** [vueComponent/ant-design-vue#337]
v1.2.3版本 样式错乱 且内容超过屏幕高度不能滚动 
![image](https://user-images.githubusercontent.com/16145005/50417281-6c65bc00-0860-11e9-910d-eb58d3f905bc.png)
因为 .ant-layout-content 加了（min-height:0）的原因

**Comment by chuanHH** [comment]
目前我改成 .ant-layout-content {min-height:auto !important} 可以兼容

**Comment by sendya** [comment]
这个通常我们要为页面内容区设置一个 100% 高

**Comment by chuanHH** [comment]
> 这个通常我们要为页面内容区设置一个 100% 高
是本来写好的项目 更新版本 才出的问题 100%肯定设置过了呀

**Comment by tangjinzhou** [comment]
这个是为了解决firefox下的一个兼容问题，具体详情可以查看这个pr:
https://github.com/ant-design/ant-design/pull/12295
