### ISSUE TITLE
form表单如何异步设置错误信息

### ISSUE THREAD

**Issue by hurenzhan** [vueComponent/ant-design-vue#3374]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
vue 3.0

### Reproduction link
[https://github.com/hurenzhan/cloud-chain/blob/main/src/views/login/components/PassLogin.vue](https://github.com/hurenzhan/cloud-chain/blob/main/src/views/login/components/PassLogin.vue)

### Steps to reproduce
表单提交后，发送接口，校验不通过

### What is expected?
希望提交表单后，校验不通过，能手动设置错误信息

### What is actually happening?
文档没发现相关api

**Comment by Hyphon** [comment]
可以使用 [FormModel](https://www.antdv.com/components/form-model-cn/) 组件
通过传入 `rules` 来进行自定义校验。具体的 api 可以查看 [async-validator](https://github.com/yiminghe/async-validator)
