### ISSUE TITLE
Table 表格 动态添加树形结构未生效

### ISSUE THREAD

**Issue by faithcoco** [vueComponent/ant-design-vue#3378]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
1.6.4

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-ajax](https://www.antdv.com/components/table-cn/#components-table-demo-ajax)

### Steps to reproduce
<a-table :columns="columns" :data-source="detailsData" :scroll="{ x: 3000 }"/>
handleAddItem(record) {
var child = []
child.push(JSON.parse(JSON.stringify(record)))
record.children = child

console.log('data-->', JSON.stringify(this.detailsData))
},

### What is expected?
列表动态变为树形结构

### What is actually happening?
bug

**Comment by sendya** [comment]
请提供 codesandbox 复现，谢谢
