### ISSUE TITLE
最新版menu菜单设置展开菜单式，页面进入的瞬间会闪一下 ，但是旧版不会

### ISSUE THREAD

**Issue by insertSweat** [vueComponent/ant-design-vue#338]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.3

### Environment
Mac OS X 10_13_6 Chrome/71.0.3578.98 Vue2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r5mkvl21rq)

### Steps to reproduce
最新版的地址 [https://codesandbox.io/s/r5mkvl21rq](https://codesandbox.io/s/r5mkvl21rq)

1.1.6版本重现地址： [https://codesandbox.io/s/32r03jqyvp](https://codesandbox.io/s/32r03jqyvp)

### What is expected?
和旧版一致不闪动

### What is actually happening?
进入页面时闪动

**Comment by tangjinzhou** [comment]
please update to 1.2.4
