### ISSUE TITLE
Clear Field with Initial Value

### ISSUE THREAD

**Issue by rahultailwal** [vueComponent/ant-design-vue#3385]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
Windows 10, Chrome,

### Reproduction link
[https://www.antdv.com/components/form/](https://www.antdv.com/components/form/)

### Steps to reproduce
Create dropdown select with initial value and try to reset the dropdown using any button click on another dropdown change.

`<a-form-item label="Test">
    <a-select v-decorator="['companyInformation.cityid', { initialValue: companyInformation.cityid, rules: [{ required: true, message: 'Please select city name!' }] }]">
             <a-select-option v-for="pv in city" :value="pv.cityid" :key="pv.cityid">{{pv.name}}</a-select-option>
    </a-select>
</a-form-item>`

### What is expected?
this.form.resetFields('companyInformation.cityid') is resetting the field if there  is no initial value but it should also reset the field if there is initial value for the field.

### What is actually happening?
this.form.resetFields('companyInformation.cityid') is resetting the field if there  is no initial value but it should also reset the field if there is initial value for the field.

**Comment by zkwolf** [comment]
This is how it was designed
