### ISSUE TITLE
全局引入antdv无法覆盖antdv组

### ISSUE THREAD

**Issue by qiang47199** [vueComponent/ant-design-vue#3390]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
test

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/new/choose](https://github.com/vueComponent/ant-design-vue/issues/new/choose)

### Steps to reproduce
二次封装avtdv组件然后全局引入使用同样名字

### What is expected?
期望使用同一个组件名可以覆盖antdv默认组件

### What is actually happening?
无法覆盖

**Comment by sendya** [comment]
建议不要重名，这是 Vue 的规范不是 antdv 不让覆盖
