### ISSUE TITLE
下拉框样式不正确

### ISSUE THREAD

**Issue by Ttou** [vueComponent/ant-design-vue#3396]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
mac vue3.0 edge

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-rgb-fwmkm)

### Steps to reproduce
表单布局设为 inline，下拉框的长度不对；尺寸同样是 small，输入框高度是 26，下拉框高度是 24

### What is expected?
下拉框长度正常，高度一致

### What is actually happening?
下拉框长度不对，高度不一致

**Comment by zkwolf** [comment]
我这看都是24px啊

**Comment by Ttou** [comment]
![WX20201218-150059](https://user-images.githubusercontent.com/4298437/102584701-ee340b80-4141-11eb-87f7-399e5804d189.png)
![WX20201218-150121](https://user-images.githubusercontent.com/4298437/102584712-f2f8bf80-4141-11eb-9b1e-ae32be520df9.png)

**Comment by Ttou** [comment]
RangePicker 小尺寸下高度也是 24px
