### ISSUE TITLE
form-model validateField 方法执行多次bug

### ISSUE THREAD

**Issue by imic07** [vueComponent/ant-design-vue#3397]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
deepin20/chrome latest/vue 2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-table-expico-forked-0uzd2?file=/src/components/Test.vue)

### Steps to reproduce
1.不填写任何字段，点击获取验证码。发现调用了2次
2. 填写帐号和手机号，点击获取验证码。发现调用了2次
```
this.$refs.ruleForm.validateField(
    ["username", "telephone"],
    (errorMessage, a) => {
      console.log("sssssssssss", errorMessage, a);
      if (!errorMessage) {
                   this.$notification.error({
          message: "消息提示",
          description: "这里调用后端接口，应该只执行一次，！！！！！！！",
        });
      } else {
        this.$message.error("校验不通过，这里应该只执行一次！！！！！！！");
        return false;
      }
    }
  );
```

### What is expected?
对多个字段校验。成功或失败只执行一次

![image](https://user-images.githubusercontent.com/16321067/102600126-622dde00-4159-11eb-98b9-94bbfc6d1f5b.png)
![image](https://user-images.githubusercontent.com/16321067/102600188-7540ae00-4159-11eb-9e8e-feb541e87f97.png)

### What is actually happening?
对多个字段校验。成功或失败 执行了 待校验的字段个数次。

**Comment by ajuner** [comment]
validateField的callback参数对字段进行校验
应该在validateField().then中进行你的判断

**Comment by imic07** [comment]
@ajuner 没有then方法，会报错。能提供下代码吗？

**Comment by ajuner** [comment]
不好意思  好像是我搞错了
不过这个可以自己在validateFild内进行判断后自行判断是否验证通过~

**Comment by imic07** [comment]
@ajuner 我试了，不得行。你能发下代码吗？ 另外能重新打开这个issue吗？

**Comment by ajuner** [comment]
https://codesandbox.io/s/antd-vue-table-expico-forked-gtb3m

**Comment by imic07** [comment]
@ajuner 这种方法确实可行，谢谢
