### ISSUE TITLE
a-tree外的按钮怎么点击后将之前的@select方法的选中去掉

### ISSUE THREAD

**Issue by zwygithub** [vueComponent/ant-design-vue#3403]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
外部按钮，希望将之前a-tree的select操作置为空

### What does the proposed API look like?
no

**Comment by tangjinzhou** [comment]
value= []
