### ISSUE TITLE
Descriptions 描述列表组件，中的Item props，里边label可以时VNode，怎么用

### ISSUE THREAD

**Issue by zwygithub** [vueComponent/ant-design-vue#3404]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Descriptions 描述列表组件，中的Item props，里边label可以时VNode，怎么用

### What does the proposed API look like?
Descriptions 描述列表组件，中的Item props，里边label可以时VNode，怎么用

**Comment by tangjinzhou** [comment]
如果你使用 template， 用 slot 就好 
vnode 是给 jsx 用户使用的
