### ISSUE TITLE
table配合搜索区域的一些疑问

### ISSUE THREAD

**Issue by xx6822** [vueComponent/ant-design-vue#341]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格搜索功能

### What does the proposed API look like?
请问如何获取当前table的pagination, filters, sorter属性？

当我点击搜索按钮的时候，我想获取当前table在第几页，每页显示的条数，当前设置了过滤的列，当前设置了排序的列信息。

因为需要结合这些信息来完成搜索功能，请问有办法么？期待您的解答。

**Comment by xx6822** [comment]
像这张图那样：
![QQ20181225225720.png](https://www.tuchuang001.com/images/2018/12/25/QQ20181225225720.png)

当我点击搜索时，需要搜索出编号为NO 1,使用状态为关闭，服务调用次数升序排序的内容。

文档中没有找到可以触发table change事件的方法。

**Comment by tangjinzhou** [comment]
https://vuecomponent.github.io/ant-design-vue/components/table-cn/#%E4%BA%8B%E4%BB%B6
![image](https://user-images.githubusercontent.com/6937879/50428749-ee9fc000-08f4-11e9-8770-ae4ac3416abc.png)

**Comment by xx6822** [comment]
嗯，当时我也看到这个方法了，不过不清楚点击搜索的时候怎么触发。

table ref="UserTable"尝试：
```javascript
search () {
   this.$refs.UserTable.change()
}
```
change()里面的三个参数不懂填什么（不懂怎么获取pagination, filters, sorter）

**Comment by xx6822** [comment]
突然想到是不是可以将这三个参数和Vue data绑定，因为table第一次加载的时候会触发change事件？

**Comment by xx6822** [comment]
如何重置分页呢？
