### ISSUE TITLE
formModel中input输入卡顿问题

### ISSUE THREAD

**Issue by wangtyu** [vueComponent/ant-design-vue#3415]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
formModel中中有很多input,select(数据较多)，input输入时会很卡，请问怎么解决下呢

### What does the proposed API look like?
formModel中中有很多input,select(数据较多)，input输入变流畅

**Comment by tangjinzhou** [comment]
拆分成多个组件  即放在不同的 单文件中

**Comment by gdmec07140551** [comment]
> 拆分成多个组件 即放在不同的 单文件中

请问原理是什么？是dom页面太多input导致的吗？

**Comment by jueinin** [comment]
> > 拆分成多个组件 即放在不同的 单文件中
> 
> 请问原理是什么？是dom节点太多input导致的吗？

你用了v-model，每次改变输入框的值的时候都会重新跑一遍模板编译出来的渲染函数。如果模板里写了一堆v-for就会比较吃CPU然后卡住。你把这些涉及到v-for的地方都写到单独的组件里，改变输入框的值的时候那一堆v-for就不会执行了
