### ISSUE TITLE
select下拉框自定义为级联选择时，选中后输入框值改变

### ISSUE THREAD

**Issue by CLJLewis** [vueComponent/ant-design-vue#3416]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
select下拉框自定义为级联选择时，比如有三级，选择第一级时，输入框值变成value1，接着选择第二级时，输入框值变成value1/value2，到第三级时，变成value1/value2/value3，且以tags形式显示在输入框中

### What does the proposed API look like?
跟原本select的API差不多，可以加多个inputValue 显示选中时输入框的值

**Comment by tangjinzhou** [comment]
你可以使用 cascader 组件
