### ISSUE TITLE
禁用Textarea自适应高度在chrome中滚动条定位光标

### ISSUE THREAD

**Issue by Atlas-lili** [vueComponent/ant-design-vue#3418]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.2

### Environment
ant-design-vue@2.0.0-rc.2 vue@3.0.4

### Reproduction link
[https://codepen.io/Atlas-lili/pen/yLaozJj?editors=001](https://codepen.io/Atlas-lili/pen/yLaozJj?editors=001)

### Steps to reproduce
样本使用react版本，但在我在使用ant-design-vue同样存在该问题。
1. 滚动至自适应的文本框上边缘超过视口
2. 对偏上区域文本输入换行

### What is expected?
希望可以禁用这种光标定位

### What is actually happening?
在chrome中将滚动外层容器至光标贴近视口上边缘，在firefox中正常换行（不会调整容器滚动条）

---
希望可以有props选项禁用这种行为

**Comment by tangjinzhou** [comment]
我没太懂   尴尬

**Comment by Atlas-lili** [comment]
https://codesandbox.io/s/trusting-water-es2zd?file=/src/App.vue
antd-vue的demo
![image](https://user-images.githubusercontent.com/32982388/103121739-80935c80-46b8-11eb-9b6f-4b6694c86485.png)
![image](https://user-images.githubusercontent.com/32982388/103121792-b46e8200-46b8-11eb-91e4-7a9f2446af8d.png)

**Comment by tangjinzhou** [comment]
Google Chrome 已是最新版本
版本 87.0.4280.88（正式版本） (x86_64)

没能复现你说的问题

**Comment by Atlas-lili** [comment]
> Google Chrome已是最新版本
> 版本87.0.4280.88（正式版本）（x86_64）
> 
> 没能复现你说的问题

抱歉 可能是我的示例和复现步骤不准确，chrome版本是一致的。
复现步骤：
1. 滚动预览页面使文本框中文本2至视口顶端。
2. 在文本框文本4后输入enter。
3. [现象] 预览页面自动滚动使新插入的空行至视口顶端。
![image](https://user-images.githubusercontent.com/32982388/103153180-b2e0af00-47c9-11eb-8a5d-fcc3a48ada1a.png)
