### ISSUE TITLE
2.0描述文档例子有错误

### ISSUE THREAD

**Issue by duoduoObama** [vueComponent/ant-design-vue#3421]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
浏览器版本：5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 Edg/87.0.664.66 VUE：3.0

### Reproduction link
[https://2x.antdv.com/docs/vue/migration-v2-cn/](https://2x.antdv.com/docs/vue/migration-v2-cn/)

### Steps to reproduce
1.打开浏览器
2.打开链接https://2x.antdv.com/docs/vue/migration-v2-cn/
3.滚动到标题为<<2.0 中会采用按需引入的方式 >>

### What is expected?
2.0 中会采用按需引入的方式：例子应该是正确的

### What is actually happening?
2.0 中会采用按需引入的方式：a-button 结尾标签打错了（a-buttom）

**Comment by zkwolf** [comment]
修了，等更新吧
