### ISSUE TITLE
upload组件在beforeUpload时无法获取excel文件类型

### ISSUE THREAD

**Issue by tookbra** [vueComponent/ant-design-vue#3422]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
MacOs Catalina 10.15.6, Google Chrome  87.0.4280.88

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-swirles-1ftcd?file=/src/App.vue)

### Steps to reproduce
可以运行下codesandbox

### What is expected?
可以获取到文件类型

### What is actually happening?
doc，excel文件类型获取不到，但是图片，pdf文件类型可以获取

**Comment by Hyphon** [comment]
浏览器根据`<input type="file" />`上传的文件，可以通过获取 onChange 事件内的 e.target.files 来获取文件对象数组，可以通过 MDN 查询得知，每个文件对象 File 的 type字段，遵循Internet Engineering Task Force (IETF) 定义的MIME (Multipurpose Internet Mail Extensions) 类型，最新的 RFC 6838 中可查到的对应关系如下：
```
*.doc  =>   application/msword
*.xls    =>   application/vnd.ms-excel
.pdf    =>   application/pdf
// 上面是不是看着还算正常
.docx  =>   application/vnd.openxmlformats-officedocument.wordprocessingml.document
.xlsx    =>   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
```
   
所以我猜想，问题大概不是获取不到，而是和你想的类似`application/xlsx`这样的不太一样吧。

**Comment by tookbra** [comment]
> 浏览器根据`<input type="file" />`上传的文件，可以通过获取onChange事件内部的e.target.files来获取文件对象数组，可以通过MDN查询调用，每个文件对象文件的类型，从而进行Internet工程任务组（IETF）定义的MIME（多用途Internet邮件扩展名）类型，最新的RFC 6838中可查到的对应关系如下：
> 
> ```
> *.doc  =>   application/msword
> *.xls    =>   application/vnd.ms-excel
> .pdf    =>   application/pdf
> // 上面是不是看着还算正常
> .docx  =>   application/vnd.openxmlformats-officedocument.wordprocessingml.document
> .xlsx    =>   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
> ```
> 
> 所以我猜想，问题大概不是获取不到，或者和你想的类似`application/xlsx`这样的不太一样吧。
> 最后附上链接：[MDN-常见MIME类型列表](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)

我并不是想获取类似application/xlsx这样，就如你说的，我想获取的是MIME类型
在MacOs Catalina 10.15.6，谷歌浏览器87.0.4280.88 获取不到对应的MIME类型，
但是在Windows10企业版， 谷歌浏览器87.0.4280.88 可以获取到对应的MIME类型

**Comment by Hyphon** [comment]
> > 浏览器根据`<input type="file" />`上传的文件，可以通过获取onChange事件内部的e.target.files来获取文件对象数组，可以通过MDN查询调用，每个文件对象文件的类型，从而进行Internet工程任务组（IETF）定义的MIME（多用途Internet邮件扩展名）类型，最新的RFC 6838中可查到的对应关系如下：
> > ```
> > *.doc  =>   application/msword
> > *.xls    =>   application/vnd.ms-excel
> > .pdf    =>   application/pdf
> > // 上面是不是看着还算正常
> > .docx  =>   application/vnd.openxmlformats-officedocument.wordprocessingml.document
> > .xlsx    =>   application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
> > ```
> > 
> > 
> > 所以我猜想，问题大概不是获取不到，或者和你想的类似`application/xlsx`这样的不太一样吧。
> > 最后附上链接：[MDN-常见MIME类型列表](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types)
> 
> 我并不是想获取类似application/xlsx这样，就如你说的，我想获取的是MIME类型
> 在MacOs Catalina 10.15.6，谷歌浏览器87.0.4280.88 获取不到对应的MIME类型，
> 但是在Windows10企业版， 谷歌浏览器87.0.4280.88 可以获取到对应的MIME类型，很是奇怪😂

我手头没有 Mac，很遗憾帮不了你了😂😂
