### ISSUE TITLE
Table 表格如何通过customRender方法渲染其它组件

### ISSUE THREAD

**Issue by phker** [vueComponent/ant-design-vue#3423]
Table 表格如何通过customRender方法渲染其它组件
`

function txteditor(text,record,index,column){
    if(record.editable) {
          // 这里似乎无论如何都无法返回一个组件,只能返回字符串
        const obj = {
          tag:'span',
          children: '<span>1234</span>',
          attrs: {}
        }
        return obj
    } else {
      return text;
    } 
  }

const columns = [ 
  { dataIndex: '商品编码', title: '商品编码(SKU)', width: 150, fixed: 'left',editor:'textbox',  customRender: txteditor  },
  { dataIndex: '商品名称', title: '商品名称', width: 300, fixed: 'left',editor:'textbox',  customRender: txteditor},
]

`

当然我知道官方示例中是可以通过模板的形式实现的. 通过slots 可以指定模板, 但是我想通过编程的形式实现, 这样更灵活一些.
请问有方法么?

**Comment by zkwolf** [comment]
挺麻烦的。。。。可以参考一部分这个代码 https://codesandbox.io/s/edit-table-j82dw?file=/src/App.vue
