### ISSUE TITLE
Table 表格如何通过customRender方法渲染其它组件

### ISSUE THREAD

**Issue by phker** [vueComponent/ant-design-vue#3424]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Table 表格如何通过customRender方法渲染其它组件
```javascript
function txteditor(text,record,index,column){
    if(record.editable) {
// 我希望通过这个函数可以返回一个表单组件显示在表格的单元格中.  
        const obj = {
          tag:'span',
          children: '<span>1234</span>',
          attrs: {}
        }
        return obj
    } else {
      return text;
    } 
}

const columns = [
{ dataIndex: '商品编码', title: '商品编码(SKU)', width: 150, fixed: 'left',editor:'textbox', customRender: txteditor },
{ dataIndex: '商品名称', title: '商品名称', width: 300, fixed: 'left',editor:'textbox', customRender: txteditor},
]
```

当然我知道官方示例中是可以通过模板的形式实现的. 通过slots 可以指定模板, 但是我想通过编程的形式实现, 这样更灵活一些.
请问有方法么?

### What does the proposed API look like?
我在定义列的时候可以 这样用
```javascript
{ dataIndex: '商品编码', title: '商品编码(SKU)', width: 150,  editor:'textbox'  },
```
可以通过editor 来指定编辑模式下的编辑器. 可以是一个组件或者是通过一个函数返回一个组件..这样的表格将会有更多的作用.

**Comment by sendya** [comment]
`customRender: (text, record) => (<span>1234</span>)` 

https://github.com/vuejs/jsx#syntax

**Comment by phker** [comment]
> `customRender: (text, record) => (<span>1234</span>)`
> 
> https://github.com/vuejs/jsx#syntax

谢谢, 如果不用jsx, 使用ts 该 如何写这段代码?
