### ISSUE TITLE
Tree组件（包括其他组件）key只能是string单一类型

### ISSUE THREAD

**Issue by lynlich** [vueComponent/ant-design-vue#343]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
组件props只能是单一类型很不方便开发，当传入number时就会报错。

### What does the proposed API look like?
props type支持[string, number]

**Comment by tangjinzhou** [comment]
table是支持number类型key的，你使用的什么版本，如有报错，麻烦给出复现demo链接 谢谢

**Comment by lynlich** [comment]
说错了 是Tree 使用1.2.3

**Comment by lynlich** [comment]
> table是支持number类型key的，你使用的什么版本，如有报错，麻烦给出复现demo链接 谢谢

说错了 是Tree 使用1.2.3

**Comment by tangjinzhou** [comment]
please update to 1.2.4
