### ISSUE TITLE
Autocomplete suffix button show error after click slot button (bind @click to perform router push)

### ISSUE THREAD

**Issue by shahrizal96** [vueComponent/ant-design-vue#3434]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
Windows 10, Chrome, Vue 2.6.12

### Reproduction link
[https://www.antdv.com/components/auto-complete/](https://www.antdv.com/components/auto-complete/)

### Steps to reproduce
Click suffix button (let say search icon) and bind with click to change page using router push.

### What is expected?
Able to change page without error

### What is actually happening?
When click search icon, trigger error "A DOM element reference is required". However when I focus on input and dropdown-content open then click the button (while the dropdown-content still open) everything is fine (can change page).

![image](https://user-images.githubusercontent.com/52898588/102953090-7e3fcf80-450b-11eb-99bf-278193858e47.png)

https://user-images.githubusercontent.com/52898588/102953920-55203e80-450d-11eb-9ef4-92fd7221c88a.MOV

**Comment by ajuner** [comment]
I tried to simulate your steps, but the ability is limited and there is no reproduction. Can you provide a codesandbox?
