### ISSUE TITLE
希望可以在后续版本改进对可选的参数采用默认值的写法。避免IDE对缺省参数发出警告

### ISSUE THREAD

**Issue by sws797** [vueComponent/ant-design-vue#3435]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
优化使用体验

### What does the proposed API look like?
function test(a:string, b:string='xxx') {}

**Comment by sendya** [comment]
可以提供哪些函数吗？这有助于我们优化

**Comment by sws797** [comment]
@sendya 抱歉这么久才回复，我是在使用 $message(xxx).then(这里) 中发现这个问题的，其它地方并没有细看。 
![image](https://file.learnerhub.net/queshengcanshu.png)
