### ISSUE TITLE
textarea设置autosize后每次输入会导致高度重置

### ISSUE THREAD

**Issue by tracy2zhang** [vueComponent/ant-design-vue#3437]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.5

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/input-cn/#components-input-demo-autosizing-the-height-to-fit-the-content](https://2x.antdv.com/components/input-cn/#components-input-demo-autosizing-the-height-to-fit-the-content)

### Steps to reproduce
1. 给textarea设置autosize属性
2. 将textarea拖到最大
3. 输入任意内容

### What is expected?
textarea高度不变

### What is actually happening?
textarea高度回到初始状态

**Comment by tangjinzhou** [comment]
预期行为，autosize 根据内容自动调整高度
