### ISSUE TITLE
modal

### ISSUE THREAD

**Issue by isaxiao** [vueComponent/ant-design-vue#3438]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
不够自由化

### What does the proposed API look like?
高度不能指定，头部边框不能去掉。

**Comment by John60676** [comment]
可以自己通过 CSS 控制

**Comment by tangjinzhou** [comment]
dialogStyle | 可用于设置浮层的样式，调整浮层位置等

dialogClass | 可用于设置浮层的类名
