### ISSUE TITLE
自定义组件使用Switch组件时，switch组件的ts声明文件中无onChange和onClick属性

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3439]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.5

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/switch-cn/#%E4%BA%8B%E4%BB%B6](https://2x.antdv.com/components/switch-cn/#%E4%BA%8B%E4%BB%B6)

### Steps to reproduce
1.自定义SwitchItem组件中使用Switch组件
code：
<Switch
checked={unref(_value)}
disabled={!!disabled}
onChange={onChange}
/>
2.提示 不能将类型“{ checked: boolean; disabled: boolean; onChange: true; switch的声明文件无: true; 属性: true; }”分配给类型***
3.查看 ant-design-vue/lib/switch/index.d.ts 无onChange属性声明

### What is expected?
期望声明文件 存在onChange和onClick的属性

### What is actually happening?
无法使用onChaneg事件

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/102991484-401ace00-4554-11eb-9fa0-c3bd32536047.png)
请提供 codesandbox 复现，或提供代码。

**Comment by liulei92** [comment]
code
[https://codesandbox.io/s/quiet-currying-nj3ei?file=/src/components/SwitchItem.tsx](https://codesandbox.io/s/quiet-currying-nj3ei?file=/src/components/SwitchItem.tsx)

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/103131184-b0ebf280-46da-11eb-8e40-14b0bfb527d7.png)

请升级到 rc5 ，无此问题

**Comment by sendya** [comment]
好像确实没有

**Comment by liulei92** [comment]
![switch事件props声明](https://user-images.githubusercontent.com/18693333/103189015-b8dbaa80-4905-11eb-9e0e-81dbf1448bd5.png)
# @tangjinzhou 这个修复的有点问题；props中应该是 onChange 和  onClick
