### ISSUE TITLE
使用Checkbox.Group组件时会有vue:warning警告

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3440]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.5

### Environment
vue3.0.3

### Reproduction link
[https://2x.antdv.com/components/checkbox-cn/](https://2x.antdv.com/components/checkbox-cn/)

### Steps to reproduce
1.使用checkbox.group组件
code:
<a-checkbox-group v-model:value="modelRef.type">
<a-checkbox value="1" name="type">
Online
</a-checkbox>
<a-checkbox value="2" name="type">
Promotion
</a-checkbox>
<a-checkbox value="3" name="type">
Offline
</a-checkbox>
</a-checkbox-group>
2.现象
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component emitted event "update:value" but it is neither declared in the emits option nor as an "onUpdate:value" prop.

### What is expected?
修复 警告问题

### What is actually happening?
runtime-core.esm-bundler.js?5c40:38 [Vue warn]: Component emitted event "update:value" but it is neither declared in the emits option nor as an "onUpdate:value" prop.

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/102991378-0c3fa880-4554-11eb-83fa-3a05a6fe6823.png)

能提供 codesandbox 复现吗？

**Comment by liulei92** [comment]
[https://codesandbox.io/s/dry-browser-wbo1j?file=/src/App.vue](https://codesandbox.io/s/dry-browser-wbo1j?file=/src/App.vue)

有点意外,codesanbox没有复现,但项目中控制台会复现这个

ant-design-vue@^2.0.0-rc.4:
  version "2.0.0-rc.5"
![微信图片_20201224095445](https://user-images.githubusercontent.com/18693333/103049999-24eca480-45ce-11eb-9f33-c71e6c22cf01.png)

**Comment by Amour1688** [comment]
方便提供出现警告的项目代码吗
