### ISSUE TITLE
 VIP ANTD PRO VUE 收费了,  我还能继续免费使用 ANTD PRO VUE 吗?

### ISSUE THREAD

**Issue by zbclear** [vueComponent/ant-design-vue#3444]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
看到商城里  VIP ANTD PRO VUE 收费了9999,   那  ANTD PRO VUE是否仍然免费的,  还是说后续会有争议

### What does the proposed API look like?
1

**Comment by sendya** [comment]
Admin Pro 和 Ant Design Vue Pro 不是同一个产品，完全无需这个担心
