### ISSUE TITLE
Input没有将用户的输入转换为 Number 类型的功能

### ISSUE THREAD

**Issue by lostimever** [vueComponent/ant-design-vue#3446]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
Vue3.0 typescript

### Reproduction link
[https://2x.antdv.com/docs/vue/introduce-cn/](https://2x.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
input框输入数字

### What is expected?
Input没有将用户的输入转换为 Number 类型

### What is actually happening?
数字为String类型

**Comment by tangjinzhou** [comment]
使用 InputNumber 组件
