### ISSUE TITLE
给表单赋值之后，提交时表单校验不通过，显示值不能为空

### ISSUE THREAD

**Issue by LJJ1996** [vueComponent/ant-design-vue#3451]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.4

### Environment
Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-kowalevski-qulin?file=/src/App.vue)

### Steps to reproduce
异步拿到部分数据之后，给表单赋初始值，提交时表单校验不通过，显示值不能为空。但是校验不通过的字段均有值

### What is expected?
能够提交通过

### What is actually happening?
提交报错

**Comment by tangjinzhou** [comment]
state.data 的响应式已经断掉了 
参考这个：
https://codesandbox.io/s/elastic-albattani-vlm0q?file=/src/App.vue
