### ISSUE TITLE
自定义组件使用Switch组件时，switch组件的ts声明文件中无onChange和onClick属性 #3439（该修复未正常工作）

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3456]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.6

### Environment
vue3.0.4

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3439](https://github.com/vueComponent/ant-design-vue/issues/3439)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue/issues/3439
该issue修复未正常工作

![switch事件props声明](https://user-images.githubusercontent.com/18693333/103189267-d4938080-4906-11eb-85e7-aa6b61ae93d9.png)

增加的props应为 onChange 和 onClick

### What is expected?
switch onChange和onClick事件正常工作

### What is actually happening?
同 https://github.com/vueComponent/ant-design-vue/issues/3439

**Comment by tangjinzhou** [comment]
rc7
