### ISSUE TITLE
Select版本兼容，下拉框出现后立马消失

### ISSUE THREAD

**Issue by YuhuiM** [vueComponent/ant-design-vue#3457]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
Chrome66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-morning-83j3r)

### Steps to reproduce
点击下拉框

### What is expected?
正常显示

### What is actually happening?
下拉框出现后立马消失

---
下拉框动画类名未移除，导致opacity: 0一直生效

**Comment by John60676** [comment]
我这边看正常，你是如何触发的

![image](https://user-images.githubusercontent.com/21698973/103197626-65775580-4921-11eb-82be-382b6bdae68f.png)

**Comment by myh6666** [comment]
@John60676 我在Chrome66版本发现的，你的浏览器是哪个版本
