### ISSUE TITLE
最新版2.0.0-rc.6 select show-search 添加open属性，在输入框搜索不能清空placeholder，去除open属性，正常

### ISSUE THREAD

**Issue by Mrqqqwww** [vueComponent/ant-design-vue#3458]
![未清空placeholder](https://user-images.githubusercontent.com/30919325/103206254-68c90c00-4936-11eb-96d7-5c1d4809f2fb.png)
![代码](https://user-images.githubusercontent.com/30919325/103206257-6a92cf80-4936-11eb-8b2c-73b38ae24741.png)

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
dev

### Reproduction link
[https://2x.antdv.com/components/select-cn/](https://2x.antdv.com/components/select-cn/)

### Steps to reproduce
null

### What is expected?
清空placeholder

### What is actually happening?
未清空

**Comment by Mrqqqwww** [comment]
![代码](https://user-images.githubusercontent.com/30919325/103206288-7e3e3600-4936-11eb-92ad-92eb0e7ce14b.png)
![未清空placeholder](https://user-images.githubusercontent.com/30919325/103206292-81392680-4936-11eb-81f2-e0e1b52af36d.png)

**Comment by tangjinzhou** [comment]
你这个 open 是 false 状态吧
看你的场景，推荐使用 input 替代

**Comment by tangjinzhou** [comment]
如果一定要用 select ，可以自行写 css  把 placeholder 隐藏
