### ISSUE TITLE
组件重置的方法

### ISSUE THREAD

**Issue by xx6822** [vueComponent/ant-design-vue#346]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
这几天发现好些组件都没有提供重置的方法，比如Table Pagination，事件选择器等等

### What does the proposed API look like?
如果能有`reset`等方法将会方便许多，或许是有什么隐藏的技巧我没有发现？求解答

**Comment by tangjinzhou** [comment]
? 为何要重置？  直接传值就是了

**Comment by xx6822** [comment]
比如我搜索区域有个时间选择组件，点击重置的话，时间选择组件上的值要清空，这时候有什么好的办法么？

**Comment by tangjinzhou** [comment]
:value="null"
