### ISSUE TITLE
total should support bigint，It shouldn't be "shape - "total" property validation error: number - value "0" should be of type "Number""

### ISSUE THREAD

**Issue by cluyun** [vueComponent/ant-design-vue#3461]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
windows10,new Chrome，vue 3.0.4

### Reproduction link
[https://2x.antdv.com/components/pagination-cn/#API](https://2x.antdv.com/components/pagination-cn/#API)

### Steps to reproduce
use bigint total，error。使用bigint绑定分页组件总条数报错。

### What is expected?
Able to use bigint total。使用bigint类型的数值能够绑定总条数。

### What is actually happening?
error [VueTypes warn]: oneOfType - provided value does not match any of the 2 passed-in validators:
shape - "total" property validation error:
number - value "0" should be of type "Number"
looseBool - value "[object Object]" should be of type "Boolean"

---
Check other components that should support bigint。排查下其他理应支持bigint的组件属性。

**Comment by chad-bin** [comment]
@zkwolf  image 组件的preview属性设置成object也一样有这种警告。感觉很多组件有写propTypes.shape基本大部分有这个问题

**Comment by cluyun** [comment]
> @zkwolf image 组件的preview属性设置成object也一样有这种警告。感觉很多组件有写propTypes.shape基本大部分有这个问题


要是只是警告还好说，我这个是直接报错了。界面都挂掉了

**Comment by cluyun** [comment]
暂时想到的方法就是在ts中不要只使用bigint。在约定类型的时候写上bigint | number。
比如：
`
class UserEntity extends BaseEntity {
  /**
   * 用户ID
   */
  Id!: bigint | number ;
}
`
