### ISSUE TITLE
shh1

### ISSUE THREAD

**Issue by shanhan0** [vueComponent/ant-design-vue#3466]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
vue:1.1.10

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
表格的scroll当横向滚动的时候，表头和内容错位。
看样式人家正确的样式是 ： 滚动的时候，class="ant-table ant-table-fixed-header ant-table-default ant-table-bordered ant-table-scroll-position-middle"
ant-table-scroll-position-middle这个滚动的时候依次是position-left，position-middle， position-right。

而我写的是，滚动的时候的类是：class="ant-table ant-table-fixed-header ant-table-default ant-table-bordered ant-table-scroll-position-left ant-table-scroll-position-right"                        一直是ant-table-scroll-position-left，ant-table-scroll-position-right

### What is expected?
期望滚动不会错位

### What is actually happening?
滚动错位

---
希望予以回答和帮助，谢谢

**Comment by shanhan0** [comment]
有没有小伙伴遇到这种问题。各种方法都试了，无解

**Comment by sendya** [comment]
有留一列自适应宽度吗？    建议提供一个复现

**Comment by shanhan0** [comment]
https://codesandbox.io/s/vue-antd-template-forked-xksdk?file=/src/App.vue

**Comment by shanhan0** [comment]
antd vue是1.1.10版本的

**Comment by shanhan0** [comment]
项目在本地环境运行，滚动是没问题的。放在测试环境上就出现了错位的问题
很纳闷只是个环境不一样，为什么显示的样式会不一样

**Comment by shanhan0** [comment]
https://codesandbox.io/s/vue-antd-template-forked-xksdk?file=/src/App.vue:504-517
   

本地就是按照上面写的不会错位。  换个环境测试的，就错位了

**Comment by shanhan0** [comment]
> 复现

留了          本地环境不会错位。测试环境就错位了

**Comment by shanhan0** [comment]
急需各位大佬帮助，非常非常感谢

**Comment by tangjinzhou** [comment]
升级 1.7.2

**Comment by shanhan0** [comment]
好的
