### ISSUE TITLE
期望Modal.confirm 支持getContainer属性

### ISSUE THREAD

**Issue by HylenHypher** [vueComponent/ant-design-vue#3468]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
Google Chrome

### Reproduction link
[https://www.antdv.com/components/modal-cn/](https://www.antdv.com/components/modal-cn/)

### Steps to reproduce
期望Modal.confirm 支持getContainer属性

### What is expected?
期望Modal.confirm 支持getContainer属性

### What is actually happening?
期望Modal.confirm 支持getContainer属性

**Comment by sendya** [comment]
可能文档还没增加，应该是支持的，你可以试试看。

https://github.com/vueComponent/ant-design-vue/blob/next/components/modal/Modal.tsx#L127

**Comment by HylenHypher** [comment]
嗯嗯支持的，感谢🙏
