### ISSUE TITLE
spin组件设置delay无效

### ISSUE THREAD

**Issue by jingping-ye** [vueComponent/ant-design-vue#3469]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
System:     
OS: Windows 10 10.0.18363   
CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   
Binaries:     
Node: 14.15.1 - D:\installed\resource\nodejs\node.EXE      
npm: 6.14.8 - D:\installed\resource\nodejs\npm.CMD      
Browsers:    
Chrome: 86.0.4240.198  
npmPackages:
ant-design-vue: ^1.7.2 => 1.7.2
vue: ^2.6.11 => 2.6.11

### Reproduction link
[https://github.com/jingping-ye/bug-report.git](https://github.com/jingping-ye/bug-report.git)

### Steps to reproduce
1. 发起请求，此时spinning设置为true
2. 请求完毕之后，设置spinning为false。设置一个延时定时器，定时器再次发起请求。
3. 当请求时间超过delay时间时，即使下次请求小于delay时间。spinning也没有停止下来。

### What is expected?
按时停止

### What is actually happening?
spin不能停止

**Comment by ajuner** [comment]
delay对设置成true和false都会产生效果
看了一下你的问题和仓库，下面这个例子可以看出是没有问题的，而你的项目出问题的原因在你每次重新模拟发起请求时写的计时器的问题，举个例子比如你的第一次delay是8000，第二次是1000，那么是在第三秒的时候变成true，第11秒变成false，但你在第8秒的时候就发起了下次请求，而且延迟3秒钟，也就是你在第11秒的时候经历了
```
spinning=false
spinning=true
```
这两个操作，等于一直都是true导致的，同理后面不管延时多久都一样
https://codesandbox.io/s/vue-antd-template-forked-e96qo?file=/src/App.vue
