### ISSUE TITLE
a-select v-model为布尔值时，提示警告不支持

### ISSUE THREAD

**Issue by oimmc** [vueComponent/ant-design-vue#3472]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
mac vue3.0 chrome

### Reproduction link
[https://2x.antdv.com/components/select-cn/](https://2x.antdv.com/components/select-cn/)

### Steps to reproduce
```javascript
<a-select v-model:value="valueBool" size="large" placeholder="选择是否">
<a-select-option :value="true">是</a-select-option>
<a-select-option :value="false">否</a-select-option>
</a-select>
````

valueBool为布尔值时，提示不支持

### What is expected?
支持布尔值

### What is actually happening?
valueBool为布尔值时，提示不支持

**Comment by ajuner** [comment]
能描述清楚点吗

**Comment by tangjinzhou** [comment]
是不支持bool值的   你可以转成字符串

**Comment by oimmc** [comment]
> 是不支持bool值的你可以转成字符串

如果这个值是api返回的，比如：
[{
  id: 1,
  checked: false
}, {
  id: 2,
  checked: false
}],
甚至更为复杂的数据结构，那么考虑支持布尔值，这样使用者会更方便。

**Comment by ajuner** [comment]
用Switch是不是会好点

**Comment by xionglongxiang** [comment]
为什么不支持bool值呢，实际开发中就是经常用到bool。

**Comment by byk04712** [comment]
同问，为什么不支持。实际作为搜索条件是，下拉框为 是/否，传给后端是 true/false。 switch 主要是有默认值，作为查询条件不合适
