### ISSUE TITLE
Menu导航菜单递归问题

### ISSUE THREAD

**Issue by JackySoft** [vueComponent/ant-design-vue#3476]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
2.0.0-rc.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-grothendieck-b3p05?file=/src/App.vue)

### Steps to reproduce
导航菜单，通常是从后端请求回来，然后递归遍历，目前我发现在递归时最后一级菜单会同时选中或非选中，不能互斥，而且官方的递归例子可以，但是官方的例子过于麻烦。
1、模板中加载a-menu组件
<a-menu mode="inline" style="width: 256px">
<tree-menu :userMenu="userMenu"></tree-menu>
</a-menu>
// userMenu格式
{
id:'10',
name:'系统管理',
path:'/system',
icon:'user',
children:[
{
id:'10001',
name:'用户管理',
path:'/system/users'
},
]
}
2、定义递归子组件TreeMenu
<template v-for="menu in userMenu">
<a-sub-menu v-if="menu.children" :key="menu.id">
<template #title>
<span>
<DesktopOutlined /><span>{{ menu.name }}</span>
</span>
</template>
<tree-menu :user-menu="menu.children" :key="menu.id"></tree-menu>
</a-sub-menu>
<a-menu-item :key="menu.id" v-else>{{ menu.name }}</a-menu-item>
</template>
遍历出来没有什么问题，但是点击的时候，会同时选中和非选中，不知道为什么？

### What is expected?
点击父菜单或者子菜单正常展开或关闭，菜单直接互不影响

### What is actually happening?
父菜单同时会选中，子菜单也会同时选中。
系统管理下面同时有用户管理、角色管理等，当选择用户管理时，角色管理也选中了。

---
不明白为什么官方的例子递归的时候要绕一道？

**Comment by sendya** [comment]
请按文档使用

https://codesandbox.io/s/bold-napier-yirwu?file=/src/components/TreeMenu.vue

Menu 一个项目写一遍几乎不会在写，这一点应该不会太多“麻烦”

**Comment by JackySoft** [comment]
为什么一定要两次循环？一次明明可以搞定，这里面就是有隐藏的Bug未修复，我们去写递归算法，也不可能写两次循环再去递归，这不合理。

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/3354#issuecomment-743931769
看下这个回复
