### ISSUE TITLE
Tooltip箭头样式错误

### ISSUE THREAD

**Issue by lchrennew** [vueComponent/ant-design-vue#3477]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
Mac, Chrome 86, Vue3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-brahmagupta-j1vkx)

### Steps to reproduce
直接使用<a-tooltip/>

### What is expected?
箭头正常显示

### What is actually happening?
箭头变成了小方块
![image](https://user-images.githubusercontent.com/1522365/103494796-4aea3280-4e73-11eb-823f-e0f7df779773.png)

---
这是样式导致的

![image](https://user-images.githubusercontent.com/1522365/103494645-be3f7480-4e72-11eb-857c-9251ae2808c2.png)

**Comment by lchrennew** [comment]
#3470

**Comment by liulei92** [comment]
2.0.0-rc.7 复现

**Comment by mynetfan** [comment]
2.0.0-rc.5之后的版本才有此问题

**Comment by John60676** [comment]
下个版本会修复这个问题 

 Reference: #3479
