### ISSUE TITLE
在手机端模式下，Carousel走马灯组件的img和img的父级div标签均不能触发click事件（PC端则可以触发）

### ISSUE THREAD

**Issue by megatron817** [vueComponent/ant-design-vue#3478]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
Google Chrome: 87.0.4280.88（正式版本） （64 位）,   vue: 2.6.10,   windows7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-sammet-vp88g?file=/src/App.vue)

### Steps to reproduce
codesandbox调成手机模式功能是正常的，但是将谷歌浏览器调成手机模式，就会出现点击图片没反应的问题（但是点击图片特别边缘的地方就能预览）。
![QQ图片20210104110348.jpg](https://pic.baixiongz.com/uploads/2021/01/04/ff0b15ac90422.jpg)

### What is expected?
手机端模式下，Carousel组件与v-viewer插件配合能够实现图片预览的功能。

### What is actually happening?
手机端模式下，Carousel组件与v-viewer插件配合无法预览图片，但是PC端可以实现预览图片的功能。

---
谷歌浏览器要调整成手机端模式，PC端模式所有功能都是OK的，Carousel组件在手机端和PC端两种模式下，能够实现的功能不一致。

**Comment by tangjinzhou** [comment]
或许你应该去 v-viewer 提issue
或者尝试 2.0 的最新image组件

**Comment by megatron817** [comment]
> 或许你应该去 v-viewer 提issue
> 或者尝试 2.0 的最新image组件

问题的关键是：
在`手机端模式`下，Carousel组件中书写的**img标签**和img的**父级div标签**，它们二者的click事件都没有触发。
而在`PC端模式`下是完全可以触发上面两者的click事件。

是不是在手机端模式下，Carousel组件的touch事件覆盖了click事件，从而导致不能触发click事件呢？

**Comment by tangjinzhou** [comment]
看这个   https://github.com/vueComponent/ant-design-vue/issues/3119
