### ISSUE TITLE
Dep optimization failed with vite2.0

### ISSUE THREAD

**Issue by Hawods** [vueComponent/ant-design-vue#3481]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
vue: 3.0.5, vite: 2.0.0-beta.4

### Reproduction link
[https://github.com/Hawods/antd-vite2-test](https://github.com/Hawods/antd-vite2-test)

### Steps to reproduce
1. cd antd-vite2-test
2. npm install (or `yarn`)
3. npm run dev (or `yarn dev`)

### What is expected?
Dev server started

### What is actually happening?
Dep optimization failed with error:
[vite]: Rollup failed to resolve import "indexof" from "indexof?commonjs-external".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

**Comment by B1anker** [comment]
```typescript
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  optimizeDeps: {
    exclude: ['ant-design-vue', 'lodash']
  }
})

```

**Comment by bhabgs** [comment]
> ```ts
> // vite.config.ts
> import { defineConfig } from 'vite'
> import vue from '@vitejs/plugin-vue'
> 
> export default defineConfig({
>   plugins: [vue()],
>   optimizeDeps: {
>     exclude: ['ant-design-vue', 'lodash']
>   }
> })
> ```

这并不能解决任何问题

**Comment by bhabgs** [comment]
I think

This issue should be referred to the Vite team。

[link](https://github.com/vitejs/vite/issues/1360)

**Comment by yyx990803** [comment]
https://github.com/vitejs/vite/issues/1360#issuecomment-754406342

Ant Design Vue 有几个很有问题的依赖，建议仔细捋一遍依赖，尽量不要再依赖 CommonJS 格式的。

**Comment by tangdw** [comment]
> @tangjinzhou 按照尤大的建议，我捋了一遍，看看能不能帮到。如果还没人来解决，我可以解决一部分。但是很多还是要你们来处理。
> 
> 整理如下
> 
> ## 可以移动到devDependencies的包有
> * @babel/runtime.
> * babel-helper-vue-jsx-merge-props
> * node-emoji
> 
> ## 没用到的依赖有
> * add-dom-event-listener
> * intersperse
> * ismobilejs
> * is-negative-zero
> 
> ## 一些建议的包
> * omit.js 这个包可以用 lodash-es的omit代替
> * shallow-equal和shallowequal这两个包是否有重复
> * warning 这个包是否可以直接使用log代替
> 
> ## 引用了 commonjs的包
> * component-classes 内部 require('indexof') 和require('component-indexof')
> * dom-closest 内部引用了require('dom-matches')
> * json2mq 内部引用了require('string-convert/camel2hyphen')
> * raf内部引用了require('performance-now')

@chad-bin 大佬，你好。 我用 antd-mobile 里也有 component-classes 内部 require('indexof') 和require('component-indexof') 这个，导致打包后的文件里有 import 'indexof' 从而访问报错，请问有什么办法解决呢？
![image](https://user-images.githubusercontent.com/17575065/114711441-85f8dd80-9d61-11eb-8f71-bb89a1de0a29.png)

**Comment by byoungd** [comment]
这个问题有任何进展吗？
