### ISSUE TITLE
a-icon中使用 v-if 控制是否展示后，未展示的组件后面也会多一条竖的分割线

### ISSUE THREAD

**Issue by baiyuxiong** [vueComponent/ant-design-vue#3482]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
antdv1.7.2 chrome

### Steps to reproduce
<template v-slot:actions>
<a-checkbox v-if="item.id==2" @change="codeCheckboxChange(index)" :checked="item.code">免费短信校验</a-checkbox>
<a-checkbox @change="requiredCheckboxChange(index)" :checked="item.r">必填</a-checkbox>
<a-icon type="setting" v-if="item.id >= 1000" @click="configRow(index)"/>
<a-icon type="delete" @click="deleteRow(index)"/>
<a-icon type="drag"/>
</template>

如果 type=setting这个 icon 不展示，后面也会多一个 竖的分割线出来

### What is expected?
icon 不展示，就不出来分割线

### What is actually happening?
多了分割线
![image](https://user-images.githubusercontent.com/230689/103520374-016d0800-4eb2-11eb-8958-4b8bc23a8386.png)

这个 icon 是放在 a-list 组件里的，应该是 a-list 的 actions 的样式的问题

**Comment by zkwolf** [comment]
给个复现
