### ISSUE TITLE
table components issue

### ISSUE THREAD

**Issue by KuuBee** [vueComponent/ant-design-vue#3484]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
macOS 
chrome:87.0.4280.88 
Vue:2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-7hw7h?file=/src/App.vue)

### Steps to reproduce
尝试使用 `components` props 复写 `tbody`用于增加虚拟滚动功能
但尝试后发现只能修改节点dom，具体代码见连接

### What is expected?
复写 `tbody` 增加虚拟滚动功能

### What is actually happening?
报错或者无法增加节点

---
翻看js源码发现好像并没有将 `createElement` 暴露出来导致无法直接修改

**Comment by sendya** [comment]
this.$createElement

**Comment by KuuBee** [comment]
> this.$createElement

我已经修改了代码
但看起来好像并不起作用
[code](https://codesandbox.io/s/vue-antd-template-forked-7hw7h?file=/src/App.vue)

**Comment by KuuBee** [comment]
[
<img width="488" alt="22" src="https://user-images.githubusercontent.com/31151489/103612189-dbea0800-4f5e-11eb-8a7c-072d815f55b9.png">
](url)
这样可以改变根元素，但是我依旧无法获取上下文对 tr td 进行渲染
[code](https://codesandbox.io/s/vue-antd-template-forked-7hw7h?file=/src/App.vue)

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-mhoo8?file=/src/App.vue
箭头函数保留this指向
