### ISSUE TITLE
treeSelect 在搜索后，无法再调用loadData来展开子节点，请问该如何解决

### ISSUE THREAD

**Issue by jack20my** [vueComponent/ant-design-vue#3485]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.4.11

### Environment
antdv1.4.11 chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
展开treeSelect，然后搜索，此时点击主节点已展开子节点无效

### What is expected?
搜索只搜主节点，然后通过点击主节点，调用loadData来加载子节点

### What is actually happening?
无法通过点击主节点调用loadData加载子节点数据

**Comment by tangjinzhou** [comment]
1、首先测试下最新版本是否有问题
2、如果最新版有问题，请提供复现
