### ISSUE TITLE
[bug] 官方示例中, 圆形进度条从0%-10%的一个过度动画异常

### ISSUE THREAD

**Issue by 1273082756** [vueComponent/ant-design-vue#3487]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-0snln?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
[bug] 官方示例中, 圆形进度条从0%-10%的一个过度动画异常, 动画非常生硬

### What is expected?
圆形进度条在0%-10%过渡的时候动画不那么生硬

### What is actually happening?
圆形进度条在0%-10%过渡的时候动画很生硬

**Comment by ajuner** [comment]
下个版本修复
