### ISSUE TITLE
Popover 通过visible控制后，点击域外无法关闭

### ISSUE THREAD

**Issue by skywalker2013** [vueComponent/ant-design-vue#3491]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
win10 /chrome

### Steps to reproduce
在antdv pro table控件中用popover
<span slot="assign" slot-scope="text, record">
  <a-popover :visible="visible&&currentId===record.id" trigger="click" overlayClassName="assign-card" destroyTooltipOnHide @visibleChange="value => visibleChange(value, record)">
    <template slot="content">
      <div class="item" v-for="user in admins" :key="user.id" @click="allocate(record.id, user.id)">
        <div>{{user.role_name}}</div>
        <div>{{user.name}}</div>
      </div>
    </template>
    <a-icon type="swap" class="assignIcon"/>
  </a-popover>
<span>

visibleChange(visible, record) {
    if(visible) {
        this.visible = true
        this.currentId = record.id
        getCheckAdmins({order_id: record.id})
            .then(res => {
                if(res.code === 0) {
                    this.admins = res.data
                }
            })
    }
},

### What is expected?
点击域外能自动关闭

### What is actually happening?
点击域外不能关闭

**Comment by skywalker2013** [comment]
其实还是可以通过visibleChange方法来控，点击域外的时候 visible是false，然后就可以给:visible 属性赋值了

**Comment by shady-xia** [comment]
我觉得应该加一个“点击区域外是否关闭”的option
