### ISSUE TITLE
table 表格合计功能

### ISSUE THREAD

**Issue by ZzzhuzzZ** [vueComponent/ant-design-vue#3493]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
vue版本：3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-burnell-piip4?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js)

### Steps to reproduce
https://codesandbox.io/s/nice-burnell-piip4?fontsize=14&hidenavigation=1&theme=dark&file=/src/main.js

### What is expected?
在table数据下边有个自己写好的合计数据行，但是无法跟table的数据达到自适应，屏幕拖动都会出现偏差

### What is actually happening?
无法自适应

**Comment by XuedongZhou** [comment]
同问，能把表格合计功能安排上吗，这个很实用啊

**Comment by ZzzhuzzZ** [comment]
> 同问，能把表格合计功能安排上吗，这个很实用啊

后面研究了一下，只需要在a-table 添加 :scroll="{x:1000,y:500}"  x，y轴的宽，高度根据需要而定。  然后再a-table-column  定死宽度，不需要全部的column都加宽度，然后在合计部分自己画，再用弹性盒样子自适应，这样table宽度会根据合计自己画宽度自适应

**Comment by ZzzhuzzZ** [comment]
> > 同问，能把表格合计功能安排上吗，这个很实用啊
> 
> 后面研究了一下，只需要在a-table 添加 :scroll="{x:1000,y:500}" x，y轴的宽，高度根据需要而定。 然后再a-table-column 定死宽度，不需要全部的column都加宽度，然后在合计部分自己画，再用弹性盒样子自适应，这样table宽度会根据合计自己画宽度自适应

当然，如果Antd提供这个功能的话，省去很多麻烦事，开发起来也很流畅

**Comment by xiaotiansky1** [comment]
我们是每次在表格数据后面加上一个合计行

**Comment by cloudsnet** [comment]
看到没有提供tfoot 而是单独提供了一个footer 有些蒙圈，无法自适应

**Comment by 1314xulujin** [comment]
虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
1.插入两个tfoot,一个是普通的，一个是用于固定列的。
2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
4.具体步骤不懂可以联系我：微信 15970461840   qq:1599537548

**Comment by 1314xulujin** [comment]
> 看到没有提供tfoot，而是单独提供了一个footer 有些蒙圈，无法自适应
可以用插槽做到的，完美解决

**Comment by ZzzhuzzZ** [comment]
> 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> 4.具体步骤不懂可以联系我：微信 15970461840 qq:1599537548
> 5.效果图：
> ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)

能否通过沙盒来展示下如何解决呢？

**Comment by 1314xulujin** [comment]
> > 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> > 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> > 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> > 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> > 4.具体步骤不懂可以联系我：微信 15970461840 qq:1599537548
> > 5.效果图：
> > ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)
> 
> 能否通过沙盒来展示下如何解决呢？

可以，我去写一个

**Comment by ZzzhuzzZ** [comment]
> > > 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> > > 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> > > 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> > > 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> > > 4.具体步骤不懂可以联系我：微信 15970461840 qq:1599537548
> > > 5.效果图：
> > > ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)
> > 
> > 
> > 能否通过沙盒来展示下如何解决呢？
> 
> 可以，我去写一个

膜拜大佬  ORZ

**Comment by 1314xulujin** [comment]
> > > > 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> > > > 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> > > > 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> > > > 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> > > > 4.具体步骤不懂可以联系我：微信 15970461840 qq:1599537548
> > > > 5.效果图：
> > > > ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)
> > > 
> > > 
> > > 能否通过沙盒来展示下如何解决呢？
> > 
> > 
> > 可以，我去写一个
> 
> 膜拜大佬 ORZ
沙盒太卡了，我写了个demo，gitee地址是：https://gitee.com/xulujin/antdv_table.git

**Comment by ZzzhuzzZ** [comment]
> > > > > 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> > > > > 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> > > > > 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> > > > > 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> > > > > 4.具体步骤不懂可以联系我：微信 15970461840 qq:1599537548
> > > > > 5.效果图：
> > > > > ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)
> > > > 
> > > > 
> > > > 能否通过沙盒来展示下如何解决呢？
> > > 
> > > 
> > > 可以，我去写一个
> > 
> > 
> > 膜拜大佬 ORZ
> > 沙盒太卡了，我写了个demo，gitee地址是：https://gitee.com/xulujin/antdv_table.git

通俗易懂！大佬🐮🍺   ORZ

**Comment by 1314xulujin** [comment]
> > > > > > 虽然ant-design-vue没有做底部合计栏，但是通过它提供的tfoot插槽是可以插入进去的，可以实现宽度和高度的自适应，也可做到左右滑动跟随还有固定列，主要步骤：
> > > > > > 1.插入两个tfoot,一个是普通的，一个是用于固定列的。
> > > > > > 2.给他们重置好样式，固定列的根据headerlist数据判断显示还是不显示。
> > > > > > 3.左右滚动跟随，使用到了监听scroll事件，改变其scrollleft值来实现。
> > > > > > 4.具体步骤不懂可以联系我：微信 [15970461840](tel:15970461840) qq:[1599537548](tel:1599537548)
> > > > > > 5.效果图：
> > > > > > ![image](https://user-images.githubusercontent.com/55683052/108809493-e8482400-75e3-11eb-9a2c-736ed76324eb.png)
> > > > > 
> > > > > 
> > > > > 能否通过沙盒来展示下如何解决呢？
> > > > 
> > > > 
> > > > 可以，我去写一个
> > > 
> > > 
> > > 膜拜大佬 ORZ
> > > 沙盒太卡了，我写了个demo，gitee地址是：https://gitee.com/xulujin/antdv_table.git
> 
> 通俗易懂！大佬🐮🍺 ORZ

嘿嘿😁 不客气 给俺点个赞就可以

**Comment by Blackcbears** [comment]
期待此功能。。。

**Comment by PengEleven** [comment]
期待此功能。。。+1。

**Comment by Elon-188** [comment]
期待此功能。。。+1

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/132112138-8ac5b741-4bb5-41ce-a77f-5119fa77c157.png)

我是通过在表格最后push新的一行实现合计的，并对合计进行了简单的封装，[在线demo](http://buqiyuan.gitee.io/vue3-antd-admin/#/demos/summary-table)；[源码](https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/components/dynamic-table/hooks/useCalculate.ts)

**Comment by ZzzhuzzZ** [comment]
> ![图片](https://user-images.githubusercontent.com/39730999/132112138-8ac5b741-4bb5-41ce-a77f-5119fa77c157.png)
> 
> 我是通过表格最后推送新的一行实现的，证明可以简单的封装，[在线demo](http://buqiyuan.gitee.io/vue3-antd-admin/#/demos/summary-table)；[源码](https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/components/dynamic-table/hooks/useCalculate.ts)

还是要求官方能出个可配置的功能出来，这个功能太重要了！

**Comment by ZzzhuzzZ** [comment]
> ![图片](https://user-images.githubusercontent.com/39730999/132112138-8ac5b741-4bb5-41ce-a77f-5119fa77c157.png)
> 
> 我是通过表格最后推送新的一行实现的，证明可以简单的封装，[在线demo](http://buqiyuan.gitee.io/vue3-antd-admin/#/demos/summary-table)；[源码](https://github.com/buqiyuan/vue3-antd-admin/blob/main/src/components/dynamic-table/hooks/useCalculate.ts)

里面说的属性，antd没有支持呀
