### ISSUE TITLE
动态改变table cloumn 中的fixed属性，表格布局与预期不一致

### ISSUE THREAD

**Issue by FAKER-A** [vueComponent/ant-design-vue#3495]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.7

### Environment
mac, chrome, vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-andras-rists?file=/src/App.vue)

### Steps to reproduce
- 点击“改变fixed“按钮
- 将表格横向滚动到最后
- 可以看到最后一列展示不全，部分被遮挡，
- 表格前面出现一空白列

### What is expected?
表格正常显示

### What is actually happening?
- 最后一列展示不全，部分被遮挡，
- 表格前面出现一空白列

---
业务场景： 用户配置改变固定列

**Comment by FAKER-A** [comment]
老哥，我调试了一下，发现出现问题的原因如下：
1. 最终传给table的columns没有按照 fixed 属性的值排列（left -> undefined -> right)，即拥有fixed属性的为left的应该在数组的最左面，right在最右面。

现在有两种解决方案：

1. 业务代码中每次columns 改变后，自行按照fixed属性(left -> undefined -> right）进行排序。
2. 源码中加入排序逻辑帮助用户排序（用户不用关心fixed列在数组的中的位置）。

如果需要在源码中调整的话，我可以提一个相关的pr  @tangjinzhou 

感谢项目组的开源的antdv🥳

**Comment by zkwolf** [comment]
我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法

**Comment by FAKER-A** [comment]
> 我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法

ok

**Comment by Kim1am** [comment]
> > 我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法
> 
> ok

你好，目前我也遇到了相同的问题，请问你那边找到解决方案了吗thx

**Comment by FAKER-A** [comment]
> > > 我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法
> > 
> > 
> > ok
> 
> 你好，目前我也遇到了相同的问题，请问你那边找到解决方案了吗thx

```javascript
// 自定义排序方法 根据fixed值 进行排序 left -> undefined -> right
    const handleSort = (values: TableColumnsProps[]) => {
      const copyArray = deepClone(values);
      copyArray.sort((a, b) => {
        if (a.fixed === 'left' && !b.fixed) {
          return -1;
        }
        if (!a.fixed && b.fixed === 'right') {
          return -1;
        }
        if (a.fixed === 'left' && b.fixed === 'right') {
          return -1;
        }
        if (a.fixed === 'right' && b.fixed === 'left') {
          return 1;
        }
        if (a.fixed === 'right' && !b.fixed) {
          return 1;
        }
        return 0;
      });
      return copyArray;
    };
```
每次columns发生改动后，使用上面的方法进行一次排序。@Kim1am

**Comment by Kim1am** [comment]
> > > > 我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法
> > > 
> > > 
> > > ok
> > 
> > 
> > 你好，目前我也遇到了相同的问题，请问你那边找到解决方案了吗thx
> 
> ```js
> // 自定义排序方法 根据fixed值 进行排序 left -> undefined -> right
>     const handleSort = (values: TableColumnsProps[]) => {
>       const copyArray = deepClone(values);
>       copyArray.sort((a, b) => {
>         if (a.fixed === 'left' && !b.fixed) {
>           return -1;
>         }
>         if (!a.fixed && b.fixed === 'right') {
>           return -1;
>         }
>         if (a.fixed === 'left' && b.fixed === 'right') {
>           return -1;
>         }
>         if (a.fixed === 'right' && b.fixed === 'left') {
>           return 1;
>         }
>         if (a.fixed === 'right' && !b.fixed) {
>           return 1;
>         }
>         return 0;
>       });
>       return copyArray;
>     };
> ```
> 
> 每次columns发生改动后，使用上面的方法进行一次排序。@Kim1am

谢谢你的解答，目前我用分组重新排序的方法也解决了，谢谢你的思路。但是目前我遇到了一个新的BUG，请问一下你有遇到相同的情况吗？[复现地址](https://codesandbox.io/s/hopeful-joliot-9nll0?file=/src/App.vue)

**Comment by Kim1am** [comment]
> > > > 我比较倾向于外部做，可以考虑拿composition-api封装个公用的方法
> > > 
> > > 
> > > ok
> > 
> > 
> > 你好，目前我也遇到了相同的问题，请问你那边找到解决方案了吗thx
> 
> ```js
> // 自定义排序方法 根据fixed值 进行排序 left -> undefined -> right
>     const handleSort = (values: TableColumnsProps[]) => {
>       const copyArray = deepClone(values);
>       copyArray.sort((a, b) => {
>         if (a.fixed === 'left' && !b.fixed) {
>           return -1;
>         }
>         if (!a.fixed && b.fixed === 'right') {
>           return -1;
>         }
>         if (a.fixed === 'left' && b.fixed === 'right') {
>           return -1;
>         }
>         if (a.fixed === 'right' && b.fixed === 'left') {
>           return 1;
>         }
>         if (a.fixed === 'right' && !b.fixed) {
>           return 1;
>         }
>         return 0;
>       });
>       return copyArray;
>     };
> ```
> 
> 每次columns发生改动后，使用上面的方法进行一次排序。@Kim1am

我开了一个新的 [issue](https://github.com/vueComponent/ant-design-vue/issues/3556)

**Comment by FAKER-A** [comment]
@Kim1am 看起来像是宽度设置的问题
![image](https://user-images.githubusercontent.com/25676164/104980502-a276c980-5a41-11eb-8529-13e430605633.png)

**Comment by Kim1am** [comment]
@FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？

**Comment by FAKER-A** [comment]
> @FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？

这个我不敢断定，但是每一列宽度都固定，不就是已知table-width了吗。为啥还要出现amountWidth<table-width情况呢。:zany_face:

**Comment by Kim1am** [comment]
> > @FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？
> 
> 这个我不敢断定，但是每一列宽度都固定，不就是已知table-width了吗。为啥还要出现amountWidth<table-width情况呢。🤪

目前我表格定义的时x:100%,也就是说时看我当前容器的宽度的，所以。。。。。。

**Comment by FAKER-A** [comment]
> > > @FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？
> > 
> > 
> > 这个我不敢断定，但是每一列宽度都固定，不就是已知table-width了吗。为啥还要出现amountWidth<table-width情况呢。🤪
> 
> 目前我表格定义的时x:100%,也就是说时看我当前容器的宽度的，所以。。。。。。

表格宽度100%  需要最少有一列不设置宽度，要不多余的宽度，表格也不知道分配给哪一列的。

**Comment by Kim1am** [comment]
> > > > @FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？
> > > 
> > > 
> > > 这个我不敢断定，但是每一列宽度都固定，不就是已知table-width了吗。为啥还要出现amountWidth<table-width情况呢。🤪
> > 
> > 
> > 目前我表格定义的时x:100%,也就是说时看我当前容器的宽度的，所以。。。。。。
> 
> 表格宽度100% 需要最少有一列不设置宽度，要不多余的宽度，表格也不知道分配给哪一列的。

假设当前表格我设置的时100%宽度，最后一列是自适应的，进行fixed也会有问题的吧。
目前我这边做了自定义固定列、隐藏和显示列、拖拽列宽的功能。给我感觉，如果说fixed的宽度是继承scroll-table的宽度的话，体验会好很多

**Comment by Kim1am** [comment]
> > > > @FAKER-A 如果说，每一列都固定宽度，amountWidth<table-width，即无解？
> > > 
> > > 
> > > 这个我不敢断定，但是每一列宽度都固定，不就是已知table-width了吗。为啥还要出现amountWidth<table-width情况呢。🤪
> > 
> > 
> > 目前我表格定义的时x:100%,也就是说时看我当前容器的宽度的，所以。。。。。。
> 
> 表格宽度100% 需要最少有一列不设置宽度，要不多余的宽度，表格也不知道分配给哪一列的。

目前我看到是有机制如果说每一列都固定宽度，并且不足以撑满表格宽度时，是有分配机制的
