### ISSUE TITLE
a-table自定义表头中的点击事件无效

### ISSUE THREAD

**Issue by babydada** [vueComponent/ant-design-vue#3496]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.1

### Environment
mac os, Google Chrome 87.0.4280.88

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-deuui?file=/src/App.vue)

### Steps to reproduce
<a-table-column dataIndex="create_on" width="180px">
<div slot="title" class="rowflex flex1 align-items-center space-between">
<span>操作时间</span>
<div class="rowflex">
<a-icon type="caret-down" :style="{color:'#bfbfbf'}" class="c pointer" v-if="sort !== 'DESC'" @click="sortAct('DESC')" />
<a-icon type="caret-down" :style="{color:'#00796B'}" class="d" v-if="sort === 'DESC'"  />
<a-icon type="caret-up" :style="{color:'#bfbfbf'}" class="a" v-if="sort !== 'ASC'" @click="sortAct('ASC')" />
<a-icon type="caret-up" :style="{color:'#00796B'}" class="b" v-if="sort === 'ASC'"/>
</div>
</div>
</a-table-column>

class为a的该图标，click被清除了，如果把classsss c,d的放到class a,b后，则class c的事件不执行了

### What is expected?
能够点击执行事件

### What is actually happening?
click事件消失了

**Comment by John60676** [comment]
这是 Vue 的知识点 “[**用 key 管理可复用的元素**](https://cn.vuejs.org/v2/guide/conditional.html#%E7%94%A8-key-%E7%AE%A1%E7%90%86%E5%8F%AF%E5%A4%8D%E7%94%A8%E7%9A%84%E5%85%83%E7%B4%A0)”

参考：https://codesandbox.io/s/vue-antd-template-forked-jr6hp?file=/src/App.vue
