### ISSUE TITLE
Pagination showSizeChange 参数首参数应为更改后的条数

### ISSUE THREAD

**Issue by m17319325007** [vueComponent/ant-design-vue#3498]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用TS语法参数都为必选项,或者更改TSlint配置,不然会use提示,一般使用都是更改页面后,重置为第一页,当前更改后的页码也很有必要,但事在此事件应为第二参数

### What does the proposed API look like?
Function(size,current)

**Comment by John60676** [comment]
这个你可以自己封装一层

**Comment by m17319325007** [comment]
好吧。
