### ISSUE TITLE
Pagination pageSizeOptions 指定数量后,页码显示不全问题

### ISSUE THREAD

**Issue by m17319325007** [vueComponent/ant-design-vue#3499]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
下拉分页切换页码select 继承了父级高度,我这边目前父级可能是因为bug没有显示页/条中文字幕,下拉因为父级宽度自适应导致子集宽度不能显示全,希望下拉显示全,为防止宽度过大设置最大宽度就OK

### What does the proposed API look like?
.ant-pagination-options {
.ant-select-dropdown {
width: auto;
max-width: 100px;
}
}

**Comment by m17319325007** [comment]
https://github.com/LSP-XA/vue3-filters.git 
路由/home 页面有图示
早上是因为标红的部分没有显示文字,只显示了数字所以比较明显,导致 pageSizeOptions 集合 10 20都无法正常显示

**Comment by John60676** [comment]
不太懂，这个仓库哪个页面有这个问题的重现

**Comment by m17319325007** [comment]
/home，抱歉我只做了标红，文字问题没有重现，早上出现，切换条码后，当前页条数框只显示数字，不显示文字，这个问题没有复现。希望可切换条数过大也不会有遮挡，尤其在中文下。
