### ISSUE TITLE
vite 2.0引入后启动报错

### ISSUE THREAD

**Issue by miniai** [vueComponent/ant-design-vue#3500]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
```bash
"ant-design-vue": "^2.0.0-rc.8"
"vue": "^3.0.5" 
"vite": "^2.0.0-beta.7"
```

### Reproduction link
[https://github.com/miniai/ant-vite-error.git](https://github.com/miniai/ant-vite-error.git)

### Steps to reproduce
引入ant后，npm run dev启动，无法正常启动，会报错

### What is expected?
正常启动

### What is actually happening?
Uncaught SyntaxError: The requested module '/node_modules/@ant-design/icons-vue/DownOutlined.js?v=5.1.9' does not provide an export named 'default'

**Comment by John60676** [comment]
把 `ant-design-vue` 从 `optimizeDeps.exclude` 里面移除

**Comment by miniai** [comment]
谢谢，是这个导致的
