### ISSUE TITLE
table的customRender函数可以返回vue标签吗

### ISSUE THREAD

**Issue by shanhan0** [vueComponent/ant-design-vue#3503]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        

customRender: (text, record) => {
const txt =  record['origin'][i-1] && record['origin'][i-1]['value']
return txt   <img src="~assets/images/mobile/account.png"/>

}

希望可以返回一张图片和名字

**Comment by John60676** [comment]
你可以返回一个 JSX

https://github.com/vuejs/jsx-next#syntax

```jsx
customRender: (text, record) => (
  <div>
    <img src="xxx.jpg" />
    <span> name </span>
  </div>
)
```

**Comment by shanhan0** [comment]
但是我还要在customrender中对数据坐一下处理 ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;John&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月8日(星期五) 下午5:23
收件人:&nbsp;&quot;vueComponent/ant-design-vue&quot;<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;&quot;shanhan0&quot;<2993369376@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] table的customRender函数可以返回vue标签吗 (#3503)

**Comment by shanhan0** [comment]
大佬，还是不行，报错，h is not defined




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月8日(星期五) 下午5:23
收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"2993369376"<2993369376@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] table的customRender函数可以返回vue标签吗 (#3503)





 
你可以返回一个 JSX
 
https://github.com/vuejs/jsx-next#syntax
 customRender: (text, record) =&gt; (   <div&gt;     <img src="xxx.jpg" /&gt;     <span&gt; name </span&gt;   </div&gt; )

**Comment by John60676** [comment]
参考：https://github.com/vuejs/jsx-next/issues/5

**Comment by huoyuhao** [comment]
```

import {  h  } from 'vue';
import { Button } from '@ant-design/icons-vue';

...

components: { Button },
...
children: h(<Button>点击</Button>)
```
成功，当时为何使用下面渲染失败，怎么解决，我不想使用jsx语法
`h('a-button', '点击')`

**Comment by John60676** [comment]
> ```
> import {  h  } from 'vue';
> import { Button } from '@ant-design/icons-vue';
> ...
> components: { Button },
> ...
> children: h(<Button>点击</Button>)
> ```
> 
> 成功，当时为何使用下面渲染失败，怎么解决，我不想使用jsx语法
> `h('a-button', '点击')`

vue3 的 `h` 不支持**字符串形式的自定义组件**

```js
import {  h  } from 'vue';
import { Button } from 'ant-design-vue';

...

h(Button, '点击')

```

**Comment by sumile-ting** [comment]
> 大佬，还是不行，报错，h is not defined
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "vueComponent/ant-design-vue" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月8日(星期五) 下午5:23 收件人:&nbsp;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 抄送:&nbsp;"2993369376"<2993369376@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue] table的customRender函数可以返回vue标签吗 (#3503) 你可以返回一个 JSX https://github.com/vuejs/jsx-next#syntax customRender: (text, record) =&gt; ( <div&gt; <img src="xxx.jpg" /&gt; <span&gt; name </span&gt; </div&gt; ) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

解决了吗

**Comment by aboutcroon** [comment]
> 参考：[vuejs/babel-plugin-jsx#5](https://github.com/vuejs/babel-plugin-jsx/issues/5)

This is not the same question ...
This won't help
