### ISSUE TITLE
typescript 环境,  Table  type 文件 columns 没有 slots 属性, 但实际上是可用的

### ISSUE THREAD

**Issue by chenxxzhe** [vueComponent/ant-design-vue#3504]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
"vue": "^3.0.0"

### Reproduction link
[https://www.nothing.com](https://www.nothing.com)

### Steps to reproduce
const cols: TableState['columns'] = [{
title: 'Action',
slots: { customRender: 'action' },  /*这里 typescript 报错 */
}]

### What is expected?
columns 有定义 slots 属性

### What is actually happening?
columns 没有定义 slots 属性

**Comment by zkwolf** [comment]
Fixed in latest version
