### ISSUE TITLE
自定义 font 图标 不继承自定义类名

### ISSUE THREAD

**Issue by insertSweat** [vueComponent/ant-design-vue#351]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.3

### Environment
Mac OS X 10_13_6 Chrome/71.0.3578.98 Vue2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/llx5y6p1yl)

### Steps to reproduce
我测试了react antd 没有这个问题 地址： [https://codesandbox.io/s/n05j62jxw0](https://codesandbox.io/s/n05j62jxw0)

使用iconfont的自定义图标时就会出现这个问题

### What is expected?
继承class

### What is actually happening?
未继承

**Comment by tangjinzhou** [comment]
please update to 1.2.4
