### ISSUE TITLE
在table中使用switch组件，从on切换至off再切换至on，然后刷新数据，switch失效

### ISSUE THREAD

**Issue by RicardoWL** [vueComponent/ant-design-vue#3512]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
vue:3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/snowy-hooks-j1ip0?file=/src/App.vue)

### Steps to reproduce
1.switch从on切换至off，然后再切换至on
2.点击refresh刷新数据
3.点击switch切换

### What is expected?
swtich正常切换状态

### What is actually happening?
switch未正常切换状态，也未触发loading

---
2.0.0-rc.5版本正常
初步断定应该是table中数据绑定更新出现问题，未正常进行对应数据的更新。

**Comment by tangjinzhou** [comment]
神奇的问题，问题虽然解决了  还需进一步定位，大概率还是vue3的锅
