### ISSUE TITLE
是否考虑出tsx版本使用文档，比如在实例中加入tsx使用方式

### ISSUE THREAD

**Issue by yangyin** [vueComponent/ant-design-vue#3518]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在slot使用时坑多，比如table组件中

### What does the proposed API look like?
tsx的样例

**Comment by sendya** [comment]
你可以按照 JSX 的文档来使用 slot 等

https://github.com/vuejs/jsx-next#slot

**Comment by yangyin** [comment]
这个文档我知道，在组件使用时还是有一定差别，比如：Result（直接在组件属性中就重写了slot）中和Table/Form（使用jsx-next文档中方式）中使用slots完全不一样，还是有细微差别
另：
比如在写Table中写columns时，不能加入ColumnProps，因为这里面没有slots
在Menu中结合RouterLink时，样式是有问题的

**Comment by yangyin** [comment]
vue3.0推崇ts，样例中可适当加入ts写法

**Comment by yangyin** [comment]
jsx中，怎么使用emit自定义事件，掉坑了

**Comment by John60676** [comment]
> jsx中，怎么使用emit自定义事件，掉坑了

把事件传进组件里调用就好了啊

**Comment by yangyin** [comment]
我目前也是这么做的，但是想寻求是否有vue emit的处理方式

**Comment by bhabgs** [comment]
> 我目前也是这么做的，但是想寻求是否有vue emit的处理方式



> > jsx中，怎么使用emit自定义事件，掉坑了
> 
> 把事件传进组件里调用就好了啊

![image](https://user-images.githubusercontent.com/19221378/104559165-f6b72d80-567e-11eb-97d9-8996531672b7.png)

**Comment by tangjinzhou** [comment]
会出 ts 文档，但不会出 tsx 文档
