### ISSUE TITLE
MenuItem inside of <router-link> renders "undefined-item" class.

### ISSUE THREAD

**Issue by phoenixgao** [vueComponent/ant-design-vue#3527]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue@2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-881sg?file=/src/App.vue)

### Steps to reproduce
Add a router-link to wrap a menu item

### What is expected?
menu item works

### What is actually happening?
menu item not working, it's class is render as `undefined-item` instead of `ant-menu-item`

**Comment by phoenixgao** [comment]
There are similiar issues but either get closed automatically, or like this one https://github.com/vueComponent/ant-design-vue/issues/547 was closed manually without a proper solution.

Having a router-link around menu-item is a common use case.

**Comment by tangjinzhou** [comment]
you can not use menu-item in router-link.
you can use router-link in menu-item.
or use router api

**Comment by phoenixgao** [comment]
@tangjinzhou If you did take a look at my example in the above reproduction link, you see that I used router-link in the outer level so I can pass `isActive` and `isExactActive` to menu-item, so I can add class `ant-menu-item-selected` accordingly.

If I put router-link inside menu-item, I have to implement all the routing matches with the selected class repeatedly.

Would you mind shine some light to me?
