### ISSUE TITLE
树形table在销毁时页面卡死

### ISSUE THREAD

**Issue by TaoHuaXia** [vueComponent/ant-design-vue#3531]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
vue@3.0.2 antd-vue@2.0.0-rc.8

### Reproduction link
https://codesandbox.io/s/trusting-leaf-hmrxh?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce
1.使用树形table展示数据（约1000条左右）
2.对组件进行销毁

### What is expected?
可以迅速销毁

### What is actually happening?
页面卡死大约10s以上

---
通过issue可看到类似的https://github.com/vueComponent/ant-design-vue/issues/2508，虽然issue已被关闭，但是感觉没有进行解决（包括查看了后面的合并的代码，也没有解决此问题的提交）

**Comment by TaoHuaXia** [comment]
补充：tableData从1000条数据（叶子节点）更新为空数组，也会直接卡死

**Comment by TaoHuaXia** [comment]
https://codesandbox.io/s/trusting-leaf-hmrxh?fontsize=14&hidenavigation=1&theme=dark

**Comment by TaoHuaXia** [comment]
现在已经在项目中使用，所以望大佬们能给个解决方案

**Comment by TaoHuaXia** [comment]
暂时先用了element的table，等修复后再切换回来

**Comment by betgar** [comment]
@TaoHuaXia 可以试试这个https://github.com/x-extends/vxe-table

**Comment by TaoHuaXia** [comment]
> @TaoHuaXia 可以试试这个https://github.com/x-extends/vxe-table

@betgar 感谢老哥，我已经先用element的table顶着了

**Comment by eeeqxxtg** [comment]
我可能定位到了性能问题：
https://github.com/vueComponent/ant-design-vue/blob/f589c8f7233586427f2a5731e09ed1beb1ef115d/components/_util/store/create.js#L5

1000行的table，每一个row都subscribe了store。
这1000行数据，每一行的变化都会同时触发其他999行注册的事件。极端情况下，性能就被吃掉太多了。
比如卸载这1000行数据，会触发1000+999+998+...1=500500次注册事件。就算每个注册事件耗时0.02ms，整个卸载过程也会耗时超过10s。

建议这里的store考虑使用vue的响应式设计

**Comment by eeeqxxtg** [comment]
https://github.com/vueComponent/ant-design-vue/blob/f589c8f7233586427f2a5731e09ed1beb1ef115d/components/vc-table/src/ExpandableTable.jsx#L116

注释掉这行代码，可以极大提高楼主的卸载速度。

**Comment by tangjinzhou** [comment]
update to 2.0.1

**Comment by cnguu** [comment]
> update to 2.0.1

1.x版本存在同样的销毁性能问题

**Comment by betgar** [comment]
希望能够移植回到1.x

**Comment by zkwolf** [comment]
1.x应该发版到1.7.4了

**Comment by AlexZhong22c** [comment]
@zkwolf 1.74修复了。但是1.75之后好像函数还在

**Comment by AlexZhong22c** [comment]
不同意楼上 zkwolf所说的，1.x还是有问题

**Comment by AlexZhong22c** [comment]
@zkwolf 老哥，这个bug分配了给你。现在1.x还是有问题的
