### ISSUE TITLE
modal 太宽会被挤到页面下方去

### ISSUE THREAD

**Issue by kshq1996** [vueComponent/ant-design-vue#3534]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue 1.7.2

### Reproduction link
[https://2x.antdv.com/components/modal-cn/](https://2x.antdv.com/components/modal-cn/)

### Steps to reproduce
modal宽度设为1100然后左右缩放的时候 宽度会减少一些，但是会被挤到下方，要下滑才能看到，而且蒙层还在，但是当宽度小于768的时候会自动适应宽度又上来了

### What is expected?
应该会缩放到 < 768的时候那种 适应宽度就好了

### What is actually happening?
modal宽度设为1100然后左右缩放的时候 宽度会减少一些，但是会被挤到下方，要下滑才能看到，而且蒙层还在，但是当宽度小于768的时候会自动适应宽度又上来了

**Comment by kshq1996** [comment]
视频：
https://user-images.githubusercontent.com/25955989/104438116-9797e100-55ca-11eb-9719-ed0b13c36dc5.mp4


https://user-images.githubusercontent.com/25955989/104438131-9b2b6800-55ca-11eb-842a-2dd91c509d60.mp4

**Comment by kshq1996** [comment]
是不是我写的不对导致的？

**Comment by Hyphon** [comment]
最好把组件版本，vue版本标识清楚。还有最好能提供一份最小的可复现问题的代码。

**Comment by SmileTR** [comment]
请问如何解决这个问题，我也遇到了相同问题 @kshq1996
