### ISSUE TITLE
Input.Search指定class无效

### ISSUE THREAD

**Issue by jackhe16** [vueComponent/ant-design-vue#3539]
- [] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
- mac os 10.15.6
- chrome  87.0.4280.141
- vue 3.0.5

### Reproduction link
[https://github.com/jackhe16/antdv-input-search-class-demo](https://github.com/jackhe16/antdv-input-search-class-demo)

### Steps to reproduce
在vue3使用2.0.8版本ant-design-vue时, Input.Search组件传递class props无效

### What is expected?
Input.Search组件传递class属性生效

### What is actually happening?
Input.Search组件传递class属性无效

### Additional
<https://github.com/vueComponent/ant-design-vue/blob/next/components/input/Search.tsx#L170>

```javascript
if (enterButton) {
  inputClassName = classNames(prefixCls, className, {
    [`${prefixCls}-enter-button`]: !!enterButton,
    [`${prefixCls}-${size}`]: !!size,
  });
} else {
  inputClassName = prefixCls;
}
```

```javascript
if (enterButton) {
  inputClassName = classNames(prefixCls, className, {
    [`${prefixCls}-enter-button`]: !!enterButton,
    [`${prefixCls}-${size}`]: !!size,
  });
} else {
  inputClassName = classNames(prefixCls, className);
}
```

**Comment by zkwolf** [comment]
welcome pr
