### ISSUE TITLE
Table组件的表头实现固钉功能

### ISSUE THREAD

**Issue by nnzbz** [vueComponent/ant-design-vue#3545]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如题，Table组件的表头实现固钉功能
表格比较长，滚动到后面时，能把表头固定在上方

### What does the proposed API look like?

```html
<Table
headerAffix="true"
/>
```

**Comment by zkwolf** [comment]
https://2x.antdv.com/components/table-cn/#%E5%9B%BA%E5%AE%9A%E5%A4%B4%E5%92%8C%E5%88%97

**Comment by nnzbz** [comment]
@zkwolf 你理解错意思了，这里说的固定表头指的是header，不是固定列

**Comment by nnzbz** [comment]
@zkwolf 固定表头不是像demo那样设置一个高度，然后行可以滚动，表头固定。
我这里指的是高度超长了，长过页面了，滚动页面的时候，当表头滚动到页面顶部时，固定在那里，行可以继续滚
如果不理解的话，可以看看Affix(固钉)组件，要的是那个效果

**Comment by zkwolf** [comment]
反复脑补了一下大概理解了，就是滚到table header的时候header固定然后内容滚动？

nnzbz <notifications@github.com> 于2021年1月16日周六 上午9:17写道：

**Comment by nnzbz** [comment]
@zkwolf 是的，这个是针对页面滚动的，不是表格里的行滚动

**Comment by nnzbz** [comment]
就是Affix(固钉)组件那个demo的效果，我想应该用Affix(固钉)组件把表头包裹一下就可以了，但目前好像没有api，要自定义实现不知道如何做，有否暴露自定义渲染表头的API？

**Comment by 296604153** [comment]
@nnzbz 你好，这个功能现在有好的解决方案吗？
