### ISSUE TITLE
Table header sticky feature

### ISSUE THREAD

**Issue by nnzbz** [vueComponent/ant-design-vue#3547]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?

如题，Table组件的表头实现固钉功能
表格比较长，滚动到后面时，能把表头固定在上方

**注意！注意！注意！没看懂之前请不要再关闭了**
这个功能不是像demo那样设置一个高度，然后行可以滚动，表头固定。
我这里指的是高度超长了，长过页面了，滚动页面的时候，当表头滚动到页面顶部时，固定在那里，行可以继续滚
如果不理解的话，可以看看Affix(固钉)组件，要的是那个效果

### What does the proposed API look like?
```html
<Table
headerAffix="true"
/>
```

**Comment by tangjinzhou** [comment]
着急的话使用 position:sticky 自行实现

**Comment by nnzbz** [comment]
@tangjinzhou 不知道在哪里设置 `position:sticky`，我在浏览器的元素的header，tr，th里都设置了一下，加上了 `top: 0`，似乎受父容器的某些设置冲突，没有起效果

**Comment by Wobugaosuni** [comment]
> @tangjinzhou 不知道在哪里设置 `position:sticky`，我在浏览器的元素的header，tr，th里都设置了一下，加上了 `top: 0`，似乎受父容器的某些设置冲突，没有起效果

+1

**Comment by heboliufengjie** [comment]
> @tangjinzhou 不知道在哪里设置 `position:sticky`，我在浏览器的元素的header，tr，th里都设置了一下，加上了 `top: 0`，似乎受父容器的某些设置冲突，没有起效果

+1

**Comment by plusice** [comment]
弄了个vue指令可以支持：https://gist.github.com/plusice/87e3e89cbba417dfff0c990723ed55b4
