### ISSUE TITLE
inputNumber组件格式化返回值错误

### ISSUE THREAD

**Issue by daijie1989** [vueComponent/ant-design-vue#3548]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
win10, Chrome 87.0.4280.141, vue2.6.10

### Reproduction link
[https://2x.antdv.com/components/input-number-cn/#格式化展示](https://2x.antdv.com/components/input-number-cn/#格式化展示)

### Steps to reproduce
官网案例 格式化展示 输入数字10000

### What is expected?
应该展示$ 10,000

### What is actually happening?
实际展示$ 100,000

**Comment by ajuner** [comment]
#3298
定位一下，应该是win10微软输入法出现的问题吧
