### ISSUE TITLE
TreeSelect组件在无数据的时候，无法正常渲染

### ISSUE THREAD

**Issue by jiacy061** [vueComponent/ant-design-vue#355]
### **Version**
1.2.3

### **Environment**
Win10 Chrome/70.0.3538.77 Vue2.5.17

Reproduction link
[![Edit Vue Antd Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2pjkr0n67n)

Steps to reproduce
最新版的地址 https://codesandbox.io/s/2pjkr0n67n

1.1.7版本重现地址： https://codesandbox.io/s/j22nx8jpv3

What is expected?
和旧版一致，在没有数据的时候正常显示“Not Found”

What is actually happening?
新版报错，无法在无数据的时候正常打开TreeSelect，难道是新特征？
React版本也有同样的问题。

`[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"
found in
---> <BasePopup>
       <SinglePopup>
         <Anonymous>
           <Anonymous>
             <Anonymous>
               <Anonymous>
                 <Anonymous>
                   <Trigger>
                     <SelectTrigger>
                       <TreeSelect>
                         <Anonymous>
                           <ATreeSelect>
                             <TreeSelect> at /src/components/TreeSelect.vue
                               <App> at /src/App.vue
                                 <Root>`

**Comment by tangjinzhou** [comment]
可以传递一个空数组解决：
`<a-tree-select :treeData="[]"/>`

下个版本会做兼容

**Comment by tangjinzhou** [comment]
please update to 1.2.4
