### ISSUE TITLE
select选择器，选择列表的数据比较多时会造成页面卡顿。

### ISSUE THREAD

**Issue by cheng11231456** [vueComponent/ant-design-vue#3552]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
Vue：2.6.10，谷歌浏览器

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
-

### What is expected?
页面流畅无卡顿

### What is actually happening?
select选择器。当下拉列表数据为200条时，根据输入项进行筛选时输入中文搜索时会使页面变的卡顿，

**Comment by tangjinzhou** [comment]
升级到2.0 版本支持虚拟滚动

**Comment by cheng11231456** [comment]
ant design vue 好像没有更新到2.0我看最新更新记录也就1.7.2

**Comment by loveyyao** [comment]
2.0的版本不支持Vue2.0版本的吧

**Comment by yeerbaobao** [comment]
怎么升级到2.0.。。。

**Comment by AmmyXu** [comment]
请问，有计划再1.*版本加入虚拟滚动条吗

**Comment by xuchao996** [comment]
> 请问，有计划在1.*版本加入虚拟滚动吗

同问
