### ISSUE TITLE
a-table组件页面自定义fixed列后，有scroll情况下正常，无scroll情况下宽度不匹配

### ISSUE THREAD

**Issue by Kim1am** [vueComponent/ant-design-vue#3556]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue: 2.6.11,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-joliot-9nll0?file=/src/App.vue)

### Steps to reproduce
1、每一列固定宽度
2、所有列宽度不足a-table总宽度
3、fixed某一列
即可复现

### What is expected?
当所有列宽度不足a-table总宽度时（无scroll），fixed固定的某一列，应继承原有a-table的width auto-width。而不是单独width
当width综合超过a-table宽度是不会出现该bug

### What is actually happening?
fixed列后，出现空隙。经确认：fixed列宽度 = colums设置width。而table宽度对应的colums宽度时width  auto-width（自适应宽度）。从而导致宽度不匹配的空隙出现

**Comment by tangjinzhou** [comment]
留一列不设置宽度自适应

**Comment by Kim1am** [comment]
> 留一列不设置宽度自适应

您好，如果我需要配合拖拽+列固定的话，这样是不是会有问题？因为fixed列是根据colums原始设定的width展现的，如果拖拽后，再进行fixed，那是否有问题？
