### ISSUE TITLE
The component needs a fixed property to carry business data

### ISSUE THREAD

**Issue by betgar** [vueComponent/ant-design-vue#3559]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
The component needs a fixed property to carry business data, and the fixed attribute can prevent potential conflicts with the component's own properties.

### What does the proposed API look like?
```javascript
// example: Select Options
// Options:  array<{value, label, [disabled, key, title]}>
// add a `extraData` prop for business data
// demo
const options = [
{
key: 1,
value: 1,
title: 'Org',
extraData: {
// some props
}
}
]
```

**Comment by sendya** [comment]
try

```vue
<a-select>
  <a-select-option v-for="item in businessData " :value="item.value">{{ item.xxx }}</a-select-option>
</a-select>
```

**Comment by sendya** [comment]
or

```js
<a-select :options="businessData.map(item=>return { label:item.xxx, value: item.abc })" />
```

**Comment by betgar** [comment]
@sendya First, thank you for you work and thank you team.
You misunderstand what I say. Because the select `options.value` only be `string | number`, that's  cannot satisfy the need. 
When I use select `change` event, I need the second arguments `options`, `onChange(value, option)`, but option is not a pure data model, it is a VNode, so I debug it.

![image](https://user-images.githubusercontent.com/15810150/106140608-f4d68980-61a9-11eb-8d69-7426d217a83c.png)

Because the in the onChange handler I need the `value` and `other data` , so I give the option data model like this 
```
const options = [
   value: 6626079,
   title: 'Test org'
   orgCode: 'test',
   orgId: 6626079
]
```
`<a-select :options="options"  @change="onChange"/>`
but when I get it inside the `onChange` handler, I must be write it like this `option.data.props.orgCode`. This code has big risk in the future.

A other example:  The tree `onCheck` event , the handler signature is ` function(checkedKeys, e:{checked: bool, checkedNodes, node, event})`,  the `e.node` is also a VNode type, so when I want get tree node prop `isLeaf`, I do it like this.

![image](https://user-images.githubusercontent.com/15810150/106142343-5a2b7a00-61ac-11eb-970b-9952545e7548.png)

I don't know is there have other ways to do this. If no, the code has big risk in future. So I hope  team, consider that, give a fixed property or fixed method  to carry other data  which I passed to the Component options. So if possable, I hope team consider
my advice.

example: 
![image](https://user-images.githubusercontent.com/15810150/106143592-f609b580-61ad-11eb-9fec-8de2a64e2d43.png)

![image](https://user-images.githubusercontent.com/15810150/106143665-10dc2a00-61ae-11eb-8ed0-d07640e04a8a.png)
