### ISSUE TITLE
二次封装form、select，select回显bug

### ISSUE THREAD

**Issue by zoushenglin** [vueComponent/ant-design-vue#3561]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
所有版本

### Reproduction link
[二次封装select回显bug](https://github.com/vueComponent/ant-design-vue/issues/9999)

### Steps to reproduce
<RequestModal @form="getForm" ref="requestModal" :title="isAdd ? '新增店铺' : '修改店铺'" :requestFn="requestFn" :wrapperCol="{span: 15}" v-bind="$attrs">
<template #default>
<a-form-item label="店铺名称">
<a-input placeholder="请输入店铺名称" v-decorator="['name', {rules: [{
required: true,
message: '请输入店铺名称'
}]}]" />
</a-form-item>
<a-form-item label="片区" :wrapperCol="{span: 18}">
<a-row>
<a-col :span="20">
<HgboxScrollRequestSelect @search="search" :data="chooseAreaRequestFn" placeholder="请选择片区" v-decorator="['area_id']"></HgboxScrollRequestSelect>

</a-col>
<a-col :span="4">
<a-button type="primary" style="margin-left: 10px;" @click="$refs.addAreaModal.show()">新增片区</a-button>
</a-col>
</a-row>
</a-form-item>
<a-form-item label="货柜编号">
<a-input placeholder="请输入货柜编号" v-decorator="['cabinet_code']" />
</a-form-item>
<a-form-item label="详细地址">
<a-input placeholder="请输入详细地址" v-decorator="['address', {rules: [{
required: true,
message: '请输入详细地址'
}]}]" />
</a-form-item>
</template>
</RequestModal>

HgboxScrollRequestSelect组件代码
<a-select v-bind="$attrs" show-search @popupScroll="popupScroll" :options="options" @search="search" :filterOption="false" v-on="$listeners"></a-select>

### What is expected?
回显正常

### What is actually happening?
二次封装的select回显有问题

**Comment by zoushenglin** [comment]
@zkwolf 您好，已经创建demo了，https://codesandbox.io/s/vue-antd-template-forked-gmku7

**Comment by zkwolf** [comment]
1.x吗？自定义组件需要提供value受控属性和onChange事件

**Comment by zoushenglin** [comment]
@zkwolf  是的，1.6.2版本，好的，我试试看，感谢

**Comment by zoushenglin** [comment]
用v-decorator指令不能生效吗？我用的这个指令的，在表单新增的时候没问题，但是表单修改的时候，需要把数据回填到select中，这个时候就回填不了了
