### ISSUE TITLE
<a-table bordered>存在嵌套子表格时会影响子表格样式，且主表格不可scroll

### ISSUE THREAD

**Issue by galleonsZcc** [vueComponent/ant-design-vue#3568]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
vue 3.x

### Reproduction link
[https://2x.antdv.com/components/table-cn/#API](https://2x.antdv.com/components/table-cn/#API)

### Steps to reproduce
主表格使用带边框的样式bordered，且设置:scroll="{y: 300}"
#expandedRowRender嵌套子表格并设置:bordered="false"

### What is expected?
期望主表格可设置滚动，且子表格样式独立，无边框。

### What is actually happening?
主表格存在scroll且有子表格时会提示:
warning.js?2149:6 Warning: [antdv: `expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.]。
同时子表格受主表格影响，存在边框

**Comment by galleonsZcc** [comment]
经试验，macos环境下warning存在但是实际效果不受影响，主表格可以scroll

**Comment by galleonsZcc** [comment]
缺少rowExpandable参数，无法设置是否需要expandedRowRender

**Comment by bufanyun** [comment]
Warning: [antdv: `expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.] 

这个问题还没有解决吗

**Comment by a981610389** [comment]
试了下可以吧expandedRowRender整成变量，组件初始化后再赋值跳过这个警告
