### ISSUE TITLE
 this.form.setFieldsValue赋值问题

### ISSUE THREAD

**Issue by wuyouzhuguli** [vueComponent/ant-design-vue#357]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.3

### Environment
win10 chrome70 vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/32vvk0x5q1)

### Steps to reproduce
第一次点击open打开抽屉，form表单无法成功赋值，第二次打开才成功

### What is expected?
第一次打开便可赋值

### What is actually happening?
第二次打开才赋值

**Comment by tangjinzhou** [comment]
建议使用按需加载，你会得到相关提示，
抽屉内容是打开时才会渲染，所以第一次打开时，不能立即setFieldsValue,你可以通过getFieldDecorator进行注册，或放在nextTick中setFieldsValue。
https://codesandbox.io/s/8lp3989kyj

**Comment by wuyouzhuguli** [comment]
好的，非常感谢您的解答
