### ISSUE TITLE
在Drawer的某个按钮调用Modal后关闭，然后关闭Drawer，Modal会弹出

### ISSUE THREAD

**Issue by Roxannej** [vueComponent/ant-design-vue#3572]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
谷歌浏览器最新版

### Reproduction link
[https://www.antdv.com/components/modal-cn/](https://www.antdv.com/components/modal-cn/)

### Steps to reproduce
1、打开Drawer，点击按钮，弹出Modal
2、点击Modal的确定，关闭Modal（如果点击❌关闭则不会出现这个情况）
3、关闭Drawer，Modal再一次显示

### What is expected?
点击Drawer中的按钮，打开Modal，点击Modal的确定，关闭Modal，关闭Drawer，Modal不会弹出

### What is actually happening?
点击Drawer中的按钮，打开Modal，点击Modal的确定，关闭Modal，关闭Drawer，Modal弹出

**Comment by zkwolf** [comment]
迷惑。。。给个复现或者录像？

**Comment by Roxannej** [comment]
> Hello @Roxannej. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @Roxannej, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。



> Hello @Roxannej. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @Roxannej, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

最近有点儿忙，过年有时间，然后复现下
