### ISSUE TITLE
select组件的输入框没有随被选中选项的title改变

### ISSUE THREAD

**Issue by MeowTownMeow** [vueComponent/ant-design-vue#3574]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
win10/chrome78.0/vue3.0.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-z3vkq?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.vue)

### Steps to reproduce
1/点击按钮获取title
2/切换select选项

### What is expected?
select输入框为被选中选项的title

### What is actually happening?
select输入框没有随选中选项的title而改变

**Comment by zkwolf** [comment]
https://codesandbox.io/s/vue-antd-template-forked-of0tq?file=/src/App.vue 需要初始化select.value，要不然会丢响应
原因可以参考https://cn.vuejs.org/v2/guide/reactivity.html#%E5%AF%B9%E4%BA%8E%E5%AF%B9%E8%B1%A1
