### ISSUE TITLE
Table 合并行列配合可扩展,合并区域无法包含扩展区域

### ISSUE THREAD

**Issue by kagaricyan** [vueComponent/ant-design-vue#3578]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
chrome vue 2.6

### Reproduction link
[https://github.com/kagaricyan/bug-demo](https://github.com/kagaricyan/bug-demo)

### Steps to reproduce
无

### What is expected?
列对齐

### What is actually happening?
扩展展开后列没有对齐

**Comment by tangjinzhou** [comment]
这个交互就有问题
展开区域和合并行 是冲突的
展开的会占 rowSpan 一行，会导致错乱
建议更改交互

**Comment by kagaricyan** [comment]
> 这个交互就有问题
> 展开区域和合并行 是冲突的
> 展开的会占 rowSpan 一行，会导致错乱
> 建议更改交互

我的场景是表格某一列需要合并行，同时每行有额外内容需要展开显示其余信息。希望能考虑下这种场景的解决方案。
