### ISSUE TITLE
级联选择器a-cascader，异步加载数据lodata没有反应，请问怎么解决？

### ISSUE THREAD

**Issue by yu-aa** [vueComponent/ant-design-vue#3581]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
vue2.0

### Reproduction link
[https://www.antdv.com/components/cascader-cn/#API](https://www.antdv.com/components/cascader-cn/#API)

### Steps to reproduce
<a-cascader
:options="assetTypeOption"
placeholder="请选择设备类型"
style="color: #0a0b0e"
change-on-select
:load-data="loadData"
/>

方法：loadData（selectedOptions）{
const targetOption = selectedOptions [selectedOptions.length-1];
console.log（targetOption，'targetOption =='）
}，
打印日志没有反应：console.log（targetOption，'targetOption =='）

### What is expected?
怎么使用:load-data="loadData"

### What is actually happening?
能实际运用

**Comment by MillyTang** [comment]
@yu-aa hello,  刚遇到同样的问题，观察了一下他们给定的数据类型，你应该在数据项
[{
        value: 'xxx',
        label: 'xxx',
        isLeaf: false,
 }] 中给定 isLeaf 的值才可以，我试过了，第一级的数据项内加了isLeaf， loadData就起作用了
