### ISSUE TITLE
Carousel 走马灯自定义分页展示图片加载不出来

### ISSUE THREAD

**Issue by ChenS-Cs** [vueComponent/ant-design-vue#3582]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
浏览器版本：83.0.4103.116（正式版本）

### Reproduction link
[https://www.antdv.com/components/carousel-cn/](https://www.antdv.com/components/carousel-cn/)

### Steps to reproduce
打开https://www.antdv.com/components/carousel-cn/   下面的自定义分页展示

### What is expected?
图片展示出来

### What is actually happening?
图片显示不出来

**Comment by John60676** [comment]
检查一下自己的网络

![image](https://user-images.githubusercontent.com/21698973/105565403-92245e80-5d61-11eb-9f8b-9c4e53c9a4e2.png)
