### ISSUE TITLE
Failed to bind value using directive v-model on <a-input /> when using vue3 brand-new setup api

### ISSUE THREAD

**Issue by peterczg** [vueComponent/ant-design-vue#3584]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.8

### Environment
vue@next & node@12.18.3

### Reproduction link
[https://2x.antdv.com/components/input-cn/](https://2x.antdv.com/components/input-cn/)

### Steps to reproduce
Using v-model directive on <a-input />, it just didn't work. But worked with Manual binding input event to change the value attributes

### What is expected?
V-model can work normally on data-binding

### What is actually happening?
Just doesn't work

---
If this is proven to be a bug, please fix this little bug ASAP and let me know, thank you .

**Comment by ajuner** [comment]
please use v-model:value

**Comment by peterczg** [comment]
Have tried, still not works, when deleting string "a-",  native input can work, without any choices I opened this issue , guessing it's not my fault .@ajuner
