### ISSUE TITLE
tree组件的异步请求数据方法load-data更新tree-data，与外部接口更新tree-data结合使用后，load-data失效

### ISSUE THREAD

**Issue by Ennya** [vueComponent/ant-design-vue#3590]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
chrome 87.0.4280.88

### Reproduction link
[https://www.antdv.com/components/tree-cn/#无线上链接](https://www.antdv.com/components/tree-cn/#无线上链接)

### Steps to reproduce
tree组件的异步请求数据方法load-data更新tree-data,展开节点更新tree-data的效果是正常的。但是通过外部操作重置tree-data数据后（当前是加了个搜索功能非tree组件的搜索），因为与之前load-data展开节点过的节点数据一样，导致此节点的load-data失效了。
ps:有两个接口，一个是load-data调用，一个搜索接口，都是作用在tree-data上

<a-tree
show-line
:tree-data="dataList"
:replaceFields="replaceFields"
:load-data="onLoadData"
@select="onSelect"
>
</a-tree>
一、 通过使用load-data展开节点请求节点数据，这一步骤正常<br/>
onLoadData(treeNode, test) {
return new Promise(resolve => {
if (treeNode.dataRef.child && treeNode.dataRef.child.length) {
resolve();
return;
}
setTimeout(() => {
let id = treeNode.dataRef.id
this.fetchCategoryData(id).then(res => {
treeNode.dataRef.child = res
this.dataList = [...this.dataList]
resolve();
})
}, 400);
});
},
<br/>
二、非tree组件的搜索，通过接口获取数据，更新到tree-data上，覆盖原来的dataList,由于搜索出来的数据和通过load-data展开节点的“数据是相同的”，并且此节点是有子节点的，在搜索前就已经通过load-data加载展开过它的子节点，搜索后再操作这个节点的展开不能触发load-data。<br/>

this.searchCategoryList ({
name:value
}).then(res => {
this.dataList = res // 这里是覆盖load-data时的tree-data
// this.dataList = [...res]
// this.dataList = Object.assign([],res)
})

### What is expected?
希望能找到方法解决我上面说的问题

### What is actually happening?
load-data展开过的节点，tree-data更新后，这个还是默认展开状态，并且load-data失效

**Comment by alwayszb** [comment]
+1 Same issue.

**Comment by luoyonglan** [comment]
> +1 Same issue.
> 
> 找到原因了, 是因为更新 treeData 后, tree 内部的 loadedKeys 值没有更新, 数据刷新后手动设置 a-tree 的 `loadedKeys` 属性即可.

请问你你是怎么设置的呀？能贴一下代码吗？
