### ISSUE TITLE
There is an error in the table documentation

### ISSUE THREAD

**Issue by daiwa233** [vueComponent/ant-design-vue#3591]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
macos 11.1    chrome87

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-waterfall-r2sis?file=/src/App.vue)

### Steps to reproduce
remove the selections config in the a-table component

### What is expected?
The default selections config should be used and display selections, as described by https://antdv.com/components/table-cn/#API

### What is actually happening?
doesn't show the selections

**Comment by arika163** [comment]
same problem in earlier versions

**Comment by zkwolf** [comment]
看起来应该是文档的问题
