### ISSUE TITLE
Tabs 切换卡顿

### ISSUE THREAD

**Issue by happydoop** [vueComponent/ant-design-vue#3592]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
win10, chrome 87.0.4280.141;Vue 3

### Reproduction link
[https://2x.antdv.com/components/tabs-cn/](https://2x.antdv.com/components/tabs-cn/)

### Steps to reproduce
在某个tab pane中有大量dom时（如：一个tab pane中有5个handsontable实例），此时tabs切换会 **非常** 卡顿！

### What is expected?
即使某个pane中含有大量dom，切换也应该流畅

### What is actually happening?
dom多时，切换卡顿

---
通过性能分析，发现 getTypeValue 会频繁调用 js 中的 getComputedStyle 方法导致不断reflow

![源码截图](https://user-images.githubusercontent.com/74850387/105785093-0dca1980-5fb5-11eb-8374-302a087e1783.png)

仅仅是getTypeValue这一个函数调用就用了 437.6 ms！

**Comment by galleonsZcc** [comment]
我也发现了这个问题，当tab-pane里有数据量超大的表格时，问题会非常明显
