### ISSUE TITLE
drawer组件使用v-if会导致使用v-else的兄弟组件无法渲染。

### ISSUE THREAD

**Issue by tangchi695** [vueComponent/ant-design-vue#3593]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue 2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q4wo7)

### Steps to reproduce
通过v-if切换drawer和其他组件，drawer渲染以后再切换，兄弟组件无法渲染。

### What is expected?
能够切换drawer和兄弟组件

### What is actually happening?
通过v-if切换drawer和其他组件，drawer渲染以后再切换，兄弟组件无法渲染。

**Comment by John60676** [comment]
**请检查自己的代码逻辑哦**

你绑定了 `visible` ，在 `onClose` 触发时该值被设置为 `false`。 当 `drawer` 这个变量第二次被设置为 `true` 时，`visible` 的值还是 `false`

**Comment by tangchi695** [comment]
> **请检查自己的代码逻辑哦**
> 
> 你绑定了 `visible` ，在 `onClose` 触发时该值被设置为 `false`。 当 `drawer` 这个变量第二次被设置为 `true` 时，`visible` 的值还是 `false`

是通过v-if打开drawer以后再关闭，红色的div框不显示了，不是drawer不能再打开了。

**Comment by John60676** [comment]
`drawer` 这个变量为 `true` 的情况下，红色的 `div` 如何显示？？

**请检查自己的代码逻辑！！**

**Comment by tangchi695** [comment]
> `drawer` 这个变量为 `true` 的情况下，红色的 `div` 如何显示？？
> 
> **请检查自己的代码逻辑！！**

close方法里面我设置了 `drawer`变量为false

**Comment by John60676** [comment]
> **请检查自己的代码逻辑哦**
> 
> 你用 `show` 绑定了 **`visible prop`** ，在 `onClose` 触发时该值被设置为 `false`。 当 `drawer` 这个变量第二次被设置为 `true` 时，`show` 的值还是 `false`，这就导致了 `a-drawer` 无法渲染，从而出现你所说的 _“兄弟组件无法渲染。”_

你自己先按这个好好捋一下逻辑吧，认真读一下

**Comment by tangchi695** [comment]
> > **请检查自己的代码逻辑哦**
> > 你用 `show` 绑定了 **`visible prop`** ，在 `onClose` 触发时该值被设置为 `false`。 当 `drawer` 这个变量第二次被设置为 `true` 时，`show` 的值还是 `false`，这就导致了 `a-drawer` 无法渲染，从而出现你所说的 _“兄弟组件无法渲染。”_
> 
> 你自己先按这个好好捋一下逻辑吧，认真读一下

我更新了codesandbox，你再看看我说的是什么意思。。。
你可以在codesandbox里把antd的版本降到一个低版本，比如1.3.0，再看效果有什么不一样。

**Comment by John60676** [comment]
`v-if`  不要直接加在 `a-drawer` 组件上面，会引起 `vue` 的渲染问题

**Comment by itmeryn** [comment]
> `v-if` 不要直接加在 `a-drawer` 组件上面，会引起 `vue` 的渲染问题。有这样的业务需求的，最好用 `div` 包裹一层，把 `v-if` 放在 `div` 上

可以！
