### ISSUE TITLE
select中的属性maxTagPlaceholder是不是不能用？tree-select组件中的maxTagPlaceholder可以

### ISSUE THREAD

**Issue by tansentcn** [vueComponent/ant-design-vue#3594]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
vue-2.6.10

### Reproduction link
[https://www.antdv.com/components/select-cn/](https://www.antdv.com/components/select-cn/)

### Steps to reproduce
:maxTagPlaceholder="maxTagPlaceholder"

maxTagPlaceholder(values) {
console.log(values)
return '1'
}

然后输出：
ƒ (a, b, c, d) { return createElement(vm, a, b, c, d, true); }

### What is expected?
同tree-select一样，正确输出下拉框中选中的值（多选）

### What is actually happening?
值返回错误

**Comment by AdmireWang** [comment]
同样问题，解决方法：
maxTagPlaceholder需要再返回一个函数，如下：
`maxTagPlaceholder() {
            return (omittedValues) => {
                console.log(omittedValues);
                return omittedValues.join(',')
            }
        },`
