### ISSUE TITLE
日期选择组件，中文语言下，月份和周显示的是英文

### ISSUE THREAD

**Issue by mingtianyihou33** [vueComponent/ant-design-vue#3597]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
vue3.0.5

### Reproduction link
[https://2x.antdv.com/components/config-provider-cn/](https://2x.antdv.com/components/config-provider-cn/)

### Steps to reproduce
1.打开链接来到2.x的官方文档，选择全局化配置
2.语言选择中文
3.点击date-picker组件，弹出日期选择弹窗
4.里面的月份和周显示的是英文的

### What is expected?
应该同1.x一样显示中文的

### What is actually happening?
显示了英文

**Comment by ajuner** [comment]
Duplicate of #2527

**Comment by mingtianyihou33** [comment]
> Duplicate of #2527

那是1.x的问题，而且已经没有了，我这是2.x版本的问题

**Comment by ajuner** [comment]
https://codesandbox.io/s/happy-voice-kx6z7?file=/src/App.vue
