### ISSUE TITLE
Select.Option.name 是 'option' 而不是 'ASelectOption'，在局部注册组件的时候没法{ [Select.Option.name]: Select.Option }这样注册了

### ISSUE THREAD

**Issue by shanlisi** [vueComponent/ant-design-vue#3599]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
3.0.5

### Reproduction link
[https://2x.antdv.com/components/select-cn/](https://2x.antdv.com/components/select-cn/)

### Steps to reproduce
import {Select} from 'ant-design-vue';
console.log(Select.Option.name);// Option

### What is expected?
Select.Option.name === 'ASelectOption'

### What is actually happening?
需要这样局部注册组件，ASelectOption: Select.Option

**Comment by ajuner** [comment]
这。。好像就是'ASelectOption'吧。。
![image](https://user-images.githubusercontent.com/53512912/105823607-522ad900-5ff8-11eb-9fae-b92ae72028f1.png)

**Comment by zkwolf** [comment]
Select.Option.displayName
