### ISSUE TITLE
dropdownStyle not working

### ISSUE THREAD

**Issue by mIcHyAmRaNe** [vueComponent/ant-design-vue#360]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.4

### Environment
elementary os, firefox 64.0, vue 2.5.21, vue-template-compiler 2.5.21

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y214ry12wv)

### Steps to reproduce
add `dropdownStyle="{ background-color: 'green' }"` to `a-select`

### What is expected?
that the background of the item list of the select becomes green

### What is actually happening?
nothing, drop style not working 

---
any example will be welcome
i tried to add a `.ant-select-dropdown-menu-item` in `<style></style>` but not working too (nothing changed)

--- 
Fixed

**Comment by tangjinzhou** [comment]
Please provide a demo that works fine. 
fix error

**Comment by mIcHyAmRaNe** [comment]
the only error i got is about `dropdownStyle`
I asked for help to solve the error, and you ask me to fix it 😕

- after a good dose of sleep, I managed to solve it
`:dropdownStyle="{ 'background-color': 'green' }"`
or 
`:dropdownStyle="{ backgroundColor: 'green' }"`

- and other thing: we have to **not add semicolon** at the end of the style value:
`:dropdownStyle="{backgroundColor: 'red;'}"` => _not working_ 
`:dropdownStyle="{backgroundColor: 'red'}"` => _working_

**Comment by huangd-d** [comment]
:dropdownStyle="{ 'width': '300px' }"  style="width:150px";
but the dropdown dom style is 160px; dropdownStyle is not use;
