### ISSUE TITLE
全局引入时怎么全局配置组件size

### ISSUE THREAD

**Issue by BayMax619** [vueComponent/ant-design-vue#3602]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
所有组件一次性引入, 一次性设置size='small',这样就不需要每写一个组件都需要添加size属性

### What does the proposed API look like?
import Vue from 'vue';
import Element from 'element-ui';
Vue.use(Element, { size: 'small', zIndex: 3000 });

**Comment by zkwolf** [comment]
暂时还没实现

**Comment by zkwolf** [comment]
Duplicate #3506
