### ISSUE TITLE
ant design vue是否有类似pro的后台管理系统？

### ISSUE THREAD

**Issue by bi-kai** [vueComponent/ant-design-vue#361]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
ant design vue是否有类似pro的后台管理系统？
如果没有是否有计划推出一款呢？

### What does the proposed API look like?
不涉及

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue-awesome

**Comment by bi-kai** [comment]
已star，再问下ant-design-vue是ant design官方出的么？
这个链接里的Admin是不是都是第三方出的？

**Comment by tangjinzhou** [comment]
都不是官方的
