### ISSUE TITLE
带面包屑页头。在页头（PageHeader）中加入 面包屑导航（breadcrumb）定义routes[].path时默认为hash模式，如何设为historyMode? 

### ISSUE THREAD

**Issue by geeklibin** [vueComponent/ant-design-vue#3613]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可直接使用带面包屑页头，使用historyMode路由

### What does the proposed API look like?
```
import { createWebHistory } from 'vue-router'
<a-page-header  :breadcrumb="{ history: createWebHistory(process.env.BASE_URL),routes:[...] }"/>
```

**Comment by zkwolf** [comment]
https://2x.antdv.com/components/breadcrumb-cn/#components-breadcrumb-demo-vue-router-integration 类似于这个自定义一下itemRender?

**Comment by geeklibin** [comment]
Duplicate of #

> https://2x.antdv.com/components/breadcrumb-cn/#components-breadcrumb-demo-vue-router-integration 类似于这个自定义一下itemRender?

直接使用Breadcrumb是可以用itemRender。但是我想用页头组件(Pageheader)自带的面包屑导航。或者可以为PageHeader提供Breadcrumb的插槽。

**Comment by zkwolf** [comment]
了解

**Comment by sendya** [comment]
PageHeader 中的 breadcrumb 可以直接传递 itemRender 方法；
https://2x.antdv.com/components/breadcrumb/#API


看这里：https://codesandbox.io/s/hardcore-sutherland-xne0b?file=/src/App.vue
