### ISSUE TITLE
2.0的定制主题文档有误

### ISSUE THREAD

**Issue by Jane0220** [vueComponent/ant-design-vue#3618]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
vue-cli3

### Reproduction link
[https://2x.antdv.com/docs/vue/customize-theme-cn/](https://2x.antdv.com/docs/vue/customize-theme-cn/)

### Steps to reproduce
vue cli3的定制化配置，文档要求如下配置：

```
// vue.config.js for less-loader@6.0.0
module.exports = {
css: {
loaderOptions: {
less: {
lessOptions: {
modifyVars: {
'primary-color': '#1DA57A',
'link-color': '#1DA57A',
'border-radius-base': '2px',
},
javascriptEnabled: true,
},
},
},
},
};
```

实际多了lessOptions这一层，应该是

```
// vue.config.js for less-loader@6.0.0
module.exports = {
css: {
loaderOptions: {
less: {
modifyVars: {
'primary-color': '#1DA57A',
'link-color': '#1DA57A',
'border-radius-base': '2px',
},
javascriptEnabled: true,
},
},
},
};
```

### What is expected?
能成功完成主题定制

### What is actually happening?
按文档配置不起效果，发现官方文档有误（从1.X的文档到2.X的文档中，关于vue-cli3部分的配置都有问题）

**Comment by zkwolf** [comment]
其实没问题的，less-loader从6开始要求的
https://github.com/webpack-contrib/less-loader/blob/master/CHANGELOG.md#600-2020-04-24

**Comment by laodaia** [comment]
感谢，终于解决了。找这个错找半天了
