### ISSUE TITLE
Space  组件没有 .d.ts 声明文件，在 ts 中无法按需引入

### ISSUE THREAD

**Issue by lin15263550843** [vueComponent/ant-design-vue#3619]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
"typescript": "3.9.3",   "ant-design-vue": "1.7.2",  "vuex": "3.4.0"

### Reproduction link
[https://www.antdv.com/components/space-cn/](https://www.antdv.com/components/space-cn/)

### Steps to reproduce
import { Space } from 'ant-design-vue'

模块 ""../../../node_modules/ant-design-vue/types"" 没有导出的成员 "Space"。你是想改用 "import Space from "../../../node_modules/ant-design-vue/types"" 吗?ts(2614)

### What is expected?
可以按需导入  Space 组件

### What is actually happening?
实际无法按需导入 Space 组件

**Comment by ajuner** [comment]
https://github.com/vueComponent/ant-design-vue/pull/3340
