### ISSUE TITLE
iview与ant design vue非常类似，iview-admin与react版pro也非常类似，是否有什么关联？

### ISSUE THREAD

**Issue by bi-kai** [vueComponent/ant-design-vue#362]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
iview与ant design vue非常类似，iview-admin与react版pro也非常类似，是否有什么借鉴？
为什么会这么像呢？

### What does the proposed API look like?
no

**Comment by tangjinzhou** [comment]
iview与ant design vue非常类似？
答：iview初期也是antd的vue版本实现

iview-admin与react版pro的关系？
答：不详
