### ISSUE TITLE
开启ESLint时，折叠面板 (collapse-panel) 使用v-for，key与组件bind的属性key冲突

### ISSUE THREAD

**Issue by liyao2598330** [vueComponent/ant-design-vue#3623]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
"vue": "^2.6.10"

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
``` html
  <a-card :loading="loading" :bordered="false" :body-style="{padding: '0'}">
    <a-collapse :accordion="true">
      <a-collapse-panel
        v-for="item in items"
        :key="1"  // 这里
        header="This is panel header 1"
       >
         <p>{{ item.text }}</p>
       </a-collapse-panel>
    </a-collapse>
  </a-card>
```

### What is expected?
除了关闭ESLint检查，有其他的方法能规避掉这个问题吗

### What is actually happening?
我想使用v-for渲染一个折叠面板，ESLint 提示与v-for的key冲突了

![image](https://user-images.githubusercontent.com/22042809/106414993-f5f90680-6488-11eb-8b04-0bdde1e5dcd2.png)

**Comment by zkwolf** [comment]
大概是你理解错了，提示是想让你绑个v-for里声明的值，比如item.text
