### ISSUE TITLE
ant时间选择框手动输入开始,结束时间时间之后，按下enter，如果两个时间都是同一个月，则会把后面的时间延长一个月

### ISSUE THREAD

**Issue by wyq-L** [vueComponent/ant-design-vue#3628]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
win10 chrome88.0 vue2.6

### Reproduction link
[https://1x.antdv.com/components/date-picker-cn/](https://1x.antdv.com/components/date-picker-cn/)

### Steps to reproduce
ant时间选择框手动输入开始,结束时间之后，按下enter，如果两个时间都是同一个月，则会把后面的时间延长一个月,官网链接也可以重现

### What is expected?
期望按下enter时间框为已输入的时间

### What is actually happening?
结束时间会自动延长一个月

**Comment by ajuner** [comment]
1.x 不做改动
原因参考：ant-design/ant-design#5663

2.x 会重构解决
