### ISSUE TITLE
Request a version whose UI is synchronized with version 4.x of Ant Design's react version.

### ISSUE THREAD

**Issue by mobilesite** [vueComponent/ant-design-vue#3632]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
It seems that the UI of Ant Design Vue 2.x is not synchronized with version 4.x of Ant Design. Is there a branch or any plan whose UI is synchronized with version 4.x of Ant Design? If not, how should I update to that myself?

### What does the proposed API look like?
null

**Comment by zkwolf** [comment]
We plan to sync all of the ant design 4.x style change in 3.0 and we dev it in v3 branch now.
