### ISSUE TITLE
Official website loading forever

### ISSUE THREAD

**Issue by Pacheco95** [vueComponent/ant-design-vue#3635]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
Google Chrome Version 87.0.4280.141 (Official Build) (64-bit)

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
Open https://www.antdv.com/

### What is expected?
The site to be loaded

### What is actually happening?
The site is loading forever

---
That is not the first way I see this and in the normal performance the site takes about 5 seconds to load a page

**Comment by zkwolf** [comment]
Can you give the graph of the network in devtools to help us analyze?

**Comment by Pacheco95** [comment]
Sure! 
![image](https://user-images.githubusercontent.com/12385467/106741409-65dace80-65fa-11eb-8995-f792834f03d5.png)

**Comment by Pacheco95** [comment]
Have the official docs moved to https://aaronwn.github.io/vue-antd/docs/vue/introduce/?

**Comment by tangjinzhou** [comment]
> Have the official docs moved to https://aaronwn.github.io/vue-antd/docs/vue/introduce/?

no.
 this is not lastest doc.

you can try reload antdv,com.

**Comment by Pacheco95** [comment]
Still not loading

**Comment by Pacheco95** [comment]
https://user-images.githubusercontent.com/12385467/106778079-5a9c9880-6624-11eb-8d68-5cbe5f25dd58.mp4

**Comment by Pacheco95** [comment]
Problem persists until today. Are you using server side rendering? It seems so because there is no pending requests neither failed request or console errors

**Comment by tangjinzhou** [comment]
can you try  2x.antdv.com?
If ok, I will change cdn point

**Comment by Pacheco95** [comment]
Official docs it's working now but http://2x.antdv.com/ don't
