### ISSUE TITLE
之前的声明文件被移到哪里了

### ISSUE THREAD

**Issue by onlymisaky** [vueComponent/ant-design-vue#3638]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/next/components/form](https://github.com/vueComponent/ant-design-vue/tree/next/components/form)

### Steps to reproduce
```ts
import { Form } from 'ant-design-vue/types/form/form.d';
const formRef = ref() as Ref<Form>;
formRef.value.validate();
```

### What is expected?
现在声明文件全没了啊

### What is actually happening?
没有声明文件了

**Comment by zkwolf** [comment]
额，在组件目录下

**Comment by onlymisaky** [comment]
> 额，在组件目录下

导出来没法直接使用，不是interface或type

**Comment by yingzhiji** [comment]
FormProps、FormItemProps 都是通过这种方式声明的：
```js
export declare const FormProps: {}
```
然而会被 ts 识别为一个 value 而不是 type，不能用在泛型里或者继承
