### ISSUE TITLE
Timeline按需加载依赖报错

### ISSUE THREAD

**Issue by simonwangtx** [vueComponent/ant-design-vue#364]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.4

### Environment
macos、chrome、vue-cli 3

### Reproduction link
[https://jsfiddle.net/7pdc8tu4/1/](https://jsfiddle.net/7pdc8tu4/1/)

### Steps to reproduce
使用babel按需加载，在某个vue组件中实现antd-vue的demo代码，如果componets中只写[Timeline.name]: Timeline，会提示找不到组件TimelineItem,但是如果尝试import{TimelineItem }from 'ant-design-vue'又会提示'ant-design-vue'中没有TimelineItem

### What is expected?
实现按需加载中的timeline demo

### What is actually happening?
无法实现按需加载中的timeline demo

**Comment by tangjinzhou** [comment]
建议使用Vue.use(Timeline)全局注册，
全局注册和按需加载不冲突，
如果非要局部注册，可以注册 `[Timeline.Item.name]: Timeline.Item`
