### ISSUE TITLE
无法通过触摸操作上下滑动select下拉框

### ISSUE THREAD

**Issue by BenjaminCharlies** [vueComponent/ant-design-vue#3649]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
chrome 88, vue 3.0.4

### Reproduction link
[https://2x.antdv.com/components/select-cn/](https://2x.antdv.com/components/select-cn/)

### Steps to reproduce
在触摸设备以及chrome调试中无法通过触摸操作上下滑动select下拉框，在antdesign1.x版本没有此bug

### What is expected?
触摸可以上下滚动select下拉框

### What is actually happening?
在触摸设备以及chrome调试中无法通过触摸操作上下滑动select下拉框，在antdesign1.x版本没有此bug

**Comment by zkwolf** [comment]
下个版本修复
