### ISSUE TITLE
antd-vue使用tooltip导致a-input卡顿

### ISSUE THREAD

**Issue by Yuanmengyao** [vueComponent/ant-design-vue#3651]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
windows10、Google V88.0.4324.104、vue:2.6.11

### Reproduction link
[https://github.com/Yuanmengyao/showDown.git](https://github.com/Yuanmengyao/showDown.git)

### Steps to reproduce
给首页shutDown.vue文件的v-for内部div添加a-tootip。For example:
```
<div
class="bottom_channel"
v-for="item in otherList"
:key="item.id"
>
<a-tooltip
:title="item.alias"
:destroyTooltipOnHide="true"
>
<div
@click="selectOther(item)"
:class="[item.clickStatus? 'selectChannel':'defaultChannel']"
:title="item.alias"
>
{{item.alias}}
</div>
</a-tooltip>
</div>
```

### What is expected?
首页a-input可以流畅的输入

### What is actually happening?
实际情况是会有2秒的卡顿

**Comment by tangjinzhou** [comment]
给出有效的 Reproduction link
