### ISSUE TITLE
滑动输入条始终显示ToolTip的复位问题

### ISSUE THREAD

**Issue by 1369521908** [vueComponent/ant-design-vue#3656]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
Chrome 88.0.4324.146

### Reproduction link
[https://www.antdv.com/components/slider-cn/](https://www.antdv.com/components/slider-cn/)

### Steps to reproduce
:tooltip-visible="true" 时 修改父元素窗口大小(如宽度) 后, ToolTip显示位置异常

### What is expected?
:tooltip-visible="true" 时 修改父元素窗口大小(如宽度) 后, ToolTip显示位置正常常

### What is actually happening?
Tooltip位置显示异常
![image](https://user-images.githubusercontent.com/32727597/107002432-337dcc80-67c6-11eb-8455-b2dbb62ed430.png)

**Comment by zkwolf** [comment]
给个最小化复现？

**Comment by sendya** [comment]
我这边看官方文档是会自动调整位置的，提供一个复现来看看把

![GIF](https://user-images.githubusercontent.com/5404542/107259599-26880400-6a78-11eb-9d7c-2f4fde8e587a.gif)

**Comment by 1369521908** [comment]
我是用滑动输入条和上传图片这两个做成同一个组件 然后在另一个页面引用的

**Comment by 1369521908** [comment]
代码在公司 回家了 复现暂时参考这个
https://codesandbox.io/s/vue-antd-template-forked-tb4wq?fontsize=14&hidenavigation=1&theme=dark
