### ISSUE TITLE
Menu.Item: Property 'onClick' does not exist on type...

### ISSUE THREAD

**Issue by zhoubangfu** [vueComponent/ant-design-vue#3661]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
os: Mac Big Sur 11.1；vscode: 1.53.0

### Reproduction link
[https://github.com/zhoubangfu/vue3-admin/blob/with-antd-vue/src/layouts/NavBar/index.tsx#L176](https://github.com/zhoubangfu/vue3-admin/blob/with-antd-vue/src/layouts/NavBar/index.tsx#L176)

### Steps to reproduce
在tsx中使用Menu.Item组件，并尝试添加onClick。

### What is expected?
onClick在Menu.Item能正常提示、使用

### What is actually happening?
onClick在Menu.Item中能正常使用，但是抛出了不存在类型的错误。

**Comment by zkwolf** [comment]
下个版本修复
