### ISSUE TITLE
为什么定制主题在less-loader6.0.0版本生效，在less-loader7.2.1版本不生效

### ISSUE THREAD

**Issue by yhzy888** [vueComponent/ant-design-vue#3665]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
chrome 87.0.4280.141   vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
按照https://2x.antdv.com/docs/vue/customize-theme-cn 进行主题颜色配置，less-loader的版本7.2.1的时候不生效，改成6.0.0版本则生效。

### What is expected?
希望less-loader的任何版本下修改主题颜色配置都能生效

### What is actually happening?
按照https://2x.antdv.com/docs/vue/customize-theme-cn 进行主题颜色配置，less-loader的版本7.2.1的时候不生效，改成6.0.0版本则生效。

**Comment by zkwolf** [comment]
less-loader哪来的7.1.2

**Comment by yhzy888** [comment]
> less-loader哪来的7.1.2
是7.2.1

**Comment by zhangzhi93** [comment]
也遇到这个问题了，直接报错，报错信息是
`
Syntax Error:

    position: absolute;
    top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;
  ^
Operation on an invalid type
`

"less": "^4.1.1",
"less-loader": "^7.2.1",

**Comment by zhangzhi93** [comment]
也遇到这个问题了，直接报错，报错信息是
`
Syntax Error:

    position: absolute;
    top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;
  ^
Operation on an invalid type
`

"less": "^4.1.1",
"less-loader": "^7.2.1",

**Comment by tangjinzhou** [comment]
less 4 语法有改动 
`top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;`
这个是不合法的，改成
`top: 8px + (@font-size-base * @line-height-base / 2) - (@font-size-base / 2);`
要么降级 less 到 3.x版本

**Comment by zhangzhi93** [comment]
> less 4 语法有改动
> `top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;`
> 这个是不合法的，改成
> `top: 8px + (@font-size-base * @line-height-base / 2) - (@font-size-base / 2);`
> 要么降级 less 到 3.x版本

那1.x不再维护了吗？1.x不再支持less4？

**Comment by tangjinzhou** [comment]
less-loader 7 内置了依赖 less 4

**Comment by tangjinzhou** [comment]
> > less 4 语法有改动
> > `top: 8px + @font-size-base * @line-height-base / 2 - @font-size-base / 2;`
> > 这个是不合法的，改成
> > `top: 8px + (@font-size-base * @line-height-base / 2) - (@font-size-base / 2);`
> > 要么降级 less 到 3.x版本
> 
> 那1.x不再维护了吗？1.x不再支持less4？

维护，但不对less 的改动在做兼容，使用less3 即可

**Comment by ayiaq1** [comment]
在 less 的配置项中指定 math 为 "always" 即可：

  addLessLoader({
    lessOptions: {
      modifyVars: {
        '@primary-color': '#1DA57A',
        '@link-color': '#1DA57A',
      },
      javascriptEnabled: true,
      math: 'always'   // 此处指定为兼容 less-loader 3.x 的默认选项
    },
  }),
具体原因是 less-loader 从 3.x 升级到 4.x 后对于数学计算的默认配置发生了变化（详情参考这里)

**Comment by guozhengzhongGit** [comment]
> 在 less 的配置项中指定 math 为 "always" ：
> 
> ```
>    lessOptions: {
>       modifyVars: {
>         '@primary-color': 'xx',
>       },
>       javascriptEnabled: true,
>      // 兼容 less-loader 3.x 
>       math: 'always' 
>     }
> ```
> 
> less-loader 从 3.x 升级到 4.x 后语法有变化

cool

**Comment by kangaroo-525** [comment]
为何我这样不行呢 
    css: {
      loaderOptions: {
        less: {
          lessOptions: {
            modifyVars: {
              '@primary-color': 'xx'
            },
            javascriptEnabled: true,
            // 兼容 less-loader 3.x
            math: 'always'
          }
        }
      }
    }

**Comment by kangaroo-525** [comment]
为何我这样不起作用呢


    css: {
      loaderOptions: {
        less: {
          lessOptions: {
            modifyVars: {
              '@primary-color': 'xx'
            },
            javascriptEnabled: true,
            // 兼容 less-loader 3.x
            math: 'always'
          }
        }
      }
    },
