### ISSUE TITLE
期望带showQuickJumper分页， 页码变化，将值同步至输入框（或者清空输入框的值）

### ISSUE THREAD

**Issue by whateveryoudo** [vueComponent/ant-design-vue#3668]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
自定义添加跳转按钮，输入框与页码未双向联动

### What does the proposed API look like?
内置处理下，无需提供新的api

**Comment by tangjinzhou** [comment]
？ 使用 v-model 或 change 回调
