### ISSUE TITLE
在form中 使用v-if渲染的form-item 在不渲染的时候也进行了必填验证??

### ISSUE THREAD

**Issue by feng9217** [vueComponent/ant-design-vue#367]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.1

### Environment
vue 2.9.6  Chrome/71.0.3578.98

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7o52l8x86)

### Steps to reproduce
在form中 使用v-if对不同的form-item进行渲染 选择其中一个值渲染出表单后 再选另一个值渲染对应的表单 结果前值的表单的必填项也跟着被验证了
例如重现例子中 我选了1 再选2 结果1中的必填表单也被验证了

### What is expected?
根据当前的 v-if 验证 对应的必填项(在选择过后)

### What is actually happening?
全部都给验证了

---
重现链接里的 ant-design-vue 加载不出来?

**Comment by tangjinzhou** [comment]
没发现问题，确定是1.2.4版本？
and 建议先把控制台一堆的警告先解决了
![image](https://user-images.githubusercontent.com/6937879/50638262-10a1de00-0f98-11e9-8556-4683683e7305.png)

**Comment by feng9217** [comment]
https://codesandbox.io/s/q7o52l8x86
更新了 看了是用的1.1.1的版本 ..
之前开发也没见控制台有这些 一直就这样用了 ..
已经可以复现了 先选了一个派车方式 再选另一个 填完再提交 ~

**Comment by feng9217** [comment]
![image](https://user-images.githubusercontent.com/6224010/50671818-1e467a80-100f-11e9-859d-4c5906d17604.png)
已进行升级, 点击提交后还是出现 .....
在线地址也已更新, 可复现
![image](https://user-images.githubusercontent.com/6224010/50671798-05d66000-100f-11e9-9112-2a63cc944ca1.png)

**Comment by tangjinzhou** [comment]
重新安装依赖也可解决问题, 升级底层依赖[vue-ref](https://github.com/vueComponent/vue-ref)

**Comment by cyb2952873** [comment]
https://codesandbox.io/s/q7o52l8x86 这个连接失效了。。 能否贴个解决方法出来
