### ISSUE TITLE
使用cdn方式导入vue后使用ant-design-vue存在报错

### ISSUE THREAD

**Issue by FanhuaCloud** [vueComponent/ant-design-vue#3670]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
Vue 3.0.5，vite@2.0.0-beta.65

### Reproduction link
[https://github.com/FanhuaCloud/antd_vuecdn](https://github.com/FanhuaCloud/antd_vuecdn)

### Steps to reproduce
1.使用vite创建项目

2.安装ant-design-vue

3.main.js中引入

4.修改vite.config.js，添加alias
```
alias: {
vue: "https://cdn.jsdelivr.net/npm/vue@3.0.5/dist/vue.esm-browser.js",
// "ant-design-vue": "https://cdn.jsdelivr.net/npm/ant-design-vue@2.0.0/lib/index.min.js",
// moment: "https://cdn.jsdelivr.net/npm/moment@2.29.1/dist/moment.js",
},
```
5.yarn run dev

### What is expected?
正常运行，不产生报错

### What is actually happening?
```
下午12:23:14 [vite] config or .env file changed, restarting server...
Pre-bundling dependencies:
ant-design-vue
(this will be run only when your dependencies or config have changed)
> node_modules/ant-design-vue/es/space/index.js: error: Cannot read file "https:/cdn.jsdelivr.net/npm/vue@3.0.5/dist/vue.esm-browser.js": The filename, directory name, or volume label syntax is incorrect.
1 │ import { createVNode as _createVNode, isVNode as _isVNode } from "vue";
╵                                                                  ~~~~~
```

**Comment by sendya** [comment]
cdn 引入试下这个

https://cdn.jsdelivr.net/npm/ant-design-vue@2.0.0/dist/antd.min.js

**Comment by FanhuaCloud** [comment]
> cdn 引入试下这个
> 
> https://cdn.jsdelivr.net/npm/ant-design-vue@2.0.0/dist/antd.min.js

这个文件没法用esm导入，而且问题是不加ant-design-vue没问题，加上就会有这样问题

**Comment by sendya** [comment]
开发时建议直接从 npm 库安装 ant-design-vue，打包时过滤使用 cdn 即可。
