### ISSUE TITLE
下拉菜单点击选项后可控制隐藏

### ISSUE THREAD

**Issue by vibeme** [vueComponent/ant-design-vue#3672]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如果下拉菜单内嵌入一个tabs组件，当用户切换tab的时候，下拉菜单会自动隐藏，无法持久化显示

### What does the proposed API look like?
直接props传入组件，控制下拉菜单点击后是否隐藏

如
```html
<a-dropdown :hide-on-click="true">

</a-dropdown>
```

**Comment by sendya** [comment]
Props

visible(v-model) | 菜单是否显示 | boolean | -
-- | -- | -- | --

v-model 改成 受控即可
