### ISSUE TITLE
Button icons don't work

### ISSUE THREAD

**Issue by ssnowicki** [vueComponent/ant-design-vue#3674]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
"@ant-design/icons-vue": "^6.0.1",    "ant-design-vue": "2.0.0-rc.1",     "core-js": "^3.6.5",     "moment": "2.29.1",     "vue": "3.0.2"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-yalow-l6wig?file=/src/App.vue)

### Steps to reproduce
Open the link to reproduction. Look at the button on the App.vue screen.

### What is expected?
Icon appears in button.

### What is actually happening?
No icon, and the following console error:
Warning: [@ant-design/icons-vue] Should have `component` prop/slot or `children`.

**Comment by Amour1688** [comment]
```diff
- import PlusOutlined from "@ant-design/icons-vue";
+ import { PlusOutlined } from "@ant-design/icons-vue";
```
