### ISSUE TITLE
iocn 引入报错

### ISSUE THREAD

**Issue by aixinaxc** [vueComponent/ant-design-vue#3675]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
vue 3.0

### Steps to reproduce
npm install --save @ant-design/icons-vue

### What is expected?
正常加载

### What is actually happening?
ERROR  Failed to compile with 46 errors下午3:49:22

These relative modules were not found:

* ./es/icons/ArrowLeftOutlined in ./node_modules/@ant-design/icons-vue/ArrowLeftOutlined.js
* ./es/icons/BarsOutlined in ./node_modules/@ant-design/icons-vue/BarsOutlined.js
* ./es/icons/CalendarOutlined in ./node_modules/@ant-design/icons-vue/CalendarOutlined.js
* ./es/icons/CaretDownFilled in ./node_modules/@ant-design/icons-vue/CaretDownFilled.js
* ./es/icons/CaretDownOutlined in ./node_modules/@ant-design/icons-vue/CaretDownOutlined.js
* ./es/icons/CaretUpFilled in ./node_modules/@ant-design/icons-vue/CaretUpFilled.js
* ./es/icons/CheckCircleFilled in ./node_modules/@ant-design/icons-vue/CheckCircleFilled.js
* ./es/icons/CheckCircleOutlined in ./node_modules/@ant-design/icons-vue/CheckCircleOutlined.js
* ./es/icons/CheckOutlined in ./node_modules/@ant-design/icons-vue/CheckOutlined.js
* ./es/icons/ClockCircleOutlined in ./node_modules/@ant-design/icons-vue/ClockCircleOutlined.js
* ./es/icons/CloseCircleFilled in ./node_modules/@ant-design/icons-vue/CloseCircleFilled.js
* ./es/icons/CloseCircleOutlined in ./node_modules/@ant-design/icons-vue/CloseCircleOutlined.js
* ./es/icons/CloseOutlined in ./node_modules/@ant-design/icons-vue/CloseOutlined.js
* ./es/icons/DeleteOutlined in ./node_modules/@ant-design/icons-vue/DeleteOutlined.js
* ./es/icons/DoubleLeftOutlined in ./node_modules/@ant-design/icons-vue/DoubleLeftOutlined.js
* ./es/icons/DoubleRightOutlined in ./node_modules/@ant-design/icons-vue/DoubleRightOutlined.js
* ./es/icons/DownOutlined in ./node_modules/@ant-design/icons-vue/DownOutlined.js
* ./es/icons/DownloadOutlined in ./node_modules/@ant-design/icons-vue/DownloadOutlined.js
* ./es/icons/EllipsisOutlined in ./node_modules/@ant-design/icons-vue/EllipsisOutlined.js
* ./es/icons/ExclamationCircleFilled in ./node_modules/@ant-design/icons-vue/ExclamationCircleFilled.js
* ./es/icons/ExclamationCircleOutlined in ./node_modules/@ant-design/icons-vue/ExclamationCircleOutlined.js
* ./es/icons/EyeInvisibleOutlined in ./node_modules/@ant-design/icons-vue/EyeInvisibleOutlined.js
* ./es/icons/EyeOutlined in ./node_modules/@ant-design/icons-vue/EyeOutlined.js
* ./es/icons/FileOutlined in ./node_modules/@ant-design/icons-vue/FileOutlined.js
* ./es/icons/FilterFilled in ./node_modules/@ant-design/icons-vue/FilterFilled.js
* ./es/icons/FolderOpenOutlined in ./node_modules/@ant-design/icons-vue/FolderOpenOutlined.js
* ./es/icons/FolderOutlined in ./node_modules/@ant-design/icons-vue/FolderOutlined.js
* ./es/icons/InfoCircleFilled in ./node_modules/@ant-design/icons-vue/InfoCircleFilled.js
* ./es/icons/InfoCircleOutlined in ./node_modules/@ant-design/icons-vue/InfoCircleOutlined.js
* ./es/icons/LeftOutlined in ./node_modules/@ant-design/icons-vue/LeftOutlined.js
* ./es/icons/LoadingOutlined in ./node_modules/@ant-design/icons-vue/LoadingOutlined.js
* ./es/icons/MinusSquareOutlined in ./node_modules/@ant-design/icons-vue/MinusSquareOutlined.js
* ./es/icons/PaperClipOutlined in ./node_modules/@ant-design/icons-vue/PaperClipOutlined.js
* ./es/icons/PictureTwoTone in ./node_modules/@ant-design/icons-vue/PictureTwoTone.js
* ./es/icons/PlusOutlined in ./node_modules/@ant-design/icons-vue/PlusOutlined.js
* ./es/icons/PlusSquareOutlined in ./node_modules/@ant-design/icons-vue/PlusSquareOutlined.js
* ./es/icons/RedoOutlined in ./node_modules/@ant-design/icons-vue/RedoOutlined.js
* ./es/icons/RightOutlined in ./node_modules/@ant-design/icons-vue/RightOutlined.js
* ./es/icons/RotateLeftOutlined in ./node_modules/@ant-design/icons-vue/RotateLeftOutlined.js
* ./es/icons/RotateRightOutlined in ./node_modules/@ant-design/icons-vue/RotateRightOutlined.js
* ./es/icons/SearchOutlined in ./node_modules/@ant-design/icons-vue/SearchOutlined.js
* ./es/icons/StarFilled in ./node_modules/@ant-design/icons-vue/StarFilled.js
* ./es/icons/UpOutlined in ./node_modules/@ant-design/icons-vue/UpOutlined.js
* ./es/icons/WarningFilled in ./node_modules/@ant-design/icons-vue/WarningFilled.js
* ./es/icons/ZoomInOutlined in ./node_modules/@ant-design/icons-vue/ZoomInOutlined.js
* ./es/icons/ZoomOutOutlined in ./node_modules/@ant-design/icons-vue/ZoomOutOutlined.js

**Comment by littleCareless** [comment]
请问 解决了吗?
