### ISSUE TITLE
官网的Upload组件 -> 手动上传有bug

### ISSUE THREAD

**Issue by ParkerOu** [vueComponent/ant-design-vue#3676]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
Google Chrome 88.0.4324.150

### Reproduction link
[https://2x.antdv.com/components/upload-cn](https://2x.antdv.com/components/upload-cn)

### Steps to reproduce
1. 至手动上传 点击Select File上传文件
2. 按Start Upload开始上传

### What is expected?
开发者工具中的Request Header

Form Data
```
files[]: (binary)
```

### What is actually happening?
开发者工具中的Request Header

Form Data
```
files[]: undefined
```

---
[1.7.2是正常的](https://www.antdv.com/components/upload-cn/)

**Comment by tangjinzhou** [comment]
fixed
