### ISSUE TITLE
在vite模板工程中引用List组件报错

### ISSUE THREAD

**Issue by skyearthsong** [vueComponent/ant-design-vue#3677]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-rc.9

### Environment
chrome 87

### Reproduction link
[https://github.com/skyearthsong/ant-design-vue-list-issue](https://github.com/skyearthsong/ant-design-vue-list-issue)

### Steps to reproduce
1、npm run dev
2、在浏览器打开localhost:3000
3、在控制台出现Uncaught TypeError: Cannot read property 'content' of undefined

### What is expected?
期望List组件可以正常根据listdata渲染出多个card

### What is actually happening?
结果报错无法识别item

**Comment by tangjinzhou** [comment]
参考 https://2x.antdv.com/components/list-cn#components-list-demo-basic  示例
