### ISSUE TITLE
按需引入 Menu 在使用 css 会提示 `Failed to resolve loader: less-loader`

### ISSUE THREAD

**Issue by crazyhl** [vueComponent/ant-design-vue#3678]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
maxos 、 chrome88 、 vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-architecture-p737f)

### Steps to reproduce
`import 'ant-design-vue/lib/menu/style/css';`

### What is expected?
使用 `css` 的时候不会使用 `less`

### What is actually happening?
`Failed to resolve loader: less-loader
You may need to install it.`
![image](https://user-images.githubusercontent.com/5474833/108173850-a168b300-7139-11eb-977d-cffec8fa4534.png)

---
我在看代码的时候发现是文件 `ant-design-vue/lib/menu/style/css` 中 第七行

`require("../../tooltip/style");`

此行引起的问题，改写为

`require("../../tooltip/style/index.css");`

就不会报错了
![image](https://user-images.githubusercontent.com/5474833/108173817-944bc400-7139-11eb-9f9a-af702e92744c.png)

**Comment by sendya** [comment]
请安装 less, less-loader

**Comment by sendya** [comment]
如需按需引入，直接 import { Menu } from 'ant-design-vue' 即可

**Comment by crazyhl** [comment]
> 请安装 less, less-loader

如果决定使用了 css 的话，为什么还要安装 less 呢?
如果选择 less 直接就用 less 就好了

**Comment by zkwolf** [comment]
下个版本会修复

**Comment by crazyhl** [comment]
> 下个版本会修复

thx

**Comment by ethan666** [comment]
我用vue-cli创建项目。最终环境
`  "dependencies": {
    "ant-design-vue": "^2.2.8",
    "core-js": "^3.6.5",
    "register-service-worker": "^1.7.1",
    "vue": "^3.0.0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-pwa": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.3",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "less": "^3.0.0",
    "less-loader": "^5.0.0",
    "prettier": "^2.2.1"
  }`
不知道应该装什么版本的less-loader。
装最新的提示this.getOptions is not a function
装旧的提示
`// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in D:\workspace\learning\home-website\node_modules\ant-design-vue\es\style\color\bezierEasing.less (line 110, column 0)`
@sendya

**Comment by ethan666** [comment]
我是不是应该最新的vue-cli 
npm install -g @vue/cli@next
