### ISSUE TITLE
初次装载Tabs组件报错

### ISSUE THREAD

**Issue by Darwin666** [vueComponent/ant-design-vue#368]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.4

### Environment
vue3.2.1

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/tabs-cn/#components-tabs-demo-basic-usage](https://vuecomponent.github.io/ant-design-vue/components/tabs-cn/#components-tabs-demo-basic-usage)

### Steps to reproduce
使用vue-cli3搭建的工程，在.vue中按需引入Tabs组件，并使用Tabs文档中的基础用法

### What is expected?
console无报错，页面正常展示

### What is actually happening?
页面正常展示，console报一系列错：
[Vue warn]: Failed to resolve directive: ant-ref (found in <TabBarTabsNode>)
[Vue warn]: Failed to resolve directive: ant-ref (found in <InkTabBarNode>)
[Vue warn]: Failed to resolve directive: ant-ref (found in <ScrollableTabBarNode>)
[Vue warn]: Failed to resolve directive: ant-ref (found in <TabBarRootNode>)
[Vue warn]: Failed to resolve directive: ant-ref (found in <Sentinel>)
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'style' of undefined" found in
---> <InkTabBarNode>
<ScrollableTabBarNode>
<TabBarRootNode>
<Anonymous>
<ScrollableInkTabBar>
<Tabs>
<ATabs>
<About> at src/views/About.vue
<Anonymous>
<ALayoutContent>
<Anonymous>
<ALayout>
<Anonymous>
<ALayout>
<Anonymous>
<ALayout>
<App> at src/App.vue
<Root>
TypeError: Cannot read property 'style' of undefined
at componentDidUpdate (InkTabBarNode.js?027b:38)
at VueComponent.eval (InkTabBarNode.js?027b:123)
at Array.eval (vue.runtime.esm.js?2b0e:1916)
at flushCallbacks (vue.runtime.esm.js?2b0e:1835)

**Comment by tangjinzhou** [comment]
提供下在线复现demo ？

建议在入口处Vue.use(Tabs)注册组件

**Comment by ningstudy** [comment]
我也是这样，前面都可以，今天就不行了 1.3.8版本

**Comment by kavil** [comment]
+1
按需加载时会出现
