### ISSUE TITLE
table tree 组件增强建议

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#3680]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
建议table,tree这块可以像miniui或者easyui这样做企业级的框架学习下，他们对表格和树里面的操作的函数什么挺丰富的，可以借鉴完善下，多丰富下操作函数

**Comment by sendya** [comment]
根据 Vue 的使用建议，更推荐对**数据的操作**来达到 表格/树 的变化，尽量减少通过调用函数来达到目的

**Comment by wsxe9988** [comment]
我的意思可能没表述清楚，我想说的是能否对比下miniui，多增加API及属性配置:比如分页条数的设置，columnschanged，rowclick，cellbeginedit，cellcommitedit，cellendedit，cellvalidation等这些扩展的API 。之前是使用miniui做前端框架的，现在打算升级成antdesignvue，表格这块功能确实有些欠缺，移植的过程中存在些困难

**Comment by wsxe9988** [comment]
今年的roadmap有嘛

**Comment by tangjinzhou** [comment]
table 会进行重构，你说的这些有些会有，有些暂时不能确定  还需讨论

**Comment by vxhly** [comment]
如果能加上大数据，渲染优化就更好了
