### ISSUE TITLE
ant-design-vue 是否会支持在线动态变化主题？

### ISSUE THREAD

**Issue by Aimer-Fan** [vueComponent/ant-design-vue#3682]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
看到 ant-design-vue 的官网支持【默认主题】和【暗黑主题】的切换，但是文档是并没有找到相关的描述。想问下后续是否会开放相关的 API，切换主题色？

### What does the proposed API look like?
能够像 ant-design-vue 和 github 一样支持在线切换主题。

**Comment by tangjinzhou** [comment]
https://2x.antdv.com/docs/vue/customize-theme-cn#%E4%BD%BF%E7%94%A8%E6%9A%97%E9%BB%91%E4%B8%BB%E9%A2%98
