### ISSUE TITLE
InputNumber数字输入框-格式化展示-输入重复问题，值错误

### ISSUE THREAD

**Issue by wangkris03** [vueComponent/ant-design-vue#3683]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
/

### Reproduction link
[https://www.antdv.com/components/input-number-cn/](https://www.antdv.com/components/input-number-cn/)

### Steps to reproduce
/

### What is expected?
/

### What is actually happening?
/

---
/

**Comment by a15008282884** [comment]
你好 我也遇到同样的问题 在版本1.7.4中  在中文输入法下 当连续输入第四位数字后 （出现千分位标点时） 会出现连续输入重复的问题

**Comment by ajuner** [comment]
> 你好 我也遇到同样的问题 在版本1.7.4中 在中文输入法下 (formatter用的官网示例) 当连续输入第四位数字后 （出现千分位标点时） 会出现连续输入重复的问题
https://github.com/vueComponent/ant-design-vue/pull/3825
1.x下个版本修复
