### ISSUE TITLE
index-with-locales.js文件错误 导致构建文件语言包不完全

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue#3684]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
vue3.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/next/index-with-locales.js](https://github.com/vueComponent/ant-design-vue/blob/next/index-with-locales.js)

应该将js 改为ts

**Comment by tangjinzhou** [comment]
没明白  什么错

**Comment by ShinyGwyn** [comment]
> 没明白 什么错

目前的2.0的浏览器引入 antd.locales是没内容的. 因为这个
```
const req = require.context('./components', true, /^\.\/locale-provider\/(?!__tests__).+_.+\.js$/);
```
locale-provider 这个文件夹下面已经没js文件了

个人将其改成 
```
const req = require.context('./components', true, /^\.\/locale-provider\/(?!__tests__).+_.+\.ts$/);
```
后重新构建就没没问题了

**Comment by rashagu** [comment]
`const match = mod.match(/\/([^/]+).js$/);`
这里的js 没有改成 ts
