### ISSUE TITLE
antd2.0.0 vue3.0.5 vite2.0.0 搭建项目成功 但 IE 显示空白

### ISSUE THREAD

**Issue by JinPengGeng** [vueComponent/ant-design-vue#3685]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
win10 vscode node12.13 antd2.0.0 vue3.0.5 vite2.0.0

### Reproduction link
[https://2x.antdv.com/docs/vue/introduce-cn](https://2x.antdv.com/docs/vue/introduce-cn)

### What is expected?
1、使用vite的场景下，**在开发阶段和生产阶段**，怎么做才能**兼容IE**，需要有个例子，或者是template PJ之类的

2、如果vite 不能做到**在开发阶段和生产阶段都兼容IE**, 是否还是使用webpack vue.config进行配置才能生效，需要给个明确的指导，或例子

3、el-plus 现在支持 命令行创建项目，ant2这边也有吗？文档地址在那里？

### What is actually happening?
使用vite 创建antV2.0后，在开发阶段不支持IE、在生产阶段也不支持IE，相关的配置文档没有，是否只有使用webpack方式才能兼容IE，Vite怎么做都不会支持，没有相关文档，查找各种插件（vite-babel-plugin、@vitejs/plugin-legacy等等）最后都失败了，能否给个意见或者实现方式

**Comment by sendya** [comment]
vue3 还不支持 IE，antdv2.0 依赖于 vue3

**Comment by sendya** [comment]
你可以去 vue 仓库跟踪支持 IE 的相关问题

**Comment by JinPengGeng** [comment]
> vue3 还不支持 IE，antdv2.0 依赖于 vue3。
> 需要支持 IE 可以使用 1.x + vue2

那为何 antdv2.0的文档会说明兼容性支持IE11

**Comment by sendya** [comment]
> 那为何 antdv2.0的文档会说明兼容性支持IE11

现在的问题不是 vue3 不兼容 IE11 吗，你可以去 Vue3 的仓库等 IE 的兼容通知~
