### ISSUE TITLE
下载最新版后，直接运行npm install后，执行npm run serve报错

### ISSUE THREAD

**Issue by skyworth365** [vueComponent/ant-design-vue#3686]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
win 10专业版

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
下载最新版后，直接运行npm install后，执行npm run serve报错

### What is expected?
可以正常运行，在浏览器看到效果

### What is actually happening?
1、ERROR in ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--3!./node_modules/vue-loader/dist??ref--13-0!./examples/App.vue?vue&type=script&lang=js)
Module not found: Error: Can't resolve '../v2-doc/src/docs/affix/demo/basic.vue' in 'D:\Company\Self\ant-design-vue-next\examples'
@ ./examples/App.vue?vue&type=script&lang=js (./node_modules/babel-loader/lib??ref--3!./node_modules/vue-loader/dist??ref--13-0!./examples/App.vue?vue&type=script&lang=js) 2:0-59 6:10-14
@ ./examples/App.vue?vue&type=script&lang=js
@ ./examples/App.vue
@ ./examples/index.js

2、ant-design-vue-next\components\vc-select\generate.tsx
./components/vc-select/generate.tsx 929:51-60
[tsl] ERROR in  D:\ant-design-vue-next\components\vc-select\generate.tsx(929,52)
TS2345: Argument of type 'Timeout' is not assignable to parameter of type 'number'.

3、ERROR in D:\ant-design-vue-next\components\vc-select\generate.tsx
./components/vc-select/generate.tsx 941:32-41
[tsl] ERROR in D:\ant-design-vue-next\components\vc-select\generate.tsx(941,33)
TS2345: Argument of type 'Timeout' is not assignable to parameter of type 'number'.

**Comment by skyworth365** [comment]
选错分支了

**Comment by lypynmdl** [comment]
v2-doc这个子模块无法下载

**Comment by ajuner** [comment]
> v2-doc这个子模块无法下载

文档暂未开放
