### ISSUE TITLE
请求新增Login 登录组件

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#3687]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决登录页面的问题

### What does the proposed API look like?
参考项目：

viewui Login 登录：https://www.iviewui.com/components/pro/login

**Comment by xrkffgg** [comment]
Try Form

**Comment by wsxe9988** [comment]
我觉得可以单独做下这个登录的业务组件  其他框架也有这个
比如https://www.iviewui.com/components/pro/login
https://file.iviewui.com/doc/component/pro/login2.jpg
https://file.iviewui.com/doc/component/pro/login3.jpg  等等，这样显得咱们框架更加强大

**Comment by ajuner** [comment]
你提的这些在ant-design-vue-pro里面应该都有示例吧  每项目需求的登录界面不一定是一样的  是不是没有这个必要

**Comment by tangjinzhou** [comment]
admin pro中已提供
https://store.antdv.com/pro/
