### ISSUE TITLE
请求新增GlobalFooter 全局页脚组件

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#3693]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
全局页脚常居中位于页面最底部，承载版权等信息。

### What does the proposed API look like?
参考项目:https://www.iviewui.com/components/pro/global-footer
![image](https://user-images.githubusercontent.com/5828057/108614967-61a41300-743a-11eb-8664-1fa87c69661f.png)

**Comment by tangjinzhou** [comment]
pro 相关组件都在 https://store.antdv.com/pro/
