### ISSUE TITLE
Skeleton 翻译错误

### ISSUE THREAD

**Issue by 724493602** [vueComponent/ant-design-vue#3694]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
-

### Reproduction link
[https://2x.antdv.com/components/skeleton-cn](https://2x.antdv.com/components/skeleton-cn)

### Steps to reproduce
Skeleton 翻译为代码演示， 不是应该骨架屏吗

### What is expected?
rt

### What is actually happening?
rt

**Comment by ajuner** [comment]
感谢 已经修复了  过一小段时间重新发布上去的
