### ISSUE TITLE
日期及日历组件中可以使用dayjs替换moment.js吗

### ISSUE THREAD

**Issue by 841440416** [vueComponent/ant-design-vue#3697]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
由于moment停更，并且包比较大，所以最好在项目中使用轻量的功能强大的时间库dayjs

### What does the proposed API look like?
import dayjs from 'dayjs'

**Comment by sendya** [comment]
后续会提供切换 dayjs 的方案。

**Comment by dgptyu** [comment]
在 ant-design-vue@1.7.2 中使用以下方案经不完全测试，发现可行：

1. webpack 配置 alias 替换 moment:
```js
module.exports = {
  resolve: {
    alias: {
      // 替换 antd 的 moment.js 为 dayjs
      moment: path.resolve(__dirname, "./path/to/replace-moment-with-dayjs")
    }
  }
}
```

2. `replace-moment-with-dayjs` 文件：
```js
import dayjs from "dayjs";
import localeData from "dayjs/plugin/localeData";
import moment from "dayjs/plugin/isMoment";
import mutable from "dayjs/plugin/badMutable";

dayjs.extend(localeData);
dayjs.extend(moment);
dayjs.extend(mutable);

export const isMoment = dayjs.isDayjs;
export default dayjs;
```

`alias: { moment: "dayjs" }` 不可行是因为 dayjs 本身是 immutable 的，但可通过重写原型方法变成 mutable。dayjs 提供了 `badMutable` 插件模拟 moment 的特性。因此这里先加载必要插件，再导出 dayjs。

缺点是这些插件会影响全局，如不想产生副作用，可考虑使用 webpack external 特性将 moment 替换为你打包好的 dayjs umd / commonjs 文件。

总体思路大致如此，至于各种 moment 和 dayjs 的 api 兼容问题，可加载对应插件，或自行修改原型方法。

**Comment by leochen-g** [comment]
> 后续会提供切换 dayjs 的方案。

求尽快提供官方解决方案，感谢
