### ISSUE TITLE
custom model binding in Select component

### ISSUE THREAD

**Issue by vciloglu** [vueComponent/ant-design-vue#3698]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
 I am trying to bind a custom object to antdv select component.
Custom object has ID and Name fields instead of "key" and "label"

Basically, I want to learn how to bind an object with ID and Name fields to antdv select component.

Is it possible to use model binding without converting the custom object list to a key-label pair?
Organization object is like this:
```
{
ID: "1",
Name:"Name"
}
```
Below code doesn't work because component is looking for "key" and "label" fields instead of "ID" and "Name"
```
<a-select
          v-model="model.Organizations"
          mode="multiple"
          style="width: 100%"
          placeholder="select one Organization"
          :options="$store.getters['GET_Organizations']()"
          labelInValue
        >
        </a-select>
        
```

**Comment by zkwolf** [comment]
You can use a-select-option and v-for like https://2x.antdv.com/components/select#components-select-demo-basic
