### ISSUE TITLE
image预览参数配置不生效

### ISSUE THREAD

**Issue by gfppower** [vueComponent/ant-design-vue#3701]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
2.0.0

### Reproduction link
[https://github.com/gfppower/vue-antd-test](https://github.com/gfppower/vue-antd-test)

### Steps to reproduce
我期望我的image的预览窗口在指定的容器内生成。目前配置不成功。

### What is expected?
期望能在本案例中将预览窗口生成在balabala这个容器内。

### What is actually happening?
```
<template>
<div class="balabala" ref="balabala">
<a-image
:width="200"
:preview="previewType"
src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
/>
</div>
</template>
<script lang="ts">
import { defineComponent,h ,computed,ref} from "vue";

export default defineComponent({
name: "AppAvailable",
setup(props, context) {
const balabala = ref(null)

const previewType = {
getContainer:balabala.value
}

return {
balabala,previewType
}
}
});

</script>

```
中的getContainer方法不生效。无法将预览窗口生成在balabala窗口中

**Comment by legend-li** [comment]
看了下源码，发现源码中在往下传递getContainer时，传递到Preview组件时，Preview组件根本没有使用getContainer。
下图是源码：

![image](https://user-images.githubusercontent.com/20475084/108812714-98b92680-75ea-11eb-9a78-99f62b7a969b.png)

![image](https://user-images.githubusercontent.com/20475084/108812668-80490c00-75ea-11eb-9ec9-36210245b9c2.png)

**Comment by zch233** [comment]
对，不生效
