### ISSUE TITLE
使用抽屉(Drawer)初次渲染时候会出现画面偏移情况,可在官方样例中复现

### ISSUE THREAD

**Issue by happyplum** [vueComponent/ant-design-vue#3703]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
Google Chrome(88)/Edge(88)x64

https://2x.antdv.com/components/drawer-cn

### Steps to reproduce
找到样例"渲染在当前 DOM"
点击open即可重现

### What is expected?
左侧画面不变动,弹出右侧抽屉

### What is actually happening?
第一次显示抽屉时左侧画面会出现抽屉宽度(width)的偏移,隐藏后再次打开恢复正常显示.可使用f5刷新重现

**Comment by happyplum** [comment]
我尝试了下,在火狐中不会出现左侧偏移的情况,但是每次打开抽屉右侧中的字体会出现上下抖动

**Comment by ajuner** [comment]
我看看是案例的问题还是组件的问题。。

**Comment by ajuner** [comment]
Drawer组件在placement设置为right时部分浏览器复现
overflow不设置为hidden的话不会有这个问题。。具体的没定位到。。

**Comment by happyplum** [comment]
> Drawer组件在placement设置为right时部分浏览器复现
> overflow不设置为hidden的话不会有这个问题。。具体的没定位到。。

我尝试了下默认把父元素的width设置成100%,然后通过pointer-events:none穿透去触发事件,不会触发这个问题.
应该是和width有关
我现在解决方案是默认visible为true,在onMount的时候再把它设置为false就没问题了

**Comment by ajuner** [comment]
文档临时修复了  会抽时间把drawer组件重构一下解决这个问题

**Comment by zhuxianglong** [comment]
@ajuner 这个问题修复了吗
