### ISSUE TITLE
The modal method property closable is invalid

### ISSUE THREAD

**Issue by Ariel-Tang** [vueComponent/ant-design-vue#3704]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
所有环境

### Reproduction link
[https://www.antdv.com/components/modal-cn/#API](https://www.antdv.com/components/modal-cn/#API)

### Steps to reproduce
this.$confirm({
title: '测试',
content: '测试内容',
closable: true
});

### What is expected?
The property "closable" is valid

### What is actually happening?
The property "closable" is invalid

**Comment by tangjinzhou** [comment]
@zkwolf https://github.com/vueComponent/ant-design-vue/pull/3642

**Comment by zkwolf** [comment]
下个版本修复
