### ISSUE TITLE
FormModel 表单中的 DatePicker 日期选择框 placeholder 没有本地化（已设置全局中文）

### ISSUE THREAD

**Issue by codesyofo** [vueComponent/ant-design-vue#3708]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
vue2.x

### Reproduction link
[https://antdv.com/components/form-model-cn/](https://antdv.com/components/form-model-cn/)

**Comment by ajuner** [comment]
https://github.com/vueComponent/ant-design-vue/issues/2527

**Comment by codesyofo** [comment]
> #2527
> 看一下这个的处理方法

我配置了的，在 Form 表单里是正常的，但 FormModel 表单的placeholder没有，周一到周日都是中文

form的
![image](https://user-images.githubusercontent.com/49975575/108940672-c192f780-768e-11eb-8a5e-5cfdb585e3bf.png)

formModel的
![image](https://user-images.githubusercontent.com/49975575/108940628-ab853700-768e-11eb-8c38-61546687231a.png)

**Comment by ajuner** [comment]
给个复现？

**Comment by codesyofo** [comment]
> 给个复现？

先前描述错了，项目中form没有放在modal中，formModal在modal中

[form和formModal在modal都有这个问题](https://codesandbox.io/s/vue-antd-template-forked-606f6?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ajuner** [comment]
应该是全局的$confirm拿不到a-config-provider的配置
可以这么使用下
```
import locale from "ant-design-vue/es/date-picker/locale/zh_CN";

<a-range-picker locale={locale} />
```

**Comment by codesyofo** [comment]
> 应该是全局的$confirm拿不到a-config-provider的配置
> 可以这么使用下
> 
> ```
> import locale from "ant-design-vue/es/date-picker/locale/zh_CN";
> 
> <a-range-picker locale={locale} />
> ```

这样用确实能解决 placeholder 的问题，但项目中这样用的地方有点多，有没有全局的方式使用

**Comment by ajuner** [comment]
要不Modal content里面也用config-provider包一层封装一下？

**Comment by codesyofo** [comment]
> 要不Modal content里面也用config-provider包一层封装一下？

这样也行，和直接locale要好点，但就不能统一配置了，感谢

**Comment by codesyofo** [comment]
confirm 中可直接配置 `parentContext` 获取父级 `ConfigProvider` 配置
