### ISSUE TITLE
Alert 组件自定义 icon 后，图标错位不对齐（官网的例子也是如此）

### ISSUE THREAD

**Issue by zhenzhenChange** [vueComponent/ant-design-vue#3712]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version

- ant-design-vue v2.0.0
- @ant-design/icons-vue v6.0.1

### Environment

Win10 x64、Google Chrome 88.0.4324.182、Vue 3.0.4

### Reproduction link

[https://2x.antdv.com/components/alert-cn](https://2x.antdv.com/components/alert-cn)

### Steps to reproduce

自定义 `icon` 错误偏移

![errorCode](https://s3.ax1x.com/2021/02/25/yjUKo9.png)
![error](https://s3.ax1x.com/2021/02/25/yjUeLF.png)

---

默认 `icon` 正常对齐

![successCode](https://s3.ax1x.com/2021/02/25/yjU3z6.png)
![success](https://s3.ax1x.com/2021/02/25/yjUsQf.png)

### What is expected?

图标居中，与 message 对齐在同一水平线

### What is actually happening?

向下偏移

这是官网的例子：

![off](https://s3.ax1x.com/2021/02/25/yjUvf1.png)

**Comment by ajuner** [comment]
下个版本修复~

**Comment by zhenzhenChange** [comment]
另外有两点顺带提一下

https://2x.antdv.com/components/overview-cn


- 新文档里，没有 Tag 标签组件的导航菜单
- 新文档里，每个组件页面最右边的的 API 锚点导航点了也不生效，不会跳转到 API 锚点处

**Comment by zhenzhenChange** [comment]
> 另外有两点顺带提一下
> 
> https://2x.antdv.com/components/overview-cn
> 
> * 新文档里，没有 Tag 标签组件的导航菜单（需要搜索才能找到）
> * 新文档里，每个组件页面最右边的的 API 锚点导航点了也不生效，不会跳转到 API 锚点处

这两个问题均已修复，感谢各位的辛勤付出！
