### ISSUE TITLE
vite2+vue2 Build failed

### ISSUE THREAD

**Issue by sz-shui** [vueComponent/ant-design-vue#3715]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
vue 2.6.12,vite 2.0.3

### Reproduction link
[https://github.com/sz-shui/vite-vue2-adv](https://github.com/sz-shui/vite-vue2-adv)

### Steps to reproduce
1. yarn
1. yarn run build

### What is expected?
build success

### What is actually happening?
```
transforming (359) node_modules\.pnpm\ant-design-vue@1.7.3_vue@2.6.12\node_modules\ant-design-v
be resolved – treating it as an external dependency
transforming (1120) node_modules\.pnpm\lodash@4.17.21\node_modules\lodash\_coreJsData.js'isMome
'isMoment' is not exported by 'node_modules\.pnpm\moment@2.29.1\node_modules\moment\dist\moment
'isMoment' is not exported by 'node_modules\.pnpm\moment@2.29.1\node_modules\moment\dist\moment
'isMoment' is not exported by 'node_modules\.pnpm\moment@2.29.1\node_modules\moment\dist\moment
'isMoment' is not exported by 'node_modules\.pnpm\moment@2.29.1\node_modules\moment\dist\moment
```

**Comment by JinPengGeng** [comment]
yarn add moment

**Comment by tangjinzhou** [comment]
you can use ant-design-vue@2.0

**Comment by carl-jin** [comment]
vue2 可以直接和  ant-design-vue@2.0 一起使用？

**Comment by carl-jin** [comment]
https://github.com/carl-jin/vite-plugin-antdv1-momentjs-resolver
写了小插件, 解决了这个问题

**Comment by moliyu** [comment]
试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题

**Comment by walid1992** [comment]
问题还是存在，只是错误由4行减少到1行了。会导致build很慢

**Comment by walid1992** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/16499191/192962696-1f88646f-9df9-4a0c-a006-45d25e25cf90.png">

**Comment by moliyu** [comment]
> 

可以看看你的错误吗，或者试试我的插件

**Comment by walid1992** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/16499191/192962892-cb51adfe-dcd2-4967-8267-949c552ab8ee.png">

**Comment by walid1992** [comment]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/16499191/192963011-5d561e64-a72e-47a9-aab1-0d0e3c3b3495.png">

**Comment by walid1992** [comment]
> > 
> 
> 可以看看你的错误吗，或者试试我的插件

简单初始化了一个 Vite 3.0 + Vue 2.0 的项目，就可以验证出来这个问题

**Comment by moliyu** [comment]
> antdvFix({files=['**/**.js']})你可以试着添加排除目录

**Comment by moliyu** [comment]
> > > 
> > 
> > 
> > 可以看看你的错误吗，或者试试我的插件
> 
> 简单初始化了一个 Vite 3.0 + Vue 2.0 的项目，就可以验证出来这个问题

能给个地址么

**Comment by walid1992** [comment]
> > > > 
> > > 
> > > 
> > > 可以看看你的错误吗，或者试试我的插件
> > 
> > 
> > 简单初始化了一个 Vite 3.0 + Vue 2.0 的项目，就可以验证出来这个问题
> 
> 能给个地址么

就官方 Vite 的初始化流程走完就遇到啦，哈哈哈

**Comment by walid1992** [comment]
> 

https://github.com/walid1992/vite-sample 非常简单的项目，push 了一下，

**Comment by walid1992** [comment]
> > > > 
> > > 
> > > 
> > > 可以看看你的错误吗，或者试试我的插件
> > 
> > 
> > 简单初始化了一个 Vite 3.0 + Vue 2.0 的项目，就可以验证出来这个问题
> 
> 能给个地址么

https://github.com/walid1992/vite-sample 非常简单的项目 push 了一下

**Comment by moliyu** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 可以看看你的错误吗，或者试试我的插件
> > > 
> > > 
> > > 简单初始化了一个 Vite 3.0 + Vue 2.0 的项目，就可以验证出来这个问题
> > 
> > 
> > 能给个地址么
> 
> 您有帮忙试一下吗 是否有同样的问题呀
在看，稍等

**Comment by walid1992** [comment]
感谢感谢 😁

**Comment by walid1992** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/16499191/193000810-97febc98-904f-4f1f-a221-64bd6d204943.png">

构建后还是有问题，monent 的 奇怪了

**Comment by moliyu** [comment]
> 感谢感谢 😁

你现在可以了么

**Comment by zjg910723** [comment]
> 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题

你这个插件开发环境没问题，打包到生产就不行了

**Comment by moliyu** [comment]
> > 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题
> 
> 你这个插件开发环境没问题，打包到生产就不行了

生产环境得问题是啥

**Comment by zjg910723** [comment]
> > > > 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题
> > > 
> > > 
> > > 你这个插件开发环境没问题，打包到生产就不行了
> > 
> > 
> > 生产环境得问题是啥
> 
> 提示 <img alt="image" width="734" src="https://user-images.githubusercontent.com/26216606/194733660-8b84652e-7867-411d-b7db-da26c39804ea.png"> 这个就是moment的问题

<img width="928" alt="image" src="https://user-images.githubusercontent.com/26216606/194733730-ffc6702d-82d5-4a68-a43e-5c2d8bfa3c86.png">
这是我的配置文件

**Comment by moliyu** [comment]
> > > > > 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题
> > > > 
> > > > 
> > > > 你这个插件开发环境没问题，打包到生产就不行了
> > > 
> > > 
> > > 生产环境得问题是啥
> > 
> > 
> > 提示 <img alt="image" width="734" src="https://user-images.githubusercontent.com/26216606/194733660-8b84652e-7867-411d-b7db-da26c39804ea.png"> 这个就是moment的问题
> 
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/26216606/194733730-ffc6702d-82d5-4a68-a43e-5c2d8bfa3c86.png">
> 
> 这是我的配置文件

能提供一个复现仓库吗

**Comment by moliyu** [comment]
> > > > > 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题
> > > > 
> > > > 
> > > > 你这个插件开发环境没问题，打包到生产就不行了
> > > 
> > > 
> > > 生产环境得问题是啥
> > 
> > 
> > 提示 <img alt="image" width="734" src="https://user-images.githubusercontent.com/26216606/194733660-8b84652e-7867-411d-b7db-da26c39804ea.png"> 这个就是moment的问题
> 
> <img alt="image" width="928" src="https://user-images.githubusercontent.com/26216606/194733730-ffc6702d-82d5-4a68-a43e-5c2d8bfa3c86.png">
> 
> 这是我的配置文件

试试1.0.2

**Comment by meiliujun** [comment]
> > > > > > 试试这个 [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)，同时解决了生产环境require is not defined的问题
> > > > > 
> > > > > 
> > > > > 你这个插件开发环境没问题，打包到生产就不行了
> > > > 
> > > > 
> > > > 生产环境得问题是啥
> > > 
> > > 
> > > 提示 <img alt="image" width="734" src="https://user-images.githubusercontent.com/26216606/194733660-8b84652e-7867-411d-b7db-da26c39804ea.png"> 这个就是moment的问题
> > 
> > 
> > <img alt="image" width="928" src="https://user-images.githubusercontent.com/26216606/194733730-ffc6702d-82d5-4a68-a43e-5c2d8bfa3c86.png">
> > 这是我的配置文件
> 
> 试试1.0.2

可以试试在html的head标签中添加<script>var module = {};</script>，盲猜和rollup-plugin-commonjs有关系，没有代码仓库确认不了问题。可以参考 https://github.com/vitejs/vite/issues/4113 这个issue

@moliyu 另外麻烦1.0.2上传一下npm仓库吧。。现在最新版本还是1.0.1

**Comment by moliyu** [comment]
> 

已经上传了
