### ISSUE TITLE
ublock origin

### ISSUE THREAD

**Issue by EricSUID** [vueComponent/ant-design-vue#3718]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
Win10 19042.804(20H2), Vivaldi 3.6.2165.40 (Stable channel) （64 位）Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.186 Safari/537.36, Vue 1.X

### Reproduction link
[https://2x.antdv.com/components/cascader-cn](https://2x.antdv.com/components/cascader-cn)

### Steps to reproduce
1. 关闭ublock origin插件
2. 重启浏览器

### What is expected?
ublock origin添加白名单后可以查看展开代码

### What is actually happening?
关闭ublock origin插件并重启浏览器也无法查看展开代码

**Comment by zkwolf** [comment]
我试了一下ublock，关了是可以的啊

**Comment by EricSUID** [comment]
![image](https://user-images.githubusercontent.com/43235133/109129110-3b101000-778b-11eb-9fe0-7a92ec43e4a0.png)
...那或许是浏览器的问题，edge也没问题

**Comment by zkwolf** [comment]
vivaldi似乎自带了广告过滤（宣传是这么说的哈哈

**Comment by EricSUID** [comment]
那我知道了😅
