### ISSUE TITLE
types 目录为啥不一起发布到npm?

### ISSUE THREAD

**Issue by xxbld** [vueComponent/ant-design-vue#372]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
types 目录为啥不一起发布到npm?

### What does the proposed API look like?
types 目录为啥不一起发布到npm?

**Comment by tangjinzhou** [comment]
types是1.2.4版本之后才有的  下个版本会发布的

**Comment by xxbld** [comment]
可以加一个scrollbar功能吗.目前找到的都是虚拟的affix和backtop都无法拿到滚动距离
