### ISSUE TITLE
Carousel 走马灯 路面路由手机版无法点击、导航到新路由页面

### ISSUE THREAD

**Issue by jiankian** [vueComponent/ant-design-vue#3721]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
macOS:10.15.7,Chrome:latest/版本 90.0.4421.5（正式版本）dev (x86_64)

### Reproduction link
[https://1x.antdv.com/components/carousel-cn/](https://1x.antdv.com/components/carousel-cn/)

### Steps to reproduce
链接PC页面可以点击，切换开发者模式响应式手机版就不能点击路由链接，真机也不行

### What is expected?
链接PC页面可以点击，切换开发者模式响应式手机版就不能点击路由链接，真机也不行

### What is actually happening?
Mobile mode,and Chrome Mobile/iPad Mode。手机版都会发生

---
```
<a-carousel arrows style="width:900px;max-width:100%;">
  <router-link to="/Topic/innovation-index-loan">
    <img src="/static/images/Banner_innovation_index_loan.jpg" style="width: 100%;max-width: 100%">
  </router-link>
  <router-link to="/Topic/innovation-index-loan">
    <img src="/static/images/Banner_innovation_index_loan.jpg" style="width: 100%;max-width: 100%">
  </router-link>
</a-carousel>
```

**Comment by tangjinzhou** [comment]
img 改成 div  图片用 background
