### ISSUE TITLE
date-picker run error

### ISSUE THREAD

**Issue by oimmc** [vueComponent/ant-design-vue#3726]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
mac vue3.06 chrome

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn](https://2x.antdv.com/components/date-picker-cn)

### Steps to reproduce
select date

### What is expected?
no error

### What is actually happening?
error:
Uncaught (in promise) TypeError: Cannot assign to read only property 'onKeyDown' of object '#<Object>'

**Comment by ajuner** [comment]
vue先退到3.0.5吧

**Comment by tangjinzhou** [comment]
https://github.com/vuejs/vue-next/issues/3300

**Comment by zkwolf** [comment]
update to vue3.0.7
