### ISSUE TITLE
Carousel and Steps components report errors

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#3728]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0

### Environment
vite2.03   vue3.05

### Reproduction link
[https://2x.antdv.com/components/carousel-cn](https://2x.antdv.com/components/carousel-cn)

### Steps to reproduce
使用Carousel和Steps组件，js报错

Carousel 的报错信息
![图片](https://user-images.githubusercontent.com/64787128/109308448-fcf31900-787c-11eb-9a38-c53ef009c42d.png)

Steps 的报错信息
![图片](https://user-images.githubusercontent.com/64787128/109308219-b0a7d900-787c-11eb-91a3-17a796fd138b.png)

### What is expected?
不报错，正常显示

### What is actually happening?
Carousel和Steps组件无法正常显示

**Comment by tangjinzhou** [comment]
https://github.com/vuejs/vue-next/issues/3300
等待 vue 发版本   暂时使用 3.0.5 版本即可

**Comment by zkwolf** [comment]
upgrade to vue3.0.7
