### ISSUE TITLE
Why does ant-design-vue 2.x not fully adopt the combined api method for development?

### ISSUE THREAD

**Issue by stupidLast** [vueComponent/ant-design-vue#3730]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决内心的疑惑

### What does the proposed API look like?
Win10、Chrome 88、Vue3

**Comment by sendya** [comment]
重构需要时间，只能一个组件一个组件的来
