### ISSUE TITLE
要求增加二维码生成组件

### ISSUE THREAD

**Issue by w2yong77** [vueComponent/ant-design-vue#374]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
二维码生成

### What does the proposed API look like?
<a-qrcode src="xxxx"/>

**Comment by dsonet** [comment]
QR Code already has many implementations. And it has nothing to do with ant-design.

**Comment by nabaonan** [comment]
react版的有么？这个感觉组件库不会有的

**Comment by tangjinzhou** [comment]
暂不考虑
