### ISSUE TITLE
After a-table-column loop traversal, the content slot is invalid

### ISSUE THREAD

**Issue by Emp2612** [vueComponent/ant-design-vue#3740]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
操作系统：windows10；浏览器：Chrome版本 88.0.4324.150；Vue版本："^2.6.11"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-j2ggg?file=/src/App.vue)

### Steps to reproduce
Table组件使用template方式循环遍历column后，slot失效，链接里有详细demo

### What is expected?
使用template方式循环遍历column后，可正常使用 slot

### What is actually happening?
使用template方式循环遍历column后，slot失效

**Comment by ajuner** [comment]
两者挑一个用吧，建议使用<a-table :columns="columns">

**Comment by Emp2612** [comment]
> 两者挑一个用吧，建议使用

改用JSX方式使用，解决了这个问题
