### ISSUE TITLE
about v-model:value parameter '$event' implicitly has an 'any' type

### ISSUE THREAD

**Issue by ifzm** [vueComponent/ant-design-vue#3742]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
windows 10, chrome 88, vue 3.0.7

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
- use vscode
- install VueDX
- input `<a-input v-model:value="xxx" style="width: 80%" />` of a.vue
- appear error tips `parameter '$event' implicitly has an 'any' type`

### What is expected?
no error tips

### What is actually happening?
appear error tips

---
it does not affect the use of, but it is not legal in ide. (

I want to know if it is the problem of VueDX or ant-design-vue types, I hope to get help, thanks

**Comment by luliangce** [comment]
this problem lead a typecheck faild when use `npx vuedx-typecheck `
