### ISSUE TITLE
Drawer Keyboard doesn't get triggered when drawer area is not clicked

### ISSUE THREAD

**Issue by ryuchaehwa** [vueComponent/ant-design-vue#3749]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
vue@2.6.11

### Reproduction link
[http://.](http://.)

### Steps to reproduce
1. Add a drawer component with button to trigger it.
2. Click button to open the drawer component
3. Press 'esc' key on the keyboard

### What is expected?
A drawer closes itself.

### What is actually happening?
A drawer doesn't close itself, user has to click any area on the drawer component, then press 'esc' key on the keyboard will work.

---
Sorry to not providing a link. It's just really a minor bug so......

**Comment by zkwolf** [comment]
It seems that the fix of #3148 was not committed to 1.x version

**Comment by zkwolf** [comment]
Will be fixed in next release #3790.
