### ISSUE TITLE
table component，use template api， when value is array ：throw error: Maximum recursive updates exceeded.

### ISSUE THREAD

**Issue by greper** [vueComponent/ant-design-vue#3751]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
vue 3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-noyce-jf69m)

### Steps to reproduce
```
<template>
<a-table :data-source="dataRef">
<a-table-column key="tags" title="Tags" data-index="tags" />
</a-table>
</template>
<script>
import { defineComponent, ref, onMounted } from "vue";
const data = [
{
tags: ["123"], // 这里使用数组会报错，如果是字符串、Object、 number 都正常
},
];

export default defineComponent({
setup() {
const dataRef = ref([]);
onMounted(() => {
dataRef.value = data;
});
return {
dataRef,
};
},
});
</script>

```

### What is expected?
当  tags: ["123"]  不要报错

### What is actually happening?
tags: ["123"], // 这里使用数组会报错，如果是字符串、Object、 number 都正常

**Comment by joker77877** [comment]
我遇到了同样的错误，什么时候修复

**Comment by ajuner** [comment]
定位到数组类型被createElement方法包了一层
尝试修复中。。
