### ISSUE TITLE
1.7.3 version production environment table table component remote loading data module code word misspelling

### ISSUE THREAD

**Issue by TencentIT** [vueComponent/ant-design-vue#3754]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
antDesign of vue 生产环境1.7.3版本

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
1.打开antDesign of Vue 中文官网 https://www.antdv.com/components/table-cn/；
2.版本号选择1.7.3；
3.点击左侧菜单栏“Table 表格”组件
4.查看 “远程加载数据 #”这块使用用法的示例代码，下面是目前官网的实例代码
`<template>
<a-table
:columns="columns"
:row-key="record => record.login.uuid"
:data-source="data"
:pagination="pagination"
:loading="loading"
@change="handleTableChange"
>
<template slot="name" slot-scope="name"> {{ name.first }} {{ name.last }} </template>
</a-table>
</template>
<script>
import reqwest from 'reqwest';
const columns = [
{
title: 'Name',
dataIndex: 'name',
sorter: true,
width: '20%',
scopedSlots: { customRender: 'name' },
},
{
title: 'Gender',
dataIndex: 'gender',
filters: [
{ text: 'Male', value: 'male' },
{ text: 'Female', value: 'female' },
],
width: '20%',
},
{
title: 'Email',
dataIndex: 'email',
},
];

export default {
data() {
return {
data: [],
pagination: {},
loading: false,
columns,
};
},
mounted() {
this.fetch();
},
methods: {
handleTableChange(pagination, filters, sorter) {
console.log(pagination);
const pager = { ...this.pagination };
pager.current = pagination.current;
this.pagination = pager;
this.fetch({
results: pagination.pageSize,
page: pagination.current,
sortField: sorter.field,
sortOrder: sorter.order,
...filters,
});
},
fetch(params = {}) {
console.log('params:', params);
this.loading = true;
reqwest({
url: 'https://randomuser.me/api',
method: 'get',
data: {
results: 10,
...params,
},
type: 'json',
}).then(data => {
const pagination = { ...this.pagination };
// Read total count from server
// pagination.total = data.totalCount;
pagination.total = 200;
this.loading = false;
this.data = data.results;
this.pagination = pagination;
});
},
},
};
</script>`
5.发现里面有一个单词拼写错误 “reqwest” ，作者的本意应该是引入ajax请求，但是请求这个单词拼写错误了，应该为 “request”

### What is expected?
实例代码应该改成下面这样：
`<template>
<a-table
:columns="columns"
:row-key="record => record.login.uuid"
:data-source="data"
:pagination="pagination"
:loading="loading"
@change="handleTableChange"
>
<template slot="name" slot-scope="name"> {{ name.first }} {{ name.last }} </template>
</a-table>
</template>
<script>
import request from 'request ';
const columns = [
{
title: 'Name',
dataIndex: 'name',
sorter: true,
width: '20%',
scopedSlots: { customRender: 'name' },
},
{
title: 'Gender',
dataIndex: 'gender',
filters: [
{ text: 'Male', value: 'male' },
{ text: 'Female', value: 'female' },
],
width: '20%',
},
{
title: 'Email',
dataIndex: 'email',
},
];

export default {
data() {
return {
data: [],
pagination: {},
loading: false,
columns,
};
},
mounted() {
this.fetch();
},
methods: {
handleTableChange(pagination, filters, sorter) {
console.log(pagination);
const pager = { ...this.pagination };
pager.current = pagination.current;
this.pagination = pager;
this.fetch({
results: pagination.pageSize,
page: pagination.current,
sortField: sorter.field,
sortOrder: sorter.order,
...filters,
});
},
fetch(params = {}) {
console.log('params:', params);
this.loading = true;
request ({
url: 'https://randomuser.me/api',
method: 'get',
data: {
results: 10,
...params,
},
type: 'json',
}).then(data => {
const pagination = { ...this.pagination };
// Read total count from server
// pagination.total = data.totalCount;
pagination.total = 200;
this.loading = false;
this.data = data.results;
this.pagination = pagination;
});
},
},
};
</script>```

### What is actually happening?
页面都是正常的，但是官网实例代码单词拼写错误，感觉不是很好

---
开发的时候看实例代码的时候发现的

**Comment by TencentIT** [comment]
**总结这个bug：**
table组件 官网实例代码单词 **reqwest** 这个单词应该修改成 **request**

**Comment by zkwolf** [comment]
https://www.npmjs.com/package/reqwest 

reqwest也是一个请求库
