### ISSUE TITLE
types interface customSelction  in table.d.ts

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#376]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.5

### Environment
1.2.5

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/types/table/table.d.ts#L16](https://github.com/vueComponent/ant-design-vue/blob/master/types/table/table.d.ts#L16)

### Steps to reproduce
change customSelction  to customSelection

### What is expected?
export interface customSelection {

### What is actually happening?
export interface customSelction {

**Comment by tangjinzhou** [comment]
Can you give us a PR directly?

**Comment by agoni1212** [comment]
#377
