### ISSUE TITLE
Tree transfer problem, please help me

### ISSUE THREAD

**Issue by 531431988** [vueComponent/ant-design-vue#3760]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
VUE2.X

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-treetransfer-forked-4ohb9)

### Steps to reproduce
无

### What is expected?
https://codepen.io/Aoobruce/pen/eYpwBbM

### What is actually happening?
https://codepen.io/Aoobruce/pen/eYpwBbM

---
tree transfer 问题，求各位大佬帮看看，有个REACT版本的tree transfer 问题，求各位大佬帮看看

**Comment by John60676** [comment]
描述一下你的问题？

**Comment by 531431988** [comment]
> 描述一下你的问题？

想用antv做个 https://codepen.io/Aoobruce/pen/eYpwBbM 这种效果，支持数据保存后，根据保存的数据初始化组件状态

**Comment by John60676** [comment]
你这代码都有了，直接用 Vue 实现一遍就好了

**Comment by 531431988** [comment]
> 你这代码都有了，直接用 Vue 实现一遍就好了
上面有个链接弄了有问题，没找到，还有就是回显的不知道怎么处理

**Comment by 531431988** [comment]
> 你这代码都有了，直接用 Vue 实现一遍就好了
https://codesandbox.io/s/antd-treetransfer-forked-4ohb9?file=/src/App.vue
还有点问题

**Comment by John60676** [comment]
> > 你这代码都有了，直接用 Vue 实现一遍就好了
> > https://codesandbox.io/s/antd-treetransfer-forked-4ohb9?file=/src/App.vue
> > 还有点问题

有问题你要描述你的问题。不然没人知道你想要问啥

**Comment by 531431988** [comment]
> > > 你这代码都有了，直接用 Vue 实现一遍就好了
> > > https://codesandbox.io/s/antd-treetransfer-forked-4ohb9?file=/src/App.vue
> > > 还有点问题
> 
> 有问题你要描述你的问题。不然没人知道你想要问啥
问题1：勾选选中项添加到右侧时，右侧的选项没有禁用
问题2：初始化选中指定项目后，左侧的项目没有禁用，也没有被添加到右侧
修改版本地址：https://codesandbox.io/s/antd-treetransfer-forked-4ohb9?file=/src/App.vue

**Comment by 531431988** [comment]
![image](https://user-images.githubusercontent.com/8703951/111092781-fd282f80-8571-11eb-84b1-41e190fdfa3e.png)
![image](https://user-images.githubusercontent.com/8703951/111092826-25b02980-8572-11eb-804b-c392e8d54df5.png)

**Comment by John60676** [comment]
这是你自己实现的问题，与框架无关
