### ISSUE TITLE
Click the a-modal cross to report an error, and the popup cannot be closed

### ISSUE THREAD

**Issue by lixianyu-icon** [vueComponent/ant-design-vue#3761]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
vue3.0.1

### Reproduction link
[http://xxx.com](http://xxx.com)

### Steps to reproduce
1.父级组件通过<Edit v-model:visible="visible" />

2.子组件
<a-modal
v-model:visible="visible"
centered
destroyOnClose
:title="modalTitle"
@cancel='handleCancel1'
@ok="handleOk">
<p>Some contents...</p>
<p>Some contents...</p>
<p>Some contents...</p>
<template #footer>
<a-button key="back" @click="handleCancel1">返回</a-button>
<a-button key="submit" type="primary" :loading="loading" @click="handleOk">确认</a-button>
</template>
</a-modal>

3.// 实现代码
setup(props, context) {
/** 加载中 */
const loading = ref(false);

const handleOk = (e: MouseEvent) => {
close();
};
const handleCancel1 =() => {
close();
}
const close = () => {
context.emit('update:visible', false);
}
const modalTitle = computed(() => {
return titleMap.get(props.mode);
});
return {
loading,
handleOk,
modalTitle,
handleCancel1
};
},
点击取消按钮可以关闭，点击叉叉报错：
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'visible'
at _createBlock.onUpdate:visible._cache.<computed>._cache.<computed> (Edit.vue:4)
at callWithErrorHandling (runtime-core.esm-bundler.js:154)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
at emit (runtime-core.esm-bundler.js:642)
at Proxy.handleCancel (Modal.js:145)
at Proxy.__emit (BaseMixin.js:57)
at Proxy.close4 (Dialog.js:482)
at callWithErrorHandling (runtime-core.esm-bundler.js:154)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:308)
我这里怀疑是cancel回调的执行时机太早

### What is expected?
点击可以直接关闭

### What is actually happening?
不能关闭并报错

**Comment by lixianyu-icon** [comment]
> Hello @lixianyu-icon. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @lixianyu-icon, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

**Comment by lixianyu-icon** [comment]
那我问一个直接的问题吧。
cancel回调里面能否使用context

**Comment by lixianyu-icon** [comment]
> Hello @lixianyu-icon. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @lixianyu-icon, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

回显地址：https://codesandbox.io/s/beautiful-volhard-tgbsu

**Comment by zkwolf** [comment]
大概是因为你v-model绑定了prop吧

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/dank-dream-x743z?file=/src/components/modal.vue

1. prop 值 不建议修改
2. 不建议用父来控制子的属性，可以采用方法的形式

**Comment by lixianyu-icon** [comment]
> 大概是因为你v-model绑定了prop吧

这是不是vue3官方的写法吗？

**Comment by lixianyu-icon** [comment]
> https://codesandbox.io/s/dank-dream-x743z?file=/src/components/modal.vue
> 
> 1. prop 值 不建议修改
> 2. 不建议用父来控制子的属性，可以采用方法的形式

这只能解决点击叉关闭的问题，点击取消和确定又不行了。方法我试过了，还没执行cancel就报错了。

**Comment by lixianyu-icon** [comment]
> https://codesandbox.io/s/dank-dream-x743z?file=/src/components/modal.vue
> 
> 1. prop 值 不建议修改
> 2. 不建议用父来控制子的属性，可以采用方法的形式

这只能解决点击叉关闭的问题，点击取消和确定又不行了。方法我试过了，还没执行cancel就报错了。

**Comment by xrkffgg** [comment]
![Kapture 2021-03-09 at 13 57 52](https://user-images.githubusercontent.com/29775873/110425554-7c83b200-80df-11eb-95fc-78ed89bd6e33.gif)

**Comment by lixianyu-icon** [comment]
https://user-images.githubusercontent.com/73095124/110434225-8233c480-80ec-11eb-8931-2dbd2baf6fe7.mp4

Are you sure?

**Comment by xrkffgg** [comment]
😳

**Comment by xrkffgg** [comment]
应该没问题的，你再试试

**Comment by lixianyu-icon** [comment]
> 应该没问题的，你再试试

const refModal = ref()
    const openModal = () => {
      refModal.value.openModal()
    };
    return {
      refModal,
      openModal,
    };
采用了再父组件调用子组件的方法，这样是可以的

**Comment by oimmc** [comment]
只有在用vue3中使用setup，才会有报错。

**Comment by oimmc** [comment]
"ant-design-vue": "2.1.0"

vuex4中会有报错：
Uncaught Error: [vuex] do not mutate vuex store state outside mutation handlers.

v-model:visible="$store.visible"
@cancel="handleCancel"

handleCancel并被没有执行。

**Comment by rainmanhhh** [comment]
jsx/tsx里面怎么写呢？
v-model:visible报Failed to resolve directive: model:visible
vModel:visible又无法编译

**Comment by CurryPaste** [comment]
> > 应该没问题的，你再试试
> 
> const refModal = ref()
> const openModal = () => {
> refModal.value.openModal()
> };
> return {
> refModal,
> openModal,
> };
> 采用了再父组件调用子组件的方法，这样是可以的

试了一下，用自定页脚的方式也可以，这样改动应该比较小了
