### ISSUE TITLE
Form nested data problem

### ISSUE THREAD

**Issue by yeojongki** [vueComponent/ant-design-vue#3763]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-lamarr-9ghyw?file=/src/main.js)

### Steps to reproduce
1. 在名称输入框输入任意字符，触发 `rules` 的 `validator` 函数，可以正确获取到 `value` 值
2. 在嵌套名称中输入任意字符，触发 `rules` 的 `validator` 函数，不能获取到 `value` 值
3. 点击提交，在 `onFinish` 事件中不能获取 `sub.name` 的值

### What is expected?
嵌套数据能够正常校验，`onFinish` 事件中能获取正确的值

### What is actually happening?
嵌套数据不能正常校验，`onFinish` 事件中不能获取正确的值

---
补充：使用 `jsx` 编写，请问是写法有问题还是不支持嵌套数据? 看示例只有用 `useForm` 才支持嵌套数据?

**Comment by yeojongki** [comment]
@tangjinzhou

**Comment by zkwolf** [comment]
duplicate #3901
