### ISSUE TITLE
V-Decorator in autocomplete

### ISSUE THREAD

**Issue by rahultailwal** [vueComponent/ant-design-vue#3774]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
Windows 10, Chrome,

### Reproduction link
[https://www.antdv.com/components/auto-complete/](https://www.antdv.com/components/auto-complete/)

### Steps to reproduce
As per documentation we have to use v-model to get and update the value in auto complete but what if we have other fields in form using v-decorator. How to do that?

### What is expected?
V-decorator should be there with autocomplete also.

### What is actually happening?
Not allowing to use v-decorator

**Comment by zkwolf** [comment]
https://www.antdv.com/components/form-cn/#components-form-demo-registration There is a demo that using auto-complete in form.

**Comment by rahultailwal** [comment]
Hi I see there is no autocomplete in that example. Its cascader https://www.antdv.com/components/cascader/. Please let me know if I am seeing wrong

**Comment by zkwolf** [comment]
![image](https://user-images.githubusercontent.com/8555127/110434691-19008100-80ed-11eb-9a6d-99331502da97.png)

**Comment by rahultailwal** [comment]
Thanks, got it. Question: How can we ensure that user should select the values from the options instead of typing anything in the autocomplete field?

**Comment by rahultailwal** [comment]
any news for it? @zkwolf
