### ISSUE TITLE
Change the font color of the label in Form.Item

### ISSUE THREAD

**Issue by Brave-Jun** [vueComponent/ant-design-vue#3780]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
  

大家好了，请教一下Form.Item中label样式如何更改

![image](https://user-images.githubusercontent.com/24540871/110410926-a11e6080-80c4-11eb-8829-5afb68465212.png)

**Comment by John60676** [comment]
https://1x.antdv.com/components/form-cn/#Form.Item  可以自己使用 `label`  的插槽来实现

**Comment by Brave-Jun** [comment]
> https://1x.antdv.com/components/form-cn/#Form.Item 可以自己使用 `label` 的插槽来实现

好的，感谢，我现在是直接在a-form-item下使用了span标签显示label
