### ISSUE TITLE
The data structure returned by form onFinish is incorrect when the form-item name is passed into the array

### ISSUE THREAD

**Issue by lihxhit** [vueComponent/ant-design-vue#3782]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
vue3

### Steps to reproduce

a-form-item :name='["bannerInfo", "openType"]'/>

data(){
return {
formState:{
bannerInfo:{openType:1}
}
}
}

onFinish(value){
console.log(value)
}

### What is expected?
//  {
bannerInfo:{openType:1}
}

### What is actually happening?
{
'bannerInfo,openType':1
}

**Comment by lihxhit** [comment]
form不支持嵌套属性吗？

**Comment by lihxhit** [comment]
有人关注到这个问题吗？

**Comment by zkwolf** [comment]
最新版试试？我用最新版没复现出来
