### ISSUE TITLE
Is there no formModel component in the 2.x version? Hope to add formModel components

### ISSUE THREAD

**Issue by tanxuewei** [vueComponent/ant-design-vue#3791]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac, vue2,webpack4.x

### Reproduction link
[https://www.antdv.com/docs/vue/customize-theme-cn](https://www.antdv.com/docs/vue/customize-theme-cn)

### Steps to reproduce
1.x版本中有formModel组件，并在使用；
2.x版本没有formModel组件了么？希望增加formModel组件。

### What is expected?
2.x版本增加formModel组件

### What is actually happening?
2.x版本没有formModel组件

**Comment by zkwolf** [comment]
formmodel在2.0作为默认form实现了
