### ISSUE TITLE
Modal custom dialogStyle:{top:20px}, when the button in #footer is in the loading state, the dialogStyle is invalid

### ISSUE THREAD

**Issue by kagaricyan** [vueComponent/ant-design-vue#3793]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
win10、 chrome 88、vue 2.6.11

### Reproduction link
[https://github.com/kagaricyan/bug-demo/blob/v1.0.1/src/App.vue](https://github.com/kagaricyan/bug-demo/blob/v1.0.1/src/App.vue)

### Steps to reproduce
运行项目，点击`打开dialog`
点击dialog中的`解析`

### What is expected?
modal top 20px

### What is actually happening?
modal top 20px 失效

**Comment by John60676** [comment]
fixed in #3794
