### ISSUE TITLE
url does not exist

### ISSUE THREAD

**Issue by zonghuaj** [vueComponent/ant-design-vue#3798]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
2.0.1

### Reproduction link
[https://github.com/vueComponent/v2-doc](https://github.com/vueComponent/v2-doc)

### Steps to reproduce
[submodule "v2-doc"]
path = v2-doc
url = https://github.com/vueComponent/v2-doc
url = https://github.com/vueComponent/v2-doc 不存在

### What is expected?
url = https://github.com/vueComponent/v2-doc 不存在

### What is actually happening?
url = https://github.com/vueComponent/v2-doc 不存在

---
url = https://github.com/vueComponent/v2-doc 不存在

**Comment by John60676** [comment]
这个是文档仓库，暂时还没有公开
