### ISSUE TITLE
Can the official website sample code be made public?

### ISSUE THREAD

**Issue by zonghuaj** [vueComponent/ant-design-vue#3800]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
官网示例代码能否公开

### Reproduction link
[https://github.com/vueComponent/v2-doc](https://github.com/vueComponent/v2-doc)

### Steps to reproduce
官网示例代码能否公开

### What is expected?
官网示例代码能否公开

### What is actually happening?
官网示例代码能否公开

**Comment by ajuner** [comment]
1.x文档已公开
2.x暂不公开
