### ISSUE TITLE
ABackTop works abnormally under Keep-Alive

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#3801]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
MacOS 10.13.4, Chrome 87.0.4280.141, Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdeisgnvue-abacktop-51jbz?file=/src/App.vue)

### Steps to reproduce
Please see codesandbox link

### What is expected?
ABackTop is invisible

### What is actually happening?
ABackTop is still visible

**Comment by gaokun** [comment]
I would like to add `activated` to handle scroll in BackTop, sounds good?

like: 
```js
activated() {
    this.$nextTick(() => {
      this.handleScroll();
    });
}
```

**Comment by John60676** [comment]
Wellcome PR

**Comment by gaokun** [comment]
@John60676 
PR submitted.

If approved, I think we need to do same in `next` branch.

**Comment by John60676** [comment]
done
