### ISSUE TITLE
Tree tree control-searchable tree full name search can not expand the search results

### ISSUE THREAD

**Issue by 164250072** [vueComponent/ant-design-vue#3809]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
2.x

### Reproduction link
[https://2x.antdv.com/components/tree-cn](https://2x.antdv.com/components/tree-cn)

### Steps to reproduce
例如搜索0-0-0-1
1. 输入0-0-0展开已存在的节点
2. 继续输入0-0-0-1，所有节点折叠

### What is expected?
期望展开0-0-0-1所在节点

### What is actually happening?
所有节点折叠

**Comment by zkwolf** [comment]
唔，例子我给修了，网站还没更新

**Comment by zkwolf** [comment]
已更新
