### ISSUE TITLE
How does the a-date-picker component control the unselectable year?

### ISSUE THREAD

**Issue by Easy-MJ** [vueComponent/ant-design-vue#3810]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
MacOS，版本 88.0.4324.146（正式版本） (x86_64)，2.6.11

### Reproduction link
[https://antdv.com/components/date-picker-cn/](https://antdv.com/components/date-picker-cn/)

### Steps to reproduce
- 使用组件
``` js
<a-date-picker
:mode="mode"
:open="startYear.open"
:disabled-date="disabledYearStartDate"
@openChange="onStartYearOpenChange"
@panelChange="onStartYearPanelChange"
v-decorator="decorators.start_time"
format="YYYY" />
```

- 定义禁用处理方法
``` js
disabledYearStartDate (current) {
console.log(current.year(), this.$moment().year())
return current && current.year() < this.$moment().year()
},
```

### What is expected?
可以正常对当前年份之前的年份实现禁用

### What is actually happening?
禁用无效

**Comment by John60676** [comment]
用你提供的代码，这不禁用了吗

https://codesandbox.io/s/vue-antd-template-forked-q9o4b
