### ISSUE TITLE
The Steps bar under ie11 shows NAN

### ISSUE THREAD

**Issue by wuyi1995** [vueComponent/ant-design-vue#3813]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
ie11

### Reproduction link
[https://1x.antdv.com/components/steps-cn/](https://1x.antdv.com/components/steps-cn/)

### Steps to reproduce
ie11下官网链接打不开（https://1x.antdv.com/components/steps-cn/）打开估计就能看到Steps的bug,步骤条正常是1——2——3——4，IE11下是NAN——NAN——NAN——NAN
![123](https://user-images.githubusercontent.com/75347280/111440409-44b0e600-8741-11eb-87e9-5ce04043b267.png)

### What is expected?
Steps步骤正常显示

### What is actually happening?
Steps步骤在ie11下显示不正常

**Comment by John60676** [comment]
![image](https://user-images.githubusercontent.com/21698973/111559107-e29cc300-87ca-11eb-9b75-39f64f211026.png)

没有重现出来

**Comment by wuyi1995** [comment]
https://codesandbox.io/s/vue-antd-template-forked-z27c9?file=/src/main.js
![image](https://user-images.githubusercontent.com/75347280/111719160-4a6c1000-8896-11eb-879b-413566112dd5.png)

**Comment by wuyi1995** [comment]
https://codesandbox.io/s/vue-antd-template-forked-z27c9?file=/package.json
![image](https://user-images.githubusercontent.com/75347280/111721100-31fdf480-889a-11eb-93ab-a726327b44b9.png)

**Comment by John60676** [comment]
应该是你自己项目的设置问题

你自己 clone 下来测试一下吧： https://github.com/John60676/vue-antdv-v1
