### ISSUE TITLE
a-input-number 组件会重复输入数字

### ISSUE THREAD

**Issue by Asuancaiyu** [vueComponent/ant-design-vue#3814]
- ‘a-input-number’ 组件问题：

输入1234 则会出现 12344；
输入123456 则会出现 123445566；

- 该问题出现在版本v1.7.3 ‘a-input-number’ 组件的 ‘格式化展示’ 示例中，下方为官网示例代码：

`<template>
  <div>
    <a-input-number
      :default-value="1000"
      :formatter="value => `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')"
      :parser="value => value.replace(/\$\s?|(,*)/g, '')"
      @change="onChange"
    />
  </div>
</template>
<script>
export default {
  methods: {
    onChange(value) {
      console.log('changed', value);
    },
  },
};
</script>
`

**Comment by ajuner** [comment]
确认一下是微软输入法+谷歌浏览器才会出现的吗

**Comment by Asuancaiyu** [comment]
> 确认一下是微软输入法+谷歌浏览器才会出现的吗

是的，我用的微软输入法+谷歌浏览器，后面我尝试使用手心输入法则没有该问题。
最后我使用 ant v.2.x 的 ‘a-input-number’则没有输入法的问题。

**Comment by ajuner** [comment]
好的  会尽快修复
