### ISSUE TITLE
The Steps Error affects operation

### ISSUE THREAD

**Issue by gongjianh** [vueComponent/ant-design-vue#3815]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
windows,Chrome 89.0.4389.82, vue 3.0.6

### Reproduction link
[https://codesandbox.io/s/cool-tdd-hr0b1?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/cool-tdd-hr0b1?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
use Steps

### What is expected?
repair

### What is actually happening?
Uncaught (in promise) TypeError: Cannot assign to read only property 'calcStepOffsetWidth' of object '#'

**Comment by gongjianh** [comment]
https://codesandbox.io/s/cool-tdd-hr0b1?fontsize=14&hidenavigation=1&theme=dark

**Comment by tangjinzhou** [comment]
update vue to 3.0.7
