### ISSUE TITLE
v-model.trim doesn't work

### ISSUE THREAD

**Issue by Huanghaiting** [vueComponent/ant-design-vue#3816]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
browser version：版本 89.0.4389.82（正式版本） （64 位）

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
<a-input v-model.trim="formInline.id" placeholder="请输入编号" allowClear />
无法自动过滤用户输入的首尾空白字符

### What is expected?
自动过滤用户输入的首尾空白字符

### What is actually happening?
无法自动过滤用户输入的首尾空白字符

**Comment by Huanghaiting** [comment]
https://codesandbox.io/s/snowy-rain-5wxri?file=/src/components/HelloWorld.vue

**Comment by Huanghaiting** [comment]
https://codesandbox.io/s/snowy-rain-5wxri?file=/src/components/HelloWorld.vue

**Comment by John60676** [comment]
绑定 `v-model` 不是 这样写 `v-model.trim="number"`，而是要这样写 `v-model:value.trim="number"`

请仔细看文档： https://2x.antdv.com/components/input#API

**Comment by Huanghaiting** [comment]
![image](https://user-images.githubusercontent.com/17808807/111593341-ccabf400-8804-11eb-8589-b78ba3d8f31a.png)
for vue2 怎么书写？

**Comment by Huanghaiting** [comment]
大佬再问一个~for vue2 的写法是？
![image](https://user-images.githubusercontent.com/17808807/111593651-20b6d880-8805-11eb-895f-fefa763a29e9.png)

**Comment by Huanghaiting** [comment]
> 大佬再问一个~for vue2 的写法是？
> ![image](https://user-images.githubusercontent.com/17808807/111593651-20b6d880-8805-11eb-895f-fefa763a29e9.png)

@John60676

**Comment by John60676** [comment]
vue2 的写法是 `v-model="number"`

注意：vue2 的 `v-model` 不支持在**自定义组件**里面使用**修饰符**，你可以自己使用其他方式去实现 `trim`

详细讨论可以参考 https://github.com/vuejs/vue/issues/3666

**Comment by John60676** [comment]
好像是有点问题，这个我还要再看一下

**Comment by Huanghaiting** [comment]
大佬，在<a-form-model></a-form-model>内使用是可以的，单独使用不可以

**Comment by Huanghaiting** [comment]
大佬，在表单内使用是可以的

**Comment by yinlei1126** [comment]
> 好像是有点问题，这个我还要再看一下

可以改成如 原生一样吗 v-model.trim="", 为什么一定要加一个 v-model:value, 这样感觉不理想
element ui 里的 el-input 组件，是支持 v-model 方式的，如 原生一样，希望能调整下

**Comment by John60676** [comment]
> > 好像是有点问题，这个我还要再看一下
> 
> 可以改成如 原生一样吗 v-model="", v-model.trim 为什么一定要加一个 v-model:value, 这样感觉不理想
> element ui 里的 el-input 组件，是支持 v-model 方式的，如 原生一样，希望能调整下

1.x 版本不用加 `:value` 啊

**Comment by yinlei1126** [comment]
> > > 好像是有点问题，这个我还要再看一下
> > 
> > 
> > 可以改成如 原生一样吗 v-model="", v-model.trim 为什么一定要加一个 v-model:value, 这样感觉不理想
> > element ui 里的 el-input 组件，是支持 v-model 方式的，如 原生一样，希望能调整下
> 
> 1.x 版本不用加 `:value` 啊

大佬：2.x 版本为什么要加这个呀

**Comment by yajore** [comment]
> > > > 好像是有点问题，这个我还要再看一下
> > > 
> > > 
> > > 可以改成如 原生一样吗 v-model="", v-model.trim 为什么一定要加一个 v-model:value, 这样感觉不理想
> > > element ui 里的 el-input 组件，是支持 v-model 方式的，如 原生一样，希望能调整下
> > 
> > 
> > 1.x 版本不用加 `:value` 啊
> 
> 大佬：2.x 版本为什么要加这个呀

2.x基于vue3的啊，这是vue3的变化导致的啊，先把vue3了解下

**Comment by John60676** [comment]
下个版本修复
