### ISSUE TITLE
MonthPicker component correction

### ISSUE THREAD

**Issue by xkim1994** [vueComponent/ant-design-vue#3818]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
开始以为直接引入MonthPicker组件就可以使用没想到在DatePicker的下一级，希望即使纠正更新文档

### What does the proposed API look like?
Vue.component(MonthPicker.name, MonthPicker)

**Comment by tangjinzhou** [comment]
推荐直接使用  Vue.use(DatePicker)  会自动为你注册子组件
