### ISSUE TITLE
card jsx scopedSlots.default is invalid

### ISSUE THREAD

**Issue by codesyofo** [vueComponent/ant-design-vue#3823]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
Vue 2+. JSX 

### Steps to reproduce
```
 const scopedSlots = {
    cover: () => <header>header</header>,
    default: () => <div>content</div>
  }
  return <a-card scopedSlots={scopedSlots} />
```

### What is expected?
修复哈

### What is actually happening?
源码用的是 `$slots['default']` 没有输出内容，改用 `$scopedSlots.default()` 能输出内容

![image](https://user-images.githubusercontent.com/49975575/111751535-97200d00-88cf-11eb-8017-2d879f0fc88b.png)

打印 `card` 返回的 `$slots` `$scopedSlots`

![image](https://user-images.githubusercontent.com/49975575/111752056-2decc980-88d0-11eb-841b-c715bdb6f717.png)

**Comment by tangjinzhou** [comment]
vue 具体版本信息提供下

**Comment by codesyofo** [comment]
> vue 具体版本信息提供下

`"vue": "^2.6.12"`

**Comment by codesyofo** [comment]
> vue 具体版本信息提供下

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-km69c?fontsize=14&hidenavigation=1&theme=dark)

**Comment by zkwolf** [comment]
default 这样吧， 大多数组件对default都没做特殊处理
```
<a-card {...scoped}>
  <div>default</div>
</a-card>
```
