### ISSUE TITLE
disabled option can be selected

### ISSUE THREAD

**Issue by vibeme** [vueComponent/ant-design-vue#3824]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
Windows10，FireFox87，Vue2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-framework-766jm?file=/src/components/HelloWorld.vue)

### Steps to reproduce
Input keyWords to search  disabled option in selector and blur the item.
在选择框中搜索被禁用的选项，并失焦，即可复现

### What is expected?
disabled option can not be selected

### What is actually happening?
disabled option be selected

---
目前只在对话框中复现
only reappeared in dialog

**Comment by tangjinzhou** [comment]
确认下 版本号  我看 2.x 是没有问题的

**Comment by vibeme** [comment]
> 
> 
> 确认下 版本号 我看 2.x 是没有问题的

抱歉，是1.7.4版本，在上面的codesandbox链接里面可见版本号

**Comment by zkwolf** [comment]
下个版本修复
