### ISSUE TITLE
using v-for and the a-form or form-model component leaves the fields with very slow loading

### ISSUE THREAD

**Issue by lbarussi** [vueComponent/ant-design-vue#3831]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
development, chrome, vue 2

### Reproduction link
[https://www.antdv.com/components/form-model/#components-form-model-demo-dynamic-form-item](https://www.antdv.com/components/form-model/#components-form-model-demo-dynamic-form-item)

### Steps to reproduce
I'm having serious problems with the ev-for-model-item-form (example considerably the same as in the documentation [as available link.])

In the ** Dynamic form item ** section, if you add multiple entries, you will begin to notice a certain slowness when typing in the fields.

In my development case, I have 21 fields, 11 of which are connected to a v-for (a-row v-for [....] [fields ...]

At first, I thought it could be some @change that would be running unnecessarily, but after testing it in its own documentation, I realized this and decided to come here to open this issue.

I'm a big fan of your work, but it made me a little confused.

### What is expected?
improved performance of various inputs with the form component (if necessary)

### What is actually happening?
I'm having serious problems with the ev-for-model-item-form (example considerably the same as in the documentation [as available link.])

In the ** Dynamic form item ** section, if you add multiple entries, you will begin to notice a certain slowness when typing in the fields.

In my development case, I have 21 fields, 11 of which are connected to a v-for (a-row v-for [....] [fields ...]

At first, I thought it could be some @change that would be running unnecessarily, but after testing it in its own documentation, I realized this and decided to come here to open this issue.

Example reference: https://www.antdv.com/components/form-model/#Dynamic-Form-Item

navigate to the Dynamic-Form-Item section
Click on the ADD FIELD button several times, hold down any key and see how slow it is.

Link with example:
[https://streamable.com/9yrvi3](https://streamable.com/bfsz7u)
[https://streamable.com/bfsz7u](https://streamable.com/bfsz7u)

**Comment by lbarussi** [comment]
Link with example: 

[https://streamable.com/9yrvi3](url)

**Comment by jakubkoje** [comment]
Did you find any fix?

**Comment by jakubkoje** [comment]
I found out that when I split the fields into multiple columns/rows, it fixed my issue.

**Comment by lbarussi** [comment]
@jakubkoje  yea! I also discovered that
