### ISSUE TITLE
The showInkInFixed configuration in the anchor is invalid

### ISSUE THREAD

**Issue by Chloey61** [vueComponent/ant-design-vue#3832]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
mac11.2.3、谷歌89.0.4389.90、vue3

### Reproduction link
[https://2x.antdv.com/components/anchor-cn](https://2x.antdv.com/components/anchor-cn)

### Steps to reproduce
api文档中showInkInFixed（固定模式是否显示小圆点）

### What is expected?
showInkInFixed 为 false，展现条状

### What is actually happening?
showInkInFixed 为 false， 展现点状

---
vue2版本适应的ui框架里展示的都是点状，且都没有设置showInkInFixed；
vue3版本适应都ui框架里左侧展示的锚点是条状，而事例全是点状。

**Comment by John60676** [comment]
官方组件没有条状的锚点，文档右边 toc 显示的条状是我们自己写的样式。

`showInkInFixed`的作用是小圆点的显示与隐藏

**Comment by nabaonan** [comment]
> 官方组件没有条状的锚点，文档右边 toc 显示的条状是我们自己写的样式。
> 
> `showInkInFixed`的作用是小圆点的显示与隐藏

为什么设置隐藏和显示没有效果呢？始终是显示的

**Comment by John60676** [comment]
> > 官方组件没有条状的锚点，文档右边 toc 显示的条状是我们自己写的样式。
> > `showInkInFixed`的作用是小圆点的显示与隐藏
> 
> 为什么设置隐藏和显示没有效果呢？始终是显示的

如果遇到问题可以开个新的 issue，并且提供重现示例

**Comment by YY88Xu** [comment]
同问，vue3 版本 showInkInFixed false 不起作用
