### ISSUE TITLE
If <a-switch/>the outermost city wraps <a-row>, then the data bound to a-switch in two directions will not be changed in time

### ISSUE THREAD

**Issue by pengshengguang** [vueComponent/ant-design-vue#3833]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
vue3.0  antd2.x

### Reproduction link
[https://2x.antdv.com/components/grid-cn](https://2x.antdv.com/components/grid-cn)

### Steps to reproduce
<template>
<div v-for="(item, index) in data.choices">
<a-row>
<a-switch size="small" v-model:checked="item.ifAllowFillInBlanks" />
</a-row>
</div>
</template>
<script>
import { reactive, ref } from 'vue';
export default {
setup() {
const data = reactive({
"choices": [
{
"ifAllowFillInBlanks": false, //是否能填空
},
{
"ifAllowFillInBlanks": true,
}
]
})
return { data }
},
}
</script>

运行上诉代码

### What is expected?
当切换switch状态，ifAllowFillInBlanks 的状态要及时改变

### What is actually happening?
当切换switch状态，ifAllowFillInBlanks 的状态并无及时改变

**Comment by yunwuxin** [comment]
我也发现同样的问题了
