### ISSUE TITLE
The width of Affix in component Affix & Anchor

### ISSUE THREAD

**Issue by Sampwood** [vueComponent/ant-design-vue#3836]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
既然组件不支持随容器宽度变化自动变化，能不能不要在style中写入width，或者通过props能手动去修改这个width

### What does the proposed API look like?
Affix & Anchor中Affix 支持 手动设置width而不去自动计算。例如可以设置成width:100%，然后就可以自动适配父容器宽度。

**Comment by tangjinzhou** [comment]
没懂说的哪个组件
