### ISSUE TITLE
I hope antdv icon svg can supports svg-sprite

### ISSUE THREAD

**Issue by leiroc** [vueComponent/ant-design-vue#3837]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
When i use svg-icon im'not home inline html,so i hope supports svg-sprite

### What does the proposed API look like?
i have no idea

**Comment by tangjinzhou** [comment]
may be you can try some svg loader  like https://github.com/JetBrains/svg-sprite-loader
