### ISSUE TITLE
[BUG] `update:checked` on `a-checkbox` is called twice on value change

### ISSUE THREAD

**Issue by CarterLi** [vueComponent/ant-design-vue#3838]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
3.0.7

### Reproduction link
[http://example.com](http://example.com)

### Steps to reproduce
```
<a-checkbox :checked="false" @update:checked="test">test</a-checkbox>
```

```
test(value) {
  console.log(value)
}
```

### What is expected?
`test` should only be called once with value `true`

### What is actually happening?
`test` is called twice. Antdv passes an event object at the first time, which is not expected.

### Others

![image](https://user-images.githubusercontent.com/6134068/112104280-f5a5fd80-8be5-11eb-8f2a-c3f2ce77b9d1.png)

https://github.com/vueComponent/ant-design-vue/blob/next/components/vc-checkbox/src/Checkbox.jsx#L92

**Comment by zkwolf** [comment]
Will be fixed in next release.
