### ISSUE TITLE
Placeholder is not shown for select

### ISSUE THREAD

**Issue by oleksii-shaposhnikov** [vueComponent/ant-design-vue#3839]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-glitter-iidzj?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/jolly-glitter-iidzj?file=/src/App.vue

### What is expected?
A placeholder should be shown in select component

### What is actually happening?
Placeholder is hidden in select component

**Comment by ajuner** [comment]
use: ref(null)

**Comment by oleksii-shaposhnikov** [comment]
@ajuner do you think it's a good solution? What if I don't want to use null value in TS project in order to reduce the potential type errors?

**Comment by oleksii-shaposhnikov** [comment]
Also, it also doesn't work if I use something like this:


```
// setup function
...

const form = reactive({
 selectedId: '',
})
...

return {
 form
}
```

```
<!-- template -->

<el-select v-model:value="form.selectedId">
...
```

**Comment by wkcole** [comment]
non-stale

**Comment by Roto1707** [comment]
I'm looking for this but seems no solution yet

**Comment by Roto1707** [comment]
non-stale
