### ISSUE TITLE
Input组件的handleChange中‘this.$forceUpdate()’起什么作用？

### ISSUE THREAD

**Issue by Tan90Qian** [vueComponent/ant-design-vue#384]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在输入框的input事件处理函数中，有`this.$forceUpdate()`这样一行代码，是在外部传入value（或直接使用双向绑定）时调用的，但是似乎移除这行代码后，功能依然正常。而在编写单元测试时，这行代码会导致在使用setValue API强行触发输入框的input事件时，change.value事件的监听器收到一个空字符串引起测试失败。
这行代码是出于什么考虑而使用的？官方文档中的描述是`迫使 Vue 实例重新渲染。注意它仅仅影响实例本身和插入插槽内容的子组件，而不是所有子组件。`但props的变化本来就会引起重新渲染，似乎是多此一举？

### What does the proposed API look like?
```javascript
handleChange (e) {
// https://github.com/vueComponent/ant-design-vue/issues/92
if (isIE && !isIE9 && this.stateValue === e.target.value) {
return
}
if (!hasProp(this, 'value')) {
this.stateValue = e.target.value
} else {
this.$forceUpdate()
}
if (!e.target.composing) {
this.$emit('change.value', e.target.value)
}
this.$emit('change', e)
this.$emit('input', e)
},
```

```javascript
input.setValue('test');
input.setValue('test2');

expect(wrapper.emitted()['change.value']).toBeTruthy();
expect(wrapper.emitted()['change.value'].length).toBe(2);
expect(wrapper.emitted()['change.value'][0]).toEqual(['test']);  // Expected value to equal:  ["test"]  Received:   [""]
```

**Comment by tangjinzhou** [comment]
为了保证input的值和传递的value一致。
有这样一种情况: 
<Input value="should not change" />
input传递了一个固定的value值，当在input中进行输入时触发handleChange，但是传递的value并没有变化，此时input内的值就不应该变化，如果不使用forceUpdate，组件就不会重新渲染，那么input的值就不能保证和传递的值一致。

**Comment by Tan90Qian** [comment]
那可以不可以用`this.$nextTick(this.$forceUpdate)`来延后强制刷新的时间点？这样数据可以保证不变 测试也可以通过

**Comment by tangjinzhou** [comment]
或许你应该做的是调整测试代码。
即便组件内部调整了，你的测试代码也只是侥幸为了通过case而已。
