### ISSUE TITLE
Select component has scrollbar issue when wrapped by Spin component

### ISSUE THREAD

**Issue by Charbo23** [vueComponent/ant-design-vue#3840]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
Windows 10.0.19041.867    Chrome  89.0.4389.90  Vue 3.0.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serverless-frost-65qu3?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1.Wrap Select component in a Spin, the data for selecting must be  enough to cause overflow
2.Choose an option then make any other updates on the page (such as typing words in the input box)
3.Open the dropdown menu again, the scrollbar is missing, the dropdown cannot be scrolled also

### What is expected?
The dropdown menu can  be scrolled whenever it should be

### What is actually happening?
The dropdown menu cannot  be scrolled after other updates are made

---
There is a solution effective for now: add "v-if" directive on the parent node of the Select component, the expression can even be simply"true".

**Comment by guibwl** [comment]
我也有类似的问题，我的情况是，当 a-select-option > 8 且 < 11 条时，选中第一条以外的 a-select-option 会导致无法滚动。
