### ISSUE TITLE
When a-menu-item is placed in an external file, the mouse hover displays multiple highlights

### ISSUE THREAD

**Issue by lvlingjie** [vueComponent/ant-design-vue#3846]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
系统：macOS11.0.1，浏览器：chrome89.0.4389.90，vue：^3.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-chandrasekhar-uq59k?file=/src/components/HelloWorld.vue)

### Steps to reproduce
具体请看连接

### What is expected?
和官方demo一样正常显示

### What is actually happening?
hover的时候同级全部高亮，点击二级菜单的时候，同级所有二级菜单都会展开

**Comment by John60676** [comment]
Reference #3032
