### ISSUE TITLE
树形控件的 a-directory-tree 不能自定义icon？

### ISSUE THREAD

**Issue by Bourne115** [vueComponent/ant-design-vue#385]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.0-beta.0

### Environment
树形控件的 a-directory-tree 不能自定义icon？

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
树形控件的 a-directory-tree 不能自定义icon？

### What is expected?
树形控件的 a-directory-tree 不能自定义icon？

### What is actually happening?
树形控件的 a-directory-tree 不能自定义icon？

---
树形控件的 a-directory-tree 不能自定义icon？

**Comment by Bourne115** [comment]
树形控件的 a-directory-tree 不能自定义icon？

**Comment by tangjinzhou** [comment]
是

**Comment by dsonet** [comment]
antd 3.12支持了自定义icon. 这边同步后应该就可以了

**Comment by luyu1314** [comment]
怎么添加？ 3.12是哪来的版本号？

**Comment by tangjinzhou** [comment]
已经支持

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-dy58e
