### ISSUE TITLE
[Select] Use a-checkbox in dropdownRender, click on the label to automatically collapse

### ISSUE THREAD

**Issue by wkcole** [vueComponent/ant-design-vue#3850]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
Windows 10， Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-t4yl2?file=/src/App.vue)

### Steps to reproduce
<template>
<a-select defaultValue="lucy" style="width: 120px">
<div slot="dropdownRender" slot-scope="menu">
<a-checkbox @mousedown="e => e.preventDefault()">asdasdsd</a-checkbox>
</div>
<a-select-option value="jack">Jack</a-select-option>
<a-select-option value="lucy">Lucy</a-select-option>
</a-select>
</template>
<script>
export default {
data: () => ({ console: console }),
components: {
VNodes: {
functional: true,
render: (h, ctx) => ctx.props.vnodes
}
}
};
</script>

### What is expected?
点击checkbox后面的文字，不会收起下拉

### What is actually happening?
收起了

**Comment by John60676** [comment]
https://codesandbox.io/s/vue-antd-template-forked-9i2xv?file=/src/App.vue
