### ISSUE TITLE
formRef.value.resetFields()失效

### ISSUE THREAD

**Issue by hexueguo** [vueComponent/ant-design-vue#3851]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
vue3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/red-bush-hp6wz?file=/src/Header.vue)

### Steps to reproduce
https://codesandbox.io/s/red-bush-hp6wz?file=/src/Header.vue

### What is expected?
重置表单数据

### What is actually happening?
无效果

**Comment by hexueguo** [comment]
在官方例子中可以重置，但在实际环境中无法实现重置效果

**Comment by zkwolf** [comment]
你需要在a-form-item上绑定name的，比如这个例子https://2x.antdv.com/components/form-cn#components-form-demo-validation
