### ISSUE TITLE
https://codesandbox.io/s/exciting-hamilton-3t34g?file=/src/components/HelloWorld.vue

### ISSUE THREAD

**Issue by yinlei1126** [vueComponent/ant-design-vue#3852]
可以改成如 原生一样吗 v-model="", v-model.trim 为什么一定要加一个 v-model:value, 这样感觉不理想
element ui 里的 el-input 组件，是支持 v-model 方式的，如 原生一样，希望能调整下

**Comment by ajuner** [comment]
#3094
