### ISSUE TITLE
Load less error on demand, version 1.7.4

### ISSUE THREAD

**Issue by yudan215** [vueComponent/ant-design-vue#3858]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.12

### Environment
Win10,Chorme,nuxt2.0

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
plugins目录增加插件文件
aut-ui.js
```
import Vue from 'vue'
import Table from 'ant-design-vue/lib/table'; // 加载 JS
import Pagination from 'ant-design-vue/lib/pagination';
Vue.use(Table)
Vue.use(Pagination)

```
nuxt.config.js改为
```
css: [
'ant-design-vue/lib/table/style/index.css',
'ant-design-vue/lib/pagination/style/index.css',
],
build: {
/*
** You can extend webpack config here
*/
extend (config, ctx) {
config.module.rules.push(
{
test:/\.less/,
loader: 'less-loader', // compiles Less to CSS
options: {
modifyVars: {
'primary-color': '#00BD92',
},
javascriptEnabled: true,
},
}
)
}
}
```
在页面使用后出现报错

### What is expected?
不报错，正常修改主题色

### What is actually happening?
Module build faild
.icontfont-size-under-12px(10px);
Error evaluating function `unit`: the first argument to unit must be a number.

**Comment by tangjinzhou** [comment]
1.x just support less 4.x

**Comment by TimorCookie** [comment]
> 1.x just support less 4.x

"less": "^4.1.1",
"less-loader": "^7.3.0",
"ant-design-vue": "^1.7.4",

same issue

**Comment by zkwolf** [comment]
> > 1.x just support less 4.x
> 
> "less": "^4.1.1",
> "less-loader": "^7.3.0",
> "ant-design-vue": "^1.7.4",
> 
> same issue

down to less 3.x，the version supported above is a typo
