### ISSUE TITLE
I need more detailed documentation for Tabs API 'tabBarStyle'

### ISSUE THREAD

**Issue by SignDawn** [vueComponent/ant-design-vue#3859]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
it is an object , I don't know what we should use.

### What does the proposed API look like?
I need a example!

**Comment by zkwolf** [comment]
Same as the vue syntax like https://cn.vuejs.org/v2/guide/class-and-style.html#%E5%AF%B9%E8%B1%A1%E8%AF%AD%E6%B3%95-1
