### ISSUE TITLE
Can the cell corresponding to the table component be programmed in the callback mode?

### ISSUE THREAD

**Issue by yiptsangkin** [vueComponent/ant-design-vue#3860]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前我想通过table->components->body->cell去覆盖，但是想根据不同cell/column的属性覆盖不同的component，但是测试了下目前貌似cell没办法支持，是否可以考虑下增加下这个功能？

### What does the proposed API look like?
// 目前
components.body.cell = NewComponent

// 期望
components.body.cell = (column) => {
if (column.id === 1) {
return NewComponentA
} else {
return NewComponentB
}

}

**Comment by yiptsangkin** [comment]
目前尝试了通过在组件内部去获取slot里面的vnode，但是这种方式v-model的绑定比较混乱

**Comment by yiptsangkin** [comment]
cell如果传一个compoent的话，slotScoped 里面customerRender的record就会失效，是否有什么解决办法

**Comment by zkwolf** [comment]
建议还是写个复现看看你怎么用的
