### ISSUE TITLE
TreeSelect showCheckedStrategy=SHOW_ALL does not take effect

### ISSUE THREAD

**Issue by xingxinglail** [vueComponent/ant-design-vue#3861]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
MacOS 10.14.6  Chrome  89.0.4389.90  Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]( https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
<template>
<a-tree-select
v-model:value="value"
show-search
style="width: 100%"
:dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
placeholder="Please select"
allow-clear
tree-default-expand-all
:showCheckedStrategy="SHOW_ALL"
>
<a-tree-select-node key="0-1" value="parent 1" title="parent 1">
<a-tree-select-node key="0-1-1" value="parent 1-0" title="parent 1-0">
<a-tree-select-node key="random" value="leaf1" title="my leaf" />
<a-tree-select-node key="random1" value="leaf2" title="your leaf" />
</a-tree-select-node>
<a-tree-select-node key="random2" value="parent 1-1" title="parent 1-1">
<a-tree-select-node key="random3" value="sss">
<template #title><b style="color: #08c">sss</b></template>
</a-tree-select-node>
</a-tree-select-node>
</a-tree-select-node>
</a-tree-select>
<order-list />
</template>

<script lang="ts">
import { ref } from 'vue';
import { TreeSelect } from 'ant-design-vue';

export default {
setup () {
const value = ref<string>();

return {
value,
SHOW_ALL: TreeSelect.SHOW_ALL
};
}
};
</script>

### What is expected?
配置:showCheckedStrategy="SHOW_ALL" 后，回填的方式显示所有选中节点(包括父节点)

### What is actually happening?
回填只显示子节点

**Comment by zkwolf** [comment]
逻辑应该是没有问题的，父节点在半选的时候不显示
