### ISSUE TITLE
my icon can not work in page header component

### ISSUE THREAD

**Issue by bluemiaomiao** [vueComponent/ant-design-vue#3864]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
antd of vue 2.1.0
vue3
### Environment
Node 14.x

### Reproduction link
[https://2x.antdv.com/components/page-header-cn/#PageHeader-1-5-0-](https://2x.antdv.com/components/page-header-cn/#PageHeader-1-5-0-)

### Steps to reproduce
```
// AppHeader.vue
<a-page-header style="border: 1px solid rgb(235, 237, 240)" title="Title" sub-title="This is a subtitle"
@back="changeLeftMenuDisplayMode" back-icon="<AppstoreOutlined/>"/>
```

```
// main.js
import {PageHeader} from 'ant-design-vue'
import {AppstoreOutlined} from '@ant-design/icons-vue'

const app = createApp(App)
app.config.productionTip = false;
app.use(Button)
app.use(PageHeader)
app.use(store)
app.use(router)
app.component(AppstoreOutlined.name, AppstoreOutlined)

app.mount('#app')
```

### What is expected?
show page header icon
![image](https://user-images.githubusercontent.com/45991640/112628643-2009ec00-8e6e-11eb-8e81-edef0b4a631a.png)

### What is actually happening?
the icon display to text `<AppstoreOutlined/>`
![image](https://user-images.githubusercontent.com/45991640/112628497-f355d480-8e6d-11eb-87b0-b4a53c1b5095.png)

**Comment by zkwolf** [comment]
你这样用绑定的就是个字符串，可以用slot
```
<template #backIcon>
  <AppstoreOutlined />
</template>
```

**Comment by bluemiaomiao** [comment]
那么这说明官网文档对于这个地方是错误的。

**Comment by bluemiaomiao** [comment]
同样的效果在React中使用是可以的。

**Comment by sendya** [comment]
react 是 JSX，如果你用 JSX 写 vue 也可以这样

**Comment by sendya** [comment]
实在想用 prop 也可以把 template 的 prop 绑定写对，:back-icon="h(icon)"
