### ISSUE TITLE
How does the FormModel item set the width of the label?

### ISSUE THREAD

**Issue by Xing-WenKai** [vueComponent/ant-design-vue#3865]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有些表单项的label文字可能会过长，导致label与后面的表单项重叠，用户体验不好

### What does the proposed API look like?
希望可以使用label-width自定义lebel的宽度

**Comment by tangjinzhou** [comment]
style="width: 100px"
