### ISSUE TITLE
checkbox-group  渲染方向问题

### ISSUE THREAD

**Issue by winken168** [vueComponent/ant-design-vue#387]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在checkbox-group 的渲染方向默认是横向的，有没有纵向的渲染方式或属性，文档上没找到解决方案。
有没有计划加入属渲染方向的功能？

**Comment by tangjinzhou** [comment]
暂无该计划，可以自行使用css覆盖样式或使用checkbox自行组装
