### ISSUE TITLE
Select component will report an error when using route jump

### ISSUE THREAD

**Issue by SeigeC** [vueComponent/ant-design-vue#3870]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
vue3.0.9 vue-router-4.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/floral-currying-6vt4n?file=/src/App1.vue)

### Steps to reproduce
点击 go 跳转后不点击 Select 组件 back 可以正常跳转
点击 go 跳转后点击 Select 组件 back 不能正常跳转

### What is expected?
back 可以正常跳转

### What is actually happening?
back 不能正常跳转

**Comment by huihui14569** [comment]
我也碰到这样的问题,好坑啊

**Comment by tangjinzhou** [comment]
降级vue 到 3.0.7 等待 vue 修复

**Comment by tangjinzhou** [comment]
update vue to 3.0.10
