### ISSUE TITLE
When date-picker mode=year. disabledDate disabled, not selectable, not effective

### ISSUE THREAD

**Issue by sxl1996KKK** [vueComponent/ant-design-vue#3872]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
vue版本2.6.10

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
无法禁用

### What is expected?
可以支持年份时，禁用生效

### What is actually happening?
现在写了disabledDate，不生效

**Comment by sxl1996KKK** [comment]
https://codesandbox.io/s/vue-antd-template-forked-8sey8?file=/src/App.vue

**Comment by ajuner** [comment]
之后会重构datePicker组件，解决这个问题

**Comment by donley828** [comment]
@ajuner 重构会考虑 1.x 版本么？如果不考虑，我提针对这个问题对 1.x 提了一个pr #3988 ，烦请review一下，项目bug需要解决。

**Comment by huangche007** [comment]
@sxl1996KKK  Have you solve this problem？I have same problem，the `ant-design-vue` version is 2.1.2

**Comment by huangche007** [comment]
@ajuner  大佬打算这个bug在哪个版本能够解决，目前我使用的是`vue3`+`ant-design-vue 2.1.2`依然有这个问题
