### ISSUE TITLE
The vue-cli3.0 project has multiple entries configured, but there can only be one theme. How to configure one theme for each entry page?

### ISSUE THREAD

**Issue by zoushenglin** [vueComponent/ant-design-vue#3875]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
vue-cli3.0的项目，配置了多入口，但是主题只能是一份，如何配置每个入口页面一个主题啊

### What does the proposed API look like?
暂时没解决方案

**Comment by tangjinzhou** [comment]
入口处加载不同 less 文件
