### ISSUE TITLE
After the select component is clicked, it will report an error after being destroyed Cannot read property'removeEventListener' of null

### ISSUE THREAD

**Issue by wcldyx** [vueComponent/ant-design-vue#3878]
![error](https://user-images.githubusercontent.com/26700595/112862967-cf0f1900-9062-11eb-9481-ebb009860b1f.gif)
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
win10, chrome89

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vxe-table-3x-vue-26-wentiyanshi-forked-53qc5?file=/src/App.vue)

### Steps to reproduce
1: 先点开select 选择器
2:然后点 销毁 按钮（销毁组件后会报错）

### What is expected?
能正常销毁select 组件

### What is actually happening?
select 组件在被销毁后报错：Cannot read property 'removeEventListener' of null

---
经过反复测试，引起报错的位置在 ant-design-vue/es/vc-virtual-list/ScrollBar.js 里面，beforeUnmount 方法被调用了两次导致错误

**Comment by sendya** [comment]
降级到 vue3.0.7，等 vue 修复

**Comment by lihxhit** [comment]
vue 3.0.9好像还是有这个问题

**Comment by sendya** [comment]
> vue 3.0.9好像还是有这个问题

就是3.0.9出现的问题

**Comment by moetanahy** [comment]
I'm getting this problem as well in 3.0.9.  Does anyone have any solutions or know when this might be fixed?

**Comment by tangjinzhou** [comment]
update vue to 3.0.10
