### ISSUE TITLE
The number of words in the textarea text area is displayed in the lower right corner of the text area "inside" instead of the lower right corner of the text area "outside".

### ISSUE THREAD

**Issue by Stars-Star** [vueComponent/ant-design-vue#3880]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以解决多个文本域字数显示的排版问题

### What does the proposed API look like?
求助

**Comment by John60676** [comment]
设计是跟 antd 统一的 https://ant.design/components/input-cn/#components-input-demo-textarea-show-count，如果 antd 修改了，我们也会跟进的

如果你想在内部显示，可以考虑自己封装一下
