### ISSUE TITLE
How to use variable color when using notification to customize icon

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#3890]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
win10 64

### Reproduction link
[https://2x.antdv.com/components/notification-cn/](https://2x.antdv.com/components/notification-cn/)

### Steps to reproduce
``` javascript
var pointColor
this.$notification.open({
message: '提示',
description: 'tishi',
icon: <a-icon type="warning" style="color: red" />, // 这里是官网例子
btn: h => {
  return h(
    'a-button',
      {
        props: {
          type: 'primary',
          size: 'small',
        },
        on: {
          click: () => that.handleQa(rdata),
        },
      },
      '快速处理',
  );
},
 key: rdata.warnId,
 onClose: close,
});
```
// 上面它是可以的， 现在想根据一个变量来赋值不同的颜色
自己试过 fn(h)
``` javascript
icon: h => {
  return h(
    'a-icon',
      {
        props: {
          type: 'warning',
          style: '{color: that.colorArr[Number(rdata.warnRate)]}'
        }
      }
  )
},
```
想根据warnRate的不同去给a-icon赋值不同的颜色，但是这样子写法貌似有问题 不能实现
请问该如何写？

### What is expected?
可以正常根据变量使用不同颜色图标，甚至 如果我不使用<a-icon>, 使用 <img src="xxx.png"> 这种方式可以实现吗

### What is actually happening?
目前无法动态改变颜色

**Comment by sendya** [comment]
https://codesandbox.io/s/practical-microservice-uso73?file=/src/App.vue


```vue
this.$notification.open({
        message: "提示",
        description: "tishi",
        icon: (
          <a-icon
            type="warning"
            style={{ color: rdata.warnId === 1 ? "red" : "green" }}
          />
        ), // 这里是官网例子
        btn: (h) => {
          return h(
            "a-button",
            {
              props: {
                type: "primary",
                size: "small",
              },
              on: {
                click: () => that.handleQa(rdata),
              },
            },
            "快速处理"
          );
        },
        key: rdata.warnId,
        onClose: close,
      });
```

**Comment by hugselina2019** [comment]
> https://codesandbox.io/s/practical-microservice-uso73?file=/src/App.vue
> 
> ```
> this.$notification.open({
>         message: "提示",
>         description: "tishi",
>         icon: (
>           <a-icon
>             type="warning"
>             style={{ color: rdata.warnId === 1 ? "red" : "green" }}
>           />
>         ), // 这里是官网例子
>         btn: (h) => {
>           return h(
>             "a-button",
>             {
>               props: {
>                 type: "primary",
>                 size: "small",
>               },
>               on: {
>                 click: () => that.handleQa(rdata),
>               },
>             },
>             "快速处理"
>           );
>         },
>         key: rdata.warnId,
>         onClose: close,
>       });
> ```

好的 谢谢大佬， 上面是一个三元 如果我需要变换8种颜色的话 用 style = {{ color: nowColor }} 这种变量赋值是吧

**Comment by John60676** [comment]
是的
