### ISSUE TITLE
Menu Bug

### ISSUE THREAD

**Issue by mlongf** [vueComponent/ant-design-vue#3891]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
火狐，谷歌

### Reproduction link
[https://1x.antdv.com/components/layout-cn/](https://1x.antdv.com/components/layout-cn/)

### Steps to reproduce
递归菜单
菜单默认打开（layout-sider打开），选择菜单子节点
关闭菜单（layout-sider关闭），父级菜单没有高亮，这时候根本不知道哪一个菜单被选中了
接着
鼠标滑过被选中的菜单，父级菜单又出现了高亮

![截屏2021-04-02 下午5 06 34](https://user-images.githubusercontent.com/35618634/113401384-db360600-93d5-11eb-98a2-43f50d920ed4.png)
![截屏2021-04-02 下午5 06 42](https://user-images.githubusercontent.com/35618634/113401396-dec98d00-93d5-11eb-85fe-46cfa835d3fa.png)

### What is expected?
不管菜单是几级，只要选中了子菜单，那么菜单关闭的时候，父级菜单高亮。如果能够自定义颜色就完美了，谢谢

### What is actually happening?
漫长的等待优化

**Comment by mlongf** [comment]
这个问题就没人解决么

**Comment by tangjinzhou** [comment]
组件库的懒加载 + vue3 中的子节点都是按需render，导致父组件无法根据子组件的key，来判断当前key是否是“子节点”

如果去掉懒加载，数据量大的时候回卡顿

考虑重新设计key关联父子节点，如子节点key a-b，父节点的key 就是 a，这将是一个破坏性更新   😓

**Comment by mlongf** [comment]
@tangjinzhou 老师你好，看您的课程发现的这个问题，不知道有没有什么好的解决办法呢，这个菜单因为这个BUG，体验不太好啊

**Comment by tangjinzhou** [comment]
update to 2.2.0-beta.2
