### ISSUE TITLE
2.x use vite build Error cascader/index.d.ts:307:13 type error

### ISSUE THREAD

**Issue by nshusr** [vueComponent/ant-design-vue#3895]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
manjaro linux, chrome 89, "vue": "^3.0.5", "vite": "^2.1.5", "vue-tsc": "^0.0.15", "ant-design-vue": "^2.1.2",

### Steps to reproduce
npm init @vitejs/app my-vue-app -- --template vue-ts
npm i
npm i -S ant-design-vue@next
npm run build

> vue-tsc --noEmit && vite build

node_modules/.pnpm/ant-design-vue@2.1.2_8c46f6c1080be7f80954bdf18f02ae8b/node_modules/ant-design-vue/lib/cascader/index.d.ts:307:13 - error TS2411: Property 'disabled' of type 'boolean' is not assignable to string index type 'void | Element'.

307             disabled: boolean;
~~~~~~~~


Found 1 error.

ERROR  Command failed with exit code 2.

### What is expected?
packaged

### What is actually happening?
packaging error



        

<!-- generated by issue-helper. DO NOT REMOVE -->

**Comment by qwerty22121998** [comment]
I have the same issue and currently have no solution yet.

**Comment by qwerty22121998** [comment]
From line 305, We should change from
```ts
}[] | {
            [x: string]: void | JSX.Element;
            disabled: boolean;
        }[];
```
to 
```ts
}[] | {
            disabled: boolean;
        } & {
            [x: string]: void | JSX.Element;
        }[];
```

**Comment by nshusr** [comment]
> From line 305, We should change from
> 
> ```ts
> }[] | {
>             [x: string]: void | JSX.Element;
>             disabled: boolean;
>         }[];
> ```
> 
> to
> 
> ```ts
> }[] | {
>             disabled: boolean;
>         } & {
>             [x: string]: void | JSX.Element;
>         }[];
> ```

Effective, is it convenient for you to submit a PR?

**Comment by qwerty22121998** [comment]
@nshusr alternative solution is set compilerOptions.skipLibCheck to true

**Comment by wflixu** [comment]
I have same problem .
reproduce  repo: https://github.com/wflixu/today-pc/tree/vue-ts

**Comment by nshusr** [comment]
> @nshusr alternative solution is set compilerOptions.skipLibCheck to true

@wflixu use that config in tsconfig.json but this just ignores the problem

**Comment by John60676** [comment]
Fix in the next version
