### ISSUE TITLE
Can't run tests

### ISSUE THREAD

**Issue by alexey2baranov** [vueComponent/ant-design-vue#3897]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
manjaro linux latest

### Reproduction link
[https://github.com/alexey2baranov/issue-test](https://github.com/alexey2baranov/issue-test)

### Steps to reproduce
git clone https://github.com/alexey2baranov/issue-test

npm i
npm test

### What is expected?
test runs

### What is actually happening?
orror on compilation

/home/alexey/issue-test/node_modules/lodash-es/isPlainObject.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import baseGetTag from './_baseGetTag.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module

at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
at Object.<anonymous> (node_modules/ant-design-vue/lib/_util/props-util/index.js:27:45)

---
I have added `lodash-es` to transformIgnorePatterns into jest.config.js

**Comment by tangjinzhou** [comment]
So sorry,  If you change some config file.   You have to  try resolve it by youself.

**Comment by alexey2baranov** [comment]
What?

**Comment by alexey2baranov** [comment]
Did you try to do this ?
