### ISSUE TITLE
1.x Add missing update:prop events

### ISSUE THREAD

**Issue by viruscamp** [vueComponent/ant-design-vue#3898]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

I will send pull requests later.
  
### What problem does this feature solve?
For 1.x version, Add missing update:prop events for components, to use `:prop.sync="p"`.
针对 1.x 版，补上各个组件 缺少的事件 update:prop 以便使用  `:prop.sync="p"` 语法。

| TODO    | Component            | props                          | events                               | 待增加 to add                                                |
|-----------|---------------|-----------------------------|------------------------------------|----------------------------------------------------------|
| []      | auto-complete | open                        | dropdownVisibleChange              |                                                      |
| []      | select        | open                        | dropdownVisibleChange              |                                                      |
| []      | cascader      | popupVisible                | popupVisibleChange                 |                                                      |
| []      | card          | activeTabKey                | tabChange                          |                                                      |
| []      | date-picker   | open                        | openChange                         |                                                      |
|         |               |                             |                                    |                                                      |
| [] 未定  | drawer        | visible                     | afterVisibleChange                 |                                                      |
| [] 未定  | carousel      |                             | afterChange <br/> beforeChange           | 属性 activeSlideNumber<br/>事件 update:activeSlideNumber |
| [] 未定  | transfer      | selectedKeys<br/>targetKeys | selectChange<br/>change            |                                                      |
|         |               |                             |                                    |                                                      |
| v-model | dropdown      | visible                     | visibleChange                      |                                                      |
| v-model | popconfirm    | visible                     | visibleChange                      |                                                      |
| v-model | tooltip       | visible                     | visibleChange                      |                                                      |
| 已有      | time-picker   | open                        | openChange<br/>update:open         |                                                      |
| 已有      | menu          | openKeys                    | openChange<br/>update:openKeys     |                                                      |
| 已有      | pagination    | pageSize                    | showSizeChange<br/>update:pageSize |

**Comment by viruscamp** [comment]
前5个，应该很容易加。  
3个未定的，需要多考虑怎么做。  
后面的都是已有的， 还有属性和事件已经是 v-model 的。

**Comment by viruscamp** [comment]
关于的文档编写。 考虑同一为 属性上写 visible(.sync) value(v-model) 。删除解释 .sync 用法与关联事件的说明。  
如果只有一个 update:visible 和 v-model 关联的事件， 则不写在事件表中。  
如果有为兼容考虑保留的同功能事件，事件表同一格中写出，同样不解释 .sync 用法与关联属性。 如:
|visibleChange<br>update:visible|

**Comment by tangjinzhou** [comment]
这几个组件的  open visible  并不是很常用，很少场景需要控制 open visible

是否有必要支持这类改动

**Comment by viruscamp** [comment]
我希望能保证一种统一性。
time-picker 已经加了，其他几个没有道理不加啊。
auto-complete  select cascader date-picker 以及 time-picker 的 popupVisible open 和对应事件，很明显是同一个东西。
命名时最好就能保持一致。 但兼容性考虑让我不好改名字。
而对应的 update:prop 事件其实已经有了，仅仅是事件名字不同而已。

**Comment by viruscamp** [comment]
我希望能保证一种统一性。
time-picker 已经加了，其他几个没有道理不加啊。
auto-complete  select cascader date-picker 以及 time-picker 的 popupVisible open 和对应事件，很明显是同一个东西。
命名时最好就能保持一致。 但兼容性考虑让我不好改名字。
而对应的 update:prop 事件其实已经有了，仅仅是事件名字不同而已。

**Comment by viruscamp** [comment]
类似的属性以及对应事件命名，2.x 最好能统一，趁现在改代价小。
