### ISSUE TITLE
Form cannot verify nested data

### ISSUE THREAD

**Issue by huangqian0310** [vueComponent/ant-design-vue#3901]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
windows10，google v87.0.4280.141，vue 3.0.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-volhard-2foy6?file=/src/App.vue)

### Steps to reproduce
点击选择框 选择值

### What is expected?
校验通过

### What is actually happening?
校验失败

---
是否是bug，如果是操作方式有误是否在文档更新正确使用方式

**Comment by zkwolf** [comment]
https://codesandbox.io/s/crazy-lalande-87cyf?file=/src/App.vue 参考这个吧

**Comment by huangqian0310** [comment]
好的，谢谢
