### ISSUE TITLE
how to fix ''Warning: [antdv: DatePicker] `value` provides invalidate moment time. If you want to set empty value, use `null` instead.''

### ISSUE THREAD

**Issue by Huanghaiting** [vueComponent/ant-design-vue#3902]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
browser version：版本 89.0.4389.82（正式版本） （64 位） vue2

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
筛选时间就出现了，请问如何修复？

### What is expected?
vue2.0 筛选时间就出现了，请问如何修复？

### What is actually happening?
''Warning: [antdv: DatePicker] `value` provides invalidate moment time. If you want to set empty value, use `null` instead.''

**Comment by ajuner** [comment]
我试了下没有警告  能提供个复现嘛

**Comment by Huanghaiting** [comment]
https://codesandbox.io/s/vue-antd-template-forked-ohv9g?file=/src/App.vue
![image](https://user-images.githubusercontent.com/17808807/113800337-58bc9600-9789-11eb-99ab-ea5dcc2761b9.png)
@ajuner 大佬帮我看看~

**Comment by Huanghaiting** [comment]
是我还没深刻理解呢，谢谢大佬了~我关闭一下
