### ISSUE TITLE
vite message error

### ISSUE THREAD

**Issue by transtone** [vueComponent/ant-design-vue#3904]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue3, vite

### Reproduction link
[https://github.com/transtone/vben-admin-thin-next/blob/main/src/App.vue#L11](https://github.com/transtone/vben-admin-thin-next/blob/main/src/App.vue#L11)

### Steps to reproduce
只要引入 message 就报错

### What is expected?
正常使用message

### What is actually happening?
```js
Uncaught ReferenceError: InfoCircleFilled_default is not defined
at Object.default (InfoCircleFilled.js:1)
at index.js:50
```

现象和这个类似： https://github.com/vueComponent/ant-design-vue/issues/3570

**Comment by transtone** [comment]
现在是莫名奇妙因 alert 报错了，出错的是另外一个icon：
```js
CloseCircleFilled.js:1 Uncaught ReferenceError: CloseCircleFilled_default is not defined
    at Object.default (CloseCircleFilled.js:1)
    at index.js:37
```

**Comment by hoozi** [comment]
> 现在是莫名奇妙因 alert 报错了，出错的是另外一个icon：
> 
> ```js
> CloseCircleFilled.js:1 Uncaught ReferenceError: CloseCircleFilled_default is not defined
>     at Object.default (CloseCircleFilled.js:1)
>     at index.js:37
> ```

同样的问题，请问解决了吗
