### ISSUE TITLE
The Cascader component  has an  error  like "TS2411:..."  when I run "npm run build" 

### ISSUE THREAD

**Issue by wflixu** [vueComponent/ant-design-vue#3905]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
os:macos11.2.3;vue :3.0.5;vite:2.1.5;TypeScript:4.1.3

### Reproduction link
[https://github.com/wflixu/today-pc/tree/vue-ts](https://github.com/wflixu/today-pc/tree/vue-ts)

### Steps to reproduce
1. git clone the repo from  'https://github.com/wflixu/today-pc/tree/vue-ts'
2. run "npm i "  in the terminal base the project directory
3. run  "npm run build "

### What is expected?
I can build the App when run "npm run build"

### What is actually happening?
The program crashed

---
I think this is a TypeScript type error. I'm actually using version 2.1.2.

**Comment by ajuner** [comment]
This problem has nothing to do with `ant-design-vue`, and there is no dependency package of the project in the link given, but I personally recommend you to double check whether the typescript type is wrong, hope it can help you.

**Comment by John60676** [comment]
Duplicate of #3895

**Comment by wflixu** [comment]
> This problem has nothing to do with `ant-design-vue`, and there is no dependency package of the project in the link given, but I personally recommend you to double check whether the typescript type is wrong, hope it can help you.

I'm sorry I forgot to save the dependency to package.json, but the problem is real, I just updated the repo and the problem is still there
