### ISSUE TITLE
table expandedRowRender and rowSelection exist at the same time, only the 0th can be checked, no matter how many checkboxes are checked, the console returns the 0th index

### ISSUE THREAD

**Issue by Newgar** [vueComponent/ant-design-vue#3909]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
Windows NT 10.0; Win64; x64 | Chrome/89.0.4389.114| vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-rgb-x8r2p?file=/src/App.vue)

### Steps to reproduce
直接点多选框就知道了，但是全选和全不选不影响

### What is expected?
当存在嵌套表格时，table的复选框能正确的显示选中行的样式并返回正确的值,我看@tangjinzhou在[#1518](https://github.com/vueComponent/ant-design-vue/issues/1518)里贴过运行正常的图，请问下 能贴下代码和antdv版本号么

### What is actually happening?
当存在嵌套表格时，table 的复选框只会选中第0行，并不停返回第0行的值

**Comment by John60676** [comment]
`rowKey` 使用得不对，应该是表格行 `key` 的取值。

参考：
https://codesandbox.io/s/eager-lehmann-nqf53?file=/src/App.vue:134-148

**Comment by Newgar** [comment]
大佬 我试了下,感觉问题好像出现在rowkey是字符串还是数字上，由于业务需要，刷新table是需要清除选中状态，所以必须用自定义rowkey，在每次刷新时给他们加上一个randomKey，但是这个自定义的rowkey貌似 是字符串时就会出现无法勾选的问题，是数字时就不会，详情见
https://codesandbox.io/s/stupefied-rgb-x8r2p?file=/src/App.vue




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vueComponent/ant-design-vue] table expandedRowRender and rowSelection exist at the same time, only the 0th can be checked, no matter how many checkboxes are checked, the console returns the 0th index (#3909)





 
rowKey 使用得不对，应该是表格行 key 的取值。
 
参考：
 https://codesandbox.io/s/eager-lehmann-nqf53?file=/src/App.vue:134-148

**Comment by John60676** [comment]
不要脱离文档去使用，否则会出现很多意料之外的问题。`rowKey` 请遵循[文档](https://www.antdv.com/components/table-cn/#%E6%B3%A8%E6%84%8F)说明去使用 

参考：https://codesandbox.io/s/eager-lehmann-nqf53?file=/src/App.vue

**Comment by Newgar** [comment]
是我没看仔细，还有个selectedRowKeys 属性，感谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月8日(星期四) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vueComponent/ant-design-vue] table expandedRowRender and rowSelection exist at the same time, only the 0th can be checked, no matter how many checkboxes are checked, the console returns the 0th index (#3909)





 
不要脱离文档去使用，否则会出现很多意料之外的问题。rowKey 请遵循文档说明去使用
 
参考：https://codesandbox.io/s/eager-lehmann-nqf53?file=/src/App.vue
