### ISSUE TITLE
[BUG] Select component is not working properly in production build

### ISSUE THREAD

**Issue by Oleksii14** [vueComponent/ant-design-vue#3910]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
-

### Reproduction link
[https://github.com/Oleksii14/ant-design-select-bug](https://github.com/Oleksii14/ant-design-select-bug)

### Steps to reproduce
Clone the repo
`yarn build`
`npm install http-server -g`
`http-server ./dist`

Then take a look at the select component in production

### What is expected?
Select should work the same as in development build

### What is actually happening?
The select component does not display labels for select options and is behaving strangely in general

**Comment by Oleksii14** [comment]
By the way, the version I use is 2.1.2, not 2.1.1 as selected here

**Comment by John60676** [comment]
Refer to the following code

```ts
// main.ts

import { createApp } from 'vue'
import App from './App.vue'
import { Select } from 'ant-design-vue';

const app = createApp(App)
app.use(Select).mount('#app')
```

**Comment by Oleksii14** [comment]
@John60676  Shouldn’t we use ‘app.component’ to register it? Is that documented anywhere?

**Comment by Oleksii14** [comment]
@John60676 your code example with `use` fixed this issue. Can someone add this to the documentation?

**Comment by John60676** [comment]
see also: [Import ant-design-vue](https://2x.antdv.com/docs/vue/getting-started)
