### ISSUE TITLE
Calendar component, date click has no effect

### ISSUE THREAD

**Issue by var-zhangbao** [vueComponent/ant-design-vue#3914]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
vite2.0 vue3.0 ts tsx语法

### Reproduction link
[https://2x.antdv.com/components/calendar-cn](https://2x.antdv.com/components/calendar-cn)

### Steps to reproduce
在Vue3版本下，使用tsx 语法 引用Calendar组件，点击日期没有选中的效果。

import { defineComponent, onMounted, ref } from 'vue';
import { Moment } from 'moment';
// import { Calendar } from 'ant-design-vue/es';
import '../style/home.scss';
export default defineComponent({
components: {
// Calendar
},
setup() {
const value = ref<Moment>();
console.log(value)
const getListData = (value: any)=> {
// console.log(value.current.date(), '222')
let listData
switch (value.current.date()) {
case 8:
listData = [
{ type: 'warning', content: '1.' },
{ type: 'success', content: '2' },
];
break;
case 10:
listData = [
{ type: 'warning', content: '3' },
{ type: 'success', content: '4' },
{ type: 'error', content: '5' },
];
break;
case 15:
listData = [
{ type: 'warning', content: 'This is warning event' },
{ type: 'success', content: 'This is very long usual event。。....' },
{ type: 'error', content: 'This is error event 1.' },
{ type: 'error', content: 'This is error event 2.' },
{ type: 'error', content: 'This is error event 3.' },
{ type: 'error', content: 'This is error event 4.' },
];
break;
default:
break;
}
return listData || [];
}
const getMonthData = (value: Moment) => {
if (value.month() === 8) {
return 1394
}
}
const onPanelChange = (value: Moment) => {
console.log(value)
console.log(111)
}
onMounted(() => {
})
return () => (
<>
<div class="home">
<a-row>
<a-col span={16}>
<a-card>
<a-calendar onSelect={onPanelChange} value={value.value} v-slots={{dateCellRender:(value:any) => <ul class="events">
{getListData(value).map(item => (
<li>
<a-badge status={item.type} text={item.content}></a-badge>
</li>
))}
</ul>}}></a-calendar>
</a-card>
</a-col>
<a-col span={6} offset={2}>右边</a-col>
</a-row>
</div>
</>
)
}
})

### What is expected?
实现官方例子的效果

### What is actually happening?
实际上并没有选中的效果

**Comment by John60676** [comment]
```tsx
import { defineComponent, ref } from 'vue';
import { Calendar } from 'ant-design-vue';

export default defineComponent({
  setup() {
    const value = ref();
    return () => <Calendar v-model={[value.value, 'value']} />;
  },
});

```
