### ISSUE TITLE
Form in class component not work

### ISSUE THREAD

**Issue by zhdwwf** [vueComponent/ant-design-vue#392]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.5

### Environment
windows 10 chrome 71 Vue 2.5.21

### Reproduction link
[https://github.com/zhdwwf/adv-ts-demo](https://github.com/zhdwwf/adv-ts-demo)

### Steps to reproduce
```
git clone https://github.com/zhdwwf/adv-ts-demo.git
npm install
npm run serve
visit http://localhost:8080
```
The input component can't type any words，like this.
![image](https://github.com/zhdwwf/megalo-demo/raw/master/123.gif)
![image](https://user-images.githubusercontent.com/564279/50955301-b652d100-14f3-11e9-9467-a3b03eb12cf9.png)

### What is expected?
The input work normally

### What is actually happening?
The input can't type any words

**Comment by tangjinzhou** [comment]
```
export default class App extends Vue {
  // public form: any = this.$form.createForm(this);
  created () {
    this.form = this.$form.createForm(this)
  }
  // or use data
  // data() {
  //   return {
  //     form:  this.$form.createForm(this),
  //   }
  // }
}
```
`this` is not `this`
I do not know why. I think it is a problem with [vue-class-component](https://github.com/vuejs/vue-class-component).
You can create a form collector using created or data.

**Comment by envision** [comment]
Experiencing this issue likewise.

**Comment by HenryYong** [comment]
> ```
> export default class App extends Vue {
>   // public form: any = this.$form.createForm(this);
>   created () {
>     this.form = this.$form.createForm(this)
>   }
>   // or use data
>   // data() {
>   //   return {
>   //     form:  this.$form.createForm(this),
>   //   }
>   // }
> }
> ```
> `this` is not `this`
> I do not know why. I think it is a problem with [vue-class-component](https://github.com/vuejs/vue-class-component).
> You can create a form collector using created or data.

Having exactly the same issue...and this solution works for me...

Meanwhile, if I am using `public form: any = this.$form.createForm(this);` and add following code in `v-decorator`, after I type in input, I find that value is replaced by what I last type
```
onValuesChange (props, value) {
    console.log('props', props)
     console.log('value', value)
}
```

Anyway, I hope this issue could be treated as a bug and be fixed soon... thx
