### ISSUE TITLE
3.0 for Easier to use

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#3922]
We plan to start the development of 3.0, the main purpose is to make the component library easier to use. The reconstruction is mainly from the following points:

0. open sources doc
1. Improve the ts type
2. Remove the defaultXxxx api and support more v-model directives
3. Use dayjs to reconstruct date-related components
4. More components support virtual scrolling
5. .....

If you have other suggestions, please leave a message

progress:  https://github.com/vueComponent/ant-design-vue/discussions/4575

try: https://next.antdv.com/components/overview/

**Comment by chad-bin** [comment]
1. 希望能最先加强表格，很多人选ui库最重要的是看表格，特别是pc端这种。默认支持拖拽/虚拟列表，这些常用的功能

**Comment by wsxe9988** [comment]
希望能加强表格  和vxe-table能配合使用

**Comment by TimRChen** [comment]
Expected:
1. intergrate sort table
2. tabs could define deep class style, now could not.
3. better table scroll height and scroll width calculate.

best wish.
to ant-design-vue developer.

**Comment by chad-bin** [comment]
2.按钮可以增加场景色，这个还是非常常用的

**Comment by cdll** [comment]
helping optimize the every components' exported name 🙏

**Comment by 862775170** [comment]
下拉选择框组件：显示的标签可以自定义(目前好像默认是tag)

**Comment by Adrek** [comment]
Use scrollbars in components (timepicker, sidebar, etc) like perfect-scrollbar.

**Comment by zhenzhenChange** [comment]
- `Button`（或者其它类似有 `type` 的组件）
  - 可否内置更多主色、辅色（如：`success`），丰富`type`？
  - 或者自定义颜色
  - 虽然咱可以通过`CSS`或者`Less`变量去修改，但还是觉得不够丰富

- 事件参数的类型
  - 比如`Menu`的`openChange`事件，类型明确为：`function(openKeys: string[])`，但实际上是：`(...payload: unknown[]) => unknown`
  - 当然，文档上的体现只是便于理解，但是还是希望能够明确这些类型

- 文档
  - 目前的文档是按组件的用途分类（比如：数据展示、反馈等等）
  - 希望能出一个选择，直接按组件字母顺序排序（其实很多时候知道文档有这么一个组件，即使翻了很多次，用了很多次，但是翻来翻去却又不知道在哪个位置了，如果是字母排序，我知道我要用的组件是什么字母开头，能秒定位）

- 希望能多多暴露各个组件的类型接口
- 希望能在文档中说明各个组件的样式变量（这里不得不提，`Vant`的文档中每个组件下就有该组件的各个样式变量说明，这样需要修改的时候其实会方便很多）

**Comment by dmyz** [comment]
@ant-design-vue/use

**Comment by chad-bin** [comment]
感觉还是需要开放文档的，现在已经使整个项目失去了社区的pr了。像element plus 已经即将超过去了。离不开社区pr

**Comment by chad-bin** [comment]
2.x 其实算失败的，真正算下来可能2kstart都不到。现在的star及社区活跃度90%是1.x版本的。被element-plus拉了很长了，还需加油

**Comment by dargoner** [comment]
表格大数据量的虚拟滚动，这个是最重要的

**Comment by tangjinzhou** [comment]
> 2.x 其实算失败的，真正算下来可能2kstar都不到。现在的star及社区活跃度90%是1.x版本的。被element-plus拉了很长了，还需加油

不 care，star 能当饭吃 ？   你去拉一下 element 和 plus 的重叠 star 有多少？  新增能有 1000 都逆天了   

有能力和意愿 PR 的，文档不是障碍。   如果没有文档，就PR不了的，大概率也是给我们增加 review 成本的，提高PR门槛，能帮助我们节省很多review 成本，不是针对谁，说的是概率事件。

**Comment by sendya** [comment]
@zhenzhenChange https://2x.antdv.com/components/overview/ 有提供搜索，可以直接输入搜索

**Comment by zhenzhenChange** [comment]
> @zhenzhenChange https://2x.antdv.com/components/overview/ 有提供搜索，可以直接输入搜索

是的，是有搜索功能，不过我 jio 得速度有点慢 😂

**Comment by van-chin** [comment]
表单：
1.form-item 增加hidden属于
2.表单验证增强

**Comment by jahnli** [comment]
1、表格功能增强
2、（选择器 表格）等内部滚动条美观

**Comment by ais-one** [comment]
1) If possible, just use vanilla JS instead of dayjs
2) design such that if vuejs moves to version 4, there is less breakage
3) make more use of html5 custom elements

**Comment by agileago** [comment]
### 在线主题切换
- 使用css变量来书写css,达到更容易的变换主题的方式，现在用了很多less function导致不太容易搞
- 表格增强，很难想象现在表格竟然不支持列宽拖拽，建议去看看 `vxe-table`
- 希望组件的逻辑和UI能分开，这样每个人甚至可以自定义组件，比如分成 `button.service.ts`、`button.component.tsx`、`button.component.css`,如果对button组件的ui不满意，我可以单独使用`button.service.ts`来进行自己的ui展示

**Comment by wkcole** [comment]
### 更方便的主题切换 +1

目前我们用的sass，为了换自定义主题色，还要加个less/less-loader就很离谱，CSS变量是个不错的方案

**Comment by skksksksks** [comment]
支持拖拽的Modal

**Comment by kerm1it** [comment]
表格的固定列使用 sticky 实现，这样整个表格渲染就不会分开，以后支持虚拟列表渲染也很方便。

**Comment by wensonsmith** [comment]
1. Table 支持虚拟滚动
2. Table 支持汇总
3. Table 列宽支持 flex 类似的设置
3. Form Item label 可以定宽，现在 labelCol 会随着页面宽度变化
4. 提供更多的 composition api, 展示和逻辑分离后，就可以自定义更多元素
5. 更好的键盘支持，毕竟管理系统用的多。 可以参考 Chakra UI
6. 动画优化，优化 Checkbox/ Radio 选中动画，还有 modal 显示等动画， antdv 的总感觉反应慢一拍，肉肉的

**Comment by wensonsmith** [comment]
同时建议新开一个 ant-design-vue-next 的 repo

**Comment by jahnli** [comment]
动画优化，antdv 总感觉卡卡的。。。

**Comment by wensonsmith** [comment]
@jahnli 

仔细对比了一下， 就是卡，确诊了

这不是 ant-design-vue 的问题， react 的也是卡

**Comment by jahnli** [comment]
@tangjinzhou  咨询大佬~

**Comment by itmarck** [comment]
Easier forms use.
Sass support maybe.

**Comment by itmarck** [comment]
Easier forms use.
Sass support maybe.
Custom scroll global.

**Comment by itmarck** [comment]
Easier forms use (remove v-decorator).
Sass support maybe or css variables.
Global styled scroll for pages, inside tables, etc.

**Comment by jiyingzhi** [comment]
希望和最新的 antd 对齐

**Comment by Archer03** [comment]
difficult to search props in docs now, because the demo codes is all folded at first. try to list props used simply below the introduction?

**Comment by Haiwar** [comment]
可不可以让css更兼容呢？我只想用某个组件但却让我安装 less ....

**Comment by dahei07** [comment]
Using canvas based rendering to improve performance。
某些场景下能否切换到canvas渲染呢？

**Comment by liliang1993** [comment]
> 高性能表格，可以体验 https://store.antdv.com/pro/preview/list/big-table-list

这个是还没有开源的功能是吗

**Comment by liliang1993** [comment]
我现在项目里一百条左右的数据在表格里滚动卡顿明显，需要被拯救

**Comment by xy-wind** [comment]
表格功能有点弱，很多东西都需要自己去实现。还有一个头痛的问题，比如：有固定列时，点击行进行编辑，渲染编辑行时行的高度发生变更这时固定列与非固定列的对齐就会错乱。
Input,InputNumber,Select 这种高频组件希望能把功能加强一下吧。Input的只读状态可以增强一下，比如有些时候表单的状态是只读状态(只允许查看)，输入框虽然只读但应该允许有焦点可以复制数据，再加个只读状态下的背景色属性就更好了。
InputNumber应该直接不允许输入非数字，而不是失去焦点后再置空。Select可以增强一下功能，比如可以编辑输入也可以选择下拉列表项，因为有些时候下拉列表没有，是需要自己手动输入的。
对于PC端来说，表格是核心库中的核心，真诚希望能把Table功能再加强！！！

**Comment by Ttou** [comment]
在封装时，有些组件的类型没有导出来，很不方便

**Comment by joel785454405** [comment]
能否把@ant-design-vue/use 的动态校验完善一下。

**Comment by BoringDays** [comment]
至今还没找到一个scss环境下可用的主题色更改方案，请提供官方示例，整个项目从scss迁移到less成本太高了

**Comment by dahei07** [comment]
日期范围控件的选择逻辑是否可以参考 fusion design 的？

**Comment by toddyeah** [comment]
> 2.x 其实算失败的，真正算下来可能2kstar都不到。现在的star及社区活跃度90%是1.x版本的。被element-plus拉了很长了，还需加油

呵呵，element-plus文档真的一言难尽。。。。

**Comment by AliceLanniste** [comment]
想为antdv贡献，但无论是README.md还是issues都没有`how to contribute`文档，能否提供

**Comment by uniquejava** [comment]
## Tutorial on how to contribute / write custom component
Some learning/contribution oriented tutorial on how to write simple custom components for ant-design-vue, how to build/manage/publish such a huge repo is very much appreciated.

For example, how the who repo is structured and how can we study the source code. 🙃

## New course
Maybe consider recording/selling an extended version of your current course - besides the existing one from Geekbang(I bough that one some years ago). I will definitely buy new version if you sell.

最后， 文档上的搜索功能太不明显了。 （加个looking glass或者把搜索框高亮？）
我一直用ctrl+F 然后 滚动条定位component。 这样不爽了好几年， 直到前阵子在学习reactjs 和 ant design react的一个视频里发现有快速使用搜索框 定位component文档的功能。

**Comment by uniquejava** [comment]
我就想想看看大佬是如何修bug 或者开发组件的。 录一些小视频放在b站上我们学习学习？😆

**Comment by tangjinzhou** [comment]
try  https://github.com/vueComponent/ant-design-vue/releases/tag/2.2.0-beta.1

**Comment by tomgao365** [comment]
建议增加年、月、时间的范围选择组件。

**Comment by uinio** [comment]
> 表单：
> 1.form-item 增加hidden属于
> 2.表单验证增强

vue 模板是支持hidden，tsx 也一样，只是需要声明文件
参考
```ts
export interface VueSlots<T = any> {
  [name: string]: (payload?: T) => JSX.Element;
}

export declare type VueModel =
  | string
  | number
  | boolean
  | bigint
  | null
  | undefined
  | symbol
  | Record<string, unknown>
  | [unknown, string];

interface JsxComponentCustomProps {
  vShow?: boolean;
  vSlots?: VueSlots;
  vModel?: VueModel;
  vModels?: VueModel[];
  vHtml?: string | JSX.Element;
  innerHTML?: string | JSX.Element;
}

declare module 'vue' {
  interface HTMLAttributes extends JsxComponentCustomProps {}

  interface ComponentCustomProps extends HTMLAttributes {}
}

```

**Comment by tangjinzhou** [comment]
> 建议增加年、月、时间的范围选择组件。

ing

**Comment by stefnotch** [comment]
In light of recent-ish Microsoft announcements, would it be reasonable to consider dropping IE11 support for version 3.0? This would have the nice advantage of letting you use all the latest features that web platforms have to offer.

> the Internet Explorer 11 desktop application will be retired and go out of support on June 15, 2022, for certain versions of Windows 10.
> -- https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

On that note, it seems like Vue 3 is also [dropping internet explorer support](https://github.com/vuejs/rfcs/pull/294)

**Comment by liekkas** [comment]
add colorPIcker

**Comment by Silentdoer** [comment]
antd vue的dialog能不能像react vue和angular vue一样可以直接用一个service.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便

**Comment by zhenzhenChange** [comment]
- 某些 `props` 的值是否应该调整一下默认值？
  - 比如 `Select` 或者 `TreeSelect` 的搜索过滤 `prop`，默认设置为 `title` 或者 `label` 是否会好一点，因为 `value` 通常是 `id` 值，应该不会搜 `id` 值的吧
- 部分 `props` 统一是否会好一点？
  - 比如 `TreeSelect` 的 `replaceFields` ，有 `key` ，有 `value`
  - 而 `Tree` 的 `replaceFields` ，只有 `key`，没有 `value` （在文档体现上）
  - 个人感觉稍微有点冗余（`key`/`value`）并且稍微有点模糊不清，不知道是有什么用意
- `a-input-search`
  -  假若要自定义 `enterButton` `slot` ，所拥有的事件好像还是有关 `search` 的
  -  希望这块可以宽松一点，增强一丢丢扩展性，因为如果要用 `addonAfter` 设置自定义后缀按钮的话，这个按钮会和输入框的大小不匹配
-  希望 `3.0` 是一场新生

**Comment by studentLLL** [comment]
建议加入级联选择的多选功能，虽然有treeSelect，但是总觉得不太适用

**Comment by snowchenlei** [comment]
功能还需完善，跟ng和react版本还是有不少差距。
treeselect、cascader延迟加载功能没有

**Comment by tangjinzhou** [comment]
> antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便

你在看看文档 ？

**Comment by zhenzhenChange** [comment]
行合并功能申请 +1

https://github.com/ant-design/ant-design/issues/28327

需求示例：
[![Rghrbd.png](https://z3.ax1x.com/2021/07/03/Rghrbd.png)](https://imgtu.com/i/Rghrbd)

**Comment by snowchenlei** [comment]
文档完善性有待增强。
checkStrictly=true。tree点击某一节点如何获取父节点并设置父节点选中或取消选中。

**Comment by zkwolf** [comment]
> `Descriptions`行合并功能申请 +1
> 
> [ant-design/ant-design#28327](https://github.com/ant-design/ant-design/issues/28327)
> 
> 需求示例：
> [![Rghrbd.png](https://camo.githubusercontent.com/bba2d9a994896d8532dad3bea4660a389b6af20e996939955b73274e835326d5/68747470733a2f2f7a332e617831782e636f6d2f323032312f30372f30332f5267687262642e706e67)](https://imgtu.com/i/Rghrbd)
> 
> * 行合并之后可以省下很多空间用于展示额外的数据字段
> * 指定该区域打印时也不会显得很突兀（一般都会要求照片在右上角）
> * 表格合并，emmmmmmmm....

灵魂画手

**Comment by iceprosurface** [comment]
> antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便

vue2 + composition api 的话可以这么搞(有些用的不是 官方推荐的 api，如果打算升级 vue3的可能不太行)：


```ts
/**
 * 指令式modal
 * @return 以Promise形式展示返回，confirm将作为resolve结果，cancel将作为reject结果
 * */
export function show<T>(component: Component, { props, parent, ...other }, app = Vue) {
  const VueComponent = app.extend(component as VueConstructor);
  const modalVm: any = new VueComponent({
    parent,
    propsData: {
      visible: false,
      ...props,
    },
    ...other,
  });
  let canceler: ModalCanceler = () => void 0;
  return new Promise<T>((resolve, reject) => {
    canceler = () => {
      reject();
      modalVm?.$destroy();
    };

    modalVm.$mount();
    modalVm.show();
    // event handler
    modalVm.$on(ModalEvent.CONFIRM, resolve);
    modalVm.$on(ModalEvent.CANCEL, reject);
    modalVm.$on(ModalEvent.DESTROY, canceler);
  }).finally(() => {
    // 做结束的清理工作
  });
}
```

再简单实现一个 useModal

```ts
function useModal() {
  const visible = ref(false);
  const vm = getCurrentInstance()?.proxy;
  const cancel = <T extends any>(error?: T) => {
    visible.value = false;
    vm?.$emit(ModalEvent.CANCEL, error ?? new ModalError('Modal was canceled'));
  };
  const confirm = (...args) => {
    visible.value = false;
    vm?.$emit(ModalEvent.CONFIRM, ...args);
  };
  const destroy = () => vm?.$emit(ModalEvent.DESTROY);
  return {
    visible,
    cancel,
    confirm,
    destroy,
    show: () => (visible.value = true),
  };
}
```

vue2 的只能先暂时绑定到 vue 上了

```ts
function install (app: Vue) {
  app.prototype.$modalShow = function <T>(component: Component, props: any = {}) {
    return show<T>(component, { props, parent: this }, Vue);
  };
}
```

最后使用的话这么用：

```ts
this.$modalShow(xxxComponent, { ...props });

// 或者直接把 show  方法带进来
const vm = getCurrentInstance()?.proxy;
if (vm) {
  show(xxxComponent, {parent: vm})
}
```

**Comment by lzj97** [comment]
> antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便

https://1x.antdv.com/components/modal-cn/#Modal.method()
完整引入Antd的话使用 `this.$info`、`this.$success...` 就好了

**Comment by maicWorkGithub** [comment]
希望 progress 组件 增加 内部文字。类似这个的 https://element.eleme.cn/#/zh-CN/component/progress#bai-fen-bi-nei-xian text-inside。谢谢大佬

**Comment by iyikin** [comment]
希望能支持modal和notification的config来改变类名的前缀，因为这两个组件无法共享ConfigProvider提供的prefixCls
`notification.config({
  prefixCls: 'ant-notification'
});`
`Modal.config({
  rootPrefixCls: 'ant',
});`

**Comment by Silentdoer** [comment]
> 
> 
> > antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便
> 
> https://1x.antdv.com/components/modal-cn/#Modal.method()
> 完整引入Antd的话使用 `this.$info`、`this.$success...` 就好了

这里的content可以是组件名吗？content: SubPage,这种，如果可以，那么SubPage里怎么关闭自己呢？在angular antd里有Modal类型可以来关闭自己，当自己是成为了一个modal框的时候

**Comment by snowchenlei** [comment]
> > antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便
> 
> https://1x.antdv.com/components/modal-cn/#Modal.method()
> 完整引入Antd的话使用 `this.$info`、`this.$success...` 就好了

需要的不是这个功能，而是类似于[ng.antd](https://ng.ant.design/components/modal/zh#components-modal-demo-service)的`服务方式创建`，可以直接传入组件名称弹出框

**Comment by snowchenlei** [comment]
table的远程加载示例对于新手不太友好，看不懂。希望简化。

**Comment by lichinlichin** [comment]
form能不能继续提供 setFields 这类API？
我们有大量表单需要前端校验提示，同时支持后端返回错误提示的help，如果像以前一样有setFields就好了，能节省大量时间

**Comment by JasonSubMara** [comment]
cascader loadData & defaultValue 
级联选择器的回显问题希望能有更好的解决方案，现在的issue下面也难找到解决方案，这是个很久的问题了，希望得到修复～

**Comment by wsxe9988** [comment]
尽量和ant deisgn的功能和细节对标，现在和ant design有点距离了。一些数据呈现的组件能支持虚拟的就支持，提高性能。另外能否和formily合作下，完善下ant design vue版的formily表单设计器和相关的

**Comment by wsxe9988** [comment]
增加 Typography 字体  Border 边框 Link 文字链接  Color(场景色) Scrollbar 滚动条(用于替换浏览器原生滚动条)  ColorPicker 颜色选择器

**Comment by tangjinzhou** [comment]
> cascader loadData & defaultValue
> 级联选择器的回显问题希望能有更好的解决方案，现在的issue下面也难找到解决方案，这是个很久的问题了，希望得到修复～

@JasonSubMara 先搞明白  defaultValue 的意义吧   官网常见问题有答案

**Comment by JHeLiu** [comment]
希望增加 https://2x.antdv.com/components/menu-cn 菜单手风琴模式。只需一个参数是否开启就可

**Comment by mehunk** [comment]
有个困扰很久的问题，还不太好自定义修改，希望 3.0 版本里面能解决掉。

当前有个全局样式是这么写的，这样写以后 body 的最大高度就是浏览器窗口的高度了，默认的滚动条就不会出现在 window 上，而且出现在 body 下的 div 上，这样导致的问题一是有的浏览器滚动的时候会有 bug，二是我之前给一些元素设置 position: sticky 属性的时候不生效。希望新版本能够把这个样式去掉。

```css
html, body {
    width: 100%;
    height: 100%;
}
```

**Comment by yehoan** [comment]
有个问题 tree-select 新增全选和反选   因为这个当tree-select的数据很大的时候 当用户想全选或者反选的时候 没有这个功能 导致操作不是很方便  麻烦 考虑一下谢谢

**Comment by Silentdoer** [comment]
> 
> 
> > antd vue的dialog能不能像react antd和angular antd一样可以直接用一个modalService.create(XxxComponent, props: {...}, ..)这样的方式创建啊？否则每次都必须在主页面里添加一个dialog元素就不太方便
> 
> 你在看看文档 ？

看了呀，antd-vue文档里没写用Modal.method()可以传组件的props，各类参数；而且antd-angular里可以在组件里（这个组件将作为modal）引入Modal对象m；然后可以在组件内部控制自己是否要关闭，即m.close()；而不是在外层组件里的modal对象来控制，外层的modal对象可以监听close时的返回参数；

**Comment by 814096703** [comment]
建议加入表格列宽调整，最好能记录下用户调整后的值。

**Comment by ZzzhuzzZ** [comment]
建议还是优先把table表格得虚拟滚动以及合计栏先弄好，pc这边特别需要。。。

**Comment by cuteCloud** [comment]
麻烦优先下table的性能吧 table的作用在PC端不言而喻  多数据展示的时候 滚动条拖动卡顿这个问题确实亟待解决  急求虚拟滚动上3.0

**Comment by wensonsmith** [comment]
> 麻烦优先下table的性能吧 table的作用在PC端不言而喻 多数据展示的时候 滚动条拖动卡顿这个问题确实亟待解决 急求虚拟滚动上3.0

@cuteCloud 

3.0 的 alpha 已经出了。 按照 QQ 群里作者的回复， 并没有计划做 Table 的开箱虚拟滚动。

因为 Ant Design React 版本也不支持虚拟滚动，而是用的第三方库做的支持。

所以不要报太高的希望，另寻他法吧

**Comment by k983551019** [comment]
> 建议还是优先把table表格得虚拟滚动以及合计栏先弄好，pc这边特别需要。。。

需要的请买Admin PRO，8999  帮你解决这个问题🤪

**Comment by daiwanxing** [comment]
请问 可以直接平滑从2.2.* 升级到 3.*吗？

**Comment by Nakus0426** [comment]
> formily
是的，要是接入了formily的话确实会方便很多

**Comment by adleader** [comment]
@tangjinzhou 高性能表格项目下线了吗 https://github.com/surely-vue/table 找不到了

**Comment by zzlit** [comment]
@tangjinzhou 希望`Menu`增加一个类似于`tooltip`的`align`，能自己定义值合并到`placement`中，现在好像是没有？

**Comment by puppetsheep** [comment]
[3.0.0-alpha.0](https://next.antdv.com/docs/vue/changelog-cn#_3-0-0-alpha-0) 更新日志提到 
> 文档开源，如果您的公司不能外网访问，可以私有化部署，但不可以传播，不可以商业化

是antdv3.x组件库不能用于商业化吗？

**Comment by dengshicheng1996** [comment]
在 form 中如果自定义较为复杂的表单感觉就有点吃不消啊。数据结构如下，外层和内存的数组都是可以进行动态更新的。难道需要不断的套formItem？
```
[
{
  key: '',
  value: ['']
}
]
```

**Comment by zct1989** [comment]
建议完善`SSR`的支持

https://github.com/vueComponent/ant-design-vue/blob/042bf616f87805c63d8676d601c07e0ece7cbc56/components/vc-trigger/Trigger.tsx#L29-L34

**Comment by wsxe9988** [comment]
希望新增一个Gantt 甘特图组件 参考https://devui.design/components/zh-cn/gantt/demo

**Comment by wsxe9988** [comment]
希望新增一个RelativeTime 人性化时间转换组件   参考https://devui.design/components/zh-cn/relative-time/demo
![image](https://user-images.githubusercontent.com/5828057/141224078-34097f7f-f1ca-4c38-81d5-d7214acde4fa.png)
![image](https://user-images.githubusercontent.com/5828057/141224098-939a9fd5-3fa3-430c-a112-a9ff1adbab90.png)

**Comment by xy-wind** [comment]
Pagination 分页组件，显示总数能否支持自定义v-slot插糟，并且可指定显示位置在 左侧 或者 右侧。

**Comment by wsxe9988** [comment]
我看component文件夹里有color-picker组件，为啥在文档里看不到呢

**Comment by maicWorkGithub** [comment]
> 我看component文件夹里有color-picker组件，为啥在文档里看不到呢

文档上有个定制主体，选颜色的功能……

**Comment by balck-paint** [comment]
主题切换很难不支持

**Comment by lk1942** [comment]
自从高级组件的出现，已不抱有幻想，求人不如求己

**Comment by Noemi-** [comment]
如果vue出了2.7版本，就是官方实现3.0特性的vue2.x版本，可以配套使用antdv3.+版本么？

**Comment by zkwolf** [comment]
> 如果vue出了2.7版本，就是官方实现3.0特性的vue2.x版本，可以配套使用antdv3.+版本么？

我觉得还是挺困难的，除了Composition API 还有Teleport、Fragment之类的东西得兼容

**Comment by 724493602** [comment]
> 自从高级组件的出现，已不抱有幻想，求人不如求己

以后上述都会变为付费功能
