### ISSUE TITLE
date-picker validate is not work

### ISSUE THREAD

**Issue by linkscope** [vueComponent/ant-design-vue#3925]
### Version
2.0.1

### Environment
Vue3.0

### Reproduction link
It's not need to reproduction

### Steps to reproduce
use form validator, and config date-picker's rule: {required: true, message: 'need date', trigger: 'change'}

### What is expected?
when i config {required: true, message: 'need date', trigger: 'change'}, can also pass.

### What is actually happening?
When use form validate on date-picker, no matter how i select date, it will still report an error message.
but if i use validator, i can get value and make it pass

**Comment by John60676** [comment]
Reference: https://codesandbox.io/s/little-http-0f0b7?file=/src/App.vue

**Comment by linkscope** [comment]
@John60676 Okey, Thanks your answer.
