### ISSUE TITLE
Regarding the use of select component form validation in the Form form.

### ISSUE THREAD

**Issue by FlyFishCode** [vueComponent/ant-design-vue#3926]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.0

### Environment
vue：3.0.0，Chrome: 89.0.4389.114

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-ptolemy-ou9n7?file=/src/main.js)

### Steps to reproduce
下拉选中数据之后，点击按钮

### What is expected?
下拉组件选中数据之后，点击按钮验证成功

### What is actually happening?
下拉组件选中数据之后，点击按钮验证失败

---
很疑惑，是不是ant-design-vue（2.1.1）已经修复这个问题了。还是我使用方式错误？

**Comment by John60676** [comment]
`form-item` 的 `name` 弄错了

参考 https://codesandbox.io/s/amazing-hugle-dm974?file=/src/components/HelloWorld.vue

**Comment by FlyFishCode** [comment]
多谢、
