### ISSUE TITLE
table - template style - a-table-column-group

### ISSUE THREAD

**Issue by runkobe24** [vueComponent/ant-design-vue#3929]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
Vue3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-hybkz?file=/src/components/HelloWorld.vue)

### Steps to reproduce

Use  a-table-column v-for  Placed under the a-table-column-group component, the result a-table-colum shows empty

### What is expected?

Use  a-table-column v-for  Placed under the a-table-column-group component, the result a-table-colum can be normal

### What is actually happening?
The a-table-column under the a-table-column-group component cannot be looped out by the for

**Comment by John60676** [comment]
Provide a usable reproduce

**Comment by runkobe24** [comment]
https://codesandbox.io/s/solitary-frog-nqs44?file=/src/components/HelloWorld.vue:266-271

**Comment by runkobe24** [comment]
> Hello @runkobe24. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @runkobe24, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

https://codesandbox.io/s/solitary-frog-nqs44?file=/src/components/HelloWorld.vue

**Comment by runkobe24** [comment]
> Provide a usable reproduce

https://codesandbox.io/s/solitary-frog-nqs44?file=/src/components/HelloWorld.vue

**Comment by runkobe24** [comment]
> Provide a usable reproduce

**Comment by runkobe24** [comment]
> Provide a usable reproduce

The connection has been provided, can it be repaired?
