### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "onChange". Expected Function, got Array  

### ISSUE THREAD

**Issue by w18701660942** [vueComponent/ant-design-vue#3933]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
开发

### Reproduction link
[http://localhost:8090/country/country_list](http://localhost:8090/country/country_list)

### Steps to reproduce
开发2次组件时，只要加chang事件就报[Vue warn]: Invalid prop: type check failed for prop "onChange". Expected Function, got Array

### What is expected?
能正常使用

### What is actually happening?
能正常使用

---
<template>

<a-checkbox-group :value="value" name="checkboxgroup" :options="plainOptions" @change="change" />
</template>

<script lang="ts">
import { useEmits, useProps } from '@/hooks'
import { defineComponent, ref } from 'vue'
const plainOptions = ['Apple', 'Pear', 'Orange']
export default defineComponent({
props: {
...useProps(),
value: Array,
},
emits: ['update:value'],
setup(props, ctx) {
const { emit } = ctx
const change = (checkedValue: any) => {
emit('update:value',checkedValue)
}
return {
change,
plainOptions,
value1: ref([])
}
}
})
</script>

**Comment by w18701660942** [comment]
![image](https://user-images.githubusercontent.com/20851373/114496818-56f44600-9c53-11eb-952f-265dccd0fd6c.png)

**Comment by w18701660942** [comment]
![Uploading image.png…]()

**Comment by w18701660942** [comment]
![image](https://user-images.githubusercontent.com/20851373/114496900-7db27c80-9c53-11eb-9d2e-3ccf6b7295c6.png)

**Comment by w18701660942** [comment]
我自己找到解决方法了，用emits重写一下，覆盖原来的方法就行，建议不要合并成数组

**Comment by G-lory** [comment]
> 我自己找到解决方法了，用emits重写一下，覆盖原来的方法就行，建议不要合并成数组

遇到同样的问题了 能详细说一下怎么解决的吗？谢谢！:D

**Comment by G-lory** [comment]
> 我自己找到解决方法了，用emits重写一下，覆盖原来的方法就行，建议不要合并成数组

哦 我懂了 `emits:['change']` 这样…… 打扰了 :P

**Comment by GZ0759** [comment]
> > 我自己找到解决方法了，用emits重写一下，覆盖原来的方法就行，建议不要合并成数组
> 
> 哦 我懂了 `emits:['change']` 这样…… 打扰了 :P

为什么会这样呢，我在setup中的emits添加 change 也不报警告了

**Comment by passioncsu** [comment]
> 

请先允许我哭会, 刚开始用的"ant-design-vue": "3.1.0-rc.1"报这个告警, 然后更新为当前最新 "ant-design-vue": "3.1.0-rc.5" 还是报这个告警,虽然不影响使用,但是对于强迫症来说必须消除告警.     这个描述真的太隐晦了. 对于小白的我没看懂.


总之就是  在组件里面声明一下change的这个emit就好了,  底层原因没深究真的有点迷.

如下这么写一下就不告警了, 希望帮到别人.
<script lang="ts" setup>
  const emit = defineEmits(['update:modelValue', 'change']);
<script>

**Comment by RSS1102** [comment]
> > 
> 
> 请先允许我用的哭会-vue-vue-vue.1.1.1”最新消息，然后刚开始更新为当前ant-design-vue.0”最新消息，然后更新：“ant-design-v”：“3.1.0- 5" 还是报这个热门话题。虽然不影响使用，但必须要热门话题。这个描述真的太隐晦了。对于小白的我没看懂。
> 
> 那就是在组件里面声明一下改变的这个放出来就好了，动力原因没深究真的有点迷。
> 
> 就这样写一下，别想了，希望帮到你
> 
> <script lang="ts" setup> const emit = defineEmits(['update:modelValue', 'change']); <脚本>

thanks，我也遇到了这个问题，通过你的方法解决了。我是将upload挂在到vue实例上之后产生的这个错误。而且事件被判定为`Array`not`Function`，而导致不能使用。

**Comment by RSS1102** [comment]
> Function

那个问题好像是有一个拦截他的change事件然后分配给传过来的`参数`，来指定子传父触发的方法。你通过重新定义了`@change`默认事件传递之后，就不会走他拦截的那个方法了（个人认为是这样的。）
