### ISSUE TITLE
Table row/column merge problem

### ISSUE THREAD

**Issue by guan-jade** [vueComponent/ant-design-vue#3941]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vs2019 typescript asp.net core ant-design-vue1.7.3 vue2.6.12

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
1.学习试用ant-design-vue官网的组件table表格行/列合并的代码
2.运行时报错，报错信息：Uncaught SyntaxError: Unexpected token '<'
3.报错定位：return <a href="javascript:;">{text}</a>;
![image](https://user-images.githubusercontent.com/82485028/114646126-44d6de00-9d0d-11eb-8b72-20b241a31cb8.png)

### What is expected?
能够实现还原官网提供的代码实例

### What is actually happening?
1.运行时报错，报错信息：Uncaught SyntaxError: Unexpected token '<'
2.报错定位：return <a href="javascript:;">{text}</a>;
![image](https://user-images.githubusercontent.com/82485028/114646136-4b655580-9d0d-11eb-8e4b-021184269e23.png)

**Comment by John60676** [comment]
装一下 [jsx](https://github.com/vuejs/jsx)
