### ISSUE TITLE
Descriptions Component slot label usage is inconsistent

### ISSUE THREAD

**Issue by Huanghaiting** [vueComponent/ant-design-vue#3944]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
browser version：版本 89.0.4389.82（正式版本） （64 位）vue2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-xydfd?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-forked-xydfd?file=/src/App.vue

### What is expected?
想了解不一致出现的原因，是否正确使用该组件

### What is actually happening?
Descriptions 组件插槽label使用展示不一致

**Comment by John60676** [comment]
`solt` => `slot`
