### ISSUE TITLE
在upload的beforeUpload中压缩图片之后交给promise上传，结果传的不是压缩后的文件

### ISSUE THREAD

**Issue by ZmjDns** [vueComponent/ant-design-vue#3945]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
wind10，chrome79，  vue^2.6.10

### Reproduction link
[https://github.com/ZmjDns/dnpicture.git](https://github.com/ZmjDns/dnpicture.git)

### Steps to reproduce
beforeUpload (file) {
let isJpgOrPng = file.type === 'image/jpeg' || file.type === 'image/png'
if (!isJpgOrPng) {
this.$message.error('此文件类型不允许上传!')
return new Promise((resolve, reject) => {
reject(false)
})
}
let isLt2M = file.size / 1024 / 1024 < 2
if (!isLt2M) {
imageConversion.compressAccurately(file, 500)
.then(res => {
return new Promise((resolve, reject) => {
resolve(res)
})
})
.catch(err => {
console.log('压缩失败', err)
})
} else {
return new Promise((resolve, reject) => {
console.log('未压缩上传...............', file)
resolve(file)
})
}
}

### What is expected?
通过 new Promise((resolve, reject) => {
resolve(file)
})
上传压缩过的文件，而不是源文件

### What is actually happening?
官方文档上写着：上传文件之前的钩子，参数为上传的文件，若返回 false 则停止上传。支持返回一个 Promise 对象，Promise 对象 reject 时则停止上传，resolve 时开始上传（ resolve 传入 File 或 Blob 对象则上传 resolve 传入对象）。注意：IE9 不支持该方法。
但是当我把压缩完的文件传给 resolve 处理的时候，结果它上传的竟然是源文件

**Comment by John60676** [comment]
你确定的的代码是返回了Promise？
```js
beforeUpload(file) {
  let isJpgOrPng = file.type === "image/jpeg" || file.type === "image/png"
  if (!isJpgOrPng) {
    this.$message.error("此文件类型不允许上传!")
    return new Promise((resolve, reject) => {
      reject(false)
    })
  }
  let isLt2M = file.size / 1024 / 1024 < 2
  if (!isLt2M) {
    imageConversion
      .compressAccurately(file, 500)
      .then((res) => {
        return new Promise((resolve, reject) => {
          resolve(res)
        })
      })
      .catch((err) => {
        console.log("压缩失败", err)
      })
  } else {
    return new Promise((resolve, reject) => {
      console.log("未压缩上传...............", file)
      resolve(file)
    })
  }
}

```

**Comment by ZmjDns** [comment]
我是在压缩之后的then方法中返回的Promise，代码的倒数第14行
![11111111](https://user-images.githubusercontent.com/30400636/114820599-ce5fdc00-9df1-11eb-838c-f7e3d3816e12.jpg)

**Comment by John60676** [comment]
你再仔细看看 `imageConversion` 有没有返回出去

```js
if (!isLt2M) {
    imageConversion
      .compressAccurately(file, 500)
      .then((res) => {
        return new Promise((resolve, reject) => {
          resolve(res)
        })
      })
      .catch((err) => {
        console.log("压缩失败", err)
      })
  } else {
    return new Promise((resolve, reject) => {
      console.log("未压缩上传...............", file)
      resolve(file)
    })
  }
```

**Comment by ZmjDns** [comment]
懂您的意思了，我怎么才能在执行完imageConversion 之后再将Promise返回出去呢？

**Comment by John60676** [comment]
https://codesandbox.io/s/vue-antd-template-forked-zi0mh?file=/src/App.vue

**Comment by ZmjDns** [comment]
我在您写的这个方法里上传了一个大于2M的图片(我只修改了压缩的大小)，他就卡在这里了(小于2M的图片不走压缩是没有问题的）
![2222222](https://user-images.githubusercontent.com/30400636/114825407-c35c7a00-9df8-11eb-8ad3-ad0b38d28688.png)

**Comment by John60676** [comment]
因为上传失败了啊。你换回自己的接口

**Comment by ZmjDns** [comment]
我切换回自己自己的接口之后上传，却报了这个错误，Invalid prop: custom validator check failed for prop "items"，虽然之前有解决，但是对我这个错误好像不起作用
![33333333](https://user-images.githubusercontent.com/30400636/114828569-a5911400-9dfc-11eb-9d74-ec967a4ea58d.png)

**Comment by John60676** [comment]
新开一个issue吧，提供一个重现示例

**Comment by ZmjDns** [comment]
好的
