### ISSUE TITLE
not compatible with `vue@2` on `vite@2`

### ISSUE THREAD

**Issue by cdll** [vueComponent/ant-design-vue#3946]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
i tried using vite to bundle my project which based on `vue@2` and `and-design-vue@1.7` but running in browser it came into an Error with messaging `index.8605c336.js:33 TypeError: Failed to resolve module specifier "indexof". Relative references must start with either "/", "./", or "../".` which i think it was produced by `component-classes@1`.

### What does the proposed API look like?
could this be fixed on `antDeisgnVue@1`, hoping it to be fixed. 感谢

**Comment by tangjinzhou** [comment]
antDeisgnVue@1  not support vite
