### ISSUE TITLE
The action column is fixed in the table, and the table is misaligned after page turning

### ISSUE THREAD

**Issue by Zhai6319** [vueComponent/ant-design-vue#3952]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.2

### Environment
os macos big sur，browser Google，vue 3.0.9

### Reproduction link
[http://test.work.zjcmyl.com/#/user/vehicles](http://test.work.zjcmyl.com/#/user/vehicles)

### Steps to reproduce
表格action 列，右侧固定，翻页后固定列高度于表格高度不一致导致错位
![image](https://user-images.githubusercontent.com/29478697/114856995-5659dc00-9e1a-11eb-9368-57cb62af2738.png)
![image](https://user-images.githubusercontent.com/29478697/114857035-65408e80-9e1a-11eb-8c52-b660a0f60029.png)

### What is expected?
希望表格操作可以如丝般顺滑

### What is actually happening?
我也不知道发送了什么，就是表格错位，各种宽度制定，空一格无宽度的列，调试后均无效，表格第一页正常，翻页后出现错位
<a-table
:columns="columns"
:data-source="data"
:rowKey="(record, index) => {return index;}"
:pagination="pagination"
:loading="loading"
:scroll="{ x: 2000 }"
:size="$store.getters.themeSize"
@change="handleTableChange"
></a-table>
const columns = [
{
title: "品牌",
align: "center",
dataIndex: "brand",
key: "brand",
width: 100,
},
{
title: "运力类型id",
align: "center",
dataIndex: "capacityTypeId",
key: "capacityTypeId",
width: 100,
slots: { customRender: "capacityTypeId" },
},
{
title: "行驶证",
align: "center",
dataIndex: "drivingLicense",
key: "drivingLicense",
width: 100,
slots: { customRender: "drivingLicense" },
},
{
title: "发动机编号",
align: "center",
dataIndex: "engineNo",
key: "engineNo",
width: 100,
},
{
title: "状态",
align: "center",
dataIndex: "vehicleStatus",
key: "vehicleStatus",
width: 100,
slots: { customRender: "vehicleStatus" },
},
{
title: "车挂号",
align: "center",
dataIndex: "hangingNum",
key: "hangingNum",
width: 100,
},
{
title: "车牌号",
align: "center",
dataIndex: "licensePlate",
key: "licensePlate",
width: 100,
},
{
title: "车牌类型",
align: "center",
dataIndex: "licensePlateType",
key: "licensePlateType",
width: 100,
slots: { customRender: "licensePlateType" },
},
{
title: "型号",
align: "center",
dataIndex: "model",
key: "model",
width: 100,
slots: { customRender: "model" },
},
{
title: "核定载人数",
align: "center",
dataIndex: "passengerNum",
key: "passengerNum",
width: 100,
},
{
title: "操作",
align: "center",
key: "operation",
fixed: "right",
width: 100,
slots: { customRender: "action" },
},
];

**Comment by weed-x** [comment]
同样的问题，我用的是1.7.3版本的antd
![image](https://user-images.githubusercontent.com/66823026/115044672-4c160b80-9f08-11eb-8719-4701627d8561.png)

**Comment by weed-x** [comment]
> 就是没人给出复现示例

[https://codesandbox.io/s/vue-antd-template-forked-es0b9](url)
在新窗口下预览效果很明显
![image](https://user-images.githubusercontent.com/66823026/115099093-4ea74e00-9f66-11eb-8f12-254f663172f9.png)

**Comment by weed-x** [comment]
[https://codesandbox.io/s/vue-antd-template-forked-es0b9](url)
在新窗口下浏览效果明显

**Comment by weed-x** [comment]
> 就是没人给出复现示例

https://codesandbox.io/s/vue-antd-template-forked-es0b9
请原谅我没有使用链接，尝试了两次使用链接都无法访问，复制地址到浏览器可以访问。。。
在新窗口打开预览效果明显

**Comment by weed-x** [comment]
请问这个问题会修复吗？

**Comment by kzxuan** [comment]
相同的问题，给出示例了，但是官方不回复？

**Comment by tangjinzhou** [comment]
固定图片高度  https://codesandbox.io/s/vue-antd-template-forked-wifuc?file=/src/App.vue

**Comment by tangjinzhou** [comment]
或者升级 2.x 3.x
