### ISSUE TITLE
使用select组件时候的报错

### ISSUE THREAD

**Issue by EJairwin** [vueComponent/ant-design-vue#396]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.7

### Environment
vue：2.5.17

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/select-cn/#API](https://vuecomponent.github.io/ant-design-vue/components/select-cn/#API)

### Steps to reproduce
```html
<a-form-item
label='主员工'
fieldDecoratorId="employee_id"
:fieldDecoratorOptions="{rules: [{ required: true, message: '必须选择主员工' }]}"
>
<a-select
showSearch
placeholder="请选择主员工"
:defaultActiveFirstOption="false"
:showArrow="false"
:filterOption="false"
@search="handleSearch"
:notFoundContent="null"
>
<a-select-option v-for="item in employee_list" :key="item.id">{{item.name}}</a-select-option>
</a-select>
</a-form-item>
```

### What is expected?
使用下拉框的时候无报错情况

### What is actually happening?
[Vue warn]: Invalid prop: custom validator check failed for prop "selectedKeys".

---
导航菜单：https://vuecomponent.github.io/ant-design-vue/components/menu-cn/#API

**Comment by EJairwin** [comment]
已解决

**Comment by MillionQW** [comment]
@EJairwin 怎么解决的，可以分享一下吗？

**Comment by tenadolanter** [comment]
item.icon
