### ISSUE TITLE
Version 2.1.2 refers to the use of icon components in ant-design/icons-vue, ts prompts type error

### ISSUE THREAD

**Issue by AREA-CQK** [vueComponent/ant-design-vue#3961]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
macos 11.2.2  chrome 版本 89.0.4389.128（正式版本）vue@3.0.5

### Reproduction link
[https://2x.antdv.com/components/icon](https://2x.antdv.com/components/icon)

### Steps to reproduce
使用vite开发，引用 SearchOutlined图标组件，打包提示类型问题
src/components/Search/index.vue:23:12 - error TS2322: Type '{}' is not assignable to type 'SearchOutlinedIconType & Omit<__VLS_GlobalAttrs, keyof SearchOutlinedIconType> & Record<string, unknown>'.
Property 'displayName' is missing in type '{}' but required in type 'SearchOutlinedIconType'.

23           <SearchOutlined />
~~~~~~~~~~~~~~

node_modules/@ant-design/icons-vue/lib/icons/SearchOutlined.d.ts:4:5
4     displayName: string;
~~~~~~~~~~~
'displayName' is declared here.


### What is expected?
无类型报错

### What is actually happening?
有类型报错



        

<!-- generated by issue-helper. DO NOT REMOVE -->

**Comment by joker77877** [comment]
什么时候修复
