### ISSUE TITLE
nuxt install ant design vue v2.x

### ISSUE THREAD

**Issue by s5510886103** [vueComponent/ant-design-vue#3962]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
"nuxt": "^2.15.3" "ant-design-vue": "^2.1.2",

### Steps to reproduce
npx create nuxt
npm i --save ant-design-vue@next

### What is expected?
Fix issue

### What is actually happening?
WARN  Compiled with 41 warnings
WARN  in ./node_modules/ant-design-vue/es/_util/props-util/index.js
"export 'Comment' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/tree-select/index.js
"export 'Fragment' (imported as '_Fragment') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/_util/props-util/index.js
"export 'Fragment' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/vc-drawer/src/Drawer.js
"export 'Teleport' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/button/button.js
"export 'Text' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/_util/transition.js
"export 'Transition' (imported as 'T') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/_util/transition.js
"export 'TransitionGroup' (imported as 'TG') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/alert/index.js
"export 'cloneVNode' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'computed' was not found in 'vue'
"export 'createApp' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/pagination/Pagination.js
"export 'createTextVNode' (imported as '_createTextVNode') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'createVNode' (imported as '_createVNode') was not found in 'vue'
WARN  in ./node_modules/@ant-design/icons-vue/es/icons/CloseOutlined.js
"export 'createVNode' (imported as '_vue') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/layout/layout.js
"export 'createVNode' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'defineComponent' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'getCurrentInstance' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/_util/props-util/index.js
"export 'h' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/vc-image/src/PreviewGroup.js
"export 'inject' (imported as '_inject') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'inject' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/auto-complete/index.js
"export 'isVNode' (imported as '_isVNode') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/card/Card.js
"export 'isVNode' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/table/Table.js
"export 'markRaw' was not found in 'vue'
WARN  in ./node_modules/@ant-design/icons-vue/es/icons/CloseOutlined.js
"export 'mergeProps' (imported as '_vue') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/back-top/index.js
"export 'nextTick' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/descriptions/index.js
"export 'onBeforeUnmount' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/vc-select/hooks/useLock.js
"export 'onBeforeUpdate' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'onMounted' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'onUnmounted' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'onUpdated' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/vc-image/src/PreviewGroup.js
"export 'provide' (imported as '_provide') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/auto-complete/index.js
"export 'provide' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'reactive' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'ref' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/typography/Base.js
"export 'toRaw' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/menu/index.js
"export 'toRef' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/layout/layout.js
"export 'toRefs' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/alert/index.js
"export 'vShow' (imported as '_vShow') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/affix/index.js
"export 'watch' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/tag/index.js
"export 'watchEffect' was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/alert/index.js
"export 'withDirectives' (imported as '_withDirectives') was not found in 'vue'
WARN  in ./node_modules/ant-design-vue/es/input/Input.js
"export 'withDirectives' was not found in 'vue'

**Comment by ajuner** [comment]
nuxt 2.x版本不支持vue3
