### ISSUE TITLE
Modal.confirm, etc. and notification do not support the configuration of rootPrefixCls

### ISSUE THREAD

**Issue by prettyboyweiwei** [vueComponent/ant-design-vue#3969]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.2

### Environment
vue 3

### Reproduction link
[https://www.antdv.com/components/modal-cn/](https://www.antdv.com/components/modal-cn/)

### Steps to reproduce
1. ```<configProvider prefixCls='abc' />```
2. ```Modal.info({ })```

### What is expected?
期望 Modal 、notification 支持如下写法来配置类名前缀。
Modal.config({ rootPrefixCls: 'abc' }); notification.config({ prefixCls: 'abc' });
目前 vue antd 只有 message 支持以上配置， react antd 则全部支持。

### What is actually happening?
无

**Comment by RootJian** [comment]
Input 的 password组件也无法生效，使用了prefixCls 后  依然是ant-input-password

**Comment by iyikin** [comment]
我也遇到了这个问题，希望能增加Modal 、notification的rootPrefixCls配置
