### ISSUE TITLE
When the options of the Select component change dynamically, the virtual list of the drop-down box is displayed abnormally and fails to scroll normally

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3971]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
https://codesandbox.io/s/confident-galois-3wyp6?file=/src/App.vue

### Reproduction link
[https://2x.antdv.com/components/select-cn](https://2x.antdv.com/components/select-cn)

### Steps to reproduce
1.先定义select的options
2.动态更改options的长度
3.发现下拉框展开后 列表异常

### What is expected?
下拉框展开后列表正常

### What is actually happening?
1.先定义select的options
2.动态更改options的长度
3.发现下拉框展开后 列表异常
4.环境为2.1.2

---
详情见codebox demo

**Comment by liulei92** [comment]
![image](https://user-images.githubusercontent.com/18693333/116050572-393ecc00-a6aa-11eb-9ec1-d4941dc1eb75.png)
此问题修复后，动态更新options后出先translateY 异常的问题；望紧急修复版本

**Comment by zkwolf** [comment]
确认一下到底有问题吗
