### ISSUE TITLE
When using the search time of a-input-search, warning.js is loaded by default? 2149:6 Warning: `onSearch` should work with `showSearch` instead of use alone.

### ISSUE THREAD

**Issue by w18701660942** [vueComponent/ant-design-vue#3974]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
dev

### Reproduction link
[http://localhost:8090/country/country_list](http://localhost:8090/country/country_list)

### Steps to reproduce
使用a-input-search 的search时间时，默认加载报warning.js?2149:6 Warning: `onSearch` should work with `showSearch` instead of use alone.

### What is expected?
使用a-input-search 的search时间时，默认加载报warning.js?2149:6 Warning: `onSearch` should work with `showSearch` instead of use alone.

### What is actually happening?
没有找到showSearch属性

**Comment by w18701660942** [comment]
![image](https://user-images.githubusercontent.com/20851373/115539781-f8bd0800-a2cf-11eb-9534-62934f7db563.png)

**Comment by w18701660942** [comment]
![image](https://user-images.githubusercontent.com/20851373/115539960-27d37980-a2d0-11eb-9f12-4e2958373abe.png)

**Comment by zkwolf** [comment]
看了一下这应该是select的warning

**Comment by w18701660942** [comment]
不是，我不加a-input-search这个组件的@search就没事

**Comment by w18701660942** [comment]
我看源码中也没有相关的内容， 很奇怪

**Comment by zkwolf** [comment]
能给个复现吗

**Comment by w18701660942** [comment]
只能远程看一下

**Comment by w18701660942** [comment]
其实很简单， 就是封装了一个表单， 调有了a-input-search, 然后在form上添加了@search

**Comment by boot-vue** [comment]
same problem

**Comment by boot-vue** [comment]
> same problem

after add `show-search` and remove `mode='multiple' label-in-value` , it work ok.

**Comment by zkwolf** [comment]
能写个复现吗
