### ISSUE TITLE
Table checkbox performance issues

### ISSUE THREAD

**Issue by lianshuang** [vueComponent/ant-design-vue#3987]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表格数据稍微一多 50条100条以上渲染就很卡，而且前面有选择框的时候选择和取消选择都非常的卡，研究发现只有v-model  v-if 
 v-show在同文件发生了视图变化就会重新渲染表格，你们可以试试用customRow这个属性看看表格得重新渲染，表格得row-selection也会造成这种问题，对比了element ui这个性能差的不是一点半点啊，求官方修复，目前用的是1.7.4版本

The table data is slightly more than 50 and more than 100. The rendering is very stuck, and when there is a selection box in front of the card, the selection and deselection are very good. The study found that there is only v-model v-if
  V-show will re-render the table if the view changes in the same file. You can try to use the customRow attribute to see if the table has to be re-rendered. The row-selection of the table will also cause this problem. Compare the poor performance of element ui. It’s not just a little bit, I ask for an official fix, the current version is 1.7.4

### What does the proposed API look like?
a-table

**Comment by lianshuang** [comment]
anyone help？

**Comment by tangjinzhou** [comment]
升级 1.x 的最新版  会 2.x 的最新版

**Comment by lianshuang** [comment]
现在1.7.4没什么用，还是一样，2.x的话需要升级vue版本没去用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月8日(星期六) 下午5:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vueComponent/ant-design-vue] Table checkbox performance issues (#3987)





 
升级 1.x 的最新版  会 2.x 的最新版
