### ISSUE TITLE
After refactoring the Switch component in version 2.1.3, the onChange prop of the component is lost, and ts reports an error

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3993]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
ant-design-vue 2.1.3

### Reproduction link
[https://2x.antdv.com/components/switch-cn](https://2x.antdv.com/components/switch-cn)

### Steps to reproduce
null

### What is expected?
onChange 事件prop

### What is actually happening?
onChange 事件prop 无此类型

**Comment by ajuner** [comment]
能告知下是啥插件报的错嘛

**Comment by liulei92** [comment]
当前是使用tsx进行的 组件封装，在你这个重构前的2.0几的版本中，也出现了ts声明文件中关于onChange的prop缺失

**Comment by liulei92** [comment]
<Switch
            checked={props.value}
            // name={name}
            disabled={!!disabled}
            size="small"
            onChange={onChange}
          />

**Comment by liulei92** [comment]
https://github.com/vueComponent/ant-design-vue/issues/3456 现象同此

**Comment by liulei92** [comment]
switchProps
缺少 onChange 和 onClick的 propstypes.Func

**Comment by ajuner** [comment]
感谢反馈！

**Comment by liulei92** [comment]
感觉有问题啊；应该是 onChange 等等

**Comment by ajuner** [comment]
对 刚看到了

**Comment by liulei92** [comment]
本周会有紧急修复更新吗

**Comment by ajuner** [comment]
应该有
