### ISSUE TITLE
When the options of the Select component change dynamically, the virtual list of the drop-down box is displayed abnormally

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#3995]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
https://codesandbox.io/s/confident-galois-3wyp6?file=/src/App.vue

### Reproduction link
[https://2x.antdv.com/components/select-cn](https://2x.antdv.com/components/select-cn)

### Steps to reproduce
1.先定义select的options
2.动态更改options的长度
3.发现下拉框展开后 列表异常

### What is expected?
下拉框展开后列表正常

### What is actually happening?
1.先定义select的options
2.动态更改options的长度
3.发现下拉框展开后 列表异常
4.环境为2.1.2

![image](https://user-images.githubusercontent.com/18693333/116051025-bf5b1280-a6aa-11eb-8cad-73fb609606f3.png)

**Comment by zkwolf** [comment]
2.1.3试试

**Comment by liulei92** [comment]
有点奇怪；下午刚更新2.1.3的时候，下拉框展开后，有点不正常；现在又好了。。。
