### ISSUE TITLE
Warnings on console when using Menu component

### ISSUE THREAD

**Issue by ais-one** [vueComponent/ant-design-vue#3998]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
Windows 10, Chrome 89, Vue 3.0.11

### Reproduction link
[https://2x.antdv.com/components/menu](https://2x.antdv.com/components/menu)

### Steps to reproduce
Use the example code for Menu, with version ant-design-vue version 2.1.3

### What is expected?
It is working properly but...

### What is actually happening?
There is warnings in the console

reactivity.esm-bundler.js:337 Set operation on key "_" failed: target is readonly. {_: 1, __vInternal: 1, default: ƒ}

**Comment by zly9** [comment]
我这边也出现了同样的问题，目前还不知道是啥原因，就是更新了新的版本之后就冒出来了

**Comment by kriszheng-cashwerkz** [comment]
The same warnings occur when hovering or clicking on menu items. It does not have any impact on the functionalities and the warnings don't show after build.

**Comment by zkwolf** [comment]
似乎没复现出来，哪个例子有问题我去试试

**Comment by lemonchip** [comment]
I also had the same problem ：the console warning  Set operation on key "xxxx" failed: target is readonly.

**Comment by liulei92** [comment]
> I also had the same problem ：the console warning Set operation on key "xxxx" failed: target is readonly.

i, too

**Comment by liulei92** [comment]
具体demo
warning：Set operation on key "expandIcon" failed: target is readonly. 

munu中使用了
`
<template #expandIcon>
  <i class="icomoon icon-arrow_right"></i>
</template>
`
自定义了expandIcon

**Comment by bao2314483** [comment]
我也是出現這個問題,報錯誤是Set operation on key "default" failed: target is readonly.
引起這個錯誤的代碼是如下
```
<a-menu theme="dark" mode="inline" v-model:selectedKeys="SelectedKeys" @click="OnMuenClick">
        <a-menu-item v-for="Item in Routers" :key="Item.name">
          <SvgIcon :name="Item.meta?.icon" />
          <span>{{ Item.meta?.title }}</span>
        </a-menu-item>
      </a-menu>
```

**Comment by nshusr** [comment]
俺也一样
The same for me

**Comment by rmlzy** [comment]
mark

**Comment by rmlzy** [comment]
v2.1.2 没有此问题

**Comment by zkwolf** [comment]
检查一下warning的vue版本？

**Comment by bao2314483** [comment]
> v2.1.2 没有此问题

升級了2.1.3就出現了

**Comment by rmlzy** [comment]
@zkwolf vue@3.0.11

**Comment by zly9** [comment]
> 检查一下warning的vue版本？

我前天试过，将vue版本回退到3.0.6也不行，3.0.11也是一样会出先这个问题，用的vite

**Comment by ndrshn** [comment]
vue@3.0.11
ant-design-vue@2.1.2
vite@2.1.5

same warnings

**Comment by nshusr** [comment]
"vue": "3.0.11",
"ant-design-vue": "2.1.3",
"vite": "^2.2.3",

There is this warning message

**Comment by zkwolf** [comment]
It seems that only vite env will report this warning, I reproduce this warning with vite@2.2.3. Is there anyone have this warning without vite env?

**Comment by huangzhengyon** [comment]
I had the same problem

**Comment by TimRChen** [comment]
mark.

**Comment by bandaoqiu** [comment]
vue@3.0.11
ant-design-vue@2.1.3
vite@2.2.3

same warning

**Comment by jiabinbin** [comment]
mark

**Comment by zjlovezj** [comment]
"mark" or "I have the same problem" is very annoying, please stop spamming this thread.

**Comment by rmlzy** [comment]
> It seems that only vite env will report this warning, I reproduce this warning with vite@2.2.3. Is there anyone have this warning without vite env?

@vue/cli-service 4.5.12

**Comment by ais-one** [comment]
I am using vite and having this problem

    "vue": "^3.0.11",
    ***@***.***/plugin-vue": "^1.2.2",
    ***@***.***/compiler-sfc": "^3.0.11",
    "vite": "^2.2.3"



*Warmest Regards,*

*Aaron*


The information herein is given on a general basis without obligation and
is strictly for information purposes only. We do not warrant the accuracy
or completeness of the information, graphics, links, or other items
contained herein, and expressly disclaim liability for errors or omissions
in these materials.

**Comment by ais-one** [comment]
If it helps... this is the versions that I see the problem, my env is vite

    "vue": "^3.0.11",
    "@vitejs/plugin-vue": "^1.2.2",
    "@vue/compiler-sfc": "^3.0.11",
    "vite": "^2.2.3"

**Comment by fengbaoheng** [comment]
鼠标滑过Menu组件时报这个问题，也是最近更新过依赖版本后才有的
  "dependencies": {
    "@ant-design/icons-vue": "^6.0.1",
    "ant-design-vue": "^2.1.2",
    "vue": "^3.0.11",
    "vuex": "^4.0.0"
  },

**Comment by tangjinzhou** [comment]
use vue 3.0.10

**Comment by fengbaoheng** [comment]
> use vue 3.0.10
> 
> ref [vuejs/vue-next#3695](https://github.com/vuejs/vue-next/issues/3695)

I've tried, but it's still unresolved.
"ant-design-vue": "^2.1.2",
"vue": "^3.0.10"

**Comment by tuyutian** [comment]
用的异步数据更新SubMenu的时候，就会这样，连带着其他固定写死的副菜单也会报这个warning，鼠标一移上去就会
![DB5C0BE9-B8D7-44ed-91CD-F936D764C178](https://user-images.githubusercontent.com/28928344/116660403-8df18800-a9c5-11eb-8020-98fc75722854.png)
 "dependencies": {
	"@ant-design/icons-vue": "^6.0.1",
	"ant-design-vue": "^2.1.3",
	"axios": "^0.21.1",
	"vue": "^3.0.11",
}
移上去报一批移下来报一批

**Comment by Hello-Alex-Cheng** [comment]
![image](https://user-images.githubusercontent.com/29221658/116969012-23538b80-ace8-11eb-9785-bb95eaf2700a.png)

通过 v-for 去循环 a-menu-item 就会出现这个问题，如果只是简单的利用 ant-design-vue 的官网的例子就不会出现这个问题。
感觉这个问题好奇怪啊。

![image](https://user-images.githubusercontent.com/29221658/116969176-61e94600-ace8-11eb-9693-6ef1eadcbdc2.png)

**Comment by Hello-Alex-Cheng** [comment]
Ops，，，I got the same problem. But I don't know why，Mark.

**Comment by varzy** [comment]
Same problem.

**Comment by yexiaodong** [comment]
解决了吗？

**Comment by akirarika** [comment]
+1

**Comment by zhuxianglong** [comment]
我也遇到这个问题

**Comment by ais-one** [comment]
It may be an ant design problem also, based on the following assumptions...

- there is no warning in 2.1.2 but there is in 2.1.3 of ant-design-vue,
- the vue library version is same...

**Comment by white-007** [comment]
mark!!!!   the same problem

**Comment by 973782523** [comment]
退回2.1.2是正常, 搞了一两个小时....

**Comment by Jmysy** [comment]
升级这几个版本后，菜单无法正常使用

**Comment by icepole-jon** [comment]
这个搭配使用正常
```json
{
    "ant-design-vue": "^2.1.2",
    "vue": "^3.0.11"
}
```
升级antdv到2.1.2以上就会报警告，但是使用正常

**Comment by natuan62** [comment]
- I hame same problem with `a-collapse`

![image](https://user-images.githubusercontent.com/10808157/118068223-33e0c180-b3cc-11eb-9e3f-6300922c7c01.png)

```
// package.json

"ant-design-vue": "2.1.4",
"vue": "3.1.0-beta.3",
```

**Comment by 973782523** [comment]
> * I hame same problem with `a-collapse`
> 
> ![image](https://user-images.githubusercontent.com/10808157/118068223-33e0c180-b3cc-11eb-9e3f-6300922c7c01.png)
> 
> ```
> // package.json
> 
> "ant-design-vue": "2.1.4",
> "vue": "3.1.0-beta.3",
> ```

You try to
"ant-design-vue": "2.1.2",

**Comment by zhenzhenChange** [comment]
我的菜单有50多个，每次热更新之后就会报警告，改几次代码之后警告4000多个，当场卡死😭😭😭😭😭

**Comment by tangjinzhou** [comment]
是因为 组件库用的 11构建出来的版本，所以降级 vue 没有效果
我用 10 构建一个版本出来吧

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/07b4150966411f32a36376f9f2b0c7615b0c148a

**Comment by tangjinzhou** [comment]
update 2.1.6

**Comment by tangjinzhou** [comment]
vue 同步使用 3.0.10
依然还有少量 warning ，等待 vue 修复了

**Comment by ais-one** [comment]
> 我的菜单有50多个，每次热更新之后就会报警告，改几次代码之后警告4000多个，当场卡死😭😭😭😭😭

I am requesting for vue team the increase the urgency from p3-minor-bug, it should be p1

https://github.com/vuejs/vue-next/issues/3695#issuecomment-840665259

**Comment by zhenzhenChange** [comment]
> > 我的菜单有50多个，每次热更新之后就会报警告，改几次代码之后警告4000多个，当场卡死😭😭😭😭😭
> 
> I am requesting for vue team the increase the urgency from p3-minor-bug, it should be p1
> 
> [vuejs/vue-next#3695 (comment)](https://github.com/vuejs/vue-next/issues/3695#issuecomment-840665259)

Good brother thank you ~

After replacing this item with `v2.1.6` for my 50+ menus, the warning was removed and another small item was synchronized with the version and there was actually, hahaha my goodness

**Comment by zhenzhenChange** [comment]
> vue 同步使用 3.0.10
> 依然还有少量 warning ，等待 vue 修复了

辛苦了

**Comment by Kunkka0229** [comment]
同样的问题

**Comment by jackywu** [comment]
还没有最终解决么？菜鸟也踏入此坑了。

**Comment by bao2314483** [comment]
> update 2.1.6

我刚刚试了2.16 
vue:3.0.10
依然有警告

**Comment by lizaiya** [comment]
我刚刚试了2.16
vue:3.0.10
依然有警告

**Comment by ais-one** [comment]
Hi All,

If you want to bring the issue to attention of VueJS maintainers, the issue link is here...

https://github.com/vuejs/vue-next/issues/3695

**Comment by arthur-0595** [comment]
mark！

**Comment by chenhaizano** [comment]
mark

### package.json dependencies

>  "ant-design-vue": "^2.1.6",  
> "vue": "^3.0.0",

### components

> Menu

### warn
`
Set operation on key "default" failed: target is readonly.
`

**Comment by pprory** [comment]
mark!

**Comment by wwhsuccess** [comment]
还是这个问题，一直没法解决。

**Comment by zhangshaoying19** [comment]
"ant-design-vue": "2.1.2",
  "axios": "^0.21.1",
  "vue": "3.0.11",

  "vite":^2.3.3

这样没warning

**Comment by ais-one** [comment]
Hi,

The fixes have been merged... https://github.com/vuejs/vue-next/pull/3698

Please wait for the next update of vue-next, and then try out the fixes.

The fix for this issue currently depends on vue and not ant-design-vue team.

**Comment by xiaohuaye** [comment]
mark

**Comment by dokodream** [comment]
![image](https://user-images.githubusercontent.com/41332133/120600949-ec55ce80-c47b-11eb-9d2c-d8d9cee26204.png)
![image](https://user-images.githubusercontent.com/41332133/120600969-f24baf80-c47b-11eb-8441-32913008659e.png)
只要是修改`:selectedKeys`的引用值就会报这个问题，不是vue的问题

**Comment by fuyongshuai7** [comment]
mark

**Comment by qiuyaofan** [comment]
> v2.1.2 没有此问题

然而，vite build会报错～
[#3895](https://github.com.cnpmjs.org/vueComponent/ant-design-vue/issues/3895)

**Comment by Sandural** [comment]
"vue": "^3.0.0",
"ant-design-vue": "2.1.6",
still warngings.....

**Comment by Sandural** [comment]
> "ant-design-vue": "2.1.2",
> "vue": "3.0.11",
> 
> "vite":^2.3.3
> 
> no warning

实测可用!!! "ant-design-vue": "2.1.6" 却报错!!

**Comment by ais-one** [comment]
vue 3.1.1 has no more working but has a problem with layout is created...

https://github.com/vueComponent/ant-design-vue/issues/4173

**Comment by 335296558** [comment]
The version I use is:
"vite": "2.1.5"
"vue": "3.0.10" || "vue": "3.0.11"
Both Set operation on key "default" failed: target is readonly. Question。

Then I updated vue to "vue": "3.1.1" The problem was solved
