### ISSUE TITLE
row-selection param cause cannot read property '__disableEmitter' of undefined

### ISSUE THREAD

**Issue by wjaven** [vueComponent/ant-design-vue#3999]
### Version
2.1.3

### Environment
"ant-design-vue": "2.1.3",
"vue": "3.0.11",
"vue-router": "4.0.3",
"vue-i18n": "9.1.6"

### Steps to reproduce
When I change page (vue-router)，the errors happen. And found that when I delete row-selection param in a-table,It won't happen。
```
vue-i18n.esm-bundler.js?47e2:1775 Uncaught (in promise) TypeError: Cannot read property '__disableEmitter' of undefined
at Proxy.beforeUnmount (vue-i18n.esm-bundler.js?47e2:1775)
at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
at Array.hook.__weh.hook.__weh (runtime-core.esm-bundler.js?5c40:1953)
at invokeArrayFns (shared.esm-bundler.js?9ff4:470)
at unmountComponent (runtime-core.esm-bundler.js?5c40:4824)
at unmount (runtime-core.esm-bundler.js?5c40:4736)
at unmountChildren (runtime-core.esm-bundler.js?5c40:4864)
at unmount (runtime-core.esm-bundler.js?5c40:4760)
at unmountChildren (runtime-core.esm-bundler.js?5c40:4864)
```
I have found a similar issue in ['vue-i18n-next'](https://github.com/intlify/vue-i18n-next/issues/412) and show it's solved in vue@3.0.10 or later, but I use vue@3.0.11. And I found use row-selection param in a-table it happen again. So, I can not sure what's the problem with it.

        
![image](https://user-images.githubusercontent.com/22413497/116181432-2d581600-a74d-11eb-840b-9d6a075c935f.png)

**Comment by wjaven** [comment]
I found the unmountComponent is this when the error happen.
![image](https://user-images.githubusercontent.com/22413497/116333078-79669180-a805-11eb-91b5-8b7e9b29871f.png)

**Comment by wjaven** [comment]
Now I found that when I remove fixed setting in row-selection, the error It didn't happen too.

**Comment by ngwinglam** [comment]
> Now I found that when I remove fixed setting in row-selection, the error It didn't happen too.

I found that the problem may occurred in the component `SelectionCheckboxAll` in Table. When you use the `fixed` and `columnTitle` setting in rowSelection, the error will not happen.

**Comment by wjaven** [comment]
> > Now I found that when I remove fixed setting in row-selection, the error It didn't happen too.
> 
> I found that the problem may occurred in the component `SelectionCheckboxAll` in Table. When you use the `fixed` and `columnTitle` setting in rowSelection, the error will not happen.

**Comment by wjaven** [comment]
> > Now I found that when I remove fixed setting in row-selection, the error It didn't happen too.
> 
> I found that the problem may occurred in the component `SelectionCheckboxAll` in Table. When you use the `fixed` and `columnTitle` setting in rowSelection, the error will not happen.

I haved try this and It is, but I will use SelectionCheckboxAll. There is something wrong, but I'm not sure which dependency caused the problem.

**Comment by lzdzjl** [comment]
This problem can be avoided by setting fixed in rowselection to flase and then configuring the CSS style of table.
