### ISSUE TITLE
When the AutoComplete autocomplete class uses the option that passes #dataSource directly, the console will report warning.js? 2149:6 Warning: [antdv: AutoComplete] `dataSource` is deprecated, please use `options` instead.

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue#4004]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
2.1.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3210](https://github.com/vueComponent/ant-design-vue/issues/3210)

### Steps to reproduce
warning.js?2149:6 Warning: [antdv: AutoComplete] `dataSource` is deprecated, please use `options` instead.

### What is expected?
希望不要显示此警告

### What is actually happening?
warning.js?2149:6 Warning: [antdv: AutoComplete] `dataSource` is deprecated, please use `options` instead.

**Comment by John60676** [comment]
谷歌翻译：**警告：[antdv：自动完成] `dataSource` 已过时，请改用 `options`。**

**Comment by cff-github** [comment]
请问不用datasource如何才才自定义选项
