### ISSUE TITLE
AutoComplete The console will report an error when using the option that directly passes #dataSource to the AutoComplete component. It is not recommended to use the datasource. How can I customize the options with options?

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue#4012]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
2.1.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3210](https://github.com/vueComponent/ant-design-vue/issues/3210)

### Steps to reproduce
AutoComplete 自动完成组件在使用 #dataSource 自定义Option时控制台会报错(不推荐使用datasource,建议用options),请问如何用options自定义选项

### What is expected?
希望能自定义选项并且控制台不报错

### What is actually happening?
AutoComplete 自动完成级件在使用直接传递 #dataSource 的Option时控制台会报错不推荐使用datasource,请问如何用options自定义选项

**Comment by zkwolf** [comment]
就是prop改名了吧

**Comment by zzxxiinn** [comment]
https://github.com/vueComponent/ant-design-vue/blob/3a93f198dfe2207dd327ab48ed7ccd5f3b4439ce/components/auto-complete/index.tsx#L17-L23

由于上面的定义，下面这里的代码判断 `'dataSource' in slots` 会为 true

https://github.com/vueComponent/ant-design-vue/blob/93c2bc15525a7953556b586e0a94799d4117db08/components/auto-complete/index.tsx#L45

所以这里是需要改进的。

**Comment by zkwolf** [comment]
@John60676

**Comment by John60676** [comment]
@zzxxiinn 你是不是看错了，定义的是 `props`，判断的是 `'dataSource' in slots`，怎么会是 `true`

**Comment by zzxxiinn** [comment]
@John60676 感谢回复指出，上面是我引用的不对。不过我在 error stack 中看到报错是
```javascript
// webpack:///./node_modules/ant-design-vue/es/auto-complete/index.js?28da
 setup: function setup(props, _ref) {
    var slots = _ref.slots;
    warning(!('dataSource' in props || 'dataSource' in slots), 'AutoComplete', '`dataSource` is deprecated, please use `options` instead.');
    return {
      configProvider: inject('configProvider', defaultConfigProvider),
      popupRef: null,
      select: null
    };
  },
```
用的 antd 版本是 `version "2.1.6"`

**Comment by John60676** [comment]
@zzxxiinn 这个 issue 在 `2.2.0-beta.5` 解决的，你可以更新一下版本
