### ISSUE TITLE
The expandedRowRender slot of a-table cannot be rendered when the component is used by the browser

### ISSUE THREAD

**Issue by mqhe2007** [vueComponent/ant-design-vue#4014]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
macos v11.3；Microsoft Edge v90.0.810.1；Vue v3.0.11；ant-design-vue v2.1.3

### Reproduction link
[https://jsfiddle.net/mqhe2007/kn5emLvg/17/](https://jsfiddle.net/mqhe2007/kn5emLvg/17/)

### Steps to reproduce
1. 以浏览器引入方式使用ant-design-vue
2. 使用a-table组件并设置expandedRowRender插槽

### What is expected?
表格第一列渲染出可展开的按钮

### What is actually happening?
表格没有渲染出控制展开的第一列

**Comment by zkwolf** [comment]
https://jsfiddle.net/0yes4t6v/2/ 可以这样，浏览器引入的话slot name都会被lower处理掉

**Comment by mqhe2007** [comment]
> https://jsfiddle.net/0yes4t6v/2/ 可以这样，浏览器引入的话slot name都会被lower处理掉

可以了，非常感谢！
