### ISSUE TITLE
a-table 使用 template 配置 column的scopedSlots  表格列无法渲染列 slot 内容

### ISSUE THREAD

**Issue by winken168** [vueComponent/ant-design-vue#403]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.1

### Environment
msox   chrome   vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/81rv6x4y5j)

### Steps to reproduce
<template>
<div>
<a-table
:columns="gridColumns"
:dataSource="dataSource"
:rowKey="rowKey"
:pagination="pagination"
:rowSelection="{
selectedRowKeys: selectedRowKeys,
onChange: updateSelect
}"
>
<template v-for="item in columnSlots">

<a-tag
v-if="item.slot == 'tag'"
:slot="item.key"
slot-scope="text,
record"
:color="record[item.key] == 1 ? 'blue' : 'red'"
:key="item.key"
>{{ renderYesNo(record[item.key]) }}</a-tag
>
</template>

<a-tag
slot="ismenu"
slot-scope="text,
record"
:color="record['ismenu'] == 1 ? 'blue' : 'red'"
key="ismenu"
>{{ renderYesNo(record["ismenu"]) }}</a-tag
>

</a-table>
</div>
</template>

<script>
import ATable from "ant-design-vue/es/table/Table";
export default {
name: "App",
props: {
。。。
},
data() {
return {
。。。。
columnSlots: [],
needTotalList: []
};
},
methods: {
updateSelect(selectedRowKeys, selectedRows) {
。。。。
},
/**表格数据字段初始化 */
gridColumns_init() {
const that = this;
this.gridColumns = this.columnsConfigs.map(item => {
let column = {
width: item.width,
title: item.cn_name || item.en_name,
key: item.en_name || item.cn_name,
gid: item.gid
};
if (item.ctr_type == "bit") {
column.scopedSlots = { customRender: item.en_name || item.cn_name };
that.columnSlots.push({ key: item.en_name, slot: "tag" });
} else {
column.dataIndex = item.en_name;
}
return column;
});

console.log("columnSlots-->", this.columnSlots);

this.loadDatas();
},
/** 加载表格字段配置信息 */
loadConfig() {
this.columnsConfigs = [
{
gid: "2019010803260500046",
en_name: "gid",
cn_name: "主键",
ctr_type: "text"
},
{
gid: "2019010803260500058",
en_name: "ismenu",
cn_name: "是否是菜单",
ctr_type: "bit"
},
{
gid: "2019010803260500061",
en_name: "isopen",
cn_name: "是否打开",
ctr_type: "bit"
}
];
},
/** 加载表格数据 */
loadDatas() {
this.dataSource = [
{
isopen: 1,
gid: "100000000000000001",
ismenu: 1
},
{
isopen: 1,
gid: "100000000000000002",
ismenu: 1
},
{
isopen: 1,
gid: "100000000000000003",
ismenu: 1
},
{
isopen: 1,
gid: "100000000000000004",
ismenu: 0
},
{
isopen: 0,
gid: "100000000000000005",
ismenu: 1
},
{
isopen: 0,
gid: "100000000000000006",
ismenu: 1
}
];
},

renderYesNo(val) {
return val === 0 || val === "0" ? "否" : "是";
}
},
watch: {
columnsConfigs: function() {
this.gridColumns_init();
}
},
created() {
this.loadConfig();
}
};
</script>

<style></style>

### What is expected?
<template v-for="item in columnSlots">

<a-tag
v-if="item.slot == 'tag'"
:slot="item.key"
slot-scope="text,
record"
:color="record[item.key] == 1 ? 'blue' : 'red'"
:key="item.key"
>{{ renderYesNo(record[item.key]) }}</a-tag
>
</template>

这样使用模板循环绑定的方式无法实现既定的效果，能否这样使用？或有没其它的方式。

### What is actually happening?
colum slot 能正常渲染出这一列的内容 ： {
gid: "2019010803260500061",
en_name: "isopen",
cn_name: "是否打开",
ctr_type: "bit"
}

**Comment by winken168** [comment]
问题代码请看  https://codesandbox.io/s/81rv6x4y5j

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/zwxmq0m5p
