### ISSUE TITLE
where do I need to find these types of Columns in the table?

### ISSUE THREAD

**Issue by Darma1106** [vueComponent/ant-design-vue#4034]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Typescript代码完整性

### What does the proposed API look like?
Columns

**Comment by zkwolf** [comment]
在table/interface.ts里export了

**Comment by Ttou** [comment]
columns 的类型错了，应该包个数组
