### ISSUE TITLE
export FieldDecoratorOptions

### ISSUE THREAD

**Issue by henrycjchen** [vueComponent/ant-design-vue#4035]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
antd-vue 1.x

### Environment
-

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
-

### What is expected?
I want to use type FieldDecoratorOptions, but it is not exported

### What is actually happening?
I can not get the type FieldDecoratorOptions

**Comment by zkwolf** [comment]
1.x?

**Comment by henrycjchen** [comment]
yes, both FieldDecoratorOptions in form and form-model need to be exported

**Comment by henrycjchen** [comment]
active
