### ISSUE TITLE
confirm模态框的确定按钮的okButtonProps属性使用无效...

### ISSUE THREAD

**Issue by cschensai** [vueComponent/ant-design-vue#404]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://tangjinzhou.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by marswong** [comment]
$confirm 的用法如下：

```js
this.$confirm({
    okButtonProps: {
        loading: true,
    },
});
```

和 component 的用法不一样：

```vue
<a-modal
    :okButtonProps="{ props: { loading: true } }"
></a-modal>
```

感觉 component API 的实现坑了不少人。。。
