### ISSUE TITLE
The layout of the table component is disordered when using fixed

### ISSUE THREAD

**Issue by weed-x** [vueComponent/ant-design-vue#4041]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
macOS 11.2.3 /  Chrome 90.0.4430.93 / Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-es0b9)

### Steps to reproduce
程序运行即发生布局错乱

### What is expected?
希望大佬能看一下

### What is actually happening?
布局错乱已经影响到正常使用了

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/117599639-c9861200-b17c-11eb-8514-0359d451bf9f.png)
哪里乱了

**Comment by weed-x** [comment]
<img width="1879" alt="WX20210510-111915@2x" src="https://user-images.githubusercontent.com/66823026/117601721-9c882e00-b181-11eb-929b-47f2403e591c.png">
多刷新浏览器就会出现的，不是必现。
