### ISSUE TITLE
Table X-axis and Y-axis scroll bar always show

### ISSUE THREAD

**Issue by eyunhua** [vueComponent/ant-design-vue#4044]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
macOs 10.15.7,chrome 90.0.0.4430.85,vue3.0.11,ant-desgn-vue2.1.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-table-qxpjm)

### Steps to reproduce
内容宽度和高度没有超出父级的宽度和高度时，没有出现滚动条，但是仍显示滚动条占位

### What is expected?
不出现滚动条占位，overflow: auto

### What is actually happening?
出现滚动条占位，overflow:scroll

**Comment by xiaoyudesu** [comment]
I have this issues too。

**Comment by asunaCC** [comment]
加一，上次领导问，怎么在不超出的时候隐藏，我一脸尴尬
