### ISSUE TITLE
issueThe table tree data cannot be expanded after using "ExpandedrowKeys"

### ISSUE THREAD

**Issue by ghf961380551** [vueComponent/ant-design-vue#4058]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
windows ,chorme 89.0.4389.90,vue 2

### Reproduction link
[https://www.antdv.com/components/table/#components-table-demo-tree-data](https://www.antdv.com/components/table/#components-table-demo-tree-data)

### Steps to reproduce
issueThe table tree data cannot be expanded after using "ExpandedrowKeys"

### What is expected?
设置"ExpandedrowKeys"默认展开行的时候 能够正常展开 收起行

### What is actually happening?
无法展开和收起

**Comment by John60676** [comment]
文档问题
