### ISSUE TITLE
希望在 input  的组件中添加一个快速清空的功能

### ISSUE THREAD

**Issue by vxhly** [vueComponent/ant-design-vue#406]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有的时候，在 input 里面写了非常非常多的东西，然后突然发现需要删掉重写，那么选择 Ctrl A 在按 delete 的体验不佳，可以在 input 里面添加 一个 clearable 用以清空 input 里面的内容，就如 http://element-cn.eleme.io/#/zh-CN/component/input#ke-qing-kong 这样的

### What does the proposed API look like?

参数	(clearable)            说明   (是否可清空)               类型 (boolean)            默认值(false)
| 参数	 | 说明 | 类型 |
| ------ | ------ | ------ |
| clearable | 是否可清空 | boolean |

```html
<a-input   clearable >
```

**Comment by tangjinzhou** [comment]
Duplicate of #395
