### ISSUE TITLE
A hierarchy is also displayed when the Cascader component Children is empty

### ISSUE THREAD

**Issue by sarahMmh** [vueComponent/ant-design-vue#4061]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
macOS Catalina 10.15.7、Chrome 90.0.4430.85，Vue3.0,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/smoosh-shadow-dz3zj?file=/src/components/CascaderDemo.vue)

### Steps to reproduce
选择到最后一个层级进行点击的时候，右侧会多出来一个空白层级

### What is expected?
最后一个层级的children是空数组的时候不要出现一个空白层级

### What is actually happening?
最后一个层级的children是空数组的时候会出现一个空白层级

**Comment by ajuner** [comment]
可以把空的children设置成null试试

**Comment by sarahMmh** [comment]
> 可以把空的children设置成null试试

设置成null是可以的，但是这样就会多一步操作数据，希望能够在是空数组的时候就不需要重新操作数据了
