### ISSUE TITLE
style conflicts with tailwind css

### ISSUE THREAD

**Issue by boot-vue** [vueComponent/ant-design-vue#4066]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue 3

### Reproduction link
[https://github.com/boot-vue/bug](https://github.com/boot-vue/bug)

### Steps to reproduce
git clone https://github.com/boot-vue/bug.git

cd vite1

yarn install

yarn dev

open http://localhost:3000/

### What is expected?
antv message style performance normal

### What is actually happening?
message box icon position is unnormal

---
It is affected by tailwind css, but I don't know  which style in tailwind css led to this result

**Comment by sendya** [comment]
**ant-design-vue override my global styles!**

Yes, ant-design-vue is designed to develop a complete background application, we override some global styles for styling convenience, and it can't be removed now. More info trace https://github.com/ant-design/ant-design/issues/4331 .

**Comment by boot-vue** [comment]
> **ant-design-vue override my global styles!**
> 
> Yes, ant-design-vue is designed to develop a complete background application, we override some global styles for styling convenience, and it can't be removed now. More info trace [ant-design/ant-design#4331](https://github.com/ant-design/ant-design/issues/4331) .

ok, I known how to resolve.  [tailwind](https://tailwindcss.com/docs/preflight#disabling-preflight)
