### ISSUE TITLE
When the element size changes, fixed columns cannot rendered correctly 

### ISSUE THREAD

**Issue by arsqu** [vueComponent/ant-design-vue#4082]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
windows 10/Edg/91.0.864.19/Vue 2.6.10

### Reproduction link
[https://jpm9i.csb.app/](https://jpm9i.csb.app/)

### Steps to reproduce
step1: open the link
step2: Set the browser size to 1200-1300 pixels
step3: collapse or expand menu

### What is expected?
fixed columns can be rendered correctly

### What is actually happening?
render wrong

<hr/>
When you collapse or expand the menu, you need to actively trigger the window to resize

**Comment by zkwolf** [comment]
#1493 你的复现是1.6.2，应该在1.6.5修复了

**Comment by arsqu** [comment]
> #1493 你的复现是1.6.2，应该在1.6.5修复了

当我展开或关闭左侧菜单栏时 ，如果 thead 的高度发生了变化，固定列 tr 的高度的高度还是变化前的，就会导致错位

**Comment by zkwolf** [comment]
似乎确实有点问题
