### ISSUE TITLE
升级到1.3.1后，文本框输入时，控制台报错

### ISSUE THREAD

**Issue by wuxj** [vueComponent/ant-design-vue#409]
![image](https://user-images.githubusercontent.com/3871484/51244333-d08f2200-19bf-11e9-902f-f172391fc053.png)

**Comment by wuxj** [comment]
![image](https://user-images.githubusercontent.com/3871484/51244524-43000200-19c0-11e9-8829-704711898b6c.png)
错误 信息如上，把模块卸载了重新install,始终出错，请问我还需要做什么呢？

**Comment by tangjinzhou** [comment]
固定1.3.0版本

**Comment by tangjinzhou** [comment]
下个版本会修复   或者form 使用最新的api
