### ISSUE TITLE
The date and time picker selects the day, the date and time interval that appears is the same date and time seconds

### ISSUE THREAD

**Issue by moonwaystudio** [vueComponent/ant-design-vue#4092]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue3 chrome macos10.15.7

### Reproduction link
[https://antdv.com/components/date-picker-cn/](https://antdv.com/components/date-picker-cn/)

### Steps to reproduce
点击today出现的日期时间区间为同一日期时间秒

### What is expected?
今天的区间,比如现在是2021/10/10 12:30:58  那么选择的区间为 2021/10/10 0:0:0 ~ 2021/10/10 12:30:58

### What is actually happening?
2021/10/10 12:30:58 ~ 2021/10/10 12:30:58

**Comment by zkwolf** [comment]
自定义ranges的值即可
