### ISSUE TITLE
ant-design-vue ---component--Calendar

### ISSUE THREAD

**Issue by childJzl** [vueComponent/ant-design-vue#4093]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
chrom浏览器 ，版本 90.0.4430.212（正式版本） （64 位）    操作系统 Win10。

### Reproduction link
[https://2x.antdv.com/components/calendar-cn](https://2x.antdv.com/components/calendar-cn)

### Steps to reproduce
Calendar 月份选择, 1月 - 12月 ，在12月的正下方,多了个12.官网展示也是如此,12月下面多了个12.

### What is expected?
期望12月下面的12消失

### What is actually happening?
Calendar 月份 1月 - 12月 ，在12月的正下方 多了个12.官网展示也是如此,12月下面多了个12.

---
没了.

**Comment by zkwolf** [comment]
组件库已经修了，等网站更新吧
