### ISSUE TITLE
AutoComplete can not clear placeholder automatic in  Lookup-Patterns 

### ISSUE THREAD

**Issue by wubiandaxian** [vueComponent/ant-design-vue#4094]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
windows， Chrome(89.0.4389.114)， 3.0.11

### Reproduction link
[https://2x.antdv.com/components/auto-complete#API](https://2x.antdv.com/components/auto-complete#API)

### Steps to reproduce
In Lookup-Patterns , when typing Chinese，the placeholder would not disappear before choose a word. But the character typed already in the input box

### What is expected?
The placeholder can disappear automatic when I typing character , no matter in English or Chinese

### What is actually happening?
In Lookup-Patterns , when typing Chinese，the placeholder would not disappear before choose a word.

**Comment by zkwolf** [comment]
先把placeholder加到a-input上吧

**Comment by zkwolf** [comment]
文档我同步修改了，等网站更新

**Comment by wubiandaxian** [comment]
> 文档我同步修改了，等网站更新

组件这个问题会更新么

**Comment by zkwolf** [comment]
我还是比较倾向于这算demo写的问题，因为自定义input的话只有值改变的时候状态才会同步到父组件

**Comment by wubiandaxian** [comment]
> 我还是比较倾向于这算demo写的问题，因为自定义input的话只有值改变的时候状态才会同步到父组件

比较奇怪的是，只有“查询模式”会出现这种情况，其它并不会。我已经使用Input代替了，没有问题

**Comment by zkwolf** [comment]
因为查询模式自定义了input，其他的都是用的内部的input，会自己控制
