### ISSUE TITLE
定制主题色不生效

### ISSUE THREAD

**Issue by lumos102** [vueComponent/ant-design-vue#410]
根据文档提示**在 vue cli 3中定制主题**方式定制主题色修改vue.config.js，且已根据“如果你是通过 'ant-design-vue/dist/antd.css' 引入样式的，改为 ant-design-vue/dist/antd.less。”提示修改成.less。没有生效，请问和vue cli3.0 新建时选的stylus有关吗

**Comment by leehf** [comment]
> 根据文档提示**在 vue cli 3中定制主题**方式定制主题色修改vue.config.js，且已根据“如果你是通过 'ant-design-vue/dist/antd.css' 引入样式的，改为 ant-design-vue/dist/antd.less。”提示修改成.less。没有生效，请问和vue cli3.0 新建时选的stylus有关吗

 看到这个 刚好解决  谢谢！

**Comment by ensignwy** [comment]
> > 根据文档提示**在 vue cli 3中定制主题**方式定制主题色修改vue.config.js，且已根据“如果你是通过 'ant-design-vue/dist/antd.css' 引入样式的，改为 ant-design-vue/dist/antd.less。”提示修改成.less。没有生效，请问和vue cli3.0 新建时选的stylus有关吗
> 
> 看到这个 刚好解决 谢谢！

请问如何解决的
