### ISSUE TITLE
Switch component is missing onClick and onChange attributes

### ISSUE THREAD

**Issue by wubiandaxian** [vueComponent/ant-design-vue#4101]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
tsx中，Switch 组件缺失onClick和onChange属性

### What does the proposed API look like?
<Switch onClick={clickEvent}/>

**Comment by ajuner** [comment]
https://github.com/vueComponent/ant-design-vue/pull/3994

**Comment by ajuner** [comment]
更新下版本

**Comment by wubiandaxian** [comment]
> 更新下版本

OK，新版本有的
