### ISSUE TITLE
@ant-design/icon-vue build is not introduced on demand after build

### ISSUE THREAD

**Issue by white-007** [vueComponent/ant-design-vue#4104]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
版本：2.14        
### What problem does this feature solve?
@ant-design/icon-vue build后不是按需引入的，项目中只这样（import { UpOutlined, DownOutlined } from '@ant-design/icons-vue'）引入了几个图标，但是build出来后是把所有的图标都引入了，导致@ant-design这个包很大

### What does the proposed API look like?
@ant-design/icon-vue build后不要全量引入，只构建使用了的图标

<img width="1294" alt="WeChat4d000b00cb20721a84e7f1b7ef66f5b9" src="https://user-images.githubusercontent.com/12726827/118944381-193bb900-b987-11eb-8520-eec8573c0656.png">

**Comment by tangjinzhou** [comment]
说的是组件库  还是自己项目

**Comment by white-007** [comment]
自己的项目，build后图标是全量引入的

**Comment by white-007** [comment]
> 说是组件库还是自己的项目
自己的项目，build后图标是全量引入的，但是我只用了几个图标。

**Comment by zkwolf** [comment]
可以考虑像组件库一样`import CloseCircleFilled from '@ant-design/icons-vue/CloseCircleFilled'`处理引入，或者拿babel-plugin-import加个配置处理一下

**Comment by white-007** [comment]
> 可以考虑像组件库一样`import CloseCircleFilled from '@ant-design/icons-vue/CloseCircleFilled'`处理引入，或者拿babel-plugin-import加个配置处理一下

babel-plugin-import我试了，打包还是全量的，感谢
