### ISSUE TITLE
The Select component cannot trigger the inputKeydown event

### ISSUE THREAD

**Issue by FreedomFoolt** [vueComponent/ant-design-vue#4108]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
"vue": "^3.0.11"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dank-bird-b3e42?file=/src/components/HelloWorld.vue)

### Steps to reproduce
在Select组件中通过键盘录入新的标签，并不能触发inputKeydown事件

### What is expected?
控制台输出 `handleInputTag`

### What is actually happening?
控制台没有输出

**Comment by John60676** [comment]
文档问题，改成 `inputKeyDown` 即可
