### ISSUE TITLE
定制颜色不生效

### ISSUE THREAD

**Issue by lumos102** [vueComponent/ant-design-vue#411]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.1

### Environment
win10 chrome

### Reproduction link
[https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme](https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme)

### Steps to reproduce
根据文档提示在“vue cli 3中定制主题方式”定制主题色修改了vue.config.js文件，且已根据“如果你是通过 'ant-design-vue/dist/antd.css' 引入样式的，改为 ant-design-vue/dist/antd.less。”提示修改成.less。没有生效，请问和vue cli3.0 新建时选的stylus有关吗

### What is expected?
换肤

### What is actually happening?
定制颜色没有生效

**Comment by wangxueliang** [comment]
提供了vue-cli3的 Ant Design Vue 插件（https://github.com/vueComponent/vue-cli-plugin-ant-design），可以参考下~

**Comment by sendya** [comment]
也可以参考一下 

https://github.com/sendya/ant-design-pro-vue/blob/master/vue.config.js#L42
https://github.com/sendya/ant-design-pro-vue/blob/master/src/core/use.js#L8

**Comment by lumos102** [comment]
项目中按钮列表什么的现在的颜色是实现自定义了。只是layout布局中的layout-header的颜色按说应该也是主题色。看到ant-design-vue文档目前主题色是#7dbcea，layout-header的颜色也是#7dbcea，控制台看到它覆盖了原本的#001529。我本地用了绿色的主题色，但是layout-header的颜色还是#001529

**Comment by sendya** [comment]
我不清楚你说的 layout-header 颜色是哪一块的颜色。并且这个应该不属于颜色变量控制的
目前有提供控制的颜色变量应该就

```
@primary-color: #1890ff;                         // 全局主色
@link-color: #1890ff;                            // 链接色
@success-color: #52c41a;                         // 成功色
@warning-color: #faad14;                         // 警告色
@error-color: #f5222d;                           // 错误色
@font-size-base: 14px;                           // 主字号
@heading-color: rgba(0, 0, 0, .85);              // 标题色
@text-color: rgba(0, 0, 0, .65);                 // 主文本色
@text-color-secondary : rgba(0, 0, 0, .45);      // 次文本色
@disabled-color : rgba(0, 0, 0, .25);            // 失效色
@border-radius-base: 4px;                        // 组件/浮层圆角
@border-color-base: #d9d9d9;                     // 边框色
@box-shadow-base: 0 2px 8px rgba(0, 0, 0, .15);  // 浮层阴影
```

如果你还需要控制这些原本不被控制颜色的组件或者元素，可以自己在样式中使用上面所述的变量，这样就可以同时跟随主题色变化了

**Comment by lumos102** [comment]
嗯是这样的，layout-header不在默认的主题色控制范围之内。

**Comment by wangxueliang** [comment]
所有样式变量  https://github.com/vueComponent/ant-design-vue/blob/master/components/style/themes/default.less

**Comment by lumos102** [comment]
@wangxueliang @sendya  <br>
嗯是的，看到了，感谢~
