### ISSUE TITLE
vite cannot be compiled

### ISSUE THREAD

**Issue by uinio** [vueComponent/ant-design-vue#4112]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue 3.0.11
vite  2.3.3

![image](https://user-images.githubusercontent.com/49021590/119308393-91fc8700-bc9f-11eb-9713-00eb34893d26.png)

**Comment by zkwolf** [comment]
upgrade @ant-design-vue/use to latest version
