### ISSUE TITLE
Menu component has many warnings under version 2.1.6/2.1.4

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue#4113]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
2.1.4

### Steps to reproduce
Menu组件在2.1.6/2.1.4版下出现很多警告

### What is expected?
清除警告

### What is actually happening?
![image](https://user-images.githubusercontent.com/69131256/119313098-b78c8f00-bca5-11eb-84fa-ffb870a28fc9.png)

**Comment by zs-g** [comment]
我在群里问了   好像vue 的BUG  在等 VUE  改

**Comment by xicheng412** [comment]
same problem.

**Comment by tangjinzhou** [comment]
update to 2.2.0-beta.2
