### ISSUE TITLE
Switch and InputNumber Componnent has no interface export

### ISSUE THREAD

**Issue by Lozoe** [vueComponent/ant-design-vue#4115]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
prod

### Reproduction link
[https://2x.antdv.com/components/input-number-cn](https://2x.antdv.com/components/input-number-cn)

### Steps to reproduce
/

### What is expected?
Provide a type export such as interface.d.ts

### What is actually happening?
When doing component self-encapsulation, the interface definition of the component needs to be inherited

---
Switch and InputNumber Componnents has no interface export

**Comment by John60676** [comment]
`Switch` has exported types
