### ISSUE TITLE
The default value of the a-select component must be undefined to trigger the placeholder attribute display

### ISSUE THREAD

**Issue by sdutwsl** [vueComponent/ant-design-vue#4117]
- [ √] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
Windows 10 ,Chrome 90.0, Vue 2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-zy54q?file=/src/App.vue)

### Steps to reproduce
参考codesandbox的链接

### What is expected?
当select的v-model为null或者空字符串的时候，也应当显示placeholder，或者单独一个属性控制placeholder是否显示

### What is actually happening?
当且仅当v-model为undefined时，才会显示placeholder，众所周知，大家都不想在代码中出现undefined

**Comment by zkwolf** [comment]
https://github.com/ant-design/ant-design/issues/2367
