### ISSUE TITLE
Hope that Modal component will add【beforeClose】callback parameter

### ISSUE THREAD

**Issue by geeklibin** [vueComponent/ant-design-vue#4121]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Modal关闭前的确认、loading等

### What does the proposed API look like?
版本：2.1.2；

当前只有``afterClose``。
希望可以增加``beforeClose``（最好可以支持``Promise``），关闭前执行``beforeClose``，``return false``或``reject``时 不关闭，``return true``或``resolve``时，执行关闭。
```
<a-modal :beforeClose="beforeClose">
//...
</a-modal>

...
const beforeClose = new Promise((resolve,reject) => {
Modal.confirm({
title:'确定要关闭弹窗吗',
onOk:() => {
resolve()
},
onCancel:() => {
reject()
}
})
})
//或
const beforeClose = () => {
return true;
}
```

**Comment by ajuner** [comment]
https://codesandbox.io/s/brave-yalow-tih68?file=/src/App.vue
可以在onOk的事件中传入Promise

**Comment by geeklibin** [comment]
> https://codesandbox.io/s/brave-yalow-tih68?file=/src/App.vue
> 可以在onOk的事件中返回一个Promise

但是 **通过使用组件的方式**时，点击【取消、遮罩层、关闭按钮】时想阻止弹窗的关闭做不到，，事件@cancel与@ok并不支持阻止弹窗的关闭。
### 希望的api是这样的
```
<a-modal :beforeClose="beforeClose" destroyOnClose>
...FORM
</a-modal>
...
let beforeClose = () => new Promise((resolve,reject) => {
   Modal.confirm({
    title:'关闭窗口,填写的资料将丢失，确定关闭吗？',
   onOk:() => {
     resolve()
   },
   onCancel:() => {
     reject()
    }
   })
})
...
```
因为在很多时候，在modal弹窗组件中使用表单时，用户填写信息填写了一半，点击了遮罩层，弹窗就关闭了。
所以希望有一个类似beforeClose的api，在用户填写了一半信息未提交时点击关闭按钮，可以再弹窗提示“关闭窗口资料将丢失，确定关闭吗？”，如果用户点取消，就不关闭该modal

**Comment by geeklibin** [comment]
这是一个例子：https://codesandbox.io/s/determined-wind-fgh7c?file=/src/App.vue
