### ISSUE TITLE
$notification description attribute uses vueNode, img local path is invalid, you need to use {defaultImg} this variable form, and then defaultImg needs to require() in data; also consult how to bind methods in vueNode, such as using @click = "handleClick" or Can only bind methods in funciton(h)? This method is very troublesome when there are multiple levels of nesting.

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#4127]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
win10 64

### Reproduction link
[https://www.antdv.com/components/notification-cn/](https://www.antdv.com/components/notification-cn/)

### Steps to reproduce
one step

### What is expected?
可以正常展示本地路径图片， 可以便捷的绑定事件方法

### What is actually happening?
![image](https://user-images.githubusercontent.com/20763416/119600565-e0ce2c00-be19-11eb-8b2f-f2efb07b1082.png)

**Comment by John60676** [comment]
参考 vuejs/vue-loader/issues/193

**Comment by hugselina2019** [comment]
> 参考 [vuejs/vue-loader/issues/193](https://github.com/vuejs/vue-loader/issues/193)

好的 感谢大佬
