### ISSUE TITLE
There is a problem with the onClick triggering method of the notification. Now it is triggered directly. It should be triggered after the click

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#4128]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
win10 64

### Reproduction link
[https://2x.antdv.com/components/notification-cn/](https://2x.antdv.com/components/notification-cn/)

### Steps to reproduce
（版本1.7.2 & 1.7.5 ）不传参数 是点击后才触发， 传了参数 直接触发了 都没点击； 另外andv最新文档和安装版本是1.7.5 这里为什么选不了1.7.5 最高只到1.7.3 ?

### What is expected?
传参后click才会触发onClick的回调，

### What is actually happening?
没有click, 直接触发了

![image](https://user-images.githubusercontent.com/20763416/119628879-14bc4800-be40-11eb-997f-7dd6a56cd89d.png)

**Comment by hugselina2019** [comment]
大概知道为什么了 传参后它把函数当成了 fn() 立即执行了， 那么现在怎样传参可以不会执行这个fn呢？

**Comment by hugselina2019** [comment]
目前暂时想到一个替代办法， 在notification下面加一层隐藏dom  position: absolute; z-index: 2000; 进行覆盖，这样不管点击这个notify的哪里点击的其实都是这个覆盖dom
然后通过$event与 data-xxx去拿值, 暂时满足了需求， 但是还是希望官网尽早给出正经的传参路子
![image](https://user-images.githubusercontent.com/20763416/119636540-51d80880-be47-11eb-9d10-096b3f90b970.png)

**Comment by John60676** [comment]
```js
onClick: () => this.handleNotfClick(params)
```

**Comment by hugselina2019** [comment]
@John60676  感谢大佬， 对JS函数的理解又进了一步
