### ISSUE TITLE
The checkbox-group setting v-decorator cannot select the corresponding checkbox

### ISSUE THREAD

**Issue by cuijiudai** [vueComponent/ant-design-vue#4136]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
1.7.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-forked-guwe1?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
设置了不好用，
```
<a-checkbox-group
:options="clusters"
:disabled="disabled"
v-decorator="[ 'checkedClusters', { rules: [{ required: true, message: '请选择部署集群'}]}]"
></a-checkbox-group>
```

如果把 v-decorator去掉，用v-model="checkedClusters"是可以选中的。

### What is expected?
checkbox-group 设置  v-decorator 选中对应checkbox

### What is actually happening?
1.4.2发现有问题，升到1.7.5还是不行

**Comment by John60676** [comment]
不懂什么问题，你提供的代码也没能重现你说的问题

![image](https://user-images.githubusercontent.com/21698973/120054141-ccc83b80-c060-11eb-8cf5-998f264b5888.png)

**Comment by cuijiudai** [comment]
@John60676 你截图里有v-model ，去掉v-model。 只用 v-decorator 不是应该就能选中吗？

**Comment by cuijiudai** [comment]
实际环境中同时使用  v-model  ，v-decorator 会报错：

warning.js?4063:34 Warning: `getFieldDecorator` will override `value`, so please don't set `value and v-model` directly and use `setFieldsValue` to set it.

**Comment by John60676** [comment]
https://codesandbox.io/s/vue-antd-template-forked-lwice

**Comment by cuijiudai** [comment]
@John60676 这链接也是不起作用的。我的做法是 setFieldsValue重新set 一次，就选中了

**Comment by John60676** [comment]
![Kapture 2021-06-03 at 17 34 33](https://user-images.githubusercontent.com/21698973/120623715-8de81a80-c492-11eb-93d3-1fdbd74dd04e.gif)

**Comment by cuijiudai** [comment]
你理解错了，不是点击无法选中checkbox。而是初始化的时候 checkedClusters 已经赋值为[1,2]了， 但是value = 1 和 value = 2 的 checkbox 不是选中状态。

**Comment by John60676** [comment]
https://codesandbox.io/s/vue-antd-template-forked-64q8q?file=/src/App.vue

![image](https://user-images.githubusercontent.com/21698973/120625841-a78a6180-c494-11eb-9e84-2a7a29acb9af.png)


看文档

**Comment by cuijiudai** [comment]
能看下 switch 赋初始值问题吗？  v-decorator , initialValue, setFieldsValue都没效果呢，v-model是可以的。   https://codesandbox.io/s/vue-antd-template-forked-64q8q?file=/src/App.vue

**Comment by John60676** [comment]
你先仔细看一遍文档吧

![image](https://user-images.githubusercontent.com/21698973/120630932-e373f580-c499-11eb-9087-d5812781e382.png)

**Comment by cuijiudai** [comment]
抱歉，文档之前看了，的确没看懂，谢谢你的帮助！
如果 switch 必须要写死设置 valuePropName: 'checked',  为啥switch组件不给做兼容处理呢？不懂。
