### ISSUE TITLE
upload组件获取不到后台response

### ISSUE THREAD

**Issue by simonwangtx** [vueComponent/ant-design-vue#414]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.1

### Environment
macos、chrome、vue-cli 3

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/upload-cn/#components-upload-demo-upload-manually](https://vuecomponent.github.io/ant-design-vue/components/upload-cn/#components-upload-demo-upload-manually)

### Steps to reproduce
当使用defaultFileList进行文件列表数据绑定时，控制台打印change正常，能看到”uploading"、“done"状态以及“done”状态下的response字段。使用fileList进行数据绑定时，打印change只有“uploading”状态，无法获取response

### What is expected?
使用fileList进行数据绑定时，能看到”uploading"、“done"状态以及“done”状态下的response字段。

### What is actually happening?
.

**Comment by wangxueliang** [comment]
官网有类似demo，是没有问题的，如果还不行，麻烦提供复现链接
