### ISSUE TITLE
Table select class quasi-tree select drop-down table component

### ISSUE THREAD

**Issue by mansai** [vueComponent/ant-design-vue#4145]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用于数据展示：
企业管理系统经常用到
使用场景：例如物料信息展示（搜索料号时，同时展示品名、规格、单位、库存数量等）

### What does the proposed API look like?
参考示例
https://www.jeasyui.com/demo-vue/main/index.php?plugin=ComboGrid&theme=material-teal&dir=ltr&pitem=&sort=asc

**Comment by zkwolf** [comment]
可以找找有没有第三方开发的组件
