### ISSUE TITLE
Table tree data display, click to expand icon is invalid

### ISSUE THREAD

**Issue by cuijiudai** [vueComponent/ant-design-vue#4146]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
mac:10.15.7 ; chrome:90.0.4430.93;vue:2.6.10

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-tree-data](https://www.antdv.com/components/table-cn/#components-table-demo-tree-data)

### Steps to reproduce
1.7.5 的 官方示例也不行

### What is expected?
table可以正常展开

### What is actually happening?
table树形数据展示 无法展开

**Comment by WAGFS** [comment]
I think you can try to upgrade the antd version , https://2x.antdv.com/components/table-cn#components-table-demo-expand-children

**Comment by cuijiudai** [comment]
> I think you can try to upgrade the antd version , https://2x.antdv.com/components/table-cn#components-table-demo-expand-children

2x version rely on vue 3x， what  makes mass work to update ;

**Comment by WAGFS** [comment]
> > I think you can try to upgrade the antd version , https://2x.antdv.com/components/table-cn#components-table-demo-expand-children
> 
> 2x version rely on vue 3x， what makes mass work to update ;

I tried it, and there is indeed a problem with the 1.7.2 version. You only need to upgrade the version to 1.7.5. As for the official version, I am not sure why it does not work.

**Comment by John60676** [comment]
Duplicate of #4058
