### ISSUE TITLE
Use a-image-preview-group will  appear picture concatenation between multiple components and the order of left and right picture preview is reversed

### ISSUE THREAD

**Issue by WAGFS** [vueComponent/ant-design-vue#4147]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
chrome 90.0.4430.212 （64 bit）、vue 3.0.5

### Reproduction link
[https://2x.antdv.com/components/image-cn#components-image-demo-previewGroup](https://2x.antdv.com/components/image-cn#components-image-demo-previewGroup)

### Steps to reproduce
Introduce this component in any page, click on the image preview, then go back to the home page, and enter another page preview image that references this component. You will find that there is an image from the previous page in the preview image, and when the page image is greater than 2 The order of the pictures switched from left to right is reversed. feeling bad.

### What is expected?
1. Do not cache the address of the preview image in the previous page.
2. When there are multiple pictures on the page, the order of the pictures can be restored to normal by switching the preview pictures left and right.

### What is actually happening?
1. The preview component caches the address of the picture preview in the previous interface.
2. The order of the left and right switching of the picture is reversed.

**Comment by qiuqiux1** [comment]
Hello, excuse me, have you finally solved this problem?I also encountered this bug recently. I don't know what to do。

**Comment by gangchn** [comment]
Is this issue resolve? I still got the same problem in the latest version 3.2.14. @tangjinzhou
