### ISSUE TITLE
p/article/ul will have a default style, can this be cancelled?

### ISSUE THREAD

**Issue by any86** [vueComponent/ant-design-vue#4149]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-g9y1b?file=/src/App.vue)

### Steps to reproduce
如demo所示

### What is expected?
没有默认样式

### What is actually happening?
如demo所示

**Comment by Hyphon** [comment]
这些元素的样式是浏览器添加的默认样式，说明可见 [文档链接](https://www.w3.org/TR/CSS21/cascade.html#cascade)
所以可以通过自己编写的 CSS 进行覆盖，或使用 normalize.css 等 CSS 库进行样式重置

**Comment by any86** [comment]
![image](https://user-images.githubusercontent.com/8264787/122701223-542f5600-d27f-11eb-811f-6cebe1b65c22.png)

![image](https://user-images.githubusercontent.com/8264787/122701294-7b862300-d27f-11eb-821b-3d857073fa99.png)

这个是ant的css, 建议样式都加到具体class上, 有时候用户重置了某一个元素的样式就会影响组件的样式, 这提问过了好几天了, 具体是哪个组件被影响我想不起来了, 我稍后再看到补充个图.

**Comment by Hyphon** [comment]
> 这个是ant的css, 建议样式都加到具体class上, 有时候用户重置了某一个元素的样式就会影响组件的样式, 这提问过了好几天了, 具体是哪个组件被影响我想不起来了, 我稍后再看到补充个图.

你可以参考下 [这个](https://github.com/necolas/normalize.css/issues/765)，按照当时的讨论，标准化旨在使得各个浏览器的表现统一，而非直接将 margin 重置 为 0

**Comment by sendya** [comment]
https://antdv.com/docs/vue/faq-cn/#ant-design-vue-%E8%A6%86%E7%9B%96%E4%BA%86%E6%88%91%E7%9A%84%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F%EF%BC%81

![Uploading image.png…]()

**Comment by any86** [comment]
我的意思是你组件内部的元素不要使用"元素样式"和上面讨论的根本不冲突.  毕竟别的UI组件库可没这个问题, 比如iview和饿了么, 所以这是个开发体验反馈. 走向主创自己定吧. 咱俩没必要讨论"是否元素应该有默认样式"  @Hyphon

**Comment by Hyphon** [comment]
> 我的意思是你组件内部的元素不要使用"元素样式"和上面讨论的根本不冲突.
> 
> 毕竟别的UI组件库可没这个问题, 比如iview和饿了么.
> 
> 所以这是个开发体验反馈. 走向主创自己定吧. 咱俩没必要讨论"是否元素应该有默认样式" @Hyphon

很明显你没明白我所表达的意思。就好像 vue 2.0 使用了 Flow 而非 Typescript 导致 TS 支持不是和好一样，antd 使用了 normalize.css 而出现的问题是技术选型导致的历史问题，不是一句`不要使用`就能解决的了的。
鉴于你的回复态度，这个问题就到此为止。

**Comment by any86** [comment]
我有啥态度... 这么敏感?  喝多少酒啊...

**Comment by Hyphon** [comment]
> 我有啥态度... 这么敏感? 喝多少酒啊...

没有明白别人的表述就直接自说自话，建议你先了解下一些基础知识：
[提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
总之请不用再回复了，谢谢

**Comment by morningbao** [comment]
> > 我有啥态度... 这么敏感? 喝多少酒啊...
> 
> 没有明白别人的表述就直接自说自话，建议你先了解下一些基础知识：
> [提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
> 总之请不用再回复了，谢谢

提问的智慧。。。没人问你吧。。人家回复没有态度，是你太敏感了

**Comment by upupupfly** [comment]
> > 我有啥态度... 这么敏感? 喝多少酒啊...
> 
> 没有明白别人的表述就直接自说自话，建议你先了解下一些基础知识：
> [提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
> 总之请不用再回复了，谢谢

正常技术交流也能破防么，玻璃心吗
