### ISSUE TITLE
message.config 全局配置在vue-cli中如何使用呢

### ISSUE THREAD

**Issue by wuxj** [vueComponent/ant-design-vue#415]
我在 main.js文件中添加 如下代码： 
message.config({
  top: `100px`,
  duration: 2,
  maxCount: 1
})
得到如下的错误，我要怎么配置才能正确使用呢？
![image](https://user-images.githubusercontent.com/3871484/51293850-7e93de00-1a4b-11e9-97ad-052073ad625d.png)

**Comment by zdxweb** [comment]
message配置maxCount为什么不会自动关闭
