### ISSUE TITLE
When using #title and #default slots, a large number of warnings are caused when the mouse is hovered to the Menu menu

### ISSUE THREAD

**Issue by lchrennew** [vueComponent/ant-design-vue#4156]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
MacOSX Big Sur 11.3, Chrome 90.0.4430.212, Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-zhukovsky-cqn0f)

### Steps to reproduce
进入复现页面https://codesandbox.io/s/silly-zhukovsky-cqn0f
打开Chrome浏览器开发者工具-控制台，鼠标浮动到菜单上，查看控制台warning

### What is expected?
没有warnings

### What is actually happening?
很多warnings

![image](https://user-images.githubusercontent.com/1522365/120406720-1b861600-c37e-11eb-9bea-0799591348e9.png)

**Comment by ajuner** [comment]
https://github.com/vueComponent/ant-design-vue/issues/3998
