### ISSUE TITLE
How to eliminate the warning caused by the combination of menu and menuItem?

### ISSUE THREAD

**Issue by daniellan4039** [vueComponent/ant-design-vue#4157]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
macOS 11, chrome89.0, vue3

### Reproduction link
[https://2x.antdv.com/components/form-cn](https://2x.antdv.com/components/form-cn)

### Steps to reproduce
use MenuItem inside Menu component.

### What is expected?
消除警告

### What is actually happening?
控制台打印出警告：Set operation on key "default" failed: target is readonly. {__vInternal: 1, default: ƒ}

**Comment by uniquejava** [comment]
Set operation on key "default" failed: target is readonly.  谢谢还真搜到了。 
相同的代码 `  "ant-design-vue": "^2.1.0",`  好使， 升级到最新的 2.1.4不好使出警告。

```vue
 <a-dropdown :trigger="['click']" class="nav-item">
      <span class="display-name">
        <img src="/src/assets/head-user.png" width="20" class="user-avatar" />
        {{ data.user.displayName }}
        <CaretDownOutlined />
      </span>
      <template #overlay>
        <a-menu @click="doClickUserAvatar">
          <a-menu-item key="logout">ログアウト</a-menu-item>
        </a-menu>
      </template>
    </a-dropdown>
```
每次点下拉菜单都会出这个警告。

**Comment by tangjinzhou** [comment]
update to 2.2.0-beta.2
