### ISSUE TITLE
Input.TextArea does not implemented as a controlled component

### ISSUE THREAD

**Issue by jackhe16** [vueComponent/ant-design-vue#4158]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
mac os 10.15.6, chrome  87.0.4280.141, vue 3.0.11

### Reproduction link
[https://github.com/jackhe16/antdv-textarea](https://github.com/jackhe16/antdv-textarea)

### Steps to reproduce
Input and Input.TextArea do not add onChange event:
- The view does not change when the Input component inputs content
- The view changes when the Input.TextArea component inputs content

### What is expected?
- It should be a controlled component like the Input component
- The view does not change when the Input.TextArea component inputs content

### What is actually happening?
- The view changes when the Input.TextArea component inputs content

---
![1622631967628](https://raw.githubusercontent.com/jackhe16/antdv-textarea/main/resource/1622631967628.jpg)
![1622631976625](https://raw.githubusercontent.com/jackhe16/antdv-textarea/main/resource/1622631976625.jpg)

**Comment by Hyphon** [comment]
You should follow the [Getting Started](https://2x.antdv.com/docs/vue/getting-started) doc.

```
import { createApp } from "vue";
import App from "./App";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";
// add next 3 lines, then it works
+ import Antd from 'ant-design-vue';
+ import 'ant-design-vue/dist/antd.css';

createApp(App)
+  .use(Antd)
  .use(store)
  .use(router)
  .mount("#app");
```

**Comment by jackhe16** [comment]
This is not a issue of style, Input.TextArea should implemented as a controlled component. This means that when I pass the value "text" to Input.TextArea without adding the onChange event, the component should always be displayed as "text" when inputting content in the box.

**Comment by jackhe16** [comment]
Ant-design React版本的Input.TextArea是实现为受控的, 组件props上不指定onChange时, 在视图上输入框内输入内容不会发生变化。

[Codesandbox Demo](https://codesandbox.io/s/agitated-murdock-fgqlu)
