### ISSUE TITLE
The type definition of the ranges property of the RangePicker component is incorrect

### ISSUE THREAD

**Issue by comvir** [vueComponent/ant-design-vue#4159]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
win10,chrome latest,vue3

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges](https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges)

### Steps to reproduce
使用**typescript+jsx**开发时，会出现类型**检查错误**。
RangePicker 组件的**ranges**属性作用是**预设快捷选择的日期范围**，
按照官方文档说明应该接收类型
```typescript
{ [range: string]: moment[] } | { [range: string]: () => moment[] }
```
而当前版本给ranges定义的类型是RangePickerValue
```typescript
// node_modules\ant-design-vue\lib\date-picker\index.d.ts
timePicker?: import("../_util/type").VueNode;\\line:223
showTime?: boolean | Record<string, any>;\\line:224
ranges?: import("./interface").RangePickerValue;\\line:225
```
```typescript
//node_modules\ant-design-vue\lib\date-picker\interface.d.ts line:4
export declare type RangePickerValue = undefined[] | null[] | [moment.Moment | string] | [undefined, moment.Moment | string] | [moment.Moment | string, undefined] | [null, moment.Moment | string] | [moment.Moment | string, null] | [moment.Moment, moment.Moment] | [string, string];
```

虽然这个类型错误并不影响程序最终运行，但是部分使用typescript的项目会因此无法编译

### What is expected?
请修正RangePicker 组件的ranges属性的类型定义

### What is actually happening?
RangePicker 组件的ranges属性的类型定义错误，这会导致部分typescript项目因类型检查错误而无法编译

**Comment by Hyphon** [comment]
RangePickerValue 类型里预设了 startValue 或 endValue 可以为 null/undefined 的情况，如传入 [moment(), undefined] 也是允许的，感觉还是比较合理的。
能不能提供下 Demo 看看具体的场景？

**Comment by comvir** [comment]
> RangePickerValue 类型里预设了 startValue 或 endValue 可以为 null/undefined 的情况，如传入 [moment(), undefined] 也是允许的，感觉还是比较合理的。
> 能不能提供下 Demo 看看具体的场景？

[RangePicker组件的预设日期范围功能](https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges)

**Comment by Hyphon** [comment]
> > RangePickerValue 类型里预设了 startValue 或 endValue 可以为 null/undefined 的情况，如传入 [moment(), undefined] 也是允许的，感觉还是比较合理的。
> > 能不能提供下 Demo 看看具体的场景？
> 
> [RangePicker组件的预设日期范围功能](https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges)

额。我是想说提供一下所说的编译错误的代码 Demo

**Comment by comvir** [comment]
> > > RangePickerValue 类型里预设了 startValue 或 endValue 可以为 null/undefined 的情况，如传入 [moment(), undefined] 也是允许的，感觉还是比较合理的。
> > > 能不能提供下 Demo 看看具体的场景？
> > 
> > 
> > [RangePicker组件的预设日期范围功能](https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges)
> 
> 额。我是想说提供一下所说的编译错误的代码 Demo

这是类型检查错误的提示
![image](https://user-images.githubusercontent.com/7907986/122544492-70ed4300-d05f-11eb-9e02-a12079c42e65.png)
这是为了规避类型检查错误采取的折中办法
![image](https://user-images.githubusercontent.com/7907986/122544749-b3168480-d05f-11eb-98ca-581d1cdc349e.png)
![image](https://user-images.githubusercontent.com/7907986/122544948-de00d880-d05f-11eb-8fb5-19ba25975c6b.png)

**Comment by comvir** [comment]
改不改呀，就要求把date-picker\index.d.ts里面的类型定义改正确，官方文档是你们写的，代码也是你们写的，好好对比一下就明白我在说啥了
