### ISSUE TITLE
Function h from vue can't render  antd Components

### ISSUE THREAD

**Issue by BigDeep** [vueComponent/ant-design-vue#4163]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
os:macOS   Vue:3.0.4

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
follow the step below
```javascript
customRender: (data: unknown) => {
return h(
'a-button',
{
style: { cursor: 'pointer' },
onClick: () => {
console.log(data)
},
type: 'primary',
size: 'small',
},
'edit',
)
},
```
I found that i can't render a  "a-button" , but i can render it while import {Button} from 'ant-design-vue' like below
```javascript
import { Button } from 'ant-design-vue'
customRender: (data: unknown) => {
return h(
Button,
{
style: { cursor: 'pointer' },
onClick: () => {
console.log(data)
},
type: 'primary',
size: 'small',
},
'edit',
)
},
```

### What is expected?
I had global inject antd ,but when i use ”h “ from vue i can't render an antd components by componentsName，
must import it and put it as a parameter into the function h

### What is actually happening?
follow the step below
```javascript
customRender: (data: unknown) => {
return h(
'a-button',
{
style: { cursor: 'pointer' },
onClick: () => {
console.log(data)
},
type: 'primary',
size: 'small',
},
'edit',
)
},
```
I found that i can't render a  "a-button" , but i can render it while import {Button} from 'ant-design-vue' like below
```javascript
import { Button } from 'ant-design-vue'
customRender: (data: unknown) => {
return h(
Button,
{
style: { cursor: 'pointer' },
onClick: () => {
console.log(data)
},
type: 'primary',
size: 'small',
},
'edit',
)
},
```

**Comment by John60676** [comment]
Reference: https://github.com/vuejs/vue-next/issues/1927#issuecomment-678330753

**Comment by BigDeep** [comment]
> Reference: [vuejs/vue-next#1927 (comment)](https://github.com/vuejs/vue-next/issues/1927#issuecomment-678330753)

thanks,it works
