### ISSUE TITLE
Incorrect style of embedded text in split Divider component

### ISSUE THREAD

**Issue by zhenzhenChange** [vueComponent/ant-design-vue#4166]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
### Version

- "ant-design-vue": "2.1.6"

### Environment

- "vue": "3.0.10"

### Reproduction link

[https://2x.antdv.com/components/divider-cn#components-divider-demo-with-text](https://2x.antdv.com/components/divider-cn#components-divider-demo-with-text)

### Steps to reproduce

内嵌文本后线条与文本不居中对齐问题

```html
<Divider>不居中</Divider>
```

粗略检查应该是伪元素 `::after` 、`::before` 多了一行样式：`transform: translateY(50%);`

### What is expected?

居中对齐

### What is actually happening?

不居中

**Comment by zkwolf** [comment]
目前divider应该还是同步的ant design 3.x的样式

**Comment by zhenzhenChange** [comment]
问题倒不是很大，可以先 hack 一波 😂😂

```scss
.ant-divider {
  &::after,
  &::before {
    transform: unset !important;
  }
}
```

**Comment by zhenzhenChange** [comment]
新版本已修复
