### ISSUE TITLE
Popup bubble card document Is this a style bug?

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#4167]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
win10 64

### Reproduction link
[https://2x.antdv.com/components/notification-cn/](https://2x.antdv.com/components/notification-cn/)

### Steps to reproduce
悬停和单击的弹出窗口。

### What is expected?
不知道是不是样式问题？ 还是有什么特殊原因？

### What is actually happening?
不知道是不是样式问题？ 还是有什么特殊原因？

![image](https://user-images.githubusercontent.com/20763416/120877651-52606400-c5ea-11eb-8b45-f18f6fd94cff.png)

**Comment by hugselina2019** [comment]
鄙人不是处女座 但看的很难受

**Comment by John60676** [comment]
welcome PR

**Comment by John60676** [comment]
#4196
