### ISSUE TITLE
when mouse leave or enter menu components, console log file "runtime-core.esm-bundler.js:2794" warning

### ISSUE THREAD

**Issue by nnnnnnnnnni** [vueComponent/ant-design-vue#4169]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
windows10, edge 91.0.864.41, vue 3.0.5

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
mouse move in menu component

### What is expected?
have no warning console

### What is actually happening?
when mouse leave or enter menu components, console log file "runtime-core.esm-bundler.js:2794" warning

**Comment by tangjinzhou** [comment]
update to 2.2.0-beta.2
