### ISSUE TITLE
AutoComplete -> filterOption Is it invalid?

### ISSUE THREAD

**Issue by HaceraI** [vueComponent/ant-design-vue#4170]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.2

### Environment
windows x64, edge, 3.0.11

### Reproduction link
[https://2x.antdv.com/components/auto-complete-cn#API](https://2x.antdv.com/components/auto-complete-cn#API)

### Steps to reproduce
View and use: Non-case-sensitive AutoComplete

### What is expected?
Non-case-sensitive AutoComplete

### What is actually happening?
I tried to use lowercase, but it didn't seem to work.

![image](https://user-images.githubusercontent.com/48341368/120917343-5de28680-c6e1-11eb-9014-62b4b4bdd2bd.png)
![image](https://user-images.githubusercontent.com/48341368/120917347-663ac180-c6e1-11eb-9253-134d2a986bf0.png)

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/accea40ab21f1cd017d0bd6c97107d481d5b89d0

we will release it at this week
