### ISSUE TITLE
Vue 3.1.1 breaks layout

### ISSUE THREAD

**Issue by ais-one** [vueComponent/ant-design-vue#4173]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
Windows 10 Home, Chrome 91, Vue 3.1.1 (refer to package.json of minimal reproduction for details)

### Reproduction link
[https://github.com/ais-one/vite-antd-bug](https://github.com/ais-one/vite-antd-bug)

### Steps to reproduce
1. clone example repo
2. npm i
3. npm run dev

you can see the problem with layout.

### What is expected?
layout with custom trigger looks same as documentation - https://2x.antdv.com/components/layout#components-layout-demo-custom-trigger

The minimal reproduction uses the sample code in the documentation and is found in App.vue file

### What is actually happening?
menu is on top and the content is pushed to the bottom

---
bug seen when upgrading to Vue 3.1.1

**Comment by dustdu** [comment]
早上一看更新了，升级了下，直接炸了。。。

**Comment by sendya** [comment]
请记住，不要跨版本升级！ 特别是 vue 官方还写了 Breaking Changes

**Comment by dustdu** [comment]
> 请记住，不要跨版本升级！ 特别是 vue 官方还写了 Breaking Changes

看到了，被Menu警告搞烦了，抱着侥幸心理试了一下，还是不行。现在有空就看新版本发布没。。。

**Comment by JasonSubMara** [comment]
盆友，受伤害的不止你一个人～ @dustdu

**Comment by tangjinzhou** [comment]
update to 2.2.0-beta.2

**Comment by atom-git** [comment]
这个虽然解决了warn问题，但是菜单下拉延迟明显


> update to 2.2.0-beta.2

**Comment by atom-git** [comment]
VUE升级到3.1.1解决了这个问题，但是页面感觉好卡

**Comment by tangjinzhou** [comment]
？本地感觉流畅很多啊

**Comment by tangjinzhou** [comment]
> VUE升级到3.1.1解决了这个问题，但是页面感觉好卡

新开issue反馈吧

**Comment by yushaoyi** [comment]
1
