### ISSUE TITLE
2.x demo table filter bug 

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#4174]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
chrome

### Reproduction link
[https://2x.antdv.com/components/table-cn#components-table-demo-reset-filter](https://2x.antdv.com/components/table-cn#components-table-demo-reset-filter)

### Steps to reproduce
first click the name filter button
second click the address filter button

### What is expected?
the second condition can be selected

### What is actually happening?
the second condition can not be selected

![image](https://user-images.githubusercontent.com/22545824/121141961-1b01e980-c86e-11eb-8c20-3c478f0a797c.png)

**Comment by tangjinzhou** [comment]
you can try 2.2.0-beta.2.
now doc base v2.1
