### ISSUE TITLE
In the tsx component, the Menu component lacks the onClick prop

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#4177]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
vue3.1.1

### Reproduction link
[https://2x.antdv.com/components/menu-cn](https://2x.antdv.com/components/menu-cn)

### Steps to reproduce
在tsx组件中，Menu组件缺少onClick的prop；
老问题了，好几次组件更新或者重构时，会出现这样的问题；之前有menu chekbox select等组件也出现过缺少ts的prop

### What is expected?
Menu组件补全onClick的prop

### What is actually happening?
在tsx组件中，Menu组件缺少onClick的prop；
代码就不贴了

**Comment by tangjinzhou** [comment]
参考这个文件，在项目中添加吧  
https://github.com/vueComponent/ant-design-vue/blob/next/typings/vue-tsx-shim.d.ts

@Amour1688 emits 事件是否可以添加到类型提示里

**Comment by Amour1688** [comment]
> 参考这个文件，在项目中添加吧
> https://github.com/vueComponent/ant-design-vue/blob/next/typings/vue-tsx-shim.d.ts
> 
> @Amour1688 emits 事件是否可以添加到类型提示里

等这个 PR 被合入 https://github.com/vuejs/vue-next/pull/3926

**Comment by uinio** [comment]
参考jsx.d.ts
```ts
export interface VueSlots<T = any> {
  [name: string]: (payload?: T) => JSX.Element | null;
}

export declare type VueModel =
  | string
  | number
  | boolean
  | bigint
  | null
  | undefined
  | symbol
  | Record<string, unknown>
  | [unknown, string];

interface JsxComponentCustomProps {
  vShow?: boolean;
  vSlots?: VueSlots;
  vModel?: VueModel;
  vModels?: VueModel[];
  vHtml?: string | JSX.Element | null;
  vAction?: [string, string];
}

declare module 'vue' {
  interface HTMLAttributes extends JsxComponentCustomProps {}

  interface ComponentCustomProps extends HTMLAttributes {}
}
```

**Comment by liulei92** [comment]
感谢提供解决方法
