### ISSUE TITLE
[Vue warn]: injection "FormContext" not found.

### ISSUE THREAD

**Issue by liulei92** [vueComponent/ant-design-vue#4178]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
vue3.1.1

### Reproduction link
[https://2x.antdv.com/components/form-cn](https://2x.antdv.com/components/form-cn)

### Steps to reproduce
2.1.6中，form的子组件可以通过inject("FormContext")获取form的实例，
但2.2.0-beta中提示 not found.

### What is expected?
FormContext 继续保留，有些场景需要在form的子组件中利用到form的一些方法

### What is actually happening?
[Vue warn]: injection "FormContext" not found.

**Comment by tangjinzhou** [comment]
FormContext 一直是内部方法，不建议业务中直接使用
新版本你可以使用 useInjectForm，但依然不建议使用，这些都是内部方法，而且是什么场景需要操作这些方法呢

**Comment by tangjinzhou** [comment]
fix: form-item class  https://github.com/vueComponent/ant-design-vue/commit/617e534fda2ae6d468b5e9d3eb43370f8a4b0000

**Comment by liulei92** [comment]
场景时而这样的：
- 基于form-item二次封装了 dd-form-item组件
- 基于 dd-form-item 和 input 封装了ip地址输入框（3个input组合），组件ip-item
- 之前的做法是，利用inject FormContext获取到form的对象，通过getFieldsByNameList获取到当前的ip-item的ref对象，从而在3个input的change和blur的时候去调用 ip-item的ref的onFieldChange和onFieldBlur事件，触发表单验证
- 昨天更新了下后，发现FormContext不在暴露，此外 form/context.ts中的useInjectForm hook，其中也只包含了部分方法，并未expose出 onFieldChange和onFieldBlur事件

**Comment by liulei92** [comment]
- 我可看到了 https://github.com/vueComponent/ant-design-vue/issues/4183 这个issue中的解决方法，是期望使用validateFields代替onFieldChange和onFieldBlur的话，我去尝试下；
- 望增加 https://2x.antdv.com/components/form-cn 文档中关于onFieldChange和onFieldBlur的方案在2.2.0中废弃的提示

**Comment by tangjinzhou** [comment]
sorry  文档尽然用了这个api，那就稳定下来，我把 onFieldChange和onFieldBlur 添加回去好了

**Comment by sendya** [comment]
FormContext 尽量不要使用，属于组件库内部状态管理所用，版本变化时随时可能有改变

二次封装表单组件应当遵循 Form 组件的使用说明

```vue
<a-form-item name="form.name" ref="name" :autoLink="false">
  <a-input v-model:value="other" />
  <span>hahha</span>
  <div>
    <a-input
      v-model:value="form.name"
      @blur="() => {$refs.name.onFieldBlur()}"
      @change="() => {$refs.name.onFieldChange()}"
    />
  </div>
</a-form-item>
```
![image](https://user-images.githubusercontent.com/5404542/121289838-30cbe900-c918-11eb-84ee-d28adb66d38f.png)

**Comment by liulei92** [comment]
尴尬，刚才去试了下 validateFields 的可行性；如果onFieldChange和onFieldBlur 继续保留，那当前是更好的了 ^-^

**Comment by liulei92** [comment]
@tangjinzhou 想咨询下，form组件能否支持继续expose出fields

**Comment by tangjinzhou** [comment]
> @tangjinzhou 想咨询下，form组件能否支持继续expose出fields

no

**Comment by liulei92** [comment]
ok，那我去使用getFieldsValue去获取当前form中有效的项吧
