### ISSUE TITLE
version 2.2.0 beta and vue 3.1.1 table demo edit row gives error (there is workaround)

### ISSUE THREAD

**Issue by ais-one** [vueComponent/ant-design-vue#4182]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
Windows 10 Home, Chrome 91, Vue 3.1.1, Ant Design 2.2.0-beta-2

### Reproduction link
[https://2x.antdv.com/components/table#components-table-demo-edit-row](https://2x.antdv.com/components/table#components-table-demo-edit-row)

### Steps to reproduce
Use the sample code in minimal reproduction link (select version 2.X), use JS

### What is expected?
normal operation

### What is actually happening?
page is crashing with error: v-model value must be a valid JavaScript member expression

---
Error on line 7 v-model:value="editableData[record.key][col]"

temporary work around is to use

:value="editableData[record.key][col]"
@change="(e) => editableData[record.key][col] = e.target.value"

**Comment by zkwolf** [comment]
https://github.com/vuejs/vue-next/issues/3910

**Comment by tangjinzhou** [comment]
update vue to 3.1.2
