### ISSUE TITLE
The less variable @text-color in the document is inconsistent with the actual

### ISSUE THREAD

**Issue by jiangmaniu** [vueComponent/ant-design-vue#4190]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
```sh
$ npx envinfo --system --npmPackages ant-design-vue --binaries --browsers

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Memory: 2.58 GB / 15.92 GB
  Binaries:
    Node: 14.17.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    ant-design-vue: ^2.1.6 => 2.1.6
```

### Environment
ant-design-vue: ^2.1.6

### Steps to reproduce
我看官网[文档](https://2x.antdv.com/docs/vue/customize-theme-cn#ant-design-vue-%E7%9A%84%E6%A0%B7%E5%BC%8F%E5%8F%98%E9%87%8F)和less [变量](https://github.com/vueComponent/ant-design-vue/blob/master/components/style/themes/default.less#L48) ，`@text-color` 的值都是 `rgba(@black, .65)` 。

但在使用 `ant-design-vue/dist/theme` 包中的 `getThemeVariables ` 函数时，返回的 `@text-color` 变量的值是 `rgba(@black, .85)` 。

![image](https://user-images.githubusercontent.com/50100681/121454159-e65c7200-c9d4-11eb-9cd3-3666220ac9d4.png)

虽然我在变量导入到 `less preprocessorOptions` 之前可以将 `@text-color` 原本的值为 `rgba(@black, .85)` 替换成 `rgba(@black, .65)`，但我想知道这是文档错误还是有什么特殊考虑而有意为之的呢？

**Comment by zkwolf** [comment]
官网有一部分没更新，现在2.x在next分支上
