### ISSUE TITLE
version 2.2.0 modal open and close animation disappear

### ISSUE THREAD

**Issue by liwuxi** [vueComponent/ant-design-vue#4191]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
vue 3.1.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/gallant-kalam-9whd6)

### Steps to reproduce
none

### What is expected?
display open and close animation

### What is actually happening?
modal open and close animation disappear

**Comment by bandaoqiu** [comment]
menu菜单的click事件回调item为undefined

**Comment by tangjinzhou** [comment]
> menu菜单的click事件回调item为undefined

item已移除，不同问题请单独开issue

**Comment by lanyu0623** [comment]
我也遇到了modal打开关闭没有动画效果，请问如何解决的？
