### ISSUE TITLE
Input输入时，已经禁用的按钮被自动启动

### ISSUE THREAD

**Issue by yangy9593** [vueComponent/ant-design-vue#420]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.2

### Environment
windows 10，chrome 70，vue 2.5.22

### Reproduction link
[https://tangjinzhou.gitee.io/ant-design-vue/components/form-cn/#components-form-demo-registration](https://tangjinzhou.gitee.io/ant-design-vue/components/form-cn/#components-form-demo-registration)

### Steps to reproduce
1.将按钮‘Get captcha’设为禁用
2.在文本框随便输入一些内容，按钮会变成启用状态

### What is expected?
已经被禁用的按钮，仍然被禁用

### What is actually happening?
它被起用了

**Comment by tangjinzhou** [comment]
没能复现你的问题 
![image](https://user-images.githubusercontent.com/6937879/51321214-2a194e80-1a9d-11e9-9818-cbfc717749e0.png)
请再次确认，如还有问题，请通过 https://codesandbox.io/s/2wpk21kzvr 提供复现demo

**Comment by yangy9593** [comment]
https://codesandbox.io/s/jp28x2x6xv

复现步骤一样

**Comment by tangjinzhou** [comment]
使用姿势不对，
不要手动改变DOM，
正确姿势：
`<a-button disabled>Get captcha</a-button>`

**Comment by yangy9593** [comment]
在表单验证中，例如checkbox和文件上传，验证了必须选中
操作步骤：
1.直接点提交，触发checkbox和文件上传的校验
2.选中checkbox后校验消失
3.取消checkbox的选中，点击提交
4.文件上传同上，先选中后取消

预期：再次出现校验提示

结果：没有再次出现提示

是我的姿势不对吗，附上链接：https://codesandbox.io/s/3kprzr3v16

**Comment by tangjinzhou** [comment]
是的  姿势不对， 上传组件比较特殊，demo中有相关示例 
https://vuecomponent.github.io/ant-design-vue/components/form-cn/#components-form-demo-other-form-controls

https://codesandbox.io/s/2v68qv9wkr
