### ISSUE TITLE
carousel modify the automatic carousel interval time

### ISSUE THREAD

**Issue by date-convert** [vueComponent/ant-design-vue#4200]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
自定义轮播间隔时间

### What does the proposed API look like?
组件添加 timeout： 2000ms 属性 设置间隔时间

**Comment by zkwolf** [comment]
可以用autoplaySpeed
