### ISSUE TITLE
Component data is not updated

### ISSUE THREAD

**Issue by WuChenDi** [vueComponent/ant-design-vue#4201]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.2

### Environment
- OS: Windows 10
- Browser (vendor and version): chrome v90.0.4430.93
- vue: 3.0.0-0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-https-ij0oz?file=/src/components/HelloWorld.tsx)

### Steps to reproduce
codesandbox 代码

### What is expected?
希望数据更新

### What is actually happening?
数据不更新

**Comment by tangjinzhou** [comment]
你的示例不是在更新吗   有啥问题，描述清楚点

**Comment by sendya** [comment]
https://codesandbox.io/s/modern-framework-2fwor?file=/src/components/HelloWorld.tsx

建议仔细核对下文档，  Input 的值绑定为 `v-model:value` ，其对于的 JSX 写法为 `v-model={[state, 'value']}`

**Comment by WuChenDi** [comment]
> 你的示例不是在更新吗 有啥问题，描述清楚点

不好意思，是原生组件数据更新，ant组件数据不更新

**Comment by WuChenDi** [comment]
> https://codesandbox.io/s/modern-framework-2fwor?file=/src/components/HelloWorld.tsx
> 
> 建议仔细核对下文档， Input 的值绑定为 `v-model:value` ，其对应的 JSX 写法为 `v-model={[state, 'value']}`

好的，谢谢，能否问下是核对 jsx-next 这个库的文档吗，因为在ant官网看到只是template的写法

**Comment by tangjinzhou** [comment]
jsx-next
