### ISSUE TITLE
The space component cannot work on the mobile terminal

### ISSUE THREAD

**Issue by xuewangwang** [vueComponent/ant-design-vue#4207]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
ios14.4、safria、vue3.1.1

### Reproduction link
[https://2x.antdv.com/components/space-cn](https://2x.antdv.com/components/space-cn)

### Steps to reproduce
<a-space :size="20">
<span>menu1</span>
<span>menu2</span>
<span>menu3</span>
<span>menu5</span>
<span>menu6</span>
<span>menu7</span>
</a-space>

### What is expected?
take effect

### What is actually happening?
It doesn't work

---
It may be a gap compatibility problem

**Comment by tangjinzhou** [comment]
提供有效的复现示例和 Steps to reproduce

**Comment by whvcse** [comment]
Space组件的间距现在使用css的gap实现的，以前是用margin实现了，gap很多主流浏览器还不支持，建议改回margin-right

**Comment by tangjinzhou** [comment]
> Space组件的间距现在使用css的gap实现的，以前是用margin实现了，gap很多主流浏览器还不支持，建议改回margin-right

是做了判断的   不支持gap 的， 会自动降级margin
