### ISSUE TITLE
Duplicate children head when grouping table head

### ISSUE THREAD

**Issue by fajrizulfikar** [vueComponent/ant-design-vue#4208]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
Vue version: 2.5.17

### Reproduction link
[https://du33k.csb.app/](https://du33k.csb.app/)

### Steps to reproduce
1. Import and call a-table in the view with the following spec: scroll.x =1500, scroll.y= 300
2. Define the columns like in the codesandbox

### What is expected?
Children head not duplicated

### What is actually happening?
Children head duplicated

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-xkhfu
留一列不设置宽度
