### ISSUE TITLE
文档缺陷

### ISSUE THREAD

**Issue by chinajoy** [vueComponent/ant-design-vue#421]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
你这文档初学者没有几个人能看懂，学Ant Design 就学全一点

### What does the proposed API look like?
看下别人youzan的文档 https://youzan.github.io/vant/#/zh-CN/intro 就不在一个水平上

**Comment by tangjinzhou** [comment]
能力有限 欢迎pr

**Comment by sendya** [comment]
现在的初学者呀... 不能沉下心来看文档了吗

**Comment by BusyHe** [comment]
@tangjinzhou 这种评论你可以不用理会，让我们来，哈哈哈

**Comment by Pythonfo** [comment]
伸手党做得那么心安理得？一点贡献意识没有？
而且有赞是公司团队的开源项目，而adv只是几个ant+vue的爱好者共同维护的。

**Comment by chinajoy** [comment]
> 现在的“初学者”呀... 不能沉下心来看文档了吗

说话经过大脑吗？

**Comment by sendya** [comment]
> > 现在的“初学者”呀... 不能沉下心来看文档了吗
> 
> 说话经过大脑吗？

你这话说我，还是说你自己？

**Comment by tangjinzhou** [comment]
的确精力有限，感谢各位关注，issue就关掉了
欢迎PR 欢迎PR 欢迎PR
