### ISSUE TITLE
update gh-pages

### ISSUE THREAD

**Issue by Modarola** [vueComponent/ant-design-vue#4210]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
we need document offline. but the latest of gh-pages only suppose 1.4

### What does the proposed API look like?
we need document offline. but the latest of gh-pages only suppose 1.4

**Comment by zkwolf** [comment]
the latest doc of 1.x in there https://github.com/vueComponent/ant-design-vue/tree/1.x/antdv-demo

**Comment by Modarola** [comment]
> the latest doc of 1.x in there https://github.com/vueComponent/ant-design-vue/tree/1.x/antdv-demo

I need 2.x document offline

**Comment by 506258220** [comment]
I need 2.x document offline
