### ISSUE TITLE
Question about virtual scrolling!

### ISSUE THREAD

**Issue by qqfei1858** [vueComponent/ant-design-vue#4211]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1.目前看到推出了table的虚拟滚动,是否支持树形虚拟滚动?开启虚拟功能后功能都能和普通表格没有区别吧?
2.tree组件的虚拟化有啥计划吗?

### What does the proposed API look like?
OS: win10
Chrome: 90.0.4430.212
Vue: v3

**Comment by tangjinzhou** [comment]
1、有区别  try it  行高无法自动换行
2、ing
