### ISSUE TITLE
Checkbox cannot attribute custom data attribute(data-*)

### ISSUE THREAD

**Issue by b4-tahayashi** [vueComponent/ant-design-vue#4212]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue3.0.11 / macOS 10.15.7 / chrome 91.0.4472.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-cebcp?file=/src/main.js)

### Steps to reproduce
* Add custom data attribute to <a-checkbox> (e.g `<a-checkbox data-foo="foo">~~~</a-checkbox>` ) component.

### What is expected?
* custom data attribute attributed to `<label>`tag.  (e.g `<label class="ant-checkbox-wrapper" data-foo="foo">` )

### What is actually happening?
custom data attribute is not generated.

**Comment by b4-tahayashi** [comment]
I encountered a similar problem with `a-input-search`.
Is this the same problem?

Reproduce
```html
<a-input-search
  class="InputClassName"
  data-foo="FooValue"
  data-bar="BarValue"
  placeholder="PlaceholderValue"
/>
```

Exptected
```html
<span class="ant-input-search ant-input-affix-wrapper InputClassName" data-foo="FooValue" data-bar="BarValue">
  <input 
    placeholder="PlaceholderValue" 
    class="ant-input"
  >
      <span class="ant-input-suffix">
         ...
      </span>
   </input>
</span>
```

Happening
```html
<span class="ant-input-search ant-input-affix-wrapper InputClassName">
  <input 
    placeholder="PlaceholderValue" 
    data-foo="FooValue"
    data-bar="BarValue"
    class="ant-input"
  >
      <span class="ant-input-suffix">
         ...
      </span>
   </input>
</span>
```

**Comment by tangjinzhou** [comment]
> I encountered a similar problem with `a-input-search`.
> Is this the same problem?
> 
> Reproduce
> 
> ```
> <a-input-search
>   class="InputClassName"
>   data-foo="FooValue"
>   data-bar="BarValue"
>   placeholder="PlaceholderValue"
> />
> ```
> 
> Exptected
> 
> ```
> <span class="ant-input-search ant-input-affix-wrapper InputClassName" data-foo="FooValue" data-bar="BarValue">
>   <input 
>     placeholder="PlaceholderValue" 
>     class="ant-input"
>   >
>       <span class="ant-input-suffix">
>          ...
>       </span>
>    </input>
> </span>
> ```
> 
> Happening
> 
> ```
> <span class="ant-input-search ant-input-affix-wrapper InputClassName">
>   <input 
>     placeholder="PlaceholderValue" 
>     data-foo="FooValue"
>     data-bar="BarValue"
>     class="ant-input"
>   >
>       <span class="ant-input-suffix">
>          ...
>       </span>
>    </input>
> </span>
> ```
This is correct, we specifically mounted it on input
