### ISSUE TITLE
Ant design Vue page is down

### ISSUE THREAD

**Issue by Arturokin12** [vueComponent/ant-design-vue#4213]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
MacOS

### Reproduction link
[https://www.antdv.com](https://www.antdv.com)

### Steps to reproduce
go to https://www.antdv.com

### What is expected?
page loaded

### What is actually happening?
https://www.antdv.com page is not loading, stucks loading forever

**Comment by tangjinzhou** [comment]
you can try some vpn
