### ISSUE TITLE
Statistic countdown control The set function cannot be called after the countdown is over

### ISSUE THREAD

**Issue by shumyun** [vueComponent/ant-design-vue#4214]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
最新版vue

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
倒计时结束后不能调用设置的函数

### What is expected?
倒计时结束后不能调用设置的函数

### What is actually happening?
倒计时结束后不能调用设置的函数

**Comment by shumyun** [comment]
https://codesandbox.io/s/serene-gauss-ojur0?file=/src/components/HelloWorld.vue

**Comment by FanhuaCloud** [comment]
I have same ploblem, it can't call when time finish.
