### ISSUE TITLE
Vite 2.x onn-demand introduce gets warned?

### ISSUE THREAD

**Issue by xieyezi** [vueComponent/ant-design-vue#4217]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
- vue: 3.0.5
- vite: 2.3.7

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3281](https://github.com/vueComponent/ant-design-vue/issues/3281)

### Steps to reproduce
1. 在配置文件里面按需导入
```ts
// vite.config.ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import styleImport from 'vite-plugin-style-import'

// https://vitejs.dev/config/
export default defineConfig({
	plugins: [
		vue(),
		styleImport({
			libs: [
				{
					libraryName: 'ant-design-vue',
					esModule: true,
					resolveStyle: (name) => `ant-design-vue/es/${name}/style/index`
				}
			]
		})
	],
  css: {
		preprocessorOptions: {
			less: {
				javascriptEnabled: true
			}
    }
  }
})

```
2. 在`main.ts`里面使用`app.use(xxx) `按需导入组件
```ts
import {
	Row,
	Col,
	Form,
	Input,
	Button,
	Modal,
	Steps,
	Divider,
	Result,
	Dropdown,
	Menu,
	Tabs,
	Popconfirm
} from 'ant-design-vue'


const app = createApp(App)

app.use(Button)
app.use(Input)
app.use(Form)
app.use(Modal)
app.use(Steps)
app.use(Divider)
app.use(Result)
app.use(Dropdown)
app.use(Menu)
app.use(Tabs)
app.use(Popconfirm)

app.use(router).mount('#app')
```

使用的确是正常的，但是在控制台得到一个警告：

<img width="1708" alt="QQ20210617-110820@2x" src="https://user-images.githubusercontent.com/16821989/122324978-57170780-cf5c-11eb-8d2a-8bb39510a36e.png">

### What is expected?
请问如何解决这个警告?

**Comment by ajuner** [comment]
问题看样子是vite插件导致的  可以找一下问题
或者尝试使用vite-plugin-importer

**Comment by xieyezi** [comment]
@ajuner 谢谢回复，`vite-plugin-importer`的确有用❤️
