### ISSUE TITLE
a-form-item style has changed to a flex layout

### ISSUE THREAD

**Issue by liwuxi** [vueComponent/ant-design-vue#4218]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
vue 3.1.1

### Reproduction link
[https://2x.antdv.com/components/form-cn](https://2x.antdv.com/components/form-cn)

### What is actually happening?
I noticed that the style has changed to a flex layout

---
The documentation does not have the relevant demo, is this a problem with the way I use it?

I don't want to create two a-form-items

**Comment by zkwolf** [comment]
应该2.x的时候就是flex布局了吧，主要是因为内部用了a-row/a-col，a-row在2.x下变成了flex布局

**Comment by liwuxi** [comment]
@zkwolf 上几个版本好像不是这样，但我的用法似乎是错误的，我看1.x版本的demo，

发现

```javascript
<a-form-item label="name">
  <a-form-item v-bind="validateInfos.firstName">
    <a-input placeholder="first name" />
  </a-form-item>
  <a-form-item v-bind="validateInfos.lastName">
    <a-input placeholder="last name" />
  </a-form-item>
</a-form-item>
```

这才是正确使用姿势？
