### ISSUE TITLE
How does vite customize the theme?

### ISSUE THREAD

**Issue by hojas** [vueComponent/ant-design-vue#4220]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
vue3 vite

### Reproduction link
[http://null.com](http://null.com)

### Steps to reproduce
vue3 vite

### What is expected?
自定义主题颜色等

### What is actually happening?
[plugin:vite:css] Inline JavaScript is not enabled. Is it set in your options?

**Comment by ajuner** [comment]
是想在vite中自定义主题颜色嘛
是的话请参考配置
vite.config.js
```
export default {
  ...
  css: {
    preprocessorOptions:{ 
      less: {
        modifyVars: { 
          'primary-color': '#1DA57A',
        },
      },
    },
  },
}
````

**Comment by hojas** [comment]
@ajuner  是的，可以了，谢谢~

**Comment by Jenniferyingni** [comment]
请问除了vite.config.js的配置，还需要修改其他地方么
ant-design-vue  v2.1.2，vite  v2.3.7


main.js
``` javascript
import { createApp } from 'vue'
import App from './App.vue'

import Antd from 'ant-design-vue';
import 'ant-design-vue/dist/antd.css';

const app = createApp(App);

app.use(Antd)
app.mount('#app')

```

vite.config.js
``` javascript
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  css: {
    preprocessorOptions:{ 
      less: {
        javascriptEnabled: true,
        modifyVars: { 
          'primary-color': '#7546c9',
        },
      },
    },
  },
})
```

我这样写换肤还是没有生效

@hojas @ajuner

**Comment by SalahAdDin** [comment]
> 是想在vite中自定义主题颜色嘛 是的话请参考配置 vite.config.js
> 
> ```
> export default {
>   ...
>   css: {
>     preprocessorOptions:{ 
>       less: {
>         modifyVars: { 
>           'primary-color': '#1DA57A',
>         },
>       },
>     },
>   },
> }
> ```

It does not work.

**Comment by webxmsj** [comment]
However, if I use the following configuration, it does not take effect
```javascript
export default {
  ...
  css: {
    preprocessorOptions:{ 
     less: {
          javascriptEnabled: true,
          additionalData: `
            @import "@/assets/themes/variables.less";
          `
        }
    },
  },
}
```
