### ISSUE TITLE
ExpandIcon of the A-table in the production environment returns the expanded parameter props cannot be changed by clicking the extra expand button

### ISSUE THREAD

**Issue by saiyoulala** [vueComponent/ant-design-vue#4223]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
windows7 and windows 10, Chrome91.0.4472.106,vue 2.9.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-lztjx?file=/src/App.vue)

### Steps to reproduce
In 1.7.5, click the extra expansion button of the table. There are no expansion lines and the button has not changed to minus-square

### What is expected?
In 1.7.5, if you click the extra expansion button in Table, the extra row will expand normally, and the extra expansion button will be changed to minus-square

### What is actually happening?
In 1.7.5 version of component A-table, using the expandIcon parameter, the function's callback parameter 'expanded' in 'props' always returns false when the button is clicked. This only happens in production, not test or local. This was ultimately resolved by lowering the version to 1.7.2. Since 1.7.5 is not available in your version selection that raised the question, I can only choose 1.7.3 as a substitute.

---
Both the local environment and the test environment are fine, only the online environment has problems

**Comment by tangjinzhou** [comment]
Please provide a working example

**Comment by saiyoulala** [comment]
> Please provide a working example

I have provided a new work example, please check it.

**Comment by ajuner** [comment]
> I have provided a new work example, please check it.

Is this the [address](https://codesandbox.io/s/vue-antd-template-forked-lztjx?file=/src/App.vue)?
It looks like there is nothing wrong with it

**Comment by ajuner** [comment]
Sorry, I have not reproduced it in the production environment, but I think there may be a problem of specifying the row-key, please try it

**Comment by saiyoulala** [comment]
> Sorry, I have not reproduced it in the production environment, but I think there may be a problem of specifying the row-key, please try it

Sorry, I forgot to add rowkey to the fake data, now I have added it, but it is added in my online project, so I think it is not the problem.

**Comment by ajuner** [comment]
![image](https://user-images.githubusercontent.com/53512912/123208139-20f3fd80-d4f1-11eb-8856-4c7a7e058ab9.png)
It seems no problem

**Comment by saiyoulala** [comment]
> ![image](https://user-images.githubusercontent.com/53512912/123208139-20f3fd80-d4f1-11eb-8856-4c7a7e058ab9.png)
> It seems no problem

I don't know why my project has this problem. Thank you. Let me check why my project causes this problem

**Comment by tangjinzhou** [comment]
set alias for vue
