### ISSUE TITLE
select multiple selection mode, hope to increase the maximum option limit

### ISSUE THREAD

**Issue by MatrixYe23** [vueComponent/ant-design-vue#4224]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
应用场景就是模式为multiple/tag 的时候希望有一个最大选项限制，当用户选择数到达最大值时，multiple模式下禁止用户选择，tag模式下禁止输入。

### What does the proposed API look like?
最大选项限制: maxSelectedCount；

**Comment by tangjinzhou** [comment]
你可以使用受控模式  控制数量

**Comment by MatrixYe23** [comment]
> 受控模式



> 受控模式

我是用的是2.x, 文档中没有找到‘受控模式’， 可以提供详细点的材料吗? 谢谢

**Comment by sky124380729** [comment]
我也想知道，如何控制最大多选的最大数量

**Comment by Gardent** [comment]
应该是使用value，和change自己赋值，不直接使用v-model。
