### ISSUE TITLE
Click the second to last CollapsePanel ,it will collapse with the last CollapsePanel togather

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#4228]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.3

### Environment
Vue3.1.1, MacOS 10.15.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-collapse-panel-buhee?file=/src/App.vue)

### Steps to reproduce
Click the second to last CollapsePanel

### What is expected?
The second panel will not affect the last panel

### What is actually happening?
The second panel affect the last panel

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/bug-collapse-panel-forked-3i2mp

set key for everyone
