### ISSUE TITLE
When using form components, why are they required to provide data structures?

### ISSUE THREAD

**Issue by hardmanhong** [vueComponent/ant-design-vue#4230]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
版本2.1.2中，我正在封装一个常用的列表搜索表单，我发现demo中要么给form传递一个model属性，而且组件还要绑定具体的属性值，如`v-model:value=formModel.x`，理想情况下我是不需要关心需要绑定什么值，我只需要触发提交事件时，直接返回一个数据结构给我，或者在不需要校验表单，不需要写`v-model:value=formModel.x`的情况下，如何获取表单的值，看了文档，没找到对应的方法！

像1.7.5版本就可以达到我想要的封装效果，不需要让组件关心数据

**Comment by tangjinzhou** [comment]
仔细查阅vue文档
 v-model:value 是 value @update:value 的语法糖

**Comment by hardmanhong** [comment]
> 仔细查阅vue文档
> v-model:value 是 value @update:value 的语法糖

嗯嗯，我知道是:value.sync的语法糖，但是我没明白这跟我的问题有什么关联吗？

**Comment by tangjinzhou** [comment]
木有了

**Comment by hardmanhong** [comment]
> 木有了

后续有计划支持吗
