### ISSUE TITLE
Cascading selectors cannot be lazily loaded within subsets (cascading selectors cannot be lazily loaded within subsets)

### ISSUE THREAD

**Issue by umbrella22** [vueComponent/ant-design-vue#4236]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.4

### Environment
vue version：3.1.1; os version：Windows 10 20H2 19042.1055; browser version：Microsoft Edge 版本 91.0.864.54

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-breeze-likm8)

### Steps to reproduce
<template>
<a-cascader
v-model:value="value"
:options="options"
:load-data="loadData"
placeholder="Please select"
/>
</template>

<script>
import { defineComponent, ref } from "vue";
export default defineComponent({
setup() {
const options = ref([
{
value: "zhejiang",
label: "Zhejiang",
isLeaf: false,
},
{
value: "jiangsu",
label: "Jiangsu",
isLeaf: false,
},
]);

function loadData(selectedOptions) {
console.log(selectedOptions);
const targetOption = selectedOptions[selectedOptions.length - 1];
targetOption.loading = true;

// load options lazily
setTimeout(() => {
targetOption.loading = false;
targetOption.children = [
{
label: `${targetOption.label} Dynamic 1`,
value: "dynamic1",
children: [],
isLeaf: false,
loading: false,
},
{
label: `${targetOption.label} Dynamic 2`,
value: "dynamic2",
children: [
{
label: `${targetOption.label} Dynamic 2`,
value: "dynamic2",
},
],
},
];
}, 1000);
}

return {
options,
loadData,
};
},
});
</script>

<style scoped>
h3 {
margin: 40px 0 0;
}
ul {
list-style-type: none;
padding: 0;
}
li {
display: inline-block;
margin: 0 10px;
}
a {
color: #42b983;
}
</style>

### What is expected?
子集内children仍然可以调用loadData方法，如此循环直到children数组长度为0或者为null

The loadData method can still be called by the children in the subset until the length of the children array is 0 or null

### What is actually happening?
https://codesandbox.io/s/quizzical-breeze-likm8

演示dome

**Comment by tangjinzhou** [comment]
你这demo，不是正常吗  ？

**Comment by umbrella22** [comment]
@tangjinzhou 并不，期望是想如果children数组为空并且isLeaf:false时，可以加载远程，但是例子中并不会触发loadData函数，= =必须是children数组不存在时才可以触发，- - 虽然是解决了这问题，但是总感觉。。。children数组为空时仍然会展示空白级联并且不触发loadData有一些怪怪的。。。如果能完善一下文档就更好了，比如想要开启懒加载就一定要带上isLeaf:false，并且确保children不存在
