### ISSUE TITLE
"ant-design-vue"' has no exported member 'Modal' (not only Modal, and other component is so on)

### ISSUE THREAD

**Issue by heart-er** [vueComponent/ant-design-vue#4237]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue 3.1.1 / chrome / typescript 4.3.3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
not only Modal, and other component is so on

### What is expected?
1. import { Modal } from 'ant-design-vue' 2. vscode ts warning: Module '"ant-design-vue"' has no exported member 'Modal'. Did you mean to use 'import Modal from "ant-design-vue"' instead? 3. Button styles not show in the browser

### What is actually happening?
not error

**Comment by tangjinzhou** [comment]
1.x  or 2.x ?

**Comment by heart-er** [comment]
@tangjinzhou 2.x

**Comment by tangjinzhou** [comment]
不能复现  大概率和你的各种配置有关
