### ISSUE TITLE
a-auto-complete custom dataSource demo bug / a-auto-complete custom dataSource official website sample bug

### ISSUE THREAD

**Issue by bunnyxt** [vueComponent/ant-design-vue#4240]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.4

### Environment
/

### Reproduction link
[https://antdv.com/components/auto-complete-cn/#components-auto-complete-demo-customized](https://antdv.com/components/auto-complete-cn/#components-auto-complete-demo-customized)

### Steps to reproduce
1. type something
2. click one of select option
3. see \n and spaces fill back

---

1. 随便输入点啥
2. 点击任意一个选择项
3. 可以看到a-select-option中的\n和空格也被回填了

![aaa](https://user-images.githubusercontent.com/32478279/122766752-769f8e80-d2d4-11eb-8689-87fb73d2d9f8.png)
![bbb](https://user-images.githubusercontent.com/32478279/122766761-77d0bb80-d2d4-11eb-8a53-284a617e9762.png)

### What is expected?
\n and spaces will not fill back

\n和空格不被回填

### What is actually happening?
\n and spaces fill back

\n和空格被回填

---
just remove \n and spaces in a-select-option demo code

删除demo中a-select-option标签中的空格和换行即可

```html
      <!-- wrong -->
      <a-select-option v-for="email in result" :key="email">
        {{ email }}
      </a-select-option>
```

```html
      <!-- correct-->
      <a-select-option v-for="email in result" :key="email">{{ email }}</a-select-option>
```

**Comment by tangjinzhou** [comment]
https://vue-loader-v14.vuejs.org/zh-cn/options.html#preservewhitespace
vue loader 配置问题吧
