### ISSUE TITLE
components/form/utils/validateUtil.ts When validateFirst is true or false, the reject promise cannot be returned for form.vlidate

### ISSUE THREAD

**Issue by cmtter** [vueComponent/ant-design-vue#4246]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue3 chrome

### Reproduction link
[https://2wpk21kzvr.csb.app/](https://2wpk21kzvr.csb.app/)

### Steps to reproduce
设置validateFirst为true, 当验证失败的是无法返回 reject promise，不清楚为什么？
components/form/utils/validateUtil.ts  at row 200

### What is expected?
设置validateFirst为true时, 当验证失败的是能返回 reject promise,  保证和不设置validateFirst属性时的 api使用一致性

### What is actually happening?
这是不是一种缺陷，还是说就是合理的设计

**Comment by tangjinzhou** [comment]
提供有效的 Reproduction link
