### ISSUE TITLE
Edge and chrome have different effect of setting column fixed width

### ISSUE THREAD

**Issue by Junior125306** [vueComponent/ant-design-vue#4247]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
antdv ^1.7.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-4jo3p)

### Steps to reproduce
edge会自动分配列宽 无视在columns中配置的 width
导致滚动条显示不正确
如图 https://dow.zz-yy.top/1624443351%281%29.jpg

### What is expected?
想要知道怎么才让两个浏览器显示结果一样

### What is actually happening?
一个能够正确的识别代码中的宽度  一个识别不了

**Comment by Junior125306** [comment]
![](https://dow.zz-yy.top/1624443351%281%29.jpg)

**Comment by tangjinzhou** [comment]
看你demo里面的组件库版本是 1.3.4  请升级 17.5 试试

**Comment by Junior125306** [comment]
> 看你demo里面的组件库版本是 1.3.4 请升级 17.5 试试

可以了非常感谢    我是你的粉丝 看过你的视频❤💕
