### ISSUE TITLE
When will 2.2.0 be officially released

### ISSUE THREAD

**Issue by techrex** [vueComponent/ant-design-vue#4249]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
请问2.2.0什么时候正式发布

### What does the proposed API look like?
请问2.2.0什么时候正式发布

**Comment by 5265liu** [comment]
同问，现在一堆警告啊，多会能发版

**Comment by tangjinzhou** [comment]
基本稳定  可以用了

**Comment by techrex** [comment]
生产环境使用，想等一个稳定版

**Comment by jahnli** [comment]
@tangjinzhou  3.0 预计什么时间发布
