### ISSUE TITLE
Table tree problem

### ISSUE THREAD

**Issue by luguanrui** [vueComponent/ant-design-vue#4251]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
web

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-tree-data](https://www.antdv.com/components/table-cn/#components-table-demo-tree-data)

### Steps to reproduce
表格属性数据展示

### What is expected?
期望以下问题能够快速解决

### What is actually happening?
`1.7.5`版本 树形表格的问题：

1. 树的展开/收起符号不能切换，目前只有收起的符号
2. 表头分组，使用`bordered`属性时，第一级缺少下划线
3. 树的部分不支持`fixed`的定位

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/4271
