### ISSUE TITLE
The select drop-down local search option-filter-prop="children" example is wrong, which makes the search unavailable. 2.x does not support the children option, you need to remake it yourself, please correct it

### ISSUE THREAD

**Issue by xiebin1** [vueComponent/ant-design-vue#4252]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.5

### Environment
2.1.3

### Reproduction link
[https://2x.antdv.com/components/select-cn#components-select-demo-search](https://2x.antdv.com/components/select-cn#components-select-demo-search)

### Steps to reproduce
不能直接指定option-filter-prop="children"，需要自己定义一个key来当做他的值

### What is expected?
修改更正一下官方示例

### What is actually happening?
暂未处理

**Comment by yuandongx** [comment]
+1
