### ISSUE TITLE
A-cascader adds :autoFocus ='true', input gets the focus, but the picker below does not pop up, the console reports an error, why? ?

### ISSUE THREAD

**Issue by zhixialihan** [vueComponent/ant-design-vue#4253]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.5

### Environment
"ant-design-vue": "^1.7.5",       "vue": "^2.6.11"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-z2n72?file=/src/App.vue)

### Steps to reproduce
<a-cascader
:options="options"
:autoFocus = 'true'
placeholder="Please select"
@change="onChange"
/>

### What is expected?
input 在获取焦点的时候级联面板也弹出来

### What is actually happening?
input 在获取焦点， 级联面板没有弹出来

**Comment by tangjinzhou** [comment]
按下回车键才会显示
并没有发现所谓的报错
