### ISSUE TITLE
Can you extract all the slots of the table and use a slot in the slot?

### ISSUE THREAD

**Issue by noenif** [vueComponent/ant-design-vue#4254]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
能不能把table 的slot 都抽出来,用slot里面套

### What does the proposed API look like?
https://www.antdv.com/components/table-cn/

当我在封装tableList的时候
![image](https://user-images.githubusercontent.com/25174520/123231691-03339200-d50b-11eb-8e25-8a222b0b9b6f.png)
上面是官方案例.

我想在外面我封装的组件中这样
![image](https://user-images.githubusercontent.com/25174520/123232061-5d345780-d50b-11eb-9033-cb050008bc74.png)

这种写法不对,有没有什么方法可以解决这种需求

**Comment by zkwolf** [comment]
用jsx/tsx是可以的

**Comment by w88975** [comment]
同样的问题

**Comment by fayeah** [comment]
这个issue没有答案嘛 [哭笑不得]

**Comment by fayeah** [comment]
> 用jsx/tsx是可以的

请问tsx怎么使用呢？能给到一个代码片段嘛？

**Comment by zkwolf** [comment]
给个最小复现我给你改？

**Comment by fayeah** [comment]
> 给个最小复现我给你改？

```
// 自定义Table, XXX.tsx
export default defineComponent({
  name: "BTable",
  props,
  setup(props, ctx) {
    const change = (event: Event) => {
      ctx.emit("change", event);
    };
    return {
      change,
    };
  },

  render() {
    const { loading, total, current } = this;

    return (<a-table
        dataSource={this.dataSource}
        columns={this.columns}
        rowKey="id"
        change={(event: Event) => this.change(event)}
        loading={loading}
      >
        { Object.keys(this.$slots).map(name => (<template slot={name}>{this.$slots[name]}</template>)) }
      </a-table>
);
  },
});


// 使用自定义Table, XXX.vue
<b-table
    :dataSource="dataSource"
    :columns="columns"
    :total="totalCount"
    :current="currentPage"
    :loading="loading"
    @change="onChange"
  >
    <template #name="{ record }">
      <a :href="xxx">{{ record.name }}</a>
    </template>
  </b-table>
```

**Comment by fayeah** [comment]
更新：

使用的vue3和ts，`this.$slots[name]`需要这样写: `this.$slots[name]?.()`，但是还不能正常显示，因为slot里面的`record` 拿不到，也不知道为啥。
![image](https://user-images.githubusercontent.com/29644978/139676803-0602bab2-3390-483f-96e9-d6782a8f6f84.png)

**Comment by zkwolf** [comment]
要是用jsx的话可以这么写
```
<a-table v-slots={this.$slots}>
</a-table>
```
来接收父级传入的slots，传给a-table组件

**Comment by fayeah** [comment]
> 来接收父级传入的slots，传给

加上v-slots可以渲染了，但是我需要动态拿到dataSource的record，这个时候我应该怎么传呢？比如说:
```
// 使用的组件
<b-table
    ...
  >
     <template #name="{ record }">
      <span>{{ record.id }} </span>   //想获取record的id
    </template>
  </b-table>
```
想拿到record的id，之前的静态的数据可以拿到，那怎么动态地传递record以及text这些数据呢？

**Comment by zkwolf** [comment]
https://codesandbox.io/s/lucid-lehmann-gwyeq?file=/src/main.js 直接用就可以啊

**Comment by fayeah** [comment]
我说一直报错:`console.log("this", this.$slots.name?.());`，这段话导致页面加载出错，。现在可以了，非常感谢 ~~~
