### ISSUE TITLE
When searching the input content in the Treeselect input box (the data contains the content) part of the search results cannot be found

### ISSUE THREAD

**Issue by LiangJieMr** [vueComponent/ant-design-vue#4255]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.1

### Environment
vue3.0

### Reproduction link
[https://2x.antdv.com/components/tree-select-cn/](https://2x.antdv.com/components/tree-select-cn/)

### Steps to reproduce
Treeselect输入框输入内容时（数据包含该内容），部分结果搜不出来

### What is expected?
可以搜索出结果

### What is actually happening?
Treeselect输入框搜索内容无数据

**Comment by wubiandaxian** [comment]
文档内容：
filterTreeNode:  是否根据输入项进行筛选，默认用 treeNodeFilterProp 的值作为要筛选的 TreeNode 的属性值

TreeNode props
     value:  默认根据此属性值进行筛选（其值在整个树范围内唯一）

解决：
 搜索默认使用的是 TreeNode props 中 value字段，要是想自定义，可以使用treeNodeFilterProp设置，或者在filterTreeNode中使用函数自定义
