### ISSUE TITLE
<Menu.Item inlineIndent={24}> 报错错误

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue#4257]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.5

### Environment
windows10,google chrome 79.0.3945.130,vue 3.05

### Reproduction link
[https://github.com/vueComponent/pro-layout/blob/next/examples/index.tsx#L119](https://github.com/vueComponent/pro-layout/blob/next/examples/index.tsx#L119)

### Steps to reproduce
1. 将ant-design-vue切换成2.2.0-beta.5
2. ![](https://markdown-1252756644.cos.ap-guangzhou.myqcloud.com/20210624185605.png)

### What is expected?
没有ts报错

### What is actually happening?
![](https://markdown-1252756644.cos.ap-guangzhou.myqcloud.com/20210624185605.png)

**Comment by tangjinzhou** [comment]
menu.item 没有inlineIndent属性
menu才有
