### ISSUE TITLE
Cascader not auto select popup menu at first time when using loadData

### ISSUE THREAD

**Issue by tinpont** [vueComponent/ant-design-vue#4262]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
vue:3.0.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-ramanujan-yddms)

### Steps to reproduce
1. click cascader, popup menu not auto selected
2. close popup menu
3. click cascader again, popup menu has auto selected

### What is expected?
popup menu should auto select at first time

### What is actually happening?
popup menu not auto select at first time

**Comment by ajuner** [comment]
`loadData` is used to load a single option, it will affect the rendering of the `value`
Just remove the `loadData` parameter

**Comment by tinpont** [comment]
@ajuner Hi, I have 4 level areas(province, city, district, town). Due to reduce local storage size, I only cache 3 level areas(province, city, district). So for level 4(town), the only way is use `loadData` to load remote data by parent area code. Maybe there is a better way to solve this problem?

**Comment by tinpont** [comment]
Hi, @ajuner , I update my `CodeSandbox` example to make things clear.

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-ramanujan-yddms?file=/src/App.vue)

**Comment by ajuner** [comment]
There is a related issue: https://github.com/ant-design/ant-design/issues/16968
