### ISSUE TITLE
[Blocking] My app no longer bootstraps after upgrading to the latest beta

### ISSUE THREAD

**Issue by CarterLi** [vueComponent/ant-design-vue#4263]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.5

### Environment
vue 3.1.2, vite v2.3.8

### Reproduction link
[http://example.com](http://example.com)

### Steps to reproduce
```
createApp(xxx).use(Antd)
```

### What is expected?
Runs normally

### What is actually happening?'
`TypeError: Cannot read property 'name' of undefined`: `List.Item` is undefined

![image](https://user-images.githubusercontent.com/6134068/123374205-57954b00-d5b9-11eb-8f82-36fd3947bca6.png)

https://github.com/vueComponent/ant-design-vue/blob/8d8f940552f1bd87c8a0966e61410c265f0c7115/components/list/index.tsx#L327

**Comment by zkwolf** [comment]
清一下vite的缓存看看？我这试了一下没问题

**Comment by tangjinzhou** [comment]
再不行 删除 node_modules  重新安装
