### ISSUE TITLE
[BUG] <Button> prevent mouse events of <i> <span> inside

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#4264]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.x & 1.x

### Environment
MacOS 10.13.4, Chrome 91.0.4472.114, Vue 2.6.10

### What is expected?
remove: `pointer-events: none;`

### What is actually happening?
`pointer-events: none` will prevent mouse events of  `i` & `span` in `Button`

---
Antdv was copied from Ant Design (React), so the issue was copied too.

And then Ant Design reverted that PR 2 years later, but Antdv didn't.

Here is why we have `pointer-events: none`: 
https://github.com/ant-design/ant-design/issues/7034

And here is why it had been removed:
https://github.com/ant-design/ant-design/issues/24090

**Comment by gaokun** [comment]
@tangjinzhou  
Plz help to check
Thx

**Comment by John60676** [comment]
Will be supported in the next version
