### ISSUE TITLE
我把示例download 下来之后在本地跑不起来 缺少文件

### ISSUE THREAD

**Issue by guoshuke** [vueComponent/ant-design-vue#427]
![a2ff1d71-18cf-4826-a2d4-49b7f527e5e1](https://user-images.githubusercontent.com/20693126/51509708-2129d380-1e35-11e9-9d8f-0aa95c11861b.png)

**Comment by guoshuke** [comment]
![image](https://user-images.githubusercontent.com/20693126/51509842-a01f0c00-1e35-11e9-84dc-f7e1e37e18fc.png)

**Comment by wangxueliang** [comment]
你可以根据提示自己创建这个文件，或者用npm start
