### ISSUE TITLE
Divider component dashed top border color error

### ISSUE THREAD

**Issue by atom-git** [vueComponent/ant-design-vue#4270]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.5

### Environment
MAC chrome91 ant design vue 2.2.0-beta.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-g4utx?file=/src/App.vue)

### Steps to reproduce
Divider component dashed top border color error

### What is expected?
thank you for make this error correctly

### What is actually happening?
border color is right

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/4271
