### ISSUE TITLE
The anchor component is used in the drawer, it is invalid, it is not automatically selected with scrolling, and it will not be automatically positioned when clicked (routing mode is hash)

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#4274]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.6

### Environment
MacOS 10.15.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-anchor-test-r5ul9?file=/src/Home.vue)

### Steps to reproduce
1. 滚动页面到最下方，anchor会自动选中对应的部分
2. 点击按钮打开抽屉，在抽屉中滚动，anchor不会自动选中对应的部分

### What is expected?
在抽屉中滚动anchor可以跟随滚动自动选中，点击anchor也可以自动定位到相应的位置

### What is actually happening?
抽屉中anchor失效了

**Comment by tangjinzhou** [comment]
查看文档  使用 getContainer
