### ISSUE TITLE
Use vite-plugin-components to load on demand. There is a problem that the style cannot be loaded. The tsx .vue components are not effective! ! ! ! !

### ISSUE THREAD

**Issue by zs-g** [vueComponent/ant-design-vue#4279]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.6

### Environment
2.2.0-bate.6  谷歌游览器 版本 91.0.4472.114（正式版本） （64 位）  vue 3.1.2   vite-plugin-components 0.11.2

### Reproduction link
[https://github.com/antfu/vite-plugin-components](https://github.com/antfu/vite-plugin-components)

### Steps to reproduce
按照 vite-plugin-components 提供的针对 ant design vue  配置例子 配置    启动项目之后  出现样式无法 加载的问题！

### What is expected?
自动 按需加载样式

### What is actually happening?
没有按需加载样式

![1](https://user-images.githubusercontent.com/46895375/123570716-65d2a980-d7fb-11eb-9593-0f09bfa0c241.jpg)
![2](https://user-images.githubusercontent.com/46895375/123570720-679c6d00-d7fb-11eb-870b-3f22f40f0690.jpg)
![3](https://user-images.githubusercontent.com/46895375/123570725-69663080-d7fb-11eb-8e23-f766a31d6735.jpg)

**Comment by ajuner** [comment]
vite-plugin-components更新到0.11.3试试

**Comment by zs-g** [comment]
> vite-plugin-components 更新到0.11.3 学习

最新版本只有  0.11.2

**Comment by ajuner** [comment]
好吧  还没发版

**Comment by zs-g** [comment]
不是 ant design vue 的问题 是 vite-plugin-components 内置的 AntDesignVueResolver 方法出现了问题  
使用：
import ViteComponents from 'vite-plugin-components'

ViteComponents({customComponentResolvers: [
      (name: string) => {
        return {
          importName: name.slice(1),
          path: 'ant-design-vue/es',
          sideEffects: "ant-design-vue/es/style",
        }
      }
      // AntDesignVueResolver()
]})

不要直接使用 vite-plugin-components 提供的 AntDesignVueResolver 即可解决样式无法加载的问题   

希望 0.11.3版本 能解决这个问题

**Comment by ajuner** [comment]
这样是不是也有点问题  样式不是按需加载的

**Comment by zs-g** [comment]
> 这样是不是也有点问题 样式不是按需加载的

这个 其实就是  AntDesignVueResolver 实现的逻辑  只是不知道作者在 调用 还是什么环节  导致 AntDesignVueResolver  出现了问题了  https://github.com/antfu/vite-plugin-components/blob/main/src/resolvers/antdv.ts 你看一下 AntDesignVueResolver  的实现源码  

下载了 它的源码 搞不太懂   不然 可以去提个 PR

**Comment by coopoo** [comment]
import viteComponents, { kebabCase } from "vite-plugin-components";
const AntDesignVueResolver = () => (name: string) => {
  const noEffects = ["LayoutHeader", "LayoutFooter", "LayoutContent"];
  if (name.match(/^A[A-Z]/)) {
    const partialName = name.slice(1);
    const path = "ant-design-vue/es";
    if (partialName === "CardMeta") return path + "/card/Meta";
    if (partialName === "LayoutSider") return path + "/layout/Sider";
    return {
      importName: partialName,
      path,
      sideEffects: !noEffects.includes(partialName)
        ? `ant-design-vue/es/${kebabCase(partialName)}/style/css`
        : void 0,
    };
  }
};
能解决大部分问题吧, 细节自己调

**Comment by coopoo** [comment]
`
import viteComponents, { kebabCase } from "vite-plugin-components";
const AntDesignVueResolver = () => (name: string) => {
  const noEffects = ["LayoutHeader", "LayoutFooter", "LayoutContent"];
  if (name.match(/^A[A-Z]/)) {
    const partialName = name.slice(1);
    const path = "ant-design-vue/es";
    if (partialName === "CardMeta") return path + "/card/Meta";
    if (partialName === "LayoutSider") return path + "/layout/Sider";
    return {
      importName: partialName,
      path,
      sideEffects: !noEffects.includes(partialName)
        ? `ant-design-vue/es/${kebabCase(partialName)}/style/css`
        : void 0,
    };
  }
};`

能解决大部分问题吧, 细节自己调

**Comment by coopoo** [comment]
<pre>
import viteComponents, { kebabCase } from "vite-plugin-components";
  const AntDesignVueResolver = () => (name: string) => {
  const noEffects = ["LayoutHeader", "LayoutFooter", "LayoutContent"];
  if (name.match(/^A[A-Z]/)) {
    const partialName = name.slice(1);
    const path = "ant-design-vue/es";
    if (partialName === "CardMeta") return path + "/card/Meta";
    if (partialName === "LayoutSider") return path + "/layout/Sider";
    return {
      importName: partialName,
      path,
      sideEffects: !noEffects.includes(partialName)
        ? `ant-design-vue/es/${kebabCase(partialName)}/style/css`
        : void 0,
    };
  }
};
</pre>

能解决大部分问题吧, 细节自己调

**Comment by coopoo** [comment]
<pre>
import viteComponents, { kebabCase } from "vite-plugin-components";
  const AntDesignVueResolver = () => (name: string) => {
  const noEffects = ["LayoutHeader", "LayoutFooter", "LayoutContent"];
  if (name.match(/^A[A-Z]/)) {
    const partialName = name.slice(1);
    const path = "ant-design-vue/es";
    if (partialName === "CardMeta") return path + "/card/Meta";
    if (partialName === "LayoutSider") return path + "/layout/Sider";
    return {
      importName: partialName,
      path,
      sideEffects: !noEffects.includes(partialName)
        ? `ant-design-vue/es/${kebabCase(partialName)}/style/css`
        : void 0,
    };
  }
};
</pre>

能解决大部分问题吧, 细节自己调

**Comment by coopoo** [comment]
<pre>
import viteComponents, { kebabCase } from "vite-plugin-components";
  const AntDesignVueResolver = () => (name: string) => {
  const noEffects = ["LayoutHeader", "LayoutFooter", "LayoutContent"];
  if (name.match(/^A[A-Z]/)) {
    const partialName = name.slice(1);
    const path = "ant-design-vue/es";
    if (partialName === "CardMeta") return path + "/card/Meta";
    if (partialName === "LayoutSider") return path + "/layout/Sider";
    return {
      importName: partialName,
      path,
      sideEffects: !noEffects.includes(partialName)
        ? `ant-design-vue/es/${kebabCase(partialName)}/style/css`
        : void 0,
    };
  }
};
</pre>

能解决大部分问题吧, 细节自己调

**Comment by uinio** [comment]
try https://github.com/anncwb/vite-plugin-style-import

**Comment by nabaonan** [comment]
[vite-plugin-components  按需加载样式PR](https://github.com/antfu/vite-plugin-components/pull/78)
提了好久，一直没有通过，作者也没有发版，要不就考下来先用着，等发版 @zs-g

**Comment by nabaonan** [comment]
最近在掘金更的文章，可以做个参考   [按需加载更优雅的解决方案——vite-plugin-components](https://juejin.cn/post/6976558626425028645)

**Comment by zs-g** [comment]
这个文章写很好啊    文章中所解决的 BUG  都是我遇到的 ！！！！！  谢谢兄弟！！
________________________________
发件人: 内小子 ***@***.***>
发送时间: 2021年6月29日 4:02
收件人: vueComponent/ant-design-vue ***@***.***>
抄送: 清欢 ***@***.***>; Mention ***@***.***>
主题: Re: [vueComponent/ant-design-vue] Use vite-plugin-components to load on demand. There is a problem that the style cannot be loaded. The tsx .vue components are not effective! ! ! ! ! (#4279)


最近在掘金更的文章，可以做个参考 按需加载更优雅的解决方案――vite-plugin-components<https://juejin.cn/post/6976558626425028645>

―

**Comment by nabaonan** [comment]
今天早上antfu合了PR，主要加了css和less可选配置项，敬请期待发版咯~ @zs-g

**Comment by nabaonan** [comment]
更新一下插件版本到0.11.4，已经发版了 @zs-g 试一下

**Comment by nabaonan** [comment]
插件配置方式如下：

一共加了三个参数，默认什么都不传，如果传参则通过对象的形式传
默认值：
` importStyle: true`
` importCss：true`   
` importLess:false ` 


1. 只加载css   
```js
AntDesignVueResolver()
```

2. 只加载less  
```js
AntDesignVueResolver({
    importLess: true
})
```
说明：需要开启less的  ` javascriptEnabled: true,`

3. 不加载组件样式：
```js
AntDesignVueResolver({
    importStyle: false
})
```

插件参数定义如下
```typescript
export interface AntDesignVueResolverOptions {
  /**
   * import style along with components
   *
   * @default true
   */
  importStyle?: boolean
  /**
   * import css along with components
   *
   * @default true
   */
  importCss?: boolean
  /**
   * import less along with components
   *
   * @default false
   */
  importLess?: boolean
}
```

**Comment by Leebusan** [comment]
@nabaonan  vite-plugin-components我更新到了0.13.2 碰到了一个问题：
```
 import  { message, Modal } from 'ant-design-vue'
 Modal.confirm({...}）
```
 这样使用时，不会加载 modal的样式
然后全局导入
` @import 'ant-design-vue/dist/antd.css';`
样式正常，但是这样违背了按需加载的初衷？

**Comment by nabaonan** [comment]
> 样式正常，但是这样违背了按需加载的初衷？

这个vite插件只解析了模板中的内容，tsx中我再试试，感觉这个插件应该不会自动解析非template的组件，tsx中可以试试vite-plugin-style-import这个插件

**Comment by nabaonan** [comment]
@Leebusan https://codesandbox.io/s/antdv-tsx-ondemand-9ipv0    配合vite-plugin-style-import是可以的

**Comment by Leebusan** [comment]
@nabaonan  谢谢 我试了下 可以加载
