### ISSUE TITLE
How to change the style of collapse content?

### ISSUE THREAD

**Issue by cis1124** [vueComponent/ant-design-vue#4281]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Is there any way to change the style of collapse content,not header?
有没有办法修改折叠面板内容样式，不包括Header?

### What does the proposed API look like?
such as :bodyStyle="style"

**Comment by cis1124** [comment]
![image](https://user-images.githubusercontent.com/5029476/123575546-9a972e80-d804-11eb-9ccd-f4eaa4aefa07.png)

**Comment by tangjinzhou** [comment]
```
<a-collapse-panel key="1" header="This is panel header 1">
      <p class="xxx">{{ text }}</p>
    </a-collapse-panel>
```
