### ISSUE TITLE
Failed to drag and retract the retractable column! 20210628

### ISSUE THREAD

**Issue by houkanlark** [vueComponent/ant-design-vue#4285]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.6

### Environment
chrome

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-resizable-column](https://www.antdv.com/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
官网案例操作失败

### What is expected?
拖动表格列可伸缩

### What is actually happening?
拖动表格列不可伸缩

---
一周前可正常伸缩

**Comment by tangjinzhou** [comment]
添加样式 

```css
.resize-table-th .table-draggable-handle {
    position: absolute;
}
```
