### ISSUE TITLE
Ask the author some questions about source code governance.

### ISSUE THREAD

**Issue by jason-chang** [vueComponent/ant-design-vue#4287]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
问作者几个代码治理相关的问题
1. 为什么组件代码分 component(TS) 和 vc-components(JS) 两部分？为什不全用 ts 写？
2. 项目应该是会定期 合并 antd react 的特性吧。请问一般怎么做人工定期吗？还是会有机器人辅助？组件代码分两部分是不是和这个（合并特性）有关？这个（合并特性）是否会遇到什么挑战，怎么解决的

### What does the proposed API look like?
无

**Comment by tangjinzhou** [comment]
1、都会用 ts 的，只是时间精力问题
2、ci 辅助 + 人工，以及部分组件会和 react版本差别较大，同步方式变成了 UI同步，逻辑独立例如 form
