### ISSUE TITLE
No access to the menu component of version 1.7.6, https://1x.antdv.com/docs/vue/introduce-cn/

### ISSUE THREAD

**Issue by leejaygo** [vueComponent/ant-design-vue#4289]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
1.7.6

### Reproduction link
[https://1x.antdv.com/docs/vue/introduce-cn/](https://1x.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
无法访问

### What is expected?
修复

### What is actually happening?
无法访问

**Comment by tangjinzhou** [comment]
正常
试试清空缓存
