### ISSUE TITLE
The a-textarea component cannot be dragged now (the resize attribute has no effect)

### ISSUE THREAD

**Issue by ch1ies** [vueComponent/ant-design-vue#4292]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
MAC chrome

### Reproduction link
[https://antdv.com/components/input-cn/](https://antdv.com/components/input-cn/)

### Steps to reproduce
···

### What is expected?
默认使用a-textarea组件时支持resize 拖动

### What is actually happening?
现在需要手动在textarea属性上设置resize: 'vertical'

---
好像从1.5.0版本后都不支持

**Comment by heshijian** [comment]
这个应该是一行内容太多了 所以拖拽那个就不显示了 我刚才也遇到了
