### ISSUE TITLE
When the anchor component is in affix mode, the showInkInFixed attribute is invalid

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#4293]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-rc.1

### Environment
MacOS 10.15.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdv-anchor-showinkinfixed-ts0z5?file=/src/App.vue:47-61)

### Steps to reproduce
showInkInFixed无论设置true还是false，小圆点都不消失

### What is expected?
showInkInFixed设置为false小圆点消失

### What is actually happening?
showInkInFixed 无论设置true还是false，小圆点总显示

**Comment by tangjinzhou** [comment]
https://github.com/ant-design/ant-design/commit/ca18e8cd8708fa81eac0466d5006cb9208b2d1e7
文档会更新
