### ISSUE TITLE
Use a-icon in vuecli3 to report an error and cannot be displayed

### ISSUE THREAD

**Issue by songlinrong** [vueComponent/ant-design-vue#4295]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-rc.1

### Environment
vue3.0.0

### Reproduction link
[https://gitee.com/songlinrong/antd-vue3.0.git](https://gitee.com/songlinrong/antd-vue3.0.git)

### Steps to reproduce
<a-icon type="home" />

### What is expected?
页面回显图标

### What is actually happening?
不显示图标，浏览器显示警告Failed to resolve component: a-icon

**Comment by zkwolf** [comment]
参见文档
![image](https://user-images.githubusercontent.com/8555127/123907759-fdc1c600-d9a8-11eb-9cbb-f3ab8e2f34e3.png)

**Comment by songlinrong** [comment]
@zkwolf  里面是没有icon文件的，按照截图方式引入是找不到icon的。

**Comment by zkwolf** [comment]
给你个示例吧如果你用`<a-icon type="home" />`的话，需要`import HomeOutlined from '@ant-design/icons-vue/HomeOutlined'`

**Comment by songlinrong** [comment]
> 
> 
> 给你个示例吧如果你vue2里用`<a-icon type="home" />`的话，vue3需要`import HomeOutlined from '@ant-design/icons-vue/HomeOutlined'`
> 
> btw:文档那个路径好像确实有点问题
谢谢，试过你给的方式，是可以的。
