### ISSUE TITLE
update to 2.20-rc.1 typescript error

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#4296]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-rc.1

### Environment
vs code, yarn ,vite , typescript

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/commit/c563097faa4f5dfd9c04ace19999160c44bd6e80#diff-3fee134a410a783dfd5f6f89b1a8f7e7eb1ba8e332aeaf4cafdefc4c723088e9R59-R62](https://github.com/vueComponent/ant-design-vue/commit/c563097faa4f5dfd9c04ace19999160c44bd6e80#diff-3fee134a410a783dfd5f6f89b1a8f7e7eb1ba8e332aeaf4cafdefc4c723088e9R59-R62)

### Steps to reproduce
yarn build

### What is expected?
build success

### What is actually happening?
error:
Property 'title' of type 'string | undefined' is not assignable to string index type 'string'.ts(2411)
(property) title?: string | undefined

![image](https://user-images.githubusercontent.com/22545824/123896042-68680700-d993-11eb-9b81-b0bfdc751f2d.png)

**Comment by zguolee** [comment]
I have the same problem.

**Comment by tangjinzhou** [comment]
try clear vite cache or reinstall node_modules

**Comment by nabaonan** [comment]
![image](https://user-images.githubusercontent.com/17247526/123942543-d03b4380-d9cd-11eb-830a-d80e6bbcdba0.png)
I have a ts 2345 problem

**Comment by nabaonan** [comment]
> ![image](https://user-images.githubusercontent.com/17247526/123942543-d03b4380-d9cd-11eb-830a-d80e6bbcdba0.png)
> I have a ts 2345 problem

disable Volar ,can resolve my problem

**Comment by tanggd** [comment]
I have the same problem.

**Comment by tanggd** [comment]
I have the same problem.

**Comment by zguolee** [comment]
can delete `vue-tsc --noEmit &&` to solve, maybe vue-tsc bug

**Comment by tanggd** [comment]
![image](https://user-images.githubusercontent.com/23456667/124057331-d8d95b80-da59-11eb-8e31-2e84d0b02756.png)

**Comment by tanggd** [comment]
use "vue-tsc --noEmit --skipLibCheck && vite build" or "vite build"

**Comment by agoni1212** [comment]
@zguolee I do not think so
downgrade to beta 6, it works fine

> can delete `vue-tsc --noEmit &&` to solve, maybe vue-tsc bug.
> [same problem](https://github.com/element-plus/element-plus/issues/1886)

**Comment by agoni1212** [comment]
downgrade to beta 6, it works fine
