### ISSUE TITLE
a-row and a-col can be combined at any level without restriction. The upper level of a-col must be a-row or a-row can be bound to other doms in the form of use.

### ISSUE THREAD

**Issue by cloud0072** [vueComponent/ant-design-vue#4308]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-row和a-col可以任意层级的组合而不必限制 a-col的上一级必须是a-row
或者a-row可以使用use的形式绑定在其他dom上

### What does the proposed API look like?
使antdesignvue 2.x 支持< a-row >< div >< a-col >< /a-col >< /div >< /a-row >形式的写法或 < div ref='ant-row' >< a-col >< /a-col >< /div >

**Comment by zkwolf** [comment]
大概这样？ #3805

**Comment by tangjinzhou** [comment]
试试最新 2.2 版本

**Comment by cloud0072** [comment]
非常感谢唐老师能够帮助我们项目上的难题！通过以下代码顺利运行成功
<a-row&gt;
  <div style="display: flex; flex-wrap: wrap; width: 100%"&gt;
    <a-col :span="6"&gt;1</a-col&gt;
    <a-col :span="6"&gt;2</a-col&gt;
    <a-col :span="6"&gt;3</a-col&gt;
    <a-col :span="6"&gt;4</a-col&gt;
    <a-col :span="6"&gt;5</a-col&gt;
    <a-col :span="6"&gt;6</a-col&gt;
    <a-col :span="6"&gt;7</a-col&gt;
    <a-col :span="6"&gt;8</a-col&gt;
  </div&gt;
</a-row&gt;
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月4日(星期天) 下午2:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] a-row and a-col can be combined at any level without restriction. The upper level of a-col must be a-row or a-row can be bound to other doms in the form of use. (#4308)





 
试试最新 2.2 版本
