### ISSUE TITLE
After the TreeSelect component searches and selects the node, click the component again, the tree is collapsed

### ISSUE THREAD

**Issue by wubiandaxian** [vueComponent/ant-design-vue#4314]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.3

### Environment
windows， Chrome(89.0.4389.114)， 3.0.11

### Reproduction link
[https://2x.antdv.com/components/tree-select-cn#API](https://2x.antdv.com/components/tree-select-cn#API)

### Steps to reproduce
TreeSelect组件搜索后，点击搜索的结果完成选择，再点击组件，树形组件不会自动展开到当前选中的结果分支。
官方实例，后缀图标示例。
1. 点击组件，把树折叠
2. 搜索 ‘leaf2’，选中搜索结果
3. 再次点击组件，树还是折叠状态，并没有展开对应的分支

### What is expected?
搜索且选择节点后，再次点击组件，能够自动打开该节点所在的分支

### What is actually happening?
搜索且选择节点后，再次点击组件，树是折叠的

**Comment by tangjinzhou** [comment]
预期行为

**Comment by wubiandaxian** [comment]
> 预期行为

那我是否什么办法，能在搜索完成后设置打开选中项所在分支为打开状态。
