### ISSUE TITLE
table组件是否可以支持“显示行号”功能

### ISSUE THREAD

**Issue by BeautifulHao** [vueComponent/ant-design-vue#432]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决行号显示问题

### What does the proposed API look like?
showLineNumber:true/false

**Comment by tangjinzhou** [comment]
可以通过如下方式添加
```
const columns = [{
  dataIndex: 'number',
  key: 'number',
  title: '序号',
  customRender: (text, record, index)=> index
}]
```

**Comment by windylaugit** [comment]
+1，同样需求。
----
研究了一天table和vc-talbe源码，没找到可行方式添加行序号，只能等官方支持了。。。

**Comment by kagaricyan** [comment]
> 可以通过如下方式添加
> 
> ```
> const columns = [{
>   dataIndex: 'number',
>   key: 'number',
>   title: '序号',
>   customRender: (text, record, index)=> index
> }]
> ```

分页情况下index只是当前页的index，我还想展示整个数据中的index

**Comment by ydfzgyj** [comment]
> 分页情况下index只是当前页的index，我还想展示整个数据中的index

乘一下页码不就好了？

**Comment by kagaricyan** [comment]
> > 分页情况下index只是当前页的index，我还想展示整个数据中的index
> 
> 乘一下页码不就好了？

问题就是我没找到如何获取页码

**Comment by ydfzgyj** [comment]
> 问题就是我没找到如何获取页码。我用的它自带的分页器

传一个自定义的 pagination 进去就好了，current 是 v-model 绑定的，可以直接取

**Comment by kagaricyan** [comment]
> > 问题就是我没找到如何获取页码。我用的它自带的分页器
> 
> 传一个自定义的 pagination 进去就好了，current 是 v-model 绑定的，可以直接取

多谢，已解决

**Comment by haossu** [comment]
> > > 问题就是我没找到如何获取页码。我用的它自带的分页器
> > 
> > 
> > 传一个自定义的 pagination 进去就好了，current 是 v-model 绑定的，可以直接取
> 
> 多谢，已解决

你好,请问是咋解决的...方便分享一下吗

**Comment by kagaricyan** [comment]
> > > > 问题就是我没找到如何获取页码。我用的它自带的分页器
> > > 
> > > 
> > > 传一个自定义的 pagination 进去就好了，current 是 v-model 绑定的，可以直接取
> > 
> > 
> > 多谢，已解决
> 
> 你好,请问是咋解决的...方便分享一下吗

table组件绑定pagination对象，然后监听翻页事件，手动更新页码。这样页码就是你提供的，怎么获取就不用说了吧

**Comment by shady-xia** [comment]
这是一个很常见的功能，不知道为什么ant-design一直不做集成

**Comment by zkwolf** [comment]
大概是因为自己实现也很简单，可以考虑文档给补个demo
