### ISSUE TITLE
a-upload needs to display the upload progress value

### ISSUE THREAD

**Issue by computer-idol** [vueComponent/ant-design-vue#4320]
-  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
默认的进度上传只有进度条，没有显示出进度数值，尤其是上传视频，让用户可以清晰地看到还有多少没有上传完成

### What does the proposed API look like?
操作系统：win10
浏览器版本： chrome 91.0.4472.124
Vue版本:  v2

**Comment by tangjinzhou** [comment]
数据在你接口里已经有了  自行展示即可
