### ISSUE TITLE
When implementing a table scalable column, the column setting attribute ellipsis is true. The minimum width is not valid .

### ISSUE THREAD

**Issue by CuteTing** [vueComponent/ant-design-vue#4321]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
WIn10、Google Chrome91.0.4472.114（正式版本）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-c6f5n?file=/src/App.vue)

### Steps to reproduce
复制官网表格伸缩列的案例，将columns数据每条数据都添加属性ellipsis:true

### What is expected?
收缩列的时候列要留最小宽度显示

### What is actually happening?
收缩列的时候整个列可以缩不见

**Comment by tangjinzhou** [comment]
伸缩只是个 demo  组件本身没有提供api，自行扩展示例，控制宽度

**Comment by CuteTing** [comment]
好的
