### ISSUE TITLE
In Safari, DatePicker moves the page when selecting a date, and the document example can be reproduced

### ISSUE THREAD

**Issue by elvisqi** [vueComponent/ant-design-vue#4323]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-rc.1

### Environment
macOs 11.4, safari 14.1.1

### Reproduction link
[https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-start-end](https://2x.antdv.com/components/date-picker-cn#components-date-picker-demo-start-end)

### Steps to reproduce
1、打开官方文档地址：https://2x.antdv.com/components/date-picker-cn
2、将第一个日期选择框移动到页面顶部
3、点击 请选择日期，光标foucs到弹出选择日期的位置，导致页面位置发生了变化

### What is expected?
不需要foucs，设置了:autofocus="false" 也无效

### What is actually happening?
光标foucs，导致页面位置发生了变化

https://user-images.githubusercontent.com/3584916/124475664-8c34ae00-ddd4-11eb-8221-d3cc929681bb.mov

**Comment by tangjinzhou** [comment]
顶部广告突然展示的问题吧

**Comment by elvisqi** [comment]
仔细看下最后的画面，整个页面跳到了top:0 的位置
我分析问题应该是由于只有选择日期的时候，出现的input中有foucs，导致页面被定位到了中间。

再录个屏，从顶部开始

https://user-images.githubusercontent.com/3584916/124527266-caaf8480-de37-11eb-855d-5794173b5ee6.mov
