### ISSUE TITLE
When the menu component in the layout component shrinks with submenu items, no animation is triggered

### ISSUE THREAD

**Issue by tengli1990** [vueComponent/ant-design-vue#4325]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
macOS Catalina 10.15.7 (19H524)、Chrome 91.0.4472.114（正式版本）、vue ^3.0.11

### Reproduction link
[https://2x.antdv.com/components/layout-cn#components-layout-demo-side](https://2x.antdv.com/components/layout-cn#components-layout-demo-side)

### Steps to reproduce
1、Open address https://2x.antdv.com/components/layout-cn#components-layout-demo-side
2、Open the layout component, view the sidebar component, and click the shrink button. There is no animation when some menus shrink

### What is expected?
The animation is consistent when the menu shrinks

### What is actually happening?
Menus with submenus have no shrink animation

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/124551299-825a8b80-de64-11eb-9863-94fc5be9046e.png)
this?

**Comment by tengli1990** [comment]
是的，收缩的时候，没动画，图标一下子就剧中了，感觉会闪一下，侧边栏越宽越明显。
