### ISSUE TITLE
[Tree]how to get parent node on click

### ISSUE THREAD

**Issue by snowchenlei** [vueComponent/ant-design-vue#4326]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

[document](https://2x.antdv.com/components/tree-cn)
        
### What problem does this feature solve?
当checkStrictly设置为true并在check回调中需要获取父节点状态，并设置父节点选中状态时，我没有找到api可以实现此需求。

### What does the proposed API look like?
node参数可以获取父节点，并设置父节点的状态

**Comment by maicss** [comment]
能不能在check或者select事件里暴露一个path的属性？现在有个私有属性pos，就是类似这个属性，不过现在如果想要拿到用户自己的数据，就要用户一个个去循环遍历出来。

path 举例：
path: ['北京市', '东城区']，或者设置的key数组也行。
