### ISSUE TITLE
table typescript error

### ISSUE THREAD

**Issue by xuewangwang** [vueComponent/ant-design-vue#4327]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
vue3.1.4，ts4.3.4，antd2.2.1

### Reproduction link
[https://2x.antdv.com/components/table-cn](https://2x.antdv.com/components/table-cn)

### Steps to reproduce
TS type check failed while building a project。

error code:
export declare type ColumnProps = Partial<ExtractPropTypes<typeof columnProps>> & {
slots?: {
title?: string;
filterIcon?: string;
filterDropdown?: string;
customRender?: string;
[key: string]: string;
};
};

error info:
node_modules/ant-design-vue/lib/table/interface.d.ts:131:9 - error TS2411: Property 'title' of type 'string | undefined' is not assignable to string index type 'string'.

title?: string;
~~~~~


### What is expected?
TS type check failed while building a project。

### What is actually happening?
TS type check failed while building a project。



        

<!-- generated by issue-helper. DO NOT REMOVE -->

**Comment by tangjinzhou** [comment]
duplicate https://github.com/vueComponent/ant-design-vue/issues/4296
