### ISSUE TITLE
The menu link on the official website is somewhat broken

### ISSUE THREAD

**Issue by zhenzhenChange** [vueComponent/ant-design-vue#4328]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0

### Environment
none

### Reproduction link
[https://2x.antdv.com/components/anchor-cn](https://2x.antdv.com/components/anchor-cn)

### Steps to reproduce
部分菜单无法跳转

### What is expected?
正确跳转

### What is actually happening?
无法跳转

[![RooE5V.png](https://z3.ax1x.com/2021/07/06/RooE5V.png)](https://imgtu.com/i/RooE5V)

**Comment by tangjinzhou** [comment]
例如？

**Comment by zhenzhenChange** [comment]
啊 emmmmm，现在又好了.....刚刚真打不开😂

**Comment by zhenzhenChange** [comment]
> 例如？

https://2x.antdv.com/components/anchor-cn#Anchor-Props

这里貌似是样式错乱了？

**Comment by zhenzhenChange** [comment]
没啥问题了，咱就close吧(●'◡'●)
