### ISSUE TITLE
Ant Design Tree asynchronous data load on dynamic tree data

### ISSUE THREAD

**Issue by rahultailwal** [vueComponent/ant-design-vue#4333]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
Windows 10, Chrome,

### Reproduction link
[https://www.antdv.com/components/tree/#load-data-asynchronously](https://www.antdv.com/components/tree/#load-data-asynchronously)

### Steps to reproduce
1. Make the tree data as dynamic based on some button click. On start it will be blank.
2. Expand the node first time to see the loaded data.
3. Clear the tree data and again add the same data and you will lost the expand icon on the nodes.

### What is expected?
Expand icon should always be there on the clear of treedata and again adding the treedata.

### What is actually happening?
Expand icon is not present second time.

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/124682475-69ea7f80-defd-11eb-9fe7-9b987d39b5ec.png)
you can use loadedKeys to reset state.

**Comment by rahultailwal** [comment]
Thanks @tangjinzhou . Is there any code example for loadedkeys?

**Comment by joker77877** [comment]
Why not give an example？
