### ISSUE TITLE
How to change the default style?

### ISSUE THREAD

**Issue by 1422667480** [vueComponent/ant-design-vue#4335]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
"ant-design-vue": "2.2.0", "vue": "^3.0.5",

### Reproduction link
[https://2x.antdv.com/components/popover-cn](https://2x.antdv.com/components/popover-cn)

### Steps to reproduce
How to change the default style?

### What is expected?
Tag styles with default styles such as "p li ul ol" can be modified

### What is actually happening?
Because there is li[data-v-*****] in the style that cannot be modified, adding "important" will affect the style in the project

        
![image](https://user-images.githubusercontent.com/37292247/124696752-38cb7880-df18-11eb-8a0c-e6752a97b348.png)

**Comment by tangjinzhou** [comment]
use class

**Comment by 1422667480** [comment]
> use class

I mean, I want to be clear about the global default style, because it is the default style in the browser, but after compiling it because of 'scope', adding 'data-v-*' directly overwrites the style will not work, but using 'important'.
