### ISSUE TITLE
Put message in ts before useStore(), useStore() will be undefined

### ISSUE THREAD

**Issue by verynong** [vueComponent/ant-design-vue#4337]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
System:     OS: macOS 11.4     
CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz     
Memory: 30.57 MB / 16.00 GB     
Shell: 5.8 - /bin/zsh   
Binaries:     Node: 16.1.0 - ~/.nvm/versions/node/v16.1.0/bin/node     
npm: 7.11.2 - ~/.nvm/versions/node/v16.1.0/bin/npm   
Browsers:     Chrome: 91.0.4472.114     Safari: 14.1.1

### Reproduction link
[https://github.com/verynong/template-vite-vue-pc](https://github.com/verynong/template-vite-vue-pc)

### Steps to reproduce
代码在App.vue中
运行项目查看Console

### What is expected?
ts中message放到useStore()前面使用，useStore()可以正常获取store

### What is actually happening?
ts中message放到useStore()前面使用，useStore()会为undefined
Console报App.vue:45 Uncaught (in promise) TypeError: Cannot read property 'state' of undefined

---
env dev 和 production 都会报undefined

**Comment by tangjinzhou** [comment]
i think this is Vue bug.

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/vue-next/issues/4076

**Comment by tangjinzhou** [comment]
按照官方说法，inject 尽可能前置  目前没有更好的方案
