### ISSUE TITLE
树形表格，当children数组为 0 时，不应该显示加号

### ISSUE THREAD

**Issue by 347184068** [vueComponent/ant-design-vue#434]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.2

### Environment
win10、chrome、vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/x2z65om7qq)

### Steps to reproduce
表格展示树形数据时，children数组长度为0，那么列表前面的操作符显示不正确

### What is expected?
表格展示树形数据时，当children数组为 0 时，不应该显示加号

### What is actually happening?
表格展示树形数据时，当children数组为 0 时，也显示加号

**Comment by tangjinzhou** [comment]
有数组为0时展示加号的需求，如 异步加载
你可以将children置为null
