### ISSUE TITLE
Why is Button type="danger" removed

### ISSUE THREAD

**Issue by tanggd** [vueComponent/ant-design-vue#4343]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
vue3、vite2

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
<a-button type="danger">Danger</a-button>

### What is expected?
<a-button type="danger">Danger</a-button> 不能出现移除前的效果了，但是业务还是很需要这样的效果的

### What is actually happening?
utils.ts:57   [VueTypes warn]: oneOf - value should be one of "default", "primary", "ghost", "dashed", "link", "text".

---
可以保留type="danger"不？

**Comment by John60676** [comment]
`danger` 改为了单独的属性 

`<a-button danger> danger button </a-button>`

**Comment by tanggd** [comment]
> `danger` 改为了单独的属性
> 
> `<a-button danger> danger button </a-button>`

可是不是填充的红色了

**Comment by John60676** [comment]
> > `danger` 改为了单独的属性
> > `<a-button danger> danger button </a-button>`
> 
> 可是不是填充的红色了

`<a-button type="primary" danger> danger button </a-button>`
