### ISSUE TITLE
When Select is performing v-for, if the keys are the same, a bug will occur

### ISSUE THREAD

**Issue by LiLixikun** [vueComponent/ant-design-vue#4348]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
"vue":3.0.2、  "ant-design-vue": "2.1.6",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blazing-shadow-u7kkb?file=/package.json:236-241)

### Steps to reproduce
https://codesandbox.io/s/blazing-shadow-u7kkb?file=/package.json:236-241

### What is expected?
可以渲染、控制台出现警告⚠️

### What is actually happening?
页面直接卡死、我在实际会会出现把 name 渲染成一样的

**Comment by tangjinzhou** [comment]
开发环境会有提示

请不要使用相同的key
