### ISSUE TITLE
Document page crashed ?

### ISSUE THREAD

**Issue by silverlovesl** [vueComponent/ant-design-vue#4356]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
any

### Reproduction link
[https://www.antdv.com/docs/vue/introduce/](https://www.antdv.com/docs/vue/introduce/)

### Steps to reproduce
https://www.antdv.com/docs/vue/introduce/

### What is expected?
Show me the demo page

### What is actually happening?
This site can’t be reached

**Comment by tangjinzhou** [comment]
try again
