### ISSUE TITLE
Select & TreeSelect

### ISSUE THREAD

**Issue by danwell7** [vueComponent/ant-design-vue#4363]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Vue2.6

### Reproduction link
[https://www.antdv.com/components/tree-select/#TreeSelect](https://www.antdv.com/components/tree-select/#TreeSelect)

### Steps to reproduce
1. Example basic 列表中 y轴边框设置滚动， 高度设置小于内容高度 ，2. 滚动鼠标， treeSelect 弹出框会随着鼠标随意滚动

### What is expected?
没有聚焦下拉框内容时，滚动鼠标需要隐藏下拉框

### What is actually happening?
下拉框会随着鼠标随意滚动

**Comment by John60676** [comment]
没看懂你的描述，最好提供一个 demo 并把重现步骤写清楚一些
