### ISSUE TITLE
official website(https://antdv.com/) have bug and can't open  it now  

### ISSUE THREAD

**Issue by Dortok** [vueComponent/ant-design-vue#4364]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
null

### Reproduction link
[https://antdv.com/](https://antdv.com/)

### Steps to reproduce
null

### What is expected?
null

### What is actually happening?
null

---
null

**Comment by tengda100** [comment]
访问不了文档了，闹心

**Comment by Xingsir1991** [comment]
没人管了吗

**Comment by xiaowang1314** [comment]
官方文档挂了
