### ISSUE TITLE
About <a-form> form verification

### ISSUE THREAD

**Issue by 941477276** [vueComponent/ant-design-vue#4365]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
系统：windows10
浏览器：chrome最新版
vue：vue3.0.5
ant-design-vue：2.2.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-khorana-dljk7?file=/src/App.vue)

### Steps to reproduce
`<a-form>`中`<a-select>、<a-radio-group>`等选择性的组件即使选择了值表单校验依然通不过
![a-form bug](https://user-images.githubusercontent.com/20528541/125590446-8c586c19-b976-4495-b512-0650ce669165.gif)

### What is expected?
`<a-form>`中`<a-select>、<a-radio-group>`等选择性的组件选择了值表单校验能正常通过

### What is actually happening?
`<a-form>`中`<a-select>、<a-radio-group>`等选择性的组件即使选择了值表单校验依然通不过

**Comment by lichinlichin** [comment]
看起来radio暂时不支持数字，直接用字符串吧

**Comment by tangjinzhou** [comment]
指定类型 
```js
trueTeeShipId: [
          {
            required: true,
            message: '请选择是否托管设备标识',
            trigger: 'change',
            type: 'number',
          },
        ],
```
