### ISSUE TITLE
@vue/compat support

### ISSUE THREAD

**Issue by connected** [vueComponent/ant-design-vue#4368]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
We currently have a big project running Vue 2 and Antd Vue 1.7.6 and would like to upgrade to Vue 3.

Vue 3 provides migration build (@vue/compat) that helps migrating to new codebase. We were able to start the project under compatibility build with warnings to be fixed as expected, but some Antd components crash with errors. Possibly due to the usage of undocumented features (private component properties/methods etc.)

For example:

SubPopupMenu.js crashes with "Cannot read property 'propsData' of undefined"; Trigger.js crashes with "this.renderComponent is not a function"

Running with "MODE: 3" set in compatConfig leads to: "TypeError: Cannot read property 'getPrefixCls' of undefined" for empty.js

### What does the proposed API look like?
Antd Vue v1 should be tested against migration build and errors should be fixed thus making it possible to migrate to Vue 3.

**Comment by tangjinzhou** [comment]
If you want to use vue3. you can use  antd vue v2.2+.

**Comment by StarHosea** [comment]
same issue

**Comment by pabtab** [comment]
Same issue, how did you solve it?

**Comment by randomVariable2000** [comment]
> Same issue, how did you solve it?

@tangjinzhou

**Comment by YashKandalkar** [comment]
Hi, @tangjinzhou !
We're having the same error: `Uncaught TypeError: Cannot read properties of undefined (reading 'getPrefixCls')`.
I have tried using the latest and the 2.2.8 version too but it gave the same error. Is there any way to make antdv work with `@vue/compat`? Please let me know if you need any additional information. 

![image](https://user-images.githubusercontent.com/35102959/171703837-43d68acd-3fe2-4151-9671-73270dd1fa10.png)


Package versions: 
```
"vue": "^3.1.0",
"ant-design-vue": "^2.2",
"@vue/compat": "^3.1.0",
```
