### ISSUE TITLE
Blank rows appear in nested tables

### ISSUE THREAD

**Issue by liwuxi** [vueComponent/ant-design-vue#4375]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Vue 3.1.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-cookies-xfnsp?file=/src/App.vue)

### Steps to reproduce
see demo

### What is expected?
One more blank expandable line

### What is actually happening?
no black row

**Comment by tangjinzhou** [comment]
children 和 expandedRowRender 是两个冲突的配置

看这两个demo

https://2x.antdv.com/components/table-cn#components-table-demo-expand-children
https://2x.antdv.com/components/table-cn#components-table-demo-nested-table
