### ISSUE TITLE
 I need to customize the location of the required tags (*) for the form.

### ISSUE THREAD

**Issue by full-stop** [vueComponent/ant-design-vue#4377]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
customize the location of the required tags (*) for the form.

### What does the proposed API look like?
```html
<a-form :required-mark-direction="after | before">
```
Default is before

**Comment by tangjinzhou** [comment]
you can use `<template #lable>xxxx <span style="color: red">*</span></template>` to custom label

**Comment by full-stop** [comment]
> you can use `<template #lable>xxxx <span style="color: red">*</span></template>` to custom label

I need a global configuration.
