### ISSUE TITLE
jsx controlled checkbox selection single invalid

### ISSUE THREAD

**Issue by Haloxylon** [vueComponent/ant-design-vue#4378]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在jsx中受控的checkbox 只有全选这个checkbox有用，checkbox-group选择没有任何反应

### What does the proposed API look like?
优化下jsx的 onChange

**Comment by Haloxylon** [comment]
https://codesandbox.io/s/shoukong-checkbox-vlwi8?file=/src/App.tsx

打开的有点慢

**Comment by zkwolf** [comment]
Checkbox.Group 应该监听onChange去改变state.checkedList啊

**Comment by Haloxylon** [comment]
这个本意并不是用onChange再去监听Checkbox.Group

**Comment by zkwolf** [comment]
那你就应该去双向绑定state.checkedList，checkbox group受控状态下选择没反应是预期行为

**Comment by John60676** [comment]
https://codesandbox.io/s/shoukong-checkbox-forked-y6kp5?file=/src/App.tsx
