### ISSUE TITLE
Display Error after Switch Tabs Several Times by Using a-tabs and a-card in ANTD.

### ISSUE THREAD

**Issue by EternallyAscend** [vueComponent/ant-design-vue#4379]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Microsoft Windows 10 20H2, Chrome 91.0.4472.124 & Edge 91.0.864.37, Vue 2.

### Reproduction link
[https://gitee.com/eternallyascend/issue_example](https://gitee.com/eternallyascend/issue_example)

### Steps to reproduce
- router.config.js 建立一个新的路径，重定向到子页面，子页面hideChildrenInMenu，并使用的格式实现子页面的子页面，创建多个Tab，对应的view组件使用BasicList文件中标准列表的填充。(a-tabs, a-tab-pane)
- 启动npm run serve
- 在浏览器中登录，并在路由中选择新创建的路径。
- 反复切换Tab
- Tab内组件显示异常(应该是组件宽度识别到浏览器宽度而不是tab页面宽度了，不清楚原因)

### What is expected?
请求分析错误原因并寻求可能可行的解决方案，以便于解决显示异常的问题。

### What is actually happening?
存在问题的代码处在src/views/cc/views/communication目录下。
正常情况
https://ftp.bmp.ovh/imgs/2021/07/65e3eb118700da85.png
多次切换Tab后
https://ftp.bmp.ovh/imgs/2021/07/3485664e22a0295e.png

**Comment by tangjinzhou** [comment]
路径太长了  请提供最小复现示例
