### ISSUE TITLE
版本升级后，国际化 下 日期控件中的月、日不生效

### ISSUE THREAD

**Issue by sunhui5415** [vueComponent/ant-design-vue#438]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.2

### Environment
win10

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/date-picker-cn/](https://vuecomponent.github.io/ant-design-vue/components/date-picker-cn/)

### Steps to reproduce
引入日期插件，按照国际化方式进行处理

### What is expected?
年月日应该为中文，和阿拉伯数字组成

### What is actually happening?
显示英文的月，周等，年是中文

**Comment by tangjinzhou** [comment]
给个复现链接    文档中的demo 没发现你说的问题

**Comment by shaokunpeng** [comment]
我也遇到同样的问题，把依赖全部删了再用yarn装一遍就好了
