### ISSUE TITLE
Use Input.Password, how to get this Property of visibilityToggle be use in vue3?

### ISSUE THREAD

**Issue by M69W** [vueComponent/ant-design-vue#4392]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
doc: https://2x.antdv.com/components/input,
use Input.Password, I hope it be set the prefix icon for the Input.Password dynamically by `visibilityToggle`, like `ant-design:unlock-filled` or `ant-design:lock-filled`.

### What does the proposed API look like?
like `visibilityToggle` is event that can be watched dynamically.

**Comment by tangjinzhou** [comment]
```html
<template #iconRender="visible"></template>
```

**Comment by M69W** [comment]
![image](https://user-images.githubusercontent.com/15809201/126245452-4ff1ce1e-ebc4-4695-91bd-ed60293fb5b6.png)
