### ISSUE TITLE
An example of table header grouping, if the Company column is removed, there will be a blank column before other. If you look at the source code, two identical tables will be generated.

### ISSUE THREAD

**Issue by stevenliu87** [vueComponent/ant-design-vue#4393]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
1.7.3

### Reproduction link
[https://1x.antdv.com/components/table-cn/](https://1x.antdv.com/components/table-cn/)

### Steps to reproduce
table表头分组的例子，如果把Company列去掉，other前面就会多出一个空白列，查看源码，会生成两个一样的table

### What is expected?
正确显示，不多空白列

### What is actually happening?
多空白列

**Comment by stevenliu87** [comment]
代码在线看吧，地址 https://codesandbox.io/embed/friendly-bassi-xryqw?fontsize=14&hidenavigation=1&theme=dark，问题name列和other列之间有个空白列，

**Comment by stevenliu87** [comment]
着急用 请解决下

**Comment by zkwolf** [comment]
至少留一列不固定宽度

**Comment by stevenliu87** [comment]
代码中有列呀，能具体说下吗

**Comment by stevenliu87** [comment]
为什么不回复 这是你们的bug

**Comment by zkwolf** [comment]
https://codesandbox.io/s/friendly-bassi-xryqw?from-embed=&file=/src/App.vue 比如这样

**Comment by stevenliu87** [comment]
name列和other列之间有个空白列呀，给解决下呀

**Comment by zkwolf** [comment]
我好像没保存上, 把Age的width删掉,总之留一列不指定width,https://codesandbox.io/s/happy-grothendieck-0trzo

**Comment by stevenliu87** [comment]
谢谢你的答复，可把Age的width删掉,Age的列就太宽了，有好的解决办法吗，能让宽度Age自适应吗

**Comment by zkwolf** [comment]
脑补一下,你指定了scroll-x,其他列固定宽度,如果scorll-x过长,Age列自适应就会很长了,限制一下scroll-x的大小

stevenliu87 ***@***.***> 于2021年7月27日周二 下午4:26写道：

**Comment by stevenliu87** [comment]
在实际的项目中，Age列是动态生成的，会生成多个Age列，数量不定，如果scroll-x的大小写成固定的，Age列的宽度就会不固定，有时宽有时窄，怎么能让宽度固定或者自动适配

**Comment by stevenliu87** [comment]
请尽快回复，项目中急着用
