### ISSUE TITLE
a-select dorp-down list scroll error.

### ISSUE THREAD

**Issue by jackyyyy-dev** [vueComponent/ant-design-vue#4396]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.1

### Environment
vue@3.1.6

### Reproduction link
[https:www.none.cnm](https:www.none.cnm)

### Steps to reproduce
```
<a-select
style="width: 300px;"
:mode="mode"
:value="value"
placeholder="请选择"
@change="selectChange"
>
<a-select-option
v-for="prop in courseList"
:value="prop.id"
:key="prop.id"
>
{{ prop.name }}
</a-select-option>
</a-select>
```

### gif image
![select-scroll-error.gif](https://i.loli.net/2021/07/20/EDUZWT6B8eVyubp.gif)

### What is expected?
Show scrollbar

### What is actually happening?
The first time you open it, you can scroll normally, after you select it once, you can't scroll & no scroll bar when you open the drop-down menu again, you can see that there is data on the DOM.

But when I quickly select the option and then click select again to open the drop-down list, the scroll bar appears

---
Are these two related?

https://github.com/ant-design/ant-design/issues/31321

**Comment by LonHon** [comment]
@tangjinzhou 这个在项目里是部分出现的，有A,B,C 3处使用到a-select，其中A会出现而且一直会有
所以不能提供100%复现 :-(

**Comment by zkwolf** [comment]
最好是给个最小复现，确认一下组件库和vue的版本

**Comment by LonHon** [comment]
> 最好是给个最小复现，确认一下组件库和vue的版本

Vue@3.1.6, ant-design-vue@2.2.1，其它的只有上面GIF了

**Comment by heying517** [comment]
怎么解决的？我也遇到了

**Comment by heying517** [comment]
please try again, I  had this problem too

https://codesandbox.io/s/hardcore-star-gk1jt?file=/src/App.vue

**Comment by heying517** [comment]
> Since the issue was labeled with `Need Reproduce`, but no response in 7 days. This issue will be closed. If you have any questions, you can comment and reply.
> 
> 由于该 issue 被标记为需要复现信息，却 7 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

please try again, I had this problem too

https://codesandbox.io/s/hardcore-star-gk1jt?file=/src/App.vue
