### ISSUE TITLE
Table: In customCell, the cell property rowSpan will still be rendered when the value is set to 0

### ISSUE THREAD

**Issue by Daki-l** [vueComponent/ant-design-vue#4399]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-11jes?file=/src/components/HelloWorld.vue)

### Steps to reproduce
使用table组件 并在columns里使用customCell 并设置单元格属性rowSpan 为0

### What is expected?
表格支持行/列合并，使用 render 里的单元格属性 colSpan 或者 rowSpan 设值为 0 时，设置的表格不会渲染。
我在使用customCell中更改单元格rowspan为0时 表格不渲染

### What is actually happening?
在使用customCell中更改单元格rowspan为0时 表格依旧渲染

**Comment by zkwolf** [comment]
https://codesandbox.io/s/vue-antd-template-forked-k4luq

**Comment by Daki-l** [comment]
用null代替0是可用的 但是控制台会有报错信息

**Comment by Daki-l** [comment]
把rowSpan 从0改成null是可用的 我现在用的就是这个方式 但是控制台会有报错信息
[Vue warn]: Error in render: "TypeError: Cannot convert undefined or null to object"

**Comment by zkwolf** [comment]
等等，干嘛不像官网demo一样用customRender啊

**Comment by Daki-l** [comment]
我需要使用customRender渲染一个比较复杂的自定义组件，同时需要进行列合并操作，在customCell的定义中是设置单元格属性,而rowSpan是控制单元格合并和是否渲染的属性，就想使用customCell来实现列合并，customRender实现自定义组件

**Comment by zkwolf** [comment]
customCell看了一下源码应该就是原封不动的传递了attr和prop，应该是达不到合并的作用，customRender里有对应的判断，等于0就不渲染 https://github.com/vueComponent/ant-design-vue/blob/1.x/components/vc-table/src/TableCell.jsx#L105

**Comment by Daki-l** [comment]
好吧 那这个就是不是bug了 那customCell这个api后面能支持rowSpan为0不渲染嘛

**Comment by zkwolf** [comment]
我觉得不会支持，直接用customRender就好了
