### ISSUE TITLE
使用浏览器引入方式antd.min.js，在后端渲染模式的html调用分页组件时，中横线写法无法触发showSizeChange事件

### ISSUE THREAD

**Issue by frank5380** [vueComponent/ant-design-vue#440]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.2

### Environment
mac, chrome, vue2.5.22

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/pagination-cn/](https://vuecomponent.github.io/ant-design-vue/components/pagination-cn/)

### Steps to reproduce
使用浏览器引入方式antd.min.js，在后端渲染模式的html调用组件时，中横线写法无法触发自定义事件

### What is expected?
中横线写法可以触发showSizeChange事件

### What is actually happening?
中横线写法无法触发showSizeChange事件

**Comment by tangjinzhou** [comment]
Duplicate #268
