### ISSUE TITLE
2.2.2 Custom filter menu Click the search icon and the page scrolls to the top, and the code for switching TS is exactly the same as JS

### ISSUE THREAD

**Issue by Y-Joe** [vueComponent/ant-design-vue#4404]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vue3

### Reproduction link
[https://2x.antdv.com/components/table-cn/#components-table-demo-custom-filter-panel](https://2x.antdv.com/components/table-cn/#components-table-demo-custom-filter-panel)

### Steps to reproduce
https://2x.antdv.com/components/table-cn/#components-table-demo-custom-filter-panel

### What is expected?
点点看就知道了

### What is actually happening?
2.2.2 自定义筛选菜单点击搜索图标页面滚动至顶，且切换TS的代码与JS一模一样

**Comment by tangjinzhou** [comment]
change
```js
setTimeout(() => {
              searchInput.value.focus();
            }, 0);
```
to
```js
setTimeout(() => {
              searchInput.value.focus();
            }, 100);
```
