### ISSUE TITLE
Can not expand a-collapse-panel created using v-for

### ISSUE THREAD

**Issue by Yakoot** [vueComponent/ant-design-vue#4405]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
manjaro, Vivaldi 4.0.2312.33, vue 3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-bash-7tr4i)

### Steps to reproduce
click to a-collapse-panel

### What is expected?
panel expands

### What is actually happening?
nothing

**Comment by John60676** [comment]
`key` 改为字符串类型

**Comment by Yakoot** [comment]
> You can temporarily change the `key` to a string type

thanks, it works
