### ISSUE TITLE
Need  types export about form related component like  'a-input' .etc

### ISSUE THREAD

**Issue by calali** [vueComponent/ant-design-vue#4406]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I started a new Vue3 project and used ant-design-vue 2.2.When I wrote a new Commform component and use form related component like 'a-input' or 'a-select',I need to get types from 'ant-design-vue' but faild.

I hope ant-design-vue 2.x can support 'types' files content exported like 1.x.

### What does the proposed API look like?
no

**Comment by tangjinzhou** [comment]
we have refactor compoennts by ts.  you should use this type.
