### ISSUE TITLE
a-directory-tree

### ISSUE THREAD

**Issue by c179205350** [vueComponent/ant-design-vue#4408]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.1

### Environment
Vue2.0

### Reproduction link
[https://2x.antdv.com/components/tree-cn](https://2x.antdv.com/components/tree-cn)

### Steps to reproduce
a-directory-tree 不支持slot-scope 自定义节点吗？

### What is expected?
a-directory-tree 不支持slot-scope 自定义节点吗？

### What is actually happening?
a-directory-tree 不支持slot-scope 自定义节点吗？

---
有什么有什么方案可以解决的

**Comment by tangjinzhou** [comment]
https://2x.antdv.com/components/tree-cn#components-tree-demo-directory
