### ISSUE TITLE
Select bug in chrome 66 —— ant-select-dropdown not show（opacity：0）

### ISSUE THREAD

**Issue by ltgan1121** [vueComponent/ant-design-vue#4409]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.0-beta.6

### Environment
chrome66

### Reproduction link
[https://2x.antdv.com/components/select-cn](https://2x.antdv.com/components/select-cn)

### Steps to reproduce
2.2.0版本的Select在chrome66 点击展开下拉会闪烁，发现展开的ant-select-dropdown多了这两个class slide-up-appear slide-up-appear-prepare，导致展开闪一下就看不到下拉框了

### What is expected?
show the ant-select-dropdown

### What is actually happening?
2.2.0版本的Select在chrome66 点击展开下拉会闪烁，发现展开的ant-select-dropdown多了这两个class slide-up-appear slide-up-appear-prepare，导致展开闪一下就看不到下拉框了

**Comment by tangjinzhou** [comment]
try 2.2.2

**Comment by ltgan1121** [comment]
> try 2.2.2

I try，the same question... ant-select-dropdown have 'slide-up-appear slide-up-appear-prepare'  and not show when click select

**Comment by ltgan1121** [comment]
> Hello @ltgan1121. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @ltgan1121, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

https://ltgan1121.github.io/mylab/hello-v3/dist/
在chrome66版本下select点击下拉框闪一下就消失

**Comment by ltgan1121** [comment]
我在项目里，先去掉了展开的动画，暂时能用，
.ant-select-dropdown.slide-up-appear{
  animation:none !important;
  opacity:1 !important;
}

望组件库尽早修复此bug，谢谢

**Comment by ltgan1121** [comment]
> Since the issue was labeled with `Need Reproduce`, but no response in 7 days. This issue will be closed. If you have any questions, you can comment and reply.
> 
> 由于该 issue 被标记为需要复现信息，却 7 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

我已经给了复现的demo url：https://ltgan1121.github.io/mylab/hello-v3/dist/
code：https://github.com/ltgan1121/mylab/tree/main/hello-v3/dist

这种类似bug在多个组件下都存在，比如下拉菜单drop down menu、model mask，都会存在闪一下就消失，show and than quickly hide（opacity：0）in chrome 66.
