### ISSUE TITLE
vite-plugin-components custom theme Impacting the development experience ?

### ISSUE THREAD

**Issue by yinfoyuan** [vueComponent/ant-design-vue#4411]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vite vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-haze-23h3u)

### Steps to reproduce
https://codesandbox.io/s/young-haze-23h3u

<img width="960" alt="ant" src="https://user-images.githubusercontent.com/35027364/126622408-287be330-be84-44ca-a989-65830fc133b8.png">

Console printing

new dependencies found: ant-design-vue/es, ant-design-vue/es/layout/style, updating...

✨ dependencies updated, reloading page...

### What is expected?
No impact on the development experience

### What is actually happening?
impact on the development experience

**Comment by tangjinzhou** [comment]
please report to vite-plugin-components
