### ISSUE TITLE
upgrade 2.2.2 error

### ISSUE THREAD

**Issue by z3214965** [vueComponent/ant-design-vue#4412]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vue 3.1.4

### Steps to reproduce
upgrade 2.1.6->2.2.2 error

### What is expected?
normal use

### What is actually happening?
not use

        

![捕获](https://user-images.githubusercontent.com/18589356/126733868-a6a51eb4-2f42-4487-a8f8-df5b2f8b3890.PNG)
![捕获1](https://user-images.githubusercontent.com/18589356/126733869-c32ea506-b92f-492c-b698-409d7dc9b40f.PNG)

**Comment by tangjinzhou** [comment]
delete node-moduels and some lock files.
reinstall pkg
