### ISSUE TITLE
The expandIconColumnIndex in the Table component is invalid

### ISSUE THREAD

**Issue by Weilence** [vueComponent/ant-design-vue#4416]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
ant-design-vue@2.2.2 vue@3.1.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sparkling-star-l1fxu)

### Steps to reproduce
点击复现链接，查看expand列的位置

### What is expected?
expandIconColumnIndex控制展开的图标显示在哪一列，如果没有 rowSelection，默认显示在第一列，否则显示在选择框后面

### What is actually happening?
expandIconColumnIndex无效，并且填写了rowSelection，也不会在选择框后面。

**Comment by tangjinzhou** [comment]
set `expandIconAsCell = false`

**Comment by gaweki** [comment]
@tangjinzhou please add expandIconAsCell into the API documentation. So we know it is  API property too
