### ISSUE TITLE
 TableComponents header cell with columns change render error

### ISSUE THREAD

**Issue by macheteHot** [vueComponent/ant-design-vue#4418]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vue 3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-clarke-uof4e?file=/src/App.vue)

### Steps to reproduce
click  set Fixed  three time and click del Fixed  three time

### What is expected?
header render order correct

### What is actually happening?
header render is repeat

**Comment by tangjinzhou** [comment]
set uni key by 
```js
createVNode('th', { key: props.key }, ctx.children);
```
