### ISSUE TITLE
Use the button with type="text" to warn infinitely in the console

### ISSUE THREAD

**Issue by sinanIndex** [vueComponent/ant-design-vue#4420]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vite2.0.5 or vite 2.4.3，vue-3.1.4

### Reproduction link
[https://2x.antdv.com/components/button-cn](https://2x.antdv.com/components/button-cn)

### Steps to reproduce
pure code: get warning once

```
<template>
  <div>
    <a-button type="text" size="small">修改</a-button>
    <a-button type="text" size="small">删除</a-button>
  </div>
</template>
```

full code: get Infinite warning
```
<template>
  <div>

    <vxe-table
      align="center"
      :data="listData">

      <vxe-table-column title="操作">
        <template #default>
          <a-button type="text" size="small">修改</a-button>
          <a-button type="text" size="small">删除</a-button>
        </template>
      </vxe-table-column>
    </vxe-table>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from 'vue'

export default defineComponent({
  name: 'index',
  setup () {

    const listData = ref([
      { id: 10001, name: 'Test1', role: 'Develop', sex: 'Man', age: 28, address: 'vxe-table 从入门到放弃' },
      { id: 10002, name: 'Test2', role: 'Test', sex: 'Women', age: 22, address: 'Guangzhou' },
      { id: 10003, name: 'Test3', role: 'PM', sex: 'Man', age: 32, address: 'Shanghai' },
      { id: 10004, name: 'Test4', role: 'Designer', sex: 'Women', age: 24, address: 'Shanghai' }
    ])

    return {
      listData
    }
  }
})
</script>
```

### What is expected?
There should be no warning in the console.

### What is actually happening?
Use the button with type="text" to warn once in the console .I also used it with vxe-table，and then get infinite warning in the console.But it has examples  using type="text" in the document with version 2.2.2. 
---
控制台内容：
[Vue warn]: Invalid prop: custom validator check failed for prop "type".
at <AButton type="text" size="small" >
at <VxeTableBody ref=Ref< Proxy {…} > tableData= (4) [Proxy, Proxy, Proxy, Proxy] tableColumn= (7) [Proxy, Proxy, Proxy, Proxy, Proxy, Proxy, Proxy] >
at <VxeTable align="center" data= (4) [{…}, {…}, {…}, {…}] >
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > key="/system/dict" >
at <KeepAlive key=0 include= (2) ["Analysis", "Dict"] >
at <BaseTransition mode="out-in" appear=true persisted=false  ... >
at <Transition name="fade-slide" mode="out-in" appear="" >
at <RouterView>
at <PageLayout>
at <LayoutContent>
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="vben-default-layout-main" >
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="ant-layout ant-layout-has-sider" >
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="vben-default-layout" >
at <DefaultLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {_pStores: {…}, …} > >
at <RouterView>
at <AppProvider>
at <ALocaleProvider locale= {locale: "zh-cn", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" >
at <LocaleReceiver children=fn<children> >
at <AConfigProvider locale= {locale: "zh-cn", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} >
at <App>

utils.ts:57 [VueTypes warn]: oneOf - value should be one of "default", "primary", "ghost", "dashed", "danger", "link"

**Comment by zkwolf** [comment]
As the warnig said, the type prop should not accept `text`.

**Comment by tangjinzhou** [comment]
没有复现  如果是vxe 引起的，你可以去他们那边报bug

**Comment by sinanIndex** [comment]
谢谢你的评论，我想可能是vben-admin二次封装a-button引起的，vben-admin依然支持type=“danger”的方式的按钮，和官方文档并不一致。我理解的他们的按钮封装是将type直接传递给ant-design-vue的button，所以以为是ant-design-vue的问题。抱歉浪费你们的时间了，vite+vue3的项目，我实在是无法分清产生的错误是vben-admin自己封装插件或者打包配置产生，或是vite，亦或是ant-design-vue产生的，这个架构现在产生的各种问题很多，都快是一步一个坑的地步了，我还是考虑继续用vue/cli做项目。再次表示感谢
