### ISSUE TITLE
Style disorder

### ISSUE THREAD

**Issue by yao-xiyan** [vueComponent/ant-design-vue#4426]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
windows、谷歌浏览器

### Reproduction link
[https://www.antdv.com/components/space-cn/](https://www.antdv.com/components/space-cn/)

### Steps to reproduce
间距代码演示的第一个演示示例

### What is expected?
限制在边框以内

### What is actually happening?
超出了边框

**Comment by yao-xiyan** [comment]
有个强迫症似的看着别扭

**Comment by tangjinzhou** [comment]
截个图看看
