### ISSUE TITLE
Input-password cannot customize prefixCls through config-provider

### ISSUE THREAD

**Issue by yiwuyu** [vueComponent/ant-design-vue#4427]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
os: macos big sur 11.1, brower: chrome 91.0.4472.106, vue version: 3.1.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-hypatia-0jgpy?file=/src/App.vue)

### Steps to reproduce
设置 config-provider 的 prefixCls 为 `antdv`，查看input-password的类名前缀是否更改

### What is expected?
input-password 的类名前缀变为 antdv- ，样式将失效

### What is actually happening?
input-password 的样式仍然为ant-design默认样式，而input 已经样式失效

---
由于在 sandcodebox 中设置 vue.config.js 失效，antd.less 导入失败，只能通过控制台确认类名未改变

**Comment by xujiali111** [comment]
这个bug修复后什么时候发包啊，等着用

**Comment by tangjinzhou** [comment]
周末
