### ISSUE TITLE
如何解决TreeSelect异步加载数据，当前选中数据并不在初始数据上时，能正常显示数据

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#443]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如何解决TreeSelect异步加载数据，当前选中数据并不在初始数据上时，能正常显示数据

### What does the proposed API look like?
如何解决TreeSelect异步加载数据，当前选中数据并不在初始数据上时，能正常显示数据

**Comment by wangxueliang** [comment]
我的理解：
1、这是你业务问题
2、如果想正常显示初始数据，在自己业务代码中处理
