### ISSUE TITLE
Cascader componet, setting props expandTrigger:hover and loaddata

### ISSUE THREAD

**Issue by lzghost** [vueComponent/ant-design-vue#4438]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
see the file package.json

### Reproduction link
[https://github.com/lzghost/vue-cxskde/tree/master](https://github.com/lzghost/vue-cxskde/tree/master)

### Steps to reproduce
1、yarn install
2、 yarn serve
3、 use it

### What is expected?
expandTrigger:hover, method loaddata，希望鼠标经过isLeaf=false的节点时不是直接修改value，而且只调用loaddata

### What is actually happening?
设置expandTrigger:hover, method loaddata，当鼠标在第一层悬浮经过时，会自动设置经过的Menu中对应的value

**Comment by lzghost** [comment]
2.2.2 和 1.7.6 代码查看过并没有区别

**Comment by tangjinzhou** [comment]
因为你配置了  change-on-select
