### ISSUE TITLE
Integrated pinia

### ISSUE THREAD

**Issue by toolse** [vueComponent/ant-design-vue#4439]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
极大简化数据状态管理的操作过程，降低数据状态管理的成本，同时实现组件之间的低耦合数据状态

### What does the proposed API look like?
简封装一下集成到ant-design-vue框架中即可

**Comment by zkwolf** [comment]
组件库没有必要和状态管理耦合啊
