### ISSUE TITLE
the message component can't move-up in mobile when I click it 

### ISSUE THREAD

**Issue by HDZ6666** [vueComponent/ant-design-vue#4440]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue 2.X  chrome 92 antd 1.7x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-ru9vd?file=/src/App.vue)

### Steps to reproduce
this.$message.warning('xxxx')

### What is expected?
the message component can move-up after duration time whether you click or not

### What is actually happening?
it will show all the time if i not clik in other places

---
i find some word in Notice.js on vc-notification package, { 'mouseenter': clearCloseTimer, 'mouseleave': startCloseTimer,} This event is not available on mobile， please fix it use touch event

**Comment by tangjinzhou** [comment]
This is expected behavior.
