### ISSUE TITLE
vite2.2, the button click under jsx Dropdown cannot be selected, but the button under the template can be

### ISSUE THREAD

**Issue by bailihuiyue** [vueComponent/ant-design-vue#4441]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vite2.2 vue3.0.4

### Reproduction link
可复现的网址
https://codesandbox.io/embed/exciting-sunset-fdp75?fontsize=14&hidenavigation=1&theme=dark
### Steps to reproduce
如题

### What is expected?
无法选中

### What is actually happening?
可以选中

**Comment by bailihuiyue** [comment]
import "ant-design-vue/lib/menu/style/index.css";
import "ant-design-vue/lib/dropdown/style/index.css";
import { Menu, Dropdown } from 'ant-design-vue'
import { defineComponent, ref } from 'vue';
export default defineComponent({
  setup () {
    const currentLang = ref(1)
    const changeLang = ({ key }) => currentLang.value = key
    const langMenu = (
      <Menu selectedKeys={[currentLang.value]} onClick={changeLang}>
        <Menu.Item key={1}>
          1
        </Menu.Item>
        <Menu.Item key={2}>
          2
        </Menu.Item>
      </Menu>
    )
    return () => <span>{currentLang.value}<Dropdown overlay={langMenu}><span>点我</span></Dropdown></span>
  }
})

**Comment by tangjinzhou** [comment]
https://codesandbox.io/embed/exciting-sunset-fdp75?fontsize=14&hidenavigation=1&theme=dark

setup 仅仅执行一次，必然不会更新，可以放在 render中，或者传入方法
