### ISSUE TITLE
tree table expandIcon slot usage is invalid

### ISSUE THREAD

**Issue by zhaogaolei** [vueComponent/ant-design-vue#4444]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.2

### Environment
vue2.6  Google Chrome  92.0.4515.107 正式版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-58v3u?file=/src/App.vue)

### Steps to reproduce
<a-icon slot="expandIcon" slot-scope="props" :type="[props.expanded ? 'down' :'up']"/>

### What is expected?
解决问题

### What is actually happening?
table的expandIcon API使用插槽写法时并没有生效

**Comment by zkwolf** [comment]
1.x现在只维护1.7版本了，可以考虑jsx

**Comment by tangjinzhou** [comment]
v1.7.7
