### ISSUE TITLE
Empty setting configProvider prefixcls does not take effect

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue#4446]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.6

### Environment
windows10,google chrome 79.0.3945.130,vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-kf003?file=/src/App.vue)

### Steps to reproduce
1. 用configProvider设置prefixCls
2. 使用empty组件

### What is expected?
empty组件的class，会被改变成设置的prefixCls

### What is actually happening?
empty组件的class，没有被改变成设置的prefixCls

---
https://github.com/vueComponent/ant-design-vue/blob/1.7.3/components/empty/index.jsx#L32
不应该使用ConfigConsumerProps.getPrefixCls方法
应该像下面代码，inject configProvider
https://github.com/vueComponent/ant-design-vue/blob/1.7.3/components/input/Input.jsx#L62

**Comment by candy-Tong** [comment]
message configProvider prefixCls 也不生效
https://github.com/vueComponent/ant-design-vue/blob/next/components/message/index.tsx#L13

**Comment by tangjinzhou** [comment]
message.config(options)

> message configProvider prefixCls 也不生效
> https://github.com/vueComponent/ant-design-vue/blob/next/components/message/index.tsx#L13
