### ISSUE TITLE
When the Table component sets the rowKey function, the expandedRowRender set will expand after clicking an icon, and all the additional expanded rows will be expanded

### ISSUE THREAD

**Issue by xiziliang** [vueComponent/ant-design-vue#4450]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
windows 10  Chrome  92.0.4515.107  Vue 3.1.0

### Reproduction link
[https://2x.antdv.com/components/table-cn#API](https://2x.antdv.com/components/table-cn#API)

### Steps to reproduce
for example：
```javascript
<a-table
:row-key="() => 'id'"
>
<template #expandedRowRender="{ record }">
<p style="margin: 0">
{{ record.job }}
</p>
</template>
</a-table>
```

### What is expected?
期望在设置rowKey为函数时，点击对应的展开按钮，展开对应的expandedRowRender

### What is actually happening?
点击对应的展开按钮，展开了所有的expandedRowRender

**Comment by tangjinzhou** [comment]
因为你的 rowkey 相同  都是 id

**Comment by SWUSTLJW** [comment]
表格能否在一行添加多个展开图标
