### ISSUE TITLE
Can the Tree component increase the accordion mode?

### ISSUE THREAD

**Issue by cuteCloud** [vueComponent/ant-design-vue#4451]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
tree结构展开太多，每一个还要自己手动去关闭

### What does the proposed API look like?
类似折叠面板一样，提供一个accordion属性

**Comment by tangjinzhou** [comment]
你可以自行控制  expandedKeys 数组长度永远为 1 即可

**Comment by cuteCloud** [comment]
> 你可以自行控制 expandedKeys 数组长度永远为 1 即可
折叠的意思是折叠同级，也就是同层只能展开一个，仅仅保持为1的话折叠效果就会错乱。希望从框架tree组件提供这个功能，不然自己处理每次点击都要去遍历树，处理这些id，tree的折叠效果应该还是挺常用和基础的特性 希望考虑下吧  谢谢
