### ISSUE TITLE
The nested table in the form sets one of the items as an input box and binds it with v-decorator , The input value is not displayed after the input box loses focus

### ISSUE THREAD

**Issue by jiq1997** [vueComponent/ant-design-vue#4455]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
windows 10 , Chrome81.0.4044.92 , Vue 2.6.11

### Reproduction link
[https://github.com/oaifshdfaseo/ant-vue-problem](https://github.com/oaifshdfaseo/ant-vue-problem)

[https://codesandbox.io/s/ant-vue-form-table-cvv6v?file=/src/App.vue:987-1025](https://codesandbox.io/s/ant-vue-form-table-cvv6v?file=/src/App.vue:987-1025)(When using the 1.x shape model component to use a-table, it will report an error)

### Steps to reproduce
1.This phenomenon occurs in 1.7.5 and 1.7.6;
2.Enter content in the input box of the form;
3.After the content changes with the input, the mouse moves out of the input box;
4.Mouse click input content changes to the original content but the value in the form object has changed;
5.GitHub repository: https://github.com/oaifshdfaseo/ant-vue-problem

### What is expected?
Normal binding echo

### What is actually happening?
It feels like the binding is invalid or the binding field cannot be found

**Comment by tangjinzhou** [comment]
recommended to use the FormModel component in version 1.x

**Comment by oaifshdfaseo** [comment]
> 建议在版本1.x中使用外形模型组件

Shape model component address：https://codesandbox.io/s/ant-vue-form-table-cvv6v?file=/src/App.vue:987-1025
使用1.x的外形模型组件使用a-table时就会报错
![image](https://user-images.githubusercontent.com/38250682/127796287-075b938a-d56a-4c50-88b5-dfb821069055.png)

**Comment by jiq1997** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> 1.7.3
> 
> ### Environment
> windows 10 , Chrome81.0.4044.92 , Vue 2.6.11
> 
> ### Reproduction link
> https://github.com/oaifshdfaseo/ant-vue-problem
> 
> ### Steps to reproduce
> 1.This phenomenon occurs in 1.7.5 and 1.7.6;
> 2.Enter content in the input box of the form;
> 3.After the content changes with the input, the mouse moves out of the input box;
> 4.Mouse click input content changes to the original content but the value in the form object has changed;
> 5.GitHub repository: https://github.com/oaifshdfaseo/ant-vue-problem
> 
> ### What is expected?
> Normal binding echo
> 
> ### What is actually happening?
> It feels like the binding is invalid or the binding field cannot be found

·

**Comment by tangjinzhou** [comment]
update vue to 2.6.14+

**Comment by jiq1997** [comment]
1.x shape model component can already run normally，But after the input is moved out of the input , the input data will not be displayed

Shape model component address：https://codesandbox.io/s/ant-vue-form-table-cvv6v?file=/src/App.vue:987-1025

**Comment by Tomaszal** [comment]
Any update on this issue? I am using Vue 2.6.14 and using the FormModel component is not possible in my case as I need to have access to Form component methods such as isFieldsTouched, which is not available on FormModel.
