### ISSUE TITLE
TreeSelect cannot close search when multiple

### ISSUE THREAD

**Issue by cnguu** [vueComponent/ant-design-vue#4456]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
vue2.5.17, windows10, chrome92.0.4515.107

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-r5e7i?file=/src/TreeSelectBug1.vue)

### Steps to reproduce
1. open the link and see the `TreeSelectBug1`
2. selected TreeSelect and it can't hide search input

### What is expected?
Expect to be able to close the search when it is multiple

### What is actually happening?
Cannot close search

**Comment by zkwolf** [comment]
设计就是这样的，多选得手动close

**Comment by cnguu** [comment]
> 设计就是这样的，多选得手动close

手动close应该如何做呢？我没有找到有用的props

**Comment by zkwolf** [comment]
那个open应该就是控制下拉开关的
