### ISSUE TITLE
There is an error using the directory tree component for recursive rendering, Warning: Tree only accept TreeNode as children.

### ISSUE THREAD

**Issue by humbinal** [vueComponent/ant-design-vue#4461]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
winodws11, chrome 92, vue 3.1.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-architecture-rzrd7)

### Steps to reproduce
use a-tree-node by recursive

### What is expected?
can be rendered.

### What is actually happening?
Warning: Tree only accept TreeNode as children. and not works.

**Comment by tangjinzhou** [comment]
sub-directory-tree 可以先用函数式组件形式
或者直接用 treeData

**Comment by tangjinzhou** [comment]
用 treeData 吧   因为无法hoc组件，未来 tree-node 方式会被废弃
