### ISSUE TITLE
Contextmenu in the tree component doesn't work.(version 1.x)

### ISSUE THREAD

**Issue by yzqdev** [vueComponent/ant-design-vue#4462]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
windows v19043.1110 ; vue v2.6.14 ; chrome  Edge/92.0.902.62

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-ltfb5?file=/src/App.vue)

### Steps to reproduce
[https://1x.antdv.com/components/tree-cn/#components-tree-demo-context-menu ](https://1x.antdv.com/components/tree-cn/#components-tree-demo-context-menu )

The contextmenu  does not work.

### What is expected?
On right clicking the tree component ,contextmenu appears;

### What is actually happening?
contextmenu doesn't appear;

**Comment by zkwolf** [comment]
组件库还没发新版

**Comment by 1002237913** [comment]
```
// v1.7.6 数据中加这个 可以解决
scopedSlots: {
    title: 'title',
  },
```
![xiug](https://user-images.githubusercontent.com/4089290/128156069-9e9ad3d8-dc7b-4183-9e90-2c40526b09b0.png)

**Comment by tangjinzhou** [comment]
1.7.7
