### ISSUE TITLE
Popconfirm cannot be closed by losing focus while using the visible property

### ISSUE THREAD

**Issue by tuikoushui** [vueComponent/ant-design-vue#4464]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
win10，chrome9，vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-r4pul?file=/src/App.vue)

### Steps to reproduce
Create Popconfirm and use the visible property, then click anywhere but Popconfirm

### What is expected?
Popconfirm was closed

### What is actually happening?
Popconfirm is not closed

---
Is there a maskClosable property similar to modal to control it？

**Comment by zkwolf** [comment]
you can use visibleChange like this https://codesandbox.io/s/vue-antd-template-forked-dvokw?file=/src/App.vue
