### ISSUE TITLE
Setting selectedRowKeys cannot be selected

### ISSUE THREAD

**Issue by douhua-d** [vueComponent/ant-design-vue#4465]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.0.0-beta.15

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-ilz2n)

### Steps to reproduce
const rowSelection = {
onChange: (selectedRowKeys, selectedRows) => {
selectedRowKeysArray.value = selectedRowKeys;
console.log(`selectedRowKeys: ${selectedRowKeys}`, "selectedRows: ", selectedRows);
if (selectedRowKeys.length > 0) {
selectedIdArray.value = selectedRowKeys.map(key => key.split("-")[0]);
selectedRowsArray.value = selectedRows;
hasSelected.value = true;
} else {
hasSelected.value = false;
}
},
selectedRowKeys: selectedRowKeysArray.value,
getCheckboxProps: record => ({
disabled: record.thefair_status == "audit_deleted" || record.thefair_status == "deleted"// Column configuration not to be checked
})
};

### What is expected?
能够手动改变和生效

### What is actually happening?
这样设置后无法选中

**Comment by ajuner** [comment]
你应该在onChange事件中修改rowSelection中selectedRowKeys，而不是data里面的selectedRowKeys，可以尝试用这种方式
```
onChange: function(selectedRowKeys) {
  this.selectedRowKeys = selectedRowKeys;
},
```
