### ISSUE TITLE
There are still problems with web-types.json, including some slot/item is still wrong

### ISSUE THREAD

**Issue by rxliuli** [vueComponent/ant-design-vue#4467]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Windows 10, Chrome Last，vue@3.1.5

### Reproduction link
[https://github.com/rxliuli/example/tree/df6ecffe7b88ee519d1eaf5f99bf93d7d5e169ae/antdv_web_types_error_demo](https://github.com/rxliuli/example/tree/df6ecffe7b88ee519d1eaf5f99bf93d7d5e169ae/antdv_web_types_error_demo)

### Steps to reproduce
1. 在 WebStorm 创建 vite 项目安装 ant-design-vue 项目
2. 在代码中使用 antdv 的组件

包含错误如下

- `ATabPane` 未定义，已有定义是 `a-tabs-tab-pane`
- `AList` 缺少 slot `renderItem`，并且参数缺少类型提示（好吧这个吾辈就不奢望了，ts 毕竟救不了 vue 的模板）
- `AListItemMeta` 未定义，已有定义是 `a-list-item.-meta`

### What is expected?
web-types.json 正确以使 WebStorm 能够正确进行代码提示

### What is actually happening?
web-types.json 有很多地方是不正确的

![image](https://user-images.githubusercontent.com/24560368/128117590-96f72ad3-5979-403e-9cff-ee7a98d84c91.png)

> 我不确定是 jetbrains 的生成器有问题还是类型定义有问题，所以先在这边提一下

**Comment by maicWorkGithub** [comment]
一些属性也不正确：
![image](https://user-images.githubusercontent.com/15863224/129647413-97502f2c-2371-40e4-bb48-9618ecf15149.png)

**Comment by zkwolf** [comment]
自动关了。。。我这今年要是还有能挤出来的时间会看看这坑能不能填上

**Comment by wensonsmith** [comment]
@zkwolf  today is the last day 😅

**Comment by zkwolf** [comment]
看起来得推到年后了，我今天得开一天会233333
