### ISSUE TITLE
code error in code examples of your website

### ISSUE THREAD

**Issue by we-go-bo** [vueComponent/ant-design-vue#4471]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
doesn't matter

### Reproduction link
[https://2x.antdv.com/components/form#components-form-demo-custom-validation](https://2x.antdv.com/components/form#components-form-demo-custom-validation)

### Steps to reproduce
1. type anything in "Confirm" input field
2. type anything in "Password" input field
3. see error of input field "Password" sayin' "n.value.validateField is not a function"

### What is expected?
calling "Confirm" input field validation

### What is actually happening?
undefined function error in the "Password" input field error message

---
```
let validatePass = async (rule: RuleObject, value: string) => {
  if (value === '') {
    return Promise.reject('Please input the password');
  } else {
    if (formState.checkPass !== '') {
    formRef.value.validateField('checkPass');// <= validateField is missing an "s" assuming one wanna call validateFields('checkPass')
  }
  return Promise.resolve();
  }
};
```

**Comment by John60676** [comment]
it has been fixed, waiting for release
