### ISSUE TITLE
why v2-doc gitmodule is 404?

### ISSUE THREAD

**Issue by cmdfas** [vueComponent/ant-design-vue#4475]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
github

### Reproduction link
[https://github.com/vueComponent/v2-doc](https://github.com/vueComponent/v2-doc)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue

branch: next

click v2-doc 404

<img width="1294" alt="g1" src="https://user-images.githubusercontent.com/19399732/128302698-f8aeeb05-a2a8-4827-8f7f-b4504ab36df5.png">

<img width="884" alt="g2" src="https://user-images.githubusercontent.com/19399732/128302734-7cb7249b-cc69-4056-8548-0cb9a17074fc.png">

### What is expected?
Display file

### What is actually happening?
404

**Comment by nabaonan** [comment]
because 你没有权限

**Comment by cmdfas** [comment]
> because 你没有权限

But the "examples/App.vue" relying on this file

How to run this project ?

**Comment by zkwolf** [comment]
You can replace it with your demo.
