### ISSUE TITLE
After the drop-down box is selected, select it again, it will not be able to drop down

### ISSUE THREAD

**Issue by TomatoDroid** [vueComponent/ant-design-vue#4476]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
chrome:92.0.4515.131     vue:3.2.0beat7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-flower-jzzzv?file=/src/App.vue)

### Steps to reproduce
点击下拉框，下拉款可以下拉，选择值后可以再次点击下拉框，然后无法下拉

### What is expected?
点击下拉框，下拉款可以下拉，选择值后可以再次点击下拉框可以下拉选值

### What is actually happening?
点击下拉框，下拉款可以下拉，选择值后可以再次点击下拉框，无法下拉选值

**Comment by John60676** [comment]
无法重现

https://user-images.githubusercontent.com/21698973/128441884-e1737072-7752-450f-975a-25f4fde82b89.mp4

**Comment by zkwolf** [comment]
Duplicate #4396

**Comment by TomatoDroid** [comment]
> 无法重现
> 
>  Kapture.2021-08-06.at.09.25.29.mp4

第一次选择后下拉框滚动条消失，无法选择滚动条下面的选项。
