### ISSUE TITLE
How to dynamically change the style or content of notification

### ISSUE THREAD

**Issue by songweionline** [vueComponent/ant-design-vue#4478]
我不确定这个是bug还是我自己没写对。
export default {
  name: "App",
  data() {
    return {
      moment,
      version,
      console: console,
      rdata: 1,
      content: "tishi",
    };
},
methods: {
    test() {
      console.log(this.rdata);
      this.rdata = this.rdata === 1 ? 2 : 1;
      this.content = this.rdata === 1 ? "tishi" : "notishi";
    },
    handleQa() {},
    showNotice() {
      console.log(this.rdata);
    
      const rdata = {
      warnId: this.rdata,
      };
      this.$notification.open({
        message: "提示",
        description: this.content,
        icon: (
          <a-icon
          type="warning"
          style={{ color: rdata.warnId === 1 ? "red" : "green" }}
          />
        ), // 这里是官网例子
        btn: (h) => {
          return h(
          "a-button",
            {
              props: {
              type: "primary",
              size: "small",
            },
          on: {
            click: () => that.handleQa(rdata),
          },
          },
          "快速处理"
          );
          },
          key: rdata.warnId,
          onClose: close,
        });
      },
    },
  };

notification 不能动态改变样式或者内容，想在notification 里做一个进度条，但无论如何进度条都无法实时更新。最后发现notification好像只在创建的时候渲染一次之后就无法更新了。只能通过操作真实dom去实现。实在太傻了。
notification能不能提供动态更新的方法，或者能够实现绑定数据动态更新？或者给一个现在可以使用的写法。

https://codesandbox.io/s/boring-violet-yv8b9?file=/src/App.vue:507-1626

希望notification提供一个能够update的方法。

**Comment by tangjinzhou** [comment]
https://antdv.com/components/notification-cn/#components-notification-demo-update-message-content
看这个示例
