### ISSUE TITLE
表格能否提供表尾行合计功能

### ISSUE THREAD

**Issue by qiugu** [vueComponent/ant-design-vue#448]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
类似element中的表尾合计功能，进行表格数据统计

### What does the proposed API look like?
summary-method

**Comment by tangjinzhou** [comment]
可以结合 table footer 实现
可以参考 antd的issue： https://github.com/ant-design/ant-design/issues/4581
