### ISSUE TITLE
Unknown custom element: <a-tree-node> - did you register the component correctly

### ISSUE THREAD

**Issue by FriezaKing** [vueComponent/ant-design-vue#4480]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
dev

### Reproduction link
[https://www.antdv.com/components/tree/#Tree](https://www.antdv.com/components/tree/#Tree)

### Steps to reproduce
https://www.antdv.com/components/tree/#Tree

<template>
  <a-directory-tree multiple default-expand-all @select="onSelect" @expand="onExpand">
    <a-tree-node key="0-0" title="parent 0">
      <a-tree-node key="0-0-0" title="leaf 0-0" is-leaf />
      <a-tree-node key="0-0-1" title="leaf 0-1" is-leaf />
    </a-tree-node>
    <a-tree-node key="0-1" title="parent 1">
      <a-tree-node key="0-1-0" title="leaf 1-0" is-leaf />
      <a-tree-node key="0-1-1" title="leaf 1-1" is-leaf />
    </a-tree-node>
  </a-directory-tree>
</template>
<script>
import { Tree } from 'ant-design-vue'
export default {
  name: 'QaConversion',
  methods: {
    onSelect(keys, event) {
      console.log('Trigger Select', keys, event)
    },
    onExpand() {
      console.log('Trigger Expand')
    },
  },
}
</script>

### What is expected?
正常使用

### What is actually happening?
浏览器报错

**Comment by tangjinzhou** [comment]
app.use(Tree)
或者
import {Tree, TreeNode } from 'ant-design-vue'
