### ISSUE TITLE
When "vite" is loaded on demand and used with "rollup-plugin-visualizer", an error "Can't resolve original location of error" is generated

### ISSUE THREAD

**Issue by darkXmo** [vueComponent/ant-design-vue#4481]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.3

### Environment
"vue": "^3.0.5", "rollup-plugin-visualizer": "^5.5.2"

### Reproduction link
[https://gitee.com/dXmo/hhf1-fontend/tree/bug%2Fvisualizer/](https://gitee.com/dXmo/hhf1-fontend/tree/bug%2Fvisualizer/)

### Steps to reproduce
yarn build

### What is expected?
```bash
✓ 970 modules transformed.
dist/assets/logo.03d6d6da.png    6.69kb
dist/index.html                  0.67kb
dist/assets/index.67298355.css   0.34kb / brotli: 0.18kb
dist/assets/index.e3c668c4.js    0.96kb / brotli: 0.47kb
dist/assets/vendor.348ce819.js   56.79kb / brotli: 16.21kb
Done in 13.21s.
```

### What is actually happening?
```bash
# 大量诸如此类的错误提示信息
transforming (862) node_modules/ant-design-vue/es/vc-lazy-load/src/LazyLoad.jsError when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
Error when using sourcemap for reporting an error: Can't resolve original location of error.
```
![image](https://user-images.githubusercontent.com/37503114/128591866-66d4276d-7351-45f1-beca-0d77405fd009.png)

---
主要关注点在 `vite.config.ts` 文件夹中，一旦引入 `antdv` 的组件，`rollup` 的可视化bundle工具(`rollup-plugin-visualizer`)与配置
```ts
ViteComponents({
customComponentResolvers: [AntDesignVueResolver()],
}),
```
就会产生 build 上的错误。
该冲突虽然不会导致 visualizer 的彻底失败，但是会在命令行中产生成吨的 ERR 提示。

**Comment by tangjinzhou** [comment]
给 vite-plugin-components 提issue 吧  ，目测丢失了sourceMap 文件
