### ISSUE TITLE
The scroll bar is always displayed when the table component is set to scroll

### ISSUE THREAD

**Issue by 6baobao9** [vueComponent/ant-design-vue#4484]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.3

### Environment
vue 3.1 chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-oskar-pcrwj?file=/src/App.vue)

### Steps to reproduce
table组件设置scroll属性 如 <a-table :scroll="{x: null, y: 600}">

### What is expected?
在数据少时自动隐藏滚动条

### What is actually happening?
滚动条始终显示 因为设置了overflow-y: scroll; 我不知道这是出于什么目的，我现在只能在项目 自定义overflow-y: auto的样式，我不知道有没有更好的办法

**Comment by mynetfan** [comment]
commit只解决了横向滚动条的问题。纵向滚动条仍然是老样子

**Comment by LBC100** [comment]
有人解决吗
![image](https://user-images.githubusercontent.com/38514123/137099774-fe03af3c-c3b6-4b96-acf4-3ad0b22c858f.png)
