### ISSUE TITLE
Select selector When the default value is cleared, the default value is displayed as undefined

### ISSUE THREAD

**Issue by lotherli** [vueComponent/ant-design-vue#4485]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.4

### Environment
window、谷歌92.0.4515.131 ， vue2.6.11

### Reproduction link
[https://zhy3f.csb.app/](https://codesandbox.io/s/vue-antd-template-forked-zhy3f?file=/src/App.vue)

### Steps to reproduce
allowClear，清空后默认值显示为undefined

### What is expected?
预期清空后显示为空

### What is actually happening?
清空后显示为undefined

**Comment by zkwolf** [comment]
这是预期行为啊

**Comment by lotherli** [comment]
> 这是预期行为啊
清空的时候不能为空吗？？现在就时清空的时候我需要自身进行处理undefined的值

**Comment by zkwolf** [comment]
#4117
