### ISSUE TITLE
useForm: Call the resetFields method directly through the button will add isTrusted key to modelRef

### ISSUE THREAD

**Issue by icepole-jon** [vueComponent/ant-design-vue#4486]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.3

### Environment
win10, chrome v92, vue3.1.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-bird-mz9jr?file=/src/App.vue)

### Steps to reproduce
按钮直接调用 useForm 返回的 resetFields 方法，会向modelRef中插入 isTrusted: true .
包装一层后调用则不会插入

### What is expected?
按钮直接调用不插入额外数据

### What is actually happening?
按钮直接调用插入了额外数据

---
查看重现链接的console

**Comment by tangjinzhou** [comment]
```html
@click="resetFields()"
```
