### ISSUE TITLE
<a-popover> cause duplicate execution of $root life hooks

### ISSUE THREAD

**Issue by Mitscherlich** [vueComponent/ant-design-vue#4487]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
OS: macOS 11.5 Browser: Chrome 92.0.4515.131 Vue: 2.6.14

### Reproduction link
[https://codepen.io/mitscherlich/pen/YzVdzyL](https://codepen.io/mitscherlich/pen/YzVdzyL)

### Steps to reproduce
1. Wrap `Dialog` component with `Vue.extend`
2. add example code with <a-popover>：

```html
<div class="dialog">
  <a-popover title="Title">
    <template slot="content">
      <p>Content</p>
      <p>Content</p>
    </template>
    <a-button type="primary">
      Hover me
    </a-button>
  </a-popover>
</div>
```

3. add log to `Dialog` components' life hooks：

```js
let count = 0;

const Dialog = Vue.extend({
  template: $('#dialog-tpl').innerHTML,
  mounted() {
    if (  count < 2) {
      console.log("I'm mounted and that's my first journal :)")
    } else {
      console.log("I'm mounted and I will run twice. x_x")
    }
    
    document.body.appendChild(this.$el)
  }
})
```

4. Hover on <a-button> and will print "I'm mounted and I will run twice. x_x"

### What is expected?
do not call `Dialog` life hooks

### What is actually happening?
do call `Dialog` life hooks

**Comment by Mitscherlich** [comment]
I believe this caused by this line

https://github.com/vueComponent/ant-design-vue/blob/72b13122098c71430806ba45b029a59a5f167f3c/components/_util/ContainerRender.jsx#L56

**Comment by tangjinzhou** [comment]
you can use `new Vue` at 1.x

In the 2.x version we have removed this.$root.constructor

**Comment by Mitscherlich** [comment]
OK.. but we won't upgrade to vue@3 recently and `Vue.extend` is essential in our case :rofl: I'll find other way to avoid this issue.

BTW thx.

**Comment by tangjinzhou** [comment]
Sorry, we do not plan to make major changes to 1.x. 
Especially changes with breaking change.
