### ISSUE TITLE
tree supports typical patterns

### ISSUE THREAD

**Issue by cole-dda** [vueComponent/ant-design-vue#4488]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在典型的tree，点击一个节点是选择状态（高亮），再次点击还是选择状态，但是现在的tree点击后会改变状态，符合多选，或者check模式。

### What does the proposed API look like?
希望支持典型模式，如：mode='classic' or mode='single'

**Comment by tangjinzhou** [comment]
使用受控模式控制 checkedKeys 长度永远为1
