### ISSUE TITLE
Input输入组件设置v-decorator后不能使用默认值

### ISSUE THREAD

**Issue by qq447665722** [vueComponent/ant-design-vue#449]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.3

### Environment
mac 10.14,chrome 71.0.3578.98,vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ov55mlq9j6)

### Steps to reproduce
输入框使用v-decorator不能设置输入框的默认值

**Comment by qq447665722** [comment]
多看文档
![image](https://user-images.githubusercontent.com/14967427/51891146-28268800-23d9-11e9-96ef-4b651d2d3afd.png)
https://vuecomponent.github.io/ant-design-vue/components/form-cn/
附带处理结果
https://codesandbox.io/s/61j33ppoon

**Comment by yellowbeee** [comment]
@qq447665722  我项目采用typescript 使用@Component装饰组件  组件内使用v-decorator指令后，input输入框不能输入东西是什么问题？？

**Comment by aiddroid** [comment]
foreach list 到多个表单的时候，list 里面的对象item怎么 通过v-decorator映射 ？

**Comment by wwwwwwwwwy** [comment]
> @qq447665722 我项目采用typescript 使用@component装饰组件 组件内使用v-decorator指令后，input输入框不能输入东西是什么问题？？

 我也遇到同样的问题了，文本框不能输入，有什么方法解决吗？

**Comment by yellowbeee** [comment]
@wwwwwwwwwy

**Comment by yellowbeee** [comment]
@wwwwwwwwwy 
方便贴下代码吗？

**Comment by aiddroid** [comment]
已经换成 elementui，一路顺畅，毫无违和感。

**Comment by wwwwwwwwwy** [comment]
> @wwwwwwwwwy
> 方便贴下代码吗？

```html
<template>
  <a-form class="createleft" :form="form">
    <a-form-item label="文本信息">
      <a-input v-decorator="[
      'username'
      ]" />
    </a-form-item>
  </a-form>
</template>

<script lang="ts">
import { Vue, Component } from "vue-property-decorator";
@Component({})
export default class demo extends Vue {
  form = this.$form.createForm(this);
}
</script>
```

**Comment by Siffre** [comment]
@wwwwwwwwwy  我也是typescript遇到这个问题，求指点

**Comment by xcy161106** [comment]
v-decorator="[`loadNum[${index}]`

这样可以拿到。
this.form.validateFields() 
拿到value后遍历那个数组。
data.push(value.loadNum[index])

**Comment by sunny920406** [comment]
我也遇到同样的问题了。
“目测问题是 @component 的问题，虽然我不清楚你怎么用的，解决方案：createForm放在created声明周期中“
上面的作者的的回复，
  created() {
    this.form = this.$form.createForm(this);
  }
改成这样就解决了

**Comment by Siffre** [comment]
@sunny920406 是的，就是这样解决的
