### ISSUE TITLE
[Vue ^3.2.1] Autocomplate error: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by aov2005** [vueComponent/ant-design-vue#4490]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.3

### Environment
Vue 3.2.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-perlman-1hels?file=/src/App.vue)

### Steps to reproduce
升级新版本vue

### What is expected?
正常使用

### What is actually happening?
下拉选择的时候，报错
Cannot read property 'value' of undefined

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/6f3fca48a1f5c0abbd41e4cdb3c99c2a9bd41309
已修复，等发版本
