### ISSUE TITLE
About search in  Select Component 

### ISSUE THREAD

**Issue by ommoren** [vueComponent/ant-design-vue#4492]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
the Option props in document tell me to use 'title',but in fact it is  'lable'.
the search can filter options,but the results is match values,maybe match label is right

### What does the proposed API look like?
maybe get the result match label ,or remove the auto search, then i will change the options value when the @search is triggered

**Comment by tangjinzhou** [comment]
?
where `title`

If you are submitting an issue, please provide a reproduction link.

如果是中文用户，就提交中文吧，看不太懂你的问题 😓

**Comment by ommoren** [comment]
select这个组件的搜索好像是按value筛选的，比如我的选项是{value:1,label:"a"},{value:2,label:"b"},我想搜a是没有结果的，但是输入框填1就能把第一个选项查到。
然后我想自己在@search的事件里改option来实现筛选也不行

**Comment by tangjinzhou** [comment]
```js
const filterOption = (input: string, option: any) => {
      console.log(option);
      return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0;
    };
```

**Comment by tangjinzhou** [comment]
或者  option-filter-prop="label"

**Comment by transtone** [comment]
> ```js
> const filterOption = (input: string, option: any) => {
>       console.log(option);
>       return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0;
>     };
> ```

@tangjinzhou  版本 `3.1.1`，获取到的 `option` 中根本就没有 `label` 字段。
用 `option-filter-prop="label"` 也没有任何改变。


![image](https://user-images.githubusercontent.com/46688/162562948-17e9945a-71d0-4287-9521-86bba2efc049.png)
