### ISSUE TITLE
Can I not use fixed and ellipsis at the same time in the columns setting in the table? At the same time, there will be style bugs

### ISSUE THREAD

**Issue by hugselina2019** [vueComponent/ant-design-vue#4497]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
win10 64

### Reproduction link
[https://www.antdv.com/components/table-cn/](https://www.antdv.com/components/table-cn/)

### Steps to reproduce
1、使用table
2、在columns中配置  ellipsis: true,  fixed: "left",

### What is expected?
可以正常同时使用

### What is actually happening?
样式会有bug 看图
![image](https://user-images.githubusercontent.com/20763416/129025320-e4657f43-31d1-49c3-9aff-3d54e1822d43.png)
![image](https://user-images.githubusercontent.com/20763416/129025476-631dc6ad-c8eb-4bf8-85d6-e0e611416552.png)
如果注释掉fixed: left 样式是没问题的， 而且也会超出隐藏
![image](https://user-images.githubusercontent.com/20763416/129025550-8e039cb7-42c8-4e7a-ae68-5ad898afbdf4.png)

![image](https://user-images.githubusercontent.com/20763416/129025523-013cce44-094a-49ea-a668-d653d50b18c5.png)

**Comment by hugselina2019** [comment]
如果这里我想同时使用 有什么办法吗

**Comment by xinller** [comment]
所以最后怎么解决呢

**Comment by hugselina2019** [comment]
> 所以最后

**Comment by Timo534** [comment]
在rowSelection中配置columnWidth属性，rowSelection: { columnWidth: 60  }
