### ISSUE TITLE
Form can be used in version 2.1.6 but not in version 2.2.5

### ISSUE THREAD

**Issue by RanxinStart** [vueComponent/ant-design-vue#4506]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.5

### Environment
codesandbox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-sutherland-32i2l?file=/src/App.vue)

### Steps to reproduce
```vue
<template>
<div style="padding-left: 50px">
<p>TestForm</p>
<a-form>
<a-form-item label="account" name="account">
<a-input />
</a-form-item>
</a-form>
</div>
</template>
```

> An error has occurred
TypeError
expose is not a function

### What is expected?
Can be used in codesandbox

### What is actually happening?
TypeError
expose is not a function

---
In the later version of 2.2.0, `validate()` caused Maximum recursive updates exceeded when verifying.
Cannot test in codesandbox

**Comment by zkwolf** [comment]
update vue version to 3.2.x

**Comment by RanxinStart** [comment]
update vue version to 3.2.x 
Solved
