### ISSUE TITLE
Table width expandedRowRender render error

### ISSUE THREAD

**Issue by maicWorkGithub** [vueComponent/ant-design-vue#4507]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.5

### Environment
Windows 10 latest; Chrome latest;

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-mendel-z933g?file=/src/components/official.vue)

### Steps to reproduce
click button "update table data"

### What is expected?
update table data and layout correctly

### What is actually happening?
layout changed weird

**Comment by chsword** [comment]
+1

**Comment by qinjiahui01** [comment]
+1

**Comment by tangjinzhou** [comment]
update to 2.2.6

**Comment by an-liyang** [comment]
a-table 中{scroll-x:true}宽度不给scroll-y也不给。能够完全适配。我现在scroll-y:500,每一列都需要给宽度，而且我设置了.ant-table td { white-space: nowrap; }需要一行展示，那么每一列宽度文案最大宽度不订，即时设置了定宽，很多时候内容直接覆盖了。实际场景是需要限定高度但不想设置每一列的宽度，20列宽度最终还需要和x保持差不多太恶心了，如果不设置高度每页展示60条数据，整个表格又太长了，而且页码切换无法触发scrollToFirstRowOnChange。能不能设置scroll-y:500的时候不需要知道列宽自动匹配每列最大宽度，如果设置了某一列宽度就为定宽适配。或者有什么其他的解决方案。
