### ISSUE TITLE
The style problem of table zebra crossing

### ISSUE THREAD

**Issue by chengQVQ** [vueComponent/ant-design-vue#4510]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
win11、vue: 3.2.1、chrome最新版

### Reproduction link
[https://2x.antdv.com/components/table-cn#components-table-demo-stripe](https://2x.antdv.com/components/table-cn#components-table-demo-stripe)

### Steps to reproduce
1.使用官方的实例（带斑马纹表格）
2.给表格最后一列增加fixed:'right'

### What is expected?
都有斑马纹样式

### What is actually happening?
固定的列没有斑马纹样式

---
ant design vue2.2.2版本不会出现此问题

**Comment by chengQVQ** [comment]
![_IH5T(X5D3$5M 6(}05QS%O](https://user-images.githubusercontent.com/64277988/129170699-9568e75d-fa65-4370-8b0c-c00beb43ee54.png)

**Comment by tangjinzhou** [comment]
```html
<style scoped>
.ant-table-striped :deep(.table-striped) td {
  background-color: #fafafa;
}
</style>
```

**Comment by chengQVQ** [comment]
这不是bug吗 2.2.2以及之前的版本没有这种情况

**Comment by tangjinzhou** [comment]
😓   斑马纹表格是组件提供的示例，不能算是组件内部的API。
针对这种示例样式修改，只能说尽可能保证没有破坏性
