### ISSUE TITLE
how to get v2-doc

### ISSUE THREAD

**Issue by zhHub** [vueComponent/ant-design-vue#4511]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vueComponent / ant-design-vue@next

### Reproduction link
[https://github.com/vueComponent/v2-doc/tree/e5fb2accb9cf5e02e2fd0011310a70041b5ff7a1](https://github.com/vueComponent/v2-doc/tree/e5fb2accb9cf5e02e2fd0011310a70041b5ff7a1)

### Steps to reproduce
git clone https://github.com/vueComponent/ant-design-vue.git
clone 的文件中没有 v2-doc文件

### What is expected?
可以获得 v2-doc文件

### What is actually happening?
clone 的文件中没有 v2-doc文件

---
由于公司网络限制，不能访问资源的外网，公司暂时不能提供资源的代理访问方式，是否可以提供方法可以在本地打包使用文档，供学习和工作使用，谢谢

**Comment by maicWorkGithub** [comment]
![image](https://user-images.githubusercontent.com/15863224/129648160-503eaecb-f7ce-4a94-94b0-7c84a20aac9e.png)

**Comment by zkwolf** [comment]
目前这个仓库不对外开放
