### ISSUE TITLE
Support sticky header with fixed column 

### ISSUE THREAD

**Issue by TJ666** [vueComponent/ant-design-vue#4512]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
support sticky header with fixed column , like antd react, https://ant.design/components/table-cn/#components-table-demo-sticky

### What does the proposed API look like?
https://ant.design/components/table-cn/#components-table-demo-sticky

**Comment by gomorizsolt** [comment]
+1

**Comment by gomorizsolt** [comment]
Bump.

**Comment by gomorizsolt** [comment]
Bump!

**Comment by gomorizsolt** [comment]
Bump!
