### ISSUE TITLE
Tree Checking is very slow and causes a large re-render when you have alot of nodes expanded

### ISSUE THREAD

**Issue by OwenPattison** [vueComponent/ant-design-vue#4517]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Chrome 92.0.4515.131, Vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-glade-umf9c?file=/src/components/HelloWorld.vue)

### Steps to reproduce
load 1000 items into tree data and expand all the items, check the root level node

### What is expected?
The tree should be able to efficiently manage checking nodes when they have many expanded child items

### What is actually happening?
The tree takes 2-4 seconds to render the checkbox ticks and locks up the system

---
Currently, my test data has 980 items but I'm really looking to be able to handle at least double that.

This seems to be an issue that also occurred in the react version you can find some information here: https://github.com/ant-design/ant-design/issues/3789

the solution they used was virtualizing large data trees

**Comment by tangjinzhou** [comment]
we will support virtua dom at v3.x

**Comment by hisuwh** [comment]
Is it supported in your v3.x build as it stands?  If not is there another issue we can track?
