### ISSUE TITLE
update from 2.1.6->2.2.6

### ISSUE THREAD

**Issue by z3214965** [vueComponent/ant-design-vue#4521]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vue 3.2

### Reproduction link
[https://github.com/z3214965/test-Ant-Design-of-Vue](https://github.com/z3214965/test-Ant-Design-of-Vue)

### Steps to reproduce
npm run dev

### What is expected?
no warnings and errors

### What is actually happening?
warnings and errors occur

---
view link to reproduction

**Comment by tangjinzhou** [comment]
请提供最小复现，不要直接扔一个完整项目

**Comment by z3214965** [comment]
@tangjinzhou 
这已经最小的了，项目运行npm，可以看见很多警告，浏览器访问可以看见错误。

**Comment by z3214965** [comment]
@tangjinzhou 
安装完依赖后，npm run dev，就应该能看见很多警告，浏览器输入localhost:4302白屏，F12看见错误，不需要完全运行程序

**Comment by tangjinzhou** [comment]
看不出来是 form 的问题，如果你确定是form 的问题  请提供 form 的最小复现示例

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/4271

**Comment by tangjinzhou** [comment]
关掉了，按照 https://github.com/vueComponent/ant-design-vue/issues/4271 格式新开提供issue  
相互扯，浪费大家时间
