### ISSUE TITLE
I cannot coexist Modal.confirm and AForm

### ISSUE THREAD

**Issue by CNMathon** [vueComponent/ant-design-vue#4532]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
Vue Version: 3.1.4

### Reproduction link
[https://github.com/CNMathon/antdv-issue](https://github.com/CNMathon/antdv-issue)

### Steps to reproduce
I write business code and call the relevant methods.

### What is expected?
No warnings are displayed and ATable is displayed properly in AModal when I call "Modal.confirm".

### What is actually happening?
It reports a warning like the following:
[Vue warn]: resolveComponent can only be used in render() or setup().
[Vue warn]: withDirectives can only be used inside render functions.

**Comment by CNMathon** [comment]
@tangjinzhou 
I have created a minimized Github repository. You can navigate to it by clicking [here](https://github.com/CNMathon/antdv-issue).

**Comment by tangjinzhou** [comment]
1、Modal.confirm will use new createApp，you can not use `a-form` `a-form-item` ...  register at app.vue
2、v-model-value not correct, you can visit https://github.com/vuejs/jsx-next find api
3、we recommend use <a-modal> in template，unless you have to leave the appcontext


![image](https://user-images.githubusercontent.com/6937879/130194846-16fcbcb0-bf62-403f-b93e-ea93a8c1165f.png)

**Comment by CNMathon** [comment]
@tangjinzhou 
But if we write in a template, this will make us need to manage a lot of states. And you know, in fact, many states in modal are used temporarily.

**Comment by tangjinzhou** [comment]
```html
<a-modal :key="String(visible)"></a-modal>
```
you can get new modal every time

**Comment by CNMathon** [comment]
> ```
> String(visible)
> ```

@tangjinzhou I've tried this, but it causes the closing animation to fail.

**Comment by CNMathon** [comment]
> ```
> <a-modal :key="String(visible)"></a-modal>
> ```
> 
> you can get new modal every time

I've tried this, but it causes the closing animation to fail.

**Comment by tangjinzhou** [comment]
> > ```
> > <a-modal :key="String(visible)"></a-modal>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can get new modal every time
> 
> @tangjinzhou I've tried this, but it causes the closing animation to fail.

那就换个和 visible 无关的 key，visible 的时候更换一个新的key，关闭的时候不变
