### ISSUE TITLE
The actual performance of the validateField method of useForm is inconsistent with the document description. (The actual performance of the validateField method of useForm is inconsistent with the document description.)

### ISSUE THREAD

**Issue by sevth-developer** [vueComponent/ant-design-vue#4536]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
mac 11.2.3, chrome 92.0 vue 3.0

### Reproduction link
[https://github.com/sevth-developer/antdv-bug-report.git](https://github.com/sevth-developer/antdv-bug-report.git)

### Steps to reproduce
1. Don't input anything, click test2 button
2. enter something, click test2 button

### What is expected?
- The validate passed should be reflected in then.
- 校验通过应该在 `then` 中体现。

### What is actually happening?
- Regardless of whether the rule is validated or not, the `validateField` method will always reflect the result in the `catch`.
- `validateField` 方法不管规则验证与否，结果始终在 `catch` 的体现。

---
- I don't know how this is done [here](https://github.com/vueComponent/ant-design-vue/blob/af0620d14e3f02cface68017df682d0bd14a3328/components/form/useForm.ts#L174).I don't know if the documentation is misleading, this is how it works.
- 这个[链接](https://github.com/vueComponent/ant-design-vue/blob/af0620d14e3f02cface68017df682d0bd14a3328/components/form/useForm.ts#L174)里的使用方法是在 catch 中处理的。感觉像是我被文档误导了，这个方法就是在 `catch` 中处理。

**Comment by tangjinzhou** [comment]
validate 就够了吧   
validateField 不推荐使用
