### ISSUE TITLE
When building with vue.extend, there are components such as Select, DataPicker, etc., which will trigger the execution of two life cycles

### ISSUE THREAD

**Issue by HGthecode** [vueComponent/ant-design-vue#4538]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
"ant-design-vue": "1.7.7",     "vue": "^2.6.11"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-extend-use-antdv-select-abnormal-dqpz8)

### Steps to reproduce
1、点击下方 Open Modal 按钮，此时myModal组件内created执行（这是正常的）

2、点击弹出的myModal组件内的Select时，又会触发一次myModal组件内created执行

### What is expected?
不重复触发组件生命周期

### What is actually happening?
使用 vue.extend 构建一个组件的显示， 当组件内,存在如Select、DataPicker等，有展开面板的组件。 会触发两次生命周期的执行。

**Comment by tangjinzhou** [comment]
ref #4487
