### ISSUE TITLE
[SSR error] ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bowencool** [vueComponent/ant-design-vue#454]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
![image](https://user-images.githubusercontent.com/20217146/51893718-afc3c500-23e0-11e9-9e52-6922020d4da7.png)

        
### Version
1.3.3

### Environment
node 10.15.0

---
回到v1.3.2又恢复正常

**Comment by bowencool** [comment]
[#451](https://github.com/vueComponent/ant-design-vue/issues/451)

**Comment by tangjinzhou** [comment]
duplicate #451
