### ISSUE TITLE
table customRender set tooltip  maximum call stack

### ISSUE THREAD

**Issue by macheteHot** [vueComponent/ant-design-vue#4541]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
*

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-pascal-3hrd6?file=/src/App.vue)

### Steps to reproduce
当 table 配置 customRender 中 jsx 包含变量自身 则栈溢出

### What is expected?
正常显示

### What is actually happening?
栈溢出

---
当使用不同变量无此问题 cloneDeep 无此问题

**Comment by tangjinzhou** [comment]
和组件库无关，你可以去给 vue 或 jsx-next 提issue

另外，你应该避免出现“包含变量自身”的操作
