### ISSUE TITLE
Form component, when v-decorator configures trigger to blur, starting the timer will cause input failure

### ISSUE THREAD

**Issue by IanLew** [vueComponent/ant-design-vue#4545]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
os version: windows10, browser version: Google Chrome 91.0.4472.106, Vue version: 2.6.14

### Reproduction link
[https://codesandbox.io/s/vue-antd-template-forked-lqjc2](https://codesandbox.io/s/vue-antd-template-forked-lqjc2)

### Steps to reproduce
使用v-decorator，trigger为blur，此时使用定时器输入框无法输入，输入数据会被清除
```html
<a-input
v-decorator="[
'captcha',
{
rules: [
{
required: true,
message: 'Please input the captcha you got!',
},
],
trigger: 'blur',
},
]"
/>
```

### What is expected?
用户不主动进行相关操作，输入数据应不受影响

### What is actually happening?
输入框输入数据被清除，无法正常输入

**Comment by tangjinzhou** [comment]
使用 a-form-model 吧   v-decorator 不在推荐使用  
https://antdv.com/components/form-model-cn/

**Comment by IanLew** [comment]
> 使用 a-form-model 吧 v-decorator 不在推荐使用
> https://antdv.com/components/form-model-cn/

已经改用a-form-model了，只是觉得v-decorator比较强大，就试用了一下
