### ISSUE TITLE
After the mouse is like the Menu component, an exception is thrown: Set operation on key "default" failed: target is readonly

### ISSUE THREAD

**Issue by xiupengfei** [vueComponent/ant-design-vue#4546]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
谷歌浏览器, vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/](https://github.com/vueComponent/ant-design-vue/)

### Steps to reproduce
鼠标移入menu组件

### What is expected?
期望不抛出异常

### What is actually happening?
抛大量异常

**Comment by tangjinzhou** [comment]
目测vue 和组件库 版本过低   升级
