### ISSUE TITLE
After upgrading to 2.2.6, there is an issue with the rendering of table's API 'customRow'.

### ISSUE THREAD

**Issue by yuandongx** [vueComponent/ant-design-vue#4547]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
windows7/centos7, Google Chrome 版本 91.0.4472.124（正式版本） （64 位）,vue: 3.1.4,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-swirles-sdvye)

### Steps to reproduce
请查看 https://codesandbox.io/s/interesting-swirles-sdvye

### What is expected?
在用2.2.0-beta.3版本时，columns 中设置了fixed: "left"参数, 自定义渲染也能完整的渲染

### What is actually happening?
2.2.6 columns 中设置了fixed: "left"参数的列颜色没有渲染上

        

### 2.2.0-beta3 (期望)
![image](https://user-images.githubusercontent.com/35824522/130043058-75ef5d8a-c525-408d-b988-3f339c127e46.png)
### 2.2.6 （实际）
![image](https://user-images.githubusercontent.com/35824522/130043146-bb870b3e-8a0a-4f23-bb8e-0c682d29d7f2.png)

**Comment by tangjinzhou** [comment]
2.2.6 tabel 使用了 sticky 来固定列，所以给了默认白色背景
你可以使用 class，来修改白色
