### ISSUE TITLE
Where is this v2-doc

### ISSUE THREAD

**Issue by 1014470807** [vueComponent/ant-design-vue#4548]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vue

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
Where is this v2-doc

### What is expected?
Where is this v2-doc

### What is actually happening?
Where is this v2-doc

---
Where is this v2-doc

**Comment by wkl007** [comment]
https://2x.antdv.com/

**Comment by John60676** [comment]
目前这个仓库不对外开放
