### ISSUE TITLE
ColorPicker, is there a colorpicker function? I can't find it

### ISSUE THREAD

**Issue by Mrsbetter** [vueComponent/ant-design-vue#4550]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vue3

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
none

### What is expected?
希望有个colorpicker组件

### What is actually happening?
none

**Comment by RemMai** [comment]
真心希望AntV支持ColorPicker，希望工程师加把油，努把力，干出来。
