### ISSUE TITLE
ant-design-table  rowKey:Function!!(not String)

### ISSUE THREAD

**Issue by Tnon** [vueComponent/ant-design-vue#4552]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
last

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-tess-d012x?file=/src/App.vue)

### Steps to reproduce
rowKey 设置函数，并在函数打印record，打印次数很奇快，目前也没发现规律，跟行数也没关系

### What is expected?
函数执行次数=行数

### What is actually happening?
函数执行次数远远大于行数

**Comment by Tnon** [comment]
<template>
  <div>
    <a-table :columns="columns" :aa="ss" :data-source="data" :rowKey="rowKey">
    </a-table>
    <button @click="ccc">按钮</button>
  </div>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue'
const columns = [
  {
    title: 'Age',
    dataIndex: 'age'
  },
  {
    title: 'Address',
    dataIndex: 'address'
  }
]

const data = [
  {
    age: 42,
    address: 'London No. 1 Lake Park'
  }
]

export default defineComponent({
  setup() {
    const ss = ref<boolean>(false)
    const ccc = () => {
      ss.value = !ss.value
    }
    const rowKey = (record) => {
      console.log(record)
      return record.address
    }
    return {
      data,
      columns,
      rowKey,
      ss,
      ccc
    }
  }
})
</script>

**Comment by tangjinzhou** [comment]
render的次数不能保证， 确保你的 rowKey 不要有副作用
