### ISSUE TITLE
Input component supports mergeProps of events

### ISSUE THREAD

**Issue by wxhccc** [vueComponent/ant-design-vue#4558]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前Input组件内部对于传入的onBlur事件是直接调用的，而二次封装的Input组件可能存在绑定mergeProps(attrs, { onBlur })的情况，而mergeProps函数对同名事件会添加到一个数组之中，这时直接调用会导致类型报错。
具体可见：https://codesandbox.io/s/dark-tree-te8x1

### What does the proposed API look like?
Input组件内部事件调用时进行类型判断，如果是数组则遍历调用（目前仅发现Input组件存在这个问题，但不确定是不是其他有onBlur事件的组件也存在）

**Comment by tangjinzhou** [comment]
建议直接用 {...attrs, onBlur: ()=> { emit('blur')}} 覆盖合并    
组件内如如果做大量的数组判断，影响性能
