### ISSUE TITLE
$store is undefined in Modal

### ISSUE THREAD

**Issue by yxc888** [vueComponent/ant-design-vue#4560]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Chrome

### Reproduction link
[https://antdv.com/docs/vue/introduce/](https://antdv.com/docs/vue/introduce/)

### Steps to reproduce
Firstly, define a component A which use vuex.

Then, use function Modal.confirm,
Modal.confrim({
content: h => <A />,
})

### What is expected?
get $store correctly

### What is actually happening?
TypeError: Cannot read property 'state' of undefined
at VueComponent.mappedState (vuex.esm.js?2f62:945)
at Watcher.get (vue.esm.js?a026:4488)

When i console.log(this.$store) in A, it show undefined.

**Comment by tangjinzhou** [comment]
ref #4532
