### ISSUE TITLE
When select "value" is a number type, the form verification has not passed

### ISSUE THREAD

**Issue by hunanzhoujielun** [vueComponent/ant-design-vue#4562]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vue 3.2.3

### Reproduction link
[https://2x.antdv.com/components/select-cn](https://2x.antdv.com/components/select-cn)

### Steps to reproduce
< a-select-option > "value" if the form is of digital type and fails to pass the verification, it can be verified successfully by changing to string type

### What is expected?
The form should be verified successfully

### What is actually happening?
Form verification failed

**Comment by tangjinzhou** [comment]
form rule set type : 'number'
