### ISSUE TITLE
Can official documents provide JSX/TSX demos?

### ISSUE THREAD

**Issue by Rich1e** [vueComponent/ant-design-vue#4563]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Vue 3.0 开始支持 JSX 和 Typescript，但在实际使用中，由于语法糖发生了变化，导致出现了很多莫名其妙的问题。

另外，虽然官方提供了一份 JSX 的资料，但是帮助有限。
https://github.com/vuejs/jsx-next

问题：
- 组件中使用了 `v-model` 特性时，`JSX` 与 `TSX` 有区别吗？分别如何书写？
- 组件中使用了 `v-slots` 特性时，scope 内的对象支持类型推断吗？
- 组件中绑定的值，应用于 `template` 时，在什么情况下支持解构赋值？

JSX/TSX 示例：

```HTML
<script lang="tsx">
import { defineComponent, computed, ref, watch } from 'vue'
import { Transfer, Tree } from 'ant-design-vue'
import { CheckEvent } from 'ant-design-vue/es/tree/Tree'

interface TreeDataItem {
  key: string;
  title: string;
  disabled?: boolean;
  children?: TreeDataItem[];
}

const tData: TreeDataItem[] = [
  { key: '0-0', title: '0-0' },
  {
    key: '0-1',
    title: '0-1',
    children: [
      { key: '0-1-0', title: '0-1-0' },
      { key: '0-1-1', title: '0-1-1' },
    ],
  },
  { key: '0-2', title: '0-3' },
]

const transferDataSource: TreeDataItem[] = [];
function flatten(list: TreeDataItem[] = []) {
  list.forEach(item => {
    transferDataSource.push(item);
    flatten(item.children);
  });
}
flatten(JSON.parse(JSON.stringify(tData)))

function isChecked(selectedKeys: string[], eventKey: string) {
  return selectedKeys.indexOf(eventKey) !== -1;
}

function handleTreeData(data: TreeDataItem[], targetKeys: string[] = []): TreeDataItem[] {
  data.forEach(item => {
    item['disabled'] = targetKeys.includes(item.key);
    if (item.children) {
      handleTreeData(item.children, targetKeys);
    }
  });
  return data;
}

export default defineComponent({
  setup() {
    const transferDtaSource = ref<any | TreeDataItem[]>(transferDataSource)
    const transferTargetKeys = ref<string[]>()

    const handleChange = (nextTargetKeys: string[], direction: string, moveKeys: string[]) => {
      transferTargetKeys.value = nextTargetKeys
    }

    const treeDataSource = computed<TreeDataItem[]>(() => {
      return handleTreeData(tData, transferTargetKeys.value)
    })

    const onChecked = (
      _: Record<string, string[]>,
      e: CheckEvent,
      checkedKeys: string[],
      onItemSelect: (n: any, c: boolean) => void,
    ) => {
      const { eventKey } = e.node;
      onItemSelect(eventKey, !isChecked(checkedKeys, eventKey));
    };

    return () => (
      <>
        <Transfer
          dataSource={transferDtaSource.value}
          targetKeys={transferTargetKeys.value}
          render={item => item.title}
          onChange={handleChange}
          showSelectAll={false}
          v-slots={{
            children: (direction, selectedKeys, onItemSelect) => {
              direction === 'left' &&
              <Tree
                blockNode
                checkable
                checkStrictly
                defaultExpandAll
                v-model={[selectedKeys, 'transferTargetKeys.value', ['checkedKeys']]}
                treeData={treeDataSource.value}
                onCheck={
                  (_, props) => {
                    onChecked(_, props, [...selectedKeys, ...treeDataSource.value], onItemSelect);
                  }
                }
                onSelect={
                  (_, props) => {
                    onChecked(_, props, [...selectedKeys, ...treeDataSource.value], onItemSelect);
                  }
                }
              />
            }
          }}
        />
      </>
    )
  }
})
</script>
```

截图：

![image](https://user-images.githubusercontent.com/29914689/130550411-a3b210d7-6521-4b43-a7f3-4b69a26c6ff9.png)

**组件并没有报错，但是渲染结果，与官方不一致。目前不清楚是语法糖问题，还是组件属性未正确执行。**

[官方示例](https://2x.antdv.com/components/transfer-cn#components-transfer-demo-tree-transfer)

### What does the proposed API look like?
希望官方能为组件提供 JSX/TSX 的 Demo

**Comment by sendya** [comment]
v-model={[变量, '绑定prop属性']}  建议多看 jsx 官方文档例子

```vue
const x = ref([])

v-model={[x, 'selectedKeys']}
```

slot

```jsx
<Transfer
   children={({  direction, filteredItems, selectedKeys, ...more }) => (<div></div>)}
/>
```

**Comment by Rich1e** [comment]
> v-model={[变量, '绑定prop属性']} 建议多看 jsx 官方文档例子
> 
> ```
> const x = ref([])
> 
> v-model={[x, 'selectedKeys']}
> ```
> 
> slot
> 
> ```js
> <Transfer
>    children={({  direction, filteredItems, selectedKeys, ...more }) => (<div></div>)}
> />
> ```
> 
> 如非必要，建议您使用 template 语法，执行效率上更高

slot 这段代码

**Comment by Rich1e** [comment]
执行效率更高，未必可信。（传统的 `template` 更快。）
如果只是为了执行效率更高，大可不必使用 `MV*` 框架。

之所以在项目中使用 `JSX/TSX` 编写，是因为它具有良好的编程能力，对于组织和构建复杂应用提供了便利。
另外，`antdv` 的源码中也大量使用了 `JSX/TSX` ，这就让人疑惑了？

最后，希望官方组件对于 `JSX/TSX` 的支持能公开透明。（譬如，完善的开发文档，别让用户的开发体验，像似拆盲盒。）

**Comment by sendya** [comment]
jsx 相关的问题，你可以直接去 vue-jsx 提问，我这没意见。
性能问题不好说，但尤大说明 template 性能确实会高，目前 jsx确实不会有抽离静态节点

至于盲盒，我从你上面的提问看出，你应该是缺少 jsx 的语法经验，以及没有认真看 vue-jsx 的语法导致的，并不是我们组件库要隐瞒什么。
template 用法我们写的非常明白 还有代码可以直接复制，你应该考虑 template 转换成 jsx 语法应该长成什么样，这个可以去咨询 jsx 库。谢谢

**Comment by Rich1e** [comment]
> jsx 相关的问题，你可以直接去 vue-jsx 提问，我这没意见。
> 性能问题不好说，但尤大说明 template 性能确实会高，目前 jsx确实不会有抽离静态节点
> 
> 至于盲盒，我从你上面的提问看出，你应该是缺少 jsx 的语法经验，以及没有认真看 vue-jsx 的语法导致的，并不是我们组件库要隐瞒什么。
> template 用法我们写的非常明白 还有代码可以直接复制，你应该考虑 template 转换成 jsx 语法应该长成什么样，这个可以去咨询 jsx 库。谢谢

不谢。

如果是 `jsx` 相关的问题，我不会来这提问。
性能问题不好说，但尤大希望你回去看看书，尊重一下用户开发体验（一会是属性，一会是插槽，你们是教魔法的吗？）。

至于你的专业度，我从你上面的回答看出，你应该是缺少正面采纳提问的勇气（不能接受反对意见），以及没有认真看我所提的问题导致的，并不是你们组件库要背锅。
`template` 用法你们写的文档写的一般 直接复制的代码还有各种 `Typescript` 报错，你应该考虑怎么完善 `jsx` 语法相关的文档说明，，这个就不需要咨询 jsx 库了。

**说了这么多，对于我提出的问题，没有解答而感到失望。**

**Comment by sendya** [comment]
`一会是属性，一会是插槽`

这个没给你解释，你既可以用 v-slots 也能用 props 二者选一，没有限制，均能实现同样的功能，只是写 props 会更加容易理解，可以参考 React JSX 语法。

至于你的其他问题 你要争论与你问题无关的内容 就无法给你更多回答了

**Comment by Rich1e** [comment]
原本只想弄清楚在 `JSX/TSX` 中如何使用 `Transfer` 自定义 `Tree`，
结果抛出 `执行效率上更高` ` 你应该是缺少 jsx 的语法经验`  的言论。

不要本末倒置，如果你们有详细的文档，谁会在这里提问？
你如果知道答案，毋需掰扯，请直接给出正确的解答，不要长篇大论和歪曲问题。

PS：`antdv` 官网对于如何支持 `JSX/TSX` 语法，没有示例也缺乏资料。
