### ISSUE TITLE
modal modal bug, ant-modal-wrap style does not have display: none in the test server environment, causing the page to be unclickable

### ISSUE THREAD

**Issue by laijinxian** [vueComponent/ant-design-vue#4565]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
服务器， 谷歌浏览器，

### Reproduction link
[https://2x.antdv.com/components/modal-cn](https://2x.antdv.com/components/modal-cn)

### Steps to reproduce
随意弹出弹窗，关闭后； 最外层原素有个 类名为ant-modal-root 的节点， 他下面有个  ant-modal-wrap 节点， 正式环境下  ant-modal-wrap 他会有display: none 属性， 测试环境就缺少这个样式导致整个页面无法点击

### What is expected?
和正式环境一样 模态弹窗关闭后 ant-modal-wrap 应该要有 display: none 属性

### What is actually happening?
ant-modal-wrap 缺少 display: none 属性

**Comment by laijinxian** [comment]
123

**Comment by Soo-For** [comment]
I have the same problem now.And it occurs only in the **test** environment!!

**Comment by Soo-For** [comment]
> watchEffect(() => {
> const modelWrap:HTMLElement|null = document.querySelector('.ant-modal-wrap')
> if (!visible.value && modelWrap) {
> nextTick(() => {
> modelWrap.style.display = 'none'
> })
> }
> })暂时先这么搞

When a page has Model elements more than two, there will still be the problem.
Improved code:
```js
watchEffect(() => {
  const modelWrap: NodeList = document.querySelectorAll('.ant-modal-wrap');
  if (!state.modelVisible && modelWrap.length) {
    nextTick(() => {
      modelWrap.forEach((el: HTMLElement) => {
        el.style.display = 'none';
      });
    });
  }
});
```

**Comment by wulucxy** [comment]
same problem +1

**Comment by wulucxy** [comment]
@laijinxian 你是怎么解决了么

**Comment by wulucxy** [comment]
问题解决了：
加上`destroyOnClose` 就有问题，不加没问题了

**Comment by nikolausliu** [comment]
这个issue为什么要关闭？bug修复了吗？2.2.0版本bug依然存在

**Comment by nikolausliu** [comment]
3.2版本了，这个bug依然存在

**Comment by AmmyXu** [comment]
这个bug没人处理么？

**Comment by wanghao1991** [comment]
希望官方注意下，这是个大坑，本地环境，dev开发环境都没问题，就是test测试环境有这个bug, 害我查了大半天！！！！！我的目前是3.2版本  。 我的情况是用modal.confirm打开的弹框，无论是点击关闭，还是确定, 都会出现这个bug!!

**Comment by tangjinzhou** [comment]
process.env.NODE_ENV === 'test' 被占用了，可以先换个环境变量打包测试环境的包，下个版本会改掉

**Comment by q359352759** [comment]
我使用vite4就没有这问题了，使用vite3依然会出现这情况
