### ISSUE TITLE
Alarm warning when using ConfigProvider to set up Chinese environment

### ISSUE THREAD

**Issue by dairsaber** [vueComponent/ant-design-vue#4567]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue 3.2.4  web环境  vite2.5 ant-design-vue 2.2.6

### Reproduction link
[https://github.com/dairsaber/my-vue-test-app](https://github.com/dairsaber/my-vue-test-app)

### Steps to reproduce
启动就报警告

### What is expected?
配置能正常使用

### What is actually happening?
在使用 ConfigProvider 设置中文环境的 的时候报警警告 而且的确 设置不上

runtime-core.esm-bundler.js:6873 [Vue warn]: Extraneous non-props attributes (local) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.
at <ALocaleProvider locale=undefined ANT_MARK__="internalMark" local= Object >
at <LocaleReceiver children=fn<children> local= Object >
at <AConfigProvider local= Object >
at <App>

**Comment by sendya** [comment]
![image](https://user-images.githubusercontent.com/5404542/130596388-feae0533-06e5-4ec7-84c5-922b67db2c8c.png)

 `local` -> `locale`
