### ISSUE TITLE
DatePicker, RangePicker Cannot read property 'key' of undefined

### ISSUE THREAD

**Issue by koaqiu** [vueComponent/ant-design-vue#457]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.3

### Environment

win10,vue:2.5.21

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
添加到页面
```
<a-date-picker @change="onChangeDate" key="date-picker"/>
```
然后点击 控件选择日期

### What is expected?
正常弹出日期选择框

### What is actually happening?
无法选择日期，并且报错：RangePicker Cannot read property 'key' of undefined

        

https://boomdaily.oss-cn-shanghai.aliyuncs.com/tmp/20190131091606.png

**Comment by tangjinzhou** [comment]
使用这个https://codesandbox.io/s/2wpk21kzvr 提供复现demo 谢谢

**Comment by koaqiu** [comment]
@tangjinzhou 
我上传了一个
https://codesandbox.io/s/3x37pwv5np 这里好像运行不了 TypeScript项目

也上传到这里了
https://github.com/koaqiu/test-ant-design-vue

**Comment by tangjinzhou** [comment]
class component的使用方式不对，https://github.com/vuejs/vue-class-component
```
<script lang="ts">
import Vue from 'vue'
import Component from 'vue-class-component'

@Component
export default class App extends Vue {
}
</script>
```

**Comment by koaqiu** [comment]
@tangjinzhou 我的代码是vue-cli自动生成的，用的是```import { Component, Prop, Vue } from 'vue-property-decorator';```
我按你说的改了，可以了

谢谢了。

**Comment by tangjinzhou** [comment]
`import { Component, Prop, Vue } from 'vue-property-decorator';`
也可以，没有问题，你的问题是没有使用 ` @Component` 修饰

**Comment by gouflv** [comment]
遇到同样的坑，找了半天才发现有个模块忘了写修饰
