### ISSUE TITLE
The problem that Option cannot use Number type in Select multi-select mode

### ISSUE THREAD

**Issue by Hccake** [vueComponent/ant-design-vue#4570]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Windows, Chrome, Vue 2.6.12

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-4qpjc)

### Steps to reproduce
使用 number 作为 option 的值

### What is expected?
多选模式下支持 number 作为 option 的值

### What is actually happening?
报错

---
想了解下为什么这么设计，使用 Number 作为 Option 的值，应该是一个比较常见的需求

**Comment by tangjinzhou** [comment]
基础组件逻辑来源于 react-component  https://github.com/ant-design/ant-design/issues/2857
react版本由于依赖 key，而且key只能为 string，所以限制了 string 类型，可以看看这个 pr https://github.com/react-component/select/pull/229

虽然 vue 没有 string 限制，但有大量逻辑判断是基于string类型的，导致简单的放开类型权限会有较多问题

不过我们会在  2.2.7 版本中去掉该限制

**Comment by Hccake** [comment]
感谢回答，那这边就暂时只能先对数据做下特殊处理了，期待后续版本更新
