### ISSUE TITLE
Select in Modal couldn't be opened

### ISSUE THREAD

**Issue by yandixuan** [vueComponent/ant-design-vue#4582]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hidden-violet-vbn59?file=/src/components/Modal.vue)

### Steps to reproduce
open and open then click select 

### What is expected?
select should work

### What is actually happening?
getOffsetParent.js:34 Uncaught (in promise) TypeError: element.nodeName.toLowerCase is not a function
    at getOffsetParent (getOffsetParent.js:34)
    at getVisibleRectForElement (getVisibleRectForElement.js:52)
    at isOutOfVisibleRect (alignElement.js:7)
    at alignElement (alignElement.js:23)
    at Align.js:68
    at trigger2 (useBuffer.js:11)
    at goAlign2 (Align.js:112)
    at Align.js:124
    at callWithErrorHandling (runtime-core.esm-bundler.js:6990)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:6999)
getOffsetParent @ getOffsetParent.js:34
getVisibleRectForElement @ getVisibleRectForElement.js:52
isOutOfVisibleRect @ alignElement.js:7
alignElement @ alignElement.js:23
(anonymous) @ Align.js:68
trigger2 @ useBuffer.js:11
goAlign2 @ Align.js:112
(anonymous) @ Align.js:124
callWithErrorHandling @ runtime-core.esm-bundler.js:6990
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6999
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2270
flushPostFlushCbs @ runtime-core.esm-bundler.js:7191
flushJobs @ runtime-core.esm-bundler.js:7228
flushJobs @ runtime-core.esm-bundler.js:7236
Promise.then (async)
nextTick @ runtime-core.esm-bundler.js:7081
updated3 @ Trigger.js:131
callWithErrorHandling @ runtime-core.esm-bundler.js:6990
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6999
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2270
flushPostFlushCbs @ runtime-core.esm-bundler.js:7191
flushJobs @ runtime-core.esm-bundler.js:7228
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:7120
queueCb @ runtime-core.esm-bundler.js:7142
queuePreFlushCb @ runtime-core.esm-bundler.js:7145
scheduler @ runtime-core.esm-bundler.js:7410
triggerEffects @ reactivity.esm-bundler.js:358
triggerRefValue @ reactivity.esm-bundler.js:948
set value @ reactivity.esm-bundler.js:987
setInnerOpen2 @ generate.js:499
onToggleOpen2 @ generate.js:527
onMousedown3 @ index.js:178
callWithErrorHandling @ runtime-core.esm-bundler.js:6990
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6999
invoker @ runtime-dom.esm-bundler.js:347

**Comment by John60676** [comment]
Related issue: https://github.com/ant-design/ant-design/issues/31792

**Comment by tangjinzhou** [comment]
3.0 直接默认加前缀   避免此类问题
