### ISSUE TITLE
VUE-CLI 2.0定制主题会报错

### ISSUE THREAD

**Issue by luotingv1** [vueComponent/ant-design-vue#459]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
vue-cli 2.0  vue": "^2.5.2",

### Reproduction link
[https://user-images.githubusercontent.com/24503005/52096724-d06b6500-2602-11e9-97dc-72fb298559fb.png](https://user-images.githubusercontent.com/24503005/52096724-d06b6500-2602-11e9-97dc-72fb298559fb.png)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/24503005/52096693-b467c380-2602-11e9-8497-6287376068a1.png)

![image](https://user-images.githubusercontent.com/24503005/52096711-c34e7600-2602-11e9-9140-cacc61f6f178.png)

### What is expected?
success run dev

### What is actually happening?
![image](https://user-images.githubusercontent.com/24503005/52096724-d06b6500-2602-11e9-97dc-72fb298559fb.png)

**Comment by luotingv1** [comment]
原来是less-loader没装  问题是这个报错不对啊

**Comment by SongJuXin** [comment]
@luotingv1 怎么解决的。我看到你的配置和报错都跟我的一样，less-loader也安装了，但是还是报你截图里面的错。请求你是怎么解决的。

**Comment by dangnuo7** [comment]
> @luotingv1 怎么解决的。我看到你的配置和报错都跟我的一样，less-loader也安装了，但是还是报你截图里面的错。请求你是怎么解决的。

解决了吗？我现在也碰到同样的问题

**Comment by luotingv1** [comment]
> @luotingv1 怎么解决的。我看到你的配置和报错都跟我的一样，less-loader也安装了，但是还是报你截图里面的错。请求你是怎么解决的。
更新下vue版本
