### ISSUE TITLE
Upload upload file When selecting a file, press Enter twice in succession to select a file, and a pop-up window for selecting a file will pop up twice

### ISSUE THREAD

**Issue by x3852** [vueComponent/ant-design-vue#4594]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
操作系统：windows 10、浏览器版本：Chrome 92.0.4515.131，Vue版本：2.6.12

### Reproduction link
[https://www.antdv.com/components/upload-cn/](https://www.antdv.com/components/upload-cn/)

### Steps to reproduce
1：点击上传文件出现系统选择文件弹框
2：鼠标选择要上传的文件（只选择文件不要确定）
3：按键盘Enter键多次确定选择文件
4：弹窗消失后会立即再次弹出选择文件弹框

### What is expected?
选择文件时多次按Enter键不再次出现选择文件弹框

### What is actually happening?
多次按Enter键选择文件会连续出现多次选择文件弹框

**Comment by tangjinzhou** [comment]
上传依然处在 focus 状态，你可以在上传回调中主动 blur，使其失焦

**Comment by x3852** [comment]
貌似并没有作用，我在change和beforeUpload事件中都试过调用input的blur方法并没有起作用
let uploadFile = this.$refs.uploadFile
let fileElem = uploadFile.$el.querySelector('input[type=file]')
fileElem.blur()
