### ISSUE TITLE
v-model can not work properly on a-select（in tag mode）

### ISSUE THREAD

**Issue by arika163** [vueComponent/ant-design-vue#4596]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
windows10@1909,chrome@81.0.4044.122,vue@2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-parm-h3r7l?file=/src/App.vue)

### Steps to reproduce
try to add or drop some options in my reproduction, `v-bind:value` works find ,when `v-model` can't pass value from parent to a-select

### What is expected?
`v-model` can pass value from parent to a-select

### What is actually happening?
only `v-bind:value` can work correctly

**Comment by tangjinzhou** [comment]
v-model  not :v-model
https://codesandbox.io/s/beautiful-allen-k1jzf?file=/src/App.vue
