### ISSUE TITLE
👨🏻‍💻👩🏻‍💻欢迎加入 Ant Design Vue 交流群

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#460]
### 微信订阅号：ant-design-vue
掌握最新动态，分享前沿文章，扫码订阅
<img width="258" src="https://cdn.nlark.com/yuque/0/2019/jpeg/87084/1550303926433-assets/web-upload/3bf5b121-fea2-44bb-9ef9-0d61616c85e3.jpeg"/>

### QQ自助交流群：217490093
扯淡、交流、分享，扫码加入
<img width="258" src="https://user-images.githubusercontent.com/6937879/52161659-9635bc80-2703-11e9-9437-d1ba25b623c9.png"/>

**Comment by cduyzh** [comment]
赞一个 ，希望bug处理的快一点

**Comment by YuGe** [comment]
Do we have guide of how to contribute?

**Comment by gauseen** [comment]
@tangjinzhou 你好我想问一下，ant-design-vue 会一直跟官方 ant-design UI 保持一致吗？

**Comment by tangjinzhou** [comment]
@gauseen 会，但不会那么快同步到新版本，我们需要时间开发，测试

**Comment by meooxx** [comment]
提个问题： 源代码里面的 英文注释实在晦涩难懂？可以尽量把意思表达到位吗？

**Comment by tangjinzhou** [comment]
> 提个问题： 源代码里面的 英文注释实在晦涩难懂？可以尽量把意思表达到位吗？

😓 好尴尬

**Comment by yurizhang** [comment]
搞个钉钉群或是微信群啊~~

**Comment by Nekosandesu** [comment]
微信群加一，扣扣都不怎么用了

**Comment by golangscott** [comment]
@tangjinzhou IE11 和 Edge 上面还是蛋疼的存在

**Comment by cdmalcl** [comment]
让阿里弄微信群不太.....之前研究vue弄的群：
![delme](https://user-images.githubusercontent.com/8749073/59036765-7fb29400-88a2-11e9-9643-7d322bf318a0.png)

**Comment by teachat8** [comment]
@cdmalcl 二维码失效了

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/62036228-fbd2b380-b223-11e9-8097-27074fffa7c3.png)

**Comment by fangbenling** [comment]
antd vue  主题色 如何做全局修改 包括组件的颜色

**Comment by NickYangZY** [comment]
Upload上传组件的change事件中，参数event到底能不能用的，打印全部也没找到用event这个东西

**Comment by zongzmz** [comment]
QQ为什么不让加了

**Comment by tangjinzhou** [comment]
@zongzmz 可以添加啊 只不过是10元付费添加了  群已经超2000人了

**Comment by wwwjun** [comment]
想克隆个官网内部部署，没找到，请问应该是没有开源是吧？

**Comment by xiaohuan1111** [comment]
IE还是有问题 怎么办

**Comment by cnlydia** [comment]
加 qq群竟然要收费，6.6？？？

**Comment by fengyun2** [comment]
QQ为什么不让加了

**Comment by newlifebegins** [comment]
可以加一个选择年的功能吗？

**Comment by golangscott** [comment]
建议增加，月选择器，增加农历节气扩展，能够支持月/周/日视图无缝切换，支持增加事件参考，Google Calendar



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhanyoulin456"<notifications@github.com&gt;; 
发送时间: 2019年9月11日(星期三) 晚上11:23
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "golangscott"<go.lang@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] &#x1F468;&#x1F3FB;&#x200D;&#x1F4BB;&#x1F469;&#x1F3FB;&#x200D;&#x1F4BB;欢迎加入 Ant Design Vue 交流群 (#460)




DataPiker建议加一个年选择器
 
&mdash;

**Comment by golangscott** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"golangscott"<go.lang@qq.com&gt;;
发送时间:&nbsp;2019年9月18日(星期三) 下午2:20
收件人:&nbsp;"vueComponent/ant-design-vue"<reply@reply.github.com&gt;;"vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;;
抄送:&nbsp;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;回复： [vueComponent/ant-design-vue] &amp;#x1F468;&amp;#x1F3FB;&amp;#x200D;&amp;#x1F4BB;&amp;#x1F469;&amp;#x1F3FB;&amp;#x200D;&amp;#x1F4BB;欢迎加入 Ant Design Vue 交流群 (#460)



建议增加，月选择器，增加农历节气扩展，能够支持月/周/日视图无缝切换，支持增加事件参考，Google Calendar



------------------ 原始邮件 ------------------
发件人: "zhanyoulin456"<notifications@github.com&gt;; 
发送时间: 2019年9月11日(星期三) 晚上11:23
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com&gt;; 
抄送: "golangscott"<go.lang@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [vueComponent/ant-design-vue] 👨🏻‍💻👩🏻‍💻欢迎加入 Ant Design Vue 交流群 (#460)




DataPiker建议加一个年选择器

**Comment by ensignwy** [comment]
菜单组件，当使用外部链接的时候，能不能不要高亮，因为它已经跳到外部去了，而不是本系统的路由了，不应该高亮
![image](https://user-images.githubusercontent.com/24467171/65579309-174f0600-dfaa-11e9-9b04-9b0b5bf0cfbc.png)

**Comment by sendya** [comment]
> 菜单组件，当使用外部链接的时候，能不能不要高亮，因为它已经跳到外部去了，而不是本系统的路由了，不应该高亮
> ![image](https://user-images.githubusercontent.com/24467171/65579309-174f0600-dfaa-11e9-9b04-9b0b5bf0cfbc.png)

:selectedKeys 手动控制一下即可

**Comment by ensignwy** [comment]
> > 菜单组件，当使用外部链接的时候，能不能不要高亮，因为它已经跳到外部去了，而不是本系统的路由了，不应该高亮
> > ![image](https://user-images.githubusercontent.com/24467171/65579309-174f0600-dfaa-11e9-9b04-9b0b5bf0cfbc.png)
> 
> :selectedKeys 手动控制一下即可

我试了一下，虽然可以，但是有个bug，就是跳出链接后再回来这个页面，会有两个高亮的菜单，要把鼠标移动一下，才能消失。你看看，https://codesandbox.io/embed/vue-template-i7hkk

**Comment by sendya** [comment]
> > > 菜单组件，当使用外部链接的时候，能不能不要高亮，因为它已经跳到外部去了，而不是本系统的路由了，不应该高亮
> > > ![image](https://user-images.githubusercontent.com/24467171/65579309-174f0600-dfaa-11e9-9b04-9b0b5bf0cfbc.png)
> > 
> > 
> > :selectedKeys 手动控制一下即可
> 
> 我试了一下，虽然可以，但是有个bug，就是跳出链接后再回来这个页面，会有两个高亮的菜单，要把鼠标移动一下，才能消失。你看看，https://codesandbox.io/embed/vue-template-i7hkk

我试了没问题，具体看下图，图有点大 加载比较慢
![GIF](https://user-images.githubusercontent.com/5404542/65655916-7f582780-e050-11e9-9447-a2be30f6db7a.gif)

另外实在不行，给 menu 加个 ref，然后 $refs.menu.bulr() 失焦试试

**Comment by ensignwy** [comment]
> > > > 菜单组件，当使用外部链接的时候，能不能不要高亮，因为它已经跳到外部去了，而不是本系统的路由了，不应该高亮
> > > > ![image](https://user-images.githubusercontent.com/24467171/65579309-174f0600-dfaa-11e9-9b04-9b0b5bf0cfbc.png)
> > > 
> > > 
> > > :selectedKeys 手动控制一下即可
> > 
> > 
> > 我试了一下，虽然可以，但是有个bug，就是跳出链接后再回来这个页面，会有两个高亮的菜单，要把鼠标移动一下，才能消失。你看看，https://codesandbox.io/embed/vue-template-i7hkk
> 
> 我试了没问题，具体看下图，图有点大 加载比较慢
> ![GIF](https://user-images.githubusercontent.com/5404542/65655916-7f582780-e050-11e9-9447-a2be30f6db7a.gif)
> 
> 另外实在不行，给 menu 加个 ref，然后 $refs.menu.bulr() 失焦试试

真有这个问题，实际上就是点这个链接的时候，这个地方处于hover状态，但是你再回来的时候，如果鼠标没有移动，hover状态还是在原来那个点上，这好像没法解决啊， $refs.menu.blur()方法不存在（顺便问一下，你用什么做的gif啊😶)

**Comment by tangjinzhou** [comment]
@ensignwy @sendya  新开个issue 讨论吧

**Comment by zhimo** [comment]
希望文档能够版本化

**Comment by jiangtao** [comment]
求钉钉群

**Comment by lizhongyi** [comment]
群的管理员，不知道是不是作者，阴阳怪气的，不建议加群，看文档就好了。

**Comment by fengyun2** [comment]
还好没入坑
