### ISSUE TITLE
Cant import Menu children directly

### ISSUE THREAD

**Issue by Nisgrak** [vueComponent/ant-design-vue#4601]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
Windows 10, WSL 2, Chrome, Vue 3.2.6

### Reproduction link
[https://github.com/Nisgrak/example-antd](https://github.com/Nisgrak/example-antd)

### Steps to reproduce
Execute yarn serve in the project and see the error in the console

### What is expected?
Allow to import Menu children directly, don't need to use app.use widely in the app. Select and other components with childrens works well

### What is actually happening?
Have a strange error

---
I can't use app.use because it's an component unit test, so cant registres widely things

**Comment by tangjinzhou** [comment]
1、remove babel-plugin-import & node_modules cache
2、use `import { Menu as AMenu, MenuItem as AMenuItem, MenuItemGroup as AMenuItemGroup, SubMenu as ASubMenu } from 'ant-design-vue';`

or

1、const AMenu = Menu.Item

**Comment by book12085** [comment]
请问现在是不支持 babel-plugin-import吗？
