### ISSUE TITLE
The 2.2.6 version 'EventHandlerNonNull' ts type definition is missing

### ISSUE THREAD

**Issue by rashagu** [vueComponent/ant-design-vue#4613]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
yarn,  node 14

### Reproduction link
[https://github.com/rashagu/antdvText2](https://github.com/rashagu/antdvText2)

### Steps to reproduce
atndv 2.2.6 版本
vite vue-tsc --noEmit && vite build
ts 类型检查

### What is expected?
构建成功

### What is actually happening?
```
node_modules/ant-design-vue/lib/date-picker/index.d.ts:54:15 - error TS2304: Cannot find name 'EventHandlerNonNull'.

54     onFocus?: EventHandlerNonNull;
```

**Comment by tangjinzhou** [comment]
固定 typescript版本到 4.3

**Comment by tjx666** [comment]
感觉这个问题挺严重

**Comment by Fallsleep** [comment]
我这边更夸张，`a-divider`、`a-card`、`a-row`、`a-col`全都报错，`package.json`里指定的`4.3.4`，`VSCode`也设置成使用项目的`typescript`版本了，但是`vue-tsc --noEmit && vite build`和`VSCode`依然报这样的错误：
```
error TS2345: Argument of type '{}' is not assignable to parameter of type 'App<any> & IntrinsicAttributes & Record<string, unknown> & Partial<{ prefixCls: string; }> & Omit<Readonly<{ span?: unknown; order?: unknown; offset?: unknown; push?: unknown; pull?: unknown; xs?: unknown; ... 6 more ...; flex?: unknown; } & { ...; } & { ...; }> & VNodeProps & AllowedComponentProps & ComponentCustom...'.
  Type '{}' is missing the following properties from type 'App<any>': version, config, use, mixin, and 11 more
```

@tangjinzhou

**Comment by atomjaylee** [comment]
@Fallsleep 可以暂时将volar插件回退一个版本

**Comment by Fallsleep** [comment]
@atomjaylee 将volar插件回退到`0.27.13`后`VSCode`不再提示类型不匹配。

早上看到`VSCode`的扩展提示`Your vue-tsc dependency is not same with Extension version (0.27.9 ~ 0.27.13). It may cause inconsistent type check results between cli and IDE.`，就把扩展升级到了`0.27.14`，然后按照提示又把`vue-tsc@^0.3.0`依赖的`vscode-vue-languageservice@^0.27.0`下的`vscode-typescript-languageservice`等库从`^0.27.9`升级到了`^0.27.14`，就悲剧了。

发现扩展回退到`0.27.13`没问题后，又把`yarn.lock`还原，把相关依赖降级回`0.27.9`后`build`也没问题了。

volar看来不能随便升级。

**Comment by tjx666** [comment]
@Fallsleep  你这个问题我也碰到了，不过我把 node_modules 手动删除以后重新 pnpm install 就没有这个问题了

**Comment by J-env** [comment]
![image](https://user-images.githubusercontent.com/25259920/132440817-5885fba3-7cc0-4892-b23e-f8a4f1b76127.png)
@rashagu 目前这样解决的

**Comment by Nakus0426** [comment]
4.3版本的typescript才不会报错
