### ISSUE TITLE
ASwitch onchange event handler params type define incorrect

### ISSUE THREAD

**Issue by daiwanxing** [vueComponent/ant-design-vue#4615]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
windows10, chrome 92, vue 3.2

### Reproduction link
[https://github.com/daiwanxing/issue-repo](https://github.com/daiwanxing/issue-repo)

### Steps to reproduce
1. 在JSX中使用ASwitch组件
2. 给ASwitch组件onChange事件注册一个回调函数， 回调函数中定义了一个形参，该形参被ts推断成了any类型，而不是CheckedType类型

### What is expected?
应该被正确推断为CheckedType类型

### What is actually happening?
实际该形参被推断成了any类型

**Comment by daiwanxing** [comment]
![image](https://user-images.githubusercontent.com/37327614/132092319-3e753975-f232-49fa-94a6-b334682dc69d.png)
由于最后一个onChange的类型定义将所有的参数定义为any，类型交叉后，导致不能被正确推断对应的参数类型了

**Comment by tangjinzhou** [comment]
@Amour1688 props emits  同时声明了事件，合并规则是否可以调整
