### ISSUE TITLE
Modal.confirm content create Input and change value not updates

### ISSUE THREAD

**Issue by sendya** [vueComponent/ant-design-vue#4627]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
Windwos11, Edge 89, Vue3.2, AntDesignVue2.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-babbage-02cwv?file=/src/App.vue)

### Steps to reproduce
use...

```vue
    const dataRef = ref("123");

    const onClick = () => {
      Modal.confirm({
        title: "填写一个新的值",
        content: createVNode(Input, {
          value: dataRef.value,
          onChange: (e) => {
            dataRef.value = e.target.value;
          },
        }),
      });
    };
```

### What is expected?
Input  value not update

### What is actually happening?
Input value updated

**Comment by tangjinzhou** [comment]
你这个场景其实应该直接写在模板里啊

**Comment by 497013661** [comment]
![Image_20210909102426](https://user-images.githubusercontent.com/19503721/132612194-0539d95e-ae02-49fe-aa19-ca08fa0a77f1.png)
![Image_20210909102336](https://user-images.githubusercontent.com/19503721/132612208-620e0d8c-d472-42ae-b253-43b716c6446e.png)
title?: () => VNodeTypes | VNodeTypes;
这里的ts 都必须使用 ()=>{return  **  } 返回吗?

**Comment by sendya** [comment]
@497013661 

title: () => msgData.title

**Comment by lx-Inuyasha** [comment]
TS2322: Type 'string' is not assignable to type '() => VNodeTypes'.

title、content类型校验无法判断string?

**Comment by tangjinzhou** [comment]
类型要优化下

**Comment by liulei92** [comment]
是我理解的有问题吗
() => VNodeTypes | VNodeTypes ，这个类型就是函数返回 VNodeTypes | VNodeTypes ？确定不是类型写错了？？

**Comment by lx-Inuyasha** [comment]
> 是我理解的有问题吗
> () => VNodeTypes | VNodeTypes ，这个类型就是函数返回 VNodeTypes | VNodeTypes ？确定不是类型写错了？？

前面那个是方法，返回值为VNodeTypes，类型要求没错。但是校验上有问题

**Comment by yuanfangCBC** [comment]
所以？请问这个是怎么解决的啊。。

**Comment by inkn** [comment]
```
  Modal.confirm({
        title: "填写一个新的值",
        content: createVNode(Input, {
          defaultValue: dataRef.value,
          onChange: (e) => {
            dataRef.value = e.target.value;
          },
        }),
      });
```
value 改为 defaultValue 即可
