### ISSUE TITLE
Can select multiple force one line to be displayed?

### ISSUE THREAD

**Issue by mrdznet** [vueComponent/ant-design-vue#4633]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在 select multiple 如果选项宽度大于 input宽度，就会自动换行，能否强制1行显示？

可以参考  ele select 的  collapse-tags 功能

### What does the proposed API look like?
可以参考  ele select 的  [collapse-tags 功能](https://element-plus.gitee.io/?from=thosefree.com#/zh-CN/component/select-v2#yin-cang-duo-yu-biao-qian-de-duo-xuan)

**Comment by zkwolf** [comment]
你把maxTagCount设成1就是一样的效果了吧

**Comment by tangjinzhou** [comment]
maxTagCount = 'responsive'
