### ISSUE TITLE
After the table component updates the data, the sorting cannot be switched normally

### ISSUE THREAD

**Issue by cansonzheng** [vueComponent/ant-design-vue#4634]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
3.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hidden-tdd-lmvcu?file=/src/App.vue)

### Steps to reproduce
点击两次以上的排序

### What is expected?
排序应该要能正常切换

### What is actually happening?
在表格 data-source 属性的值发生变化后，排序操作就无法切换。
同样，表格 loading 属性的值发生变化之后，也会造成这样的结果。

**Comment by zkwolf** [comment]
你这demo没复现出来啊

**Comment by cansonzheng** [comment]
> 你这demo没复现出来啊
您重新看一遍。我也是后来才发现的，通过属性设置列没问题，使用组件列才会出现这个问题
