### ISSUE TITLE
是不是少了components/test/index.vue这个文件？

### ISSUE THREAD

**Issue by Mar-Max** [vueComponent/ant-design-vue#464]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
OS 10.14.2

### Reproduction link
[http://0.0.0.0:3001/](http://0.0.0.0:3001/)

### Steps to reproduce
执行npm run dev

### What is expected?
正确编译

### What is actually happening?
ERROR in ./site/dev.js
Module not found: Error: Can't resolve '../components/test/index.vue' in '/Users/kmf/Documents/works/others/ant-design-vue/site'
报错

**Comment by tangjinzhou** [comment]
`npm start`
