### ISSUE TITLE
Dynamic form validation is invalid

### ISSUE THREAD

**Issue by douhua-d** [vueComponent/ant-design-vue#4644]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
vue3

### Reproduction link
[https://blog.csdn.net/Dou_Hua6/article/details/120244528](https://blog.csdn.net/Dou_Hua6/article/details/120244528)

### Steps to reproduce
链接

### What is expected?
解决动态添加表单校验

### What is actually happening?
解决动态添加表单校验

**Comment by apubascao** [comment]
hello, i have a question regarding dynamic form validation 
![Screen Shot 2021-09-23 at 12 25 34 PM](https://user-images.githubusercontent.com/13758107/134454462-f9797fd4-c18e-4fee-a3dc-d3fc5dd14088.png)

validating Input is working but it seems that validating Select is not working, i added required rule to `a-form-item`:
```
{
  required: true,
  message: 'Please select role',
  trigger: 'change'
}
```
but it keeps showing the error even if it has a value
