### ISSUE TITLE
The problem of preview failure in upload component

### ISSUE THREAD

**Issue by ChenChienhang** [vueComponent/ant-design-vue#4651]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
os: windons 19042.1165, browser:Google Chrome 93.0.4577.63, Vue: 3.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-bas-01o1m?file=/src/App.vue)

### Steps to reproduce
在upload组件中，`fileList`设为`v-model`，然后按照文档中的示例可以进行图片预览，但是有时候可能需要对上传的图片进行操作（例如裁剪）,然后在赋值进去`fileList`，当希望手动控制filelist（取消`v-model`)，并在`beforeUpload`获取图片文件进行裁剪后再手动赋进`fileList`时预览图片失败了。（在提供的reproduction中仅仅是在`beforeUpload`中进行`fileList`的赋值貌似就已经不能预览了）

### What is expected?
有无方法解决上述的手动控制flieList预览问题

### What is actually happening?
手动控制fileList时图片预览失败

**Comment by tangjinzhou** [comment]
参考这个示例  https://2x.antdv.com/components/upload-cn/#components-upload-demo-transform-file

beforeUpload 的意思是上传之前的回调，此时还没有文件，复制给 fileList 的是一个没有文件的 file
