### ISSUE TITLE
when a-Upload component upload file ,status always "uploading"

### ISSUE THREAD

**Issue by 418545106** [vueComponent/ant-design-vue#4652]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
chrome  93.0.4577.63

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-dust-hytd7)

### Steps to reproduce
<a-upload
name="file"
list-type="picture-card"
:file-list="fileList"
:customRequest="upload"
@preview="handlePreview"
@change="handleChange"
>
<a-icon type="plus" />
</a-upload>
...
//method
upload (data) {
data.onSuccess()
},
handleChange ({ fileList }) {
this.fileList = fileList
}
![image](https://user-images.githubusercontent.com/29942834/133093062-9ab4cad2-d21f-422f-bdfe-bbe4cc22706c.png)

### What is expected?
when data.onSuccess() is invoke file status should be done.

### What is actually happening?
file status always uploading

**Comment by tangjinzhou** [comment]
You can refer to the example of react customRequest
https://github.com/react-component/upload/blob/master/docs/examples/customRequest.tsx
