### ISSUE TITLE
According to the introduction of the official document custom theme chapter, the importing of antd.less compilation error

### ISSUE THREAD

**Issue by jianglei81** [vueComponent/ant-design-vue#4654]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
windows-10, chrome-92, vue-3.2.11, vue-cli-4.5.13, webpack-4.0.0, less-loader-7.3.0, less-4.1.1

### Reproduction link
[https://github.com/jianglei81/antd-sample.git](https://github.com/jianglei81/antd-sample.git)

### Steps to reproduce
按照 https://2x.antdv.com/docs/vue/customize-theme-cn 文档介绍进行编写
1.在css文件中@import '~ant-design-vue/dist/antd.less'，尚未引入其它less文件
2.执行vue-cli的构建

### What is expected?
编译通过，构建成功

### What is actually happening?
./node_modules/ant-design-vue/lib/tree/style/index.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./node_modules/ant-design-vue/lib/tree/style/index.less)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(11:1) Unknown word

   9 | @tree-node-padding: 4px;
  10 | 
> 11 | .antCheckboxFn(@checkbox-prefix-cls: ~'@{ant-prefix}-tree-checkbox');
     | ^
  12 | 
  13 | .@{tree-prefix-cls} {

---
控制台还报出很多其它Unknown word错误，本质上应该一样，没有在此列出了
在css文件中@import '~ant-design-vue/dist/antd.css';不会出错；另外，在vue.config.js文件中配置css节点的方式也无法让定制生效
修改less-loader版本从v7.x到v5.x，less版本从v4到v3，各种版本组合，问题都一样

**Comment by tangjinzhou** [comment]
css 文件只能引 css
less 文件要用 less 文件引入

**Comment by jianglei81** [comment]
> css 文件只能引 css
> less 文件要用 less 文件引入

非常感谢，通过在main.js中直接import less文件解决了这个问题。建议官方文档中对此稍作说明，官方文档目前说的是用 @import导入less文件，@import在less文件和css文件中才能使用的，在js文件中只能用import，官方文档中说用@import就让我这种新手误解要到css文件里去导入了。
