### ISSUE TITLE
Clicking on a component with a drop-down content in a global component created using Vue.extend will cause the parent component to re-execute created

### ISSUE THREAD

**Issue by sqaiyan** [vueComponent/ant-design-vue#4657]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.7

### Environment
windows10,chrome91.*,vue 2 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-k0eng?file=/src/test.js)

### Steps to reproduce
1.写一个普通组件./test.vue，内部引入a-select或a-datepicker
2.写一个全局方法./test.js/$test()，内部为渲染该组件
3.调用方法
4.点击组件内下拉框或时间选择组件，

### What is expected?
带有下拉内容的组件点击显示内容时不影响外部组件

### What is actually happening?
点击显示下拉内容时会触发组件的created方法

---
该组件当作一个普通的component引入时不会出现此情况

**Comment by tangjinzhou** [comment]
不要用 extend  应该就没问题
