### ISSUE TITLE
Autocomplete inside Form cannot be reset

### ISSUE THREAD

**Issue by 0biWanKenobi** [vueComponent/ant-design-vue#4663]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
windows, chrome 93.0.4577.82, Vue 3.2.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ehsz8)

### Steps to reproduce

- Create a form and place an autoselect within, using Antd Vue components.
- Create a button that calls a function to clear the form.
- Select an option from the autoselect.
- Try to clear the form by clicking the button.

### What is expected?
The autocomplete value is reset to default.

### What is actually happening?
The form state object is reset, but the UI is not. The autocomplete still shows the value that the user selected.

---
You can also observe that other types of form items can be reset correctly. See the text input in the reproduction.

**Comment by zkwolf** [comment]
741718a0f92c790266e7a07d8d129c5673344a7e wait for next release.
