### ISSUE TITLE
dropdown to choose whether to destroy popup boxes when closing

### ISSUE THREAD

**Issue by wy916787036** [vueComponent/ant-design-vue#4666]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Built multiple right-click menus, if each one is clicked, there will be many pop-up boxes that are not destroyed

### What does the proposed API look like?
destroyPopupOnHide: Boolean

**Comment by tangjinzhou** [comment]
we can add it to 3.0 @ajuner
