### ISSUE TITLE
An error in the "Allow-Clear" attribute of the INPUT component under the IE browser.

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [vueComponent/ant-design-vue#4679]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue 2.6 IE 11 Windows10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-forked-qgdms?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Join the ALLOW-CLEAR attribute in the input Form form, then enter the value click to clear the icon, it will report an error: "Error IN V-ON Handler:" TypeError: Strict Strict Strict mode does not allow allocation to read-only properties "" Make sure to be in the IE11 version

### What is expected?
Clear content in Input

### What is actually happening?
I feel that everything is normal, I don't know what happened.

**Comment by ajuner** [comment]
Fixed in the next version
