### ISSUE TITLE
Table record undefined

### ISSUE THREAD

**Issue by vKarter** [vueComponent/ant-design-vue#468]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q3m0r4rk1)

### Steps to reproduce
https://codesandbox.io/s/3q3m0r4rk1

### What is expected?
record should be fill correctly

### What is actually happening?
Table record undefined in slot-scoped

**Comment by tangjinzhou** [comment]
please use vue 2.5.x

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/vue/issues/9468

**Comment by vxhly** [comment]
楼主的 vue 版本已经是 2.5.x 了，最近我也是发现这个问题的，我的vue版本号是 2.5.21

**Comment by tangjinzhou** [comment]
^2.5.x is not necessarily 2.5.x, please refer to the npm version rules for the version rules. @vxhly

**Comment by tangjinzhou** [comment]
fixed in 2.6.5
