### ISSUE TITLE
keepAlive does not take effect

### ISSUE THREAD

**Issue by xiaobo1215** [vueComponent/ant-design-vue#4683]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
keepAlive  不生效

### Reproduction link
[https://preview.pro.antdv.com/form/advanced-form](https://preview.pro.antdv.com/form/advanced-form)

### Steps to reproduce
keepAlive  不生效

### What is expected?
keepAlive  不生效

### What is actually happening?
keepAlive  不生效

---
keepAlive  不生效

**Comment by zkwolf** [comment]
pro的问题去pro提，这边只接收组件库的issue
