### ISSUE TITLE
The vue3x vite ts date component cannot be completely finished, especially where the month is

### ISSUE THREAD

**Issue by JHeLiu** [vueComponent/ant-design-vue#4684]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue 3.2.6

### Reproduction link
[https://gitee.com/misslius/ant-vue3-ts-date-bug.git](https://gitee.com/misslius/ant-vue3-ts-date-bug.git)

### Steps to reproduce
https://gitee.com/misslius/ant-vue3-ts-date-bug.git

### What is expected?
可以完全汉化

### What is actually happening?
没有完全汉化

---
github 推不上 所以建了个gitee仓库，github上面的方法全部试过了，都无法达到效果

**Comment by JHeLiu** [comment]
解决办法

不能安装  moment  ，如果已经有 moment  了，需要卸载，如果不行，把 node_modules 删除，删除 moment 然后初始化接口

```
//全局配置 这样解决
import locale from 'ant-design-vue/es/locale/zh_CN';
import moment from 'moment'
import 'moment/dist/locale/zh-cn'

```

可以关闭这个 issue

**Comment by tangjinzhou** [comment]
你可以自己关掉的
