### ISSUE TITLE
select use large memory when dropdownMatchSelectWidth="false"

### ISSUE THREAD

**Issue by qpxtWhite** [vueComponent/ant-design-vue#4685]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue 3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/da-shu-ju-ant-design-vue-next-forked-mqwbk)

### Steps to reproduce
copy the demo on docs，add :dropdownMatchSelectWidth="false"

### What is expected?
show the option dropdown quickly and smoothly

### What is actually happening?
page no response

**Comment by tangjinzhou** [comment]
`false` will disable virtual scroll

**Comment by tangjinzhou** [comment]
we will update doc for it
