### ISSUE TITLE
When moving the internal trigger of the Dropdown component, the position of the spring box is incorrect

### ISSUE THREAD

**Issue by IMLaoJI** [vueComponent/ant-design-vue#4686]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
window10 chrome92 vue3

### Reproduction link
[![Edit on CodeSandbox Vue version](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-https-06glo?file=/src/components/demo.js)

[![Edit on CodeSandbox React Version ](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blazing-microservice-q3px3)

### Steps to reproduce
Vue version error  https://codesandbox.io/s/distracted-https-06glo?file=/src/components/demo.js
React version right https://codesandbox.io/s/blazing-microservice-q3px3
when you focus And click input the inner trigger move.  

### What is expected?
When using a drop-down box component, the code moves the position of an internally triggered component (such as input) via the JS DOM API (such as swapping to siblings). The position of the drop-down box does not follow dynamically, as with the React version of the drop-down box component

### What is actually happening?
When using a drop-down box component, the code moves the position of an internally triggered component (such as input) via the JS DOM API (such as swapping to siblings). The position of the drop-down box does not follow dynamically, as with the React version of the drop-down box component

---

vue version https://codesandbox.io/s/distracted-https-06glo?file=/src/components/demo.js

react version https://codesandbox.io/s/blazing-microservice-q3px3

**Comment by tangjinzhou** [comment]
啥玩意，咋还操作 dom   不要操作dom，数据驱动

**Comment by IMLaoJI** [comment]
> 啥玩意，咋还操作 dom 不要操作dom，数据驱动

我这个例子是demo，具体场景有几十个div，我需要监控键盘操作，动态将dropdown内部的input 放在在相应的div之间，使用React Ant Design 效果是正常的，vue中应该如何实现

**Comment by tangjinzhou** [comment]
试试 3.0 吧    动态添加也不需要操作dom啊，直接  v-if v-show

**Comment by IMLaoJI** [comment]
> 试试 3.0 吧 动态添加也不需要操作dom啊，直接 v-if v-show

我试试3.0，主要div数量可增可减和dropdown的位置随时都需要变化，使用v-if有点难实现，我试下能不能把div和dropdown用数据动态驱动试试
