### ISSUE TITLE
The attribute maxtagtextlength of the component select selector in version 2.2.8 has no effect

### ISSUE THREAD

**Issue by Johnharvy** [vueComponent/ant-design-vue#4690]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
node 14   / chrome

### Reproduction link
--

### Steps to reproduce
--

### What is expected?
The attribute maxtagtextlength of the component select selector  has effected

### What is actually happening?
no effect

**Comment by tangjinzhou** [comment]
提供下复现示例    试了下没问题

**Comment by IMLaoJI** [comment]
> 提供下复现示例 试了下没问题

老大，能看下我提的那个issue吗，是不是我英文没描述清楚

**Comment by lerry521** [comment]
版本号2以上，设置这个maxTagTextLength不起作用
