### ISSUE TITLE
Custom class DO NOT append after original classes of ant-desgin-vue

### ISSUE THREAD

**Issue by ince01** [vueComponent/ant-design-vue#4692]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
nuxt@^2.15.8, ant-design-vue@^1.7.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-p1tr6?file=/src/App.vue)

### Steps to reproduce
- Use `a-select` component
- Add `custom-class` into class attribute of `a-select`

### What is expected?
After rendering into HTML, the `custom-class` string must be added after the classes of `a-select` component.
Example:

```html
<div class="ant-select ant-select-enabled custom-class">
...
</div>
```

### What is actually happening?
But the `custom-class` string has been append before the classes of `a-select` component.
Like this:

```html
<div class="custom-class ant-select ant-select-enabled">
...
</div>
```

---
This behaviour prevented override the styles of components, so I can't use ant-design-vue components with tailwindcss 😥

**Comment by tangjinzhou** [comment]
😓    so you should to learn css.   
class="a b"  and class="b a"  is exactly equal.
