### ISSUE TITLE
When the table component uses a fixed column, it cannot be scrolled when the amount of data is large

### ISSUE THREAD

**Issue by 2wsk3** [vueComponent/ant-design-vue#4706]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
window7   Google Chrome 93.0.4577.82    vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-u7x19?file=/src/App.vue)

### Steps to reproduce
表格列设置固定，表格设置大量数据，无法滚动，滚动时卡死

### What is expected?
能够正常滚动

### What is actually happening?
界面卡死，无法滚动，取消固定列属性（fixed）后恢复正常

**Comment by tangjinzhou** [comment]
1.x 请使用分页表格
