### ISSUE TITLE
Body has overflow-x: hidden in destroyed drawer

### ISSUE THREAD

**Issue by Nisgrak** [vueComponent/ant-design-vue#4710]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Vue 3.2.19

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-next-forked-bkuce)

### Steps to reproduce
1. Ensure that the table of the example have horizontal scroll
2. Open the drawer
3. Close the drawer
4. The table don't have horizontal scroll

### What is expected?
The table has horizontal scroll when the drawer with `destroy-on-close` active is destroyed

### What is actually happening?
The body have a `overflow-x: hidden` that the destroyed drawer didn't remove

**Comment by ajuner** [comment]
V3 will fix it, you can pay attention to this https://github.com/vueComponent/ant-design-vue/pull/4708

Temporary solution
```
const afterVisibleChange = (bool: boolean) => {
  if (!bool) {
    document.body.style.removeProperty("overflow");
  }
};
```

**Comment by ajuner** [comment]
ref [3.0.0-alpha.1](https://github.com/vueComponent/ant-design-vue/releases/tag/3.0.0-alpha.1)
