### ISSUE TITLE
The Chinese and English structures of internationalized multilingual translation files are not symmetrical, resulting in an error in the TS development mode, and there is no way to switch languages

### ISSUE THREAD

**Issue by ouyang434** [vueComponent/ant-design-vue#4713]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.0

### Environment
Vue(^3.0.0) ts(~4.1.5) antd（^2.2.8）

### Reproduction link
[https://5pyhl.csb.app/](https://5pyhl.csb.app/)

### Steps to reproduce
例如：monthBeforeYear这个变量，在英文翻译文件中有，但是在中文翻译文件中就没有

### What is expected?
统一翻译文件格式

### What is actually happening?
在引入组件进行国际化语言切换的时候，因翻译文件结构不一致，导致TS环境编译不通过，项目没办法运行

**Comment by tangjinzhou** [comment]
试试升级  ts    还有明确你的版本号  不要用 ^ ~ ，我们需要知道具体版本号     还有确认你这 Reproduction link 可以复现你的问题？

**Comment by ouyang434** [comment]
这个Reproduction link 之前是会报错的，但是现在没有报错了。应该是问题解决了。另外在之前结构不一致的情况下，换一种写法就行：
 const antdLocal = computed(() => {
      const localMap = {
        ["zh"]: zhCN,
        ["en"]: enUS,
      };
      return localMap[state.locale];
    });
