### ISSUE TITLE
After antd-table deletes the data of the last page, the current page number of the pagenation will be updated, but the change event of the table is not triggered

### ISSUE THREAD

**Issue by PanClear** [vueComponent/ant-design-vue#4718]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Vue version

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/new/choose](https://github.com/vueComponent/ant-design-vue/issues/new/choose)

### Steps to reproduce
1、使用a-table组件，通过http请求获取某一页的数据，列表数据大于一页
2、翻到最后一页（第二页），http请求删除最后一页的数据，然后再次获取该页的数据

### What is expected?
删除数据后更新分页配置的total，分页器的页码更新，自动往前翻了一页，此时应该触发绑定的change事件，那么我会按新的页码更新分页信息并查询列表数据

### What is actually happening?
删除数据后更新分页配置的total，分页器的页码更新，自动往前翻了一页，但是绑定的change事件并没有触发，分页器看起来当前页是变成了第一页。

**Comment by tangjinzhou** [comment]
change 事件是你去操作翻页、过滤等操作导致分页配置变化才会触发，这就像输入框，你直接键盘输入会触发change，但你直接更改绑定的value却不触发，是一样的道理

你可以自行配置分页属性，达到完全受控的状态
