### ISSUE TITLE
Warning: `getFieldDecorator` will override `value`

### ISSUE THREAD

**Issue by bowencool** [vueComponent/ant-design-vue#472]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Vue SSR:
Vue 2.6.6
Chrome 71.0.3578.98（正式版本） （64 位）
Node 10.15.1

### What is expected?
no warning

### What is actually happening?
控制台报错：(Node和Chrome均有出现，jsx写法没有问题)
```
Warning: `getFieldDecorator` will override `value`, so please don't set `value and v-model` directly and use `setFieldsValue` to set it.     browser.js:49 
```
我根本就没写v-model/value：
```
<a-form-item>
  <a-textarea
    style="padding: 32px;"
    placeholder="请填写20字以上的意见或建议，以便我们提供更好的服务"
    :autosize="{ minRows: 6 }"
    v-decorator="['content', {
      rules: [{
        required: true,
        min: 20,
        message: '请填写20字以上',
      }, {
        max: 500,
        message: '500字以内',
      }],
      validateTrigger: 'blur'
    }]"
  ></a-textarea>
</a-form-item>
```

**Comment by tangjinzhou** [comment]
没能复现，方便的话基于 https://codesandbox.io/s/2wpk21kzvr 提供下复现demo

**Comment by bowencool** [comment]
没能复现
