### ISSUE TITLE
Tag tag dynamic delete data bug

### ISSUE THREAD

**Issue by zhuxianglong** [vueComponent/ant-design-vue#4721]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue3

### Reproduction link
[https://2x.antdv.com/components/tag-cn](https://2x.antdv.com/components/tag-cn)

### Steps to reproduce
动态删除tag会把后面的数据删除掉,先添加两个Tag,在删除第一个Tag

### What is expected?
希望和vue2或者react版本使用一样

### What is actually happening?
没有真实删除或者会删除后面的Tag

**Comment by tangjinzhou** [comment]
参考这个改就好了   文档示例有错误 https://github.com/vueComponent/ant-design-vue/commit/1228e1d6046e6f2df451211c44f3e77018153871
