### ISSUE TITLE
colorPalette is not defined when use theme

### ISSUE THREAD

**Issue by fengyeall111** [vueComponent/ant-design-vue#4724]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
win10 vite2 vue3 vscode

### Reproduction link
[https://github.com/ant-design/ant-design/pull/26395/](https://github.com/ant-design/ant-design/pull/26395/)

### Steps to reproduce
vite2创建vue3 spa应用，页面@import '~ant-design-vue/dist/antd.less'时报错，
<style lang='less'>
@import 'ant-design-vue/dist/antd.dark.less';
@import './assets/global.less';
</style>

### What is expected?
样式正确引入

### What is actually happening?
出错情况如下：
// It is hacky way to make this function will be compiled preferentially by less
// resolve error: `ReferenceError: colorPalette is not defined`
// https://github.com/ant-design/ant-motion/issues/44
，ant-design里面也有

---
ant-design里面出现过这个issue，ant-design-vue里面没有修复这个问题吗？
https://github.com/ant-design/ant-design/pull/26395/

**Comment by sendya** [comment]
要安装 less 你安装了吗？ 要启用 less 的 javascriptEnabled 你启用了吗？

**Comment by fengyeall111** [comment]
> 
> 
> 要安装 less 你安装了吗？ 要启用 less 的 javascriptEnabled
vite自动加载less，只需要安装对应插件。没有启用 javascriptEnabled，非常感谢。
