### ISSUE TITLE
Warning: `Form.Item` cannot generate `validateStatus` and `help` automatically, while there are more than one `getFieldDecorator` in it.

### ISSUE THREAD

**Issue by bowencool** [vueComponent/ant-design-vue#473]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Vue SSR:
Vue 2.6.6
Chrome 71.0.3578.98（正式版本） （64 位）
Node 10.15.1

### What is expected?
这是正常需求啊，感觉没必要报这个错

### What is actually happening?
控制台报错：
```
browser.js:49 
Warning: `Form.Item` cannot generate `validateStatus` and `help` automatically, while there are more than one `getFieldDecorator` in it. 
```

**Comment by tangjinzhou** [comment]
只是提醒

**Comment by bowencool** [comment]
可是他是红色的😂

**Comment by masquevil** [comment]
+1，一般我们要求以 0 warning 的原则开发，但是正常需求在 console 里报个 error 类型的 warning 真的很影响

**Comment by uniquejava** [comment]
后来是怎么解决的 @masquevil  @tangjinzhou  应该怎么消除啊

**Comment by yuanyayi** [comment]
警告FormItem中有两个组件存在v-decorator，无法配置自动校验。可以选择删除外层的FormItem，或者在其中套入两个FormItem分开两个组件。可以参考这个issue: [5052](https://github.com/ant-design/ant-design/issues/5052)
