### ISSUE TITLE
Tree Transfer Check question

### ISSUE THREAD

**Issue by FC0511** [vueComponent/ant-design-vue#4731]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
win10、谷歌92.0.4515.131（正式版本）、vue2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-worker-2zdy9?file=/src/components/HelloWorld.vue)

### Steps to reproduce
![https://image-static.segmentfault.com/662/188/66218821-615cf367d9969](https://image-static.segmentfault.com/662/188/66218821-615cf367d9969)

我把官网这个案例的树改成支持父节点选择之后子节点也能被选中（移除案例中的checkStrictly），但是通过父节点选择之后子节点无法取消选择了（其实已经被取消选中但是勾选状态没变）。

官方示例
https://www.antdv.com/components/transfer-cn/#components-transfer-demo-tree-transfer

步骤：
先勾选0-1，因为是联动的所以子节点也被选中了，然后取消勾选0-1-0（取消不掉），点击穿梭按钮，右侧的数据是对的（不包含0-1-0）

### What is expected?
树的勾选效果正常

### What is actually happening?
已经被取消选中但是勾选状态没变

**Comment by tangjinzhou** [comment]
使用受控模式  https://codesandbox.io/s/magical-mcclintock-0j8b0?file=/src/components/HelloWorld.vue
这个demo并不完善，仅供参考
