### ISSUE TITLE
I tried to use the customRequest operation to override the default operation of the upload component and get a list of duplicate pictures.

### ISSUE THREAD

**Issue by noecs** [vueComponent/ant-design-vue#4736]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Vue 3.1.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-glitter-cy86x?file=/src/App.vue)

### Steps to reproduce
我使用`Upload`组件进行上传，因为后端有签名相关，所以我使用`customRequest`覆盖`Upload`组件的默认上传配置。
我在`cutsomRequest`中进行自定义上传一张图片，上传之后的结果直接赋值给`fileList`。

### What is expected?
我的预期是，当我覆盖了`customRequest`，上传之后，修改`fileList`应该得到一个正确的图片列表。而不是我自定义的属性和Upload组件的File对象混杂的一个列表。

### What is actually happening?
在图片列表却展示出来两个。第一张为上传中的占位，第二张为上传成功的图片。

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/competent-proskuriakova-ys6gq?file=/src/App.vue

调用 res.onSuccess()

**Comment by noecs** [comment]
> https://codesandbox.io/s/competent-proskuriakova-ys6gq?file=/src/App.vue
> 
> 调用 res.onSuccess()

然而我尝试这个例子，依然出现了重复的图片列表。
![image](https://user-images.githubusercontent.com/23306366/136497475-8386f291-ab5c-4d4d-88c5-df96a0f7bef0.png)

**Comment by noecs** [comment]
> 你 push 一个，上传一个，那不就是两个吗 😓

老哥。这个不是应该在上传了之后，才给预览吗？这还没到上传完成就已经预览了，而且fileList里面两种对象混杂在一起...感觉有亿点点不妥。
