### ISSUE TITLE
The nested form-item error `getFieldDecorator` will override `value', so please don't set `value and v-model` direct and use `setFieldsValue` to set it.

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#474]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
windows, chrome 72 , vue 2.5 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lr9pz9v33m)

### Steps to reproduce
Vue single file nesting uses form-item

### What is expected?
I know exactly what I'm doing, expecting errors to disappear and async-validator: warnings to disappear

### What is actually happening?
There was a mistake.

        

---
嵌套组件内出现错误，我很清楚自己要做什么，有什么好的办法可以避免么，虽然不影响功能上的使用。

**Comment by tangjinzhou** [comment]
It is recommended that you do not nest it.
We will optimize for the next version.
You can do it like https://codesandbox.io/s/kkplmlrorr.

**Comment by bosens-China** [comment]
> It is recommended that you do not nest it.
> We will optimize for the next version.
> You can do it like https://codesandbox.io/s/kkplmlrorr.
---

Well, hopefully the next version will see that if you want the form to be displayed on one line, and each line can be validated independently, you can try flex.
``` JavaScript
<a-row>
<a-col:span="5">col-12</a-col>
<a-col:span="12">col-12</a-col>
</a-row>
` ` ` `
