### ISSUE TITLE
When Table fixed headers and fixed columns, the rows of the scrolling column and the rows of the fixed column cannot be aligned after zooming

### ISSUE THREAD

**Issue by KaygNas** [vueComponent/ant-design-vue#4740]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue@2.6.11

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header](https://www.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header)

### Steps to reproduce
1. Ctrl   鼠标滚动将浏览器缩放至 150%；
2. 发现滚动列的行与固定列的行未对齐；

### What is expected?
滚动列的行与固定列的行能够对齐；

### What is actually happening?
1. 固定头固定列时，为了消除固定头的 scrollBarWidthOfHeader，源码设置了负数的margin，因而初次渲染时表格的滚动区域行与固定列的行能够对齐；
2. 但是对浏览器进行缩放后，scrollBarWidthOfHeader 并没有被重新计算，因而导致行无法对齐；
3. 或许可以对缩放事件进行监听并重新计算 scrollBarWidthOfHeader 以解决此问题？

**Comment by tangjinzhou** [comment]
这个问题在 2.x 3.x 版本已经通过 sticky 方式修复

1.x 缩放导致的高度问题，你可以尝试 pr

**Comment by Timo534** [comment]
> 这个问题在 2.x 3.x 版本已经通过 sticky 方式修复
> 
> 1.x 缩放导致的高度问题，你可以尝试 pr

请问在2.x的哪一个版本修复的
