### ISSUE TITLE
How do SELECT components limit the number of choices

### ISSUE THREAD

**Issue by jerryzn** [vueComponent/ant-design-vue#4765]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Components are more flexible and user-friendly

### What does the proposed API look like?
有没有其他更的方法来实现？

**Comment by tangjinzhou** [comment]
try 3.0  next.antdv.com
