### ISSUE TITLE
Drawer is broken (mask not appear, only right drawer appear, ...)

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#477]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
mac OS / chrome / latest / vue:2.5.22

### Reproduction link
[https://github.com/Afondevi/vue-renter](https://github.com/Afondevi/vue-renter)

### Steps to reproduce
all is in the title.

Is use drawer and put option on it :

```
<a-drawer
title="Basic Drawer"
placement="bottom"
:closable="true"
:mask="true"
@close="onClose"
:visible="visible"
>
<p>Some contents...</p>
<p>Some contents...</p>
<p>Some contents...</p>
</a-drawer>
```

No Mask, and if placement is not right, nothing appear.

### What is expected?
all word..

### What is actually happening?
Nothing appear when not right placement
For right placement working, don't have mask

**Comment by wangxueliang** [comment]
The code you provided is ok, and the official website(https://vuecomponent.github.io/ant-design-vue/components/drawer/) also has a corresponding examples, you can refer to it.

ps: It is best to provide a recurring link, similar (https://codesandbox.io/s/2wpk21kzvr)

**Comment by Afondevi** [comment]
https://codesandbox.io/s/l28lkyr98z

But my project no working on codesandbox :/

**Comment by wangxueliang** [comment]
we are currently unable to go to troubleshoot the information you provided.

**Comment by tangjinzhou** [comment]
https://github.com/Afondevi/vue-renter  404 @Afondevi
