### ISSUE TITLE
Can you beautify the scroll bar component in the project

### ISSUE THREAD

**Issue by bzw1204** [vueComponent/ant-design-vue#4770]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1. 目前的滚动条样式风格实在跟整体UI框架不搭，感觉格格不入

### What does the proposed API look like?
希望是跟整体UI风格搭配的滚动条样式

**Comment by tangjinzhou** [comment]
https://segmentfault.com/a/1190000012800450
