### ISSUE TITLE
[1.x][FormModel] Rule type: 'number' and type: 'integer' are not working

### ISSUE THREAD

**Issue by sneakylenny** [vueComponent/ant-design-vue#4771]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
```
os: Windows 10 Pro;
browsers: all; 
vue-version: 2.6.14;
ant-design-vue: ^1.7.6;
```
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-number-validation-not-working-correctly-wz5mv)

### Steps to reproduce
1. Create a form based off of [docs](https://1x.antdv.com/components/form-model)
2. Create a rule where `type: 'number'` or `type: 'integer'`. Which should work according to [Antd Validation rules](https://1x.antdv.com/components/form-model/#Validation-Rules) and [yiminghe/async-validator](https://github.com/yiminghe/async-validator#type)
3. Enter a number/int in the field

### What is expected?
I expect the validation to pass when a number is entered

### What is actually happening?
The number is (probably) interpenetrated as string and validation shows an error telling me I didn't enter a valid number

---
I'm using v1.7.6 but it was not possible to select it.
I love your work, I'm a big fan of the clean style and usability! Keep it up!

**Comment by tangjinzhou** [comment]
please use a-input-number component
or
use rule.transform to change value before validate like https://codesandbox.io/s/vue-antd-number-validation-not-working-correctly-forked-m90d9?file=/src/App.vue

**Comment by 438413530** [comment]
remove the validate or validateTrigger in rules, and everything is ok!
