### ISSUE TITLE
How to work in Nuxt3

### ISSUE THREAD

**Issue by liaozheng-yi** [vueComponent/ant-design-vue#4783]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
nuxt3 latest  & ant-design-vue 2.2.8

### Reproduction link
[https://github.com/liaozheng-yi/nuxt3-antd-vue](https://github.com/liaozheng-yi/nuxt3-antd-vue)

### Steps to reproduce
Command "npx nuxi init nuxt3-app" to init project, install ant-design-vue, add ant-design.ts and set nuxt.config.ts like that git repository.

### What is expected?
work in nuxt3

### What is actually happening?
Error report: Cannot find module 'D:\*******\nuxt3-app\node_modules\@ant-design\icons-vue\ArrowLeftOutlined' imported from D:\*******\nuxt3-app\.nuxt\dist\server\server.mjs

---
I had follow the answer in https://github.com/nuxt/framework/discussions/1208  ,  but still meet error.

**Comment by nickliya** [comment]
+1

**Comment by Piocat** [comment]
I had meet same problems. This issue was closed. Did you find any methods to solve？

**Comment by wobsoriano** [comment]
https://github.com/vueComponent/ant-design-vue/discussions/5210

**Comment by wobsoriano** [comment]
I got it working. Check steps here https://github.com/vueComponent/ant-design-vue/discussions/5210

**Comment by TLovers** [comment]
按照这种方式导入后message 消息提示框全都不展示啊，有办法解决吗
