### ISSUE TITLE
 Computed property "post" was assigned to but it has no setter.

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#479]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
windows, chrome 72 , vue 2.5 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r7rn9j75vn)

### Steps to reproduce
Vue incorporates post calculation attributes to cause errors

### What is expected?
The error message is not prompted and does not affect the use of my method

### What is actually happening?
Computed property "post" was assigned to but it has no setter.

**Comment by tangjinzhou** [comment]
Has nothing to do with the component.
You should go to Vue to ask questions.
