### ISSUE TITLE
tree a-directory-tree cannot use the right-click menu

### ISSUE THREAD

**Issue by boerzhijinguoqiang** [vueComponent/ant-design-vue#4795]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-directory-tree无法使用右键菜单就很奇怪，我觉得这样的需求蛮多的，如：文件夹目录结构需要右键创建文件、删除文件夹等操作。

### What does the proposed API look like?
a-tree组件我看是支持的，期望 a-directory-tree也能有相同的使用方式

**Comment by zkwolf** [comment]
下个版本修复

**Comment by rysinal** [comment]
> 下个版本修复

大佬 1.7.8不是vue2.0的最后一个版本了么，好像没有在vue2.0里修复啊

**Comment by ouyangshikang** [comment]
这个问题修复后，没有发版吗？ @zkwolf @tangjinzhou  目前vue2 最新的1.7.8并没有看到
