### ISSUE TITLE
table横向滚动是否可以自动生成

### ISSUE THREAD

**Issue by t270173732** [vueComponent/ant-design-vue#480]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
chorme

### Reproduction link
[https://vuecomponent.github.io/ant-design-vue/components/table-cn/](https://vuecomponent.github.io/ant-design-vue/components/table-cn/)

### Steps to reproduce
数据超出页面区域是数据被隐藏了

### What is expected?
当数据超出页面显示自动生成横向滚动条

### What is actually happening?
现在必须通过属性设置x值来生成滚动条

**Comment by tangjinzhou** [comment]
参考 https://github.com/ant-design/ant-design/issues/14789

**Comment by rxy8023** [comment]
> 参考 [ant-design/ant-design#14789](https://github.com/ant-design/ant-design/issues/14789)

您解决了吗，antd-vue设置了max-content好像没有出现滚动条
