### ISSUE TITLE
必看常见问题

### ISSUE THREAD

**Issue by tangjinzhou** [vueComponent/ant-design-vue#481]
必看常见问题：https://vuecomponent.github.io/ant-design-vue/docs/vue/faq-cn/

必看、必看、必看

**Comment by meatbuns82** [comment]
ant-design-vue里抽屉里的信息预览抽屉里的 ./descriptionItem这个组件找不到，也没有提供入口，官方能否对一些自定义组件提供下载的方式或者入口?

**Comment by tangjinzhou** [comment]
@meatbuns82 你说的是pro吧  可以去pro的issue区提问

**Comment by sendya** [comment]
@meatbuns82 https://github.com/vueComponent/ant-design-vue/blob/master/components/drawer/demo/descriptionItem.vue

demo 里的，应该是这个？

**Comment by gaga-code** [comment]
为什么a-select组件的 :maxTagCount="10" 会无效，如果有1000多条数据的时候页面会卡顿，版本是1.4.10

<a-form-item label="客户" :labelCol="labelCol" :wrapperCol="wrapperCol">
            <a-select 
              placeholder="请选择客户" 
              v-decorator="[
                'fromunit',
                {
                  rules: [{ required: true, message: '请选择客户' }]
                }]"
              showSearch 
              optionFilterProp="children"  
              :maxTagCount="10"
              @change="selectCust">
              <a-select-option v-for="item in custList" :key="item.id" :value="item.id">
                {{ item.cuatomername }}</a-select-option>
            </a-select>
          </a-form-item>
![微信图片_20200304191857](https://user-images.githubusercontent.com/51053648/75874810-782e1480-5e4d-11ea-9446-fbb463578480.png)

**Comment by gaga-code** [comment]
为什么a-select组件的 :maxTagCount="10" 会无效，如果有1000多条数据的时候页面会卡顿，版本是1.4.10

```
<a-form-item label="客户" :labelCol="labelCol" :wrapperCol="wrapperCol">
            <a-select 
              placeholder="请选择客户" 
              v-decorator="[
                'fromunit',
                {
                  rules: [{ required: true, message: '请选择客户' }]
                }]"
              showSearch 
              optionFilterProp="children"  
              :maxTagCount="10"
              @change="selectCust">
              <a-select-option v-for="item in custList" :key="item.id" :value="item.id">
                {{ item.cuatomername }}</a-select-option>
            </a-select>
          </a-form-item>

```
