### ISSUE TITLE
Official website document Carousel revolving light Component Custom arrow How to use The arrow on the left is not displayed normally

### ISSUE THREAD

**Issue by n1203** [vueComponent/ant-design-vue#4821]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.6

### Environment
官方文档

### Reproduction link
[https://next.antdv.com/components/carousel-cn#components-carousel-demo-customArrows](https://next.antdv.com/components/carousel-cn#components-carousel-demo-customArrows)

### Steps to reproduce
阅读 时候发现

### What is expected?
阅读 时候发现

### What is actually happening?
阅读 时候发现

**Comment by no-pear** [comment]
这个问题怎么解决的呢 @n1203
