### ISSUE TITLE
The select component cannot be searched by label

### ISSUE THREAD

**Issue by tow-gorillajobs** [vueComponent/ant-design-vue#4836]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
vue 2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-babbage-pzq57?file=/src/App.vue)

### Steps to reproduce
**1. optionFilterProp 无效
```html
//搜索无效 并报错 Cannot read properties of undefined (reading 'length')
<a-select mode="multiple" :options="options" v-model="data" option-filter-prop="label"></a-select>
```

**2. filterOption 无效
```html
filterOption(input, option) {
// option 为VNode对象 仅能从option.data.props.value拿到value 拿不到 label字段
console.log(option)
return option.label.indexOf(input) >= 0
}
```

### What is expected?
可以按label搜索选项

### What is actually happening?
设置optionFilterProp="label"或者filterOption无效

---
在issues搜到提问者但未得到解决就关闭了issues，希望可以解决

**Comment by zkwolf** [comment]
可以考虑options用`{ title: "张三", value: 1 }` title代替label，option-filter-prop用title，或者用v-for初始化数据

**Comment by tao-bitbulk** [comment]
感谢，换成title可以了，文档上两处对于options描述有点冲突。
- Select props （看似label必传）
![1](https://user-images.githubusercontent.com/90334474/139999014-92fffff2-cc26-41bc-a299-a0259eb277f0.jpg)

- Option props （没有label）
![2](https://user-images.githubusercontent.com/90334474/139999024-1579eba7-fb4d-40fa-a28c-1631f95a5d0a.jpg)
