### ISSUE TITLE
message 组件在文档中没有导入方法

### ISSUE THREAD

**Issue by newpepsi** [vueComponent/ant-design-vue#484]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
message 组件文档中没有导入方法实测为
import {message} from 'ant-design-vue'
并且组件中不支持
this.$message写法

### What does the proposed API look like?
在文档中标明 import 方式 注意大小写风格统一。

**Comment by wangxueliang** [comment]
有哈， https://vue.ant.design/docs/vue/getting-started-cn/

**Comment by newpepsi** [comment]
> 
> 
> 有哈， https://vue.ant.design/docs/vue/getting-started-cn/

是组件文档。不是入门章节

**Comment by newpepsi** [comment]
https://vue.ant.design/components/message-cn/

**Comment by tangjinzhou** [comment]
欢迎pr @newpepsi

**Comment by newpepsi** [comment]
@tangjinzhou 没找到哪里改这个文档
