### ISSUE TITLE
Select cannot be fully controlled, but Input is possible

### ISSUE THREAD

**Issue by ZenDay** [vueComponent/ant-design-vue#4848]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.1.4

### Environment
OSX Mojave 10.14.6/Chrome 86, Vue 3.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-wescoff-b9mqe)

### Steps to reproduce
Select 通过 :value 和 @change 来试图让其受控。

### What is expected?
Select 应该与 Input 表现类似，在使用了 :value 和 @change 时完全受控。
Input 如果在 @change 中没有变更绑定的 value 值，展示的仍然是变更前的值

### What is actually happening?
在 @change 并没有变更 value 值的情况下，Select 仍然展示的是变更后的值。

---
如果这是 select 的特性，我应该如何让 select 完全受控呢？

**Comment by tangjinzhou** [comment]
试试 3.0
已经在 3.0 修复了

**Comment by tangjinzhou** [comment]
或者试试这种方式 https://codesandbox.io/s/keen-butterfly-zwy66?file=/src/App.vue

**Comment by ZenDay** [comment]
1. 3.0 有一定升级成本，可能不考虑升级；
2. 已经使用了  https://codesandbox.io/s/keen-butterfly-zwy66?file=/src/App.vue 的方式，目前来看没什么问题。
