### ISSUE TITLE
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto

### ISSUE THREAD

**Issue by ysaakpr** [vueComponent/ant-design-vue#485]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

Fix for can be made now available

https://github.com/ant-design/ant-design/issues/14306

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://ant-design-vue.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by tangjinzhou** [comment]
#471 
A new version will be released this week.
