### ISSUE TITLE
Missing tag info in `web-type.json`

### ISSUE THREAD

**Issue by billychennn** [vueComponent/ant-design-vue#4860]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
IDE: Webstorm

### Reproduction link
[https://unpkg.com/browse/ant-design-vue@2.2.8/vetur/web-types.json](https://unpkg.com/browse/ant-design-vue@2.2.8/vetur/web-types.json)

### Steps to reproduce
1. check this [link](https://unpkg.com/browse/ant-design-vue@2.2.7/vetur/web-types.json) and we can see info of `a-xxx` tags.
2. toggle `Version` to `v2.2.8` and we can see these info disappear.

### What is expected?
`web-types.json` can still have those info so that Webstorm can recognize tags of an-design-vue.

### What is actually happening?
So many warning msg on Webstorm camplaining about "Unknown html tag a-xxxx" due to missing typing.

---
some issue in v3.x

**Comment by aov2005** [comment]
我也是，现在不得不回退版本

**Comment by yzy9527** [comment]
走了走了，去饿了吗plus

**Comment by wxlzmt** [comment]
2.2.7 正常，详见 https://unpkg.com/browse/ant-design-vue@2.2.7/vetur/web-types.json

2.2.8 的 "tags" 是空的 ， 详见 https://unpkg.com/browse/ant-design-vue@2.2.8/vetur/web-types.json
