### ISSUE TITLE
 Failed to resolve component: a-tree-select-node 

### ISSUE THREAD

**Issue by Eyran** [vueComponent/ant-design-vue#4862]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue3，windo10 64位，Chrome 版本 95.0.4638.69

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
根据文档使用TreeSelect 显示该问题

### What is expected?
能正常使用

### What is actually happening?
runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: a-tree-select-node
at <AuthModal modal= {show: false, id: 0, title: '添加', formsRef: {…}, operationTimestamp: undefined} visible=false width=600  ... >
at <PageWrapper>
at <Auth onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/rabc/auth" >
at <KeepAlive key=0 include= (2) ['Welcome', 'auth'] >
at <BaseTransition mode="out-in" appear=true persisted=false  ... >
at <Transition name="fade-slide" mode="out-in" appear="" >
at <RouterView>
at <PageLayout>
at <LayoutContent>
at <Anonymous prefixCls="ant-layout" hasSider=undefined tagName="section"  ... >
at <ALayout class="eis-default-layout-main" >
at <Anonymous prefixCls="ant-layout" hasSider=undefined tagName="section"  ... >
at <ALayout class="" >
at <Anonymous prefixCls="ant-layout" hasSider=undefined tagName="section"  ... >
at <ALayout class="eis-default-layout" >
at <DefaultLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
at <RouterView>
at <AppProvider>
at <ALocaleProvider locale=undefined ANT_MARK__="internalMark" >
at <LocaleReceiver children=fn<children> >
at <AConfigProvider locale=null >
at <App>

**Comment by tangjinzhou** [comment]
app.use(Tree)

**Comment by Eyran** [comment]
> app.use(Tree)

不是的，在vben-admin中使用 文档的 <a-tree-select></a-tree-select> 标签无法解析，使用 import 引入 TreeSelect 组件之后，在使用 <tree-select></tree-select> 就可以渲染出来。

**Comment by ricarduuu** [comment]
放弃吧 最近遇到大量数据场景，2版本没有虚拟滚动，treeselect点击 checkbox会有500ms延迟 v3版本100ms延迟，
同样的element-plus只有5ms 真的是奇迹
