### ISSUE TITLE
When will the problem of component type be dealt with?

### ISSUE THREAD

**Issue by agileago** [vueComponent/ant-design-vue#4863]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
mac, chrome95,vue3,webstorm

### Reproduction link
[https://www.jsdelivr.com/package/npm/ant-design-vue?version=3.0.0-alpha.10&path=lib%2Fconfig-provider](https://www.jsdelivr.com/package/npm/ant-design-vue?version=3.0.0-alpha.10&path=lib%2Fconfig-provider)

### Steps to reproduce
很多组件在tsx下没有属性提示

### What is expected?
修复所有组件的类型定义, 现在通过vue生成的定义过于复杂，建议参考vxe-table独立定义组件类型 https://github.com/x-extends/vxe-table/tree/master/types

### What is actually happening?
很多组件都没有
1. affix
2. configProvider
3. table竟然是any
... 我也没检查完

**Comment by tangjinzhou** [comment]
下个版本

**Comment by rashagu** [comment]
npm 上最新的 还是3.0.0-alpha.11 的版本
