### ISSUE TITLE
layout-sider bad declaration?

### ISSUE THREAD

**Issue by jvalrog** [vueComponent/ant-design-vue#4866]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue 3.2.16, unplugin-vue-components 0.17.2, vite 2.6.4, vitejs/plugin-vue 1.9.3, vite-tsc 0.3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
Add "layout-sider" to a template

### What is expected?
Expects a correct declaration in "component.d.ts" auto import so I can pass the correct parameters to the component

### What is actually happening?
LayoutSider is imported as "any" and there is no declaration of the parameters

---
In "ant-design-vue/es/layout/index.d.ts" LayoutSider is declared as:

```
export declare const LayoutSider: any;
```

Is this correct?

**Comment by Tanimodori** [comment]
Note: `Tree.TreeNode` not exported issue in 2.x is fixed here.
