### ISSUE TITLE
when I use a-input with prop allowClear in a-tooltip ant trigger is focus,it does not work expected

### ISSUE THREAD

**Issue by dobettest** [vueComponent/ant-design-vue#4869]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue@^2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-currying-efdwn)

### Steps to reproduce
use a-input with prop allowClear in a-tooltip ant trigger is focus

### What is expected?
when cursor focus in a-input,it show the tips for me

### What is actually happening?
it doest not show the tips

---
sorry,the ant-design-vue version is 1.7.8,but the versions select has no such version

**Comment by tangjinzhou** [comment]
you can not nest a-input  in form-item, or use form like https://antdv.com/components/form#components-form-demo-customized-form-controls.

and， Recommend you to use 3.0, 3.0 does not have this restriction
