### ISSUE TITLE
a-select search doesn't support Chinese labels

### ISSUE THREAD

**Issue by immzz** [vueComponent/ant-design-vue#4870]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
MacOS, Chrome 95.0, Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/dai-sou-suo-kuang-ant-design-vue-3-0-0-alpha-11-forked-1mii4?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
* add a Chinese label in options when rendering a-select, for example:
```
const options = ref<SelectProps['options']>([
      { value: 'jack', label: '这是一段中文' },
      { value: 'lucy', label: 'Lucy' },
      { value: 'tom', label: 'Tom' },
    ]);
```

* enable search by adding show-search attribute to a-select
* type any character of the Chinese label
* a-select shows "No Data"

### What is expected?
a-select should show the options that contains the input as a substring.

### What is actually happening?
a-select shows "No Data"

**Comment by immzz** [comment]
This is also reproducible in other versions of antdv, for example:
https://codesandbox.io/embed/dai-sou-suo-kuang-ant-design-vue-next-forked-hov91?fontsize=14&hidenavigation=1&theme=dark

**Comment by 776A0A** [comment]
> This is also reproducible in other versions of antdv, for example in 2.2.8: https://codesandbox.io/embed/dai-sou-suo-kuang-ant-design-vue-next-forked-hov91?fontsize=14&hidenavigation=1&theme=dark

you can use filterOption. According to your code, you did not pass filterOption to a-select.
And you need to change the code to
```
const filterOption = (input: string, option: any) => {
      return option.value.toLowerCase().indexOf(input.toLowerCase()) >= 0 || String(option.label).includes(input);
    };
```

**Comment by immzz** [comment]
I'm assuming this should be supported by default since it's a pretty basic use case. Do we need to update the default filter option?

**Comment by tangjinzhou** [comment]
set filterOption
