### ISSUE TITLE
Affix nails

### ISSUE THREAD

**Issue by nslgit** [vueComponent/ant-design-vue#4873]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
2.2.8

### Reproduction link
[https://2x.antdv.com/components/affix-cn](https://2x.antdv.com/components/affix-cn)

### Steps to reproduce
https://2x.antdv.com/components/affix-cn
官方示例-滚动容器示例
当滚动容器达到使固钉固定后，固钉就会相对屏幕的位置固定，即使容器已经被滚动到其他位置，固钉仍然不会移动位置。

### What is expected?
期望在固钉被固钉后，若容器位置发生变化时，固钉也随之变化位置。

### What is actually happening?
固钉被固定后，容器的位置变化不会带着固钉一起变化。

---
既然容器给了大小，是否考虑使用css3的position: sticky实现容器的固钉会更好，直接让浏览器自身来实现。不过旧版本的浏览器不会生效。

**Comment by tangjinzhou** [comment]
position: sticky 限制很多

**Comment by tangjinzhou** [comment]
关注这个，实时更改位置性能开销太大，目前没有好的方式    https://github.com/ant-design/ant-design/issues/16120
