### ISSUE TITLE
Date selection box (DatePicker) in Chinese environment (zh_CN), but month is English, when using vite to compile and run the project.

### ISSUE THREAD

**Issue by bluesword12350** [vueComponent/ant-design-vue#4875]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.11

### Environment
vite 2.6.4, vue 3.2.20, Microsoft Edge 95.0.1020.44, Windows 10

### Reproduction link
[https://github.com/bluesword12350/antdv-vite-bug-demo](https://github.com/bluesword12350/antdv-vite-bug-demo)

### Steps to reproduce
运行并访问，点击日期选择尝试更改月份，会看到月份任旧是英文，星期也是英文

### What is expected?
中文环境下日期选择框中的月份应该为中文。

### What is actually happening?
中文环境下日期选择框中的月份是英文

**Comment by yanbowe** [comment]
> * [x]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> 3.0.0-alpha.11
> 
> ### Environment
> vite 2.6.4, vue 3.2.20, Microsoft Edge 95.0.1020.44, Windows 10
> 
> ### Reproduction link
> https://github.com/bluesword12350/antdv-vite-bug-demo
> 
> ### Steps to reproduce
> 运行并访问，点击日期选择尝试更改月份，会看到月份任旧是英文，星期也是英文
> 
> ### What is expected?
> 中文环境下日期选择框中的月份应该为中文。
> 
> ### What is actually happening?
> 中文环境下日期选择框中的月份是英文

你应该导入dayjs的语言包

import 'dayjs/locale/zh-cn'

**Comment by bluesword12350** [comment]
这样啊

**Comment by bluesword12350** [comment]
@yanbowe 懂了
