### ISSUE TITLE
Regarding inputNumber after entering a Chinese comma, entering a number again will overwrite the previous number that has been entered

### ISSUE THREAD

**Issue by Shanrunan** [vueComponent/ant-design-vue#4878]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
vue 2.6.11

### Reproduction link
[https://www.antdv.com/components/input-number-cn/](https://www.antdv.com/components/input-number-cn/)

### Steps to reproduce
1.首先输入一个数字，如1
2.再输入一个中文逗号（因为业务需要支持中文逗号，可以不用在输入框里面看到直接过滤掉）
3.之后再输入一个数字，如5，就会发现输入框里面已经没有第一次输入的数字1了，只剩下5这个数字了

### What is expected?
希望的效果就是，可以在输入框里面不看到中文逗号，但是不能影响我已经输入的数字

### What is actually happening?
是必现的bug

**Comment by ajuner** [comment]
这个可以自己在parser里面写个规则把中文逗号过滤掉

**Comment by tangjinzhou** [comment]
不是bug，按照楼上的方法去解，中文字符是不合法字符

**Comment by Shanrunan** [comment]
> 不是bug，按照楼上的方法去解，中文字符是不合法字符

怎么不是bug,中文逗号是不合法字符，输入框可以让我不要输入，但是不能影响我之前输入的数字吧

**Comment by Shanrunan** [comment]
> 这个可以自己在parser里面写个规则把中文逗号过滤掉

我已经写了，但是还是存在这个Bug的，你们可以看下他原本最原始的输入框，不带任何parse的，就会出现这种情况，我知道可以写语句让他过滤掉，但是你不能影响我已经输入的数字吧，他这个是你输入中文逗号之后，再输入一个数字，就会把之前输入的数字覆盖掉

**Comment by Shanrunan** [comment]
你们可以输入任何的中文字符看一下，都不会出现我上面的情况，但是如果是中文逗号，就会覆盖掉我之前输入的数字

**Comment by Shanrunan** [comment]
1.数字输入框不支持中文逗号输入是非常合理的，但是不能是用户不小心输入了中文逗号，直接把前面的数字覆盖掉，影响用户已经输入的值吧。
2.你们可以看下最基本的数组输入框，不带任何parse的就会有个问题，我后面即使加了parse也会存在这个问题，证明这个组件的基础就是有这个问题的

**Comment by ajuner** [comment]
为啥我没这种情况。。。可以问下用的什么输入法嘛。。。

> 1.数字输入框不支持中文逗号输入是非常合理的，但是不能是用户不小心输入了中文逗号，直接把前面的数字覆盖掉，影响用户已经输入的值吧。 2.你们可以看下最基本的数组输入框，不带任何parse的就会有个问题，我后面即使加了parse也会存在这个问题，证明这个组件的基础就是有这个问题的

**Comment by Shanrunan** [comment]
> 为啥我没这种情况。。。可以问下用的什么输入法嘛。。。
> 
> > 1.数字输入框不支持中文逗号输入是非常合理的，但是不能是用户不小心输入了中文逗号，直接把前面的数字覆盖掉，影响用户已经输入的值吧。 2.你们可以看下最基本的数组输入框，不带任何parse的就会有个问题，我后面即使加了parse也会存在这个问题，证明这个组件的基础就是有这个问题的

嗯对，这个也是我后来发现的，我是windows系统，用搜狗输入法和微软自带输入法都会必现，我让我同事用ios系统自带输入法就正常
