### ISSUE TITLE
In the stable version 2.2.8, vue3 warns that there is no install method

### ISSUE THREAD

**Issue by Dylan-lijl** [vueComponent/ant-design-vue#4879]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows10,chrome最新版,vue3

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
调用createApp().use(组件)

### What is expected?
消除警告

### What is actually happening?
含有警告

---
vue3警告日志:A plugin must either be a function or an object with an "install" function.

**Comment by whapply** [comment]
请问这个解决了吗 ？ 我这也报 A plugin must either be a function or an object with an "install" function.


"ant-design-vue": "^2.2.8",

**Comment by Dylan-lijl** [comment]
> 请问这个解决了吗 ？ 我这也报 A plugin must either be a function or an object with an "install" function.
> 
> "ant-design-vue": "^2.2.8",

这个警告是浏览器开启了vue插件导致的,vue插件对vue3支持不是很好

**Comment by whapply** [comment]
> > 请问这个解决了吗 ？ 我这也报 A plugin must either be a function or an object with an "install" function.
> > "ant-design-vue": "^2.2.8",
> 
> 这个警告是浏览器开启了vue插件导致的,vue插件对vue3支持不是很好

这样啊， 就是不用解决了是吧， 感谢

**Comment by havenothingtosay** [comment]
> Since the issue was labeled with `Need Reproduce`, but no response in 7 days. This issue will be closed. If you have any questions, you can comment and reply.
> 
> 由于该 issue 被标记为需要复现信息，却 7 天未收到回应。现关闭 issue，若有任何问题，可评论回复。

我写了一个简单的[在线例子](https://codesandbox.io/s/antdv-an-xu-jia-zai-plugin-install-gx1nkz?file=/src/main.js)，可以复现。例子中只写了LayoutSider组件会引起告警，实际我的项目中还有很多其他组件也会有同样的问题。
