### ISSUE TITLE
table's rowSelection onChange can't work inside modal with asynchronous data

### ISSUE THREAD

**Issue by liaozheng-yi** [vueComponent/ant-design-vue#4880]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
win10 chrome@latest vue3.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-leftpad-30qh7?file=/src/App.vue)

### Steps to reproduce
click that sandbox link

### What is expected?
rowSelection onChange should work

### What is actually happening?
onChange always response emty array

---
it doesn't happen in old version of antv, only met in antv3.x

**Comment by zyplayer** [comment]
+1

**Comment by tangjinzhou** [comment]
fixed at #4889
