### ISSUE TITLE
The precision conversion is incorrect when inputNumber is a negative number

### ISSUE THREAD

**Issue by docodocool** [vueComponent/ant-design-vue#4886]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
"ant-design-vue": "1.7.8",     "moment": "2.22.1",     "vue": "2.5.17"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-4suyp)

### Steps to reproduce
设置精度为0, 输入-1.5, 查看结果

### What is expected?
-2

### What is actually happening?
-1

**Comment by tangjinzhou** [comment]
precision 不是简单的  toFixed
你可以使用 formatter 自行处理 precision 逻辑
