### ISSUE TITLE
The table's checkbox column can't be fixed on left side when set `rowSelection: { fixed: true }`

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#4894]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Vue3.2 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-villani-hjv43?file=/src/App.vue)

### Steps to reproduce
```html
<a-table :row-selection="{ fixed: true }" :scroll="{ x: 500 }"></a-table>
```

### What is expected?
The checkbox column should be fixed on left side

### What is actually happening?
The checkbox column couldn't be fixed on left side since v2.2.3

**Comment by tangjinzhou** [comment]
you. can use { fixed: 'left' }
