### ISSUE TITLE
Custom column is missing slots declaration

### ISSUE THREAD

**Issue by keke599** [vueComponent/ant-design-vue#4896]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
vue3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9dz8h)

### Steps to reproduce
案例存在这个问题

### What is expected?
正常显示自定义列

### What is actually happening?
未显示

**Comment by tangjinzhou** [comment]
`bodyCell` 是从 3.0 开始支持的api
你用的 是 2.x 版本，注意区分文档 2x.antdv.com
