### ISSUE TITLE
The official website is hanging

### ISSUE THREAD

**Issue by Yjk0010** [vueComponent/ant-design-vue#4898]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
访问环境，公司前端这边10台电脑都尝试了

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
就是访问打不开

### What is expected?
希望跟antd一样搞一个国内镜像

### What is actually happening?
页面空白

---
主要的css和js资源10秒被failed了。

**Comment by zkwolf** [comment]
1.x和3.x文档可以考虑内网自己部署一下

**Comment by tangjinzhou** [comment]
服务器本身就在国内，公司运维看看吧
