### ISSUE TITLE
Tabs v-model:activeKey is not update

### ISSUE THREAD

**Issue by menghany** [vueComponent/ant-design-vue#4899]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
windows11,chrome 52,vye 3.2.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-fermat-8zj7s?file=/src/App.vue)

### Steps to reproduce
create empty activeKey string ref.Is not update activeKey when init tabs component.

### What is expected?
activeKey can update value when init tabs component

### What is actually happening?
not update activeKey

**Comment by tangjinzhou** [comment]
This is meaningless, you should ensure that the activeKey is a valid value, instead of relying on the internal components to modify
