### ISSUE TITLE
message配置maxCount不会自动关闭

### ISSUE THREAD

**Issue by rongj** [vueComponent/ant-design-vue#490]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
*

### Reproduction link
[https://codepen.io/anon/pen/Jxxvdq](https://codepen.io/anon/pen/Jxxvdq)

### Steps to reproduce
- 配置message的maxCount3
- 连续点击出现的提示大于3个
- 提示会一直出现，不会自动关闭

### What is expected?
message提示自动关闭

### What is actually happening?
message没有自动关闭

**Comment by wangxueliang** [comment]
![image](https://user-images.githubusercontent.com/4122593/53002917-cbaf0980-3468-11e9-8aa0-95bc58d12fb0.png)
切换最新版本1.3.4

**Comment by zdxweb** [comment]
已经更新到版本1.3.9，还是出现问题（ie)
