### ISSUE TITLE
When columns are used by the ADirectoryTree component, the slot-scope-supported attribute cannot be configured through this attribute

### ISSUE THREAD

**Issue by Yowi** [vueComponent/ant-design-vue#4904]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
MacOS、Chrome、Vue2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-9rm7b?file=/src/App.vue)

### Steps to reproduce
ADirectoryTree 组件使用 columns 时，无法通过该属性配置支持 slot-scope 的属性，如 scopedSlots: { title: 'XXX'}

```vue
<a-directory-tree  ...  :tree-data='[{ title: "Expand to load", key: "0", scopedSlots: { title: "title" } }]' />
```

### What is expected?
ADirectoryTree 组件使用 columns 时，scopedSlots 起效

### What is actually happening?
ADirectoryTree 组件使用 columns 时，scopedSlots 不起效

**Comment by zkwolf** [comment]
6eb92cc297c7be1f2e5fb587e1f0639ea68d5589 下个版本修复
