### ISSUE TITLE
Is the interface.d.ts file in the table removed?

### ISSUE THREAD

**Issue by sinceseason** [vueComponent/ant-design-vue#4905]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
无法找到模块“./interface”的声明文件。“/node_modules/ant-design-vue/lib/table/interface.js”隐式拥有 "any" 类型

### What does the proposed API look like?
丢失了table/interface.d.ts文件吗，

**Comment by sinceseason** [comment]
![image](https://user-images.githubusercontent.com/14029440/142600718-1f8e6607-7fa3-487a-9bdf-0a3052a6a242.png)

**Comment by sinceseason** [comment]
"ant-design-vue": "^3.0.0-alpha.11"
"vue": "^3.2.20",

**Comment by tangjinzhou** [comment]
we will release alpha.12 to fixed it
