### ISSUE TITLE
The autofocus attribute of the drawer component is invalid

### ISSUE THREAD

**Issue by Veloma-Timer** [vueComponent/ant-design-vue#4907]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
electron 15.3.0; vue 3.2.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/next/components/drawer/index.tsx](https://github.com/vueComponent/ant-design-vue/blob/next/components/drawer/index.tsx)

### Steps to reproduce
1. 创建一个input组件
2. 创建一个drawer组件
3.input聚焦的时候 显示drawer, input失去焦点的时候隐藏drawer
4. 这个时候会发现drawer是出现不了的
5. 即使将drawer的autofocus属性设置为false, 焦点依旧会脱离input

### What is expected?
使drawer组件的autofocus属性生效

### What is actually happening?
drawer组件的autofocus属性失效

---
查看了drawer组件的源码, 发现源码中虽然接收了autofocus属性, 但并未对其处理

![image](https://user-images.githubusercontent.com/49268882/142754944-52f294c2-04eb-4128-a13e-7ce77d0a1d3c.png)

**Comment by tangjinzhou** [comment]
没发现问题，请提供复现示例

```html
<template>
  <a-button type="primary" @click="showDrawer">Open</a-button>
  <a-input @focus="handleFocus" @blur="handleBlur"></a-input>
  <a-drawer
    v-model:visible="visible"
    class="custom-class"
    style="color: red"
    title="Basic Drawer"
    placement="right"
    :autofocus="false"
    @after-visible-change="afterVisibleChange"
  >
    <p>Some contents...</p>
    <p>Some contents...</p>
    <p>Some contents...</p>
  </a-drawer>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue';
export default defineComponent({
  setup() {
    const visible = ref<boolean>(false);

    const afterVisibleChange = (bool: boolean) => {
      console.log('visible', bool);
    };

    const showDrawer = () => {
      visible.value = true;
    };

    return {
      visible,
      afterVisibleChange,
      showDrawer,
      handleFocus: () => {
        visible.value = true;
      },
      handleBlur: () => {
        console.log('blur');
      },
    };
  },
});
</script>

```

**Comment by Veloma-Timer** [comment]
@tangjinzhou  你好，我在项目中运行了你的实例，也发现了跟我相同的问题，就是当点击input的时候(此时input聚焦), drawer就会弹出，此时input会失去焦点, 这看起来是正常的, 因为此时mask为true, 但当mask为false是，我所预期的是 input的焦点不会失去
