### ISSUE TITLE
Calendar custom header (headerRender) data changes after the view is not updated

### ISSUE THREAD

**Issue by liujianchao1995** [vueComponent/ant-design-vue#4910]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0te7g?file=/src/demo.vue)

### Steps to reproduce
Calendar自定义头部（headerRender）数据变化后，视图无更新。

### What is expected?
Calendar自定义头部（headerRender）数据变化后，视图无更新。

### What is actually happening?
Calendar自定义头部（headerRender）数据变化后，视图无更新。

**Comment by tangjinzhou** [comment]
最新版应该没问题了吧

**Comment by tangjinzhou** [comment]
alpha 9 也没复现

**Comment by liujianchao1995** [comment]
> alpha 9 不再复现

上面的示例，通过两个自定义的下拉框调用onChange切换年、月，下面的视图并没有更新啊。

**Comment by liujianchao1995** [comment]
> alpha 9 也没复现

我看了下官网示例，alpha.14这个问题不再复现了。
