### ISSUE TITLE
使用vite2.x 打包 ant-design-vue-3.0.0-alpha.12提示error TS2411: Property 'title' of type '((data: DataNode) => any) | undefined' is not assignable to 'string' index type '(d: any) => any'.

### ISSUE THREAD

**Issue by moligithub** [vueComponent/ant-design-vue#4912]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
Vue版本：3.2.22、vite版本：2.6.14、typescript版本：4.5.2

### Reproduction link
[https://github.com/moligithub/ant-design-vue-issues.git](https://github.com/moligithub/ant-design-vue-issues.git)

### Steps to reproduce
1. ant-design-vue版本3.0.0-alpha.11打包正常。
2. ant-design-vue版本升级到3.0.0-alpha.12后打包报错。

### What is expected?
ant-design-vue版本3.0.0-alpha.12使用vite可以正常打包。

### What is actually happening?
ant-design-vue版本3.0.0-alpha.12使用vite打包报错。

**Comment by tangjinzhou** [comment]
降级 typescript 到 4.3
