### ISSUE TITLE
The initial data of the tree component should not be affected by the parent-child linkage

### ISSUE THREAD

**Issue by gas0324** [vueComponent/ant-design-vue#4915]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows10 20h2，chrome 96.0.4664.45，vue3.2.20

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/urm6e)

### Steps to reproduce
设置checkedKeys = ref<string[]>(['0-0-0', '0-0-1']);

### What is expected?
按checkedKeys设置节点选中状态，其中节点：{ key: '0-0-1-0', title: 'sss' }  不应该被选中

### What is actually happening?
{ key: '0-0-1-0', title: 'sss' }被选中

---
我需要按数据库中存储的设置来初始化已授权的角色菜单，当父节点下的子节点未被全部选中时，初始化页面状态错误，我认为当开发者手动传入checkedKeys时，实际选中的就是开发者所设置的，不应该受父子联动影响

**Comment by gas0324** [comment]
有人吗

**Comment by tangjinzhou** [comment]
set  checkStrictly  https://next.antdv.com/components/tree-cn/#API
