### ISSUE TITLE
table headerCell slot have no effect

### ISSUE THREAD

**Issue by hipi** [vueComponent/ant-design-vue#4916]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.12

### Environment
win10 ,ChromeV95,vue 3.2

### Reproduction link
[https://codepen.io/yuyehack/pen/oNeRwoR](https://codepen.io/yuyehack/pen/oNeRwoR)

### Steps to reproduce
ant-design-vue@3.0.0-alpha.12 版本，官方文档示例，使用官方的 codesandbat-design-vue@3.0.0-alpha.12和 自己另写了  codepen 表格的headerCell  插槽都没有效果

### What is expected?
实际展示 headerCell  插槽效果

### What is actually happening?
没有展示

**Comment by lamelamb** [comment]
2021.1.14   3.0.0  beta 6  still  has  the same bug, looks like the beta version problem, switch ant-design- vue to 2.xx verison can shortly resolve the problem
