### ISSUE TITLE
a-range-picker placeholder passes array and reports ts type error

### ISSUE THREAD

**Issue by yezipi** [vueComponent/ant-design-vue#4917]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
macos m1, chrome 96.0.4664.55, vue3.2.22

### Reproduction link
[https://next.antdv.com/components/date-picker-cn](https://next.antdv.com/components/date-picker-cn)

### Steps to reproduce
a-range-picker的placeholder传入数组

### What is expected?
传入数组不会有ts类型错误

### What is actually happening?
提示不能将类型“string[]”分配给类型“string”

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/143674229-52a6966f-f98d-4860-853c-d08218682e0d.png)
没发现发问题啊

**Comment by yezipi** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/143674229-52a6966f-f98d-4860-853c-d08218682e0d.png) 没发现发问题啊

![image](https://yangpin.shop/file202111a37d4e82af0c7524.png)
