### ISSUE TITLE
Tree tree control-automatically expand child nodes after clicking on the node

### ISSUE THREAD

**Issue by zhouzuixin** [vueComponent/ant-design-vue#4919]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
左侧的小箭头可点击区域太小，操作不太方便，希望点击节点名称也能自动展开子节点

### What does the proposed API look like?
antdv 2版本里面之前是有这个函数的，不清楚antdv 3版本里面为什么去掉了（还是改成其他方式了？）。
在select事件中（function(selectedKeys, e:{selected: bool, selectedNodes, node, event})）可以通过e.node.onExpand()触发这个动作。

version：3.0.0-alpha.12

**Comment by zkwolf** [comment]
这功能可以考虑监听select事件控制expandedkeys吧

**Comment by zhouzuixin** [comment]
对的，antdv3里面去掉那个函数（ e.node.onExpand()  ）之后，我现在是这么实现的😀

zkwolf ***@***.***> 于2021年11月26日周五 下午2:14写道：

**Comment by tangjinzhou** [comment]
e.node.onExpand() 算是非文档 api 了，没写在文档的随时都有可能改掉啊
