### ISSUE TITLE
The tree expansion node is slow to load

### ISSUE THREAD

**Issue by kfhechenglong** [vueComponent/ant-design-vue#4920]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.12

### Environment
windows10，chrome 96.0.4664.45，vue3.2.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/urm6e)

### Steps to reproduce
节点中自定义了title和图标
```
<template #title="{ id, dptLeaderName, dptName }">
<span :class="id === 1 ? 'bold' : ''">{{ dptName }}</span>
<a-space :size="8" class="icon-group">
<i v-has="ORGANIZATION.ORGANIZATION_ADD" class="iconfont icon-xinzeng" @click.stop="handleDepart('add', id)"></i>
<i v-has="ORGANIZATION.ORGANIZATION_EDIT" class="iconfont icon-edit-1" @click.stop="handleDepart('modify', id)"></i>
<i v-has="ORGANIZATION.ORGANIZATION_DELETE" class="iconfont icon-a-delete" @click.stop="handleDepart('del', id)"></i>
</a-space>
<a-space :size="4" v-if="dptLeaderName" class="icon-name">
<span>（</span>
<i class="iconfont icon-a-user"></i>
<span>{{dptLeaderName}}</span>
<span>）</span>
</a-space>
</template>
```
### What is expected?
点击父节点展开收起图标，正常展开关闭子节点树；

### What is actually happening?
节点展开与关闭卡顿，但是在2.2.8版本无此现象

**Comment by zkwolf** [comment]
给个最小复现？

**Comment by kfhechenglong** [comment]
无法复现，无需解决
