### ISSUE TITLE
input v-model - Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array

### ISSUE THREAD

**Issue by Djaangoo** [vueComponent/ant-design-vue#4922]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-waterfall-mvpsf?file=/src/components/RichText.vue)

### Steps to reproduce
Go to the reproduction link and try to enter text into the field
in console, you should see a lot of warnings

### What is expected?
updating model without warnings

### What is actually happening?
Warning in console -  Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array

**Comment by sorryjs** [comment]
v-model:value, 删除value
