### ISSUE TITLE
Pagination group price, 20/page, 50/page. The entrance to Chinese could not be found, and it could not be converted to 20/page or 50/page.

### ISSUE THREAD

**Issue by islittlezhou** [vueComponent/ant-design-vue#4923]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.7

### Environment
node版本v12.16.3、谷歌浏览器、windows操作系统开发环境、vue3.0版本

### Reproduction link
[https://next.antdv.com/components/pagination-cn](https://next.antdv.com/components/pagination-cn)

### Steps to reproduce
我使用antd-vue3的组件库，其中表格组件 自带 的 分页组件， 20/page,  50/page 无法 转成  20/页   50/页。我看官方组件例子却又是中文的，组件中配置文件又没找到可以 修改的 入口。

### What is expected?
我使用antd-vue3的组件库，其中表格组件 自带 的 分页组件， 20/page,  50/page 无法 转成  20/页   50/页。我看官方组件例子却又是中文的，组件中配置文件又没找到可以 修改的 入口。

### What is actually happening?
我使用antd-vue3的组件库，其中表格组件 自带 的 分页组件， 20/page,  50/page 无法 转成  20/页   50/页。我看官方组件例子却又是中文的，组件中配置文件又没找到可以 修改的 入口。

---
如果你们解决了， 或者你们发现了 我修改 成 中文失败的原因，或者是我没找到正确修改的办法。还请您联系我一下，我的微信号是  15886497846。不胜感激，毕竟我也是给你们捐赠过一点小钱的，还望告知一下解决方案

**Comment by tangjinzhou** [comment]
https://next.antdv.com/docs/vue/i18n-cn
