### ISSUE TITLE
Use config-provider to report errors

### ISSUE THREAD

**Issue by sinceseason** [vueComponent/ant-design-vue#4926]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
vue@3.2.20

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-dqfc6?file=/src/components/AppProvider.vue)

### Steps to reproduce
<template>
<config-provider>
<slot></slot>
</config-provider>
</template>
<script lang="ts">
import { toRefs, defineComponent } from 'vue';
import { ConfigProvider } from 'ant-design-vue';
import zhCN from 'ant-design-vue/es/locale/zh_CN';
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';
import { prefixCls } from '#/settings/styleSetting';
import { createAppProviderCtx } from '../hooks/useAppCtx';

export default defineComponent({
components: { ConfigProvider },
name: 'AppProvider',
props: {
prefixCls: {
type: String,
default: prefixCls,
},
locale: {
type: Object,
default: () => zhCN,
},
},
setup(props) {
dayjs.locale('zh-cn');
const { prefixCls } = toRefs(props);
createAppProviderCtx({ prefixCls });
},
});
</script>

### What is expected?
正确设置locale

### What is actually happening?
TypeError: Cannot read properties of undefined (reading 'antLocale')

**Comment by sinceseason** [comment]
![image](https://user-images.githubusercontent.com/14029440/143410196-9b2a37f4-3893-4855-8a01-4e545afa09ef.png)

**Comment by sinceseason** [comment]
如果注释config-provider的内容
```
<template>
	<!-- <a-config-provider :locale="zhCN"> -->
		<app-provider>
			<router-view />
		</app-provider>
	<!-- </a-config-provider> -->
</template>
```
报错信息为：
![image](https://user-images.githubusercontent.com/14029440/143418724-e33df156-f3cd-4772-bbf1-c361af8c8e6d.png)
![image](https://user-images.githubusercontent.com/14029440/143418789-7dc726a4-7c82-4374-83d1-32eed851442e.png)

**Comment by tangjinzhou** [comment]
提供可以运行的复现示例，
盲猜是引入了不同的 vue 文件，可以试着删除 nodemodules 重装，或者设置 alias

**Comment by sinceseason** [comment]
> 提供可以运行的复现示例， 盲猜是引入了不同的 vue 文件，可以试着删除 nodemodules 重装，或者设置 alias

是的，node_modules 同时引入了2.x和3.x的库，删除后重新install，就可以了
非常感谢
