### ISSUE TITLE
this.$route.push({name: "myRoute"}) not select left menu item named `myRoute`

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#493]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
mac OS / chrome / latest / vue:2.5.22

### Reproduction link
[https://github.com/Afondevi/vue-renter](https://github.com/Afondevi/vue-renter)

### Steps to reproduce
Create this.$route.push({name: "myRoute"})
Create item menu call `myRoute`
When click on menu is ok, but when click on button doing the `this.route.push...` the uri change, the page too, but not the selected menu.

### What is expected?
Menu selected when I use `this.$route.push...`

### What is actually happening?
Menu not selected when I use `this.$route.push...`

**Comment by tangjinzhou** [comment]
I think this is your business problem, the router and menu are not directly connected.

**Comment by Afondevi** [comment]
It’s solve, need to use ‘selectedKeys’ tag to change it.
