### ISSUE TITLE
anchor had className “fixed” when set affix=false

### ISSUE THREAD

**Issue by aov2005** [vueComponent/ant-design-vue#4931]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue 3.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/51874d9cee2c4c67f6aebb84e756f0d8794ad8bc/components/anchor/Anchor.tsx?_pjax=%23js-repo-pjax-container#L241](https://github.com/vueComponent/ant-design-vue/blob/51874d9cee2c4c67f6aebb84e756f0d8794ad8bc/components/anchor/Anchor.tsx?_pjax=%23js-repo-pjax-container#L241)

### Steps to reproduce
```html
<a-anchor :affix="false" ></a-anchor>
---to---
<div class="ant-anchor fixed"></div>
```

### What is expected?
```html
<div class="ant-anchor ant-fixed"></div>
```

### What is actually happening?
与tailwind冲突，能否增加前缀？如 ant-fixed

**Comment by aov2005** [comment]
```js
classNames(pre, {
        fixed: !affix && !showInkInFixed,
      })
```

看到有加前缀了，那应该是bug了

**Comment by zkwolf** [comment]
看了一下ant design,应该是没前缀

**Comment by aov2005** [comment]
看到 ant design 居然一样，好像也没生效不知道干啥的
