### ISSUE TITLE
useForm causes watchEffect of select options of FormItem to be triggered

### ISSUE THREAD

**Issue by candy-Tong** [vueComponent/ant-design-vue#4932]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows10,google chrome 79.0.3945.130,vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/useform-basic-usage-ant-design-vue-3-0-0-alpha-12-forked-s730h?file=/src/demo.vue)

### Steps to reproduce
该demo是有一个select组件，watchEffect监听options改变，改变则将select value改为options的第一个值。可以直接看demo.vue
```JavaScript
    watchEffect(() => {
      console.log("typeOptions.value[0]", options.value[0]?.value);
      const option = options.value[0]
      modelRef.region = option.value;
    });
```

1. 一进入页面，select 的 value 为 key，
2. 选择select的 key2选项
3. 第一次选择 key2 后，watchEffect被调用，导致 select value 被设置成为options的第一项，即key
4. 再次选择 key2，才正常

### What is expected?
第一次选择 key2 后，watchEffect被调用，导致 select value 被设置成为options的第一项，即key

### What is actually happening?
第一次选择key2，watchEffect没有被调用，select value被正常修改

自己排查过一下，只要注释掉useForm，就没问题了

**Comment by zkwolf** [comment]
考虑一下用watch直接监听options？

**Comment by candy-Tong** [comment]
> 考虑一下用watch直接监听options？

可以暂时先使用watch代替，试了一下，watch 不会被触发

**Comment by candy-Tong** [comment]
![image](https://user-images.githubusercontent.com/20377280/143548533-5d640d7f-13bd-4719-bfdf-bc71f19ec0e1.png)
看起来可能是这一行导致的，我注释之后，就正常了。但我想不明白为什么这个会触发了 watchEffect
