### ISSUE TITLE
Button control href function requirements

### ISSUE THREAD

**Issue by menkeydyvh** [vueComponent/ant-design-vue#4933]
### What problem does this feature solve?
Button 控件 href 设置后是直接通过a标签重新加载了整个页面，导致整个页面抖动
可否类似于router-link方式去处理 这样点击后的跳转更平滑不会导致页面抖动重载

### What does the proposed API look like?
api不变，内部实现需处理一下

**Comment by tangjinzhou** [comment]
建议直接 通过 click 事件去调用 vuerouter 的api

组件库并不知道你使用的是什么路由管理器
