### ISSUE TITLE
Select single-selection mode, searchable, no defocus after selection

### ISSUE THREAD

**Issue by tracy2zhang** [vueComponent/ant-design-vue#4934]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.12

### Environment
vue3.2.16, chrome 95.0.4638.69，macos12.0.1

### Reproduction link
[https://next.antdv.com/components/select-cn#components-select-demo-search](https://next.antdv.com/components/select-cn#components-select-demo-search)

### Steps to reproduce
1.select单选模式，支持搜索
2.选中任意一项

### What is expected?
选中后下拉框收起，光标失焦

### What is actually happening?
选中后没有失焦

**Comment by tangjinzhou** [comment]
这是特性
你可以选中后操作ref  调用 blur
