### ISSUE TITLE
Source/Target panes not checking all items

### ISSUE THREAD

**Issue by olufemioyedepo** [vueComponent/ant-design-vue#4939]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.9

### Environment
Windows 10, Mozilla Firefox v92.0, Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lj6kj?file=/src/demo.vue)

### Steps to reproduce
The transfer plugin example at https://next.antdv.com/components/transfer/#components-transfer-demo-basic demoed at https://codesandbox.io/s/lj6kj?file=/src/demo.vue doesn't seem to select/check all items on the Source & Target panes

### What is expected?
The transfer plugin was supposed to check all items on click of the checkbox on the Source and Target panes

### What is actually happening?
The transfer plugin is not checking all items on click of the checkbox on the Source and Target panes

**Comment by tangjinzhou** [comment]
v-model support at 3.0
If you use v2.x, you should use selectChange event to control  selectedKeys

**Comment by olufemioyedepo** [comment]
I don't quite understand your response.

The Transfer plugin doesn't work well even from the official sandbox
https://codesandbox.io/s/lj6kj?file=/src/demo.vue

**Comment by tangjinzhou** [comment]
Sorry, it looks like the version is not correctly for codesandbox.
