### ISSUE TITLE
HTML模板下，menu 组件的 openChange事件无法检测

### ISSUE THREAD

**Issue by dongnanyanhai** [vueComponent/ant-design-vue#494]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
win10，谷歌浏览器最新版，vue 2.6

### Reproduction link
[http://201803.h5power.cn/vue-test/index.html](http://201803.h5power.cn/vue-test/index.html)

### Steps to reproduce
使用 antd-with-locales.js 版本，按https://vue.ant.design/components/menu-cn/#components-menu-demo-open-current-submenu-only 此链接中“只展开当前父级菜单”的代码，发现在html模板下，不管使用@open-change="onOpenChange"，还是@openChange="onOpenChange"，都无法给菜单的OpenChange函数绑定处理函数。

### What is expected?
可以给事件绑定处理函数！

### What is actually happening?
无法给事件绑定处理函数！

**Comment by tangjinzhou** [comment]
首先不建议你直接使用HTML模板，如果非要用可以使用如下插件来获取驼峰事件的兼容
https://github.com/vueComponent/vue-dash-event

**Comment by dongnanyanhai** [comment]
> 首先不建议你直接使用HTML模板，如果非要用可以使用如下插件来获取驼峰事件的兼容
> https://github.com/vueComponent/vue-dash-event

好的，谢谢！

我用插件来兼容，非常感谢！
