### ISSUE TITLE
The Transfer source data list is tree-like, and it is not a tree-like structure if you check to move to the target data list

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#4945]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.13

### Environment
chrome 94.0.4606.54

### Reproduction link
[https://next.antdv.com/components/transfer-cn](https://next.antdv.com/components/transfer-cn)

### Steps to reproduce
在https://next.antdv.com/components/transfer-cn    树穿梭框 可以复现
![image](https://user-images.githubusercontent.com/5828057/143767839-65ec2547-04e0-4b22-a68e-41ac7177ee24.png)

### What is expected?
Transfer  源数据列表是树状的，勾选移到目标数据列表还是树状结构
![image](https://user-images.githubusercontent.com/5828057/143767857-a7b1b85e-1f9f-43c2-9dc4-607f095c8c89.png)
### What is actually happening?
Transfer  源数据列表是树状的，勾选移到目标数据列表就不是树状结构

**Comment by tangjinzhou** [comment]
https://next.antdv.com/components/transfer-cn#components-transfer-demo-tree-transfer  参考这个

**Comment by wsxe9988** [comment]
参考了，但是勾选了父级和子级节点，移到右边目标数据列表后，并不是树状结构，就是在官网连接试的，还需要怎么改造么

**Comment by gaojs920426** [comment]
+1   求如何处理

**Comment by zkwolf** [comment]
仔细看那个`v-if="direction === 'left'"`，右边树加上判断自定义就可以了
