### ISSUE TITLE
How to implement classification selector with select component

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#4947]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用select 组件如何实现分类选择器

### What does the proposed API look like?
用select 组件如何实现分类选择器
![image](https://user-images.githubusercontent.com/5828057/143797060-508a687c-48f9-46a0-a5b3-e30cd234fb7a.png)
如果可以实现的话，能否给个示例，不能的话是否考虑拓展出这个组件，这类的需求还挺多，挺实用的

**Comment by tangjinzhou** [comment]
使用 https://next.antdv.com/components/cascader-cn
