### ISSUE TITLE
关于 Checkbox 多选框，a-checkbox-group 绑定 v-model="checkedList" :options="plainOptions" ， plainOptions 数组里的每一项如果是一个具有 value 和 label 属性的对象，全选失效！全选和反选起到的效果都是反选 

### ISSUE THREAD

**Issue by 1906136787** [vueComponent/ant-design-vue#4949]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.13

### Environment
好像任何版本都有这个问题

### Reproduction link
https://codesandbox.io/s/vue-antd-template-forked-31fhy?file=/src/App.vue:608-620

### Steps to reproduce
当 plainOptions 数组赋值是 data 下面的 // ["表格", "折线图", "柱状图", "饼图", "玫瑰图", "其他"], 全选和反选没有任何问题。但如果换成具有 value 和 label 属性的对象，其他功能都没问题，就全选无法实现全选操作，全选功能在浏览器页面上起到的效果是反选，onCheckAllChange() 函数里的代码为我的各种尝试，都不起效，但是 checkedList 确实已经改变。最后我定位到具体原因是仅 plainOptions 为 value 和 label 对象，全选功能会出现这种情况。

### What is expected?
期望的结果是 plainOptions 数组的每一项都是具有 value 和 label 属性的对象时，全选功能也起到应有的作用！

### What is actually happening?
plainOptions 数组的每一项都是具有 value 和 label 属性的对象时，全选功能在浏览器页面上呈现的作用是反选！

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-ukh2f?file=/src/App.vue
