### ISSUE TITLE
I hope that a-switch will add a time before the state changes for asynchronous operation.

### ISSUE THREAD

**Issue by kfhechenglong** [vueComponent/ant-design-vue#4950]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.13

### Environment
3版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-31fhy)

### Steps to reproduce
点击a-switch先不改变状态，异步操作完成后再更改a-switch的状态值

代码中目前没有提供机会可供操作
![image](https://user-images.githubusercontent.com/25744535/143846575-b23d0200-0bb3-4414-b86f-2bde0198e316.png)

**Comment by sendya** [comment]
:loading 可以控制处理 loading 等待异步结束，调整 loading 即可

**Comment by kfhechenglong** [comment]
click事件或者change事件并不会因为loading的状态改变而阻止。我希望的流程是点击-执行异步-更改状态，目前的流程是点击后没有机会阻止状态改变，一个常用的场景是：点击switch-确认弹框层-发送请求-改变状态；

**Comment by kfhechenglong** [comment]
> :loading 可以控制处理 loading 等待异步结束，调整 loading 即可

click事件或者change事件并不会因为loading的状态改变而阻止。我希望的流程是点击-执行异步-更改状态，目前的流程是点击后没有机会阻止状态改变，一个常用的场景是：点击switch-确认弹框层-发送请求-改变状态；
