### ISSUE TITLE
Select dropdown position is not correct

### ISSUE THREAD

**Issue by nageguanzi** [vueComponent/ant-design-vue#4959]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue3.1.4， chrome 96

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-brook-7jf6j?file=/src/App.vue)

### Steps to reproduce
If the select is on the bottom of a page(the dropdown will appear top of the select), you click the select after the page rendered first time, or click the select quickly, the position of dropdown may cover the select。

### What is expected?
dropdown position is correct

### What is actually happening?
dropdown position is not correct

**Comment by tangjinzhou** [comment]
you can update to 3.0
