### ISSUE TITLE
anchor组件 无法获得addEventListener事件

### ISSUE THREAD

**Issue by JackeLbb** [vueComponent/ant-design-vue#496]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
browser version，Vue version

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
vue创建组件中使用ant-anchor模块会出现报错：[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'addEventListener' of undefined"

found in

---> <AAnchor>

### What is expected?
anchor锚点正常监听滚轮事件

### What is actually happening?
报错：[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'addEventListener' of undefined"

found in

---> <AAnchor>

**Comment by tangjinzhou** [comment]
提供复现demo链接 谢谢
