### ISSUE TITLE
Normal Configure on-demand according to the document The component does not take effect

### ISSUE THREAD

**Issue by LHR19950403** [vueComponent/ant-design-vue#4972]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.13

### Environment
vue 2.0 谷歌版本 96.0.4664.55（正式版本） (x86_64)

### Reproduction link
[https://www.antdv.com/docs/vue/use-with-vue-cli-cn/](https://www.antdv.com/docs/vue/use-with-vue-cli-cn/)

### Steps to reproduce
根据文档按需引入步骤

### What is expected?
按需引入组件库 根据文档不能生效

### What is actually happening?
按需引入组件库 根据文档应该生效

---
vue-cli vue2.0 按需引入使用babelrc配置 按需引入不生效

**Comment by tangjinzhou** [comment]
and  填写正确的版本号
