### ISSUE TITLE
After the Carousel component dynamically changes the image array data, the large image is not updated in the custom paging mode

### ISSUE THREAD

**Issue by pickmonster** [vueComponent/ant-design-vue#4974]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Carousel 组件再动态改变图片数组数据后，自定义分页模式下大图不更新，仅更新了列表图片数据

### What does the proposed API look like?
Carousel 组件再动态改变图片数组数据后，大图和列表数据都更新

**Comment by gefangshuai** [comment]
为啥关掉了？请问怎么解决的？

**Comment by gefangshuai** [comment]
唉，我是通过加了一个标识，然后用v-if强制又渲染了一遍
```javascript
watch(
    () => props.product.id,
    () => {
      hasData.value = false;
      setTimeout(() => {
        hasData.value =
          props.product.productPictures &&
          props.product.productPictures.length > 0;
      }, 100);
    },
    {
      immediate: true,
    }
  );
```
