### ISSUE TITLE
Safari中固定头和列的表格，左右滑动时会出现双滚动条

### ISSUE THREAD

**Issue by Caozefu** [vueComponent/ant-design-vue#498]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Mac OS 10.14.3、Safari 12.0.3

### Reproduction link
[https://vue.ant.design/components/table-cn/](https://vue.ant.design/components/table-cn/)

### Steps to reproduce
Safari打开官网文档，table模块，固定头和列的部分，左右滑动表格，会出现双滚动条

Safari opens the official website document, table module, fixed head and column parts, slides the table left and right, and double scroll bars appear.

### What is expected?
去掉类名为ant-table-header的div中的css属性：overflow: scroll

Remove the css attribute from the div with the class "name ant-table-header": overflow: scroll

### What is actually happening?
去掉指定属性后就没有上面的滚动条了

After removing the specified attribute, there is no scroll bar above.

**Comment by tangjinzhou** [comment]
没能复现你的问题
![image](https://user-images.githubusercontent.com/6937879/53152330-33dc2780-35f0-11e9-923d-bef1707db378.png)

**Comment by Caozefu** [comment]
这是我这里看到的，还是会出现，我同事也会出现这样的情况

**Comment by Caozefu** [comment]
> 没能复现你的问题
> ![image](https://user-images.githubusercontent.com/6937879/53152330-33dc2780-35f0-11e9-923d-bef1707db378.png)



> 没能复现你的问题
> ![图片](https://user-images.githubusercontent.com/6937879/53152330-33dc2780-35f0-11e9-923d-bef1707db378.png)

![bug](https://user-images.githubusercontent.com/23171288/53152859-aa2d5980-35f1-11e9-9002-be768a0997dc.gif)
你好，可以看一下这个gif

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/13994
