### ISSUE TITLE
rowSelection.getCheckboxProps, infinite loop, browser crashes

### ISSUE THREAD

**Issue by Tnon** [vueComponent/ant-design-vue#4986]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
vue3 antdv- alpha.13

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yuan-cheng-jia-zai-shu-ju-ant-design-vue-3-0-0-alpha-14-forked-tyn6d?file=/src/demo.vue)

### Steps to reproduce
在getCheckboxProps里面，我想通过record，动态给selectedkeys   push，以达到当前页面数据自动选择的操作，2.2.8没有问题，3.0.0导致浏览器崩溃，死循环

### What is expected?
浏览器不会崩溃，getCheckBoxProps能够每一次push一个rowkey

### What is actually happening?
浏览器崩溃 卡死

**Comment by tangjinzhou** [comment]
什么场景 getCheckboxProps 的时候， 还需要动态改变 selectedkeys 的值

**Comment by Tnon** [comment]
一键选择全部数据，但部分数据 disabled不可选择

**Comment by Tnon** [comment]
场景是这样的，表格 外部有个按钮，这个按钮的功能是“选择全部数据”（包括数据库全部数据，不只是当前页），当点击表格下一页的时候，我必须手动改变selectedKeys 已达到选择页面数据，此刻我就想找个函数，能够在渲染每一条数据的时候，把当前rowkey  push到selectedKeys，2.2.8版本的 getcheckboxprops能够实现我这个需求。3.0.0 貌似在这个函数我改变selectedkeys的时候，就崩溃了

**Comment by Tnon** [comment]
> 场景是这样的，表格 外部有个按钮，这个按钮的功能是“选择全部数据”（包括数据库全部数据，不只是当前页），当点击表格下一页的时候，我必须手动改变selectedKeys 已达到选择页面数据，此刻我就想找个函数，能够在渲染每一条数据的时候，把当前rowkey push到selectedKeys，2.2.8版本的 getcheckboxprops能够实现我这个需求。3.0.0 貌似在这个函数我改变selectedkeys的时候，就崩溃了

**Comment by Tnon** [comment]
这如果是个bug，请关注，如果不是，我移除副作用。

**Comment by tangjinzhou** [comment]
不是bug，这个写法就有问题
你的场景  for循环数据，赋值给 selectedKeys 即可

**Comment by Tnon** [comment]
好的，那我写纯函数吧 谢了
