### ISSUE TITLE
CheckBoxGroup file is missing

### ISSUE THREAD

**Issue by reactleaner** [vueComponent/ant-design-vue#4987]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
nodejs14.17

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/s/bu-ju-ant-design-vue-3-0-0-alpha-14-forked-wllyr?file=/src/demo.vue)

### Steps to reproduce
无

### What is expected?
正常导入

### What is actually happening?
组件缺失

**Comment by reactleaner** [comment]
![image](https://user-images.githubusercontent.com/89075874/144832831-efcabd46-034f-49f7-a797-8e34743a48c3.png)

**Comment by ajuner** [comment]
Checkbox.Group

**Comment by tangjinzhou** [comment]
这是用了什么插件自动导入吧  ，你应该去看看插件如何配置
