### ISSUE TITLE
Scope-slot doesn't work by using wrapper table 

### ISSUE THREAD

**Issue by amantiwari1** [vueComponent/ant-design-vue#4988]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.5.4

### Environment
win 11, brave ,  2.6.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-serm6?file=/src/App.vue)

### Steps to reproduce
after using Scope-slot in table

### What is expected?
it should be same wrapper table result and normal table result

### What is actually happening?
it is getting error due to slot scope doesn't work because of wrapper

**Comment by tangjinzhou** [comment]
first, customTitle is slot, not scope-slot.
second, some scope-slot is multipe args.   v-slot:[slot]="scope" just get first arg.  You have to deal with different scope-slots separately.
And, we have change multipe args to only one arg from antdv@v2.x.  you can upgrade to use vue3 & antdv2

**Comment by amantiwari1** [comment]
okay got it @tangjinzhou
