### ISSUE TITLE
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

### ISSUE THREAD

**Issue by YuGe** [vueComponent/ant-design-vue#499]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
macOS Mojave, chrom Version 72.0.3626.109, Vue 2.6.6, Nuxt 2.4.3, postcss 7.0.14

### Reproduction link
[https://github.com/YuGe/ant-design-vue-text-decoration-skip](https://github.com/YuGe/ant-design-vue-text-decoration-skip)

### Steps to reproduce
npm run dev

### What is expected?
no warn

### What is actually happening?
```
WARN  in ./node_modules/ant-design-vue/lib/style/index.css                               friendly-errors 14:35:52
Module Warning (from ./node_modules/postcss-loader/src/index.js):                         friendly-errors 14:35:52
Warning
(160:11) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed friendly-errors 14:35:52
@ ./node_modules/ant-design-vue/lib/style/index.css 4:14-143 14:3-18:5 15:22-151
@ ./node_modules/ant-design-vue/lib/button/style/css.js
@ ./plugins/antd-ui.js
@ ./.nuxt/index.js
@ ./.nuxt/client.js
@ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js
```

---
This has been fixed in Ant Design React.

**Comment by tolerious** [comment]
vue?

**Comment by meng458544582341** [comment]
@YuGe  怎么解决的？ 下一个版本修复么？

**Comment by tangjinzhou** [comment]
ref #485
