### ISSUE TITLE
In the <a-table> component, when the x attribute of scroll is set, the table will appear abnormal when the page is loaded for the first time.

### ISSUE THREAD

**Issue by ll60** [vueComponent/ant-design-vue#4993]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
操作系统: macOS12.0.1、浏览器: Chrome 版本 96.0.4664.55（正式版本） (arm64)、VUE版本: 3.2.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-0-0-alpha-13-forked-5xwkp?file=/src/demo.vue)

### Steps to reproduce
页面创建一个<a-table>，设置scroll的x为任意值，首次进入页面会出现异常现象，之后又正常，刷新页面可重现异常样式。

### What is expected?
预期设置scroll的x值后，显示正常

### What is actually happening?
设置scroll的x值后，表格首次进入页面出现异常显示，之后一瞬间又好了，貌似是table的内部容器，宽度样式丢失了。

---
请在本地电脑项目验证这一bug, 在线编辑器中无法重现当前问题。

**Comment by tangjinzhou** [comment]
本地电脑没复现

**Comment by ll60** [comment]
> 电脑本地没复现
<img width="1346" alt="WeChat09276f80516182e49590406df021d042" src="https://user-images.githubusercontent.com/30487969/145133725-743e4706-dd0f-4aae-bbd6-b7e330177d1f.png">
你好，是进入页面一瞬间的情况，看上述截图
在，网页里写
onMounted(() => {
  setTimeout(() => {
    window.location.reload()
  }, 50)
})
一直刷新页面，可以一直复现这个情况。

**Comment by ll60** [comment]
> 电脑本地没复现

你好，请问是否可以复现当前问题

**Comment by tangjinzhou** [comment]
没能复现   😓

**Comment by ll60** [comment]
> 没能复现 😓
![11CCDC0021D7D7C032B14A684D8F3AE5](https://user-images.githubusercontent.com/30487969/145542581-d4b0a756-0ef2-49dd-a3ca-ef6120677219.jpg)

**Comment by Cheerwhy** [comment]
确实有这个问题, 只要scroll的x属性设置了，无论为何值，组件第一次渲染就有这个显示bug

**Comment by tangjinzhou** [comment]
能复现的帮忙看看呗  感谢

**Comment by ll60** [comment]
> 能复现的帮忙看看呗 感谢

233...就用vite创建个初始项目，之后引入ant，用a-table,设置x就复现了，不知道为啥你电脑没复现..我用好几个同事的电脑，都有这种情况。有mac，有window..
