### ISSUE TITLE
modal display and hide lead to refresh of the entire page component (if computed or filters are called, methods will be called again)

### ISSUE THREAD

**Issue by qiuxinlei** [vueComponent/ant-design-vue#4994]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Vue2.6.11 ant-design-vue 1.7.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdzhong-tableyu-modalwen-ti-2pepw?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1、点击编辑
2、查看console会发现，模态框显示隐藏后，方法会调用

### What is expected?
预期是模态框显示、隐藏不应该，影响到该页面内容

### What is actually happening?
影响了页面内容，调用了computed、filters、methods
而且如果在此filters改变了内容就会出现死循环，测试过element-ui的dialog不会出现此情况，所以觉得这不是vue的问题，应该是modal组件导致整个页面有重新渲染的嫌疑

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/antdzhong-tableyu-modalwen-ti-forked-h8xrp?file=/src/components/HelloWorld.vue

那就去掉 模态框 试试

**Comment by qiuxinlei** [comment]
所以这是vue双向绑定就是这样的？

**Comment by tangjinzhou** [comment]
数据(visible)变化，重新render

想不执行，试试计算属性
