### ISSUE TITLE
The right arrow animation of the a-select component is missing

### ISSUE THREAD

**Issue by shengting1** [vueComponent/ant-design-vue#4999]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
操作系统: windows 10， 浏览器：Chrome  96.0.4664.45（正式版本）， Vue： 3.2.16

### Reproduction link
[https://next.antdv.com/components/select-cn](https://next.antdv.com/components/select-cn)

### Steps to reproduce
页面创建一个a-select组件，点击a-select组件，在选项列表出现情况下，右侧箭头仍是向下

### What is expected?
点击a-select组件，出现选项列表时，右侧箭头应以动画形式旋转为向上方向（具体可参考1.x版本的动画）

### What is actually happening?
在点击a-select组件时，右侧箭头不会发生方向和状态的改变

**Comment by tangjinzhou** [comment]
antd 最新设计规范如此
