### ISSUE TITLE
The click event of the dropdown-button in the layout will be triggered twice

### ISSUE THREAD

**Issue by jiagang** [vueComponent/ant-design-vue#5002]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
win10、chrome96、vue3.2.24

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-goldberg-20v0u)

### Steps to reproduce
layout 中出现 layout-sider 时

### What is expected?
按钮的点击事件应该只触发一次

### What is actually happening?
dropdown-button的点击事件会触发两次

---
普通button是正常的，layout中不出现layout-sider时也是正常的

**Comment by 24min** [comment]
阻止冒泡事件【`e.stopPropagation()`】对此issue似乎可行，

业务组件中：
![dd5bc5a3a0bf807d78e7275bebc2bf6](https://user-images.githubusercontent.com/32154293/145507858-2eddb71b-99a1-49d1-b266-d916cb7595c4.png)

或者
components\dropdown\dropdown-button.tsx：
![1e008d6220addd39e6465feac7bbfee](https://user-images.githubusercontent.com/32154293/145507847-def17a16-6557-4b8c-be92-8b107ebc3900.png)

**阻止冒泡虽然能解决这个触发两次的问题，但具体触发此问题的原因，还不明确。**

**Comment by tangjinzhou** [comment]
感觉是 vue 的bug

**Comment by tangjinzhou** [comment]
不是冒泡的问题

**Comment by 24min** [comment]
> 不是冒泡的问题

组止冒泡的话是一个治标不治本的改法。但是具体为啥会有这个问题，水平有限，无法找到😕

**Comment by jiagang** [comment]
是很奇怪，我发现绑定事件改成这样就正常了
![image](https://user-images.githubusercontent.com/3692361/145757333-84f116ab-c510-4544-9756-d60ddd023bf6.png)
