### ISSUE TITLE
Introduce type TreeProps error

### ISSUE THREAD

**Issue by joker77877** [vueComponent/ant-design-vue#5003]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
macOs10.15.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sh276?file=/src/demo.vue)

### Steps to reproduce
import type  {TreeProps}  from 'ant-design-vue';
![image](https://user-images.githubusercontent.com/62642184/145381968-d6b83dd4-1d55-4e9a-a2f9-e301c5c32faa.png)

### What is expected?
不报错

### What is actually happening?
模块 ""ant-design-vue"" 没有导出的成员 "TreeProps"。你是想改用 "import TreeProps from "ant-design-vue"" 吗?

---
import type  {TreeProps}  from 'ant-design-vue';

**Comment by tangjinzhou** [comment]
确认你的版本，3.0.0-alpha.14 应该没问题，
在ts 文件内是否可行，如果 ts文件没问题，那就是你的配置有问题

**Comment by joker77877** [comment]
抱歉是我更新完antd之后没有重启项目.
