### ISSUE TITLE
Form verification required = true, only the string is verified, and I assign a number by default, it will prompt that the verification fails

### ISSUE THREAD

**Issue by hangjob** [vueComponent/ant-design-vue#5007]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
rules[item.key] = [{
required: true,
message: `请填写 ${item.title}`,
trigger: 'blue'
}]
只设置了required = true, 然后点击编辑的时候，赋值默认值，其中有一个赋值了为了数字，当我点击提交的时候提示我校验不通过
formRef.value.validate()

### What is expected?
我认为正常来讲，‘required = true’ 不管是数字还是字符串，则都为通过，否则自己去写验证规则

### What is actually happening?
然后点击编辑的时候，赋值默认值，其中有一个赋值了为了数字，当我点击提交的时候提示我校验不通过

**Comment by tangjinzhou** [comment]
rule 添加  type = 'any'
