### ISSUE TITLE
Write style error on tree component

### ISSUE THREAD

**Issue by Luooooooo** [vueComponent/ant-design-vue#5010]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
win10；360极速-版本号:21.0.1040.0内核版本:95.0.4621.0；vue3.2.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3qlfc)

### Steps to reproduce
点击弹窗报错： TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported.
```
 | setStyle | @ | runtime-dom.esm-bundler.js?830f:160
  | patchStyle | @ | runtime-dom.esm-bundler.js?830f:115
  | patchProp | @ | runtime-dom.esm-bundler.js?830f:377
  | mountElement | @ | runtime-core.esm-bundler.js?5c40:3807
  | processElement | @ | runtime-core.esm-bundler.js?5c40:3770
  | patch | @ | runtime-core.esm-bundler.js?5c40:3690
  | componentUpdateFn | @ | runtime-core.esm-bundler.js?5c40:4238
  | run | @ | reactivity.esm-bundler.js?a1e9:160
  | callWithErrorHandling | @ | runtime-core.esm-bundler.js?5c40:6706
  | flushJobs | @ | runtime-core.esm-bundler.js?5c40:6945
  | Promise.then (async) |   |  
  | nextTick | @ | runtime-core.esm-bundler.js?5c40:6797
  | useInsertStyles | @ | utils.js?2adb:78
  | IconBase | @ | IconBase.js?6ba3:44
 ```

### What is expected?
正常弹出

### What is actually happening?
TypeError: Failed to set an indexed property on 'CSSStyleDeclaration': Indexed property setter is not supported.

**Comment by Luooooooo** [comment]
树的checkedKeys也不是受控的属性。测试同样写在上面的sandbox里

**Comment by tangjinzhou** [comment]
不同问题，分开提问  谢谢

**Comment by tangjinzhou** [comment]
https://next.antdv.com/components/modal-cn#FAQ   第二个问题看这里
改成函数形式：
content: () => xxxx

报错问题，麻烦提供更加详细的信息：浏览器版本，报错具体信息，如果能给到具体行数更好

**Comment by Luooooooo** [comment]
好的 😁
