### ISSUE TITLE
DirectoryTree: [Vue warn]: Slot "default" invoked outside of the render function

### ISSUE THREAD

**Issue by think-gem** [vueComponent/ant-design-vue#5013]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
win、chrome92、vue3

### Reproduction link
[https://2x.antdv.com/components/tree-cn](https://2x.antdv.com/components/tree-cn)

### Steps to reproduce
The tree directory warns when using TSX:

```
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.
at <ADirectoryTree>
at <Tree>
......
```

Example code:
```
<script lang="tsx">
  import { defineComponent } from 'vue';
  import { Tree } from 'ant-design-vue';
  export default defineComponent({
    setup() {
      return () => {
        return (
          <Tree.DirectoryTree>
            <Tree.TreeNode key="0-0" title="parent 0">
              <Tree.TreeNode key="0-0-0" title="leaf 0-0" is-leaf />
              <Tree.TreeNode key="0-0-1" title="leaf 0-1" is-leaf />
            </Tree.TreeNode>
            <Tree.TreeNode key="0-1" title="parent 1">
              <Tree.TreeNode key="0-1-0" title="leaf 1-0" is-leaf />
              <Tree.TreeNode key="0-1-1" title="leaf 1-1" is-leaf />
            </Tree.TreeNode>
          </Tree.DirectoryTree>
        );
      };
    },
  });
</script>
```

### What is expected?
There is no warning

### What is actually happening?
A warning  [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by GroupOfStar** [comment]
我也遇到了这个警告，虽然可以正常渲染显示，但如果你无视这个警告的话，但打包运行后就无法正常显示了。
这应该是与vue@3.2版本兼容的问题.
参考https://stackoverflow.com/questions/69928229/vue-3-cli-service-app-slot-default-invoked-outside-of-the-render-function-w

**Comment by think-gem** [comment]
@tangjinzhou

Reproduce code: 

<https://gitee.com/thinkgem/jeesite-vue/blob/master/src/components/Tree/src/Tree.vue#L578>

will
```
const TreeComp = showIcon ? Tree.DirectoryTree : Tree;
```
change
```
const TreeComp = Tree;
```
after modification，no warning.

But I hope, use `DirectoryTree` no warning.
