### ISSUE TITLE
[Table] Support row-selection-on-click triggering `onSelect` event

### ISSUE THREAD

**Issue by 1sm23** [vueComponent/ant-design-vue#5015]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
The [demo](https://codesandbox.io/s/row-selection-on-click-tr58v) in the document cannot trigger `rowSelection` `onSelect` event, although it has checked the checkbox or radio.

### What does the proposed API look like?
Triggering events when checkbox or radio checked.

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/145703551-306d816a-3127-46ca-b28c-ec34a1222693.png)

**Comment by 1sm23** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/145703551-306d816a-3127-46ca-b28c-ec34a1222693.png)

I mean, click on entire row

**Comment by tangjinzhou** [comment]
when click on entire row, you use selectRow to control selectedRowKeys.

onSelect only trigger by click checkbox.
