### ISSUE TITLE
Tree Component: the node spacing is getting bigger if the node has a number of child

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#502]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
1.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24kj72mj2p)

### Steps to reproduce
link to https://codesandbox.io/s/24kj72mj2p

### What is expected?
normal spacing between tree node

### What is actually happening?
growing spacing

**Comment by tangjinzhou** [comment]
According to the specification, we need a hierarchical relationship.
If you don't need it, you can override the style.

```css
.ant-tree li ul {
 padding-left: 0;
}
```

**Comment by agoni1212** [comment]
@tangjinzhou you may misunderstand what i meant
the spacing between node 0-0-0-0-15  and not 0-1 is too height  in vertical.
to make it clear , i add the style you pointed out , [https://codesandbox.io/s/24kj72mj2p](url)

**Comment by tangjinzhou** [comment]
I get it.
you can add code:
```
.ant-tree li {
    padding: 8px 0 0;
}
```
We will fix it in next version.

**Comment by agoni1212** [comment]
@tangjinzhou the commit you added makes the node spacing between each other is higher than before

**Comment by tangjinzhou** [comment]
@agoni1212 I will continue to optimize. Thanks for feedback.
