### ISSUE TITLE
When using prefixCls to modify the class name, normal components can be modified, but the message and modal are called through static methods, and the class name still starts with ant

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5020]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue3 antd2.2.8

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
通过prefixCls修改类名，其他组件正常修改。
message和modal静态方法调用，如message.success等

### What is expected?
出现的message、modal类名仍为.ant开头。
但通过组件调用方式的Modal是已修改的类名。

### What is actually happening?
message类名被一并修改

**Comment by tangjinzhou** [comment]
update to 3.0

**Comment by wishong** [comment]
> update to 3.0

ok，升级到3.0已经正常
