### ISSUE TITLE
useForm validateFields does not process the array

### ISSUE THREAD

**Issue by pengfeiWang** [vueComponent/ant-design-vue#5022]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
mac os

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/useform-ji-ben-biao-dan-ant-design-vue-3-0-0-alpha-15-forked-vxptm?file=/src/demo.vue)

### Steps to reproduce
校验表单

### What is expected?
正常校验

### What is actually happening?
正常校验

**Comment by tangjinzhou** [comment]
useForm 无法知道 modelRef rulesRef 之间的映射关系，
你可以这么写 
```js
const { resetFields, validate, validateInfos } = useForm(
      modelRef.list[0],
      rulesRef,
      {
        onValidate: (...args) => console.log(...args),
      },
    );
```
