### ISSUE TITLE
Select and TreeSelect cannot be selected when use custom prefixCls

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5023]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.15

### Environment
3.0.0-alpha.15

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
使用Select和TreeSelect

### What is expected?
无法选择

### What is actually happening?
版本回退到3.0.0-alpha.14正常
![14](https://user-images.githubusercontent.com/53365470/145750937-f3ab1d1e-60f2-4722-bac5-7165b3700ab3.gif)

3.0.0-alpha.15选不了
![15](https://user-images.githubusercontent.com/53365470/145750948-addd5161-d2f1-4216-8561-e5b87af6f531.gif)

**Comment by tangjinzhou** [comment]
官网示例没问题啊  给个复现吧

**Comment by wishong** [comment]
> 官网示例没问题啊 给个复现吧

可以看下这个demo
https://github.com/wishong/antd-bug

**Comment by tangjinzhou** [comment]
自己跑一下了吗  我这没问题

**Comment by wishong** [comment]
> 自己跑一下了吗 我这没问题

我和同事的电脑都不行 您可以用别人电脑试一下

**Comment by wsxe9988** [comment]
> > 自己跑一下了吗 我这没问题
> 
> 我和同事的电脑都不行 您可以用别人电脑试一下

你可以提供下出现问题的电脑的操作系统，浏览器类型及版本 供排查问题。

**Comment by wishong** [comment]
> 你可以提供下出现问题的电脑的操作系统，浏览器类型及版本 供排查问题。

win10家庭版 chore 96.0.4664.45

**Comment by wishong** [comment]
> 你可以提供下出现问题的电脑的操作系统，浏览器类型及版本 供排查问题。

win10家庭版 chrome 96.0.4664.45

**Comment by tangjinzhou** [comment]
试着 删除 nodemodules .lock 文件重装试试吧 
 我没能复现

**Comment by yandixuan** [comment]
@tangjinzhou 我也是的build完后 nginx跑 .15版本根本不能选 .14版本select 第一次打开就这个问题再打开就好了。本地复现不出来这个问题

**Comment by yandixuan** [comment]
debug了下第一次open下拉框时渲染的dom，ant-select-dropdown的style属性有个 pointer-events：none; 关闭之后第二次打开这个属性就没了（.14版本） @tangjinzhou

**Comment by tangjinzhou** [comment]
如果是 build 之后才会有问题，那提交一个包含 build 之后代码的仓库

**Comment by tangjinzhou** [comment]
你们自定义了动画 ？

**Comment by yandixuan** [comment]
https://github.com/yandixuan/build-error
@tangjinzhou 已经包含build 直接点进去第一个页面的select都无法选择

**Comment by tangjinzhou** [comment]
> https://github.com/yandixuan/build-error @tangjinzhou 已经包含build 直接点进去第一个页面的select都无法选择

你这是用 yarn build:test 构建的吧，组件内部对 test 模式做了特殊处理   😓

**Comment by tangjinzhou** [comment]
不知道你们是不是同一个问题

**Comment by yandixuan** [comment]
🤣 那我换个mode , thanks for youur reply @tangjinzhou

**Comment by wishong** [comment]
> 不知道你们是不是同一个原因 @yandixuan @wishong

我是开发环境就不行了

**Comment by tangjinzhou** [comment]
是否在 less 自定义了  prefixCls @wishong

**Comment by wishong** [comment]
> 是否在 less 自定义了 prefixCls @wishong

是的，定义了。也有可能是这个问题。

**Comment by tangjinzhou** [comment]
你给的复现示例并没有反映出这个 配置，方便的话在核实下 https://github.com/wishong/antd-bug  这个仓库能复现选不中问题 ？

**Comment by wishong** [comment]
> 你给的复现示例并没有反映出这个 配置，方便的话在核实下 https://github.com/wishong/antd-bug 这个仓库能复现选不中问题 ？

我的demo中是有修改前缀类名的。
刚才又试了一下，真的是prefixCls导致的。删除之后选择都正常了。您可以看一下是否是这个影响到了

**Comment by transtone** [comment]
> debug了下第一次open下拉框时渲染的dom，ant-select-dropdown的style属性有个 pointer-events：none; 关闭之后第二次打开这个属性就没了（.14版本） @tangjinzhou

不仅是ant-select-dropdwon有这个问题，下拉选择都有这个问题。ant-dropdown  也一样会多一个 `pointer-events: none;` 的样式，导致鼠标移不进去。

**Comment by IvanRoslov** [comment]
It's very sad that you don't use English. Using the library becomes very difficult. Thanks to Google translator, I realized that I have the same problem, but I didn't understand whether it was a bug or a problem in my implementation.

P.S. If you add a rule to write an issue and discuss in English, it will greatly help developers from other countries. Thank you for your work.

**Comment by IvanRoslov** [comment]
The problem is in `pointer-events: none`, I agree with that. All my selects and dropdowns broke down. Rolled back to 3.0.0-alpha.14 everything works well in this version.

**Comment by tangjinzhou** [comment]
@IvanRoslov update to 3.0.0-beta.7

**Comment by IvanRoslov** [comment]
@tangjinzhou Unfortunately, it didn't help. Beta 7 also has this bug.
![select](https://user-images.githubusercontent.com/69309824/148819456-265ddca5-adbc-49ad-bbab-d7f9db0b8089.gif)

**Comment by transtone** [comment]
> @IvanRoslov update to 3.0.0-beta.7

无效。

**Comment by transtone** [comment]
> It's very sad that you don't use English. Using the library becomes very difficult. Thanks to Google translator, I realized that I have the same problem, but I didn't understand whether it was a bug or a problem in my implementation.
> 
> P.S. If you add a rule to write an issue and discuss in English, it will greatly help developers from other countries. Thank you for your work.

也许英语会帮到一些外国人，但就帮不到更多的使用中文的人了。有谷歌翻译不是一样的吗。

**Comment by tangjinzhou** [comment]
Can someone give me an example by codesandbox to reproduce this issue.

**Comment by tangjinzhou** [comment]
And you should not use `NODE_ENV= test` env to deploy or dev site.
Maybe is other reason，but you should give me a reproduce demo for debugger it.

**Comment by IvanRoslov** [comment]
@tangjinzhou 

Example https://stackblitz.com/edit/vitejs-vite-ubopey?file=src/App.vue

**Comment by transtone** [comment]
still not fix with `3.0.0-beta.9`

**Comment by snecker** [comment]
have the same problem 
version is **3.0.0-beta.9**

**Comment by snecker** [comment]
have the same problem 
version is **3.0.0-beta.9**

**Comment by transtone** [comment]
@tangjinzhou  `3.1.0-rc5` still not fix this problem.
