### ISSUE TITLE
a-input-search, after adding a clear button, clicking the button will trigger the search event

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5031]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.15

### Environment
vue3 vite2

### Reproduction link
[https://next.antdv.com/components](https://next.antdv.com/components)

### Steps to reproduce
<a-input-search allow-clear @search="onSearch" />

const onSearch = () => {
console.log('onSearch');
}

### What is expected?
点击清空按钮会触发search

### What is actually happening?
不应该触发search

**Comment by geeklibin** [comment]
确实，我也遇到了，应该需要解决一下

**Comment by tangjinzhou** [comment]
这是预期行为，可以查看 antd 这边：
ref https://github.com/ant-design/ant-design/issues/33059
