### ISSUE TITLE
How to use the permission control in a single page now in the new version?

### ISSUE THREAD

**Issue by sunzlit** [vueComponent/ant-design-vue#5039]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
老版本是用 v-action:add自定义指令来控制某个按钮，现在是怎么控制用户增删改查等权限的呢？
<authority :authority="['admin']">test</authority>
这个貌似是针对用户页面权限，并非增删改查等权限吧？
没太明白这个的具体用法，感谢回复。

### What does the proposed API look like?
期望可以在单个页面内可以控制某个用户所对应的权限操作类型。

**Comment by tangjinzhou** [comment]
你应该去 pro 的issue 区提问

**Comment by sunzlit** [comment]
不好意思，我已经在pro提了工单，望回复，谢谢。



| |
sunzl
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月15日 23:07 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [vueComponent/ant-design-vue] How to use the permission control in a single page now in the new version? (Issue #5039) |

你应该去 pro 的issue 区提问

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
