### ISSUE TITLE
ie 11 以下table 组件的本身的hove 效果，和table 的子组件的click 事件没法触发，在里面加个input 组件 点击无法获取焦点，麻烦解决下 我看官网了也会出现同样的问题！

### ISSUE THREAD

**Issue by lixiaolongxl** [vueComponent/ant-design-vue#504]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.2.4

### Environment
333

### Reproduction link
[http://cpp.cjmltest.cn](http://cpp.cjmltest.cn)

### Steps to reproduce
ie 11 以下table 组件的本身的hove 效果，和table 的子组件的click 事件没法触发，在里面加个input 组件 点击无法获取焦点，麻烦解决下 我看官网了也会出现同样的问题！

### What is expected?
44

### What is actually happening?
44

---
44

**Comment by tangjinzhou** [comment]
找不到 cpp.cjmltest.cn 的服务器 IP 地址。

**Comment by lixiaolongxl** [comment]
http://cpp.zhipeicloud.com/#/login   用户名：智配服务商管理    密码：000000

**Comment by lixiaolongxl** [comment]
ie 11 以下不行你看下

![image](https://user-images.githubusercontent.com/28329718/53102839-7a397400-3567-11e9-8541-e5c01a10fd6b.png)

**Comment by lixiaolongxl** [comment]
正常的ie 11
![image](https://user-images.githubusercontent.com/28329718/53102961-abb23f80-3567-11e9-8d14-87ff3e529569.png)

**Comment by lixiaolongxl** [comment]
Tabs 组件 ie10切换正常，ie9切换就不正常了，官网demo 也是这样麻烦给看下！
![image](https://user-images.githubusercontent.com/28329718/53104825-07ca9300-356b-11e9-8005-5985fa58c6a3.png)
当前情况下我已经点击了Tabs3按钮了

**Comment by tangjinzhou** [comment]
https://vue.ant.design/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7
自行添加 Polyfills

**Comment by lixiaolongxl** [comment]
import "babel-polyfill";
import Vue from 'vue'
import APP from './APP.vue'
import Antd from 'ant-design-vue'
// import 'ant-design-vue/dist/antd.css'
// 使用less 编译
import 'ant-design-vue/dist/antd.less'

import Loading from '../../components/Loading/index'
import store from '../../store/index'
import router from '../../router'

// console.log(router)
// es6Promise.polyfill();
Vue.use(Loading)
Vue.use(Antd)
Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  router,
  store,
  render: h => h(APP)
}).$mount('#app')
 我已添加 过了！不然ie 是打不开的！ import "babel-polyfill";

**Comment by tangjinzhou** [comment]
@lixiaolongxl  已经解决了？虚拟机没能复现你的问题

**Comment by tangjinzhou** [comment]
@wangxueliang 可以先给出未发版之前的临时解决方案

**Comment by wangxueliang** [comment]
.ant-spin-container::after {
  display: none\9;
}
先使用样式覆盖
