### ISSUE TITLE
a-form dynamically add or subtract form items

### ISSUE THREAD

**Issue by wananle** [vueComponent/ant-design-vue#5041]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
win10

### Reproduction link
[https://qnmy6.csb.app/](https://qnmy6.csb.app/)

### Steps to reproduce
官方的例子， input换成InputNumber

### What is expected?
表单验证和自己匹配的规则一致

### What is actually happening?
表单验证和自己匹配的规则不一致

**Comment by k983551019** [comment]
https://codesandbox.io/s/dong-tai-zeng-jian-biao-dan-xiang-ant-design-vue-next-forked-lp74j?file=/src/Demo.vue

**Comment by tangjinzhou** [comment]
rule 添加  type: 'number',
