### ISSUE TITLE
Can't use showTotal with simple mode

### ISSUE THREAD

**Issue by constantkek** [vueComponent/ant-design-vue#5042]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.15

### Environment
Ubuntu 20.04, Chrome 92.0.4515.131, Vue 2.6.11

### Reproduction link
[https://antdv.com/components/pagination](https://antdv.com/components/pagination)

### Steps to reproduce
Create pagination component with simple and showTotal attributes

### What is expected?
Simple pagination with text on the left like there https://antdv.com/components/pagination/#Total-number

### What is actually happening?
Text doesn't show up

---
Is this feature or a bug? :D

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/32696

**Comment by constantkek** [comment]
Pagination with simple mode needs lesser space than default one. It's likely to use that free space for something else, for example, additional info about that table (total, filtered). Default pagination with some text on the left might look overloaded
