### ISSUE TITLE
使用lodash-webpack-plugin后，打包项目Form组件的v-decorator会报错

### ISSUE THREAD

**Issue by ocubexo** [vueComponent/ant-design-vue#505]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Vue2.6

### Reproduction link
[http://none.none](http://none.none)

### Steps to reproduce
添加lodash-webpack-plugin开发依赖，将使用了antd的项目打包。
打开使用了Form组件的页面，控制台会输出t is not a function

### What is expected?
组件能够正常渲染

### What is actually happening?
控制台报错

**Comment by tangjinzhou** [comment]
麻烦提供复现demo，
另外，我认为这和组件没有关系，大概率是你业务代码问题

**Comment by ocubexo** [comment]
你可以新建一个基于antd的项目，然后安装并配置lodash-webpack-plugin。在app.vue上使用Form组件并使用表单校验功能就能复现。这应该是个插件的兼容性问题，我在去除这个插件后就不会有任何错误。

**Comment by maroon1** [comment]
@tangjinzhou 我也遇到这个问题
https://github.com/maroon1/ant-design-vue-lodash-webpack-plugin-issue

**Comment by mistkafka** [comment]
我也遇到了，貌似ant-design vue使用了lodash，然后lodash-webpack-plugin把其依赖的函数给干掉了。

**Comment by ocubexo** [comment]
没错，错误原因就是因为lodash-webpack-plugin把antd依赖的lodash给去掉了。

**Comment by mistkafka** [comment]
@ocubexo 我决定放弃用插件优化了，直接自己套一层按需引入，反正用到的函数不多。

**Comment by ocubexo** [comment]
@mistkafka 你这种按需引入是可以用babel的插件替代的，webpack插件的优点主要是还加了Tree Shake优化。

**Comment by mistkafka** [comment]
@ocubexo 不太懂，[文档](https://github.com/lodash/lodash-webpack-plugin#webpackconfigjs)里应该是要求bebel插件跟webpack插件都要用的吧？

你的意思是，webpack就是加了Tree Shake，如果没有也没事？

**Comment by ocubexo** [comment]
对，两者结合压缩力度大



在 迷雾卡夫卡 <notifications@github.com>，2019年6月20日 18:14写道：

@ocubexo<https://github.com/ocubexo> 不太懂，文档<https://github.com/lodash/lodash-webpack-plugin#webpackconfigjs>里应该是要求bebel插件跟webpack插件都要用的吧？

你的意思是，webpack就是加了Tree Shake，如果没有也没事？

**Comment by ocubexo** [comment]
对，两者结合压缩力度大，但是不一起用也没事。
