### ISSUE TITLE
bug: Clicking the Select select box to clear the button did not make other elements lose focus

### ISSUE THREAD

**Issue by rxliuli** [vueComponent/ant-design-vue#5050]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

![Select clear 没有正确失焦问题演示](https://user-images.githubusercontent.com/24560368/146484977-13ac8673-230b-43f4-9249-16c0bd39afa2.gif)

        
### Version
3.0.0-alpha.15

### Environment
Windows 10, Chrome Last，vue@3.1.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-christian-9lhbs)

### Steps to reproduce
1. 选择下拉框
2. 点击输入框
3. 点击选择框的清除按钮

### What is expected?
点击选择框的清除按钮应该让 input 失去焦点

### What is actually happening?
input 没有失去焦点

**Comment by tangjinzhou** [comment]
就这么设计的，你可以手动 blur

**Comment by rxliuli** [comment]
> 就这么设计的，你可以手动 blur

点击 clear 的时候手动调用 input 的 blur？
