### ISSUE TITLE
InputNumber in FormItem cannot pass the required validator

### ISSUE THREAD

**Issue by ayizhi** [vueComponent/ant-design-vue#5053]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.15

### Environment
vue 3.2.26 ant-design-vue 3.0.0-alpha15

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-cache-mny1z?file=/src/App.vue)

### Steps to reproduce
1, input the InputNumber a number
2, blur
3, get the error, but the value is filled

### What is expected?
after the inputNumber component filled, the required validator should not be triggered

### What is actually happening?
after the inputNumber component filled, the required validator still triggered

**Comment by tangjinzhou** [comment]
rule add type: 'number'

**Comment by ayizhi** [comment]
> rule add type: 'number'

thanks bro
