### ISSUE TITLE
Upload upload component is invalid in Edge browser

### ISSUE THREAD

**Issue by lauxiao** [vueComponent/ant-design-vue#5060]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.16

### Environment
操作系统 macOS monterey 12.1  浏览器 Microsoft Edge 版本 96.0.1054.6 (arm64)

### Reproduction link
[https://www.antdv.com/components/upload-cn/](https://www.antdv.com/components/upload-cn/)

### Steps to reproduce
项目中的上传组件失效（点击按钮无反应，无法弹出文件选择窗口），访问官网点击演示示例（https://next.antdv.com/components/upload-cn/）同样如此

### What is expected?
点击上传按钮，弹出文件选择窗口

### What is actually happening?
点击上传按钮无反应，控制台未抛异常

---
使用Google Chrome 浏览器 （版本 96.0.4664.110 (arm64) ）可以正常使用组件

**Comment by zkwolf** [comment]
同12.1没复现
