### ISSUE TITLE
useForm resetFields  delete the fields which dynamic added, please  just clear the fields instead of remove it, like ref reset.

### ISSUE THREAD

**Issue by WormGirl** [vueComponent/ant-design-vue#5062]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.16

### Environment
vue3

### Reproduction link
[http://localhost:3000/](http://localhost:3000/)

### Steps to reproduce
no

### What is expected?
please  just clear the fields instead of remove it

### What is actually happening?
useForm resetFields  delete  all fields dynamic added

**Comment by jinxinkai** [comment]
3.0.0-alpha.16有这个问题3.0.0-alpha.15是正常的

**Comment by WormGirl** [comment]
> 3.0.0-alpha.16有这个问题3.0.0-alpha.15是正常的

I used 3.0.0-alpha.14

**Comment by zkwolf** [comment]
还是给个复现链接吧

**Comment by WormGirl** [comment]
> 还是给个复现链接吧

https://github.com/WormGirl/vite-vue-antv-form

**Comment by jinxinkai** [comment]
What's new?

**Comment by tangjinzhou** [comment]
不支持，你可以使用传统模式（非 useForm）

**Comment by WormGirl** [comment]
> https://github.com/WormGirl/vite-vue-antv-form

这是复现链接

**Comment by zkwolf** [comment]
事实上就是不支持，useForm的机制做的比较简单，reset的时候就是直接把值变成传进来的初始值
