### ISSUE TITLE
Form form validation, radio, value: Ref<number>, validation is invalid

### ISSUE THREAD

**Issue by Tnon** [vueComponent/ant-design-vue#5064]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.16

### Environment
chrome 95 / 96/  vue3@lasted,vite@2,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-dan-yan-zheng-ant-design-vue-3-0-0-alpha-16-forked-80n26?file=/src/demo.vue)

### Steps to reproduce
value为number时候，表单验证不通过，字符串没有问题

### What is expected?
支持number

### What is actually happening?
不支持number

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/biao-dan-yan-zheng-ant-design-vue-3-0-0-alpha-16-forked-wjn4g?file=/src/demo.vue

add type: 'number'
