### ISSUE TITLE
The tree control node expands and flashes

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5069]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.16

### Environment
vue3 vite2

### Reproduction link
[https://next.antdv.com/components/tree-cn](https://next.antdv.com/components/tree-cn)

### Steps to reproduce
点击树节点会闪烁，2.x版本不会。官网案例即可复现
![test](https://user-images.githubusercontent.com/53365470/147242252-69a98ef5-c1b4-4be4-b555-a7d441e0f5e3.gif)

### What is expected?
展开时闪烁

### What is actually happening?
展开时不闪烁

**Comment by zhangsanfe** [comment]
+1
