### ISSUE TITLE
 webpack vue-design

### ISSUE THREAD

**Issue by cindyrise** [vueComponent/ant-design-vue#507]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
node11

### Reproduction link
[https://vue.ant.design/docs/vue/introduce-cn/](https://vue.ant.design/docs/vue/introduce-cn/)

### Steps to reproduce
npm run dev

### What is expected?
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

### What is actually happening?
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

---
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

**Comment by tangjinzhou** [comment]
ref #485
