### ISSUE TITLE
Select component in multiple mode, It will jump a certain distance after scrolling and click item.

### ISSUE THREAD

**Issue by StereoApp** [vueComponent/ant-design-vue#5073]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.16

### Environment
Windows 10; Chrome 96; Vue 3.2.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biao-qian-ant-design-vue-3-0-0-alpha-16-forked-ijrfs)

### Steps to reproduce
1. Click select component to expand options.
2. Scroll any distance.
3. Click an option.

### What is expected?
Keep the original position.

### What is actually happening?
It will jump a certain distance.

---
在Select组件的多选模式中，点击Select组件展开选项后，先滚动一段距离再点击选项，下拉选项会跳动一段距离，似乎滚动的越多跳的距离越远。

**Comment by tangjinzhou** [comment]
升级 3.0.0-beta.1

**Comment by StereoApp** [comment]
> 升级 3.0.0-beta.1

谢谢，升级后解决
