### ISSUE TITLE
3.0.0-beta.1 cannot import components

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5076]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.1

### Environment
vue3 vite2

### Reproduction link
[https://next.antdv.com/docs/vue](https://next.antdv.com/docs/vue)

### Steps to reproduce
更新到3.0.0-beta.1，提示缺少声明。
看node_modules下少了index.d.ts。
![QQ图片20211225131037](https://user-images.githubusercontent.com/53365470/147377913-56759a10-f44a-4a99-b287-fafb19781a4e.png)

### What is expected?
引用不了组件

### What is actually happening?
可以引用

**Comment by tangjinzhou** [comment]
没安装吧   没复现

**Comment by wishong** [comment]
> 没安装吧 没复现

肯定安装了呀，yarn了好几次了。
您可以删掉node_modules yarn一下看看。
yarn下来只有这些东西
![QQ图片20211225175337](https://user-images.githubusercontent.com/53365470/147382538-498b3304-af28-4af7-a31c-c2c7fab35a33.png)

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/147396588-d63d1e4d-0997-497a-92d7-b25be5f8a172.png)
目前看只有你这边有这个问题，是不是用了一些 npm 镜像，镜像同步出现了问题

**Comment by wishong** [comment]
用同一个镜像地址，npm 和 cnpm 都可以下载完整包，就 yarn 不行，奇怪了😥
