### ISSUE TITLE
When the form-item has a value, the error message still does not disappear

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5086]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.3

### Environment
vue3 vite2

### Reproduction link
[https://next.antdv.com/docs/vue/changelog-cn](https://next.antdv.com/docs/vue/changelog-cn)

### Steps to reproduce
比如封装了一个图片上传组件，且绑定了表单值和rules。
```
<a-form-item label="图标" name="avatar">
    <upload v-model:files="formModel.avatar" type="avatar" :max="1" :width="80" :height="80" />
</a-form-item>
```
当我上传完图片之后，会出现rules中的错误提示，但实际上绑定的值已经存在了。
3.0.0-alpha.16不会出现这个问题，3.0.0-beta.1及后续版本后会出现。

### What is expected?
值存在，但是出现错误提示

### What is actually happening?
不应该出现错误提示

**Comment by tangjinzhou** [comment]
自定义组件的规范在 3.0 中有调整，具体查看文档  https://next.antdv.com/components/form-cn#_3-x

alpha 16  之所以没问题是因为一个错误的”修复“，可以查看这个 issue 
 https://github.com/vueComponent/ant-design-vue/issues/4955 
beta1中进行了回滚

**Comment by wishong** [comment]
ok 已解决 感谢
