### ISSUE TITLE
TextArea setting allowClear causes style issues

### ISSUE THREAD

**Issue by super-hu** [vueComponent/ant-design-vue#5108]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.4

### Environment
vue3.2.26

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/next/components/input/TextArea.tsx](https://github.com/vueComponent/ant-design-vue/blob/next/components/input/TextArea.tsx)

### Steps to reproduce
Modal中表单中嵌入TextArea并设置allowClear，导致边框丢失

### What is expected?
样式正常

### What is actually happening?
边框丢失

![企业微信截图_16409220952381](https://user-images.githubusercontent.com/10434110/147802293-ebd2866c-8a39-44e6-abfd-03be2580bd25.png)

     
![企业微信截图_16409221069637](https://user-images.githubusercontent.com/10434110/147802296-f83ce015-e9ee-4415-8a8d-5ac48f6464d0.png)

**Comment by yangzheli** [comment]
我刚刚测试了一下，没问题啊
<img width="568" alt="截屏2021-12-31 下午4 27 39" src="https://user-images.githubusercontent.com/43645580/147812332-d04e2694-c559-40ff-9a76-262dfb91e838.png">
有没有复现案例

**Comment by super-hu** [comment]
找到问题，是因为在另外工程下之前版本有个覆盖样式的less文件，我们是从V2-V3就出现兼容问题了。已解决
