### ISSUE TITLE
Linter warning in CSS file

### ISSUE THREAD

**Issue by JoepOomens** [vueComponent/ant-design-vue#511]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Vue 2.6.6, ESLint 5.14.1, Nuxt 2.4.3

### Steps to reproduce
Create a project with ant-design-vue and build that using Nuxt & ESLint.

### What is expected?
No compilation warnings

### What is actually happening?
It creates a module warning: "Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed" in ./node_modules/ant-design-vue/dist/antd.css (168:11)

**Comment by tangjinzhou** [comment]
duplicate #485
