### ISSUE TITLE
Table-when there are fixed columns, scrolling is out of sync

### ISSUE THREAD

**Issue by blaze87** [vueComponent/ant-design-vue#5110]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue2.x

### Reproduction link
[https://1x.antdv.com/components/table-cn/#API](https://1x.antdv.com/components/table-cn/#API)

### Steps to reproduce
nodecode

### What is expected?
期望滚动同步

### What is actually happening?
我觉得是监听hover引起的 但我没找到代写在哪里的

**Comment by tangjinzhou** [comment]
若列头与内容不对齐或出现列重复，请指定固定列的宽度 width。如果指定 width 不生效或出现白色垂直空隙，请尝试建议留一列不设宽度以适应弹性布局，或者检查是否有超长连续字段破坏布局。
建议指定 scroll.x 为大于表格宽度的固定值或百分比。注意，且非固定列宽度之和不要超过 scroll.x。


或者 升级到 3.0
