### ISSUE TITLE
antd3.0 version icon component problem

### ISSUE THREAD

**Issue by arlen-s** [vueComponent/ant-design-vue#5112]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
框架的初衷说为了简洁易用，而不是一味的以‘外物皆组件’的思想来做。一个icon为什么要做成组件。做成引用clss有什么弊端隐患吗？极其不灵活。想要动态的的加个图标都很难。如（动态菜单icon）。如果有相关实现的方式。那么麻烦API描述清楚。

### What does the proposed API look like?
vue3.0 ant-design-vue3.0

**Comment by yangzheli** [comment]
[#10353](https://github.com/ant-design/ant-design/issues/10353)
动态使用图标可以使用 [自定义 SVG 图标 ](https://next.antdv.com/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87) 的方式吧

**Comment by tangjinzhou** [comment]
为了按需加载，为了使用 svg 矢量图
但你依然可以使用 iconfont 的模式，只是不再是默认方案

**Comment by Yuweiai** [comment]
结合时事来说，建议对待开源项目礼貌一点（即使已经捐赠）
