### ISSUE TITLE
Modal component adds onOpen onClose event

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5116]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
期望增加onOpen(对话框打开后（动画结束）触发),onClose(对话框关闭后（动画结束）触发) 事件

### What does the proposed API look like?
期望增加onOpen(对话框打开后（动画结束）触发),onClose(对话框关闭后（动画结束）触发) 事件
尽管antdesign没有，但不代表antdesignvue不能有，可以借鉴https://arco.design/vue/component/modal  博采众长
![image](https://user-images.githubusercontent.com/5828057/147879918-e1ab2b38-ad64-4f04-bbac-a8b88e570c13.png)

**Comment by tangjinzhou** [comment]
watch visible 即可

**Comment by juanbrujo** [comment]
```
watch(() => props.visible, (val) => { 
  if (val) {
    ... // is visible true
  }
})
```

**Comment by ZiuChen** [comment]
I need `onOpen` event to achieve similar effect:

```ts
Modal.confirm({
  onOpen() {
    nextTick(() => InpurRef.value?.focus())
  }
})
```
