### ISSUE TITLE
DatePicker time scroll bar optimization

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5117]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
DatePicker  时间滚动条优化
antdv：
![image](https://user-images.githubusercontent.com/5828057/147882497-56dee57f-44ba-4a72-bde0-00cf3cbfc5ed.png)
arco design vue
![image](https://user-images.githubusercontent.com/5828057/147882515-a5ee78d0-68da-4999-aed8-9228b382e2f7.png)

### What does the proposed API look like?
DatePicker  时间滚动条去掉滚动条

**Comment by zkwolf** [comment]
去掉的话就只能滚轮来交互上下滚动了吧？

**Comment by wsxe9988** [comment]
或者美化下滚动条，系统自带的滚动条不太美观

**Comment by tangjinzhou** [comment]
全局配置个滚动条 css 不香吗
