### ISSUE TITLE
The cursor does not change after the upload component setting is disabled

### ISSUE THREAD

**Issue by extclp** [vueComponent/ant-design-vue#5126]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.5

### Environment
Windows11, Chrome96.0.4664.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yi-shang-chuan-de-wen-jian-lie-biao-ant-design-vue-3-0-0-beta-5-forked-x26nc?file=/src/demo.vue)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/24100

`a-button` add disabled prop, like
```html
<a-button disabled></a-button>
```
