### ISSUE TITLE
There are some wrans when add click event on menu that inside the dropdwon

### ISSUE THREAD

**Issue by rocwong** [vueComponent/ant-design-vue#5138]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.5

### Environment
vue 3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/you-jian-cai-dan-ant-design-vue-3-0-0-beta-5-forked-7evm7?file=/src/demo.vue)

### Steps to reproduce
- 问题一: 给dropdown里的menu加click事件，打开下拉时会出现很多warn(功能正常);
- 问题二: dropdown打开时，(不关闭)再一次右键打开下拉，下拉会抽风;

### What is expected?
- 不出现warn (不是我使用上的问题的话)
- dropdown正常显示

### What is actually happening?
如上描述

**Comment by tangjinzhou** [comment]
重复 #5127
