### ISSUE TITLE
嵌套子表格时，将某一列设置成fixed，子表格显示异常

### ISSUE THREAD

**Issue by zhangtaoBqteam** [vueComponent/ant-design-vue#514]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
mac 10.13.3, chorme 68.0.3440.106, vue 2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kx3731o46v)

### Steps to reproduce
点击展开行按钮

### What is expected?
子表格正常显示

### What is actually happening?
子表格显示异常

**Comment by tangjinzhou** [comment]
duplicate #308

**Comment by zhangtaoBqteam** [comment]
所以这是不能这么用，还是后面会完善？

**Comment by tangjinzhou** [comment]
不能这么用
