### ISSUE TITLE
Navigation menu -> single file recursive menu mode="horizontal", the offset position on the left side of the drop-down menu is deviated

### ISSUE THREAD

**Issue by ZhouNick** [vueComponent/ant-design-vue#5143]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-alpha.14

### Environment
window10，chrome96，vue3.0

### Reproduction link
[https://next.antdv.com/components/menu-cn#components-menu-demo-template](https://next.antdv.com/components/menu-cn#components-menu-demo-template)

### Steps to reproduce
1.在antd官网切换到3.0版本，点击组件-导航菜单，选择"单文件递归菜单"，打开CodeSandbox，删除多余代码，修改菜单模式为'horizontal'
2.在右侧看到Navigation 2的下拉菜单偏移位置有偏差

### What is expected?
下拉菜单左侧偏移位置正确，3级菜单上方偏移位置正确

### What is actually happening?
下拉菜单左侧偏移位置有偏差，包括3级菜单上方偏移位置也有偏差
![微信图片_20220111114018](https://user-images.githubusercontent.com/22462099/148877540-27de3a9f-e5ee-4d82-82d3-4275a5c9efd5.png)

**Comment by ZhouNick** [comment]
不用单文件递归是正常的，点击官网的 顶部导航，打开CodeSandbox
![image](https://user-images.githubusercontent.com/22462099/148892247-f3f75fe5-c3c3-471b-8ffc-3bc32d03bcfa.png)

**Comment by tangjinzhou** [comment]
其实是一样的   只是你认为正常的那个左侧没有选中，感知不出来距离

这是正常的，并没有偏移，你可以调整css达到你想要的视觉
```css
.ant-menu-dark.ant-menu-horizontal > .ant-menu-submenu {
padding: 0px;
}
```

**Comment by ZhouNick** [comment]
> 其实是一样的 只是你认为正常的那个左侧没有选中，感知不出来距离
> 
> 这是正常的，并没有偏移，你可以调整css达到你想要的视觉
> 
> ```css
> .ant-menu-dark.ant-menu-horizontal > .ant-menu-submenu {
> padding: 0px;
> }
> ```
之前也想到了，但是没有padding的话会难看，因为有hover的背景效果，里面的字会紧贴两边
![image](https://user-images.githubusercontent.com/22462099/149050162-7b8ad53a-220c-4591-8359-72f0f7407641.png)

**Comment by ZhouNick** [comment]
> 其实是一样的 只是你认为正常的那个左侧没有选中，感知不出来距离
> 
> 这是正常的，并没有偏移，你可以调整css达到你想要的视觉
> 
> ```css
> .ant-menu-dark.ant-menu-horizontal > .ant-menu-submenu {
> padding: 0px;
> }
> ```

谢谢，解决了，看了1.x的菜单，根据1.x 先.ant-menu-horizontal:not(.ant-menu-dark) > .ant-menu-submenu{padding: 0px;}，再把.ant-menu-horizontal:not(.ant-menu-dark) > .ant-menu-submenu .ant-menu-submenu-title {padding: 0 20px}
