### ISSUE TITLE
nested loop of form items validation does not work

### ISSUE THREAD

**Issue by fayeah** [vueComponent/ant-design-vue#5146]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/chu-fa-fang-shi-ant-design-vue-3-0-0-beta-5-forked-hh37l?file=/src/demo.vue)

### Steps to reproduce
input any value of items and then click button

### What is expected?
the corresponding error message disappeared

### What is actually happening?
value comes out to be "undefined"

---
Not sure why, I cannot really startup the demo correctly, but the Point is when the valus of input changes, the logs are always undeifined. Please help to check it.

**Comment by tangjinzhou** [comment]
`v-model:value=`  not  `v-model=`
