### ISSUE TITLE
[Tag component] When the custom color is too light, the content is not displayed clearly

### ISSUE THREAD

**Issue by zlm11** [vueComponent/ant-design-vue#5153]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用Tag组件，当设置的自定义颜色太浅时因为文本颜色固定是白色导致内容显示不清晰。
<a-tag color="#FFECDB">#FFECDB</a-tag>
![image](https://user-images.githubusercontent.com/7533144/149254667-6586317c-4da0-41d0-aac5-c71576136c0a.png)

### What does the proposed API look like?
建议当颜色太浅时对文本颜色进行反转，或者开放设置文本颜色的参数。

**Comment by tangjinzhou** [comment]
css 覆盖不就是api嘛
