### ISSUE TITLE
Modal cannot be vertically centered when footer is set to null

### ISSUE THREAD

**Issue by meesii** [vueComponent/ant-design-vue#5155]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
3.0.0-beta.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-agnesi-o9vd5?file=/src/App.vue)

### Steps to reproduce
modal已经设置centered，但是不能垂直居中，刚好差一个footer的高度

### What is expected?
垂直居中

### What is actually happening?
modal已经设置centered，但是不能垂直居中，刚好差一个footer的高度

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/149338459-ff922b4c-4a92-41d2-97a9-8f694f7c314e.png)

**Comment by meesii** [comment]
> ![image](https://s4.ax1x.com/2022/01/13/7lfheU.png)

你截图看一下像素，上边107px，下边130px。
我把页面缩小就很明显了，截图看下能不能显示
