### ISSUE TITLE
The table is opened in the QQ browser and an error is reported

### ISSUE THREAD

**Issue by 314134925** [vueComponent/ant-design-vue#5156]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
VUE3.0 win10  QQ浏览器10.84（chrome内核）

### Reproduction link
[https://next.antdv.com/components/table-cn#components-table-demo-resizable-column](https://next.antdv.com/components/table-cn#components-table-demo-resizable-column)

### Steps to reproduce
打开 antdesin-vue ,选择table
https://next.antdv.com/components/table-cn#components-table-demo-resizable-column

### What is expected?
展示表格

### What is actually happening?
控制台报错，无法显示

---
官方table 使用qq浏览器报错，修复一下吧

**Comment by tangjinzhou** [comment]
自行添加 polifill
