### ISSUE TITLE
The upload file dialog cannot be invoked in the local development environment of the upload component

### ISSUE THREAD

**Issue by DW961109** [vueComponent/ant-design-vue#5157]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
MACOS 12.0.1    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36   Vue 2.6.11

### Reproduction link
[https://vuecomponent.github.io/issue-helper/?lang=zh](https://vuecomponent.github.io/issue-helper/?lang=zh)

### Steps to reproduce
<a-upload
name="file"
accept="video/*"
:action="env.apiurl_one   '/api/service/uploader'"
:before-upload="beforeUpload"
@change="handleChange"
:showUploadList="false"
:file-list="fileList"
withCredentials
>
<a-button type="primary" size="large">上传素材</a-button>
</a-upload>

### What is expected?
唤起上传文件对话框

### What is actually happening?
无法唤起

---
mac下最新版的Chrome浏览器出现的这个问题，本来是好的，更新浏览器后出现了问题，a-upload 组件在本地开发环境下无法唤起上传文件对话框，生产环境是正常的

**Comment by ggggwffgqeg** [comment]
I had this problem too and rebooted Chrome to fix it
