### ISSUE TITLE
Can Cascader support multiple selection?

### ISSUE THREAD

**Issue by isHidden** [vueComponent/ant-design-vue#5160]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac os, chrome

### Reproduction link
[https://ant.design/components/cascader/#components-cascader-demo-multiple](https://ant.design/components/cascader/#components-cascader-demo-multiple)

### Steps to reproduce
NONE

### What is expected?
https://ant.design/components/cascader/#components-cascader-demo-multiple

Like Antd Cascader supports multiple choices

### What is actually happening?
Multiple selection is not supported

**Comment by zkwolf** [comment]
Duplicate #5063
