### ISSUE TITLE
Which version of antdv should the vue3 project use? @next installed 2.2.8, should I install the beta version?

### ISSUE THREAD

**Issue by TingLen** [vueComponent/ant-design-vue#5161]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
vue3

### Reproduction link
[https://next.antdv.com/docs/vue/getting-started-cn](https://next.antdv.com/docs/vue/getting-started-cn)

### Steps to reproduce
.

### What is expected?
vue3项目应该使用哪个版本的antdv? @next安装下来是2.2.8, 我应该安装的是beta版本吗？

### What is actually happening?
..

**Comment by tangjinzhou** [comment]
2.2.8 和 3.0.0 都支持 vue3.0
