### ISSUE TITLE
vue2,, antd1.7.1, the v-decorator attribute of the form does not take effect under the jsx writing method

### ISSUE THREAD

**Issue by Elliot-Zn** [vueComponent/ant-design-vue#5162]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
              <a-form-item label={item.label} key={i}>
                <a-input v-decorator={['name', { initialValue: '123' }]} />
              </a-form-item>
v-decorator没有生效
### What problem does this feature solve?
可以支持render写法

### What does the proposed API look like?
希望支持render写法

**Comment by zkwolf** [comment]
你要用jsx的话可以参考ant deisign 3.x 的jsx写法用getFieldDecorator, https://3x.ant.design/components/form-cn/#components-form-demo-register

**Comment by Elliot-Zn** [comment]
> 你要用jsx的话可以参考ant deisign 3.x 的jsx写法用getFieldDecorator, https://3x.ant.design/components/form-cn/#components-form-demo-register

在antd deisign1.7.8并不支持getFieldDecorator函数 目前我们的项目无法升级到3

**Comment by zkwolf** [comment]
额，这块比较蛋疼，有时间我给你加个example

**Comment by Elliot-Zn** [comment]
> 你要用jsx的话可以参考ant deisign 3.x 的jsx写法用getFieldDecorator, https://3x.ant.design/components/form-cn/#components-form-demo-register


> 额，这块比较蛋疼，有时间我给你加个example

我正在研究，
