### ISSUE TITLE
Incorrect version of the installed package in the documentation

### ISSUE THREAD

**Issue by Azema4ka** [vueComponent/ant-design-vue#5163]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
https://next.antdv.com/docs/vue/introduce#Installation

### Reproduction link
[https://next.antdv.com/docs/vue/introduce#Installation](https://next.antdv.com/docs/vue/introduce#Installation)

### Steps to reproduce
At the moment when installing as written in the documentation (https://next.antdv.com/docs/vue/introduce#Installation) is installed package version 2.2.8, which is not the correct version, waiting for version 3.0.0-beta.7

### What is expected?
At the moment when installing as written in the documentation (https://next.antdv.com/docs/vue/introduce#Installation) is installed package version 2.2.8, which is not the correct version, waiting for version 3.0.0-beta.7

### What is actually happening?
At the moment when installing as written in the documentation (https://next.antdv.com/docs/vue/introduce#Installation) is installed package version 2.2.8, which is not the correct version, waiting for version 3.0.0-beta.7

**Comment by fahmiegerton** [comment]
I was asked about it too in here https://github.com/vueComponent/ant-design-vue/discussions/5141

**Comment by Azema4ka** [comment]
UP!
