### ISSUE TITLE
Uncaught (in promise) TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by tgy3300** [vueComponent/ant-design-vue#5168]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
win64 miniblink   vue3

### Reproduction link
[https://next.antdv.com/components/table-cn](https://next.antdv.com/components/table-cn)

### Steps to reproduce
Uncaught (in promise) TypeError: Object.fromEntries is not a function

reactivePick @ reactivePick.js:16
setup @ Table.js:461
............

### What is expected?
表格在 win64 miniblink 使用不了

### What is actually happening?
表格在 win64 miniblink 使用不了

**Comment by zkwolf** [comment]
自己引入polyfill兼容一下吧

**Comment by yaoshaohua** [comment]
请问最后如何解决的啊

**Comment by wen81643956** [comment]
是否可以参考element plus修改？哪位大佬给提个pr
<img width="772" alt="image" src="https://user-images.githubusercontent.com/9970475/168536606-aad725ec-1bda-496a-838e-1c8fb11ed6bd.png">
