### ISSUE TITLE
Error when import css

### ISSUE THREAD

**Issue by smallp** [vueComponent/ant-design-vue#5169]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
vue3 vite unplugin-vue-components

### Reproduction link
I'll create one if needed.

### Steps to reproduce
```
import { message } from "ant-design-vue"
import "ant-design-vue/lib/message/style/css"
```

### What is expected?
work fine.

### What is actually happening?
`Uncaught Error: Dynamic require of "/Users/xiaoping/Documents/t/process/node_modules/.pnpm/ant-design-vue@3.0.0-beta.7_vue@3.2.26/node_modules/ant-design-vue/lib/style/index.css" is not supported`

**Comment by smallp** [comment]
Changing lib to es works fine. So please update the [document](https://next.antdv.com/docs/vue/getting-started-cn).

**Comment by zkwolf** [comment]
主要还是因为用了vite吧，看了一眼unplugin-vue-components插件的规则默认也是引用es下的

**Comment by smallp** [comment]
是的，我就是看了那个插件发现引用es，就尝试了一下好了。
