### ISSUE TITLE
DirectoryTree: [Vue warn]: Slot "default" invoked outside of the render function

### ISSUE THREAD

**Issue by think-gem** [vueComponent/ant-design-vue#5170]
- [  ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
win、chrome92、vue3

### Reproduction link
<https://gitee.com/thinkgem/jeesite-vue/blob/master/src/components/Tree/src/Tree.vue#L578>

### Steps to reproduce
The tree directory warns when using TSX:

```
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.
at <ADirectoryTree>
at <Tree>
......
```

will
```
const TreeComp = showIcon ? Tree.DirectoryTree : Tree;
```
change
```
const TreeComp = Tree;
```
after modification，no warning.

But I hope, use `DirectoryTree` no warning. 

Old issues: https://github.com/vueComponent/ant-design-vue/issues/5013

### What is expected?
There is no warning

### What is actually happening?
A warning  [Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.

**Comment by tangjinzhou** [comment]
建议改成 treeData 的数据源的写法

**Comment by tangjinzhou** [comment]
或者升级 vue 试试，我没复现
and，你要提供一个最小化代码复现，而不是给我一个大型项目去排查问题

**Comment by think-gem** [comment]
> 建议改成 treeData 的数据源的写法

谢谢回复。好的，因为有一些数据还需要处理，如果改为 treeData 前端还需要再次递归处理数据，我看了antdv 3也只能支持treeData了，我先试一下这种方式，看看结果。

最小化的复现代码，就是我上次提的 issues，放到 ts vue3 的工程里就可以运行。https://github.com/vueComponent/ant-design-vue/issues/5013

**Comment by think-gem** [comment]
谢谢回复。好的，因为有一些数据还需要处理，如果改为 treeData 前端还需要再次递归处理数据，我看了antdv 3也只能支持treeData了，我先试一下这种方式，看看结果。


最小化的复现代码，就是我上次提的 issues，放到 ts vue3 的工程里就可以运行。https://github.com/vueComponent/ant-design-vue/issues/5013
On 1/17/2022 ***@***.***> wrote：

建议改成 treeData 的数据源的写法

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by think-gem** [comment]
> 建议改成 treeData 的数据源的写法

谢谢回复。好的，因为有一些数据还需要处理，如果改为 treeData 前端还需要再次递归处理数据，我看了antdv 3也只能支持treeData了，我先试一下这种方式，看看结果。

最小化的复现代码，就是我上次提的 issues，放到 ts vue3 的工程里就可以运行。https://github.com/vueComponent/ant-design-vue/issues/5013

**Comment by think-gem** [comment]
@tangjinzhou  修改为 treeData 可行，没有警告了，谢谢。https://gitee.com/thinkgem/jeesite-vue/commit/ac627b2e1af8611172aba2190d8009d05d9020ad
