### ISSUE TITLE
The column in the table didn't show up in any breakpoint when set prop responsive

### ISSUE THREAD

**Issue by fahmiegerton** [vueComponent/ant-design-vue#5171]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
Windows 10 Home x64, Microsoft Edge 97.0.1072.55 x64, Vue 3.0.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-3-0-0-beta-5-forked-3pqn7)

### Steps to reproduce
When I set `responsive` prop in one of the column like `column: ['md']`, the column is just disappear in any breakpoints. If I remove this prop, the column is shown again.

### What is expected?
When set `responsive` prop in the column, it should be appear according the breakpoint that has been set, like this thread https://stackoverflow.com/questions/65508782/how-to-make-ant-design-table-responsive/65529726?noredirect=1#comment125007029_65529726, but tried with ant vue design 3, it didn't show up in any display width size

### What is actually happening?
The column is disappear in every breakpoint even just set only one breakpoint like `md` and will not shown in all display size

related thread https://github.com/vueComponent/ant-design-vue/discussions/5122

**Comment by fahmiegerton** [comment]
Great now it solved, thanks, but how do I get this fix? tried update it and reinstall still the same bug, or will it release on the next beta?

**Comment by zkwolf** [comment]
It will be fixed in next release.
