### ISSUE TITLE
in a-table component 'filtered' parameter in filterIcon slot returns wrong value

### ISSUE THREAD

**Issue by rong4188** [vueComponent/ant-design-vue#5173]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
chrome 96

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/txff0)

### Steps to reproduce
the behavior in document in incorrect as well. the custom filter icon is always blue, we expect it to be blue only when filtered. see [document](https://2x.antdv.com/components/table-cn#components-table-demo-custom-filter-panel)
`https://2x.antdv.com/components/table-cn#components-table-demo-custom-filter-panel`

### What is expected?
return correct value

### What is actually happening?
always return true

**Comment by tangjinzhou** [comment]
doc error update `#filterIcon="filtered"` to `#filterIcon="{filtered}"`
