### ISSUE TITLE
When the `scroll = { x: True }`attribute is added to the table, ellipsis fails

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [vueComponent/ant-design-vue#5174]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
chrome 96 vue2.6.11 window10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-wave-n356x?file=/src/components/HelloWorld.vue)

### Steps to reproduce
It’s obvious from the dome

### What is expected?
Add scroll = { X: true } to the table and hope the ellipsis attribute works

### What is actually happening?
Nothing’s changed

**Comment by tangjinzhou** [comment]
add
```html
<style>
.ant-table td {
  white-space: nowrap;
}
.ant-table-fixed {
  width: 100% !important;
}
</style>
```
