### ISSUE TITLE
Can't use dark theme with vue-router

### ISSUE THREAD

**Issue by ZhangWei12138** [vueComponent/ant-design-vue#5182]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
Vite   ts   vue3   Vue-Router

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-thompson-3yc0m?file=/src/App.vue)

### Steps to reproduce
1. Use dark theme
2. Use vue router
3. Use antd component

### What is expected?
Show dark theme

### What is actually happening?
Show light theme

**Comment by tangjinzhou** [comment]
theme and router，This is a function of no relation and will not have any effect.

you should provide more information

**Comment by ZhangWei12138** [comment]
> 

But is happend ,when i use Modal in router-view . Modal is light , not dark
You can see reproduction link

**Comment by ZhangWei12138** [comment]
ok ,i solved it. 
vite config:
```
 plugins: [
      vue(),
      vueJsx(),
      Components({
        resolvers: [AntDesignVueResolver({ importStyle: false })]
      }),
]
```
