### ISSUE TITLE
Color attribute for Buttons

### ISSUE THREAD

**Issue by Bradley-H** [vueComponent/ant-design-vue#5183]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
The feature would give more control to the developer. Currently, buttons only have 4 options ( primary, danger, dashed, and link ), sometimes our projects may require more control such as a certain color scheme, for example - may be in a project i require a button with a purple background color.

### What does the proposed API look like?
Wouldn't take much, just take the type attribute and allow hex or RGBA values.

So for example <a-button type="#3a71b6">testing</a-button>

**Comment by tangjinzhou** [comment]
please use `class` or `style` to set more color
