### ISSUE TITLE
Rendering tree structure in table component

### ISSUE THREAD

**Issue by zhangjing007** [vueComponent/ant-design-vue#5185]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当table中渲染树结构的时候，数据结构可能为每一层极不管是否有子集，可能都有children字段，只不过如果是末级节点的话，children为一个空数组，这样一来的话，前面展开收起的图标就不对了。期望能够考虑到这种情况

### What does the proposed API look like?
期望组件能通过判断children长度是否大于0，来渲染展开、收起的图标

**Comment by tangjinzhou** [comment]
不考虑，自行判断 children
还有更多人的场景是只要有 children 就显示折叠，方便异步加载
