### ISSUE TITLE
Datepick combined with moment invalid date

### ISSUE THREAD

**Issue by xlanghejianfeng** [vueComponent/ant-design-vue#5189]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Environment
vue:3.2.27

### Reproduction link
[https://next.antdv.com/components/date-picker-cn](https://next.antdv.com/components/date-picker-cn)

### Steps to reproduce
选择日期格式问题

### What is expected?
日期控件兼容moment日期格式，项目替换dayjs代价比较大

### What is actually happening?
moment日期选择 format等问题

**Comment by tangjinzhou** [comment]
https://next.antdv.com/docs/vue/replace-date-cn
