### ISSUE TITLE
Button type dashed no working

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#519]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
mac OS / chrome / latest / vue:2.5.22

### Reproduction link
[https://github.com/Afondevi/vue-renter](https://github.com/Afondevi/vue-renter)

### Steps to reproduce
`<a-button type="dashed">Dashed</a-button>`

### What is expected?
apprear dashed button like a doc

### What is actually happening?
appear normal button

**Comment by tangjinzhou** [comment]
give me valid Reproduction link ？

**Comment by Afondevi** [comment]
don't have .. and don't know how do that

**Comment by tangjinzhou** [comment]
I can't help you, I can't reproduce your problem.

**Comment by Afondevi** [comment]
hum..

**Comment by Afondevi** [comment]
did you have codesandbox for vuejs ?

**Comment by Afondevi** [comment]
ok sorry it's my css..

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/2wpk21kzvr
