### ISSUE TITLE
The dialog component is not compatible with the latest vue

### ISSUE THREAD

**Issue by extclp** [vueComponent/ant-design-vue#5190]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vdf8j)

**Comment by tangjinzhou** [comment]
update to 3.0.0-beta.8
