### ISSUE TITLE
vue-cli 3 配置 babel-plugin-import { style: true } 报错

### ISSUE THREAD

**Issue by Arman19941113** [vueComponent/ant-design-vue#520]
按官方文档修改babel.config.js文件，配置 babel-plugin-import 报错如下（安装了less的）
```js
module.exports = {
    presets: [
        '@vue/app'
    ],
    plugins: [
        [
            "import",
            {libraryName: "ant-design-vue", libraryDirectory: "es", style: true}
        ]
    ]
}
```
![image](https://user-images.githubusercontent.com/35905177/53241185-e3da8f00-36db-11e9-8420-8da5f00f806d.png)
如果把 true 改成 "css" 也会有警告
![image](https://user-images.githubusercontent.com/35905177/53241296-374cdd00-36dc-11e9-971e-1ae9dd9db771.png)

**Comment by wangxueliang** [comment]
请翻看之前issues，有类似问题哈

**Comment by tangjinzhou** [comment]
Your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://vuecomponent.github.io/issue-helper/) to create an issue, thank you!  <br/><br/> 为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://vuecomponent.github.io/issue-helper/) 来创建 issue 以方便我们定位错误。谢谢配合！

**Comment by Arman19941113** [comment]
找完了没看啊，可以给个链接吗

三点包子 <notifications@github.com> 于2019年2月23日周六 上午10:41写道：

**Comment by haledc** [comment]
需要这样设置，不要安装less 和less-loader
module.exports = {
  presets: ['@vue/app'],
  plugins: [['import', { libraryName: 'ant-design-vue' }, 'ant-design-vue']]
}
另外还要再全局引用样式。
import 'ant-design-vue/dist/antd.css'
建议尽快修改文档吧。

**Comment by wangxueliang** [comment]
#68

**Comment by Arman19941113** [comment]
你这是引入全局样式，我是想局部引入。。

Hale Deng <notifications@github.com> 于2019年2月26日周二 下午7:19写道：

**Comment by Arman19941113** [comment]
这个issue是全局引入css样式。。。

三点包子 <notifications@github.com> 于2019年2月26日周二 下午7:22写道：

**Comment by tangjinzhou** [comment]
不同问题请分开提issue，多谢
less问题参考这个配置 https://vue.ant.design/docs/vue/customize-theme-cn/#%E5%9C%A8-vue-cli-3%E4%B8%AD%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98
