### ISSUE TITLE
Offcial website docs issue

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#5205]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
offcial website

### Reproduction link
[https://next.antdv.com/docs/vue/getting-started-cn](https://next.antdv.com/docs/vue/getting-started-cn)

### Steps to reproduce
open https://next.antdv.com/docs/vue/getting-started-cn, see screenshort below.

### What is expected?
correct code in doc

### What is actually happening?
it is not

![image](https://user-images.githubusercontent.com/7044628/150773619-9069b53b-f242-4da3-98d5-665b0fcb218b.png)

--
same issue in 2.x docs

https://2x.antdv.com/docs/vue/getting-started-cn

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/95ce5f4eb113b49f8c7ec69a7b27d88e37ba96ee
