### ISSUE TITLE
The fieldNames property of treeSelect is invalid

### ISSUE THREAD

**Issue by balck-paint** [vueComponent/ant-design-vue#5206]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
win10、chrome 97.0.4692.99、vue 3.2.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tyyqh?file=/src/demo.vue)

### Steps to reproduce
简单来说fieldNames不起作用，想将titile替换为name

### What is expected?
替换字段名

### What is actually happening?
fieldNames不起作用

**Comment by JobinJia** [comment]
不晓得为啥这个codesandbox我打开后，一直跑不起来，但是看提供的示例上的 是写的 name: 'title' ，但是文档上是写的
![image](https://user-images.githubusercontent.com/9244703/150895187-69a40c6a-6fca-42fb-9d5e-50fa845fb2b8.png)
所以正确的应该是 label: 'title'
便你的示例上对应的数据的结构是 
```
const treeData = ref<TreeSelectProps["treeData"]>([
      {
        name: "parent 1",
        value: "parent 1",
        children: [
          {
            name: "parent 1-0",
            value: "parent 1-0",
            children: [
              {
                name: "my leaf",
                value: "leaf1",
              },
              {
                name: "your leaf",
                value: "leaf2",
              },
            ],
          },
          {
            name: "parent 1-1",
            value: "parent 1-1",
          },
        ],
      },
    ]);
```

所以正确的应该是 
```
:fieldNames="{
      children: 'children',
      name: 'title', // 这里应该是 label: 'name'
      key: 'key', // 数据中没有对应key的属性
      value: 'value',
    }"
```

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-0-0-beta-8-forked-2tsxd?file=/src/demo.vue

**Comment by balck-paint** [comment]
@JobinJia 感谢，可以了。可能是我理解的有问题，文档中写道

替换 treeNode 中 title,value,key,children 字段为 treeData 中对应的字段 | object | {children:'children', label:'title', key:'key', value: 'value' }

这样理解下来是将 title替换为 label,也就是是说{ 想代替的名称放前面：被替换的名称放后面}
但是现在的替换是要这样写 {children:'children', label:'name', key:'key', value: 'value' } ，不是很理解。文档也没有相关示例，很难这样写
