### ISSUE TITLE
Invalid VNode type: undefined (undefined) on Select component with search when the value of the option is an object

### ISSUE THREAD

**Issue by fahmiegerton** [vueComponent/ant-design-vue#5208]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
Windows 10 Home Version 21H1 (Build 19043.1466), Microsoft Edge 97.0.1072.69 (Official build) (64-bit), Vue 3.0.5, @inertiajs/inertia-vue3 0.6.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-with-search-field-ant-design-vue-3-0-0-beta-8-forked-if4j9?file=/src/demo.vue)

### Steps to reproduce
1. Click on select component, then it shows the list in dropdown
2. Select one of the option
3. Then in the console, there's a warning from vue `Invalid VNode type: undefined (undefined)` on the `<OptionList />`

### What is expected?
No warn

### What is actually happening?
there's a warning from vue `Invalid VNode type: undefined (undefined)` on the `<OptionList />` when one of the option is selected

---
This happens only when the value of the option is an object, but not with string or int. But I check on vue devtools, it assign just fine. The v-model I initialize as null. Like this:
```
const form = ref({
     value: null
});
```
and it store to the variable just fine
```
const form = ref({
     value: {
        id: 1,
        name: 'jack'
        age: 12
    }
});
```

idk what cause this warn, but either I should initialize it as `[]` or else. Thanks

**Comment by fahmiegerton** [comment]
I check where the error occurred, the `value` (v-model) expect only string or number, and nothing else. But in the docs it accept `string|number|string[]|number[]`

![image](https://user-images.githubusercontent.com/5303871/150905845-1739bdd4-2e68-416a-9ef0-66924991e9e4.png)

**Comment by fahmiegerton** [comment]
I'm so dumb, it's not supported to returning as an object isn't? can it be a feature request?

**Comment by fahmiegerton** [comment]
Oh God, it won't support return as an object, isn't? https://github.com/ant-design/ant-design/issues/2857

**Comment by tangjinzhou** [comment]
value only support string or number

**Comment by fahmiegerton** [comment]
> value only support `string | number | string[] | number[]`

is there any chance in the future that it would be supported in the next version? like vuetify does in here https://vuetifyjs.com/en/api/v-select/#props-items
