### ISSUE TITLE
use required in v-for with v-model

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#521]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
mac OS / chrome / latest / vue:2.5.22

### Reproduction link
[https://github.com/Afondevi/vue-renter](https://github.com/Afondevi/vue-renter)

### Steps to reproduce
..

### What is expected?
..

### What is actually happening?
Sorry but it not a really bug but personnal probléme.

I have form and loop on object `prices`
I have 1 field for `price.name` and one for `price.value`
The user can add new price ( push object new price in  prices) or delete price if he want.

The question is : How can I use `required` field with message if is empty, without use `v-decorator` because `v-decorator` is really limited !
I need to use v-model to show existing price from database, or update or add new one.

I really don't manage to do that..
Thanks for help

<img width="734" alt="capture d ecran 2019-02-22 a 14 42 58" src="https://user-images.githubusercontent.com/11740298/53246168-34d48e00-36b0-11e9-963a-c7d3bdc66126.png">

**Comment by tangjinzhou** [comment]
It is recommended to use `v-decorator`, refer to demo: https://vue.ant.design/components/form/#components-form-demo-dynamic-form-item.
If you not use `v-decorator`, you can refer this demo: https://vue.ant.design/components/form/#components-form-demo-customized-validation

**Comment by Afondevi** [comment]
thanks :), the second one do the job I think
