### ISSUE TITLE
AutoComplete component setting optionLabelProp invalid

### ISSUE THREAD

**Issue by yuyang1004** [vueComponent/ant-design-vue#5212]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
3.0.0-beta.8 vue3

### Reproduction link
[https://vuecomponent.github.io/issue-helper/?lang=zh](https://vuecomponent.github.io/issue-helper/?lang=zh)

### Steps to reproduce
<a-auto-complete
:options="bookingUserList"
v-model:value="formState.orderName"
:not-found-content="bookingUserFetching ? undefined : null"
:allowClear="true"
:backfill="true"
@select="onSelectBookingUser"
optionLabelProp="mobile"
>

### What is expected?
选择后是否应该是mobile属性的值

### What is actually happening?
返回的还是value的值

**Comment by yuyang1004** [comment]
https://codesandbox.io/s/spring-mountain-r7rfg?file=/src/components/HelloWorld.vue
https://r7rfg.csb.app/

**Comment by yuyang1004** [comment]
> Hello @yuyang1004. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @yuyang1004, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

https://codesandbox.io/s/spring-mountain-r7rfg?file=/src/components/HelloWorld.vue
https://r7rfg.csb.app/

**Comment by yuyang1004** [comment]
https://codesandbox.io/s/spring-mountain-r7rfg?file=/src/components/HelloWorld.vue
https://r7rfg.csb.app/

**Comment by tangjinzhou** [comment]
这是一个漏掉写进文档的破坏性更新，AutoComplete 不再支持 `optionLabelProp` 属性了

**Comment by yuyang1004** [comment]
> 是一个漏掉写进文档的破坏性更新，AutoComplete 不再支持 `optionLabelPro`

有替换方案吗？

**Comment by tangjinzhou** [comment]
直接使用  value字段存储  mobile 数据
