### ISSUE TITLE
TreeSelect number selection in the case of multiple selections, enter and return to appear empty Tag

### ISSUE THREAD

**Issue by yundmb** [vueComponent/ant-design-vue#5217]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.8

### Environment
vue version: 3.2.27

### Reproduction link
[https://next.antdv.com/components/tree-select-cn#components-tree-select-demo-basic](https://next.antdv.com/components/tree-select-cn#components-tree-select-demo-basic)

### Steps to reproduce
TreeSelect 数选择开启多选模式
直接回车，会出现空的Tag

### What is expected?
不应该出现空Tag

### What is actually happening?
是个BUG吧？

---
-

**Comment by zkwolf** [comment]
我感觉像是bug
