### ISSUE TITLE
Many components should be optimized for this problem or I don't quite understand why it is designed like this

### ISSUE THREAD

**Issue by Axu96** [vueComponent/ant-design-vue#5218]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
树形选择控件和下拉选择框，value	默认根据此属性值进行筛选（其值在整个树范围内唯一），为什么会默认根据value去筛选呢，value一般都是id  用户输入id筛选？用户既然看到的是label那就应该根据label筛选啊，作为用户你知道下拉框后面的value是什么值吗？

### What does the proposed API look like?
默认根据label进行筛选

**Comment by tangjinzhou** [comment]
1、label 是可选值
2、即便label合理，但更改api影响较大
