### ISSUE TITLE
After the treeselect component selects item

### ISSUE THREAD

**Issue by boot-vue** [vueComponent/ant-design-vue#5220]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
vue3

### Reproduction link
[https://next.antdv.com/components/tree-select-cn](https://next.antdv.com/components/tree-select-cn)

### Steps to reproduce
随便点一个demo,  选中一条item
触摸板再次点击选择框,  tree树形下拉框会闪烁

### What is expected?
像鼠标操作一样丝滑

### What is actually happening?
触摸板操作忒难受了

**Comment by tangjinzhou** [comment]
mac ?
没复现，可以录制个视频看看

**Comment by boot-vue** [comment]
https://user-images.githubusercontent.com/36025992/152637988-1f924a51-4fd8-4fd7-b442-b854d5684cf2.mp4


windows下 笔记本触摸板表现

**Comment by boot-vue** [comment]
https://user-images.githubusercontent.com/36025992/152638130-0d7d7642-50bb-47de-83a3-74214588972c.mp4


windows下 鼠标操作比较顺畅 


可以参考一下ant design react的实现   他们的鼠标  触摸板  操作都流畅

**Comment by tangjinzhou** [comment]
我没复现，方便的话可以帮助我们进一步定位吗
另外提交了一个可能相关的改动，https://github.com/vueComponent/ant-design-vue/commit/ad06a9ee058db76e6324bfb20ce09640b196dcbd   你可以试试是否可以解决问题

**Comment by boot-vue** [comment]
> 我没复现，方便的话可以帮助我们进一步定位吗 另外提交了一个可能相关的改动，[ad06a9e](https://github.com/vueComponent/ant-design-vue/commit/ad06a9ee058db76e6324bfb20ce09640b196dcbd) 你可以试试是否可以解决问题

试了一下不行,  前端这块

`1.7.8`  `2.2.8`  版本 windows触摸板操作都表现ok  

我的笔记本 `Dell G7   Win10`  , 就触摸板操作别扭 ,  鼠标 键盘操作都ok

**Comment by tangjinzhou** [comment]
我用mac点按触控板触发了一样的问题，方便的话你试试是否可以解决windows 这个问题  @boot-vue

**Comment by boot-vue** [comment]
> added


`ok`      正常了
