### ISSUE TITLE
DatePicker has weird behavior with manual typing using date-fns

### ISSUE THREAD

**Issue by JeromeDeLeon** [vueComponent/ant-design-vue#5221]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-3-0-0-beta-9-forked-rcehv)

### Steps to reproduce
1. Select any date using the date picker
2. Manually update the date with input

### What is expected?
The cursor should stay where you are typing

### What is actually happening?
The cursor is moving around like going at the end of the input

**Comment by JeromeDeLeon** [comment]
Thank you @tangjinzhou for fixing this. May I know when will the next release that includes this fixed?

**Comment by tangjinzhou** [comment]
in about a week.
Actually you also can refer to `data-fns.tsx` to customize a component to solve this problem

**Comment by JeromeDeLeon** [comment]
@tangjinzhou Should I wait for a day for the build to reflect? I just tested it using the latest release and the bug still happening.
Here's the [CSB](https://codesandbox.io/s/basic-usage-ant-design-vue-3-0-0-beta-9-forked-oj9rk1?file=/src/demo.vue).
