### ISSUE TITLE
The 3.0.0-beta.5 version has been used, why is the color picker still unavailable?

### ISSUE THREAD

**Issue by daisy-cyt** [vueComponent/ant-design-vue#5227]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
已经是3.0.0-beta.5版本，看到之前issue说3.0版本会增加，目前源码中看到color picker组件，但是没有导出无法使用，文档中也没有，想问下这个组件大概什么时候可以正式使用呢？

### What does the proposed API look like?
使用该组件

**Comment by tangjinzhou** [comment]
日期待定，或许 3.1 3.2 
推荐使用 https://github.com/Simonwep/pickr   不依赖任何库
