### ISSUE TITLE
Reload table checkbox props when data changes

### ISSUE THREAD

**Issue by Nisgrak** [vueComponent/ant-design-vue#5228]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Vue 3.2.30, Chrome 98, Windows 10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-ant-design-vue-next-forked-nny78)

### Steps to reproduce
- Create a table with data-source
- Set the getCheckboxProps of row-selection
- Update the data in the array
- The disabled checkbox didn't update

### What is expected?
The disabled checkbox changes from row 4 to row 3

### What is actually happening?
When the data of the `data-source` of a ATable changes the `getCheckboxProps` don't update, so the disable checkbox is wrong

---
Maybe a function to call with a ref to recheck the condition would be nice, if don't want to make reactive.

**Comment by tangjinzhou** [comment]
you can use new key for table.
And we recommend update antdv to 3.0

**Comment by Nisgrak** [comment]
Using `:rowKey="a => a.id + a.name"` and add relevant fields works yes.

I'm waiting the exit of the beta!
