### ISSUE TITLE
PostCSS should be updated to latest version

### ISSUE THREAD

**Issue by mediatec** [vueComponent/ant-design-vue#523]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
Any OS, Any Browser

### Reproduction link
[https://i.gyazo.com/1006537c34f74d7501c803c73a6629ee.png](https://i.gyazo.com/1006537c34f74d7501c803c73a6629ee.png)

### Steps to reproduce
Create a Vue project with PostCSS feature and inject ant-design-vue styles to the project.

### What is expected?
No warnings

### What is actually happening?
Warning
(160:11) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed
@ ./node_modules/ant-design-vue/es/style/index.css

Its related to https://github.com/postcss/autoprefixer/issues/1179

**Comment by tangjinzhou** [comment]
#485
