### ISSUE TITLE
Can not select a item by clicking the item in mention component

### ISSUE THREAD

**Issue by mehunk** [vueComponent/ant-design-vue#5233]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
Mac 12.1, Chrome 98, Vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mention-bug-1ikyy)

### Steps to reproduce
输入 @，点击弹出框里面的选项，没有选中点击的选项

### What is expected?
应该选中点击的选项

### What is actually happening?
看了一下 ant design react 的代码，逻辑上应该是出发 DropdownMenu.jsx 文件下的 onFocus 事件，但实际上该事件没有触发

**Comment by tangjinzhou** [comment]
没懂，不能选中？

**Comment by mehunk** [comment]
你用官网的例子试一下就知道了，可以按回车选择元素，但是点击鼠标就不能，弹出框一下就消失了，我对比了一下 React 的组件，感觉应该是元素上没有加上 tabindex 属性，导致 dropwdownMenu 里的 onFocus 和 onBlur 事件没有触发。我也试着加上这个属性还是没有成功。

**Comment by tangjinzhou** [comment]
你看直接在官网上有问题吗 ，我这没问题啊

**Comment by mehunk** [comment]
![QQ20220217-114110-HD](https://user-images.githubusercontent.com/10388497/154400961-48a0715f-0667-42fc-999e-e81c3d503dab.gif)

**Comment by mehunk** [comment]
我用了三个浏览器（Chrome/Edge/Firefox），还用了同事的电脑，都是这个问题啊，Ant Design React 就没有这个问题，我也往上加了 tabindex 属性，还是不行。你要是方便的话可以加我微信，mehunk

**Comment by wubiandaxian** [comment]
> 我没能复现，方便的话可以帮助我们进一步定位下吗

试了很多次 ，鼠标点击选项的时候左键不要松开，就可以复现了（输入框会失去焦点），快速的点击是能够正常选中的。
