### ISSUE TITLE
Ant Design Vue 1.7.8 Select component, when combined with search and remote data, the input search content value is bound to the requirements.

### ISSUE THREAD

**Issue by mr-chk** [vueComponent/ant-design-vue#5236]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1、目前用户在输入框输入的内容无法被限制，如果提供一些api并且提供与该输入绑定的属性，那么开发可以有更大的发挥空间。
2、注意到与之类似的组件有AutoComplete，但两者使用有区别，依然具有局限性。

### What does the proposed API look like?
最重要的是提供与该输入值绑定的属性。

**Comment by tangjinzhou** [comment]
1.x 版本不再添加新功能，只修复bug
你可以升级3.x 版本
