### ISSUE TITLE
Form 中的switch开关无法设置默认值

### ISSUE THREAD

**Issue by wry5560** [vueComponent/ant-design-vue#524]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
win10 x64，vue 2.5.21

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6l5myp5x9k)

### Steps to reproduce
https://codesandbox.io/s/6l5myp5x9k
设置默认值后，开关显示不正常

### What is expected?
设置默认值开关显示正常

### What is actually happening?
设置默认值开关显示正常

**Comment by tangjinzhou** [comment]
提供有效的复现链接

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/91xy0m69lp

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/53285584-257f3e80-379d-11e9-94f1-557122e01065.png)
