### ISSUE TITLE
How does the tree select component turn off virtual scrolling

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5242]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
vue3

### Reproduction link
[https://next.antdv.com/components/tree-select-cn](https://next.antdv.com/components/tree-select-cn)

### Steps to reproduce
使用TreeSelect ，数据较多时会默认使用虚拟滚动
但是虚拟滚动的滚动条只有滚动时才存在，所以想使用css滚动条
看文档使用 dropdownMatchSelectWidth:false 可以关闭，但实际上不行

### What is expected?
虚拟滚动未被关闭

### What is actually happening?
关闭虚拟滚动

**Comment by tangjinzhou** [comment]
先直接使用 virtual= false

**Comment by wishong** [comment]
已解决 感谢
