### ISSUE TITLE
Switch component animation jitter

### ISSUE THREAD

**Issue by know-that** [vueComponent/ant-design-vue#5245]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
windows11   chrome  98.0.4758.82   vue2.6.14

### Reproduction link
[https://antdv.com/components/switch-cn](https://antdv.com/components/switch-cn)

### Steps to reproduce
Compare the switch component of react on the official website with the component of Vue version

### What is expected?
The switch component of react does not have any exceptions，Please keep the same effect as the react version。

### What is actually happening?
Switch component animation jitter

---
Please compare the examples of the following two official websites：

[React](https://antdv.com/components/switch-cn)  [Vue](https://antdv.com/components/switch-cn)

**Comment by tangjinzhou** [comment]
please update to antdv@3.x
