### ISSUE TITLE
How to get the native e in the focus method of the input-number component in 3.0.0-beta.9

### ISSUE THREAD

**Issue by Zengwy-zmc** [vueComponent/ant-design-vue#5246]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
2的版本中input-number组件调用focus方法可以直接获取原生e去修改target的value, 升级3的版本后不支持了吗

### What does the proposed API look like?
vue版本

**Comment by tangjinzhou** [comment]
使用 v-model。
另外，直接修改 target.value 是不合规的

**Comment by Zengwy-zmc** [comment]
那我想获取组件的位置或者样式等其他内部信息，没有抛出原生e/event，我怎么去获取，为啥3版本不抛出这些了，是出于什么考虑
