### ISSUE TITLE
Duplicate text in switch component documentation API

### ISSUE THREAD

**Issue by Epic-Deno** [vueComponent/ant-design-vue#5248]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue version: vue 3.0.1 , browser version: chrome 98.0.4758.80（正式版本）

### Reproduction link
[https://2x.antdv.com/components/switch-cn](https://2x.antdv.com/components/switch-cn)

### Steps to reproduce
API文档

### What is expected?
API文档只显示：一个unCheckedChildren	非选中时的内容

### What is actually happening?
现在API文档只显示两个unCheckedChildren	非选中时的内容
![image](https://user-images.githubusercontent.com/74635349/154031888-e2d6fbac-f06e-4fda-82ac-e46784cdfd43.png)

**Comment by xiongmao86** [comment]
Hello there,  I have tried to find the right documents location to fix error, but the docs in `next` branch seem to be OK. When I check out `2.x`, the submodule I think documents of `swtich` component reside in, doesn't seem to be fetchable.

**Comment by xiongmao86** [comment]
Forget to say, I have checked the `2.2.8` version, `v2-doc` directory is also missing, cannot `git submodule update`.

**Comment by tangjinzhou** [comment]
OK，so sorry. I forget v2 doc is private repo
