### ISSUE TITLE
Fixed column of table enabled Ellipsis shadow failure problem

### ISSUE THREAD

**Issue by xiaowenlai** [vueComponent/ant-design-vue#5249]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
winows 10  chorme 98.0.4758.82 vue3.2.9

### Reproduction link
[http://nolink](http://nolink)

### Steps to reproduce
Fixed column of table enabled Ellipsis shadow failure problem

### What is expected?
Remarks in this document

### What is actually happening?
Shadow of the failure

**Comment by tangjinzhou** [comment]
and please update to 3.x
