### ISSUE TITLE
tabs type=card时 size无效

### ISSUE THREAD

**Issue by whenevery** [vueComponent/ant-design-vue#525]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
浏览器

### Reproduction link
[https://vue.ant.design/components/tabs-cn/](https://vue.ant.design/components/tabs-cn/)

### Steps to reproduce
任何情况

### What is expected?
type=card时 size能正常切换大小

### What is actually happening?
type=card时 size无效

**Comment by sendya** [comment]
你好，经过测试。是有效果的哦
具体可以点开下方 `CodeSandbox` 链接：
[![](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/62vq1vkmrk?fontsize=14)
