### ISSUE TITLE
datePicker  use  a-month-picker cant set Chinese

### ISSUE THREAD

**Issue by ZhouShiXiong** [vueComponent/ant-design-vue#5257]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
win10、chrome least、Vue2.6.11

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/](https://www.antdv.com/components/date-picker-cn/)

### Steps to reproduce
根据文档设置locale 月份依然为英文

### What is expected?
月份为中文

### What is actually happening?
设置无法正常生效

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/config-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-ConfigProvider-locale%EF%BC%8C%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F
