### ISSUE TITLE
The modal cancel event can't emit

### ISSUE THREAD

**Issue by FFFFof7** [vueComponent/ant-design-vue#5260]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
vue3.2.23    chrome98.0.4758.102   win10;

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-elion-699eqh?file=/src/main.js)

### Steps to reproduce
cancel event emit and console 'cancel emit'

cancel事件触发并且打印cancel emit

### What is expected?
cancel event emit and console 'cancel emit'

cancel事件触发并且打印cancel emit

### What is actually happening?
cancel event not emit

cancel事件没有触发

---
If maskClosable is set to false than click the mask, the cancel event will not be emitted. The document is user click mask instead of model close. Sometimes we need to show some tips before the modal is closed.

如果设置maskClosable为false然后点击遮罩, cancel事件不会触发。文档里面为用户点击遮罩而并非modal关闭。有时候我们需要在关闭之前展示一些提示。

**Comment by tangjinzhou** [comment]
你这个场景不设置 maskClosable 为 false 就好了
根据 cancel 事件参数就可以判断点击的元素来区分点击的触发区域
