### ISSUE TITLE
range-picker component's autofocus attribute has no effect when setting it as true

### ISSUE THREAD

**Issue by Gcalolin** [vueComponent/ant-design-vue#5262]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.9

### Environment
vue: 3.2.30

### Reproduction link
[http://nolink](http://nolink)

### Steps to reproduce
使用range-picker组件，设置autofocus为true, 初始化后没有自动获焦

### What is expected?
range-picker组件设置了autofocus属性为true后  组件初始化后能正常自动获焦

### What is actually happening?
在使用range-picker组件时，使用了autofocus属性，并设置为true, 发现没起作用，看了框架代码，在generateRangePicker.js文件中第69行：
```
onMounted(function () {
  nextTick(function () {
    var _a;
    
    if (process.env.NODE_ENV === 'test') {
    if (props.autofocus) {
      (_a = pickerRef.value) === null || _a === void 0 ? void 0 : _a.focus();
      }
    }
  });
});
```
被设置了 process.env.NODE_ENV 为 test 才生效？ 为什么要限制env?

**Comment by tangjinzhou** [comment]
非测试环境 会走浏览器的 autofocus 逻辑，我这没复现，麻烦提供复现示例
