### ISSUE TITLE
Tabs label component supports right-click event

### ISSUE THREAD

**Issue by gujiwork** [vueComponent/ant-design-vue#5269]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当Tabs标签变多时，希望可以增加右键事件这样可以批量关闭标签或者实现右键复制标签

### What does the proposed API look like?
contextmenu

**Comment by tangjinzhou** [comment]
```html
<a-tabs v-model:activeKey="activeKey" @contextmenu="test"></a-tabs>
```

**Comment by gujiwork** [comment]
> ```
> <a-tabs v-model:activeKey="activeKey" @contextmenu="test"></a-tabs>
> ```

这样不生效，请问示例代码 ant-vue版本多少
