### ISSUE TITLE
datePicker - select date without globaly (without years)

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#527]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Hello,

I am currently trying to have a datepicker without the year, which allows me to say (for all years):
I have a global variable called `color`.
- from January 1st to March 5th, I want `color` to be equal to: green
- from March 6 to May 10, I want `color` to be equal to: red
...

Is it possible today?

thank you in advance

### What does the proposed API look like?
like today, but with the whole month of February with 29 days instead of having them every 4 years.

**Comment by tangjinzhou** [comment]
https://vue.ant.design/components/date-picker/#components-date-picker-demo-customized-date-rendering  

We can customize the rendering of date cells in the calendar by providing a `dateRender` function to DatePicker.
