### ISSUE TITLE
Missing type declaration InputProps

### ISSUE THREAD

**Issue by hzb1** [vueComponent/ant-design-vue#5273]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我想为a-input的props提供类型提示，但现在缺少InputProps。
```
const fieldProps:InputProps = {}
<a-input {...fieldProps} />
```

### What does the proposed API look like?
import type { InputProps } from "ant-design-vue";

**Comment by tangjinzhou** [comment]
update 3.0.0-beta.10+
