### ISSUE TITLE
table integration vue-draggable-resizable realizes scalable columns except action, other columns are all set with width, action column is set with fixed: right and two actions appear when the screen is so large that there is no scroll bar

### ISSUE THREAD

**Issue by songxianling** [vueComponent/ant-design-vue#5274]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
ant-design-vue 1.6.3 and (vue-draggable-resizable 2.1.0 or 2.2.0)

### Reproduction link
[http://Examples](http://Examples)

### Steps to reproduce
table集成vue-draggable-resizable,实践中发现都要设置宽度，如果留一列不设置宽度用来自适应的话，该列就不能拖拽。但是数据过多的话想把最后一列操作列固定在最右边，最后一列使用fixed后无论该列有没有设置width,屏幕大道无滚动条时会出现2列操作列，其中一列压在了另一列的上面，另一列露出了一部分。屏幕小到出现滚动条时是正常的。

### What is expected?
设置fixed时出现两列操作列且宽度不同都能被看到

### What is actually happening?
设置fixed时出现两列操作列且宽度不同都能被看到

**Comment by songxianling** [comment]
[http://image.lz517.com/statement/DQPpXR_1645435704400.png](url)
多出来的一块区域比设置的width大了许多

**Comment by tangjinzhou** [comment]
这只是个示例，你可以自行修改。
或者升级 3.0， 已经内置了拖动
