### ISSUE TITLE
jest run warn at transition.js

### ISSUE THREAD

**Issue by super-hu** [vueComponent/ant-design-vue#5275]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.10

### Environment
vue3.2.26

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/commit/47066753ac2dab47806584e8f90950cf5958c95e](https://github.com/vueComponent/ant-design-vue/commit/47066753ac2dab47806584e8f90950cf5958c95e)

### Steps to reproduce
npm run test

### What is expected?
本地跑test，为什么这里需要打印警告用pro env？控制台有日志，期望规避

### What is actually happening?
跑测试用例，控制台都是警告

**Comment by tangjinzhou** [comment]
故意为之，等单侧重构后移除(时间未知)
