### ISSUE TITLE
Is there a better way to reference components for the syntactic sugar of "script setup"

### ISSUE THREAD

**Issue by geeklibin** [vueComponent/ant-design-vue#5276]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在script setup的语法糖中，
```
<template>
<Button>Button</Button>
</template>
<script setup>
import {Button} from 'ant-design-vue'
</script>
```
或
```
<template>
<a-button>Button</a-button>
</template>
<script setup>
import {Button as AButton} from 'ant-design-vue'
</script>
```

### What does the proposed API look like?
```
import {AButton} from 'ant-design-vue'
```

**Comment by zkwolf** [comment]
unplugin-vue-component你值得拥有？

**Comment by geeklibin** [comment]
> unplugin-vue-component你值得拥有？

3Q..
