### ISSUE TITLE
The child window form validation label prompt is undefined

### ISSUE THREAD

**Issue by lazebird** [vueComponent/ant-design-vue#5278]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
https://codesandbox.io/s/duo-biao-dan-lian-dong-ant-design-vue-3-0-0-beta-9-forked-dlgqhz

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-biao-dan-lian-dong-ant-design-vue-3-0-0-beta-9-forked-dlgqhz)

### Steps to reproduce
https://codesandbox.io/s/duo-biao-dan-lian-dong-ant-design-vue-3-0-0-beta-9-forked-dlgqhz

### What is expected?
子窗口表单错误提示显示正常label

### What is actually happening?
显示为undefined

**Comment by tangjinzhou** [comment]
更新到 3.0以上
