### ISSUE TITLE
menu component, single file recursive menu error

### ISSUE THREAD

**Issue by yearspark** [vueComponent/ant-design-vue#5281]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.10

### Environment
vue3.0

### Reproduction link
[https://next.antdv.com/components/menu-cn#components-menu-demo-template](https://next.antdv.com/components/menu-cn#components-menu-demo-template)

### Steps to reproduce
按照官网的例子复制代码，运行menu组件中的单文件递归菜单会出现警告

### What is expected?
menu组件，递归后能正常显示

### What is actually happening?
菜单无法正常显示，且有警告：[Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js".

**Comment by tangjinzhou** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/6937879/155445129-56610335-c4fe-41b2-aad6-183e5deeba12.png">
you can rewrite it to a single file component, if not, you should config vue alias to vue/dist/vue.esm-bundler.js
