### ISSUE TITLE
form.item select element validation exception

### ISSUE THREAD

**Issue by lazebird** [vueComponent/ant-design-vue#5283]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
https://codesandbox.io/s/zi-ding-yi-xiao-yan-gui-ze-ant-design-vue-3-0-0-beta-9-forked-h7i120?file=/src/demo.vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xiao-yan-gui-ze-ant-design-vue-3-0-0-beta-9-forked-h7i120?file=/src/demo.vue)

### Steps to reproduce
https://codesandbox.io/s/zi-ding-yi-xiao-yan-gui-ze-ant-design-vue-3-0-0-beta-9-forked-h7i120?file=/src/demo.vue

### What is expected?
选择id后，应该通过校验

### What is actually happening?
选择id后，提示'id' is not a valid undefined

---
3.0貌似正常

**Comment by tangjinzhou** [comment]
那就升级 3.0  ，不升级也没办法在当前版本打补丁
