### ISSUE TITLE
The mouse should not enter the tooltip

### ISSUE THREAD

**Issue by gamenic-pawanrai** [vueComponent/ant-design-vue#5288]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
As of now cursor can enter tooltip bubble and select tooltip text.

### What problem does this feature solve?
Tooltip will hide when the mouse enters the tooltip bubble.

### What does the proposed API look like?
Add api named `enterable` with default value `true`.
If set to false mouse cannot enter tooltip bubble.

**Comment by tangjinzhou** [comment]
please use control  visible mode
