### ISSUE TITLE
slider console warning

### ISSUE THREAD

**Issue by mofada** [vueComponent/ant-design-vue#5289]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.10

### Environment
windows 11 ， chrome 版本 98.0.4758.102（正式版本） （64 位） ，Vue ^3.2.31

### Reproduction link
[https://next.antdv.com/components/slider-cn#components-slider-demo-event](https://next.antdv.com/components/slider-cn#components-slider-demo-event)

### Steps to reproduce
```vue3
<template>
<div class="code-box-demo">
<a-slider v-model:value="value1" @afterChange="onAfterChange" />
<a-slider v-model:value="value2" range :step="10" @afterChange="onAfterChange" />
</div>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue';

export default defineComponent({
setup() {
const value1 = ref<number>(30);
const value2 = ref<[number, number]>([20, 50]);

const onAfterChange = (value: number) => {
console.log('afterChange: ', value);
};

return {
value1,
value2,
onAfterChange,
};
},
});
</script>
<style scoped>
.code-box-demo .ant-slider {
margin-bottom: 16px;
}
</style>
```

### What is actually happening?
Component emitted event "beforeChange" but it is neither declared in the emits option nor as an "onBeforeChange" prop.
Component emitted event "afterChange" but it is neither declared in the emits option nor as an "onAfterChange" prop.

warn2	@	runtime-core.esm-bundler.js:38
emit$1	@	runtime-core.esm-bundler.js:666
onEnd	@	Slider.js:98

**Comment by mofada** [comment]
![image](https://user-images.githubusercontent.com/22286246/155320492-1481a1b8-b59d-4e43-8396-ae270ef38562.png)

**Comment by SignDawn** [comment]
你需要发一个能重现的线上例子，不然大家不是要搭环境嘛？
https://codesandbox.io/

**Comment by qcj007** [comment]
3.0以上版本的slider丢失了beforeChange
