### ISSUE TITLE
【enhancement】上传组建新增文字说明字段

### ISSUE THREAD

**Issue by rainJohn** [vueComponent/ant-design-vue#529]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
上传组建目前只提供了图片，希望提供一个图片在上面，文字在下面的增强功能

### What does the proposed API look like?
针对上传组建，是否可以提供一个文字说明，如description的字段？

**Comment by sendya** [comment]
可以试试 
https://vue.ant.design/components/upload/#Drag-and-Drop

具体效果如下：
![20190226112029](https://user-images.githubusercontent.com/5404542/53385193-8df63780-39b8-11e9-8846-0a6f918b83e9.png)

**Comment by rainJohn** [comment]
![20190226141851](https://user-images.githubusercontent.com/4311236/53391526-9149ed00-39d1-11e9-8dfc-9db85a42265d.png)
我的意思是想在上传好的照片墙下面，会有一个说明性文字,如图所示哦。

**Comment by tangjinzhou** [comment]
你可以自行在业务层面实现，组件暂无计划添加该功能
