### ISSUE TITLE
Button with Icon property can't work

### ISSUE THREAD

**Issue by kirinkaka** [vueComponent/ant-design-vue#5291]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.10

### Environment
VUE 3.2

### Reproduction link
[![Edit 加载中状态 - ant-design-vue@3.0.0-beta.11](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jia-zai-zhong-zhuang-tai-ant-design-vue-3-0-0-beta-11-ll5ov8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
I use  <a-button type="primary" icon="search">Primary Button</a-button>, the page show a button with text "searh Primary Button ",no icon shows
set icon property not working

### What is expected?
the same as
<a-button type="primary" shape="circle">
<template #icon><SearchOutlined /></template>
</a-button>

### What is actually happening?
no icon but text only

**Comment by kirinkaka** [comment]
你们自己官方的例子图标都无法显示

**Comment by shijunti19** [comment]
官方不要用机器人管理了，没看到这个是bug吗，怎么直接关了
