### ISSUE TITLE
Pagination when size is change,the page change function will be trigger at the same time

### ISSUE THREAD

**Issue by 2071534594** [vueComponent/ant-design-vue#5293]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.10

### Environment
window10, "browser chrome": "版本 98.0.4758.102（正式版本）",     "vue": "3.2.29"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-sky-u06rct?file=/src/App.vue)

### Steps to reproduce
代码
main.js
```
import { createApp } from "vue";
import App from "./App.vue";
import "ant-design-vue/dist/antd.css";
import { Pagination } from "ant-design-vue";

createApp(App).use(Pagination).mount("#app");
```
APP.vue
```
<template>
<a-pagination
size="small"
:total="topTable.total"
:showSizeChanger="true"
:pageSizeOptions="topTable.pageSizeOptions"
:pageSize="topTable.pageSize"
:current="topTable.current"
@showSizeChange="sizeChange"
@change="pageChange"
>
</a-pagination>
</template>

<script lang="ts">
import { defineComponent } from "vue";
export default defineComponent({
name: "App",
setup() {
const topTable = {
pageSize: 50,
pageSizeOptions: ["50", "100", "200"],
total: 0,
current: 1,
};
const sizeChange = () => {
console.debug("sizeChange");
};
const pageChange= (current, size) => {
console.debug("pageChange");
};
return {
topTable,
sizeChange,
pageChange,
};
},
});
</script>

<style lang="css">
</style>
```
1.设置可选每页大小pageSize为50，100，200
2.选择从50条/页改为100条/页的

### What is expected?
只触发showSizeChange方法，console只打印“sizeChange”

### What is actually happening?
实际是同时触发了showSizeChange方法与change方法，打印了“sizeChange”、“pageChange”，不应该触发页发生改变的方法

**Comment by tangjinzhou** [comment]
预期行为，我们会优化文档

**Comment by 2071534594** [comment]
这种是正常的么，这个不是bug么？请问这样不是无法确定当前到底是触发的“sizeChange”、“pageChange”，如此两个回调函数都会被执行了

> 预期行为，我们会优化文档
