### ISSUE TITLE
When the pager of a-table uses the Ref<number> value as pageSize, current, and total, more than 20 types of mismatch warnings appear in the background

### ISSUE THREAD

**Issue by liutian0117** [vueComponent/ant-design-vue#5297]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue 3.2.12 ant design vue 2.2.8

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
我这里编写一个查询页面，拥有一个计划列表和分页器。
a-table：
<a-table
:columns="columns"
:data-source="data"
rowKey="id"
:size="tableSize"
:scroll="{ y: height }"
:pagination="pagination"
></a-table>
在script setup中定义的分页器：
<script setup>
const resTotal = ref(0)
const pageNum = ref(1)
const pageSi = ref(15)
const pagination = {
pageSize: pageSi,
current: pageNum,
defaultPageSize: 15, // 默认当前页显示数据的大小
total: resTotal,
showSizeChanger: true,
showQuickJumper: true,
pageSizeOptions: ['5', '15', '30', '50', '100'],
showTotal: resTotal => `共 ${resTotal} 条`, // 显示总数
onShowSizeChange: (current, pageSize) => {
//  some code
},
// 改变每页数量时更新显示
onChange: (current, size) => {
//  some code
}
}
</script>

### What is expected?
后台无警告，页面正常显示，分页器正常使用。

### What is actually happening?
后台报二十多个警告，页面正常显示，分页器正常使用：
当我把 resTotal、pageNum、pageSi 的值设成 number 时，后台不报警告。
当我删除 pagination 中的 pageSize、current、total 属性时， 后台不报警告。
当我仅仅保留分页器的 pageSize 属性时，警告数量不变。

[VueTypes warn]: oneOfType - provided value does not match any of the 2 passed-in validators:
shape - "pageSize" property validation error:
number - value "[object Object]" should be of type "Number"
looseBool - value "[object Object]" should be of type "Boolean"

[Vue warn]: Invalid prop: custom validator check failed for prop "pagination".
at <Table columns= (6) [{…}, {…}, {…}, {…}, {…}, {…}] scroll= {y: 518} pagination= {pageSize: RefImpl, current: RefImpl, defaultPageSize: 15, total: RefImpl, showSizeChanger: true, …}  ... >
at <ATable columns= (6) [{…}, {…}, {…}, {…}, {…}, {…}] data-source= (15) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] rowKey="id"  ... >
at <ASpin spinning=false >
at <ACard style= {margin: '8px'} size="small" >
at <PlanManage onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {__v_skip: true} > >
at <KeepAlive key=0 >
at <BaseTransition appear=false persisted=false mode=undefined  ... >
at <Transition name="fade-top" >
at <RouterView key=0 >
at <Index style= {overflow: 'auto'} >
at <Anonymous hasSider=undefined prefixCls="ant-layout-content" tagName="main"  ... >
at <ALayoutContent class="fixedHeader muiltTab" >
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section" >
at <ALayout>
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout id="layout" class="theme-dark layout-side" >
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy {…} > >
at <RouterView>
at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" >
at <LocaleReceiver children=fn<children> >
at <AConfigProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} >
at <App>

**Comment by tangjinzhou** [comment]
使用 number
