### ISSUE TITLE
3.0.0-beta.11  upload listType is 'picture-card'  fileList async style error

### ISSUE THREAD

**Issue by qingyuun** [vueComponent/ant-design-vue#5298]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.11

### Environment
chrome 98.0.^  vue 3.2.31  antd-design-vue 3.0.0-beta.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-proskuriakova-30ebbw)

### Steps to reproduce
filelist  默认值为 空数组时,通过 异步延时赋值后 , listType 为 'picture-card' 时样式不正确渲染 ,

### What is expected?
在 listType 为 'picture-card'  时   fileList 异步渲染 时 渲染区域  class  为 `ant-upload-list-picture-card-container` 的div  元素上, 去除 行内 style  "height: 20px; opacity: 1;"

### What is actually happening?
在 listType 为 'picture-card'  时   fileList 异步渲染 时 渲染区域  class  为 `ant-upload-list-picture-card-container` 的div  元素上, 添加了 行内 style  "height: 20px; opacity: 1;"

**Comment by hzgotb** [comment]
https://github.com/vueComponent/ant-design-vue/blob/fe0fc8084fd3db1eb5a2a5176465cea0c363cb83/components/upload/UploadList/listAnimation.ts#L17

这个位置赋值了。
我试了一下官网的实例，上传一张新的图片，也出现这个问题。
