### ISSUE TITLE
message 组建文档没有提供全局配置方法

### ISSUE THREAD

**Issue by C0deZLee** [vueComponent/ant-design-vue#530]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
Vue 2.5, vue-ant-design 1.3.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n4x0k9rjy4)

### Steps to reproduce
main.js
```
import Vue from 'vue';
import Antd from 'ant-design-vue';
import App from './App.vue';
import router from './router';
import store from './store/index';

import './styles/theme.less';

Vue.config.productionTip = false;
Vue.use(Antd);
// message.config({ top: '100px' }); 无效
// Vue.message.config({ top: '100px' }); 无效
// Vue.$message.config({ top: '100px' }); 无效
// $message.config({ top: '100px' }); 无效

new Vue({
router,
store,
render: (h) => h(App),
}).$mount('#app');
```

### What is expected?
文档中应该提供详细的全局配置方法

### What is actually happening?
文档没有提供任何帮助

---
这个文档的体验真的很糟糕

**Comment by tangjinzhou** [comment]
```
Antd.message.config({top: '100px'})
or
Vue.prototype.$message.config({top: '100px'})
```

**Comment by C0deZLee** [comment]
Antd.message.config({top: '100px'}) 依然会报cannot read property 'config' from undefined。
在我的环境下只有第二个有效。

另外建议更新文档

**Comment by zdxweb** [comment]
为什么设置最大显示数后，message不会消失?
