### ISSUE TITLE
When using the components property in the table to override the default table element, the table data information cannot be obtained

### ISSUE THREAD

**Issue by hrhrhr2** [vueComponent/ant-design-vue#5301]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.11

### Environment
macos11、chrome98、vue 3.2

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
<Table :columns="props.columns" :dataSource="props.dataSource"
:components = "components"
>
const components = {
header:{
cell:(data)=>{

console.log(data);
}
}
}
data中获取不到具体列数据

### What is expected?
可以获取到列属性

### What is actually happening?
获取不到列属性

---
在antd react版本中有children属性可以获取到 vue版本没有该属性

**Comment by tangjinzhou** [comment]
header 相当于 vue 组件，你这是函数式组件，使用 函数式组件 规范获取相关数据
