### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by Jkssns** [vueComponent/ant-design-vue#5305]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
浏览器

### Reproduction link
[https://2x.antdv.com/docs/vue/getting-started-cn](https://2x.antdv.com/docs/vue/getting-started-cn)

### Steps to reproduce
官网---文档---Ant Design of Vue ---下滑到底---Vite 按需(相关插件和文档已更名，使用方法已更新“vite-plugin-components has been renamed to unplugin-vue-components, see the migration guide.”)

### What is expected?
改成更新后的unplugin-vue-components

### What is actually happening?
vite-plugin-components的相关使用说明

**Comment by bluemiaomiao** [comment]
AntDesign 的 Vue 版本简直就是 KPI 工程，虽然我也是阿里的。。有没有发现开源出来就容易不维护了，要不然就是占坑抢市场。。推荐一个全平台的 Vue UI框架吧：[https://quasar.dev/](https://quasar.dev/)。若干年前那个狗啃按钮事件就够恶心人的。。。

**Comment by bluemiaomiao** [comment]
The Vue version of AntDesign is simply a KPI project, although I am also Ali's... If you don't find open source, it's easy not to maintain it, or you'll grab the market... Recommend a platform-wide Vue UI framework: [https://quasar.dev/](https://quasar.dev/). A few years ago, the dog biting the button incident was disgusting enough...
