### ISSUE TITLE
Different tab headers render different styles

### ISSUE THREAD

**Issue by ReySong** [vueComponent/ant-design-vue#5308]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
根据页签的内容为页签头渲染不同的样式（例如内容有误时页签头文字显示红色）

### What does the proposed API look like?
类似table组件的rowClassName，为页签头动态绑定不同的class name

**Comment by tangjinzhou** [comment]
直接使用  class

**Comment by greper** [comment]
直接使用class，class会落在panel上，并不会落在nav tab上
看源码目前不支持页签头绑定class
![image](https://user-images.githubusercontent.com/1687298/200099570-e326761e-67ff-487d-b6bb-4d18264d50f9.png)
