### ISSUE TITLE
Cacader onChange Event Type Error

### ISSUE THREAD

**Issue by bundery** [vueComponent/ant-design-vue#5309]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
macOS 11.5; chrome 96; vue ^3

### Reproduction link
[https://antdv.com/components/cascader-cn/](https://antdv.com/components/cascader-cn/)

### Steps to reproduce
const onChange: CascaderProps['onChange'] = (value, selections) => void

### What is expected?
No Type Error

### What is actually happening?
error: 不能将类型“(value: ValueType, selectOptions: DefaultOptionType[] | DefaultOptionType[][]) => void”分配给类型“(payload: Event) => void”。ts(2322)

**Comment by tangjinzhou** [comment]
重启 volar 或 ts

ts config 导入用于支持 volar 的类型文件 "node_modules/ant-design-vue/typings/global.d.ts"

**Comment by bundery** [comment]
重新禁用 volar 再开启，仍然不生效

**Comment by lubulikai** [comment]
@bundery 你好，请问这个问题你解决了吗？
