### ISSUE TITLE
application freezes and show high CPU usage when forms instantiated from property

### ISSUE THREAD

**Issue by pumano** [vueComponent/ant-design-vue#531]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
vue: 2.6.7, ant-design-vue: 1.3.5, vue-class-component: 7.0.1, typescript: 3.3.3, vue-property-decorator: 7.3.0

### Reproduction link
[https://stackblitz.com/edit/typescript-vuejs-form-init](https://stackblitz.com/edit/typescript-vuejs-form-init)

### Steps to reproduce
it caused only when we instantiate forms from class component

### What is expected?
in examples we see something like:
```
export default {
  data () {
     return {
       hasErrors,
       form: this.$form.createForm(this),
     };
  }
}
```
it's same if we use pure class property in vue class component:
```
export class MyComponent extends Vue {

// data
form = this.$form.createForm(this);

}
```
but that instantiation just freeze application and you can't enter any value to form.

If we use `created()` hook it will work properly:

```
export class MyComponent extends Vue {

// data
form;

created() {
    this.form = this.$form.createForm(this);
}

}
```

### What is actually happening?
`this.form = this.$form.createForm(this);` not working in vue class component and freeze application with high CPU usage

---
check stackblitz example for demo

**Comment by tangjinzhou** [comment]
ref #392

**Comment by pumano** [comment]
Note: in some examples `createForm` executed on `beforeCreate` hook.

**Comment by tangjinzhou** [comment]
you can createform before beforecreate.

**Comment by bmfs** [comment]
I've faced the same issue.
creating the form either in beforeCreate or data() are the solutions.
Nevertheless, I would expect some kind of error if the instantiation isn't done correctly. Having the browser freeze doesn't seem a good behaviour.

**Comment by Shuunen** [comment]
still having this issue with `"ant-design-vue": "^1.6.2",` 😟
