### ISSUE TITLE
FormItems in sub component are not response to `validate`

### ISSUE THREAD

**Issue by lchrennew** [vueComponent/ant-design-vue#5311]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
macOS Monterey 12.2.1; Chrome 99.0.4844.51; Vue 3.2.31

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-albattani-4ooqig)

### Steps to reproduce
1. See the minimal reproduction
2. Click the `Save` button
3. You'll see the `URL` field is not be validated.

### What is expected?
the URL field should be validated as `required`

### What is actually happening?
the URL field is not validated as `required`

**Comment by tangjinzhou** [comment]
modelRef add url field

https://codesandbox.io/s/determined-wing-ttfgqn?file=/src/components/Configurer.vue:509-517

**Comment by lchrennew** [comment]
> modelRef add url field
> 
> https://codesandbox.io/s/determined-wing-ttfgqn?file=/src/components/Configurer.vue:509-517

大神，但这样就破坏了依赖关系，因为url是内聚在custom-configurer中的，有没有什么更好的方式能够在custom-configurer中将url注入到modelRef里？

**Comment by lchrennew** [comment]
#5330
