### ISSUE TITLE
Can I use slots: { customRender: 'XXX'} when the table uses template style? how to use?

### ISSUE THREAD

**Issue by agoni1212** [vueComponent/ant-design-vue#5314]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
template 风格使用 slots: { customRender: 'XXX'}

### What does the proposed API look like?
template 风格使用 slots: { customRender: 'XXX'}

        
`<a-table>
      <a-table-column title="日期1" align="center" :width="120" data-index="doc_dt1" :slots="{ customRender: 'formateDate' }" />
      <a-table-column title="日期2" align="center" :width="120" data-index="doc_dt2" :slots="{ customRender: 'formateDate' }" />
      <span slot="formateDate" slot-scope="text">{ text }</span>
</a-table>`

**Comment by tangjinzhou** [comment]
不可以，也没必要

**Comment by agoni1212** [comment]
比如一个 table里，有五个column 都是日期格式，想要format 成 同一格式，在template 风格下， 有什么方式能减少代码量，请指教
