### ISSUE TITLE
The problem of using the X scroll bar together with the form and the modal pop-up window

### ISSUE THREAD

**Issue by q7486828035** [vueComponent/ant-design-vue#5315]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
"ant-design-vue": "2.2.8",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-ant-design-vue-next-forked-r19s3q?file=/src/Demo.vue)

### Steps to reproduce
https://codesandbox.io/s/gu-ding-tou-he-lie-ant-design-vue-next-forked-r19s3q?file=/src/Demo.vue
切换成 2.2.3及以后版本 会出现关闭弹窗后 滚动条自动到最右边

### What is expected?
滚动条不变动

### What is actually happening?
滚动条滑动到了最右边

**Comment by 10816187** [comment]
我也遇到了，1.5.0-rc.6，表格列插槽中的modal，关闭后会导致表格滚动到最顶部
