### ISSUE TITLE
TreeSelect组件的treeData子节点disabled都为true时，选中状态不显示当前值

### ISSUE THREAD

**Issue by gaothing** [vueComponent/ant-design-vue#5316]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
macos10.15.4 (19E287)  ,Google Chrome 99.0.4844.51（正式版本） (x86_64),vue:3.2.11

### Reproduction link
[https://next.antdv.com/components/tree-select-cn](https://next.antdv.com/components/tree-select-cn)

### Steps to reproduce
```
<template>
<div>
<TreeSelect
style="width: 100px"
:treeData="treeData"
:fieldNames="{ label: 'name', key: 'id', value: 'id' }"
/>
</div>
</template>
<script lang="ts" setup>
import { TreeSelect } from 'ant-design-vue';
const treeData = [
{
id: 1,
name: '111',
pid: 0,
disabled: false,
children: [
{ id: 11, name: '111', pid: 1, children: [], disabled: true },
{ id: 12, name: '222', pid: 1, children: [], disabled: true },
],
},
{ id: 2, name: '222', pid: 0, children: [], disabled: true },
];
</script>
```

### What is expected?
可选中，且选完显示值

### What is actually happening?
可选中，选完不显示值

**Comment by 438413530** [comment]
我也遇到了,而且在 2.x版本没有这个问题
