### ISSUE TITLE
Cascader returns incorrect data when multiple selections are made

### ISSUE THREAD

**Issue by adogie** [vueComponent/ant-design-vue#5319]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
node v14.17.4 ;   vue: "^3.1.4" ;

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-ant-design-vue-3-0-0-beta-13-forked-wdgkxu?file=/src/demo.vue)

### Steps to reproduce
1.使用官网文档的demo随便写点多级节点数据。
2.当级联选择的数据有三级选项时，选择第一条数据的三级节点，返回的是第二级节点的数据。

### What is expected?
选择第一条数据时返回正确数组

### What is actually happening?
选择第一条数据的三级节点，返回的是第二级节点的数据。
奇怪的是其他节点没有问题，只有第一条数据的三级节点有问题。

**Comment by 549898972** [comment]
+1   我也遇到了这样的情况

**Comment by 549898972** [comment]
具体问题是    多选  选择最后一条数据的时候会打乱所有 value<Array>的值

**Comment by tangjinzhou** [comment]
预期行为，点中最后一条相当于全选，会返回根节点的值
如果需要其它模式，可以自行处理
and
`@change` 第二个参数可以拿到更多的值信息

**Comment by wsxe9988** [comment]
我觉得这块是值得商榷得地方，虽然and-design也是这样得。但我觉得可以增加个配置项，控制在多选情况下，选中某一级得全部节点，是显示上一级节点得值还是显示当前这一级全部选中得节点值。Tdesign就不是这样，
![image](https://user-images.githubusercontent.com/5828057/158009919-e76ad6cd-cee9-4ef1-96ba-3fc068b3b9de.png)
