### ISSUE TITLE
I need to change the type in the a-input form submission to facilitate mobile device identification and configure the corresponding soft keyboard

### ISSUE THREAD

**Issue by selectcount** [vueComponent/ant-design-vue#5320]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我需要在a-input表单提交里面，更改type类型，以方便移动端设备识别，并配置对应的软键盘，目前type类型无法被<input>识别，所以在移动端无法弹出对应的软键盘类型，例如，我将type设为tel，那么对应的移动端软键盘应该是电话类型的键盘

### What does the proposed API look like?
暂无

![图片](https://user-images.githubusercontent.com/49188675/157587176-1a202199-756b-49fc-b94b-d0fd7f2a8d14.png)

**Comment by selectcount** [comment]
我的版本是ant design vue 1.7.8

**Comment by tangjinzhou** [comment]
升级 3.0

and

1.7.8 应该是支持type 的

**Comment by selectcount** [comment]
> 升级 3.0
> 
> and
> 
> 1.7.8 应该是支持type 的

我需要的是 type = tel 这种类型，这个ui最终解析出来的是全键盘，不会在h5里面弹出题中如图所示的电话类型的软键盘
