### ISSUE TITLE
DatePicker components use attribute value-format="YYYY-MM-DD"  click open panel appear type Mismatch warning 

### ISSUE THREAD

**Issue by LinbinSuccess** [vueComponent/ant-design-vue#5323]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
os version：macOS 10.15.1、browser version：100.0.4892.0（正式版本）dev (x86_64)、Vue version：3.2.25

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-dan-rq74sd?file=/src/App.vue)

### Steps to reproduce
Normal use DatePicker components that will do，binding v-model:value 、use value-format="YYYY-MM-DD" attribute。then click components eject Date panel time Will appear Warning of type mismatch

### What is expected?
Do not warn of date mismatches，Because of the use of value-format="YYYY-MM-DD" Property should be of type string

### What is actually happening?
A warning has occurred： Invalid prop: type check failed for prop "value". Expected Object, got String with value "".

---
nothing

**Comment by tangjinzhou** [comment]
wait next version
or
set init value to null, not empty string
