### ISSUE TITLE
Cascader returns incorrect data when multiple selections are made

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5332]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
node v14.17.4 ; vue: "^3.1.4" ;

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-ant-design-vue-3-0-0-beta-13-forked-wdgkxu?file=/src/demo.vue)

### Steps to reproduce
1.使用官网文档的demo随便写点多级节点数据。
2.当级联选择的数据有三级选项时，选择第一条数据的三级节点，返回的是第二级节点的数据。

### What is expected?
选择第一条数据时返回正确数组

### What is actually happening?
选择第一条数据的三级节点，返回的是第二级节点的数据。
奇怪的是其他节点没有问题，只有第一条数据的三级节点有问题。

        

我觉得这块是值得商榷得地方，虽然and-design也是这样得。但我觉得可以增加个配置项，控制在多选情况下，选中某一级得全部节点，是显示上一级节点得值还是显示当前这一级全部选中得节点值。Tdesign就不是这样，
![image](https://user-images.githubusercontent.com/5828057/158049378-3d4a0b3d-d08e-4d9c-b128-58a825a735a5.png)

**Comment by suifeng50124** [comment]
![image](https://user-images.githubusercontent.com/48434203/163764065-1eab3dc8-da00-4e43-bb92-ac8f13e3106b.png)
建议增加这2种配置项功能
