### ISSUE TITLE
When the table component is rewritten using the components property, the data cannot be obtained

### ISSUE THREAD

**Issue by hrhrhr2** [vueComponent/ant-design-vue#5338]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.0.0-beta.13

### Environment
macos11、chrome98、vue 3.2

### Reproduction link
[https://www.antdv.com/](https://www.antdv.com/)

### Steps to reproduce
table中属性components为:
components={{

body: {
row: renderTableRow
},

}}

const renderTableRow=(row)=>{
console.log(row)
}
row中只有
{class: "ant-table-row ant-table-row-level-0"
data-row-key: "0018"
onClick: ƒ onClick(event)
style: {}}
这些属性,
没有子组件信息，获取不到组件信息就这样的话就没办法进行渲染，
而在ant-design react版本中，row打印出来含有chidren属性，里面就有子组件信息

### What is expected?
可以获取到子组件信息

### What is actually happening?
获取不到子组件信息

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/issues/5301

去看看 vue 文档函数式组件的使用方式

**Comment by hrhrhr2** [comment]
了解了，感谢您
