### ISSUE TITLE
auto-complete输入搜索内容后，无法使用上下键选择搜索的内容

### ISSUE THREAD

**Issue by BrotherMa** [vueComponent/ant-design-vue#534]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
官网也存在这个问题

### Reproduction link
[https://vue.ant.design/components/auto-complete-cn/](https://vue.ant.design/components/auto-complete-cn/)

### Steps to reproduce
在“不区分大小写”demo中进行搜索，默认是可以使用上下按键的，但是如果进行了搜索以后，如输入“ee”搜索完成以后是无法使用上下按键的【输入一个“e”的时候是正常的，但是输入一个以上字符会出现这个问题】，这时候即使将搜索框中的内容删除，也是无法使用上下按键的

### What is expected?
输入搜索内容后可以使用上下按键进行选择

### What is actually happening?
如果输入一个以上的字符无法使用上下按键进行选择内容

**Comment by wangxueliang** [comment]
麻烦删除node_modules和package-lok.json,重新安装，底层依赖有点问题，已修复，谢谢

**Comment by wensonsmith** [comment]
这个修复是在 1.3.6 中是么？ 还是1.3.5 已经解决了。 

我用的是浏览器引入 js 的方法使用的 ant-design-vue

我这边也出现了这个问题，第一次搜索后可以上下键选择，清空后再搜索，出来选项无法上下键选择了

**Comment by tangjinzhou** [comment]
@wensonsmith 建议你使用npm安装，底层依赖的更新可以很方便的同步解决。
如果你使用的是cdn版本，那就只能等1.3.6了  或者你自己打个包出来放在本地

**Comment by wensonsmith** [comment]
感谢大佬，已经本地打包解决了！
