### ISSUE TITLE
Do you plan to continue to update the 1.x version, it seems that there is no new version for a long time, is there any planned update?

### ISSUE THREAD

**Issue by Yowi** [vueComponent/ant-design-vue#5346]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Do you plan to continue to update the 1.x version, it seems that there is no new version for a long time, is there any planned update?

### What does the proposed API look like?
1.*

**Comment by tangjinzhou** [comment]
We no longer add new features, only fix blocking bugs.
