### ISSUE TITLE
About the defaultExpandAllRows property of the table

### ISSUE THREAD

**Issue by syily** [vueComponent/ant-design-vue#535]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
when i load data with ajax,i wanna to open all tree data,but defaultExpandAllRows was not work.only i can use the expandedRowKeys but find in data what can open was complex.

### What does the proposed API look like?
so i wanna some new property or update the defaultExpandAllRows to real time update the tree data open

**Comment by tangjinzhou** [comment]
https://vue.ant.design/docs/vue/faq/#It-doesn't-work-when-I-change-defaultValue,defaultOpenKeys,-initialValue-dynamically.
