### ISSUE TITLE
The scalable column of the table is invalid

### ISSUE THREAD

**Issue by foxmiy** [vueComponent/ant-design-vue#5355]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.0

### Environment
谷歌浏览器 86.0.4240.111（正式版本） （64 位）

### Reproduction link
[https://next.antdv.com/components/table-cn/#components-table-demo-resizable-column](https://next.antdv.com/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
例子失效

### What is expected?
例子有效

### What is actually happening?
例子有效

**Comment by tangjinzhou** [comment]
重复 #5348
