### ISSUE TITLE
slider console warning

### ISSUE THREAD

**Issue by likui628** [vueComponent/ant-design-vue#5357]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/90845831/158930253-bf39db0b-da31-4cc3-9139-32ab64ef211d.png">

有一个相同的issue被关闭了https://github.com/vueComponent/ant-design-vue/issues/5289

### Version
3.0.0-beta.10

### Environment
windows 11 ， Vue ^3.2.23

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-bose-9vblm6)

### Steps to reproduce
鼠标拖动滑块使slider的值发生变化

### What is expected?
no warning

### What is actually happening?
[Vue warn]: Component emitted event "afterChange" but it is neither declared in the emits option nor as an "onAfterChange" prop.

[Vue warn]: Component emitted event "beforeChange" but it is neither declared in the emits option nor as an "onBeforeChange" prop.

**Comment by tangjinzhou** [comment]
udpate to 3.1
