### ISSUE TITLE
Suggess  about  Tree  

### ISSUE THREAD

**Issue by yemaozi999** [vueComponent/ant-design-vue#5358]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
it looks like this
![image](https://user-images.githubusercontent.com/16147749/158933624-53e5bb8e-86da-4451-b41c-653fe98698e3.png)

        
### What problem does this feature solve?
i want to add  a button or other things behind the tree   how ever i cant find the slot

### What does the proposed API look like?
add a new slog

**Comment by yemaozi999** [comment]
by the way, the Tree component halfchecked  on edit is hard to use

**Comment by tangjinzhou** [comment]
update to 3.1 use title slot
