### ISSUE TITLE
Form的input校验每个都要单独添加，页面不简洁，是否考虑借鉴Element的实现方法

### ISSUE THREAD

**Issue by yuanxianfeng1995** [vueComponent/ant-design-vue#536]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
不用再form-item里面每个单独添加v-decorator校验，而是通过往form传入整体的rules对象.保持页面写法上的简洁

### What does the proposed API look like?
浏览器：谷歌   vue版本:3.0.1

**Comment by gdyxml2000** [comment]
赞同！
关键问题是，校验规则，不知道怎么动态设置，v-decorator是在声明组件的时候就要提前定义好的，不支持动态绑定，但是动态定义某个输入的框的校验规则怎么实现呢？ 用getFieldDecorator 好像不起作用~ 
谁有更好的办法。

**Comment by tangjinzhou** [comment]
你可以提供一个key value 对象 如formConfig: { name: ['name', {rules: []}], age: ['age'], ...}
使用的时候直接v-decorator="formConfig.name"  
这样你的模板一样还是简洁的
