### ISSUE TITLE
The Select component enables virtual scrolling, 10w data, the input content matches, the input content response is very busy, and it is easy to get stuck

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5365]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
chrome 94.0.4606.54

### Reproduction link
[https://next.antdv.com/components/select-cn](https://next.antdv.com/components/select-cn)

### Steps to reproduce
1.点击控件
2.键盘输入内容，控件里内容出现卡顿，页面容易无响应

### What is expected?
键盘输入内容，控件里内容不出现卡顿

### What is actually happening?
键盘输入内容，控件里内容出现卡顿，页面容易无响应

**Comment by tangjinzhou** [comment]
还有空间，你可以试着帮助我们优化，谢谢

**Comment by wsxe9988** [comment]
试了下刚发布的RC3，Select组件 虚拟滚动下，10W数据，搜索无卡顿了。金州大大，你说还有优化空间？

**Comment by huangche007** [comment]
@wsxe9988 我使用`3.1.0-rc.2`版本，对于大量数据(其实也就三千条左右)，使用`TreeSelect`组件进行多选操作的时候，还是会比较卡

**Comment by huangche007** [comment]
@tangjinzhou 想问下大佬，`ant-design-vue 3`的稳定正式版大约什么时候能发布？

**Comment by wsxe9988** [comment]
> @wsxe9988 我使用`3.1.0-rc.2`版本，对于大量数据(其实也就三千条左右)，使用`TreeSelect`组件进行多选操作的时候，还是会比较卡

你更新到最新版。官网上是最新的，10万条数据确实不卡顿，搜索也已经不卡顿了

**Comment by huangche007** [comment]
@wsxe9988  好的，我有空更新到最新版看下最新的效果

**Comment by huangche007** [comment]
@wsxe9988 关键是涉及到`TreeSelect`这种多选(取消多选)，然后又滚动。就会很卡了
