### ISSUE TITLE
TreeSelect component Turn on virtual scrolling, 10w data, match the input content, the response of the input content is very busy, and it is easy to get stuck

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5366]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
chrome 94.0.4606.54

### Reproduction link
[https://next.antdv.com/components/tree-select-cn)

### Steps to reproduce
1.点击控件
2.键盘输入内容，控件里内容出现卡顿，页面容易无响应

### What is expected?
键盘输入内容，控件里内容不出现卡顿

### What is actually happening?
键盘输入内容，控件里内容出现卡顿，页面容易无响应

**Comment by tangjinzhou** [comment]
重复 #5365
