### ISSUE TITLE
Menu在选中菜单状态时,菜单被缩起选中的菜单显示，需要鼠标移动上去再移动出去才会消失

### ISSUE THREAD

**Issue by yuanxianfeng1995** [vueComponent/ant-design-vue#537]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
vue版本：^2.5.2  浏览器：谷歌

### Reproduction link
[https://vue.ant.design/components/menu-cn/#只展开当前父级菜单]

### Steps to reproduce
Menu在展开的时候选中菜单项,菜单被缩起时选中的菜单弹出，需要鼠标移动上去再移动出去才会消失

### What is expected?
在菜单是缩起状态下，不显示弹出菜单

### What is actually happening?
Menu在展开的时候选中菜单项,菜单被缩起时选中的菜单弹出，需要鼠标移动上去再移动出去才会消失

**Comment by sendya** [comment]
你好，这个可以由 `openKeys` 属性自行控制，当菜单被缩起时，把 `openKeys` 清空。当菜单被还原大小时，在把 `openKeys` 设置回去

可以参考这个： https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/menu/index.js#L47

**Comment by bosens-China** [comment]
这个问题依然存在
``` html
    <a-menu
      :defaultOpenKeys="openKeys"
      :defaultSelectedKeys="selectedKeys "
      :openKeys="!collapsed ? openKeys : null"
      mode="inline"
      theme="dark"
      :inlineCollapsed="collapsed"
      @openChange="openChange"
      @click="menuClick"
    >
```
在我菜单收起时将菜单的`openKeys`设置为null，鼠标移动上去不在弹出子列表

**Comment by bosens-China** [comment]
> 你好，可以这个由`openKeys`属性自行控制，当菜单被缩起时，把`openKeys`清空。当菜单被还原大小时，把在`openKeys`设置回去
> 
> 可以参考这个：[https](https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/menu/index.js#L47)：[//github.com/sendya/ant-design-pro-vue/blob/master/src/components/menu/index.js#L47](https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/menu/index.js#L47)

这个问题依然存在
``` html
    <a-menu
      :defaultOpenKeys="openKeys"
      :defaultSelectedKeys="selectedKeys "
      :openKeys="!collapsed ? openKeys : null"
      mode="inline"
      theme="dark"
      :inlineCollapsed="collapsed"
      @openChange="openChange"
      @click="menuClick"
    >
```
在我菜单收起时将菜单的`openKeys`设置为null，鼠标移动上去不在弹出子列表
