### ISSUE TITLE
tigger cannot expand left sidebar after responsive layout sidebar is minimized

### ISSUE THREAD

**Issue by jellyidea** [vueComponent/ant-design-vue#5373]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
edge

### Reproduction link
[https://next.antdv.com/components/layout-cn#components-layout-demo-responsive](https://next.antdv.com/components/layout-cn#components-layout-demo-responsive)

### Steps to reproduce
当显示区小到一定程度,响应式生效时,左侧边栏隐藏,会出现tigger,此时点tigger并不会显示出侧边栏

### What is expected?
版本1,2中都无此问题,可以点tigger后正常显示出侧边栏

**Comment by tangjinzhou** [comment]
先用 v-model:collapsed  
下个版本修复
