### ISSUE TITLE
When the datepicker select date pop-up box is opened on ie, the upper left corner flashes and then displays normally

### ISSUE THREAD

**Issue by ding991** [vueComponent/ant-design-vue#5374]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue:2.6.10

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/#API](https://www.antdv.com/components/date-picker-cn/#API)

### Steps to reproduce
在IE11上打开时间选择器，首先会在左上角闪烁。

### What is expected?
参考#1833，用cdn加载解决不了，全量引入的包过大，改动弹框的动画也无效，所以想问问有没有别的解决方案。

### What is actually happening?
datepicker 选择日期弹框在ie上打开时左上角闪烁后又正常显示

**Comment by tangjinzhou** [comment]
参考文档代码，加入 polifill

**Comment by ding991** [comment]
@tangjinzhou 引入了core-js，但是没效果
