### ISSUE TITLE
When is form size supported ?

### ISSUE THREAD

**Issue by Ryongyon** [vueComponent/ant-design-vue#5376]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
https://ant.design/components/form-cn/#components-form-demo-size

### What does the proposed API look like?
https://ant.design/components/form-cn/#components-form-demo-size

**Comment by tangjinzhou** [comment]
update to 3.1
