### ISSUE TITLE
A-modal component hidden bug

### ISSUE THREAD

**Issue by wtsoftware** [vueComponent/ant-design-vue#5378]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
Google chrome85

### Reproduction link
[https://next.antdv.com/components/modal-cn#API](https://next.antdv.com/components/modal-cn#API)

### Steps to reproduce
通过a-tab组件加号 窗同modal新增tab，点击取消或者关闭modal后，整个页面不可点击 了。像是有个遮罩层挡住了

### What is expected?
取消后应该可以正常点击

### What is actually happening?
点击关闭modal后，当前页面不可用 了

**Comment by wangyibinwangyi** [comment]
我出现相同的问题，在开发环境打开modal，然后点击取消按钮关闭弹窗以后，可以看到下面的节点被销毁
![image](https://user-images.githubusercontent.com/24824599/200489334-3e0050b4-08ef-4b14-853b-3fcba57b8aef.png)

但是打包好到测试环境，相同操作后弹窗确实被关闭了，但是该节点并未被销毁
![image](https://user-images.githubusercontent.com/24824599/200489676-352dfb59-d5c7-4430-be88-56d6b4607830.png)
导致整个页面被一层透明遮罩覆盖，所有按钮都无法点击

**Comment by wanglei520** [comment]
> 我出现相同的问题，在开发环境打开modal，然后点击取消按钮关闭弹窗以后，可以看到下面的节点被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489334-3e0050b4-08ef-4b14-853b-3fcba57b8aef.png)
> 
> 但是打包好到测试环境，相同操作后弹窗确实被关闭了，但是该节点并未被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489676-352dfb59-d5c7-4430-be88-56d6b4607830.png) 导致整个页面被一层透明遮罩覆盖，所有按钮都无法点击

我遇到了类似的bug，你这里怎么解决的？

**Comment by evanlee01** [comment]
解决了吗！！同问！

**Comment by evanlee01** [comment]
> > 我出现相同的问题，在开发环境打开modal，然后点击取消按钮关闭弹窗以后，可以看到下面的节点被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489334-3e0050b4-08ef-4b14-853b-3fcba57b8aef.png)
> > 但是打包好到测试环境，相同操作后弹窗确实被关闭了，但是该节点并未被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489676-352dfb59-d5c7-4430-be88-56d6b4607830.png) 导致整个页面被一层透明遮罩覆盖，所有按钮都无法点击
> 
> 我遇到了类似的bug，你这里怎么解决的？

解决了吗！！同问！

**Comment by evanlee01** [comment]
家人们，我的问题找到原因了：https://github.com/vueComponent/ant-design-vue/issues/4565
“process.env.NODE_ENV === 'test' 被占用了，可以先换个环境变量打包测试环境的包，下个版本会改掉“，详情看上述链接

**Comment by evanlee01** [comment]
> > 我出现相同的问题，在开发环境打开modal，然后点击取消按钮关闭弹窗以后，可以看到下面的节点被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489334-3e0050b4-08ef-4b14-853b-3fcba57b8aef.png)
> > 但是打包好到测试环境，相同操作后弹窗确实被关闭了，但是该节点并未被销毁 ![image](https://user-images.githubusercontent.com/24824599/200489676-352dfb59-d5c7-4430-be88-56d6b4607830.png) 导致整个页面被一层透明遮罩覆盖，所有按钮都无法点击
> 
> 我遇到了类似的bug，你这里怎么解决的？

问题原因与解决方案：https://github.com/vueComponent/ant-design-vue/issues/4565
