### ISSUE TITLE
引用Menu组件在IE11下报错

### ISSUE THREAD

**Issue by Seansun1314** [vueComponent/ant-design-vue#539]
`[Vue warn]: Error in render: "ReferenceError: “Symbol”未定义"；`

用的CLI3.0，尚未在工程中引入babel-polyfil。

其他浏览器显示正常，请问原因是什么？

**Comment by Seansun1314** [comment]
是因为没有引入babel-polyfill  IE不支持ES6函数导致的吗

**Comment by tangjinzhou** [comment]
是

**Comment by fuhongwei041** [comment]
ant-design-vue docs says should include es5-shim, es6-shim. after i do a try, i failed. finally, i include babel-polyfill. it works. how kengde IE.
https://www.bootcdn.cn/babel-polyfill/
