### ISSUE TITLE
The icon of Menu.Item cannot enter the slot

### ISSUE THREAD

**Issue by mapleby** [vueComponent/ant-design-vue#5390]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
Vue@3.2.31

### Reproduction link
[https://next.antdv.com/components/menu-cn#API](https://next.antdv.com/components/menu-cn#API)

### Steps to reproduce
我根据官方代码进行复制粘贴组件Menu.Item 在对 icon 进行插入的时候，始终保持原有的状态，图标无任何变化，无法载入自己的图标。

### What is expected?
我想正常使用

### What is actually happening?
Menu.Item 在进行 slot icon 时候失效了
![image](https://user-images.githubusercontent.com/45815225/159846158-c6fa2c34-f5c3-4ba6-b4e5-429c0a8f80a9.png)
![image](https://user-images.githubusercontent.com/45815225/159846180-a8cf3f8c-8444-497d-b924-2448dbe877f5.png)

**Comment by mapleby** [comment]
![image](https://user-images.githubusercontent.com/45815225/159847560-c567f990-9500-4f5f-aab7-22cb1170a7ae.png)
我在想，是不是因为类名被覆盖，所以导致的

**Comment by mapleby** [comment]
已经发现问题了，
![image](https://user-images.githubusercontent.com/45815225/159866394-221cfca5-28b3-401a-8db0-39d1e8a0d667.png)
dang
当已i图标作为插槽内容时候就不显示

**Comment by tangjinzhou** [comment]
请填写正确的版本号
