### ISSUE TITLE
The default selection data of the tree under checkstrict is a one-dimensional array, but once clicked, it becomes a two-dimensional array of checked: and halfchecked

### ISSUE THREAD

**Issue by yemaozi999** [vueComponent/ant-design-vue#5395]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
chrome

### Reproduction link
[[https://www.undefinded.com](https://www.undefinded.com)](https://codesandbox.io/s/f0w5es?file=/src/App.vue)

### Steps to reproduce
checkStrictly 下的tree 默认选择数据是 一维数组[1,2,3], 但是一点击 就变成 checked:[1,2,3] 和 halfChecked:[] 的二维数组,
我一开始传 二维数组, 整个tree 都点不了了

### What is expected?
传入的数据是一维,  点击后的动态数据 一维,   或者 传入的二维  点击也是二维
The incoming data is one-dimensional, the dynamic data after clicking is one-dimensional, or the incoming two-dimensional click is also two-dimensional

### What is actually happening?

checkStrictly 下的tree 默认选择数据是 一维数组, 但是一点击 就变成 checked: 和 halfChecked 的二维数组,
我一开始传 二维数组, 整个tree 都点不了了

The default selection data of the tree under checkstrict is a one-dimensional array, but once clicked, it becomes a two-dimensional array of checked: and halfchecked,When I first passed the two-dimensional array, the whole tree couldn't be clicked

**Comment by yemaozi999** [comment]
https://codesandbox.io/s/f0w5es?file=/src/App.vue

**Comment by yemaozi999** [comment]
这样数据格式变化, 会出现处理的问题,   要写两种方法来区分 初始数据 和点击数据

**Comment by yemaozi999** [comment]
而且在checkStrictly  模式下, 无论怎么点  halfChecked 数组都不会有值

**Comment by tangjinzhou** [comment]
下传单数组没来就是错误的，只是组件做了容错处理。
checkStrictly 下 halfChecked 要手动控制，因为你不可能点击出半选啊

**Comment by FrozenJun** [comment]
checkStrictly为false的情况下，onCheck回调没有返回halfChecked的值，只是返回checked值的数组，但组件当前的状态是父子节点选中状态存在关联。
当checkStrictly为true时，onCheck会返回带halfChecked的对象，但此时父子节点没有关联，所以halfChecked永远是空数组。
