### ISSUE TITLE
preventing parent components changing steps component text align property. 

### ISSUE THREAD

**Issue by siaikin** [vueComponent/ant-design-vue#5396]
this issues copy from [pull request](https://github.com/ant-design/ant-design/pull/24486)
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
not need

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dot-style-ant-design-vue-next-forked-4or47m?file=/src/Demo.vue)

### Steps to reproduce
Setting text-align anywhere above the dom tree causes problematic view on steps component.

![](https://user-images.githubusercontent.com/34946061/82933912-5a2b0880-9f93-11ea-9e44-3902fa04d60b.png)
### What is expected?
step point normal display.

### What is actually happening?
stop point is offset, when setting text-align

---
just simple copy this [pull request](https://github.com/ant-design/ant-design/pull/24486)

**Comment by tangjinzhou** [comment]
update to 3.1
