### ISSUE TITLE
Select component dynamic options cannot display options

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5398]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.3

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-wood-4hrhmi?file=/src/App.vue)

### Steps to reproduce
<a-select :options="options" />
动态插入options选项，下拉框没有实时添加，rc2是正常的

### What is expected?
实时添加数据

### What is actually happening?
没有实时添加数据

**Comment by tangjinzhou** [comment]
请给出有效的 Reproduction link

**Comment by wishong** [comment]
https://codesandbox.io/s/prod-wood-4hrhmi?file=/src/App.vue

**Comment by snoopy1412** [comment]
我也遇到了这个情况，费解，请问是用法问题吗？

**Comment by wishong** [comment]
> 我也遇到了这个情况，费解，请问是用法问题吗？

升到最新版本就可以了，已经修复了

**Comment by snoopy1412** [comment]
> > 我也遇到了这个情况，费解，请问是用法问题吗？
> 
> 升到最新版本就可以了，已经修复了

我早上升级的r5版本，没成功，又返回到了r2版本了。我是在Select下用Option组件，然后里面的值没有动态变化，r2版本无问题

**Comment by wishong** [comment]
> 我早上升级的r5版本，没成功，又返回到了r2版本了。我是在Select下用Option组件，然后里面的值没有动态变化，r2版本无问题

建一个复现链接，重新提个issues，这个issues已经被关闭了。
