### ISSUE TITLE
unmount errors in Carousel component with vue-i18n

### ISSUE THREAD

**Issue by jirex** [vueComponent/ant-design-vue#5399]
[-](url) [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.3

### Environment
development

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-pateu-jeo3el?file=/src/router/index.js)

### Steps to reproduce
use vue-i18n and vue-router
add a-carousel
use custom component in a-carousel
when change page
in browser console. it show errors
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__disableEmitter')
and page frozen

### What is expected?
no errors

### What is actually happening?
errors

<img width="1149" alt="WX20220325-142534@2x" src="https://user-images.githubusercontent.com/7694514/160067338-0bb91c79-0e6a-4d7c-9dd2-efdf9e5eb666.png">

        
<img width="400" alt="WX20220325-142708@2x" src="https://user-images.githubusercontent.com/7694514/160067381-b2307c53-8181-4389-8936-2da68f53ebe6.png">

**Comment by Djaangoo** [comment]
I Have a similar error 

The problem is a carousel 
When We have routing on the page - changing page where is a carousel - makes an error

Fixed Reproduction  -> [https://codesandbox.io/s/agitated-cloud-xgmbku?file=/src/App.vue](url)

Go to /carousel and go to /home 
you should see error
