### ISSUE TITLE
calendar - 1 event for multidays

### ISSUE THREAD

**Issue by Afondevi** [vueComponent/ant-design-vue#540]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
how it's possible to create item in calendar who take multi day ? not between 2 hours but between 2 date ?

### What does the proposed API look like?
how it's possible to create item in calendar who take multi day ? not between 2 hours but between 2 date ?

**Comment by tangjinzhou** [comment]
You can set the item day by day.

**Comment by Afondevi** [comment]
Ok.. rubbish lol
