### ISSUE TITLE
Nested table duplicates child nodes data

### ISSUE THREAD

**Issue by BackWebDev** [vueComponent/ant-design-vue#5409]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.3

### Environment
Mac

### Reproduction link
[https://antdv.com/components/table/#components-table-demo-nested-tables](https://antdv.com/components/table/#components-table-demo-nested-tables)

### Steps to reproduce
https://antdv.com/components/table/#components-table-demo-nested-tables

### What is expected?
Not duplicating child records

### What is actually happening?
Child records similar to each item in the table

---
Sorry for the stupid question but I really don't find any solution, but really want to continue using your package. Thanks!

**Comment by tangjinzhou** [comment]
no change innerData
