### ISSUE TITLE
The validation of props.onUpdate:value of components such as input only accepts functions.

### ISSUE THREAD

**Issue by merfais** [vueComponent/ant-design-vue#5410]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
ant-design-vue": "^3.0.0-beta.3 ""vue": "^3.2.31"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-shadow-665wj2?file=/src/App.vue)

### Steps to reproduce
1. 新建子组件input-demo，里面只使用a-input，组件绑定 @update:value接口, <a-input @update:value="onInputUpdate" />
2. 新建组件，使用上面定义的子组件，也绑定@update:value接口给 <InputDemo @update:value="onParentUpdate" />

### What is expected?
console中不报错，vue3本身支持了attrs透传和绑定，也支持了事件的合并，因此校验时function是不妥的，也可能是Array<Function>

### What is actually happening?
console中有校验报错
[Vue warn]: Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array
at <AInput value="123" onUpdate:value= (2) [ƒ, ƒ] >
at <AntInput onUpdate:value=fn<onUpdate> >
at <App>

**Comment by tangjinzhou** [comment]
添加 inheritAttrs: false, 取消继承合并

**Comment by merfais** [comment]
> 添加 inheritAttrs: false, 取消继承合并

就是要继承，你却让取消继承，解决问题的方式是消灭问题吗？！！

**Comment by KaygNas** [comment]
> > 添加 inheritAttrs: false, 取消继承合并
> 
> 就是要继承，你却让取消继承，解决问题的方式是消灭问题吗？！！

你的情况应该和我遇到的是类似的 https://github.com/vueComponent/ant-design-vue/issues/5414#issuecomment-1335487003
