### ISSUE TITLE
Use with vite2

### ISSUE THREAD

**Issue by xunnasu** [vueComponent/ant-design-vue#5417]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我可以用这个框架结合vite2 打包工具一起用吗

### What does the proposed API look like?
vue3 +vite2 + ant-design-vue

**Comment by tangjinzhou** [comment]
可以
