### ISSUE TITLE
ant-design-vue 在使用组件的时候编译报错

### ISSUE THREAD

**Issue by wuchaoya** [vueComponent/ant-design-vue#542]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
mac 0.12.5  Chrome vue 2.6.6

### Reproduction link
[https://github.com/wuchaoya/vue-ts.git](https://github.com/wuchaoya/vue-ts.git)

### Steps to reproduce
写在前面：
我的项目是用vue-cli创建的ts项目，在项目中我是以vue官网文档上基于类的vue组件。

```
import Vue, {CreateElement} from 'vue';
import Component from 'vue-class-component';
import {Layout, Button} from 'ant-design-vue';
import SiderMenu from '@/components/SiderMenu';
import Header from './Header';
import TopNavHeader from '@/components/TopNavHeader';
import './BasicLayout.less';

const {Content} = Layout;

@Component

export default class BasicLayout extends Vue  {

render (h: CreateElement) {
    return (
      <div>
        <Layout>
          <Header>
            <TopNavHeader />
          </Header>
          <Layout>
            <SiderMenu />
            <Layout>
              <Content>
                <Button type='primary'>按钮</Button>
              </Content>
            </Layout>
          </Layout>
        </Layout>
      </div>
    )
  }
}
}
```

如上面代码所示，在使用Button这个组件时候，我试图给Button组件一个type，结果就出现了一个错误：
Type '{ type: string; }' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
Property 'type' does not exist on type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.

这个错误同样出现在ant-design-vue 的任意一个组件我去给它传递属性的时候，如传递一个class，style，size。

### What is expected?
可以正常使用任何一个组件

### What is actually happening?
组件无法传递任何属性

**Comment by wuchaoya** [comment]
补充说明：

 我在自己封装组件的时候也是遇到了一个相同的错误，开始是这样写的：

```
import Vue, {CreateElement} from 'vue';
import Component from 'vue-class-component';
import {  Prop } from "vue-property-decorator";
import './font/style.less';

@Component

export default class WebFont extends Vue {
  
  @Prop({default: '标题', type: String}) title!: string
  
  render (h: CreateElement, context: any) {
    return   <i class='webFont'>{this.$props.title}</i>
  }
}
```

之后: 
```
 import Vue, {CreateElement} from 'vue';
import Component from 'vue-class-component';
import {  Prop } from "vue-property-decorator";
import './font/style.less';

@Component

export default class WebFont extends Vue {
  
  @Prop({default: '爱云兔', type: String}) title!: string
  
  constructor (props: any) {
    super(props)
  }
  
  render (h: CreateElement, context: any) {
    return   <i class='webFont'>{this.$props.title}</i>
  }
}
```

加上了一个constructor 再使用这个组件就没有错误了。

**Comment by tangjinzhou** [comment]
如果方便可以帮助我们一起探索下 ts 的优化方案 😆

**Comment by wuchaoya** [comment]
我听说vue3的话会解决这个问题
