### ISSUE TITLE
Can an image component be provided?

### ISSUE THREAD

**Issue by hesunfly** [vueComponent/ant-design-vue#5420]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
组件可以提供图片的展示，图片墙展示，图片点击放大预览。之前使用element ui觉得挺好用，希望antdv也可以加上。

### What does the proposed API look like?
基本的api即可

**Comment by tangjinzhou** [comment]
https://next.antdv.com/components/image-cn

**Comment by hesunfly** [comment]
@tangjinzhou 我看到该组件为3.x版本提供，目前vue2可以使用3.x版本吗
