### ISSUE TITLE
How to use the virtual technology of large volume data of Select component in Vue2?

### ISSUE THREAD

**Issue by sicaifang** [vueComponent/ant-design-vue#5423]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1. solve the Select data more than 2,000, resulting in slow rendering, lag;
2. You don't need to upgrade Vue in order to upgrade the Select component.

### What does the proposed API look like?
vue：2.6
ant-design-vue： 1.7.2
browser：chrome 99
link：https://1x.antdv.com/components/select-cn

**Comment by sicaifang** [comment]
I hope 1. x will be sent a secondary version number

**Comment by tangjinzhou** [comment]
1.x no longer adds new features

**Comment by sicaifang** [comment]
好的，有什么好的解决方案可以建议么？
