### ISSUE TITLE
Input autofocus doesn't work

### ISSUE THREAD

**Issue by cihadturhan** [vueComponent/ant-design-vue#5427]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.3

### Environment
any browser vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-sfzp1z?file=/src/App.vue)

### Steps to reproduce
See codesandbox

### What is expected?
Should focus

### What is actually happening?
Doesn't focus

---
I think it's because of this.
It only works in testing environment?
https://github.com/vueComponent/ant-design-vue/blob/main/components/input/Input.tsx#L249

**Comment by tangjinzhou** [comment]
`autoFocus` fro 1.x
`autofocus` for 2.x、3.x

**Comment by yetiyeti1998** [comment]
> `autoFocus` for 1.x `autofocus` for 2.x、3.x

I tried, autofocus doesn't work
