### ISSUE TITLE
cascader component Initialize dynamic load value

### ISSUE THREAD

**Issue by 2720851545** [vueComponent/ant-design-vue#5429]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
none

### Reproduction link
[https://stackblitz.com/edit/vue-zee4mv?file=src/App.vue](https://stackblitz.com/edit/vue-zee4mv?file=src/App.vue)

### Steps to reproduce
Assigning a value to v-model:value or defaultValue will automatically call the loadData callback

### What is expected?
Assigning a value to v-model:value or defaultValue will automatically call the loadData callback

### What is actually happening?
After the component is initialized, assigning the initial value does not automatically call the loadData callback to load the child nodes, and only the first-level data is displayed

---
![](https://pic.imgdb.cn/item/624665b127f86abb2adeb2ef.jpg)

------

![](https://pic.imgdb.cn/item/624665b627f86abb2adebe0b.jpg)

**Comment by tangjinzhou** [comment]
Expected behavior, manually invoked on initialization
