### ISSUE TITLE
There are multiple input-numbers in a-space, and the layout is disordered after using addon-after

### ISSUE THREAD

**Issue by chenkby** [vueComponent/ant-design-vue#5437]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.3

### Environment
macOS 10.15.3，Chrome 100.0.4896.60（正式版本） (x86_64)，vue 3.2.31，antdv 3.1.0-rc.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-framework-ouegds?file=/src/App.vue)

### Steps to reproduce
可查看重现链接

### What is expected?
修复？

### What is actually happening?
修复或只能自己解决？

**Comment by labike** [comment]
style="display: flex;align-items: center;"

**Comment by labike** [comment]
个人感觉应该不算是bug;[a-space对齐](http://localhost:3000/components/space-cn#components-space-demo-align)

**Comment by tangjinzhou** [comment]
set align="center"
