### ISSUE TITLE
Component Menu-Single-file recursive menu three-level style display problem

### ISSUE THREAD

**Issue by Zwanwei** [vueComponent/ant-design-vue#5438]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue2.6.0     ant-design-vue1.7.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-forked-632kjr?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
问题1：点击第三级菜单Option 2-3-2，父节点选中样式正常，根节点选中样式丢失，发现丢失ant-menu-submenu-selected的className，inline-collapsed为true的情况下也是丢失的
问题2：重复问题1的步骤在theme为light的情况下根节点存在className为ant-menu-submenu-open，但是没有选中的样式，这在dark下是正常的

### What is expected?
希望在基于vue2的版本下被修复或给出临时的解决方法

### What is actually happening?
问题2只是一个样式展示的问题，但是问题1子项被选中，它的父级根节点却丢失了ant-menu-submenu-selected的className，这很重要。出现这样的问题好像是因为单文件递归菜单的问题，经过测试对于层级少不使用递归组件的情况下几乎是正常的。使用的代码几乎跟文档上的一致

![微信图片_20220403131416](https://user-images.githubusercontent.com/39650950/161412724-1d790b66-9eda-42a4-8832-12c140db2ee0.png)

![微信截图_20220403131544](https://user-images.githubusercontent.com/39650950/161412784-03e8837e-ea4b-4be3-a721-5c2ecfed4fdd.png)

@tangjinzhou 希望作者给与答复

**Comment by tangjinzhou** [comment]
1.x 版本可以试试用 jsx 或 render 函数构建多层菜单

3.x已经不用那么麻烦，可以考虑升级了

**Comment by Zwanwei** [comment]
> 1.x 版本可以试试用 jsx 或 render 函数构建多层菜单
> 
> 3.x已经不用那么麻烦，可以考虑升级了

感谢，我已用过jsx的方式解决了这个问题
