### ISSUE TITLE
drawer 组件无效

### ISSUE THREAD

**Issue by xuhaichaoy** [vueComponent/ant-design-vue#544]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
10.14.3

### Steps to reproduce
<template>
<div>
<a-button type="primary" @click="showDrawer">
Open
</a-button>
<a-drawer
title="Basic Drawer"
placement="right"
:closable="false"
@close="onClose"
:visible="visible"
>
<p>Some contents...</p>
<p>Some contents...</p>
<p>Some contents...</p>
</a-drawer>
</div>
</template>
<script>
export default {
data() {
return {
visible: false,
}
},
methods: {
showDrawer() {
this.visible = true
},
onClose() {
this.visible = false
},
},
}
</script>

### What is expected?
失效

### What is actually happening?
没有生效

**Comment by tangjinzhou** [comment]
使用这个提供有效的复现链接  https://codesandbox.io/s/2wpk21kzvr

**Comment by xuhaichaoy** [comment]
那个网站里面没有 复现

**Comment by tangjinzhou** [comment]
你不能复现，我只能猜，
可以看看issue 或许是这个问题 https://github.com/vueComponent/ant-design-vue/issues/305

**Comment by xuhaichaoy** [comment]
https://github.com/xuhaichaoy/my_website  这是我项目的地址 有空能看看嘛？ page 里面的 test.vue

**Comment by xuhaichaoy** [comment]
https://codesandbox.io/s/3rylv48vrq    复现了

**Comment by tangjinzhou** [comment]
使用这个 
`import Vue from "vue";`
而不是
`import Vue from "vue/dist/vue.js";`
