### ISSUE TITLE
Can't access the official website

### ISSUE THREAD

**Issue by labike** [vueComponent/ant-design-vue#5441]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
windows

### Reproduction link
[http://antdv.com](http://antdv.com)

### Steps to reproduce
无法访问官网

### What is expected?
快看看

### What is actually happening?
能访问官网

**Comment by mqhe2007** [comment]
me too

**Comment by labike** [comment]
https://www.antdv.com/components/overview-cn

**Comment by sugubei** [comment]
+1 空白页面

**Comment by labike** [comment]
http://1x.antdv.com

**Comment by tangjinzhou** [comment]
try again

**Comment by labike** [comment]
@tangjinzhou 
![Uploading 微信截图_20220406144802.png…]()

**Comment by labike** [comment]
@tangjinzhou 
![微信截图_20220406144802](https://user-images.githubusercontent.com/15871933/161912649-10b98ec2-b285-4f60-bf7b-f2574b347a73.png)

**Comment by tangjinzhou** [comment]
刷新不行吗   奇怪

**Comment by tangjinzhou** [comment]
先加上  www   
www.antdv.com

**Comment by labike** [comment]
@tangjinzhou www.antdv.com也不行,1x.antdv.com才能访问

**Comment by tangjinzhou** [comment]
应该可以了

**Comment by labike** [comment]
好了
