### ISSUE TITLE
form form reset does not reset the multi-select dropdown box correctly

### ISSUE THREAD

**Issue by Remiliia** [vueComponent/ant-design-vue#5445]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
vue 3.2.31

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiao-yan-qi-ta-zu-jian-ant-design-vue-3-1-1-forked-zq4djp?file=/src/demo.vue)

### Steps to reproduce
表单中使用select 组件的mode为multiple时，重置表单方法不能正确重置表单数据

### What is expected?
将表单数据重置为初始状态

### What is actually happening?
表单数据未正确重置

**Comment by MainHou** [comment]
` formState.multiple.length = 0;` restform函数中的 `formRef.value.resetFields();` 是验证格式用的

**Comment by Remiliia** [comment]
邮件已收到~（自动回复，无需理会^_^）

**Comment by MainHou** [comment]
Main、侯已经收到你的邮箱

**Comment by Remiliia** [comment]
> 数据重置是` formState.multiple.length = 0;` restform函数中的 `formRef.value.resetFields();` 是验证格式用的

官方文档是说的resetFields "对整个表单进行重置，将所有字段值重置为初始值并移除校验结果"
那调用是不是应该重置表单字段为初始的呢

**Comment by MainHou** [comment]
重置了验证的错误，但是没有重置表单

**Comment by MainHou** [comment]
用rules必须将name和你的form对应，你的初始值也要和规则的类型一致
![image](https://user-images.githubusercontent.com/32701177/162152189-b189c83b-d69d-4e52-a36b-442f163fe312.png)
![image](https://user-images.githubusercontent.com/32701177/162152221-0a974c33-2de6-49b4-8206-2c6b554550c0.png)

**Comment by Remiliia** [comment]
已解决，感谢
