### ISSUE TITLE
setting theme colors throw error

### ISSUE THREAD

**Issue by qq380428652** [vueComponent/ant-design-vue#5446]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
Window 64 ,Chrome v97.0.4692.99 ,Vue 3.2.25

### Reproduction link
[https://gitee.com/qq380428652/dance-web](https://gitee.com/qq380428652/dance-web)

### Steps to reproduce
1、import { ConfigProvider } from 'ant-design-vue'
2、
ConfigProvider.config({
theme: {
primaryColor: '#25b864',
},
});

### What is expected?
not throw error and normal use

### What is actually happening?
Uncaught TypeError: ConfigProvider.config is not a function

**Comment by tangjinzhou** [comment]
The reproduction you gave did not reproduce the problem

**Comment by qq380428652** [comment]
邮件已收到，会尽快处理！

**Comment by qq380428652** [comment]
Sorry. I just found that upgrading 'ant-design-vue' form v2.x to v3.x yesterday without restarting this service. no problem now
