### ISSUE TITLE
AMenuItemGroup  ->>>Error in render: "TypeError: renderMenuItem is not a function"

### ISSUE THREAD

**Issue by ShuangDa1018** [vueComponent/ant-design-vue#5447]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
all in  https://codesandbox.io/s/vue-antd-template-forked-75ue9l?file=/src/App.vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-75ue9l?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-forked-75ue9l?file=/src/App.vue ->>>>hower will have bug

### What is expected?
no =>  Error in render: "TypeError: renderMenuItem is not a function"

### What is actually happening?
Error in render: "TypeError: renderMenuItem is not a function"

---
大佬救我

**Comment by tangjinzhou** [comment]
选择正确的版本很难吗

**Comment by ShuangDa1018** [comment]
> 选择正确的版本吗

公司 用的1.7.0 作组件库，我试到1.7.8还是有这个bug ，是哪个分支改的  2x好像就是vue3了

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/162348820-fc4a023c-58f9-4c59-81fa-fd2d7606098d.png)

**Comment by ShuangDa1018** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/162348820-fc4a023c-58f9-4c59-81fa-fd2d7606098d.png)

ok，版本是1.7.8

**Comment by tangjinzhou** [comment]
1.x 版本 menu的子组件只能是 menugroup submenu menuitem ，
删除 a-spin

**Comment by ShuangDa1018** [comment]
但是1.7.0 这段代码没问题
