### ISSUE TITLE
select选择器为多选且maxTagCount设为0时无法正确显示为选项设置的title内容

### ISSUE THREAD

**Issue by youyi2016** [vueComponent/ant-design-vue#545]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.0

### Environment
vue ^2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5xoyvjpm1p)

### Steps to reproduce
a-select设置为多选，maxTagCount设为0

### What is expected?
鼠标放在选择器选项上显示提示框，提示框中显示当前选项的完整内容

### What is actually happening?
鼠标放在选择器选项上显示提示框，提示框中显示的是选择框中的内容，选择框中的内容是当前已经选择的选项个数

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/53638752-3c70d580-3c62-11e9-9226-dbf556e80ab1.png)

**Comment by tangjinzhou** [comment]
like this https://codesandbox.io/s/q3lvw3830w
