### ISSUE TITLE
Popover bubble card repeated rendering performance problem

### ISSUE THREAD

**Issue by rocky-git** [vueComponent/ant-design-vue#5450]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-nova-xsbw55?file=/src/App.vue)

### Steps to reproduce
在我使用content渲染大量组件的时候很卡，然后我 渲染了100 li标签做测试，我尝试用ref抓取数量，发现是100的好几倍，可以证明这里重复渲染了好几次导致性能问题

### What is expected?
希望能改进只渲染一遍，正常获取ref 数量100个

### What is actually happening?
渲染了100 li标签做测试，我尝试用ref抓取数量，发现是100的好几倍

![image](https://user-images.githubusercontent.com/44958386/162248258-69e7e4d8-7a85-41fa-acf7-c7da02e502b8.png)

**Comment by tangjinzhou** [comment]
第一、vue、ant-design-vue 都升级到最新版
第二、组件无法保证只render 一次，只保证最终结果
第三、如果需要获取 ref，可以将 ref 和 key 绑定，如 :ref=“(d)=> setItemRef(d, key)”
