### ISSUE TITLE
Empty Component

### ISSUE THREAD

**Issue by caiotarifa** [vueComponent/ant-design-vue#546]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm migrating a project from React to Vue and the "Empty" component is missing in the Vue library. Or at least I didn't find the documentation.

### What does the proposed API look like?
``` html
<Empty>
  <span>Customize <a href="#">Description</a></span>
  <Button>Create</Button>
</Empty>
```

The API should contain:

- `description`: as `String` or `v-slot`;
- `image`: as `String` or `v-slot:image`.

Original:

https://ant.design/components/empty/

**Comment by keikoro** [comment]
@Amour1688 You closed this issue without comment and I can't see any new labels attached to it, nor other issues or PRs linked. Is this a `wont-fix`, or was this solved, i.e. is there such a component now? Thanks.

**Comment by Amour1688** [comment]
@keikoro https://www.antdv.com/components/empty/

**Comment by keikoro** [comment]
Thank you!
