### ISSUE TITLE
MenuItem inside of CheckboxGroup renders "undefined-item" class.

### ISSUE THREAD

**Issue by caiotarifa** [vueComponent/ant-design-vue#547]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues) of this repository and believe that this is not a duplicate.

### Version
1.3.5

### Environment
macOS 10.14, Safari 12, Vue.js 2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1v0z432l97)

### Steps to reproduce
Create a dropdown (triggered from a button) that contains a list of checkboxes inside a MenuItem, which will be envolved by a CheckboxGroup.

``` html
<a-dropdown v-model="dropdown">
  <a-menu slot="overlay">
    <a-menu-item>
      <a-checkbox>Out</a-checkbox>
    </a-menu-item>

    <a-menu-divider />

    <a-checkbox-group v-model="selectedItems">
      <a-menu-item v-for="item in items" :key="item.value">
        <a-checkbox :value="item.value">Inner {{ item.label }}</a-checkbox>
      </a-menu-item>
    </a-checkbox-group>
  </a-menu>

  <a-button>
    Hover me!
    <a-icon type="down" />
  </a-button>
</a-dropdown>
```

Test JavaScript for this example:

``` js
export default {
  data() {
    return {
      dropdown: false,
      selectedItems: []
    };
  },

  computed: {
    items() {
      return [
        { label: "Item 1", value: "_1" },
        { label: "Item 2", value: "_2" },
        { label: "Item 3", value: "_3" },
        { label: "Item 4", value: "_4" },
        { label: "Item 5", value: "_5" }
      ];
    }
  }
};
```

### What is expected?
The `LI` rendered by `MenuItem` should have `ant-dropdown-menu-item` class.

### What is actually happening?
The `LI` has `undefined-item` class.

---
Another option would be to create a "transparent" `<a-checkbox-group>` that doesn't render an element, like a `<div>`.

**Comment by tangjinzhou** [comment]
The children of Menu must be `MenuItem` or `SubMenu` or `MenuDivider`.
