### ISSUE TITLE
table columns 设置width属性无效

### ISSUE THREAD

**Issue by Rain120** [vueComponent/ant-design-vue#548]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.1.2

### Environment
vue 2.5.2 chrome 72

### Steps to reproduce
table columns 设置width属性无效，width取值为etc. '10%'

### What is expected?
width限制宽度

### What is actually happening?
width属性值无效

**Comment by tangjinzhou** [comment]
请提供复现链接 谢谢

**Comment by Rain120** [comment]
> 请提供复现链接 谢谢

暂时是本地开发，没有复现链接，只有代码和页面截图

![image](https://user-images.githubusercontent.com/20939839/53791150-ad1a3980-3f63-11e9-8c0c-207706bd1bab.png)

![image](https://user-images.githubusercontent.com/20939839/53791195-c8854480-3f63-11e9-8737-6ef25c9abbc2.png)
![image](https://user-images.githubusercontent.com/20939839/53791208-cf13bc00-3f63-11e9-8794-2ad9d12e35cb.png)
![image](https://user-images.githubusercontent.com/20939839/53791255-ec488a80-3f63-11e9-9c8d-987a04581b1b.png)

**Comment by tangjinzhou** [comment]
使用 https://codesandbox.io/s/2wpk21kzvr 提供复现链接 谢谢

**Comment by Rain120** [comment]
我找到我的错误了，谢谢

**Comment by nature-li** [comment]
@Rain120 请问错误在哪里啊？

**Comment by hzyyy** [comment]
请问怎么解决的

**Comment by Rain120** [comment]
@hzyyy 你可以考虑customRender函数，自定义dom，定义新的style，你可以试试

**Comment by Rain120** [comment]
@nature-li 有点久远，不记得了，不过貌似这个属性没作用，我又试了一次，还是一样，试试强制dom样式修改吧

**Comment by Rain120** [comment]
@nature-li 有点久远，不记得了，不过貌似这个属性没作用，我又试了一次，还是一样，试试强制dom样式修改吧

**Comment by Rain120** [comment]
@nature-li 有点久远，不记得了，不过貌似这个属性没作用，我又试了一次，还是一样，试试强制dom样式修改吧
