### ISSUE TITLE
vite config for customize theme

### ISSUE THREAD

**Issue by hamedg68** [vueComponent/ant-design-vue#5481]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I use vite and unplugin-vue-components and now I want to customize theme but there is no documentation for it. any one can help me completely?

### What does the proposed API look like?
customize theme with vite and unplugin-vue-components

**Comment by kimmanwky** [comment]
@hamedg68 are you manage to solve it? I have the same problem. Please provide some guides to help me out if you have the solutions or references. Thanks.

**Comment by zkwolf** [comment]
@kimmanwky Provide a minimal reproduction or repo. I will try to give you the solution.
