### ISSUE TITLE
In version 3.1.1, the custom expand collapse icon is used in the tree component, and the rotation style is lost.

### ISSUE THREAD

**Issue by xzp-git** [vueComponent/ant-design-vue#5484]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
vue 3.2.31

### Reproduction link
[https://www.antdv.com/components/tree-cn#components-tree-demo-customized-icon](https://www.antdv.com/components/tree-cn#components-tree-demo-customized-icon)

### Steps to reproduce
-The custom unfold and collapse icon used in version 3.1.1 will not rotate     https://www.antdv.com/components/tree-cn#components-tree-demo-customized-icon

-In version 2.x.x, the user-defined expansion and collapse icon can be rotated        https://2x.antdv.com/components/tree-cn#components-tree-demo-switcher-icon

### What is expected?
Is this how the tree component was designed in version 3.1.1? Or is this a bug

### What is actually happening?
The custom unfold and collapse icon used in version 3.1.1 will not rotate

---
The default expand collapse icon can be rotated.
Add the class name "switchercls = ` ${prefixcls} - switcher icon `" to the custom expansion and collapse icon, and the rotation style will take effect.

Check the code and find it in " ant design Vue \ components \ tree \ utils \ iconutil Tsx "  will add the class name  " switchercls = ` ${prefixcls} - switcher icon ` " to the default icon.

In "3.1.1", if you want to use a custom expansion and collapse icon, "switchercls" class name will be passed to the user as a parameter of the scope slot, instead of directly adding the class name to the custom icon as in "2.1.3".

**Comment by tangjinzhou** [comment]
use `<template #switcherIcon="{ switcherCls }"><down-outlined :class="switcherCls" /></template>`

**Comment by xzp-git** [comment]
Does the props type description in the tree switchicon document need to be modified？#5485
