### ISSUE TITLE
TypeError with nuxt-ts-edge 2.5 & ant-design-vue 1.3.5 in SubPopupMenu

### ISSUE THREAD

**Issue by ux-engineer** [vueComponent/ant-design-vue#549]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
### Version
1.3.5

### Environment
Mac 10.14.3, Chrome 72.0.3626.119

### Reproduction link
[https://github.com/envision/nuxt-ts-with-antd-submenu-bug](https://github.com/envision/nuxt-ts-with-antd-submenu-bug)

### Steps to reproduce
`git clone https://github.com/envision/nuxt-ts-with-antd-submenu-bug && cd nuxt-ts-with-antd-submenu-bug && yarn && yarn dev`

### What is expected?
Ant Design Vue library's components should be usable in vue templates after importing plugin via a plugin file.

### What is actually happening?
In file `/app/components/AppHeader.vue` there is`a-menu` component with a single nested `a-menu-item`. If that item is removed, there is no errors, but with it:

```
TypeError
Cannot read property 'propsData' of undefined
../node_modules/ant-design-vue/lib/vc-menu/SubPopupMenu.js:318:47
```

---
AntD components are not working in templates here on Nuxt like they were working on plain Vue (I'm refactoring to Nuxt in TypeScript here). In AppHeader I needed to import each component individually to be able to use them. Even though for what I've read the guides and threads, it seems that these components should be working without individually importing them. Using a plugin file to import the library at `/app/plugins/antd-ui.js`.

**Comment by dzcpy** [comment]
Nuxt, Typescript and Antd Vue... I don't think they work toghether very well...

**Comment by dzcpy** [comment]
By the way, I'm developing a module, which will help integrating Ant Design Vue with Nuxt. So far it works pretty well. I'll release it after polishing it a bit more.

**Comment by dzcpy** [comment]
https://github.com/dzcpy/nuxt-ant-design-vue
