### ISSUE TITLE
The default class of button is ant-btn, can you add a unique one, such as ant-btn-default, to facilitate individual customization of styles

### ISSUE THREAD

**Issue by zhang-jianxun** [vueComponent/ant-design-vue#5490]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
可以通过class名称单独修改默认样式

### What does the proposed API look like?
class="ant-btn ant-btn-default"

**Comment by tangjinzhou** [comment]
？ 自己加不就完了  <a-button class="custom-classname"></a-button>

**Comment by zhang-jianxun** [comment]
> 单独修改默认样式



> ？ 自己加不就完了 `<a-button class="custom-classname"></a-button>`

我的意思是单独定制type为default的按钮样式，而不影响type为primary | ghost | dashed | link | text的样式，目前我是通过not排除掉了其他class。
