### ISSUE TITLE
Inputnumber setting prefix is invalid

### ISSUE THREAD

**Issue by xjpe** [vueComponent/ant-design-vue#5493]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.4

### Environment
Vue3

### Reproduction link
[https://www.antdv.com/components/input-number-cn#components-input-number-demo-prefix](https://www.antdv.com/components/input-number-cn#components-input-number-demo-prefix)

### Steps to reproduce
<a-input-number
prefix="$"
class="tw-w-24"
style="width: 100%"
v-model:value="values[0]"
:controls="false"
>
</a-input-number>

### What is expected?
Inputnumber can set prefix normally

### What is actually happening?
Inputnumber setting prefix is invalid

---
Version：
"ant-design-vue": "^3.0.0-alpha.14",

**Comment by tangjinzhou** [comment]
update to 3.1.1
