### ISSUE TITLE
a-time-range-picker setting the hour, minute and second step has no effect

### ISSUE THREAD

**Issue by yangliusi0826** [vueComponent/ant-design-vue#5498]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0-rc.2

### Environment
系统：win11、浏览器：Google Chrome 100.0.4896.88、Vue：3.2.31

### Reproduction link
[https://antdv.com/components/time-picker-cn](https://antdv.com/components/time-picker-cn)

### Steps to reproduce
```
<a-time-range-picker :minute-step="30" />
```

### What is expected?
时间范围选择器可以支持使用 hourStep minuteStep secondStep 按步长展示可选的时分秒

### What is actually happening?
时间范围选择器设置hourStep minuteStep secondStep 不生效，目前是有单个的时间选择器设置步长才生效

**Comment by wuyuedefeng** [comment]
version: 3.2.0 exists same problem.

**Comment by yangh-fe** [comment]
3.2.3遇到同样的问题，现在有解决方案吗

**Comment by yangliusi0826** [comment]
> 3.2.3遇到同样的问题，现在有解决方案吗
可以使用日期时间组件，日期时间组件中是可以设置时间步长的
