### ISSUE TITLE
Table component, when the row height of other columns changes, the row height of the fixed column will not change synchronously

### ISSUE THREAD

**Issue by xiaogang12131** [vueComponent/ant-design-vue#5499]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue3.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
当table列中嵌入文本框textarea或多选框时，输入内容，列的高度发生变化

### What is expected?
左右固定列的高度也随着一起变化

### What is actually happening?
左右固定列的高度不变，导致错位

**Comment by arika163** [comment]
https://codesandbox.io/s/throbbing-shape-0k1jwf?file=/src/App.vue
