### ISSUE TITLE
Warning about the Input component

### ISSUE THREAD

**Issue by wvq** [vueComponent/ant-design-vue#5504]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
antdv 3.1.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-leavitt-dziv5b)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue/blob/cddaf8cbc47e025e0d239d27975c70a5a5b20dac/components/input/Input.tsx#L286-L313

If `inputProps.size` is a false value, like `0`, `null`, `undefined`,
and pass it to `<input {...inputProps} />`.

A warning appears.

[Vue warn]: Failed setting prop "size" on : value 0 is invalid. DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.

### What is expected?
do not warning.

### What is actually happening?
[Vue warn]: Failed setting prop "size" on : value 0 is invalid. DOMException: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.

**Comment by tangjinzhou** [comment]
size only support `large` `default` `small`

**Comment by ayizhi** [comment]
> size only support `large` `default` `small`

don't close 😂
I get this problem as well, if not set the "size" attr of  a-input, this warning would be ejected.
on the case of ant-design-vue is required by **"script" or webpack external**
but there should be default value of a-input
hope for fixed, thx for creating this remarkable ui component project
