### ISSUE TITLE
Error when compiling yarn build

### ISSUE THREAD

**Issue by weilianxiao** [vueComponent/ant-design-vue#5506]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
windows&linux vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/main/components](https://github.com/vueComponent/ant-design-vue/tree/main/components)

### Steps to reproduce
yarn build时报 Rollup failed to resolve import "project_url/.../node_modules/ant-design-vue/es/textarea/style/index" from "src/views/formDevelopment/index.vue".
This is most likely unintended because it can break your application at runtime

### What is expected?
希望能解决yarn build报错问题

### What is actually happening?
已经找到问题所在 yarn install 后 node_modules/ant-design-vue/es/文件夹下无textarea文件夹 ，需要创建textarea文件夹 并从node_modules/ant-design-vue/es/input中把关于textarea文件复制到新创建的node_modules/ant-design-vue/es/textarea文件夹中才可以编译通过

**Comment by tangjinzhou** [comment]
用了什么插件吧，去给插件提 issue 吧

**Comment by weilianxiao** [comment]
可能是描述有问题 没用其他插件 v3版本 开发时引用Textarea是可以run起来的 但是build的时候编译不成功 看了下你源码的目录 Textarea是在Input下面的  在代码里使用   const { Textarea } = Input  运行和编译则都会报错 是否可以在下个版本的时候运行和编译保持一致

**Comment by hunshcn** [comment]
猜测使用 vben-admin？那应该与 https://github.com/vbenjs/vue-vben-admin/pull/2365 有关
