### ISSUE TITLE
Input component causes warning: "Failed setting prop "size" on <input>: value 0 is invalid"

### ISSUE THREAD

**Issue by keithhchen** [vueComponent/ant-design-vue#5509]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
`ant-design-vue@3.1.1`, `vue@3.2.33`

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-cloud-yh4y5n?file=/src/App.vue)

### Steps to reproduce
1. Follow "Getting Started" steps to create `antd-demo` from [antdv.com](https://www.antdv.com/docs/vue/getting-started)
2. Paste the 1st code example from [antdv.com - components - form](https://www.antdv.com/components/form/#Form-Item-Component) into App.vue or any SFC
```vue
<template>
  <a-form
    :model="formState"
    name="basic"
    :label-col="{ span: 8 }"
    :wrapper-col="{ span: 16 }"
    autocomplete="off"
    @finish="onFinish"
    @finishFailed="onFinishFailed"
  >
    <a-form-item
      label="Username"
      name="username"
      :rules="[{ required: true, message: 'Please input your username!' }]"
    >
      <a-input v-model:value="formState.username" />
    </a-form-item>

    <a-form-item
      label="Password"
      name="password"
      :rules="[{ required: true, message: 'Please input your password!' }]"
    >
      <a-input-password v-model:value="formState.password" />
    </a-form-item>

    <a-form-item name="remember" :wrapper-col="{ offset: 8, span: 16 }">
      <a-checkbox v-model:checked="formState.remember">Remember me</a-checkbox>
    </a-form-item>

    <a-form-item :wrapper-col="{ offset: 8, span: 16 }">
      <a-button type="primary" html-type="submit">Submit</a-button>
    </a-form-item>
  </a-form>
</template>
<script>
import { defineComponent, reactive } from 'vue';
export default defineComponent({
  setup() {
    const formState = reactive({
      username: '',
      password: '',
      remember: true,
    });

    const onFinish = values => {
      console.log('Success:', values);
    };

    const onFinishFailed = errorInfo => {
      console.log('Failed:', errorInfo);
    };

    return {
      formState,
      onFinish,
      onFinishFailed,
    };
  },

});
</script>
```
3. Check console for warning:
```
[Vue warn]: Failed setting prop "size" on <input>: value 0 is invalid.
Error: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
```
4. Downgrading to `ant-design-vue@2.2.8` will remove console warning

### What is expected?
Input component should work without warning.

### What is actually happening?
```
[Vue warn]: Failed setting prop "size" on <input>: value 0 is invalid.
Error: Failed to set the 'size' property on 'HTMLInputElement': The value provided is 0, which is an invalid size.
```

---
Warning only occurs with `<a-input>`. In the case of `textarea` (from [here](https://www.antdv.com/components/form/#components-form-demo-lable-width)), `<a-input v-model:value="formState.desc" type="textarea" />` will also produce console warning. Using `<a-textarea>` instead will not.

This occurs in any version > 3.0.

**Comment by Mako-Jin** [comment]
I have the same problem

**Comment by yearspark** [comment]
我也遇到同样的问题，也是更新到最新版本时候，会出现这个警告

**Comment by tangjinzhou** [comment]
ref #5177 
update vue

**Comment by IFnGSiYu** [comment]
更新了vue也不行
