### ISSUE TITLE
When select is used with a-select-option, filterOption cannot get the label, and option-filter-prop is also invalid.

### ISSUE THREAD

**Issue by transtone** [vueComponent/ant-design-vue#5510]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
antdv-3.1.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-0rb2g6?file=/src/App.vue)

### Steps to reproduce
select 在配合a-select-option使用时，filterOption 无法获取到 label，option-filter-prop 也失效。

### What is expected?
select 在配合a-select-option使用时，filterOption 能获取到 label，option-filter-prop 有效。

### What is actually happening?
select 在配合a-select-option使用时，filterOption 无法获取到 label，option-filter-prop 也失效。

**Comment by transtone** [comment]
https://github.com/vueComponent/ant-design-vue/issues/4492

**Comment by tangjinzhou** [comment]
请提供正确的版本：复现是 1.7 这里又是 3.1

**Comment by zkwolf** [comment]
#4836 参考这个看看能不能解决
