### ISSUE TITLE
PageHeader header

### ISSUE THREAD

**Issue by q7486828035** [vueComponent/ant-design-vue#5511]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
mac 12.3.1 (21E258),谷歌版本 100.0.4896.88（正式版本） (x86_64)，"vue": "^3.0.0",

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/3613](https://github.com/vueComponent/ant-design-vue/issues/3613)

### Steps to reproduce
PageHeader 在 browserHistory 路由模式下，出现 # 号，根据 https://github.com/vueComponent/ant-design-vue/issues/3613 方案可用 但会出现警告， 插槽 itemRender 也无法使用

### What is expected?
browserHistory模式不需要 # 号

### What is actually happening?
路由跳转带出了 #

**Comment by q7486828035** [comment]
警告是由 resolveComponent router-link 这个组件提示的，插槽 itemRender 是无法使用的

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/stoic-mendel-h8nq3n?file=/src/App.vue
