### ISSUE TITLE
Tree custom expand/collapse icon style problem

### ISSUE THREAD

**Issue by johnnyhwa** [vueComponent/ant-design-vue#5512]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
OS: Win11; Browser: chrome：100.0.4896.88（正式版本） （64 位）; Vue: 3.2.11

### Reproduction link
[https://www.antdv.com/components/tree-cn](https://www.antdv.com/components/tree-cn)

### Steps to reproduce
1. 打开ant-design-vue 2.x版本文档
https://2x.antdv.com/components/tree-cn，查看Tree组件，自定义展开/折叠图标示例，点击展开图标

2. 打开ant-design-vue 3.x版本文档
https://www.antdv.com/components/tree-cn，查看Tree组件，自定义展开/折叠图标示例，点击展开图标

3. 比较展开树节点后，图标的样式表现

### What is expected?
3.x版本的Tree组件表现与2.x版本一致，展开后Icon自动转向

### What is actually happening?
3.x版本更新后，自定义展开/折叠图标在节点折叠后无相关样式联动

**Comment by tangjinzhou** [comment]
ref https://github.com/vueComponent/ant-design-vue/issues/5484
