### ISSUE TITLE
The official website documentation is switched to version 3.0 by default, and the old 2.0 documentation cannot be found

### ISSUE THREAD

**Issue by liukaibin123** [vueComponent/ant-design-vue#5519]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
https://2x.antdv.com/docs/vue

### Reproduction link
[https://2x.antdv.com/docs/vue](https://2x.antdv.com/docs/vue)

### Steps to reproduce
https://2x.antdv.com/docs/vue

### What is expected?
请保留原来的2.0的版本文档，得考虑老用户的使用。你们当前2.2.8的文档明显不对，是3.0的用法。请尽快解决，阻塞我们老用户的使用了，把原来的2.0版本的文档API还原出来

### What is actually happening?
官网文档默认切换到3.0版本了，老的2.0文档找不到了。我们项目都是用的vue2.0，antd-design 也是2.0版本。 我们很大的项目，不可能切到3.0的。现在2.0文档都找不到了，上面那个2.2.8版本的文档也根本不是原来的文档。 很不合理啊。起码得考虑我们这些老用户的使用吧， 直接找不到2.0的版本文档了。

**Comment by tangjinzhou** [comment]
antd-design 2 是 vue 3 的，你这样自己都搞不清楚版本，很不合理啊，起码得考虑我们这些开发者的理解能力吧，直接懵逼了
