### ISSUE TITLE
The tooltip arrow has a strange location.

### ISSUE THREAD

**Issue by joseph415** [vueComponent/ant-design-vue#5521]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
^3.1.1

### Environment
chrome 100.0.4896.127, vue ^3.2.31

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/el2170)

sorry reproduction link is CodeSendBox in docs example. 
It works fine here, but it works weird when you import a library from a local environment.

### Steps to reproduce
If you copy and paste the example of tooltip docs, the arrow direction of the tooltip will be strange.

It's not just a tooltip issue, it's the same with popover.

### What is expected?
It should look the same as the example in docs.

### What is actually happening?
The direction of the arrow enters the tooltip content box.
As a result of debugging, the position of *, *::before, and *::after is relative, but if you change it to static, it will work normally.

**Comment by tangjinzhou** [comment]
you can try upload some img snap

**Comment by joseph415** [comment]
@tangjinzhou 
I'm sorry, this is not an issue. The position attribute was changed in my project base.
I don't think it'll be a problem if we close the issue. 

Thank you
