### ISSUE TITLE
[Vue warn]: Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array 

### ISSUE THREAD

**Issue by 35871342** [vueComponent/ant-design-vue#5522]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
Vue3、Vite、TypeScript

### Reproduction link
[https://vvbin.cn/next/#/comp/form/basic](https://vvbin.cn/next/#/comp/form/basic)

### Steps to reproduce
[Vue warn]: Invalid prop: type check failed for prop "onUpdate:value". Expected Function, got Array
at <ASelect onDropdownVisibleChange=fn<handleFetch> showSearch="" onUpdate:value=
Array [ value($event), 0($event)
]
... >
at <ApiSelect api=fn<optionsListApi> showSearch="" value="0"  ... >
at <ACol style=
Object { width: "calc(100% - 200px)" }
class="ant-form-item-control" >
at <Anonymous name="field32" label=
Object { __v_isVNode: true, __v_skip: true, type: "span", props: null, key: null, ref: null, scopeId: null, slotScopeIds: null, children: (2) […], component: null, … }
rules=
Array [ {…} ]
... >
at <ARow class="ant-form-item" key="row" >
at <AFormItem name="field32" colon=false class=""  ... >
at <ACol span=8 >
at <BasicFormItem key="field32" tableAction=undefined formActionType=
Object { getFieldsValue: getFieldsValue(), setFieldsValue: async setFieldsValue(values), resetFields: async resetFields(), updateSchema: async updateSchema(data), resetSchema: async resetSchema(data), setProps: async setProps(formProps), removeSchemaByFiled: async removeSchemaByFiled(fields), appendSchemaByField: async appendSchemaByField(schema, prefixField, first), clearValidate: async clearValidate(name), validateFields: async validateFields(nameList)
, … }
... >
at <ARow style=
Object {  }
>
at <AForm actionColOptions=
Object { span: 24 }
model=
Object { field2: "111", field30: "0", field31: "0", field32: "0", field34: "1", selectA: [], selectB: [], field22: 3 }
labelWidth=200  ... >
at <BasicForm autoFocusFirstItem="" labelWidth=200 schemas=
Array(31) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
... >
at <BaseTransition mode="out-in" onBeforeEnter=fn<onBeforeEnter> onEnter=fn  ... >
at <Transition mode="out-in" onBeforeEnter=fn<beforeEnter> onEnter=fn<enter>  ... >
at <CollapseTransition enable=true >
at <CollapseContainer title="基础示例" >
at <PageWrapper title="表单基础示例" contentFullHeight="" >
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<
Proxy { <target>: {…}, <handler>: {…} }
> key="/comp/form/basic" >
at <KeepAlive key=0 include=
Array(3) [ "Analysis", "UseFormDemo", "FormBasicDemo" ]
>
at <BaseTransition mode="out-in" appear=true persisted=false  ... >
at <Transition name="fade-slide" mode="out-in" appear="" >
at <RouterView>
at <PageLayout>
at <LayoutContent>
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="vben-default-layout-main" >
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="ant-layout ant-layout-has-sider" >
at <Anonymous hasSider=undefined prefixCls="ant-layout" tagName="section"  ... >
at <ALayout class="vben-default-layout" >
at <DefaultLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref<
Proxy { <target>: {…}, <handler>: {…} }
> >
at <RouterView>
at <AppProvider>
at <ALocaleProvider locale=
Object { locale: "zh-cn", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, global: {…}, Table: {…}, Modal: {…}, Popconfirm: {…}, Transfer: {…}, … }
ANT_MARK__="internalMark" >
at <LocaleReceiver children=fn<children> >
at <AConfigProvider locale=
Object { locale: "zh-cn", Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, global: {…}, Table: {…}, Modal: {…}, Popconfirm: {…}, Transfer: {…}, … }
>
at <App> runti

### What is expected?
不在出现这种警告错误。

### What is actually happening?
表单控件点击任意一个，都提示这种错误。

---
最新版更新后，在表单控件应用中存在这个问题。

**Comment by tangjinzhou** [comment]
你可以去 vvbin 提issue
