### ISSUE TITLE
Image component, close the mask and its content when hovering

### ISSUE THREAD

**Issue by wishong** [vueComponent/ant-design-vue#5524]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
vue3

### Reproduction link
[https://www.antdv.com/components/image-cn](https://www.antdv.com/components/image-cn)

### Steps to reproduce
最新版本，hover的时候会出现一个mask，但是之前版本没有
通过现有 api 似乎无法移除mask

### What is expected?
移除 mask

### What is actually happening?
mask 无法移除

**Comment by tangjinzhou** [comment]
用 css 覆盖

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/164225542-e9055f39-6c17-409b-a0df-9114d673d594.png)
待发版后，可通过设置`previewMask`为`false`取消mask
