### ISSUE TITLE
v2 documents is v3 content?

### ISSUE THREAD

**Issue by tu6ge** [vueComponent/ant-design-vue#5525]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
web

### Reproduction link
[https://2x.antdv.com/components/select-cn](https://2x.antdv.com/components/select-cn)

### Steps to reproduce
v2 docs is same as v3 docs

### What is expected?
v2 select docs is change to normal

### What is actually happening?
v3 select docs

**Comment by tu6ge** [comment]
the post issue is very difficulty

**Comment by zkwolf** [comment]
哪里看出来是V3的？

**Comment by tu6ge** [comment]
Is v2 requirement vue3 ? I was careless
