### ISSUE TITLE
After upgrading to 3.2.0, vite packaging error

### ISSUE THREAD

**Issue by summer1874** [vueComponent/ant-design-vue#5527]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
node-v16.14.2 vue-v3.2.33

### Reproduction link
[https://github.com/summer1874/vue3-admin-template](https://github.com/summer1874/vue3-admin-template)

### Steps to reproduce
build

### What is expected?
打包成功

### What is actually happening?
打包报错

**Comment by buqiyuan** [comment]
建议你提交代码的时候 不要提交`auto-import.d.ts`文件，或者更改你的插件配置
