### ISSUE TITLE
Add a formatter feature to input similar to input-number

### ISSUE THREAD

**Issue by jimvandervoort** [vueComponent/ant-design-vue#553]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I often want to add some formatting to my text inputs to e.g trim whitespaces or capitalise the first letter of an input.

This improves end user experience because they can immediately see how their values will actually be parsed and edit their input if required.

I don't believe we'll need to implement a parser since input components don't need to convert from String to Number.

### What does the proposed API look like?
Formatter would be identical to input-number:
```vue
<template>
  <a-input
    placeholder="First name"
    v-model="lastname"
    formatter="value => value.trim"
  >
</template>
```

**Comment by uniquejava** [comment]
decorator也需要! 现在用户仅输入了空格.   就满足规则了.. 这个怎么简单的处理?
rules中也能不能加个`trim:true`的属性. @tangjinzhou 
 
```html
  <a-input
            maxlength="32"
            v-decorator="['name', { rules: [{ required: true, trim:true, message: this.$t('xxx.nameRequired') }] }]"
          />
```

**Comment by 540240126** [comment]
same here

**Comment by tangjinzhou** [comment]
formatter 只是做展示格式化，最终的value 并没有变化
考虑：transformValue
