### ISSUE TITLE
The document instance has an error (Dropdown)

### ISSUE THREAD

**Issue by lppoi** [vueComponent/ant-design-vue#5536]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
Vue3

### Reproduction link
[https://www.antdv.com/components/dropdown-cn](https://www.antdv.com/components/dropdown-cn)

### Steps to reproduce
Dropdown component  attribute placement has error

### What is expected?
"topCenter", "bottomCenter"

### What is actually happening?
"top""bottom"

**Comment by tangjinzhou** [comment]
v3 以上就是 top bottom

**Comment by lppoi** [comment]
***@***.***
Antd Vue版本是3.2.0

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月22日 10:22
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [vueComponent/ant-design-vue] The document instance has an error (Dropdown) (Issue #5536)


v3 以上就是 top bottom

―
