### ISSUE TITLE
message content vnode is empty

### ISSUE THREAD

**Issue by maxiloEmmmm** [vueComponent/ant-design-vue#554]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
ant-design-vue@1.3.5 vue@2.6.7 chrome@69.0.3497.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pkky869ym0?fontsize=14)

### Steps to reproduce
ant-design-vue@1.3.5
vue@2.6.7
chrome@69.0.3497.106

```js
this.$utils.msg.info(h=>{
return (<div>1</div>)
}, 5)
```
![image](https://user-images.githubusercontent.com/16779121/53825971-820b0680-3fb2-11e9-8c83-407eedc33dab.png)

```js
this.$utils.notification.info({
description: h=>{
return (<div>1</div>)
},
message: 'x',
duration: 5
})
```
![image](https://user-images.githubusercontent.com/16779121/53826061-b41c6880-3fb2-11e9-82b5-3fa84030bf6a.png)

### What is expected?
vnode display in message component

### What is actually happening?
vnode no display in message component

**Comment by sendya** [comment]
Hi, dear:

Please refer to [![](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rr5o12zlwq?fontsize=14)

**Comment by tangjinzhou** [comment]
@sendya we should support `VNode` and ` (h)=>VNode` . 

@maxiloEmmmm  You can use vnode directly like @sendya .
we will fix it in next version.

**Comment by maxiloEmmmm** [comment]
@sendya 
@tangjinzhou 
thx.

**Comment by yurizhang** [comment]
這個在
    this.$confirm({
             title: 'Confirm',
             content:  <strong>content</strong>}） 好像也不行

**Comment by xhubert** [comment]
这样处理，亲测可行：
```html
...
          <a-button
            @click="confirm"
          >
            Confirm
          </a-button>
···
```
```javascript
confirm() {
      const confirmOptions = {
        title: 'Confirm',
        content: (
          <div>
            <p>some messages...some messages...</p>
            <p>some messages...some messages...</p>
          </div>
        ),
        okText: 'OK',
        cancelText: 'Cancel',
        autoFocusButton: 'cancel',
        onOk: () => {
          return new Promise((resolve, reject) => {
            setTimeout(Math.random() > 0.5 ? resolve : reject, 1000)
          }).catch(() => console.log('Oops errors!'))
        }
      }
      this.$confirm(confirmOptions)
}
```
