### ISSUE TITLE
Progress dashboard styles missing

### ISSUE THREAD

**Issue by ShawnKoga** [vueComponent/ant-design-vue#5549]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
Vue 3

### Reproduction link
[https://www.antdv.com/components/progress](https://www.antdv.com/components/progress)

### Steps to reproduce
<a-progress type="dashboard" :percent="75" />

### What is expected?
The dashboard style of a-progress should be styled so it isn't a full circle

### What is actually happening?
The dashboard style of a-progress matches the circle style of a-progress

**Comment by tangjinzhou** [comment]
?

**Comment by ShawnKoga** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/30784153/165212136-43dfd6ef-0e05-4c70-9b40-6e1e0de84134.png">

**Comment by tangjinzhou** [comment]
now you can set `:gapDegree="75"`.
we will fixed at next version
