### ISSUE TITLE
tabs设置activeKey后无法切换的bug

### ISSUE THREAD

**Issue by xiaoming0827** [vueComponent/ant-design-vue#555]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome 72.0.3626.121（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qql7r55j5w)

### Steps to reproduce
1、使用tabs组件
2、给tabs设置activeKey属性，点击tab不能正常切换

### What is expected?
可以正常切换而且绑定的activeKey的值会随着切换而变化

### What is actually happening?
给tabs设置activeKey属性，点击tab不能正常切换

**Comment by sendya** [comment]
你好，请参照以下用法

[![](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w093p5rr4l?fontsize=14&module=%2Fsrc%2FApp.vue)

需要注意的是 


参数 | 说明 | 类型 | 默认值
-- | -- | -- | --
activeKey(v-model) | 当前激活 tab 面板的 key | string | 无

`activeKey` 不是 `.sync` 的，所以无法由组件修改你的绑定值，需要你自行维护。

**Comment by tangjinzhou** [comment]
也可以直接v-modl="activeKey"
