### ISSUE TITLE
Timeline component adds horizontal style

### ISSUE THREAD

**Issue by L-Z-Y** [vueComponent/ant-design-vue#5552]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
We need to use a horizontal timeline in development, but it seems that the component does not support it at present

### What does the proposed API look like?
like this "https://arco.design/vue/component/timeline"

**Comment by tangjinzhou** [comment]
you can use steps component.
https://www.antdv.com/components/steps
