### ISSUE TITLE
When the showline attribute is used in the Tree component, the switcherIcon of the current node keeps the expanded state on the treeData source data

### ISSUE THREAD

**Issue by webwusen** [vueComponent/ant-design-vue#5554]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.2

### Environment
"ant-design-vue": "^3.2.2", "vue": "^3.2.23"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-wright-5711ip?file=/src/App.vue)

### Steps to reproduce
1.Click on the switcherIcon of parent 1
2.The SwitcherIcon of parent 1 will not change

### What is expected?
SwitcherIcon can change

### What is actually happening?
SwitcherIcon will not change

**Comment by zkwolf** [comment]
不应该添加expanded:true吧

**Comment by tangjinzhou** [comment]
Your example cannot be reproduced

**Comment by webwusen** [comment]
https://5711ip.csb.app/
![7759f2c6970bdc40997751f524a6e9c2](https://user-images.githubusercontent.com/47802031/165672029-2f506a23-9d73-40ac-951a-8304c2fb060c.gif)
parent 1节点的图标一直是minus-square
其它的会变化

**Comment by tangjinzhou** [comment]
> 不应该添加expanded:true吧

是的，会覆盖组件属性
