### ISSUE TITLE
Error Uncaught TypeError: Cannot read properties of null (reading 'match') when using pagination

### ISSUE THREAD

**Issue by zengyuhan503** [vueComponent/ant-design-vue#5557]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
谷歌浏览器@100.0.4896.127（正式版本） （64 位），  vue@3.2.16

### Reproduction link
[http://cms-stage.skyworthxr.com/#/login](http://cms-stage.skyworthxr.com/#/login)

### Steps to reproduce
使用分页的时候。报错Uncaught TypeError: Cannot read properties of null (reading 'match')，但并不影响分页功能

### What is expected?
解决报错

### What is actually happening?
登录方式：admin1  12345678   页面管理员列表，  翻页功能报错有时候有有时候没有，

### 图片：

        
![FNRJ1XD}NL7Z6B}TUHKRR11](https://user-images.githubusercontent.com/48934169/165663988-f6d16a8b-4d9c-4952-93cf-d7d7beabce9e.jpg)
![`SHU}E~$9XT}V9GP~3{K54L](https://user-images.githubusercontent.com/48934169/165664046-1dc2cd8e-d1d4-46e6-af61-85b067648709.jpg)

**Comment by whiter001** [comment]
网上查到的资料显示是用了页面上用了面包屑，分页组件里用的a标签没有href属性导致的；
