### ISSUE TITLE
求问 怎么在a-menu-item中加入路由 各种不舒服斯基

### ISSUE THREAD

**Issue by top-dante** [vueComponent/ant-design-vue#556]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
求问 怎么在a-menu-item中加入路由 各种不舒服斯基

### What does the proposed API look like?
在a-menu-item中加入路由 价格一个 to啊

**Comment by sendya** [comment]
参考

[![](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/znv4k5p2nm?fontsize=14&module=%2Fsrc%2FApp.vue)
