### ISSUE TITLE
The reset of the table filter needs to be clicked outside the dropdown area to take effect

### ISSUE THREAD

**Issue by 547414** [vueComponent/ant-design-vue#5560]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.2

### Environment
win10-20H2,  chrome 101.0.4951.41,  vue3

### Reproduction link
[https://www.antdv.com/components/table-cn#components-table-demo-reset-filter](https://www.antdv.com/components/table-cn#components-table-demo-reset-filter)

### Steps to reproduce
官网上就有。。。 https://www.antdv.com/components/table-cn#components-table-demo-reset-filter
录屏：https://cloud.crysu.com/tmp/4.mp4
Firefox、edge、chrome 下均有此问题

### What is expected?
点击重置按钮立即生效,而不是还要再点一次dropdown外面

### What is actually happening?
点击重置按钮不会立即生效,而是还要再点一次dropdown外面

**Comment by 547414** [comment]
真是暴躁 ****

**Comment by tangjinzhou** [comment]
新特性，参考 https://github.com/ant-design/ant-design/pull/31809

**Comment by dasoncheng** [comment]
遇到同样的问题，点击“重置”后没有立即触发change事件，需要点击“确认”或者关闭筛选框后才可触发
