### ISSUE TITLE
The tree structure can be selected. There is a child node with the same ID under the expanded two parent nodes. CheckNode returns the problem.

### ISSUE THREAD

**Issue by Jdan-coder** [vueComponent/ant-design-vue#5561]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
Windows10、100.0.4896.127（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-greider-ux45if?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1、渲染一个拥有两个父节点的树，并默认展开（两个父节点均拥有一个Key相同的子节点：item-1）。
2、选择第一个父节点中的 " item-1 "
3、查看所选节点信息

### What is expected?
所选节点信息中parentId为第二个父节点Key

### What is actually happening?
所选节点信息parentId为第一个父节点Key

**Comment by tangjinzhou** [comment]
不要用相同key
