### ISSUE TITLE
[a-range-picker] mode [year, year] Expected function error, please refer to [month, month] type function for details

### ISSUE THREAD

**Issue by tansentcn** [vueComponent/ant-design-vue#5562]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
Vue2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-4rlfvb?file=/src/App.vue)

### Steps to reproduce
rangePicker
set prop :mode=['year', 'year']

### What is expected?
年份区间无法正确选择

月份范围选择，正确选择和禁用
![image](https://user-images.githubusercontent.com/38307150/165910723-c6012726-7e9f-4a82-8de7-438b74ed09d0.png)

年份范围选择，错误选择和禁用
![image](https://user-images.githubusercontent.com/38307150/165910868-b8bc5352-4ef1-45e4-b094-891cca0b3328.png)

### What is actually happening?
应该正确选择起始、结束年份，并正确禁用范围之外的年份

**Comment by tangjinzhou** [comment]
https://1x.antdv.com/docs/vue/faq-cn#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-DatePicker/RangePicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD/%E6%9C%88%E4%BB%BD%EF%BC%9F
