### ISSUE TITLE
a-table component memory leak

### ISSUE THREAD

**Issue by lihuabest** [vueComponent/ant-design-vue#5569]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
"ant-design-vue": "^2.2.8","vue": "^3.2.31"

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
a-table组件绑定数据频繁的情况下，在一些运行内存不充足的机器上存在内存不能及时释放的问题。复现条件大概是每秒绑定200条全新数据给a-table组件，通过浏览器工具查看JVM实例不断上升至浏览器崩溃。

### What is expected?
更新的数据可以被内存回收

### What is actually happening?
内存无法回收

---
修正办法：通过浏览器工具的内存-堆快照发现是ant-design-vue/es/vc-table/src/TableRow.js的有一个rowRef的引用没有在组件销毁的时候调用，所以可以增加一行代码，希望官方看到了可以发个版本来解决，现在我们是采用替换文件来解决的。
unmounted: function unmounted() {
this.rowRef = null;
},

**Comment by tangjinzhou** [comment]
升级 3.x 吧
