### ISSUE TITLE
如何实现Ant Design of React日期组件的效果，更改头部输入框内容不会立刻关闭日期组件

### ISSUE THREAD

**Issue by bosens-China** [vueComponent/ant-design-vue#557]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
日期组件不会立刻关闭，有跳动效果

### What does the proposed API look like?
vue 2.6, chrome 72, vue 2.6

**Comment by bosens-China** [comment]
https://ant.design/components/date-picker-cn/

可否提供一个思路，我之前想用open来判断实现，不过发现判断逻辑有问题，我无法得知。两个日期同时选择

**Comment by tangjinzhou** [comment]
可以正常输入啊 😳

**Comment by bosens-China** [comment]
> 可以正常输入啊

老哥就是输入日期之后，点击上面的输入框改变会有一个动画效果，比如之前用鼠标点到了20日，之后用键盘更改上面的日期会有一个跳转动画。
但是如果不是更改输入框部分，只是用鼠标点击，那么会自动关闭，这个效果不知道如何实现
![gif](https://user-images.githubusercontent.com/39508895/53935633-11630780-40e2-11e9-8d50-7f9a5e900ead.gif)
