### ISSUE TITLE
Can I use Image component in v1.7.8(Vue 2.6)?

### ISSUE THREAD

**Issue by coturiv** [vueComponent/ant-design-vue#5573]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
macOS 11.4, Vue 2.6

### Reproduction link
[https://antdv.com/components/image](https://antdv.com/components/image)

### Steps to reproduce
I can see the Image component in 2.x or 3.x, but not in 1.x.

![image](https://user-images.githubusercontent.com/5830587/166968316-ab193b6c-f73b-4857-8085-fab90fea101f.png)

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/167050691-536cd06e-dd9e-4921-9d83-7589ff0a3a37.png)
文档有就有，没有就没有
