### ISSUE TITLE
The .my-menu style of <a-menu class="my-menu"> + <style scoped> is invalid

### ISSUE THREAD

**Issue by lin09** [vueComponent/ant-design-vue#5578]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
win10 / Chrome 96.0.4664.110（正式版本） （64 位） /  vue 3.2.33

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-almeida-tciug3?file=/src/App.vue)

### What is expected?
a-menu 能支持 <style scoped>

### What is actually happening?
``` <a-menu class="my-menu"> ``` + ```<style scoped>``` 的.my-menu样式无效

**Comment by tangjinzhou** [comment]
menu 根节点不是唯一节点，目前 vue 尚不支持，https://github.com/vuejs/core/issues/2669


另外：或许可以直接从 vnode上取 scopeId (`getCurrentInstance().vnode.scopeId`)， 担心未来会变化，等 Vue 官方明确API在支持
