### ISSUE TITLE
Modal.confirm of config —— prefixcls  is not valid for buttons

### ISSUE THREAD

**Issue by RainyNight9** [vueComponent/ant-design-vue#5579]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
```js
Modal.confirm({
title: '确认',
content: '是否退出登录',
okText: '退出',
prefixCls: 'main-app-modal',
getContainer: () => document.getElementById('modal-mounted-flag'),
onOk: () => {
},
onCancel () {}
})
```

### What does the proposed API look like?
Add prefixcls to the buttons

**Comment by tangjinzhou** [comment]
`Modal.confirm` `prefixCls` only effect modal dom, not for other component.
you should set `prefixCls` by `ConfigProvider.config({prefixCls: 'xxx'})` to set it.
