### ISSUE TITLE
form组件 onchange事件导致 数据置空

### ISSUE THREAD

**Issue by luotingv1** [vueComponent/ant-design-vue#558]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
vue-cli 2.0  vue": "^2.6.6",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9okx4kv6m4?tdsourcetag=s_pctim_aiomsg)

### Steps to reproduce
电话客服按钮多次点击

### What is expected?
电话客服按钮多次点击不影响 微信客服

### What is actually happening?
微信客服自动置空

---
业务场景:修改客服数据,默认数据父组件传入 然后 修改后 通过handleSubmit传回去 修改

**Comment by tangjinzhou** [comment]
你可以先给formItem设置唯一key来解决这个问题，我们下个版本会优化

**Comment by luotingv1** [comment]
> 你可以先给formItem设置唯一key来解决这个问题，我们下个版本会优化

群里 大佬说 v-if改v-show 也可以  是不是源码 重新渲染了 这个form组件

**Comment by tangjinzhou** [comment]
v-show可以解决问题，但不是根本问题，根本问题是组件依赖的数据收集注销机制问题，用key可以解决问题，对于动态表单的最佳实践也应该添加key
不过我们会尝试解决，使其不用加key
