### ISSUE TITLE
The current will be reassigned once in data(), taking the smallest of the current and page max values, should this trigger the onChange event? I think it should be triggered.

### ISSUE THREAD

**Issue by QiangGuZi** [vueComponent/ant-design-vue#5589]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
Vue: 3.2.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-ant-design-vue-3-2-3-forked-vw24nx?file=/src/demo.vue:438-464)

### Steps to reproduce
just click the link

### What is expected?
console will print 6 and then print 5
控制台打印 6，然后马上打印 5

### What is actually happening?
just print 6
只打印 6

---
场景（Table）：
0. 数据库共 31 条数据，table 每页 10 条，显示第 4 页
1. 远程获取数据（current: 4, pageSize: 10），返回 （total: 31, data: [/*一条数据*/]），一条数据
2. 页面上删除第 4 页第 1 条，删除后，数据库还剩 30 条
3. 删除后重新获取数据（current:4, pageSize: 10) ，远程返回 (total: 30, data: []），注意注意注意，是 0 条数据
4. pagination current prop 为 4，total 为 30，pageSize 为 10
5. 在 pagination 对 total 的 watch 中，会将 stateCurrent 更新为 3（逻辑：Math.min(4, 3)） （4 props，3 为当前 total、pageSize 能显示的最大页码）
6. 于是页面上，页码显示为 3，但显示的是第 4 页的空数据（因为 datasource 获取的是第 31-40 条的数据）
7. 异常。第 3 页实际是能获取到第 21-30 条数据的

期望：
1. total 的 watch 中，若 stateCurrent 改变，则触发 onUpdate:value 以及 onChange 事件
2. 用户在 onChange 中根据新的页码 3，重新请求远程数据（第 21-30 条），页面页码显示 3，同时显示对应的数据

其他：
标题内只写了 data() ，实际上还包括 watch 中的 total()

**Comment by QiangGuZi** [comment]
current 在 data() 和 total() 中会进行一次重新赋值，取 current 和页码最大值中的最小值，若取后者，这是否应该触发 onChange 事件？我认为应该触发。

**Comment by QiangGuZi** [comment]
data() 函数
<img width="910" alt="图片" src="https://user-images.githubusercontent.com/42662849/167669141-6cda81db-0eb9-4358-8a7e-8e2584255440.png">

watch total() 函数
<img width="908" alt="图片" src="https://user-images.githubusercontent.com/42662849/167669261-634d44f6-7c2d-4b9c-ab58-24f5bf3fdc47.png">

**Comment by QiangGuZi** [comment]
If you think so, let's me make a PR?

如果你觉得没问题，让我来提个 PR？

**Comment by tangjinzhou** [comment]
如果用了 v-model:current 或 current 应该自行保证有效性，不然受控的意义就不存在了，受控：完全由你控制
而 change 事件也只会在用户通过 ui 操作(翻页、切换等)时才会触发

你的场景用  :defaultCurrent="current" 应该可以解决，注意defaultCurrent只在第一次render 有效，如果远程获取，可以在获取数据后重新实例化 table

**Comment by QiangGuZi** [comment]
@tangjinzhou 收到，感谢！！

还有一个疑问请教一下，讲到受控的话，current是受控的，那么在 total 的watch 中改变 current 是否有待商榷？在 antd react 也提过这个问题，他们关于此的答复是 total 更新不会也不应该（受控）更改 current
