### ISSUE TITLE
In treeSelect select event callback (value, node, extra) extra parameter is undefined

### ISSUE THREAD

**Issue by ylw1997** [vueComponent/ant-design-vue#5591]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
windows 11 ,chrome 101,vue3.2

### Reproduction link
[https://antdv.com/components/tree-select-cn#API](https://antdv.com/components/tree-select-cn#API)

### Steps to reproduce
treeSelect select 打印select结果

### What is expected?
希望extra参数能够出现

### What is actually happening?
treeSelect的Select事件extra参数为undefined

**Comment by ylw1997** [comment]
![image](https://user-images.githubusercontent.com/19940543/167755989-7152426f-6a39-4dc4-9763-e505e3d63189.png)
![image](https://user-images.githubusercontent.com/19940543/167756019-0080959a-7736-4269-8244-f801ec3f732f.png)

**Comment by tangjinzhou** [comment]
希望这个参数是什么呢

**Comment by ylw1997** [comment]
之前版本的extra里面有checkedNodes和halfCheckedKeys

**Comment by ylw1997** [comment]
> 希望这个参数是涂抹

之前版本的额外内容有checkedNodes和halfCheckedKeys
