### ISSUE TITLE
How to achieve the height of the collapse panel to adapt to the parent component?

### ISSUE THREAD

**Issue by andyesfly** [vueComponent/ant-design-vue#5594]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
貌似目前只能根据内容自适应高度，我想实现类似VSCODE的资源视图折叠面板的效果，能自适应父组件高度，且可以手动改变高度

### What does the proposed API look like?
resizable

**Comment by tangjinzhou** [comment]
自己写样式
