### ISSUE TITLE
Carousel will trigger onMounted multiple times if more than one components

### ISSUE THREAD

**Issue by ldsenow** [vueComponent/ant-design-vue#5597]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
windows 10, vue 3.x

### Reproduction link
[https://github.com/ldsenow/ant-carousel-issue](https://github.com/ldsenow/ant-carousel-issue)

### Steps to reproduce
Launch the vue project from the repo, and check the console logs.

### What is expected?
Should mount once per component

### What is actually happening?
Mount multiple times

---
I found this issue due to i have some highchart components within the carousel. The display is pefect, however, when i navigate to another page. An error is thrown which is about highchart tries to destroy something and the instance is already destroyed. I finally find out it is causing by the carousel control somehow trigger the OnBeforeUnmount event multiple times. I guess the root cause is the mount event is triggered more than once in the early beginning. I am not quite sure how to avoid or make a work around it.

**Comment by tangjinzhou** [comment]
comonent use cloneVNode for animation.
you can add some condition to avoid error

**Comment by ldsenow** [comment]
However, i have no control about the destroy function from highcharts lib. Good to know the insight. Thanks
