### ISSUE TITLE
drawer can't close with mask or close icon

### ISSUE THREAD

**Issue by maxiloEmmmm** [vueComponent/ant-design-vue#560]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
ant-design-vue@1.3.5 vue@2.6.7 chrome@69.0.3497.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1z51r10344?fontsize=14)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/16779121/53937942-9c93cb80-40e9-11e9-8c2e-0887b3866cc0.png)
Tracked here, find `this.close` is `true` and return, nothing happened.

### What is expected?
click no affect

### What is actually happening?
click to close drawer

**Comment by tangjinzhou** [comment]
Provide a valid Reproduction link,
And You pass `open= true`. If you want to close, please assign it to false in the close callback.
![image](https://user-images.githubusercontent.com/6937879/53938317-cd283500-40ea-11e9-8d4a-6edabbe45c16.png)

**Comment by maxiloEmmmm** [comment]
@tangjinzhou 
I understand it wrong,i thought callback after closed, sorry.
