### ISSUE TITLE
使用vite和tsx，styles cannot be loaded on demand

### ISSUE THREAD

**Issue by Topthinking** [vueComponent/ant-design-vue#5602]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
最新版本

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-kls3sn?file=src%2Fmain.tsx](https://stackblitz.com/edit/vitejs-vite-kls3sn?file=src%2Fmain.tsx)

### Steps to reproduce
直接根据上面地址查看即可

### What is expected?
希望样式可以按需加载，类似react的ant-design

### What is actually happening?
现在样式没法按需加载了

**Comment by tangjinzhou** [comment]
unplugin-vue-components 只能在 template 文件中按需加载样式吧，你可以去那边问问

**Comment by Topthinking** [comment]
> unplugin-vue-components 只能在 template 文件中按需加载样式吧，你可以去那边问问

没用，那么不支持，vant好像可以的，他们提供了个resolve的，你们看看要提供么

还有，我们这边整体都使用tsx开发vue项目，一些ts的提示貌似不太完善，比如Row组件上的style没有提示，类似React吧

![image](https://user-images.githubusercontent.com/13382821/168561317-9907dd91-d9a6-4168-825f-250fa19e14d7.png)

**Comment by liulei92** [comment]
遇到同样的问题，环境也是一致的，目前只能选择在tsx组件中 单独引入style了

**Comment by huiliangShen** [comment]
tsx中 `vite-plugin-imp` 可以解决这个问题
