### ISSUE TITLE
logo div gone missing in layout components in demo

### ISSUE THREAD

**Issue by Vickko** [vueComponent/ant-design-vue#5604]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
vue@3.2.33

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7i6vqz?file=/src/main.js)

### Steps to reproduce
Just copy one of the demos with a logo div in layout components, and run it in a minimum vue project

### What is expected?
The box of logo div should display correctly, like it is shown in antdv.com

### What is actually happening?
The logo div disappear in real render

---
It's just a little mistake in CSS, logo's css is "#components-layout-demo-top-side-2 .logo", but \<a-layout>'s id gone missing. By the way, should I just fix and PR it?

**Comment by tangjinzhou** [comment]
I didn't find a good way to solve this example id problem. Of course, if you have a good way, you can PR. 
Abd I don't think it's necessary.
