### ISSUE TITLE
When the Select drop-down menu is expanded, the direction of the small arrow should rotate down, from down to up

### ISSUE THREAD

**Issue by ytyqn** [vueComponent/ant-design-vue#5606]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
vue3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
点击表单 Select 下拉菜单展开后，箭头没有转变方向。

### What is expected?
箭头改为向上

### What is actually happening?
就是状态变化这里没带上小箭头

**Comment by tndong799** [comment]
@tangjinzhou Hi, I want to disable animation of suffix icon when dropdown open, can you help me?
