### ISSUE TITLE
v-for and slot="filterDropdown" will show two same dom

### ISSUE THREAD

**Issue by Autumnwater** [vueComponent/ant-design-vue#5609]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-v5bjhk?file=/src/App.vue)

### Steps to reproduce
点击下拉筛选，点击第一个，在开发者工具可以发现出现2个 相同的input。这里可直接搜索请输入111
同样情况，其实在vue的开发者工具内，我发现是因为fixed引起的。
left的fixed会组成第一个 <HeadTable><HeadBody> 常规的组成第二个一摸一样的<HeadTable><HeadBody>
而点击的时候，下拉的filterDropdown也存在于2个相同的<HeadTable>，同样的组件 下拉了。

### What is expected?
只出现一个filterDropdown的下拉

### What is actually happening?
2个相同的filterDropdown 会下啦。

![fixed   solt](https://user-images.githubusercontent.com/8455381/168572327-8c1ca6b7-e95c-4a0a-8ea4-57516ae74ecd.jpg)

![请输入](https://user-images.githubusercontent.com/8455381/168572213-e4e3cd28-d8d8-4ed1-8afb-5292c07f9d92.jpg)

**Comment by tangjinzhou** [comment]
update to antdv 3
