### ISSUE TITLE
表格内容存在连续英文单词时，表格样式会变形

### ISSUE THREAD

**Issue by linziguan** [vueComponent/ant-design-vue#561]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
chrome 69.0,Vue 2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4xxxqvk0x0?fontsize=14)

### Steps to reproduce
在表格中，引用带长串英文的数据时，表格页面变形

### What is expected?
表格可正常显示，内容自动换行

### What is actually happening?
非长串英文的列被挤压

---
小屏幕下更明显。

**Comment by linziguan** [comment]
建议在.ant-table-tbody > tr > td样式中，增加
`    word-wrap: break-word;
    table-layout: fixed;
    word-break: break-all;
`

**Comment by sendya** [comment]
框架组件一般不做这种事情，应当由使用者去决定是否处理这种情况。
而且这种情况处理方案很多，比如使用 `Tooltip` 组件

实际效果如下：

![20190308193727](https://user-images.githubusercontent.com/5404542/54026726-d643ff80-41d9-11e9-8ce5-8bd132878997.png)

**Comment by shiyingyan** [comment]
你说的也对 ，组件不应该封装。 但是根据你们提供的api，无法设置样式呢 ？  请问该如何设置

**Comment by shiyingyan** [comment]
> 框架组件一般不做这种事情，应当由使用者去决定是否处理这种情况。
> 而且这种情况处理方案很多，比如使用 `Tooltip` 组件
> 
> 实际效果如下：
> 
> ![20190308193727](https://user-images.githubusercontent.com/5404542/54026726-d643ff80-41d9-11e9-8ce5-8bd132878997.png)
你说的也对 ，组件不应该封装。 但是根据你们提供的api，无法设置样式呢 ？ 请问该如何设置
