### ISSUE TITLE
FunctionalComponent  failed to update Input value

### ISSUE THREAD

**Issue by Lisheri** [vueComponent/ant-design-vue#5617]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
os version: macos12.2; browser version: chrome 101.0.4951.64 (arm64)； Vue version: 3.2.33

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-margulis-fzso7w?file=/src/components/Input.jsx)

### Steps to reproduce
1. import { Input } from 'ant-design-vue'
2. use the Input by FunctionalComponent, binding values ​​by "v-model"
3. The value cannot be updated, and the view cannot be updated, but onChange shows that the value has changed, but the next time it is restored
4. But component defined with "defineComponent" works fine

### What is expected?
Works fine under FunctionalComponent

### What is actually happening?
Use the Input by FunctionalComponent, binding values ​​by "v-model"
The value cannot be updated, and the view cannot be updated, but onChange shows that the value has changed, but the next time it is restored

**Comment by Lisheri** [comment]
这个是我使用函数组件的姿势问题吗

**Comment by tangjinzhou** [comment]
函数式组件里面不能用 ref 啊，每次都会执行 ref('') 所以被清空了 
setup 只会执行一次

**Comment by Lisheri** [comment]
哦哦, 感谢哥
