### ISSUE TITLE
table filter improvements (show the value of the select filter next to the list in the header)

### ISSUE THREAD

**Issue by duke-git** [vueComponent/ant-design-vue#5620]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在table列的filter里面选择后，能不能把选择的值显示到表头的列表旁边

### What does the proposed API look like?
无

        

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/5037603/169242922-2387062b-d4e7-4a2e-95d7-75dff585d7b8.png">

**Comment by tangjinzhou** [comment]
使用 headerCell 插槽自定义
