### ISSUE TITLE
When the a-range-picker component prohibits the selection of the time after the current time, the OK button becomes disabled when the hour, second, and minute selected by the non-current date are greater than the hour, second, and minute of the current date (time range verification failed)

### ISSUE THREAD

**Issue by yaowangmx** [vueComponent/ant-design-vue#5621]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue: 2.6.11   moment: 2.29.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-0l6qkk?file=/src/App.vue)

### Steps to reproduce
选择一个非当日日期与一个当日日期然后选择 select date，第一个时间选择大于当前时秒分的时间就可以看到OK按钮变灰

### What is expected?
非当日日期选择的时秒分大于当日日期时秒分时，OK按钮为可点击状态

### What is actually happening?
非当日日期选择的时秒分大于当日日期时秒分时，OK按钮会变灰（日期范围检验失败）

**Comment by yaowangmx** [comment]
a-range-picker组件禁止选择当前时间之后的时间时，非当日日期选择的时秒分大于当日日期时秒分时确定按钮变成禁用（时间范围校验失败）

**Comment by tangjinzhou** [comment]
文档有点问题， 不是 dates  是 date

可以考虑升级  v3 了，全新交互，新增各种特性

**Comment by yaowangmx** [comment]
> 

这个参数不是一个数组的吗？这种禁止选择之后的时间的要怎么配置呢？
