### ISSUE TITLE
Carousel make Error on route change

### ISSUE THREAD

**Issue by Djaangoo** [vueComponent/ant-design-vue#5623]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-cloud-xgmbku?file=/src/App.vue)

### Steps to reproduce
Go to link

Go to /carousel and go to /home
you should see error

which makes impossible to change route by vue-router

### What is expected?
Carousel will works with vue-router

### What is actually happening?
When We have routing on the page - changing page where is a carousel - makes an error

**Comment by Djaangoo** [comment]
#5399

**Comment by tangjinzhou** [comment]
you can update vue-i18n to 9.2.0+

**Comment by Djaangoo** [comment]
Cool, thanks!
