### ISSUE TITLE
The tree component does not support scrollTo to a node, currently only the react version supports it

### ISSUE THREAD

**Issue by yeyuliang2015** [vueComponent/ant-design-vue#5626]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
树组件不支持scrollTo到某个节点，目前只有react版本的才支持

### What does the proposed API look like?
树组件不支持scrollTo到某个节点，目前只有react版本的才支持

**Comment by yeyuliang2015** [comment]
树组件不支持scrollTo到某个节点，目前只有react版本的才支持

**Comment by yeyuliang2015** [comment]
调用scrollTo方法后，还是无法滚动到指定的节点，请问具体改怎么调用呢？我调用的方式如下：
treeRef.value.scrollTo(node.key)

**Comment by yeyuliang2015** [comment]
成功了，是传的参数不对，好像不能展开收起来的节点。

**Comment by rookiiiie** [comment]
i meet the problem too! the tree dom doesn't provide the Tree Methods "scrollTo" in vue version😫
