### ISSUE TITLE
Tooltip doesn't read getPopupContainer from the configProvider

### ISSUE THREAD

**Issue by mrakjos** [vueComponent/ant-design-vue#5636]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
MacOS Safari, Chrome, Win Edge, Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdv-tootlip-configprovider-o9wnog?file=/src/App.vue)

### Steps to reproduce
- Hover with mouse sorted columns in the table for displaying a tooltip
- or hover the text "Tooltip will show when mouse enter."

### What is expected?
- All tooltips show text with red text

### What is actually happening?
- Tootip in the table doesn't show a text with red color
- Simple tooltip does not show text with red color for the first text "Tooltip will show when mouse enter."
- Only tooltip for the second text "Tooltip will show when mouse enter." show text in red (it reads getPopupContainer directly)

---
Custom filter dropdown works correctly in the table - it has a red text in the input

**Comment by peritot** [comment]
当设置全局 getPopupContainer 到父节点后，某些组件的内置 Tooltip 都会渲染到其父节点（比如表格排序表头的 Tooltip），会出现样式问题，请问如何处理？
<img width="745" alt="image" src="https://user-images.githubusercontent.com/8265374/207584061-1c072d00-bf23-4f1f-9e06-3fa7023a2b33.png">

getPopupContainer 函数参数对外提供判断节点类型的方法，是开发者能自行处理 Tooltip 类型的渲染节点？

**Comment by peritot** [comment]
@tangjinzhou 望回复，谢谢！
