### ISSUE TITLE
warning.js:6 Warning: [antdv: Breadcrumb] Only accepts Breadcrumb.Item and Breadcrumb.Separator as it's children

### ISSUE THREAD

**Issue by shiwanjun1995** [vueComponent/ant-design-vue#5638]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
vue 3.2.25

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-m37y85?file=/src/App.vue)

### Steps to reproduce
has warning

### What is expected?
no warning

### What is actually happening?
has warning

---
what can i do?

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/169973254-e798b83b-8a0b-453e-9ade-a55768b18579.png)

**Comment by shiwanjun1995** [comment]
The same codes as ElementUI is right. 
I am confused,is this a bug of AntdV?
[ElementUI code](https://codesandbox.io/s/element-plus-spa-forked-ydkdj3?file=/src/App.vue)
