### ISSUE TITLE
嵌套组件导致样式丢失

### ISSUE THREAD

**Issue by luoxiaoji** [vueComponent/ant-design-vue#564]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### Reproduction link
[https://github.com/luoxiaoji/testDemo](https://github.com/luoxiaoji/testDemo)

### Steps to reproduce
比如这样：
```
<a-dropdown :trigger="['click']">
<a class="ant-dropdown-link"
href="#">
Click me
<a-icon type="down" />
</a>
<a-menu slot="overlay">
<a-dropdown :trigger="['click']">
<a class="ant-dropdown-link"
href="#">
Click me
<a-icon type="down" />
</a>
<div slot="overlay">
<a-menu-item key="0">
<a href="http://www.alipay.com/">1st menu item</a>
</a-menu-item>
<a-menu-item key="1">
<a href="http://www.taobao.com/">2nd menu item</a>
</a-menu-item>
<a-menu-divider />
<a-menu-item key="3">3rd menu item</a-menu-item>
</div>
</a-dropdown>
</a-dropdown>
```

### What is expected?
下拉里的下拉应该能正常点击 并且样式正常

### What is actually happening?
背景什么的 样式丢失，并且下拉无法点击。

**Comment by luoxiaoji** [comment]
备注我看到另外一个一模一样的BUG，但是 我想知道的为啥会影响，我用 slot="overlay" 理论至少背景样式不会影响，里面的不用菜单不可以吗？ 另外还是说必须要用菜单来定义 slot="overlay"， 不好意思，因为我是从其他UI转过来的，觉得这种方式有点不科学。如有冲撞望理解。

**Comment by tangjinzhou** [comment]
menu为何嵌套dropdown，就算嵌套也应该是menuitem嵌套dropdown吧，
另外如果使用的开发版本，menu的子元素如果不合法，控制台应该给出了相应的提示。

**Comment by luoxiaoji** [comment]
> menu为何嵌套dropdown，就算嵌套也应该是menuitem嵌套dropdown吧，
> 另外如果使用的开发版本，menu的子元素如果不合法，控制台应该给出了相应的提示。

是的，menu 嵌套除菜单外 感觉都不对劲，所以按照 我之前的用的UI 思路是  slot="overlay"  用div 定义也可以，里面的内容可以随意DIY嵌套任何东西。但是事实，会报错。。

所以目前只能用menuitem 来嵌套东西，然后在把 menuitem 的CSS 在挨个改。。

**Comment by luoxiaoji** [comment]
> menu为何嵌套dropdown，就算嵌套也应该是menuitem嵌套dropdown吧，
> 另外如果使用的开发版本，menu的子元素如果不合法，控制台应该给出了相应的提示。

多谢回复，决定  用 Popconfirm 来解决好了。 每个组件都应该对针对性的用处
