### ISSUE TITLE
the first td element of "ant-table-expanded-row" will be affected by transformCellText

### ISSUE THREAD

**Issue by arika163** [vueComponent/ant-design-vue#5641]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.6.5

### Environment
latest chrome, windows 10,vue 2.x

### Steps to reproduce
```javascript
transformCellText({ text }) {
  return text === "" || text === null || text === undefined ? "-" : text
}
```
set this function to config provider and write a simple expand table in it

[reproduce link](https://codesandbox.io/s/unruffled-haze-25czli?file=/src/App.vue)

**Comment by tangjinzhou** [comment]
you can get more info from transformCellText arguments. like record、column.
