### ISSUE TITLE
[bug] When set select of dropdown in open state which is in popover component, that is not work.

### ISSUE THREAD

**Issue by dongggcom** [vueComponent/ant-design-vue#5643]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
vue@^3.2.33, ant-design-vue@^3.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-yonath-0bp1g1?file=/src/App.vue)

### Steps to reproduce
popover wrap a select component which set open state.
用 popover 下包裹一个 select 并设置 open

### What is expected?
The open state of dropdown is control.
open 可用

### What is actually happening?
in popover component
在 popover 组件下使用

**Comment by tangjinzhou** [comment]
set dropdown-match-select-width = false

**Comment by dongggcom** [comment]
> dropdown-match-select-width = false

有用
