### ISSUE TITLE
the filterTreeNode is not effective in <a-tree> component

### ISSUE THREAD

**Issue by dylansss** [vueComponent/ant-design-vue#5646]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.2

### Environment
macos vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/long-forest-ecd1fl?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
传入filterTreeNode函数发现不生效

### What is expected?
树节点根据filterTreeNode的结果正确展示隐藏

### What is actually happening?
树节点没有隐藏

---
在源码components/vc-tree中唯一一次使用filterTreeNode是给树节点添加了一个‘filter-node’类名，不知道是不是我用法有误，现在只能先用样式实现隐藏

**Comment by tangjinzhou** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/6937879/170279579-f7982993-8c8b-42d2-bbb3-0716e4fba8a1.png">
仔细看文档，说的是高亮

**Comment by coffee377** [comment]
> <img alt="image" width="550" src="https://user-images.githubusercontent.com/6937879/170279579-f7982993-8c8b-42d2-bbb3-0716e4fba8a1.png">
> 
> 仔细看文档，说的是高亮

实际使用时，结果属性节点也并未高亮
![image](https://user-images.githubusercontent.com/13707072/181209497-bed37de7-6f7d-41e9-a6da-6d8e03e7fe87.png)
![image](https://user-images.githubusercontent.com/13707072/181210056-0f9d1f65-fe34-475a-9ebb-bcd394078a11.png)
