### ISSUE TITLE
DatePicker[picker="quarter"] use attribute value-format='YYYY-[Q]Q' has a bug

### ISSUE THREAD

**Issue by wangmin0314** [vueComponent/ant-design-vue#5647]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
os version：macOS Big Sur 11.6、browser version：Chrome 101.0.4951.64（正式版本） (x86_64)、Vue version：3.2.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-mcnulty-ugzyvg?file=/src/App.vue)

### Steps to reproduce
<DatePicker
style="width: 50%"
v-model:value="useDate"
picker="quarter"
value-format="YYYY-[Q]Q"
/>

### What is expected?
You can make the right choice

### What is actually happening?
Whatever you choose, the result is YYYY-Q1

**Comment by tangjinzhou** [comment]
ref https://github.com/iamkun/dayjs/issues/845
