### ISSUE TITLE
table的分页控制, 初始化过后使用 pagination 对象的 current定位到第几页，会导致分页不可点击

### ISSUE THREAD

**Issue by wangbinbinge** [vueComponent/ant-design-vue#565]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
mac 10.14.2,  chrome 72.0.3626.119  vue 2.5.17 或 2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1y3xlkqzpj)

### Steps to reproduce
打开 https://codesandbox.io/s/1y3xlkqzpj 链接 可以看到效果

### What is expected?
希望 在初始化过后  使用table 的 pagination 的 current 属性 再次定位到第几页以后 分页条还可以点击

### What is actually happening?
点击分页条上一页  下一页 第几页的按钮 没有反应

**Comment by sendya** [comment]
你好，请参考这个栗子：

[![](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vqkoqx9vj3?fontsize=14&module=%2Fsrc%2FApp.vue)

> 原因：因为你将 `pagination` 进行了绑定，而 current 不是受控属性，此时需要你自行维护 `current` 才能完成你想要的效果。
> 此时可以利用 `a-table` 组件的 `change` 事件 来获取到分页器的改变。从而改变你的 `paginationObject` 对象

**Comment by useryechen** [comment]
> 你好，请参考这个栗子：
> 
> [![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/vqkoqx9vj3?fontsize=14&module=%2Fsrc%2FApp.vue)
> 
> > 原因：因为你将 `pagination` 进行了绑定，而 current 不是受控属性，此时需要你自行维护 `current` 才能完成你想要的效果。
> > 此时可以利用 `a-table` 组件的 `change` 事件 来获取到分页器的改变。从而改变你的 `paginationObject` 对象

您好，我现在遇到个问题，就是我将`pagination`进行绑定后，在`paginationObject`中也写了`onChange`函数，但是这个`onChange`函数没有执行，这样我的快速跳转就无法触发
