### ISSUE TITLE
3.x version, how to globally modify the default value of the component

### ISSUE THREAD

**Issue by dgf957492430** [vueComponent/ant-design-vue#5656]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
某些组件的很多prop的默认值和我想要的不一样，这样每次调用ant组件时，都需要把这些属性传一下，如何能全局修改呢？

### What does the proposed API look like?
在2.x中，可以这样：
```
import { Tooltip } from 'ant-design-vue'
Tooltip.props.arrowPointAtCenter.default = true
Tooltip.props.destroyTooltipOnHide.default = true
```
但在3.x中，不行了，有没有什么办法能全局修改呢？如果不能的话，后续能否考虑支持一下？

**Comment by tangjinzhou** [comment]
不建议直接更改组件原型，你可以自己封装一层
