### ISSUE TITLE
the scrollToField not work

### ISSUE THREAD

**Issue by hoozi** [vueComponent/ant-design-vue#5659]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
3.2.5

### Reproduction link
[https://antdv.com/components/form](https://antdv.com/components/form)

### Steps to reproduce
/

### What is expected?
/

### What is actually happening?
当formItem的name是一个array的时候，比如name="['a','b']"，那么用scrollToField就不起作用，2.x的时候这个是好的，看了一下源码，发现name不能是个数组,既然NamePath可以是array类型，为什么在这里用array类型就不行？

**Comment by tangjinzhou** [comment]
array 指的是嵌套字段，不是多个字段的意思

**Comment by hoozi** [comment]
> 

但是嵌套字段目前不起作用
