### ISSUE TITLE
Global ConfigProvider.config style configuration does not take effect

### ISSUE THREAD

**Issue by Zhliyun** [vueComponent/ant-design-vue#5661]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
ant-design-vue 3.2.5   vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-worker-4737x8?file=/src/App.vue)

### Steps to reproduce
const colorState = reactive({
primaryColor: "red",
errorColor: "red",
warningColor: "red",
successColor: "red",
infoColor: "red",
});

ConfigProvider.config({
theme: colorState,
});

配置全局样式不生效

### What is expected?
配置样式主题色生效

### What is actually happening?
配置样式主题色不生效

**Comment by tangjinzhou** [comment]
使用  antd.variable.css
