### ISSUE TITLE
The example on the guide page is old, needed to update!

### ISSUE THREAD

**Issue by lujiaxing** [vueComponent/ant-design-vue#5662]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
None

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-franklin-1w72v)

### Steps to reproduce
Open "https://www.antdv.com/docs/vue/getting-started" (the document page of ant-design-vue)
Click "Edit on CodeSandbox" button
On the new opened project page, choose "package.json"
the version of "dependencies -> ant-design-vue" is still "2.2.8", but the newest version should be "3.2.5"

### What is expected?
Recreate the example project with newest version Ant-Design-Vue 3.2.x or replace it with "https://codesandbox.io/s/jvnyy4" (3.2.3)

### What is actually happening?
the version that the example project is using an obsolete and unsupported version of And-Design-Vue

**Comment by tangjinzhou** [comment]
try again
