### ISSUE TITLE
How to support converting more less variables to CSS variables？

### ISSUE THREAD

**Issue by core-admin** [vueComponent/ant-design-vue#5663]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
How to support the conversion of more less variables into CSS variables, such as @border-radius-base in less variables, which I can use or modify through VAR (- border-radius-base).

怎么支持 更多的less变量转成css变量，比如less变量中的@border-radius-base，我可以通过var(—border-radius-base) 的方式使用或者修改它。

### What does the proposed API look like?
This is a question

**Comment by 4KDA** [comment]
News?
