### ISSUE TITLE
Notification component has no styles when using on-demand import

### ISSUE THREAD

**Issue by Oleksii14** [vueComponent/ant-design-vue#5665]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
Described in the package.json

### Reproduction link
[https://github.com/Oleksii14/ant-design-notification-issue](https://github.com/Oleksii14/ant-design-notification-issue)

### Steps to reproduce
1. npm i
2. npm run dev
3. open app, see the notification component without css

### What is expected?
The notification component should load the styles on demand

### What is actually happening?
While using on-demand import with `unplugin-vue-components`, the notification component has no styles loaded.

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/36737084/171908818-0447d4c4-9cd9-4485-9a90-bef60b20aa46.png">

**Comment by tangjinzhou** [comment]
unplugin-vue-components 只会按需加载 template 中的组件样式
 api类型的组件不会，你可以手动引入该类型组件的样式  或者给 unplugin-vue-components 提issue

**Comment by nvhoang55** [comment]
I don't know if you still need the solution for this or not, but here's how I fixed it:

1. Manually import the notification style file like this:
```js
import 'ant-design-vue/lib/notification/style/index.css'
or
import 'ant-design-vue/lib/notification/style' // import index.less
```

2. Make sure you import all Antd styles (```ant-design-vue/dist/antd.css```) globally somewhere in your app. Here's how I do it in Nuxt 3:
```js
export default defineNuxtConfig({
  css: [
  'ant-design-vue/dist/antd.css',
  ],
})
```

**Comment by haiting** [comment]
> I don't know if you still need the solution for this or not, but here's how I fixed it:
> 
> 1. Manually import the notification style file like this:
> 
> ```js
> import 'ant-design-vue/lib/notification/style/index.css'
> or
> import 'ant-design-vue/lib/notification/style' // import index.less
> ```
> 
> 2. Make sure you import all Antd styles (`ant-design-vue/dist/antd.css`) globally somewhere in your app. Here's how I do it in Nuxt 3:
> 
> ```js
> export default defineNuxtConfig({
>   css: [
>   'ant-design-vue/dist/antd.css',
>   ],
> })
> ```

Is one of the two options okay？
