### ISSUE TITLE
访问  https://2x.antdv.com/components/overview   直接白屏了啊  

### ISSUE THREAD

**Issue by yehoan** [vueComponent/ant-design-vue#5668]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.5.6

### Environment
vue 2.X

### Reproduction link
[https://2x.antdv.com/components/overview](https://2x.antdv.com/components/overview)

### Steps to reproduce
访问 https://2x.antdv.com/components/overview   网站白屏

### What is expected?
https://2x.antdv.com/components/overview 能正常访问官网

### What is actually happening?
https://2x.antdv.com/components/overview  直接白屏

**Comment by yehoan** [comment]
想查看一下2.X的文档 直接白屏....

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/172049586-97c641b0-90d0-4c8e-a89d-9fcd1203004b.png)

**Comment by yehoan** [comment]
到处报错...  麻烦看下啊

**Comment by tangjinzhou** [comment]
清缓存刷新试试吧 ，我这没问题

**Comment by yehoan** [comment]
和缓存没关系 关了

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/173756033-7db121d8-17f4-4369-b1d1-a441b3dcf907.png)
这个是无痕浏览器打开的效果   不可能是浏览器的问题  而且我用的是谷歌

**Comment by yehoan** [comment]
代码是不是有什么BUG
