### ISSUE TITLE
cascader 组件options数据中的value 为数字时会报错

### ISSUE THREAD

**Issue by castawayy** [vueComponent/ant-design-vue#567]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前的数据value都是为数字 但是此组件目前只支持字符串 在组件使用时会有warn 提示

### What does the proposed API look like?
value数据类型应该是any

**Comment by Binote** [comment]
实际上第三方组件库都会有这种项目中不太适用的问题，建议自己二次封装。。。作为一个爬iview坑的人的建议

**Comment by mcmf** [comment]
还有`defaultValue` 只能['2','3'] 这种格式 ，实际上 [2,3]这种情况也是比较多了 没必要转为string

**Comment by tangjinzhou** [comment]
ref #595
