### ISSUE TITLE
Some props of time-picker are invalid

### ISSUE THREAD

**Issue by qilimazhualuo** [vueComponent/ant-design-vue#5671]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
node16

### Reproduction link
[https://www.antdv.com/components/time-picker-cn#components-time-picker-demo-basic](https://www.antdv.com/components/time-picker-cn#components-time-picker-demo-basic)

### Steps to reproduce
```vue
<a-time-range-picker
:disabledMinutes="() => [29, 59]"
:hideDisabledOptions="true"
:minuteStep="15"
/>
```
这三个props都是无效的，设置了但是没有效果
a-time-picker 是可以的

### What is expected?
可以使用步长参数 can use step props

### What is actually happening?
步长参数不能使用 steps cannot use

**Comment by tangjinzhou** [comment]
使用 
```html
:disabled-time="
      () => ({
        disabledMinutes: () => [30, 50],
      })
    "
```

直接使用 disabledMinutes 会被废弃，

minuteStep 会在下个版本修复

**Comment by qilimazhualuo** [comment]
大佬 hideDisabledOptions 这个属性呢
```html
<a-time-range-picker hideDisabledOptions="true" />
```

```html
<a-time-range-picker 
    :disabled-time="() => ({
          disabledMinutes: () => [29, 59],
          hideDisabledOptions: true
     })"
 />
```
这俩种好像都不行
感谢您回复我
