### ISSUE TITLE
Backtop doesn't work on mobile

### ISSUE THREAD

**Issue by hdtopku** [vueComponent/ant-design-vue#5673]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
华为手机自带浏览器，鸿蒙系统2.0

### Reproduction link
[https://www.antdv.com/components/back-top-cn](https://www.antdv.com/components/back-top-cn)

### Steps to reproduce
移动端直接打开：https://www.antdv.com/components/back-top-cn
然后往下翻，backtop不显示

### What is expected?
移动端也能显示出来

### What is actually happening?
移动端未能显示出来

![WechatIMG732](https://user-images.githubusercontent.com/14859466/172183830-8c5632dc-e61d-46e3-95c5-c678a992bcbf.jpeg)

![WechatIMG730](https://user-images.githubusercontent.com/14859466/172183843-4a1cf534-71f3-4e9a-b0af-29301d85e809.jpeg)

**Comment by tangjinzhou** [comment]
手中设备未复现问题，如果方便，你可以尝试定位问题并提交 PR， 谢谢

**Comment by hdtopku** [comment]
确实，我用iphone6s是出现了，华为mate30pro，鸿蒙2.0系统，不管是微信还是自带浏览器中打开都出现不了。



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 7, 2022 10:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vueComponent/ant-design-vue] Backtop doesn't work on mobile (Issue #5673)




 
手中设备未复现问题，如果方便，你可以尝试定位问题并提交 PR， 谢谢
