### ISSUE TITLE
ctrl and scroll wheel to zoom in and out of the page fail in the virtual scrolling tree

### ISSUE THREAD

**Issue by paoyideyun** [vueComponent/ant-design-vue#5687]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
vue3.2.31 ，chrome 99，

### Reproduction link
[https://www.antdv.com/components/tree-cn#components-tree-demo-virtual-scroll](https://www.antdv.com/components/tree-cn#components-tree-demo-virtual-scroll)

### Steps to reproduce
ctrl 和滚轮在虚拟滚动的tree中进行操作

### What is expected?
期望能够正常进行放大缩小

### What is actually happening?
实际啥也没发生

![GIF](https://user-images.githubusercontent.com/10071303/172976213-5646f238-5a87-4522-8cf6-6fc509b31473.gif)

**Comment by tangjinzhou** [comment]
没看出来啥

**Comment by paoyideyun** [comment]
按住ctrl后在滚动滚轮可以对网页进行缩放，但是在虚拟滚动的tree的区域，无法进行缩放
