### ISSUE TITLE
The website language is switched to Chinese, causing the attributes in the document to also become Chinese

### ISSUE THREAD

**Issue by zbkha** [vueComponent/ant-design-vue#5698]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
Windows 10 Chrome 102.0.5005.63 Vue 3.2.36

### Reproduction link
[https://www.antdv.com/components/table-cn#API](https://www.antdv.com/components/table-cn#API)

### Steps to reproduce
表格组件中API Table locale,  默认值是
filterConfirm: 'Ok'
filterReset: 'Reset'
emptyText: 'No Data'，
网站语言切换成中文后，属性值也被翻译了，变成了
filterConfirm: 确定
filterReset: 重置
emptyText: 暂无数据
同样问题也出现在列表组件中API List locale

### What is expected?
个人认为属性值不应该被翻译，因为它是不随网站语言变化的。

### What is actually happening?
由于只涉及到中文，就不用英文创建issue了。

**Comment by tangjinzhou** [comment]
是这样要变的
