### ISSUE TITLE
The andt component in the custom component cannot be parsed using the h function

### ISSUE THREAD

**Issue by inkn** [vueComponent/ant-design-vue#5699]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
win10, Chrom 最新，    "ant-design-vue": "^3.2.6",     "vue": "^3.2.37"

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-46elve?file=src/App.vue](https://stackblitz.com/edit/vitejs-vite-46elve?file=src/App.vue)

### Steps to reproduce
使用 h 函数创建子组件 vnode ,再使用 render 函数渲染

### What is expected?
h 函数创建子组件 vnode ,再使用 render 函数渲染后，子组件里的 antd 组件能够被解析

### What is actually happening?
h 函数创建子组件 vnode ,再使用 render 函数渲染后，子组件里的 antd 组件未被解析

**Comment by tangjinzhou** [comment]
全局注册的组件在 render 里找不到吧，可以用局部注册

或者给 vue 提 issue

**Comment by inkn** [comment]
> 全局注册的组件在 render 里找不到吧，可以用局部注册
> 
> 或者给 vue 提 issue

非常感谢，局部注册可以解决了
