### ISSUE TITLE
Image component preview, the mouse wheel image zoom in and out fails

### ISSUE THREAD

**Issue by mustars** [vueComponent/ant-design-vue#5700]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/34w2lq)

### Steps to reproduce
Image 组件预览，鼠标滚轮操作，图片的放大缩小功能失效。官方示例可复现。

### What is expected?
Image预览时鼠标滚动可放大或缩小图片

### What is actually happening?
没有响应放大或缩小图片

**Comment by tangjinzhou** [comment]
@buqiyuan 不确定是否支持过，可以看看 antd，没有支持的话，可以先放着

**Comment by buqiyuan** [comment]
> @buqiyuan 不确定是否支持过，可以看看 antd，没有支持的话，可以先放着

antd是支持的，我当时应该是写漏了，antd对应[代码片段](https://github.com/react-component/image/blob/f74f6e04f57e6e00fdc19c9c4d88e2abfbb4d8b1/src/Preview.tsx#L243-L250)，@techbirds感谢[PR](https://github.com/vueComponent/ant-design-vue/pull/5703)！LGTM
