### ISSUE TITLE
Versions after 3.2.4 date-picker can't select the value, it should be affected by the later version

### ISSUE THREAD

**Issue by qq449245884** [vueComponent/ant-design-vue#5704]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
vite

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
官网的例子

### What is expected?
正常

### What is actually happening?
日期控制选中不了值

**Comment by wang3690004** [comment]
同遇到这个问题，在3.2.5的时候写的时间组件 没有任何问题，  后面升级到了3.2.7 之后 a-date-picker 组件就会有报错 value设置的值是 [dayjs(),dayjs()] 。 后面没办法 把版本降低到3.2.5 恢复正常
