### ISSUE TITLE
Table drag resize column col.width changed, but the display is not updated

### ISSUE THREAD

**Issue by jellyidea** [vueComponent/ant-design-vue#5705]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
Win10,Edge,Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-ej4p4e?file=/src/App.vue)

### Steps to reproduce
使用模版风格的TABLE时，当使用鼠标拖动Table列去调整大小时，col.width变了，但显示没有更新。

### What is expected?
官方网正常
https://www.antdv.com/components/table-cn#components-table-demo-resizable-column

**Comment by jellyidea** [comment]
希望能得到验证，确认这是否是一个问题？谢谢~~~

**Comment by jellyidea** [comment]
@tangjinzhou 希望能得到验证，确认这是否是一个问题？谢谢~~~

**Comment by tangjinzhou** [comment]
核对版本，仅支持  3.x

**Comment by jellyidea** [comment]
我这边使用的是 3.2.6 但表头拖动调大小不好用

**Comment by jellyidea** [comment]
我在沙箱中按我的真实环境版本重新处理了一下，vue 3 + antdv 3.2.6
https://codesandbox.io/s/stoic-darwin-nc5k9y?file=/src/App.vue
这回问题应该已经重现了 @tangjinzhou

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/old-night-pu3dhz?file=/src/App.vue

**Comment by tangjinzhou** [comment]
使用响应式数据

**Comment by jellyidea** [comment]
您这个试例如果多个可调整大小的列的话是不是就不行了？

**Comment by jellyidea** [comment]
我作个数组使用您这方法吧。应该就可以了

**Comment by jellyidea** [comment]
如果希望可以多个列可调整要怎么做好呢？新手望指教。还有就是不使用setup是否可以？
https://codesandbox.io/s/stoic-darwin-nc5k9y?file=/src/App.vue
@tangjinzhou 
万分感谢

**Comment by jellyidea** [comment]
https://codesandbox.io/s/stoic-darwin-nc5k9y?file=/src/App.vue
当拖动调整开始时。鼠标按下。下方就会出现一个很长的滑动条。这个是否是存在问题？
@tangjinzhou

**Comment by tangjinzhou** [comment]
不同问题请分开提问  谢谢
