### ISSUE TITLE
what's the problem

### ISSUE THREAD

**Issue by mei2015** [vueComponent/ant-design-vue#5709]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
nuxt3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
打包

### What is expected?
ag-grid-vue3 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry

point). Please contact the package author to fix.

### What is actually happening?
ag-grid-vue3 doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry

point). Please contact the package author to fix.

**Comment by ajuner** [comment]
ag-grid-vue3 库的问题，看看有没有esm的用法
