### ISSUE TITLE
<a-List/>中如果列表没有元素时，可以自定义默认显示内容而不只是 “No data”

### ISSUE THREAD

**Issue by ShenQingchuan** [vueComponent/ant-design-vue#571]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
## 因为什么而催生了该需求：
首先是因为我在用 <a-list/> 列表组件制作一个评论列表，但是当我的某一个帖子没有评论时：
- <a-list/>原有的 header 我通过 :header="`${comments.length} 条评论`" ，显示的是 0条评论，这很好，没有问题
- 但是令我不满意的是下面还有一个 No data，这看上去很不好。

## 我想解决的问题：
就是可以自定义这个 列表元素为空时 的提示文字 emptyText（通过 Chrome vue-devtool 看到的这个其实是 a-spin 加载组件的一个匿名组件的属性）

### What does the proposed API look like?
```vue
<a-list  :dataSource="comments"
:header="`${comments.length} 条评论`"
:emptyText=" '还没人回复这条帖子，快来抢沙发！' ">
```

**Comment by sendya** [comment]
文档中有提供自定义 `无数据` 时的 API `locale`

![20190312011245](https://user-images.githubusercontent.com/5404542/54143053-f8e94900-4463-11e9-8ff6-fed36c062648.png)

**Comment by rex-mark** [comment]
不生效

**Comment by facccccer** [comment]
Why doesn't the locate attribute work?

Test Code:
`<a-list
...
:locate="{emptyText: '暂无数据'}"
:dataSource="[]"
/>`


![image](https://user-images.githubusercontent.com/41008551/77795509-954eaf80-70a8-11ea-9f5e-84efe4586ca5.png)
