### ISSUE TITLE
The tree data display of the table component and the expandable data display cannot be shared

### ISSUE THREAD

**Issue by horsecms** [vueComponent/ant-design-vue#5711]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
win 10  chrome  vue 3.2.25

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shu-xing-shu-ju-zhan-shi-ant-design-vue-3-2-7-forked-whedv6?file=/src/demo.vue)

### Steps to reproduce
同时使用树形数据展示和可展开数据展示会造成无法形成树形

### What is expected?
可同时使用树形数据展示和可展开数据展示

### What is actually happening?
不可以同时使用树形数据展示和可展开数据展示

**Comment by tangjinzhou** [comment]
不支持同时使用
