### ISSUE TITLE
Tooltip cannot be displayed

### ISSUE THREAD

**Issue by BeADre** [vueComponent/ant-design-vue#5714]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
macos: 10.15; chrome: 102; vue: 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-7-forked-w5j5dv?file=/src/demo.vue)

### Steps to reproduce
Tooltip cannot be displayed when the Upload component is `default slot`

### What is expected?
Tooltip can be displayed

### What is actually happening?
Tooltip cannot be displayed

---
View the source code and find that `rcUploadProps` in the `Upload.tsx` file does not receive `attrs`, I hope it can help

**Comment by tangjinzhou** [comment]
you can use like
```html
<template>
  <a-tooltip>
    <template #title>prompt text</template>
    <div>
    <a-upload>
      <a-button> Click to Upload </a-button>
    </a-upload>
    </div>
  </a-tooltip>
</template>

```

**Comment by BeADre** [comment]
thanks
