### ISSUE TITLE
The sortDirections property in the columns property of the Table component does not behave as expected

### ISSUE THREAD

**Issue by liuyuan22** [vueComponent/ant-design-vue#5715]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
vue@3.2.33 ant-design-vue@3.2.7 chrome@102.0.5005.115

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-currying-gf44ns?file=/src/App.vue)

### Steps to reproduce
参照https://codesandbox.io/s/trusting-currying-gf44ns?file=/src/App.vue

### What is expected?
示例中表格只有一列，该列可以排序，默认排序方式为descend，重复点击表头上的排序按钮时，期望该列的排序方式只能在descend和ascend之间切换（不包括undefined）

### What is actually happening?
重复点击表头上的排序按钮时，该列的排序方式在descend、ascend和undefined之间切换

**Comment by tangjinzhou** [comment]
`sortDirections=['descend', 'ascend', 'descend']`  即可

**Comment by liuyuan22** [comment]
> `sortDirections=['descend', 'ascend', 'descend']` 即可

感谢
