### ISSUE TITLE
the ant-design-vue of v1.7.8 has a bug with vite

### ISSUE THREAD

**Issue by sxlleo** [vueComponent/ant-design-vue#5717]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue2

### Reproduction link
[https://1x.antdv.com/components/menu-cn/](https://1x.antdv.com/components/menu-cn/)

### Steps to reproduce
1、build the vue2 project witch use ant-design-vue of v1.7.8 with vite;
2、vite preview;

### What is expected?
can brower

### What is actually happening?
there is an error in devtool console, tips is "require is not defined", i guess mutationobserver-shim trigger the error

**Comment by tangjinzhou** [comment]
1.x 不会默认支持 vite，可以自行配置(百度、google)

**Comment by nooooooom** [comment]
这么配置可以解决

```ts
// vite.config.js
build: {
    commonjsOptions: {
      transformMixedEsModules: true
    }
  },
```
