### ISSUE TITLE
select选择器在多选且选项项目多到产生动作条，将滚动条滚动任意距离，鼠标上下离开选择器区域会对滚动区域产生偏移

### ISSUE THREAD

**Issue by bearchQ** [vueComponent/ant-design-vue#572]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
win10,chrome72,vue2.6.6

### Reproduction link
[https://ant-design-vue.gitee.io/components/select-cn/#API](https://ant-design-vue.gitee.io/components/select-cn/#API)

### Steps to reproduce
select选择器在多选且选项项目多到产生动作条，将滚动条滚动任意距离，鼠标上下离开选择器区域会对滚动区域产生偏移

### What is expected?
不会产生偏移

### What is actually happening?
产生了偏移

![demo](https://user-images.githubusercontent.com/20750313/54126013-7e0f3680-4441-11e9-9906-2c3918c6be66.gif)

**Comment by SpanishOnion** [comment]
我也遇到这个问题了

**Comment by apple006** [comment]
我遇到了会自动回到顶部

**Comment by luotingv1** [comment]
我也遇到了 你楼主解决了?
