### ISSUE TITLE
Is antdv3 compatible with 2.7.0-alpha.12?

### ISSUE THREAD

**Issue by zhou5631** [vueComponent/ant-design-vue#5720]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
dev

### Reproduction link
[https://cdnpm.teleware.cn/](https://cdnpm.teleware.cn/)

### Steps to reproduce
无

### What is expected?
因为种种原因，系统要兼容IE，所以只能用VUE2。但我们用的技术栈是Ant Design Vue
最近有一个好消息，vue2.7出来了，拥有vue3的特性，咱们Ant Design Vue3会不会兼容vue2.7啊

### What is actually happening?
因为种种原因，系统要兼容IE，所以只能用VUE2。但我们用的技术栈是Ant Design Vue
最近有一个好消息，vue2.7出来了，拥有vue3的特性，咱们Ant Design Vue3会不会兼容vue2.7啊

---
因为种种原因，系统要兼容IE，所以只能用VUE2。但我们用的技术栈是Ant Design Vue
最近有一个好消息，vue2.7出来了，拥有vue3的特性，咱们Ant Design Vue3会不会兼容vue2.7啊

**Comment by tangjinzhou** [comment]
不会
