### ISSUE TITLE
Select render mismatch with csr(Client Side Render)

### ISSUE THREAD

**Issue by wheeljs** [vueComponent/ant-design-vue#5734]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
macOS Monterey version 12.4, Google Chrome Version 102.0.5005.115 (Official Build) (x86_64), Vue@3.2.37

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-evglmf?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-evglmf?file=src%2FApp.vue)

### Steps to reproduce
1. Setup a vite with ssr project by ['vite-ssr'](https://github.com/frandiox/vite-ssr#installation) module.
2. Add `<a-select mode="multiple">` into component, select multiple options.
3. Only one selected options in `<a-select>` has remove icon.

### What is expected?
All selected options should have remove icon after its label.

### What is actually happening?
Only one selected options in `<a-select>` has remove icon.

---
Withour SSR(Works) reproduction link: [https://stackblitz.com/edit/vitejs-vite-c6xqfq?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-c6xqfq?file=src%2FApp.vue)

I have also fire this issue in [vite-ssr repo](https://github.com/frandiox/vite-ssr/issues/169), [ant-design-icons repo](https://github.com/ant-design/ant-design-icons/issues/531). Sorry for my English.

**Comment by wheeljs** [comment]
As a workaround, I set removeIcon prop to "X"(character) instead of the default `CloseOutlined` from `@ant-design/icons-vue`, then `<a-select>` renders removeIcon for every selected option correctly. I think this may be an unexpected result with `@ant-design/icons-vue` not `ant-design-vue`. `<CheckOutlined>` in select options popover also have this problem.

**Comment by tangjinzhou** [comment]
应该是 vite-ssr 问题
它不支持  export { default }

**Comment by wheeljs** [comment]
> 应该是 vite-ssr 问题 它不支持 export { default }

Thanks for your replying, is there have any workaround?

**Comment by vcasy** [comment]
> 应该是 vite-ssr 问题 它不支持 export { default }

The icons are not the issue. 
Proof - this will not work:

1) create a very simple component
2) use it in the icon slot

```
<a-select
mode="tags"
:options="options" 
>
  <template #removeIcon>
    <SimpleComponent />
  </template 
</a-select>
```

→ Component in icon slot will not render reliably
However if the slot is something simple like a native HTML Element (for example `<button>test</button>`) it works.

Somehow vite will not render the HTML content of any component in this slot.
Oddly enough the component itself will be attached correctly according to Vue.js devtools
