### ISSUE TITLE
Table-pagination

### ISSUE THREAD

**Issue by zbkha** [vueComponent/ant-design-vue#5736]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
Windows 10 Chrome 102.0.5005.63 Vue 3.2.36

### Reproduction link
[https://www.antdv.com/components/pagination-cn/](https://www.antdv.com/components/pagination-cn/)

### Steps to reproduce
Table组件中配置pagination中的pageSize固定为某个值的时候，如果不配置showSizeChanger，页数少的时候正常（不显示sizeChanger，因为文档中showSizeChanger默认为false），但页数多的时候就会显示sizeChanger，只能手动配置showSizeChanger为false，才能不显示sizeChanger。

### What is expected?
如上

### What is actually happening?
如上

**Comment by tangjinzhou** [comment]
3.0 新特性  https://www.antdv.com/components/table-cn#%E8%A1%A8%E6%A0%BC%E5%88%86%E9%A1%B5%E4%B8%BA%E4%BD%95%E4%BC%9A%E5%87%BA%E7%8E%B0-size-%E5%88%87%E6%8D%A2%E5%99%A8%EF%BC%9F

**Comment by zbkha** [comment]
如何在Table组件中配置pagination中的current(v-model)？
配置change事件是onChange属性，这一点是猜出来的，我没在文档中找到具体说明，current(v-model)试不出来。
如果不在Table组件中配置pagination，就得新建一个Pagination组件，这样可以解决问题。但新建的pagination组件默认布局是文档流，在Table组件左下方显示，不符合人的使用体验，还得自己添加css样式改变位置。而Table组件中的pagination配置项则是显示在右下角，符合使用体验。
综上，是否可以在Table组件中配置pagination中的current(v-model)？，如果可以，该怎样配置？
