### ISSUE TITLE
When the table component has fixed columns, the fixed columns will be misaligned with the non-fixed columns during the scrolling process, and they will be restored after the scrolling ends.

### ISSUE THREAD

**Issue by curryft** [vueComponent/ant-design-vue#5739]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
chrome102 ，vue2.x

### Reproduction link
[https://1x.antdv.com/components/table-cn/#components-table-demo-grouping-table-head](https://1x.antdv.com/components/table-cn/#components-table-demo-grouping-table-head)

### Steps to reproduce
https://1x.antdv.com/components/table-cn/#components-table-demo-grouping-table-head
官网的这个示例在滚动过程中name列会与其他列有错位

### What is expected?
滚动过程中没有错位，2.x版本的同一个示例中就不会错位

### What is actually happening?
如上

**Comment by wshhfy** [comment]
请问问题解决了吗

**Comment by 474112265** [comment]
顶上顶上，我也遇到这个问题了
