### ISSUE TITLE
a-typography-link specifies the copyable attribute, limiting the self event of the copy button to not be thrown

### ISSUE THREAD

**Issue by atom-git** [vueComponent/ant-design-vue#5746]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
例如<a-typography-link @click="handleLinked" underline copyable></a-typography-link>中，点击copy按钮，click事件也会被响应，有可能会需要两种动作

### What does the proposed API look like?
copyable时，copy按钮 onclick中增加stop阻止冒泡

**Comment by tangjinzhou** [comment]
使用 copyableIcon 插槽自定义 copy icon 就可以了

**Comment by atom-git** [comment]
> 使用 copyableIcon 插槽自定义 copy icon 就可以了

https://codesandbox.io/s/wen-ben-yu-chao-lian-jie-zu-jian-ant-design-vue-3-2-7-forked-6g751e?file=/src/demo.vue
亲，麻烦看下，按照您的说法，还是一样的，点击copy按钮，绑定在a-typography-link中的动作也生效了

**Comment by tangjinzhou** [comment]
```html
<template #copyableIcon="{ copied }">
        <span @click.stop>
        <CopyOutlined v-if="!copied" />
        <CheckOutlined v-else style="color: blue" />
        </span>
      </template>
```

自定义 stop  啊

**Comment by atom-git** [comment]
> ```
> <template #copyableIcon="{ copied }">
>         <span @click.stop>
>         <CopyOutlined v-if="!copied" />
>         <CheckOutlined v-else style="color: blue" />
>         </span>
>       </template>
> ```
> 
> 自定义 stop 啊

场景是，通过link展示一个链接文本，后面提供复制长文本的能力，同时点击链接时又能够自定义响应动作，两个动作是分离的，这里stop后，copy默认动作也丢失了。

**Comment by atom-git** [comment]
> ```
> <template #copyableIcon="{ copied }">
>         <span @click.stop>
>         <CopyOutlined v-if="!copied" />
>         <CheckOutlined v-else style="color: blue" />
>         </span>
>       </template>
> ```
> 
> 自定义 stop 啊

场景是，通过link展示一个链接文本，后面提供复制长文本的能力，同时点击链接时又能够自定义响应动作，两个动作是分离的，这里stop后，copy默认动作也丢失了。
