### ISSUE TITLE
When the a-typography-link component is copyable, add the @click event, and the content part click event will also be triggered when copying

### ISSUE THREAD

**Issue by atom-git** [vueComponent/ant-design-vue#5752]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
MACOS12.4 WINDOWSEDGE 103

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wen-ben-yu-chao-lian-jie-zu-jian-ant-design-vue-3-2-7-forked-6g751e?file=/src/demo.vue)

### Steps to reproduce
<a-typography-link
@click="handleClick"
:ellipsis="true"
content=" Ant Design Vue (copyable Link)Ant Design Vue (copyable Link)Ant Design Vue(copyable Link)Ant"
underline
copyable
>
<template #copyableIcon="{ copied }">
<CopyOutlined v-if="!copied" />
<CheckOutlined v-else style="color: blue" />
</template>
</a-typography-link>

是否自定义copy按钮，在a-typography-link组件中增加@click响应均会出现copy点击也会触发内容部分click的情况

### What is expected?
copy expand edit等按钮点击不触发typography内容部分自定义的click事件

### What is actually happening?
copy expand edit等按钮点击触发typography内容部分自定义的click事件

**Comment by tangjinzhou** [comment]
ref #5746
