### ISSUE TITLE
Tree component Click the currently selected node, can you not remove the selected effect? ​​One must be selected.

### ISSUE THREAD

**Issue by yeyuliang2015** [vueComponent/ant-design-vue#5753]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
树组件点击当前选中节点，可以不去掉选中效果吗，必须选中一个。

### What does the proposed API look like?
树组件点击当前选中节点，可以不去掉选中效果吗，必须选中一个。

**Comment by yeyuliang2015** [comment]
树组件点击当前选中节点，可以不去掉选中效果吗，必须选中一个。

**Comment by tangjinzhou** [comment]
可以  受控模式
