### ISSUE TITLE
LIst-pagination-current(v-model)

### ISSUE THREAD

**Issue by zbkha** [vueComponent/ant-design-vue#5754]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
Windows 10 Chrome 102.0.5005.63 Vue 3.2.36

### Reproduction link
[https://www.antdv.com/components/list-cn#pagination](https://www.antdv.com/components/list-cn#pagination)

### Steps to reproduce
LIst组件中的pagination配置项里的current(v-model)问题
如果直接写:pagination="{current: page, onChange: handleChange}",那么当前页码就永远是变量page的初始值，根本没办法换页，直接固定死了。点击其它页码不换页但是能触发change事件，如果又把page绑定到其它DOM上面，那页码就能随着page值的变化而变化了。也就是说这种写法只是单向绑定。文档中并没有相关说明（onChange的写法也是自己猜出来的）。
如何在List组件中正确配置pagination中的current(v-model)？

### What is expected?
我想要的效果就是在List组件中正确配置pagination中的current(v-model)。

### What is actually happening?
我不知道怎么正确配置。

**Comment by tangjinzhou** [comment]
onChange 或 onUpdate:current

`@change` 事件在配置中就是对应 `onChange`
而 `v-model:current` 对应的事件是 `@update:current`，相应的 `@update:current` 对应的配置就是 `onUpdate:current`

这是 vue 规范，不是组件规范

**Comment by zbkha** [comment]
> onChange 或 onUpdate:current
> 
> `@change` 事件在配置中就是对应 `onChange` 而 `v-model:current` 对应的事件是 `@update:current`，相应的 `@update:current` 对应的配置就是 `onUpdate:current`
> 
> 这是 vue 规范，不是组件规范

多谢，使用了以下写法，果然奏效了。不过在配置中使用双向绑定，就必须用原始写法了，没有组件中的v-model语法糖方便。
```ts
const pageChange = (p: number) => {
  page.value = p
}
```
```vue
<a-list :pagination="{current: page, 'onUpdate:current': pageChange}" />
```

**Comment by tangjinzhou** [comment]
https://github.com/vuejs/babel-plugin-jsx  可能有语法糖支持
