### ISSUE TITLE
Dynamic theme configuration invalid after modifying prefixCls

### ISSUE THREAD

**Issue by jiangtwelve** [vueComponent/ant-design-vue#5756]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
"ant-design-vue": "^3.2.9" "vue": "^3.0.0",

### Reproduction link
[https://gitee.com/jiangtwelve/antd-vue-bug.git](https://gitee.com/jiangtwelve/antd-vue-bug.git)

### Steps to reproduce
根据动态主题文档 修改主题 primaryColor: "#25b864". 结果无异常，当修改前缀prefixCls: "custom" 动态主题配置失效
```
ConfigProvider.config({  prefixCls: "custom", theme: {  primaryColor: "#25b864", } })
```

### What is expected?
lessc --js --modify-var="ant-prefix=custom" node_modules/ant-design-vue/dist/antd.variable.less modified.css命令生成新的modified.css文件中变量前缀已经修改为 custom 但是颜色是默认配置 并非 动态主题指定的颜色

### What is actually happening?
修改类名前缀同时不支持修改主题色 是否是我操作不当造成 复现仓库地址：https://gitee.com/jiangtwelve/antd-vue-bug.git

**Comment by tangjinzhou** [comment]
同步更改 @base-primary less 变量

**Comment by jiangtwelve** [comment]
> 同步更改 @base-primary less 变量

具体应该怎么操作呢 可以详细说一下嘛

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/customize-theme-cn
