### ISSUE TITLE
How antv-tree expands all under lazy loading

### ISSUE THREAD

**Issue by 2016011969sunyifang** [vueComponent/ant-design-vue#5761]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
想要一个展开全部的功能 通过按钮点击实现树的展开全部 目前米有找到什么好的方法 直接赋值会引发节点刷新的问题

### What does the proposed API look like?
给一个属性暴露出来 如果为true则自动站看 据我所知现在的expendAll只能在初始化时候应用

**Comment by tangjinzhou** [comment]
受控模式，同过 expandKeys 展开
