### ISSUE TITLE
Console error message "xx.confirm is not a function" and not show dialog.

### ISSUE THREAD

**Issue by wengx-unx** [vueComponent/ant-design-vue#5763]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
Vite^2.9.9、Vue^3.2.36、pnpm

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confirm-error-6om3v8?file=/src/demo.vue)

### Steps to reproduce
1. Create a Vue project using the above environment.
2. Using [Confirmation modal dialog](https://antdv.com/components/modal) Example
3.  `pnpm run build ` and click button.

### What is expected?
Show a confirmation modal dialog.

### What is actually happening?
Console error message "xx.confirm is not a function" and not show dialog.

---
In the build environment.

**Comment by cshuting** [comment]
Has this problem been fixed?

**Comment by wengx-unx** [comment]
> Has this problem been fixed?

Not yet

**Comment by techbirds** [comment]
After verification, under the premise of the same environment, the pop-up window after construction can work normally. You can take a look at this example:

https://github.com/techbirds/my-vue-app

```
pnpm i
pnpm run serve
```

**Comment by gitgundam** [comment]
> > Has this problem been fixed?
> 
> Not yet

same problem, after builded the project with vite.

**Comment by eisir** [comment]
you can try to use
import Modal from "ant-design-vue/lib/modal"
 instead of
import Modal from "ant-design-vue"

**Comment by chapubest** [comment]
> you can try to use import Modal from "ant-design-vue/lib/modal" instead of import { Modal } from "ant-design-vue"

it worked

**Comment by chenjiangui** [comment]
same problem with vite and antdv 3.2.10

**Comment by zch233** [comment]
the same

**Comment by peerlessXu** [comment]
i have the same problem

**Comment by wjkang** [comment]
the same

**Comment by asiyuan** [comment]
have any result

**Comment by asiyuan** [comment]
> you can try to use import Modal from "ant-design-vue/lib/modal" instead of import { Modal } from "ant-design-vue"

so use this, can't open in development

**Comment by cn-wang** [comment]
you can try to use

```ts
// modal.ts
import { Modal } from 'ant-design-vue'
export const {  info, success, error, warning, confirm } = Modal
```

```vue
// demo.vue
<template>
  <button @click="handleClick">click me</button>
</template>

<script  lang="ts">
import {confirm} from './modal'
export default {
  setup() {

    return {
      handleClick() {
       confirm({
          title: "title", 
          onOk() {
            console.log("hi...")
          }
        })
      }
    }
  }
}
</script>
```


I think this question should be in vite...

**Comment by dodaydream** [comment]
> you can try to use
> 
> ```ts
> // modal.ts
> import { Modal } from 'ant-design-vue'
> export const {  info, success, error, warning, confirm } = Modal
> ```
> 
> ```
> 
> <template>
>   <button @click="handleClick">click me</button>
> </template>
> 
> <script  lang="ts">
> import {confirm} from './modal'
> export default {
>   setup() {
> 
>     return {
>       handleClick() {
>        confirm({
>           title: "title", 
>           onOk() {
>             console.log("hi...")
>           }
>         })
>       }
>     }
>   }
> }
> </script>
> ```
> 
> I think this question should be in vite...

Tried the above solution, still does not work. Can confirm this question occurred in vite. However, importing from `ant-design-vue/lib/modal` works.

**Comment by Tangchony** [comment]
same problem

**Comment by thaotrong2000** [comment]
**- My solution is:**
I use confirm modal in package "ant-design-vue".
I dont import all component, i import several component.

_// important_
import { Modal } from "ant-design-vue";
Vue.prototype.$confirm = Modal.confirm;

**Comment by thaotrong2000** [comment]
> same problem
My solution:
https://github.com/vueComponent/ant-design-vue/issues/5763#issuecomment-1488380170

**Comment by Tangchony** [comment]
> 
Thanks! I have successed in his way ([eisir](https://github.com/eisir) )

**Comment by Tangchony** [comment]
> > 
> 
> Thanks! I have successed in his way ([eisir](https://github.com/eisir) )

https://github.com/vueComponent/ant-design-vue/issues/5763#issuecomment-1177231433
