### ISSUE TITLE
@vue/compat error with Cannot read properties of undefined (reading 'getPrefixCls')

### ISSUE THREAD

**Issue by HenryWong-fe** [vueComponent/ant-design-vue#5765]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
vue version 3.2.36

### Reproduction link
[https://github.com/HenryWong-fe/vue-compet-ant-design-vue](https://github.com/HenryWong-fe/vue-compet-ant-design-vue)

### Steps to reproduce
在使用@vue/compat做vue2项目升级时，使用ant-design-vue会出现报错

### What is expected?
可以使用@vue/compat的同时，使用ant-design-vue

### What is actually happening?
无法使用

**Comment by tangjinzhou** [comment]
@vue/compet 是什么，不知道

**Comment by HenryWong-fe** [comment]
> @vue/compet 是什么，不知道

这是官方提供的，用于vue2升级至vue3的方案，对于项目已经很庞大的我们来说，没有办法直接升级vue3

**Comment by adnabb** [comment]
the same.

**Comment by Tiquiero** [comment]
@HenryWong-fe 请问这个问题有解决办法嘛？
