### ISSUE TITLE
will ant-design-vue(1.7.8) upgrade vue2 to 2.7.0?

### ISSUE THREAD

**Issue by iceprosurface** [vueComponent/ant-design-vue#5768]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
for: https://github.com/vuejs/vue/releases/tag/v2.7.0

### What does the proposed API look like?
NO

**Comment by tangjinzhou** [comment]
1.7.8   现在兼容 2.7 啊

**Comment by shiyeling** [comment]
> I did tryed on vue2.7, it works perfectly for me.

No issue at all? 
I'm having issue with binding ref variable to v-model, which accepts only string or number, but got an object.
