### ISSUE TITLE
Cannot read property 'propsData' of undefined  at VueComponent.renderCommonMenuItem

### ISSUE THREAD

**Issue by XiaYuYing** [vueComponent/ant-design-vue#577]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
Windows x64, Chrome 70, vue-cli 3.5.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3820z4v0zp?fontsize=14)

### Steps to reproduce
follow the step: https://vue.ant.design/components/menu-cn/#API

### What is expected?
It should be the same as the image example of the official website.

### What is actually happening?
throw an error:
```
vue.runtime.esm.js?2b0e:1887 TypeError: Cannot read property 'propsData' of undefined
    at VueComponent.renderCommonMenuItem (SubPopupMenu.js?1462:277)
    at VueComponent.renderMenuItem (SubPopupMenu.js?1462:338)
    at eval (SubPopupMenu.js?1462:390)
    at Array.map (<anonymous>)
    at Proxy.render (SubPopupMenu.js?1462:389)
    at VueComponent.Vue._render (vue.runtime.esm.js?2b0e:3535)
    at VueComponent.updateComponent (vue.runtime.esm.js?2b0e:4041)
    at Watcher.get (vue.runtime.esm.js?2b0e:4444)
    at Watcher.run (vue.runtime.esm.js?2b0e:4519)
    at flushSchedulerQueue (vue.runtime.esm.js?2b0e:4275)
```

**Comment by mediatec** [comment]
Hi there!

You should import custom sub-menu component (see docs)
Screenshot: https://i.gyazo.com/bc8d07bb333546164dff9ca8a779e858.png

**Comment by XiaYuYing** [comment]
But i have already input `antd` globally,Is there still have the necessity to input again?

**Comment by tangjinzhou** [comment]
@XiaYuYing  `<a-sub-menu />` not `<sub-menu/>`

**Comment by uniquejava** [comment]
@tangjinzhou  I met the same issue.

**Comment by mgnrfk** [comment]
Hi,

I have a similar issue, I used the fully imported Antd but I want to switch to importing components one by one, if I import "Menu", I have the same "Cannot read property 'propsData' of undefined when I replace <a-menu ..> with <Menu ..>

**Comment by dzcpy** [comment]
@mgnrfk Have you found any solution?

**Comment by sjaslow** [comment]
This appears to be a design problem in SubPopupMenu::render() around line 393, where the code makes an assumption that child nodes are antd menu items. That prevents using other components within <a-menu> such as OP's example, or portals/slots for dynamic menus, and so on. For example, you will get the error doing:

`
<a-menu>
    <slot name="menu-items"></slot>
</a-menu>
`

**Comment by Leocat81** [comment]
> 但是我已经`antd`在全球范围内输入了，是否仍然需要再次输入？
不需要了

**Comment by grafikri** [comment]
When I wanted to use ant-design-vue dropdown menu plugin, I was getting such kind of error. My components registrations was like this;

```js
components: {
  'a-menu': Menu,
  'a-menu-item': Menu.Item,
  'a-dropdown': Dropdown,
}
```

Then I removed the 'a-menu-item' line, the error disappeared
```js
components: {
  'a-menu': Menu,
  'a-dropdown': Dropdown,
}
```

maybe it could be help

**Comment by kevinxuv** [comment]
same issue

**Comment by kevinxuv** [comment]
> @xiayuying `<a-sub-menu />` not `<sub-menu/>`

加了还是有问题
