### ISSUE TITLE
[DatePicker]: Moment.isMoment is not a function

### ISSUE THREAD

**Issue by nooooooom** [vueComponent/ant-design-vue#5778]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Windows10, Chrome 102.0.5005.115, Vue 2.6.14

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/acaad271351ca0966f828fd323ecfa05cefe6537/components/_util/moment-util.js#L2](https://github.com/vueComponent/ant-design-vue/blob/acaad271351ca0966f828fd323ecfa05cefe6537/components/_util/moment-util.js#L2)

### Steps to reproduce
Start with vite.

### What is expected?
DatePicker working well.

### What is actually happening?
An error has occurred, It's described as moment.isMoment is not a function.

---
The moment 2.21.0 doesn't support es module export, so import * as XX will have an error.

**Comment by nooooooom** [comment]
![image](https://user-images.githubusercontent.com/61452855/177324911-1fb07c83-0059-4c68-8820-2c20ee286fd6.png)
![image](https://user-images.githubusercontent.com/61452855/177324958-670061b5-c50c-42d0-bb30-2efa2749176c.png)

**Comment by nooooooom** [comment]
This question is a duplicate, but was never addressed.

**Comment by tangjinzhou** [comment]
For 1.x, we not change this.
you can try use alias `moment-util.js` to new file.

**Comment by nooooooom** [comment]
> For 1.x, we not change this. you can try use alias `moment-util.js` to new file.

Thanks, this solves the problem.

**Comment by moliyu** [comment]
@nooooooom you can try my plugin [vite-plugin-antdv-fix](https://www.npmjs.com/package/vite-plugin-antdv-fix)
