### ISSUE TITLE
在新版Vue下通过createForm创建的form在有rules校验规则时在文本框中长按任意键输入或输入过快时页面卡顿线程阻塞

### ISSUE THREAD

**Issue by Sun79** [vueComponent/ant-design-vue#578]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
windows 10 x64, chrome 72.0.3626.109 x64, vue 2.6.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2z8x8qylon?fontsize=14)

### Steps to reproduce
1.聚焦任意文本框；
2.长按某个按键或快速输入；

### What is expected?
和在低版本Vue上一样可以流畅输入

### What is actually happening?
输入卡顿

---
低版本vue
https://codesandbox.io/s/l9j70xxomz?fontsize=14

**Comment by tangjinzhou** [comment]
没能复现哎，你在确认下？

**Comment by Sun79** [comment]
我是笔记本可能处理器比较弱，按住某个键输入时真的很卡，处理器占用很高，vue2.6.x之后都存在这个问题，vue2.5.x没有这个问题。
https://codesandbox.io/s/yvjq6rvrzz?fontsize=14
![](http://ww1.sinaimg.cn/large/b4ba039fgy1g13azw3p44j21hc0swti0.jpg)

**Comment by Conor-D** [comment]
The same thing happened to me, please.

https://codesandbox.io/s/5zjk8z5pk

**Comment by tangjinzhou** [comment]
@Conor-D 
Your question is not the same thing.
Your table data is too large, it should be separated from the form into two components, avoid multiple updates.  https://codesandbox.io/s/jkmo4927w

**Comment by guying-01** [comment]
I have the same problem.
When the number of  '<a-form-item>' is more than 10 ,problem will be obvious.
You can try it at here,[link](https://vue.ant.design/components/form-cn/#components-form-demo-registration),quickly enter at 'website' and you will find it.

**Comment by KyLeoHC** [comment]
确实有卡顿问题。尤其用了ant库的组件，在一个页面上达到一定数量时，输入框(不一定是a-input，就算是原始的input用v-model双向绑定)就会输入卡顿。chrome性能分析会发现cpu占用很高。。

**Comment by Sun79** [comment]
1.3.17-beta.1版本已解决，非常感谢唐老师🌹
