### ISSUE TITLE
The preview in the a-image component controls whether the preview text is displayed

### ISSUE THREAD

**Issue by atom-git** [vueComponent/ant-design-vue#5789]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
图片设置较小时，预览文字超出，导致显示异常，增加标记位设置preview中的预览文字不显示，仅显示icon

### What does the proposed API look like?
preview: { showType: 'icon' } icon 或者 text 或者 both

**Comment by liwenpmz** [comment]
解决了吗
