### ISSUE TITLE
固定表头的表格，在FireFox下出现不对齐问题

### ISSUE THREAD

**Issue by wshsm1** [vueComponent/ant-design-vue#579]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
FireFox v65

### Reproduction link
[https://vue.ant.design/components/table-cn/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4](https://vue.ant.design/components/table-cn/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4)

### Steps to reproduce
官方DEMO页面
https://vue.ant.design/components/table-cn/#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4

### What is expected?
期望展示正常

### What is actually happening?
表头下多了一小行，导致很多地方不对齐

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/54358853-48b25500-469c-11e9-8884-e28327754b18.png)


没能复现你的问题

**Comment by wshsm1** [comment]
![图片](https://user-images.githubusercontent.com/48546829/54574118-071e0300-4a2a-11e9-8a4b-ca616de3343a.png)
麻烦看下，我是win10环境，我们这边所有开发人员的FireFox最新版本都会有这个问题，我估计跟滚动条的宽度有关。1.3.7版本解决了表头的滚动条，但是依然不对齐

**Comment by wshsm1** [comment]
你们是用苹果的系统，估计滚动条比较细所以没这个问题

**Comment by wshsm1** [comment]
react版本没有这个问题
![图片](https://user-images.githubusercontent.com/48546829/54574426-31bc8b80-4a2b-11e9-971e-14aede790a7c.png)

**Comment by sendya** [comment]
的确有这个问题，看起来像是这个 `padding-bottom: 20px` 引起的。
但是去除 .ant-table-header 的 `overflow: scroll;`  就正常了

![20190319141137](https://user-images.githubusercontent.com/5404542/54584065-36943600-4a51-11e9-91ca-a752f0941051.png)

![20190319141249](https://user-images.githubusercontent.com/5404542/54584068-372ccc80-4a51-11e9-8bd5-e2d6ae27f3ec.png)

![20190319141321](https://user-images.githubusercontent.com/5404542/54584070-372ccc80-4a51-11e9-9ace-e897efca30a4.png)
