### ISSUE TITLE
Whether Form.Item can increase the prop of value is the value of the current input component

### ISSUE THREAD

**Issue by fshihu** [vueComponent/ant-design-vue#5800]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
对于动态输入框来说，prop传参不是太方便，而且还必须要把值放在from的model里面

### What does the proposed API look like?
**现在是这样**

`<a-form-model-item :prop="'form.' index '.name'" ref="name" :autoLink="false" v-for="(item ,index) in form_data.options">
<a-input v-model="item.name" />
</a-form-model-item>`

**期望**

`<a-form-model-item :value="item.name" ref="name" :autoLink="false" v-for="(item ,index) in form_data.options">
<a-input v-model="item.name" />
</a-form-model-item>`

**Comment by fshihu** [comment]
版本 1.7.8

**Comment by tangjinzhou** [comment]
1.x  不在添加新功能
