### ISSUE TITLE
Components.Tree：Document sample judgment error @drop=ondrop

### ISSUE THREAD

**Issue by shuimupj** [vueComponent/ant-design-vue#5801]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
chrome

### Reproduction link
[https://www.antdv.com/components/tree-cn#components-tree-demo-draggable](https://www.antdv.com/components/tree-cn#components-tree-demo-draggable)

### 文档的“Tree 树形控件”参考案例中拖动示例代码
```
const onDrop = info => {
...
if (!info.dropToGap) {
...
} else if (
(info.node.children || []).length > 0 && // Has children
info.node.expanded && // Is expanded
dropPosition === 1 // On the bottom gap
) {
...
} else {
...
}
...
}
```
### What is expected?
能否解释一下else if的逻辑作用

### What is actually happening?
@drop=onDrop 的回调参数info，  info.node下并无children

**Comment by tangjinzhou** [comment]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/6937879/180633404-82e96821-80a5-4c73-a6ef-ec0a86c01ceb.png">
