### ISSUE TITLE
When useform is used, the trigger configuration'blur'in rules is invalid, only'change'is used

### ISSUE THREAD

**Issue by san346596324** [vueComponent/ant-design-vue#5802]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
win10、vue3

### Reproduction link
[https://www.antdv.com/components/form-cn#API](https://www.antdv.com/components/form-cn#API)

### Steps to reproduce
rules: [{ validator: againCheck, trigger: ['blur'] }]

### What is expected?
'blur'is effective when using validator

### What is actually happening?
only'change'is used

**Comment by tangjinzhou** [comment]
![image](https://user-images.githubusercontent.com/6937879/178910714-d1b4582b-8e87-4d3f-ad45-2c5505d9b711.png)
