### ISSUE TITLE
The shuttle box has prompts for the total number and the selected number. Can this part be turned into a slot and can be customized. You can't customize the slot, at least you can control the display and hide (using display none doesn't feel very good)

### ISSUE THREAD

**Issue by SKT1yang** [vueComponent/ant-design-vue#5804]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
不是bug，穿梭框有总数和选中数量的提示，这部分能不能变成一个slot可以自定义，在复杂自定义穿梭框的时候，显示不正确，比如：左边树，右边表格，穿梭后不是disabled掉，而是直接过滤掉了。这个时候显示的总数数量是不对的（不是bug）。不能slot自定义，起码能后控制显示隐藏

### What does the proposed API look like?
<a-transfer
v-model:target-keys="targetKeys"
:data-source="mockData"
:disabled="disabled"
:show-search="showSearch"
:filter-option="(inputValue, item) => item.title.indexOf(inputValue) !== -1"
:show-select-all="false"
@change="onChange"
>
<template
#children="{
direction,
filteredItems,
selectedKeys,
disabled: listDisabled,
onItemSelectAll,
onItemSelect,
}"
>
<a-table
:row-selection="
getRowSelection({
disabled: listDisabled,
selectedKeys,
onItemSelectAll,
onItemSelect,
})
"
:columns="direction === 'left' ? leftColumns : rightColumns"
:data-source="filteredItems"
size="small"
:style="{ pointerEvents: listDisabled ? 'none' : null }"
:custom-row="
({ key, disabled: itemDisabled }) => ({
onClick: () => {
if (itemDisabled || listDisabled) return;
onItemSelect(key, !selectedKeys.includes(key));
},
})
"
/>
</template>
<template #header={
filteredItems,
checkedKeys
}>
<span>
<span>{getSelectAllLabel(checkedKeys.length, filteredItems.value.length)}</span>
</span>
</template>
</a-transfer>

**Comment by tangjinzhou** [comment]
css 隐藏默认的，使用 titles 自定义
