### ISSUE TITLE
How to set the error message in the form?

### ISSUE THREAD

**Issue by chen-ccll** [vueComponent/ant-design-vue#5805]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表单提交数据后，后端接收到数据，然后返回错误信息，这时需要form设置表单项的错误信息，之前1.0版本，有一个setFields可以设置一组表单项的错误状态信息，希望3.0版本也能提供一个相应的方法。3.0如果有其他的方法实现此需求的话，麻烦请教一下，谢谢。

### What does the proposed API look like?
提供一个setFields方法，可以设置表单项的错误状态

**Comment by tangjinzhou** [comment]
直接改 rules(前提是响应式的) 里的message 数据就可以了吧

**Comment by chen-ccll** [comment]
感谢你的回答，我按照你说的去实现了一下，但似乎不能解决。业务场景是这样的：
![1b17bfb4a50868e518faf11f08cee13](https://user-images.githubusercontent.com/59905508/179435568-0ad392ad-e49c-42d8-afa6-4b98d6351dd4.png)
图片上数据提交到后端之后，后端返回错误信息，比如名字重复了。这时需要设置这项表单状态错误。
![89001ad4bdfdabd3419ff11131be356](https://user-images.githubusercontent.com/59905508/179435652-d465f429-64e5-49d3-99ef-ab210e37cfb4.png)

**Comment by mansion-sun** [comment]
...

**Comment by mansion-sun** [comment]
> Refere

例：
```template
<a-form-item>
  <a-input
    class="login-item-content"
    size="large"
    type="text"
    :placeholder="$t('user.login.username.placeholder')"
    v-decorator="[
      'username',
      {
        rules: [{ required: true, whitespace: true, message: $t('user.userName.required') }],
        validateTrigger: 'blur',
        initialValue: state.userName
      },
    ]"
    @blur="handleNameBlur"
  >
    <a-icon slot="prefix" type="user" :style="{ color: 'rgba(0,0,0,.5)' }" />
  </a-input>
</a-form-item>
this.form?.setFields({ username: { value, errors: [ new Error(message || '用户名不存在') ] } })
```
```script
// 用户名失焦校验
handleNameBlur (e) {
  const value = e?.target?.value?.trim()
  console.log('handleNameBlur value, e', value, e)
  const loginNm = encryptAES(value)
  !!value && checkUser({ loginNm, })
  .then(res => {
    console.log('checkUser res', res)
    const { status, message } = { ...res }
    if (status === 'success') {
      this.form?.setFields({ username: { value, errors: null } })
    } else {
      this.form?.setFields({ username: { value, errors: [ new Error(message || '用户名不存在') ] } })
    }
  })
  .catch(error => {
    console.log('checkUser error', error)
    const message = error?.response?.data?.message
    this.form?.setFields({ username: { value, errors: [ { message: message || '用户名输入有误' }, ] } })
  })
},
// 提交按钮回调
handleSubmit (e) {
  e.preventDefault()
  const {
    form: { validateFields },
  } = this

 validateFields(['username', ], { force: true }, (err, values) => {})
},
```
未触发 validateFields(['username', ], { force: true }, (err, values) => {})中err
是v-decorator指令写法不对吗，如何setFields设置errors才能触发validateFields中err

"ant-design-vue": "^1.7.8",
"vue": "^2.6.14",
