### ISSUE TITLE
An error occurred when importing components on demand

### ISSUE THREAD

**Issue by suqiernb** [vueComponent/ant-design-vue#5808]
- [ * ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.10

### Environment
Vue 3.2.13
Google Chrome 102.0.5005.63
Windows 11 x64

### Reproduction link
[https://github.com/suqiernb/ant-design-vue-import-test](https://github.com/suqiernb/ant-design-vue-import-test)

### Steps to reproduce
``` bash
git clone https://github.com/suqiernb/ant-design-vue-import-test.git
cd ant-design-vue-import-test
npm install
npm run serve
```

### What is expected?
可以按需球引入组件, 减小项目体积

### What is actually happening?
```
# Error
Module not found: Error: Can't resolve 'ant-design-vue/es/form/style/css' in '$PROJECT_PATH'
Module not found: Error: Can't resolve 'ant-design-vue/es/form-item/style/css' in '$PROJECT_PATH'
```

**Comment by tangjinzhou** [comment]
使用  unplugin-vue-components/vite
