### ISSUE TITLE
DatePicker date range selection How to display the OK button in the lower right corner, no related configuration items are found

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5816]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
DatePicker  日期范围选择 右下角确定按钮怎么显示出来，没找到相关配置项，组件文档里有ok	点击确定按钮的回调
![image](https://user-images.githubusercontent.com/5828057/179398347-eb8517d9-2949-4778-b826-dfd1440e83d3.png)
如图所属
### What does the proposed API look like?
DatePicker  日期范围选择 右下角确定按钮怎么显示出来，没找到相关配置项，组件文档里有ok	点击确定按钮的回调

**Comment by tangjinzhou** [comment]
show-time 时显示，如果其它需要，可以自定义 footer，自行添加
