### ISSUE TITLE
DatePicker date range selection The preset common date range, currently it is displayed below, whether it can be displayed on the left, or made into a configuration item, the user can customize

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#5817]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
DatePicker  日期范围选择 预设常用日期范围，目前看是在下面显示，是否可以在左边显示，或者做成配置项，用户可以自定义
![image](https://user-images.githubusercontent.com/5828057/179398398-50add239-c7cf-4b70-a6f8-f638828387d9.png)
![image](https://user-images.githubusercontent.com/5828057/179398425-1b3582dd-cf89-438a-9a19-b964d5d9199a.png)

### What does the proposed API look like?
DatePicker  日期范围选择 预设常用日期范围，目前看是在下面显示，是否可以在左边显示，或者做成配置项，用户可以自定义

**Comment by tangjinzhou** [comment]
不能

**Comment by wsxe9988** [comment]
ant design 计划在5.x时进行支持，并说放在下面确实不如放在侧边好，
https://github.com/ant-design/ant-design/issues/36860
期望ant design支持后，咱们也能支持
