### ISSUE TITLE
May I ask how the default sorting field of the table interacts with the back-end, if it cannot interact with the back-end, is it a bit of a base class (basic data will interact with the back-end instead of being hard-coded)

### ISSUE THREAD

**Issue by zxiaozhou** [vueComponent/ant-design-vue#5826]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
支持设置了默认排序字段的列生效并且能与后端交互，即第一次查询数据时就应该能获取到，同时表头也标明当前字段的排序状态

### What does the proposed API look like?
目前无，但是element vue是支持设置默认排序并且能与后端交互的(第一次请求数据时)

**Comment by tangjinzhou** [comment]
仔细看文档吧
