### ISSUE TITLE
Controlled filtering and sorting of document table components

### ISSUE THREAD

**Issue by slackerRen** [vueComponent/ant-design-vue#5827]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
Win10，谷歌浏览器103.0.5060.114

### Reproduction link
[https://2x.antdv.com/components/table-cn#components-table-demo-reset-filter](https://2x.antdv.com/components/table-cn#components-table-demo-reset-filter)

### Steps to reproduce
点击name的筛选列表，然后选择joe，点击确定，然后点击Clear filters的按钮（清空），再次点击筛选列表，选择jim，会发现joe和jim都勾选了

### What is expected?
期望点击Clear filters的按钮，会将筛选列表真正清空

### What is actually happening?
实际：还是保留上一次的筛选选项

**Comment by slackerRen** [comment]
这个是官方文档就稳定复现的问题

**Comment by tangjinzhou** [comment]
升级 3.x，2.x不建议使用了
