### ISSUE TITLE
Date picker exception 3.2.0+

### ISSUE THREAD

**Issue by wmdsj-z** [vueComponent/ant-design-vue#5828]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
谷歌最新版

### Reproduction link
[https://www.antdv.com/components/date-picker-cn](https://www.antdv.com/components/date-picker-cn)

### Steps to reproduce
vite-vue3 ts 打包后 点击日期选择器

### What is expected?
打开选择器面板选中日期

### What is actually happening?
面板未打开

**Comment by tangjinzhou** [comment]
应该是引入了两份 Vue 或者 dayjs ，看下依赖吧

**Comment by wmdsj-z** [comment]
打包以后用不了本地没问题

**Comment by wmdsj-z** [comment]
> 应该是引入了两份vue或者dayjs，看下依赖吧

打包以后用不了, 本地没问题

**Comment by wmdsj-z** [comment]
> 应该是引入了两份vue或者dayjs，看下吧

我今天把组件版本更新了没问题了
