### ISSUE TITLE
Editable table unit, when inputting content with Sogou Chinese input method, use the mouse to select the content, the text will disappear after a few seconds of input.

### ISSUE THREAD

**Issue by yxy3511** [vueComponent/ant-design-vue#5829]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
macOS Mojava 10.14.5/google chrome 版本 102.0.5005.61/vue 3.2.13

### Reproduction link
[https://www.antdv.com/components/table-cn](https://www.antdv.com/components/table-cn)

### Steps to reproduce
1.定位到页面“可编辑单元格”示例处
2.点击"Add"按钮
3.编辑新增数据的"name"
4.使用输入法打出中文内容，不用空格选择，使用鼠标选中想要的内容
5.内容出现在input中，几秒后内容消失

### What is expected?
选中的内容出现在input中，不消失

### What is actually happening?
选中的内容出现在input中，几秒后消失

**Comment by tangjinzhou** [comment]
pressEnter 改成 change

**Comment by yxy3511** [comment]
> pressEnter 改成 change

刚刚又去官网试了试，好像和这个方法名没关系。鼠标选择时需要在选项上悬浮几秒，当拼音出现在输入框后再点击选中，就可以正常显示了。
