### ISSUE TITLE
Table  设置宽度不起作用 

### ISSUE THREAD

**Issue by DawnL6** [vueComponent/ant-design-vue#583]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
vue 版本2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4158nmwjo)

### Steps to reproduce
重现步骤见 连接https://codesandbox.io/s/r4158nmwjo

### What is expected?
希望宽度有用或者我的不能正常工作的原因

### What is actually happening?
https://codesandbox.io/s/r4158nmwjo

**Comment by sendya** [comment]
可以使用  `Tooltip` 组件来解决英文单词过长无法分词的的问题，而且这样不破坏整体布局

![54026726-d643ff80-41d9-11e9-8ce5-8bd132878997](https://user-images.githubusercontent.com/5404542/54355449-169cf500-4694-11e9-95e7-0d0f30450ab4.png)
