### ISSUE TITLE
Use ColumnGroup child tableColumn default sorting invalid

### ISSUE THREAD

**Issue by 12Park** [vueComponent/ant-design-vue#5831]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
win10,win11,chrome99.0.4844.51,vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-1s2nc4?file=/src/App.vue)

### Steps to reproduce
使用ColumnGroup在tableColumn表头上排序失效（只能升序或降序）

### What is expected?
使用ColumnGroup嵌套tableColumn，期望获取正确的sorter排序order

### What is actually happening?
实际只能获取到固定的升序或降序值，不会随着点击排序符号改变

**Comment by tangjinzhou** [comment]
请正确填写版本

**Comment by 12Park** [comment]
> 
"vue": "^3.2.13",
"ant-design-vue": "^2.2.8",

**Comment by 12Park** [comment]
> 请正确填写版本

"vue": "^3.2.13",
"ant-design-vue": "^2.2.8",

**Comment by 12Park** [comment]
需要加key属性

**Comment by MohitDeshwal** [comment]
@12Park which key? for the columns for the rows? either not working for me.

**Comment by 12Park** [comment]
> @12Park which key? for the columns for the rows? either not working for me.

set column's key ,
eg:
const columns = [{
            title: 'Block',
            children: [
              {
                title: 'Building',
                dataIndex: 'building',
                key: 'building',
                width: 100,
              },
              {
                title: 'Door No.',
                dataIndex: 'number',
                key: 'number',
                width: 100,
              },
            ],
          }]
