### ISSUE TITLE
Official website https://codesandbox.io/s/wtsnvk demo The actual effect cannot be achieved

### ISSUE THREAD

**Issue by shenghui-shan** [vueComponent/ant-design-vue#5833]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
vue3

### Reproduction link
[https://www.antdv.com/docs/vue/customize-theme-cn](https://www.antdv.com/docs/vue/customize-theme-cn)

### Steps to reproduce
官网 https://codesandbox.io/s/wtsnvk   demo实际效果实现不了

### What is expected?
官网 https://codesandbox.io/s/wtsnvk   demo实际效果实现不了

### What is actually happening?
官网 https://codesandbox.io/s/wtsnvk   demo实际效果实现不了

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/customize-theme-variable-cn
