### ISSUE TITLE
a-input-number When 2 decimal places are reserved, the input 555.555 is not rounded, and the result is 555.55

### ISSUE THREAD

**Issue by SilentLand** [vueComponent/ant-design-vue#5837]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
window,"Google Chrome";v="103"，"vue": "^2.6.11"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-ygsgt3?file=/src/App.vue)

### Steps to reproduce
a-input-number 数字输入框精度为2，输入555.555，结果为555.55

### What is expected?
a-input-number 数字输入框精度为2，输入555.555，结果为555.56

### What is actually happening?
a-input-number 数字输入框精度为2，输入555.555，结果为555.55

**Comment by SilentLand** [comment]
Version
1.7.8有同样的问题，其他版本还未尝试

**Comment by tangjinzhou** [comment]
1.x 不再更新，请使用 3.x
