### ISSUE TITLE
表格多行数据时,按钮触发打开抽屉时卡顿

### ISSUE THREAD

**Issue by TigerGxl** [vueComponent/ant-design-vue#584]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
MacOS10.14.3   Chrome72   Vue2.6.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/TigerGxl/sally/)

### Steps to reproduce
https://github.com/TigerGxl/sally/blob/master/src/views/EventPush.vue
渲染表格和打开抽屉的代码都在这个组件里,重现链接里可以查看执行情况

### What is expected?
在表格只有单行数据时和官方教程的效果几乎一样,流畅滑进滑出,并且多行数据应当相同

### What is actually happening?
当表格中只有一行数据时,抽屉滑进滑出的效果流畅,当行数超过一行开始明显抽屉滑动的效果明显开始变卡顿,在表格行数持续增加时,卡顿也越明显

---
<a-drawer>的代码完全来自于官方教程,只是增加了 table 并多赋值了几行数据,并且触发滑动抽屉的按钮每一行都存在,但是抽屉滑动效果明显卡顿,先前在 vue2.5的时候是这样,接着升级到2.6还是这样,降级卡顿的方法①减少表格行数,②减少抽屉渲染的内容,本身没有任何的业务交互,只是有 created 中请求接口获取要渲染表格的数据

**Comment by tangjinzhou** [comment]
1. 你这个codesandbox 运行出错啊 
2. 我大概看了下你代码，你这个是点击按钮的时候同时开了N个抽屉哎  你应该把抽屉代码放在table外面吧

**Comment by TigerGxl** [comment]
抱歉codesandbox运行错误,并且花时间review 指出错误
哈,谢谢大佬的指点,野路子出身,没有太注意这方面,已经修正,谢谢
