### ISSUE TITLE
Failed to upload file

### ISSUE THREAD

**Issue by missqingqing** [vueComponent/ant-design-vue#5844]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
1.7.8

### Reproduction link
[https://1x.antdv.com/components/upload-cn/](https://1x.antdv.com/components/upload-cn/)

### Steps to reproduce
点击上传没有触发 包括文档一样

### What is expected?
能点击上传

### What is actually happening?
点击无效

---
上传图片的时候 点击无效 在官网也是一样的

**Comment by tangjinzhou** [comment]
文档用的第三方限量免费后端接口，超量后会上传失败
