### ISSUE TITLE
Whether the upload component can support the function of opening albums on mobile phones

### ISSUE THREAD

**Issue by cff-github** [vueComponent/ant-design-vue#5857]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
upload 组件是否可以支持手机上打开相册功能

### What does the proposed API look like?
upload 组件是否可以支持手机上打开相册功能

**Comment by cff-github** [comment]
![image](https://user-images.githubusercontent.com/69131256/181714069-16b2855d-a209-499a-93a6-121bf7846c66.png)

**Comment by tangjinzhou** [comment]
set `:capture="null"`

**Comment by TwT-L** [comment]
> set `:capture="null"`

记得修改一下文档哦
[上传upload - Ant Design Vue](https://antdv.com/components/upload-cn#%E6%89%8B%E6%9C%BA%E8%AE%BE%E5%A4%87%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E7%9B%B8%E5%86%8C%E6%88%96%E6%96%87%E4%BB%B6%E5%A4%B9%EF%BC%9F)
