### ISSUE TITLE
DatePicker 组件在readOnly为true时，依然可选

### ISSUE THREAD

**Issue by linziguan** [vueComponent/ant-design-vue#586]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
win10,chrome69,vue2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk71684174?fontsize=14)

### Steps to reproduce
1、给DatePicker 组件，设置readOnly为true
2、正常是只显示值，而不能选择的
3、但实际结果是还是可选

### What is expected?
设为readOnly为true时，不可选。估计其它组件也有类似的需求。可以参考Input组件。

### What is actually happening?
可选

---
估计其它组件也有类似的需求。可以参考Input组件。

**Comment by tangjinzhou** [comment]
DatePicker 没有提供 readOnly API 啊
你可以使用 disabled

**Comment by linziguan** [comment]
readOnly 跟 disabled还是有区别的，建议提供

**Comment by linziguan** [comment]
`http://www.nowamagic.net/html/html_ReadonlyAndDisabled.php`

**Comment by tangjinzhou** [comment]
> `http://www.nowamagic.net/html/html_ReadonlyAndDisabled.php`

看你这个文章说的很清楚，readOnly只对输入框生效，对选择性的并不适用，所以 DatePicker 没有必要提供这个功能吧

**Comment by linziguan** [comment]
即然是一个富体验的UI框架，建议从最本质的设计去考虑一下。

**Comment by Luooooooo** [comment]
input 也没有readonly，建议提供

**Comment by nongzhenli** [comment]
是啊，为什么a-input a-inpuit-number 也不提供呢。

**Comment by 531431988** [comment]
是啊，为什么a-input a-inpuit-number 也不提供呢。
