### ISSUE TITLE
when I use ATree, set prop 'fieldName' to change the field (such as "key": "id"), the selectedKeys is not change at the same time

### ISSUE THREAD

**Issue by JiatLn** [vueComponent/ant-design-vue#5861]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
chrome vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/snowy-firefly-47ttgc?file=/src/App.vue)

### Steps to reproduce
i use the config follow, to set the key is id, but when i click the tree node, the selectedKeys is not change at the same time

`:field-name="{ children: 'children', title: 'name', key: 'id' }"`

### What is expected?
the selectedKeys is ['123']

### What is actually happening?
the selectedKeys is [ "0-0" ]

**Comment by tangjinzhou** [comment]
`:field-names`   not  `:field-name`
