### ISSUE TITLE
Unable to use v-show command on dropdown's menu-item node

### ISSUE THREAD

**Issue by Hccake** [vueComponent/ant-design-vue#5862]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
Windows, Chrome, Vue 3.2.33

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dropdown-v-show-unft0t?file=/src/App.vue)

### Steps to reproduce
dropdown 的  a-menu-item 中添加 v-show 指令即可复现

### What is expected?
可以在 dropdown 中正常使用 v-show 指令

### What is actually happening?
```js
runtime-core.esm-bundler.js:38 [Vue warn]: Runtime directive used on component with non-element root node. The directives will not function as intended.
at <Trigger popupClassName="ant-dropdown-menu-inline-collapsed-tooltip" prefixCls="ant-tooltip" action="hover"  ... >
at <Tooltip title=null overlayClassName="ant-dropdown-menu-inline-collapsed-tooltip" trigger="hover"  ... >
at <ATooltip title=null visible=false placement="right"  ... >
at <AMenuItem>
at <OverflowContextProvider key=0 value= {prefixCls: 'ant-dropdown-menu-overflow-item', responsive: false, component: {…}, invalidate: true, order: 0, …} >
```
控制台有 warning 警告，v-show 无效

**Comment by tangjinzhou** [comment]
用  v-if 
a-menu-item 不是唯一根节点

**Comment by Hccake** [comment]
> 用 v-if a-menu-item 不是唯一根节点

在menu 中 a-menu-item  是可以使用 v-show 指令的，但是在 dropdown 中无法使用

**Comment by coolxiaohao** [comment]
一样的问题，请问楼主解决了吗

**Comment by coolxiaohao** [comment]
不过我不是v-show我是自定义了一个指令用于按钮权限控制
