### ISSUE TITLE
There is also a problem with the dialog level problem after vite is packaged and the date picker cannot be selected after packaging. There are also problems with pop-up

### ISSUE THREAD

**Issue by zengyuanqiu** [vueComponent/ant-design-vue#5868]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.10

### Environment
windows11、edge、vue3

### Reproduction link
[https://zengyuanqiu.github.io/antd-bug/](https://zengyuanqiu.github.io/antd-bug/)

### Steps to reproduce
使用 vite build --mode test 打包后 使用 npm run preview 预览页面，导致 a-date-picker 组件选择日期无效

### What is expected?
期望正常使用

### What is actually happening?
无法回显到日期组件中的输入框

---
#5824 已经提出过此bug，显示无效。弹窗问题也有遇到过。

**Comment by tangjinzhou** [comment]
建议不要用  mode  test  ，这个一般是给单测用的   换个名字？
