### ISSUE TITLE
ipad using dropdown to trigger using contextmenu mode will trigger browser default behavior

### ISSUE THREAD

**Issue by MTCherish** [vueComponent/ant-design-vue#5869]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
vue ipad

### Reproduction link
[https://antdv.com/components/dropdown-cn](https://antdv.com/components/dropdown-cn)

### Steps to reproduce

<template>
<div class="container-box ">
<a-dropdown
:trigger="['contextmenu']">
<div
:style="{
textAlign: 'center',
background: '#f7f7f7',
height: '200px',
lineHeight: '200px',
color: '#777',
}">
click
</div>
<template #overlay>
<a-menu>
<a-menu-item key="1">
1st menu item
</a-menu-item>
</a-menu>
</template>
</a-dropdown>
</div>
</template>
<script lang="ts">

### What is expected?
不出现浏览器默认行为

### What is actually happening?
ipad 上长按 出现了默认行为

**Comment by tangjinzhou** [comment]
是什么
来个录屏 ？
