### ISSUE TITLE
How can I not open the 1.x document. we are still using

### ISSUE THREAD

**Issue by guagezuishuai** [vueComponent/ant-design-vue#5875]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
1.7.2

### Reproduction link
[https://1x.antdv.com/docs/vue/migration-v3-cn](https://1x.antdv.com/docs/vue/migration-v3-cn)

### Steps to reproduce
在线文档地址打不开了

### What is expected?
在线文档地址打不开了

### What is actually happening?
在线文档地址打不开了

**Comment by kekekezi** [comment]
同

**Comment by 850036165** [comment]
same problem

**Comment by caomingdong** [comment]
同

**Comment by tangjinzhou** [comment]
可以了吧   证书过期了 ，已经可以了
