### ISSUE TITLE
ant-design-vue v3 dor CN

### ISSUE THREAD

**Issue by RSS1102** [vueComponent/ant-design-vue#5876]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
win10 Chrome100 

### Reproduction link
[https://antdv.com/components/overview-cn](https://antdv.com/components/overview-cn)

### Steps to reproduce
进入 v3中文版无法正常访问

### What is expected?
正常访问

### What is actually happening?
发生错误
![image](https://user-images.githubusercontent.com/81673017/183324960-53f4f87d-2402-4733-befd-b2883b921c75.png)

**Comment by valcosmos** [comment]
same problem.

![image](https://user-images.githubusercontent.com/53572196/183325178-d8ceca96-4beb-4e1f-82c6-187497dc65fe.png)

**Comment by RSS1102** [comment]
> 同样的问题。
> 
> ![图片](https://user-images.githubusercontent.com/53572196/183325178-d8ceca96-4beb-4e1f-82c6-187497dc65fe.png)

now  we can used https://antdv.com/components/form  to access.
