### ISSUE TITLE
Nuxt 3 Support

### ISSUE THREAD

**Issue by kasvith** [vueComponent/ant-design-vue#5881]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Ant Design Vue doesn't register components with Nuxt3. It would be cool to create a nuxt module which does this

### What does the proposed API look like?
Will need a new repo to be listed on modules.nuxt.org

**Comment by Aurion72** [comment]
Any news from this ?

**Comment by fskarmeta** [comment]
Yes please :D

**Comment by gsabater** [comment]
today launched nuxt 3 officially and a lot of people will want this.

**Comment by NarHakobyan** [comment]
+1

**Comment by artavdalyan** [comment]
+1

**Comment by UsVfxArtia** [comment]
sad, still no options?

**Comment by BillEliot** [comment]
有最新的方案了吗？nuxt3使用ant design vue 4？如何不再报 document is not defined 错误
