### ISSUE TITLE
When ant-v6 registers antdv components, settings such as config-provider prefixCls are invalid

### ISSUE THREAD

**Issue by oushu1tanqiang1** [vueComponent/ant-design-vue#5886]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
Mac 12.3.1, Chrome lastest, Vue lastest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-shape-8ciig?file=/package.json:0-2)

### Steps to reproduce
ant v6 画布注册Antd Vue Btn 组件节点，新建画布，添加Btn组件节点

### What is expected?
Antdv Btn 正常工作，样式正常

### What is actually happening?
样式丢失，因为该Btn ant-prefix class 未受 config provider 影响

---
最小仓库复现链接目前是假的，我待会再上一个

**Comment by oushu1tanqiang1** [comment]
![image](https://user-images.githubusercontent.com/87287753/183893652-7674246d-4499-4df2-a235-20e95be90831.png)

**Comment by oushu1tanqiang1** [comment]
上面的复现链接中，Vue升级成 3，引入Antdv，配置ConfigProvider，能够复现

稍等我弄一个现成的

**Comment by tangjinzhou** [comment]
你这复现不对啊

**Comment by oushu1tanqiang1** [comment]
@tangjinzhou 不好意思，这个问题不存在，是我学艺不精，打扰你了。

Ant X6注册的 Vue 节点，实际在添加（使用）时，内部是新建了一个 Vue 对象，每个节点都会新建一个，和项目的 Vue 对象完全独立，所以 ConfigProvider 不会起作用，任何注册在项目里的 component 在 X6 的节点里自然也是不可用，这是正常情况。

再次抱歉，打扰你了！
