### ISSUE TITLE
render function using in notification cannot get provided variables

### ISSUE THREAD

**Issue by Kijin-Seija** [vueComponent/ant-design-vue#5895]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
vue:3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-dong-guan-bi-de-yan-shi-ant-design-vue-3-2-11-forked-uhznon?file=/src/demo.vue)

### Steps to reproduce
click "open the notification box"
点击 "open the notification box"

### What is expected?
The title of the notification is "render text is: hello world!"(same as the text under the button)
显示的通知标题为"render text is: hello world!"(和按钮下方的文本一致)

### What is actually happening?
The title of the notification is "render text is:"
显示的通知标题为"render text is:"

![image](https://user-images.githubusercontent.com/27846243/184811232-d18c8596-6d87-4f84-a4ff-444a352d0a53.png)

**Comment by oushu1wanjie1** [comment]
猜测应该是Notifacation里渲染的组件不属于当前组件的后代，所以无法获取当前组件的provide
