### ISSUE TITLE
Does the a-table component support dragging rows?

### ISSUE THREAD

**Issue by yeyuliang2015** [vueComponent/ant-design-vue#5897]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
请问a-table组件支持拖动行么？

### What does the proposed API look like?
请问a-table组件支持拖动行么？

**Comment by yeyuliang2015** [comment]
请问a-table组件支持拖动行么？

**Comment by tangjinzhou** [comment]
不支持
s-table 支持  https://surely.cool/doc/dragable#drag-row
