### ISSUE TITLE
After the date component selects a date, clicks the year and month, and clicks OK without clicking the day. The selected value will not change, then the valueFormat will be invalid, resulting in inconsistent value patterns.

### ISSUE THREAD

**Issue by atom-git** [vueComponent/ant-design-vue#5906]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
ant design vue 3.2.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ri-qi-ge-shi-ant-design-vue-3-2-11-forked-l4edk1?file=/src/demo.vue)

### Steps to reproduce
1.选择一个日期
2.点击年月随意改变值，选择的结果不变，也不会触发change事件
3.此时valueFormat并未生效，双绑的值会自动变成dayjs类型

### What is expected?
在点击年、月进行时间改变时，触发change事件，并变改显示框值，且value经过valueFormat格式化

### What is actually happening?
仅点击月份或者年份的改变，不会触发change事件，且valueFormat对于双绑的值失效

**Comment by tangjinzhou** [comment]
仅点击月份或者年份，之后直接确定？
这样就是没有变化的，你切换月份后，日期面板并没有选中项啊，所以日期还是之前的值

**Comment by atom-git** [comment]
> 仅点击月份或者年份，之后直接确定？ 这样就是没有变化的，你切换月份后，日期面板并没有选中项啊，所以日期还是之前的值
这里的问题是绑定一个值是字符串类型，但是通过上述的操作实际并未对值做出改变，再次获取绑定值的时候变成了dayjs对象，配置的valueFormat未生效
