### ISSUE TITLE
[Need help] Can the official provide some documents on the best way to introduce Antdv3.0 through CDN

### ISSUE THREAD

**Issue by windylaugit** [vueComponent/ant-design-vue#5909]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
期望官方能在文档或github中直接提供一些文档或示例，用于介绍如何使用CDN的方式引入AntDesignVue3.0，以及一些基本的注意事项(例如dayjs的引入等)。
虽然网上也能零星找到一些私人开发者发布的相关资料，但总是不全面、权威，对于期望在全新项目中使用全新版本AntDesignVue的开发者来说，总是不大友好。
目前期望的示例能提供的使用组合： AntDesignVue3.x   Vue3.0   Vite
不胜感激！

### What does the proposed API look like?
# antdv cdn links
JS: https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.11/dist/antd.min.js
CSS: https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.11/dist/antd.min.css

# vite.config.js
defineConfig({
build: {
// ...
rollupOptions: {
// 确保外部化处理那些你不想打包进库的依赖
external: ['antd'],
output: {
globals: {
antd: 'antd'
}
}
}
}
})

**Comment by SKT1yang** [comment]
为啥关了啊，antd vue的打包和less部分都很慢，cdn是一个很好的办法

**Comment by windylaugit** [comment]
> 为啥关了啊，antd vue的打包和less部分都很慢，cdn是一个很好的办法

tang added tags:  enhancement、docs.  wait for update...
