### ISSUE TITLE
Has [ant-design-icons](https://github.com/ant-design/ant-design-icons/issues) stopped maintenance

### ISSUE THREAD

**Issue by merfais** [vueComponent/ant-design-vue#5911]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
这么多 issues <[ant-design-icons issues](https://github.com/ant-design/ant-design-icons/issues) >和 PR <
[ant-design-icons PR](https://github.com/vueComponent/ant-design-vue/pulls) >
没人管理，作为 [ Ant Design Vue](https://antdv.com/components/icon-cn) 官方推荐的的icons库，此项目是要被废弃吗？
距离最后一次更新，已经过去了5个月

![image](https://user-images.githubusercontent.com/18030318/185773097-cb2ca978-ebbb-4900-bc7b-21b90854e768.png)

### What does the proposed API look like?
none

**Comment by tangjinzhou** [comment]
欢迎 PR
