### ISSUE TITLE
Modal.method() cancelText does not take effect

### ISSUE THREAD

**Issue by donghero** [vueComponent/ant-design-vue#5912]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.6

### Environment
Vue version: ^3.2.25

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bitter-http-rnzprr?file=/src/App.vue:297-302)

### Steps to reproduce
1. when I add the cancelText API to Modal.method() Object

### What is expected?
I just want to show this cancelText="取消"

### What is actually happening?
**取消按钮并不显示**

**Comment by tangjinzhou** [comment]
不是所有 method 都有 cancel 的，confirm 才有

**Comment by donghero** [comment]
@tangjinzhou 
![image](https://user-images.githubusercontent.com/43608856/186567150-dc6be7d6-7987-47e2-9a7e-6a4534804747.png)
Thanks your comment
