### ISSUE TITLE
support ie ie9 ie compatibility issues

### ISSUE THREAD

**Issue by SilentFlute** [vueComponent/ant-design-vue#5914]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
- chrome: 版本 104.0.5112.102（正式版本） （64 位）
- node: v16.17.0
- yarn: 1.22.18
- create-vue: @2
- vue: 2.7.7
- antdv: 1.7.8
- vite: 3.0.2

### Reproduction link
[https://github.com/SilentFlute/antdv-ie](https://github.com/SilentFlute/antdv-ie)

### Steps to reproduce
1. yarn
2. yarn dev

### What is expected?
在ie9 ie10 ie11上能顺利运行

### What is actually happening?
ie11打开页面空白

---
这边需要做一个pc项目, 兼容`ie9 `, 多方查找之后发现`antdv1`符合需求, 而`antdv1`要和`vue2`来用, 于是我就着手安装`vue2`

由于[vue-cli](https://github.com/vuejs/vue-cli)文档中推荐使用[create-vue](https://github.com/vuejs/create-vue)来生成项目, 即使是`vue2`, 因此我使用了`create-vue@2`来生成项目, 以及目前生成的`vue`的项目都是基于[vite](https://cn.vitejs.dev/)的

看了[antdv1_兼容性](https://1x.antdv.com/docs/vue/getting-started-cn/#%E5%85%BC%E5%AE%B9%E6%80%A7)文档之后发现要用`babel`, 但多方尝试之后依旧没头绪, 遂来`issue`区求助

在这之前使用了`vite-plugin-imp`来做按需引入(这个是没问题的), 以及尝试了[awesome-vite](https://github.com/vitejs/awesome-vite#plugins)中的`vite-plugin-babel`但依旧不行, `ie11`都不行, 打开白屏, 希望能帮忙看一下, 感谢

以及我发现`index.html`文件中有`type="module"`的`script`, 既然`vue2`能兼容`ie`, 那有这个属性在, 必然是没法在`ie`上运行的, 这是为何啊?

**Comment by SilentFlute** [comment]
@tangjinzhou 大佬, 求支援~ 我这边`issue` `ie`相关的都看完了, 但实在是没找到如何配置, 因此才来提`issue`, 希望大佬能帮忙看看, 感谢~

**Comment by sendya** [comment]
建议用 vue-cli 老的版本基于 webpack 的实现

**Comment by SilentFlute** [comment]
@sendya 感谢回复, 我最后完成了兼容`ie9+`的需求, 这里顺带记录一下, 以便后面的朋友参考

我研究了下`vue-cli`生成`vue2.x`项目, 目前`vue-cli`最新版是`5.0.8`, 这个版本使用的`babel`和[vue-cli文档](https://cli.vuejs.org/zh/index.html)中提到的不一样, 个人能力有限, 多方查找之后并没找到`5.0.8`版本生成的`vue2.x`项目的兼容配置, 于是装了`vue-cli@4.x`, 但也和`vue-cli@5.0.8`一样, 最后我装了`vue-cli@3.x`: `$ yarn global add @vue/cli@3`, 得到的版本是`3.12.1`, 这个版本所做的配置就和文档中一致了, 然后就配置好了, 这里也贴一下各相关文件:

`babel.config.js`:
```js
module.exports = {
  presets: [
    ["@vue/app", {
      useBuiltIns: "entry"
    }]
  ],
  plugins: [
    ["import", {
      libraryName: "ant-design-vue",
      libraryDirectory: "es",
      style: "css"
    }]
  ]
}
```

`package.json`:
```js
{
  "name": "hello-world",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "ant-design-vue": "^1.7.8",
    "core-js": "^2.6.5",
    "vue": "^2.6.10"
  },
  "devDependencies": {
    "@babel/polyfill": "^7.12.1",
    "@vue/cli-plugin-babel": "^3.12.0",
    "@vue/cli-plugin-eslint": "^3.12.0",
    "@vue/cli-service": "^3.12.0",
    "babel-eslint": "^10.0.1",
    "babel-plugin-import": "^1.13.5",
    "eslint": "^5.16.0",
    "eslint-plugin-vue": "^5.0.0",
    "vue-template-compiler": "^2.6.10"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/essential",
      "eslint:recommended"
    ],
    "rules": {},
    "parserOptions": {
      "parser": "babel-eslint"
    }
  },
  "postcss": {
    "plugins": {
      "autoprefixer": {}
    }
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <=8"
  ]
}
```

`vue.config.js`:
```js
module.exports = {
  transpileDependencies: ['*'],
  configureWebpack: {
      entry: ['@babel/polyfill', './src/main.js']
  }
}
```

然后从[Form表单](https://1x.antdv.com/components/form-cn/)中复制第一个基础用法进去之后是可以使用的, `ie9+`都行

只是`ie9+`运行时会有这个错, 个人推测是`hmr`使用了`websocket`, 然后`ie`对这个有自己的一些限制吧, 所以报错了, 但不影响:

![image](https://user-images.githubusercontent.com/28900312/186383002-1baeafb3-76f1-4d3b-ae48-31ef318c8e3a.png)
