### ISSUE TITLE
antd.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'extend')

### ISSUE THREAD

**Issue by zyqwks** [vueComponent/ant-design-vue#5919]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
win11、Chrome 浏览器 版本 104.0.5112.102（正式版本） （64 位）、vue3.2.7
Win11, Chrome browser version 104.0.5112.102 (official version) (64 bit), vue3.2.7

### Reproduction link
[http://bug.nswlp.cn/](http://bug.nswlp.cn/)

### Steps to reproduce
打开网址，按f12，在console中即可看到，如果没有，请重新刷新
Open the web address, press F12, and you can see it in the console. If not, please refresh it again

### What is expected?
解决报错
Resolve error reporting

### What is actually happening?
解决报错
Resolve error reporting

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5
