### ISSUE TITLE
icon cannot be displayed dynamically

### ISSUE THREAD

**Issue by cxx-iloveyou** [vueComponent/ant-design-vue#5921]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.0

### Environment
win10\谷歌\vue3

### Reproduction link
[https://www.antdv.com/components/overview-cn/](https://www.antdv.com/components/overview-cn/)

### Steps to reproduce
用一个对象数组去渲染图标

### What is expected?
期望可以动态渲染图标

### What is actually happening?
实际只能通过全局化图标组件才能动态使用

---
请多考虑些开发实际场景

**Comment by EnochGao** [comment]
ng中的图标是直接传图标名就加载，发现vue中每一个图标是一个组件，业务系统的菜单是配置出来的，里面有icon，这种vue中怎么根据icon名动态加载
