### ISSUE TITLE
After textarea sets autoSize, the cursor will move to the end of continuous input of text.

### ISSUE THREAD

**Issue by qpxtWhite** [vueComponent/ant-design-vue#5922]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
win10\chrome\vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sjt8or)

### Steps to reproduce
1、a-textarea设定 :auto-size="{ minRows: 2, maxRows: 5 }"
2、在输入框中将光标定位到文案中间
3、连续快速的输入中文
![a](https://user-images.githubusercontent.com/4169498/186842258-f4ab1236-1a1c-4473-b9e9-8393ee6a01dd.gif)

### What is expected?
正常在文案中间插入字符

### What is actually happening?
光标会移动到最后，导致输入位置错误

**Comment by tangjinzhou** [comment]
mac 搜狗没有复现

**Comment by qpxtWhite** [comment]
Add one console line here:
![image](https://user-images.githubusercontent.com/4169498/188078049-b9a333f0-1858-429c-9732-e376f53031b9.png)

And get the following result:
![a](https://user-images.githubusercontent.com/4169498/188078629-c59dae36-c5fb-415e-a38e-1aed9e8bdff2.gif)
currentStart suddenly jump to 111

I dont know why

**Comment by hymsnow** [comment]
我也出现了和你一模一样的问题，我的操作方式是这样的：比如同时不停的按 B（或者其他字母也行）+空格键

![QQ截图20220922100309](https://user-images.githubusercontent.com/16634708/191643335-17b54963-c6bf-4a8f-a992-c91b810ac0ce.png)
后面我发现导致此原因主要是 因为加了   :autosize="{ minRows: 4, maxRows: 20 }" 这句，去掉后就不会出现

**Comment by qpxtWhite** [comment]
在ResizableTextArea.tsx文件中，会根据resizeStatus设置overflow属性；
经过一番调试，发现去掉这个overflow样式变化之后，不会再出现这个光标乱跳的问题，如截图这段代码：
![image](https://user-images.githubusercontent.com/4169498/193461713-95ffcd52-5508-41fe-8199-5a5612e65943.png)
我不确定这个overflow属性是用来干嘛的，能不能去掉，去掉会不会影响其他功能；
我在项目里复制了一份textarea组件，去掉了红框中的代码，暂时跑着没问题
