### ISSUE TITLE
It is found that the icon components in icons-vue are not compatible with vitest

### ISSUE THREAD

**Issue by tu6ge** [vueComponent/ant-design-vue#5927]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
```Shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 4.35 GB / 15.96 GB
  Binaries:
    Node: 16.13.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.63)
    Internet Explorer: 11.0.19041.1566
```

### Reproduction link
[https://github.com/tu6ge/tauri-publish-app](https://github.com/tu6ge/tauri-publish-app)

### Steps to reproduce
在 vue3 的组件中，引入
import { SettingOutlined, PlusOutlined } from '@ant-design/icons-vue'

然后将组件使用
import { mount } from '@vue/test-utils'
导入到 vitest 单元测试中，运行单元测试，

可以 clone 上面的重现连接，然后运行 pnpm test
commit sha值为 35b6ca804b2c66780762a00becbf233466e94cc0 在 testcase 分支

测试用例文件为 tests\unit\home.test.js
待测试的组件为 src\views\Home.vue

直接运行可以发现错误所在，如果将 Home.vue 文件 中的 207行和221行注释掉，就没有问题了

### What is expected?
测试过程不报错

### What is actually happening?
TypeError: Failed to execute 'insertBefore' on 'Node': 2 arguments required, but only 1 present.
❯ HTMLElement.insertBefore node_modules/.pnpm/happy-dom@6.0.4/node_modules/happy-dom/lib/nodes/node/Node.js:304:19
❯ HTMLElement.insertBefore node_modules/.pnpm/happy-dom@6.0.4/node_modules/happy-dom/lib/nodes/element/Element.js:331:35
❯ insertCss node_modules/.pnpm/@ant-design icons-vue@6.1.0_vue@3.2.37/node_modules/@ant-design/icons-vue/lib/insert-css.js:46:17
❯ node_modules/.pnpm/@ant-design icons-vue@6.1.0_vue@3.2.37/node_modules/@ant-design/icons-vue/lib/utils.js:110:35

**Comment by tangjinzhou** [comment]
或许你应该给 vitest 提issue

**Comment by tu6ge** [comment]
我发现 icon 相关的组件，标签没有闭合导致的

**Comment by tangjinzhou** [comment]
哪里没有闭合 ？

**Comment by tu6ge** [comment]
只是有这种怀疑，我也不确定了

**Comment by gaokun** [comment]
This issue was caused by `ant-design-icons`, refer to [PR](https://github.com/ant-design/ant-design-icons/pull/540)

@tangjinzhou plz help to review

**Comment by Fallsleep** [comment]
确实，我在用`happy-dom`做测试时会触发这个错误，按照 @gaokun pr里的方式修改后就好了

**Comment by Fallsleep** [comment]
> This issue was caused by `ant-design-icons`, refer to [PR](https://github.com/ant-design/ant-design-icons/pull/540)
> 
> @tangjinzhou plz help to review

@tangjinzhou 请问一下ant-design-icons近期会有修复的计划么
