### ISSUE TITLE
Remove peer dependencies vue-template-compiler

### ISSUE THREAD

**Issue by dongnaebi** [vueComponent/ant-design-vue#5928]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
win11,chrome,vue2.7

### Reproduction link
[https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01](https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01)

### Steps to reproduce
pnpm i

### What is expected?
└─┬ ant-design-vue 1.7.8
├── ✕ missing peer vue-template-compiler@^2.6.0
└─┬ @ant-design/icons-vue 2.0.0
└── ✕ missing peer vue-template-compiler@>=2.5.0
Peer dependencies that should be installed:
vue-template-compiler@">=2.6.0 <3.0.0"

### What is actually happening?
vue 2.7 (https://github.com/vuejs/vue/blob/main/CHANGELOG.md#270-2022-07-01) has no longer need vue-template-compiler, please remove it in peer dependencies
> Upgrade vue to ^2.7.0. You can also remove vue-template-compiler from the dependencies - it is no longer needed in 2.7

**Comment by Ym-haohan** [comment]
我最近升级2.7之后也有这个警告，缺少vue-template-compiler这个依赖会影响antd的正常运行吗？
