### ISSUE TITLE
Table search, sort and editable row

### ISSUE THREAD

**Issue by simoneromano96** [vueComponent/ant-design-vue#593]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
Win10x64/Linux Debian 9 amd64, Chrome 73.0.3683.75/Firefox 65.0.2, Vue 2.6.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0v3x638z3p?fontsize=14)

### Steps to reproduce
* Start by creating a table populating it
* Add sorting and row editing (no problems here)
* Try to add search filter

### What is expected?
Have a working search filter, it doesn't work probably because of the :slot="col" imposed by the editable row while the search filter needs the customRender.

### What is actually happening?
The search either doesn't work or gives a blank table or the editable cells are all wrong (for example you edit the name and the characters are appended to another column)

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/pmlkk43m37
