### ISSUE TITLE
When pagination is set to false in table component (custom pagination), `scrollToFirstRowOnChange` is invalid after page number switch.

### ISSUE THREAD

**Issue by dasoncheng** [vueComponent/ant-design-vue#5930]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.9

### Environment
macOS12.5, Microsoft Edge Version 104.0.1293.70 (Official build) (x86_64), Vue 3.2.13

### Reproduction link
[https://github.com/dasoncheng/antdv-report](https://github.com/dasoncheng/antdv-report)

### Steps to reproduce
scrollToFirstRowOnChange is invalid after page number switch.

### What is expected?
scrollToFirstRowOnChange is invalid after page number switch.

### What is actually happening?
Scroll to the top

**Comment by tangjinzhou** [comment]
scrollToFirstRowOnChange not support custom pagination
