### ISSUE TITLE
a-popconfirm lacks the setVisible method and cannot actively control the display and hide. The ant-design 2.x version has the setVisible property.

### ISSUE THREAD

**Issue by 13250515751** [vueComponent/ant-design-vue#5931]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
window10、谷歌浏览器、vue3

### Reproduction link
[https://www.antdv.com/components/popconfirm-cn#API](https://www.antdv.com/components/popconfirm-cn#API)

### Steps to reproduce
a-popconfirm 缺少setVisible 方法，不能主动控制显示隐藏，ant-design 2.x版本有setVisible 属性。

### What is expected?
ant-design-vue 3.2.11提供a-popconfirm 组件提供setVisible 方法

### What is actually happening?
ant-design-vue 2.2.8 升级到 ant-design-vue 3.2.11 API缺失

**Comment by ajuner** [comment]
直接修改visible就行吧
参考这个：[demo](https://www.antdv.com/components/popconfirm-cn#components-popconfirm-demo-dynamic-trigger)

**Comment by tangjinzhou** [comment]
而且你说的 setVisible 也是 非文档 api 吧，也不是破坏性更新
