### ISSUE TITLE
defaultExpandAllRows The default expansion row does not take effect

### ISSUE THREAD

**Issue by yehoan** [vueComponent/ant-design-vue#5936]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
vue2.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-b0vctd?file=/src/App.vue)

### Steps to reproduce
异步生效

### What is expected?
defaultExpandAllRows  defaultExpandAllRows  在异步获取数据的时候都不生效

### What is actually happening?
defaultExpandAllRows  defaultExpandAllRows  在异步获取数据的时候生效

**Comment by yehoan** [comment]
发现异步获取数据以后 该方法无法生效

**Comment by yehoan** [comment]
defaultExpandAllRows  defaultExpandedRowKeys  都不生效

**Comment by tangjinzhou** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/6937879/188045784-67e3bad7-86fe-49a5-a291-2d0339276f1f.png">

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-defaultOpenKeys-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by Gilbert5210** [comment]
和你描述的不一样，因为并不是动态修改defaultExpandAllRows的值，而是，第一次加载数据的时候，我希望可以自动展开全部，你现在代码实现，远程加载数据的话，怎么都不行

除非你使用v-if，这样也太戳了。
或者你说真正业务场景下，就希望在第一次加载完数据就展开全部的，怎么才可以做到？你或者可以提供一个expandAll？
