### ISSUE TITLE
Introduced in CDN mode, the global variable antd disappears

### ISSUE THREAD

**Issue by feelinglin** [vueComponent/ant-design-vue#5945]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
Ant Design Vue 3.2.11 或 3.2.12

### Environment
MacOS, Chrome, Vue 3.2.38

### Reproduction link
[https://lib.baomitu.com/ant-design-vue/3.2.12/antd-with-locales.js](https://lib.baomitu.com/ant-design-vue/3.2.12/antd-with-locales.js)

### Steps to reproduce
CDN方式引入 https://lib.baomitu.com/ant-design-vue/3.2.12/antd-with-locales.min.js，3.2.10版本具有名为antd的全局变量，3.2.11或者3.2.12起就没有了

### What is expected?
正常使用antd全局变量

### What is actually happening?
antd全局变量丢失

---
3.2.10版本正常，3.2.11、3.2.12丢失

**Comment by feelinglin** [comment]
很奇怪，我引用的地址跟你这个是一样的，但是没有。换回3.2.10，就有了。。。

**Comment by tangjinzhou** [comment]
看看有没有报错，有报错先解决报错
引入 dayjs 相关内容
