### ISSUE TITLE
3.2.12 There is tagRender usage in the Cascader component API, but there is no actual demo, please add

### ISSUE THREAD

**Issue by linfanxxxx** [vueComponent/ant-design-vue#5947]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
补充Cascader的tagRender使用demo

### What does the proposed API look like?
补充demo

**Comment by webvs2** [comment]
#5954 have prepared,Give it a thumbs up if it works,add document instance was added
