### ISSUE TITLE
table component's slot camel-case name lost effect in cdn import style 

### ISSUE THREAD

**Issue by ylyly** [vueComponent/ant-design-vue#5958]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
MacOS:12.4,Chrome: 103.0.5060.114,Vue:3.2.39

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
纯CDN方式全局引入antdv，发现table组件中的v-slot:bodyCell、v-slot:headerCell 方式用起来有问题，只能用template #[myslotvar] myslotvar的值为'bodyCell' 的方式

<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.12/dist/antd.min.css">
</head>
<body>

<div id="app" style="margin: 10px">
<a-divider>直接用 template #bodyCell  operation列无显示</a-divider>
<a-table :columns="columns" :data-source="records" :pagination="false">
<template #bodyCell="{ column }">
<template v-if="column.key === 'operation'">
<a>action</a>
</template>
</template>
</a-table>
<a-divider>用 template #[myslotvar] myslotvar的值为'bodyCell' operation列显示成功</a-divider>
<a-table :columns="columns" :data-source="records" :pagination="false">
<template #[myslotvar]="{ column }">
<template v-if="column.key === 'operation'">
<a>action</a>
</template>
</template>
</a-table>
<a-divider>用 template #bodycell="..." operation列无显示</a-divider>
<a-table :columns="columns" :data-source="records" :pagination="false">
<template #bodycell="{ column }">
<template v-if="column.key === 'operation'">
<a>action</a>
</template>
</template>
</a-table>
<a-divider>用 template #body-cell="..." operation列无显示</a-divider>
<a-table :columns="columns" :data-source="records" :pagination="false">
<template #body-cell="{ column }">
<template v-if="column.key === 'operation'">
<a>action</a>
</template>
</template>
</a-table>
</div>

</body>
<script src="https://unpkg.com/dayjs/dayjs.min.js"></script>
<script src="https://unpkg.com/dayjs/locale/zh-cn.js"></script>
<script src="https://unpkg.com/dayjs/plugin/customParseFormat.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekday.js"></script>
<script src="https://unpkg.com/dayjs/plugin/localeData.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekOfYear.js"></script>
<script src="https://unpkg.com/dayjs/plugin/weekYear.js"></script>
<script src="https://unpkg.com/dayjs/plugin/advancedFormat.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@3.2.39/dist/vue.global.min.js"></script>

<script src="https://cdn.jsdelivr.net/npm/ant-design-vue@3.2.12/dist/antd-with-locales.min.js"></script>

<script>

const columns = [
{ title: 'Full Name', width: 100, dataIndex: 'name', key: 'name'},
{ title: 'Age', width: 100, dataIndex: 'age', key: 'age'},
{ title: 'Address', width: 100, dataIndex: 'address', key: '1' },
{
title: 'Action',
key: 'operation',
width: 100,
},
];

const records = [
{
key: '1',
name: 'John Brown',
age: 32,
address: 'New York Park',
},
{
key: '2',
name: 'Jim Green',
age: 40,
address: 'London Park',
},
];

// vue3的对象
const vue3Composition = {
data() {
return {
myslotvar:'bodyCell',
columns,
records,
}
}
}
const { createApp } = Vue;

const app = createApp(vue3Composition);
app.use(antd);
app.mount("#app");

</script>
</html>

### What is expected?
template #bodyCell="{ column }"起作用

### What is actually happening?
template #bodyCell="{ column }"不起作用，只能采用用动态变量的方式template #[myslotvar]="{ column }"

**Comment by tangjinzhou** [comment]
盲猜你是直接在 html里写组件，在html中是无法区分大小写的，这是vue规范
建议用vue compile
