### ISSUE TITLE
The expandIconColumnIndex property of the v1 and 2 versions table has been removed in the v3 version.

### ISSUE THREAD

**Issue by 13249129236** [vueComponent/ant-design-vue#5959]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
该属性在v3文档没有显示，但是可以正常使用。

### What does the proposed API look like?
希望API文档能重新添加该属性，以免混淆。

**Comment by tangjinzhou** [comment]
expandIconColumnIndex  is deprecated
 Please use `EXPAND_COLUMN` in `columns` directly
