### ISSUE TITLE
dropdown animation and its lag

### ISSUE THREAD

**Issue by yzw2017** [vueComponent/ant-design-vue#5961]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
vue@3.2.38 win10

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
环境是 npm init vue脚手架创建的项目，引入antd ，使用dropdown组件
```javascript
<a-dropdown>
<a @click.prevent>
<a-avatar shape="square">U</a-avatar>
<span>666</span>
</a>
<template #overlay>
<a-menu @click="handleMenuClick">
<a-menu-item key="logout">
<a href="javascript:;">退出</a>
</a-menu-item>
</a-menu>
</template>
</a-dropdown>
```

我怀疑你们开发中有内存泄漏，我在公司window10电脑和在家里mac电脑，开发过程中，过一段时间，hover dropdown显示 menu item 时，动画极其的卡

### What is expected?
动画流畅

### What is actually happening?
显示menu item 时动画极其的卡

**Comment by yzw2017** [comment]
用了ant design vue这库 开发时页面明显感觉到卡顿，就简简单单开发几个页面 登录注册 首页， 谷歌浏览器vue扩展查看vue devtools时，渲染组件都是红色报警的，就是极其的卡，性能不好。希望团队查看一下什么原因，谢谢了。我最喜欢的UI库

**Comment by yzw2017** [comment]
首先我看了自己写得代码很精简，就短短几个登录注册接口 首先我肯定可以排除自己写得代码导致内存泄漏的问题

**Comment by tangjinzhou** [comment]
关闭  vue devtools

**Comment by Kchengz** [comment]
> 关闭 vue devtools

我这边也遇到相同的问题，在关闭 vue devtools之后得到改善，想了解具体是什么原因造成卡顿

**Comment by tangjinzhou** [comment]
vue devtools 会”代理“你的数据，并且会一直记录改写历史，会越来越卡
