### ISSUE TITLE
There is a table in the tabs. When the tabs are switched, the boder on the right side of the table header will not render, nor can it be covered by itself.

### ISSUE THREAD

**Issue by fanrax** [vueComponent/ant-design-vue#5965]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows  浏览器版本chrome 105.0.5195.102  vue2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-wfw4gk?file=/src/App.vue)

### Steps to reproduce
tabs多次切换就能复现该bug

### What is expected?
期望得到解决

### What is actually happening?
实际体验不佳

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-forked-8i9wcx?file=/src/App.vue
