### ISSUE TITLE
Unable to find dark theme in ant-design-vue v1 for vue2.

### ISSUE THREAD

**Issue by abhijeetj100** [vueComponent/ant-design-vue#5967]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Windows 11, Chrome105, Vue2

### Reproduction link
[https://github.com/abhijeetj100/vue-with-ant-design-vue-demo](https://github.com/abhijeetj100/vue-with-ant-design-vue-demo)

### Steps to reproduce
https://github.com/abhijeetj100/vue-with-ant-design-vue-demo

### What is expected?
I want to use dark theme in ant-design-vue v1 with vue2

Also, is it possible to use the latest versions of ant-design-vue with vue2? Like ant-design-vue v2 and v3, is there a way to use them with vue2? I tried adding v3, but then it started giving me warnings related to vue3.

### What is actually happening?
I am unable to use dark theme.

PS: Let me know if this is not the correct place for this question, if so kindly advise me where to ask this.

Thanks

**Comment by tangjinzhou** [comment]
try https://darkreader.org/

**Comment by abhijeetj100** [comment]
@tangjinzhou , that's a chrome extension. And I don't think that can be considered as a solution to what I asked.
I asked whether there is a solution **in ant-design-vue** to enable dark theme in v1.

Also its not practical to ask whomever uses my app to also download a chrome extension for dark theme.

I guess its simply not possible with ant-design-vue v1.

Thanks
