### ISSUE TITLE
A dynamic style section will be generated in the header, and sometimes there will be two identical sections.

### ISSUE THREAD

**Issue by yurizhang** [vueComponent/ant-design-vue#5969]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
vue3.2

### Reproduction link
[https://www.antdv.com/components/icon](https://www.antdv.com/components/icon)

### Steps to reproduce
F12打开调试器
展开header style段

### What is expected?
为什么会产生这个动态的样式？有时会有2段。https://www.antdv.com/components/icon源文件里就能看到，

### What is actually happening?
是ant-design/icons-vue": "^6.0.1", 版本的原因吗？

---

.anticon {
display: inline-block;
color: inherit;
font-style: normal;
line-height: 0;
text-align: center;
text-transform: none;
vertical-align: -0.125em;
text-rendering: optimizeLegibility;
-webkit-font-smoothing: antialiased;
-moz-osx-font-smoothing: grayscale;
}

.anticon > * {
line-height: 1;
}

.anticon svg {
display: inline-block;
}

.anticon::before {
display: none;
}

.anticon .anticon-icon {
display: block;
}

.anticon[tabindex] {
cursor: pointer;
}

.anticon-spin::before,
.anticon-spin {
display: inline-block;
-webkit-animation: loadingCircle 1s infinite linear;
animation: loadingCircle 1s infinite linear;
}

@-webkit-keyframes loadingCircle {
100% {
-webkit-transform: rotate(360deg);
transform: rotate(360deg);
}
}

@keyframes loadingCircle {
100% {
-webkit-transform: rotate(360deg);
transform: rotate(360deg);
}
}

 
![image](https://user-images.githubusercontent.com/20555332/190355548-53aeffaa-b86e-420e-a057-c8a98e794953.png)

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/190355905-91f40403-38b9-4e2c-b8cc-6a65b5c9c5aa.png)
切换路由的时候就会产生2段，内容是一样的;
还好，最多就只出现2段~

**Comment by tangjinzhou** [comment]
按理说只有一段才对，icon 图标动态写入一份

**Comment by yurizhang** [comment]
但是最多也只会写入2段~~蛮奇怪的~
