### ISSUE TITLE
table columns maxWidth minWidth property has no effect

### ISSUE THREAD

**Issue by qingyuun** [vueComponent/ant-design-vue#5971]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
ant-design-vue 3.2.12 vue 3.2.39

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-ant-design-vue-3-2-12-forked-7j1uiz?file=/src/demo.vue)

### Steps to reproduce
table  columns  属性下 存在 maxWidth minWidth 两个属性,但使用后均无效

### What is expected?
table  columns  属性下   maxWidth minWidth  生效

### What is actually happening?
table  columns  属性下 存在 maxWidth minWidth 两个属性,但使用后均无效

---
可直接预览效果  https://7j1uiz.csb.app/
代码:    https://codesandbox.io/s/ke-bian-ji-dan-yuan-ge-ant-design-vue-3-2-12-forked-7j1uiz?file=/src/demo.vue

**Comment by TwinkleSevenStream** [comment]
从文档中的描述来看，table column的maxWidth和minWidth属性为针对**拖动列**的可拖动最大宽度和最小宽度（resizable=true且width设为固定值作为初始宽度）
https://www.antdv.com/components/table-cn#Column
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/21072732/190959307-c2687c33-b9e8-4b68-afde-3b4deb4e05ec.png">

在文档Demo中的[可伸缩列](https://www.antdv.com/components/table-cn#components-table-demo-resizable-column)，就用到了maxWidth和minWidth

**Comment by qingyuun** [comment]
好吧,拖动列 😓
