### ISSUE TITLE
Spin style issue display:none multiple other characters

### ISSUE THREAD

**Issue by airlenet** [vueComponent/ant-design-vue#5974]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
windows, edge/chrome,3.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/main/components/spin/style/index.less](https://github.com/vueComponent/ant-design-vue/blob/main/components/spin/style/index.less)

### Steps to reproduce
ant-design-vue/components/spin/style/index.less

### What is expected?
ant-design-vue/components/spin/style/index.less
89行 非法样式
display: ~'none \9';

### What is actually happening?
prod-layout组件，使用时

导致浏览器无法渲染样式，

**Comment by tangjinzhou** [comment]
和这个应该没关系，你去 prod-layout 那里提 issue

**Comment by airlenet** [comment]
我就很奇怪了，
display: ~'none \9';    这里\9 写法正常吗，

有这种语法吗，为啥要推到其他项目上面，如果没有这种语法，请修复

**Comment by gomorizsolt** [comment]
@tangjinzhou would you mind shedding some light on the reasoning?

```css
display: ~'none \9';
```

`\9` makes no sense to me.
