### ISSUE TITLE
When datepicker sets the mode to year,Selecting the year does not trigger panel-change, and the selector does not automatically close

### ISSUE THREAD

**Issue by Ysh-WEB-GITHUB** [vueComponent/ant-design-vue#5976]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
win10,Google:105.0.5195.102,vue:3.2.20

### Reproduction link
[https://www.antdv.com/components/date-picker-cn#API](https://www.antdv.com/components/date-picker-cn#API)

### Steps to reproduce
//<a-form-item >
//<a-date-picker
//v-model:value="value"
//:disabledDate="disabledDate"
//mode="year"
//format="YYYY"
//valueFormat="YYYY"
//:open="state.isopen"
//@change="onChangeValue"
//@open-change="handYearChange"
//@panel-change="panelYearChange"
///>
//</a-form-item>

### What is expected?
Trigger @panel-change, execute panelYearChange function

### What is actually happening?
not triggered

**Comment by Ysh-WEB-GITHUB** [comment]
这个问题可以解决么,望回复

**Comment by tangjinzhou** [comment]
没懂啥意思

**Comment by LeanderY** [comment]
在3.2.15 版本中当a-date-picker mode="year"时，无法触发 panel-change 事件
