### ISSUE TITLE
There is a bug when the range-picker component selects the rules by week

### ISSUE THREAD

**Issue by skywalker1992** [vueComponent/ant-design-vue#5978]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
Chrome

### Reproduction link
[https://www.antdv.com/components/date-picker-cn#components-date-picker-demo-range-picker](https://www.antdv.com/components/date-picker-cn#components-date-picker-demo-range-picker)

### Steps to reproduce
打开URL，选则开始周、结束周，关闭。再次打开

### What is expected?
再次打开时，没有选中中间的日期

### What is actually happening?
再次打开时，选中中间的日期

**Comment by tangjinzhou** [comment]
交互就这样，这个和 react 的保持一致 https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker
