### ISSUE TITLE
table组件的列宽为什么不能像react版那样可以拖拽调整呢？

### ISSUE THREAD

**Issue by dxvgef** [vueComponent/ant-design-vue#598]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用户体验更友好

### What does the proposed API look like?
都行

**Comment by lky5230** [comment]
同求，拖拽列宽是客户的硬需求，项目第一次用表格时发现不能拖，不得已全部重写改成element-ui

**Comment by kylinBlack** [comment]
同求

**Comment by gerryli0214** [comment]
同求

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/table/#components-table-demo-resizable-column
