### ISSUE TITLE
Can vue3 not put html elements in the description parameter when using the notification component? It is possible in vue2

### ISSUE THREAD

**Issue by ponysb** [vueComponent/ant-design-vue#5987]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
vue3

### Reproduction link
[https://antdv.com/components/notification-cn#components-notification-demo-update](https://antdv.com/components/notification-cn#components-notification-demo-update)

### Steps to reproduce
notification组件内description参数输入html元素报错

### What is expected?
notification组件内description参数输入html正常运行html

### What is actually happening?
notification组件内description参数输入html元素报错

**Comment by tangjinzhou** [comment]
什么叫输入？  input 框？
