### ISSUE TITLE
Background color overflowed when setting it for the table header

### ISSUE THREAD

**Issue by nieyuyao** [vueComponent/ant-design-vue#5990]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
vue 2.6.14

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-pbw7gj)

### Steps to reproduce
1. setting `scroll.y` to `<a-table>`
2. setting `background-color: red` to `.antd-table-header`
3. the red background color overflows

### What is expected?
no overflow.

### What is actually happening?
background color overflowed.

---
i found that when the `scroll.y` is set for the table, this issue occurs because the `table-header` is set to `overflow:scroll`.

**Comment by tangjinzhou** [comment]
审查元素，添加到具体元素上

**Comment by nieyuyao** [comment]
> 审查元素，添加到具体元素上

如果设置`scroll.y`的话，table-header是不是不应该设置`overflow: scroll`？
