### ISSUE TITLE
If the new tabs component is set with closeIcon of pane, the tab title and close button will appear in 2 rows in the list of more tabs

### ISSUE THREAD

**Issue by FengMingQiang** [vueComponent/ant-design-vue#5991]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
windows10，google浏览器105.0.5195.54，Vue3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hua-dong-ant-design-vue-3-2-12-forked-df7uy1?file=/src/demo.vue)

### Steps to reproduce
使用tab和closeIcon插槽生成标签页，当足够多时点击more按钮

### What is expected?
标签页标题和关闭按钮在一行

### What is actually happening?
标签页标题和关闭按钮在两行

---
目前临时解决方案是把关闭按钮放到tab插槽，然后设置:closable="false"

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/hua-dong-ant-design-vue-3-2-12-forked-3kmw97?file=/src/demo.vue

用了插槽自定义，就要自行去解决样式布局问题，组件内部无法处理你的块级元素，或者说，你都设置了一个宽度 100% 的元素，却又不想换行（但有人却又希望是换行的）  ，组件并不智能
