### ISSUE TITLE
When I use modal to make multiple pop-ups, I set mask=false and cannot click on the modal below and use pointer-events:none; but if the modal is too long, I cannot scroll

### ISSUE THREAD

**Issue by wang22295881** [vueComponent/ant-design-vue#5992]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我当前客户需求，需要在不同页面查看多个modal  有的modal用于查看文献 当设置pointer-events:none 时解决了mask=false遮盖无妨点起其他元素的
但同时却不发让过长modal 进行鼠标滚动

### What does the proposed API look like?
windows,chrome,vue2,antd-vue:1.7.7

**Comment by tangjinzhou** [comment]
自定义样式把 mask 隐藏掉

**Comment by wang22295881** [comment]
能举个例子吗
