### ISSUE TITLE
ant-design-vue 3.2.12 version source can not run

### ISSUE THREAD

**Issue by theseagull5233** [vueComponent/ant-design-vue#5993]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
windowns 11  chrome version is 103.0.5060.114（正式版本） （64 位）

### Reproduction link
[http://www.baidu.com/not address](http://www.baidu.com/not address) 暂无地址

### Steps to reproduce
1. git clone https://github.com/vueComponent/ant-design-vue.git
2. npm install
3. npm run dev

### What is expected?
page is normal show. chrome console not show error.

### What is actually happening?
chrome browser console log is above
Logo.vue:32 Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
at Logo.vue:32:17

**Comment by theseagull5233** [comment]
ant-design-vue 3.2.12的源码 npm install 安装依赖后，再运行npm run dev 日志如下
PS E:\WebProject\ant-design-vue> npm run dev

> ant-design-vue@3.2.12 predev E:\WebProject\ant-design-vue
> npm run version && node node_modules/esbuild/install.js


> ant-design-vue@3.2.12 version E:\WebProject\ant-design-vue
> node ./scripts/generate-version


> ant-design-vue@3.2.12 dev E:\WebProject\ant-design-vue
> npm run predev && npm run routes && vite serve site


> ant-design-vue@3.2.12 predev E:\WebProject\ant-design-vue
> npm run version && node node_modules/esbuild/install.js


> ant-design-vue@3.2.12 version E:\WebProject\ant-design-vue
> node ./scripts/generate-version


> ant-design-vue@3.2.12 routes E:\WebProject\ant-design-vue
> node site/scripts/genrateRoutes.js

▲ [WARNING] "../components/style/color/colorPalette.less" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    site/vite.config.ts:49:49:
      49 │           hack: `true;@import "${require.resolve('../components/style/color/colorPalette.less')}";`,
         ╵                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] "../components/style/color/colorPalette.less" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    site/themeConfig.ts:9:45:
      9 │       hack: `true;@import "${require.resolve('../components/style/color/colorPalette.less')}";`,
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


  VITE v3.1.3  ready in 2715 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.102.47:5173/
  ➜  Network: http://192.168.105.1:5173/
  ➜  Network: http://192.168.245.1:5173/

浏览器输入 http://localhost:5173/ 
控制台提示错误
Logo.vue:32 Uncaught TypeError: Cannot read properties of undefined (reading 'accept')
at Logo.vue:32:17

**Comment by zerobin** [comment]
版本3.2.20 同样会报这个问题
