### ISSUE TITLE
Form `model` is required for validateFields to work.

### ISSUE THREAD

**Issue by joker77877** [vueComponent/ant-design-vue#5997]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
macOS10.15.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/useform-qian-tao-biao-dan-ant-design-vue-3-2-12-forked-f3t5bz?file=/src/demo.vue)

### Steps to reproduce
输入就报错

### What is expected?
不报错

### What is actually happening?
输入就报错

**Comment by tangjinzhou** [comment]
formRef 和 useForm 不要混着用

**Comment by joker77877** [comment]
我要在ruleRes中使用 validate方法，useForm还没有声明那我如何使用呢?
