### ISSUE TITLE
Add inputmask for a-input component

### ISSUE THREAD

**Issue by sherzodbek2557791** [vueComponent/ant-design-vue#600]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
It helps for input patterns to be used.
It would be happy to contribute this issue (enhancement)!

### What does the proposed API look like?
Example: https://github.com/scleriot/vue-inputmask
or like this example:
https://github.com/scleriot/vue-inputmask/issues/6

**Comment by sherzodbek2557791** [comment]
I want to add this feature

**Comment by Pacheco95** [comment]
No updates here? I've been looking for this feature for a long time

**Comment by Pacheco95** [comment]
I discovered a beautiful way to do that. Take a look https://github.com/vuejs-tips/vue-the-mask/issues/168
