### ISSUE TITLE
After setting fieldNames in directory-tree, when defaultExpandAll is set to true, all tree nodes cannot be expanded

### ISSUE THREAD

**Issue by SilenceAdam** [vueComponent/ant-design-vue#6007]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
系统版本：macOS Big Sur 11.4  浏览器版本：Chrome 105.0.5195.125  Vue 版本：3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cocky-tharp-1ezunj?file=/src/App.vue:151-162)

### Steps to reproduce
在directory-tree组件中，设置 fieldNames 后，再设置defaultExpandAll为 true

### What is expected?
所有树节点能够展开

### What is actually happening?
只展开了部分树节点

**Comment by chenuvi** [comment]
解决了吗，我遇到了这个问题，
 Version 3.2.15

**Comment by SilenceAdam** [comment]
> 解决了吗，我遇到了这个问题， Version 3.2.15

解决了，在 3.2.13 已经修复了。
