### ISSUE TITLE
Modal's dialogStyle property setting is invalid

### ISSUE THREAD

**Issue by 490626721** [vueComponent/ant-design-vue#6015]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
vite: 3.0.1   vue: "^3.2.37"

### Reproduction link
[https://iwj59w.csb.app/](https://iwj59w.csb.app/)

### Steps to reproduce
按照文档设置Modal的dialogStyle无任何变化，可参照sandbox

### What is expected?
正确显示设置的dialogStyle

### What is actually happening?
设置后无任何变化

---
当设置了modal的getContainer属性后，mask和modal只影响设置getContainer内

**Comment by tangjinzhou** [comment]
直接使用  style 吧

**Comment by weishaoy** [comment]
4.0.1版本好像又有这个问题了
