### ISSUE TITLE
Searching for my keyword in the official example of the TreeSelect component can't find the data?

### ISSUE THREAD

**Issue by zhaowei2530** [vueComponent/ant-design-vue#6017]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
windows10

### Reproduction link
[https://www.antdv.com/components/tree-select-cn/#TreeSelect-](https://www.antdv.com/components/tree-select-cn/#TreeSelect-)

### Steps to reproduce
界面例子最后一个搜索案例，搜索“my”英文关键字，搜不到？

### What is expected?
能搜到“my”的树

### What is actually happening?
搜不到“my”的树

**Comment by zhaowei2530** [comment]
![企业微信20221011-171035](https://user-images.githubusercontent.com/13674210/195049031-07152535-df03-49ca-9323-88a2cbc7a65b.png)

**Comment by zhaowei2530** [comment]
![企业微信20221011-171220](https://user-images.githubusercontent.com/13674210/195049495-1a800960-dc43-48c7-b8c9-bf787b3a3027.png)

**Comment by tangjinzhou** [comment]
看代码，示例搜索的是 value ，不是 title
