### ISSUE TITLE
Cascader component to automatically find the parent through the child and select it

### ISSUE THREAD

**Issue by zhaoqiang1024** [vueComponent/ant-design-vue#6018]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在后端日常设计中对于级连结构的一般只存储末级节点，当前端需要反显时后端服务接口需要拼接该节点的父级及祖父级数据如：defaultValue=[一级id,二级id,三级id]否则的话将造成前端无法显示选中的标签，是否可以将defaultValue通过传入的id自适应选中父级，例如defaultValue传入[三级id]，页面展示效果可以自动选中一级与二级

### What does the proposed API look like?
大概的伪代码：defaultValue=[三级id]
效果如下：
<img width="413" alt="image" src="https://user-images.githubusercontent.com/26315518/195055771-484c23db-cd75-414c-b65c-a6581109b3bf.png">

**Comment by tangjinzhou** [comment]
自己处理这个逻辑就好了
