### ISSUE TITLE
The placeholder of the select component disappears abnormally

### ISSUE THREAD

**Issue by yalin28** [vueComponent/ant-design-vue#6021]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
"vue": "^3.2.38", mac os, Google Chrome106.0.5249.103 (x86_64)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e-wai-de-ye-jiao-ant-design-vue-3-2-12-forked-ypz8kx?file=/src/demo.vue)

### Steps to reproduce
There is no problem with filtering the options once, but the
placeholder disappears when filtering the "ALL" option consecutively.

### What is expected?
The placeholder does not disappear after repeated filtering

### What is actually happening?
placeholder disappears when filtering the "ALL" option consecutively.

---
中文说明：通过设置某个选项为undefined，达到选择这个选项的时候不显示选项并显示placeholder。但是重复选择定义为undefined的值时，placeholder消失了。

**Comment by tangjinzhou** [comment]
首先，code：ref(xxx) 不支持这种，你要用 code: xxx   
第二：不要拿 undefined 来做值，你可以用 null
