### ISSUE TITLE
AutoComplete When filterOption and allowClear are set at the same time, some Chinese cannot be input

### ISSUE THREAD

**Issue by aov2005** [vueComponent/ant-design-vue#6030]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3

### Environment
vue 3.2，微软拼音输入法

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autocomplete-bug-jejl4e?file=/src/App.vue:185-196)

### Steps to reproduce
```vue
<a-auto-complete
:options="options"
:filter-option="filterOption"
allow-clear
/>
```

中文输入z开头，q开头，w开头等的字符无法输入，造成输入法未输入完成就主动blur掉了，比如【最】这个词就没办法输入，只能先随便输入一个字符才能避免该bug，去掉allow-clear也能正常使用

### What is expected?
中文输入法能正常输入，并且能allow-clear与filter-option并存

### What is actually happening?
未输入完成就主动触发一次blur事件

**Comment by dh13899396662** [comment]
have met the same issue

**Comment by dh13899396662** [comment]
@aov2005 I had met the same issue with yours. And I test it in your Reproduction link, just found an interesting thing that was if you add 'v-model:value="formData.value"',  then there was ok, otherwise, it would be faild.

**Comment by aov2005** [comment]
> @aov2005 I had met the same issue with yours. And I test it in your Reproduction link, just found an interesting thing that was if you add 'v-model:value="formData.value"', then there was ok, otherwise, it would be faild.

原本不是有`v-model:value="formData.test"`么？我换成`v-model:value="formData.value"`也是同样复现

**Comment by cppp1111** [comment]
allow-clear和filter-option同时使用的话，第一次为空时无论输入中文还是英文，在输入第一个字母或数字自动失焦
