### ISSUE TITLE
Calendar的Su | Mo | Tu | We | Th | Fr | Sa怎么变成一 | 二 | 三 | 四 | 五 | 六 | 日

### ISSUE THREAD

**Issue by horizon188** [vueComponent/ant-design-vue#6036]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
dev

### Reproduction link
[https://2x.antdv.com/docs/vue/i18n-cn](https://2x.antdv.com/docs/vue/i18n-cn)

### Steps to reproduce
~

### What is expected?
a-calendar怎么汉化呢？

### What is actually happening?
汉化成功

**Comment by horizon188** [comment]
Su | Mo | Tu | We | Th | Fr | Sa
这些是写死了吗

**Comment by horizon188** [comment]
"ant-design-vue": "^3.2.12"

**Comment by horizon188** [comment]
Su | Mo | Tu | We | Th | Fr | Sa怎么变成一 | 二 | 三 | 四 | 五 | 六 | 日
用jsdom吗

**Comment by wermdany** [comment]
你可能需要去设置 moment 的国际化

**Comment by waynerQiu** [comment]
放弃吧， vue这个版本貌似没人维护了，这个问题永远解决不了

**Comment by TmRichrd** [comment]
<script setup lang="ts">
import 'dayjs/locale/zh-cn'; //需要引入这一段
</script>

**Comment by horizon188** [comment]
改了个版本"ant-design-vue": "3.2.0",
根目录
import { ConfigProvider } from "ant-design-vue";
import zhCN from "ant-design-vue/es/locale/zh_CN";

  <ConfigProvider :locale="zhCN">
      <router-view></router-view>
  </ConfigProvider>


这样就可以

**Comment by Vencyuuu** [comment]
尝试一下确认入口全局汉化配置<a-config-provider></a-config-provider>，同时确保装最新版本的ant-design-vue和dayjs，
开了个demo发现1.11.5的dayjs和3.2.15的 antdv 会出现只有月份没汉化的情况，1.11.7和3.2.15没出现。

**Comment by DAmarkday** [comment]
> 尝试一下确认入口全局汉化配置，同时确保装最新版本的ant-design-vue和dayjs， 开了个demo发现1.11.5的dayjs和3.2.15的 antdv 会出现只有月份没汉化的情况，1.11.7和3.2.15没出现。

一下午都没解决成功，重装了下这两个版本的包后发现问题解决了。谢谢大佬！

**Comment by DAmarkday** [comment]
> 尝试一下确认入口全局汉化配置，同时确保装最新版本的ant-design-vue和dayjs， 开了个demo发现1.11.5的dayjs和3.2.15的 antdv 会出现只有月份没汉化的情况，1.11.7和3.2.15没出现。

一下午都没解决成功，重装了下这两个版本的包后发现问题解决了。谢谢大佬！
