### ISSUE TITLE
Single-file recursive menu generation error

### ISSUE THREAD

**Issue by luyang5123** [vueComponent/ant-design-vue#604]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
1.3.6

### Reproduction link
[https://vue.ant.design/components/menu-cn/#components-menu-demo-open-current-submenu-only](https://vue.ant.design/components/menu-cn/#components-menu-demo-open-current-submenu-only)

### Steps to reproduce
Using the demo in https://vue.ant.design/components/menu-cn/#components-menu-demo-single-file-recursive-menu and introduce the correct sub - menu： Error in render: "TypeError: Cannot read property 'isRootMenu' of undefined"

### What is expected?
At this point a-menu and a-sub-menu are in two files and then report an error

### What is actually happening?
At this point a-menu and a-sub-menu are in two files and then report an error

---
Error in render: "TypeError: Cannot read property 'isRootMenu' of undefined"

**Comment by sendya** [comment]
bug reports require https://codesandbox.io/s/2wpk21kzvr

**Comment by zhouzhili** [comment]
我今天也出现这个问题了
您在 [issue 556](https://github.com/vueComponent/ant-design-vue/issues/556) 给了一个参考，subMenu中使用了functional模板，但是当我把它改为普通vue组件的时候，就会报错：Cannot read property 'isRootMenu' of undefined"

[示例](https://codesandbox.io/embed/vue-antd-template-7bbtg)

@sendya
