### ISSUE TITLE
Table custom header hover effect

### ISSUE THREAD

**Issue by yehoan** [vueComponent/ant-design-vue#6048]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
VUE:2.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-table-slot-forked-sftexx?file=/src/App.vue)

### Steps to reproduce
期望就是我鼠标移入到sex这一列的时候有个弹窗说明 "这是性别" 的解释说明

### What is expected?
期望就是我鼠标移入到sex这一列的时候有个弹窗说明 "这是性别" 的解释说明

### What is actually happening?
目前没有类似的API

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/197456140-320dafe2-d8f3-41e6-bd8b-63c80eb3c2df.png)
想实现类似这样的效果  我使用了  customHeaderRow  但是发现这个 没法做到针对特定列来处理 只能做到所有的 官网在这块没有具体的例子 麻烦说明一下谢谢  也希望后续能在官网补充一下

**Comment by tangjinzhou** [comment]
headerCell 插槽

**Comment by yehoan** [comment]
headerCell   这个没看见官网有说明吧..

**Comment by yehoan** [comment]
api 里面没有这个关键词啊

**Comment by yehoan** [comment]
查到了 是v3.0+  我想问下 这个必须是v3.0+? 目前项目用得版本是v1.7+   请问可以做到向下兼容嘛  项目做不到重构...

**Comment by yehoan** [comment]
v1.7.x 用不了了么
