### ISSUE TITLE
Tree component checkStrictly attribute implements logic problems

### ISSUE THREAD

**Issue by Kerbores** [vueComponent/ant-design-vue#6050]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
windows11,edge106.0.1370.52,vue3

### Steps to reproduce
1. 选中子节点，此时父节点半选
2. 此时提交数据应用有半选的父节点信息

### What is expected?
checkStrictly 为 false的时候checkedKeys的数据结构为{checked: string[] | number[], halfChecked: string[] | number[]}其中halfChecked中的数据是被关联选择的父节点，checkStrictly 为true时，父子节点不关联，返回数据结构为string[] | number[]

### What is actually happening?
组件实现逻辑问题

**Comment by Kerbores** [comment]
1. 当设置 checkStrictly 为 true 的时候 checkStrictly  无论如何不会有值，父节点的选中状态也无法联动，说明作者本意是在设置为true的时候不关联，既然不关联那么选中的数据就应该是 string[] | number[] 这样的类型
2. 当设置 checkStrictly 为false 的时候，组件呈现效果为父子节点联动，也有半选状态，但是此时返回的数据结构却是string[] | number[]，半选的节点也不在其中，此时应设置为{checked: string[] | number[], halfChecked: string[] | number[]}这样的返回结构让用户自定决定如何处理为好
以此判断应该是组件实现逻辑上有问题

**Comment by Kerbores** [comment]
看了下react版本的文档也是这么写的,不知道实现方式是不是这样

**Comment by jackielin7789978** [comment]
我也遇到相同問題，當 checkStrictly 為 true 時元件不會有半選狀態，可回傳的 data 卻是 `{checked: string[] | number[], halfChecked: string[] | number[]}`  結構，反之為 false 時元件有半選狀態，可回傳的 data 卻沒有提供。作者不修正一下嗎？
