### ISSUE TITLE
@input event triggered after complete composition in case of IME language

### ISSUE THREAD

**Issue by SonUngBea** [vueComponent/ant-design-vue#6055]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
Mac OS Chrome Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/composition-input-event-iref8r?file=/src/App.vue)

### Steps to reproduce
Typing Korean to a-input sequentially like (강아지)
ㄱ
가
강
강ㅇ
강아
강앚
강아지

### What is expected?
Native input event is triggered during composition like
ㄱ => triggered
가 => triggered
강 => triggered

However antdv @input event is triggered after complete composition like
ㄱ => Not triggered
가 => Not triggered
강 => Not trigeered
강ㅇ=> triggered

### What is actually happening?
I expect like native input event, input event is triggered not only complete composition but also during composition

**Comment by tangjinzhou** [comment]
you can set prop `lazy= false`

**Comment by SonUngBea** [comment]
It works well!
Thanks @tangjinzhou ! :)

**Comment by zhangyangeng** [comment]
> you can set prop `lazy= false`

你好，当input当做dropdown的触发元素时，且手动控制dropdown弹框显隐时，会出现一个现象就是中文输入还未完成时，即compositionend还未触发时，dropdown显示，此时输入法的虚拟输入区域的拼音被删除了，我刚刚看见这个issue，发现使用lazy输入属性可以解决我当前问题，但官方文档中并未看见有lazy属性，请问这个属性主要的作用是什么呢？

vue 版本：3.2.45
antd 版本：3.2.15
现象如下图：
![1.gif](https://s2.loli.net/2023/10/11/m8Twv2i9nlBYo5x.gif)
