### ISSUE TITLE
Error thrown out in Menu widget when use Random function in key binding

### ISSUE THREAD

**Issue by tnmoon** [vueComponent/ant-design-vue#6057]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
macOS, Chrome 106.0.5249.119, Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-chihiro-6ncxpe?file=/src/App.vue)

### Steps to reproduce

1. click 菜单1;
2. click 菜单2;
3. Cannot read properties of undefined (reading 'childrenEventKeys') thrown out;

### What is expected?
avoid to throw error when use Random function in key binding;

### What is actually happening?
err thrown out when use Random function in key binding;

**Comment by tangjinzhou** [comment]
这个 key 加的没有任何意义啊
