### ISSUE TITLE
a question about intl.

### ISSUE THREAD

**Issue by liuyuan22** [vueComponent/ant-design-vue#6060]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
vue@3.2.33 ant-design-vue@3.2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-morse-37food?file=/src/App.vue)

### Steps to reproduce
1. open https://codesandbox.io/s/unruffled-morse-37food?file=/src/App.vue
2. click date picker

### What is expected?
the header of the popup should display '2022年 10月'

### What is actually happening?
the header of the popup display '2022年 Oct'

**Comment by tangjinzhou** [comment]
https://www.antdv.com/docs/vue/i18n-cn
