### ISSUE TITLE
Hopefully the column.ellipsis property of Table can split the header and columns so that they are controlled separately

### ISSUE THREAD

**Issue by wangxiaocuo** [vueComponent/ant-design-vue#6061]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前列头缩略不支持和排序筛选一起使用，属性功能拆分的话，可以列头窄时正常换行，并且支持排序筛选。

### What does the proposed API look like?
- `column.headEllipsis`
- `column.columnEllipsis`

**Comment by tangjinzhou** [comment]
你可以自己写 css 覆盖
