### ISSUE TITLE
Directory tree doesn't have scrollTo method.

### ISSUE THREAD

**Issue by oushu1tanqiang1** [vueComponent/ant-design-vue#6064]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Directory tree have scrollTo method.

### What does the proposed API look like?
Directory tree expose treeRef to let developer to use.

**Comment by oushu1tanqiang1** [comment]
https://github.com/vueComponent/ant-design-vue/issues/5235

在上面这个 issue 里有人提到 tree 没有 scroll to.

开发者在 22-05-21 的一次 commit 中有修复 https://github.com/vueComponent/ant-design-vue/commit/4439e0f3c324ef66c9c89af96046db804d75eefd

但是 Directory Tree 还是没有。。

Directory Tree 基于 Tree 封装，setup 中没有 expose treeRef


a-tree expose
![图片](https://user-images.githubusercontent.com/87287753/198869622-74cbc000-3965-4a8a-951e-fc0101c71843.png)

a-directory-tree expose
![图片](https://user-images.githubusercontent.com/87287753/198869647-24944009-4c9a-4aaf-91d8-65bba25cf023.png)

**Comment by oushu1tanqiang1** [comment]
此外，原 a-tree 最开始的修复版本，是 expose scrollTo 方法，与官方 API 文档相对应，后面改成了 expose 整个 vc-tree ref 对象，文档可能也需要改一下？

方便的话，我可以提 PR~

**Comment by tangjinzhou** [comment]
加个 scrollTo 吧，整个ref暴露出去意义不大
