### ISSUE TITLE
When the table has few columns, the width is abnormal when dragged。

### ISSUE THREAD

**Issue by a949066041** [vueComponent/ant-design-vue#6065]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
Vue:3.2.28

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-shen-suo-lie-ant-design-vue-3-2-13-forked-8grqgy)

### Steps to reproduce
Drag table width

### What is expected?
The width varies with the mouse

### What is actually happening?
A sudden stretch in width

**Comment by tangjinzhou** [comment]
please try to leave one column at least without width to fit fluid layout
