### ISSUE TITLE
select not working correctly as slot component within radio option, possible a style problem

### ISSUE THREAD

**Issue by swatchion** [vueComponent/ant-design-vue#6075]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
vue 3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
```js
cont formState =  reactive({
"limit": 1,
"user": 1,
})

const userOptions = [
{value: 1, label: 'jack'}, {value: 2, label: 'bob'}
];

```

```html
<a-radio-group class="flex flex-col" v-model:value="formState['limit']">
<a-radio :value="1">
<span>limit user 限定用户</span>
<span>
select user 选择用户:<a-select :options="userOptions"  v-model:value="formState['user']</a-select>
<span>
</a-radio>
<a-radio :value="2">global 不限定用户</a-radio>
</a-radio-group>

```
**在 radio 内部使用 select， select userOptions can not be selected 无法被选择**

after move the select slot out of radio, and use a v-if to check, the select option can selected just fine.

在将 select 从 radio 内部移出后，在同级新建一个 dom 节点，使用 v-if 来条件选然后，select 工作正常

### What is expected?
select as slot work fine with a radio option component

### What is actually happening?
select options can not be selected

**Comment by tangjinzhou** [comment]
提供能够反应你问题的复现
