### ISSUE TITLE
message style display problem

### ISSUE THREAD

**Issue by zhenxinDev** [vueComponent/ant-design-vue#6078]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
所有

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
使用message

### What is expected?
期望显示正常

### What is actually happening?
message 样式icon位置显示偏下

**Comment by cshuting** [comment]
解决了吗？
