### ISSUE TITLE
IE11日历选择框有值的情况无法打开选择框

### ISSUE THREAD

**Issue by chenyulun** [vueComponent/ant-design-vue#608]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
window7 IE11

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/](https://vue.ant.design/components/date-picker-cn/)

### IE11里面点击日历选择框的时候会触发input事件,导致日历选择器打不开问题
webpack:///./node_modules/ant-design-vue/es/vc-calendar/src/date/DateInput.js
```javascript
onInputChange: function onInputChange(event) {
var str = event.target.value;
var _$props = this.$props,
disabledDate = _$props.disabledDate,
format = _$props.format,
selectedValue = _$props.selectedValue; // 没有内容，合法并直接退出
```
的<code>onInputChange<code>事件，导致<code>有值的情况</code>下
webpack:///./node_modules/ant-design-vue/es/vc-calendar/src/RangeCalendar.js
下面的
```javascript
function onInputSelect(direction, value) {
if (!value) {
return;
}
```
接着触发
webpack:///./node_modules/ant-design-vue/es/vc-calendar/src/Picker.js里面的
<code>onCalendarSelect</code>事件执行<code>this.closeCalendar(this.focus);</code>
不会阻止关闭；
### What is expected?
复现IE11问题并且修复他

### What is actually happening?
IE11里面点击日历选择框的时候会触发input事件,导致日历选择器打不开问题

**Comment by chenyulun** [comment]
在提一个问题：IE11里面有左上角闪烁到选框的问题，查到闪烁的问题了
components/vc-align/Align.jsx
里面延迟了对<code>this.forceAlign</code>在IE11有闪烁问题，其实宿主元素早就固定了，没有必要延迟计算位置吧

![Jietu20190320-202355](https://user-images.githubusercontent.com/15979948/54684112-552c2700-4b4e-11e9-9ffe-e1c8ab9c3cd1.jpg)

**Comment by chenyulun** [comment]
我想自己解决这个问题，发现存在这个属性
popupStyle | 额外的弹出日历样式 | object | {}
设置<code>:popupStyle="{top:xx,left:xxx}"</code>属性，会同时设置宿主和日历选框上

**Comment by wangxueliang** [comment]
![image](https://user-images.githubusercontent.com/4122593/54766612-8c760300-4c36-11e9-985c-9274d39cf7fe.png)
![image](https://user-images.githubusercontent.com/4122593/54766622-90a22080-4c36-11e9-8201-13404b358913.png)
使用官方示例，环境是win7系统 ie11版本 未能复现你的问题

**Comment by chenyulun** [comment]
> ![image](https://user-images.githubusercontent.com/4122593/54766612-8c760300-4c36-11e9-985c-9274d39cf7fe.png)
> ![image](https://user-images.githubusercontent.com/4122593/54766622-90a22080-4c36-11e9-8201-13404b358913.png)
> 使用官方示例，环境是win7系统 ie11版本 未能复现你的问题

![捕获](https://user-images.githubusercontent.com/15979948/54867666-d2110800-4dbd-11e9-9d26-c2e9a4d6711e.PNG)
这个就打不开

**Comment by wangxueliang** [comment]
ref #626

**Comment by whateveryoudo** [comment]
360浏览器兼容模式出现了闪动左上角,然后显示正确的问题

**Comment by tangjinzhou** [comment]
@whateveryyoudo https://github.com/vueComponent/ant-design-vue/issues/1833
