### ISSUE TITLE
Close the modal page shake 【Close the modal page shake】

### ISSUE THREAD

**Issue by k650dg4d2** [vueComponent/ant-design-vue#6080]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
win10，Chromium 102.0.5005.167，vue 3.2.38

### Reproduction link
[http://localhost:5173/](http://localhost:5173/)

### Steps to reproduce
使用了官网样例

### What is expected?
页面元素不动【Page elements do not move】

### What is actually happening?
页面元素抖动【Page element shake】

---
不知道为什么所有vue3的UI的modal弹窗都会使页面发生抖动，在弹窗关闭的时候。不胜其烦，请问可以加个包裹标签防止这种情况吗。或者有什么一劳永逸的解决办法。【I don't know why the MODAL pop -up window of all Vue3's UI will shake the page when the pop -up window is closed.Is it annoying, can you add a package label to prevent this?Or have any solutions once and for all.】

如图所示【as the picture shows】
![VeryCapture_20221107214224](https://user-images.githubusercontent.com/32454224/200327303-9af66042-883a-442f-b677-e812bfa1f477.gif)

可以看到"with text"和"operation"字体在抖动，还有其他组件也受影响，没有展示。【You can see that "with text" and "operation" fonts are shaking, and other components are also affected and have not been displayed.】

**Comment by tangjinzhou** [comment]
注意页面右侧滚动条，打开弹窗的时候会把body 的滚动去掉，导致内容区域变宽了，所以产生了”抖动“
不想要抖动，就给body 加个 !important 的overflow 样式，覆盖 modal 自动添加的，但也要接受一个现实，就是打开弹窗后底部内容依然可以滚动的这个问题

鱼和熊掌不可兼得
