### ISSUE TITLE
input need a function when input complete to execute not input once excute once

### ISSUE THREAD

**Issue by Q32223** [vueComponent/ant-design-vue#6088]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
input need a function when input complete to execute not input once excute once,and blur function not change but also excute

### What does the proposed API look like?
input need a function when input complete to execute not input once excute once,and blur function not change but also excute

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/issues/6089
