### ISSUE TITLE
For <a-tabs>,I want to clear the bottom border of tabBar， but why is it invalid to set the style through tabBarStyle Property.

### ISSUE THREAD

**Issue by lamb007** [vueComponent/ant-design-vue#6094]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
vue3.2.41 vite3.2.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-nightingale-qgto3g?file=/src/components/HelloWorld.vue)

### Steps to reproduce
use <a-tabs> and use tabBarStyle Property to set the style of tab bar.
```
<a-tabs v-model:activeKey="activeKey"
:tabBarGutter="100"
:tabBarStyle="{ textAlign: 'center', borderBottom: 'unset' }"
centered>
<a-tab-pane key="1" tab="tab1">
1
</a-tab-pane>
<a-tab-pane key="2" tab="tab2  " force-render>
2
</a-tab-pane>
</a-tabs>
</div>
```

### What is expected?
The bottom border of the tabsBar will be cleared

### What is actually happening?
cannot clear the bottom border,use tabBarStyle.

---
Besides, I try to set font-size of tab-bar in tabBarStyle but it is invalid too.

**Comment by tangjinzhou** [comment]
you can use css to control it
like:
```css
.xxxx .xxx {
  border-bottom: none;
}
```
