### ISSUE TITLE
按照官方文档使用vue-cli引入ant-design-vue错误

### ISSUE THREAD

**Issue by awefeng** [vueComponent/ant-design-vue#610]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
系统版本： window 10  浏览器版本: chrome 72.0 Vue版本 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1opq7px9o3)

### Steps to reproduce
1. 按照官方文档引入antd，是使用的 import antd from 'ant-design-vue' ，而实际上该使用 import antd from 'ant-design-vue/es'，望修正。
2. vue-cli3使用babel-plugin-import配置以后，使用 import antd from 'ant-design-vue/es' 导入antd是缺少样式的，也就是说import 'ant-design-vue/dist/antd.css'不能省略

### What is expected?
修改文档

### What is actually happening?
按照文档引用错误

**Comment by HelloMoli** [comment]
我的也是cli3.0  按照官方引用没报错误 正常啊

**Comment by sendya** [comment]
使用了 `babel-plugin-import` 请一定按照 **按需加载** 的配置方式来引入，而不是你所描述的方式。

这个不能漏，[#使用 babel-plugin-import](https://vue.ant.design/docs/vue/use-with-vue-cli-cn/#%E4%BD%BF%E7%94%A8-vue-cli-3-%E7%9A%84%E5%B0%8F%E4%BC%99%E4%BC%B4) 

如果不配置这个，是不会加载 css 的。 另外 也不需要用 ant-design-vue/es 引入，直接使用 
`import { Button } from 'ant-design-vue'` 这样

**Comment by awefeng** [comment]
刚刚重新写了下，发现是我这边的问题。麻烦两位了。

**Comment by shaomingming008** [comment]
老铁你是什么问题的  我这也是报错

**Comment by shaomingming008** [comment]
![image](https://user-images.githubusercontent.com/22759207/54860151-faaee880-4d50-11e9-8fe7-537b9faff4f0.png)
![image](https://user-images.githubusercontent.com/22759207/54860155-0ac6c800-4d51-11e9-88f2-c8b888a61808.png)
![image](https://user-images.githubusercontent.com/22759207/54860162-1e722e80-4d51-11e9-8766-9fdc2106174b.png)
