### ISSUE TITLE
a-calendar component setting initial time problem

### ISSUE THREAD

**Issue by manggo-dilivery** [vueComponent/ant-design-vue#6102]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
chrome 105

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/99jpp9?file=/src/Demo.vue)

### Steps to reproduce
给时间设置初始值时出问题，使用dateTime = ref(moment('2022-11-13'))设置时间后，所有天数都高亮显示

### What is expected?
设置初始时间，应当只高亮显示初始时间

### What is actually happening?
本地运行时所有天数高亮显示，codesandbox中报错(0 , moment_1.default) is not a function，
codesandbox地址https://codesandbox.io/s/99jpp9?file=/src/Demo.vue

**Comment by tangjinzhou** [comment]
使用  dayjs，默认是 dayjs了
