### ISSUE TITLE
气泡卡片popover承载图片时第一次显示错位

### ISSUE THREAD

**Issue by LittleEven** [vueComponent/ant-design-vue#611]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
chrome 72.0.3626.121, Vue 2.5.17

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
气泡卡片承载图片第一次显示错位
```
<a-popover placement="bottom">
<img slot="content" :src="IconIcity"/>
<img class="picture"  :src="IconCode"/>
</a-popover>
```

### What is expected?
能够正常显示

### What is actually happening?
第一次显示产生偏移

**Comment by zwenli** [comment]
我也遇到这种情况，限制图片大小就不会出现这个问题了

**Comment by tangjinzhou** [comment]
图片给出宽高，不然图片未加载前，计算的位置是有问题的
