### ISSUE TITLE
<Image/>The component does not support 'object fit'. It is recommended to add this API

### ISSUE THREAD

**Issue by GitHub-Mr-Chen** [vueComponent/ant-design-vue#6110]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.2

### Environment
浏览器

### Reproduction link
[https://antdv.com/components/image-cn](https://antdv.com/components/image-cn)

### Steps to reproduce
如题

### What is expected?
如题

### What is actually happening?
如题

**Comment by tangjinzhou** [comment]
使用 css
