### ISSUE TITLE
Why is my dark theme suddenly not working?

### ISSUE THREAD

**Issue by kukufeizei** [vueComponent/ant-design-vue#6116]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.12

### Environment
vue3

### Reproduction link
[http://test.ims.humanbacker.com/login     longyi 123456](http://test.ims.humanbacker.com/login     longyi 123456)

### Steps to reproduce
1

### What is expected?
期望暗黑重新生效

### What is actually happening?
之前一直是可以的，这周突然发现不行了

**Comment by zkwolf** [comment]
复现的网站是可以切换的啊

**Comment by kukufeizei** [comment]
试试http://test.tms.humanbacker.com/home&nbsp; &nbsp;账号密码 一样&nbsp; &nbsp; &nbsp; &nbsp;这个是打包命令"build--test": "vue-tsc --noEmit &nbsp;&amp;&amp; cross-env vite build --mode test",

**Comment by kukufeizei** [comment]
http://test.tms.humanbacker.com/login&nbsp; 账号longyi&nbsp; 密码123456&nbsp; 这个页面登录进去以后。 暗黑模式和浅色模式就有问题，&nbsp; 有空麻烦帮忙看一下呗&nbsp;
