### ISSUE TITLE
keep-alive select Scroll to the bottom Return to the activated page blank

### ISSUE THREAD

**Issue by gossip-girl** [vueComponent/ant-design-vue#6117]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.2

### Environment
vite3.0 vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
keep-alive select 滚动到底部 重新回到activited页面 空白

### What is expected?
keep-alive select 滚动到底部 重新回到activited页面 空白

### What is actually happening?
keep-alive select 滚动到底部 重新回到activited页面 空白

**Comment by gossip-girl** [comment]
![image](https://user-images.githubusercontent.com/27011339/203473754-fc6fa82b-f80a-4353-9847-dfaadab60316.png)

**Comment by VENI-VIDIVICI** [comment]
每次切换加个key？？？

**Comment by ElsaOOo** [comment]
一样遇到这个问题了， antv版本 "ant-design-vue": "2.1.0"

**Comment by ElsaOOo** [comment]
> 一样遇到这个问题了， antv版本 "ant-design-vue": "2.1.0"

发现可以在dropdownVisibleChange回调里面重新请求下拉列表数据，并重新赋值，就没有空白了

**Comment by gossip-girl** [comment]
> > 一样遇到这个问题了， antv版本 "ant-design-vue": "2.1.0"
> 
> 发现可以在dropdownVisibleChange回调里面重新请求下拉列表数据，并重新赋值，就没有空白了

虚拟滚动的问题，将virtual设置为false就好了

**Comment by ElsaOOo** [comment]
> 

我用的是2.x版本的，还没有虚拟滚动这个props😂
