### ISSUE TITLE
Version 1.7.8 upload component photo wall server uploaded without status=done callback can not get pictures

### ISSUE THREAD

**Issue by hyyky** [vueComponent/ant-design-vue#6127]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue 2.6

### Reproduction link
[https://1x.antdv.com/components/upload-cn/#components-upload-demo-pictures-wall](https://1x.antdv.com/components/upload-cn/#components-upload-demo-pictures-wall)

### Steps to reproduce
Version 1.7.8 is too junk, upload the photo wall,
The list type="picture card" change callback cannot return the status "done".

### What is expected?
If you are a bad developer, you might as well not have it. Garbage is trapped by kpi products, which makes me angry.

### What is actually happening?
If you are a bad developer, you might as well not have it. Garbage is trapped by kpi products, which makes me angry.

**Comment by zhouzhangfan** [comment]
#6126
