### ISSUE TITLE
a-range-picker日期选择设置属性disabledDate无效的bug

### ISSUE THREAD

**Issue by xiaoming0827** [vueComponent/ant-design-vue#613]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
chrome 72.0.3626.121（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3qy30xo6y)

### Steps to reproduce
1、前提是直接使用script标签直接引用使用的antd库
2、设置disabled属性，但是无法限制日期选择器不可选择的范围，疑似disabled属性无效
### What is expected?
可以正常设置不可选日期的范围

### What is actually happening?
不能正常设置不可选日期的范围

---
怀疑是直接script标签引入导致的设置disabledDate不生效，十分谢谢。

**Comment by xiaoming0827** [comment]
直接运行以下代码，disabledDate不可用
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.bootcss.com/vue/2.6.9/vue.common.dev.js"></script>
    <script src="https://cdn.bootcss.com/moment.js/2.24.0/moment.min.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@1.3.7/dist/antd.min.css">
    <script src="https://cdn.jsdelivr.net/npm/ant-design-vue@1.3.7/dist/antd.min.js"></script>
</head>
<body>
<div id="app">
    <a-range-picker
            :disabledDate="disabledDate"
          ></a-range-picker>
</div>
<script>
new Vue({
    el:'#app',
    data:{
        message:'123'
    },
    methods:{
        disabledDate(current) {
            // Can not select days before today and today
            return current && current < moment().endOf('day');
        }
    }

})
</script>
</body>
</html>

**Comment by xiaoming0827** [comment]
直接运行一下代码，disabledDate不生效
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.bootcss.com/vue/2.6.9/vue.common.dev.js"></script>
    <script src="https://cdn.bootcss.com/moment.js/2.24.0/moment.min.js"></script>
    <link type="text/css" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ant-design-vue@1.3.7/dist/antd.min.css">
    <script src="https://cdn.jsdelivr.net/npm/ant-design-vue@1.3.7/dist/antd.min.js"></script>
</head>
<body>
<div id="app">
    <a-range-picker
            :disabledDate="disabledDate"
          ></a-range-picker>
</div>
<script>
new Vue({
    el:'#app',
    data:{
        message:'123'
    },
    methods:{
        disabledDate(current) {
            // Can not select days before today and today
            return current && current < moment().endOf('day');
        }
    }

})
</script>
</body>
</html>
```

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/jvwl6263ww
html中不支持驼峰，这是Vue规范
