### ISSUE TITLE
Using input in the slot renderExtraFooter of rangePicker, the input box cannot be focused

### ISSUE THREAD

**Issue by BalotT** [vueComponent/ant-design-vue#6137]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
ant-design-vue@3.2.14; vue@3.2.37

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/e-wai-de-ye-jiao-ant-design-vue-3-2-12-forked-ueiyql?file=/src/demo.vue)

### Steps to reproduce
使用rangePicker组件,在额外页脚插槽renderExtraFooter中添加input输入框，点击输入框，当前输入框无法获取焦点；如果使用的是a-input-number计数输入框，点击数字输入框的增减按钮可以强行把时间组件的聚焦状态移到数字输入框中

### What is expected?
在rangePicker的renderExtraFooter使用input，renderExtraFooter里的输入框可以正常获取焦点

### What is actually happening?
在rangePicker的renderExtraFooter使用input，renderExtraFooter里的输入框无法正常获取焦点

**Comment by BalotT** [comment]
目前想到的方案 在输入框绑定点击事件
const handleClickInput = e => {
    e.target.focus();
}
主动让当前input获取焦点

**Comment by glorydreamtop** [comment]
> 目前想到的方案 在输入框绑定点击事件 const handleClickInput = e => { e.target.focus(); } 主动让当前input获取焦点
但是面板会自动消失，从而也无法使用在extra footer里的输入框，请问如何保持面板显示
