### ISSUE TITLE
a-image-preview-group > a-image set props.preview, not work

### ISSUE THREAD

**Issue by arbing** [vueComponent/ant-design-vue#6143]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
所有浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/delicate-bash-zsg73f)

### Steps to reproduce
多张图片使用preview-group渲染，分别设置自定义预览图片，预览图片不生效

### What is expected?
自定义预览图片生效

### What is actually happening?
发现是preview-group情况下，previewUrls没有使用preview.src，拿的是image.src，如下修改后生效
```diff
-        unRegister = registerImage(currentId.value, props.src, canPreview.value);
+        unRegister = registerImage(currentId.value, preview.value.src || props.src, canPreview.value);
```

**Comment by tangjinzhou** [comment]
给的复现链接里面运行没问题啊

**Comment by greper** [comment]
有问题，点预览之后应该显示另外一个大图（女孩捧茶杯），复现链接里面显示的是vue的logo

**Comment by zhangkx666** [comment]
楼主提的问题依然存在，麻烦修复下呢。需求是缩略图只是一个小图，点预览才会加载大图。
自定义预览图片功能在a-image-preview-group下不生效，单独使用a-image时是有效的
