### ISSUE TITLE
The notification component clicks the close icon and calls the onClose function repeatedly

### ISSUE THREAD

**Issue by Dai-ww** [vueComponent/ant-design-vue#6144]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
node 16.15.1   macOS Ventura13.0  vue3.2.31

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-3-2-14-forked-b1e9v0)

### Steps to reproduce
1、点击notification box
2、点击关闭图标观察控制台  等待几秒后再次观察控制台

### What is expected?
点击关闭图标调用close函数  不点击则定时器触发close函数

### What is actually happening?
重复调用close函数

**Comment by kovsu** [comment]
因为 Notificaiton，设置了自动关闭，有个定时器。你应该在这里面设置 `duration` 为 0，这样就不会出现调用两次 onClose 的情况了。
```js
notification.open({
    .....
    duration: 0,
});
```

**Comment by Dai-ww** [comment]
这是自动关闭的时间，但是如果我手动点击了关闭图标。按理说定时器应该不会触发。

> 因为 Notificaiton，设置了自动关闭，有个定时器。你应该在这里面设置 `duration` 为 0，这样就不会出现调用两次 onClose 的情况了。
> 
> ```js
> notification.open({
>     .....
>     duration: 0,
> });
> ```

**Comment by kovsu** [comment]
![image](https://user-images.githubusercontent.com/82451257/206443303-8f674c90-f785-406d-bc51-4d1c53729274.png)
事实上他就是触发了两次 onClose 事件，一次你手动关闭，第二次就是这个 自动关闭 事件。而且上面这个图片，他也说了如果要取消自动关闭就将 duration 赋值为 0。

**Comment by Dai-ww** [comment]
1. 当前设计是否为antd expected behavior？
2. 如果设置0，会导致用户体验发生改变。由原本用户需“指定时间”或者“手动”关闭通知变更为只能手动关闭。
3. 当前表现与antd-react行为表现是否一致？
react 官方表现如下
https://codesandbox.io/s/zi-dong-guan-bi-de-yan-shi-antd-5-0-4-forked-vrkqq6?file=/demo.tsx

**Comment by kovsu** [comment]
> 1. 当前设计是否为antd expected behavior？
> 2. 如果设置0，会导致用户体验发生改变。由原本用户需“指定时间”或者“手动”关闭通知变更为只能手动关闭。
> 3. 当前表现与antd-react行为表现是否一致？
>    react 官方表现如下
>    https://codesandbox.io/s/zi-dong-guan-bi-de-yan-shi-antd-5-0-4-forked-vrkqq6?file=/demo.tsx

今天，看了下源码。发现就是，他给这个添加了 `mouseLeave` 和 `mouseEnter` 事件。在 `unMounted` 之后，他还运行了一次 `mouseLeave` 事件，又创建了一次定时器，所以导致 `onClose` 事件触发了两次。
