### ISSUE TITLE
About calling the Modal.confirm method to assign jsx to the content attribute in the passed props object

### ISSUE THREAD

**Issue by xiaojianggege** [vueComponent/ant-design-vue#6146]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-morning-7ci6xj?file=/src/App.vue)

### Steps to reproduce
1.  我打算用编程式使用moda组件
2. 官方文档中的modal.confirm方法接收的props对象中content属性的类型接受vnode | jsx
3. 于是我在js中调用modal.confirm方法并给props中的content赋值了jsx
4. 但是报错了

### What is expected?
调用modal.confirm方法给接收的props对象中content属性赋值jsx

### What is actually happening?
报错了

**Comment by tangjinzhou** [comment]
jsx 类型，不是jsx文件
<TestModal /> not TestModal
打个日志consele.log(TestModal)出来看看就知道了
