### ISSUE TITLE
Anchor 组件的 getContainer 方法返回报错

### ISSUE THREAD

**Issue by baranwang** [vueComponent/ant-design-vue#615]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
Chrome 72, Vue 2.6.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pmpmqzpow0)

### Steps to reproduce
当页面滚动不在`body`时，给`Anchor`设置`getContainer` 返回报错

### What is expected?
返回正常

### What is actually happening?
[Vue warn]: Error in nextTick: "TypeError: Cannot read property 'addEventListener' of undefined" found in ---> <AAnchor>

TypeError: Cannot read property 'addEventListener' of undefined

Uncaught TypeError: Cannot read property 'scrollTop' of undefined

**Comment by KeiferJu** [comment]
您解决这个问题了吗?
