### ISSUE TITLE
Why can't you design a dark mode switch like arco, but change a different less style file. This design seems very backward, and it will undoubtedly increase the development cost.

### ISSUE THREAD

**Issue by zxiaozhou** [vueComponent/ant-design-vue#6161]
- [✅ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我感觉arco那样内置动态切换黑暗模型非常友好，实现也不是那么难。为啥不能那样设计了？？？？？目前的设计显得非常落后。这无疑是增加了开发成本。

### What does the proposed API look like?
```
document.body.setAttribute('arco-theme', 'dark');
or
document.body.setAttribute('arco-theme');
```

**Comment by tangjinzhou** [comment]
welcome pr

**Comment by 974869973** [comment]
主题跟主题色能不能分开设置啊？
