### ISSUE TITLE
Table sticky scrollbar disappears

### ISSUE THREAD

**Issue by junyangfan** [vueComponent/ant-design-vue#6164]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
vue: 3.2.36

### Reproduction link
[https://antdv.com/components/table-cn#API](https://antdv.com/components/table-cn#API)

### Steps to reproduce
当Table表格支持左右拖动的时候，页面拖动到最下面，拖动粘性滚动条会消失

### What is expected?
粘性滚动条正常显示

### What is actually happening?
粘性滚动条消失

**Comment by junyangfan** [comment]
other

**Comment by DMQ** [comment]
@junyangfan 请问这个问题解决了吗？

**Comment by junyangfan** [comment]
> 

没有解决，但是消失这个现象是正常现象，然而它好像没监听到页面上下滚动，需要看下源码

**Comment by junyangfan** [comment]
> 

@DMQ 没有解决，但是消失这个现象是正常现象，然而它好像没监听到页面上下滚动，需要看下源码

**Comment by DMQ** [comment]
> > 
> 
> @DMQ 没有解决，但是消失这个现象是正常现象，然而它好像没监听到页面上下滚动，需要看下源码

我昨天看了下源码找到办法了，你的场景可能跟我的有点像。sticky需要传入一个 `{ getContainer: () => {} }` 通过getContainer返回实际的滚动节点，不然会默认使用`document.body`

相关源码：
https://github.com/vueComponent/ant-design-vue/blob/main/components/vc-table/Table.tsx#L359
https://github.com/vueComponent/ant-design-vue/blob/main/components/vc-table/hooks/useSticky.ts#L29
https://github.com/vueComponent/ant-design-vue/blob/main/components/vc-table/stickyScrollBar.tsx#L171
