### ISSUE TITLE
When the select component scrolls down, the text color in the drop-down list will deepen

### ISSUE THREAD

**Issue by web-tg** [vueComponent/ant-design-vue#6177]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
chrome last 2 versions

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-liskov-yr2yb1?file=/src/App.vue)

### Steps to reproduce
1.select点开下拉，鼠标滚动；
2.下拉列表文字会出现文字从灰色变黑色加粗的情况；（非必然出现，需尝试多次滚动）

### What is expected?
下列列表滚动时，文字颜色不出现变化

### What is actually happening?
下列列表滚动时，文字颜色会出现变化

**Comment by tndong799** [comment]
I also have the same problem. Give me the solution if you find it. Thank you!!!

**Comment by tndong799** [comment]
> 
select 'a1' and scroll down.

**Comment by lelezh** [comment]
我也是，chrome和edge有这种现象，有的电脑上下拉框滚动时还出现了短暂的花屏，firefox是正常的，有人知道原因吗？

**Comment by lelezh** [comment]
把select下ul的样式的overflow改为visible后正常了，同时把padding也改为了0，看上去似乎没什么问题了，但是不知道原因。
