### ISSUE TITLE
table组件  Expandable Row can't do it

### ISSUE THREAD

**Issue by JoeXin** [vueComponent/ant-design-vue#6178]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
browser

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-joe21u](https://stackblitz.com/edit/vitejs-vite-joe21u)

### What is expected?
Table 组件
可展开
当表格内容较多不能一次性完全展示时。
使用这种方式生效

### What is actually happening?
希望能修复

**Comment by JoeXin** [comment]
希望能解决一下，谢谢

**Comment by zkwolf** [comment]
You can use v-slots like [this demo](https://stackblitz.com/edit/vitejs-vite-snmmqw).
