### ISSUE TITLE
I hope that cascader can support multi-select operation to actually select the data as the last node

### ISSUE THREAD

**Issue by zhangguixin** [vueComponent/ant-design-vue#6181]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
数据库一般存储为全路径数据 , 目前cascader选中数据后会自动合并数据为上级ID , 希望有个参数可以阻止这一行为 。 例如地址选择 , 为得出全路径 ,不得不将选择的参数进行多次循环查找构建新的地址数组 , 降低了页面的处理速度

### What does the proposed API look like?
希望的输出结果为 [ 1 , 10 , 101 ][ 1 , 10, 102 ] , 而非现在的自动合并数据 [1]

**Comment by zzpqp50** [comment]
反人类，能不能学习原版antd。人家就是有几个值返回几个

**Comment by masicheng** [comment]
确实反人类，怎么判断是选择了父节点还是选择全部子节点合并过来的

**Comment by masicheng** [comment]
确实反人类，还得处理数据
