### ISSUE TITLE
table组件滚动条和选择框同时存在时，表头和内容有一点点错位

### ISSUE THREAD

**Issue by 289420843** [vueComponent/ant-design-vue#6188]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuan-ze-he-cao-zuo-ant-design-vue-3-2-14-forked-r9xgl1?file=/src/demo.vue)

### Steps to reproduce
开启row-selection，开启滚动 scroll="{ y: 200 }"，开启边框bordered，columns尽量多些，越是靠后的列约明显

### What is expected?
表头和内容的边框线条对齐
![ADB9BBA5-5BF0-41e4-AFD1-82EA8E955288](https://user-images.githubusercontent.com/5706753/211238429-37f26e50-065d-4ff7-afec-8711c4f1a00a.png)

### What is actually happening?
表头与内容的列错位，边框显示不整齐

**Comment by 289420843** [comment]
经过排查与是否开启row-selection没有关系，是因为单元格实际宽度是有小数点的，但是 vc-resize-observer 获取到的 offsetWidth 是整数导致。

**Comment by nikojxie** [comment]
> 经过排查与是否开启row-selection没有关系，是因为单元格实际宽度是有小数点的，但是 vc-resize-observer 获取到的 offsetWidth 是整数导致。

请问有什么解决的办法吗
