### ISSUE TITLE
In the Nuxt3 SSR environment, the component Select only displays the first suffix icon in the list under multiple selections

### ISSUE THREAD

**Issue by ka3hun9** [vueComponent/ant-design-vue#6196]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
Nuxt3

### Reproduction link
[https://stackblitz.com/edit/nuxt-starter-dzs5pw](https://stackblitz.com/edit/nuxt-starter-dzs5pw)

### Steps to reproduce
1. 打开可选下拉列表
2. 从上往下勾选

### What is expected?
多选情况下, 所有选中的选项应显示后缀图标

### What is actually happening?
组件Select在Nuxt3 在SSR环境中, 多选情况下仅显示列表第一个的后缀图标
1. 在非服务器渲染下无此错误
2. 在SSR下,图标更改为字符, 无此错误
3. 在SSR下,从下往上勾选, 无此错误

**Comment by hugegegewu** [comment]
+1

**Comment by fskarmeta** [comment]
+1

**Comment by 233333-doge** [comment]
+1

**Comment by 233333-doge** [comment]
How did you settle it？

**Comment by noyalin** [comment]
+1
