### ISSUE TITLE
The table column resizable function does not support template column

### ISSUE THREAD

**Issue by TaoziDeGitHub** [vueComponent/ant-design-vue#6199]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
table column resizable功能不支持template column

### What does the proposed API look like?
https://codesandbox.io/s/template-feng-ge-de-api-ant-design-vue-3-2-14-forked-nsrsix?file=/src/demo.vue

**Comment by liamwang** [comment]
Hmm, I'm having the same problem and suggest reopening this issue.
