### ISSUE TITLE
Table filter menu is very slow for large data

### ISSUE THREAD

**Issue by mdwekat** [vueComponent/ant-design-vue#6200]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.15

### Environment
macOs 13.1, Chrome 108.0.5359.124, vue 3.2.45

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-slow-table-filter-kcfbc0)

### Steps to reproduce
Open the https://codesandbox.io/s/antd-vue-slow-table-filter-kcfbc0 on the table and try to use the filter icon located in the country column header. Notice how long it takes to open.

### What is expected?
For the drop-down menu to open fast

### What is actually happening?
The menu takes almost 2 seconds to open.

**Comment by runlong-yao** [comment]
[useVirtualList](https://vueuse.org/core/useVirtualList/)
In order to improve performace,you can use  "useVirtualList" to custom filterOptions
