### ISSUE TITLE
ssr, nuxt3, tabs are dynamically added, beyond the width, the mouse is placed on the more button, and the error hydration node does not match

### ISSUE THREAD

**Issue by uuApi** [vueComponent/ant-design-vue#6202]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
Win10,Google,nuxt3

### Steps to reproduce
[Vue warn]: Hydration node mismatch:
- Client vnode: Symbol(Comment)
- Server rendered DOM: "" (text)
at <AMenuItem key="/admin" id="rc-tabs-0-more-popup-/admin" role="option"  ... >
at <Anonymous>
at <ResizeObserver disabled=true onResize=fn<onOverflowResize2> >
at <Overflow tabindex=-1 role="menu" aria-activedescendant=null  ... >
at <AMenu onClick= (2) [ƒ, ƒ] id="rc-tabs-0-more-popup" tabindex=-1  ... >
at <Align target=fn<bound getRootDomNode> key="popup" ref=Ref< undefined >  ... >
at <BaseTransition onBeforeEnter=fn<onBeforeEnter> appear=false persisted=false  ... >
at <Transition ref=Ref< undefined > onBeforeEnter=fn<onShowPrepare2> >
at <PopupInner prefixCls="ant-tabs-dropdown" point=null align=

### What is expected?
tabs动态添加,超出宽度,鼠标放到更多按钮上面,报错水合节点不匹配

### What is actually happening?
tabs动态添加,超出宽度,鼠标放到更多按钮上面,报错水合节点不匹配

**Comment by codingcn** [comment]
https://tehub.com/a/bwvuiRZkiq
