### ISSUE TITLE
pagination select display exception

### ISSUE THREAD

**Issue by CCherry07** [vueComponent/ant-design-vue#6204]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
os: macos  browser : Google Chrome 109 Vue: 3.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-xia-la-xuan-xiang-ant-design-vue-3-2-14-forked-e8kg8n?file=/src/demo.vue)

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/79909910/212464169-56ec5d56-795e-4fe1-9c8d-75eb528e5d66.png">

### Steps to reproduce
pageSizeOptions User-defined: ["30", "40", "50"]

### What is expected?
pagination select Display ["30", "40", "50"]

### What is actually happening?
pagination select Display exception ["10" , "30", "40", "50"]

**Comment by tangjinzhou** [comment]
建议直接修改 defaultPageSize

**Comment by CCherry07** [comment]
但是用户也许是没有传pageSize 或者 defaultPageSize , 但是传了 size options ， 他只是在change 事件 去处理这个东西的时候，视图是明显错误的。 @tangjinzhou 这个也许需要一个解决方式，默认 pegesize 为 size options 第一个 也是符合直觉的

**Comment by tangjinzhou** [comment]
这个有点问题， defaultPageSize 只有在首次render 的时候才会生效，后续的动态更改都不会生效，这是 defaultXXxx 这类api 的规范

但size options 很大可能是动态的，如果支持了首次从 options[0]取，同样也会带来新的疑问，个人建议直接文档给提示好了

不然文档解释起来会更麻烦，用户更难理解

**Comment by CCherry07** [comment]
options[0] 的值，这个一般是约定好的，文档指出了[0]为默认，或者 10 。其他的 size option 是动态 已经意义不大了，所以反应在视图仍然是没有问题的。当没有绑定defaultPageSize 以及 pageSize  也许歧义更大。而且当options[0] 不为 10时， 反应到视图更为严重。
