### ISSUE TITLE
In the vite environment, antdesign vue is used, and the ".env.test" file is used as the package configuration file, which is deployed in the service area. The date selector will be invalidated and you cannot select a date. You must change the ".env.test" file name to something else to restore normal.

### ISSUE THREAD

**Issue by pettyspider** [vueComponent/ant-design-vue#6209]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
win10,macOs 12.2.1, Chrome 109.0.5414.87, vue 3.2.14

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/signin?utm_source=landingpage)

### Steps to reproduce
1. Package the.env.test configuration file locally and deploy the package on the server.
2. Access the project and open the Date Selector

### What is expected?
You can also use.env.test as the name of the configuration file locally

### What is actually happening?
.env.test file name must be changed, so that the date selector of ant-design-vue can be used properly

---
normal:.env.test=>.env.sandbox
bug: .env.test

**Comment by LoveIsReal** [comment]
我也遇到了这个问题，坐等作者修复

**Comment by chenyongcai** [comment]
modal modal bug   https://github.com/vueComponent/ant-design-vue/issues/4565
