### ISSUE TITLE
I cannot import component library directly in browser，I think component library umd file There may be some errors.

### ISSUE THREAD

**Issue by BoxiTon** [vueComponent/ant-design-vue#6223]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.15

### Environment
https://unpkg.com/vue@3.2.45/dist/vue.global.js

### Reproduction link
[https://unpkg.com/ant-design-vue@3.2.15/dist/antd.min.js](https://unpkg.com/ant-design-vue@3.2.15/dist/antd.min.js)

### Steps to reproduce
I build the `index.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<link rel="icon" href="/favicon.ico">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<script src="https://unpkg.com/vue@3.2.45/dist/vue.global.js"></script>
<script src="https://cdn.bootcdn.net/ajax/libs/dayjs/1.4.1/dayjs.min.js"></script>
<script>
// only add this line, can solve the browser console error.
dayjs.extend = () => {};
</script>
<script>
console.log(dayjs().format())
</script>
<script src="https://unpkg.com/ant-design-vue@3.2.15/dist/antd.min.js"></script>
<title>Vite App</title>
</head>
<body>
<div id="app"></div>
</body>
</html>
```

Then, I try to get `console.log(window.antd)` on the console. if no exists `dayjs.extend = () => {};`, it cause an error.

***Uncaught TypeError: Sh(...).extend is not a function***

I think dayjs lose the function, for example, `dayjs.extend()`.

![image](https://user-images.githubusercontent.com/30290771/216075159-2e9c32fb-1593-49d3-bc7d-d142ce3f1ab6.png)

![image](https://user-images.githubusercontent.com/30290771/216075264-368aec94-ced9-45da-a554-01ab23af4116.png)

### What is expected?
i hope This problem can be solved quickly. and add some documents to explain how to directly reference the component library in the browser.

### What is actually happening?
console error:

***Uncaught TypeError: Sh(...).extend is not a function***

---
I think dayjs lose the function, for example, `dayjs.extend()`.

**Comment by zkwolf** [comment]
https://antdv.com/docs/vue/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5 you should import dayjs like this

**Comment by BoxiTon** [comment]
> https://antdv.com/docs/vue/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5 you should import dayjs like this

ok，thank you.

**Comment by BoxiTon** [comment]
> https://antdv.com/docs/vue/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5 you should import dayjs like this

ok，thank you.
