### ISSUE TITLE
Layout.slider trigger不生效

### ISSUE THREAD

**Issue by Mister-Hope** [vueComponent/ant-design-vue#624]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
win10 1809, chrome74,  2.6.10

### Reproduction link
[https://github.com/GodofHope/antdvueBug2](https://github.com/GodofHope/antdvueBug2)

### Steps to reproduce
just open the project and look at the slider

### What is expected?
The trigger icon is DIY and can be changed when collapese changes.

### What is actually happening?
The icon remain unedited.

---
The doc says it can accept a slot.

**Comment by GodofHope** [comment]
I looked at the code，and find only null can switch to adifferent situation.  I am not expert enough to send a pr， so could you handle it？

**Comment by sendya** [comment]
Custom zero trigger are not supported. and React Ant Design version is the same.

https://codesandbox.io/s/mol9852z29

**Comment by GodofHope** [comment]
Maybe you should update the docs?
The docs still says it can accept a slot, and may mislead some people.
