### ISSUE TITLE
The (clearValidate) parameter of (api) of (a-form) is invalid if an array is passed

### ISSUE THREAD

**Issue by firstSunrain** [vueComponent/ant-design-vue#6242]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/s/silly-flower-ct1f1u)](https://codesandbox.io/s/objective-rubin-z1ckwb)

### Steps to reproduce
第一步：触发动态表单的第一行第一个的输入框的必填校验提示。
第二步：点击Clear dynamic按钮。
Step 1: trigger the required verification prompt in the first input box of the first line of the dynamic form.
Step 2: Click the Clear dynamic button.

### What is expected?
点击按钮后，清除第一行第一个的输入框的必填校验提示。
Click the button to clear the required verification prompt in the first input box of the first line.

### What is actually happening?
There is no change.

---
点击Clear fixed按钮时，非动态表单的错误校验提示可以被顺利清除，初步怀疑是form表单的clearValidate方法不支持数组格式参数。
When you click the (Clear fixed) button, the error verification prompt of the non-dynamic form can be cleared successfully. It is initially suspected that the (clearValidate) method of the (form) form does not support array format parameters.

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/restless-cloud-27rckn?file=/src/App.vue

[[]]  双数组

**Comment by firstSunrain** [comment]
原来是双数组清除多个指定字段的设计 感谢 已解决
