### ISSUE TITLE
The panelChange event of the DatePicker component cannot be triggered

### ISSUE THREAD

**Issue by lizhihaoerdaye** [vueComponent/ant-design-vue#6243]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
windows11,Google Chrome109.0.5414.120,vue3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zp9bkd?file=/src/demo.vue)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/47618476/217468788-99710131-092d-40bb-8e20-e445d48e1edc.png)

### What is expected?
可以正确触发handlePanelChange

### What is actually happening?
无法正确触发handlePanelChange事件

**Comment by zedyuan999** [comment]
我看了下源码，是因为Picker里没有接收onPanelChange参数，而RangePicker却有接收onPanelChange

**Comment by purple-color** [comment]
啥时候修复一下

**Comment by zedyuan999** [comment]
> 啥时候修复一下

我提了pr，没人合
https://github.com/vueComponent/ant-design-vue/pull/6543

**Comment by w-z-y** [comment]
我也遇到了，现在卡在这一天了都
