### ISSUE TITLE
In IE9-10 this will cause the area wrapped by the Spin component to be unclickable

### ISSUE THREAD

**Issue by zj9495** [vueComponent/ant-design-vue#625]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
Windows7/Windows10,IE9-10

### Reproduction link
[https://vue.ant.design/components/table/](https://vue.ant.design/components/table/)

### Steps to reproduce
The Table component in the official document can be reproduced

### What is expected?
Clickable

### What is actually happening?
Unclickable

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14365

**Comment by tangjinzhou** [comment]
本周会发 patch 再更新一下，着急的话可以写一个 css 样式覆盖掉：

```
.ant-spin-container::after {
  display: none\9;
}
```
