### ISSUE TITLE
ie11下组件DatePicker 日期选择框不显示且控制台报错

### ISSUE THREAD

**Issue by TTcom** [vueComponent/ant-design-vue#626]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.4

### Environment
window10、ie11、vue2.5.22

### Reproduction link
[https://github.com/TTcom/tree-demo](https://github.com/TTcom/tree-demo)

### Steps to reproduce
运行项目npm run serve,然后打开浏览器ie11,打开控制台就可看到报错

### What is expected?
DatePicker 日期选择框组件可在ie11上正常使用

### What is actually happening?
DatePicker 日期选择框组件可在ie11上无法使用

**Comment by sendya** [comment]
IE 请引入 `@babel/polyfill` 依赖，并处理相关配置

具体可以参考 [Vue 官方文档](https://cli.vuejs.org/zh/guide/browser-compatibility.html#polyfill)

babel.config.js
```js
module.exports = {
  presets: [
    '@vue/app',
    [
      '@babel/preset-env',
      {
        'useBuiltIns': 'entry'
      }
    ]
  ],
   plugins: [
    [
      "import",
      { libraryName: "ant-design-vue", libraryDirectory: "es", style: true }
    ]
  ]
}
```

![20190326201318](https://user-images.githubusercontent.com/5404542/54996218-aaab7c80-5003-11e9-8abe-021ade58f5e9.png)

**Comment by chenyulun** [comment]
麻烦调试一下代码，我都说明了打不开的原因和情况，请看#608

**Comment by sendya** [comment]
> 麻烦调试一下代码，我都说明了打不开的原因和情况，请看#608

你好，首先 我解决的是 IE11 下打不开 DatePicker

其二，我看了 #608 （有值的情况下），但是没有复现出来。
![GIF](https://user-images.githubusercontent.com/5404542/55054704-b480be80-509b-11e9-950b-451afc2aad52.gif)

如果你需要解决这个问题，你应当提供一个能够复现的 repo 或者 codesandbox 以供我们查询定位问题

**Comment by tangjinzhou** [comment]
@chenyulun 都给你pr了，我们还能做什么？  😓
and 如果问题解决了 麻烦关掉 issue

**Comment by TTcom** [comment]
@sendya  @tangjinzhou 代码我已经更新，按照你的提示日期组建是可以正常显示了，但还有两个问题
1、可是每次弹出日期框的时候都会现在网页左上角闪一下然后回到正确的位置。
2、在选择过日期然后在对日期控件进行v-if摧毁处理后控制台就会报错。
![捕获1](https://user-images.githubusercontent.com/29853303/55082678-11509900-50dd-11e9-9c17-87eba04d9931.PNG)
![捕获](https://user-images.githubusercontent.com/29853303/55082538-d0f11b00-50dc-11e9-93f3-e77d3f5d049f.PNG)

**Comment by tangjinzhou** [comment]
ref #865
