### ISSUE TITLE
DatePicker date selection box control, when set to the quarter mode, input the specified quarter in the input box, the panel cannot be rendered normally

### ISSUE THREAD

**Issue by yiyimamay** [vueComponent/ant-design-vue#6272]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
browser

### Reproduction link
[https://www.antdv.com/components/date-picker-cn](https://www.antdv.com/components/date-picker-cn)

### What is expected?
可以修复

### What is actually happening?
yes

**Comment by bigsnowballhehe** [comment]
https://github.com/vueComponent/ant-design-vue/blob/b695dc95e3fd129bdd5aee4cbdf9b77563f9fadb/components/vc-picker/generate/dayjs.ts#L165  
问题出在这里,除了Q1,其他的都是invalid.
