### ISSUE TITLE
DatePicker component cannot select month or year

### ISSUE THREAD

**Issue by kuikuiGe** [vueComponent/ant-design-vue#6273]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
ant-desing-vue 1.7.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-datepicker-yfpel8?file=/src/App.vue)

### Steps to reproduce
1. select a day in the next month
2. swith to month mode
3. select current month

### What is expected?
can choose current month

### What is actually happening?
can't choose the current month

![This is an image](https://raw.githubusercontent.com/kuikuiGe/temp/main/antd-datepicker-bug1.png?raw=true)

---
the year mode has the same problem

**Comment by wengx-unx** [comment]
you can try to use.
```javascript
disabledDate(current) {
    // Can not select days before today and today
    // return current && current < moment().endOf("day");

    return current && current <= moment().subtract(1, "day");
}
```

**Comment by kuikuiGe** [comment]
> if you select March 1，can you get back to today in month mode

**Comment by kuikuiGe** [comment]
> you can try to use.
> 
> ```js
> disabledDate(current) {
>     // Can not select days before today and today
>     // return current && current < moment().endOf("day");
> 
>     return current && current <= moment().subtract(1, "day");
> }
> ```

if you select March 1，can you get back to today in month mode
