### ISSUE TITLE
When using Ant Design Msu in Nuxt v3: Gives an error: Hydration node mismatch

### ISSUE THREAD

**Issue by ghost** [vueComponent/ant-design-vue#6279]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
Nuxt Framework version 3.2.0, vue version 3.2.47

### Reproduction link
[https://github.com/Roman-00/iteca-web/blob/PR-7/app/components/header/LangSwither.vue](https://github.com/Roman-00/iteca-web/blob/PR-7/app/components/header/LangSwither.vue)

### Steps to reproduce
Download the repository -> Go to the app folder -> Run yarn install -> Next, launch the yarn died project, open the developer console when you click on the language change item in the top menu, a warning about: Hydration node mismatch

### What is expected?
Correction Vue warn Hydration node mismatch

### What is actually happening?
A warning drops into the console: Hydration node mismatch

![photo_2023-02-15_09-12-01](https://user-images.githubusercontent.com/58338625/218944902-e4097d09-9a67-4733-8dd7-aa6ec58a84aa.jpg)

**Comment by codingcn** [comment]
临时解决方案：https://tehub.com/a/bwvuiRZkiq
