### ISSUE TITLE
mode api of the controlled panel demo

### ISSUE THREAD

**Issue by ggunmo** [vueComponent/ant-design-vue#628]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
window7sp1,chrome浏览器环境下、Vue版本为2.5.22

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-date-format](https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-date-format)

### Steps to reproduce
I set the mode with year,and when I open the datepicker panel,it can also select date

### What is expected?
I just want to choose the year

### What is actually happening?
it can choose date

---
I cann't find the description of mode in the API

**Comment by iboying** [comment]
I encountered the same problem. Is there a plan to solve it?
