### ISSUE TITLE
The position displayed by popover flashes every time it is clicked

### ISSUE THREAD

**Issue by yiranmiao** [vueComponent/ant-design-vue#6281]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue 2.6

### Reproduction link
[https://1x.antdv.com/components/popover-cn/](https://1x.antdv.com/components/popover-cn/)

### Steps to reproduce
<a-popover
v-model:visible="popoverVisible"
arrow-point-at-center
trigger="click"
</a-popover>

### What is expected?
popover 位置计算有问题，每次点击后的位置会发生变化，会在两个位置之间反复横跳

### What is actually happening?
popover 位置计算有问题，每次点击后的位置会发生变化，会在两个位置之间反复横跳

---
提问之前查阅了issues，有类似问题如下：
https://github.com/vueComponent/ant-design-vue/issues/3147
为什么要重新提问：
这里的解决办法是设置transitionName=""，确实可以解决闪跳的问题，但是同时也使popover失去了展现时的动画效果。目前看2和3版本的ant deisgn已经解决了这个问题，1.7.8是否还会有后续更新解决这个bug？感谢查看。

**Comment by tangjinzhou** [comment]
v1 不再更新

**Comment by yiranmiao** [comment]
> v1 不再更新

感谢回复，可以告知一下2和3版本对于这个问题的解决思路吗，我可以尝试自己修复源码中的这个BUG。

**Comment by DuanShuaiShuai** [comment]
> > v1 不再更新
> 
> 感谢回复，可以告知一下2和3版本对于这个问题的解决思路吗，我可以尝试自己修复源码中的这个BUG。

增加属性transitionName
