### ISSUE TITLE
Vue2.7.14   antd v1.7.8 throw error for binding ref to v-model

### ISSUE THREAD

**Issue by shiyeling** [vueComponent/ant-design-vue#6287]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Windows 10, Chrome  110.0.5481.97, vue2.7.14

### Reproduction link
[https://github.com/shiyeling/testvue](https://github.com/shiyeling/testvue)

### Steps to reproduce
Clone the below repo:
git@github.com:shiyeling/testvue.git

npm install  and npm run serve

then open the link: http://localhost:8080/ with browser and navigate to http://localhost:8080/login

### What is expected?
the page should display an input with predefined string value.

### What is actually happening?
the value is showing as object

**Comment by zkwolf** [comment]
don't bind ref and v-model to same value
