### ISSUE TITLE
checkbox中 对勾的位置问题

### ISSUE THREAD

**Issue by noobalex** [vueComponent/ant-design-vue#630]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
Chrome 73, Safari 12

### Reproduction link
[https://preview.pro.loacg.com/list/table-list](https://preview.pro.loacg.com/list/table-list)

### Steps to reproduce
使用checkbox组件

### What is expected?
checkbox 对勾位置居中

### What is actually happening?
checkbox 对勾位置偏移

![image](https://user-images.githubusercontent.com/20298142/54904501-aefb6b00-4f19-11e9-965d-138ab97f6da9.png)

**Comment by xrkffgg** [comment]
官网组件中没有看到此现象： https://www.antdv.com/components/checkbox-cn/
