### ISSUE TITLE
Form validation rules not working properly when submit button has html-type="submit"

### ISSUE THREAD

**Issue by msmosavar** [vueComponent/ant-design-vue#6304]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
Vue: 3.2.45 - browser: Chrome 110.0.5481 - Windows 11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-tdd-h5uj9r?file=/src/App.vue)

### Steps to reproduce
Fill the input with something (e.g. abc), click "Save" button

### What is expected?
No validation errors should occur and the success message fires

### What is actually happening?
The required validation error occurres and the error message fires

---
This is happening only when the html-type="submit" is set on the button

**Comment by fliize** [comment]
use "v-model:value" instead of  "v-model" on the input component
