### ISSUE TITLE
Datepicker: Input field format not according to locale

### ISSUE THREAD

**Issue by SinBirb** [vueComponent/ant-design-vue#6306]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
Firefox Nightly, Firefox stable

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-3-2-14-forked-ltprxi?file=/src/demo.vue)

### Steps to reproduce
In the topmost DatePicker, select 23rd February 2023.

### What is expected?
Format shown in the input field after the date was selected should be 23.02.2023.

### What is actually happening?
Format shown in the input field after the date was selected is 2023-02-23

**Comment by tangjinzhou** [comment]
please add format prop to custom it
