### ISSUE TITLE
tabs cannot be switched under the ie9

### ISSUE THREAD

**Issue by homeant** [vueComponent/ant-design-vue#631]
Version
1.3.7

Environment
Reproduction link
https://vue.ant.design/components/tabs-cn/

Steps to reproduce
use ie9

What is expected?
It runs in ie9

What is actually happening?
tabs cannot be switched under the ie9

**Comment by tangjinzhou** [comment]
https://ant-design-vue.gitee.io/docs/vue/introduce/#Environment-Support
please add polyfills by yourself

**Comment by homeant** [comment]
Incompatibility due to flex layout
