### ISSUE TITLE
About Ant Design Vue vue3 a-table expand icon position！！！

### ISSUE THREAD

**Issue by lingdengke** [vueComponent/ant-design-vue#6318]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
研究半天，关于a-table中看展开列表和嵌套子表格中展开图标用哪个方法可以使其移到表格最右边除自定义方法外，感谢。。。

### What does the proposed API look like?
如果没有，后期是否考虑。。。。

**Comment by van-chin** [comment]
我也没有，找到如何把展开图标 如何放到其他列的方法，有研究出来么
