### ISSUE TITLE
InputNumber在Form下校验表单错误，提示‘is not a string'

### ISSUE THREAD

**Issue by zj9495** [vueComponent/ant-design-vue#632]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
macOS 10.14.3/Windows 7,Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x0v6795no)

### Steps to reproduce
在输入框中输入数字无法通过校验

### What is expected?
可以正常校验

### What is actually happening?
无法正常通过校验

**Comment by agoni1212** [comment]
remove code 

`trigger: 'blur'`

**Comment by tangjinzhou** [comment]
添加type: number，文档有说明，
https://codesandbox.io/s/xr643w0xvo

**Comment by agoni1212** [comment]
why the demo is correct after remove  `trigger: 'blur'`
