### ISSUE TITLE
Table setting fixed columns does not take effect fixed:'right'

### ISSUE THREAD

**Issue by Zlessio** [vueComponent/ant-design-vue#6322]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gu-ding-tou-he-lie-ant-design-vue-3-2-14-forked-13k9ug?file=/src/demo.vue)

### Steps to reproduce
1、直接新建demo
2、  const columns = ref([
{
title: '商品名称',
dataIndex: 'name',
searchAble: true,
fixed: 'right',
}
])

### What is expected?
预期可以固定到右侧

### What is actually happening?
没有固定到右侧

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/gu-ding-tou-he-lie-ant-design-vue-3-2-14-forked-rj607e

自行调整顺序
