### ISSUE TITLE
Remove the :value in v-model:value

### ISSUE THREAD

**Issue by bill-mark** [vueComponent/ant-design-vue#6325]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
多了个:value  旧项目升级特别麻烦 而且现在elementplus都不带:value,你们要觉得无所谓 我也只能转投elementplus了 必须带:value写起来啰嗦

### What does the proposed API look like?
v-model=""

**Comment by TAUnionOtto** [comment]
@tangjinzhou Eh…… but why rejected to remove?

**Comment by ramwin** [comment]
为什么要拒绝这个需求啊。[官网](https://cn.vuejs.org/guide/essentials/forms.html#basic-usage) 都用v-model的
