### ISSUE TITLE
The split slot display is missing from the space doc

### ISSUE THREAD

**Issue by Zz-ZzzZ** [vueComponent/ant-design-vue#6326]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
3.2.0

### Reproduction link
[https://www.antdv.com/components/space/#API](https://www.antdv.com/components/space/#API)

### Steps to reproduce
https://www.antdv.com/components/space/#API

### What is expected?
should show split slots

### What is actually happening?
not display

---
split slot code is defined in the source code, but is not shown in the doc

```typescript
            const split = slots.split?.();
            /// ...
            return (
              <>
                <div class={itemClassName} style={itemStyle}>
                  {child}
                </div>
                {index < latestIndex && split && (
                  <span class={`${itemClassName}-split`} style={itemStyle}>
                    {split}
                  </span>
                )}
              </>
            );
```

**Comment by tangjinzhou** [comment]
？

**Comment by Zz-ZzzZ** [comment]
> ？

space组件里有个split插槽，文档没写是不是漏了
