### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by duanhjlt** [vueComponent/ant-design-vue#6330]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
node v16.13.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
yarn
yarn compile

### What is expected?
compile success

### What is actually happening?
antd-tools run compile
start compile at  2023-03-03T13:48:44.569Z
[Parallel] Compile to es...
[Parallel] Compile to js...
components/mentions/index.tsx(207,47): error TS2769: No overload matches this call.
The last overload gave the following error.
Argument of type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }, ... 11 more ..., { ...; }>'.
Type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }>> & { ...; }, ... 10 more ..., string>'.
Types of property 'emits' are incompatible.
Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.

**Comment by didengren** [comment]
Have the error reporting issues been resolved?

**Comment by mars-ou1991** [comment]
same issues

**Comment by mars-ou1991** [comment]
Currently I fix it like this...

![image](https://user-images.githubusercontent.com/12790790/231650599-6b6e0039-7bc6-4974-af2f-38c93a0024c2.png)
![image](https://user-images.githubusercontent.com/12790790/231650652-f52727b3-fd31-4070-9c10-511d9c12da59.png)
![image](https://user-images.githubusercontent.com/12790790/231650697-600d6bf8-8393-4547-a38d-9b4ff0b6e269.png)
