### ISSUE TITLE
The parameter showCheckedStrategy value of the tree select component does not work. Choose SHOW_ALL or display child nodes. When the child nodes are not fully selected, you need to be able to get the value of the parent node.

### ISSUE THREAD

**Issue by yiran00** [vueComponent/ant-design-vue#6336]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
all

### Reproduction link
[https://www.antdv.com/components/tree-select-cn](https://www.antdv.com/components/tree-select-cn)

### Steps to reproduce
任意地方引入<a-select-tree> 设置show-checked-strategy为TreeSelect.SHOW_ALL，然后子节点选中一部分，这时需要父节点的value,未展示

### What is expected?
子节点选中一部分，这时需要父节点的value，而不是选中了父节点才展示父节点的value

### What is actually happening?
子节点选中一部分时，未展示父节点值

**Comment by zkwolf** [comment]
应该就是这么设计的，只展示full checked的值
