### ISSUE TITLE
The InputNumber number input box cannot be used in the vue3 js up and down keys, and it is useless to put the list of the official website into the code

### ISSUE THREAD

**Issue by hmyBuy** [vueComponent/ant-design-vue#6341]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
vue3 js

### Reproduction link
[https://www.antdv.com/components/input-number-cn](https://www.antdv.com/components/input-number-cn)

### Steps to reproduce
InputNumber 数字输入框在vue3 js中上下键无法使用，把官网的列子放到代码里面，也是没有用

### What is expected?
vue3 js中上下键能够使用

### What is actually happening?
InputNumber 数字输入框在vue3 js中上下键无法使用

**Comment by XiaoLuo01** [comment]
请问解决了吗？我现在也遇到同样的问题，为什么这个issue没有人回答呢？
