### ISSUE TITLE
The DatePicker date selection box does not trigger the change event when the date is clicked

### ISSUE THREAD

**Issue by l406054531** [vueComponent/ant-design-vue#6350]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
3.2.13

### Reproduction link
[https://antdv.com/components/date-picker-cn](https://antdv.com/components/date-picker-cn)

### Steps to reproduce
DatePicker 日期选择框 在点击日期的时候  change事件不触发

### What is expected?
期望选择日期 或者show-time开启后  选择时间都能触发change时间

### What is actually happening?
实际没触发

**Comment by CCherry07** [comment]
这个好像是触发的
