### ISSUE TITLE
datepicker presets commonly used dates, and 5.x has been adjusted, and 4.0.0.alpah1 has no corresponding adjustment

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#6354]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
datapicker 预设常用日期 这块and5.x已经调整，4.0.0.alpah1没有对应调整

### What does the proposed API look like?
datapicker 预设常用日期 这块and5.x已经调整，与antd5.x保持一致
![image](https://user-images.githubusercontent.com/5828057/225175969-fb67fff8-3cc7-4332-b1b5-3de501faa6b9.png)

**Comment by CCherry07** [comment]
我来试试
