### ISSUE TITLE
Progress, Steps component variants are not consistent with ant5.x

### ISSUE THREAD

**Issue by wsxe9988** [vueComponent/ant-design-vue#6355]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Progress,Steps 组件变体 未与ant5.x保持一致

### What does the proposed API look like?
Progress,Steps 组件变体 未与ant5.x保持一致
![image](https://user-images.githubusercontent.com/5828057/225176565-8c060f91-726f-4124-87ff-2f41f64528e7.png)

**Comment by CCherry07** [comment]
我来试试
