### ISSUE TITLE
Bugs about Ant Design of Vue official website documentation

### ISSUE THREAD

**Issue by Epic-Deno** [vueComponent/ant-design-vue#6356]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### Reproduction link
[https://www.antdv.com/docs/vue/introduce-cn/](https://www.antdv.com/docs/vue/introduce-cn/)

### Steps to reproduce
右上角版本切换，从v3的文档切换到v1的文档，然后再点击右上角切换从v1的文档切回到v3的文档， 这时候文档显示就是v3的文档，而是v4的文档， 想要切换回v3的文档需要，从v4文档切换v2的文档，再从v2文档切换到v3的文档，这时候才可以显示出v3 的文档。

### What is expected?
希望可以正常切换查看各个版本的文档

### What is actually happening?
现在文档切换有问题

### video about above description

https://user-images.githubusercontent.com/74635349/225222084-5a4271dc-6d0f-40a8-95ef-abdf0a05762b.mov

**Comment by tangjinzhou** [comment]
ok 了
