### ISSUE TITLE
When adding the @click event to the button element, the onClick attribute is also defined in the value of v-bind. The operation prompts that onClick needs to accept a Function, but it gets an Array, and the code can run normally. How to remove this warning prompt

### ISSUE THREAD

**Issue by ay-seeing** [vueComponent/ant-design-vue#6363]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
浏览器环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/friendly-pond-p5xdcb?file=%2Fsrc%2FApp.vue)

### Steps to reproduce
打开控制台就可以看到

### What is expected?
希望去掉 [Vue warn]: Invalid prop: type check failed for prop "onClick". Expected Function, got Array 提示

### What is actually happening?
代码运行提示warn

**Comment by tangjinzhou** [comment]
v-bind="omit(xxx, 'onClick')"
