### ISSUE TITLE
4.0.2 The menu dividing line disappeared

### ISSUE THREAD

**Issue by jiubanqingchen** [vueComponent/ant-design-vue#6365]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
macos 13.3 chrome 111.0.5563.64 vue3.2.47

### Reproduction link
[https://next.antdv.com/components/dropdown-cn#components-dropdown-demo-item](https://next.antdv.com/components/dropdown-cn#components-dropdown-demo-item)

### Steps to reproduce
打开文档 https://next.antdv.com/components/dropdown-cn#components-dropdown-demo-item 这个示例可以发现分割线并没有显示

### What is expected?
修复这个功能

### What is actually happening?
本地使用dropdown组件 发现分割线消失 查看官网文档也消失了

**Comment by tangjinzhou** [comment]
update 4.0.0-alpha.3
