### ISSUE TITLE
select组件展开折叠时动画卡顿

### ISSUE THREAD

**Issue by ShadowSpeedy** [vueComponent/ant-design-vue#637]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
chrome,Vue2.5.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/](https://github.com/vueComponent/ant-design-vue/)

### Steps to reproduce
<a-select  v-model="selectItem" style="width: 120px">
<a-select-option value="${jack}">${jack}</a-select-option>
<a-select-option value="${lucy}">${lucy}</a-select-option>
<a-select-option value="${yiminghe}">${yiminghe}</a-select-option>
</a-select>

### What is expected?
让动画更加流程

### What is actually happening?
在收起选项框时，选中项会默认跳到第一项，然后收起，过程卡顿不流畅，期间会出现只有选项文字没有底色的样式。

**Comment by ShadowSpeedy** [comment]
![image](https://user-images.githubusercontent.com/28926508/54976650-f8a98b80-4fd5-11e9-89aa-7e0dc91e6127.png)

**Comment by ShadowSpeedy** [comment]
![image](https://user-images.githubusercontent.com/28926508/54976725-2bec1a80-4fd6-11e9-8866-fb625105f0e6.png)
![image](https://user-images.githubusercontent.com/28926508/54976762-3d352700-4fd6-11e9-966a-fe034b4f4df2.png)

**Comment by wangxueliang** [comment]
请提供复现链接（https://codesandbox.io/s/2wpk21kzvr）方便排查  谢谢

**Comment by ShadowSpeedy** [comment]
> 请提供复现链接（[https://codesandbox.io/s/2wpk21kzvr）方便排查](https://codesandbox.io/s/2wpk21kzvr%EF%BC%89%E6%96%B9%E4%BE%BF%E6%8E%92%E6%9F%A5) 谢谢

![GIF](https://user-images.githubusercontent.com/28926508/55217176-d021cb80-5239-11e9-9c36-19236be0e406.gif)
![GIF3](https://user-images.githubusercontent.com/28926508/55217179-d3b55280-5239-11e9-8ef5-68b8fbd39f53.gif)

**Comment by wangxueliang** [comment]
这只是截图，看不到你的代码，很难排查问题出在哪里啊

**Comment by ShadowSpeedy** [comment]
> 这只是截图，看不到你的代码，很难排查问题出在哪里啊

你们官方示例也存在这个问题你看一下
