### ISSUE TITLE
ant-piker-cell-range-hover-end style error

### ISSUE THREAD

**Issue by CCherry07** [vueComponent/ant-design-vue#6372]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0.alpha.2

### Environment
os: macos  browser : Google Chrome 109 Vue: 3.x

### Reproduction link
[https://www.antdv.com/components/date-picker-cn/#DatePicker-](https://www.antdv.com/components/date-picker-cn/#DatePicker-)

### Steps to reproduce
月份 以及年份 hover 选择的最后一个 月/年 提示框明显偏移错误
<img width="613" alt="image" src="https://user-images.githubusercontent.com/79909910/226337775-6bdae34a-cb2f-4009-ae92-9be3661394fa.png">

### What is expected?
<img width="590" alt="image" src="https://user-images.githubusercontent.com/79909910/226337700-81709ebd-d805-47a9-b90b-4cee64858037.png">

### What is actually happening?
月份 以及年份 hover 选择的最后一个 月/年 提示框明显偏移错误

**Comment by zkwolf** [comment]
看起来ant design 那边已经修了，而且右侧按设计是保持对齐的，直接同步ant design的修改就好了 https://github.com/ant-design/ant-design/pull/40607

**Comment by CCherry07** [comment]
@zkwolf  好的👌
