### ISSUE TITLE
If using dark theme

### ISSUE THREAD

**Issue by zhou5631** [vueComponent/ant-design-vue#6376]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
ant-design-vue4.0

### Reproduction link
[https://next.antdv.com/docs/vue/customize-theme-cn](https://next.antdv.com/docs/vue/customize-theme-cn)

### Steps to reproduce
      options: {
        lessOptions: { // 如果使用less-loader@5，请移除 lessOptions 这一级直接配置选项。
          modifyVars: getThemeVariables({
            dark: true, // 开启暗黑模式
          }),
          javascriptEnabled: true,
        },
      },

### What is expected?
由于4.0没有CSS文件了，暗黑主题官方文档还是3.0的模板

### What is actually happening?
现在应该怎么样使用暗黑主题呢

**Comment by thikiiii** [comment]
找到解决办法了吗？我也是找不到设置暗黑主题的地方

**Comment by CCherry07** [comment]
@thikiiii @zhou5631 

https://next.antdv.com/docs/vue/customize-theme-cn

官方的 dark token https://github.com/vueComponent/ant-design-vue/tree/feat-v4/components/theme/themes/dark
