### ISSUE TITLE
上传组件upload例子fileList实际逻辑有问题。

### ISSUE THREAD

**Issue by luoyang125024608** [vueComponent/ant-design-vue#638]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
生产

### Reproduction link
[https://ant-design-vue.gitee.io/components/upload-cn/](https://ant-design-vue.gitee.io/components/upload-cn/)

### Steps to reproduce
官网例子

### What is expected?
正确回调@change

### What is actually happening?
不回调@change

**Comment by luoyang125024608** [comment]
[https://github.com/luoyang125024608/lllyyy-github-images/blob/master/a-upload.jpg](url)

**Comment by wangxueliang** [comment]
没太明白你所指的逻辑问题在哪里
ps: 你截图部分，是自定义展示逻辑，你所上传的文件返回内容不满足demo自定义逻辑，就不展示哈
方便的话，提供复现链接（https://codesandbox.io/s/2wpk21kzvr）

**Comment by luoyang125024608** [comment]
> 没太明白你所指的逻辑问题在哪里
> ps: 你截图部分，是自定义展示逻辑，你所上传的文件返回内容不满足demo自定义逻辑，就不展示哈
> 方便的话，提供复现链接（[https://codesandbox.io/s/2wpk21kzvr）](https://codesandbox.io/s/2wpk21kzvr%EF%BC%89)

的确response.status 是服务器给的状态。所以一旦复制了这个逻辑。。就傻了。
