### ISSUE TITLE
Some component colors cannot be adjusted after customizing the theme

### ISSUE THREAD

**Issue by tenyears94** [vueComponent/ant-design-vue#6383]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
版本：3.2.14，应客户要求自定义了主题色，但是目前部分组件颜色无法适配。最严重的就是下拉框已选中项的背景色和字体（展开下拉框时）一直为白色，导致选项看不清楚，试过了`select-selection-item-bg`等变量，仍不能控制，请问解决办法或修改的变量

### What does the proposed API look like?
有个地方显示先可控制主题的变量及释义

**Comment by tenyears94** [comment]
![image](https://user-images.githubusercontent.com/49542458/227405795-b405832b-971a-4d9e-b076-338d38fe330a.png)

**Comment by zkwolf** [comment]
应该是这个 select-item-selected-bg

**Comment by chenxiaofie** [comment]
@tenyears94 `  css: {
    preprocessorOptions: {
      less: {
        modifyVars: {
          '@primary-color': '#000000',
          '@select-item-selected-bg': '#ccc',
        },
        javascriptEnabled: true,
      },
    },
  },`
你要改变的是@select-item-selected-bg，这个是vite下modifyVars的配置，更详细的主题配置请看[这里](https://github.com/vueComponent/ant-design-vue/blob/main/components/style/themes/default.less)
