### ISSUE TITLE
In a-range-picker week mode, the binding formatted date display error

### ISSUE THREAD

**Issue by Jitianpeng** [vueComponent/ant-design-vue#6384]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
mac os 12.6 chrome111.0.5563.64 vue 3.2.46

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-morning-ytgwch?file=/src/App.vue)

### Steps to reproduce
1、a-range-picker picker 模式选择 week valueFormat和format 设置 YYYY-ww
2、v-model:value 绑定格式化后的默认日期 例如：date: [2023-22,2023-23]
3、组件显示日期为 [2023-01,2023-01]

### What is expected?
组件显示日期与绑定值一致

### What is actually happening?
datejs 无法将 YYYY-ww 格式的字符串转为 正确日期格式的日期, 导致日期选择组件绑定默认值时，显示的日期与绑定值不符

**Comment by CCherry07** [comment]
@Jitianpeng  你目前可以考虑这样去写以达到这个需求

```vue
<template>
  <a-range-picker
    :value="dateComputedRef"
    picker="week"
    format="YYYY-ww"
    value-format="YYYY-ww"
    @change="handleChange"
  />
</template>

<script>
import { ref, computed } from "vue";
import dayjs from "dayjs";
export default {
  name: "App",
  setup() {
    const date = ref(["2023-22", "2023-24"]);
    const dateComputedRef = computed(() => {
      return date.value.map((item) => {
        const dateStr = item.split("-");
        return dayjs(dateStr[0], "YYYY").week(dateStr[1]);
      });
    });
    const handleChange = (val) => {
      date.value = val;
    };
    return {
      dateComputedRef,
      handleChange,
    };
  },
};
</script>
```

**Comment by Jitianpeng** [comment]
好的，感谢
