### ISSUE TITLE
在Table组件的rowSelection属性中，使用getCheckboxProps回调函数，并不能将Table中的Checkbox disable掉

### ISSUE THREAD

**Issue by GennCai** [vueComponent/ant-design-vue#639]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
codesandbox vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/3vx9klpv66)

### Steps to reproduce
1.新建Vue项目
2.安装AntD
3.使用Table组件，添加数据
4.将rowSelection属性中的getCheckboxProps设置为()=>({disabled: true})

### What is expected?
期望所有表格的CheckBox被Disable，和React Antd的实现一样

### What is actually happening?
表格的CheckBox并没有被Disable

---
文档中没有rowSelection中getCheckboxProp属性的示例，希望后面加上

**Comment by lxiaosky** [comment]
你写错了,应该这么写
`getCheckboxProps (record) {
      return {
        props: {
          disabled: record.called_id !== '',
          name: record.name
        }
      }
    }`

**Comment by pqhchan** [comment]
getCheckboxProps的disabled可以支持动态修改吗？

**Comment by xuminke** [comment]
经过多次踩坑，貌似不支持动态修改。。苦恼中 @pqhchan 有办法嘛？

**Comment by xuminke** [comment]
https://github.com/vueComponent/ant-design-vue/issues/935 这里有解决的办法，把disabled所参考的变量保存在record本身的某个值当中，就能动态修改。但是我不知道为什么使用this.xxx这种外层的变量为什么就不可以。。。

**Comment by JinLuhuan** [comment]
onChange中将tableData重新设置即可再次触发

**Comment by wxy1234567890** [comment]
> onChange中将tableData重新设置即可再次触发

当前tableData是父组件通过props传到子组件中，子组件中如何重新设置tableData，
