### ISSUE TITLE
@arco-plugins/vite-vue 插件导向控制台打印的行数与代码实际行数不一致

### ISSUE THREAD

**Issue by thikiiii** [vueComponent/ant-design-vue#6391]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
win11、vue3.2.47、@arco-plugins/vite-vue@1.4.5

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-ixdnin?file=src/App.vue](https://stackblitz.com/edit/vitejs-vite-ixdnin?file=src/App.vue)

### Steps to reproduce
复现地址：https://stackblitz.com/edit/vitejs-vite-ixdnin?file=src/App.vue
按F12，打开控制台会看到 打印的”测试1“和”测试2“的行数一样，但是代码中“测试1”“测试2”的实际的行数是3和4。

去掉 @arco-plugins/vite-vue 插件后，控制台打印的行数与实际代码的行数一致。

### What is expected?
期望控制台打印的行数与实际代码的行数一致，希望能够解决这个问题，谢谢

### What is actually happening?
控制台打印的行数与实际代码的行数不一致

---
只有在 .vue 文件中有这个问题

**Comment by CCherry07** [comment]
你这个也许要把issue 提给@arco-plugins/vite-vue@1.4.5

**Comment by thikiiii** [comment]
> 你这个也许也要把问题提交[@arco-plugins/vite-vue@1.4.5](https://github.com/arco-design/arco-plugins)才能解决你的问题
上周就提交了，但是没人回复...
