### ISSUE TITLE
treeNode prop增加checked的属性，决定节点是否选中

### ISSUE THREAD

**Issue by kotoyo1516** [vueComponent/ant-design-vue#640]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
设置checkedKeys时候，目前tree使用checkStrictly的可以控制准确勾选，但需要勾选父节点下的所有节点会变得很繁琐，增加此功能后：
能实现精准设置checkedKeys，但是又能保留勾选父节点下的所有节点的操作
https://codesandbox.io/s/4j1vwzzj50
我仅仅想设置"0-0-0", "0-0-0-1"两个节点选中，用户操作的时候保留勾选父节点下的所有节点，除非设置checkStrictly我递归计算所有节点的checked和halfchecked

### What does the proposed API look like?
{
title: "0-1",
key: "0-1",
checked:true,
children: [
{ title: "0-1-0-0", key: "0-1-0-0",checked:true },
{ title: "0-1-0-1", key: "0-1-0-1" },
{ title: "0-1-0-2", key: "0-1-0-2" }
]
}

**Comment by wangxueliang** [comment]
组件暂不考虑实现
ps: 你可以考虑二次封装组件实现你的需求

**Comment by kotoyo1516** [comment]
好吧，其实已经在二次封装了……那我就再写一个计算checked的function吧……
