### ISSUE TITLE
预设与 tailwindcss 冲突，没有设置途径

### ISSUE THREAD

**Issue by jiangmaniu** [vueComponent/ant-design-vue#6407]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-alpha.3

### Environment

根据 [antd issues](https://github.com/ant-design/ant-design/issues/38794) 可知 由于权重问题，导致样式会被 tailwindcss 预设给覆盖，根据[官网](https://ant.design/docs/react/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8)可知，通过将 `StyleProvider ` 组件的 hashPriority 属性设置为 "high"，即可解决该问题，但我再使用时发现该组件库没有导出`StyleProvider` 组件，看了源码后发现是通过 `inject/provide` 实现的，并且`hashPriority `属性是写死的，无法通过业务层设置。

https://github.com/vueComponent/ant-design-vue/blob/ae27d430e52edc109d98f251fec56aa97eea0e7a/components/_util/cssinjs/StyleContext.tsx#L79

如果
 

### Reproduction link
[http://baidu.com](http://baidu.com)

希望能与antd一样导出一个`StyleProvider`组件供用户设置，也可以将设置参数集成到`ConfigProvider`组件中，或者以其他方式进行设置。

> 可有可能是我没有发现相关设置的途径，我已尽我所能去源码中寻找。如果确实如此，请您告诉我该怎么做

**Comment by CCherry07** [comment]
@jiangmaniu   我感觉可以，将useStyleProvider提供用户？

**Comment by tangjinzhou** [comment]
> @jiangmaniu 我感觉可以，将useStyleProvider引入，如果可以，我会去提一个pr
> 
> ```ts
> import { useStyleProvider } from 'ant-design-vue/es/_util/cssinjs';
> useStyleProvider({
>   hashPriority:"high",
> });
> ```

@CCherry07 包一个 StyleProvider 组件出来吧，用use 的有点问题（调用use的那个组件不会生效）

**Comment by selvinzr** [comment]
`<style-provider hashPriority="high">
{node}
</style-provider>

<script setup lang="ts">
import { StyleProvider } from 'ant-design-vue/es/_util/cssinjs';
</script>

它在rc6依然可用
`

**Comment by selvinzr** [comment]
```
<template>
<style-provider hashPriority="high">
{node}
</style-provider>
</template>
<script setup lang="ts">
import { StyleProvider } from 'ant-design-vue/es/_util/cssinjs';
</script>
```
我在rc6中运行正常，并提供了其他的api

**Comment by selvinzr** [comment]
> @jiangmaniu 我感觉可以，将useStyleProvider引入，如果可以，我会去提一个pr
> 
> ```ts
> import { useStyleProvider } from 'ant-design-vue/es/_util/cssinjs';
> useStyleProvider({
>   hashPriority:"high",
> });
> ```

它在控制台报了一个错误
`[Vue warn]: Invalid watch source:  {hashPriority: 'high'} A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. `

**Comment by gaokun** [comment]
应该将StyleProvider用法, 添加到ant design vue的官方文档中
