### ISSUE TITLE
ie9下,drawer使用destroyOnClose 不起作用，组件没有被销毁，只是增加了opacity: 0

### ISSUE THREAD

**Issue by mkxj** [vueComponent/ant-design-vue#641]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.3

### Environment
IE9

### Reproduction link
[https://vuecomponent.github.io/issue-helper/#repro-modal](https://vuecomponent.github.io/issue-helper/#repro-modal)

### Steps to reproduce
ie9下，打开drawer,关闭后再打开，里面的内容还保留上次填写的

### What is expected?
关闭drawer后，子组件被销毁

### What is actually happening?
关闭drawer后，子组件未被销毁，只是增加了样式opacity: 0

**Comment by tangjinzhou** [comment]
提供复现链接谢谢

**Comment by mkxj** [comment]
我大概知道原因了，你在代码里用了
![image](https://user-images.githubusercontent.com/38096863/55134893-23761a00-5165-11e9-930f-f3e413ee509a.png)，而ie9不支持transitionend这个事件

**Comment by yun-cn** [comment]
确实发现不能进行数据销毁.
