### ISSUE TITLE
trigger clear event when the Input is cleared by clicking the clear button

### ISSUE THREAD

**Issue by likui628** [vueComponent/ant-design-vue#6411]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
When conducting a search, I need to distinguish whether the user clicked the "clear" button or deleted a keyword.
If the user clicks the "clear" button, I need to clear the search results; if only a keyword was deleted, then nothing needs to be done.

### What does the proposed API look like?
clear	when the Input is cleared by clicking the clear button	function(e)

**Comment by CCherry07** [comment]
hello, You may need to include the allow clear attribute, or the suffix attribute will do what you need.
https://www.antdv.com/components/input#components-input-demo-allow-clear
https://www.antdv.com/components/input#API

**Comment by likui628** [comment]
```js
 <Input v-model:value="searchKeyword" placeholder="input something">
          <template #suffix>
            <Icon
              v-if="searchKeyword" icon="material-symbols:cancel-outline-rounded"
              class="clear cursor-p"
              @click="() => clearSearch()"
            />
            <Button type="text" size="small" @click="() => search()">
              Search
            </Button>
          </template>
</Input>
```
I wonder if there's an easier way to do it. for example: emit `clear` event

**Comment by CCherry07** [comment]
我的考虑是，这里的这个slot，本身不是一定是做清理的工作，是一种你自定义的工作，并且 allow clear 设计之初，仅仅是能快速的清除 value ，如果想监听 这个value 的改变 ，可以使用 change 事件

**Comment by likui628** [comment]
明白了，我想起@tangjinzhou说过，antdv是跟ant design保持一致的，谢谢你的回复
