### ISSUE TITLE
a-input works incorrect with passed property as object field with default value

### ISSUE THREAD

**Issue by vmusulainen** [vueComponent/ant-design-vue#6412]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
ant-design-vue 3.2.13; vue-3.2.37

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/zealous-greider-l0cvb8)

### Steps to reproduce
lets App.vue be as

<template>
<HelloWorld v-model:name="model.name"/>
</template>

<script setup>
import HelloWorld from './components/HelloWorld.vue'

const model = {name: 'initial value'}
</script>

and HelloWorl.vue as

<template>
<input :value="name" @input="$emit('update:name', $event.target.value)">
<a-input :value="name" @input="$emit('update:name', $event.target.value)" />
</template>

<script setup>
import { defineProps,  } from 'vue';
defineProps(['name'])
</script>

Input characters in both inputs.

The both inputs display "initial value", but only plain input can work correctly wint user input - all changes passed to model.
The <a-input> always displaying "initial value" and pass to model "initial value" with just pressed character.

### What is expected?
The behaviour should be as plain html input.

### What is actually happening?
The <a-input> always displaying "initial value" and pass to model "initial value" with just pressed character.

**Comment by CCherry07** [comment]
Hello, this is missing responsiveness ，no two-way binding ， so，you should

```ts
const model = ref({ name: "initial value" });
```
