### ISSUE TITLE
The issue with render class ant-upload-drag-container in the DOM

### ISSUE THREAD

**Issue by Dmytro-Lukashenko** [vueComponent/ant-design-vue#6417]
Hello!
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
Windows10, Chrome Version 111.0.5563.147, ant-design-vue 3.2.16; vue-3.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/a-upload-dragger-class-issue-nzg0v9?file=/src/App.vue)

### Steps to reproduce
There is an incorrect rendering of the class "ant-upload-drag-container" in the DOM. If we use an empty tag <a-upload-dragger></a-upload-dragger>, the empty <div> with class "[object Object]-drag-container" renders in the DOM.

### What is expected?
The class "ant-upload-dragger-container" should be rendered in the DOM

### What is actually happening?
The class "[object Object]-drag-container" renders in the DOM

---
This issue happens because of an error in string 397 of the Upload.tsx file.
<div class={${prefixCls}-drag-container}>{slots.default?.()}</div>
prefixCls - ComputedRef, not a string.
To fix this issue, we can modify the code to access the string value of the prefixCls object - prefixCls.value
My suggestion:
<div class={${prefixCls.value}-drag-container}>{slots.default?.()}</div>

**Comment by CCherry07** [comment]
我来看看

**Comment by Dmytro-Lukashenko** [comment]
Hi! Thanks for your comment! I think that this issue should be closed because my pull request https://github.com/vueComponent/ant-design-vue/pull/6413 was merged in the "main" branch
