### ISSUE TITLE
二维码组件在显示器进行了缩放，会导致二维码变形

### ISSUE THREAD

**Issue by jiyao8951** [vueComponent/ant-design-vue#6418]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-alpha.3

### Environment
Vue 3.2.47 ant-design-vue 4.0.0-alpha.3 浏览器chrome

### Reproduction link
[https://next.antdv.com/components/qrcode-cn](https://next.antdv.com/components/qrcode-cn)

### Steps to reproduce
在项目试验新版本中的二维码组件，发现不同分辨率的显示器，缩放比100%情况下，同尺寸二维码大小相同，但是显示器进行了缩放（比如125%缩放比），会导致二维码变形，不同分辨率下尺寸不一致，会导致内部canvas二维码超出边界显示不全

### What is expected?
能够保持和antd5.x中的效果一样就可以，经检查antd5.x的二维码组件不存在该问题

### What is actually happening?
二维码canvas不受控

**Comment by selicens** [comment]
看起来确实有这个问题
