### ISSUE TITLE
a-date-picker getPopupContainer bug

### ISSUE THREAD

**Issue by YDKD** [vueComponent/ant-design-vue#6419]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
Vue 3.2.47、Vite 4.1.4，Ant Design Vue 4.0.0-alpha.3、浏览器 Chroe

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/main/components/date-picker/generatePicker/generateSinglePicker.tsx](https://github.com/vueComponent/ant-design-vue/blob/main/components/date-picker/generatePicker/generateSinglePicker.tsx)

## 使用方式
<a-date-picker />

### What is expected?
能够显示出时间组件

### What is actually happening?
直接运行报错，检测代码报错内容大致如下：
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
at Proxy.<anonymous> (generateSinglePicker.js:207:82)
找到源码定位位置为：ant-design-vue/blob/main/components/date-picker/generatePicker/generateSinglePicker.tsx
227行： getPopupContainer={attrs.getCalendarContainer || getPopupContainer.value}

---
疑问：我在传递了 getPopupContainer之后，还是报错，
暂时解决报错方式： <a-date-picker  :getCalendarContainer="ev=> ev || ev.parentNode"/>

**Comment by YDKD** [comment]
暂时解决爆粗方式： <a-date-picker  :getCalendarContainer="ev=> ev || ev.parentNode"/>

**Comment by YDKD** [comment]
解决方式：传递了属性：:getCalendarContainer="ev=> ev || ev.parentNode"

**Comment by CCherry07** [comment]
这里是默认值没有写，我去提一个pr 

```ts
export const defaultConfigProvider: ConfigProviderInnerProps = {
  getPrefixCls: (suffixCls?: string, customizePrefixCls?: string) => {
    if (customizePrefixCls) return customizePrefixCls;
    return suffixCls ? `ant-${suffixCls}` : 'ant';
  },
  iconPrefixCls: computed(() => defaultIconPrefixCls),
 // getPopupContainer: computed(() => () => document.body),
};
```

**Comment by YDKD** [comment]
> 这里是默认值没有写，我去提一个pr
> 
> ```ts
> export const defaultConfigProvider: ConfigProviderInnerProps = {
>   getPrefixCls: (suffixCls?: string, customizePrefixCls?: string) => {
>     if (customizePrefixCls) return customizePrefixCls;
>     return suffixCls ? `ant-${suffixCls}` : 'ant';
>   },
>   iconPrefixCls: computed(() => defaultIconPrefixCls),
>  // getPopupContainer: computed(() => () => document.body),
> };
> ```

对的，按理来说应该是默认挂载到body的

**Comment by CCherry07** [comment]
这个是 antdv4.x 的问题吧，3.x没有

**Comment by YDKD** [comment]
> 这个是 antdv4.x 的问题吧，3.x没有

嗯嗯，说的就是4的问题
