### ISSUE TITLE
pagination分页器无效

### ISSUE THREAD

**Issue by leaf1992** [vueComponent/ant-design-vue#642]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
chrome（73.0.3683.86（正式版本） （64 位）），vue版本为2.5.2

### Reproduction link
[https://vue.ant.design/components/pagination-cn/#components-pagination-demo-jumper](https://vue.ant.design/components/pagination-cn/#components-pagination-demo-jumper)

### Steps to reproduce
按照官网demo，
```
<template>
<a-pagination
:pageSizeOptions="pageSizeOptions"
:total="total"
showSizeChanger
:pageSize="pageSize"
v-model="current"
@showSizeChange="onShowSizeChange"
>
<template slot='buildOptionText' slot-scope='props'>
<span v-if="props.value!=='50'">{{props.value}}条/页</span>
<span v-if="props.value==='50'">全部</span>
</template>
</a-pagination>
</template>
<script>
export default {
data() {
return {
pageSizeOptions: ['10', '20', '30', '40', '50'],
current: 1,
pageSize: 10,
total: 50,
}
},
methods: {
onShowSizeChange(current, pageSize) {
this.pageSize = pageSize
},
}
}
</script>
```
分页器一直就只有一页

### What is expected?
分页器应该按照total的值显示实际分页数

### What is actually happening?
不管total的值是多少，分页器永远只有一页

---
Table组件里的分页，或者单纯的pagination组件，都是这样，分页项的total值无效

**Comment by tangjinzhou** [comment]
直接复制的你的代码，没问题，如还有问题，麻烦提供复现链接
https://codesandbox.io/s/42oj041k44

**Comment by leaf1992** [comment]
抱歉，是我把total理解错了，我以为是total是总页数，原来是总条数，非常抱歉



在 2019-03-28 13:16:55，"tangjinzhou" <notifications@github.com> 写道：


直接复制的你的代码，没问题，如还有问题，麻烦提供复现链接
https://codesandbox.io/s/42oj041k44
