### ISSUE TITLE
SSR Support for version 4.x

### ISSUE THREAD

**Issue by nhatpdXkalapa** [vueComponent/ant-design-vue#6422]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-alpha,3

### Environment
ALL

### Reproduction link
[https://ant.design/docs/react/customize-theme#server-side-render-ssr](https://ant.design/docs/react/customize-theme#server-side-render-ssr)

### Steps to reproduce
https://ant.design/docs/react/customize-theme#server-side-render-ssr

### What is expected?
https://ant.design/docs/react/customize-theme#server-side-render-ssr

### What is actually happening?
https://ant.design/docs/react/customize-theme#server-side-render-ssr

**Comment by jiangmaniu** [comment]
Same problem, it works fine, but I need to adopt `Whole export` in nuxt project to support static style extraction. This problem prevents me from using antdv4 in nuxt3, if possible, would like to know if there is any other solution?

**Comment by nhatpdXkalapa** [comment]
@jiangmaniu Not that I know, it's just problem with CSS in JS in general. Hope that one day v4 will support Inline SSR mode

**Comment by jiangmaniu** [comment]
I don't understand why there would be such a strategy, the fact that this issue is not resolved, I don't want this issue to be closed

**Comment by nhatpdXkalapa** [comment]
@jiangmaniu Any idea on how to apply whole export yet brother?

**Comment by vietanhbui** [comment]
+1

**Comment by aibayanyu20** [comment]
duplicate #6659

**Comment by BillEliot** [comment]
有最新的方案了吗？nuxt3使用ant design vue 4？如何不再报 document is not defined 错误
