### ISSUE TITLE
txs下模式下，a-upload中的事件onRreview未生效

### ISSUE THREAD

**Issue by zhou5631** [vueComponent/ant-design-vue#6431]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
4.0.0-alpha.4

### Reproduction link
[https://next.antdv.com/components/upload-cn#API](https://next.antdv.com/components/upload-cn#API)

## 代码
```
(<a-upload {...props}
beforeUpload={beforeUpload}
fileList={fileList.value}
onReject={onReject}
onRemove={onRemove}
onRreview={onRreview}
onDownload={onRreview}
v-slots={{
...slots,
default: slots.default ? slots.default : () => (
props.disabled ? undefined : (
props.listType === 'picture-card' ?
createVNode(<div>
<a-icon type="plus" style="font-size: 32px;color: #999;"/>
<div style="margin-top: 8px;color: #666;">{props.text}</div>
</div>) :
createVNode(<div>
<a-button>
<a-icon type="upload"/>
{props.text}</a-button>
</div>)
)
)
}}

/>)
```

## 生效事件

```
onRemove | onChange
```
## 未生效事件

```
onRreview | onDownload
```

但是直接用
```
<a-upload
v-model:file-list="fileList"
action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
list-type="picture-card"
@preview="handlePreview"
>
```
@preview 是生效的，但我需要在TSX中监听onRreview 预览事件，不起作用的样子

### What is expected?
--

### What is actually happening?
--

**Comment by zhou5631** [comment]
# 不好意思，我的失误
```
onPreview
onRreview
```
单词拼写错了，打扰了

**Comment by CCherry07** [comment]
哪你可以关掉issue

**Comment by zhou5631** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> 3.3.0-beta.4
> 
> ### Environment
> 4.0.0-alpha.4
> 
> ### Reproduction link
> https://next.antdv.com/components/upload-cn#API
> 
> ### Steps to reproduce
> ## 代码
> ```
> (<a-upload {...props}
> beforeUpload={beforeUpload}
> fileList={fileList.value}
> onReject={onReject}
> onRemove={onRemove}
> onRreview={onRreview}
> onDownload={onRreview}
> v-slots={{
> ...slots,
> default: slots.default ? slots.default : () => (
> props.disabled ? undefined : (
> props.listType === 'picture-card' ?
> createVNode(<div>
> <a-icon type="plus" style="font-size: 32px;color: #999;"/>
> <div style="margin-top: 8px;color: #666;">{props.text}</div>
> </div>) :
> createVNode(<div>
> <a-button>
> <a-icon type="upload"/>
> {props.text}</a-button>
> </div>)
> )
> )
> }}
> 
> />)
> ```
> 
> ## 生效事件
> ```
> onRemove | onChange
> ```
> 
> ## 未生效事件
> ```
> onRreview | onDownload
> ```
> 
> 但是直接用
> 
> ```
> <a-upload
> v-model:file-list="fileList"
> action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
> list-type="picture-card"
> @preview="handlePreview"
> >
> ```
> 
> @Preview 是生效的，但我需要在TSX中监听onRreview 预览事件，不起作用的样子
> 
> ### What is expected?
> --
> 
> ### What is actually happening?
> --
