### ISSUE TITLE
Select组件使用getPopupContainer指定挂载容器为document.body或选择器选中的节点会报错

### ISSUE THREAD

**Issue by zhangyucha0** [vueComponent/ant-design-vue#6435]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
vue@3.2.47

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duo-xuan-ant-design-vue-3-2-16-forked-05uzhl?file=/src/demo.vue)

### Steps to reproduce
:getPopupContainer="() => document.getElementById('custom-container')"
:getPopupContainer="() => document.body"

### What is expected?
将popup挂载到指定的容器上

### What is actually happening?
控制台报错：
WARN：[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core ...

ERROR：Uncaught (in promise) TypeError: Cannot read properties of null (reading 'emitsOptions') ...

在codesandbox中直接fork官方示例并复现时，点击select框页面会崩溃

**Comment by CCherry07** [comment]
这里的问题是，模版无法捕获document的存在

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/79909910/230632937-76812e10-c056-45c1-9dde-5254e7b4acbc.png">

你可以在setup 里面去书写这个getPopupContainer函数，就能正常

**Comment by zhangyucha0** [comment]
> 这里的问题是，模版无法捕获document的存在
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/79909910/230632937-76812e10-c056-45c1-9dde-5254e7b4acbc.png">
> 
> 你可以在setup 里面去书写这个getPopupContainer函数，就能正常运行 https://codesandbox.io/s/duo-xuan-ant-design-vue-3-2-16-forked-m4mwqk?file=/src/demo.vue

thx
