### ISSUE TITLE
为什么树形控件Tree中绑定checkedKeys不能使用缩写 :checkedKeys,否则无法选中tree里的checkbox

### ISSUE THREAD

**Issue by goodapiyes** [vueComponent/ant-design-vue#6437]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
windows10，chrome111, Vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wjk9p2)

### Steps to reproduce

1. 打开Tree文档第一个Demo示例
https://codesandbox.io/s/wjk9p2

2.将v-model:selectedKeys="selectedKeys"换成:selectedKeys="selectedKeys"

结果：Tree无法被选中

### What is expected?
:selectedKeys="selectedKeys"

### What is actually happening?
缩写为啥会出问题？

**Comment by tangjinzhou** [comment]
因为这并不是缩写

**Comment by shayne2018go** [comment]
https://vuejs.org/guide/components/v-model.html
有没有可能 v-model:selectedKeys 等于 :selectedKeys + @update:selectedKeys
