### ISSUE TITLE
使用的4.0.0-alpha.3版本引入css报错使用tabs组件报错

### ISSUE THREAD

**Issue by sswws** [vueComponent/ant-design-vue#6440]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
vue3

### Reproduction link
[https://next.antdv.com/docs/vue/getting-started-cn](https://next.antdv.com/docs/vue/getting-started-cn)

### Steps to reproduce
我使用的vue3版本，4.0.0-alpha.3版本，引入import 'ant-design-vue/dist/antd.css';也会报错，使用tabs组件的时候也不会报错。TypeError: Cannot read properties of undefined (reading 'value')

### What is expected?
希望能给我提供一些解决方案

### What is actually happening?
我使用的vue3版本，4.0.0-alpha.3版本，引入import 'ant-design-vue/dist/antd.css';也会报错，使用tabs组件的时候也不会报错。TypeError: Cannot read properties of undefined (reading 'value')

**Comment by shifeng1993** [comment]
你是两个问题：

1. 引入antd.css报错
2. 使用tabs报错


问题1 ：
使用 `ant-design-vue/dist/reset.css` ，引入组件库初始化样式，v4版本已经切换到cssinjs，所以不会有组件样式引入了

问题2：
请提供报错截图或者复现环境

**Comment by pengyinghao** [comment]
css in js 应该不用引入css了。全是动态编译的，但是怎么动态换肤呢，我还在研究。

**Comment by shifeng1993** [comment]
> css in js 应该不用引入css了。全是动态编译的，但是怎么动态换肤呢，我还在研究。

现在文档还没有来得及写，可以先参考react，后面补全也会和react差不多，动态换肤使用可以参考 `site` 内的用法，从theme引入 useToken，如果只是css，图个方便，可以监听token变化，动态设置 css3 var变量
