### ISSUE TITLE
a-checkbox-group数据条数多时是，不会自动换行

### ISSUE THREAD

**Issue by zhou5631** [vueComponent/ant-design-vue#6444]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
4.x

### Reproduction link
[https://next.antdv.com/components/checkbox-cn](https://next.antdv.com/components/checkbox-cn)

### Steps to reproduce
```
<a-checkbox-group v-model:value="checkedList" :options="plainOptions" />
```
几条数据还好，一但数据量多些时，不会换行显示

### What is expected?
--

### What is actually happening?
--

---
--

**Comment by zhou5631** [comment]
我调试了一下，应该是由于这2个CSS造成的
```
:where(.css-dev-only-do-not-override-1tii49m).ant-checkbox-group{
    去掉 display: inline-flex;
  去掉 white-space: nowrap;
}
```

**Comment by zhou5631** [comment]
或者手动添加
```

<a-checkbox-group v-model:value="gatewayAppRouteIds" style="display: initial;white-space:initial">
```

这样可以自动换行，这个问题官方会考虑从底层解决么

**Comment by CCherry07** [comment]
@tangjinzhou  

我刚刚看了antd 没有这个属性，我们是否需要加上，我觉得是可以加上的，他会根据父盒子的宽度来 warp
<img width="306" alt="image" src="https://user-images.githubusercontent.com/79909910/231745043-a0880503-fb34-4eaa-a74a-16c7d859cac1.png">

**Comment by tangjinzhou** [comment]
@CCherry07 可以先给 antd 提个pr，如果只是我们加的话，后续同步的时候容易遗漏
