### ISSUE TITLE
Tree 组件

### ISSUE THREAD

**Issue by nyj000** [vueComponent/ant-design-vue#645]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
macOs 10.14.3 webpack vue2.6.6

### Reproduction link
Permission denied

### Steps to reproduce
tree选择组件
两个父节点，拥有相同key的子节点
1.两个父节点同时全选
2.其中一个父节点取消全选

### What is expected?
视图正常渲染，并且解决子节点显示错误后无法点击的问题

### What is actually happening?
此时选中的key是正常的，但是节点显示错误，重复key的子节点没有取消选中，并且无法进行点击选中、取消选中

**Comment by tangjinzhou** [comment]
确保节点全局唯一，不分层次
