### ISSUE TITLE
颜色选择器 为啥在文档中未体现

### ISSUE THREAD

**Issue by davy-gan** [vueComponent/ant-design-vue#6451]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
1x 2x 3x版本 都没有

### Reproduction link
[https://1x.antdv.com/components/form-cn/](https://1x.antdv.com/components/form-cn/)

### Steps to reproduce
官网文档

### What is expected?
在文档中体现color-pick的使用

### What is actually happening?
在文档中没有color-pick的使用

**Comment by davy-gan** [comment]
能否将颜色选择器在1x版本中也实现一个

**Comment by tangjinzhou** [comment]
推荐 https://github.com/Simonwep/pickr
