### ISSUE TITLE
Table component columns missing className property.

### ISSUE THREAD

**Issue by shiwanjun1995** [vueComponent/ant-design-vue#6452]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
none

### Reproduction link
[https://antdv.com/components/table-cn/#API](https://antdv.com/components/table-cn/#API)

### Steps to reproduce
https://antdv.com/components/table-cn/#API

### What is expected?
added

### What is actually happening?
missed

**Comment by CCherry07** [comment]
你可以提供一个demo吗？

**Comment by shiwanjun1995** [comment]
这还需要提供啥demo哇,就是table组件column属性缺少一个className属性呀.

**Comment by CCherry07** [comment]
这个我觉得你可以用customCell 去设置 class 属性，目前

**Comment by tangjinzhou** [comment]
文档也没说有 className 属性呀

**Comment by shiwanjun1995** [comment]
> 文档也没说有 className 属性呀

https://ant.design/components/table-cn#column
这里呢，大佬是不是漏掉了。

**Comment by grHand** [comment]
> 这个我觉得你可以用customCell 去设置 class 属性，目前 ， 我去pr 一个class 属性

className属性里直接设置是可以了，但是customCell的return里目前依然不生效，这里是不是忘记加上了？
