### ISSUE TITLE
Tree Checking is very slow and causes a large re-render when you have a lot of nodes expanded

### ISSUE THREAD

**Issue by iamBevan** [vueComponent/ant-design-vue#6453]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
Vue 3.2.47

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-http-60gv74?file=/src/App.vue)

### Steps to reproduce
Load ~1000 items into tree data and expand all the items, check the root level node

### What is expected?
The tree should be able to efficiently manage checking nodes when they have many expanded child items

### What is actually happening?
The tree takes 2-4 seconds to render the checkbox ticks and locks up the system

**Comment by hisuwh** [comment]
It would seem the virtual scroll implementation in the Vue 3 version is not the same as the React version.  
- In the React implementation of virtual scroll on the tree component it only renders nodes in the dom that are visible and removes those at the top as they become invisible
- In the Vue 3 version it only seems to add nodes as you scroll, meaning performance slowly degrades as you get further down (scrolling is also horrifically slow with a large tree as can be seen in the sandbox above).

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/hidden-platform-d181b7?file=/src/App.vue

please use number type  `:height="500"`
