### ISSUE TITLE
下拉框在侧轴基线对齐的弹性盒子中选中选项后错位

### ISSUE THREAD

**Issue by saatana97** [vueComponent/ant-design-vue#6461]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
win7，chrome 版本 112.0.5615.86（正式版本） （64 位），vue@3.2.45

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/suspicious-wave-l94293?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A33%2C%22startColumn%22%3A24%2C%22startLineNumber%22%3A33%7D%5D)

### Steps to reproduce
整个弹性盒，里面放个下拉框，和一个span当做标签，盒子侧轴方向设置基线对齐

### What is expected?
盒子被撑大了，下拉框位置下移

### What is actually happening?
盒子无变化，下拉框位置无变化

**Comment by saatana97** [comment]
flex container with style `align-items: baseline;`
append an invisible `span` element at first in component root element after focus
I think this action cause the problem
![image](https://user-images.githubusercontent.com/34677730/232017659-dfd7c80d-0532-4f1b-b3c5-19b946e0ba1a.png)

**Comment by CCherry07** [comment]
我来看看
