### ISSUE TITLE
Image组件手机端不支持滑动

### ISSUE THREAD

**Issue by momo2019** [vueComponent/ant-design-vue#6465]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
手机浏览器

### Reproduction link
[https://antdv.com/components/image-cn#API](https://antdv.com/components/image-cn#API)

### Steps to reproduce
点开查看图片，拖动图片，失效

### What is expected?
希望手机端能支持拖动

### What is actually happening?
手机端无法拖动

---
拉了源码自己改了一下，修改vc-image/src/Preview.tsx文件
在mouseMove，mouseDown，mouseUp的位置添加了touchMove，touchStart，touchEnd事件监听。
然后对touchEvent处理了一下，使用touches下的pageX，pageY。
注意touchEnd没有touches，要做undefined判断。

希望官方有时间能兼容一下

**Comment by CCherry07** [comment]
antdv 目前是pc 的解决方案
