### ISSUE TITLE
Select 组件重新渲染产生空白

### ISSUE THREAD

**Issue by IvanLuLyf** [vueComponent/ant-design-vue#6470]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
any os, FireFox 111, vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-feather-fgjnh7?file=/src/App.vue)

### Steps to reproduce
https://fgjnh7.csb.app/

点击测试页面中的Act1，然后点开下拉框，将选项滚动到底部
点击Act2，然后点开下拉框
然后再次点击Act1，此时打开下拉框出现大面积空白，滚动鼠标滚轮后恢复正常

![image](https://user-images.githubusercontent.com/5052848/232389627-aec8a694-a29c-4dbc-80a1-d41e708ef37c.png)

### What is expected?
应该正常渲染

### What is actually happening?
虚拟滚动列表应该重新处理偏移量

**Comment by CCherry07** [comment]
我来看看
