### ISSUE TITLE
源码包进行pubsite或者site无法静态出离线文档

### ISSUE THREAD

**Issue by db46rt00ors** [vueComponent/ant-design-vue#6473]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
nodejs  v16.17

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/3.2.16](https://github.com/vueComponent/ant-design-vue/tree/3.2.16)

### Steps to reproduce
下载源码包，版本3.2.16，安装依赖后，运行命令 yarn run pub:site 或者 yarn run site后无法静态出离线手册
![Snipaste_2023-04-17_21-29-43](https://user-images.githubusercontent.com/22002911/232500041-477d93e3-56f7-43b9-ac67-8fd396fe6f49.png)

### What is expected?
可以静态出离线手册

### What is actually happening?
运行报错

**Comment by huangd-d** [comment]
我尝试了  node 14.21.3  16.14.0  18.12.0  都无法运行。 
![image](https://user-images.githubusercontent.com/30265575/233984983-607c7a17-6949-4cab-a9e9-f9b0a4d8e396.png)

**Comment by hdygxsj** [comment]
后来解决了吗
