### ISSUE TITLE
a-range-picker 不调用change事件 

### ISSUE THREAD

**Issue by zhongyu-y** [vueComponent/ant-design-vue#6476]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
vue:3.2.37, 谷歌：111.0.5563.146， macos

### Steps to reproduce
打包部署后，使用a-range-picker不触发change事件

### What is expected?
打包部署后，使用a-range-picker可以触发change事件

### What is actually happening?
打包部署后，使用a-range-picker不触发change事件

**Comment by CCherry07** [comment]
现在，还有这个问题吗？你可以提供一个demo 吗？

**Comment by fengjianying** [comment]
请问你解决了嘛 我也出现同样的问题了
