### ISSUE TITLE
Transfer with tree to close checkStrictly

### ISSUE THREAD

**Issue by 19msf** [vueComponent/ant-design-vue#6477]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.4

### Environment
win11、vue3.2.45

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yn5fb8?file=/src/demo.vue)

### Steps to reproduce
tree属性checkStrictly为false，选中父节点后再取消子节点，子节点状态为发生变化

### What is expected?
选中父节点后再取消子节点，父子节点状态关联

### What is actually happening?
节点状态取消了，但状态未发生改变

**Comment by CCherry07** [comment]
你是否是需要这样的？https://codesandbox.io/s/shu-chuan-suo-kuang-ant-design-vue-3-2-16-forked-bitwyx?file=/src/demo.vue
