### ISSUE TITLE
ant-design-vue 4怎么定制主题

### ISSUE THREAD

**Issue by L-Z-Y** [vueComponent/ant-design-vue#6479]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
之前用3.x 的时候@import "ant-design-vue/dist/antd.variable.less";覆盖样式没问题，现在4里面已经找不到这个样式文件了，请问4里面应该怎么定制样式

### What does the proposed API look like?
期望尽快完善相关文档

**Comment by CCherry07** [comment]
有一个文档pr了，你目前可以参阅一下
#6468
