### ISSUE TITLE
input-number using precision attribute was formatted before losing focus in safari, but is normal in google 

### ISSUE THREAD

**Issue by Gcalolin** [vueComponent/ant-design-vue#6481]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
the problemcan be reproduced directly on the official website.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-chaplygin-olld3y?file=/src/App.vue)

### Steps to reproduce
https://next.antdv.com/components/input-number-cn/#components-input-number-demo-digit

### What is expected?
in safari, input-number using precision attribute should be formatted after blur but  should not be formatted  when inputing

### What is actually happening?
in safari, input-number using precision attribute was formatted when inputing

**Comment by liy-1994** [comment]
同样出现了这个问题，请问如何解决的？

**Comment by liy-1994** [comment]
I have also encountered this problem. May I ask how you can solve it
