### ISSUE TITLE
vue 表格数据量大，滚动数据的时候样式渲染导致卡顿

### ISSUE THREAD

**Issue by efrontend** [vueComponent/ant-design-vue#6482]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-table 组件数据量大 onMouseEnter 加class会严重阻塞表格单元格渲染，能关闭这个效果吗？
ant-design-vue@1.7.5
vue@2.x

### What does the proposed API look like?
const TdCell = (props) => {
const { onMouseEnter, onMouseLeave, ...restProps } = props;
console.log(restProps)
return h('td',{...restProps}) // return <td {...restProps} />;
}
这个方法我在1.7.5无法使用

**Comment by efrontend** [comment]
@tangjinzhou  大佬，给看看问题，vue有解决这个问题的方法吗？

**Comment by tangjinzhou** [comment]
1.x 不再新增功能，升级 vue3，使用 [surely vue](https://www.surely.cool/)
