### ISSUE TITLE
a-table在嵌套表格时,子表格配置了:scroll="{ x: 'max-content' }"会导致子表格的column里面的ellipsis、resizable属性不生效

### ISSUE THREAD

**Issue by qhl123456** [vueComponent/ant-design-vue#6485]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.1.0

### Environment
Vue 3.2.25 Google112.0.5615.137

### Reproduction link
[https://gitee.com/cc-2018_admin/a-table-demo](https://gitee.com/cc-2018_admin/a-table-demo)

### Steps to reproduce
外层a-table使用a-table，在expandedRowRender插槽里再套用一个a-table，此时会发现子表格横向滚动时父表格也在滚动，为子表格增加:scroll="{ x: 'max-content' }"后，子表格配置好的column的ellipsis、resizable属性失效，并且最右侧的固定列在横向滚动时滚动到最右侧会晃动一下

### What is expected?
子表格配置好的column的ellipsis、resizable属性生效

### What is actually happening?
外层table使用a-table，在expandedRowRender插槽里再套用一个a-table，此时会发现子表格横向滚动时父表格也在滚动，为子表格增加:scroll="{ x: 'max-content' }"后，子表格配置好的column的ellipsis、resizable属性失效，并且最右侧的固定列在横向滚动时滚动到最右侧会晃动一下

**Comment by qhl123456** [comment]
我尝试把max-content改为:scroll="{ x: '100%' }" 也还是不行，并且子表格滑动到最右侧会有部分留白

**Comment by tangjinzhou** [comment]
使用  codesandbox 提供在线示例

**Comment by qhl123456** [comment]
https://codesandbox.io/s/determined-pascal-0l1dp4?file=/src/App.vue

**Comment by qhl123456** [comment]
如果我把最右侧的fixed: "right",去掉 滚动到最右侧晃动的问题会消失，也不会有留白，但是ellipsis、resizable属性仍然不生效，:scroll="{ x:true }"设置也不可以

**Comment by qhl123456** [comment]
> 使用 codesandbox 提供在线示例

https://codesandbox.io/s/determined-pascal-0l1dp4?file=/src/App.vue

**Comment by qhl123456** [comment]
@CCherry07 @tangjinzhou 大佬们有空看看这个问题吗？

**Comment by CCherry07** [comment]
<img width="1440" alt="imag@qhl123456 " src="https://user-images.githubusercontent.com/79909910/236783074-f03653e8-0303-40d5-b5ac-a89a964d15fb.png">

@qhl123456  这个样子

**Comment by CCherry07** [comment]
@qhl123456  你目前可以这样去写

```js
	// @resizeColumn = 'handleResizeColumn'
	// :scroll="{ x: '100%' }"
    const handleResizeColumn = (w,column)=>{
      settleTableColumns.value = settleTableColumns.value.map(item=>{
        if(item.key === column.key){
          item.width = w;
        }
        return item;
      });
    };
```

**Comment by qhl123456** [comment]
> @qhl123456 你目前可以这样去写 https://antdv.com/components/table-cn/#%E4%BA%8B%E4%BB%B6
> 
> ```js
> 	// props
> 	// @resizeColumn = 'handleResizeColumn'
> 	// :scroll="{ x: '100%' }"
>     const handleResizeColumn = (w,column)=>{
>       settleTableColumns.value = settleTableColumns.value.map(item=>{
>         if(item.key === column.key){
>           item.width = w;
>         }
>         return item;
>       });
>     };
> ```

这样拖拽的时候滚动条位置好奇怪，滚动条也会同步滚动，大佬可以设置完试一下，如果这样的话我感觉还不如就按照之前不生效的来，这样体验感觉差了好多

**Comment by qhl123456** [comment]
是的，macos我看也是正常的，但是windows是有问题的




1092750452
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午5:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] a-table在嵌套表格时,子表格配置了:scroll="{ x: 'max-content' }"会导致子表格的column里面的ellipsis、resizable属性不生效 (Issue #6485)





 

 
@qhl123456  这个样子

**Comment by tangjinzhou** [comment]
max-content 不就是让ellipsis 失效的嘛，尽可能宽

**Comment by CCherry07** [comment]
我这里似乎没有滚动条，你提供一下截图效果图？或者一个gif @qhl123456

**Comment by qhl123456** [comment]
> max-content 不就是让ellipsis 失效的嘛，尽可能宽
但是设置100%也不行是为什么呢？

**Comment by qhl123456** [comment]
> 我这里似乎没有滚动条，你提供一下截图效果图？或者一个gif @qhl123456

大佬方便留个邮箱吗？我发给你

**Comment by qhl123456** [comment]
> 我这里似乎没有滚动条，你提供一下截图效果图？或者一个gif @qhl123456

/

> 我这里似乎没有滚动条，你提供一下截图效果图？或者一个gif @qhl123456


https://user-images.githubusercontent.com/74643840/237020667-88aaae1e-84a3-4a81-8980-616245dd2778.mp4

**Comment by CCherry07** [comment]
这里是属于正常的，因为你的拖拉，他的header宽度变大了自然这个滚动条会被变宽，如果你嫌弃他丑的话，可以自己给滚动条写一个样式，或者直接去掉，使用拖拉内容的方式，也是可以的

**Comment by qhl123456** [comment]
> @qhl123456 这里是属于正常的，因为你的拖拉，他的header宽度变大了自然这个滚动条会被变宽，如果你嫌弃他丑的话，可以自己给滚动条写一个样式，或者直接去掉，使用拖拉内容的方式，也是可以的

好的，我还是加个滚动样式把，谢谢大佬
