### ISSUE TITLE
如何编译打包自己的ant-design-vue项目版本

### ISSUE THREAD

**Issue by kazaff** [vueComponent/ant-design-vue#6486]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.17

### Environment
mac os 13.3.1

### Reproduction link
[https://github.com/kazaff/ant-design-vue](https://github.com/kazaff/ant-design-vue)

### Steps to reproduce
无法完成 `npm run compile`命令

### What is expected?
期望能打包出自己的ant-design-vue版本，因为根据我的需要，我调整了一些组件的实现（如year picker）。

### What is actually happening?
异常退出：
```
kazaff@kazaffdeMacBook-Pro ant-design-vue % npm run compile

> ant-design-vue@3.2.17 precompile
> npm run version


> ant-design-vue@3.2.17 version
> node ./scripts/generate-version


> ant-design-vue@3.2.17 compile
> node antd-tools/cli/run.js compile

antd-tools run compile
start compile at  2023-04-21T03:55:43.248Z
[Parallel] Compile to es...
[Parallel] Compile to js...
components/mentions/index.tsx(207,47): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }, ... 11 more ..., { ...; }>'.
      Type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }>> & { ...; }, ... 10 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
components/table/index.tsx(19,41): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{}, () => Element, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, {}, string, Readonly<...> & { ...; }, {}>'.
      Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{}>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, () => Element, {}, {}, {}, ComponentOptionsMixin, ... 5 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
components/table/index.tsx(20,42): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<Readonly<ComponentPropsOptions<Data>>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., { ...; } | {}>'.
      Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, ... 10 more ..., string>'.
        Types of property 'setup' are incompatible.
          Type '(this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { attrs: Data; slots: Readonly<InternalSlots>; emit: (event: string, ...args: any[]) => void; expose: (exposed?: Record<...>) => void; }) => void | ... 2 more ... | Promise<...>' is not assignable to type '(this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>'.
            Types of parameters 'props' and 'props' are incompatible.
              Type 'Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>' is missing the following properties from type 'Readonly<LooseRequired<Readonly<SummaryCellProps>>>': index, colSpan, rowSpan, align
components/tree/index.tsx(29,34): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }, ... 11 more ..., { ...; }>'.
      Type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }>> & { ...; }, ... 10 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
              Type 'ThisType<void>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.
components/mentions/index.tsx(207,47): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }, ... 11 more ..., { ...; }>'.
      Type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }>> & { ...; }, ... 10 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
components/table/index.tsx(19,41): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{}, () => Element, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, {}, string, Readonly<...> & { ...; }, {}>'.
      Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{}>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, () => Element, {}, {}, {}, ComponentOptionsMixin, ... 5 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
components/table/index.tsx(20,42): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<Readonly<ComponentPropsOptions<Data>>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., { ...; } | {}>'.
      Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, ... 10 more ..., string>'.
        Types of property 'setup' are incompatible.
          Type '(this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { attrs: Data; slots: Readonly<InternalSlots>; emit: (event: string, ...args: any[]) => void; expose: (exposed?: Record<...>) => void; }) => void | ... 2 more ... | Promise<...>' is not assignable to type '(this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>'.
            Types of parameters 'props' and 'props' are incompatible.
              Type 'Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>' is missing the following properties from type 'Readonly<LooseRequired<Readonly<SummaryCellProps>>>': index, colSpan, rowSpan, align
components/tree/index.tsx(29,34): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }, ... 11 more ..., { ...; }>'.
      Type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }>> & { ...; }, ... 10 more ..., string>'.
        Types of property 'emits' are incompatible.
          Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
            Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
              Type 'ThisType<void>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.
TypeScript: 4 semantic errors
TypeScript: emit succeeded (with errors)

```

**Comment by tangjinzhou** [comment]
不知道你改了什么，如果直接拉代码后能打包，那就是你改出了问题

**Comment by kazaff** [comment]
我直接拉去代码后打包，也不行。
但我如果不打包，而是`npm run dev`，我修改的代码是不会导致问题的。

**Comment by kazaff** [comment]
另外，我修改的内容：

https://github.com/vueComponent/ant-design-vue/pull/6489

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/commit/c36b69d7bd4bfb09264cc7685d23cc474744072d

**Comment by zerobin** [comment]
同样的问题，我直接拉代码，无任何修改，也是报ts问题：
components\list\index.tsx(90,3): error TS2769: No overload matches this call.
  The last overload gave the following error.
    Type 'string[]' has no properties in common with type 'SlotsType<Record<string, any>>'.
components\list\index.tsx(317,6): error TS2339: Property 'install' does not exist on type '(props: Record<string, any> & {}) => any'.
components\list\index.tsx(319,22): error TS2339: Property 'Item' does not exist on type '(props: Record<string, any> & {}) => any'.
components\list\index.tsx(319,38): error TS2339: Property 'Item' does not exist on type '(props: Record<string, any> & {}) => any'.
components\list\index.tsx(320,22): error TS2339: Property 'Item' does not exist on type '(props: Record<string, any> & {}) => any'.
components\list\index.tsx(320,43): error TS2339: Property 'Item' does not exist on type '(props: Record<string, any> & {}) => any'.

**Comment by zerobin** [comment]
> * [x]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> 3.2.17
> 
> ### Environment
> mac os 13.3.1
> 
> ### Reproduction link
> https://github.com/kazaff/ant-design-vue
> 
> ### Steps to reproduce
> 无法完成 `npm run compile`命令
> 
> ### What is expected?
> 期望能打包出自己的ant-design-vue版本，因为根据我的需要，我调整了一些组件的实现（如year picker）。
> 
> ### What is actually happening?
> 异常退出：
> 
> ```
> kazaff@kazaffdeMacBook-Pro ant-design-vue % npm run compile
> 
> > ant-design-vue@3.2.17 precompile
> > npm run version
> 
> 
> > ant-design-vue@3.2.17 version
> > node ./scripts/generate-version
> 
> 
> > ant-design-vue@3.2.17 compile
> > node antd-tools/cli/run.js compile
> 
> antd-tools run compile
> start compile at  2023-04-21T03:55:43.248Z
> [Parallel] Compile to es...
> [Parallel] Compile to js...
> components/mentions/index.tsx(207,47): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }, ... 11 more ..., { ...; }>'.
>       Type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }>> & { ...; }, ... 10 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
> components/table/index.tsx(19,41): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{}, () => Element, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, {}, string, Readonly<...> & { ...; }, {}>'.
>       Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{}>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, () => Element, {}, {}, {}, ComponentOptionsMixin, ... 5 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
> components/table/index.tsx(20,42): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<Readonly<ComponentPropsOptions<Data>>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., { ...; } | {}>'.
>       Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, ... 10 more ..., string>'.
>         Types of property 'setup' are incompatible.
>           Type '(this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { attrs: Data; slots: Readonly<InternalSlots>; emit: (event: string, ...args: any[]) => void; expose: (exposed?: Record<...>) => void; }) => void | ... 2 more ... | Promise<...>' is not assignable to type '(this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>'.
>             Types of parameters 'props' and 'props' are incompatible.
>               Type 'Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>' is missing the following properties from type 'Readonly<LooseRequired<Readonly<SummaryCellProps>>>': index, colSpan, rowSpan, align
> components/tree/index.tsx(29,34): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }, ... 11 more ..., { ...; }>'.
>       Type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }>> & { ...; }, ... 10 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>               Type 'ThisType<void>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.
> components/mentions/index.tsx(207,47): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }, ... 11 more ..., { ...; }>'.
>       Type '{ name: string; props: { value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ value: StringConstructor; disabled: BooleanConstructor; label: (FunctionConstructor | StringConstructor | NumberConstructor)[]; }>> & { ...; }, ... 10 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
> components/table/index.tsx(19,41): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{}, () => Element, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, string[], string, {}, string, Readonly<...> & { ...; }, {}>'.
>       Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<{}>>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{}>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, () => Element, {}, {}, {}, ComponentOptionsMixin, ... 5 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
> components/table/index.tsx(20,42): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<Readonly<ComponentPropsOptions<Data>>, {}, {}, {}, {}, ComponentOptionsMixin, ComponentOptionsMixin, ... 5 more ..., { ...; } | {}>'.
>       Type '{ name: string; __isFragment?: never; __isTeleport?: never; __isSuspense?: never; setup?: (this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>; ... 54 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }, ... 10 more ..., string>'.
>         Types of property 'setup' are incompatible.
>           Type '(this: void, props: Readonly<LooseRequired<Readonly<SummaryCellProps>>>, ctx: { attrs: Data; slots: Readonly<InternalSlots>; emit: (event: string, ...args: any[]) => void; expose: (exposed?: Record<...>) => void; }) => void | ... 2 more ... | Promise<...>' is not assignable to type '(this: void, props: Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>, ctx: { ...; }) => void | ... 2 more ... | Promise<...>'.
>             Types of parameters 'props' and 'props' are incompatible.
>               Type 'Readonly<LooseRequired<Readonly<ExtractPropTypes<Readonly<ComponentPropsOptions<Data>>>> & { [x: string & `on${string}`]: (...args: any[]) => any; }>>' is missing the following properties from type 'Readonly<LooseRequired<Readonly<SummaryCellProps>>>': index, colSpan, rowSpan, align
> components/tree/index.tsx(29,34): error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to parameter of type 'ComponentOptionsWithObjectProps<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }, ... 11 more ..., { ...; }>'.
>       Type '{ name: string; props: { eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }; ... 58 more ...; tabindex?: string | number; }' is not assignable to type 'ComponentOptionsBase<Readonly<ExtractPropTypes<{ eventKey: (StringConstructor | NumberConstructor)[]; prefixCls: StringConstructor; title: VueTypeValidableDef<any>; ... 13 more ...; domRef: { ...; }; }>> & { ...; }, ... 10 more ..., string>'.
>         Types of property 'emits' are incompatible.
>           Type '({} | string[]) & ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>             Type 'ThisType<void>' is not assignable to type 'string[] & ThisType<void>'.
>               Type 'ThisType<void>' is missing the following properties from type 'string[]': length, pop, push, concat, and 28 more.
> TypeScript: 4 semantic errors
> TypeScript: emit succeeded (with errors)
> ```

你这个问题解决了吗？
