### ISSUE TITLE
Modal是否可以支持before-close的回调

### ISSUE THREAD

**Issue by Wayne529** [vueComponent/ant-design-vue#6492]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前的Modal的回调中只有afterClose 关闭后的回调，但使用场景上，很多时候需要关闭前的回调：before-close。比如我关闭的是个比较关键的Modal，需要用户二次确认是否关闭，那么就需要在关闭前弹出一个confirm而不关闭当前的Modal。在confirm的确定后才可关闭改Modal。
另外element-ui是有before-close这个回调API的，希望antd也能支持，谢谢！

### What does the proposed API look like?
before-close

**Comment by CCherry07** [comment]
你这个场景可以自己控制open的开与闭

**Comment by tangjinzhou** [comment]
3.x 用 visible

**Comment by CCherry07** [comment]
你可以对visible不做双向绑定，状态自己管理 @Wayne529

**Comment by Wayne529** [comment]
> 你可以对visible不做双向绑定，状态自己管理 @Wayne529

好的 谢谢 已将v-model:visible=“visible” 改为 :visible="visible"，问题解决
