### ISSUE TITLE
升级vs code volar插件到1.4.1版本后，所有组件都会报类型错误

### ISSUE THREAD

**Issue by yyqxjwxy** [vueComponent/ant-design-vue#6493]
希望官方看一下这个问题，以下是modal组件的类型报错

类型“{ width: number; title: string; visible: boolean; destroyOnClose: true; }”的参数不能赋给类型“App<any> & Partial<{ visible: boolean; mask: boolean; closable: boolean; forceRender: boolean; getContainer: string | false | HTMLElement | (() => HTMLElement); ... 7 more ...; confirmLoading: boolean; }> & Omit<...> & Record<...>”的参数。
类型“{ width: number; title: string; visible: boolean; destroyOnClose: true; }”缺少类型“App<any>”的以下属性: version, config, use, mixin 及其他 11 项。ts(2345)

**Comment by lucystwt** [comment]
我也有相同的问题

**Comment by qhl123456** [comment]
这个volar降低到1.2.0版本就好了,而且这是volar的问题，跟antd没什么关系，这个issue也不应该提到这里啊

**Comment by yyqxjwxy** [comment]
> 这个volar降低到1.2.0版本就好了,而且这是volar的问题，跟antd没什么关系，这个issue也不应该提到这里啊

是的，确实是这个问题，我司用的还是3.2.6的版本太旧了，而且现在volar已经发布了新版本已经没有这个问题了

**Comment by yyqxjwxy** [comment]
@lucystwt 升级新版本就好
