### ISSUE TITLE
With Transfer Tree component, child nodes auto selected but not transferred 

### ISSUE THREAD

**Issue by igorfraa** [vueComponent/ant-design-vue#6495]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.18

### Environment
Vue 3.2.13, AntDV 3.2.17, Chrome Version 112.0.5615.121

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-merkle-x40n55?file=/src/components/HelloWorld.vue)

### Steps to reproduce
1. Get code from Tree Transfer sample (https://www.antdv.com/components/transfer) or codesandbox.io link
2. edit to remove "check-strictly" from a-tree template
3. Select parent node '0-1' and see children nodes (0-1-0, 0-1-1) selected
4. Tap ">" button

### What is expected?
All selected nodes go to the right panel: 0-1, 0-1-0, 0-1-1

### What is actually happening?
Only the explicitly selected nodes go to the right panel.
It could be parent node 0-1, if one manually click the child - that also go to the right.

---
Unfortunately I was not able to make codesandbox.io live, but setup is really basic.

**Comment by igorfraa** [comment]
Would also appreciate any workaround suggestions.

**Comment by igorfraa** [comment]
Seems I could manipulate targetKeys array to put items to the right panel and bind this to `@change`, however this does not working for "left" direction transfer cause `@change` is not provided with currently selected keys

**Comment by CCherry07** [comment]
ok. You can check out this demo

https://codesandbox.io/s/shu-chuan-suo-kuang-ant-design-vue-3-2-16-forked-bitwyx?file=/src/demo.vue

**Comment by igorfraa** [comment]
@CCherry07 it's a great catch. 

Could you please point me where `onItemSelect` is documented?

**Comment by CCherry07** [comment]
How do I view records?
You should use the onChange event.
https://antdv.com/components/transfer#events
