### ISSUE TITLE
I encounter an error message that does not disappear even when I enter the correct input.

### ISSUE THREAD

**Issue by LongGGEZ** [vueComponent/ant-design-vue#6496]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

        
        
### Version
3.2.19

### Environment
- Device: Macbook Pro 2017 - OS Version: macOS Version 13.2 (22D49) - Browser: Chrome Version 112.0.5615.137

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/login-form-ant-design-vue-3-2-18-forked-er9bwj)

### Steps to reproduce
I encountered an error where the error message does not disappear when entering the correct input in the form. I'm not sure about the cause of this error, but I can provide some images of it.

### What is expected?
The error is hidden and when entered correctly

### What is actually happening?
The error message does not disappear on its own, and one has to click outside or switch to another input to hide it.

![img_v2_c26cba31-b5f5-4dd1-82bf-f0670971a79h](https://user-images.githubusercontent.com/57658187/233984148-409e3b83-0d0e-4a4c-9d58-b295544332d0.png)
![img_v2_78e5edd1-3870-4f70-8ecf-357b4d57f3bh](https://user-images.githubusercontent.com/57658187/233984198-c6ba38e0-776a-4988-be9e-b5bcb1a571f3.png)
![img_v2_0f8c41b5-8070-4de7-b492-ad77b84be06h](https://user-images.githubusercontent.com/57658187/233984238-2be091b6-8169-473c-9eaa-271f1893457d.png)

**Comment by CCherry07** [comment]
You should add a trigger

```ts
{ type: 'email', message: 'Invalid', trigger: 'blur' },
```
