### ISSUE TITLE
[Bug][Upload] Can NOT choose image from Album on iPhone Safari

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#6501]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.3.0-beta.4

### Environment
offcial website

### Reproduction link
[https://antdv.com/components/upload-cn#API](https://antdv.com/components/upload-cn#API)

### Steps to reproduce
1. open reproduction link with iPhone safari
2. click a Upload component

### What is expected?
could choose image from Album

### What is actually happening?
camera opened, only can upload image by camera

## Root Cause
According to `Upload` props, [capture](https://github.com/vueComponent/ant-design-vue/blob/ca0d8cc7c1361fdccc69e44f09439e9d568e41f7/components/vc-upload/interface.tsx#L9) should be false by default.
```
export const uploadProps = () => {
  return {
    capture: [Boolean, String] as PropType<boolean | 'user' | 'environment'>,        // <=== here
    multipart: { type: Boolean, default: undefined },
    name: String,
```

But [AjaxUploader use null](https://github.com/vueComponent/ant-design-vue/blob/ca0d8cc7c1361fdccc69e44f09439e9d568e41f7/components/vc-upload/AjaxUploader.tsx#L311) as default

```
        <Tag {...events} class={cls} role="button" style={attrs.style}>
          <input
            {...pickAttrs(otherProps, { aria: true, data: true })}
            id={id}
            type="file"
            ref={fileInput}
            onClick={e => e.stopPropagation()} // https://github.com/ant-design/ant-design/issues/19948
            key={uid.value}
            style={{ display: 'none' }}
            accept={accept}
            {...dirProps}
            multiple={multiple}
            onChange={onChange}
            {...(capture != null ? { capture } : {})}           // <=== here
          />
          {slots.default?.()}
        </Tag>
```

**Comment by tangjinzhou** [comment]
try  accept={null}

**Comment by gaokun** [comment]
already use capture=null as workaround
