### ISSUE TITLE
Notification组件使用getContainer方法挂载到一个可销毁的组件之上，会导致下次开启Notification的时候不生效

### ISSUE THREAD

**Issue by wujiaming123** [vueComponent/ant-design-vue#6503]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.2

### Environment
vue3

### Reproduction link
[https://www.antdv.com/components/notification](https://www.antdv.com/components/notification)

### Steps to reproduce
例如有一个列表组件，我将Notification通过getContainer挂载到list节点下，点击列表项出现提示框，当我关掉列表之后，再次打开列表，点击列表项，提示框就出不来了

### What is expected?
提示框无论怎样调用显示的方法就要显示

### What is actually happening?
销毁挂载组件之后提示框未显示

---
no

**Comment by tangjinzhou** [comment]
预期行为
