### ISSUE TITLE
Pagination分页组件在simple简洁模式下切换页码change事件不触发

### ISSUE THREAD

**Issue by anke117** [vueComponent/ant-design-vue#6504]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
vue: 3.2.36, antd-vue: 3.2.16, Microsoft Edge: 版本 112.0.1722.58 (正式版本) (x86_64)

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/feat-v3.3](https://github.com/vueComponent/ant-design-vue/tree/feat-v3.3)

### Steps to reproduce
<template>
<a-pagination
v-model:current="current"
simple
:total="50"
@change="changeInfo"
/>
</template>

<script>
import { ref } from "vue";
export default {
name: "App",
setup() {
const current = ref(2);
const changeInfo = () => {
console.log(12);
};
return {
current,
changeInfo,
};
},
};
</script>
codesandbox：https://codesandbox.io/s/dazzling-bardeen-6vygsh?file=/src/App.vue

### What is expected?
触发change事件

### What is actually happening?
不触发change事件

---
https://codesandbox.io/s/dazzling-bardeen-6vygsh?file=/src/App.vue

**Comment by zhengsixsix** [comment]
啊这。。。。 输入页码你摁下了enter了吗？ 我通过你的链接复现是正常的

**Comment by anke117** [comment]
> 啊这。。。。 输入页码你摁下了enter了吗？ 我通过你的链接复现是正常的
设计就是这样嘛。。我以为修改输入框输入页码之后，失去焦点就会触发change。还要按个enter
