### ISSUE TITLE
dropdown下拉项为空

### ISSUE THREAD

**Issue by li9269391** [vueComponent/ant-design-vue#651]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
Mac:10.12.6  
chrome:73.0.3683.86 
Vue:2.5.17 
ant-design-vue:1.3.17
webpack: 3.10.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/zr757w346x)

### Steps to reproduce
其它组件正常，只有这个组件有问题，构建也没报错，我提供的网页编辑器上无法重现

### What is expected?
有下拉项

### What is actually happening?
无

---
其它 API 也正常触发事件，鼠标移上去，有 dom 节点变化，里面为空
`  <div style="position: absolute; top: 0px; left: 0px; width: 100%;"><!----></div>`

**Comment by wangxueliang** [comment]
从提供链接看，说明组件自身没问题
ps： 好好检查一下自己的业务代码

**Comment by tangjinzhou** [comment]
@li9269391 
https://github.com/vueComponent/ant-design-vue/issues/103#issuecomment-447626741
你应该确保使用的vue，是同一个版本参考上面那个链接，这块后续我们会优化

**Comment by li9269391** [comment]
@tangjinzhou Confirmation is the problem.

**Comment by 50l3r** [comment]
I have the same issue:

ant-design-vue: 1.3.16
vue: 2.6.10

This is my webpack alias config:

    resolve: {
        alias: {
            '@': path.join(__dirname, '../src/renderer'),
            'vue$': 'vue/dist/vue.esm.js',
        },
        extensions: ['.js', '.vue', '.json', '.css', '.node'],
    },

I try to downgrade vue but problem persist:

![](https://i.gyazo.com/89192658518f50ce0120aa2428f2201e.png)

**Comment by 50l3r** [comment]
updating to 1.3.17-beta.1 solves the problem 👍

**Comment by tangjinzhou** [comment]
最新版本已经解决该类问题
