### ISSUE TITLE
在v4版本中命令式组件切换暗色后没有生效

### ISSUE THREAD

**Issue by eatfishs** [vueComponent/ant-design-vue#6512]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
  
![1682592147321](https://user-images.githubusercontent.com/45836182/234841389-9d1e3b25-3c33-4b5a-84c1-8075cc371cb7.png)

### Environment
V4.0.0-alpha.5

### Reproduction link
[https://next.antdv.com/components/modal-cn](https://next.antdv.com/components/modal-cn)

### Steps to reproduce
切换到暗色模式，点击信息提示

### What is expected?
期望 Modal.info 组件样式是暗色的

### What is actually happening?
Modal.info 组件样式是亮色的

**Comment by CCherry07** [comment]
你可以看一下这里 

https://next.antdv.com/components/modal-cn#FAQ

**Comment by tangjinzhou** [comment]
update to 4.0.0-beta.1
