### ISSUE TITLE
in TSX  Card Components  cover slot not work

### ISSUE THREAD

**Issue by miaolin1993** [vueComponent/ant-design-vue#6523]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue:3.2.47
unplugin-vue-components:0.24.1
 vite:4.1.4 
@vitejs/plugin-vue-jsx:3.0.1 
typescript:4.8.4
chrome

### Reproduction link
[https://www.antdv.com/docs/vue/introduce-cn](https://www.antdv.com/docs/vue/introduce-cn)

### Steps to reproduce
```
<a-card hoverable style="width: 240px;height: 600px;">
    {{
       cover: () => {
          return <img style="width: 180px" src={'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png'} />
       }
    }}

  <a-card-meta title={val.title}>
      {{
          description: () => {
              return <span>www.instagram.com</span>
          }
      }}
  </a-card-meta>
</a-card>
```
my code is this

description slot  work normal   but  cover slot is not work

in chrome element ，don't have img element

so i think  this is  a bug

### What is expected?
the card cove slot is work normal  in tsx

### What is actually happening?
1

**Comment by aibayanyu20** [comment]
可能需要调整一下代码结构，如下：

```tsx
<a-card hoverable style="width: 240px;height: 600px;">
        {{
          cover: () => {
            return <img style="width: 180px" src={'https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png'} />
          },
          default: () => {
            return <a-card-meta title="测试">
            {{
              description: () => {
                return <span>www.instagram.com</span>
              },
            }}
        </a-card-meta>
          },
        }}
      </a-card>
```

**Comment by miaolin1993** [comment]
修改了结构就可以了，估计可能是因为写了两个插槽，后面把前面的覆盖了
