### ISSUE TITLE
4.0.0-beta.1: Uncaught TypeError: ConfigProvider.config is not a function  

### ISSUE THREAD

**Issue by mwang0** [vueComponent/ant-design-vue#6528]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.1

### Environment
codesandbox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hardcore-mendeleev-zttw6e?file=%2Fpackage.json&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A13%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A13%7D%5D)

### Steps to reproduce
- [config-provider-cn/api](https://next.antdv.com/components/config-provider-cn#api)

```ts
ConfigProvider.config({
prefixCls: 'ant',
});
```

### What is expected?
no errors

### What is actually happening?
Uncaught TypeError: ConfigProvider.config is not a function

**Comment by aibayanyu20** [comment]
升级到4.0.0-beta.2
