### ISSUE TITLE
DataTable 下个功能计划？

### ISSUE THREAD

**Issue by kangning1206** [vueComponent/ant-design-vue#653]
现在使用 ant-design-vue 1.3.7版本，请问表格table控件后续有什么计划？是否会考虑以下几个功能？

1.  支持换行，拖动行更换顺序；
1.  支持换列，拖动表列可以更换列顺序；
1.  支持列宽度，拖动表头调整列宽度；

目前1，2 可以使用 sortablejs 完成功能，希望下个版本中可以集成；好像antd react版本已有这些功能；

感谢 antd 团队对业界的支持。

**Comment by cuteCloud** [comment]
> 现在使用 ant-design-vue 1.3.7版本，请问表格table控件后续有什么计划？是否会考虑以下几个功能？
> 
> 1. 支持换行，拖动行更换顺序；
> 2. 支持换列，拖动表列可以更换列顺序；
> 3. 支持列宽度，拖动表头调整列宽度；
> 
> 目前1，2 可以使用 sortablejs 完成功能，希望下个版本中可以集成；好像antd react版本已有这些功能；
> 
> 感谢 antd 团队对业界的支持。

你好 我发现引入vuedraggle后 表格内容显示不出 貌似是因为draggle标签不能包裹cloums造成的 你们是如何解决的呢 谢谢

**Comment by iwenli** [comment]
> 现在使用 ant-design-vue 1.3.7版本，请问表格table控件后续有什么计划？是否会考虑以下几个功能？
> 
> 1. 支持换行，拖动行更换顺序；
> 2. 支持换列，拖动表列可以更换列顺序；
> 3. 支持列宽度，拖动表头调整列宽度；
> 
> 目前1，2 可以使用 sortablejs 完成功能，希望下个版本中可以集成；好像antd react版本已有这些功能；
> 
> 感谢 antd 团队对业界的支持。

兄弟，这三个你都实现了吗
