### ISSUE TITLE
select选择器组件，value为空字符串''时，希望也能展示placeholder

### ISSUE THREAD

**Issue by hexiaokang** [vueComponent/ant-design-vue#6533]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
select选择器组件，value为空字符串''时，也能展示placeholder

### What does the proposed API look like?
select

**Comment by aibayanyu20** [comment]
目前与ant-design的风格是一致的
