### ISSUE TITLE
col xxxl 未生效

### ISSUE THREAD

**Issue by qingyuun** [vueComponent/ant-design-vue#6544]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.3

### Environment
chrome vue@3.2.47

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-chu-zha-ge-ant-design-vue-4-0-0-beta-4-forked-loqqbq?file=/src/demo.vue)

### Steps to reproduce
```
<template>
<a-row>
<a-col :span="24">col</a-col>
</a-row>
<a-row>
<a-col :span="12">col-12</a-col>
<a-col :span="12">col-12</a-col>
</a-row>
<a-row>
<a-col :span="8">col-8</a-col>
<a-col :span="8">col-8</a-col>
<a-col :span="8">col-8</a-col>
</a-row>
<a-row>
<a-col :xxl="{ span: 2 }">col-2</a-col>
<a-col :xxxl="{ span: 2 }">col-2</a-col>
</a-row>
</template>
````

### What is expected?
在 超大屏>2000 使用 xxxl,
是否会加回 xxxl 尺寸

### What is actually happening?
col 使用 xxxl 时,未能正确解析,

**Comment by qingyuun** [comment]
![image](https://user-images.githubusercontent.com/20103991/237056482-51cd84fc-06a7-417a-beb3-d3e29293534a.png)
中没有 xxxl

**Comment by aibayanyu20** [comment]
v4文档未更新，同步[ant-designv5文档](https://ant.design/components/grid-cn#col)

**Comment by tangjinzhou** [comment]
> v4文档未更新，同步[ant-designv5文档](https://ant.design/components/grid-cn#col)，在v4版本默认情况下仅到`xxl`

@aibayanyu20 这个定制不能扩展吧，只能更改
antdv 的 xxxl 是自己加的，antd 之前就没有
