### ISSUE TITLE
关于tree组件搜索展开项过多 性能的问题

### ISSUE THREAD

**Issue by HelloMoli** [vueComponent/ant-design-vue#655]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
tree组件 expandedKeys 过多时  搜索框 特别卡 性能极其差

### What does the proposed API look like?
tree组件   expandedKeys

**Comment by tangjinzhou** [comment]
最好能给出具体数据量，任何组件当数据量大的时候都会有一个性能极限，如果在合理范围内，我们可以通过其他手段去优化，如果你说的搜索，是不是可以考虑使用防抖来优化

**Comment by HelloMoli** [comment]
好的 我先自己研究下 这个问题暂时做保留哈 组织 大概就是expandedKeys 达到上百的时候 卡顿效果就出来了  尤其是 搜索框的操作

**Comment by KyLeoHC** [comment]
不妨考虑做节点过多自动隐藏功能？限制单次渲染同级节点的数量，加个查看更多按钮，点击继续加载剩余的。
