### ISSUE TITLE
使用 useToken 获取不到最新的主题颜色

### ISSUE THREAD

**Issue by thikiiii** [vueComponent/ant-design-vue#6550]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.4

### Environment
vite4.3.3 、vue3.2

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-vz6cxc?file=package.json,vite.config.ts,src%2FApp.vue&terminal=dev](https://stackblitz.com/edit/vitejs-vite-vz6cxc?file=package.json,vite.config.ts,src%2FApp.vue&terminal=dev)

### Steps to reproduce
1、设置主题默认颜色后，通过 useToken 获取不到最新的主题颜色
2、切换到暗黑模式后，通过 useToken 获取不到最新的文本、背景...颜色

### What is expected?
期望获取最新的主题颜色

### What is actually happening?
获取不到最新的主要颜色

**Comment by thikiiii** [comment]
![1683686253333](https://github.com/vueComponent/ant-design-vue/assets/73383713/b4f9a2c8-3275-4649-8fe6-cc568efd1720)
控制台打印的颜色还是组件库默认的颜色

**Comment by aibayanyu20** [comment]
按需加载使用非同一实例[解决方案](https://stackblitz.com/edit/vitejs-vite-uswvsd?file=package.json,vite.config.ts,src%2FApp.vue&terminal=dev)

**Comment by thikiiii** [comment]
> 按需加载使用非同一个实例[解决方案](https://stackblitz.com/edit/vitejs-vite-uswvsd?file=package.json,vite.config.ts,src%2FApp.vue&terminal=dev)

颜色如何同步呢？
![1683686505302](https://github.com/vueComponent/ant-design-vue/assets/73383713/fb2ef055-a188-4a35-9a5c-23d26c96a90c)

**Comment by thikiiii** [comment]
> 按需加载使用非同一实例[解决方案](https://stackblitz.com/edit/vitejs-vite-uswvsd?file=package.json,vite.config.ts,src%2FApp.vue&terminal=dev)

哥们，你这个解决方案里颜色也没有同步呀

**Comment by aibayanyu20** [comment]
和config-provider同级使用问题

**Comment by CCherry07** [comment]
https://stackblitz.com/edit/vitejs-vite-27mn8y?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev

@aibayanyu20  @thikiiii

**Comment by aibayanyu20** [comment]
建议使用方式：
```ts
import { theme } from 'ant-design-vue';
const token = computed(() => theme.useToken()?.token.value);
```

**Comment by aibayanyu20** [comment]
> [stackblitz.com/edit/vitejs-vite-27mn8y?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev](https://stackblitz.com/edit/vitejs-vite-27mn8y?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev)
> 
> @aibayanyu20 @thikiiii

这种写法在和config-provider同层的情况下也是有点儿问题[demo1](https://stackblitz.com/edit/vitejs-vite-dkhkvn?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev)

**Comment by CCherry07** [comment]
是变化的 @aibayanyu20

**Comment by aibayanyu20** [comment]
> 是变化的 @aibayanyu20 但是取 colorPrimary 是undefined

我测试了一下拿到的是默认值，useToken里面使用的是`inject`，在同层级下configprovider还没有注册`provider`导致的，不确定有什么好的方案可以解决这个问题

**Comment by Yacj** [comment]
同样的问题 监听token 不同主题  css var 都是一样的 有什么好办法解决

**Comment by thikiiii** [comment]
可以定义一个组件，当作 configprovider 的 子组件，专门用来获取 token 的，这样就可以监听到最新的值的

**Comment by thikiiii** [comment]
> 可以定义一个组件，当作 configprovider 的 子组件，专门用来获取 token 的，这样就可以监听到最新的值的

我测了一下这个办法，是可行的 @Yacj

**Comment by aibayanyu20** [comment]
> > 可以定义一个组件，当作 configprovider 的 子组件，专门用来获取 token 的，这样就可以监听到最新的值的
> 
> 
> 
> 我测了一下这个办法，是可行的 @Yacj 

👍

**Comment by Yacj** [comment]
@thikiiii  有stackblitz 复现么 我这边没复现出来 谢谢

**Comment by aibayanyu20** [comment]
@Yacj  可以试试这个方案[token-provider](https://github.com/antdv-pro/antdv-pro/blob/main/src/components/token-provider.vue)

**Comment by Yacj** [comment]
好的 谢谢

**Comment by thikiiii** [comment]
> @thikiiii 有stackblitz 复现么 我这边没复现出来 谢谢

https://stackblitz.com/edit/vitejs-vite-ychrpf?file=package.json,src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue&terminal=dev

**Comment by zzzgit** [comment]
> ![1683686253333](https://private-user-images.githubusercontent.com/73383713/237264053-b4f9a2c8-3275-4649-8fe6-cc568efd1720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzU4MzQsIm5iZiI6MTcwMjE3NTUzNCwicGF0aCI6Ii83MzM4MzcxMy8yMzcyNjQwNTMtYjRmOWEyYzgtMzI3NS00NjQ5LThmZTYtY2M1NjhlZmQxNzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAyMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDkwNDczYTI3ZDgwMzdiY2QyNjQ2Y2I1ZTEzYjkxNjQ4ODQwYWE0OWE0NDc0NmMyN2NiZDliOGU3ODM0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISQRUpCZpUn_gCZjD1rQqXYzgqR0Cl7inj451J00BTg) 控制台打印的颜色还是组件库默认的颜色

我連「组件库默认的颜色」都取不到

**Comment by aibayanyu20** [comment]
> > ![1683686253333](https://private-user-images.githubusercontent.com/73383713/237264053-b4f9a2c8-3275-4649-8fe6-cc568efd1720.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxNzU4MzQsIm5iZiI6MTcwMjE3NTUzNCwicGF0aCI6Ii83MzM4MzcxMy8yMzcyNjQwNTMtYjRmOWEyYzgtMzI3NS00NjQ5LThmZTYtY2M1NjhlZmQxNzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDAyMzIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMDkwNDczYTI3ZDgwMzdiY2QyNjQ2Y2I1ZTEzYjkxNjQ4ODQwYWE0OWE0NDc0NmMyN2NiZDliOGU3ODM0ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ISQRUpCZpUn_gCZjD1rQqXYzgqR0Cl7inj451J00BTg) 控制台打印的颜色还是组件库默认的颜色
> 
> 我連「组件库默认的颜色」都取不到

参考 https://github.com/antdv-pro/antdv-pro/blob/main/src/components/token-provider/index.vue
