### ISSUE TITLE
当TreeSelect的是multiple且max-tag-count="responsive"时，在开发环境下出现ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by IvanLuLyf** [vueComponent/ant-design-vue#6551]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.19

### Environment
any os,any browser, vue3

### Reproduction link
无

### Steps to reproduce

```vue
<template>
  <div>
    <a-tree-select
      style="width: 278px"
      :tree-data="treeData"
      multiple
      max-tag-count="responsive"
    />
  </div>
</template>

<script>
export default {
  name: "DemoPurePage",
  components: {},
  data() {
    return {
      treeData: [
        { title: "测试内容1", value: "1", id: "1" },
        { title: "测试内容2", value: "2", id: "2" },
        { title: "测试内容3", value: "3", id: "3" },
        { title: "测试内容4", value: "4", id: "4" },
      ],
      value: [],
    };
  },
};
</script>
```

然后随便选一些选项

在Chromium内核下
![image](https://github.com/vueComponent/ant-design-vue/assets/5052848/7f84d998-ddca-4f02-b9ed-77cd2e6c2066)

在FireFox下
![image](https://github.com/vueComponent/ant-design-vue/assets/5052848/8f64684b-b027-4aa5-8e53-46266c59d24c)

### What is expected?
不应该出现问题

### What is actually happening?
怀疑是MultipleSelector.tsx中的Overflow组件的ResizeObserver有问题

**Comment by tangjinzhou** [comment]
webpack devServer 添加  
```js
client: {
      overlay: false,
    },
```
