### ISSUE TITLE
希望可以给菜单新增一个手风琴功能

### ISSUE THREAD

**Issue by thikiiii** [vueComponent/ant-design-vue#6552]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
展开一项开的时候收起其他展开的菜单

### What does the proposed API look like?
手风琴

**Comment by tangjinzhou** [comment]
自己控制openKeys即可
