### ISSUE TITLE
table columns resizable 当内容为字母 数字时，列不能缩短

### ISSUE THREAD

**Issue by dong432** [vueComponent/ant-design-vue#6557]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.3

### Environment
window11，Microsoft Edge@110.0.1587.69，vue@3.2.37

### Reproduction link
[https://antdv.com/components/table-cn](https://antdv.com/components/table-cn)

### Steps to reproduce
表格列属性resizable当表格内容为字母 字母时，列缩短不能小于内容长度，width设置也无效

### What is expected?
表格可以通过resizable缩短内容为字母 数字的内容

### What is actually happening?
表格列属性resizable当表格内容为字母 字母时，列缩短不能小于内容长度，width设置也无效

**Comment by CCherry07** [comment]
你更新一下版本，这里，在beta的一个版本改动了的，如果还是不行的话，可以提供一个bug复现的demo
