### ISSUE TITLE
表格组件表格行悬浮样式

### ISSUE THREAD

**Issue by AtroxEzerel** [vueComponent/ant-design-vue#6558]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue2

### Reproduction link
[https://1x.antdv.com/components/table-cn/#components-table-demo-colspan-and-rowspan](https://1x.antdv.com/components/table-cn/#components-table-demo-colspan-and-rowspan)

### Steps to reproduce
antd of vue2表格合并不同的行，hover效果只显示合并的第一行，现在想要hover效果覆盖所有的hover行，有什么好的解决方案吗
[展示例子](https://1x.antdv.com/components/table-cn/#components-table-demo-colspan-and-rowspan)

### What is expected?
合并的行、列悬浮也展示背景色

### What is actually happening?
只有合并的部分有悬浮色
![zzDlRr88x#XHrN75xk32EA==](https://github.com/vueComponent/ant-design-vue/assets/55567122/4a4dcbf1-5a76-4597-9b4b-2356d3b65a2b)

**Comment by suguoyao** [comment]
最近我也遇到这个场景，自己通过以下方式解决的，仅供参考
```vue
<a-table :custom-row="rowSetting"></a-table>
```

```js
rowSetting(record) {
      return {
        on: {
          mouseenter: (e) => {
            // console.log('mouseenter', e, record)
            if (record && record.orderNo) {
              this.$nextTick(() => {
                document.querySelectorAll(`[data-row-key*=${record.orderNo}]`).forEach(el => {
                  el.style.backgroundColor = '#e6fbff'
                })
              })
            }
          },
          mouseleave: (e) => {
            // console.log('mouseleave', e, record)
            if (record && record.orderNo) {
              this.$nextTick(() => {
                document.querySelectorAll(`[data-row-key*=${record.orderNo}]`).forEach(el => {
                  el.style.backgroundColor = null
                })
              })
            }
          }
        }
      }
    },
```
