### ISSUE TITLE
3.2.17升级到4.0版本运行报错

### ISSUE THREAD

**Issue by holiy930561** [vueComponent/ant-design-vue#6559]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.3

### Environment
vue3.2.47，node19.1.0，pnpm 8.5.0

### Reproduction link
[https://ant.design/components/tabs-cn/#header](https://ant.design/components/tabs-cn/#header)

### Steps to reproduce
pnpm install ant-design-vue@latest

### What is expected?
运行正常

### What is actually happening?
Error: The following dependencies are imported but could not be resolved:

ant-design-vue/dist/antd.less

**Comment by holiy930561** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/050176a8-9125-445d-b834-8d20d5c64a7e)

**Comment by selicens** [comment]
4.x及antd5.x，由less转为css-in-js，产物不再包含less
