### ISSUE TITLE
a-date-picker使用disabledDate时，年份被错误的禁用

### ISSUE THREAD

**Issue by ChuShiZ** [vueComponent/ant-design-vue#6566]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
v1.7.8

### Environment
window 10,Edge 115.0.1843.0 (正式版本) dev,vue2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-ixm0vz?file=/src/App.vue)

### Steps to reproduce
1、使用disabledDate属性禁用一个日期之前的所有日期（这个日期距离当前日期或者当前选择的日期不能超过一年）
2、选择日期，点击年份通过年份进行选择，此时发现，年份被错误的禁选

### What is expected?
年份可以照常选择

### What is actually happening?
年份不能照常选择了
![image](https://github.com/vueComponent/ant-design-vue/assets/75254465/b5d14db4-9d98-4662-83cb-f8f8ccd53797)

**Comment by hzpcactus** [comment]
遇到了同样的问题+1

**Comment by longguotao** [comment]
可以使用 defaultPickerValue 属性 取值 moment().add(1, 'day'),

**Comment by ChuShiZ** [comment]
> 可以使用 defaultPickerValue 属性 取值 moment().add(1, 'day'),

我通过修改了ant的源码实现了我的需求，但不太明白年份这里为什么需要执行禁用的相关操作，我翻了下组件库没有看到yearPicker组件
![image](https://github.com/vueComponent/ant-design-vue/assets/75254465/ba21608c-c31a-4526-863c-0c97c1e34ce8)

**Comment by ChuShiZ** [comment]
> 我通过修改了ant的源码实现了我的需求，但不太明白年份这里为什么需要执行禁用的相关操作，我翻了下组件库没有看到yearPicker组件

并且年份的禁用，也通过disabledDate实现似乎不太合适？

**Comment by longguotao** [comment]
> > 我通过修改了ant的源码实现了我的需求，但不太明白年份这里为什么需要执行禁用的相关操作，我翻了下组件库没有看到yearPicker组件
> 
> 并且年份的禁用，也通过disabledDate实现似乎不太合适？

是的，v2+ 版本修复了这些问题
