### ISSUE TITLE
upload组件在手机端无法选择文件

### ISSUE THREAD

**Issue by Forevery1** [vueComponent/ant-design-vue#6567]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
v3.2.20

### Environment
手机edge浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dian-ji-shang-chuan-ant-design-vue-3-2-20-forked-yn5cum?file=/src/demo.vue)

### Steps to reproduce
已经按照官网配置了：:accept="null"但是不生效。

### What is expected?
可以选择文件

### What is actually happening?
不清楚

**Comment by Orange-Yellow** [comment]
遇到了相同的问题！！！
我是用的是ios16.1，react 版本的是可以有三个选项的：照片图库；拍照或录像；选取文件；
但是vue版本的直接就打开相机了，希望vue版本的也是提供react的三个选项而不是直接打开相机。

**Comment by Orange-Yellow** [comment]
添加这个设置 :capture='null'   就行了，antv默认加了capture=false~

**Comment by Forevery1** [comment]
试了下、好了。感谢
