### ISSUE TITLE
DatePicker是否可以增加一个当前时间的入参

### ISSUE THREAD

**Issue by fisheep01** [vueComponent/ant-design-vue#6569]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有些时候用户主动或被动的修改了本地设备的时间，这时候new Date()得到的就是修改后的时间；而业务上我们希望他们按照自然时间选择而非修改后的时间，我们可以通过服务端或者其他方式解决这个问题；但是DatePicker中今日快捷按钮的行为无法改变，同时日历视图上也有今天的选中效果无法处理。所以我希望可以加入一个类似today的入参来解决这个问题，或者说是否有其他解决方案

### What does the proposed API look like?
加入一个此刻的入参

**Comment by tangjinzhou** [comment]
参考 https://antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges
