### ISSUE TITLE
复选框的文字不居中

### ISSUE THREAD

**Issue by eatfishs** [vueComponent/ant-design-vue#6575]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
edge 113.0.1774.42

### Reproduction link
[https://www.antdv.com/components/checkbox-cn](https://www.antdv.com/components/checkbox-cn)

### Steps to reproduce
打开antdv官网

### What is expected?
希望复选框和ant-design-react视觉效果一致

### What is actually happening?
实际内容靠下了

![企业微信截图_1684293991737](https://github.com/vueComponent/ant-design-vue/assets/45836182/bcdf0dc4-ce8e-4f43-ad01-ea02e71f4f41)

**Comment by appleaway** [comment]
文档例子可能被什么样式影响了，单独打开codesandbox链接查看是一样的效果，这个不用担心
