### ISSUE TITLE
The Table component seems not updating the AntSorterResult onClick on column for sort - during the onChange event parameters are not updating

### ISSUE THREAD

**Issue by LuXDAmore** [vueComponent/ant-design-vue#6578]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
Chrome  113.0.5653.0, Vue 3.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-columns-sort-order-bug-ikoz6b?file=/src/App.vue)

### Steps to reproduce
- Define a sortOrder: "descend" (or "ascend") in a column;
- Click on the table-head column-head to change the sorting value;
- Check the table onChange event, the AntSorterResult is not updating, so it's impossible to update external values related to this one.

### What is expected?
It's expected that the AntSorterResult is updated with the new sorting values.

### What is actually happening?
AntSorterResult order is not updating and the sorting column key/id is setted to undefined.

---
Check the console log in the reproduction example to see it.

**Comment by aibayanyu20** [comment]
I made some adjustments to the example you provided and you can refer to it for usage [codesandbox](https://codesandbox.io/s/ant-columns-sort-order-bug-forked-4i2419?file=/src/App.vue). Normally, components should not directly modify the data passed in from the outside, so you need to manually update the sorting state.

**Comment by LuXDAmore** [comment]
@aibayanyu20 in this case is a _ref_, but what if _columns_ is a _computed_? How do you know that the event is triggered due to a _sort event_ if the params for sorting is not updated?

In the [example](https://codesandbox.io/s/ant-columns-sort-order-bug-forked-ou6rtd?file=/src/App.vue), the problem is that the **sortingParameters** is not updating from the **onChange** event, but every other parameter is working as expected (I've added the **paginationParameters** to check the value); You can see that **antSorting.value** is updated only once.

**Comment by aibayanyu20** [comment]
The problem is still the same as I mentioned before. The value of `sortOrder` property in the `column` object is not updated, resulting in no changes in the data itself. Appropriate assignment will not trigger an update. As for the situation with computed properties, it's even more important not to update external values since the data binding should be a unidirectional data flow. Internal modifications of external values shouldn't be made, rather external changes should be the way to manage the values. To determine whether a sorting is triggered, you can use the fourth parameter.

```ts
const onTableChange2 = (
      paginationParameters,
      __,
      sortingParameters,
      extra
    ) => {
      console.log(extra);
	 if(extra.action === 'sort'){
		// TODO
	}
};

```

**Comment by LuXDAmore** [comment]
@aibayanyu20 


> The problem is still the same as I mentioned before. The value of sortOrder property in the column object is not updated, resulting in no changes in the data itself. Appropriate assignment will not trigger an update.

Why with the other parameters is working? I'm not updating them from code/UI, is Ant doing it under the ground (ex. _paginationParameters_).

> To determine whether a sorting is triggered, you can use the fourth parameter.

The fourth parameters is useful, but i think **onTableChange** has to trigger the new value as it is doing with the others parameters, otherwise is not working as expected.

I've updated the example with just one table to show you the issue [HERE](https://codesandbox.io/s/ant-columns-sort-order-bug-ikoz6b)

**Comment by LuXDAmore** [comment]
I need this because the sorting/pagination is made via BackEnd, and the `extra` parameters is not giving me any information, just the `action` and the `currentDataSource`, how can i know which kind of sorting the user did? Like the order or the column? The `sortingParameters` is supposed to be used for this, but it's not updating.

**Comment by aibayanyu20** [comment]
You can try using this solution to address your issue, as it might be the best solution currently available for your problem.

**Comment by LuXDAmore** [comment]
Ok, I'm gonna try with this.

I can close this issue.
