### ISSUE TITLE
5.18最新下载依赖包，项目启动不成功

### ISSUE THREAD

**Issue by LiuChang0725** [vueComponent/ant-design-vue#6583]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.16

### Environment
chrome:版本  113.0.5672.92（正式版本） (arm64)  node: v14.21.3 npm:9.6.0

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/3.2.16](https://github.com/vueComponent/ant-design-vue/tree/3.2.16)

### Steps to reproduce
1.下载3.2.16 包
2.执行 npm install (安装过程正常，无任何报错)
3.执行 npm run dev (正常)
4.访问项目，控制台报错

<img width="1271" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/37528714/3ed454d1-8bc2-42e9-8075-7ed08280ece7">

[Vue warn]: Unhandled error during execution of render function
at <Trigger openClassName=undefined minOverlayWidthMatchTrigger=undefined alignPoint=undefined  ... >
at <Anonymous overlayClassName="is-max" arrow=undefined trigger="click"  ... >
at <ADropdown trigger="click" placement="bottomRight" overlay-class-name="is-max" >
at <Index onReload=fn<onReload> >
at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > >
at <RouterView>
at <ALocaleProvider locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} ANT_MARK__="internalMark" >
at <LocaleReceiver children=fn<children> >
at <AConfigProvider key=1 locale= {locale: 'zh-cn', Pagination: {…}, DatePicker: {…}, TimePicker: {…}, Calendar: {…}, …} getPopupContainer=fn<getPopupContainer> >
at <App>

runtime-core.esm-bundler.js:2939 Uncaught (in promise) TypeError: Object(...)(...) is not a function
at Object.get (runtime-core.esm-bundler.js:2939:1)
at Proxy.render (Trigger.js:662:1)
at renderComponentRoot (runtime-core.esm-bundler.js:816:1)
at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5696:1)
at ReactiveEffect.run (reactivity.esm-bundler.js:178:1)
at instance.update (runtime-core.esm-bundler.js:5809:1)
at setupRenderEffect (runtime-core.esm-bundler.js:5817:1)
at mountComponent (runtime-core.esm-bundler.js:5607:1)
at processComponent (runtime-core.esm-bundler.js:5560:1)
at patch (runtime-core.esm-bundler.js:5035:1)

### What is expected?
能够正常运行打包编译

### What is actually happening?
启动成功报错

**Comment by zerobin** [comment]
升级到最新版本bate.4 rc版本
