### ISSUE TITLE
关于官网table组件Column文档的疑惑

### ISSUE THREAD

**Issue by small-onion** [vueComponent/ant-design-vue#6585]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在使用ant-design-vue 4.0版的table组件时用customRender控制台提示已被废弃推荐使用customCell。
1、官网的文档关于Column部分又还保留这customRender的说明，文档没有任何关于返回值应该是什么形式的说明。搜索的好像都有是旧版用法，且不全。
2、推荐使用customCell，但customCell又不支持复杂结构渲染，也不支持含有组件的渲染。且也没有返回值的任何说明。
3、希望官网文档补充customRender、customCell应该返回什么的说明，如：对象、数组每个字段、属性代表的意思和作用。
4、如果customRender废弃，希望customCell可以支持含有组件的渲染，不然table个别字段自定义渲染就只有插槽一种方式了，而且还有局限性。

### What does the proposed API look like?
1、希望官网文档补充customRender、customCell应该返回什么的说明，如：对象、数组每个字段、属性代表的意思和作用。
2、如果customRender废弃，希望customCell可以支持含有组件的渲染，不然table个别字段自定义渲染就只有插槽一种方式了，而且还有局限性。

**Comment by appleaway** [comment]
使用自定义插槽渲染会更合理点吧，把更多的操作空间留给开发

**Comment by small-onion** [comment]
我是希望官方把文档补充完整，不提供customRender就把文档中的删掉，关于customCell的返回值的每个属性及其作用列出来。

至于哪种渲染合理，我是这个觉得哈：多一个选择嘛，自定义插槽有自定义插槽的优点，customRender也有他的优势嘛。

**Comment by small-onion** [comment]
> 使用自定义插槽渲染会更合理点吧，把更多的操作空间留给开发

我是希望官方把文档补充完整，不提供customRender就把文档中的删掉，关于customCell的返回值的每个属性及其作用列出来。

至于哪种渲染合理，我是这个觉得哈：多一个选择嘛，自定义插槽有自定义插槽的优点，customRender也有他的优势嘛。

**Comment by BG7ZAG** [comment]
目前有个奇怪的问题，如果只用customRender，当默认key的value为空时return出来的值才有效。

但是写了一个空的slot后，customRender return的优先度又上去了

```
const columns = reactive([ 
    { title: '创建时间', dataIndex: 'createTime' },
    { title: '类型', dataIndex: 'type', customRender: ({ value })=>value + '-' ])
```
```
<Table  :data-source="dataSource" :columns="columns">
 <!-- 如果不写下面这一行，customRender无效  -->
  <template #bodyCell="{}"> </template>
</Table>
```

**Comment by fucktic** [comment]
同意说法，文档不够清晰
