### ISSUE TITLE
使用  unplugin-vue-components  按需导入组件，导致动态主题无法生效，样式优先级不够。

### ISSUE THREAD

**Issue by GreatAuk** [vueComponent/ant-design-vue#6586]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
browser: latest;
vue: 3.2;
vite: 4.1.4

### Reproduction link
none

### Steps to reproduce
<img width="532" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/20253809/668a1baa-b2e0-411a-95f1-1cbaf6f859b5">

### What is expected?
动态主题生效。

### What is actually happening?
动态主题不生效

**Comment by tangjinzhou** [comment]
自动导入的不应该和动态的一样吗，
优先级问题，你应该去 unplugin-vue-components 提issue看是否支持改变style插入问题，
另外个人觉得unplugin-vue-components 也没必要支持，会带来很多其它的问题，

个人建议：
1、不使用自动导入，如果要使用就应该明白自动导入的原理就是append style到html中，优先级必然是不确定性的
或 2、确保自动导入和动态拥有相同 style，或动态的添加id前缀，加大权重

**Comment by GreatAuk** [comment]
好的，谢谢

**Comment by ILfengzi** [comment]
可以设置 ` unplugin-vue-components ` 插件的配置解决：
```
AntDesignVueResolver({
  importStyle: false
})
```

另外，想问一下，动态主题的设置ConfigProvider.config有没有暗黑主题属性可以设置呢？看了下，貌似只能设置几个颜色？
@tangjinzhou

**Comment by luocong2016** [comment]
黑暗主题
```
import { theme } from "ant-design-vue"
theme={{ algorithm: theme.darkAlgorithm }}
```

**Comment by ILfengzi** [comment]
已收到！
