### ISSUE TITLE
分页组件报错

### ISSUE THREAD

**Issue by xiaochong44** [vueComponent/ant-design-vue#6590]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.3

### Environment
vue3.3

### Reproduction link
[https://next.antdv.com/components/pagination-cn](https://next.antdv.com/components/pagination-cn)

### Steps to reproduce
打开rc3的分页组件，会报错
index.7cba2cde.js:1 TypeError: Cannot read properties of null (reading 'parentNode')
at getPopupContainer (index.7cba2cde.js:427:20035)
at h.getContainer (index.7cba2cde.js:137:12250)
at Av (index.7cba2cde.js:137:197)
at index.7cba2cde.js:137:1438
at index.7cba2cde.js:1:35385
at gi (index.7cba2cde.js:1:16759)
at Ho (index.7cba2cde.js:1:16838)
at t.__weh.t.__weh (index.7cba2cde.js:1:35265)
at is (index.7cba2cde.js:1:2256)
at Y (index.7cba2cde.js:1:60636)

### What is expected?
不报错

### What is actually happening?
发生错误了

**Comment by lengran57** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by xiaochong44** [comment]
> 我也遇到同样的问题，请问解决了吗

没有，我把showSizeChanger改为false了，等官方修复

**Comment by zerobin** [comment]
同样遇到，+1

**Comment by tangjinzhou** [comment]
update to rc4
