### ISSUE TITLE
dropdown内的menu使用inputnumber报错

### ISSUE THREAD

**Issue by haoshuaiya** [vueComponent/ant-design-vue#6591]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
Chrome 113.0.5672.93

### Reproduction link
[https://1x.antdv.com/components/dropdown-cn](https://1x.antdv.com/components/dropdown-cn)

### Steps to reproduce
在dropdown内包含一个inputnumber以修改某个数值，手动改动input内的值后，再点击上下箭头

### What is expected?
数值的增减要和预期一致

### What is actually happening?
数值的增减不对
![图片](https://cdn-us.imgs.moe/2023/05/22/646b270029fdf.gif)

---
https://codesandbox.io/s/vue-antd-template-forked-gq063o?file=/src/App.vue

**Comment by tangjinzhou** [comment]
1.x 不再维护
