### ISSUE TITLE
Tooltip组件增加自动关闭功能

### ISSUE THREAD

**Issue by nnzbz** [vueComponent/ant-design-vue#6595]
- [ * ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Tooltip一直显示没有自动关闭功能，如果这时用了Popconfirm或其它组件弹出的提示会被遮挡（因为鼠标并没有移动），我想如果有一个自动关闭功能可以缓解此问题，或者能实现点击就自动关闭可以完全解决该问题

### What does the proposed API look like?
增加一个autoClose属性，number类型，默认值0，表示不自动关闭，设置了n数值就延迟n毫秒关闭
还可以直接增加一个clickClose属性，boolean类型，默认值false，为true时，鼠标点击关闭
可以参考: https://element-plus.gitee.io/zh-CN/component/popover.html#attributes

**Comment by nnzbz** [comment]
没有人注意到？

**Comment by aibayanyu20** [comment]
这个问题应该可以通过open来自行实现吧
