### ISSUE TITLE
【Space.Compact】按需加载找不见组件(v4)

### ISSUE THREAD

**Issue by dmyz** [vueComponent/ant-design-vue#6596]
### Version
4.0.0-rc.4

### Environment
vue@3.3.4

### Reproduction link
[https://next.antdv.com/components/space-cn#components-space-demo-compact](https://next.antdv.com/components/space-cn#components-space-demo-compact)

### Steps to reproduce
按需加载中组件样式不加载
![image](https://github.com/vueComponent/ant-design-vue/assets/15307200/883c6956-b324-40c1-a631-d5dc4e8a520a)
![image](https://github.com/vueComponent/ant-design-vue/assets/15307200/6b13d88d-15ba-45b1-b2ab-0b0e3e8fe0e2)
![image](https://github.com/vueComponent/ant-design-vue/assets/15307200/2ac01134-5553-42da-a4ed-5a04a45f2ff7)
![image](https://github.com/vueComponent/ant-design-vue/assets/15307200/b1217256-d066-4185-9d3a-8dc61c8dd10e)
![image](https://github.com/vueComponent/ant-design-vue/assets/15307200/d4f8bd20-2d6e-4b24-88ec-eb7128e2720b)

### What is expected?
Button紧凑布局正常显示

### What is actually happening?
Button不紧凑布局显示

**Comment by maybeyj** [comment]
一样的情况，有解决的吗

**Comment by CCherry07** [comment]
unplugin-vue-components 还没有更新

https://github.com/antfu/unplugin-vue-components/pull/658
