### ISSUE TITLE
Hope the theme provides more token variables

### ISSUE THREAD

**Issue by L-Z-Y** [vueComponent/ant-design-vue#6597]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
For example, I wish I could set the button's color and bordercolor separately, but now I'm going to a variable's value
![截屏2023-05-24 20 54 17](https://github.com/vueComponent/ant-design-vue/assets/12064230/f577d655-03da-4526-a9ec-81bdc629e238)

### What does the proposed API look like?
add more token variables

**Comment by selicens** [comment]
config-provider

**Comment by L-Z-Y** [comment]
> config-provider

Cannot meet the demand

**Comment by selicens** [comment]
> > config-provider
> 
> Cannot meet the demand

![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/5ab3526f-3c44-4099-837b-3e572843f357)
The document for ant design vue has not been updated yet

**Comment by selicens** [comment]
有没有一种可能这个主题不止能做这俩操作。。。

**Comment by L-Z-Y** [comment]
> 

不太明白您说的意思，我们要按照自己的样式规范做主题适配，现在就是button在type为default的时候的样式，我想单独设置字体和边框的颜色，目前源码里面color和border-color都是取的一个token变量，也就是我只能设成一种颜色

**Comment by selicens** [comment]
> > 
> 
> 不太明白您说的意思，我们要按照自己的样式规范做主题适配，现在就是button在type为default的时候的样式，我想单独设置字体和边框的颜色，目前源码里面color和border-color都是取的一个token变量，也就是我只能设成一种颜色

![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/07c30429-842a-4a6c-b33e-6b1763f215c2)

**Comment by L-Z-Y** [comment]
> > > 
> > 
> > 
> > 不太明白您说的意思，我们要按照自己的样式规范做主题适配，现在就是button在type为default的时候的样式，我想单独设置字体和边框的颜色，目前源码里面color和border-color都是取的一个token变量，也就是我只能设成一种颜色
> 
> ![image](https://user-images.githubusercontent.com/69418751/240865528-07c30429-842a-4a6c-b33e-6b1763f215c2.png)

hover 和active的样式弄不了的

**Comment by selicens** [comment]
是有些bug😁

**Comment by aibayanyu20** [comment]
先给ant-design提个相关的issue吧，好像ant-design的是这样的
