### ISSUE TITLE
官网文档关于carousel组件的介绍中，Custom Arrows主题展示缺少了左箭头

### ISSUE THREAD

**Issue by Simon-chai** [vueComponent/ant-design-vue#6601]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.4

### Environment
Chrome 版本 113.0.5672.127（正式版本） （64 位）

### Reproduction link
[https://2x.antdv.com/components/carousel](https://2x.antdv.com/components/carousel)

### Steps to reproduce
打开官网就能看到。官网的示意代码复制到机器效果也是一样的：缺少左箭头

### What is expected?
Custom Arrows主题示意代码既能显示右箭头，也能显示左箭头。

### What is actually happening?
从代码上看，是有设计了左箭头和右箭头的，但是实际使用中，只显示了右箭头。

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/484dbf2c-1634-4f6b-9454-1722de4e5a4c)
https://next.antdv.com/components/carousel-cn 你看的文档是2.x的
