### ISSUE TITLE
为 Modal 组件增加 Prop 用于控制是否锁定底部页面所有滚动

### ISSUE THREAD

**Issue by UnforgetMemory** [vueComponent/ant-design-vue#6614]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
防止底部页面滚动 虽然似乎有其他方法代替或者忽略 但似乎有总过没 ——菜鸡曾经说过

### What does the proposed API look like?
参考“友商”

**Comment by CCherry07** [comment]
这个是一个bug，已经修好了#6687
