### ISSUE TITLE
treeSelect组件无法指定Key

### ISSUE THREAD

**Issue by StevenTang1994** [vueComponent/ant-design-vue#6622]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
win11 , 113.0.5672.127, vue3.2.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zi-ding-yi-zi-duan-ant-design-vue-3-2-20-forked-ntzpwv)

### Steps to reproduce
在treeSelect组件中用 fieldNames重新定义了 Key但是不生效

### What is expected?
希望节点的指定Key

### What is actually happening?
文档写了 fieldNames可以 替换 treeNode 中 label,value,key,children 字段为 treeData 中对应的字段
但是实际上无法指定节点的key

**Comment by CCherry07** [comment]
我来看看

**Comment by CCherry07** [comment]
@StevenTang1994 
这里是文档的问题，源代码是不支持key 的别名，我更新一下文档

**Comment by StevenTang1994** [comment]
能否增加这个需求 指定key的属性 不用value

**Comment by CCherry07** [comment]
@StevenTang1994 

我觉得 这里 value 的唯一性和key是一样的，UI上面，有两个相同的值，你点击其中一个之后，应该是收集的两个value. 对用户来说，也是符合直觉的。如果，收集的是一个value，如果用户下一次来点击的时候，是否存在歧义（我明明点击了为何还存在）呢，或者说，是否很容易点到另外一个导致数据的不稳定性？
