### ISSUE TITLE
PageHeader components style props error

### ISSUE THREAD

**Issue by L-Z-Y** [vueComponent/ant-design-vue#6624]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
none

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/feat-v4/components/page-header/style/index.ts](https://github.com/vueComponent/ant-design-vue/blob/feat-v4/components/page-header/style/index.ts)

### Steps to reproduce
https://next.antdv.com/components/page-header-cn

### What is expected?
fontZize to fontSize

### What is actually happening?
now is fontZize

![截屏2023-06-01 11 16 25](https://github.com/vueComponent/ant-design-vue/assets/12064230/dc636b65-59ae-4b5d-a700-9778951be6a3)
<img width="613" alt="截屏2023-06-01 11 17 40" src="https://github.com/vueComponent/ant-design-vue/assets/12064230/506f9d97-f17e-4881-a0d8-a4d34ef5d80b">

**Comment by CCherry07** [comment]
我看看
