### ISSUE TITLE
message.useMessage()方法创建的获取上下文的实例在服务端渲染场景下，第二次调用后续图标丢失。

### ISSUE THREAD

**Issue by Logosww** [vueComponent/ant-design-vue#6627]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
"vue": "3.2.45 ", ant-design-vue": "4.0.0-rc.5",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/vibrant-tu-lhx69c)

### Steps to reproduce
1、使用`Nuxt3`框架下进行SSR服务端渲染，调用`message.useMessage()`方法获取到`messageInstance`和`contextHolder`，同时`template`中使用`client-only`组件包裹`context-holder`的VNode。
2、第一次调用`messageInstance`的方法（如`error`, `warning`），组件显示正常，第二次后续调用同样的方法。

### What is expected?
组件正常渲染显示。

### What is actually happening?
后续调用的结果是渲染的组件图标丢失。
![image](https://github.com/vueComponent/ant-design-vue/assets/87473526/ebc3b14a-c935-4ff5-a702-795866460df9)

---
SSR场景下不使用 client-only 组件包裹 context-holder 会导致水合错误，但是包裹后就会出现这个问题，感觉是 teleport 的原因？

**Comment by Logosww** [comment]
这个 issue 在最新 4.0.0.rc6 中依旧存在。
This issue still remains in latest version 4.0.0.rc6.

**Comment by greenhat616** [comment]
@CCherry07  我觉得这个问题可以扩展一下。比如说 Select 组件那个 closable 的图标，ssr 模式下也是出现一次后后续的图标都是 missing（img 没有渲染出来），以及空状态等等，只要是涉及图标的都可能遇到这个问题。
