### ISSUE TITLE
modal.confirm中，同时在okText和content中使用响应式变量，输入中文时，确认输入前框内内容会消失

### ISSUE THREAD

**Issue by MJGDemon** [vueComponent/ant-design-vue#6633]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.3

### Environment
Vue: 3.2.34 ant-desing-vue: 3.2.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-waterfall-995708?file=/src/main.js)

### Steps to reproduce
1. 在倒计时过程中使用中文输入法敲入内容，不要按空格将中文键入
2. 观察输入框内容，在倒计时数字变化时，输入框内容消失

### What is expected?
能够正常输入中文

### What is actually happening?
中文输入成功前，预输入的内容消失

**Comment by ListeningRift** [comment]
我认为这个情况是合理的，这是vue的机制，你的重现中content提供的是一个匿名函数，就导致你的props变化时input组件就会进行重绘，包括聚焦都会消失，这是因为拿到的input组件并不是同一个对象，是先销毁了原input然后重新添加了一个input，当这样调整之后就没有问题了
``` tsx
Modal.confirm({
  title: "test",
  content: <Input v-model:value={text} />,
  okText: () => delay.value
});
```

**Comment by MJGDemon** [comment]
但是这样做似乎会导致双向绑定失效？ 换成这样写之后我获取到的text变量值一直都没有发生变化
