### ISSUE TITLE
Layout组件中Sider、Header不跟随主题色，Sider、Menu切换主题色明显有延时

### ISSUE THREAD

**Issue by svipchao** [vueComponent/ant-design-vue#6637]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
Chromium 102.0.5005.167

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-jie-gou-ant-design-vue-4-0-0-rc-4-forked-bw4m3h?file=/src/demo.vue)

### Steps to reproduce
点击切换主题按钮可以看到主题色变更有明显的滞后感

### What is expected?
切换主题色时Sider、Menu不应该有那么明显的滞后感

### What is actually happening?
点击切换主题按钮可以看到主题色变更有明显的滞后感

---
React版本也有这个问题，我提交了issue，他们修复了
参考链接：https://github.com/ant-design/ant-design/issues/41816

**Comment by selicens** [comment]
![transition](https://github.com/vueComponent/ant-design-vue/assets/69418751/2120379a-8997-4fbc-b189-67c3a8b9b45f)

**Comment by CCherry07** [comment]
layout 的主题色需要自己设计
