### ISSUE TITLE
a-modal is very slow when opened from a-table

### ISSUE THREAD

**Issue by igorfraa** [vueComponent/ant-design-vue#6643]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.18

### Environment
vue 3.2.13, safari/chrome current

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-e5ce3y)

### Steps to reproduce
Create an (unpaginated) <a-table> with ~1000 rows, add button with a-modal to one of columns.

### What is expected?
a-modal works as usual

### What is actually happening?
a-modal opening takes 4  seconds, closing also takes 4  seconds with high compute usage (consider m2 cpu)

---
well, I'm not sure how to debug this, but I think this is very related to number of entries in table.

**Comment by igorfraa** [comment]
(note: I was able to use modal at usual speed once it got moved out of table column template)

**Comment by appleaway** [comment]
use Modal api in your event callback, don't use in template

**Comment by tangjinzhou** [comment]
> (note: I was able to use modal at usual speed once it got moved out of table column template)

you should use modal out of table.
