### ISSUE TITLE
Switch 开关优化建议

### ISSUE THREAD

**Issue by hdtopku** [vueComponent/ant-design-vue#6644]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
macos chrome vue3

### Reproduction link
[https://next.antdv.com/components/switch-cn](https://next.antdv.com/components/switch-cn)

### Steps to reproduce
1、switch开关能否变为3个状态，目前只有2个状态。2、此外，开关的颜色只有蓝色，可否自定义其他颜色，比如开是绿色，关是红色。

### What is expected?
1、switch开关能否变为3个状态，目前只有2个状态。2、此外，开关的颜色只有蓝色，可否自定义其他颜色，比如开是绿色，关是红色。

### What is actually happening?
1、switch开关能否变为3个状态，目前只有2个状态。2、此外，开关的颜色只有蓝色，可否自定义其他颜色，比如开是绿色，关是红色。

**Comment by selicens** [comment]
😂开关开关，除了开就是关，第三种状态是禁用嘛哈哈哈

**Comment by daiwanxing** [comment]
颜色的更改你应该去参考[定制主题](https://next.antdv.com/docs/vue/customize-theme-cn)
