### ISSUE TITLE
ant-desgin-vue v3 版本使用自定义时间库，时间选择器组件报错

### ISSUE THREAD

**Issue by suiboyu** [vueComponent/ant-design-vue#6645]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
"ant-design-vue": "^3.2.16", "vue": "^3.2.37"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-glade-tss56s?file=/src/main.js)

### Steps to reproduce
没有步骤，打开时间选择器组件就可以看到样式异常

### What is expected?
正常的时间选择器样式

### What is actually happening?
时间选择器样式异常

**Comment by daiwanxing** [comment]
antd v3 开始内置的日期库已经从 momentjs 切换成 dayjs 了，没有任何理由再用 momentjs。

https://github.com/vueComponent/ant-design-vue/discussions/4575#discussioncomment-1237789

**Comment by STYH1997** [comment]
TimePicker时间选择器无法隐藏底部的确认按钮，使用css样式隐藏，面板关闭失去焦点后之前选中的时间无效

**Comment by tangjinzhou** [comment]
![image](https:github.com/vueComponent/ant-design-vue/assets/6937879/504511fb-6950-4ab1-a85b-3a6e6c871dc9)
冲突了呀，控制台已经告诉你了

**Comment by suiboyu** [comment]
可是这些代码都是从官网上面找到的，如果删除了在 main.ts 中引入的信息，页面的显示同样还是异常。项目中大量使用了 moment，使用 dayjs 进行替换，有点不太现实。希望官方可以看一下这个问题
