### ISSUE TITLE
官网的Table 组件远程加载数据案例报错

### ISSUE THREAD

**Issue by XiaoLuo01** [vueComponent/ant-design-vue#6646]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue 3.2.28

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yvdquy?file=/src/demo.vue)

### Steps to reproduce
https://codesandbox.io/s/yvdquy?file=/src/demo.vue 案例报错，我引入代码跟这个案例的报错是一样的

### What is expected?
不报错，正常加载数据

### What is actually happening?
报错，无法加载数据
<img width="537" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/25947828/b51a8a5a-6caa-4aeb-9dbb-07a66b90c562">

**Comment by wangjunjia** [comment]
```
const queryData = params => {
  return axios.get('https://randomuser.me/api?noinfo', {
    params,
  })
  .then(res => res.data.results);  // 加上这个
  // 移除 formatResult。期望用户自行在 Service 中返回最终格式的数据。
  // https://cn.attojs.org/guide/migration.html#%E8%BF%81%E7%A7%BB%E5%B8%AE%E5%8A%A9
};
```
