### ISSUE TITLE
Table 写虚拟滚动滑动时第一样 row 出现问题

### ISSUE THREAD

**Issue by dengwenj** [vueComponent/ant-design-vue#6648]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
Vue3.3.2
![WechatIMG122](https://github.com/vueComponent/ant-design-vue/assets/83458670/7ef82dc3-8151-4d77-8563-5e28c62cffb8)

### Steps to reproduce
通过 Table 写了个虚拟列表，在滑动的时候，第一行的 row有很大的一块高度

### What is expected?
第一行的 row 还是要和原来一样

### What is actually happening?
第一行的 row 出现出现了高度

**Comment by tangjinzhou** [comment]
那就是写的虚拟滚动不对吧
