### ISSUE TITLE
Modal 对话框：打开弹窗时，页面仍然可以滚动

### ISSUE THREAD

**Issue by yanyalin** [vueComponent/ant-design-vue#6649]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
官方网站，生产环境

### Reproduction link
[https://next.antdv.com/components/modal-cn](https://next.antdv.com/components/modal-cn)

### Steps to reproduce
Modal 对话框：随便打开一个就行

### What is expected?
期望和ant-design-vue3.X一样，打开弹窗时，页面无法滚动

### What is actually happening?
Modal 对话框：打开弹窗，页面可以滚动

---
我看了下，ant-design-vue，1.X、2.X、3.X都没有这个现象，ant-design react版本也没有这个现象

**Comment by CCherry07** [comment]
ok,我来看看
