### ISSUE TITLE
TimePicker组件底部确认按钮使用css样式隐藏后，选择时间后，关闭面板无法保存当前选中时间

### ISSUE THREAD

**Issue by STYH1997** [vueComponent/ant-design-vue#6652]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
官方网站，生产环境

### Reproduction link
[https://www.antdv.com/components/time-picker-cn](https://www.antdv.com/components/time-picker-cn)

### Steps to reproduce
TimePicker组件

### What is expected?
TimePicker组件可以支持隐藏底部按钮的隐藏，选中时间后，关闭面板时间依旧可以保存

### What is actually happening?
底部按钮可以使用参数进行隐藏，无需点击确认按钮就可以保存当前选中的时间

**Comment by KunerRick** [comment]
现在这个addon没法全部覆盖定制就很难受

**Comment by yimiShi** [comment]
@STYH1997 解决了吗

**Comment by huajian123** [comment]
请问解决了吗

**Comment by huajian123** [comment]
怎么自动关闭了，这个issues。。。

**Comment by STYH1997** [comment]
> 怎么自动关闭了，这个issues。。。

没解决

**Comment by huajian123** [comment]
官方要不要解决这个问题，这个跟react那边不一致

**Comment by huajian123** [comment]
我们解决了，在open的时候记录了timepicker中的title的值，给其他人做个参考吧。或者用MutationObserver来监听title
https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver

真坑。。。

**Comment by lalaxyv** [comment]
> 我们解决了，在open的时候记录了timepicker中的title的值，给其他人做个参考吧。或者用MutationObserver来监听title https://developer.mozilla.org/zh-CN/docs/Web/API/MutationObserver
> 
> 真坑。。。

要改源码吗？ 如何做？

**Comment by huajian123** [comment]
@lalaxyv let observer: any;
observer = new MutationObserver((mutations) => {
    //   console.log(mutations[0]);
    //   if (mutations[0].attributeName === 'title') {
    //     console.log(inputDom.value, "inputDom.getAttribute('title')");
    //     timeArray.push(inputDom.value);
    //     console.log(timeArray);
    //   }
    // nextTick(() => {
    //   if (mutations[0].attributeName === 'actived') {
    //     if (inputDom.getAttribute('title') === 'true') {
    //       // heightLightStepNode(step);
    //     }
    //   }
    // });
  });
  let config = { attributes: true };
  observer.observe(inputDom, config);
