### ISSUE TITLE
range-picker 格式是日期时，显示与实际值不匹配

### ISSUE THREAD

**Issue by MatrixYe23** [vueComponent/ant-design-vue#6654]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
Windows 11, Chrome 114.0.5795.110, Vue:3.2.33

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ri-qi-shi-jian-xuan-ze-ant-design-vue-3-2-20-forked-pqdjk6)

### Steps to reproduce
1. range picker 配置valueFormat MM-DD,
2. 跨年选择时间，比如 2023-12-01 to 2024-01-31，
3. range pick 显示会变成 01-31 to 12-01
但是值还是 ['12-01','01-31']
![1w](https://github.com/vueComponent/ant-design-vue/assets/52131735/3540a2b3-b3f8-475b-90c0-bf23713cdd37)
![2w](https://github.com/vueComponent/ant-design-vue/assets/52131735/38512aa2-3206-4d98-80e4-2279d64b612f)

### What is expected?
range picker 的显示应该跟值一样是 12-01 to 01-31

### What is actually happening?
range picker 的显示变成了 01-31 to  12-01

**Comment by appleaway** [comment]
valueFormat 的格式应该是 YYYY-MM-DD，才能标识正确的数据范围，否则经过dayjs生成之后都成为同年的范围了
