### ISSUE TITLE
SSR Support for v4

### ISSUE THREAD

**Issue by nhatpdXkalapa** [vueComponent/ant-design-vue#6659]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Many components like tooltip, select was working fine in v3 in Nuxt SSR. But when upgrade to v4 it throws error that document is not defined

### What does the proposed API look like?
Support SSR please

**Comment by nhatpdXkalapa** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/125876668/20777116-1463-43ea-b5a7-354804149c98)

**Comment by aibayanyu20** [comment]
try this [demo](https://github.com/antdv-pro/antdv-nuxt-starter)

**Comment by nhatpdXkalapa** [comment]
@aibayanyu20 It seems to work but still lacks support for ssr

**Comment by nhatpdXkalapa** [comment]
[screen-capture.webm](https://github.com/vueComponent/ant-design-vue/assets/125876668/bf10693b-7dd0-4808-aa41-2dad53c1ed2c)

**Comment by antlionguard** [comment]
You can wrap with ClientOnly for workaround.

**Comment by BillEliot** [comment]
so how to solve the problem?

**Comment by vietanhbui** [comment]
+1

**Comment by VasanthThoraliKumaran** [comment]
> You can wrap with `<ClientOnly>` for workaround.

I cannot wrap <ClientOnly> since I'm using Nuxt static site rendering.
