### ISSUE TITLE
Color组件什么时候能够增加？

### ISSUE THREAD

**Issue by tiantianliulang** [vueComponent/ant-design-vue#6661]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
新增Color组件

### What does the proposed API look like?
新增Color组件

**Comment by oooplz** [comment]
you could use third party component [vue3-colorpicker](https://github.com/aesoper101/vue3-colorpicker).
i hope this can help you

**Comment by CCherry07** [comment]
https://github.com/vueComponent/ant-design-vue/pull/6722
