### ISSUE TITLE
Button 组件自定义颜色

### ISSUE THREAD

**Issue by mengxianghan** [vueComponent/ant-design-vue#6667]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
不同场景使用不同颜色的按钮，降低使用组件库以外的按钮颜色时需要写更多的样式适配

### What does the proposed API look like?
<Button color="pink" text-color="#f00">自定义颜色按钮</Button>

传入 color 时，text-color 可以默认白色，当传入的 color 色纸饱和度较低的时候，可以使用text-color定义按钮文本颜色

**Comment by selicens** [comment]
```javascript
<a-config-provider :theme="token: { colorPrimary: 'xx', colorPrimaryText: 'xx' }">
    <a-button type="primary">test</a-button>
<a-config-provide>
```

**Comment by mengxianghan** [comment]
> ```js
> <a-config-provider :theme="token: { colorPrimary: 'xx', colorPrimaryText: 'xx' }">
>     <a-button type="primary">test</a-button>
> <a-config-provide>
> ```

为了使用一个按钮再嵌套一层，太麻烦了吧

**Comment by Yacj** [comment]
同要这个 button 最好加个 color 的 props 根据color 展示不同颜色

**Comment by tangjinzhou** [comment]
please use  style or class to custom
