### ISSUE TITLE
渲染后的表格数据能取到吗？

### ISSUE THREAD

**Issue by cjlhll** [vueComponent/ant-design-vue#667]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
比如我用render加了一些值，但是原始数据是没有改变的。我需要导出当前表格的excel，我怎么取到渲染完的数据？

### What does the proposed API look like?
windows10  chrome73  vue-cli3.0

**Comment by sendya** [comment]
这种需求建议直接对数据做渲染

**Comment by cjlhll** [comment]
> 这种需求建议直接对数据做渲染

好的。了解~  谢谢！

**Comment by cjlhll** [comment]
> 这种需求建议直接对数据做渲染

老哥，还有个问题，如果我直接改数据，比如把状态1，2，3改成审核中，已通过，已拒绝。后面需要判断的时候只能判断中文了啊？
