### ISSUE TITLE
Pagination 组件迷你版本 pageSize 切换器尺寸问题

### ISSUE THREAD

**Issue by mengxianghan** [vueComponent/ant-design-vue#6678]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
Edge 114；window 11

### Reproduction link
[https://next.antdv.com/components/pagination-cn#components-pagination-demo-mini](https://next.antdv.com/components/pagination-cn#components-pagination-demo-mini)

### Steps to reproduce
官网demo，Pagination组件，迷你版本

### What is expected?
pageSize 切换器 和 跳转页码 input 高度保持一致

### What is actually happening?
Pagination 组件迷你版本 pageSize 切换器尺寸和跳转页码 input 高度不一致
![image](https://github.com/vueComponent/ant-design-vue/assets/13127504/52bb6ead-0118-499c-b35c-febff8d1cbee)

**Comment by axbaa** [comment]
1

**Comment by CCherry07** [comment]
这个问题是由于官网未更新导致的
