### ISSUE TITLE
我想在Icon组件中使用font-awesome中的图标，应该怎么做呢？

### ISSUE THREAD

**Issue by penggle** [vueComponent/ant-design-vue#668]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我想在Icon组件中使用font-awesome中的图标，应该怎么做呢？

### What does the proposed API look like?
我想在Icon组件中使用font-awesome中的图标，诸如这样：<a-icon type="fa-home" /> <a-icon type="fa-cog" />

**Comment by ZY2071** [comment]
为啥非要用组件？

**Comment by sendya** [comment]
1. 引入 font-awesome 图标字体
2. 在你需要图标的地方 <i class="图标名" />
