### ISSUE TITLE
tree-select TreeNode props 在设置checkbox模式的时候，每个节点没有checkd属性可以控制是否被选中

### ISSUE THREAD

**Issue by 875817196** [vueComponent/ant-design-vue#6684]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有个实际案例，在一个省市区的选择当时，需要在选中广州市的时候，设置广州市下的区全部不可选且不被选中，不可选可以通过TreeNode props 里的diabled属性实现，但是节点是否可选没有提供对应的属性

### What does the proposed API look like?
希望在TreeNode props里能够新增一个checked属性控制节点的是否选中

**Comment by 875817196** [comment]
现在的问题是会出现，当我选中广州市下的天河区后，在单独选广州市，希望的结果是广州市下的所有区不可选且不被选中，但现在的结果是天河区依旧被选中，但不可选

**Comment by 875817196** [comment]
![截屏2023-06-21 下午3 48 56](https://github.com/vueComponent/ant-design-vue/assets/78201963/7638d486-e683-4dfc-a44a-c73e4d17a78a)

**Comment by coolwehon** [comment]
或许你可以通过控制与该TreeSelect绑定的数据进行控制，将广州市下的子节点清空后，再进行设置不可选中的操作
