### ISSUE TITLE
Right click menu does not work from Tree in 1.X and 2.X

### ISSUE THREAD

**Issue by katerberg** [vueComponent/ant-design-vue#6688]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Firefox or Chrome. Viewable on the site

### Reproduction link
[https://1x.antdv.com/components/tree/](https://1x.antdv.com/components/tree/)

### Steps to reproduce

Right click on any label in a Tree. Nothing happens.

### What is expected?
Browser context menu should open.

### What is actually happening?
Nothing happens because preventDefault is happening from the onNodeContextMenu method which cannot be overriden

---
My previous ticket was auto-closed: https://github.com/vueComponent/ant-design-vue/issues/6430

**Comment by tangjinzhou** [comment]
please update to v3+
