### ISSUE TITLE
MacOS beta版safari 适配问题

### ISSUE THREAD

**Issue by kjlamuro** [vueComponent/ant-design-vue#6690]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
版本17.0 (19616.1.17.11.4)
一个是a-menu组件会报错导致Vue失去响应性,还有4.0的悬浮按钮上移不弹出,其他浏览器目前都正常.
不知道是safari引入了web的新特性还是beta版bug.

**Comment by tangjinzhou** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/6937879/9fc1c1f4-2007-48a4-982f-fea927e62c2a)

没环境测试  😓
