### ISSUE TITLE
Calendar日历组件切换月份的时候会触发onSelect事件

### ISSUE THREAD

**Issue by maybeyj** [vueComponent/ant-design-vue#6694]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
https://github.com/ant-design/ant-design/issues/36578
react版本有一样的问题，可以参考

### What is expected?
点击年月不要触发select事件

### What is actually happening?
点击年月不要触发select事件

**Comment by tangjinzhou** [comment]
https:github.com/ant-design/ant-design/pull/42432/files 
welcome pr
