### ISSUE TITLE
是否有vue版的antd-style  https://github.com/ant-design/antd-style

### ISSUE THREAD

**Issue by agileago** [vueComponent/ant-design-vue#6696]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在最新的ant-desgin-vue中使用 vue版的antd-style

### What does the proposed API look like?
https://github.com/ant-design/antd-style

**Comment by aibayanyu20** [comment]
我们已经开发了一个基于antd-style的样式库，https://github.com/antdv-community/antdv-style

**Comment by agileago** [comment]
> 我们已经开发了一个基于antd-style的样式库，https://github.com/antdv-community/antdv-style

厉害了
