### ISSUE TITLE
表格设置了多列可以拖拽调整宽度(resizable)的时候，拖动其中一列宽度，其他列的宽度也会跟着变化

### ISSUE THREAD

**Issue by viki719632** [vueComponent/ant-design-vue#6702]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
window10，Chrome 114.0.5735.199，vue@3.3.4

### Reproduction link
[https://www.antdv.com/components/table-cn/#components-table-demo-nested-table](https://www.antdv.com/components/table-cn/#components-table-demo-nested-table)

### Steps to reproduce
1.设置表格其中两列resizable为true，width也设置一下
2.最后一列设置一下width，不需要resizable
3.拖拽调整列宽的时候 会发现其他列的宽度也在变化

### What is expected?
拖拽调整列宽的时候 其他列的宽度不变

### What is actually happening?
如果最后一列不设置宽度  就不会有这个问题

**Comment by lion2535** [comment]
赞同！这个问题还会导致，当选择部分列不展示后，checkedbox和index之类的列的宽度占比较大。
若不设置最后一列的宽度会导致在伸缩列时，拉伸某列至浏览器当前宽度的100%，出现滚动条，其他设置了宽度的列都会正常宽度展示，但是最后一列的宽度变成0，会直接隐藏。
若所有列都设置宽度，把某列收缩至最小值，其他列都会自动分配收缩的值。（期望：可以通过设置某个属性来控制某列不去自动分配该收缩的值，由除了该列的其他列去分配值）
