### ISSUE TITLE
AutoComplete 在使用自定义列表时出现问题 #option报错

### ISSUE THREAD

**Issue by xiaozan888** [vueComponent/ant-design-vue#6704]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.5

### Environment
vue 最新版本 node18以上

### Reproduction link 未找到4.0.0-rc.5 sorry
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-6d7sgg?file=/src/App.vue)

### Steps to reproduce
<a-auto-complete
v-if="useStore().sidebarOpened"
v-model:value="word"
class="w-100% mr-12 h-32"
:dropdown-match-select-width="108"
:options="menuList"
@select="onSelect"
@search="handleSearch"
>
<template #option="item">
<div class="flex items-center">
<iconfont
:type="item.icon"
class="mr-10 !text-20 !text-primary"
></iconfont>
<div
class="text-14 font-400"
v-html="formatText(item.label, searchWord)"
></div>
</div>
</template>

</a-auto-complete>

属性“option”在类型“Readonly<{ options: any; default: any; notFoundContent: any; dataSource: any; }>
#option 报错

### What is expected?
报错消失

### What is actually happening?
这种错误导致无法验证通过，不能build

**Comment by xiaozan888** [comment]
大概多久会得到回复

**Comment by CCherry07** [comment]
我来看看 @xiaozan888

**Comment by xiaozan888** [comment]
在4.0.0-rc.4当中做了尝试，未看到类似提示，在我的项目中出现了该问题（不确定和版本有没有关系）
![image](https://github.com/vueComponent/ant-design-vue/assets/86096823/e3ec555d-1266-452b-ac67-dfa3a72ba89f)

**Comment by CCherry07** [comment]
你现在通过自己的方式解决了吗？

**Comment by xiaozan888** [comment]
在新版本4.0.0中未出现上述错误

**Comment by CCherry07** [comment]
好的

**Comment by fskarmeta** [comment]
@xiaozan888 i'm on 4.0.7 and still have this typing issue

@CCherry07 was it fixed for you ??


![Screenshot 2023-11-28 at 23 40 36](https://github.com/vueComponent/ant-design-vue/assets/69222982/51495177-af11-4fe7-8baa-668e55057397)
