### ISSUE TITLE
a-style-provider 在 ^4.0.0-rc.5 中显示弃用 那我该怎么进行取消:where

### ISSUE THREAD

**Issue by afl-lxw** [vueComponent/ant-design-vue#6707]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
能够使我自由的更改样式

### What does the proposed API look like?
Chrome 已是最新版本
版本 114.0.5735.198（正式版本） (arm64)
Vue: 3.3.4
macOS Ventura 13.5 Beta版

**Comment by CCherry07** [comment]
参考: https://next.antdv.com/docs/vue/compatible-style-cn

**Comment by afl-lxw** [comment]
> 参考：[https://next.antdv.com/docs/vue/known-style-cn](https://next.antdv.com/docs/vue/compatible-style-cn)

<img width="1009" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/325a386d-42b2-4347-a500-1b76f86eb403">
<img width="512" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/b0c940b1-df6e-455d-84a5-adcd444fb983">

**Comment by CCherry07** [comment]
是否是正常工作的呢？

**Comment by afl-lxw** [comment]
> 是否是正常工作的呢？

没有生效 样式还都是附带:where 没有正常工作

**Comment by CCherry07** [comment]
你看看这个[demo](https://codesandbox.io/s/an-niu-lei-xing-ant-design-vue-4-0-0-rc-4-forked-h9n8tv?file=/src/App.vue)

**Comment by afl-lxw** [comment]
> 

我不知道你给的这个demo 为啥会没有那个提示
我现在项目的场景是这样的  我需要使用穿透(例子) :deep(.ant-menu-item)   单独修改几个menu的样式 
所以就我上述提的问题 在我的项目中 使用a-style-provider 一直是会报以下错误 
<img width="1169" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/91bc6b87-c22f-4371-9934-beaa5cfe55a1">
并且 我去问过chatGPT 以下问题
<img width="728" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/f8eaaf05-81aa-417d-936a-d885853e9146">
我提供一下 我项目中所涉及到的依赖 
<img width="363" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/355a9647-d467-46c3-bd2c-fa7213b640b9">
看看是什么问题导致  或者说是 这个组件就是在4版本中 暂时被弃用了  我最终的原意是想使用 deep 穿透 单独去修改几个样式 但就是因为 :where 降权不了 我暂时改不了

**Comment by aibayanyu20** [comment]
你是不是按需加载的组件库，如果是按需加载目前使用unplugin-vue-components中的resolver还不支持styleProvider可以使用手动注册的方式
[main.ts]
```
import { StyleProvider } from "ant-design-vue"
// ...
app.use(StyleProvider)
```

**Comment by afl-lxw** [comment]
> 你是不是按需加载的组件库，如果是按需加载目前使用unplugin-vue-components中的resolver还不支持styleProvider可以使用手动注册的方式 [main.ts]
> 
> ```ts
> import { StyleProvider } from "ant-design-vue"
> // ...
> app.use(StyleProvider)
> ```
> 
> 或者使用[antdv-component-resolver](https://www.npmjs.com/package/antdv-component-resolver/v/0.0.1-alpha.3)

感谢🙏
