### ISSUE TITLE
CSS-in-JS 如何将 hashId 添加到 less 的 modifyVars 中？

### ISSUE THREAD

**Issue by think-gem** [vueComponent/ant-design-vue#6708]
### Version
4.0.0-rc.5

### Environment
vite4、vue3

### Steps to reproduce
vite.config.js中配置：
```
import { theme } from 'ant-design-vue';
......
  css: {
      preprocessorOptions: {
        less: {
          modifyVars: {
                hashId: theme.useToken().hashId
          },
        },
      },
    },
......
```

### What is expected?
在 less 文件或代码块里获取 hashId值（.css-dev-only-do-not-override-j6gjt1）。例如： @{hashId}、@hashId

### What is actually happening?
视乎加载过早，提示错误：
```
21:20:38 [vite] Cannot read properties of undefined (reading 'hashed')
```

### Any additional comments? (optional)

1、在 StyleProvider 中，期望自己可以自定义 hashId 值（.css-dev-only-do-not-override-j6gjt1）
2、或者在 less 中得到 hashId 值，方便兼容旧样式
3、另外我尝试过 :class 替换为 :className，但是会覆盖 antdv 的默认 class

**Comment by CCherry07** [comment]
@think-gem @UphkcRNqmafQWcSSSSSS 
这个也可以参考一下 #6699

**Comment by think-gem** [comment]
谢谢各位同学，在less中我可以得到antdv的颜色变量，文档里有这块介绍
```
import { theme } from 'ant-design-vue';
const { defaultAlgorithm, defaultSeed } = theme;
const mapToken = defaultAlgorithm(defaultSeed);
```
我目前是想得到hashId值，mapToken里并没有。

目前我使用了另外 一种css优先级的方案，进行覆写样式，就不需要考虑hashId了。
