### ISSUE TITLE
DatePicker prop "value". Expected Object | String, got Number with value 1685589431

### ISSUE THREAD

**Issue by rashagu** [vueComponent/ant-design-vue#6712]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
edge 114

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
DatePicker 组件的value属性,当它使用时间戳时，发出了以下警告
```
AddEdit.vue:73  [Vue warn]: Invalid prop: type check failed for prop "value". Expected Object | String, got Number with value 1685589431.    at <ADatePicker key=16 type="date" disabled=false  ... >
```

### What is expected?
value应该要支持number类型

### What is actually happening?
value不支持number类型, vue 发出了警告

**Comment by CCherry07** [comment]
可以使用dayjs 进行包裹 

```ts
dayjs(date)
```

**Comment by rashagu** [comment]
> 可以使用dayjs 进行包裹
> 
> ```ts
> dayjs(date)
> ```

只是有警告而已，传number类型实际上也可以正常使用的
