### ISSUE TITLE
Modal中引入a-from和a-table之后， 弹框打开很慢，点击触发弹框按钮，约1s中后弹框才出现

### ISSUE THREAD

**Issue by kankantian** [vueComponent/ant-design-vue#6714]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
Nodejs v14.18.0  pnpm v7.27.0

### What is expected?
先弹出窗口再动态加载form、table, 渲染数据

### What is actually happening?
目前是请求完成、数据渲染之后，弹框才出现

**Comment by liujiayii** [comment]
楼主是怎么解决的呢？确实很卡

**Comment by tetap** [comment]
Modal Popover变得非常卡！！！

**Comment by kankantian** [comment]
重新编译运行就好了
