### ISSUE TITLE
table select style

### ISSUE THREAD

**Issue by afl-lxw** [vueComponent/ant-design-vue#6721]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
样式上的美化问题
<img width="1502" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/56349292/0b8c97ad-7f8b-4d8c-b5ec-cbe17b0d256b">

当我使用带有border- radios风格的表格  当我连续选中时 其旁边接触的部分 会有一部分的缺角 我认为是挺影响美观的 
如果说设计风格是这样 我觉得可以做一个优化点  

### What does the proposed API look like?
连续选中的背景色 是连续的 
当有两个或者两个以上的选中 其之间接触的背景色 是相容接触的

**Comment by nabaonan** [comment]
感觉这个和react版本的 同步一下table的style样式就好了
