### ISSUE TITLE
Tree 树形控件 为什么选中一个子节点却得不到父节点的值

### ISSUE THREAD

**Issue by JHeLiu** [vueComponent/ant-design-vue#6724]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当设计角色权限的时候，需要选中某一个父级菜单下面的某些子菜单，而不是全选中，这个时候无法获取到父级菜单的值

### What does the proposed API look like?
选中子级一个或者多个，而不是全选中的时候，应该保存父级key ，在 checkedKeys中得到

**Comment by mqhe2007** [comment]
同问

**Comment by H-hejin** [comment]
加1
