### ISSUE TITLE
a-tree组件数据量过大展开卡顿慢的问题如何解决

### ISSUE THREAD

**Issue by Reeyc** [vueComponent/ant-design-vue#6725]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
window10, chrome107.0.5304.107, Vue3.2.16

### Reproduction link
[http://没有在线demo](http://没有在线demo)

### Steps to reproduce
数据量过大，导致展开卡顿很慢

### What is expected?
希望展开流畅

### What is actually happening?
ant-design-vue版本从v2升级到v3，再到v4，height虚拟滚动也用了，还是展开很慢，如何优化

**Comment by KTBOY** [comment]
可以使用IntersectionObserver监听当前可以展示tree节点，避免一次性展开tree节点
