### ISSUE TITLE
Tabs很多个的时候，删除多余的页签，左下角会出现一个小白条

### ISSUE THREAD

**Issue by wangmin0314** [vueComponent/ant-design-vue#6727]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
os version：macOS Big Sur 11.6、browser version：Chrome 101.0.4951.64（正式版本） (x86_64)、Vue version：3.2.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v8evrc?file=/src/demo.vue)

### Steps to reproduce
1.打开官方文档，https://www.antdv.com/components/tabs-cn
2. 新增和删除页签示例
3.新增多个页签，直到出现更多页签的图标，删除更多下的页签，删除更多里最后一个以后，左下角会出现一个小白条
![image](https://github.com/vueComponent/ant-design-vue/assets/23734878/c5d6cbb7-1a34-4c6a-ac52-b7cc2053ac9f)
![image](https://github.com/vueComponent/ant-design-vue/assets/23734878/3e2756a0-8f97-4b98-9036-d986fb5e12f8)

### What is expected?
不出现小白条

**Comment by CCherry07** [comment]
了解

**Comment by wangmin0314** [comment]
> 了解

希望修复

**Comment by CCherry07** [comment]
给我一点时间 @wangmin0314

**Comment by wangmin0314** [comment]
@CCherry07 我直接升级就好了吗？

**Comment by zou-uoz** [comment]
请问修复了吗？要怎么解决呢？

**Comment by aibayanyu20** [comment]
#6757

**Comment by aibayanyu20** [comment]
> 请问修复了吗？要怎么解决呢？

#6757

**Comment by wangmin0314** [comment]
> 给我一点时间 @wangmin0314

我在官网4.0.0和3.x看的官方示例，这个问题还是没修复啊，我用的是3.2.20版本

**Comment by aibayanyu20** [comment]
> > 给我一点时间 @wangmin0314
> > @CCherry07
> > 我在官网4.0.0和3.x看的官方示例，这个问题还是没修复啊，我用的是3.2.20版本

已合并，等发版

**Comment by wangmin0314** [comment]
> > > 给我一点时间 @wangmin0314
> > > @CCherry07
> > > 我在官网4.0.0和3.x看的官方示例，这个问题还是没修复啊，我用的是3.2.20版本
> 
> 已合并，等发版

@aibayanyu20 什么时间发版啊？两周了还没发

**Comment by aibayanyu20** [comment]
> > > > 给我一点时间 @wangmin0314
> > > > @CCherry07
> > > > 我在官网4.0.0和3.x看的官方示例，这个问题还是没修复啊，我用的是3.2.20版本
> > 
> > 
> > 已合并，等发版
> 
> @aibayanyu20 什么时间发版啊？两周了还没发

已经发了4.0.1

**Comment by wangmin0314** [comment]
> 

3.X的版本什么时候发呀？

> > > > > 给我一点时间 @wangmin0314
> > > > > @CCherry07
> > > > > 我在官网4.0.0和3.x看的官方示例，这个问题还是没修复啊，我用的是3.2.20版本
> > > 
> > > 
> > > 已合并，等发版
> > 
> > 
> > @aibayanyu20 什么时间发版啊？两周了还没发
> 
> 已经发了4.0.1

3.x的版本什么时候发呀？

**Comment by wangmin0314** [comment]
@aibayanyu20 是不是3.X不会再发版了呀？
