### ISSUE TITLE
drawer 内嵌渲染在当前 dom 里自定义容器 按照官网案例 代码 drawer不显示  

### ISSUE THREAD

**Issue by LXJ-ziLiang** [vueComponent/ant-design-vue#6728]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue3.2.37

### Reproduction link
[https://antdv.com/components/drawer-cn/#components-drawer-demo-multi-level-drawer](https://antdv.com/components/drawer-cn/#components-drawer-demo-multi-level-drawer)

### Steps to reproduce
<div
:style="{
height: '200px',
overflow: 'hidden',
position: 'relative',
border: '1px solid #ebedf0',
borderRadius: '2px',
padding: '48px',
textAlign: 'center',
background: '#fafafa',
width: '100%'
}"
>

Render in this
<div style="margin-top: 16px">
<a-button type="primary" @click="showDrawer">Open</a-button>
</div>
<a-drawer
title="Basic Drawer"
placement="right"
:closable="false"
:visible="visible"
:get-container="false"
:style="{ position: 'absolute' }"
@close="onClose"
>
<p>Some contents...</p>
</a-drawer>
</div>

### What is expected?
drawer 显示在父级元素内

### What is actually happening?
复制黏贴 官网案例代码 drawer 不显示

**Comment by LXJ-ziLiang** [comment]
<img width="1132" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23183291/27b7ee8d-b8b7-41a6-8db7-a136891e6190">
<img width="1417" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23183291/40bdb1eb-db8e-42cb-82d9-7dbf55266bd4">

嵌入位置是对的 但是 没有高度 显示不出来

**Comment by aibayanyu20** [comment]
具体为什么不显示出来建议提交一个复现的最小demo，官网例子我点了一下没有复现你的问题

**Comment by LXJ-ziLiang** [comment]
<img width="286" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23183291/b889e80c-96ce-42ca-b42e-f6bb9ae89840">

**Comment by LXJ-ziLiang** [comment]
<img width="286" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23183291/5e983585-91f2-495f-9c92-bbcbf3f967c9">
找到问题了 是我全局设置的一个css position:relative 去了就行
