### ISSUE TITLE
4.0.0版本的 Modal.confirm的okText默认文字 为"知道了"

### ISSUE THREAD

**Issue by shadowfined** [vueComponent/ant-design-vue#6745]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
VUE3

### Reproduction link
[https://antdv.com/components/modal-cn](https://antdv.com/components/modal-cn)

### Steps to reproduce
点击弹框按钮

### What is expected?
okText默认为"确认"

### What is actually happening?
okText为"知道了"

**Comment by selicens** [comment]
ant-design5.7.0 okText文字是确定，同步这个，嘿嘿嘿
