### ISSUE TITLE
增加样式兼容后在组件中使用unocss的class不生效

### ISSUE THREAD

**Issue by holiy930561** [vueComponent/ant-design-vue#6749]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
上面最小化demo

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-ugq7b4](https://stackblitz.com/edit/vitejs-vite-ugq7b4)

### Steps to reproduce
```
1，增加  <a-style-provider hash-priority="high">
2，   <a-form ml-24px my-24px class="px-20px">
```

### What is expected?
form组件中使用的unocss生效

### What is actually happening?
使用样式兼容后 ml-24px my-24px px-20px不生效，被覆盖了。去掉样式兼容是正常生效的

![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/e44f368c-1a0c-480f-88de-c214c456c1f6)

**Comment by CCherry07** [comment]
你使用一下这个插件的 https://www.npmjs.com/package/postcss-increase-specificity 看看

**Comment by holiy930561** [comment]
message组件挂载到app下面 样式兼容不生效
![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/4d0a73cc-55d9-4ae2-866d-b024767e92df)

**Comment by aibayanyu20** [comment]
[antdv-pro#8](https://github.com/antdv-pro/antdv-pro/issues/8)
