### ISSUE TITLE
config-provider 组件如何做到响应式切换预设主题

### ISSUE THREAD

**Issue by daiwz** [vueComponent/ant-design-vue#6750]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
vue3.3.4

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
var globalTheme = reactive({})
const { storeTheme } = storeToRefs(controlStore())
watch(storeTheme, (newValue, oldValue) => {
if (newValue === "light") {
globalTheme = { ...defaultTheme, algorithm: theme.defaultAlgorithm }
} else {
// dark
globalTheme = { ...darkTheme, algorithm: theme.darkAlgorithm, }
}
},
{ immediate: true });

<a-config-provider :theme="globalTheme" @getPopupContainer="getPopupContainer">
<layout />
</a-config-provider>

### What is expected?
config-provider 组件如何做到响应式切换预设主题？

### What is actually happening?
通过修改算法可以快速生成风格迥异的主题，4.0 版本中默认提供三套预设算法，分别是默认算法 theme.defaultAlgorithm、暗色算法 theme.darkAlgorithm 和紧凑算法 theme.compactAlgorithm。你可以通过修改 ConfigProvider 中 theme 属性的 algorithm 属性来切换算法。发现修改的算法并非是响应式，请问如何才能做到响应式设置预设算法？

**Comment by CCherry07** [comment]
你这个写法失去了；响应式globalTheme，被重新赋值了，建议用ref定义

**Comment by robkah** [comment]
Hey @anhthang , the issue is that your watcher is listing only for new changes.
you just need add  **{ immediate: true }** to get the current state.

```
watch(
  () => colorMode.value,
  () => {
    if (colorMode.value === 'dark') {
      themeConfig.value.algorithm = theme.darkAlgorithm
    } else {
      themeConfig.value.algorithm = theme.defaultAlgorithm
    }
  },
  { immediate: true },
)
</script>

```
