### ISSUE TITLE
DateRangePicker not working at all

### ISSUE THREAD

**Issue by Ghostru-cmd** [vueComponent/ant-design-vue#6752]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Vue 3.3.1 Ubuntu 22.04

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-bessie-tptyll?file=/src/App.vue)

### Steps to reproduce
Try to use

### What is expected?
DateRangePicker showing on page

### What is actually happening?
DateRangePicker not showing on page

---
If you try to build a project on webpack, it will write that it cannot find styles
If you add an empty index.ts file to node_modules/ant-design-vue/es/time-picker/style, everything will work

**Comment by CCherry07** [comment]
look this  https://antdv.com/components/time-picker/#when-to-use

**Comment by Ghostru-cmd** [comment]
I have read the documentation. If this was the problem, then I would not be able to fix it by adding the file

**Comment by CCherry07** [comment]
Please upgrade to the latest

```bash
npm i ant-design-vue@4.0.0
```

**Comment by Ghostru-cmd** [comment]
Already tried this

**Comment by CCherry07** [comment]
https://codesandbox.io/s/fan-wei-xuan-ze-qi-ant-design-vue-4-0-0-forked-kmtv93?file=/src/demo.vue

**Comment by Ghostru-cmd** [comment]
I don't understand why it doesn't work for me, but thanks. I will close this issue

**Comment by Ghostru-cmd** [comment]
The solution to this problem turned out to be simple.
Need to import not 'ant-design-vue' but 'ant-design-vue/lib'
