### ISSUE TITLE
Missing styles in low-version browsers

### ISSUE THREAD

**Issue by leeskyler-top** [vueComponent/ant-design-vue#6753]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Dev Env:Win10   Apache2 (latest xampp)   npm 9.5.1   Vite 4.4.4   Vue3   JS; Current Bug Device:[iPhone7, iOS 12.3.1, Safari],[iPad gen6, iOS 12.1.3, Safari],[Android 12, WeChat 8.0.30 Browser]

### Reproduction link
[https://github.com/leeskyler-top/SITC-Publicity](https://github.com/leeskyler-top/SITC-Publicity)

### Steps to reproduce
git clone https://github.com/leeskyler-top/SITC-Publicity.git (克隆此项目)
npm install (安装依赖)
npm run build (打包)
Open the built web page on these bug device or browser. (在较低或上述提到的设备或是浏览器中打开打包后的页面)

### What is expected?
No style problems on any device.
在所有设备上，只要不是特别旧的设备，可以正常显示所有样式

### What is actually happening?
All the antdv Components' style were missed!
所有与antdv组件自带的样式全部丢失。

---

**Comment by holiy930561** [comment]
https://www.antdv.com/docs/vue/compatible-style-cn
![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/ce595059-0815-49e8-b3b7-0cf1519ee3d1)

**Comment by leeskyler-top** [comment]
感谢，问题已按照此文档解决。
