### ISSUE TITLE
antd4 PageHeader的ghost无论设置false或true，都会有白色背景

### ISSUE THREAD

**Issue by 741599086** [vueComponent/ant-design-vue#6755]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
antd4 PageHeader的ghost无论设置false或true，都会有白色背景

### Steps to reproduce
antd4 PageHeader的ghost无论设置false或true，都会有白色背景

### What is expected?
ghost参数正常工作

### What is actually happening?
antd4 PageHeader的ghost无论设置false或true，都会有白色背景

**Comment by CCherry07** [comment]
可以给一个demo吗？
