### ISSUE TITLE
styleprovider无法消费样式降级

### ISSUE THREAD

**Issue by holiy930561** [vueComponent/ant-design-vue#6756]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
上面最小化demo

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-ugq7b4](https://stackblitz.com/edit/vitejs-vite-ugq7b4)

### Steps to reproduce
1，styleprovider
2，使用message组件

### What is expected?
使用styleprovider，message的样式可以降级

### What is actually happening?
message的样式无法降级，还是:where

![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/7635ce6d-186b-4a82-9a91-7372616a7edb)

**Comment by CCherry07** [comment]
推荐使用hooks调用模式

**Comment by aibayanyu20** [comment]
调整支持了，[参考代码](https://github.com/antdv-pro/antdv-pro/commit/d0c031a5d632429083030b6f639ba864fa0e7841)

**Comment by holiy930561** [comment]
![企业微信截图_16897628055260](https://github.com/vueComponent/ant-design-vue/assets/63273780/50e4c5e3-bb86-470d-9b8c-5c9c89ad186e)
![image](https://github.com/vueComponent/ant-design-vue/assets/63273780/f1439952-4bdb-4375-a129-67ff59689ac2)

popover 箭头样式兼容问题

**Comment by holiy930561** [comment]
> ![企业微信截图_16897628055260](https://user-images.githubusercontent.com/63273780/254546952-50e4c5e3-bb86-470d-9b8c-5c9c89ad186e.png) ![image](https://user-images.githubusercontent.com/63273780/254547015-f1439952-4bdb-4375-a129-67ff59689ac2.png)
> 
> popover 箭头样式兼容问题

解决了，浏览器不支持path
.ant-tooltip-arrow::before {
      clip-path: polygon(25% 100%, 50% 0%, 75% 100%);
    }

**Comment by CCherry07** [comment]
> 

https://antdv.com/docs/vue/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7

这个应该能帮助到你

**Comment by CCherry07** [comment]
> > ![企业微信截图_16897628055260](https://user-images.githubusercontent.com/63273780/254546952-50e4c5e3-bb86-470d-9b8c-5c9c89ad186e.png) ![image](https://user-images.githubusercontent.com/63273780/254547015-f1439952-4bdb-4375-a129-67ff59689ac2.png)
> > popover 箭头样式兼容问题
> 
> 解决了，浏览器不支持path .ant-tooltip-arrow::before { clip-path: polygon(25% 100%, 50% 0%, 75% 100%); }

https://antdv.com/docs/vue/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7

这个应该能帮助到你

**Comment by holiy930561** [comment]
> > > ![企业微信截图_16897628055260](https://user-images.githubusercontent.com/63273780/254546952-50e4c5e3-bb86-470d-9b8c-5c9c89ad186e.png) ![image](https://user-images.githubusercontent.com/63273780/254547015-f1439952-4bdb-4375-a129-67ff59689ac2.png)
> > > popover 箭头样式兼容问题
> > 
> > 
> > 解决了，浏览器不支持path .ant-tooltip-arrow::before { clip-path: polygon(25% 100%, 50% 0%, 75% 100%); }
> 
> https://antdv.com/docs/vue/compatible-style-cn#css-%E9%80%BB%E8%BE%91%E5%B1%9E%E6%80%A7
> 
> 这个应该能帮助到你

使用了legacyLogicalPropertiesTransformer，但是没有处理clip-path的兼容性，参考antd的方案处理的
https://github.com/ant-design/ant-design/pull/41872
