### ISSUE TITLE
最新版本中按需加载水印组件时报警告

### ISSUE THREAD

**Issue by horsecms** [vueComponent/ant-design-vue#6759]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
chrome 116.0.5845.4, vue3.2.36，

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
no

### What is expected?
Failed to resolve component: a-watermark
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

### What is actually happening?
Failed to resolve component: a-watermark
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by CCherry07** [comment]
按需加载的插件还没有更新

**Comment by aibayanyu20** [comment]
可以考虑暂时先用[antdv-resolver](https://www.npmjs.com/package/antdv-component-resolver)代替

**Comment by horsecms** [comment]
> 按需加载的插件还没有更新 #6596

好的，那请问有更新计划吗？

**Comment by horsecms** [comment]
> 可以考虑暂时先用[antdv-resolver](https://www.npmjs.com/package/antdv-component-resolver)代替

好的  谢谢

**Comment by horsecms** [comment]
> 可以考虑暂时先用[antdv-resolver](https://www.npmjs.com/package/antdv-component-resolver)代替

好的  谢谢

**Comment by aibayanyu20** [comment]
> 
PR已经过去了，等合并就好了

**Comment by horsecms** [comment]
> > 
> 
> PR已经过去了，等合并就好了

ok  谢谢
