### ISSUE TITLE
useModal 调用destory报错

### ISSUE THREAD

**Issue by holiy930561** [vueComponent/ant-design-vue#6760]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
上面最小化demo

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-ugq7b4](https://stackblitz.com/edit/vitejs-vite-ugq7b4)

### Steps to reproduce
打开重现地址

### What is expected?
useModal 可以调用destory，destoryAll

### What is actually happening?
Uncaught TypeError: modal.destory is not a function

**Comment by aibayanyu20** [comment]
[demo](https://stackblitz.com/edit/vitejs-vite-pnmycj?file=src%2FApp.vue)
