### ISSUE TITLE
tree 组件无法将子节点拖拽至父节点同级(向下拖拽!!!)

### ISSUE THREAD

**Issue by guowenqing1** [vueComponent/ant-design-vue#6765]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
google浏览器、Vue3、ant design Vue 官方文档

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tuo-dong-shi-li-ant-design-vue-3-2-20-forked-qj65wh)

### Steps to reproduce
文字描述步骤：
1. 0-0 和 0-1 是最外层节点，0-0 节点中存在子节点: 0-0-0、0-0-1、0-0-2；
1. 我想将 0-0-1 拖动到 0-0 和 0-1 的中间(和他们变成同级关系)；
1. 这个时候我将 0-0-1 “向下拖动” 却发现无法拖动到它们中间；
1. 我尝试去调试却发现目标节点居然还是 0-0；

#### 图片示例一：tree节点截图
![](https://lxy-1304560110.cos.ap-nanjing.myqcloud.com/gwq.png)

#### 图片示例二: 拖动截图
![](https://lxy-1304560110.cos.ap-nanjing.myqcloud.com/and.png)

#### 备注：
1. 如果 codesandbox 无法正常运行，可以访问官方文档 https://3x.antdv.com/components/tree-cn 中的拖动示例
1. 如果图片无法正常打开，可以访问图片链接
- 图片示例一：tree节点截图  https://lxy-1304560110.cos.ap-nanjing.myqcloud.com/gwq.png
- 图片示例二: 拖动截图   https://lxy-1304560110.cos.ap-nanjing.myqcloud.com/and.png

### What is expected?
我希望能实现将 “子节点” 向下拖拽为父节点同级 的效果；

### What is actually happening?
我希望可以认真的去按照我的描述去尝试这个问题，我保证它是真的存在，谢谢；

**Comment by CCherry07** [comment]
请删掉

这段case

```ts

// ...
 else if (
        (info.node.children || []).length > 0 && // Has children
        info.node.expanded && // Is expanded
        dropPosition === 1 // On the bottom gap
      ) {
        loop(data, dropKey, (item: TreeDataItem) => {
          item.children = item.children || [];
          // where to insert 示例添加到头部，可以是随意位置
          item.children.unshift(dragObj);
        });
      }
// ...
```
