### ISSUE TITLE
拉动表格 报错 

### ISSUE THREAD

**Issue by swj857578** [vueComponent/ant-design-vue#6766]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
谷歌浏览器114.0.5735.199   vue3 版本

### Reproduction link
[http://xxxx.com](http://xxxx.com)

### Steps to reproduce
必现的，打开带表格的界面就报错
具体报错如下：
ResizeObserver loop completed with undelivered notifications.
ResizeObserver loop limit exceeded

### What is expected?
目前接入了报警平台 ，期望早日解决，不需要上报这种错误

### What is actually happening?
目前接入了报警平台 ，期望早日解决，不需要上报这种错误

**Comment by JIMhackKING** [comment]
我这里得到了一个类似的报错，使用

# Version
4.0.6

# Environment
1. Chrome:  118.0.5993.71
2. Vue3
3. Windows10

# Reproduction link
https://codesandbox.io/s/youthful-mclaren-cgyzdg?file=/src/App.vue
