### ISSUE TITLE
是否可以提供一个校验其他组件的demo?

### ISSUE THREAD

**Issue by horsecms** [vueComponent/ant-design-vue#6773]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
https://antdv.com/components/form-cn#components-form-demo-validate-other， 能否提供一个校验其他组件的demo，即不通过a-form-item的rules进行校验，而是通过类似formItemContext.onFieldChange()  或者useForm的某个方法进行的校验，用于封装一些公共方法，同时避免每次都要重复的写特殊校验规则

### What does the proposed API look like?
https://antdv.com/components/form-cn#components-form-demo-validate-other

**Comment by aibayanyu20** [comment]
目前没有脱离a-form-item实现校验的方式吧，如果有需要可以自己通过[async-validator](https://www.npmjs.com/package/async-validator)去实现

**Comment by horsecms** [comment]
ok
