### ISSUE TITLE
生产环境下偶尔出现图标乱码，无图标的位置会出现A符号

### ISSUE THREAD

**Issue by XZYW** [vueComponent/ant-design-vue#6774]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Vue：3.3.4 
Vite：4.3.8
Antdv：3.2.20 
Less：4.1.3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
在开发环境下，没有出现过任何问题，但当我部署到线上时，它偶尔会出现乱码的图标
![image](https://github.com/vueComponent/ant-design-vue/assets/42271882/713212c0-c902-402b-9a3f-551b3b50cfe8)
![image](https://github.com/vueComponent/ant-design-vue/assets/42271882/16e1cc13-52f3-4ece-9b97-55919c9cfcde)

### What is expected?
尽可能提供指导和帮助。

### What is actually happening?
在生产环境下会偶尔出现乱码的图标。
我已经尝试过在网络上搜索答案，有很多element的用户都碰到这个问题，原因是项目和组件库使用sass的版本不一致，将dart sass切换成node sass可以很好的解决这个问题。可是我对比过了，我的less版本和antdv使用的是一样的。我翻阅了repo issue，并没有找到类似的情况。
我不知道究竟发生了什么，如果能提供帮助，不胜感激。

---
很抱歉我无法提供一个这样的重现，因为它是极低概率在生产环境下偶发的

**Comment by XZYW** [comment]
补充：这些乱码出现的位置其实是没有icon的，查看元素之后发现content属性变成了这个字符，原本应该是空。另外目前也只会出现这个乱码。

**Comment by aibayanyu20** [comment]
可能需要提供一个复现在能帮你排查问题，我看了一个pro版本的没有发现你这样的问题，https://store.antdv.com/pro/preview/workplace

**Comment by XZYW** [comment]
@aibayanyu20 你好，感谢你的回复，但是这个问题是在我的生产环境下偶尔发生的，概率极低，大概20次会有一次这样。因为相关约定，我无法将生产环境提供给你，非常抱歉。您知道可能的原因吗？这个问题在element ui挺容易发生的，我按照网上的修复教程使用错误的sass版本就能够复现

**Comment by appleaway** [comment]
> @aibayanyu20 你好，感谢你的回复，但是这个问题是在我的生产环境下偶尔发生的，概率极低，大概20次会有一次这样。因为相关约定，我无法将生产环境提供给你，非常抱歉。您知道可能的原因吗？这个问题在element ui挺容易发生的，我按照网上的修复教程使用错误的sass版本就能够复现

https://xie.infoq.cn/article/53858953f82c403e2d484f2ea 这个链接底下有相关问题和解决方案，可以试下

**Comment by TLovers** [comment]
我也有这样的问题

**Comment by TLovers** [comment]
<img width="846" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/26561694/3775d558-870d-44d4-bf27-0e018b609d31">

**Comment by TLovers** [comment]
> > @aibayanyu20 你好，感谢你的回复，但是这个问题是在我的生产环境下偶尔发生的，概率极低，大概20次会有一次这样。因为相关约定，我无法将生产环境提供给你，非常抱歉。您知道可能的原因吗？这个问题在element ui挺容易发生的，我按照网上的修复教程使用错误的sass版本就能够复现
> 
> https://xie.infoq.cn/article/53858953f82c403e2d484f2ea 这个链接底下有相关问题和解决方案，可以试下

我们项目没有使用sass  使用的是less，不过按照这样操作无效

**Comment by TLovers** [comment]
> 可能需要提供一个复现才能帮你排查问题，我看了一下pro版本的没有发现你这样的问题，https://store.antdv.com/pro/preview/workplace

这是极低概率出现的 不是必现 测试测试很多次才会出现1次到2次

**Comment by XZYW** [comment]
> > @aibayanyu20 你好，感谢你的回复，但是这个问题是在我的生产环境下偶尔发生的，概率极低，大概20次会有一次这样。因为相关约定，我无法将生产环境提供给你，非常抱歉。您知道可能的原因吗？这个问题在element ui挺容易发生的，我按照网上的修复教程使用错误的sass版本就能够复现
> 
> https://xie.infoq.cn/article/53858953f82c403e2d484f2ea 这个链接底下有相关问题和解决方案，可以试下

网络上有挺多element ui的解决方案，但是less的却还没有看到

**Comment by aibayanyu20** [comment]
这个我尝试复现一下吧，提供一下你的node版本和打包环境

**Comment by TLovers** [comment]
这个问题有消息吗~~~

**Comment by aibayanyu20** [comment]
这个我测试了一下，linux和mac环境没有复现这个问题，win11的虚拟机也没有复现重复打包十多次没有复现，你们能复现的可以给一个最小的复现demo让我再跑一下试试

**Comment by TLovers** [comment]
> 这个我测试了一下，linux和mac环境没有复现这个问题，win11的虚拟机也没有复现重复打包十多次没有复现，你们能复现的可以给一个最小的复现demo让我再跑一下试试

主要这玩意很多次才会出现1次，但是出现1次后大概率又出现一次，后面又很难复现。只有3版本出现过这个问题，另一个项目2版本的没出现现过

**Comment by aibayanyu20** [comment]
> > 这个我测试了一下，linux和mac环境没有复现这个问题，win11的虚拟机也没有复现重复打包十多次没有复现，你们能复现的可以给一个最小的复现demo让我再跑一下试试
> 
> 主要这玩意很多次才会出现1次，但是出现1次后大概率又出现一次，后面又很难复现。只有3版本出现过这个问题，另一个项目2版本的没出现现过

可以考虑升4试试

**Comment by TLovers** [comment]
> 

没有。看了下4 和3 的差异，不敢升级。

**Comment by XZYW** [comment]
应该是构建配置的问题，已经很久没有复现了，在这期间我只是修改了字符集。

**Comment by TLovers** [comment]
> 应该是构建配置的问题，已经很久没有复现了，在这期间我只是修改了字符集。

我这边还是会偶尔出现，太菜了 不清楚为什么

**Comment by XZYW** [comment]
> > 应该是构建配置的问题，已经很久没有复现了，在这期间我只是修改了字符集。
> 
> 我这边还是会偶尔出现，太菜了 不清楚为什么

我这边已经完全不会了

**Comment by lianggegege** [comment]
@TLovers 是使用的vite么，如果是的话可以改下esbuild中charset值为ascii；我的iconfont也偶尔会加载出问题

**Comment by Linhongbin-1111** [comment]
我这边也会出偶现此问题，主要是不好复现，很难定位

**Comment by TLovers** [comment]
> 我这边也会出偶现此问题，主要是不好复现，很难定位
主要是极低概率出现，这样就没办法找问题

**Comment by Linhongbin-1111** [comment]
你好，我是林鸿斌。我已收到你的来信，谢谢你~保持开心~ 不用回复！
