### ISSUE TITLE
TypeError: "convertLegacyToken" is not a function

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [vueComponent/ant-design-vue#6775]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
"@vue/cli-service": "~5.0.0","webpack": "^5.84.1",

### Reproduction link
[https://vuecomponent.github.io/issue-helper/暂无](https://vuecomponent.github.io/issue-helper/暂无)

### Steps to reproduce
const { theme } = require('ant-design-vue/lib');
const convertLegacyToken = require('ant-design-vue/lib/theme/convertLegacyToken');

const { defaultAlgorithm, defaultSeed } = theme;

const mapToken = defaultAlgorithm(defaultSeed);
const v3Token = convertLegacyToken(mapToken);

ERROR TypeError: convertLegacyToken is not a function

### What is expected?
正常构建

### What is actually happening?
安装最新版本组件库后，配置 less 变量时，出现 convertLegacyToken is not a function 错误

**Comment by XiaoDaiGua-Ray** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/51957438/c9957ccf-d03a-461c-a4b5-ee9211bfa94d)

**Comment by XiaoDaiGua-Ray** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/51957438/0395494a-aefe-478a-8836-63179e303f7f)

**Comment by LuoHong1993** [comment]
同问

**Comment by XiaoDaiGua-Ray** [comment]
> 同问

<img width="942" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/51957438/db084986-2e5c-413d-b78f-edf6513e9c60">
我后面是这么解决的该问题

**Comment by LuoHong1993** [comment]
> > 同问
> 
> <img alt="image" width="942" src="https://user-images.githubusercontent.com/51957438/255763790-db084986-2e5c-413d-b78f-edf6513e9c60.png"> 我后面是这么解决的该问题

感谢
