### ISSUE TITLE
InputNumber suffix support

### ISSUE THREAD

**Issue by Alkaidcc** [vueComponent/ant-design-vue#6777]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Sometimes, we need InputNumber component, but also need unit to describe the number, eg: m, $, %

### What does the proposed API look like?
suffix="$"

**Comment by nabaonan** [comment]
addon-after can do it 
```jsx
    <a-input-number v-model:value="value1" addon-before="+" addon-after="$"></a-input-number>
```

**Comment by Alkaidcc** [comment]
But I wanna still keep `input` suffix style

**Comment by nabaonan** [comment]
> But I wanna still keep `input` suffix style

I can't find `suffix` in react version too.    Maybe you can wrap a custom component to implement it

**Comment by Scxw010516** [comment]
i really need InputNumber suffix support

**Comment by Limoer96** [comment]
> > But I wanna still keep `input` suffix style
> 
> I can't find `suffix` in react version too. Maybe you can wrap a custom component to implement it
antd InputNumber has `suffix` props now.
