### ISSUE TITLE
使用编译后的组件，支持切换主题

### ISSUE THREAD

**Issue by SKT1yang** [vueComponent/ant-design-vue#6786]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用编译后的组件，比如推到npm的二次开发组件，无法切换主题，希望能够支持。
下面是我复现不支持的测试项目地址：https://github.com/SKT1yang/test

复现步骤：
1. 进入antv4-issue文件夹，npm install 安装依赖
2. npm run dev 打开页面
我的config-provider配置的是dark算法的主题，但是组件显示默认主题

### What does the proposed API look like?
编译后正常使用，正常切换主题（config-provider组件正常生效）

**Comment by aibayanyu20** [comment]
二次封装的组件打包要手动排除ant-design-vue，你的组件库和你的项目中存在两个不同的实例导致的问题，建议参考[rollup external](https://cn.rollupjs.org/configuration-options/#external)

**Comment by wangliqiang1026** [comment]
请问这个问题后面解决了吗？我这边打包排除了ant-design-vue也不行。

**Comment by wangliqiang1026** [comment]
> 二次封装的组件打包要手动排除ant-design-vue，你的组件库和你的项目中存在两个不同的实例导致的问题，建议参考[rollup external](https://cn.rollupjs.org/configuration-options/#external)

手动排除ant-design-vue任然无效，二次封装的组件库采用monorepo pnpm workspace ，编译用的vite，请问有具体的示例吗？
