### ISSUE TITLE
浏览器中的dayjs.locale('zh_cn');不生效

### ISSUE THREAD

**Issue by AExiaoliou** [vueComponent/ant-design-vue#6788]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
browser edge 114.0.1823.82 (正式版本) (64 位)

### Reproduction link
[https://stackblitz.com/edit/web-platform-rq1fzb?file=index.html](https://stackblitz.com/edit/web-platform-rq1fzb?file=index.html)

### Steps to reproduce
添加dayjs和antd的script标签并使用dayjs.locale('zh_cn');，不生效

### What is expected?
中文的月份和时间

### What is actually happening?
英文的月份和时间

**Comment by aibayanyu20** [comment]
#6767

**Comment by jingjingzhao** [comment]
> #6767

你给出的例子中，效果还是英文的啊。并没有汉化成功啊
https://stackblitz.com/edit/web-platform-rq1fzb?file=index.html
