### ISSUE TITLE
4.x版本的css样式在搜狗浏览器不会渲染

### ISSUE THREAD

**Issue by Cyan-963852** [vueComponent/ant-design-vue#6792]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
搜狗浏览器 11.0.1.34700

### Reproduction link
[https://antdv.com/](https://antdv.com/)

### Steps to reproduce
通过搜狗浏览器打开官网便可以看到

### What is expected?
样式正常

### What is actually happening?
样式崩坏

**Comment by aibayanyu20** [comment]
参考  https://antdv.com/docs/vue/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by zhujunel** [comment]
根据文档添加了style-provider，但是低版本的浏览器 notification 组件样式没有了

**Comment by aibayanyu20** [comment]
> 根据文档添加了style-provider，但是低版本的浏览器 notification 组件样式没有了

使用useNotification代替试一下
