### ISSUE TITLE
vite 中使用mapToken不生效

### ISSUE THREAD

**Issue by userchun** [vueComponent/ant-design-vue#6796]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
vite 4.4  antd-vue4.0

### What is actually happening?
import { theme } from 'ant-design-vue';

const { defaultAlgorithm, defaultSeed } = theme;
const mapToken=defaultAlgorithm(defaultSeed);

vite.config.ts
css: {
preprocessorOptions: {
less: {
modifyVars: {
...mapToken,
colorPrimary:red,
},
javascriptEnabled: true,
},
},
},
不生效

**Comment by userchun** [comment]
import { fileURLToPath, URL } from 'node:url';
import { defineConfig, loadEnv } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';
// import Components from 'unplugin-vue-components/vite';
// import { AntDesignVueResolver } from 'unplugin-vue-components/resolvers';
import AutoImport from 'unplugin-auto-import/vite';
import eslintPlugin from 'vite-plugin-eslint';
import legacy from '@vitejs/plugin-legacy';
// import {
//   createStyleImportPlugin,
//   AndDesignVueResolve,
// } from 'vite-plugin-style-import';
import { BeeThemes, BeeMapToken } from '@bilibili/bee-theme';
import { theme } from 'ant-design-vue';

const { defaultAlgorithm, defaultSeed } = theme;

const mapToken = defaultAlgorithm(defaultSeed);

mapToken.colorPrimary = '#00b96b';

export default defineConfig(async ({ command, mode }) => {
  const env = loadEnv(mode, process.cwd());
  return defineConfig({
    base: env.VITE_BASE_URL,
    build: {
      chunkSizeWarningLimit: 1000,
      rollupOptions: {
        output: {
          // manualChunks: getCacheGroups(),
          chunkFileNames: 'assets/js/[name]-[hash].js',
          entryFileNames: 'assets/js/[name]-[hash].js',
          assetFileNames: 'assets/[ext]/[name]-[hash].[ext]',
        },
      },
    },
    plugins: [
      vue(),
      vueJsx(),
      eslintPlugin(),
      svgLoader({
        svgoConfig: {
          plugins: [
            {
              name: 'preset-default',
              params: {
                overrides: {
                  cleanupIds: false, // id不转换，开启会导致多个mask的id变成同一个值
                  removeViewBox: false,
                },
              },
            },
          ],
        },
      }),

      AutoImport({
        imports: [
          'vue',
          'vue-router',
          'pinia',
          {
            dayjs: [['*', 'dayjs']],
            'lodash-es': [['*', '_']],
          },
        ],
        dts: 'src/auto-import.d.ts',
        eslintrc: {
          enabled: true,
          filepath: './.eslintrc-auto-import.json',
          globalsPropValue: true,
        },
      }),
      // createStyleImportPlugin({
      //   resolves: [AndDesignVueResolve()],
      // }),
      legacy({
        targets: ['defaults', 'not IE 11'],
      }),
    ],
    css: {
      preprocessorOptions: {
        less: {
          modifyVars: mapToken,
          javascriptEnabled: true,
        },
      },
    },

    server: {
      open: true,
      host: 'local.bilibili.co',
      port: 8080,
      proxy: {
        '/api': {
          target: 'http://uat-hr.bilibili.co/',
          changeOrigin: true,
        },
      },
    },
    resolve: {
      alias: {
        '@': fileURLToPath(new URL('./src', import.meta.url)),
      },
    },
    esbuild: {
      pure: ['console.log'],
    },
  });
});

**Comment by geng130127** [comment]
解决这个问题了吗
