### ISSUE TITLE
文档网站切换组件时丢失body元素

### ISSUE THREAD

**Issue by lai9fox** [vueComponent/ant-design-vue#6797]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Chrome: 版本 115.0.5790.114（正式版本） (arm64)，MacOS Ventura

### Reproduction link
[https://www.antdv.com/components/message-cn](https://www.antdv.com/components/message-cn)

### Steps to reproduce
1. 进入[https://www.antdv.com/components/message-cn](https://www.antdv.com/components/message-cn)，4.0 版本网站
2. 切换到 Message 组件下的 Modal 组件

### What is expected?
正确的显示 Modal 组件的文档内容

### What is actually happening?
无任何内容显示，控制台查看元素，body 元素丢失

**Comment by zjclxx** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/62633990/e7aea116-a1db-4b10-a75d-c999a190b9c7)
