### ISSUE TITLE
统计数值里的倒计时组件是否应该从初始值开始算，例如5秒倒计时，应该是5-4-3-2-1-结束，而不是4-3-2-1-0-结束。

### ISSUE THREAD

**Issue by createlinux** [vueComponent/ant-design-vue#6798]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
browser version

### Reproduction link
[https://antdv.com/components/statistic-cn#components-statistic-demo-countdown](https://antdv.com/components/statistic-cn#components-statistic-demo-countdown)

### Steps to reproduce
不需要重现，目前倒计时就是4-3-2-1-0-结束，比如初始值是5s，页面开始显示的是剩余4s。

### What is expected?
希望能从初始值开始倒计时，并且能秒数在变为0的时候就立即结束，而不是0到结束之间相隔1秒后结束。

### What is actually happening?
如标题所描述，生活中倒计时的时候，例如5秒倒计时就是从5开始算，目前组件是从4s开始算，0秒到结束之间还间隔了1秒。虽然加起来一共都是5秒钟，但是实际生活中使用的时候是从5开始，而不是4开始。

**Comment by webvs2** [comment]
倒计时的思想是剩余时间，在停留1的时候，事件尚未归零

**Comment by createlinux** [comment]
> 倒计时的思想是剩余时间，在停留1的时候，事件尚未归零

你说的没错，但是不应该反应到UI上。看看手机自带的计时器，到0就是结束了，而不是到0了还停留1s后结束。
