### ISSUE TITLE
table中使用input出现Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by gh-Nick** [vueComponent/ant-design-vue#6801]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### 示例代码
<`a-table :columns="columns" :data-source="columnDates" bordered size="small" :pagination="false"
:row-selection="rowSelection" :rowKey="(record,index)=>record.columnName"
:scroll="{x:'max-content',y:450 }">
<template #bodyCell="{ column,record , text,index }">
<`template v-if="column.dataIndex === 'columnName'">
<`a-form-item :name="['columns', index, 'columnName']" hasFeedback
:rules="{required: true,message: '字段不能为空',}">
<`a-input v-model:value="record.columnName" />

<`/a-form-item>
<`/template>

### 错误信息
ERROR
Cannot read properties of null (reading 'value')
TypeError: Cannot read properties of null (reading 'value')
at eval (webpack-internal:///./node_modules/ant-design-vue/es/input/Input.js:200:30)

**Comment by aibayanyu20** [comment]
不建议直接通过record的方式双向绑定，这不是一个正常的操作，建议使用原始数据操作`columnDates[index]. columnName`

**Comment by gh-Nick** [comment]
原始数据操作 columnDates[index]. columnName 双向绑定是依旧会出现该问题

**Comment by aibayanyu20** [comment]
能提供一个完整的复现demo么

**Comment by gh-Nick** [comment]
`<template>
  <div>
      <a-form ref="formRef" has-feedback :model="artisanTableVo"
              layout="horizontal" name="form_in_modal" :rules="rules">

        <a-tabs size="small" v-model:activeKey="activeKey" type="card" style="margin-top: 16px">
          <a-tab-pane key="1" tab="表1">

            <a-table :columns="columns" :data-source="artisanTableVo.columns" bordered size="small" :pagination="false"
                     :rowKey="(record,index)=>artisanTableVo.columns[index].columnName"
                     :scroll="{x:'max-content',y:450 }">
              <template #bodyCell="{ column,record , text,index }">
                <template v-if="column.dataIndex === 'columnName'">
                  <a-form-item :name="['columns', index, 'columnName']" hasFeedback
                               :rules="{required: true,message: '字段不能为空',}">
                    <a-input ref="columnName" v-model:value="artisanTableVo.columns[index].columnName"/>

                  </a-form-item>
                </template>
                <template v-if="column.dataIndex === 'columnComment'">
                  <a-form-item :name="['columns', index, 'columnComment']"
                               :rules="{required: true,message: '字段注释不能为空',}">
                    <a-input v-model:value="artisanTableVo.columns[index].columnComment"></a-input>
                  </a-form-item>
                </template>
                <template v-if="column.dataIndex === 'columnType'">
                  <a-form-item :name="['columns', index, 'columnType']"
                               :rules="{required: true,message: '字段类型不能为空',}">
                    <a-input v-model:value="artisanTableVo.columns[index].columnType"></a-input>
                  </a-form-item>
                </template>


              </template>
              <template #title>
                <a-button @click="addColumn">新增字段</a-button>
              </template>
            </a-table>
          </a-tab-pane>
          <a-tab-pane key="2" tab="表2">
          </a-tab-pane>
        </a-tabs>


      </a-form>
  </div>
</template>

<script>
import {ref, reactive, defineExpose, toRaw} from "vue";
import {Form} from 'ant-design-vue';

const useForm = Form.useForm;
const columns = [
  {
    title: '名称',
    dataIndex: 'columnName',
  },
  {
    title: '注释',
    dataIndex: 'columnComment',
  },
  {
    title: '类型',
    dataIndex: 'columnType',
  },


];
export default {
  name: "testForm",
  setup() {
    const recordEdit = ref(false)
    const activeKey = ref("1")
    const artisanTableVo = reactive({
      /**
       * 字段
       */
      columns: [],
      /**
       *
       */
      indexes: []
    })
    const rules = reactive({
      name: [{required: true, message: '名称不能为空'}],
      permission: [{required: true, message: '权限码不能为空'}],
    })
    const columnInfo = ref({
      columnName: '',
      columnComment: '',
      columnType: '',
    })
    const {
      resetFields,
      validate,
      validateInfos,
    } = useForm(artisanTableVo, rules);

    //===================方法===============================
    const edit = (record, edit) => {
      resetFields()
      recordEdit.value = edit
      Object.assign(artisanTableVo, record)
    }
    defineExpose({edit})

    const addColumn = () => {
      artisanTableVo.columns.push(JSON.parse(JSON.stringify(columnInfo.value)))
    }

    return {
      columns,
      artisanTableVo,
      rules,
      validateInfos, activeKey,
      //===================方法===============================
      edit, addColumn
    }
  },
}
</script>

<style scoped lang="less">


</style>`
这是一个代码示例

**Comment by gh-Nick** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/47767685/898c641e-73d2-4088-befd-d9b2e06c64bc)
出现问题时调试截图

**Comment by gh-Nick** [comment]
提供一个在线 代码： https://codesandbox.io/s/muddy-flower-gskcns?file=/src/App.vue

**Comment by Tangchen2016** [comment]
我也遇到了同样的问题，有解决嘛？

**Comment by gh-Nick** [comment]
解决了 我不知你的具体情况和我的是否一样     我这边是需要一个不可变的唯一key值

**Comment by coffee67** [comment]
> 解决了 我不知你的具体情况和我的是否一样 我这边是需要一个不可变的唯一key值

能贴下具体代码吗？我这边也遇到这问题，不知道key放哪里

**Comment by gh-Nick** [comment]
就是 将table的rowKey设置一个唯一不可变的值

**Comment by gh-Nick** [comment]
> > 解决了 我不知你的具体情况和我的是否一样 我这边是需要一个不可变的唯一key值
> 
> 能贴下具体代码吗？我这边也遇到这问题，不知道key放哪里

给table的rowKey设置一个唯一且不变的的值
