### ISSUE TITLE
Button type 'primary' color style is overired by transparent color

### ISSUE THREAD

**Issue by anhlhpl52119** [vueComponent/ant-design-vue#6803]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
MacOS: **Ventura 13.4,** 
Chrome: **115.0.5790.114 (arm64),** 
Vue: **v3.3.4**

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
  Install Antdv following: https://next.antdv.com/docs/vue/getting-started
  Create file.vue
`  import {Button} from 'ant-design-vue';`
use button component as:

```
<Button type="primary">
   Primary Button
</Button>
```

### What is expected?
Button display as normal primary button as example : https://antdv.com/components/button

### What is actually happening?
Primary button style is display as 'transparent' color, not 'primary color' as default

---
I inspected the DOM and findout the style of '.ant-btn-primary' is overied by 'button, [type='button'], [type='reset'], [type='submit']'

![image](https://github.com/vueComponent/ant-design-vue/assets/46667887/9b086eb1-0624-4d42-8fe3-8e117588412f)
![image](https://github.com/vueComponent/ant-design-vue/assets/46667887/3173ef07-927d-4b5c-a2dc-1904019410e6)

**Comment by withoutmeat** [comment]
same problem

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/0ba9ec55-cafc-4efd-b5fd-0167dc344f2b)
i think it's fine now.

**Comment by aibayanyu20** [comment]
Did you use the reset style of the lib ?

**Comment by Azdoit** [comment]
是不是使用了tailwindcss ，默认情况会有tailwindcss的默认属性导致添加了bcground-color:transparent的样式。可以在tailwind的配置文件里添加corePlugins对象，并设置preflight为false

**Comment by kovsu** [comment]
When I use unocss, I encountered the same problem because I imported `import "@unocss/reset/tailwind.css";`. Everything went back to normal after commenting out this file. I think the issue here might also be because you imported other styles.

**Comment by liuyuanjun** [comment]
> 是不是使用了tailwindcss ，默认情况会有tailwindcss的默认属性导致添加了bcground-color:transparent的样式。可以在tailwind的配置文件里添加corePlugins对象，并设置preflight为false

新手请问如何配置，用的unocss，没有tailwind.config.ts ，只有 uno.config.ts

**Comment by kovsu** [comment]
@liuyuanjun 看看我 ⬆️ 面说的那段话

**Comment by MySecret** [comment]
我也遇到这个问题了，引入了‘import '@unocss/reset/tailwind.css'就会有问题，能解决吗

**Comment by aibayanyu20** [comment]
> 我也遇到这个问题了，引入了‘import '@unocss/reset/tailwind.css'就会有问题，能解决吗

引用antd自带的reset.css
