### ISSUE TITLE
Tabs animated property bug

### ISSUE THREAD

**Issue by alekseyburn** [vueComponent/ant-design-vue#6804]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
macos last stable, chrome last stable, vue last stable

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-4-0-0-forked-yx5zh4?file=/src/demo.vue)

### Steps to reproduce
just add 'animated' to tabs component

### What is expected?
animation works

### What is actually happening?
animation doesn't work. Added margin: -100% to tabs content.

**Comment by lfzs** [comment]
+1
