### ISSUE TITLE
Use `message` component with contextHolder results in routing blank pages

### ISSUE THREAD

**Issue by yameizi001** [vueComponent/ant-design-vue#6807]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
os: Windows11; browser: Edge 115.0.1901.188; Vue: 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hooks-diao-yong-tui-jian-ant-design-vue-4-0-0-forked-sq8kqc?file=/src/router/index.ts)

### Steps to reproduce
1. create vue project, use command: `npm init vue@latest`, choose ts,jsx,router,pinia,es support
2. init project, use command: `npm install`
3. add antd for vue, use command: `npm i --save ant-design-vue@4.0.0`
4. switch to AboutView.vue, add <a-button> and write code like official document(Hooks)
5. open browser, switch to About view, click button, pop-up prompt successfully
6. click Home route button to switch to Home view

### What is expected?
after step6, should switch to Home view

### What is actually happening?
blank view after step6

**Comment by anrananran** [comment]
same issue

**Comment by adampolyanskiy** [comment]
@yameizi001 Was you able to fix it?

**Comment by adampolyanskiy** [comment]
> @yameizi001 Was you able to fix it?

Ok, I saw it was fixed in the release. Thanks @tangjinzhou
