### ISSUE TITLE
使用theme.darkAlgorithm和transition会导致Ant Design Vue组件样式丢失

### ISSUE THREAD

**Issue by qiaoabcd** [vueComponent/ant-design-vue#6811]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-beta.3

### Environment
vue3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-wave-wcjfz7?file=/src/App.vue:150-160)

### Steps to reproduce
点击change按钮，Demo组件离开动画执行时 Ant Design Vue 组件的样式丢失了

### What is expected?
离开动画执行时， Ant Design Vue 组件样式正常显示

### What is actually happening?
离开动画执行时， Ant Design Vue 组件样式丢失了

**Comment by selicens** [comment]
确实，插个眼

**Comment by selicens** [comment]
transition-delay: 0.1s;改短点让别人看不到过程就行了哈哈哈哈

**Comment by qiaoabcd** [comment]
改了主题颜色也会丢失样式...

**Comment by gokhantaskan** [comment]
I'm having issues with using Nuxt 3 for page and layout transitions with a duration. Unfortunately, everything is currently broken due to this bug. As a result, I need to find an alternative to the Antd components.

**Comment by aibayanyu20** [comment]
> I'm having issues with using Nuxt 3 for page and layout transitions with a duration. Unfortunately, everything is currently broken due to this bug. As a result, I need to find an alternative to the Antd components.

We already have a corresponding solution, waiting for the release

**Comment by aibayanyu20** [comment]
> > > I'm having issues with using Nuxt 3 for page and layout transitions with a duration. Unfortunately, everything is currently broken due to this bug. As a result, I need to find an alternative to the Antd components.
> > 
> > 
> > We already have a corresponding solution, waiting for the release
> 
> The last release (4.0.1 - yesterday) didn't solve the issue. When do you plan to merge the solution?

take a look here https://github.com/vueComponent/ant-design-vue-nuxt/issues/15
