### ISSUE TITLE
<a-modal v-model:open="open"> should be <a-modal v-model:visible="open">

### ISSUE THREAD

**Issue by rok138** [vueComponent/ant-design-vue#6815]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
3.2.20 or 4.x

### Reproduction link
[http://xxx](http://xxx)

### Steps to reproduce
<a-modal v-model:open="open">

### What is expected?
expect to open the modal

### What is actually happening?
cannot open the modal

**Comment by selicens** [comment]
可以关注下官网中3.x升4.x的变化，升级组件弹框的受控可见 API 统一为 `open1，`visible` 等类似 API 都会被替换。
- Drawer 组件 `visible` 变为 `open`。
- Modal 组件 `visible` 变为 `open`。
- Dropdown 组件 `visible` 变为 `open`。
- Tooltip 组件 `visible` 变为 `open`。
- Tag 组件 `visible` 已移除。
- Slider 组件 `tooltip` 相关 API 收敛到 `tooltip` 属性中。
- Table 组件 `filterDropdownVisible` 变为 `filterDropdownOpen`。

**Comment by selicens** [comment]
组件弹框的受控可见 API 统一为 open，visible 等类似 API 都会被替换。

Drawer 组件 visible 变为 open。
Modal 组件 visible 变为 open。
Dropdown 组件 visible 变为 open。
Tooltip 组件 visible 变为 open。
Tag 组件 visible 已移除。
Slider 组件 tooltip 相关 API 收敛到 tooltip 属性中。
Table 组件 filterDropdownVisible 变为 filterDropdownOpen。

可以关注下官网中3.x升级到4.x的变化[https://www.antdv.com/docs/vue/migration-v4-cn](https://www.antdv.com/docs/vue/migration-v4-cn)
