### ISSUE TITLE
Form createFormField is not defined in d.ts file

### ISSUE THREAD

**Issue by silverlovesl** [vueComponent/ant-design-vue#682]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
ant-design-vue 1.3.8

### Reproduction link
[https://vue.ant.design/components/form-cn/](https://vue.ant.design/components/form-cn/)

### Steps to reproduce
this.$form.createFormField

### What is expected?
add type definition

### What is actually happening?
compile error

**Comment by silverlovesl** [comment]
就是少了这个方法 createFormField 的定义，typescript中会报错，希望添加
感谢作者的辛苦贡献

**Comment by tangjinzhou** [comment]
@silverlovesl 来个PR？

**Comment by silverlovesl** [comment]
提交PR了，谢谢

**Comment by callmesoul** [comment]
合并了么？
