### ISSUE TITLE
使用 <a-textarea> 控件时报 Cannot redefine property: currentTarget 错误

### ISSUE THREAD

**Issue by EiuaLee** [vueComponent/ant-design-vue#6830]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Vue3.3.4      Chrome 版本 115.0.5790.114（正式版本） (x86_64)

### Reproduction link
[https://next.antdv.com/components/input-cn/#Input](https://next.antdv.com/components/input-cn/#Input)

### Steps to reproduce
1、官网 https://next.antdv.com/components/input-cn/#Input
2、在给出的示例上输入内容

### What is expected?
/

### What is actually happening?
<img width="816" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/32054362/f67730e0-a852-4d3c-a4bb-a1eda3a37b79">

**Comment by cc-hearts** [comment]
There's no reproduction here.

**Comment by goodsosbva** [comment]
How do I resolve this error?

**Comment by cc-hearts** [comment]
need reproduction 🤔

**Comment by ureshinoSayumi** [comment]
https://www.antdv.com/components/input#components-input-demo-allow-clear

This issue can be reproduced using the example from the official documentation. I don't understand how this problem has persisted until now

**Comment by hualuozhijiandexuanlv** [comment]
怎么解决呢？

**Comment by mipawn** [comment]
从 23 年持续到现在一直有这个 bug，且直接在官网的文档上就能看到，，好像一直没人去修复

**Comment by FrankWang117** [comment]
> 从 23 年持续到现在一直有这个 bug，且直接在官网的文档上就能看到，，好像一直没人去修复

Same error.
