### ISSUE TITLE
antd CSP问题

### ISSUE THREAD

**Issue by China-jinannan** [vueComponent/ant-design-vue#6831]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
操作系统版本：win10；浏览器版本：Edge；Vue版本：3.3.4.

### Reproduction link
[https://3x.antdv.com/components/config-provider-cn#api](https://3x.antdv.com/components/config-provider-cn#api)

### Steps to reproduce
Webconfig文件增加CSP策略：<add name="Content-Security-Policy" value="img-src 'self'; script-src 'self'; style-src 'self' https://*.cn/;"/>
发布之后：控制台输出style-src报错，文件为：https://*/assets/@ant-design-0f2d764f.js
异常为：Refused to apply inline style because it violates the following Content Security Policy directive: "style-src  'self' https://*.cn/ ". Either the 'unsafe-inline' keyword, a hash ('sha256-47DEQpj8HBSa /TImW 5JCeuQeRkm5NMpJWZG3hSuFU='), or a nonce ('nonce-...') is required to enable inline execution.

### What is expected?
期待解决这个异常

### What is actually happening?
我理解是增加CSP的Style限制之后，antd有内联样式，但是我不知道如何设置解决这个问题，因为我的antd是全局配置

**Comment by EiuaLee** [comment]
<meta charset="utf-8" http-equiv="content-security-policy" content="script-src 'self' 'unsafe-eval' chrome-extension-resource; object-src 'none'; style-src 'self' 'unsafe-inline'; ">

**Comment by China-jinannan** [comment]
@EiuaLee 就是不想使用内联样式，禁用unsafe inline
