### ISSUE TITLE
跑马灯组件,开发环境正常,获取到的ref是个数组,打包后就不行了,获取不到ref,都是undefined

### ISSUE THREAD

**Issue by tckxjzc** [vueComponent/ant-design-vue#6833]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.5

### Environment
mac 12,chrome 113, vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-worker-5n2vp8?file=/src/App.vue)

### Steps to reproduce
打开页面f12,看出输出的ref

### What is expected?
开发环境和打包后一致

### What is actually happening?
undefined

**Comment by zjclxx** [comment]
一种方法就是ref为数组去遍历
[另一种方法使用vueuse的usetemplaterefslist，链接：](https://vueuse.org/core/useTemplateRefsList/#usetemplaterefslist)
