### ISSUE TITLE
官网黑夜模式下，主题切换失效

### ISSUE THREAD

**Issue by fengfengzhidao** [vueComponent/ant-design-vue#6834]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
普通浏览器

### Reproduction link
[https://3x.antdv.com/components/config-provider/#components-config-provider-demo-theme](https://3x.antdv.com/components/config-provider/#components-config-provider-demo-theme)

### Steps to reproduce
官网的暗黑模式下，修改主题无效

### What is expected?
在暗黑模式下，修改主题可以生效

### What is actually happening?
白天模式下，修改主题色
![](http://image.fengfengzhidao.com/pic/20230810234740.png)
黑夜模式下，修改主题色
![](http://image.fengfengzhidao.com/pic/20230810234815.png)

---
主要是黑夜模式下，颜色色值是写死的，没有使用变量

![](http://image.fengfengzhidao.com/pic/20230810234920.png)

白天的

![](http://image.fengfengzhidao.com/pic/20230810234945.png)

**Comment by fengfengzhidao** [comment]
我有点不太明白，3的文档上只说了用黑夜模式，没有说怎么黑夜白天切换，我倒是直接用官网的那个css文件实现了动态主题切换，但是黑夜模式下动态更改主题还是不太行
4的文档就更迷了，黑夜模式完全没有提，是这个需求现在不重要了吗，我感觉主题切换很常用呀

**Comment by fengfengzhidao** [comment]
> 

不是主题切换，是黑夜和白天模式

**Comment by xingyuv** [comment]
> 

暗黑模式和普通模式切换，改变这个就行了
theme.defaultAlgorithm  theme.darkAlgorithm

**Comment by zhanglijie5997** [comment]
4.x做的真的是一坨屎💩

**Comment by xiaozhu2024** [comment]
> 4.x做的真的是一坨屎💩

那你赶紧写一版vue的啊，开源的就是被你这样的人搞臭的，自己写不出来还在这瞎bb

**Comment by like0413** [comment]
> > 
> 
> 暗黑模式和普通模式切换，改变这个就行了 theme.defaultAlgorithm theme.darkAlgorithm

正解，不过文档说的确实不太明了
