### ISSUE TITLE
Image 组件设置height时，约束不了图片的高度

### ISSUE THREAD

**Issue by EiuaLee** [vueComponent/ant-design-vue#6836]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
Vue3.3.4   Chrome 版本 115.0.5790.170（正式版本） (x86_64)

### Reproduction link
[https://next.antdv.com/components/image-cn](https://next.antdv.com/components/image-cn)

### Steps to reproduce
直接设置 height属性即可复现

### What is expected?
正确设置height

### What is actually happening?
Image 组件设置height时，约束不了图片的高度

![image](https://github.com/vueComponent/ant-design-vue/assets/32054362/4773e639-645f-49db-b174-f086e30e519b)

**Comment by CCherry07** [comment]
ok. 了解
