### ISSUE TITLE
如果当前页面中，使用message组件是通过useMessage的方式，会导致跳转到其他页面的路由时，页面变成空白

### ISSUE THREAD

**Issue by anrananran** [vueComponent/ant-design-vue#6837]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0

### Environment
windows11, Edge115.0.1901.200，Vue3.3.4

### Reproduction link
[https://www.antdv.com/components/message-cn](https://www.antdv.com/components/message-cn)

### Steps to reproduce
1.直接访问官网message组件文档，https://www.antdv.com/components/message-cn
2.随便点击左侧任意组件链接

### What is expected?
页面正常渲染

### What is actually happening?
页面变成空白，查看DOM结构，body标签消失

**Comment by anrananran** [comment]
经过排查，BUG跟contextHolder有关系

**Comment by EchoNoReturn** [comment]
+1，系统和使用的组件版本一样，我在 Chrome 浏览器中也是有同样的问题存在，版本 115.0.5790.173（正式版本）（64 位）。
