### ISSUE TITLE
嵌套a-form-item后，required: true前面的红色*为什么没有了？

### ISSUE THREAD

**Issue by missy0u** [vueComponent/ant-design-vue#684]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Win7、Chrome 73.0.3683.103、 Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/y3k04njx7z)

### Steps to reproduce
参考CodeSandbox
![image](https://user-images.githubusercontent.com/3926664/55859106-ed448b80-5ba3-11e9-924d-e0f579a076c3.png)

### What is expected?
嵌套a-form-item后也出现红色*

### What is actually happening?
嵌套a-form-item后，required: true前面的红色*没有了

**Comment by xunmi1** [comment]
应该是外层 AFormItem 没有收集到自己卡槽内的组件的值和验证规则，建议将里面的组件（ASelect + AInput）封装成一个组件，提供名为 value 的 prop 和 $emit('change') 事件（也可以是其他名字，不过需要设置  AFormItem -> decorator 指令 ->valuePropName && trigger）,这样 decorator 就能收集相关信息

**Comment by sendya** [comment]
这种类似用法推荐这样使用 https://codesandbox.io/s/910q3039yw

**Comment by missy0u** [comment]
![image](https://user-images.githubusercontent.com/3926664/56116160-bbfaff80-5f97-11e9-8ed2-ca68d9d1df3a.png)

发现官方有相关说明，推荐 @sendya 的用法！
