### ISSUE TITLE
vue3.0的jsx中表单组件的v-modal不能正常使用

### ISSUE THREAD

**Issue by mizhicangyue** [vueComponent/ant-design-vue#6844]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
macOS ventura | chrome：115.0.5790.170（正式版本） (arm64) | antdv:4.0.0

### Reproduction link
[https://www.antdv.com/components/input-cn](https://www.antdv.com/components/input-cn)

### Steps to reproduce
1.写一个在jsx中用Input的demo
2.代码如下
import {defineComponent, ref} from "vue";
import {Button, Input,} from "ant-design-vue";
export default defineComponent({
setup(props) {
const value = ref('hello')

return () => {
return <div>
<Input v-model:value={value}  />
<Button onClick={()=>{
console.log(value.value)
}}>提交</Button>
</div>
}
}
})

### What is expected?
能够正常的完成v-modal双向数据绑定

### What is actually happening?
点击按钮去展示值的时候报错
runtime-core.esm-bundler.js:221 Uncaught TypeError: Assignment to constant variable.
at onUpdate:value (issue.jsx:16:43)
at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
at emit (runtime-core.esm-bundler.js:664:5)
at runtime-core.esm-bundler.js:7422:45
at triggerChange (Input.js:113:7)
at callWithErrorHandling (runtime-core.esm-bundler.js:158:18)
at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:17)
at emit (runtime-core.esm-bundler.js:664:5)
at runtime-core.esm-bundler.js:7422:45

<img width="1072" alt="截屏2023-08-13 17 55 10" src="https://github.com/vueComponent/ant-design-vue/assets/45323549/0dae82fa-8d9a-4139-bf3a-da17b5c8d741">

**Comment by selicens** [comment]
`<Input value={value.value} />
<Button onClick={() => (value.value++)}>click</Button>
`

**Comment by selicens** [comment]
`<Input value={value.value} />
<Button onClick={() => (value.value = '嘿嘿')}>click</Button>
`

**Comment by mizhicangyue** [comment]
> `<Input value={value.value} /> <Button onClick={() => (value.value = '嘿嘿')}>click</Button> `

主要是要实现双向数据绑定，Input输入框内容在用户输入时发生改变，绑定的ref能一起改变，这样写的话，input就没法键入了

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/5c0c215b-e9f4-45df-a8db-ec57d046d0b8)

https://github.com/vuejs/babel-plugin-jsx
