### ISSUE TITLE
Input 组件文档中，“前缀和后缀”的例子，在注释掉 prefix 图标时，输入一个字符后，input输入框就失去焦点，无法继续输入

### ISSUE THREAD

**Issue by angela-1** [vueComponent/ant-design-vue#685]
- [ X ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
文档中的 “在线演示” codesandbox 环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ol43wm0lx6)

### Steps to reproduce
复制 “前缀和后缀”的例子到 codesandbox 环境，注释掉 prefix 图标，点击输入框，输入一个字符后，输入框失去焦点，无法继续输入。
若不注释 prefix 图标，输入框可以正常连续输入。

### What is expected?
在不需要使用 prefix 图标时，可以正常连续输入

### What is actually happening?
不加入prefixx 图标时，输入框输入一个字符后失去焦点，无法继续输入。再次点击输入框才可以继续输入。

**Comment by tangjinzhou** [comment]
可以参考 react版本的解决方案 https://ant.design/components/input-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-prefix/suffix-%E6%97%B6%EF%BC%8CInput-%E4%BC%9A%E5%A4%B1%E5%8E%BB%E7%84%A6%E7%82%B9%EF%BC%9F

**Comment by FAKER-A** [comment]
@angela-1  https://codesandbox.io/s/mjnvzolnpj  弄了一下例子

**Comment by angela-1** [comment]
@FAKER-A 谢谢，按你的链接里改了一下，可以连续输入不失焦了。
