### ISSUE TITLE
calendar的dateCellRender在使用普通slot时不会重新render

### ISSUE THREAD

**Issue by woshiguabi** [vueComponent/ant-design-vue#6851]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
Vue 2.7.14

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-cloud-7hpwgl?file=/src/App.vue)

### Steps to reproduce
点击change按钮，可以看到`a-calendar`的`dateCellRender`在使用普通slot时不会重新render，如果使用scopedSlot则正常

### What is expected?
正确render

### What is actually happening?
组件data发生变化后，slot中的内容没有重新render

**Comment by zjclxx** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/62633990/80cd5c34-42fe-436b-9a20-4aa6fee5f93f)
