### ISSUE TITLE
a-popover 组件不支持nuxt ssr

### ISSUE THREAD

**Issue by sbigtree** [vueComponent/ant-design-vue#6856]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
anu-design: 4.0.0, nuxt:3.x

### Reproduction link
新建最小项目可复现

### Steps to reproduce
新建nuxt项目
pages/about.vue 路由下直接引用 a-popover

### What is expected?
document is not defined

### What is actually happening?
不支持ssr

![image](https://github.com/vueComponent/ant-design-vue/assets/48344438/38fe28b0-4d73-43f9-9116-8060748a134e)

**Comment by aibayanyu20** [comment]
fork this [demo](https://stackblitz.com/edit/nuxt-starter-eabm9p?file=app.vue) provide a online reproduction
