### ISSUE TITLE
a-input-group组件下button组件填加size导致样式失效

### ISSUE THREAD

**Issue by T-Inphic** [vueComponent/ant-design-vue#6859]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
anu-design: 4.0.0, chrome：115.0.5790.170，vue3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lcynzv?file=/src/demo.vue)

### Steps to reproduce
直接打开官网示例链接（input 输入框 - 输入框组合），在组件a-button上填加size="large"复现

### What is expected?
样式正常

### What is actually happening?
样式没添加上

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/b33e7ab5-24ef-4743-8f29-692dbb458800)

> 没有发现你说的问题

**Comment by T-Inphic** [comment]
> 
你看下button左侧的圆角是不是应该变成直角

**Comment by kovsu** [comment]
emm，怎么说呢，就算它左侧是直角。它也不和左侧高度一样啊

**Comment by T-Inphic** [comment]
> ![image](https://user-images.githubusercontent.com/82451257/261226134-b33e7ab5-24ef-4743-8f29-692dbb458800.png)
> 
> > 没有发现你说的问题

<img width="485" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/19276771/9ffa9dd0-14f1-4f38-8309-1f5df19bf14e">
默认情况是按钮左侧是直角

**Comment by T-Inphic** [comment]
> emm，怎么说呢，就算它左侧是直角。它也不和左侧高度一样啊

你可以吧input也设置成size为large

**Comment by T-Inphic** [comment]
> > ![image](https://user-images.githubusercontent.com/82451257/261226134-b33e7ab5-24ef-4743-8f29-692dbb458800.png)
> > > 没有发现你说的问题
> 
> <img alt="image" width="485" src="https://user-images.githubusercontent.com/19276771/261892155-9ffa9dd0-14f1-4f38-8309-1f5df19bf14e.png"> 默认情况是按钮左侧是直角

<img width="1414" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/19276771/43bc98dc-bebd-48d0-8323-630eb4342928">

**Comment by kovsu** [comment]
```ts
  <a-input-group compact size="large">
    <a-input v-model:value="value19" style="width: calc(100% - 200px)" />
    <a-button type="primary">Submit</a-button>
  </a-input-group>
```
正常使用应该是给 a-input-group 添加 size 属性

**Comment by kovsu** [comment]
但是给这里添加之后确实有点问题要修

**Comment by kovsu** [comment]
https://codesandbox.io/s/input-group-ant-design-vue-4-0-0-forked-f55ms8?file=/src/demo.vue

**Comment by T-Inphic** [comment]
> ```ts
>   <a-input-group compact size="large">
>     <a-input v-model:value="value19" style="width: calc(100% - 200px)" />
>     <a-button type="primary">Submit</a-button>
>   </a-input-group>
> ```
> 
> 正常使用应该是给 a-input-group 添加 size 属性

对啊，但是这样现实也不正常
<img width="1401" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/19276771/1dcb210c-6ab3-4e60-be90-3fa34bbc0205">

**Comment by kovsu** [comment]
这个我去修一下。我觉得你都用 a-input-group 就应该去单独操作这个 a-input-group，而不是去操作里面的。要是这样你还不如自己写一个组件调调样式。

**Comment by T-Inphic** [comment]
> 这个我去修一下。我觉得你都用 a-input-group 就应该去单独操作这个 a-input-group，而不是去操作里面的。要是这样你还不如自己写一个组件调调样式。

好的，之前就是在外面写的，发现有问题，换成里面了
