### ISSUE TITLE
配置全局getPopupContainer之后 在a-menu-item中嵌套a-popconfirm气泡弹出框，tips位置异常问题

### ISSUE THREAD

**Issue by OMY-onlymissyou** [vueComponent/ant-design-vue#6862]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.3

### Environment
vue版本

### Reproduction link
[https://1x.antdv.com/docs/vue/i18n-cn/](https://1x.antdv.com/docs/vue/i18n-cn/)

### Steps to reproduce
全局配置 getPopupContainer  之后   使用 a-menu-item 嵌套气泡弹框，气泡弹框  tips显示位置异常

![image](https://github.com/vueComponent/ant-design-vue/assets/58871216/91ad3a60-a454-4a85-833f-481c3fc15ef2)
![image](https://github.com/vueComponent/ant-design-vue/assets/58871216/bd549613-35ce-4b8e-86cc-74dcc147fa25)
![image](https://github.com/vueComponent/ant-design-vue/assets/58871216/9025052a-36f1-4f3a-95b0-b2d25a23981c)
![image](https://github.com/vueComponent/ant-design-vue/assets/58871216/c137f6cb-6cd1-4210-9677-3fb11a0f90d9)

### What is expected?
解决位置异常问题

### What is actually happening?
气泡弹框位置异常

**Comment by tangjinzhou** [comment]
1.x 不在维护，请升级 3.x 4.x 版本
