### ISSUE TITLE
menu组件items参数使用computed计算属性且label参数值为VNode时出现很多错误

### ISSUE THREAD

**Issue by catpigdog** [vueComponent/ant-design-vue#6864]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
vue3

### Reproduction link
[https://github.com/catpigdog/bug-antdforvue-menu](https://github.com/catpigdog/bug-antdforvue-menu)

### Steps to reproduce
使用Menu时 items参数传入一个computed返回值ItemType，且ItemType的label属性值为VNode时
menu会出现样式错乱，openKeys selectedKeys 参数没作用， inline-collapsed 参数改变时报错

### What is expected?
正确渲染

### What is actually happening?
报错 渲染错乱

---
ItemType['label'] VueNode 能改为 VueNode | ()=>VueNode 就很棒

**Comment by kovsu** [comment]
@catpigdog openKeys selectedKeys 参数没作用，是因为你没有给 key 值吧，看了一眼你仓库。其他地方你要不再仔细描述一下？[😛]

**Comment by catpigdog** [comment]
> @catpigdogopenKeys selectedKeys 参数没作用，是因为你没有给 key 值吧，赶紧查看一下你的仓库。其他地方你要不再仔细描述一下吗？[😛]
抱歉，key字段写成了name字段，仓库代码已更新。但是这个问题依然是存在的

**Comment by kovsu** [comment]
目前解决你的问题是设置 icon 属性，label 属性那里设置的 VueNode 话就会出现你那个问题（需要去修复一下）。
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/7ed2d388-aaa0-437a-bc97-cb2300e0a323)``
```ts
{
    key: 'key1',
    title: 'test1',
    icon: () => createVNode(HomeFilled),
    label: 'test1',
    children: [
      {
        key: 'key1-1',
        title: 'test1-1',
        icon: () => createVNode(HomeFilled),
        label: "test1-1",
      },
    ],
  },
```

**Comment by catpigdog** [comment]
icon和我这个问题无关，主要是由label传入Vnode后，且由vue computed计算属性返回就会出现布局错乱问题：
以下是传入items内容后更新inlineCollapsed参数或者点击该菜单(setting:1') 就会出现布局错乱，在该菜单位置多生成一个menu
```typescript
const items = computed(() => [
  {
    key: 'sub1',
    icon: () => h(SettingOutlined),
    label: 'Navigation Three - Submenu',
    title: 'Navigation Three - Submenu',
    children: [
      {
        type: 'group',
        label: 'Item 1',
        children: [
          {
            label: h(AppstoreOutlined),
            title: 'setting:1',
            key: 'setting:1',
          },
          {
            label: 'Option 2',
            key: 'setting:2',
          },
        ],
      }
    ],
  }
]);
``` 
[https://github.com/catpigdog/bug-antdforvue-menu/blob/main/bug.gif](url)

**Comment by catpigdog** [comment]
@kovsu 可以请教你点技术问题吗？可以的话发个邮件给我 1123603312@qq.com 我回复你

**Comment by greenhat616** [comment]
好像确实有这个问题

**Comment by greenhat616** [comment]
Not stale

**Comment by greenhat616** [comment]
not stale

**Comment by greenhat616** [comment]
not stale

**Comment by greenhat616** [comment]
not stale
