### ISSUE TITLE
afterVisibleChange event is not called in Drawer when nullish value is passed to getContainer prop

### ISSUE THREAD

**Issue by karachungen** [vueComponent/ant-design-vue#6869]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
Chrome Version 115.0.5790.170, Vue 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/aftervisiblechange-is-not-called-in-drawer-smz348)

### Steps to reproduce
1. Open codesandbox link
2. Click on Open button to open drawer

### What is expected?
'**visible**' with value 'true' is appearing in dev console

### What is actually happening?
**afterVisibleChange** is not called, **ADrawer** doesn't emit **afterVisibleChange** event.

**Comment by tangjinzhou** [comment]
This is the expected behavior. Active changes will not trigger change, and there is no need to trigger it. Just like input, you can watch visible
