### ISSUE TITLE
message在全屏样式下，完全失效，展示不出来

### ISSUE THREAD

**Issue by mizhicangyue** [vueComponent/ant-design-vue#6877]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
mac chrome最新

### Reproduction link
[https://www.antdv.com/components/message-cn](https://www.antdv.com/components/message-cn)

### Steps to reproduce
1.按需引入message
2.使用
3.展示不出来，但是dom节点好像是加载了

### What is expected?
希望能展示出来message

### What is actually happening?
message弹窗弹不出来，但是notification和modal都能成功使用

**Comment by sydmifan** [comment]
我也遇到同样的问题，请问你知道怎么解决了没有

**Comment by EiuaLee** [comment]
+1

**Comment by sydmifan** [comment]
下载这个Unocss插件可以解决，或者更新最新版本4.0.1

**Comment by mizhicangyue** [comment]
> 4.0.1

这个具体是啥原因导致的呢？之前我以为是zindex层级不够，遮住了，后面发现content都没有插入进去

**Comment by EiuaLee** [comment]
更新了也不行，虽然body里面content添加了进去了，但死活不弹出来

> 下载这个Unocss插件可以解决，或者更新最新版本4.0.1

**Comment by mizhicangyue** [comment]
> 更新了的确可以了，就是样式漏了left:0； ![image](https://user-images.githubusercontent.com/32054362/262330150-19916c6c-1c10-49be-aabf-2b603c10fb0e.png)
> 
> > 下载这个Unocss插件可以解决，或者更新最新版本4.0.1

这就尴尬了。也许4.0.2会处理？
