### ISSUE TITLE
table表格使用sticky属性后，出现底部滚轴不自动吸顶，或者滚动到底部出现两个横向滚轴的情况

### ISSUE THREAD

**Issue by LOU-4599** [vueComponent/ant-design-vue#6881]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
mac book pro  M2pro 13.4.1 、chrome 114.0.5735.198（正式版本）(arm64)、vue: "^3.2.45"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-cookies-hr9kl7?file=/src/components/demo.vue)

### Steps to reproduce
如果直接点击链接无法进入，请复制从浏览器地址栏打开
1、demo默认每页是4条数据，当从4条切换到20条时，再将table滚动到底部会出现两个滚轴。
2、当出现两个滚轴时，点击下面的滚轴，并拖拽，上方滚轴会消失，并且再向上滚动界面时，底部吸附滚轴不会再出现。
3、当从每页4条切换到10条时，底部吸附滚轴没有出现。

### What is expected?
期望结果解决以上三个问题

### What is actually happening?
实际结果为重现步骤内容

---
后来排查了一下这块，原因应该在于我在父组件上增加了固定高度并且添加了 overflow: auto; 样式。

**Comment by LOU-4599** [comment]
**补充一下问题图片：**
出现两个滚轴的情况
![image](https://github.com/vueComponent/ant-design-vue/assets/55049400/fcbd8131-a4dd-46ec-b5c3-82038f4db2b3)
滚轴不吸附底部的情况
![image](https://github.com/vueComponent/ant-design-vue/assets/55049400/cff1da05-1887-47cd-ae49-b82348d99509)

**Comment by kovsu** [comment]
所以问题是已经解决了吗

**Comment by LOU-4599** [comment]
没有解决，比如在封装后台管理框架的时候，可视区域不可以避免的需要给固定高度，让其超出滚动。这种情况下一但视图中使用了，table组件就会出现这个问题。

**Comment by kovsu** [comment]
你要给固定宽度的话，应该这样使用
```ts
:scroll="{ x: 1500, y: 500 }"
```
你的例子里只给了 x，我觉得给一个 y 为 500 应该就可以解决你的问题了。.box 这个样式也不需要了

**Comment by LOU-4599** [comment]
> @LOU-4599 你要给固定宽度和高度的话，应该这样使用
> 
> ```ts
> :scroll="{ x: 1500, y: 500 }"
> ```
> 
> 你的例子里只给了 x，我觉得给一个 y 为 500 应该就可以解决你的问题了。.box 这个样式也不需要了

**Comment by LOU-4599** [comment]
> @LOU-4599 你要给固定宽度和高度的话，应该这样使用
> 
> ```ts
> :scroll="{ x: 1500, y: 500 }"
> ```
> 
> 你的例子里只给了 x，我觉得给一个 y 为 500 应该就可以解决你的问题了。.box 这个样式也不需要了

不好用，这样会造成表格内部出现滚动条，而且也无法解决出现双滚动条问题

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/499a9b15-b780-4b07-a979-2046302344d5)
没有发现双滚动条啊，这个表格内部出现滚动条不是正常行为吗

**Comment by songjie55** [comment]
.ant-table-sticky-scroll{
  display: none;
}

试试吧

**Comment by zzzgit** [comment]
我这里也是两个横向滚动条，我设置的是 x: maxContent

**Comment by chendaleiQ** [comment]
> ![image](https://private-user-images.githubusercontent.com/82451257/262883855-499a9b15-b780-4b07-a979-2046302344d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3NTI4MjIsIm5iZiI6MTcwMzc1MjUyMiwicGF0aCI6Ii84MjQ1MTI1Ny8yNjI4ODM4NTUtNDk5YTliMTUtYjc4MC00YjA3LWE5NzktMjA0NjMwMjM0NGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI4VDA4MzUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OWVmNGYwZjQ3ZmJkZTY3MjQxMjNhY2M3ZGZhMDU2MDI2MmU4MWNlYjBjMThiOWU3MDg0ZTM4MmQxYmYwZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rXKNLOsfBrZ9t5oV-zRhLvaDCrX23RjbCN_8sFdq6ig) 没有发现双滚动条啊，这个表格内部出现滚动条不是正常行为吗

你把下面css中，的overflow:auto;注释打开再试试

**Comment by zzzgit** [comment]
https://codesandbox.io/p/sandbox/selection-and-operation-ant-design-vue-4-0-8-forked-9r2vvh?file=%2Fsrc%2Fdemo.vue%3A12%2C39

![image](https://github.com/vueComponent/ant-design-vue/assets/1060733/6c663da5-24e6-4eb4-8f5a-608b710c9b2c)

选择每页20行，就能看到效果

**Comment by HuangZumao** [comment]
我也遇到了  所以官方是不解决么

**Comment by wentmac** [comment]
> .ant-table-sticky-scroll{ display: none; }
> 
> 试试吧

目前看，这位兄弟这个css的解决方案是可以的，就是不知道有没有其他负作用，比如影响其他或全局的样式功能。

好奇这个bug这么久了，官方怎么就不解决呢？

**Comment by Sun79** [comment]
看了源码，找到两个横向滚动条的原因了，需要设置 getContainer 返回滚动容器
https://codesandbox.io/s/modest-bush-2mg39s
![image](https://github.com/user-attachments/assets/faf95727-985c-47ea-a4b3-ebb67fdbb7cd)

**Comment by efframia** [comment]
> 看了源码，找到两个横向滚动条的原因了，需要设置 getContainer 返回滚动容器
> 
> https://codesandbox.io/s/modest-bush-2mg39s
> 
> ![image](https://private-user-images.githubusercontent.com/17243584/356170469-faf95727-985c-47ea-a4b3-ebb67fdbb7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NDgzMzcsIm5iZiI6MTcyNjY0ODAzNywicGF0aCI6Ii8xNzI0MzU4NC8zNTYxNzA0NjktZmFmOTU3MjctOTg1Yy00N2VhLWE0YjMtZWJiNjdmZGJiN2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDA4MjcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2OGVkMTA2NWUxNDdkODVmNGFhMDNiZmFmZjNjMzNlODZkYzJkZTcwMmE3MzE3OWE5YWE1MGU2M2QwNTUzY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QGQlku7XWpAQgCRvFtj5jGYYoYBHOWf-eo4l0B5NRjg)
> 
> 可以用下面这个方法递归寻找滚动容器
> 
> ```ts
> function getScroller(el: HTMLElement | null): HTMLElement | null {
>   if (!el)
>     return el
> 
>   const computedStyle = window.getComputedStyle(el)
>   if (['auto', 'scroll'].includes(computedStyle.overflowY))
>     return el
> 
>   return getScroller(el.parentElement)
> }
> ```

这个方法是有效的，只要像图中这样getContainer这里设置外层div的ref就可以了，没有用到递归方法。
