### ISSUE TITLE
直接安装 unplugin-vue-components【0.25.1】 按需加载组件，4.0新增的组件无法使用

### ISSUE THREAD

**Issue by horsecms** [vueComponent/ant-design-vue#6882]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
win10, chrome 版本 101.0.4951.54（正式版本） （64 位）, vue 3.2.25

### Reproduction link
[https://antdv.com/docs/vue/introduce-cn#%E8%87%AA%E5%8A%A8%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6](https://antdv.com/docs/vue/introduce-cn#%E8%87%AA%E5%8A%A8%E6%8C%89%E9%9C%80%E5%BC%95%E5%85%A5%E7%BB%84%E4%BB%B6)

### Steps to reproduce
应该使用 @yeahka/unplugin-vue-components 【0.25.4】或者将 unplugin-vue-components 更新至最新版本

### What is expected?
应该使用 @yeahka/unplugin-vue-components 【0.25.4】或者将 unplugin-vue-components 更新至最新版本

### What is actually happening?
应该使用 @yeahka/unplugin-vue-components 【0.25.4】或者将 unplugin-vue-components 更新至最新版本

**Comment by aibayanyu20** [comment]
已经提供了一个独立的resolver，https://www.npmjs.com/package/antdv-component-resolver
