### ISSUE TITLE
useApp返回的modal多次触发控制台报错重复的key, 界面不正常

### ISSUE THREAD

**Issue by agileago** [vueComponent/ant-design-vue#6886]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
chrome111

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shi-yong-usemodalhuo-qu-shang-xia-wen-ant-design-vue-4-0-1-forked-mrtwck?file=/src/demo.vue)

### Steps to reproduce
demo貌似直接报错

### What is expected?
正常弹出，支持多次弹出

### What is actually happening?
界面不正常，无法关闭modal

**Comment by agileago** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-ant-design-vue-4-0-1-forked-rspn3c?file=/src/myPage.vue


补充一个， modal都无法点击

**Comment by kovsu** [comment]
第一个例子，官网示例 demo 没有问题。
第二个例子的报错是
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/409cfec4-f4eb-4444-a241-0b7c1ccc730f)

**Comment by selicens** [comment]
@kovsu Contributors list 
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/abc00c98-e03d-478b-8309-dbe47f3c6f0e)

**Comment by kovsu** [comment]
@selicens 具体哪个页面啊，我把判断条件移到父元素了，看看还有啥问题没

**Comment by selicens** [comment]
> @selicens 具体哪个页面啊，我把判断条件移到父元素了，看看还有啥问题没

官网组件页

**Comment by kovsu** [comment]
> > @selicens 具体哪个页面啊，我把判断条件移到父元素了，看看还有啥问题没
> 
> 官网组件页

看看路由 没找到。然后这个 issue，好像和你写的 App 组件有关

**Comment by selicens** [comment]
这边复现了，排查下

**Comment by agileago** [comment]
@selicens @kovsu  我再补个例子

https://stackblitz.com/edit/vite-juraqs?file=main.tsx

你点击按钮，就可以看到现象

**Comment by agileago** [comment]
![2023-08-25 10 38 49](https://github.com/vueComponent/ant-design-vue/assets/11799110/cd0e457c-3502-40db-888b-5398a1f97baa)

**Comment by agileago** [comment]
@tangjinzhou 他解决的是示例报错的问题，不是我这个功能的问题，重新打开吧

**Comment by agileago** [comment]
https://codesandbox.io/s/ji-ben-shi-yong-ant-design-vue-4-0-2-forked-kwgxqg?file=/src/myPage.vue

@tangjinzhou @kovsu @selicens 最新版依然有这个问题， useApp 返回的 modal 无法在异步中调用

**Comment by selicens** [comment]
> https://codesandbox.io/s/ji-ben-shi-yong-ant-design-vue-4-0-2-forked-kwgxqg?file=/src/myPage.vue
> 
> @tangjinzhou @kovsu @selicens 最新版依然有这个问题， useApp 返回的 modal 无法在异步中调用
真的会有人这样用嘛一直弹modal

**Comment by agileago** [comment]
调接口，然后给用户反馈·

**Comment by agileago** [comment]
@tangjinzhou 重新打开吧
