### ISSUE TITLE
[typography-paragraph]editable没有穿透传递onSave方法

### ISSUE THREAD

**Issue by aov2005** [vueComponent/ant-design-vue#6887]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
```vue
<a-typography-paragraph
    :editable="{
      onSave() {}
    }"
/>
```

无法使用onSave方法，使用场景是实时修改操作，blur自动保存

### What does the proposed API look like?
```vue
<a-typography-paragraph
    :editable="{
      onSave() {}
    }"
```

**Comment by aov2005** [comment]
[  onSave: Function as PropType<(val: string) => void>,](https://github.com/vueComponent/ant-design-vue/blob/6c13c964c5a56a440cf47aba9a8484ebbb2f3a1f/components/typography/Editable.tsx#L19C3-L19C9)

看到源码有写onSave方法

**Comment by kovsu** [comment]
https://antdv.com/components/typography#editable 这里面没有说有 onSave 方法

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/d8eed138-ab18-4306-a51d-eb52cefa241c)

然后这里其实也只是传了一个 onSave 方法，实际并没有做什么操作
