### ISSUE TITLE
Message 组件的 `<ContextHolder />` 会造成 Nuxt 在切换 Layout 使 body 消失

### ISSUE THREAD

**Issue by greenhat616** [vueComponent/ant-design-vue#6888]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Ubuntu 22.04.3 LTS on Windows 10 x86_64、Chrome 117.0.5911.2、Vue 3.3.4、Nuxt 3.6.5

### Reproduction link
[https://stackblitz.com/edit/nuxt-starter-zuubio?file=pages%2Findex.vue](https://stackblitz.com/edit/nuxt-starter-zuubio?file=pages%2Findex.vue)

### Steps to reproduce
1、在 Layout 中使用 Message 推荐的组合式 API 用法，将 `<ContextHolder />` 注册到 Layout 中。
2、在使用路由切换 Layout 时会造成 body 元素消失。
![image](https://github.com/vueComponent/ant-design-vue/assets/41122242/69856035-7a28-42fd-ad93-05a5993c5bb9)
![image](https://github.com/vueComponent/ant-design-vue/assets/41122242/04da8336-24f0-4a92-8a60-38e6681c5e0e)

### What is expected?
Body 不会消失

### What is actually happening?
Body 消失

**Comment by aibayanyu20** [comment]
update 4.0.2
