### ISSUE TITLE
无法变更被Popconfirm嵌套的Checkbox的值

### ISSUE THREAD

**Issue by Firestorm01** [vueComponent/ant-design-vue#6892]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Win11，Edge 116，Vue 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-1-forked-dhhly3?file=/src/demo.vue:0-229)

### Steps to reproduce
```html
<template>
  <a-popconfirm
    title="Are you sure delete this task?"
    ok-text="Yes"
    cancel-text="No"
    @confirm="confirm"
    @cancel="cancel"
  >
    <a-checkbox v-model:checked="check" />
  </a-popconfirm>
</template>
```

点击其中的Checkbox

### What is expected?
点击Checkbox可变更check的值

### What is actually happening?
点击Checkbox时check的值无变化

**Comment by kovsu** [comment]
如果点击就去修改 `checkbox` 的值得话，那你使用 `popconfirm` 的目的是什么。现在这样看起来好像就是正常的表现，你只需要在 `confirm ` 或者 `cancel ` 里更改 `check` 的值就行了。

**Comment by Firestorm01** [comment]
> 如果点击就去修改 `checkbox` 的值得话，那你使用 `popconfirm` 的目的是什么。现在这样看起来好像就是正常的表现，你只需要在 `confirm ` 或者 `cancel` 里更改 `check` 的值就行了。

感谢你的回复，应用场景是这样的。
checkbox的disabled为true，用popconfirm来询问是否编辑，如确认则disabled变为false。
为与其他如input组件获得相同效果，这时点击checkbox需要能够变更checked状态。

**Comment by kovsu** [comment]
我这里 checkbox 的 disabled 为 true 的话，popconfirm 都触发不了。。。你再给个复现呗。 @Firestorm01

**Comment by Firestorm01** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-1-forked-dhhly3?file=/src/demo.vue:0-229)

修改了Reproduction link的代码。
点击文本框标签选择Yes后文本框可编辑
点击复选框标签选择Yes后复选框点击无效

**Comment by kovsu** [comment]
@Firestorm01 你如果着急你先设置 `<popconfirm />` 的 `trigger` 属性为 `hover`。这样是没问题的，具体我再看看

**Comment by Firestorm01** [comment]
@kovsu 好的，麻烦你了

**Comment by tangjinzhou** [comment]
checkbox 绑定个 click 事件，自己控制选中效果吧
