### ISSUE TITLE
form 表单验证a-range-picker组件是否选择日期，校验不到。

### ISSUE THREAD

**Issue by zgl9315** [vueComponent/ant-design-vue#6901]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vuex 3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-yfqqjs?file=/src/App.vue)

### Steps to reproduce
a-range-picker也接收不到v-modal的值，form表单校验类型type 根据官网提示写array最后还是string

<template>
<div>
<a-form-model ref="ruleForm" layout="inline" :rules="rules" :model="form">
<a-form-model-item label="排班时间" prop="schedulingTime">
<a-range-picker
ref="rangePicker"
style="width: 200px"
@change="handelSelDate"
format="YYYY-MM-DD"
valueFormat="YYYY-MM-DD"
:disabled-date="disabledDateHandler"
/>
</a-form-model-item>
</a-form-model>
<a-button type="primary" @click="handelSubmit">提交</a-button>
</div>
</template>
<script>
export default {
data() {
return {
form: {},
};
},
methods: {
handelSelDate(date) {
// if (date.length > 0) {
//   this.$nextTick(() => {
//     this.form.schedulingTime = [...date];
//     this.$refs.ruleForm.clearValidate(["schedulingTime"]);
//   });
// }
this.form.schedulingTime = [...date];
},
disabledDateHandler(current) {
//当前周开始时间                               //当前周结束时间
return (
current && !(current.isoWeekday() === 1 || current.isoWeekday() === 7)
);
},
validateArray(rule, value, callback) {
value = this.form.schedulingTime;
if (
(value && !Array.isArray(value)) ||
(Array.isArray(value) && value.length == 0)
) {
callback(new Error("请选择排班时间"));
} else {
callback();
}
},
handelSubmit() {
this.$refs.ruleForm.validate((valid) => {
if (valid) {
console.log(this.form, "111111111111");
} else {
return false;
}
});
},
},
computed: {
rules() {
let rules = {
schedulingTime: [
{
required: true,
type: "array",
trigger: "change",
message: "请选择排班时间",
},
{ validator: this.validateArray, message: "请选择排班时间" },
],
};
if (this.modelType == "oneClick") {
rules["lastWeekRotation"] = [
{
required: true,
message: "请选择是否按照上周轮转",
trigger: "change",
},
];
}
return rules;
},
},
};
</script>

### What is expected?
如何解决日期区间校验问题

### What is actually happening?
a-range-picker也接收不到v-modal的值，form表单校验类型type 根据官网提示写array最后还是string

**Comment by aibayanyu20** [comment]
1.x不在维护，请升级到3.x或4.x

**Comment by zgl9315** [comment]
公司项目依赖在1.x我又不能跟换，请提供一下解决方案

**Comment by zgl9315** [comment]
公司项目依赖在1.x我又不能跟换，请提供一下解决方案
