### ISSUE TITLE
Table组件可编辑的单元格（Input组件）使用微软拼音输入中文时光标会自动跳转到文本末尾位置

### ISSUE THREAD

**Issue by titania10** [vueComponent/ant-design-vue#6907]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
window 11， Google Chrome 116，Vue.js 3.3.4

### Reproduction link
[https://codesandbox.io/s/4jryrr](https://codesandbox.io/s/4jryrr)

### Steps to reproduce
1，点击上述链接，查看Table组建-可编辑单元格；
2，切换拼音输入法为：微软拼音-中文简体；
3，点击单元格唤醒输入框，此时输入框内已经存在文本，将光标移至到输入框文本最前端，进行中文输入。

### What is expected?
光标保持在指定位置，能正常输入中文

### What is actually happening?
实际上，正在进行输入时，光标会自动跳转到文本尾部

---
1，使用“搜狗拼音输入法”可能不会出现这个问题，请使用“微软拼音-中文简体”来复现；
2，在Table组件内使用输入框Input， Textarea 都会出现上述问题，单独使用则不会。

**Comment by wangzhen-CHN** [comment]
同样遇到这个问题
