### ISSUE TITLE
[Bug反馈] StyleProvider组件只能在第一次使用时注入样式，后续使用均会丢失样式

### ISSUE THREAD

**Issue by xiaoqiang1999** [vueComponent/ant-design-vue#6912]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Windows11 / Chrome & Edge / Vue 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/confident-fog-f94y8w)

### Steps to reproduce
使用ShadowDOM隔离CSS样式，多次使用StyleProvider指定container，只会在第一次使用StyleProvider时有样式，其余均丢失样式。
注：Antd的React版本无此问题，会正常的向不同的container中注入样式。

详见CodeSandbox：https://codesandbox.io/p/sandbox/confident-fog-f94y8w

### What is expected?
多个StyleProvider的container分别拥有自己的样式

### What is actually happening?
使用ShadowDOM隔离CSS样式，多次使用StyleProvider指定container，只会在第一次使用StyleProvider时有样式，其余均丢失样式。

**Comment by xiaoqiang1999** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/40377409/b9893d4d-913f-485d-9ec8-31ddc7ffa78d)

**Comment by robertyclin** [comment]
4版本使用了css in js，怎么设置px2rem的撒

**Comment by Time-coding** [comment]
可以支持pwa吗
