### ISSUE TITLE
在shadowRoot中,通过StyleProvider重新指定了样式挂载的dom，此时按钮添加loading状态，loading 无动画

### ISSUE THREAD

**Issue by Xdy1579883916** [vueComponent/ant-design-vue#6914]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Windows11 / Chrome & Edge / Vue 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/bitter-dawn-hv47dx?file=%2Fsrc%2Fmain.tsx%3A12%2C24)

### Steps to reproduce
详见CodeSandbox

### What is expected?
应该呈现loading状态

### What is actually happening?
loading了，但是没有动起来

![image](https://github.com/vueComponent/ant-design-vue/assets/40905802/017fd313-5b49-4693-9fde-9f214321bf84)

**Comment by xiaoqiang1999** [comment]
StyleProvider问题不少啊，还有我这个问题: #6912

**Comment by Xdy1579883916** [comment]
你这个问题我提Issue之前看到过的，我的CodeSandbox案例就是拿你的改的哈哈哈。

 为了支持shadow dom，我经过多方评估，目前还是ElementPlus支持的最好（当然还是要改动一下源码的，改动不多）
 感兴趣可以了解一下[方案](https://github.com/element-plus/element-plus/issues/4462)
 
 没办法，项目已经用Element+做了，再临时换UI也是需要很大的勇气的，改动特别特别大。

**Comment by Xdy1579883916** [comment]
来晚了，或许你说的缺少样式，可以用这个解决 [方案](https://github.com/element-plus/element-plus/issues/4462#issuecomment-1702616766)

**Comment by xiaoqiang1999** [comment]
> 来晚了，或许你说的缺少样式，可以用这个解决 [方案](https://github.com/element-plus/element-plus/issues/4462#issuecomment-1702616766)

感谢分享
