### ISSUE TITLE
在webcomponent中怎么引入，样式丢失

### ISSUE THREAD

**Issue by nickolboy** [vueComponent/ant-design-vue#6915]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用defineCustomElement定义了一个webcomponent，里面引入了antd，但是样式没有。但是新版本css in js，没有样式文件，请问要怎么引入进来

### What does the proposed API look like?
文件改成了ce.vue也没用

**Comment by nickolboy** [comment]
https://codesandbox.io/s/nice-pond-w7fn6c?file=/src/components/MyButton.ce.vue

**Comment by aibayanyu20** [comment]
参考官方文档，是不支持cssinjs的，https://cn.vuejs.org/guide/extras/web-components.html#building-custom-elements-with-vue
只支持内联style的模式

**Comment by nickolboy** [comment]
貌似StyleProvider可以，但是有些组件好像有问题，例如dropdown

**Comment by xiaoqiang1999** [comment]
用StyleProvider指定container为ShadowROOT就可以了，但Vue的defineCustomElement貌似没提供ShadowRoot的实例，所以，你可以自己写个Class定义一个WebComponent，然后在这个Class中自己调用普通的Vue组件，自己处理WebComponent的attr和事件。
就是太繁琐了。

**Comment by Weicup** [comment]
用的不是cssinjs的话，例如3.x版本支持吗
