### ISSUE TITLE
vite4.0 无法排除lodash依赖

### ISSUE THREAD

**Issue by jc840031139** [vueComponent/ant-design-vue#6919]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
vue 3.3.4 、vite 4.4.9

### Reproduction link
[http://www.a.com](http://www.a.com)

### Steps to reproduce
##通过rollup-plugin-external-globals   来排除依赖
````
export default defineConfig({
build: {
rollupOptions: {
plugins: [externalGlobals({ lodash: "_" })],
},
},
});


<script src="https://unpkg.com/lodash@4.17.21/lodash.min.js"></script>
````

### What is expected?
我希望lodash 能让我通过cdn引入  微前端中子应用无需打包进去

### What is actually happening?
通过rollup-plugin-visualizer依赖分析lodash 还是被打包进去

**Comment by jc840031139** [comment]
<img width="1391" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/34274229/5720847e-458f-44a6-b76b-56c3928cdd49">
这是依赖分析

**Comment by jc840031139** [comment]
antd 也是通过 cdn加载 
<img width="339" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/34274229/7a0f3551-1505-477e-8e16-c9558f3f2a28">
 还想顺便提个小问题 @ant-design/icons-vue 的cdn引入地址我没有找到 如果有的话 请给我提供一下 感谢

**Comment by Ggmid** [comment]
分析了一下，ant-design-vue里面本身就有lodash和lodash-es两个库，如果非要去掉lodash依赖，应该ant-design-vue要按需加载并且不要用Space这个组件，不知道是否能解决这个问题
