### ISSUE TITLE
a-tabs组件的默认slot插槽中无法渲染自定义组件

### ISSUE THREAD

**Issue by lisenz** [vueComponent/ant-design-vue#6920]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.0-rc.6

### Environment
vue3.2,ant-design-vue 4.0.0

### Steps to reproduce
我对a-tabs组件以及tab-pane组件分别进行了封装，以下是我封装的组件代码：
notification.vue
```
<template>
  <div class="my-notifications-tabs">
  <a-tabs :animated="false">
  <slot></slot>
  </a-tabs>
  </div>
</template>
<script setup>
defineOptions({
name: 'notification'
});
</script>
```
notificationTab.vue
```
<template>
<a-tab-pane :key="key" :tab="title" class="my-notifications-tab">
<div class="my-notifications-container">
<slot name="top"></slot>
<div class="my-notifications-container-list">
<slot></slot>
</div>
</div>
</a-tab-pane>
</template>
<script setup>
const $props = defineProps({
title: {
type: String,
required: true
},
key: {
type: String
});
</script>
```

在App.vue中使用
```
<notification>
<notification-tab key="1" title="Tab 1">Content of Tab Pane 1</notification-tab>
<notification-tab key="2" title="Tab 2">Content of Tab Pane 2</notification-tab>
</notification>
```

但是渲染出来的效果是只有Content of Tab Pane 1这个内容有出现，标签页没有渲染出来，但是如果我把 notification-tab 组件换成 a-tab-pane 组件，就能正常渲染出标签页，请问tabs是否子组件只能是 a-tab-pane

### What is expected?
能与在a-tabs组件中使用 a-tab-pane 组件一样

### What is actually happening?
无法渲染出二次封装的 a-tab-pane 组件

**Comment by cc-hearts** [comment]
代码中现在是通过直接解析 Tabs 下面默认的插槽做的 
https://github.com/vueComponent/ant-design-vue/blob/46be19531db99f5e5d7998a773a0398409e04a2d/components/tabs/src/Tabs.tsx#L377

可以将 `notificationTab.vue` 下面的 defineProps 的 `title` 换成 `tab`

**Comment by lisenz** [comment]
@cc-hearts 谢谢，换成tab确实就可以了

**Comment by lisenz** [comment]
@cc-hearts 现在tab正常了，但是又遇到一个问题，key不正常了，接上面的代码，在notification-tab组件中，使用defineProps返回的$props变量，通过$props.key获取到的值却是undefined,但是组件使用是正常的

**Comment by cc-hearts** [comment]
> @cc-hearts 现在tab正常了，但是又遇到一个问题，key不正常了，接上面的代码，在notification-tab组件中，使用defineProps返回的$props变量，通过$props.key获取到的值却是undefined,但是组件使用是正常的

`key` 是 vue 所需要的关键字属性 用于 `diff` 比较的。 如果你需要唯一标识符 可以使用其他的命名替代。

(这里是对 vue 的 `key` 属性的描述： https://vuejs.org/api/built-in-special-attributes.html#key)
