### ISSUE TITLE
找不到模块“ant-design-vue”或其相应的类型声明。ts(2307)

### ISSUE THREAD

**Issue by zxxj** [vueComponent/ant-design-vue#6922]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
vue: 3.3.4

### Reproduction link
[https://github.com/zxxj/use-admin-template/blob/master/src/App.vue](https://github.com/zxxj/use-admin-template/blob/master/src/App.vue)

### Steps to reproduce
按需引入后,引入antdvue组件时,ts提示未找到类型声明文件

### What is expected?
消除ts的类型报错

### What is actually happening?
按需引入后,引入antdvue组件时,ts提示未找到类型声明文件

---
无

**Comment by zxxj** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/96833320/38e9a1a2-a8de-48eb-a9e8-18bbe544e396)

**Comment by cc-hearts** [comment]
无法复现，能否提供一下 vue相关的插件

<img width="368" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/fc0a9c6f-7dcf-46a5-a935-60d6fcb861fe">

**Comment by aibayanyu20** [comment]
编辑器问题，参考vue官方文档[vue takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode)
