### ISSUE TITLE
slot label of FormItem does not provide the functionality  , but slot extra works well

### ISSUE THREAD

**Issue by six5nine** [vueComponent/ant-design-vue#6928]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
chrome, vue3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
<AFormItem><template #label><div>xxxxx</div></template></AFormItem>

### What is expected?
self-defined slot content could display

### What is actually happening?
nothing happend when slot label used, but slot extra could work well.

**Comment by kovsu** [comment]
What's the reason you want to use self-defined slot? Please provide some background.

**Comment by six5nine** [comment]
> What's the reason you want to use self-defined slot? Please provide some background.

thanks for your kind reply , i just wanna have additional data depended information or icon inserted together with label names

**Comment by kovsu** [comment]
@six5nine antdv supports using `label` slot. so why don't you give us a reproduction link.

**Comment by six5nine** [comment]
it looks when aformitem with label value assigned, then slot label will be ignored,  is it expected behavior when label value in form item and slot label used in same time?

**Comment by kovsu** [comment]
@six5nine ???? give me a reason why should i use them at the same time.
