### ISSUE TITLE
选择框tag，关闭图标不出现

### ISSUE THREAD

**Issue by luyang5123** [vueComponent/ant-design-vue#693]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue@2.5.3  ant-design-vue@1.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z2rjwon4r3)

### Steps to reproduce
选择框tag，第一个输入的内容点击回车正常存在关闭icon，其他就不正常，当二次回车删掉一个数据时，再次输入内容回车正常存在关闭icon

### What is expected?
官网demo

### What is actually happening?
官网demo

**Comment by dakonglongha** [comment]
@tangjinzhou 大概什么时候能够解决呢

**Comment by tangjinzhou** [comment]
@dakonglongha 升级vue版本尝试下 2.6.10没有该问题
