### ISSUE TITLE
a-style-provider和a-watermark、a-time-picker使用就会有导入样式错误

### ISSUE THREAD

**Issue by LiuChang0725** [vueComponent/ant-design-vue#6932]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.2、4.0.1

### Environment
mac0S13.6、Chrome116.0.5845.179、Vue3.3.4、Vite4.4.9

### Reproduction link
[https://antdv.com/docs/vue/compatible-style-cn](https://antdv.com/docs/vue/compatible-style-cn)

### Steps to reproduce
重新安装antd引入使用a-style-provider和a-watermark、a-time-picker使用就会有导入样式错误、前几天4.0.2、4.0.1版本还没有问题

### What is expected?
不报错

### What is actually happening?
使用这两个组件就报错

![image](https://github.com/vueComponent/ant-design-vue/assets/37528714/5d784732-4315-4f3d-b844-53e874956666)

**Comment by LiuChang0725** [comment]
a-time-picker、a-time-range-picker也会有同样的样式引入错误

**Comment by NoTwoBoy** [comment]
@LiuChang0725 遇到同样问题，请问你解决了吗

**Comment by NoTwoBoy** [comment]
干掉babel-plugin-import依赖就好，详情请看[官网升级文档](https://antdv.com/docs/vue/migration-v4-cn#%E7%A7%BB%E9%99%A4-babel-plugin-import)
