### ISSUE TITLE
form component not support nested validate

### ISSUE THREAD

**Issue by Alkaidcc** [vueComponent/ant-design-vue#6936]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
macOS Chrome v116.0.5845.140 (arm64) Vue3.3.4

### Reproduction link
[https://github.com/Alkaidcc/a-form-nested-validate](https://github.com/Alkaidcc/a-form-nested-validate)

### Steps to reproduce
1. click the first input, then blur to trigger validation
2. text something, then blur to trigger validation,error message disapeared as expected
3. click the second input, then blur to trigger validation
4. text something, then blur to trigger validation, error message still there

### What is expected?
```
<script setup lang="ts">
import { ref } from 'vue';

const info = ref({
name: '',
person: {
sex: ''
}
})
</script>

<template>
<a-form :model="info">
<a-form-item name="name" :rules="[{required: true,message: 'name required',trigger: 'blur'}]">
<a-input v-model:value="info.name"></a-input>
</a-form-item>
<a-form-item name="person.sex" :rules="[{required: true,message: 'sex required',trigger: 'blur'}]">
<a-input v-model:value="info.person.sex"/>
</a-form-item>
</a-form>
</template>
```
here `info.person.sex` should be validated properly

### What is actually happening?
nest object validate not working

        

<img width="369" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/54631354/f4e1dc25-e3c9-4ecd-a265-118d69617cef">

**Comment by Alkaidcc** [comment]
solved by dynamic name
```
<a-form-item :name="['person', 'sex']" :rules="[{required: true,message: 'sex required',trigger: 'blur'}]">
<a-input v-model:value="info.person.sex"/>
</a-form-item>
```

**Comment by Userzhizhong** [comment]
I want to ask for a resolution in vesion 3, 3 only offer string type name

**Comment by Alkaidcc** [comment]
> solved by dynamic name
> 
> ```
> <a-form-item :name="['person', 'sex']" :rules="[{required: true,message: 'sex required',trigger: 'blur'}]">
> <a-input v-model:value="info.person.sex"/>
> </a-form-item>
> ```

It's worked as well in antdv3.2.20 @Userzhizhong. I can't understand `vesion 3` here, minimal reproduction would be helpful
