### ISSUE TITLE
Radio按钮样式左边框有问题

### ISSUE THREAD

**Issue by zmyjs** [vueComponent/ant-design-vue#6943]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
chrome 116.0.5845.187

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4jf6h8?file=/src/demo.vue)

### Steps to reproduce
Radio按钮样式，不需要做任何事情，直接在官方文档上，可以看到左边框有问题，高度大了1px。

<img width="1200" alt="微信截图_20230912120012" src="https://github.com/vueComponent/ant-design-vue/assets/20396642/44ca6c40-ca3f-41f8-b354-a9cb9deb9c84">

<img width="671" alt="微信截图_20230912121011" src="https://github.com/vueComponent/ant-design-vue/assets/20396642/d66cc02c-383d-45ad-96e7-5409dd3c75fc">

### What is expected?
边框正常

### What is actually happening?
Radio按钮样式，不需要做任何事情，直接在官方文档上，可以看到左边框有问题，高度大了1px。

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/a173e25f-6bf8-4895-892b-da8457af0efb)
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/cabfe159-9385-4507-91d0-fc704aa86997)

没有发现你这个问题

**Comment by zmyjs** [comment]
> ![image](https://user-images.githubusercontent.com/82451257/267234103-a173e25f-6bf8-4895-892b-da8457af0efb.png) ![image](https://user-images.githubusercontent.com/82451257/267234463-cabfe159-9385-4507-91d0-fc704aa86997.png)
> 
> 没有发现你这个问题

我重新回去看，可能是显示器的原因。。。

我的4K显示器，不需要放大网页，直接看就有（截图再放大图片看）。
![image](https://github.com/vueComponent/ant-design-vue/assets/20396642/99f83576-f737-4eed-956f-89c9363a9ee1)

我另外一个1680*1050显示器，直接看没有，放大之后看有。
