### ISSUE TITLE
Affix抖动以及结合Menu组件导致无法适应collapsed后的宽度

### ISSUE THREAD

**Issue by xstxhjh** [vueComponent/ant-design-vue#695]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
"vue": "^2.6.6","Google Chrome":"73.0.3683.103"

### Reproduction link
[https://chirenmeng.cn/](https://chirenmeng.cn/)

### Steps to reproduce
> 很抱歉无法提供重现链接，不过我写了一小段简单的闪动bug代码。英语水平不过关，所以也无法写英文文档。

> 快速的将滚轮上下滑动，两个div会出现闪动现象。出现概率比较随机，请多尝试几次，要特别快速的滚动。

> 还有一个问题就是：当我给a-menu组件添加了Affix之后，缩小浏览器窗口，再最大化，再collapsed折叠菜单栏。会导致宽高出现问题，影响了元素的位置。

```
<template>
<div class = "container">
<a-affix :offsetTop = "0">
<div style = "background-color: thistle;height: 60px;">hfsaahah</div>
</a-affix>
<a-affix :offsetTop = "60">
<div style = "background-color: darkturquoise;height: 60px;">hfsaahah</div>
</a-affix>
</div>
</template>

<script>
export default {
name: "test.vue"
}
</script>

<style scoped>
.container {
height: 110%;
}
</style>
```

### What is expected?
Affix在浏览器宽度发生变化时，也能自动相适应。两个相邻的Affix不会出现闪动/抖动情况。

### What is actually happening?
Affix在浏览器宽度发生变化时，不能适应其宽高，占位面积也失去作用。
两个相邻的Affix，在滚轮很快上下滑动时，会出现闪动/抖动现象。

**Comment by lvreninfo** [comment]
`<a-affix :offsetTop = "0.1">`
