### ISSUE TITLE
Grid打印样式问题

### ISSUE THREAD

**Issue by sscfaith** [vueComponent/ant-design-vue#6951]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Chrome116; Vue3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-5f9j9n?file=/src/App.vue)

### Steps to reproduce
- [复现链接](https://codesandbox.io/s/vue-antd-template-forked-5f9j9n?file=/src/App.vue)
- 点击Browser标签右侧的Open In New Window, 或直接访问此[链接](https://5f9j9n.csb.app/)
- 浏览器右键 - 打印

### What is expected?
打印样式与页面显示一致

### What is actually happening?
打印样式与页面显示不一致

### 页面显示
<img width="1748" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23066241/3b34db73-960c-4cf7-b0c9-2b762cc6c8ae">

### 打印显示
<img width="1188" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/23066241/7f31f4e2-38fd-4fd0-ba1e-4daf6137bd68">

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/1d74b1e8-6c07-436b-8c20-db673590eb7f)

横向纵向的问题
