### ISSUE TITLE
Using the CDN address to use ant-design-vue in ESM mode does not work correctly

### ISSUE THREAD

**Issue by codelzb** [vueComponent/ant-design-vue#6954]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
any

### Reproduction link
[https://jsrun.net/NGJKp](https://jsrun.net/NGJKp)

### Steps to reproduce
执行下面的代码可重现

### What is expected?
正常运行

### What is actually happening?
出现错误Uncaught TypeError: Cannot read properties of undefined (reading 'renderEmpty')

**Comment by codelzb** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div id="app">
    <a-button @click="handleButtonClick">Click me</a-button>
  </div>
  
  <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
  <script type="importmap">
    {
      "imports": {
        "ant-design-vue": "https://cdn.jsdelivr.net/npm/ant-design-vue@4.0.3/+esm"
      }
    }
  </script>
  
  <script type="module">
    import antd from "ant-design-vue";
  
    const { createApp, ref } = Vue;
    const app = createApp({
      components: {
      },
  
      setup() {
        const handleButtonClick = () => {
          alert('Button clicked!');
        };
  
        return {
          handleButtonClick,
        };
      },
    });
  
    app.use(antd).mount("#app");
  </script>
  
</body>
</html>`

**Comment by kovsu** [comment]
1. <img width="885" alt="截屏2023-09-21 09 52 04" src="https://github.com/vueComponent/ant-design-vue/assets/82451257/5501d89e-57f2-48ac-a5ed-8255d9893589">


2. es folder
<img width="802" alt="截屏2023-09-21 09 46 58" src="https://github.com/vueComponent/ant-design-vue/assets/82451257/66757f97-fa38-4e23-b20e-3f8014e1d9e4">
