### ISSUE TITLE
如何关闭按钮水波纹

### ISSUE THREAD

**Issue by NieBarBar** [vueComponent/ant-design-vue#6955]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

![image](https://github.com/vueComponent/ant-design-vue/assets/81463583/2b9053c7-e94c-47ed-b9e3-fe568866e806)
        
        
### What problem does this feature solve?
我希望按钮保持尽可能的朴素

### What does the proposed API look like?
建议可以通过props进行控制

**Comment by selicens** [comment]
antd是通过config-provider来控制是否使用wave，antdv还没有同步更新到

**Comment by NieBarBar** [comment]
了解
