### ISSUE TITLE
Expect version v4 to provide esm file output just like version v3

### ISSUE THREAD

**Issue by codelzb** [vueComponent/ant-design-vue#6960]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Like [antDv SFC - playground](https://vuecomponent.github.io/sfc-playground) online debugging antDv and can switch version, but since the v4 antDv does not provide the esm file.

### What does the proposed API look like?
bundle esm output

**Comment by kovsu** [comment]
? I don't understand what do you mean.

**Comment by codelzb** [comment]
> ? I don't understand what do you mean.

我需要基于官方[SFC-playground](https://vuecomponent.github.io/sfc-playground)的基础上做一个本地的antd playground用来内部调试antD组件，我看了sfc-playground内部代码发现需要使用支持esm的文件才能正常运行。  但是在v4以后antd 打包输出的文件不再输出esm文件了。希望能和v3版本一样提供打包后支持esm文件。   目前提供的[es文件夹](https://cdn.jsdelivr.net/npm/ant-design-vue@4.0.3/es/index.js)，在未打包之前浏览器无法识别，因为它缺少.js后缀
![image](https://github.com/vueComponent/ant-design-vue/assets/64744556/70c65117-b16c-4721-9a04-63c7450d03c4)

**Comment by codelzb** [comment]
就像这个[issues](https://github.com/vueComponent/ant-design-vue/issues/6954)里的复现方式一样， 当把antd CDN地址更换为https://cdn.jsdelivr.net/npm/ant-design-vue@4.0.3/es/index.js后浏览器访问不到文件
![image](https://github.com/vueComponent/ant-design-vue/assets/64744556/ddad6f5b-3112-47cf-8ce4-cce55726d888)

**Comment by codelzb** [comment]
> > ? I don't understand what do you mean.
> 
> 我需要基于官方[SFC-playground](https://vuecomponent.github.io/sfc-playground)的基础上做一个本地的antd playground用来内部调试antD组件，我看了sfc-playground内部代码发现需要使用支持esm的文件才能正常运行。 但是在v4以后antd 打包输出的文件不再输出esm文件了。希望能和v3版本一样提供打包后支持esm文件。 目前提供的[es文件夹](https://cdn.jsdelivr.net/npm/ant-design-vue@4.0.3/es/index.js)，在未打包之前浏览器无法识别，因为它缺少.js后缀 ![image](https://user-images.githubusercontent.com/64744556/269463111-70c65117-b16c-4721-9a04-63c7450d03c4.png)

@kovsu 有什么解决办法吗  能够让antd在SFC-playground中正确运行

**Comment by kovsu** [comment]
其实如果你要本地调试 antd 的组件的话，你可以直接 fork 仓库，然后改 componnets 里面的代码也能调试组件。或者说你想调试打包后的 antd，你可以用 npm link 去把打包好的 antd 代码软链到你的调试项目。

**Comment by codelzb** [comment]
> 其实如果你要本地调试 antdv 的组件的话，你可以直接 fork 仓库，然后改 componnets 里面的代码也能调试组件。或者说你想调试打包后的 antdv，你可以用 npm link 去把打包好的 antdv 代码软链到你的调试项目。

sorry 可能我没表达好我的意思  我说的本地调试其实是指我们内部人员会在[SFC-playground](https://vuecomponent.github.io/sfc-playground)做一些简单的开发和代码分享，我们目前有多个项目使用了不同版本的antd（包括v1、v3、v4 ）所以希望使用[SFC-playground](https://vuecomponent.github.io/sfc-playground)的时候可以随意切换antd的版本， 如果官方提供了打包后的esm文件，就会变得非常容易。
