### ISSUE TITLE
a-radio-group doesn't allow me to select an option with tab, only arrows

### ISSUE THREAD

**Issue by busybox11** [vueComponent/ant-design-vue#6964]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Vue 3,3,4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-c29jd9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
- Open the minimal reproduction
- Try to navigate in the form only using the tab key on the keyboard (first select the first input element)

### What is expected?
The navigation should go through the first input, then the first radio group item, then the second, and finally the last text input

### What is actually happening?
The navigation goes through the first input, the first radio group item ONLY and finally the last text input.

Although this behavior is not inherently wrong, an option should be provided to make it work on-demand - especially when you use the radio group styled as buttons.

---
The current behavior that permits to select an option from the keyboard only is to use the arrow keys.
Alternatively, trying to set tabindex on the radio-button items will make it work but will also select every radio item twice, one time per tab keypress.

**Comment by likui628** [comment]
https://stackoverflow.com/a/14322755/8011909
> The Tab key moves focus between radio button groups and other widgets.

**Comment by busybox11** [comment]
@likui628 Unfortunately it doesn't work like this. In my CodeSandbox, if you first try to tab without selecting anything, it will focus Option 1. Then you tab again, and it will focus on the next field. This is (probably) intended, even though I'd like to have the possibilty to change this behavior - anyway.

When I am in this second field, without having selected anything in the radio group, if I shift Tab, it will select Option 2 - why?
