### ISSUE TITLE
[Bug反馈] StyleProvider组件只能在第一次使用时注入动画样式，后续使用组件均会丢失过渡动画

### ISSUE THREAD

**Issue by xiaoqiang1999** [vueComponent/ant-design-vue#6965]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.3

### Environment
Windows11 / Chrome & Edge / Vue 3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/confident-fog-f94y8w?file=/src/main.ts)

### Steps to reproduce
与我之前提过的一个Bug类似：#6912 
CodeSandbox也是基于 #6912 改的，两个Bug之间应该有些联系，
都是在ShadowDOM下多次渲染StyleProvider出现的问题；
详见CodeSandbox：https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/confident-fog-f94y8w?file=/src/main.ts
以message、Modal为例，出现了过渡动画丢失的现象。

### What is expected?
正常的、各自独立的过渡动画

### What is actually happening?
只有第一次渲染的DOM有组件的过渡动画

**Comment by xiaoqiang1999** [comment]
#6912

**Comment by kovsu** [comment]
Duplicate of #6912
