### ISSUE TITLE
cascader级联选择异步数据设置value默认值无效 。

### ISSUE THREAD

**Issue by yuyalong0629** [vueComponent/ant-design-vue#697]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
cascader级联选择异步数据设置value或者defaultvalue默认值无效 ,也无报错 。业务需要是每次点开抽屉级联选择input显示默认值value，本地非异步请求正常显示 。

### What does the proposed API look like?
os: mojave 10.14.3,  chrome: 版本 73.0.3683.103（正式版本） （64 位） ,vue: ^2.6.6

**Comment by sendya** [comment]
请提供复现用例

**Comment by yuyalong0629** [comment]
> 请提供复现用例
<a-cascader
              :options="options"
              :fieldNames="{ label: 'name', value: 'id', children: 'childrens' }"
              :value="cateGoryInfo.categorySuperior"
              @change="onChangeCategoryName"
              placeholder="请输入分类名称"
              changeOnSelect
            />
cateGoryInfo: {
        value: 1,
        categoryClassName: '123',
        categoryRemarks: '123',
        categoryCustomer: '1',
        categorySuperior: ['一级弹簧', '二级弹簧', '三级弹簧']
      }
options异步请求，现在就是需要在input里设置value值回显，但是input设置后为空白 。
![image](https://user-images.githubusercontent.com/37603495/56106815-8a713c80-5f75-11e9-9c2f-3f17c5821072.png)

**Comment by hilads** [comment]
@yuyalong0629  你好 我也遇到了这样的问题  请问这个问题解决了？

**Comment by XuanLinWXL** [comment]
+1

**Comment by August2012** [comment]
+1 无解吗

**Comment by shilianmalaxiangguo** [comment]
+1 其实打开是选中了你的默认项的，但是回显就是空白，求解

**Comment by from-to-wpj** [comment]
据我所知value与defaultValue接收的是数组，数组项的值要设置成options单项数据的标识，这个标识是默认fieldNames的value值，
如果自定义fieldNames的value为id,那么这个标识就是id的值。
1、默认fieldNames设置指定值：
:value="[ ' 一级value值 ' ,'下一级的value值'  , '下下一级的value值'  ]"
2、自定义fieldNames，把默认value命名为id (value: 'id')
:value="[ ' 一级id的值 ' ,'下一级的id值'  , '下下一级的id值'  ]"

**Comment by laixiaotao** [comment]
> 据我所知value与defaultValue接收的是数组，数组项的值要设置成options单项数据的标识，这个标识是默认fieldNames的value值，
> 如果自定义fieldNames的value为id,那么这个标识就是id的值。
> 1、默认fieldNames设置指定值：
> :value="[ ' 一级value值 ' ,'下一级的value值' , '下下一级的value值' ]"
> 2、自定义fieldNames，把默认value命名为id (value: 'id')
> :value="[ ' 一级id的值 ' ,'下一级的id值' , '下下一级的id值' ]"
> 可以参考我的一篇文章：https://www.jianshu.com/p/d0578cadda15

懂了，意思是补足数据对吧
