### ISSUE TITLE
下拉框的垂直滚动条自动隐藏

### ISSUE THREAD

**Issue by Firestorm01** [vueComponent/ant-design-vue#6987]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Win11，Edge 118.0.2088.11 ，Vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/san-zhong-da-xiao-ant-design-vue-4-0-3-forked-twjqvs)

### Steps to reproduce
点击Select组件，大约1~2秒后Option下拉框的垂直滚动条消失

### What is expected?
垂直滚动条不自动消失或可设置

### What is actually happening?
下拉框的滚动条自动消失

---
1. 滚动条消失后不主动滚动鼠标滚轮不可知是否还有其它选项，容易产生迷惑。
2. 对没有鼠标中键以及用笔记本触摸板操作的用户不友好

**Comment by selicens** [comment]
看了下，antd也是这样，不过antd比较好的一点是鼠标重新移入滚动条会再次出现，可以同步一下

**Comment by ZhangYuScott** [comment]
May want to fix it
