### ISSUE TITLE
`AutoComplete` 组件嵌套其他输入组件时，两个组件都设置 `placeholder` 时会出现文本重叠

### ISSUE THREAD

**Issue by lai9fox** [vueComponent/ant-design-vue#6993]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
Vue@3.3.4
Antdv@4.0.3

### Environment
Chrome: 版本 117.0.5938.92（正式版本） (arm64)

### Reproduction link
[https://codepen.io/lai9fox/pen/JjwZPqd](https://codepen.io/lai9fox/pen/JjwZPqd)

### Steps to reproduce
https://codepen.io/lai9fox/pen/JjwZPqd

### What is expected?
显示内部组件的 `placeholder`，隐藏 `AutoComplete` 组件的 `placeholder`

### What is actually happening?
两个组件的 `placeholder` 都显示了

**Comment by kovsu** [comment]
AutoComplete 本身是一个 Select，不会针对 children 有没有 placeholder 属性做特殊处理。建议自定义 children 的话控制一下 placeholder 到底是给哪个元素
