### ISSUE TITLE
[UploadDragger] 在 beforeUpload 函数 return false 时仍会发起上传请求

### ISSUE THREAD

**Issue by onlyil** [vueComponent/ant-design-vue#6995]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Macos 13.4.1, Chrome 116.0.5845.187, vue 3.2.37

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-morning-vd9r33?file=/src/App.vue)

### Steps to reproduce
codepen 中对 UploadDragger 和 Upload 组件做了对照，并附有说明

### What is expected?
[UploadDragger] 组件在 beforeUpload 函数 return false 时不会发起上传请求

### What is actually happening?
[UploadDragger] 组件在 beforeUpload 函数 return false 时仍会发起上传请求
[Upload] 普通上传组件在 beforeUpload 函数 return false 时不会发起上传请求，符合预期

**Comment by WWongs** [comment]
要阻止上传，用 Upload.LIST_IGNORE。
![image](https://github.com/vueComponent/ant-design-vue/assets/31298228/b9c3ecc4-fe48-4130-9821-d89d60f83dc1)

**Comment by ZhangYuScott** [comment]
Please check your code, and improve your Vue skills. thanks a lot.
