### ISSUE TITLE
Modal组件，在关闭时会出现两次关闭动画

### ISSUE THREAD

**Issue by Tdota2** [vueComponent/ant-design-vue#6996]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
官方网站示例——“https://www.antdv.com/components/modal-cn”

### Reproduction link
[https://www.antdv.com/components/modal-cn](https://www.antdv.com/components/modal-cn)

### Steps to reproduce
点击confirm或其他按钮，点击确认或取消，会出现，非必现
![modal](https://github.com/vueComponent/ant-design-vue/assets/69885396/96def129-815f-4069-950b-12cfa1bb4de2)

### What is expected?
正常关闭modal

### What is actually happening?
偶发性出现两次关闭动画

**Comment by YYDee-0920** [comment]
![modal](https://github.com/vueComponent/ant-design-vue/assets/69885396/0d4854f4-b6df-4cd4-9879-ba1bbd0f05e1)

**Comment by DesignHhuang** [comment]
你这个好像没有办法复现哦 @YYDee-0920

**Comment by YYDee-0920** [comment]
非常抱歉这么久才回复您，我录制了一个gif，但在git上上传未成功，现在邮箱发您，您看一下，能否看清楚，当我点击confirm的取消时会出现。
我使用的是edge浏览器版本 117.0.2045.43 (正式版本) (64 位)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月28日(星期四) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] Modal组件，在关闭时会出现两次关闭动画 (Issue #6996)





 
你这个好像没有办法复现哦 @YYDee-0920

**Comment by helloword2023** [comment]
确实有这种情况，我有时候也会碰到关闭动画触发2次的情况

**Comment by dadianzi** [comment]
我也有碰到这种情况，偶发

**Comment by aibayanyu20** [comment]
升到最新版本的4.0.6试下看看呢

**Comment by cdl235** [comment]
求助！打包后modal不能正常显示怎么办？

**Comment by YYDee-0920** [comment]
> 升到最新版本的4.0.6试下看看呢

最新版本依旧会闪两次，使用全屏Modal后似乎更加明显了
![20231031-154815](https://github.com/vueComponent/ant-design-vue/assets/69885396/7235483d-992e-4977-bb51-26e5d0c56dd4)

**Comment by a952543073** [comment]
我也遇到这个问题了
怀疑跟 model 内的 dom 元素销毁时机有关系  弹窗内使用复杂组件的时候 必定会复现此问题

**Comment by a952543073** [comment]
简单的表单内容弹窗

https://github.com/vueComponent/ant-design-vue/assets/22365181/9da8219b-c4cf-4283-8af0-1b96ce1f91c1

复杂的表单内容组件弹窗

https://github.com/vueComponent/ant-design-vue/assets/22365181/62bae6c1-242c-4abe-90e5-173ee62fd4f2

**Comment by masicheng** [comment]
同样的情况，我是通过给Modal 加上transitionName=""属性去掉动画后暂时解决了。

**Comment by jack-7788** [comment]
<img width="507" alt="Snipaste_2024-01-29_10-34-09" src="https://github.com/vueComponent/ant-design-vue/assets/70838383/16f6e281-8f91-438c-81ea-fdbdca3f48fc"> 
这样子是可以的

**Comment by jack-7788** [comment]
<img width="508" alt="Snipaste_2024-01-29_10-35-00" src="https://github.com/vueComponent/ant-design-vue/assets/70838383/110a4541-e33c-449b-a11f-f7ba55016216">
这样子是可以的
