### ISSUE TITLE
表格拖拽列问题

### ISSUE THREAD

**Issue by Tnon** [vueComponent/ant-design-vue#6997]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome 95 / 96/  vue3@lasted,vite@2,

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-shen-suo-lie-ant-design-vue-4-0-3-forked-rtmnch?file=/src/demo.vue)

### Steps to reproduce
假如列宽组件重新计算后，拖拽的方法直接赋值新的宽度，会有问题。

### What is expected?
列宽能不能在组件渲染完后，计算新的。

### What is actually happening?
列宽跳动

**Comment by Tnon** [comment]
能把colgroup里的宽度，通过参数全部返回来吗

**Comment by Tnon** [comment]
或者是把表格列的真实宽度 返回一下

**Comment by Tnon** [comment]
const handleResizeColumn = (w, col) => {
    if (tableRef.value.$el.getElementsByTagName('colgroup').length) {
      const cols = tableRef.value.$el
        .getElementsByTagName('colgroup')[0]
        .getElementsByTagName('col');
      const finalWidthArr: number[] = [];
      cols.forEach((ele) => {
        const styleStr = ele.getAttribute('style');
        const startIndex = styleStr.indexOf(': ');
        const endIndex = styleStr.indexOf('px');
        const result = styleStr.slice(startIndex + 1, endIndex);
        finalWidthArr.push(~~result);
      });
      proxyColumns.value.forEach((ele, index) => {
        ele.width = finalWidthArr[index];
      });
    }
    col.width = w;
  };

**Comment by Tnon** [comment]
目前先求

**Comment by Yongest** [comment]
1.x版本，官方文档就有表格伸缩列拖拽的bug。拖拽后完全是乱的，

**Comment by Yongest** [comment]
1.x版本，官方文档就有表格伸缩列拖拽的bug。拖拽后完全是乱的，看官方文档还没有解决。这个要怎么解决呀？能不能像element-ui拖拽那么好用呢？
