### ISSUE TITLE
autofocus property does not work all the time

### ISSUE THREAD

**Issue by busybox11** [vueComponent/ant-design-vue#6998]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
macOS Sonoma, Chrome Dev 119.0.6020.3, Firefox Developer Edition 119.0b2, Vue 3.3.4, antd 4.0.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-wildflower-n2n7hq?file=/src/App.vue)

### Steps to reproduce
Open the codesandbox

### What is expected?
The input field on the browser preview right panel should autofocus on the input field

### What is actually happening?
It doesn't do anything, only render the input.

---
Going to the codesandbox preview URL in a standalone tab will make the input focus. However it does not work on some situations when developing locally, for instance I can't get it to work on a dynamically imported DIalog.

**Comment by cc-hearts** [comment]
no reproduction

<img width="1098" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/efe9a733-53ee-48e4-a952-0867bf181768">

**Comment by busybox11** [comment]
What browser are you using?

**Comment by cc-hearts** [comment]
chrome

**Comment by busybox11** [comment]
I just installed a brand new Chrome stable (v.117.0.5938.132)
I still can't get it to reproduce, it does not autofocus no matter what I do - Also tested on Safari, no luck here too.

![image](https://github.com/vueComponent/ant-design-vue/assets/29630035/3ed5bd57-6dd2-4533-94c9-c8710893397a)

**Comment by cc-hearts** [comment]
try switching ant-design-vue to version 4.0.3 and try opening the page separately (example: https://n2zql5.csb.app/)
<img width="1061" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/b213137d-2f6f-4342-abe6-47fb39c8db3e">

**Comment by busybox11** [comment]
I updated the codesandbox. Still no luck. It already worked if I opened the codesandbox preview URL on a separate tab, I said it in the description.

I guess my issue in local development could be linked to the same thing that doesn't make it work on Codesandbox's preview view (I'm just guessing. I don't actually know). Could it be possible to make it work directly in the editor?

**Comment by cc-hearts** [comment]
`focus` supports controlled mode, and here's an example I wrote that I hope will help you.

`https://codesandbox.io/s/relaxed-dust-nt7d8r?file=/src/main.js`

**Comment by busybox11** [comment]
This will probably be the approach I will use, but does it confirm my issue is actually valid?
Tried on multiple machines, browsers, versions, no luck.

**Comment by busybox11** [comment]
How do I remove the label.
