### ISSUE TITLE
popover、tooltip openChange 为true, 实际并没有真的打开, 无法操作dom

### ISSUE THREAD

**Issue by zmcode** [vueComponent/ant-design-vue#6999]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.3

### Environment
vue: 3.3.4 、 browser:chrome 、ant-design-vue：4.0.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-ch732x?file=/src/demo.vue)

### Steps to reproduce
移动按钮位置, 实际还没显示popover, 无法操作dom

### What is expected?
完全显示完毕操作dom, 期望增加after-enter api

### What is actually happening?
实际还没显示popover, 无法操作dom

---
有时候需要打开弹出获取某个元素大小,
例如像ant-design的color-pick组件, 内部使用了popver来显示, 但是初始化我需要根据颜色来定位圆点的位置, 但是无法获取圆点大小, 造成定位失败

**Comment by zmcode** [comment]
![1695963578583](https://github.com/vueComponent/ant-design-vue/assets/48686959/d6c6a722-3ce5-4492-8b70-213a55179194)
我猜测是enter动画的问题, 但是我通过样式取消他, 不起作用

**Comment by cc-hearts** [comment]
DOM operations can be performed in nextTick.
[CodeSandbox](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-v9ps74?file=/src/demo.vue)

**Comment by zmcode** [comment]
> DOM operations can be performed in nextTick. [CodeSandbox](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-v9ps74?file=/src/demo.vue)

你看链接的最新实例, 不是说获取不到dom, 而是我页面没有展示这个popover, 导致我操作一些dom的位置信息的时候, 没法获取到

**Comment by zmcode** [comment]
> DOM operations can be performed in nextTick. [CodeSandbox](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-v9ps74?file=/src/demo.vue)

[最新例子](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-ch732x?file=/src/demo.vue), 可以看到哪怕包了nextTick,我移动按钮的时候, debugger的时候 我也无法获取到这个dom的宽度, 因为此时还没有展示这个popover

**Comment by cc-hearts** [comment]
I haven't found a good workaround for the time being, But can use `ResizeObserver ` to hack, I hope it works for you.

[CodeSandbox](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-v9ps74?file=/src/demo.vue)

**Comment by DesignHhuang** [comment]
@zmcode 很简单，这边有事件执行顺序的问题。可以这样改写即可实现你的需求。

```
async function onOpenChange(visible) {
    if (visible) {
      await nextTick();
      setTimeout(() => {
        console.log(unref(dom).offsetWidth);
      }, 1);
    }
  }
```

**Comment by DesignHhuang** [comment]
> > DOM operations can be performed in nextTick. [CodeSandbox](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-v9ps74?file=/src/demo.vue)
> 
> [最新例子](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-0-3-forked-ch732x?file=/src/demo.vue), 可以看到哪怕包了nextTick,我移动按钮的时候, debugger的时候 我也无法获取到这个dom的宽度, 因为此时还没有展示这个popover

这边是display:none这个style的添加和删除是在你的代码之后执行的，所以你拿他的width永远拿到的是0。你可以通过修改源码来控制执行顺序。也可以按照我下面的方式加上setTimeout等待display:none这个样式被去掉之后再访问domRef。

**Comment by tetap** [comment]
这里应该增加一个onOpenChangeEnd 表明动画结束事件。
