### ISSUE TITLE
使用Functional(函数式组件)对a-input进行封装后，使用v-model绑定数据出错的问题

### ISSUE THREAD

**Issue by windylaugit** [vueComponent/ant-design-vue#700]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
windows7、chrome.v71.0、Vue.v2.5.22

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50xy39myzx)

### Steps to reproduce
functional组件代码：
```javascript
<script>
export default {
name: 'FunctionalInput',
functional: true,
render (createElement, context) {
return createElement('a-input', context.data, context.children)
}
}
</script>
```
使用代码
```javascript
<functional-input placeholder="FunctionalInput" v-model="url"></functional-input>
```

### What is expected?
期望该封装组件能封装a-input的所有props、attrs、事件、slots等，后续需要在此基础上进行一些props、事件的定义。

### What is actually happening?
在使用v-model绑定数据之后，通过修改输入值触发change事件后报错：Invalid prop: type check failed for prop "value". Expected String, Number, got InputEvent 。且输入值变成了 “[object InputEvent]”

**Comment by tangjinzhou** [comment]
任何组件都可以封装，但是怎么封装那是你的事情，和组件没关系

**Comment by windylaugit** [comment]
能不能不要打官腔，作为使用者，有问题，而且自己确认了无法解决，所以来求助，这难道不对么？
如果你们能知道问题所在，帮助使用者解决困惑，为何不直接点明呢？一句“和组件没关系”，这对于使用者是多么的不负责，是因为 star高了，所以 让使用者：有问题自己解决，爱用不用，是么？

**Comment by windylaugit** [comment]
> 能不能不要打官腔，作为使用者，有问题，而且自己确认了无法解决，所以来求助，这难道不对么？
> 如果你们能知道问题所在，帮助使用者解决困惑，为何不直接点明呢？一句“和组件没关系”，这对于使用者是多么的不负责，是因为 star高了，所以 让使用者：有问题自己解决，爱用不用，是么？

@tangjinzhou

**Comment by windylaugit** [comment]
能否正面回答下问题？我是使用过程中不明白，按照个人阅读文档，查阅issue，查阅资料检查，无法解决问题。以此推论，这或许对于一些需求的人来说是个问题（至少文档中没有先关方面的描述）。本着 共享、奉献的想法，本着促进资源向前发展的想法，我想我是应该来提出来的，或许是我没理解透，但是否也可能是个bug呢？
如果有人能帮忙解答问题，非常感谢。如果有人能一起讨论，乐意之至。可，何必嘲讽？

**Comment by windylaugit** [comment]
自行解决方案：
```javascript
export default {
  name: 'FunctionalInput',
  functional: true,
  model: {
    prop: 'value',
    event: 'change.value'
  },
  render (createElement, context) {
    return createElement('a-input', context.data, context.children)
  }
}
```
原因在于a-input组件使用的非change事件来修改绑定值，但是又触发了change事件，直接导致functional封装无法继承绑定，需要明确指明functional的绑定事件为 change.value
