### ISSUE TITLE
Spin添加高度配置/铺满父容器高度配置

### ISSUE THREAD

**Issue by fancyvip** [vueComponent/ant-design-vue#7004]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Spin作为页面最外层容器时需要铺满容器而不是由子元素撑起高度，目前使用wrapperClassName通过class设置Spin容器的高度

### What does the proposed API look like?
增加height通过传参设置Spin容器高度/增加autoSize自动适应父容器高度

**Comment by kovsu** [comment]
自己写样式吧，你传 height 和你自己写一个 style 没有什么区别
