### ISSUE TITLE
如何定义 table bodyCell 插槽中 record 的类型

### ISSUE THREAD

**Issue by gitdust** [vueComponent/ant-design-vue#7007]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
无（不需要demo实例）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2wpk21kzvr)

### Steps to reproduce
表格 dataSource 有确定数据类型，如 interface IUser { name: string }

### What is expected?
希望 bodyCell 插槽的 record 类型为 IUser

### What is actually happening?
bodyCell 插槽的 record 类型为 Record<string, any>

**Comment by GGqianmo** [comment]
解决了吗？我也遇到这个问题了

**Comment by lzjdong** [comment]
没人吗？ 之前any的时候还能用现在Record<string, any>直接报错
