### ISSUE TITLE
ie11下 RangePicker选择面板无法展开

### ISSUE THREAD

**Issue by luichooy** [vueComponent/ant-design-vue#701]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win10,ie11

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-date-format](https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-date-format)

### Steps to reproduce
1. 鼠标点击RangePicker
2. 选择面板展开
3. 选择面板展开瞬间又自动收起

### What is expected?
期望修复

### What is actually happening?
ie11下选择面板无法展开，展开之后会立刻自动收起

---
官网 -> DatePicker日期选择框 ->日期格式 ->第三个例子RangePicker可以复现改问题

**Comment by wangxueliang** [comment]
ref #626

**Comment by luichooy** [comment]
> ref #626  已经做了polyfill 还是不行

**Comment by luichooy** [comment]
@wangxueliang 已经做了polyfill还是不行呀

**Comment by betgar** [comment]
![image](https://user-images.githubusercontent.com/15810150/60423080-f29ff800-9c1f-11e9-87f6-4518283149f5.png)

IE 版本为上图，问题依然能够重现

**Comment by betgar** [comment]
![range-picker](https://user-images.githubusercontent.com/15810150/60423166-2844e100-9c20-11e9-9c79-e2a347d849c0.gif)
当有值的情况下，panel无法展开

**Comment by betgar** [comment]
最近遇到IE 11 RangePicker在已经有值的情况下，点击输入框无法展开的情况，我浏览了官方的issues，看到了 #608 和 #626 的处理结果，但是发现，在IE 11的不同的minor版本下还是能够重现。
我尝试调试了一下源码，发现在`DateInput#onInputChange`方法中，有逻辑短路的情况：
format: 'YYYY-MM-DD'       
![selectValue-value](https://user-images.githubusercontent.com/15810150/60427437-49f69600-9c29-11e9-9315-ae36e9c20181.jpg)

`DateInput#onInputChange`，这里出现了逻辑短路, `selectedValue !== value ` 为true ，但是后面的表达式 为false， 然后`this.__$emit('change', value)`的其他处理函数触发了select事件，看下图的调用栈

```javascript
if (selectedValue !== value || (selectedValue && value && !selectedValue.isSame(value))) {
        this.setState({
          str,
        });
        this.__emit('change', value);
      }
```
onInputChange --> OnCalendarSelect --> setOpen(false) ，导致被panel被关闭，因为对组件库的结构不是很了解，所以也不知道是否分析的正确，期待您的解答。

![onEndInputSelect](https://user-images.githubusercontent.com/15810150/60427514-698dbe80-9c29-11e9-9231-318ee2e040c1.jpg)

**Comment by tangjinzhou** [comment]
ref #865
