### ISSUE TITLE
Table theme controlHeight not work

### ISSUE THREAD

**Issue by pipinet** [vueComponent/ant-design-vue#7011]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac os

### Reproduction link
[https://antdv.com/theme-editor](https://antdv.com/theme-editor)

### Steps to reproduce
在官网的自定义样式配置中，配置table组件的controlHeight,但是不生效

### What is expected?
期待生效

### What is actually happening?
未生效

<img width="1679" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/6096680/fa9f2cc6-6687-414b-bffa-8044d1bf48fc">

**Comment by pipinet** [comment]
<img width="1566" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/6096680/f85ffe70-f6df-4be0-b2f6-be43121071e8">

**Comment by cc-hearts** [comment]
`controlHeight ` 改变的是按钮、输入框等控件的高度,不作用于普通的文本
