### ISSUE TITLE
Table scrolling problem

### ISSUE THREAD

**Issue by doom-9** [vueComponent/ant-design-vue#7016]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
Safari and chrome browser on ios

### Reproduction link
[https://3x.antdv.com/components/table-cn/#components-table-demo-sticky](https://3x.antdv.com/components/table-cn/#components-table-demo-sticky)

### Steps to reproduce
After the table component turns on sticky, when scrolling the table left and right on iOS, the table header will be delayed compared with the table scrolling.

### What is expected?
Header and table scrolling synchronization

### What is actually happening?
Scroll out of sync

**Comment by doom-9** [comment]
有人遇到类似问题吗

**Comment by doom-9** [comment]
+1

**Comment by dhaladitya108** [comment]
yeah, I have been encountering the same issue.
