### ISSUE TITLE
Table 表头分组 被分组的列右侧缺少分割线

### ISSUE THREAD

**Issue by Kuntey** [vueComponent/ant-design-vue#7017]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Ubuntu 22.04.3 LTS、 Edge117.0.2045.35、 Vue3.3.4

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-akg8ay?file=src%2Fcomponents%2FHelloWorld.vue](https://stackblitz.com/edit/vitejs-vite-akg8ay?file=src%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
```js
const columns: TableColumnsType = [
{
title: "Name",
dataIndex: "name",
key: "name",
fixed: "left",
},
{
title: "Company",
children: [
{
title: "Company Address",
dataIndex: "companyAddress",
key: "companyAddress",
},
{
title: "Company Name",
dataIndex: "companyName",
key: "companyName",
},
],
},
{
title: "Gender",
dataIndex: "gender",
key: "gender",
width: 80,
fixed: "right",
},
];
```

### What is expected?
被分组的列右侧有分割线

### What is actually happening?
被分组的列右侧没有分割线

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/34301a2d-4e91-45f3-9b41-b8b3a289400f)
不局限于分割线的话可以在a-table中使用`bordered`属性来解决，antd和antdv官网的表头分组示例取消掉`bordered`都有这个问题，最右侧没有分割线，应该是样式判断或者表头分组没有考虑到不使用边框的情形？
