### ISSUE TITLE
Textarea AutoComplete wrapped when selecting options by the Enter key

### ISSUE THREAD

**Issue by hmilin** [vueComponent/ant-design-vue#7018]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
Windows, Chrome latest,  Vue latest

### Reproduction link
[https://antdv.com/components/auto-complete#components-auto-complete-demo-custom](https://antdv.com/components/auto-complete#components-auto-complete-demo-custom)

### Steps to reproduce
1. type any character
2. select any option and press the enter key

### What is expected?
should not wrapped.
Similar to Antd:  https://ant.design/~demos/auto-complete-demo-custom

### What is actually happening?
wrapped when selecting options by the Enter key

**Comment by selicens** [comment]
```js
  <a-auto-complete
    v-model:value="value"
    :options="options"
    style="width: 200px"
    @search="handleSearch"
    @select="onSelect"
  >
    <a-textarea
      placeholder="input here"
      class="custom"
      style="height: 50px"
      @keypress="handleKeyPress"
      @press-enter="e => e.preventDefault()"
    />
  </a-auto-complete>
```
增加一行@press-enter="e => e.preventDefault()"即可解决

**Comment by hmilin** [comment]
> ```js
>   <a-auto-complete
>     v-model:value="value"
>     :options="options"
>     style="width: 200px"
>     @search="handleSearch"
>     @select="onSelect"
>   >
>     <a-textarea
>       placeholder="input here"
>       class="custom"
>       style="height: 50px"
>       @keypress="handleKeyPress"
>       @press-enter="e => e.preventDefault()"
>     />
>   </a-auto-complete>
> ```
> 
> 增加一行`@press-enter="e => e.preventDefault()"`即可解决

会导致textarea本身的换行功能用不了

**Comment by kovsu** [comment]
2.x 没有问题 3.x 版本开始有这个问题
> 😫 找半天没找到到底是哪里的问题

**Comment by DesignHhuang** [comment]
这个组件逻辑上是没有问题的，原理上你敲了回车，textarea上会切换到第二行，然后下面options中也会更新加上```enter```(也就是空格，类似下图)
![image](https://github.com/vueComponent/ant-design-vue/assets/3368397/3353f3b9-3a6a-4973-82e4-675d2e162bd7)
然后在你选择的时候，如果有回车的option(再options中其实是空车)被选中的话，回填到textarea中的时候会带上回车（也就是空行）的。
如果不允许空格输入的话，就使用 @hmilin 的方式就可以了。
@kovsu 2.x 没有问题是因为不能再textarea中是不能输入enter的，所以options中也不会存在空格。

**Comment by kovsu** [comment]
我觉得不合理。有这个选择框的时候，按回车就应该只有选择而不是还有一个输入。🤔

**Comment by DesignHhuang** [comment]
> 我觉得不合理。有这个选择框的时候，按回车就应该只有选择而不是还有一个输入。🤔

如果是这个逻辑的话， @selicens 的方式就可以处理这个问题

**Comment by DesignHhuang** [comment]
> > 我觉得不合理。有这个选择框的时候，按回车就应该只有选择而不是还有一个输入。🤔
> 
> 如果是这个逻辑的话， @selicens 的方式就可以处理这个问题

目前的设计没有办法判断按enter是输入还是选择吧，可以在select的open为true时，取消textarea的聚焦（也就是不让输入）。但是好像取消聚焦的话，select的open会变为false...

**Comment by kovsu** [comment]
我看了一下 antd，它的实现是没有问题的。

**Comment by kovsu** [comment]
先放着吧，一时半会儿也解决不了 😵‍💫

**Comment by Hakityc** [comment]
这个问题依然存在，目前有什么解决方法吗？

**Comment by Hakityc** [comment]
![Clipchamp制作](https://github.com/user-attachments/assets/3e181f2f-fa24-44c6-b370-e20256fe41a3)
可以看到，即使补全未展示时，按下回车也会选中第一项数据
