### ISSUE TITLE
在nuxt3中使用ant design vue4, 我使用任何组件的时候都是, 在刷新页面的时候, 样式会丢失, 刷新完成之后就变正常了, 这个是怎么回事呢, 我使用ant-design-vue-nuxt也是同样的效果

### ISSUE THREAD

**Issue by wolfDown** [vueComponent/ant-design-vue#7022]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
nuxt3

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
我在nuxt3中测试了, ant-design-vue-nuxt安装方式, 和普通的antd安装方式, 都会出现刷新页面样式没有了, 然后刷新成功以后样式就出来了

### What is expected?
刷新的时候样式不丢失

### What is actually happening?
任何组件都是, 在刷新页面样式没有了, 然后刷新成功以后样式就出来了

**Comment by aibayanyu20** [comment]
duplicate https://github.com/vueComponent/ant-design-vue-nuxt/issues/18

**Comment by 1than** [comment]
我也有碰到这个问题 不知道怎么解决哦，请问你有找到解决方法吗
