### ISSUE TITLE
在节点数量较多的情况下页面很卡

### ISSUE THREAD

**Issue by liujiayii** [vueComponent/ant-design-vue#7023]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.1

### Environment
ant-design-vue:4.0.3;vue:3.3.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/an-niu-lei-xing-ant-design-vue-4-0-3-forked-5t8v4v?file=/src/demo.vue)

### Steps to reproduce
vue版本demo：https://codesandbox.io/s/an-niu-lei-xing-ant-design-vue-4-0-3-forked-5t8v4v?file=/src/demo.vue
React版本demo：https://codesandbox.io/s/wandering-platform-yz9p82?file=/src/App.js
element-plus版本demo：[点我](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInZpc2libGU9IXZpc2libGVcIj7ngrnmiJE8L2VsLWJ1dHRvbj5cbiAgPC9lbC1yb3c+XG5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIiA+XG4gICAgPHVsIHYtaWY9XCJ2aXNpYmxlXCI+XG4gICAgICA8bGkgdi1mb3I9XCJpdGVtIG9mIDEwMDBcIiA6a2V5PVwiaXRlbVwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHBsYWluID5QbGFpbjwvZWwtYnV0dG9uPjwvbGk+XG4gICAgPC91bD5cbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtyZWZ9ZnJvbSAndnVlJztcbmNvbnN0IHZpc2libGUgPSByZWYoZmFsc2UpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### What is expected?
页面渲染快

### What is actually happening?
页面渲染很慢

**Comment by fts11259375** [comment]
从4.0.3开始就这样了，4.0.4还是没有改善，我现在项目都锁定使用4.0.2版本

**Comment by liujiayii** [comment]
> 从4.0.3开始就这样了，4.0.4还是没有改善，我现在项目都锁定使用4.0.2版本

赞👍，回滚到了4.0.2确实好了很多

**Comment by fts11259375** [comment]
> > 从4.0.3开始就这样了，4.0.4还是没有改善，我现在项目都锁定使用4.0.2版本
> 
> 赞👍，回滚到了4.0.2确实好了很多

但也治标不治本啊，希望开发者能早点注意到这个问题吧……

**Comment by aibayanyu20** [comment]
在看了

> > > 从4.0.3开始就这样了，4.0.4还是没有改善，我现在项目都锁定使用4.0.2版本
> > 
> > 
> > 赞👍，回滚到了4.0.2确实好了很多
> 
> 但也治标不治本啊，希望开发者能早点注意到这个问题吧……
