### ISSUE TITLE
[Bug report][Segmented] Loss of transition animation during fast switching 分段控制器快速切换时丢失过渡动效

### ISSUE THREAD

**Issue by Cheerwhy** [vueComponent/ant-design-vue#7027]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.4

### Environment
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

### Reproduction link
[https://www.antdv.com/components/segmented-cn](https://www.antdv.com/components/segmented-cn)

### Steps to reproduce
快速点击切换，会发现切换前的过渡消失

### What is expected?
动效正常

### What is actually happening?
动效不正常

**Comment by DesignHhuang** [comment]
提供一下复现代码，也有可能太快了，你没有看出来效果
