### ISSUE TITLE
4.x版本的Modal和Popover性能奇差无比！！！

### ISSUE THREAD

**Issue by tetap** [vueComponent/ant-design-vue#7028]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.4

### Environment
"vue": "^3.3.4",

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
在Modal和Popover中嵌套FormItem Select Input打开速度无比的慢，非常的慢，非常的卡！！！

### What is expected?
在Modal和Popover中嵌套FormItem Select Input打开速度无比的慢，非常的慢，非常的卡！！！

### What is actually happening?
在Modal和Popover中嵌套FormItem Select Input打开速度无比的慢，非常的慢，非常的卡！！！

**Comment by tetap** [comment]
有可能是Form的问题，目前也排查不出来什么，大概率就是渲染的时候做了什么耗时操作！

**Comment by tetap** [comment]
赶紧退回了3.X。还好改动不大，不然就GG了

**Comment by aibayanyu20** [comment]
有没有一个完整的例子，我们跑一下看看

**Comment by likui628** [comment]
没有复现demo，只有情绪化的语言，无效的issue

**Comment by tetap** [comment]
> 没有复现demo，只有情绪化的语言，无效的issue

demo

https://codesandbox.io/embed/zi-ding-yi-zi-duan-ant-design-vue-4-0-3-forked-tmnwhf?fontsize=14&hidenavigation=1&theme=dark

**Comment by tetap** [comment]
> 有没有一个完整的例子，我们跑一下看看

https://codesandbox.io/embed/zi-ding-yi-zi-duan-ant-design-vue-4-0-3-forked-tmnwhf?fontsize=14&hidenavigation=1&theme=dark

**Comment by tetap** [comment]
就把modal和form两个例子放一起 就立马能感受出来了。

**Comment by tetap** [comment]
https://github.com/vueComponent/ant-design-vue/issues/6996

这个issues也是类似的问题，不过说无法复现被关闭了，他只在关闭的时候卡顿。实际上打开和关闭都卡顿，只是官网的例子过于简单

**Comment by aibayanyu20** [comment]
modal确实存在问题，感谢反馈

> #6996
> 
> 这个issues也是类似的问题，不过说无法复现被关闭了，他只在关闭的时候卡顿。实际上打开和关闭都卡顿，只是官网的例子过于简单

**Comment by tangjinzhou** [comment]
4.0.5 试试

**Comment by tetap** [comment]
> 4.0.5 试试

似乎好了，应该是css in js的问题
