### ISSUE TITLE
a-select dropdownVisibleChange事件监听不到了

### ISSUE THREAD

**Issue by rex-ll** [vueComponent/ant-design-vue#7031]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.4

### Environment
win11 chrome 118 Vue 3.2

### Reproduction link
[https://www.antdv.com/components/select-cn#api](https://www.antdv.com/components/select-cn#api)

### Steps to reproduce
none

### What is expected?
正常监听dropdownVisibleChange事件

### What is actually happening?
监听dropdownVisibleChange事件无效

**Comment by rex-ll** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/25000285/3b48d988-4ebd-463f-8f80-232764e3c7a9)
感觉是这个修改导致的，但没轻易下定论

**Comment by selicens** [comment]
emm...

**Comment by aibayanyu20** [comment]
update v4.0.6
