### ISSUE TITLE
a-form中使用a-upload，设置openFileDialogOnClick为false，点击label会打开文件选择器

### ISSUE THREAD

**Issue by 821917380** [vueComponent/ant-design-vue#704]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Win10, Google Chrome 73.0.3683.103, Vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/w6j2rl6x8l)

### Steps to reproduce
1. 打开链接：https://codesandbox.io/embed/w6j2rl6x8l
2. 可以看到App.vue中的代码，已将openFileDialogOnClick属性设置为false
3. 点击label（图片），会打开文件选择器，而点击upload则不会

### What is expected?
如果设置openFileDialogOnClick为false，点击label（图片），不应该会打开文件选择器

### What is actually happening?
当设置openFileDialogOnClick为false时，点击label（图片），会打开文件选择器，而点击upload则不会

**Comment by tangjinzhou** [comment]
你可以给form-item随意设置一个id，取消label和input的关联即可
https://codesandbox.io/embed/w6j2rl6x8l

**Comment by 821917380** [comment]
> 你可以给form-item随意设置一个id，取消label和input的关联即可
> https://codesandbox.io/embed/w6j2rl6x8l

不对，我认为这是一个bug，如果按照随意设置id的逻辑，虽然可以解决问题，但是当设置openFileDialogOnClick为true时，也会产生问题的啊，当设置这个属性为true时，点击label应该给予相应
