### ISSUE TITLE
轮播图的多页展示，如何设置间距

### ISSUE THREAD

**Issue by keqingf** [vueComponent/ant-design-vue#7040]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
走马灯在slidesToShow设置这个参数的时候，如何设置间距

**Comment by kovsu** [comment]
<img width="500px" src="https://github.com/vueComponent/ant-design-vue/assets/82451257/6dc8c231-0f42-4450-abd2-a76e075ac86b" />

**Comment by keqingf** [comment]
> <img alt="" width="500px" src="https://user-images.githubusercontent.com/82451257/276788739-6dc8c231-0f42-4450-abd2-a76e075ac86b.png">

这个设置显示数量，假如显示3个图，3个图直接我想要间距，需要怎么书写
或者说ant-design-vue不支持
我使用其他插件比如Swiper

**Comment by kovsu** [comment]
我看了一眼，没有找到 🫠

**Comment by Fallsleep** [comment]
简单试了一下，用`css`应该就能解决了吧，在线的例子https://codesandbox.io/s/ji-ben-ant-design-vue-4-0-6-forked-pk64qn?file=/src/demo.vue
```vue
<template>
  <div>
    <a-carousel :slidesToShow="4">
      <div><h3>1</h3></div>
      <div><h3>2</h3></div>
      <div><h3>3</h3></div>
      <div><h3>4</h3></div>
    </a-carousel>
  </div>
</template>

<style scoped>
:deep(.slick-slide > div){
  margin: 0 20px;
  border: 1px solid red;
  background-color: green;
}
</style>
```

**Comment by kovsu** [comment]
nice job，那我关闭这个 issue 了
