### ISSUE TITLE
我是一个v1的版本使用者，我想文档升级版本到v4最新版本或者v3版本，但是现在社区的文档只有支持v1-v2-v3-v4的升级文档

### ISSUE THREAD

**Issue by zcx992132258** [vueComponent/ant-design-vue#7041]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
因为v2版本在官方文档上面是一个不被推荐的版本，一般都会直接升级到v3版本但是v3版本没有直接升级文档引导，会导致升级带来很多困难。

### What does the proposed API look like?
文档

**Comment by Charlie500** [comment]
可以一层层升上去试试，工作量确实也挺大

**Comment by zcx992132258** [comment]
> 可以在一层升上去尝试，工作量确实也挺大，或者你可以把文档读完，知道哪些组件，考古修复

是可以这样，我就是想知道v2版本有没有很严重的bug问题存在 他不被推荐的原因是什么

**Comment by aibayanyu20** [comment]
v1直升v3，同时看v2和v3的文档 v2和v3的改动大部分是在vue2的书写方式改成vue3的书写方式并没有太大的改动
