### ISSUE TITLE
a-space中切换显示时报警告重复key

### ISSUE THREAD

**Issue by npmrun** [vueComponent/ant-design-vue#7045]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
vue: 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-vue-4-0-6-hk9hxv)

### Steps to reproduce
多次点击切换即可看到控制台的警告逐渐增加

### What is expected?
不报警告

### What is actually happening?
a-space中切换显示时报警告重复key

**Comment by tetap** [comment]
啥时候发布解决？

**Comment by tetap** [comment]
@alirezavalizade @tangjinzhou
