### ISSUE TITLE
IE9原生报错    [Vue warn]: Error in beforeDestroy hook: "TypeError: 对象不支持“remove”属性或方法"

### ISSUE THREAD

**Issue by YingZzz** [vueComponent/ant-design-vue#705]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
vue

### Reproduction link
![image](https://user-images.githubusercontent.com/41365103/56253980-5de22f80-60f1-11e9-812e-213d8014d8d2.png)

### Steps to reproduce
开发时是好的,打包后会出现这个报错

### What is expected?
可以解决

### What is actually happening?
可以解决

### 然后全局定义pagination,分页组件触发这个属性的时候 IE全报错
也是报上图的错误
![image](https://user-images.githubusercontent.com/41365103/56253949-4440e800-60f1-11e9-9fd3-5ecc3cd9b589.png)
![image](https://user-images.githubusercontent.com/41365103/56253958-49059c00-60f1-11e9-9451-386c3de88184.png)

**Comment by YingZzz** [comment]
### 当我在组件内部使用select的时候,ie9也会报这个错
### 这个错,是我在modal里使用select组件,选中后,点击取消或者保存弹窗,会报对象不支持remove

![image](https://user-images.githubusercontent.com/41365103/56255298-fcbd5a80-60f6-11e9-9864-7fbacc04c094.png)

![image](https://user-images.githubusercontent.com/41365103/56255314-0777ef80-60f7-11e9-8f7e-0173b41afdc5.png)

**Comment by tangjinzhou** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/ChildNode/remove#Polyfill

**Comment by YingZzz** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/API/ChildNode/remove#Polyfill

非常感谢大佬,可以!!
