### ISSUE TITLE
cascader级联选择异步请求option设置value显示空白 。

### ISSUE THREAD

**Issue by yuyalong0629** [vueComponent/ant-design-vue#706]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
设置:value="['xxx']"页面input显示空白 。

### What does the proposed API look like?
vue: 2.6   os: 10.14  chrome: 73

**Comment by yuyalong0629** [comment]
![image](https://user-images.githubusercontent.com/37603495/56259646-57aa7e00-6106-11e9-95b9-56a83b3ff114.png)
![image](https://user-images.githubusercontent.com/37603495/56259662-65f89a00-6106-11e9-9b9f-052c2f60e242.png)

**Comment by yuyalong0629** [comment]
![image](https://user-images.githubusercontent.com/37603495/56259741-bc65d880-6106-11e9-95c3-065c178bb0f0.png)
options正常使用，就是设置默认值空白 ，select同样的方式也是可用的 。

**Comment by JCqiu** [comment]
@yuyalong0629 你如果是用表单的方式就不用设置默认值了，直接用表单的setFieldsValue方法
![image](https://user-images.githubusercontent.com/16211027/56405407-aab73900-629e-11e9-9575-aea9fabfb105.png)
![image](https://user-images.githubusercontent.com/16211027/56405418-b571ce00-629e-11e9-8b69-5d0ba5e114f5.png)
