### ISSUE TITLE
feat  关于Image预览操作栏

### ISSUE THREAD

**Issue by MinMr** [vueComponent/ant-design-vue#7068]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
下个版本发布Image的预览的操作栏能否同步到ant-design-react的最新版本，react最新版本的image组件预览操作栏体验怪好的呢

### What does the proposed API look like?
下个版本发布Image的预览的操作栏能否同步到ant-design-react的最新版本，react最新版本的image组件预览操作栏体验怪好的呢

**Comment by selicens** [comment]
可以同步下

**Comment by selicens** [comment]
其实也有了只是在右上角

**Comment by MinMr** [comment]
> 其实也有了只是在右上角

首先感谢大佬回复，一点小小改动，好用好多，甚至我觉得关闭按钮要是都弄到操作按钮上就好了

**Comment by wsxe9988** [comment]
对比 ant-design 5.x最新，目前Image组件文档 API上就少了很多

**Comment by selicens** [comment]
> 对比 ant-design 5.x最新，目前Image组件文档 API上就少了很多

在做了

**Comment by Mkr419** [comment]
有空能把Image组件同步成react版本的吗，或者vue版本的如何能自定义工具栏？
