### ISSUE TITLE
官网4.0版本在360极速浏览器32位版本出现样式错误

### ISSUE THREAD

**Issue by playerzzz** [vueComponent/ant-design-vue#7071]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
360极速浏览器32位版本；

### Reproduction link
[https://www.antdv.com/components/icon](https://www.antdv.com/components/icon)

### Steps to reproduce
1.下载360极速浏览器32位版本
2.输入网址     https://www.antdv.com/components/icon

### What is expected?
期望能适配一下，感谢

### What is actually happening?
下载360极速浏览器32位版本，输入网址https://www.antdv.com/components/icon

**Comment by playerzzz** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/89131614/07ed446b-8690-4958-ae65-9dc53c4f1ee4)

**Comment by bing127** [comment]
我也是同样的问题
