### ISSUE TITLE
修改 a-config-provider  的 prefixCls props，a-collapse 展开/折叠动画消失

### ISSUE THREAD

**Issue by lfzs** [vueComponent/ant-design-vue#7073]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
macOS Monterey 12.0.1 / Chrome 版本 118.0.5993.117（正式版本） (x86_64) / Vue 3.3.7

### Reproduction link
[https://github.com/lfzs/antdv-vite-prefix-bug](https://github.com/lfzs/antdv-vite-prefix-bug)

### Steps to reproduce
[步骤](https://github.com/lfzs/antdv-vite-prefix-bug#readme)

### What is expected?
修改 a-config-provider  的 prefixCls，a-collapse 展开/折叠动画正常

### What is actually happening?
a-collapse 展开/折叠动画消失

**Comment by lfzs** [comment]
v4.0.7 验证，menu 组件的展开/折叠有同样的问题 @kovsu

**Comment by kovsu** [comment]
@lfzs 好的 我看看 😀
