### ISSUE TITLE
多选下拉框不显示箭头图标，偶尔显示字符Â 

### ISSUE THREAD

**Issue by x-wink** [vueComponent/ant-design-vue#7079]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.13

### Environment
windows 10，chrome118.0.5993.118，vue3.2.47

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/main/components/select/style/multiple.ts](https://github.com/vueComponent/ant-design-vue/blob/main/components/select/style/multiple.ts)

### Steps to reproduce
https://github.com/vueComponent/ant-design-vue/blob/main/components/select/style/multiple.ts line75定义的这个字符

### What is expected?
建议显示箭头图标，或者保持什么都不显示

### What is actually happening?
显示字符Â ，并且撑高了下拉框

![企业微信截图_16989196258313](https://github.com/vueComponent/ant-design-vue/assets/133745023/eef8a862-f797-4132-ae0d-6be3edd4433a)

**Comment by yyycc** [comment]
有解决方案么？
我也遇到了这个情况，但无法稳定复现，正常的时候像图上这样是'\a0'，并不是Â。
![image](https://github.com/vueComponent/ant-design-vue/assets/36940774/b72f438d-9f45-4e78-b97e-3c1606f7f364)

**Comment by x-wink** [comment]
> 有解决方案么？ 我也遇到了这个情况，但无法稳定复现，正常的时候像图上这样是'\a0'，并不是Â。 ![image](https://private-user-images.githubusercontent.com/36940774/285712468-b72f438d-9f45-4e78-b97e-3c1606f7f364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNTc4MzYsIm5iZiI6MTcwMTA1NzUzNiwicGF0aCI6Ii8zNjk0MDc3NC8yODU3MTI0NjgtYjcyZjQzOGQtOWY0NS00ZTc4LWI5N2UtM2MxNjA2ZjdmMzY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDAzNTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZDczNDk3Nzg5NTRmYjllYjMzMDIxZGNkMWZmYTg4MDg2YzQ0MTRjNmM4ZTdjOTczNGQ1NGM0YjFjM2Q1MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B0NptHf2jEDG2SppBNEAa920CnoPQzqXWSGAAdyyGRw)

俺也一样 正常是\a0，这个是表示转义后的空格应该就是为了出现乱码才这么写的。
感觉好像是浏览器的BUG，因为控制台是浏览器层面的了，这里显示都是乱码应该更组件库没太大关系
解决方案是说服测试，说这个组件库BUG不是我写的BUG哈哈哈

**Comment by polikesen123** [comment]
俺们也遇到了乱码的问题，求解决思路🙏

**Comment by SublimeCT** [comment]
在 `nginx` 中配置一下 css 文件的 charset:

```bash
server {
    charset utf-8;
    # ...

    location / {
        # ...

        # 设置 css 文件的字符集
        if ($request_filename ~* .*\.css$) {
          add_header Content-Type "text/css; charset=UTF-8";
        }

    }
}
```
