### ISSUE TITLE
有没有类似ngZorro的Cascader可以默认值与延迟加载

### ISSUE THREAD

**Issue by JCqiu** [vueComponent/ant-design-vue#708]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
https://ng.ant.design/components/cascader/zh#components-cascader-demo-default-value-and-lazyload

### What does the proposed API look like?
可以延迟加载

**Comment by tangjinzhou** [comment]
没有独立的api
可以参考这个demo https://vue.ant.design/components/select-cn/#components-select-demo-search-and-select-users

**Comment by JCqiu** [comment]
@tangjinzhou 好像适合我的应用场景Cascader 我用作省市区的联级选择器，我通过表单默认设置了省市区的key，但是Cascader 只默认显示了省，并没自动去根据省的key发起请求并获取市的子级

**Comment by hilads** [comment]
> @tangjinzhou 好像不适合我的应用场景Cascader 我用作省市区的联级选择器，我通过表单默认设置了省市区的key，但是Cascader 只根据省的key默认显示了省名，并没自动去根据省的key发起请求并获取市的子级

你好 我也遇到了相同 问题 请问 你解决了？

**Comment by hilads** [comment]
我设置的是 动态加载 但是页面回显的时候 设置回显值  只显示 省的值 调用动态加载函数 也没效果

**Comment by JCqiu** [comment]
@hilads 没有，现在我暂时没解决，我的是默认获取省，只有根据市和区的id去调用一次，然后在吧数据赋值上去

**Comment by hilads** [comment]
@JCqiu  所以 你现在可以设置默认显示了？ 就是效果 是这样的

![image](https://user-images.githubusercontent.com/46804595/57432530-b88e2780-7268-11e9-9b48-1a21cb2f5dd4.png)

**Comment by JCqiu** [comment]
@hilads 暂时没有呢

**Comment by kid1412621** [comment]
同遇到了，但发现没有 API 支持，就用 placeholder 来 workaround

**Comment by JasonSubMara** [comment]
> 同遇到了，但发现没有 API 支持，就用 placeholder 来 workaround

额，这样子的话是怎么做的？编辑信息这种需求，岂不是没有选中的值了
