### ISSUE TITLE
[form-item] component 'label' 属性优先级高于 slots.label 插槽，这是不是搞反了

### ISSUE THREAD

**Issue by Zheng-Changfu** [vueComponent/ant-design-vue#7080]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
any

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
any

### What is expected?
any

### What is actually happening?
any

**Comment by kovsu** [comment]
都是属性优先
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/ce29756b-34d0-4f09-a323-5fc97896b8aa)

**Comment by Zheng-Changfu** [comment]
好的，之前使用 naive-ui ，发现是插槽优先，谢谢答疑
