### ISSUE TITLE
表格组件的非固定列表头在chrome浏览器有时候会消失

### ISSUE THREAD

**Issue by 1291927234** [vueComponent/ant-design-vue#7081]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
chrome 版本 118.0.5993.120（正式版本） （64 位）

### Reproduction link
[https://1x.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header](https://1x.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header)

### Steps to reproduce
1.打开上述官网demo，固定头和列的表格
2.鼠标移入表格行，上下慢速滑动、或者慢速滚动纵轴滚动条，或者打开开发者调试工具后进行上述操作，
3.出现非固定列的表头会消失的情况，在表格被重绘后又恢复正常

### What is expected?
预期表格展示正常，但是出现了非固定列的表头展示空白的情况

### What is actually happening?
打开开发者调试工具后 经常出现，不打开时复现频率相对低一些

**Comment by ghsssss** [comment]
我也遇到了，无法解决

**Comment by ghsssss** [comment]
我也遇到这个问题

**Comment by ghsssss** [comment]
@1291927234 请问有解决方案吗

**Comment by 1291927234** [comment]
升级下chrome版本试试，我现在没遇到了，感觉像是特定chrome版本下的渲染有点问题



---原始邮件---
发件人: "Jony ***@***.***&gt;
发送时间: 2024年1月24日(周三) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vueComponent/ant-design-vue] 表格组件的非固定列表头在chrome浏览器有时候会消失 (Issue #7081)




 
@1291927234 请问有解决方案吗

**Comment by ghsssss** [comment]
不行，我chrome和edge均是最新版，问题一直存在 @1291927234

**Comment by 1291927234** [comment]
这个我确实不晓得了，我最近没遇到过了，之前也是一直有问题



---原始邮件---
发件人: "Jony ***@***.***&gt;
发送时间: 2024年1月24日(周三) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vueComponent/ant-design-vue] 表格组件的非固定列表头在chrome浏览器有时候会消失 (Issue #7081)




 
不行，我chrome和edge均是最新版，问题一直存在 @1291927234

**Comment by 1291927234** [comment]
好像是它自己好的，我更新过chrome版本，具体我也不知道啥问题。。



---原始邮件---
发件人: "Jony ***@***.***&gt;
发送时间: 2024年1月24日(周三) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vueComponent/ant-design-vue] 表格组件的非固定列表头在chrome浏览器有时候会消失 (Issue #7081)




 
不行，我chrome和edge均是最新版，问题一直存在 @1291927234

**Comment by ghsssss** [comment]
@1291927234 唉，继续寻找解决办法

**Comment by 1291927234** [comment]
官方好像没人理我，哈哈哈



---原始邮件---
发件人: "Jony ***@***.***&gt;
发送时间: 2024年1月24日(周三) 下午5:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vueComponent/ant-design-vue] 表格组件的非固定列表头在chrome浏览器有时候会消失 (Issue #7081)




 
@1291927234 唉，继续寻找解决办法
