### ISSUE TITLE
App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！

### ISSUE THREAD

**Issue by kuishou68** [vueComponent/ant-design-vue#7085]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！

### Reproduction link
[https://www.antdv.com/components/app-cn](https://www.antdv.com/components/app-cn)

### Steps to reproduce
App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！

### What is expected?
App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！

### What is actually happening?
App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！

**Comment by selicens** [comment]
emmm，有什么问题可以正常反馈

**Comment by selicens** [comment]
这个组件比较特殊，没法在一个demo里把代码全部展现出来

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/7638a015-3d9b-496d-9538-3a452d7c8f8b)
这个是myPage组件的内容，这个组件需要被App包裹，myPage中才能引入App通过App.use()正确获取到message、modal、notification等

**Comment by kuishou68** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！ (Issue #7085)





 

 这个是myPage组件的内容，这个组件需要被App包裹，myPage中才能引入App通过App.use()正确获取到message、modal、notification等
 
—

如果我要做个公共的 message 提示，应该怎么做？不觉得每个需要提示的组件都包裹一层很冗余嘛？

**Comment by selicens** [comment]
```
<a-app>
  <my-page />
</a-app>
```
myPage组件需要借助a-app通过provide/inject将数据传递下去，不使用a-app包裹的话，App.use无法生效，你可以在最外层使用包裹组件。子孙组件任意一层通过以下方式使用
```
import { App } from 'ant-design-vue';
const { message, modal, notification } = App.useApp();
```

**Comment by kuishou68** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "vueComponent/ant-design-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 下午5:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue] App 包裹组件 文档写的稀里糊涂，配置代码上下文关联不上，狗屎！ (Issue #7085)





 <a-app&gt;   <my-page /&gt; </a-app&gt;  
myPage组件需要借助a-app通过provide/inject将数据传递下去，不使用a-app包裹的话，App.use无法生效，你可以在最外层使用包裹组件。子孙组件任意一层通过以下方式使用
 import { App } from 'ant-design-vue'; const { message, modal, notification } = App.useApp();  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;




就不能像 1.7.8 版本一样，作为全局调用message；必须包裹一层，每次需要提示的时候都要引入一下该组件？

**Comment by aibayanyu20** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/45655660/2a976510-09b0-46e5-8167-9f3bb1fe00a8)

两种方式都支持，文档中有写

**Comment by selicens** [comment]
message可以单独使用，不是强制绑定的，这个组件主要解决的是hooks调用message、modal、notification时需要单独写一个context-holder的痛点和一些小问题
