### ISSUE TITLE
spin包裹Modal容器使用问题

### ISSUE THREAD

**Issue by liuhui-netizen** [vueComponent/ant-design-vue#7086]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
win10，Google Chrome， "vue": "^3.3.4",，"ant-design-vue": "^4.0.6",

### Reproduction link
[https://www.antdv.com/components/spin-cn](https://www.antdv.com/components/spin-cn)

### Steps to reproduce
```
<a-modal v-model:open="createConnVisible" :maskClosable="false" title="新建连接(MySQL)" centered>
            <a-spin>
                <a-tabs v-model:activeKey="activeKey">
                    <a-tab-pane key="1" tab="常规">
                    </a-tab-pane>
                    <a-tab-pane key="2" tab="高级" force-render>
                    </a-tab-pane>
                </a-tabs>
                <template #footer>
                    <a-row>
                        <a-col :span="8">
                            <a-button type="primary" @click="checkFormRulesVailedAtConnMySQL(false)">测试连接</a-button>
                        </a-col>
                        <a-col :span="7" :offset="9">
                            <a-button key="submit" type="primary"
                                @click="checkFormRulesVailedAtConnMySQL(true)">确认</a-button>
                            <a-button key="back" @click="handleTopEvent">取消</a-button>
                        </a-col>
                    </a-row>

                </template>
            </a-spin>
        </a-modal>

```

### What is expected?
a-modal中使用 a-spin；希望能够给a-modal容器覆盖 展示一个加载框。

### What is actually happening?
在a-modal中使用a-spin; 会导致 <template #footer>插槽失效 变成默认的Close,Ok两个按钮。插槽内按钮被替换；官网文档使用默认按钮隐藏就都是隐藏状态。使用 :footer 显示也没用。不用a-spin情况下是正常的

**Comment by liuhui-netizen** [comment]
使用spin
![image](https://github.com/vueComponent/ant-design-vue/assets/68626860/f68d8ad6-4b79-45ca-9de2-235be36ec389)

不使用
![image](https://github.com/vueComponent/ant-design-vue/assets/68626860/5ed7984f-655b-4c92-9475-06fc9301c9fa)

**Comment by liuhui-netizen** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> undefined
> 
> ### Environment
> win10，Google Chrome， "vue": "^3.3.4",，"ant-design-vue": "^4.0.6",
> 
> ### Reproduction link
> https://www.antdv.com/components/spin-cn
> 
> ### Steps to reproduce
> <a-modal v-model:open="createConnVisible" :maskClosable="false" title="新建连接(MySQL)" centered>
            <a-tabs v-model:activeKey="activeKey">
                <a-tab-pane key="1" tab="常规">
                    <a-form ref="formRef" :model="formState" name="basic" :label-col="{ style: { width: '70px' } }">
                        <a-form-item label="连接名" name="name" :rules="[{ required: true, message: '请输入连接名' }]">
                            <a-input v-model:value="formState.name" :maxlength=16 />
                        </a-form-item>
                        <a-form-item label="主机" name="host" :rules="[{ required: true, message: '请输入主机' }]">
                            <a-input v-model:value="formState.host" />
                        </a-form-item>
                        <a-form-item label="端口" name="port" :rules="[{ required: true, message: '请输入端口' }]">
                            <a-input v-model:value="formState.port" :maxlength="5" />
                        </a-form-item>
                        <a-form-item label="用户名" name="user" :rules="[{ required: true, message: '请输入用户名' }]">
                            <a-input v-model:value="formState.user" />
                        </a-form-item>

                        <a-form-item label="密码" name="password" :rules="[{ required: true, message: '请输入密码' }]">
                            <a-input-password v-model:value="formState.password" :visibilityToggle="false" />
                        </a-form-item>

                        <a-form-item name="remember" :wrapper-col="{ offset: 4 }">
                            <a-checkbox v-model:checked="formState.remember">保存密码</a-checkbox>
                        </a-form-item>
                    </a-form>

                </a-tab-pane>
                <a-tab-pane key="2" tab="高级" force-render>

                </a-tab-pane>
            </a-tabs>


            <template #footer>
                <a-row>
                    <a-col :span="8">
                        <a-button type="primary" @click="checkFormRulesVailedAtConnMySQL(false)">测试连接</a-button>
                    </a-col>
                    <a-col :span="7" :offset="9">
                        <a-button key="submit" type="primary" @click="checkFormRulesVailedAtConnMySQL(true)">确认</a-button>
                        <a-button key="back" @click="handleTopEvent">取消</a-button>
                    </a-col>
                </a-row>

            </template>
        </a-modal>


> ### What is expected?
> a-modal中使用 a-spin；希望能够给a-modal容器覆盖 展示一个加载框。
> 
> ### What is actually happening?
> 在a-modal中使用a-spin; 会导致 <template #footer>插槽失效 变成默认的Close,Ok两个按钮。插槽内按钮被替换；官网文档使用默认按钮隐藏就都是隐藏状态。使用 :footer 显示也没用。不用a-spin情况下是正常的

**Comment by aibayanyu20** [comment]
```vue
<a-modal v-model:open="createConnVisible" :maskClosable="false" title="新建连接(MySQL)" centered>
            <a-spin>
                <a-tabs v-model:activeKey="activeKey">
                    <a-tab-pane key="1" tab="常规">
                    </a-tab-pane>
                    <a-tab-pane key="2" tab="高级" force-render>
                    </a-tab-pane>
                </a-tabs>
            </a-spin>
<template #footer>
                    <a-row>
                        <a-col :span="8">
                            <a-button type="primary" @click="checkFormRulesVailedAtConnMySQL(false)">测试连接</a-button>
                        </a-col>
                        <a-col :span="7" :offset="9">
                            <a-button key="submit" type="primary"
                                @click="checkFormRulesVailedAtConnMySQL(true)">确认</a-button>
                            <a-button key="back" @click="handleTopEvent">取消</a-button>
                        </a-col>
                    </a-row>

                </template>
        </a-modal>
```

插槽被嵌套在spin中会被认为是spin中的插槽，并不是modal中的插槽，vue机制问题，并不是antdv的问题
