### ISSUE TITLE
使用useForm 时，当没有初始化 field 的时候调用resetFields无法重置field的值

### ISSUE THREAD

**Issue by ctocto** [vueComponent/ant-design-vue#7089]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36, Vue 3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/useform-ji-ben-biao-dan-ant-design-vue-4-0-6-forked-g232w6)

### Steps to reproduce
1. 使用 useForm 运行Form；
2. 定义 form model 时，不定义具体的fields；
3. 在form 控件（如：Input）中输入值；
4. 重置按钮调用 resetFields；

### What is expected?
field 的值被重置为 undefined

### What is actually happening?
field 的值还是输入时候的值

---
使用useForm 的时候，此种情况无法重置fields 的值，但是**使用ref 的方式是可以重置的**。

查看源码发现在useForm  [resetFields](https://github.com/vueComponent/ant-design-vue/blob/242982301d44ac71e1999a3cb896fccd5ec9d5a9/components/form/useForm.ts#L128)中是通过 Object.assign 来对象合并覆盖实现的，所以如果没有定义fields 就不会被覆盖。

而用 ref 的方式时[resetField](https://github.com/vueComponent/ant-design-vue/blob/eae2b5d41268badbaf5ed257f65437b3cf459526/components/form/FormItem.tsx#L303C11-L303C21) 是单个赋值重置的。所以即使没有定义也正好被重置为undefined了。

**Comment by kovsu** [comment]
我想问的是，如果你都没定义这个值的话，这不已经算是一个问题了吗。而且在编译器里面不会报错吗？所以我认为这不是一个需要去修复的问题。
