### ISSUE TITLE
a-menu selectedKeys(v-model) 无法双向绑定，是不是缺陷？

### ISSUE THREAD

**Issue by cxf1112** [vueComponent/ant-design-vue#7092]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.11

### Environment
vue3版本3.3.0

### Reproduction link
[https://3x.antdv.com/components/menu-cn#API](https://3x.antdv.com/components/menu-cn#API)

### Steps to reproduce
<template>
<a-menu v-model:selected-keys="tableSize" >
<a-menu-item key="large">默认</a-menu-item>
<a-menu-item key="middle">中等</a-menu-item>
<a-menu-item key="small">紧凑</a-menu-item>
</a-menu>
</template>
<script setup>
const tableSize = ref([]);
</script>
//描述：v-model:selected-keys 双向绑定无效

### What is expected?
是否缺陷？

### What is actually happening?
v-model:selected-keys 双向绑定无效

**Comment by chua1989** [comment]
same issue for me

**Comment by changweihua** [comment]
same issue for me

**Comment by Delevin888** [comment]
我怀疑了自己10分钟。
