### ISSUE TITLE
image 可预览图片组件，建议支持可以传入图片旋转角度。

### ISSUE THREAD

**Issue by huanganfree** [vueComponent/ant-design-vue#7098]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
有业务场景是，用户点击图片预览，就需要图片旋转到一个最佳角度观看。

### What does the proposed API look like?
例如：组件可以提供rotate prop
<a-image src="https://aliyuncdn.antdv.com/logo.png" :rotate="30"/>

**Comment by kovsu** [comment]
给你推荐你的 https://github.com/huanganfree/image-ipreview 😀

**Comment by huanganfree** [comment]
> 给你推荐你的 https://github.com/huanganfree/image-ipreview 😀

@kovsu 哈哈，还是更喜欢你们ant design的ui风格 😉

**Comment by huanganfree** [comment]
> > 给你推荐你的 https://github.com/huanganfree/image-ipreview 😀
> 
> @kovsu 哈哈，还是更喜欢你们ant design的ui风格 😉

我可以贡献这个pr吗？😀
