### ISSUE TITLE
Changing Locale not work on dayjs

### ISSUE THREAD

**Issue by Djaangoo** [vueComponent/ant-design-vue#7099]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-vue-4-0-6-forked-m4747y?file=/src/demo.vue)

### Steps to reproduce
Go to the link
Try changing locale by clicking top buttons (like in [demo](https://antdv.com/components/config-provider#components-config-provider-demo-locale))

### What is expected?
Changing locale like in [demo](https://antdv.com/components/config-provider#components-config-provider-demo-locale)  work for calendars etc.

### What is actually happening?
Language of the components changed but calendar still have English names of the week

**Comment by cc-hearts** [comment]
hello, for calendar locale switching, you need to import locale resources in advance, e.g. `import 'dayjs/locale/en'`.

Here's my latest modification of the [demo](https://codesandbox.io/s/ant-design-vue-4-0-6-forked-g3p22n?file=/src/main.js) , hope it helps!

**Comment by Djaangoo** [comment]
@cc-hearts okey, thanks but it's not work in Nuxt 3 
any ideas how to fix that? 😅

**Comment by cc-hearts** [comment]
I'll look into it.🤔

**Comment by cc-hearts** [comment]
Sorry, I'm delayed for a long time due to my unfamiliarity with nuxt.Here's how I solve the language switch so far, I hope it will be useful to you

**Comment by cc-hearts** [comment]
In nuxt mode, language switching is an issue I'll follow up on further.

**Comment by cc-hearts** [comment]
Under nuxt, you need to import the packages under `dayjs` in advance for the desired switching language, here is a  [demo](https://codesandbox.io/p/devbox/beautiful-oskar-px89q9?file=%2Fapp.vue%3A1%2C1-84%2C1), hope it helps!

**Comment by Djaangoo** [comment]
Cool, thanks a lot!
