### ISSUE TITLE
【Button】click 事件触发wave组件showWave()方法报错

### ISSUE THREAD

**Issue by puppet-666** [vueComponent/ant-design-vue#7106]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
System:     
OS: Windows 10 10.0.19044     
CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz         
Memory: 2.81 GB / 15.86 GB   

Browsers:     
Edge: Spartan (44.19041.1266.0)
Chromium (119.0.2151.58)     
Internet Explorer: 11.0.19041.1566

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/an-niu-lei-xing-ant-design-vue-4-0-7-forked-xzk7p7)

### Steps to reproduce
- 使用 button 组件
- 点击 button

### What is expected?
- wave inject需要有一个默认值，而不是抛出错误 
- link #7036 
![image](https://github.com/vueComponent/ant-design-vue/assets/45839282/db638cf0-ccf7-4158-ba0e-d5f0719608bb)

### What is actually happening?
- 点击button报错

**Comment by puppet-666** [comment]
另外，这个新的 pr 在 ConfigProvider 中也没有更新文档

**Comment by ramwin** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/17930851/11805691-be02-411e-8157-3cb13725da91)

**Comment by ILiveJava** [comment]
> ![image](https://user-images.githubusercontent.com/17930851/282498822-11805691-be02-411e-8157-3cb13725da91.png)

朋友，你解决了吗？我也遇到了相同的问题，点击button后控制台报错

**Comment by puppet-666** [comment]
> > ![image](https://user-images.githubusercontent.com/17930851/282498822-11805691-be02-411e-8157-3cb13725da91.png)
> 
> 朋友，你解决了吗？我也遇到了相同的问题，点击button后控制台报错

先降级一下，把版本锁定在4.0.6吧，上面的修复pr还没有合并

**Comment by zyxeeker** [comment]
4.0.6依然存在此问题

**Comment by puppet-666** [comment]
> 4.0.6依然存在此问题

可以看下node_modules里面真正安装的版本，4.0.6并没有加上wave配置，应该是不会有这个报错的

**Comment by zyxeeker** [comment]
> > 4.0.6依然存在此问题
> 
> 可以看下node_modules里面真正安装的版本，4.0.6并没有加上wave配置，应该是不会有这个报错的

我检查了下 现在已经可以了 谢谢

**Comment by tetap** [comment]
同样发现了。

**Comment by H-hejin** [comment]
这个问题是由什么导致的呢

**Comment by godtang** [comment]
+1
4.0.7发现这个问题
刚开始学习前端，自我怀疑了好久好久

**Comment by heshine0** [comment]
> > +1 4.0.7发现这个问题 刚开始学习前端，自我怀疑了好久好久
> 
> 哥们我也是，我的版本是也是这个

我也遇到同样的问题

**Comment by luocong2016** [comment]
### 🐛 Bug 描述 Bug description
我在测试案例中发现，由于没有使用 ConfigProvider 包裹，是会报错的。
因为 `config-provider/context.ts` 中的 `defaultConfigProvider` 并没有覆盖到，
`config-provider/hooks/useConfigInject.ts` 中的 `configProvider` 、 `export default 数据`，所以
![image](https://github.com/vueComponent/pro-components/assets/25705196/6f4eb62f-1fb5-4b5b-9fb6-591f840c7323)

本测试案例的报错原因， configProvider.wave 是 undefined
``` 
 const wave = computed<{
    disabled?: boolean;
  }>(() => props.wave ?? configProvider.wave.value); // 这里 configProvider.wave 是 undefined
```

出错案例
```html
<template>
  <Button @click="handleClick">Demo</Button>
</template>

<script setup>
const handleClick = () => {}
</script>
```




### 🏞 期望结果 Desired result

```html
<!-- <ConfigProvider> -->
<div class="container">
  <Button @click="changeData">change data</Button>
</div>
<!-- </ConfigProvider> -->
```
不使用 ConfigProvider 作为全局包裹，组件也能正常使用。目前包装后就可以使用




### 🚑 其他信息 Other information

```
 "vue": "^3.3.8",
 "ant-design-vue": "4.x",
```

![image](https://github.com/vueComponent/pro-components/assets/25705196/202b5c3a-a1a2-46c8-a2d0-575001c9e21d)
