### ISSUE TITLE
Table组件 headerCell 插槽与expandedRowRender插槽一起使用时报错, 无法渲染

### ISSUE THREAD

**Issue by mmmmr** [vueComponent/ant-design-vue#7115]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
4.0.7

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/happy-shadow-wsd7l7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp0x0es70008356jbn207mou%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp0x0es60003356ji9wbna40%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp0x0es70005356j1vhe001n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp0x0es70007356jq12e3gtb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp0x0es60003356ji9wbna40%2522%253A%257B%2522id%2522%253A%2522clp0x0es60003356ji9wbna40%2522%252C%2522activeTabId%2522%253A%2522clp0x4seb012z356j2plswh99%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp0x0es60002356jajxt7rh5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.ts%2522%252C%2522id%2522%253A%2522clp0x37m000dm356jssqq3fwp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522clp0x4seb012z356j2plswh99%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp0x78oi01jw356jzxrnhigs%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clp0x0es70007356jq12e3gtb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp0x0es70006356j58mi32ra%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clp0x0es70007356jq12e3gtb%2522%252C%2522activeTabId%2522%253A%2522clp0x0es70006356j58mi32ra%2522%257D%252C%2522clp0x0es70005356j1vhe001n%2522%253A%257B%2522id%2522%253A%2522clp0x0es70005356j1vhe001n%2522%252C%2522activeTabId%2522%253A%2522clp0x0es60004356j02clzlk7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp0x0es60004356j02clzlk7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clp0x0y8w007r356jvwaod4oi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp0x0zdz007qechucvkkbhtu%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
见sandBox

### What is expected?
正常渲染

### What is actually happening?
sandBox

**Comment by mmmmr** [comment]
注释掉headerCell插槽或expandedRowRender插槽之一 可正常渲染

**Comment by tangjinzhou** [comment]
sandBox 没有示例啊

**Comment by mmmmr** [comment]
> sandBox 没有示例啊

不好意思, 重新整了一个: https://codesandbox.io/p/devbox/happy-shadow-wsd7l7?file=%2Fsrc%2FApp.vue%3A45%2C16
现在进去是报错的, 注释掉headerCell插槽或者expandedRowRender插槽可正常渲染

**Comment by sunny-ali** [comment]
I have the same problem ant-design-vue version 4.1.0

**Comment by think-gem** [comment]
I have the same problem ant-design-vue version 4.1.1、vue 3.4.15、vite 5.0.12

example:
```
<a-table
  :columns="[]"
  :dataSource="[{},{},{}]"
  :pagination="false"
>
  <template #headerCell="{ title }">
    {{ title }}
  </template>
  <template #expandedRowRender="{ record }">
    {{ record }}
  </template>
</a-table>
```
click expand button, tip error:
```
runtime-core.esm-bundler.js:2952 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE')
    at renderSlot (runtime-core.esm-bundler.js:2952:32)
    at useColumns.js:24:27
    at Array.map (<anonymous>)
    at fillSlots (useColumns.js:8:18)
    at filledColumns (useColumns.js:36:36)
    at ComputedRefImpl.transformColumns [as _value] (Table.js:338:113)
    at useColumns.js:175:39
    at ReactiveEffect.fn (reactivity.esm-bundler.js:992:13)
    at ReactiveEffect.run (reactivity.esm-bundler.js:176:19)
    at get value [as value] (reactivity.esm-bundler.js:1003:61)
```
@tangjinzhou

**Comment by think-gem** [comment]
<img width="1521" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/4160972/d07a46b7-c8d4-45ad-9ac9-afb0eb572488">
@tangjinzhou 使用npm和yarn提示错误不同，npm不渲染，yarn渲染后点击加号提示错误，示例地址：https://codesandbox.io/p/devbox/quizzical-morse-9vxgyw?file=%2Fsrc%2FApp.vue&embed=1

**Comment by mmmmr** [comment]
已经有大佬改了，等更新版本就好了

**Comment by hushuaibo** [comment]
升级到哪个版本会不再出现这个问题呢，目前"ant-design-vue": "^3.2.0"，"vue": "^3.2.33"

**Comment by bsuooo** [comment]
> 升级到哪个版本会不再出现这个问题呢，目前"ant-design-vue": "^3.2.0"，"vue": "^3.2.33" @bsuooo

4.1.2

**Comment by BryanLe97** [comment]
same issue with ant-design-vue 4.1.2

**Comment by ZedCoding** [comment]
我的antdv是 3.2.20   能不升级嘛
