### ISSUE TITLE
Upload组件使用报错 

### ISSUE THREAD

**Issue by repetition** [vueComponent/ant-design-vue#7118]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
4.0.7

### Reproduction link
[https://antdv.com/components/upload-cn#components-upload-demo-basic](https://antdv.com/components/upload-cn#components-upload-demo-basic)

### Steps to reproduce
使用官网 第一个Upload组件实例  https://antdv.com/components/upload-cn#components-upload-demo-basic

### What is expected?
不报错

### What is actually happening?
Cannot read properties of undefined (reading 'value')

**Comment by repetition** [comment]
useConfigInject.js:69 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at ReactiveEffect.eval [as fn] (useConfigInject.js:69:84)
    at ReactiveEffect.run (reactivity.esm-bundler.js:391:19)
    at get value [as value] (reactivity.esm-bundler.js:1230:33)
    at showWave (useWave.js:12:21)
    at HTMLButtonElement.onClick (index.js:49:13)

**Comment by dbgee** [comment]
# 同样报错
一个官方的demo 都报错，这个项目都没人维护了

**Comment by ramwin** [comment]
一样的报错。 我是用button组件报错的

**Comment by ramwin** [comment]
有相关MR了： [docs(config-provider): add wave setting](https://github.com/vueComponent/ant-design-vue/pull/7108)

**Comment by SQsuqi** [comment]
AutoComplete组件点击按钮也会如此

**Comment by repetition** [comment]
> # 同样报错
> 一个官方的demo 都报错，这个项目都没人维护了

我降级了 降到4.0.6就好了  4.0.7是刚发布的

**Comment by Ormicron** [comment]
我在使用button组建遇到了同样的问题，我是4.0.7版本，看到了 @ramwin 的MR连接，目前已经修复了，但是还没发布更新，临时可以将node_modules/ant-design-vue/lib/_util/wave/useWave.d.ts内容替换成
`export default function useWave(
  instance: ComponentInternalInstance | null,
  className: Ref<string>,
  wave?: ComputedRef<{ disabled?: boolean }>,
): VoidFunction {
  function showWave() {
    const node = findDOMNode(instance);

    if (wave?.value?.disabled || !node) {
      return;
    }`

**Comment by cdx111** [comment]
这个项目没有人维护了，还是用ele吧

**Comment by cdx111** [comment]
> 坐等修复

用react把

**Comment by SQsuqi** [comment]
有种为了一根葱包一盘饺子的感觉哈哈 说实话挺喜欢antd的风格的






------------------ 原始邮件 ------------------
发件人: 菜脯abc ***@***.***&gt;
发送时间: 2023年12月1日 18:07
收件人: vueComponent/ant-design-vue ***@***.***&gt;
抄送: SQsuqi ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [vueComponent/ant-design-vue] Upload组件使用报错  (Issue #7118)





  
坐等修复
  
用react把
