### ISSUE TITLE
[bug][message]使用样式兼容以后，message组件无法弹出

### ISSUE THREAD

**Issue by hdygxsj** [vueComponent/ant-design-vue#7119]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
浏览器 chrome 87

### Steps to reproduce
浏览器使用 chrome 87版，按照指引(https://www.antdv.com/docs/vue/compatible-style-cn) 配上样式兼容后，message组件失效

### What is expected?
正常使用message组件

### What is actually happening?
不弹出message的框

**Comment by liyangNB** [comment]
怎么解决的？
