### ISSUE TITLE
The dataRef of the node is undefine when loaddata is executed in TreeSelect

### ISSUE THREAD

**Issue by gaecfov** [vueComponent/ant-design-vue#712]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
1.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/lxxn9nxyl7)

### Steps to reproduce
when expand the tree node，the dataRef of node is object
when expand the treeselect node, the dataRef of node is undefine

### What is expected?
dataRef应该是原始数据，需要异步加载children

### What is actually happening?
dataRef为undefine

**Comment by nickolboy** [comment]
同上
