### ISSUE TITLE
Invalid prop: type check failed for prop "onChange". Expected Function, got Array

### ISSUE THREAD

**Issue by shiwanjun1995** [vueComponent/ant-design-vue#7120]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
online

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-mountain-8qj4wf?file=/src/components/FilterForm.vue)

### Steps to reproduce
直接控制台报警告

### What is expected?
警告去除

### What is actually happening?
控制台报警告

---
https://github.com/vueComponent/ant-design-vue/issues/3933

        

 
@buqiyuan

**Comment by buqiyuan** [comment]
由于`antdv`组件事件是通过 `props`接收的，所以遵循 [mergeprops](https://cn.vuejs.org/api/render-function.html#mergeprops) 的规则:
<img width="817" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/39730999/9a28d249-e477-4231-aa47-b973ddac7bad">
暂时只能在用户层解决，例如：
```vue
<a-select
    v-model:value="state[item.name]"
    :placeholder="item.placeholder || '请选择'"
    :allow-clear="true" 
    v-bind="{
      onChange: onSubmit,
      ...item.attrs
    }"
  ></a-select>
```

**Comment by shiwanjun1995** [comment]
非常感谢您的回复，一看就是对vue 相关api非常熟悉，自己去看了下，确实有这么个规则，可以很好的解决这个告警，从v2迁移到v3后，https://v3-migration.vuejs.org/zh/breaking-changes/listeners-removed.html，有个$listeners api 被移除了，所以如果仔细想想也应该合并在$attrs这个属性里，再次表达感谢😄。
