### ISSUE TITLE
类型“UploadFile<unknown>[] | undefined”没有匹配的类型“number”的索引签名

### ISSUE THREAD

**Issue by NingLiu1998** [vueComponent/ant-design-vue#7122]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
"@tsconfig/node18": "^18.2.2",     "@types/node": "^18.18.5",     "@vitejs/plugin-vue": "^4.4.0",     "@vue/tsconfig": "^0.4.0",     "npm-run-all2": "^6.1.1",     "typescript": "~5.2.0",     "unplugin-auto-import": "^0.16.7",     "vite": "^4.4.11",     "vue-tsc": "^1.8.19"

### Reproduction link
[https://github.com/NingLiu1998/grid-openai](https://github.com/NingLiu1998/grid-openai)

### Steps to reproduce
复制  https://www.antdv.com/components/upload-cn 文档中的代码到我自己的项目代码里后，一直出现
类型“UploadFile<unknown>[] | undefined”没有匹配的类型“number”的索引签名 这个提示，但是我看文档并没有对此有提示或者做出什么特殊操作处理，所以想知道是怎么做到的

### What is expected?
预期是不显示这个红色下划线

### What is actually happening?
就正常按照文档搭建的项目，代码也是复制文档的，它就这样出现了

---
（我想我CV的时候能够..顺畅。。。

        
![image](https://github.com/vueComponent/ant-design-vue/assets/109678937/8ee7d26b-4554-4152-b861-8fec2c69de95)

**Comment by kovsu** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/8ef7df27-e4ce-472b-9ac5-f0526b78bcd8)
我的没有报错诶

**Comment by NingLiu1998** [comment]
> ![image](https://user-images.githubusercontent.com/82451257/284105004-8ef7df27-e4ce-472b-9ac5-f0526b78bcd8.png) 我的没有报错诶

你的项目有开源吗，想看一眼对比下配置啥的，如果方便的话你看下我的
https://github.com/NingLiu1998/grid-openai

我临时解决方案是直接当any了

**Comment by kovsu** [comment]
其实我觉得是你那个类型推断那里是 UploadFile<unkown>[] | undefined，如果这个类型后面在接 [number] 就报错了。
而且我在你的项目没有找到你说的报错的地方，然后我就是用的 ant-design-vue 的源码。

**Comment by JavanShen** [comment]
可以这样处理  `NonNullable<UploadProps['fileList']>[number]`

**Comment by NingLiu1998** [comment]
> 其实我觉得是你那个类型推断那里是 UploadFile[] | undefined，如果这个类型后面在接 [number] 就报错了。 而且我在你的项目没有找到你说的报错的地方，然后我就是用的 ant-design-vue 的源码。

我改过了，直接any了

**Comment by NingLiu1998** [comment]
> 可以这样处理 `NonNullable<UploadProps['fileList']>[number]`

感谢，我试试
