### ISSUE TITLE
Style flickers and isn't applied on page load when used in Nuxt SSR with dark theme token.

### ISSUE THREAD

**Issue by fskarmeta** [vueComponent/ant-design-vue#7123]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
all browsers

### Reproduction link
[https://stackblitz.com/edit/github-52q5xr-wk4qod?file=scripts%2FantToken.json,scripts%2FgenAntdStyle.ts](https://stackblitz.com/edit/github-52q5xr-wk4qod?file=scripts%2FantToken.json,scripts%2FgenAntdStyle.ts)

### Steps to reproduce
https://stackblitz.com/edit/github-52q5xr-wk4qod?file=scripts%2FantToken.json,scripts%2FgenAntdStyle.ts

Reload the page

### What is expected?
the style to be applied immediately

### What is actually happening?
the style isn't applied of first page load.

**Comment by aibayanyu20** [comment]
try this  https://github.com/vueComponent/ant-design-vue-nuxt/issues/25
