### ISSUE TITLE
修改 a-config-provider 的 prefixCls props，a-menu 展开/折叠动画消失

### ISSUE THREAD

**Issue by lfzs** [vueComponent/ant-design-vue#7124]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
ant-design-vue 4.0.7/vue 3.3.8/Chrome 119.0.6045.159（正式版本） (x86_64) /macOS Monterey 12.0.1

### Reproduction link
[https://github.com/lfzs/antdv-vite-prefix-bug](https://github.com/lfzs/antdv-vite-prefix-bug)

### Steps to reproduce
[步骤](https://github.com/lfzs/antdv-vite-prefix-bug#readme)

### What is expected?
展开/折叠动画正常

### What is actually happening?
展开/折叠动画不正常

**Comment by webvs2** [comment]
please focus : #7150
