### ISSUE TITLE
报告两个问题，下拉框和CheckBox

### ISSUE THREAD

**Issue by crper** [vueComponent/ant-design-vue#713]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
macos / vue 2.6

### Reproduction link
[https://juejin.im/post/5cacb192f265da0362078b6f](https://juejin.im/post/5cacb192f265da0362078b6f)

### Steps to reproduce
直接调用

### What is expected?
无错误

### What is actually happening?
- `checkbox`用`v-model`绑定，控制台会报警告，但是值是正常响应的，应该是`props`的类型没限定好, 我传递的是布尔值

```js
vue.runtime.esm.js?2b0e:619 [Vue warn]: Invalid prop: type check failed for prop "checked". Expected Boolean, got Event

found in

---> <ACheckbox>
<ACol>
<ARow>
<ACard>
<ProductItem>
<ACol>
<ACard>
<BasicSetting>
```

至于下拉框的，是样式问题

很多情况下初始化宽度会变得非常小，连`placeholder`都不会撑开; 只能自己手动去设置一个最小宽度

**Comment by tangjinzhou** [comment]
1 多个问题请分开提issue
2 请提供有效复现链接
最后，感谢反馈

**Comment by crper** [comment]
收到了就好，坐等大佬们的更新

**Comment by qiaozhi520** [comment]
我也遇到这样的问题，在array[object]里绑定value改变里面的值时会报类型错误，其他情况不会 ，明明我打印出来就是boolean 值
