### ISSUE TITLE
vite 5.0.2 打包config文件被移除

### ISSUE THREAD

**Issue by mokurofuzo** [vueComponent/ant-design-vue#7132]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
vue3.3.8  vite5.0.2

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
npm run build

### What is expected?
正常打包

### What is actually happening?
打包过程中出现js文件被移除

vite v5.0.2 building for production...
node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js (2:29) A comment

"/* #__PURE__ */"

in "node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js (3:31) A comment

"/* #__PURE__ */"

in "node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js (4:32) A comment

"/* #__PURE__ */"

in "node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
node_modules/ant-design-vue/es/_util/hooks/_vueuse/_configurable.js (5:31) A comment

![image](https://github.com/vueComponent/ant-design-vue/assets/44792146/5e7135d5-e762-4b60-b07d-415a26487de1)

**Comment by kovsu** [comment]
https://github.com/vitejs/vite/issues/15100
