### ISSUE TITLE
Button Click to report an error

### ISSUE THREAD

**Issue by H-hejin** [vueComponent/ant-design-vue#7133]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
Win11, latest version from Google, vue3.3.8

### Reproduction link
[https://www.antdv.com/components/button-cn](https://www.antdv.com/components/button-cn)

### Steps to reproduce
After introducing the button normally, clicking on it will report an error, while other components are normal. This button has not referenced any events, and an error is reported once when clicked, but it does not affect its use

### What is expected?
Click not to report an error

### What is actually happening?
Click now to report an error

**Comment by puppet-666** [comment]
May be the same issue #7106

**Comment by H-hejin** [comment]
@puppet-666 Okay, thank you！
