### ISSUE TITLE
Tooltip/Popover 在svg元素下的定位问题

### ISSUE THREAD

**Issue by Kuntey** [vueComponent/ant-design-vue#7138]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
macos10.15.7，Microsoft Edge119.0.2151.72，Vue3.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/antdv-demo-popover-476dtv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp0x4i9200083p6fjo73sq8l%2522%252C%2522sizes%2522%253A%255B80.34013605442178%252C19.659863945578223%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp0x4i9200033p6fa23bscx6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp0x4i9200053p6f5wnqjkf4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp0x4i9200073p6frqt751bu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.6061452%252C56.3938548%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp0x4i9200033p6fa23bscx6%2522%253A%257B%2522id%2522%253A%2522clp0x4i9200033p6fa23bscx6%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FContextMenuTool.tsx%2522%252C%2522id%2522%253A%2522clp0x65wo00ar3p6fnhraog9r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522id%2522%253A%2522clp0xep5p01uh3p6f8s6up6ah%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp0x65wo00ar3p6fnhraog9r%2522%257D%252C%2522clp0x4i9200073p6frqt751bu%2522%253A%257B%2522id%2522%253A%2522clp0x4i9200073p6frqt751bu%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp0x4i9200063p6fx31lh9q1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp0x4i9200063p6fx31lh9q1%2522%257D%252C%2522clp0x4i9200053p6f5wnqjkf4%2522%253A%257B%2522id%2522%253A%2522clp0x4i9200053p6f5wnqjkf4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp0x4i9200043p6fbwd0kwng%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp0x4i9200043p6fbwd0kwng%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
svg元素内的rect元素添加tooltip/popover

### What is expected?
tooltip/popover显示

### What is actually happening?
tooltip/popover不显示

---
ant-design-react tooltip显示正常 [![Edit on CodeSandbox](https://codesandbox.io/p/devbox/delicate-bird-pdc6sq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpcdifdj00083p6g742kn7ca%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpcdifdj00033p6gvxrlkuq2%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpcdifdj00053p6glep6iyd0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpcdifdj00073p6grnmaywk5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpcdifdj00033p6gvxrlkuq2%2522%253A%257B%2522id%2522%253A%2522clpcdifdj00033p6gvxrlkuq2%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpcdifdj00073p6grnmaywk5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpcdifdj00063p6gj2gkz8xp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clpcdifdj00073p6grnmaywk5%2522%252C%2522activeTabId%2522%253A%2522clpcdifdj00063p6gj2gkz8xp%2522%257D%252C%2522clpcdifdj00053p6glep6iyd0%2522%253A%257B%2522id%2522%253A%2522clpcdifdj00053p6glep6iyd0%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpcdifdj00043p6giufh2v7o%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpcdifdj00043p6giufh2v7o%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by Kuntey** [comment]
有办法解决吗

**Comment by Kuntey** [comment]
1

**Comment by rauki** [comment]
svg下面的元素能触发tooltip生产提示元素，但是定位不到正确的地方，显示不出来，更改绑定的父级元素getPopupContainer也没用。有解决方案吗

**Comment by Kuntey** [comment]
将tooltip挂在绝对定位的元素上，并设置那个元素的x，y值，目前来说只能这样
