### ISSUE TITLE
输入框、数字输入框使用lazy触发两次change事件

### ISSUE THREAD

**Issue by watoken** [vueComponent/ant-design-vue#7141]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
win11,chrome,vue3

### Reproduction link
[http://blank](http://blank)

### Steps to reproduce
Html:
<a-input v-if="show" v-model:value.lazy="textItem" @change="changeHandle" />
<div style="padding: 40px;height: 200px;" @mousedown="hiddenHandle">
</div>
Ts:
const textItem = ref('1222');
const show = ref(true);
const hiddenHandle=()=>{
show.value = false;
}

const changeHandle = value => {
console.log(value);
}

### What is expected?
当使用lazy并且元素上有使用mousedown隐藏组件时会input出现报错，并且调用了两次change事件

### What is actually happening?
在隐藏组件时不应该调用两次change事件

**Comment by selicens** [comment]
线索有限，仅你贴出的代码没有复现这个问题，也许你可以补充更多条件
```
  <a-input v-if="show" v-model:value.lazy="textItem" @change="changeHandle" />  
  
  // js  
  const textItem = ref('1222');
  const show = ref(false); 
  const hiddenHandle = () => show.value = false;
  const changeHandle = value => {
    console.log(value);
  }
```

**Comment by watoken** [comment]
抱歉，少了一部分，在mousedown时会触发
//Html:
 <a-input v-if="show" v-model:value.lazy="textItem" @change="changeHandle" />  
<div style="height:200px;background:gray;" @mousedown="hiddenHandle"></div>
//js
const textItem = ref('1222'); 
const show = ref(true);
const hiddenHandle=()=>{ show.value = false; }
const changeHandle = value => {
     console.log(value);
}

**Comment by watoken** [comment]
抱歉少了触发事件的代码，下面在mousedown事件时会触发        
<a-input v-if="show" v-model:value.lazy="textItem" @change="changeHandle" />
        <div style="height:200px;background:gray;" @mousedown="hiddenHandle"></div>
  // js  
  const textItem = ref('1222');
  const show = ref(false); 
  const hiddenHandle = () => show.value = false;
  const changeHandle = value => {
    console.log(value);
  }

**Comment by selicens** [comment]
[codesandbox](https://codesandbox.io/p/devbox/peaceful-kilby-4t93dj?file=%2Fsrc%2FApp.vue%3A9%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpibvk2900083j6k45bqwo0x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpibvk2900033j6kwvg3wxj8%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpibvk2900053j6kwaueqzq8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpibvk2900073j6kex2oy822%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpibvk2900033j6kwvg3wxj8%2522%253A%257B%2522id%2522%253A%2522clpibvk2900033j6kwvg3wxj8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpic5g6w00up3j6kcysyczse%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A10%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpic5g6w00up3j6kcysyczse%2522%257D%252C%2522clpibvk2900073j6kex2oy822%2522%253A%257B%2522id%2522%253A%2522clpibvk2900073j6kex2oy822%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clpiby5cf00e13j6ksrjam9d2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpiby5cf00e13j6ksrjam9d2%2522%257D%252C%2522clpibvk2900053j6kwaueqzq8%2522%253A%257B%2522id%2522%253A%2522clpibvk2900053j6kwaueqzq8%2522%252C%2522activeTabId%2522%253A%2522clpibw6dz009j3j6kt1qjwyyk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpibw6dz009j3j6kt1qjwyyk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpibw6go0020edhufo92fesq%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
我建了一个最小复现，没有出现你说的问题

**Comment by watoken** [comment]
是这么操作的：在input中获取焦点并输入值  鼠标点击到div会触发，我试了你提供的code也有这个问题
![_17011769012372](https://github.com/vueComponent/ant-design-vue/assets/48740613/4e55d06f-3453-4ddb-8935-9ad178024cba)


https://github.com/vueComponent/ant-design-vue/assets/48740613/c266ae2d-bd70-4170-a4cb-5582a84afad8

**Comment by selicens** [comment]
这是因为使用了`v-if`，你将其换成`v-show`就没有了

**Comment by watoken** [comment]
但是在某些情况下是要使用v-if的，我做了一个设计器，配置属性的时候需要用v-if做切换

**Comment by watoken** [comment]
在使用v-show时也会有问题，值会更新不了

**Comment by selicens** [comment]
> 在使用v-show时也会有问题，值会更新不了
通过textItem取值，或者你在input失去焦点时触发事件获取值

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/28dd9483-e22f-4ed0-9cea-b03728eb027d)

**Comment by watoken** [comment]
但是我的具体功能需要使用到v-if，例如下面的，需要选中切换对应的配置上
![_17011785995881](https://github.com/vueComponent/ant-design-vue/assets/48740613/35a38b18-ea31-48ce-abb7-bd75c9af09ce)

**Comment by watoken** [comment]
我查看了input组件代码上，更新数据会同时有change和blur事件触发，是会导致重复触发然后引发的这个问题
![_17011788053805](https://github.com/vueComponent/ant-design-vue/assets/48740613/25d4247b-4654-48ee-8b98-1e6875e22d53)
