### ISSUE TITLE
I can't use upload input 

### ISSUE THREAD

**Issue by hakimov-dev** [vueComponent/ant-design-vue#7142]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.6

### Environment
vue ^3.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-dcmmmh?file=/src/App.vue)

### Steps to reproduce
I just copy and paste the code and idk how to use it.

### What is expected?
Image preview smoothly and get image to the variable

### What is actually happening?
I got error

**Comment by selicens** [comment]
You should select the corresponding version in the upper right corner of the official website. You are using code that does not belong to that version, and your Vue version does not support setup and ref

**Comment by webvs2** [comment]
I don't quite understand your needs😨，Can you describe it more？
