### ISSUE TITLE
[Bug]ConfigProvider组件设置prefixCls属性后，部分组件动画失效

### ISSUE THREAD

**Issue by yangtianxia** [vueComponent/ant-design-vue#7148]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.x | 4.x

### Environment
Vue

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/inspiring-dubinsky-6vty8w?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpjh9u5y0007356hp4zgvmgt%2522%252C%2522sizes%2522%253A%255B80.66822977725674%252C19.33177022274326%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpjh9u5y0003356htqiizhyp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpjh9u5y0004356h7bhbsfh6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpjh9u5y0006356hzp3s519w%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpjh9u5y0003356htqiizhyp%2522%253A%257B%2522id%2522%253A%2522clpjh9u5y0003356htqiizhyp%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clpjh9u5y0006356hzp3s519w%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpjh9u5y0005356h2m01u2s6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clpjh9u5y0006356hzp3s519w%2522%252C%2522activeTabId%2522%253A%2522clpjh9u5y0005356h2m01u2s6%2522%257D%252C%2522clpjh9u5y0004356h7bhbsfh6%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpjh9u5y0004356h7bhbsfh6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
ConfigProvider组件设置prefixCls属性后，部分组件动画失效

- App.tsx

```tsx
import { ConfigProvider } from 'ant-design-vue'
import { defineComponent } from "vue";
import Demo from "./demo.tsx";

export default defineComponent({
  setup() {
    return () => (
      <ConfigProvider prefixCls="h">
        <Demo />
      </ConfigProvider>
    );
  }
})
```
- demo.tsx

```tsx
import { Menu } from "ant-design-vue";
import { defineComponent } from "vue";

export default defineComponent({
  setup() {
    return () => (
      <Menu mode="inline">
        <Menu.SubMenu title="submenu-5">
          <Menu.Item>menu2</Menu.Item>
          <Menu.Item>menu3</Menu.Item>
          <Menu.Item>menu4</Menu.Item>
          <Menu.Item>menu5</Menu.Item>
          <Menu.Item>menu6</Menu.Item>
        </Menu.SubMenu>
        <Menu.Item>menu1</Menu.Item>
      </Menu>
    );
  }
});
```
- 触发元素dom

![image](https://github.com/vueComponent/ant-design-vue/assets/73974709/687bd668-d1eb-4747-bd08-f89600bd561f)

- 问题代码点

https://github.com/vueComponent/ant-design-vue/blob/e36257171918d47b1e47cd6e78730ee8fc7a73c8/components/_util/collapseMotion.tsx#L5

### What is expected?
组件动画不受ConfigProvider组件prefixCls属性影响

### What is actually happening?
因为设置ConfigProvider组件prefixCls属性，导致部分组件动画失效

**Comment by webvs2** [comment]
将查看问题
