### ISSUE TITLE
Why set p { margn-bottom: 1em;} in base.less

### ISSUE THREAD

**Issue by titancat** [vueComponent/ant-design-vue#715]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
core

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/blob/master/components/style/core/base.less](https://github.com/vueComponent/ant-design-vue/blob/master/components/style/core/base.less)

### Steps to reproduce
style/core/base.less

### What is expected?
Should not reset the style of p tag

### What is actually happening?
p {
margin-top: 0;
margin-bottom: 1em;
}

---
You shouldn't reset style of p tag. Actually, the latest version of normalize.css give up this practice.
Here's the [link](https://github.com/necolas/normalize.css/blob/master/normalize.css)

**Comment by myh6666** [comment]
and ul ol dl
