### ISSUE TITLE
a-range-picker 设置open为false 的时候 选中 picker 后  ant-picker-active-bar的样式应该为 display: none

### ISSUE THREAD

**Issue by zhangchenna** [vueComponent/ant-design-vue#7155]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
a-range-picker 设置open为false 的时候 选中 picker 后  ant-picker-active-bar的样式应该为 display: none

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
a-range-picker 设置open为false 的时候 选中 picker 后  ant-picker-active-bar的样式应该为 display: none

### What is expected?
a-range-picker 设置open为false 的时候 选中 picker 后  ant-picker-active-bar的样式应该为 display: none

### What is actually happening?
a-range-picker 设置open为false 的时候 选中 picker 后  ant-picker-active-bar的样式应该为 display: none

**Comment by mmmmr** [comment]
光标都聚焦了,显示activebar 应该没问题吧  不过位置好像有点不对 #7157

**Comment by mmmmr** [comment]
光标都聚焦了,显示activebar 应该没问题吧
