### ISSUE TITLE
RangePicker 在mode 等于year的时候，面板无法选中

### ISSUE THREAD

**Issue by fanlei1988** [vueComponent/ant-design-vue#716]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
系统版本 ：window10  浏览器版本：chrome  Vue 版本：2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zo2mvnnk4?fontsize=14)

### Steps to reproduce
```
<template>
<div style="margin: 24px">
<a-range-picker
:placeholder="['Start Year', 'End Year']"
format="YYYY"
v-model="value"
:mode="mode2"
@panelChange="handlePanelChange2"
/>
</div>
</template>

<script>
import moment from "moment";
export default {
name: "App",
data() {
return {
moment,
mode2: ['year', 'year'],
value: [],
};
},
methods: {
handlePanelChange2 (value, mode) {
this.value = value
this.mode2 = ['year','year']
},
}
};
</script>

<style></style>
```

### What is expected?
选中年份的时候，为选中状态

### What is actually happening?
选中年份的时候，无变化

---
另外，当我使用mode=month的时候，第二个选择完毕的时候，无法自动关闭，只能移动鼠标关闭

**Comment by mkxj** [comment]
我也遇到这个问题了，请问你后来是咋解决的

**Comment by luocong2016** [comment]
```
mode="year" 这里无法关闭 活动面板，只能失去焦点
```
