### ISSUE TITLE
Button點擊就報錯

### ISSUE THREAD

**Issue by zzzgit** [vueComponent/ant-design-vue#7161]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
<img width="436" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/1060733/19b371d0-9571-4859-bb5f-d85bd5aac206">

        
### Version
4.0.7

### Environment
andv 4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/button-7l6cvj?file=%2Fsrc%2Fdemo.vue%3A8%2C1)

### Steps to reproduce
1. 在組件中，放一個a-button
2. 點擊這個button
3. 控制台報錯

### What is expected?
不報錯

### What is actually happening?
控制臺報錯

**Comment by Vasanthaprakash** [comment]
Yes, I'm also getting the same issue
