### ISSUE TITLE
a-cascader  只如何存最后一级Id和回显

### ISSUE THREAD

**Issue by Hair-Serei** [vueComponent/ant-design-vue#7164]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在选择省市区下拉框时，只存最后一级（区）的数据，并根据这个数据回显

### What does the proposed API look like?
and-design-vue V2.10.1

**Comment by leizhiyou** [comment]
有解决方案么
