### ISSUE TITLE
升级到最新版本定制主题配置失效

### ISSUE THREAD

**Issue by RayforReal** [vueComponent/ant-design-vue#7168]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
"ant-design-vue": "^4.0.7", "vue": "^3.3.8",

### Reproduction link
[https://3x.antdv.com/docs/vue/customize-theme-cn](https://3x.antdv.com/docs/vue/customize-theme-cn)

### Steps to reproduce
如果把ant-desgin版本降到3.2.20，主题配置会生

### What is expected?
ant-desgin最新版本定制主题生效

### What is actually happening?
ant-desgin最新版本定制主题不生效

---
在vite.config,ts文件中配置
css: {
preprocessorOptions: {
less: {
modifyVars: { hack: `true; @import './src/assets/less/theme.less';` },
javascriptEnabled: true
}
}
}
在ant-desgin版本为4.0.7未生效，如果切回3.2.20以下版本则主题配置生效，在node_modules中ant-desgin-vue并未找到css文件，大版本4以上是否是对组件的样式文件做了不一样的处理？

**Comment by selicens** [comment]
https://www.antdv.com/docs/vue/customize-theme-cn
