### ISSUE TITLE
二次开发，把button放入span，导致click回调函数行为异常

### ISSUE THREAD

**Issue by zzzgit** [vueComponent/ant-design-vue#7169]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
![image](https://github.com/vueComponent/ant-design-vue/assets/1060733/3898011a-d55e-4a2a-bf61-aec7f99f9d53)

![image](https://github.com/vueComponent/ant-design-vue/assets/1060733/a7bc5816-e615-4f42-ba34-e13dc27e44d6)

        
### Version
3.2.20

### Environment
Vue 最新

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/danger-button-ant-design-vue-3-2-20-forked-yy3rd5?file=%2Fsrc%2Fdemo.vue%3A10%2C37)

### Steps to reproduce
1. 封装组件b-button
2. 打开浏览器控制台
3. 点击这个按钮
4. 发现回调函数会被调用两次

### What is expected?
不要循环调用回调函数

**Comment by cc-hearts** [comment]
点击事件被透传了 span上也会有点击事件 可以看下相关文档[vue attrs](https://cn.vuejs.org/guide/components/attrs.html)

**Comment by zzzgit** [comment]
> 点击事件被透传了 span上也会有点击事件 可以看下相关文档[vue attrs](https://cn.vuejs.org/guide/components/attrs.html)

不对，文档中说的是子组件和父组件各自绑定了一个函数，我的demo显然不是。可以看下相关文档[vue attrs](https://cn.vuejs.org/guide/components/attrs.html)

**Comment by cc-hearts** [comment]
<img width="1262" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/c0a0e2b3-639d-4492-80d9-9cb90e96a261">

**Comment by zzzgit** [comment]
> vue playground

我明白了，謝謝
