### ISSUE TITLE
a-select没办法动态设置faultValue

### ISSUE THREAD

**Issue by JennyLJL** [vueComponent/ant-design-vue#717]
<a-select class="appsChange" :defaultValue="defaultVal" style="width: 100%" @change="appsChange">
          <a-select-option 
            v-for="app in apps"
            :key="app.id"
          >{{app.name}}</a-select-option>
defaultVal会经常变化，但是并不会更新视图

**Comment by ChrisChenSZ** [comment]
目前这个bug我也遇到，我的解决方式是，在a-select外面的元素用v-if判断defalutValue是否异步回来才显示元素
`            <a-col :span="10"
                     v-if='selectItems && selectItems[0] && selectItems[0].category_name'>
                <a-select :defaultValue='selectItems && selectItems[0] && selectItems[0].category_name'
                          @change="handleSelectChange">
                  <a-select-option v-for='(select,index) in selectItems'
                                   :value="index"
                                   :key='select.pcId'>
                    {{select.category_name}}
                  </a-select-option>
                </a-select>
              </a-col>`
