### ISSUE TITLE
Issue with a-popconfirm not closing automatically

### ISSUE THREAD

**Issue by HtmlMak** [vueComponent/ant-design-vue#7170]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
Vue 3, latest chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/conditional-trigger-ant-design-vue-4-0-7-forked-h5yzhm)

### Steps to reproduce
Utilize the okButton slot with a native button inside the a-popconfirm. Observe that the @confirm event is triggered successfully, but the popconfirm window does not close automatically.

### What is expected?
After triggering the @confirm event, the a-popconfirm window should close automatically.

### What is actually happening?
The a-popconfirm window remains open even after the @confirm event is triggered.

**Comment by selicens** [comment]
Related to the wave of ConfigProvider, waiting for the next version update

**Comment by kovsu** [comment]
fixed in 4.0.8
