### ISSUE TITLE
table组件的columns中width属性设置无效

### ISSUE THREAD

**Issue by telsafedev** [vueComponent/ant-design-vue#7171]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.8

### Environment
vue2, windows, chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-forked-py4n6f?file=/src/App.vue)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-template-forked-py4n6f?file=/src/App.vue

### What is expected?
预期根据当前设置的宽度进行列宽的显示

### What is actually happening?
现在呈现的列宽与设置的列宽并不一样

**Comment by selicens** [comment]
例：
```js
{
    title: "Action",
    width: "100",
    key: "action",
    scopedSlots: { customRender: "action" }
 }  
```

**Comment by telsafedev** [comment]
我尝试这样编写，但是没有效果

**Comment by telsafedev** [comment]
我发现这个会计算当前如果存在滚动条的情况下，就会按照配置的列宽进行显示

**Comment by mmmmr** [comment]
你全部列都设置了width
![image](https://github.com/vueComponent/ant-design-vue/assets/91053541/df8499e8-ef28-4ba2-8b2b-2bf2928b2bf0)
