### ISSUE TITLE
4.x 版本定制主题，tailwindicss 如何使用使用定制主题

### ISSUE THREAD

**Issue by siegaii** [vueComponent/ant-design-vue#7182]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
按照定制主题中文档的  const { useToken } = theme;  const { token } = useToken(); 方法去取框架中的css变量，然后使用tailwindicss 给元素加上带有变量的类，发现没有生效

如：
<div class={`w-10 h-10 bg-[${token.value.colorBgBase}]`}><div/>

html 表现：bg-[#xxxxxx] 的值渲染上去了，但是css 没生效

### What does the proposed API look like?
macOs：12.6.7，Vue：3.3.4、浏览器: chrom 119

**Comment by aibayanyu20** [comment]
建议转换成css var变量来使用

**Comment by chenxiaoleizi** [comment]
> 建议转换成css var变量来使用

怎么转成 css变量？有现成的库吗？
