### ISSUE TITLE
官网的可编辑表格组件输入时用鼠标点选输入的字体会消失

### ISSUE THREAD

**Issue by lfandrh** [vueComponent/ant-design-vue#7189]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
Win10系统、Chrome浏览器

### Reproduction link
[https://www.antdv.com/components/table-cn#components-table-demo-edit-row](https://www.antdv.com/components/table-cn#components-table-demo-edit-row)

### Steps to reproduce
1.可编辑表格中，任意选择一行点击右侧的编辑按钮，然后鼠标点击一个输入框；2.用鼠标进行选择输入两个汉字，过程中鼠标会离开输入框到输入法的选择区，鼠标点击将文字输入进去后，再将鼠标移回输入框，此时输入的字体会消失

### What is expected?
一个简单的输入框不应该出现这种问题吧

### What is actually happening?
输入的字体会消失，然后打字的过程中还可能重新出现，消失很容易复现，重新出现则是不确定的操作下会有

视频：https://github.com/vueComponent/ant-design-vue/assets/66020573/2ff3363f-87c5-4f85-b153-37cc2541ff3c

**Comment by cc-hearts** [comment]
🤔目前定位到的问题是 table每次 hover和 focus 都会使得table行重新渲染，导致取值是 `editableData[record.key]` 所以每次会出现数据消失。

复现例子如 [codesandbox](https://codesandbox.io/p/sandbox/ke-bian-ji-dan-yuan-ge-ant-design-vue-4-0-7-forked-zjvktw?file=%2Fsrc%2Fdemo.vue%3A16%2C29)
