### ISSUE TITLE
在babel.config.js里面配置了按需加载，那么在组件内部如何访问全局提示this.$message.success()

### ISSUE THREAD

**Issue by alterhu2020** [vueComponent/ant-design-vue#719]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Vue: 2.6.10 ,ant-design-vue: "^1.3.8"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ykrr4p72jv)

### Steps to reproduce
我看到以前已经有提交过的issue： https://github.com/vueComponent/ant-design-vue/issues/336 ,但是被关闭了。
所以重新提这个问题。
1. babel.config.js 里面配置如下：

module.exports = {
'presets': [
'@vue/app'
],
'plugins': [
[
'import',
{
'libraryName': 'ant-design-vue',
'libraryDirectory': 'es',
'style': true
}
]
]
}

2. ant-design-vue.js 里面配置如下：

import Vue from 'vue'
import {
LocaleProvider,
Layout,
Input,
InputNumber,
Button,
Switch,
Radio,
Checkbox,
Select,
Card,
Form,
Row,
Col,
Modal,
Table,
Tabs,
Icon,
Badge,
Popover,
Dropdown,
List,
Avatar,
Breadcrumb,
Steps,
Spin,
Menu,
Drawer,
Tooltip,
Alert,
Tag,
Divider,
DatePicker,
TimePicker,
Upload,
Progress,
Skeleton,
Popconfirm,
notification,
message
} from 'ant-design-vue'
import config from '../config'

Vue.prototype.$message = message
Vue.prototype.$notification = notification
Vue.prototype.$info = Modal.info
Vue.prototype.$success = Modal.success
Vue.prototype.$error = Modal.error
Vue.prototype.$warning = Modal.warning
Vue.prototype.$confirm = Modal.confirm

Vue.use(LocaleProvider)
Vue.use(Layout)
Vue.use(Input)
Vue.use(InputNumber)
Vue.use(Button)
Vue.use(Switch)
Vue.use(Radio)
Vue.use(Checkbox)
Vue.use(Select)
Vue.use(Card)
Vue.use(Form)
Vue.use(Row)
Vue.use(Col)
Vue.use(Modal)
Vue.use(Table)
Vue.use(Tabs)
Vue.use(Icon)
Vue.use(Badge)
Vue.use(Popover)
Vue.use(Dropdown)
Vue.use(List)
Vue.use(Avatar)
Vue.use(Breadcrumb)
Vue.use(Steps)
Vue.use(Spin)
Vue.use(Menu)
Vue.use(Drawer)
Vue.use(Tooltip)
Vue.use(Alert)
Vue.use(Tag)
Vue.use(Divider)
Vue.use(DatePicker)
Vue.use(TimePicker)
Vue.use(Upload)
Vue.use(Progress)
Vue.use(Skeleton)
Vue.use(Popconfirm)

### What is expected?
可以直接使用： this.$message.info('This is a normal message')

### What is actually happening?
使用： this.$message.info('This is a normal message') 报错： [Vue warn]: Error in v-on handler: "TypeError: Cannot read property '$message' of undefined"

**Comment by sendya** [comment]
codesandbox 使用的 cli 是 `vue-cli2` ，不是 cli3 ，不能以 cli3 的配置形式去配置按需引入。

cli2 应当如下配置，并正确引入 `babel-plugin-import` 插件

```diff
  {
    "presets": [
      ["env", {
        "modules": false,
        "targets": {
          "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
        }
      }],
      "stage-2"
    ],
-   "plugins": ["transform-vue-jsx", "transform-runtime"]
+   "plugins": [
+     "transform-vue-jsx",
+     "transform-runtime",
+     ["import", { "libraryName": "ant-design-vue", "libraryDirectory": "es", "style": "css" }]
+   ]
  }
```

cli3 可以参考官方文档配置方式 https://vue.ant.design/docs/vue/use-with-vue-cli-cn/
或实例 [demand_load/babel.config.js](https://github.com/sendya/ant-design-pro-vue/blob/feature/demand_load/babel.config.js)

**Comment by alterhu2020** [comment]
@sendya 
配置是没有错的，是按照https://github.com/sendya/ant-design-pro-vue/blob/feature/demand_load/babel.config.js 这个里面配置的，问题就是按需导入后，使用$message采用这种方式总是报错：

```
import {message} } from 'ant-design-vue'
Vue.prototype.$message = message

```
提示$message没有定义，后来采用如下方式却可以使用了：
```
import {message} } from 'ant-design-vue'
const Message = message
!Vue.prototype.$message && Object.defineProperties(Vue.prototype, {
  $message: {
    get () {
      return Message
    }
  }
})
```

看起来是重复定义了$message,所以按需引入的时候是不是不用再引入一遍$message挂载到Vue节点了对吗？ 但是好像又不是，如果在`babel.config.js`中声明了按需引入后，不声明$message,使用的时候又会报错？

**Comment by tangjinzhou** [comment]
需要自己注册 `Vue.prototype.$message = message`

**Comment by alterhu2020** [comment]
it works now, close it.

**Comment by lizy0329** [comment]
> it works now, close it.

close 个啥，这个明显就是这个库的 BUG 啊，而且是很严重的 BUG
