### ISSUE TITLE
table组件滚动条和选择框同时存在时，表头和内容有错位严重

### ISSUE THREAD

**Issue by Gilbert5210** [vueComponent/ant-design-vue#7190]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
chrome 版本 113.0.5672.126（正式版本） (x86_64), vue@3.2.33

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
1. 因为在window上，没有滚动条的也出现了滚动条的占位
2. 所以我们在项目中，设置了这个属性，固定最后一列到最右边
```css
.ant-table-body {
overflow-y: auto!important;
}
```
3. 这个时候发现这里有一个错位
<img width="487" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/17983736/506259b0-741d-490a-a00a-30329a99262c">
<img width="299" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/17983736/7e6e50b5-fcfd-4c8f-98e4-2c110095cbf9">

### What is expected?
不存在错位，可以取消表头的这个td的显示
<th class="ant-table-cell ant-table-cell-fix-right ant-table-cell-scrollbar" colstart="13" colend="13" style="position: sticky; right: 0px;"></th>

### What is actually happening?
表头和内容存在错位

---

**Comment by Gilbert5210** [comment]
@cc-hearts 
帮忙看看
？

**Comment by cc-hearts** [comment]
🤔我研究一下

**Comment by cc-hearts** [comment]
能提供可以复现的代码吗？

**Comment by Gilbert5210** [comment]
> 能提供可以复现的代码吗？

https://codesandbox.io/p/sandbox/gu-ding-tou-he-lie-ant-design-vue-3-2-20-forked-hxtq7r
这里看看

**Comment by cc-hearts** [comment]
因为设置了`scroll.y` 会出现即使没有滚动条也有滚动条占位的情况。
```vue
<a-table :columns="columns" :data-source="data" :scroll="{ x: 1500, y: 600 }">
```

需求是 `table` 最高占 600 超过的话滚动是吗？

**Comment by cc-hearts** [comment]
如果设置了 
```vue
.ant-table-body {
overflow-y: auto!important;
}
```
或许需要自己去判断 table的高度从而动态设置 `scroll.y`属性了🤔。
