### ISSUE TITLE
Missing script setup when switching code from TS to JS in documentation.

### ISSUE THREAD

**Issue by oussema-attia** [vueComponent/ant-design-vue#7193]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
Windows 11, chrome, edge, Vue 3 , Nuxt 3

### Reproduction link
[https://antdv.com/components/layout](https://antdv.com/components/layout)

### Steps to reproduce
Open documentation for any component that have script in it and switch code from TS to JS.

### What is expected?
You will notice that the script will be missing setup and you are using composition api in the script part.

### What is actually happening?
So the const that you are using in the template will not be exposed so it will generate an error.

**Comment by JavanShen** [comment]
#7153 already have pr
