### ISSUE TITLE
InputGroup中使用 tooltip 包裹的 button[disabled] 样式不正确

### ISSUE THREAD

**Issue by ydq** [vueComponent/ant-design-vue#7195]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
MacOS14.2
Chrome 120 / safari 
vue3  

### Steps to reproduce
如下结构：

```html
<a-input-group compact>

    <a-tooltip placement="bottom" title="输入消费组后回车或点击获取Offset按钮">
        <a-input disabled/> <!-- 这个 disable 渲染也正常 -->
    </a-tooltip>

    <a-button disabled>这个按钮渲染正常</a-button>

    <a-tooltip placement="bottom" title="移除disabled恢复正常，有disabled边角样式错误">
        <a-button disabled>被包裹的按钮</a-button>
    </a-tooltip>

    <a-button disabled>这个按钮渲染正常</a-button>
</a-input-group>
```
![bug](https://github.com/vueComponent/ant-design-vue/assets/8097340/0000d864-c11f-4f61-b2e7-86414133737b)

### What is expected?
在中间的按钮应该都是直角
在边侧的按钮靠近其他元素的一边应该为直角

### What is actually happening?
被 tooltip 包裹的 button[disabled] 出现了圆角

**Comment by selicens** [comment]
应该是受到透传的样式影响，最直接的解法就是button上style给一个border-radius: 0

**Comment by ydq** [comment]
> 应该是受到透传的样式影响，最直接的解法就是button上style给一个border-radius: 0

我临时解决方案 是直接改了下结构，将 tooltips 包裹在 button 里面去了，这样做唯一的影响是鼠标必需浮在文字上才会触发 tooltip
