### ISSUE TITLE
vue3 环境下icon无法正常渲染

### ISSUE THREAD

**Issue by xiaoshi1** [vueComponent/ant-design-vue#7197]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
macos,chrome,vue3.2.13

### Reproduction link
[http://127.0.0.1/test](http://127.0.0.1/test)

### Steps to reproduce
<script lang="ts" >
import {
GroupOutlined,
VideoCameraOutlined,
UploadOutlined,
BarChartOutlined,
CloudOutlined,
AppstoreOutlined,
TeamOutlined,
ShopOutlined,
} from '@ant-design/icons-vue';
import { Layout, LayoutHeader, LayoutSider, LayoutFooter, LayoutContent, Menu, MenuItem } from 'ant-design-vue'
</script>

只截取一段模版代码
<template>
<a-layout has-sider>
<a-layout-sider :style="{ overflow: 'auto', height: '100vh', position: 'fixed', left: 0, top: 0, bottom: 0 }">
<div class="logo" />
<a-menu v-model:selectedKeys="selectedKeys" theme="dark" mode="inline">
<a-menu-item key="1">
<upload-outlined />            
<span class="nav-text">nav 1</span>
</a-menu-item>
</a-menu>
<a-layout-sider/>
</a-layout>
<template>

### What is expected?
想确认是不是bug，怎么使用才能正常加载

### What is actually happening?
icon 库尊循官方文档使用无法在最终效果中加载

---
建议使用方式可以多写几个比较清晰的样例

**Comment by cc-hearts** [comment]
如果不是 `setup` 的形式，导入的组件应该需要注册才可以使用。

能否提供更多的信息，以便排查问题。🤔

**Comment by xiaoshi1** [comment]
简单写了下
```
<script lang="ts">
import {
  UserOutlined,
  VideoCameraOutlined,
  UploadOutlined,
  BarChartOutlined,
  CloudOutlined,
  AppstoreOutlined,
  TeamOutlined,
  ShopOutlined,
} from '@ant-design/icons-vue';
import { defineComponent, reactive, ref } from 'vue';
import {Menu,Layout,MenuItem} from 'ant-design-vue'
export default defineComponent({
  name: 'APP',
  components:{
  'a-menu':Menu,
  'a-menu-item':Layout,
  ShopOutlined // 无法做为组件进行注册，另外如：MenuItem 等组件和模版中实际使用的名称不对应需要在组件注册时申明
  },
  setup() {

    return {
      selectedKeys: ref<string[]>(['4']),
    };
  },
});
</script>

```
<img width="821" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/94ca1193-ea93-4d13-9385-ded73efcfdc4">

**Comment by cc-hearts** [comment]
可以参考一下这个： [codeSandbox](https://codesandbox.io/p/sandbox/great-albattani-nyvnkj?file=%2Fsrc%2FApp.vue%3A1%2C1-39%2C1)

**Comment by cc-hearts** [comment]
icon 是 一个`slot` 所以需要写 
```vue
<template #icon>
    <MenuFoldOutlined />
</template>
```

**Comment by xiaoshi1** [comment]
你好 还是不行
<img width="925" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/805573b0-a55e-42f1-a0be-4cf62e83ef1d">
<img width="526" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/cf0a00d0-6087-41f1-afad-2b7e36598597">
<img width="827" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/c5f5bd4f-97bd-4d7f-a607-afbce65d5f8a">

**Comment by cc-hearts** [comment]
icon 插槽是Menu.Item（a-menu-item）的，应该写在这个（a-menu-item）里面

**Comment by xiaoshi1** [comment]
感谢确实加载了出来但是新的问题 span里的文字不显示了
<img width="610" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/01726f5e-f359-44c5-8f4e-771cb9ff7382">
<img width="533" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/3771883/62abee29-d98f-4a41-80b3-b0c4b7366b38">

**Comment by cc-hearts** [comment]
参考格式

```vue
<a-menu-item>
  <template #icon>
    <MenuFoldOutlined />
  </template>
  <span>nav1</span>
</a-menu-item>

```

**Comment by xiaoshi1** [comment]
好的 十分感谢

**Comment by Delevin888** [comment]
我整了一个骚写法。
