### ISSUE TITLE
ant-design-vue4.0.7版本在360极速浏览器下不兼容，样式混乱

### ISSUE THREAD

**Issue by zhenghuirong** [vueComponent/ant-design-vue#7198]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
ant-design-vue4.0.7，360极速浏览器最新版

### Reproduction link
[https://next.antdv.com/components/icon-cn](https://next.antdv.com/components/icon-cn)

### Steps to reproduce
样式未生效

### What is expected?
ant-design-vue4.0.7在360极速浏览器页面上:where() 的写法未生效，页面样式混乱，官方文档目前只有antd V5下对360极速浏览器的适配，兼容方案不能解决目前存在的问题，希望使用高版本的antd-design-vue，也希望能在360极速浏览器展示正常的页面

### What is actually happening?
ant-design-vue4.0.7在360极速浏览器页面上:where() 的写法未生效，页面样式混乱，官方文档目前只有antd V5下对360极速浏览器的适配，兼容方案不能解决目前存在的问题，希望使用高版本的antd-design-vue，也希望能在360极速浏览器展示正常的页面

**Comment by yzxinbj** [comment]
+1

**Comment by niceue** [comment]
+1，一定要用:where吗？
360极速浏览器不支持影响非常大
