### ISSUE TITLE
取不到primaryColor

### ISSUE THREAD

**Issue by zzzgit** [vueComponent/ant-design-vue#7202]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/duo-ge-an-niu-zu-he-ant-design-vue-4-0-8-forked-3ynt37?file=%2Fsrc%2Fdemo.vue%3A11%2C10)

### Steps to reproduce
1. 使用官网的方法，theme.useToken()
2. 然后打印token.primaryColor
3. 这个对象下，没有primaryColor

![image](https://github.com/vueComponent/ant-design-vue/assets/1060733/b7b0b1cc-91a5-4d7b-abae-32730fc654a0)

**Comment by Ashuangshuang** [comment]
名字是colorPrimary
