### ISSUE TITLE
input-number 设置decimal-separator属性后失焦后会变成设置的最小值

### ISSUE THREAD

**Issue by Kuntey** [vueComponent/ant-design-vue#7204]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
macos：10.15.7，"vue": "^3.3.8"，"vite": "^4.5.0",  Microsoft Edge 120.0.2210.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/vue-vite-ts-forked-mc73gt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqbr1fsi00063p6g954ukrdh%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqbr1fsi00023p6g2a9vqcnl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqbr1fsi00043p6g07xg3xu4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqbr1fsi00053p6ge2pqimkz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqbr1fsi00023p6g2a9vqcnl%2522%253A%257B%2522id%2522%253A%2522clqbr1fsi00023p6g2a9vqcnl%2522%252C%2522activeTabId%2522%253A%2522clqbs3hr100l63p6gefx1ywsn%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqbr1fsi00013p6g33q8svmz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clqbs3hr100l63p6gefx1ywsn%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clqbr1fsi00053p6ge2pqimkz%2522%253A%257B%2522id%2522%253A%2522clqbr1fsi00053p6ge2pqimkz%2522%252C%2522activeTabId%2522%253A%2522clqbrwssr007x3p6go65vixsh%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clqbrwssr007x3p6go65vixsh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqbr1fsi00043p6g07xg3xu4%2522%253A%257B%2522id%2522%253A%2522clqbr1fsi00043p6g07xg3xu4%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqbrbr4q00sx3p6gdz30f7t1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqbrvzog000ceefz6t6ibv5z%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqbrbr4q00sx3p6gdz30f7t1%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
设置decimal-separator属性

### What is expected?
设置decimal-separator属性后失焦，值不会改变

### What is actually happening?
设置decimal-separator属性后失焦，值会变成最小值

**Comment by qppq54s** [comment]
我看了下这个属性应该是用于替换小数点的字符串，用0替换小数点的话，内部进行数字转换的时候应该就有问题了。
请问您是在什么情况下需要把小数点设置为0呢？

**Comment by Kuntey** [comment]
是需要限制用户的输入为整数的时候用到的
