### ISSUE TITLE
select中tags模式，如果填写完内容，直接点击提交按钮，会获取不到最新值

### ISSUE THREAD

**Issue by havenothingtosay** [vueComponent/ant-design-vue#7206]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
vue3.2.45    chrome119.0.6045.199

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue3-antdv-select-tagsmo-shi-blurhou-zhi-bu-shi-zui-xin-de-vwhmyg)

### Steps to reproduce
在select框中输入值，直接点击submit按钮，此时value值没有获取刚刚输入的最新值

### What is expected?
希望能直接获取最新值

### What is actually happening?
未获取最新值

**Comment by zyc-on** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/23379463/f704f453-7f2a-4ec0-912d-5bc1473198e9)
看了下组件的源码, mode为tags时blur触发后有个100毫秒的定时器, 在这之后才会更新值, 目前是手动添加一个大于100毫秒的定时器之后再进行操作, 不知道有没有其他更好的办法
