### ISSUE TITLE
confirm 点击确定后控制台报错

### ISSUE THREAD

**Issue by zzzgit** [vueComponent/ant-design-vue#7209]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/confirmation-modal-dialog-ant-design-vue-4-0-7-forked-mrgkvz?file=%2Fsrc%2Fdemo.vue%3A12%2C19)

### Steps to reproduce
1. 点击按钮打开弹窗
2. 点击确定按钮
3. 控制台报错

### What is actually happening?
这个应该是transition造成的

**Comment by aibayanyu20** [comment]
demo是4.0.7的，升级到4.0.8没有复现这个问题呢 https://codesandbox.io/p/sandbox/confirmation-modal-dialog-ant-design-vue-4-0-7-forked-gwnh2c?file=%2Fpackage.json%3A6%2C30
