### ISSUE TITLE
 Is it possible to pre-specify filters and sorting for the table from the beginning?

### ISSUE THREAD

**Issue by LeeMQ-programmer** [vueComponent/ant-design-vue#7214]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I'm not proficient in either Chinese or English, so I used a translator to ask the question. It might sound a bit awkward, but please understand. I am displaying data on the screen using a datatable. Even if I reload the table asynchronously, can I specify filter and sort from the beginning? Currently, if you explicitly specify filteredValue and defaultSortOrder, it works, but you can't specify them using variables.

### What does the proposed API look like?
in https://antdv.com/components/table

filter.mainJob or sort.value.order contains the same value as explicitly written.

![image](https://github.com/vueComponent/ant-design-vue/assets/52558999/deec3383-8431-4fef-ad6a-7dd8e7e470a1)

![image](https://github.com/vueComponent/ant-design-vue/assets/52558999/c0797232-d6b0-4a33-bd70-455f316e304d)

**Comment by slmev** [comment]
[https://antdv.com/components/table#components-table-demo-reset-filter](url)
