### ISSUE TITLE
ant-design-vue@1.7.8版本a-table偶发性出现表头高度计算错误问题，导致固定列表头高度和非固定列表头高度出现错位

### ISSUE THREAD

**Issue by yueyunkeji** [vueComponent/ant-design-vue#7216]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
谷歌浏览器版本 120.0.6099.109（正式版本） (arm64)该版本偶现；另一个UOS浏览器版本号：5.2.1520.5复现的频率就比较高了，几乎是必现的

### Reproduction link
[https://github.com/youzan/vant/assets/21034570/afdf9d33-c2a3-4175-96e2-906250d07732](https://github.com/youzan/vant/assets/21034570/afdf9d33-c2a3-4175-96e2-906250d07732)

### Steps to reproduce
问题截图如：https://github.com/youzan/vant/assets/21034570/afdf9d33-c2a3-4175-96e2-906250d07732
ant-design-vue@1.7.8版本a-table偶发性出现表头高度计算错误问题，导致固定列表头高度和非固定列表头高度出现错位，特别是UOS浏览器下很容易复现该问题，麻烦协助解决该问题，在版本好无法升级的情况下应该如何修复，如果是强制高度覆盖也会影响没有固定列表格的表头换行场景，所以需要你们协助如何解决比较好，但是如何说往上升级版本应该升级到哪个版本能解决这个问题。同时是否又不影响现有的api属性等方法？

### What is expected?
期望协助解决该问题并尽量控制版本的情况下解决，因为升级版本的风险对于我们来说不可控。

### What is actually happening?

---

**Comment by sunny19990108** [comment]
chrome最新版本（ 121.0.6167.184（正式版本） (arm64)）必现。。
<img width="1270" alt="截屏2024-02-18 11 36 36" src="https://github.com/vueComponent/ant-design-vue/assets/48590125/63d1fefb-4125-4d10-92d6-0401ba62bea4">

**Comment by 1474282816** [comment]
有找到解决办法吗 @yueyunkeji @sunny19990108
