### ISSUE TITLE
table组件是否支持多层json的渲染

### ISSUE THREAD

**Issue by luger1990** [vueComponent/ant-design-vue#7219]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
table渲染多层json

### What does the proposed API look like?
table中columns的定义如下：
```javascript
const columns = reactive([
  {
    title: '姓名',
    dataIndex: 'root.name',
    key: 'root.name',
  },
  {
    title: '年龄',
    dataIndex: 'root.age',
    key: 'root.age',
  },
  {
    title: '住址',
    dataIndex: 'root.address',
    key: 'root.address',
  },
])
```

**Comment by mmmmr** [comment]
不支持，但是你可以自己支持
<img width="958" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/91053541/24cc79ea-d076-4740-92f6-c58c7fb36b53">

**Comment by luger1990** [comment]
> 据这个API自己支持

好的 多谢
