### ISSUE TITLE
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗，

### ISSUE THREAD

**Issue by 13389203735** [vueComponent/ant-design-vue#7222]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
ant-desing-vue 4.0.7  vue 3.3.8

### Reproduction link
[https://next.antdv.com/components/date-picker-cn](https://next.antdv.com/components/date-picker-cn)

### Steps to reproduce
使用选择开始和结束日期控件后，在本地一切正常，但是在测试和线上，无法拉起日期选择弹窗

### What is expected?
能够在得到焦点的时候，拉起弹窗

### What is actually happening?
无法有效的拉起弹窗

**Comment by wyy5552** [comment]
同样遇到
![image](https://github.com/vueComponent/ant-design-vue/assets/5257962/8ba40c6f-375d-4498-81a0-ac90bd3312cc)

**Comment by aShu-guo** [comment]
参考：https://github.com/vueComponent/ant-design-vue/issues/5842#issuecomment-1314702517
