### ISSUE TITLE
Failed to resolve import "ant-design-vue/es/auto-complete/style"

### ISSUE THREAD

**Issue by Kitesource** [vueComponent/ant-design-vue#7224]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
latest browser,  vue3.3

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
user [unplugin-vue-components/resolvers] 动态导入
AntDesignVueResolver({
importStyle: 'less',
resolveIcons: true,
}),

### What is expected?
可以自动导入 auto-complete 的样式

### What is actually happening?
Failed to resolve import "ant-design-vue/es/auto-complete/style"

---
expected fix it or Provide me with a solution

**Comment by cc-hearts** [comment]
能否发一下 `package.json` , 检查是否安装了 ant-design-vue ?

**Comment by zkwolf** [comment]
`importStyle: false` 4.x不需要引入样式了
