### ISSUE TITLE
reopen: tree component checkStrictly attribute implements logic problems #6050

### ISSUE THREAD

**Issue by Pork-Cheung** [vueComponent/ant-design-vue#7225]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
codesandbox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-4-0-8-forked-vtfyys?file=%2Fsrc%2Fdemo.vue%3A14%2C31)

### Steps to reproduce
1. 在a-tree后面添加<div>{{ checkedKeys }}</div>
2. 将a-tree的checkStrictly分别设置为true和flase，观察checkedKeys值的变化

### What is expected?
checkStrictly 为 false的时候checkedKeys的数据结构为{checked: string[] | number[], halfChecked: string[] | number[]}其中halfChecked中的数据是被关联选择的父节点，checkStrictly 为true时，父子节点不关联，返回数据结构为string[] | number[]

### What is actually happening?
组件逻辑与期望相反

**Comment by mmmmr** [comment]
这个halfChecked是用来给使用者指定halfChecked状态的,比如:
<img width="326" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/91053541/24b13f41-6ac5-4558-ad44-05819716a784">
组件就会变成这样：
<img width="326" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/91053541/24b13f41-6ac5-4558-ad44-05819716a784">

**Comment by H-hejin** [comment]
https://blog.csdn.net/qq_61033782/article/details/139742370

**Comment by H-hejin** [comment]
参考我写的这篇文章，已解决https://blog.csdn.net/qq_61033782/article/details/139742370
