### ISSUE TITLE
qrcode 组件添加扫描成功的状态

### ISSUE THREAD

**Issue by dadianzi** [vueComponent/ant-design-vue#7231]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
添加一个新的status状态，用来标记二维码已经被扫描成功。

**Comment by dadianzi** [comment]
如果能提供`status`插槽更好了

**Comment by selicens** [comment]
这个需求需要配合着后端来做，插槽这个倒是好实现

**Comment by selicens** [comment]
#https://github.com/ant-design/ant-design/issues/46694
