### ISSUE TITLE
Radio 组件 按钮样式的单选组合 会有边框重叠现象

### ISSUE THREAD

**Issue by David-TechNomad** [vueComponent/ant-design-vue#7237]
![企业微信截图_17038296637063](https://github.com/vueComponent/ant-design-vue/assets/23149356/613acdd4-7c14-4473-84ea-427f0afe6d53)
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
Radio 组件 按钮样式的单选组合 会有边框重叠现象

### Reproduction link
[https://antdv.com/components/radio-cn](https://antdv.com/components/radio-cn)

### Steps to reproduce
Radio 组件 按钮样式的单选组合 会有边框重叠现象

### What is expected?
Radio 组件 按钮样式的单选组合 会有边框重叠现象

### What is actually happening?
Radio 组件 按钮样式的单选组合 会有边框重叠现象

**Comment by cc-hearts** [comment]
能提供复现的代码吗

**Comment by David-TechNomad** [comment]
> 能提供复现的代码吗
![radio](https://github.com/vueComponent/ant-design-vue/assets/23149356/cd51a626-7e03-4b69-aa7b-c6e79defee2a)
<a-radio-group v-model:value="value1">
    <a-radio-button value="a">Hangzhou</a-radio-button>
    <a-radio-button value="b">Shanghai</a-radio-button>
    <a-radio-button value="c">Beijing</a-radio-button>
    <a-radio-button value="d">Chengdu</a-radio-button>
  </a-radio-group>

**Comment by cc-hearts** [comment]
<img width="472" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/1deabfb2-c784-420e-9089-4ef365c57a82">

这边没有办法复现 希望能提供更多的信息
