### ISSUE TITLE
Tooltip 组件 箭头样式在设置config-provider的theme.token.borderRadius时展示问题

### ISSUE THREAD

**Issue by guo-yonghang** [vueComponent/ant-design-vue#7238]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
windows11、chrome 120.0.6099.130、vue3.3.11

### Reproduction link
[https://www.antdv.com/components/tooltip-cn](https://www.antdv.com/components/tooltip-cn)

### Steps to reproduce
```
<a-config-provider :theme="{ token: { borderRadius: '8px' } }">
<a-tooltip title="hellow world">
<a-button>hellow world</a-button>
</a-tooltip>
</a-config-provider>
```

![QQ图片20231229163519](https://github.com/vueComponent/ant-design-vue/assets/102007415/ec5a72ed-75fb-4d92-a367-068db7e4d5c4)

### What is expected?
设置a-config-provider组件的theme.token.borderRadius属性不影响Tooltip组件的箭头样式

### What is actually happening?
Tooltip组件的箭头样式被影响，使用border做的箭头变成了四边形，设置border属性的 :where 选择器失效

**Comment by cc-hearts** [comment]
这里`borderRadius`设置有误，应该设置为 `number` 而不是 `string`

```vue
<a-config-provider :theme="{ token: { borderRadius: 8 } }">
<a-tooltip title="hellow world">
<a-button>hellow world</a-button>
</a-tooltip>
</a-config-provider>
```

**Comment by guo-yonghang** [comment]
使用number类型确实没有这个错误了，官网[https://www.antdv.com/docs/vue/customize-theme-cn](https://www.antdv.com/docs/vue/customize-theme-cn)与[https://www.antdv.com/components/config-provider-cn](https://www.antdv.com/components/config-provider-cn)，两处文档不一致

**Comment by cc-hearts** [comment]
> 使用number类型确实没有这个错误了，官网https://www.antdv.com/docs/vue/customize-theme-cn与https://www.antdv.com/components/config-provider-cn，两处文档不一致

这里确实是个问题 稍后我会对其进行修复
