### ISSUE TITLE
vuejs/core 升级 3.4.0 Slam Dunk 后 Modal 销毁出问题

### ISSUE THREAD

**Issue by hywater** [vueComponent/ant-design-vue#7239]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
win10，Version 120.0.6099.130，vue 3.4.0

### Reproduction link
[https://3x.antdv.com/components/modal-cn](https://3x.antdv.com/components/modal-cn)

### Steps to reproduce
Modal.confirm 弹窗点击关闭

### What is expected?
正常关闭

### What is actually happening?
弹窗未销毁

**Comment by J1angyue** [comment]
Modal.confirm
也无法正常销毁

**Comment by bootun** [comment]
改下`package.json`里依赖的vue版本,不要用最新版本

**Comment by ZongYan30** [comment]
兄弟，我哭死，降低下vue版本就好了，然后锁死你的依赖文件吧，今天vue更新了，antd-vue受到影响了。

**Comment by wsxe9988** [comment]
antdv可以适配下vue3.4.x了

**Comment by selicens** [comment]
如果必须要使用vue3.4.x可以先使用基本用法的modal，试了下基本用法的model没得问题

**Comment by shuxinqin** [comment]
遇上了同样问题，期待antdv 3也能一起解决！

**Comment by Delevin888** [comment]
我以为我哪里代码写的有问题。。

**Comment by BuzzWoods** [comment]
本地开发执行就没问题，还好有jenkins部署日志去对比依赖

**Comment by savelifeme** [comment]
现在 antdv 3  有退出解决方案吗？如果按照 @selicens 说的手动改，修改内容就太多了，好多页面都涉及到了，

**Comment by savelifeme** [comment]
> 我把vue的版本锁在了3.3.4、antd锁在4.0.8就可以了

如果按照你的解决方案，我这边项目中引用其他插件也有这样的问题，也需要固定版本，那样修改后，就存在好多隐患

**Comment by zaokong** [comment]
现在 antdv 3 有解决方案吗，也发现这个问题了，vue3.3.13     antd-vue是3.2.20，难受

**Comment by peixin-dev** [comment]
> 我也是找了一下午，刚解决

大佬，你是咋解决的  是基于antd-vue 3.x的版本么

**Comment by cc-hearts** [comment]
先固定一下 vue 的版本在 3.3.x 吧，注意看 `lock` 中有实际的 `vue` 版本， 例如 `^3.2.1` 如果没有 `lock`文件的话也会下载到 `3.4.x` 版本的

**Comment by zhou5631** [comment]
@tangjinzhou 修复一下这个问题呢，非常感谢

**Comment by tangjinzhou** [comment]
ref https://github.com/vuejs/core/issues/9975

**Comment by zqhll** [comment]
固定 Vue 3.3.4 ; antd-vue  固定 3.2.15  就能正常销毁了

**Comment by chang-meng** [comment]
玛德耽误我一下午划水时间

**Comment by TurbMZ** [comment]
> 固定 Vue 3.3.4 ; antd-vue 固定 3.2.15 就能正常销毁了

哭死。有其他依赖vue3.4.3的，降版本之后其他依赖就无法使用了

**Comment by BuzzWoods** [comment]
> > 固定 Vue 3.3.4 ; antd-vue 固定 3.2.15 就能正常销毁了
> 
> 哭死。有其他依赖vue3.4.3的，降版本之后其他依赖就无法使用了

为什么会这么快依赖 3.4.3

**Comment by liyunde** [comment]
vue3.4上函数式的不能关闭

**Comment by savelifeme** [comment]
> 8分钟前

找到了一个更接近的版本：

固定 Vue 3.3.13 ; antd-vue 固定 3.2.20 就能正常销毁了

**Comment by muyi0728** [comment]
看到更新只修复了4.x版本3.x的版本不兼容了吗？

**Comment by shuxinqin** [comment]
> 看到更新只修复了4.x版本3.x的版本不兼容了吗？

同问！！！

**Comment by coconutiY** [comment]
vue 3.3.4 ,antdv 3.2.20也无法关闭

**Comment by shuxinqin** [comment]
antdv 3 啥时候能修复啊，vue3.4解析速度确实快，真的很想升级vue3.4，但是项目中使用antdv3，升级就出现这个问题，很无语。

**Comment by Wubrett** [comment]
ε=(´ο｀*)))唉，早应该来这里看看了，我以为我代码写错了嘞

**Comment by BenXi630** [comment]
> vue 3.3.4 ,antdv 3.2.20也无法关闭

解决了吗

**Comment by johnnyhwa** [comment]
3.x版本啥时候适配？

**Comment by coconutiY** [comment]
> > vue 3.3.4 ,antdv 3.2.20也无法关闭
> 
> 解决了吗

看看自己的lock文件的vue版本，如果是3.4.x就去掉package.json里的版本号前^符号,再install一下

**Comment by xinbingyao** [comment]
> > 8分钟前
> 
> 找到了一个更接近的版本：
> 
> 固定 Vue 3.3.13 ; antd-vue 固定 3.2.20 也能正常销毁了

亲测好用~

**Comment by liu3594211** [comment]
> > > 8分钟前
> > 
> > 
> > 找到了一个更接近的版本：
> > 固定 Vue 3.3.13 ；antd-vue 固定 3.2.20 也能正常理智了
> 
> 亲测好用~

我改了，本地可以，但是测试环境上面有不行了

**Comment by liu3594211** [comment]
在本地可以，但是到测试环境就不行了

**Comment by Aliom252181** [comment]
有社区方案了嘛，就是如何在vue3.4.x上用antdv3的函数式Modal？

**Comment by Bassadin** [comment]
> 有社区方案了嘛，就是如何在vue3.4.x上用antdv3的函数式Modal？

I'd be interested in that as well

**Comment by oimmc** [comment]
antdv 3.x和vue3.3.13目前是不存在问题的吧？

**Comment by Bassadin** [comment]
> antdv 3.2.20和vue3.3.13目前是不存在问题的吧？

Vue 3.3.x seems to work fine, yes

**Comment by cc-hearts** [comment]
> [vue@3.4.x](mailto:vue@3.4.x) 和 antdv@3.2.20 可以用嘛？

antdv@3.2.20 建议运行 vue 3.3.x

**Comment by ZedCoding** [comment]
> > [vue@3.4.x](mailto:vue@3.4.x) 和 antdv@3.2.20 可以用嘛？
> 
> antdv@3.2.20 建议运行 vue 3.3.x

就是说antdv@3.2.20 用不了vue@3.4.x ？

**Comment by front-refined** [comment]
vue: 3.5.13，解决了这个问题。👍 
ant-design-vue: 3.2.20

**Comment by ZedCoding** [comment]
> vue: 3.5.13，解决了这个问题。👍 ant-design-vue: 3.2.20

这样可以用于生产了嘛

**Comment by nys013** [comment]
升级vue到3.5，弹窗能关闭，但是后发现存在其他问题，若是不升级ant-design-vue版本，不推荐升级vue版本。详细可看博客https://nys013.github.io/blog/update-vue/
