### ISSUE TITLE
FloatButton 悬浮按钮传入trigger属性时，支持自定义菜单弹出方向

### ISSUE THREAD

**Issue by aShu-guo** [vueComponent/ant-design-vue#7245]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
解决悬浮按钮无法自定义弹出方向的问题

### What does the proposed API look like?
placement: 'top' | 'right' | 'bottom' | 'left'

**Comment by selicens** [comment]
☺️

**Comment by limit81995** [comment]
Is there a solution?I have the same problem.
