### ISSUE TITLE
Dropdown 级联下拉组件自动隐藏的问题

### ISSUE THREAD

**Issue by zyplayer** [vueComponent/ant-design-vue#7246]
- [×] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
Microsoft Edge 版本 120.0.2210.91 (正式版本) (64 位)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/285r2d)

### Steps to reproduce
1. 点击展开下拉
2. 鼠标移动到二级上
3. 鼠标移出级联组件
4. 级联组件直接隐藏了

### What is expected?
级联组件不应该被隐藏，只是应该隐藏展开的二级菜单

### What is actually happening?
级联组件直接隐藏了

**Comment by webvs2** [comment]
这似乎是一个争议：
如果失去二级焦点后，退回第一级，二级菜单会隐藏到；如果超出级联组件范围，整体就会隐藏；这似乎是更正确的逻辑。

举例如。级联组件作为查询条件来使用，当我关注点到其他输入上，这应该被隐藏

**Comment by webvs2** [comment]
我认为这不是一个问题

**Comment by zyplayer** [comment]
如果 Dropdown 的打开方式是 **hover** 这样是没问题的，但是如果是 **click**，在打开后就应该再次点击或点击网页其他空白处才隐藏才对，不应该移到二级之后再移开就自动把整个下拉隐藏了，因为有很多的二级，移动到一个看到不对，再移到其他地方发现整个就隐藏了，又得点击一下

而且专门看了很多的**点击展开**的交互，几乎所有的都不会移出二级把整个下拉隐藏的，antdv3的版本也不会这样~就是这一小点迟迟没能升级到V4  😔 

大佬们能否考虑下呢🙏

**Comment by Aaron-zon** [comment]
我也觉得是个问题，示例中在点击Dropdown展开后鼠标直接移出下拉列表区域是不会关闭Dropdown的，只有在鼠标进入二级，再从二级上移出才会关闭Dropdown。

**Comment by mmmmr** [comment]
🙂
