### ISSUE TITLE
modal confirm不能关闭

### ISSUE THREAD

**Issue by dadianzi** [vueComponent/ant-design-vue#7249]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
{   "name": "workspace",   "private": true,   "version": "0.0.0",   "type": "module",   "scripts": {     "dev": "volar-preview-vite",     "build": "vue-tsc && vite build",     "preview": "vite preview"   },   "dependencies": {     "vue": "^3.3.9",     "ant-design-vue": "^4.0.8"   },   "devDependencies": {     "@codesandbox/vue-preview": "^0.1.1-alpha.16",     "@vitejs/plugin-vue": "^4.5.0",     "typescript": "^5.3.2",     "vite": "^5.0.4",     "vue-tsc": "^1.8.24"   } }

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/vue-demo-dtq63h?file=%2Fpackage.json%3A23%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqyzuw3300073b6hbypnwxht%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqyzuw3300023b6hz4tngs3b%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqyzuw3300043b6hmltfmtor%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqyzuw3300063b6hfsl1vb3h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqyzuw3300023b6hz4tngs3b%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqyzuw3200013b6hnokdriev%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqz04iit00023b6hbe1vy66n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A23%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A23%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqyzuw3300023b6hz4tngs3b%2522%252C%2522activeTabId%2522%253A%2522clqz04iit00023b6hbe1vy66n%2522%257D%252C%2522clqyzuw3300063b6hfsl1vb3h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqyzuw3300053b6ha002odt5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqyzuw3300063b6hfsl1vb3h%2522%252C%2522activeTabId%2522%253A%2522clqyzuw3300053b6ha002odt5%2522%257D%252C%2522clqyzuw3300043b6hmltfmtor%2522%253A%257B%2522id%2522%253A%2522clqyzuw3300043b6hmltfmtor%2522%252C%2522activeTabId%2522%253A%2522clqyzxz7i00bm3b6hc4zealsg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqyzuw3300033b6hddzrb9bb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522clqyzxz7i00bm3b6hc4zealsg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqyzxzfg004kechu2uzm0jwf%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
modal打开后点击取消或者确定都不能关闭

### What is expected?
正常关闭

### What is actually happening?
未关闭，也没有任务错误抛出

**Comment by Forevery1** [comment]
[#7239](https://github.com/vueComponent/ant-design-vue/issues/7239)

**Comment by zhou5631** [comment]
等待作者升级

**Comment by wangcuiling** [comment]
线上出现这种问题要如何解决？固定antd版本吗？

**Comment by aibayanyu20** [comment]
update 4.1

**Comment by agoni1212** [comment]
how about 3.x?

**Comment by mahovsson** [comment]
same issue but version 3.x will it be fixed ?

**Comment by wtagain** [comment]
> update 4.1

So, will version 3.x no longer be maintained?

**Comment by aibayanyu20** [comment]
duplicate #7257 
pr https://github.com/vueComponent/ant-design-vue/pull/7252
