### ISSUE TITLE
语言中文问题

### ISSUE THREAD

**Issue by tsinghua520** [vueComponent/ant-design-vue#725]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
vue2.0

### Reproduction link
[http://localhost:8080/systemConfig/organizational](http://localhost:8080/systemConfig/organizational)

### Steps to reproduce
分页控件中间的Goto切换不到中文，已经在全局更新语言包

### What is expected?
分页控件中间的Goto切换不到英文

### What is actually happening?
分页控件中间的Goto切换不到中文，已经在全局更新

---
import moment from 'moment'
import 'moment/locale/zh-cn'
moment.locale('zh-cn')

**Comment by sendya** [comment]
参考 https://vue.ant.design/components/locale-provider-cn/

![image](https://user-images.githubusercontent.com/5404542/56648613-3e7d7080-66b6-11e9-9c72-ccb6eac45183.png)
