### ISSUE TITLE
ant-design-vue 全局引入 没类型提示

### ISSUE THREAD

**Issue by parlay96** [vueComponent/ant-design-vue#7253]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
ant-design-vue 全局引入 没类型提示

### Reproduction link
[https://www.baidu.com/](https://www.baidu.com/)

### Steps to reproduce
ant-design-vue 全局引入 没类型提示

### What is expected?
ant-design-vue 全局引入 没类型提示

### What is actually happening?
ant-design-vue 全局引入 没类型提示

---
ant-design-vue 全局引入 没类型提示

**Comment by livelyPeng** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/32978177/bccc4b68-ef02-4931-b955-2abf72b8f57c)

**Comment by livelyPeng** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/32978177/b349d202-a2b5-45fc-b613-7a9cb5c300d3)
