### ISSUE TITLE
Search input component replicating id attribute

### ISSUE THREAD

**Issue by ankology** [vueComponent/ant-design-vue#726]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qqy6j89k16)

### Steps to reproduce
Create ```<a-input-search id='test'/>``` component with an id, inspect the code on browser and shows the id attribute duplicate on component structure.

### What is expected?
Non duplicate the id in element structure.

### What is actually happening?
The id given to <a-input-search/> is duplicated.

**Comment by IWANABETHATGUY** [comment]
You should give us a sample at least, use CodeSandbox

**Comment by ankology** [comment]
That's already have a sample.
