### ISSUE TITLE
Modal 对话框使用confirm()，打包后弹窗无法关闭

### ISSUE THREAD

**Issue by yde55188** [vueComponent/ant-design-vue#7261]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue3

### Reproduction link
[https://3x.antdv.com/components/modal-cn](https://3x.antdv.com/components/modal-cn)

### Steps to reproduce
使用confirm()方式弹窗，构建以后无法关闭对话框，我加上
onCancel() {
Modal.destroyAll();
},
onOk() {
Modal.destroyAll();
},
也无法关闭，但是在dev下正常可以关闭，build以后就无法关闭。

### What is expected?
希望可以关闭

### What is actually happening?
build打包以后Modal 对话框无法关闭

**Comment by AKclown** [comment]
我也遇到相同问题，不打包也不可以

**Comment by ZhengXiaowei** [comment]
请问解决了吗 遇到了同样的问题

**Comment by yijunsong-budidiao** [comment]
我也遇到同样问题vue版本3.3.4，ant-design-vue版本3.2.20, 本地运行没有问题，打包上线后就关闭不了。如果升级到vue3.4以上，本地也会有问题。当然，官网的建议是3.2.20对标的是vue的3.3.4版本。
两个解决办法：
1、降低vue版本3.3.0就没有问题
2、升级ant-design-vue到最新4.x也会解决
但是还是希望，出一个ant-design-vue 3.x的修复版本，解决这个问题

**Comment by Maxbsy** [comment]
您好，我这边也遇到的同样的问题，请问您是否已解决，可否把解决方案共享一下呢？
