### ISSUE TITLE
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗

### ISSUE THREAD

**Issue by 13389203735** [vueComponent/ant-design-vue#7262]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗

### Reproduction link
[https://antdv.com/components/overview-cn/](https://antdv.com/components/overview-cn/)

### Steps to reproduce
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗

### What is expected?
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗

### What is actually happening?
日期控件a-range-picker，在打包到测试和线上后，日期控件得到焦点时，无法有效的拉起弹窗

**Comment by szh18** [comment]
兄弟你怎么解决的？我的也是打包到测试后日期弹框拉起弹窗后点击日期后不会收起弹窗，而且日期选择也无效，但是在本地是好的，4.0.8版本

**Comment by aShu-guo** [comment]
参考：https://github.com/vueComponent/ant-design-vue/issues/5842#issuecomment-1314702517
