### ISSUE TITLE
timePicker 组件，被禁止选中的分钟，在只点击小时的情况下，输入框会默认选中被禁止的分钟

### ISSUE THREAD

**Issue by chenxiaoleizi** [vueComponent/ant-design-vue#7267]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
win11，chrome120， 3.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-ant-design-vue-4-0-6-forked-nxpf4m)

### Steps to reproduce
1.禁止选中0-10分
2.只点击小时，再点击确定，输入框的分钟会默认选中0分

### What is expected?
默认不选中被禁止的分钟

### What is actually happening?
被禁止选中的项被默认选中了

**Comment by aShu-guo** [comment]
已确认问题，正在修复

**Comment by chenxiaoleizi** [comment]
> 已确认问题，正在修复
感谢！
