### ISSUE TITLE
input-number using precision attribute was formatted before losing focus in high level of safari

### ISSUE THREAD

**Issue by Gcalolin** [vueComponent/ant-design-vue#7268]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
the problemcan be reproduced directly on the official website.

### Reproduction link
[https://next.antdv.com/components/input-number-cn/#components-input-number-demo-digit](https://next.antdv.com/components/input-number-cn/#components-input-number-demo-digit)

### Steps to reproduce
https://next.antdv.com/components/input-number-cn/#components-input-number-demo-digit

### What is expected?
in safari, input-number using precision attribute should be formatted after blur but should not be formatted when inputing

### What is actually happening?
After testing, it was found that it works fine on Safari 13.1.3, but on Safari 16.5, it will be formatted before losing focus.

**Comment by Tangchen2016** [comment]
I also encountered this problem in version of Safari 17.3. Is there a solution?
