### ISSUE TITLE
Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function

### ISSUE THREAD

**Issue by wowsummer** [vueComponent/ant-design-vue#7273]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
4.1.0

### Reproduction link
[https://www.antdv.com/components/message-cn](https://www.antdv.com/components/message-cn)

### Steps to reproduce
调用官方 message 示例，控制台警告：Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function

<template>
<context-holder />
<a-button type="primary" @click="info">Display normal message</a-button>
</template>
<script lang="ts" setup>
import { message } from 'ant-design-vue';
const [messageApi, contextHolder] = message.useMessage();

const info = () => {
messageApi.info('Hello, Ant Design Vue!');
};
</script>

### What is expected?
不要警告

### What is actually happening?
警告：Missing ref owner context. ref cannot be used on hoisted vnodes. A vnode with ref must be created inside the render function

**Comment by selicens** [comment]
update 4.1.1

**Comment by MrMa98** [comment]
> 更新4.1.1

更新4.1.2也有同样的问题，只能舍弃[Hooks 调用]用open
