### ISSUE TITLE
文档上面Notification组件,hooks调用里面那四个按钮点一下，就会报错，导致别的组件页面不会切换

### ISSUE THREAD

**Issue by concealmyface** [vueComponent/ant-design-vue#7274]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
文档

### Reproduction link
[https://www.antdv.com/components/notification-cn](https://www.antdv.com/components/notification-cn)

### Steps to reproduce
文档上面Notification组件,hooks调用里面那四个按钮点一下，就会报错，导致别的组件页面不会切换

### What is expected?
正常

### What is actually happening?
报错

---
没了

**Comment by selicens** [comment]
update 4.1.1
