### ISSUE TITLE
BUG: AutoComplete   InputSearch或Textarea时 在输入框连续切换会导致无法输入

### ISSUE THREAD

**Issue by wang22295881** [vueComponent/ant-design-vue#7276]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
我使用的操作系统:macOS Sonoma:14.2  使用谷歌、火狐浏览器分别对官网auto-complete 进行了测试都出现了问题

### Reproduction link
[https://www.antdv.com/components/auto-complete](https://www.antdv.com/components/auto-complete)

### Steps to reproduce
1.进入官网auto-complete模块：例如：查询模式 - 不确定类目
2.在搜索框里 输入中文 删除继续输入 英文字母 数字 之后会突然导致输入不进去
竟发现不使用 input-search 与 textarea的没有这个问题

### What is expected?
正常应该无障碍输入

### What is actually happening?
个人感觉是在增加了input 时emit 传递出现了问题

**Comment by Diven-xinhai** [comment]
我也遇到了这个问题，在配合使用textarea的时候出现的：
1. 一开始就输入中文，就会出现输入不上问题；
2. 一开始输入非中文，再全部删除后再次输入中文，也会出现输入不上的问题；
尝试用watch监听value时出现问题会监听不上。

**Comment by alongw** [comment]
我在使用 <template #default /> 嵌入 <a-input /> 时也有这个问题

**Comment by aShu-guo** [comment]
问题已确认

**Comment by aShu-guo** [comment]
问题已修复，已合并到主分支
