### ISSUE TITLE
文档表格组件展开报错, 导致展开不了, 自己项目也有一样的情况

### ISSUE THREAD

**Issue by concealmyface** [vueComponent/ant-design-vue#7278]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
文档

### Reproduction link
[https://www.antdv.com/components/table-cn#components-table-demo-nested-table](https://www.antdv.com/components/table-cn#components-table-demo-nested-table)

### Steps to reproduce
点击展开会报错

### What is expected?
正常

### What is actually happening?
Cannot read properties of null (reading 'isCE')

---
4.0.8版本也有

**Comment by selicens** [comment]
#7265

**Comment by selicens** [comment]
update 4.1.1
