### ISSUE TITLE
表格数据量大时,组件销毁卡顿问题

### ISSUE THREAD

**Issue by wexz** [vueComponent/ant-design-vue#728]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
vue 2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/m3o1w20j9)

### Steps to reproduce
示例

### What is expected?
数据小于1000 销毁速度小于1秒

### What is actually happening?
加载数据时的卡顿可以理解, 但是清除数据时同样造成UI严重卡顿

---
这边的需求是按每页500条显示(可能更多 < 1000)  , 由于业务需求 分页数据是自己计算的, 已排除其他个人代码性能问题

**Comment by sendya** [comment]
尝试结合 [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) 带有虚拟化（virtualization）功能，能够提高数据量大时候长列表的性能。

**Comment by IWANABETHATGUY** [comment]
这的确是个问题，我刚才试了下用iview，清除时非常快。

**Comment by IWANABETHATGUY** [comment]
@wexz 在使用v-if消除table组件时，组件会递归调用destroy 方法销毁所有组件，否则会内存泄漏，这样做是非常合理的，https://cn.vuejs.org/v2/cookbook/avoiding-memory-leaks.html，官网也是推荐这样做的。你可以尝试使用虚拟列表代替，如果没有其他的问题可以把issue关了吧。

**Comment by 604587986** [comment]
确实 是这样，而且我的树形表格数据过多，造成destroy卡顿，谁有解决方法吗
