### ISSUE TITLE
Failed to resolve import "ant-design-vue/es/default/style/css.js" from "src/entry/main.js". Does the file exist?

### ISSUE THREAD

**Issue by wjf-richard** [vueComponent/ant-design-vue#7280]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
vue:2.7.0/vite:3.2.4/

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
pnpm run build

### What is expected?
build  sucess

### What is actually happening?
error during build:
Error: Failed to resolve import "ant-design-vue/es/default/style/css.js" from "src/entry/main.js". Does the file exist?

**Comment by cc-hearts** [comment]
need reproduce

**Comment by checklittlelee** [comment]
same issue

**Comment by Sheepeer** [comment]
This issue accured after I used unplugin-vue-components to load antd-vue components. My config is like this:
```
import Components from "unplugin-vue-components/vite"
import { AntDesignVueResolver } from "unplugin-vue-components/resolvers"

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
    Components({
      resolvers: [AntDesignVueResolver()]
    })
  ],
...
```

**Comment by Sheepeer** [comment]
The err msg is: **Failed to resolve import "ant-design-vue/es/layout/style/css" from "src/layouts/MainLayout.vue". Does the file exist?**
I checked the path, found that in which there's actrully no file. Is there something wrong with AntDesignVueResolver?
![image](https://github.com/vueComponent/ant-design-vue/assets/78125933/2ad81b7a-c88a-425e-90c8-8fb39b4f57d9)

**Comment by Sheepeer** [comment]
Found the key!
Just add importStyle: 'css-in-js' or 'less' to the resolver, it works:
```
resolvers: [
        AntDesignVueResolver({
          // importStyle: 'css-in-js'
          importStyle: 'less'
        })
      ]
```
