### ISSUE TITLE
select组件的下拉框，在页面滚动时不跟随，像定在屏幕中间一样

### ISSUE THREAD

**Issue by yajzhang1** [vueComponent/ant-design-vue#7285]
https://github.com/vueComponent/ant-design-vue/assets/156650796/74a2f1c1-f241-4d0b-9157-daf335c6453f

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
mac, windows, chrome

### Reproduction link
[https://antdv.com/components/select-cn](https://antdv.com/components/select-cn)

### Steps to reproduce
select组件的下拉框，在页面滚动时不跟随，像定在屏幕中间一样

### What is expected?
下拉框跟随页面的select组件滑动

### What is actually happening?
不跟随

**Comment by mmmmr** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/91053541/83dc475d-ad0e-4bd0-9140-064beae651cb)

**Comment by yajzhang1** [comment]
感谢，已解决
