### ISSUE TITLE
vite + vue3.4.10项目中使用含三角图标的组件如tooltip时，三角形图标的css 属性clip-path出现NaNpx，导致三角图标失效。（ant官网案例没有这个问题）

### ISSUE THREAD

**Issue by Tommyshellby** [vueComponent/ant-design-vue#7286]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
vue@3.4.10

### Reproduction link
[https://next.antdv.com/components/tooltip-cn](https://next.antdv.com/components/tooltip-cn)

### Steps to reproduce
使用有三角图标的组件

### What is expected?
正常显示三角图标

### What is actually happening?
三角形图标的css 属性clip-path出现NaNpx，导致三角图标显示异常

---
vite   vue3.4.10项目有问题，ant官网案例正常

**Comment by isnl** [comment]
蹲个后续

**Comment by 970319330** [comment]
![Uploading 1711349694830.jpg…]()

**Comment by 970319330** [comment]
![Uploading 1711349694830.jpg…]()

**Comment by isnl** [comment]
> 蹲个后续

大意了，我的问题：在使用a-config-provider组件注入主题样式borderRadius的时候，用的是borderRadius: '4px'而非 borderRadius: 4

改成数字就好了

**Comment by 970319330** [comment]
> > 蹲个后续
> 
> 大意了，我的问题：在使用a-config-provider组件注入主题样式borderRadius的时候，用的是borderRadius: '4px'而非 borderRadius: 4
> 
> 改成数字就好了

真及时
