### ISSUE TITLE
表格拖拽列宽功能无效（官方示例也拖不动了）

### ISSUE THREAD

**Issue by yourcf** [vueComponent/ant-design-vue#7287]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
vue

### Reproduction link
[https://antdv.com/components/table-cn#components-table-demo-resizable-column](https://antdv.com/components/table-cn#components-table-demo-resizable-column)

### Steps to reproduce
表格拖拽列宽功能无效（官方示例也拖不动了）

### What is expected?
可以实现拖动调整列宽

### What is actually happening?
无法拖动

**Comment by wsxe9988** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/5828057/6ac4c262-35a7-49b3-ac2e-6a4d527254a0)
还是之前嵌套子表格的出现的问题。

**Comment by wsxe9988** [comment]
@selicens

**Comment by kovsu** [comment]
应该是修好了还没发版

**Comment by selicens** [comment]
> ![image](https://private-user-images.githubusercontent.com/5828057/296959231-6ac4c262-35a7-49b3-ac2e-6a4d527254a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MDA3MDQsIm5iZiI6MTcwNTQwMDQwNCwicGF0aCI6Ii81ODI4MDU3LzI5Njk1OTIzMS02YWM0YzI2Mi0zNWE3LTQ5YjMtYWMyZS02YTRkNTI3MjU0YTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTZUMTAyMDA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQyOTJkY2M2OTc2ZmI3OGNmMGNjNTliZTAzMGQ1OTUwOGU0ZThjNTg5OTU4ODgyZDQ3NGU3YmQyZWNmNWU1NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VGSEtn_BbMfwRRrmJzJFCXE9onUNk_32l3A3FA8CrYM) 还是之前嵌套子表格的出现的问题。

等待pr合并

**Comment by wsxe9988** [comment]
@selicens 官网上还是最新版本还是4.1.0，不是4.1.1，官网这块能更新么

**Comment by selicens** [comment]
> @selicens 官网上还是最新版本还是4.1.0，不是4.1.1，官网这块能更新么

唐老师空下来会更的

**Comment by lessin123** [comment]
看官网table 里面不行拖拽呀  刚产品提需求问能不能实现拖拽...

**Comment by selicens** [comment]
> 看官网table 里面不行拖拽呀 刚产品提需求问能不能实现拖拽...

可以暂时将vue版本固定到3.3.x，如package.json里vue的版本将^改为~

**Comment by selicens** [comment]
update to 4.1.2
