### ISSUE TITLE
vue 升级3.4.14 之后  treeSelect 组件中dropdownStyle 设置 { display: 'none' } 未生效

### ISSUE THREAD

**Issue by tonysun03** [vueComponent/ant-design-vue#7293]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Vue 3.4.14

### Reproduction link
[https://stackblitz.com/edit/vue-veduhh?file=src%2Fcomponents%2Ftest.vue](https://stackblitz.com/edit/vue-veduhh?file=src%2Fcomponents%2Ftest.vue)

### Steps to reproduce
见链接

### What is expected?
display 生效

### What is actually happening?
display 未生效

**Comment by cc-hearts** [comment]
I'll try to fix it

[ref](https://github.com/vuejs/core/pull/10075)

**Comment by cc-hearts** [comment]
vue 在 [3.4.20](https://github.com/vuejs/core/blob/main/CHANGELOG.md#3420-2024-02-26) 中修复了这个问题 。
