### ISSUE TITLE
nanopop包升级，使用者需要升级到node20版本

### ISSUE THREAD

**Issue by ColourfulU** [vueComponent/ant-design-vue#7298]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
win11、Chrome120.0.6099.218、Vue3.4.14

### Reproduction link
[https://sfile.chatglm.cn/img2text/a723ff5f-32c0-4fd0-a111-92e58eb75eec.jpg](https://sfile.chatglm.cn/img2text/a723ff5f-32c0-4fd0-a111-92e58eb75eec.jpg)

### Steps to reproduce
将node_modules及lock文件删除，重新安装ant-design-vue时控制台会报错

### What is expected?
不报错，能正常安装

### What is actually happening?
ant-design-vue依赖了@simonwep/pickr@1.8.2，1.8.2版本没有固定nanopop的版本

---
希望将依赖包@simonwep/pickr固定到1.9.0版本即可解决问题

**Comment by shawn-web** [comment]
同样的问题，我用的是ant-design-vue@1.6.5存在这个问题，回退到1.6.2可以解决这个问题，但是还用了k-form-design，他所引用的是ant-design-vue@1.7.8,最低版本引用的也是1.7.2，目前还没想到什么处理方案。

**Comment by shawn-web** [comment]
nanopop [issues27](https://github.com/simonwep/nanopop/issues/27)，这个问题昨天已经被关闭了，但是还是没有解决node依赖20的问题，作者提供了解决方案[/axios#5026](https://github.com/axios/axios/issues/5026)

**Comment by ColourfulU** [comment]
ant-design-vue官方如果将依赖@simonwep/pickr固定到1.9.0就可以解决问题

**Comment by shawn-web** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/42370950/3c4faaaa-bab3-4b75-b457-88c78d6969c2)

**Comment by ColourfulU** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/65552891/bed41b7e-2c29-4925-ae09-de607542a6de)
我试了在devDependencies中加入这个包，npm和pnpm是可以的，但是yarn还是不行

**Comment by ColourfulU** [comment]
> ![image](https://private-user-images.githubusercontent.com/42370950/297964639-3c4faaaa-bab3-4b75-b457-88c78d6969c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NTA0NTUsIm5iZiI6MTcwNTY1MDE1NSwicGF0aCI6Ii80MjM3MDk1MC8yOTc5NjQ2MzktM2M0ZmFhYWEtYmFiMy00Yjc1LWI0NTctODhjNzhkNjk2OWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE5VDA3NDIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YWE5YjNjNGE4MGVlMjhhOTA1YTJjNzIzYWEzYzYwOGVhZWMwM2M3NDRmZmQ3NTAyMDFkYzNlMDJhZGZhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9ghZtCME7YPkXvx-e-hmbZOSlHCvWa5txDbDu0sktX0) 这样是可以解决的，亲测有效

这个方法挺好用的，学到了
