### ISSUE TITLE
紧急：select组件，在dropdownRender里加了一个input组件，input退格时，select多选的内容会跟随退格

### ISSUE THREAD

**Issue by yajzhang1** [vueComponent/ant-design-vue#7299]
https://github.com/vueComponent/ant-design-vue/assets/156650796/cfc04de2-4881-4149-9c68-c5420858d6d1

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.7

### Environment
mac, windows, chrome

### Reproduction link
[https://antdv.com/components/select-cn](https://antdv.com/components/select-cn)

### Steps to reproduce
select组件，在dropdownRender里加了一个input组件，input退格时，select多选的内容会跟随退格

### What is expected?
select多选内容不跟着撤销

### What is actually happening?
跟随dropdownRender 的input撤销了

**Comment by cc-hearts** [comment]
需要提供一下复现的代码

**Comment by yajzhang1** [comment]
<script setup lang="ts">
  import {
    watch, ref, defineComponent, onMounted
  } from 'vue';

  import {
    SearchOutlined, CloseOutlined
  } from '@ant-design/icons-vue';

  interface Props {
    options: any
    placeholder: string
    searchPlaceholder: string
    value: any
    allowClear: boolean
    disabled: boolean
    labelInValue: boolean
    showSelectAll: boolean
  }

  const props = withDefaults(defineProps<Props>(), {
    options: [],
    placeholder: '',
    searchPlaceholder: '',
    value: null,
    allowClear: false,
    disabled: false,
    labelInValue: false,
    showSelectAll: false
  });

  const emit = defineEmits();

  const selectValue: any = ref(null);

  const filterItem: any = ref(null);

  const selectOptions: any = ref([]);

  const selectAll = ref(false);

  watch(() => props.value, async (value: boolean) => {
    selectValue.value = value;
  }, { deep: true, immediate: true });

  watch(() => props.options, async (value: boolean) => {
    if (filterItem.value) {
      filterOption();
    } else {
      selectOptions.value = value;
    }
  }, { deep: true, immediate: true });

  watch(() => selectAll.value, (value: boolean) => {
    if (value) {
      selectValue.value = [];
      selectOptions.value.forEach((item: any) => {
        if (props.labelInValue) {
          selectValue.value.push(item);
        } else {
          selectValue.value.push(item.value);
        }
      });
    } else {
      selectValue.value = [];
    }
  });

  const filterOption = () => {
    selectOptions.value = [];
    props.options.filter((option: any) => {
      if (option.label.toLowerCase().indexOf(filterItem.value.toLowerCase()) >= 0) {
        selectOptions.value.push(option);
      }
    });
  }

  const valueChange = (ev: any) => {
    emit('update:value', selectValue.value);
    emit('change', ev);
  }

  const VNodes: any = defineComponent({
    props: {
      vnodes: {
        type: Object,
        required: true,
      },
    },
    render() {
      return this.vnodes;
    },
  });

  onMounted(() => {
    // document.addEventListener('keydown', (ev) => {
    //   if (ev.keyCode === 8) {
    //     ev.preventDefault();
    //     return false;
    //   }
    // });
  });
</script>

<template>
  <a-select
    v-model:value="selectValue"
    :options="selectOptions"
    option-label-prop="label"
    mode="multiple"
    :showSearch="false"
    :placeholder="placeholder"
    :allowClear="allowClear"
    :label-in-value="labelInValue"
    :getPopupContainer="triggerNode => triggerNode.parentNode"
    :disabled="disabled"
    @change="valueChange"
  >
    <template #tagRender="{ label, closable, onClose }">
      <a-tag color="#ecf2fe" :bordered="false" :closable="closable" @close="onClose">
        <label style="color: #2c68ff;">{{ label }}</label>
        <template #closeIcon>
          <CloseOutlined :style="{color: '#2c68ff'}"/>
        </template>
      </a-tag>
    </template>
    <template #dropdownRender="{ menuNode: menu }">
      <div class="pb-2 pt-1 mx-1">
        <a-input :placeholder="searchPlaceholder" @change="filterOption" v-model:value="filterItem" allow-clear>
          <template #suffix>
            <SearchOutlined />
          </template>
        </a-input>
      </div>
      <a-space v-if="showSelectAll" style="padding: 4px 8px; margin-bottom: 4px;">
        <a-checkbox v-model:checked="selectAll">全选</a-checkbox>
      </a-space>
      <v-nodes :vnodes="menu" />
      <slot></slot>
    </template>
  </a-select>
</template>

<style lang="scss" scoped>
</style>

**Comment by yajzhang1** [comment]
> Hello @yajzhang1. Please provide a online reproduction by forking this [link for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [link for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) or a minimal GitHub repository. Make sure to choose the correct version.
> 
> 你好 @yajzhang1, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处 for vue2](https://codesandbox.io/s/2wpk21kzvr)、 [此处 for vue3](https://codesandbox.io/s/agitated-franklin-1w72v) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。请确保选择准确的版本。

https://codesandbox.io/p/sandbox/distracted-mountain-m2zrf7?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A105%2C30

构建了一个在线实例，辛苦看下

**Comment by cc-hearts** [comment]
提供的代码并没有复现出这个问题🤔
[sandbox](https://codesandbox.io/p/sandbox/reverent-mahavira-k4cqc5?file=%2Fsrc%2Fmain.js%3A3%2C1)

**Comment by yajzhang1** [comment]
> 提供的代码并没有复现出这个问题🤔 [sandbox](https://codesandbox.io/p/sandbox/reverent-mahavira-k4cqc5?file=%2Fsrc%2Fmain.js%3A3%2C1)

有呢有呢，一按回车，选中的就消失了

**Comment by tiansQAQ** [comment]
> > 提供的代码并没有复现出这个问题🤔 [sandbox](https://codesandbox.io/p/sandbox/reverent-mahavira-k4cqc5?file=%2Fsrc%2Fmain.js%3A3%2C1)
> 
> 有呢有呢，一按回车，选中的就消失了

当选中下拉列表的一个元素的时候，会有一个灰色的高亮效果。这个是个回车的快捷键，进行选中和取消选中。

**Comment by jack-7788** [comment]
<img width="378" alt="Snipaste_2024-01-29_10-37-36" src="https://github.com/vueComponent/ant-design-vue/assets/70838383/bcea54e1-1096-4d25-b8bb-b47e7da57e2a">
取消回车键的默认行为

**Comment by aShu-guo** [comment]
正如@tiansQAQ 说的那样，回车键的效果等同于click。你可以测试将鼠标放在下拉框的选项上，此时不要点击，触发回车键则会选中当前选项，再次触发则会取消。
