### ISSUE TITLE
table checkbox选择，不兼容vue3.4.13版本

### ISSUE THREAD

**Issue by caser993** [vueComponent/ant-design-vue#7300]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.1

### Environment
macOS 14.2.1，window11，chrome120.0.6099.234，vue3.4.13

### Reproduction link
[https://www.antdv.com/components/table-cn#components-table-demo-nested-table](https://www.antdv.com/components/table-cn#components-table-demo-nested-table)

### Steps to reproduce
checkbox选择报错不可选中，报错信息：Uncaught (in promise) TypeError: Cannot read properties of null (reading 'isCE') at renderSlot (runtime-core.esm-bundler.js:2952:32)
<img width="690" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/127269969/14651860-6ecf-4004-8c5f-03c33602c16e">

### What is expected?
check可选择并返回正常值

### What is actually happening?
问题同#7260，但是升级后并未解决checkbox情况

**Comment by wsxe9988** [comment]
update 4.1.1

**Comment by caser993** [comment]
> update 4.1.1

已升级，无效～

**Comment by caser993** [comment]
> @selicens @tangjinzhou 两位老是看一下

vue版本回退到vue3.3.13表现正常，升级vue3.4.x问题复现

**Comment by selicens** [comment]
我复现一下

**Comment by selicens** [comment]
@caser993 什么场景下点击无效，目前官网demo是vue3.4.x和antdv4.1.1，没有选择框点击报错的情况

**Comment by wsxe9988** [comment]
https://antdv.com/components/table-cn#components-table-demo-resizable-column[可伸缩列]
![image](https://github.com/vueComponent/ant-design-vue/assets/5828057/219ebbed-c990-4d74-bea1-280de8cc3802)
目前官网demo是vue3.4.5和antdv4.1.1 官网的例子就能复现，浏览器清除缓存后还不行。@selicens @tangjinzhou

**Comment by wsxe9988** [comment]
> > update 4.1.1
> 
> 已升级，无效～

你提供的复现例子是官网Table例子中的嵌套子表格例子，经测试，没有你截图中报的错误

**Comment by selicens** [comment]
@wsxe9988 ok

**Comment by selicens** [comment]
@cc-hearts 我看到你之前要提的pr关闭了，目前table resizable-column的demo拖拽会报错，和你想修复的有关联，你再提一个pr吧
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/02c4bacf-7bc0-4417-bd6d-39e20b8e185a)

**Comment by cc-hearts** [comment]
> @cc-hearts 我看到你之前要提的pr关闭了，目前table resizable-column的demo拖拽会报错，和你想修复的有关联，你再提一个pr吧
> 
> ![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/02c4bacf-7bc0-4417-bd6d-39e20b8e185a)
> 
> 

[ref](#7291)

**Comment by AKclown** [comment]
当vue@3.3.15和ant-design-vue@4.0.8时拖动table 也会报同样的错误，isCE...。 将vue降级为vue@3.3.12行为正常

**Comment by selicens** [comment]
update to 4.1.2
