### ISSUE TITLE
下拉框扩展菜单不支持嵌入输入框

### ISSUE THREAD

**Issue by x-wink** [vueComponent/ant-design-vue#7304]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.8

### Environment
windows 10，chrome118.0.5993.118，vue3.2.47

### Reproduction link
[https://baidu.com](https://baidu.com)

### Steps to reproduce
<a-select v-model:value="picked" :options="list">
<template #dropdownRender="{ menuNode }">
<div class="create-category">
<a-input-search
ref="refsInput"
v-model:value="name"
@search="handleCreate"
@mousedown="(e) => e.preventDefault()"
@click="refsInput.focus()"
>
<template #enterButton>
<a-button type="primary">创建</a-button>
</template>
</a-input-search>
</div>
<component :is="menuNode" />
</template>
</a-select>

### What is expected?
按照示例代码取消鼠标按下默认事件后输入框不能聚焦，使用ref强行聚焦也会导致面板关闭

### What is actually happening?
输入框能聚焦并且下拉面板不会关闭

---
我还尝试过手动控制open属性，点击下拉框本体切换面板显示与隐藏，并且通过on-click-outside组件并设置忽略下拉框本地才实现了点击外部关闭面板，但是这样选完选项只能通过下拉框的change事件来设置open=false，导致点击已选中选项时不会关闭面板，尝试了各种方法依然无法实现，真的气得吐血，难怪官方示例中只能写死add New Item。这真是我见过最傻逼的组件

**Comment by selicens** [comment]
update 4.x，谩骂并不能解决问题

**Comment by YvesChen** [comment]
升级框架吧，3.0的框架确实会有问题，我升级的版本"ant-design-vue": "^4.1.2",

**Comment by eloves** [comment]
@x-wink 认栽吧，老铁，4.x完全没问题。3.x可以通过select的open来强控，最外div上的mousedown事件里加个状态，然后在dropdownVisibleChange事件里判断要不要open
```js
dropdownVisibleChange(open) {
    if (this.opening) {
        this.opening = false
    } else {
        this.selectOpen = open
    }
},
onMousedown(e) {
    e.preventDefault()
    this.opening = true
}
```

**Comment by zwl098** [comment]
> @x-wink 认栽吧，老铁，4.x完全没问题。3.x可以通过select的open来强控，最外div上的mousedown事件里加个状态，然后在dropdownVisibleChange事件里判断要不要open
> 
> ```js
> dropdownVisibleChange(open) {
>     if (this.opening) {
>         this.opening = false
>     } else {
>         this.selectOpen = open
>     }
> },
> onMousedown(e) {
>     e.preventDefault()
>     this.opening = true
> }
> ```
老哥,这个this.selectOpen就是控制select的open吗,那这个  this.opening 是控制什么的呀,有点没搞懂,求指教

**Comment by zwl098** [comment]
```javascript
                <div
                  @mouseleave="selectOpen = false"
                  @mousedown="e => {
                    e.preventDefault()
                    this.selectOpen = true
                  }" >
                  <a-select
                    mode="multiple"
                    :open="selectOpen"
                    :getPopupContainer=" (triggerNode) => { return triggerNode.parentNode || document.body; } "
                  >
                    <div slot="dropdownRender" slot-scope="menu">
                      <v-nodes :vnodes="menu" />
                      <a-divider style="margin: 4px 0;" />
                      <div @mousedown="e => e.preventDefault()" >
                        <a-input ref="innerInput" @click="$refs.innerInput.focus()" ></a-input>
                      </div>
                    </div>
                  </a-select>
                </div>
```
我试了这样是可以的,希望能对同样遇到这个问题的人有帮助

**Comment by return1990** [comment]
老项目（v1.7.5）遇到同样的问题，用上面老哥的方法会导致 popup  异常，修改了一下：

```
<div @mousedown="handleSelectMouseDown">
  <a-select
    ref="selectRef"
    :open="selectOpen"
  >
    <div slot="dropdownRender" slot-scope="menu">
      <v-nodes :vnodes="menu"/>
      <a-divider style="margin: 4px 0;"/>
      <div @mousedown="e => e.preventDefault()">
        <a-input> <a-icon slot="suffix" type="plus" @click="() => {}"/> </a-input>
      </div>
    </div>
  </a-select>
</div>


handleSelectMouseDown(e) {
  e.preventDefault()
  this.selectOpen = true

  this.cleanupMouseLeaveListener()

  this.mouseLeaveHandler = () => {
    this.selectOpen = false
  }

  this.$nextTick(() => {
    this.$refs.selectRef?.popupRef?.$el.addEventListener('mouseleave', this.mouseLeaveHandler)
  })
},

cleanupMouseLeaveListener() {
  if (this.mouseLeaveHandler) {
    this.$refs.selectRef?.popupRef?.$el.removeEventListener('mouseleave', this.mouseLeaveHandler)
    this.mouseLeaveHandler = null
  }
},
```
