### ISSUE TITLE
下拉菜单-右键菜单配合arrow属性使用 ，剪头错位

### ISSUE THREAD

**Issue by wangziyi0526** [vueComponent/ant-design-vue#7305]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
chrome浏览器

### Reproduction link
[https://www.antdv.com/components/dropdown-cn](https://www.antdv.com/components/dropdown-cn)

### Steps to reproduce
下拉菜单 右键菜单 配合arrow 箭头错位

### What is expected?
箭头正常显示

### What is actually happening?
箭头错位
![image](https://github.com/vueComponent/ant-design-vue/assets/26397622/4eeccd05-c4fc-41c2-98c3-1acd6cff2dfd)

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/5d774778-cb6f-4591-b42e-d392de1c2fde)
