### ISSUE TITLE
select 多选时，悬浮在选项上的高亮，在内容浮层关闭后，再次点击下拉，之前的选项依然会高亮，但是单选就不会；这个是功能特性吗（官方的示例也是这样的），如果不想要这个高亮怎么处理？

### ISSUE THREAD

**Issue by Miss-An** [vueComponent/ant-design-vue#7307]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
windows ,chrome、vue3

### Reproduction link
[https://3x.antdv.com/components/select-cn/#components-select-demo-custom-dropdown](https://3x.antdv.com/components/select-cn/#components-select-demo-custom-dropdown)

### Steps to reproduce
select 设置多选；
鼠标悬浮到一个选项上会高亮，然后移除内容浮层
点击浮层关闭后，再次打开下拉内容浮层，之前的高亮还在

### What is expected?
再次打开下拉内容浮层，之前的高亮消失

### What is actually happening?
再次打开下拉内容浮层，之前的高亮没有消失

**Comment by selicens** [comment]
这一项被选择了

**Comment by Miss-An** [comment]
> 这一项被选择了

并没有选中这一项，只是鼠标移上去了，但是没有点击选中

**Comment by qppq54s** [comment]
研究了下代码，应该是选择的浮层关闭时，没有清除当前“聚焦”导致的。

**Comment by qppq54s** [comment]
发现一个方法，可以实现你要的功能。

**Comment by Miss-An** [comment]
这种方式可能每个都要单独处理
