### ISSUE TITLE
RangePickerProps无法import

### ISSUE THREAD

**Issue by hemingxing** [vueComponent/ant-design-vue#7308]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
mac os;vue:^3.3.4

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/4.1.0](https://github.com/vueComponent/ant-design-vue/tree/4.1.0)

### Steps to reproduce
import { RangePickerProps } from 'ant-design-vue';

### What is expected?
可以正常引入

### What is actually happening?
“"ant-design-vue"”没有导出的成员“RangePickerProps”。你是否指的是“TimeRangePickerProps”?

**Comment by qppq54s** [comment]
import type { RangePickerProps } from 'ant-design-vue';
这样好像可以
