### ISSUE TITLE
antd table升降序失效

### ISSUE THREAD

**Issue by AlbertEjiestein** [vueComponent/ant-design-vue#7309]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
mac,chrome 120.0.6099.216,vue2

### Reproduction link
[https://zanwufatigonglianjie](https://zanwufatigonglianjie)

### Steps to reproduce
columns = [{
dataIndex: "likeCount",
sorter: true,
className: "align-right",
slots: { title: "likeCount" },
sortKey: 1,
width: 120
}]

### What is expected?
期望使用插槽时，同时允许升降序能生效

### What is actually happening?
使用插槽时，sorter和slots会冲突，导致升降序失效，查看日志是一直返回ascend（实际是需要多次点击降序才能切换成功）
类似案例，但具体使用有差异无法复用：https://blog.csdn.net/qq_27674439/article/details/128717417

**Comment by tiansQAQ** [comment]
这个组件库老版本1.xxbug挺多的，新项目最好不要用了。
