### ISSUE TITLE
DatePicker 的 presets 每次选择都是组件挂载时候的时分秒 [官网组件案例亦如此]

### ISSUE THREAD

**Issue by shenmenga** [vueComponent/ant-design-vue#7311]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
chrome 120.0.6099.234(正式版本） (arm64)

### Reproduction link
[https://next.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges](https://next.antdv.com/components/date-picker-cn#components-date-picker-demo-presetted-ranges)

### Steps to reproduce
获取焦点，选择快捷范围，时分秒的时间停留在组件挂载的时刻

### What is expected?
每次点击应该获取当前时刻

### What is actually happening?
null

**Comment by mmmmr** [comment]
#7316 这个好像可以解决你的问题

**Comment by rauki** [comment]
> #7316这个希望可以解决你的问题

这是antd，antdv还是不支持动态配置。

**Comment by bsuooo** [comment]
> > #7316这个希望可以解决你的问题
> 
> 这是antd，antdv还是不支持动态配置。

不，那是我提的 pr， 但是没有被合并。
等官方支持吧
