### ISSUE TITLE
Select 选择器回车显示错误的值

### ISSUE THREAD

**Issue by StevenTang1994** [vueComponent/ant-design-vue#7314]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
win10,vue3 Chrome浏览器版本120.0.6099.225

### Reproduction link
[https://3x.antdv.com/components/select-cn#components-select-demo-tags](https://3x.antdv.com/components/select-cn#components-select-demo-tags)

### Steps to reproduce
```
<a-select
    ref="select"
    v-model:value="searchFormValueRef.demo"
    style="width: 120px"
    allowClear
>
    <a-select-option value="jack">Jack</a-select-option>
    <a-select-option value="lucy">Lucy</a-select-option>
    <a-select-option value="disabled" disabled>Disabled</a-select-option>
    <a-select-option value="Yiminghe">yiminghe</a-select-option>
</a-select>
<srcipt setup>
import { ref } from 'vue';
const searchFormValueRef = ref({});
</srcipt>
```
第一步 我点击选择器,选择内容会出来
第二步 不选择任何内容,直接在点击选择器,选择内容会关闭
第三步 按回车,选择器里面有意外的值

### What is expected?
按回车之后应该不会有值出现

### What is actually happening?
按回车之后会有意外的值

---
需求是按回车查询表格内容。但是现在遇到，我不选任何值，只是点了一下下拉框，在关闭下拉框，按回车查询，下拉框有意外的值，从而影响查询条件

**Comment by qppq54s** [comment]
可以把 defaultActiveFirstOption 设置为 false

**Comment by StevenTang1994** [comment]
> 可以把 defaultActiveFirstOption 设置为 false

我使用的版本是Antdv 3.2.20 没有看到这个defaultActiveFirstOption这个属性
能否详细介绍一下 谢谢
![image](https://github.com/vueComponent/ant-design-vue/assets/24404599/21cf47ab-e2b5-495a-a3d1-616daa93d0c6)

**Comment by jack-7788** [comment]
<img width="378" alt="Snipaste_2024-01-29_10-37-36" src="https://github.com/vueComponent/ant-design-vue/assets/70838383/5cb5efe9-e3ce-44b1-82c6-120ba30fa7b3">
将  onInputKeyDown 事件 取消 回车键的默认行为

**Comment by StevenTang1994** [comment]
1. 我设置了allowClear 
2. 我随便选中一个值选中之后 
3. 在×掉他 
4. 在按回车 
5. 还是会有意外的值出现

**Comment by StevenTang1994** [comment]
> 可以把 defaultActiveFirstOption 设置为 false

我设置了allowClear
我随便选中一个值选中之后
在×掉他
在按回车
还是会有意外的值出现

**Comment by StevenTang1994** [comment]
> <img alt="Snipaste_2024-01-29_10-37-36" width="378" src="https://private-user-images.githubusercontent.com/70838383/300319224-5cb5efe9-e3ce-44b1-82c6-120ba30fa7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzE5NjQsIm5iZiI6MTcwNjY3MTY2NCwicGF0aCI6Ii83MDgzODM4My8zMDAzMTkyMjQtNWNiNWVmZTktZTNjZS00NGIxLTgyYzYtMTIwYmEzMGZhN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAzMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYWExNjBmYzI2NjViNGRiOTA1ZWEyNDFiMzAxNjQ5ZmI1OTI4ZTMxMGZkZGJiZjVmM2Q2ZjYwYzRhNzYwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTSi73_-XUm1baNxsRZ4UsIizc4r83sXqv6bMtu1X2o"> 将 onInputKeyDown 事件 取消 回车键的默认行为

请问一下 这个是要改源码吗  我没有找到这段代码

**Comment by jack-7788** [comment]
> > <img alt="Snipaste_2024-01-29_10-37-36" width="378" src="https://private-user-images.githubusercontent.com/70838383/300319224-5cb5efe9-e3ce-44b1-82c6-120ba30fa7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzE5NjQsIm5iZiI6MTcwNjY3MTY2NCwicGF0aCI6Ii83MDgzODM4My8zMDAzMTkyMjQtNWNiNWVmZTktZTNjZS00NGIxLTgyYzYtMTIwYmEzMGZhN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAzMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYWExNjBmYzI2NjViNGRiOTA1ZWEyNDFiMzAxNjQ5ZmI1OTI4ZTMxMGZkZGJiZjVmM2Q2ZjYwYzRhNzYwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTSi73_-XUm1baNxsRZ4UsIizc4r83sXqv6bMtu1X2o"> 将 onInputKeyDown 事件 取消 回车键的默认行为
> 
> 请问一下 这个是要改源码吗 我没有找到这段代码

<img width="839" alt="Snipaste_2024-01-31_11-43-32" src="https://github.com/vueComponent/ant-design-vue/assets/70838383/acd14aad-156c-490c-a586-c0ec31c07c31">
组件默认就提供这个事件

**Comment by StevenTang1994** [comment]
> > > <img alt="Snipaste_2024-01-29_10-37-36" width="378" src="https://private-user-images.githubusercontent.com/70838383/300319224-5cb5efe9-e3ce-44b1-82c6-120ba30fa7b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2NzE5NjQsIm5iZiI6MTcwNjY3MTY2NCwicGF0aCI6Ii83MDgzODM4My8zMDAzMTkyMjQtNWNiNWVmZTktZTNjZS00NGIxLTgyYzYtMTIwYmEzMGZhN2IzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDAzMjc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYWExNjBmYzI2NjViNGRiOTA1ZWEyNDFiMzAxNjQ5ZmI1OTI4ZTMxMGZkZGJiZjVmM2Q2ZjYwYzRhNzYwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vTSi73_-XUm1baNxsRZ4UsIizc4r83sXqv6bMtu1X2o"> 将 onInputKeyDown 事件 取消 回车键的默认行为
> > 
> > 
> > 请问一下 这个是要改源码吗 我没有找到这段代码
> 
> <img alt="Snipaste_2024-01-31_11-43-32" width="839" src="https://private-user-images.githubusercontent.com/70838383/301032819-acd14aad-156c-490c-a586-c0ec31c07c31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTYwNzYsIm5iZiI6MTcwNjc1NTc3NiwicGF0aCI6Ii83MDgzODM4My8zMDEwMzI4MTktYWNkMTRhYWQtMTU2Yy00OTBjLWE1ODYtYzBlYzMxYzA3YzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyNDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTUyNmU4ZTAzYzc1ZWFkNjNkYTY2NjQ3YzZjZjdhMzNjNTA2ZTdiYjBmNTY0N2FlYmE4OTMzN2RmNTk1NjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pr2iWYHfWzxLcxWomOm21lizOuPLJBo4_Wi7jZBegPI"> 组件默认就提供这个事件

谢谢
