### ISSUE TITLE
Table组件 headerCell 插槽与expandedRowRender插槽一起使用时报错, 无法渲染

### ISSUE THREAD

**Issue by mmmmr** [vueComponent/ant-design-vue#7315]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
4.1.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/happy-shadow-wsd7l7)

### Steps to reproduce
注释掉headerCell插槽或expandedRowRender插槽之一 可正常渲染

### What is expected?
正常渲染

### What is actually happening?
.

**Comment by mmmmr** [comment]
#7115 这是老issue, 重新开了一个新的

**Comment by selicens** [comment]
看了下那个报错，是rendSlot的API引起的，这个已经有pr了，等待合并

**Comment by selicens** [comment]
#7291

**Comment by wsxe9988** [comment]
@selicens 这种紧急修复的pr能不被尽快被合并发一版呢

**Comment by selicens** [comment]
update to 4.1.2
