### ISSUE TITLE
modal组件在浏览器resize后导致拖拽定位出错

### ISSUE THREAD

**Issue by ArouraSypan** [vueComponent/ant-design-vue#7317]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
vue3

### Reproduction link
[https://www.antdv.com/components/modal-cn](https://www.antdv.com/components/modal-cn)

### Steps to reproduce
antdv官网（https://www.antdv.com/components/modal-cn）中提供的弹窗拖动组件Modal（useDraggable ），在打开弹窗后，只要浏览器大小变更后再次拖动位置定位有偏差；

### What is expected?
浏览器大小变更后 不出现偏差

### What is actually happening?
antdv官网（https://www.antdv.com/components/modal-cn）中提供的弹窗拖动组件Modal（useDraggable ），在打开弹窗后，只要浏览器大小变更后再次拖动位置定位有偏差；

---
请尽快解决 不然差评

**Comment by xiaozhu2024** [comment]
你是还购物的么，还差评

**Comment by ZONEZH** [comment]
确实有这个问题 还望早日修复这个bug

**Comment by Coder-XJ** [comment]
解决了吗
