### ISSUE TITLE
antdv 4.0版本后全局缺少回到顶部按钮

### ISSUE THREAD

**Issue by David-TechNomad** [vueComponent/ant-design-vue#7322]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
 
![image](https://github.com/vueComponent/ant-design-vue/assets/23149356/9ed90da3-0fd7-4d0f-920e-7b39863f4cb2)

        
### Version
4.1.0

### Environment
3.4.15

### Reproduction link
[https://next.antdv.com/components/table-cn#components-table-demo-resizable-column](https://next.antdv.com/components/table-cn#components-table-demo-resizable-column)

### Steps to reproduce
antdv 4.0版本后全局缺少回到顶部按钮

### What is expected?
希望添加全局 回到顶部按钮

### What is actually happening?
antdv 4.0版本后全局缺少回到顶部按钮

**Comment by David-TechNomad** [comment]
fix https://github.com/vueComponent/ant-design-vue/pull/7323

**Comment by hhui64** [comment]
see [CHANGELOG.md](https://github.com/vueComponent/ant-design-vue/blob/main/CHANGELOG.zh-CN.md#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84%E4%B8%8E%E7%A7%BB%E9%99%A4)

> BackTop 组件在 4.0.0 中废弃，移至 FloatButton 悬浮按钮中。如需使用，可以从 FloatButton 中引入。

**Comment by gaokun** [comment]
根据4.0的官方文档, 说明如下:

`BackTop 组件在 4.0.0 中废弃，移至 FloatButton 悬浮按钮中。如需使用，可以从 FloatButton 中引入`

[文档链接](https://next.antdv.com/docs/vue/migration-v4-cn)

**Comment by gaokun** [comment]
Sorry, 我以为是想增加Backtop组件, 看了下pr, 只是改官网doc忽略上面的回复
