### ISSUE TITLE
浏览器引入的方式下 复合单词的插槽无效

### ISSUE THREAD

**Issue by shaomingming008** [vueComponent/ant-design-vue#7326]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.3

### Environment
win10 vue3.x chrome

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
浏览器引入ant design vue
任意一个组件 例如 a-input
template #addonBefor 使用插槽
![222](https://github.com/vueComponent/ant-design-vue/assets/22759207/1a085a27-3d51-4d7a-9b36-19a4721e65ad)

### What is expected?
插槽生效

### What is actually happening?
插槽不生效
![111](https://github.com/vueComponent/ant-design-vue/assets/22759207/58d817e3-876f-4935-bce3-3bfdbf7c1284)

**Comment by aShu-guo** [comment]
挂载方式有问题，参考：

[![Edit input-slot](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/input-slot-zvd36s?file=%2Findex.html%3A46%2C17)

**Comment by shaomingming008** [comment]
好的
