### ISSUE TITLE
please advice on migration to CSS-in-JS with ant v4

### ISSUE THREAD

**Issue by igorfraa** [vueComponent/ant-design-vue#7330]
- [ yes ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I've setup my vue.config.ts as per migration documentation.
I have a simple snippet for style override:
```less
@import "~ant-design-vue/lib/input/style/index.less";

.ant-input-not-disabled:disabled {
.ant-input;
}
```

How should it look with new ant? Importing from "ant-design-vue/lib/input/style/index.js" obscurely fails despite 
`javascriptEnabled: true,` in loader config
```
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
"use strict";
^
Unrecognised input
```

### What does the proposed API look like?
A bit of helper documentation would be fine

**Comment by selicens** [comment]
If it is to cover the style, then combining the `deep` attribute within the style is sufficient

**Comment by selicens** [comment]
https://www.antdv.com/docs/vue/migration-v4-cn

**Comment by igorfraa** [comment]
@selicens as far as I can understand Chinese, I should dive deeper in the subject. 

However, the reason behind my question is a bit of trust for people can point me whatever is css-in-js and how it can be dealt with.

thank you for understanding.

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/55450e3d-2aab-492f-910e-dda8f3a05553)
https://www.antdv.com/docs/vue/migration-v4
css-in-js does not require the introduction of CSS files, and its style is included in JavaScript. If you need to overwrite it, you can achieve the goal by using deep in the style tag of Vue
