### ISSUE TITLE
DatePicker 在鼠标处于点击状态移入再松开，会触发下拉框展开

### ISSUE THREAD

**Issue by Kayintyz** [vueComponent/ant-design-vue#7333]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Chrome 最新

### Reproduction link
[https://next.antdv.com/components/date-picker-cn](https://next.antdv.com/components/date-picker-cn)

### Steps to reproduce
在DatePicker外点击鼠标，使其一直处于点击状态，然后移入到DatePicker内，会触发下拉

### What is expected?
只有点击DatePicker后才能下拉展开

### What is actually happening?
在DatePicker外点击鼠标，使其一直处于点击状态，然后移入到DatePicker内，会触发下拉

**Comment by kanggit-hub** [comment]
This is not a bug

**Comment by zjclxx** [comment]
> This is not a bug

but I have a question：DatePicker.RangerPicker just not has this phenomenon.
![image](https://github.com/vueComponent/ant-design-vue/assets/62633990/23ea1fa8-51bb-4889-b94d-0b01eb850bd2)
