### ISSUE TITLE
vue3.4.18。popconfirm和dropdown二次触发会有问题

### ISSUE THREAD

**Issue by electroluxcode** [vueComponent/ant-design-vue#7344]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
更新到 vue3.4.18版本，然后本仓库npm run dev即可。components/dropdown 和 components/popconfirm   实测vue3.4.18测试会有问题，降低到vue3.2 可以正常运行

### Reproduction link
[http://localhost:5173/components/dropdown](http://localhost:5173/components/dropdown)

### Steps to reproduce
二次 click 或者 hover 组件的时候，dropdown和popconfirm本来应该展开的状态，但是并没有展开。只有首次是相对正常的。

**Comment by electroluxcode** [comment]
现在的版本没问题了

**Comment by electroluxcode** [comment]
> 目前vue升级到最近的vue版本仍然有这个问题。

![demo_](https://github.com/vueComponent/ant-design-vue/assets/59329360/bdfdef09-9e65-42c3-88c9-72c11b2c3223)

**Comment by tangjinzhou** [comment]
升级 Vue
