### ISSUE TITLE
modal 提供keyup,keydown 事件

### ISSUE THREAD

**Issue by longyi-xw** [vueComponent/ant-design-vue#7347]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
modal 提供keyup,keydown 事件, 我无法通过keyup.native触发它

### What does the proposed API look like?
"ant-design-vue": "4.x",
"vue": "3.4.15",

**Comment by selicens** [comment]
keyup.native 只能应用在支持原生 keyup 事件的元素上，比如 <input>、<textarea> 等具有键盘输入功能的元素。而对于其他非具有键盘输入功能的元素，或是自定义组件，keyup.native 是不起作用的。

**Comment by longyi-xw** [comment]
明白了，或许自行绑定modal的键盘事件是好的处理方式。
