### ISSUE TITLE
建议添加全局滚动条，以解决在不同浏览器上滚动条一致性问题，望采纳

### ISSUE THREAD

**Issue by twosoy** [vueComponent/ant-design-vue#7352]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
建议添加全局滚动条已解决在不同浏览器上滚动条一致性问题

### What does the proposed API look like?
建议添加全局滚动条已解决在不同浏览器上滚动条一致性问题

**Comment by hero8080** [comment]
滚动条确实是个问题，select虚拟滚动的滚动条和取消虚拟滚动的滚动条就是原生的滚动条，又粗又宽，就不一样，要么都用同一个样式滚动条，要么都不处理，对于强迫症的我实在受不了，对于其他人可能觉得不是问题，
// 滚动条
::-webkit-scrollbar-track-piece {
  background: 0 0;
}
::-webkit-scrollbar-thumb {
  background-color: #cecece;
  border: 3px solid transparent;
  background-clip: padding-box;
  border-radius: 5px;
}
::-webkit-scrollbar-thumb:hover{
  background-color: #a4a4a4;
}
::-webkit-scrollbar {
  width: 10px;
  height: 10px;
}

修改原生滚动条，拿走不谢

**Comment by hero8080** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/52777521/b2cb16d8-0dd0-4c03-8235-b2b1263d919c)

**Comment by twosoy** [comment]
目前采用的业是此种方式解决的，但是我觉得框架可以考虑一次性处理掉。

**Comment by DogeLasVegas** [comment]
洛阳铲一下，请问这个问题有解决了吗，想偷懒不用自己改样式

**Comment by coder-xiaotian** [comment]
组件什么时候原生支持
