### ISSUE TITLE
有考虑过出一个对form组件的二次封装的组件么

### ISSUE THREAD

**Issue by leleccccc** [vueComponent/ant-design-vue#7359]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
把原本在template中的一些form，form-item标签，用js配置项来完成

### What does the proposed API look like?
把原本在template中的一些form，form-item标签，用js配置项来完成

**Comment by aShu-guo** [comment]
如果是希望通过json文件动态配置表单，可以参考formilyjs，不过它目前只提供了vue2版本的

**Comment by ZedCoding** [comment]
可以试试这个https://www.form-create.com

**Comment by leleccccc** [comment]
> 可以试试这个https://www.form-create.com

感觉好像不错
