### ISSUE TITLE
分页器点击“下一页”箭头以后按下回车会跳两页

### ISSUE THREAD

**Issue by Zyh20000923** [vueComponent/ant-design-vue#7360]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
win11

### Reproduction link
[https://next.antdv.com/components/pagination-cn/#Pagination-](https://next.antdv.com/components/pagination-cn/#Pagination-)

### Steps to reproduce
官网示例

### What is expected?
分页器点击“下一页”箭头以后按下回车会跳两页，上一页也同样情况。
请问这是故意的还是一个bug

### What is actually happening?
分页器点击“下一页”箭头以后按下回车会跳两页，上一页也同样情况。
请问这是故意的还是一个bug

**Comment by selicens** [comment]
没有发现你说的这个问题呢

**Comment by wsxe9988** [comment]
能试出来，和ant-design的效果是一致的

**Comment by selicens** [comment]
> 能试出来，和ant-design的效果是一致的

哦，点下一页和按回车两个操作，这两个为啥会关联到一起，好奇怪

**Comment by selicens** [comment]
当点击下一页后按下enter键，预期是出现页数加一，但实际按下enter键除了会触发键盘事件还会默认触发元素的点击事件，所以会出现页数加二的情况，反之点击上一页然后按下enter键也是如此，页数会减二而不是预期的减一

**Comment by Zyh20000923** [comment]
ant3也是这样
