### ISSUE TITLE
time-picker 组件样式异常问题 3.2.20 版本的时候还有style文件夹 4.0.0开始就没有style文件夹 然后我用自动导入的时候就报错了

### ISSUE THREAD

**Issue by Zeng-fx** [vueComponent/ant-design-vue#7369]
![微信图片_20240222102333](https://github.com/vueComponent/ant-design-vue/assets/75517704/6c19befa-ab80-41b0-952c-198357eb9480)
![微信图片_20240222102339](https://github.com/vueComponent/ant-design-vue/assets/75517704/5530c5aa-76ac-4635-bb52-58886c8f1f17)
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
"vue": "^3.4.19","ant-design-vue": "^4.1.2",

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/tree/main/components/time-picker](https://github.com/vueComponent/ant-design-vue/tree/main/components/time-picker)

### Steps to reproduce
直接在页面中使用 <a-time-picker v-model:value="value" />

页面报错：
[plugin:vite:import-analysis] Failed to resolve import "ant-design-vue/es/time-picker/style" from "src/views/demo-view/DemoView.vue". Does the file exist?
D:/web/antd/src/views/demo-view/DemoView.vue:1:121
1  |  /* unplugin-vue-components disabled */import { TimePicker as __unplugin_components_2 } from 'ant-design-vue/es';import 'ant-design-vue/es/time-picker/style';
|                                                                                                                          ^
2  |  import __unplugin_components_1 from 'D:/web/antd/src/components/dynamic-form/DynamicForm.vue';
3  |  import { Button as __unplugin_components_0 } from 'ant-design-vue/es';import 'ant-desig

### What is expected?
ailed to resolve import "ant-design-vue/es/time-picker/style" from "xxxx". Does the file exist?

### What is actually happening?
路径 ant-design-vue/es/time-picker/style， style文件夹不存在

**Comment by ThisIszas** [comment]
vite.config.ts把
`
    AntDesignVueResolver({
       importStyle: 'less'
    }),
`
改成
`
AntDesignVueResolver({
            importStyle: false
    }),
`

**Comment by IdealZXL** [comment]
你这边最后怎么解决的？我这边也遇到同样的问题了
