### ISSUE TITLE
官方文档的CodeSandbox打开后报错

### ISSUE THREAD

**Issue by An0510** [vueComponent/ant-design-vue#7371]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
chrome 版本 121.0.6167.184（正式版本） (arm64)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html)

### Steps to reproduce
table组件里任意一个都不行

### What is expected?
能支持CodeSandBox或是其他类似应用

### What is actually happening?
无法使用CodeSandBox

**Comment by An0510** [comment]
CodeSandBox打开后右侧网页报错 
←→1 of 2 errors on the page
TypeError
Cannot set properties of null (setting 'value')
...

**Comment by aShu-guo** [comment]
可以在codesandbox中先将vue版本修改`latest`，vue-request版本修改为`1.2.5`（如果有的话）。
```json
{
  "title": "远程加载数据 - ant-design-vue@4.1.2",
  "dependencies": {
    "vue": "latest",
    "ant-design-vue": "4.1.2",
    "vue-request": "1.2.5",
    "axios": "latest"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "typescript": "^4.0.5"
  },
  "browserslist": ["> 0.2%", "not dead"]
}
```

**Comment by An0510** [comment]
谢谢 有效
