### ISSUE TITLE
关于类似Tooltip的弹出所有组件第二次渲染失效问题

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [vueComponent/ant-design-vue#7372]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Windows11，Chrome：122.0.6261.57，Vue：3.2.13

### Reproduction link
[https://github.com/ErrorCodesForLzx/pop_result](https://github.com/ErrorCodesForLzx/pop_result)

### Steps to reproduce
触发一次，鼠标移开，再次触发

### What is expected?
正常显示提示框（以及其他信息，如：日期框...）

### What is actually happening?
第一次正常，第二次就会闪烁，然后消失

---
只有这个

**Comment by selicens** [comment]
#7346 follow trends

**Comment by wsxe9988** [comment]
@selicens 啥时候4.x 和3.x 合并下已有pr，解决vue3.4下问题，发下最新版呢

**Comment by selicens** [comment]
> @selicens 啥时候4.x 和3.x 合并下已有pr，解决vue3.4下问题，发下最新版呢

合并pr需要等唐老师

**Comment by wsxe9988** [comment]
> > @selicens 啥时候4.x 和3.x 合并下已有pr，解决vue3.4下问题，发下最新版呢
> 
> 合并pr需要等唐老师

唉，不知道要等到啥时候了，帮忙催催呗，大佬
