### ISSUE TITLE
datePicker 组件类型相关问题

### ISSUE THREAD

**Issue by wowsummer** [vueComponent/ant-design-vue#7376]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.2

### Environment
mac

### Reproduction link
[https://www.antdv.com/components/date-picker-cn](https://www.antdv.com/components/date-picker-cn)

### Steps to reproduce
两个问题：
一. RangePickerProps 无法导入
```
import type { RangePickerProps } from 'ant-design-vue'  // RangePickerProps 无法导入
```

二. a-date-picker 组件类型错误
```
<template>
   <a-date-picker v-bind="dateProps" /> // 组件会提示类型错误
</template>

<script lang="ts" setup>
import { ref } from 'vue'   
import type { DatePickerProps } from 'ant-design-vue'

const dateProps = ref<DatePickerProps>({ allowClear: true })
</script>
```

### What is expected?
一. RangePickerProps 能正确导入
二. <a-date-picker /> 不要提示类型错误

### What is actually happening?
一. 无法导入RangePickerProps
二. <a-date-picker /> 提示类型错误

**Comment by chouchouji** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/70570907/ff692db5-d06a-44f4-83f8-75ade7742afd)

好像并没有导出 RangePickerProps

**Comment by chouchouji** [comment]
第二个错误方便提供下报错的截图吗？

**Comment by wowsummer** [comment]
感谢回复，截图如下
![2](https://github.com/vueComponent/ant-design-vue/assets/50063749/a4bc8852-6c7e-4b8a-b2b2-5c1d8fd2f5d9)

![1](https://github.com/vueComponent/ant-design-vue/assets/50063749/2dd6adb1-9b98-4cb4-9c80-27dba61eaf28)

**Comment by chouchouji** [comment]
> 感谢回复，截图如下 ![2](https://private-user-images.githubusercontent.com/50063749/307636950-a4bc8852-6c7e-4b8a-b2b2-5c1d8fd2f5d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTAzNTgsIm5iZiI6MTcwODkxMDA1OCwicGF0aCI6Ii81MDA2Mzc0OS8zMDc2MzY5NTAtYTRiYzg4NTItNmM3ZS00YjhhLWIyYjItNWMxZDhmZDJmNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAxMTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhYzdlY2FjZTc1ODQ4ODQzNDY4ZTczY2QzMzA3NzY4ZGQ1YWM3NjY0NDJkYWZlZjE3Y2Q4MWU0ZjMwMjQwNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kmk9BPMSarWK9zeiDK8OXQlGdUEf_NJUmRbV38Ak6yo)
> 
> ![1](https://private-user-images.githubusercontent.com/50063749/307636839-2dd6adb1-9b98-4cb4-9c80-27dba61eaf28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MTAzNTgsIm5iZiI6MTcwODkxMDA1OCwicGF0aCI6Ii81MDA2Mzc0OS8zMDc2MzY4MzktMmRkNmFkYjEtOWI5OC00Y2I0LTljODAtMjdkYmE2MWVhZjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDAxMTQxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYWZlYmU4NTU4YmI4ZTE0ZTFkYzYxYmIzMTJkZjJjM2JkZWZmZTg3YzFhZmQ4YTdkZDIyMDUyOWFhYTIwOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L-VItS3jAlvJT0b6xjLplC5g8OduQqF_3Fp8w7Ap1Rw)

类型没有匹配上，可以翻下node_modules深究具体原因
![image](https://github.com/vueComponent/ant-design-vue/assets/70570907/2007ff82-abd0-4052-a20e-30b6b9898285)
