### ISSUE TITLE
Blur event or property "open" is not reactive in some situations concerning auto-complete component

### ISSUE THREAD

**Issue by GlebNekrasov** [vueComponent/ant-design-vue#7378]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Windows 10 Home (build 19045), Google Chrome 121.0.6167.189, Vue 3.2.13

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/autocomplete-blur-bug-mqhv3d)

### Steps to reproduce
1. Input "son" at top input-field. After that dropdown will open.
2. Click anywhere out of top input-field. Dropdown will be shown yet.

### What is expected?
After click out of input-field dropdown should be closed.

### What is actually happening?
After click out of input-field dropdown stays opened.

---
I created component "SearchField" using auto-complete component of Antdv. At SearchField template I bound option "open" to reactive variable "isDropdownActive". This variable is changed by 4 events: change, select, focus and blur. Events change and select work correctly. As for blur event, it changes "isDropdownActive" value correctly (you can see it at console), but changed value of "isDropdownActive" doesn't effect on dropdown status. Perhaps, reactivity is destructed somewhere in this sequence.

**Comment by aShu-guo** [comment]
the usage of `ref` is incorrect, you should use `.value` to modify the value. for example
```js
const changeHandler = (value) => {
  isDropdownActive.value = value.length >= props.minLengthDropdown;
  console.log("changeHandler");
  console.log("value length = " + value.length);
  console.log("isDropdownActive = " + isDropdownActive);
};
```
[codesandbox](https://codesandbox.io/p/sandbox/autocomplete-blur-bug-forked-9k8xwq?file=%2Fsrc%2Fcomponents%2FSearchField.vue%3A38%2C36)

**Comment by GlebNekrasov** [comment]
> the usage of `ref` is incorrect, you should use `.value` to modify the value. for example
> 
> ```js
> const changeHandler = (value) => {
>   isDropdownActive.value = value.length >= props.minLengthDropdown;
>   console.log("changeHandler");
>   console.log("value length = " + value.length);
>   console.log("isDropdownActive = " + isDropdownActive);
> };
> ```
> 
> [codesandbox](https://codesandbox.io/p/sandbox/autocomplete-blur-bug-forked-9k8xwq?file=%2Fsrc%2Fcomponents%2FSearchField.vue%3A38%2C36)

It's the shame mistake on my side. Now all work correctly. Thanks a lot.
