### ISSUE TITLE
AutoComplete组件输入BUG

### ISSUE THREAD

**Issue by Diven-xinhai** [vueComponent/ant-design-vue#7380]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
不分系统、谷歌浏览器、vue3

### Reproduction link
[https://www.antdv.com/components/auto-complete-cn](https://www.antdv.com/components/auto-complete-cn)

### Steps to reproduce
在官网文档中：https://www.antdv.com/components/auto-complete-cn
使用 富文本AutoComplete ，先输入英文，全部删除后再输入中文，只要中文输入完成就无法在之前的内容上新增内容了，永远都是最新输入的内容

### What is expected?
修复 富文本AutoComplete

### What is actually happening?
/

---
我预计是焦点的问题

**Comment by selicens** [comment]
没有复现这个问题，方便再进一步描述复现步骤或者提供最小复现在线demo

**Comment by Diven-xinhai** [comment]
![iShot_2024-03-04_11 38 58](https://github.com/vueComponent/ant-design-vue/assets/54425515/829f1c6b-b949-4f8a-8637-f200646a2d81)
可以看下这个录屏，auto-complete组件配合textarea组件使用时，中文输入完成后就会出现这个问题，输入的值始终是最新的，之前的丢失了，使用watch监听不到

**Comment by aShu-guo** [comment]
问题已修复，已合并到主分支
