### ISSUE TITLE
分段控制器动画失效，闪现问题

### ISSUE THREAD

**Issue by yuyingjie20** [vueComponent/ant-design-vue#7382]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
win10，Chrome121.0.6167.185，antV4.1.0

### Reproduction link
[https://next.antdv.com/components/segmented-cn](https://next.antdv.com/components/segmented-cn)

### Steps to reproduce
分段控制器基础用法点后边的，再点击前面的，多试几次，滑动动画会失效，滑块从左闪烁到右边（多试几次）

### What is expected?
修复下滑块闪现的问题

### What is actually happening?
现版本分段控制器滑块动画闪现问题

---
none

**Comment by aShu-guo** [comment]
![Feb-28-2024 10-21-27](https://github.com/vueComponent/ant-design-vue/assets/65716236/c5e05aa3-871d-4930-8185-fa3177a86ca7)
你好，没有复现上述问题。能否提供一个最小复现仓库或者gif图片呢？

**Comment by cn-xufei** [comment]
> 
> 
> https://github.com/vueComponent/ant-design-vue/assets/103242364/1a806636-6a6e-4a16-9da3-47b2a6b400e0
> 
> 
> 
> 看下视频最后的闪现

确实存在，看下这个 [pr](https://github.com/vueComponent/ant-design-vue/pull/8045)
