### ISSUE TITLE
a-menu组件在collapsed折叠的状态下，通过js设置selectedKeys为某个二级菜单时会弹出卡片并选中，但是鼠标不放上面再移走就不会自动消失。

### ISSUE THREAD

**Issue by romande** [vueComponent/ant-design-vue#7383]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.2

### Environment
Microsoft Edge122.0.2365.52 (正式版本) (64 位)

### Reproduction link
[https://www.antdv.com/components/menu-cn#components-menu-demo-inline-collapsed](https://www.antdv.com/components/menu-cn#components-menu-demo-inline-collapsed)

### GIF
![动画](https://github.com/vueComponent/ant-design-vue/assets/20809412/0ef4b957-5e29-44d4-8842-847b0fce82ca)

### 代码示例
```js
<a-menu
v-model:selectedKeys="selectedKeys"
mode="inline"
theme="dark"
:inline-collapsed="collapsed"
:items="menus"
@select="menuChoose"
:open-keys="state.openKeys"
@openChange="onOpenChange"
></a-menu>
</a-layout-sider>

// 高亮显示选中的菜单项
const openAndChooseSelectedMenu = (key) => {
// 展开被选中的菜单(这边的写法只支持两层菜单)
menus.value.forEach(m => {
if(m.children && m.children.find(cm => cm.key === key)) {
state.openKeys = [m.key]
}
});
// 选择具体某个菜单项
selectedKeys.value = [key]
}
```

### What is expected?
折叠的情况下，二级菜单弹出并高亮后自动消失。

### What is actually happening?
二级菜单弹出选中后，一直停留在页面上。

**Comment by aShu-guo** [comment]
能否提供一个可复现的最小仓库地址呢？

**Comment by 10187169** [comment]
你好，请问你这个问题解决了吗？我也出现这个现象 很烦恼

**Comment by sx19970123** [comment]
我也遇到了，我的做法是菜单展开状态对openKeys数组进行操作
