### ISSUE TITLE
chrome浏览器windows和macOS table表格固定头和列兼容错位问题

### ISSUE THREAD

**Issue by haoyanming** [vueComponent/ant-design-vue#7387]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.2

### Environment
电脑系统：macOs 14.3.1  浏览器版本：chrome  122.0.6261.94  vue版本：2.6.11

### Reproduction link
[https://1x.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header](https://1x.antdv.com/components/table-cn/#components-table-demo-fixed-columns-and-header)

### Steps to reproduce
官方文档1x版本table固定头和列表格可直接复现。
![image](https://github.com/vueComponent/ant-design-vue/assets/38808104/61bf8703-e716-4261-855d-bac1b96d3f98)

### What is expected?
windows和macOS都能固定头和列且不错位。

### What is actually happening?
行不能对齐

**Comment by haoyanming** [comment]
#7353中有个朋友说是在ant-table-header上增加scrollbar-width: none;我试过，试过之后macOS上是可以解决但是同事windows上chrome浏览器又出现了类似问题。
![1258771709113129_ pic](https://github.com/vueComponent/ant-design-vue/assets/38808104/d91b1ff9-448a-4a84-815d-ff100faae802)

**Comment by zhuangcuigit** [comment]
同样的问题，同求。
我的是mac，滚动槽出现在上面
同事有的也是mac和window，滚动槽出现在下面
加了scrollbar-width: none;后，同事上方的表头会被下面的表格覆盖一些内容
