### ISSUE TITLE
[DOC] 将包裹组件App的文档链接, 引入到Modal/Message/Notification的FAQ(获取上下文)下面

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#7393]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如题,  " 将包裹组件App的文档链接, 引入到Modal/Message/Notification的FAQ(获取上下文)下面"

只是官方文档的完善, 将相关联的文档, 联系在一起, 可以更方便大家更容易阅读, 节省时间

(我是几乎做了和App包裹组件同样的做法后, 才发现官方已经提供了.)

### What does the proposed API look like?
如题, 只是官方文档的完善

**Comment by selicens** [comment]
App是一个单独的组件

**Comment by gaokun** [comment]
但是存在contextHolder的共通点.

正如ant-design(react版本), 就在文档中关联了(如下图), [链接](https://ant-design.antgroup.com/components/modal-cn)

![image](https://github.com/vueComponent/ant-design-vue/assets/7044628/09e175db-7324-40bb-864e-e886ec64c60a)

vue官方文档还有一点可以完善, 即 "css in js后, 组件有哪些token可被使用"
目前需要翻阅antdv源码, 来查找.

这点, 在ant-design(react版本)也更完善(如下图), [链接](https://ant-design.antgroup.com/components/button-cn)

![image](https://github.com/vueComponent/ant-design-vue/assets/7044628/995291f9-4ecb-4969-b051-093f2b211e2d)


 希望antdv能完善一下文档

**Comment by selicens** [comment]
Message、Notification官网已有通过App包裹组件简化使用`contextHolder`的描述，modal应该是遗漏了，已补充
