### ISSUE TITLE
【input】input 组件在带前缀时autocomplete的背景色无法覆盖

### ISSUE THREAD

**Issue by tianjlj** [vueComponent/ant-design-vue#7394]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
macos ventura 13.4.1，edge  121.0.2277.83 (正式版本) (arm64)，vue 3.3.11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/intelligent-benji-x84cgk?file=%2Fsrc%2FApp.vue%3A29%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt8k7nbf00063p6giom7rqj3%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt8k7nbf00023p6gn5pyu2se%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt8k7nbf00033p6gpo808upm%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt8k7nbf00053p6gij1c8ary%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt8k7nbf00023p6gn5pyu2se%2522%253A%257B%2522id%2522%253A%2522clt8k7nbf00023p6gn5pyu2se%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt8kb01c00023p6fav07ymrw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A29%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A29%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt8kb01c00023p6fav07ymrw%2522%257D%252C%2522clt8k7nbf00053p6gij1c8ary%2522%253A%257B%2522id%2522%253A%2522clt8k7nbf00053p6gij1c8ary%2522%252C%2522activeTabId%2522%253A%2522clt8kudbc001m3p6fagyh9rk4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clt8kudbc001m3p6fagyh9rk4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clt8k7nbf00033p6gpo808upm%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clt8k7nbf00033p6gpo808upm%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
1. 创建一个 form，加入一个 2 个 form-item，分别加入一个input，类名login_input
2. 第一个 input 不加前缀，设置autocomplete=’email‘，方便填充
3. 第二个 input 加前缀<template #prefix> a </template> ，设置autocomplete=’email‘，方便填充
4. 设置样式，覆盖自动填充的背景色
.login_input:-webkit-autofill {
-webkit-box-shadow: 0 0 0 1000px green inset !important;
}
5. 页面上分别填充两个输入框

### What is expected?
能够在添加了前缀的情况下覆盖自动填充的背景色

### What is actually happening?
加了前缀，无法覆盖自动填充的背景色，不添加前缀时，是可以覆盖的

**Comment by aShu-guo** [comment]
1. 没有前缀时，input组件上的class是`直接绑定`到input标签上的

```html
<input data-v-e17ea971="" placeholder="对比-不带前缀-自动填充背景色可以覆盖" autocomplete="email" id="form_item_name1" type="text" class="ant-input css-dev-only-do-not-override-1hsjdkk login_input">
```

2. 有前缀时，input组件上的class是`并未绑定`到input标签上

```html
<span data-v-e17ea971="" class="ant-input-affix-wrapper login_input css-dev-only-do-not-override-1hsjdkk">
    <span class="ant-input-prefix"> a </span>
    <input placeholder="带前缀-自动填充背景色无法覆盖" autocomplete="email" id="form_item_username" type="text" 
                class="ant-input css-dev-only-do-not-override-1hsjdkk">
<!---->
</span>
```

注意login_input的位置

**Comment by tianjlj** [comment]
您好，您的邮件我已收到，我会尽快给您回复。

**Comment by tianjlj** [comment]
> 1. 没有前缀时，input组件上的class是`直接绑定`到input标签上的
> 
> ```
> <input data-v-e17ea971="" placeholder="对比-不带前缀-自动填充背景色可以覆盖" autocomplete="email" id="form_item_name1" type="text" class="ant-input css-dev-only-do-not-override-1hsjdkk login_input">
> ```
> 
> 2. 有前缀时，input组件上的class是`并未绑定`到input标签上
> 
> ```
> <span data-v-e17ea971="" class="ant-input-affix-wrapper login_input css-dev-only-do-not-override-1hsjdkk">
>     <span class="ant-input-prefix"> a </span>
>     <input placeholder="带前缀-自动填充背景色无法覆盖" autocomplete="email" id="form_item_username" type="text" 
>                 class="ant-input css-dev-only-do-not-override-1hsjdkk">
> 
> </span>
> ```
> 
> 注意login_input的位置

其实用组件自身的  class：ant-input ，是同样的结果，这个是都绑定在 input 上的

**Comment by aShu-guo** [comment]
这样使用也许可以解决问题

1. 修改`所有input`的autofill样式
```css
:deep(.ant-input):-webkit-autofill{
  -webkit-box-shadow: 0 0 0 1000px green inset;
}
```

2. 使用`指定类名login_input`的autofill样式
```css
.login_input:-webkit-autofill,
:deep(.login_input) .ant-input:-webkit-autofill {
  -webkit-box-shadow: 0 0 0 1000px green inset;
}
```

**Comment by tianjlj** [comment]
感谢，好使了
