### ISSUE TITLE
auto-complete 组件无法使用option 或 options 等slot自定义下拉菜单

### ISSUE THREAD

**Issue by zhou-ouha** [vueComponent/ant-design-vue#7396]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
vue@3.4.0     TS@5.3.3    ant-design-vue@4.1.2    edge@122.0.2365.59

### Reproduction link
[https://antdv.com/components/auto-complete-cn](https://antdv.com/components/auto-complete-cn)

### Steps to reproduce
使用文档中说明的 option slot 或使用TS中定义的options slot 自定义下拉菜单的选项
https://codesandbox.io/p/sandbox/priceless-galois-3mhq5c

### What is expected?
自定义菜单项，希望菜单项前面有一个选中图标

### What is actually happening?
使用 option slot ， TS会检查 option 这个slot不存在，在源码导出的几种 slot的类型，没有option
使用 options slot ，antdv 会报错 Warning: [ant-design-vue: AutoComplete] options' slot is deprecated, please use props "options"
instead

**Comment by zhou-ouha** [comment]
@selicens

**Comment by selicens** [comment]
https://www.antdv.com/components/auto-complete-cn#components-auto-complete-demo-options
可以参照官网自定义选项demo使用，我使用vue3.4.21，ant-design-vue4.1.2是可以达到你的目的
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/bd7fefd4-9c30-400c-8999-a7618a941802)

**Comment by zhou-ouha** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/67950671/6c78b52c-e86c-4203-b574-c990a2756086)

![image](https://github.com/vueComponent/ant-design-vue/assets/67950671/f8cdc275-dd3d-42fa-a43f-a3d36013e74b)

我使用官方文档这种自定义模式，TS会提示类型错误，同时通过源码查看导出的 slot 类型，并不支持 option 字段

**Comment by zhou-ouha** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/67950671/69c79d1f-4b1d-415c-b0ee-ff1b8f29d74f)
![image](https://github.com/vueComponent/ant-design-vue/assets/67950671/403ee023-ecc3-4dac-9997-563eca40d927)

使用 options 字段也是根据源码中的逻辑来的，但是会提示我该字段已废弃

**Comment by selicens** [comment]
> ![image](https://private-user-images.githubusercontent.com/67950671/310093520-6c78b52c-e86c-4203-b574-c990a2756086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDU5NTQsIm5iZiI6MTcwOTY0NTY1NCwicGF0aCI6Ii82Nzk1MDY3MS8zMTAwOTM1MjAtNmM3OGI1MmMtZTg2Yy00MjAzLWI1NzQtYzk5MGEyNzU2MDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmZjI5YmUyNjI5NzMwMWNkOTQxZDQwNTg1M2IxODJmYTRiNzE5YmU3NzAxYTk0Yzk5MmNkYjRmNGRjNDlkOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmLtrQHmoSd_9N0Umjd6HOyngnUokpoAyHsAF4DW2aw)
> 
> ![image](https://private-user-images.githubusercontent.com/67950671/310094053-f8cdc275-dd3d-42fa-a43f-a3d36013e74b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDU5NTQsIm5iZiI6MTcwOTY0NTY1NCwicGF0aCI6Ii82Nzk1MDY3MS8zMTAwOTQwNTMtZjhjZGMyNzUtZGQzZC00MmZhLWE0M2YtYTNkMzYwMTNlNzRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMzQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiNDhhMjc3Mjc4YWQ1MDQ1ZTFjMDVmYjcyMTQ4NjU3OTk5NmI1MmZkN2U2ZDNiM2Y2OTVmYWNiMGZjM2E4NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kzljTjRxk2QMPvTgpvf4TNCkm432kSkfXGaTJEZkMyA)
> 
> 我使用官方文档这种自定义模式，TS会提示类型错误，同时通过源码查看导出的 slot 类型，并不支持 option 字段

你代码中使用的是option，slot定义的是options

**Comment by selicens** [comment]
我再确认下

**Comment by Diven-xinhai** [comment]
> 我再确认下
你好，我本意的功能是想要自定义下拉选项，效果如下：
![image](https://github.com/vueComponent/ant-design-vue/assets/54425515/4cced8d0-2165-461d-8275-99398f3a2441)
所以使用option插槽实现，但是ts检测类型报错，如果按照上述方式修改后就并不能实现自定义下拉选项，而是把我插槽自定义的内容给过滤掉了，效果如官网介绍一样，我看了下源码，在下方把options给过滤掉了，所以不能展示自定义内容
![image](https://github.com/vueComponent/ant-design-vue/assets/54425515/acf48ebd-f1ca-4798-9bed-00de83cea1f1)
目前我的方法是把slots中ts类型增加了option类型，即解决了ts类型报错，又保留了插槽的作用。
其实目前我比较疑惑的option与options的用法在官网与代码中的含义好像有些冲突，我不是很理解这两者到底需要我怎么用，或者正确使用

**Comment by selicens** [comment]
> > 我再确认下
> > 你好，我本意的功能是想要自定义下拉选项，效果如下：
> > ![image](https://private-user-images.githubusercontent.com/54425515/311144925-4cced8d0-2165-461d-8275-99398f3a2441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDQ5MjUtNGNjZWQ4ZDAtMjE2NS00NjFkLTgyNzUtOTkzOThmM2EyNDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTFhNmRkYzJkODFhN2M2M2Y5MjExMmIwODI1Y2EzYmQ4NDE0NDY2NmUxZDkwNTdjMjk5YTEyMDBiOTJhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.08k_xKKR5lTgTqSakVZn5m9SN2zVMti_s205782D7ns)
> > 所以使用option插槽实现，但是ts检测类型报错，如果按照上述方式修改后就并不能实现自定义下拉选项，而是把我插槽自定义的内容给过滤掉了，效果如官网介绍一样，我看了下源码，在下方把options给过滤掉了，所以不能展示自定义内容
> > ![image](https://private-user-images.githubusercontent.com/54425515/311145557-acf48ebd-f1ca-4798-9bed-00de83cea1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDU1NTctYWNmNDhlYmQtZjFjYS00Nzk4LTliZWQtMDBkZTgzY2VhMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTA2MjM3MDI2ZTgxOTAzNjQ5ZTBjMDQ2YzY2MmIzN2MxOTI1OGIwYWExODA2NzJkNjRmY2E5OTUxOWRlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYlMviGGgVXiID5xm1yKTM_FL2P8Y3HF70_DJaDoSic)
> > 目前我的方法是把slots中ts类型增加了option类型，如下方所示：
> > ![image](https://private-user-images.githubusercontent.com/54425515/311146960-e148f246-07cf-409c-81a4-9bb5ffa30d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDY5NjAtZTE0OGYyNDYtMDdjZi00MDljLTgxYTQtOWJiNWZmYTMwZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTMwNjkwMDQ0MDg1NTc5Y2IxYmQ1MmVlYmZlOGM4MjZjMTY1OTVmN2VlZDU4MWJhZGZmNGJiMmNiMTgyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xe1dVUFr9LHy1ydRpoXmt0ksI7TWE0qPWHNHGtPyThE)
> > 即解决了ts类型报错，又保留了插槽的作用。
> > 其实目前我比较疑惑的option与options的用法在官网与代码中的含义好像有些冲突，我不是很理解这两者到底需要我怎么用，或者正确使用  

一个bug，其实应该是option，源码中使用了options，而option插槽能正确生效的原因是给select组件透传了option，select也有这个同名的插槽

**Comment by Diven-xinhai** [comment]
> > > 我再确认下
> > > 你好，我本意的功能是想要自定义下拉选项，效果如下：
> > > ![image](https://private-user-images.githubusercontent.com/54425515/311144925-4cced8d0-2165-461d-8275-99398f3a2441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDQ5MjUtNGNjZWQ4ZDAtMjE2NS00NjFkLTgyNzUtOTkzOThmM2EyNDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTFhNmRkYzJkODFhN2M2M2Y5MjExMmIwODI1Y2EzYmQ4NDE0NDY2NmUxZDkwNTdjMjk5YTEyMDBiOTJhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.08k_xKKR5lTgTqSakVZn5m9SN2zVMti_s205782D7ns)
> > > 所以使用option插槽实现，但是ts检测类型报错，如果按照上述方式修改后就并不能实现自定义下拉选项，而是把我插槽自定义的内容给过滤掉了，效果如官网介绍一样，我看了下源码，在下方把options给过滤掉了，所以不能展示自定义内容
> > > ![image](https://private-user-images.githubusercontent.com/54425515/311145557-acf48ebd-f1ca-4798-9bed-00de83cea1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDU1NTctYWNmNDhlYmQtZjFjYS00Nzk4LTliZWQtMDBkZTgzY2VhMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTA2MjM3MDI2ZTgxOTAzNjQ5ZTBjMDQ2YzY2MmIzN2MxOTI1OGIwYWExODA2NzJkNjRmY2E5OTUxOWRlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYlMviGGgVXiID5xm1yKTM_FL2P8Y3HF70_DJaDoSic)
> > > 目前我的方法是把slots中ts类型增加了option类型，如下方所示：
> > > ![image](https://private-user-images.githubusercontent.com/54425515/311146960-e148f246-07cf-409c-81a4-9bb5ffa30d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDY5NjAtZTE0OGYyNDYtMDdjZi00MDljLTgxYTQtOWJiNWZmYTMwZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTMwNjkwMDQ0MDg1NTc5Y2IxYmQ1MmVlYmZlOGM4MjZjMTY1OTVmN2VlZDU4MWJhZGZmNGJiMmNiMTgyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xe1dVUFr9LHy1ydRpoXmt0ksI7TWE0qPWHNHGtPyThE)
> > > 即解决了ts类型报错，又保留了插槽的作用。
> > > 其实目前我比较疑惑的option与options的用法在官网与代码中的含义好像有些冲突，我不是很理解这两者到底需要我怎么用，或者正确使用
> 
> 一个bug，其实应该是option，源码中使用了options，而option插槽能正确生效的原因是给select组件透传了option，select也有这个同名的插槽

抱歉，是我没表述清晰，我的意思是option的目的是可以自定义插槽吗？如果是那我明白了，因为我看在omit中把options过滤掉了，再结合你上述修改，把omit中的options改为了option，那还是无法实渲染自定义插槽中的元素，所以导致我迷惑了

**Comment by selicens** [comment]
> > > > 我再确认下
> > > > 你好，我本意的功能是想要自定义下拉选项，效果如下：
> > > > ![image](https://private-user-images.githubusercontent.com/54425515/311144925-4cced8d0-2165-461d-8275-99398f3a2441.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDQ5MjUtNGNjZWQ4ZDAtMjE2NS00NjFkLTgyNzUtOTkzOThmM2EyNDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkNTFhNmRkYzJkODFhN2M2M2Y5MjExMmIwODI1Y2EzYmQ4NDE0NDY2NmUxZDkwNTdjMjk5YTEyMDBiOTJhZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.08k_xKKR5lTgTqSakVZn5m9SN2zVMti_s205782D7ns)
> > > > 所以使用option插槽实现，但是ts检测类型报错，如果按照上述方式修改后就并不能实现自定义下拉选项，而是把我插槽自定义的内容给过滤掉了，效果如官网介绍一样，我看了下源码，在下方把options给过滤掉了，所以不能展示自定义内容
> > > > ![image](https://private-user-images.githubusercontent.com/54425515/311145557-acf48ebd-f1ca-4798-9bed-00de83cea1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDU1NTctYWNmNDhlYmQtZjFjYS00Nzk4LTliZWQtMDBkZTgzY2VhMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMTA2MjM3MDI2ZTgxOTAzNjQ5ZTBjMDQ2YzY2MmIzN2MxOTI1OGIwYWExODA2NzJkNjRmY2E5OTUxOWRlNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hYlMviGGgVXiID5xm1yKTM_FL2P8Y3HF70_DJaDoSic)
> > > > 目前我的方法是把slots中ts类型增加了option类型，如下方所示：
> > > > ![image](https://private-user-images.githubusercontent.com/54425515/311146960-e148f246-07cf-409c-81a4-9bb5ffa30d8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODI0MDMsIm5iZiI6MTcwOTg4MjEwMywicGF0aCI6Ii81NDQyNTUxNS8zMTExNDY5NjAtZTE0OGYyNDYtMDdjZi00MDljLTgxYTQtOWJiNWZmYTMwZDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3MTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyOTMwNjkwMDQ0MDg1NTc5Y2IxYmQ1MmVlYmZlOGM4MjZjMTY1OTVmN2VlZDU4MWJhZGZmNGJiMmNiMTgyMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xe1dVUFr9LHy1ydRpoXmt0ksI7TWE0qPWHNHGtPyThE)
> > > > 即解决了ts类型报错，又保留了插槽的作用。
> > > > 其实目前我比较疑惑的option与options的用法在官网与代码中的含义好像有些冲突，我不是很理解这两者到底需要我怎么用，或者正确使用
> > 
> > 
> > 一个bug，其实应该是option，源码中使用了options，而option插槽能正确生效的原因是给select组件透传了option，select也有这个同名的插槽
> 
> 抱歉，是我没表述清晰，我的意思是option的目的是可以自定义插槽吗？如果是那我明白了，因为我看在omit中把options过滤掉了，再结合你上述修改，把omit中的options改为了option，那还是无法实渲染自定义插槽中的元素，所以导致我迷惑了

我的更改犯了和之前一样的错误，稍后纠正
