### ISSUE TITLE
[Feature] antdv4.x版本, 增加CSS 变量

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#7402]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前cssinjs后, css变量已经不存在了.

> ant design在5.12.0版本重新支持了 CSS 变量, 按antdv的路线, 是跟随ant design的脚步

请问antdv是否有计划支持css变量, 若有计划, 想问下大概的时间计划. 
谢谢

### What does the proposed API look like?
参考 [ant design css变量](https://ant-design.antgroup.com/docs/react/css-variables-cn)

**Comment by selicens** [comment]
#7220 follow

**Comment by gaokun** [comment]
十分感谢, 抱歉之前没搜到这个PR.
期待这个PR的merged
