### ISSUE TITLE
希望ant-select能支持像Input那样的prefix属性

### ISSUE THREAD

**Issue by Ashuangshuang** [vueComponent/ant-design-vue#7406]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表单中的提示语label想放在ant-select边框内部，类似Input 配置prefix:"姓名"的效果。如果可以希望数据录入组件都能支持传入prefix

### What does the proposed API look like?
支持prefix属性或插槽

**Comment by selicens** [comment]
`a-select-option`就能实现这个需求吧
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/3a524e0f-4eae-4c2a-9567-bdd0c9d31c49)

**Comment by Ashuangshuang** [comment]
> `a-select-option`就能实现这个需求吧 ![image](https://private-user-images.githubusercontent.com/69418751/310347506-3a524e0f-4eae-4c2a-9567-bdd0c9d31c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzQ3MjYsIm5iZiI6MTcwOTc3NDQyNiwicGF0aCI6Ii82OTQxODc1MS8zMTAzNDc1MDYtM2E1MjRlMGYtNGVhZS00YzJhLTk1NjctYmRkMGM5ZDMxYzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2FlMjUzYTQyM2E0YmRjODZjNDIxOTliMjU4NzQ0ZDIzMWRiNTk2ZmRhNjRkYTk5MWRiYjQ1MmZmMGRiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQZyhS01vEu0eOsl5XXyQovPaXaMIXVRMRLW-X6hTAg)

想放在select框前面，不是option的前面

**Comment by selicens** [comment]
> > `a-select-option`就能实现这个需求吧 ![image](https://private-user-images.githubusercontent.com/69418751/310347506-3a524e0f-4eae-4c2a-9567-bdd0c9d31c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzQ3MjYsIm5iZiI6MTcwOTc3NDQyNiwicGF0aCI6Ii82OTQxODc1MS8zMTAzNDc1MDYtM2E1MjRlMGYtNGVhZS00YzJhLTk1NjctYmRkMGM5ZDMxYzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2FlMjUzYTQyM2E0YmRjODZjNDIxOTliMjU4NzQ0ZDIzMWRiNTk2ZmRhNjRkYTk5MWRiYjQ1MmZmMGRiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQZyhS01vEu0eOsl5XXyQovPaXaMIXVRMRLW-X6hTAg)
> 
> 想放在select框前面，不是option的前面

明白了

**Comment by Ashuangshuang** [comment]
> > > `a-select-option`就能实现这个需求吧 ![image](https://private-user-images.githubusercontent.com/69418751/310347506-3a524e0f-4eae-4c2a-9567-bdd0c9d31c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NzQ3MjYsIm5iZiI6MTcwOTc3NDQyNiwicGF0aCI6Ii82OTQxODc1MS8zMTAzNDc1MDYtM2E1MjRlMGYtNGVhZS00YzJhLTk1NjctYmRkMGM5ZDMxYzQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAxMjAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2FlMjUzYTQyM2E0YmRjODZjNDIxOTliMjU4NzQ0ZDIzMWRiNTk2ZmRhNjRkYTk5MWRiYjQ1MmZmMGRiMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TQZyhS01vEu0eOsl5XXyQovPaXaMIXVRMRLW-X6hTAg)
> > 
> > 
> > 想放在select框前面，不是option的前面
> 
> 明白了
请问表单项可以支持这个功能吗？
