### ISSUE TITLE
Tree组件tree-data属性的TS类型错误

### ISSUE THREAD

**Issue by UlyssesChou** [vueComponent/ant-design-vue#7407]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
antd 4.1.0

### Reproduction link
[http://demo](http://demo)

### Steps to reproduce
```
<a-tree
:checkable="true"
:fieldNames="replaceFields"
:tree-data="permissionList"
:default-expand-all="true"
:checkStrictly="true"
v-model:checkedKeys="checkedKeys"
/>
```

tree组件中，我得结果集是permissionList，同时搭配fieldNames一起使用，IDE编译器提示TS类型【DataNode[]】不一致。我看DataNode的key目前是不能为空。

```
export interface DataNode extends BasicDataNode {
children?: DataNode[];
key: string | number;
title?: any;
}
```

### What is expected?
```
export interface DataNode extends BasicDataNode {
children?: DataNode[];
key?: string | number;
title?: any;
}
```

### What is actually happening?
```
export interface DataNode extends BasicDataNode {
children?: DataNode[];
key: string | number;
title?: any;
}
```

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/8328206f-37e5-4368-a234-f6f91d41cc33)
这样使用试下

**Comment by UlyssesChou** [comment]
TreeData对象类型，里面的变量'key'是不能为空的，treedata这样子定义当前代码IDE也会提示

**Comment by selicens** [comment]
确实

**Comment by AlexL0ng** [comment]
我想控制tree树状控件某些节点根据一个响应式来判断css隐藏或者显；但是tree的api似乎没有提供这个
然后我使用default插槽；提示报错
<img width="598" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/53669064/68b6d86e-8395-4aa1-bd4e-aacb33456d9b">

**Comment by ysl-ccc** [comment]
这个类型好像内办法解决吧，只能使用类型断言，例如
```
:tree-data="permissionList as unkown as TreeProps['treeData']"

```
