### ISSUE TITLE
Supports Table.EXPAND_COLUMN or Table.SELECTION_COLUMN

### ISSUE THREAD

**Issue by FlyingTigerReally** [vueComponent/ant-design-vue#7409]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Custom expandedRowRender position.
Reference antd：https://codesandbox.io/p/sandbox/te-shu-lie-pai-xu-antd-5-10-1-m3rydg?file=%2Fdemo.tsx%3A13%2C1

### What does the proposed API look like?
vue3

**Comment by goodtan** [comment]
vue3中 似乎并没有能支持这样子做 似乎并不能改变位置 使用expandIconColumnIndex 你就报错了提示expandIconColumnIndex` is deprecated. Please use `Table.EXPAND_COLUMN` in `columns` instead.
<img width="417" alt="image" src="https://github.com/user-attachments/assets/0d1c9907-8129-4da9-9e5d-1ea22a52e8eb">
![image](https://github.com/user-attachments/assets/8053ed61-2561-4131-a647-3e50127b7409)
![image](https://github.com/user-attachments/assets/16cc07a0-bc86-4ea3-ac7e-2cff5988323d)
