### ISSUE TITLE
怎么定制化主题色：怎么修改主题色，比如整体是粉色的

### ISSUE THREAD

**Issue by wangyujiaoflag** [vueComponent/ant-design-vue#7411]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.0.8

### Environment
vue3

### Reproduction link
[https://github.com/jeecgboot/jeecgboot-vue3.git](https://github.com/jeecgboot/jeecgboot-vue3.git)

### Steps to reproduce
怎么修改主题色，比如整体是粉色的

### What is expected?
主题色修改成功

### What is actually happening?
没办法改，改table、form组件主题色失败 不生效，

**Comment by Ashuangshuang** [comment]
`<a-config-provider
      :theme="{
      token: {
        colorPrimary: '#7540e3',
      }
      }"
    >
      <router-view />
    </a-config-provider>`

**Comment by bsuooo** [comment]
https://next.antdv.com/components/config-provider-cn#components-config-provider-demo-theme
