### ISSUE TITLE
官网 antdv.com 的 Icon 组件页在Firefox 浏览器下无法访问

### ISSUE THREAD

**Issue by willian12345** [vueComponent/ant-design-vue#7412]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Firefox Browser 123.0 (64-bit), windows10

### Reproduction link
[https://antdv.com/components/icon](https://antdv.com/components/icon)

### Steps to reproduce
antdv.com 官网进入icon 组件而，下无法访问，浏览器控制台输出 ：

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://next.antdv.com/assets/VideoCameraOutlined.61ac7046.js. (Reason: CORS request did not succeed). Status code: (null).

TypeError: error loading dynamically imported module: https://next.antdv.com/assets/index.0f612576.js

### What is expected?
如chrome 浏览器下正常访问

### What is actually happening?
火狐浏览器下无法访问 icon 组件页

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/a66ec5ea-c666-447a-b59f-71b49132059b)
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/257b0081-d472-4630-88e9-9a742903b4d8)
我这边显示正常

**Comment by willian12345** [comment]
啊，发现是我的问题。被adBlocker 插件 影响了
