### ISSUE TITLE
Select dropdwn blinks whenever Click 2nd time after closing it.

### ISSUE THREAD

**Issue by blukhi99** [vueComponent/ant-design-vue#7415]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Vue-3, Chrome, Windows 10

### Reproduction link
[https://drive.google.com/drive/folders/1EWAWMhm8VnHolRBdWavD57A4r6nmbGjE?usp=drive_link](https://drive.google.com/drive/folders/1EWAWMhm8VnHolRBdWavD57A4r6nmbGjE?usp=drive_link)

### Steps to reproduce
1) Click on Dropdown
2) Close DropDown
3) Try to open again now it will start to flickering

DropDown, Select or confirm popup all transitions animation where is happening everywhere has issue.

### What is expected?
it should open when try to open each time after first time.

### What is actually happening?
Once the component renders and I click on any dropdown it shows my default 10 options which I have shown it as default options. But when I click 2nd time on the same dropdown it just flashes the options and closing it self each time I click on the select field.

**Comment by selicens** [comment]
follow #7346

**Comment by blukhi99** [comment]
without merge how can I fixed at my side?
i am not sure when will this changes merge. I require asap.

**Comment by blukhi99** [comment]
> follow #7346

without merge how can I fixed at my side?
i am not sure when will this changes merge. I require asap.

**Comment by selicens** [comment]
> > follow #7346
> 
> without merge how can I fixed at my side? i am not sure when will this changes merge. I require asap.

Downgrading or fixing Vue version to 3.3.x

**Comment by blukhi99** [comment]
which version is most stable? i am using vue3 and antd - ^4.1.2

**Comment by blukhi99** [comment]
@selicens  i have same issue in ant-design-vue@^3.3.0-beta.4

**Comment by selicens** [comment]
Vue version

**Comment by gambe** [comment]
Downgrade to vue 3.4.17 until it's fixed

**Comment by wsxe9988** [comment]
> follow #7346

啥时候合并pr,发个新版，大哥，帮忙问下唐老师，很久了

**Comment by tangjinzhou** [comment]
update vue to 3.4.23+
