### ISSUE TITLE
Image组件预览图片无法添加crossorigin属性

### ISSUE THREAD

**Issue by xh-shen** [vueComponent/ant-design-vue#7416]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
所有

### Reproduction link
[https://next.antdv.com/components/image-cn#previewtype](https://next.antdv.com/components/image-cn#previewtype)

### Steps to reproduce
Image组件预览时img无法追加crossorigin属性

### What is expected?
preview对象下支持crossorigin配置

### What is actually happening?
导致有些图片无法加载

**Comment by xh-shen** [comment]
没人回话吗

**Comment by huiliangShen** [comment]
bug
按照antd的写法，img自己的属性应该直接用Image标签上的，preview上并没有配置参数

**Comment by xh-shen** [comment]
这个解决了吗

**Comment by xh-shen** [comment]
![Uploading 1111.png…]()

**Comment by LHiaoeng** [comment]
referrerpolicy 属性也不行。 version：4.2.3

**Comment by whitersun** [comment]
看起來好像官方沒有打算把 crossOrigin 添加到 vue 版本裡面, 目前我使用的 ant design vue 已經是最新版本來, 看 docs api 還是沒有看到官方添加 crossOrigin, 參數使用。而外好像官方比較喜歡在 react 那邊優化, 因為我在 react 的版本有看到他們有添加一個參數是 items, 裡面可以添加 crossOrigin
