### ISSUE TITLE
如何通过主题 （theme）的方式修改layout里面header的高度

### ISSUE THREAD

**Issue by snoopy1412** [vueComponent/ant-design-vue#7426]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
我发现在ConfigProvider里面的theme里面希望修改layout里面的header高度的时候发现不支持，只能够修改有限的一些颜色token

### What does the proposed API look like?
layoutHeaderHeight: 40

**Comment by l1utian** [comment]
我也遇到了此问题...

**Comment by hongzzz** [comment]
Same issue here.
