### ISSUE TITLE
Strange behavior when setting TreeNode title

### ISSUE THREAD

**Issue by YipingRuan** [vueComponent/ant-design-vue#7435]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
Windows 11, Edge 122.0.2365.80

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-nqyajv?file=src%2Fcomponents%2FHelloWorld.vue](https://stackblitz.com/edit/vitejs-vite-nqyajv?file=src%2Fcomponents%2FHelloWorld.vue)

### Steps to reproduce
Case 1:
Click the "Set title" button

Case 2:
1.  Collapse "parent 1-1" node
2. Click the "Set title" button

### What is expected?
The tree node title should be updated, the tree should not collapse

### What is actually happening?
The tree collapse or the title is not updated (until the user click the node)

**Comment by selicens** [comment]
More detailed description is required, such as how to use it on components
