### ISSUE TITLE
Statistic component in ant-design-vue

### ISSUE THREAD

**Issue by rsrogers4** [vueComponent/ant-design-vue#744]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I would like to use the Statistic component from Ant Design in Vue. Is there a plan to implement the Statistic component in ant-design-vue?

### What does the proposed API look like?
The API would match the Ant Design Statistic API.

**Comment by rsrogers4** [comment]
@tangjinzhou, thank you!

**Comment by kevinpthorne** [comment]
This doesn't look like it's been implemented yet? There's documentation, but no implementation. (Using 1.3.17)
