### ISSUE TITLE
link的颜色随着主题色变更

### ISSUE THREAD

**Issue by duxincai** [vueComponent/ant-design-vue#7441]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
<a-button type="link">Link Button</a-button>
希望颜色随着 primary color变更，而不是固定的#1677ff

### What does the proposed API look like?
可以像danger一样再加一个属性，或者默认就是随着主题色变更

**Comment by jack-7788** [comment]
默认就是支持的，多看文档，看“动态主题”

**Comment by duxincai** [comment]
默认就支持的？
你说的“动态主题”，是在a-config-provider单独设置颜色吧
colorLink/colorLinkActive/colorLinkHover

我想的是link button被归类到button里面，默认行为是跟其它种类button一样随着主题色变更而变更
或者弄个布尔属性，决定primary/success之类的

**Comment by LogicSong** [comment]
难道固定成#1677ff比跟随主题色更合理？嘴真硬。
