### ISSUE TITLE
那个滚动轴真的很难看

### ISSUE THREAD

**Issue by luocong2016** [vueComponent/ant-design-vue#7442]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
美观级联、下拉框、树形选择等

### What does the proposed API look like?
如：element-ui、naive-ui

**Comment by wermdany** [comment]
你这种个性化要求，自己改一下嘛，又不是没有 class，全局覆盖一下
