### ISSUE TITLE
migrate vue2 to vue3 

### ISSUE THREAD

**Issue by BryanLe97** [vueComponent/ant-design-vue#7449]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
MacOS

### Reproduction link
[https://codeshare.io/DAop9l](https://codeshare.io/DAop9l)

### Steps to reproduce
I upgrade vue 1.6.0 into vue 3.4.0 and AntD 1.7.8 into 4.1.0, and using vue/compat 3.4.0

### What is expected?
not show error Cannot read properties of undefined (reading 'prefixCls')

### What is actually happening?
it shows an error  Cannot read properties of undefined (reading 'prefixCls')
in .pnpm/@ant-design icons-vue@7.0.1_vue@3.4.0/node_modules/@ant-design/icons-vue/es

---
is any advice please

**Comment by zhuzhuaicoding** [comment]
这个怎么解决啊 最近在升级框架，用vue/compat跑不起来
