### ISSUE TITLE
DirectoryTree props expandAction doesn't work for "doubleclick"

### ISSUE THREAD

**Issue by webdesus** [vueComponent/ant-design-vue#745]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Chrome 73, Vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wnq92o8jrw?fontsize=14)

### Steps to reproduce
I just tried use property expandAction accordidng docs for dubleclick mode

### What is expected?
Expanded list by dubleclick

### What is actually happening?
nothing

**Comment by nickolboy** [comment]
发现同样问题
