### ISSUE TITLE
When i have multiple steps, the title with icon would be distort.

### ISSUE THREAD

**Issue by shiwanjun1995** [vueComponent/ant-design-vue#7450]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
online

### Reproduction link
[https://3x.antdv.com/components/steps/#Steps](https://3x.antdv.com/components/steps/#Steps)

### Steps to reproduce
no

### What is expected?
normal

### What is actually happening?
abnormal

![abc](https://github.com/vueComponent/ant-design-vue/assets/38515714/9b2b9234-7bac-46e8-a9d2-7d6078d764f8)

@selicens

**Comment by selicens** [comment]
text or icon

**Comment by shiwanjun1995** [comment]
> text or icon

啥？文本或者图标，没有看明白呀。
场景：用抽屉 drawer 组件，给它固定的宽度，比如1000px，内部有一个步骤条 step 组件，step 内部的 item 足够多的话，步骤线有些缺失，并且步骤标题都遮住了。设置普通的样式，比如什么 overflow-x: auto; 都不生效，咋破呢。

**Comment by shiwanjun1995** [comment]
> text or icon

Any body help?

**Comment by alicemw** [comment]
![1c978f20d65ec65fa0e8abbca2e803b7_18591](https://github.com/user-attachments/assets/035112c4-f395-491b-92ca-a2a6a8acd977)
恶心到我了

**Comment by shiwanjun1995** [comment]
> ![1c978f20d65ec65fa0e8abbca2e803b7_18591](https://private-user-images.githubusercontent.com/28859051/366323343-035112c4-f395-491b-92ca-a2a6a8acd977.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzYzMjAsIm5iZiI6MTcyNjAzNjAyMCwicGF0aCI6Ii8yODg1OTA1MS8zNjYzMjMzNDMtMDM1MTEyYzQtZjM5NS00OTFiLTkyY2EtYTJhNmE4YWNkOTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA2MjcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMmFiZjIzZjcwMjM5ZGZkMDZmMzAwZTNhNWFlNzU2YWQyN2Y5Yzg3YWZlNTY0YmQ2Y2M1N2FkOTdhOTRlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._cqQpAYOmJrzJkgccHCp9HtbFitv6Zh5zPsbNFrT10A) 恶心到我了

咱有的用就不错了，恶心这个词严重了。但是官方没进展，确实也没谁了。。
