### ISSUE TITLE
能不能在rang-date-picker加个next的方法

### ISSUE THREAD

**Issue by lllianreg** [vueComponent/ant-design-vue#7452]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
比如使用日期时间组件时
我设定就是YYYY-MM-DD 00:00:00 - YYYY-MM-DD 23:59:59   只要用户选日期了  时间默认就给他设定好的值  不用点[确定]才去跳转下个值 （因为很大比例的用户不会去选择时间只有特殊情况下会用到）
可以自动跳转第二个日期选择或者expose一个next的方法 让开发人员可以根据用户需求自己diy
现在暴露的方法真是少到diy不起来啊
我们产品好多次都跟我说 我们换个组件吧 我TM。。。

### What does the proposed API look like?
expose({ next });

**Comment by huanguanga** [comment]
确实是这样，大多数人没有点确定的习惯

**Comment by huanguanga** [comment]
看之前的帖子，MutationObserver 这个API可以实现不点击确认就选定时间
