### ISSUE TITLE
你们的codesandbox真特么辣鸡，在线例子完全写不了

### ISSUE THREAD

**Issue by Jveen-D** [vueComponent/ant-design-vue#7453]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html)

### Steps to reproduce
https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html

### What is expected?
https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html

### What is actually happening?
https://codesandbox.io/p/sandbox/yuan-cheng-jia-zai-shu-ju-ant-design-vue-4-1-2-rk4krq?file=%2Findex.html

**Comment by selicens** [comment]
有相关pr没有合并

**Comment by CatMiaogu** [comment]
目前看还是有问题的，为什么没解决还关闭问题了

**Comment by selicens** [comment]
> 目前看还是有问题的，为什么没解决还关闭问题了

不觉得对开源社区是一个正向反馈
