### ISSUE TITLE
使用setFieldsValue动态更改表单项时，当前正在输入的那个表单项的值无法被更改

### ISSUE THREAD

**Issue by catiscat** [vueComponent/ant-design-vue#746]
- [1] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
system: macOS 10.12.6 ,  chrome: Version 75.0.3759.4 (Official Build) dev (64-bit) , vue : 1.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50kqnpyvjn)

### Steps to reproduce
在输入框中输入任意值

### What is expected?
输入框的值被重置为 ‘hello world’

### What is actually happening?
输入框的值就是当前输入的值，并没有被重置

**Comment by sendya** [comment]
可能需要考虑并发问题。

也可以为 `handleChange` 的方法操作加个定时器来错开

```
      setTimeout(() => {
          this.form.setFieldsValue({
          test: "hello world"
        });
      }, 16)
```

**Comment by wustzhaohui** [comment]
还有能不能在调用`setFieldsValue`方法的时候，可以将那个未加载input框就赋值的警告做出可关闭配置呢？

**Comment by sendya** [comment]
> 还有能不能在调用`setFieldsValue`方法的时候，可以将那个未加载input框就赋值的警告做出可关闭配置呢？

用户也没人会去开这 `console` 用。这就没什么区别了。当作 dev log 就好了

**Comment by wustzhaohui** [comment]
> > 还有能不能在调用`setFieldsValue`方法的时候，可以将那个未加载input框就赋值的警告做出可关闭配置呢？
> 
> 用户也没人会去开这 `console` 用。这就没什么区别了。当作 dev log 就好了

强迫症表示很烦...

**Comment by Polaris-z** [comment]
![image](https://user-images.githubusercontent.com/28984303/57912867-eead5600-78bd-11e9-8f1b-656dd0d11ebe.png)
直接在change事件里setvalue 会产生竟态 ，组件已经提供了接口解决这个问题。
