### ISSUE TITLE
pnpm缓存为什么对ant-design-vue无效

### ISSUE THREAD

**Issue by xiangnanscu** [vueComponent/ant-design-vue#7469]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
macos

### Reproduction link
[https://vuecomponent.github.io/issue-helper/](https://vuecomponent.github.io/issue-helper/)

### Steps to reproduce
just repeatedly delete and install node_modules via `pnpm i`

### What is expected?
pnpm will cache `ant-design-vue` without downloading

### What is actually happening?
```
mac@MacdeMacBook-Pro zzb % pnpm i
Lockfile is up to date, resolution step is skipped
Packages:  782
                                                                                                
Downloading registry.npmmirror.com/ant-design-vue/3.2.20: 10.34 MB/10.34 MB, done
Progress: resolved 782, reused 780, downloaded 2, added 782, done
```

**Comment by jack-7788** [comment]
要什么缓存呢，直接指定一个具体的版本号不就好了
