### ISSUE TITLE
[DatePicker] After blur,  the value dose NOT update as user typed

### ISSUE THREAD

**Issue by gaokun** [vueComponent/ant-design-vue#7472]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.x and 3.x

### Environment
offcial website

### Reproduction link
[https://next.antdv.com/components/date-picker-cn](https://next.antdv.com/components/date-picker-cn)

### Steps to reproduce
1. open https://next.antdv.com/components/date-picker-cn
2. choose a datepicker, select '2024-04-02'
3. focus the picker, update text as '2024-04-03'
4. click outside (blur)

### What is expected?
the value should be updated as '2024-04-03'

### What is actually happening?
the value is still '2024-04-02'

---
I did same test on '[ant-deisgn react](https://ant-design.antgroup.com/components/date-picker-cn)' and '[ant-design-vue 2.x](https://2x.antdv.com/components/date-picker-cn)', works find for both of them.

The issue only happens on ant-design-vue 4.x and 3.x

**Comment by gaokun** [comment]
Saw this [comment](https://github.com/vueComponent/ant-design-vue/blob/fa46999963a06733e69930ae7461f3c0efc358c2/components/vc-picker/hooks/usePickerInput.ts#L37)

```
/**
   * We will prevent blur to handle open event when user click outside,
   * since this will repeat trigger `onOpenChange` event.
   */
```

Can we find a balance way on that?

**Comment by gaokun** [comment]
Plz refer to [below](https://github.com/vueComponent/ant-design-vue/blob/fa46999963a06733e69930ae7461f3c0efc358c2/components/vc-picker/hooks/usePickerInput.ts#L166)

change `triggerOpen(false)` to `onSubmit()` will resolve my question

```
  // Global click handler
  onMounted(() => {
    globalMousedownEvent.value = addGlobalMousedownEvent((e: MouseEvent) => {
      const target = getTargetFromEvent(e);

      if (open.value) {
        const clickedOutside = isClickOutside(target);

        if (!clickedOutside) {
          preventBlurRef.value = true;

          // Always set back in case `onBlur` prevented by user
          raf(() => {
            preventBlurRef.value = false;
          });
        } else if (!focused.value || clickedOutside) {
          triggerOpen(false);   // change to `onSubmit()` will resolve my question
        }
      }
    });
  });
```

**Comment by ChangJin0520** [comment]
I encountered the same problem. Losing focus does not change the value, which gives users a wrong perception.

**Comment by MySecret** [comment]
删除onBlur里面的triggerOpen(false);就可以了。

**Comment by fq1798** [comment]
终于解决了：以下是参考思路：
`<template>
  <a-date-picker ref="simpleDatePicker" format="YYYY-MM-DD" />
</template>


<script setup name="JDatePicker">
import {onMounted, onUnmounted, ref} from "vue";

const simpleDatePicker = ref();
const value = ref();

const emit = defineEmits('change');

const handleDatePickerBlur: any = (e, n) => {
  // 2020-02-02
  if(e.target.value.length == 10) {
    // value.value = e.target.value;

    emit('change',  e.target.value);
  }

}

onMounted(() => {
  // 监听 change 事件
  document.querySelector(".ant-picker-input")
      .querySelector("input").addEventListener('input', handleDatePickerBlur);
});

onUnmounted(() => {
  // 移除 change 事件监听器
  document.querySelector(".ant-picker-input")
      .querySelector("input").removeEventListener('input', handleDatePickerBlur);
});



</script>
`
