### ISSUE TITLE
Dropdown组件绝对定位的top和left偏移量 有时候计算错误

### ISSUE THREAD

**Issue by rose-sun** [vueComponent/ant-design-vue#7481]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
2.2.6

### Environment
vue 3.2.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/frosty-pine-sj3dz4?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A100%2C4)

### Steps to reproduce
我设置了Dropdown的getPopupContainer属性为其父元素，没有设置placement属性，让其自动计算朝向。
正常情况下，bottomLeft的绝对偏移量应该是 left: -1px; top: 28px左右，Dropdown能正常显示在bottomLeft方位；
但是有 1/5 的概率，计算出来的left: 277px; top: -550px，导致Dropdown框溢出容器，根本看不到了。
我是这么写的：
<a-dropdown :trigger="['hover']" :mouseEnterDelay="0.3" :mouseLeaveDelay="0.2" :getPopupContainer="(triggerNode) =>triggerNode.parentElement">
<div class="icon"></div>
<template #overlay>
<a-menu>
<a-menu-item v-for="item in list " :key="item.name" @click="handleClick">
<div class="menu-item"></div>
</a-menu-item>
</a-menu>
</template>
</a-dropdown>

### What is expected?
期望能正常计算其偏移量，不要偏移过大，导致看不到框

### What is actually happening?
多次尝试，有1/5概率Dropdown组件的偏移量计算错误

**Comment by qhl123456** [comment]
getPopupContainer多加几个parentNode试试，我偶尔也会这样，直接定位到最最最外层的元素上，有时候父元素的宽度计算的有问题
