### ISSUE TITLE
使用循环生成a-menu-item选择默认的key不生效

### ISSUE THREAD

**Issue by linzehai0801** [vueComponent/ant-design-vue#7489]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
Vue3

### Reproduction link
[https://www.antdv.com/components/layout-cn](https://www.antdv.com/components/layout-cn)

### Steps to reproduce
<a-menu v-for="menu in menu_list" v-model:selectedKeys="selectedKeys" theme="dark" mode="inline">
<a-menu-item v-if="menu.children.length===0" :key="menu.id">
{{ menu.id }}
<router-link :to="menu.menu_url">
<template v-if="menu.icon === 'PieChartOutlined'">
<PieChartOutlined/>
</template>
<template v-else-if="menu.icon === 'DesktopOutlined'">
<DesktopOutlined/>
</template>
<template v-else-if="menu.icon === 'FieldTimeOutlined'">
<FieldTimeOutlined/>
</template>
<span> {{ menu.title }}</span>
</router-link>
</a-menu-item>
</a-menu>
const collapsed = ref(false);
const selectedKeys = ref(['1']);
{
id: 1, icon: 'PieChartOutlined', title: '展示中心', tube: '', 'menu_url': '/uric/show_center', children: []
},
{
id: 2, icon: 'DesktopOutlined', title: '资产管理', 'menu_url': '/uric/host', children: []
},

### What is expected?
期望const selectedKeys = ref(['1']);时会被默认选中

### What is actually happening?
没有选中任何

**Comment by qppq54s** [comment]
id改成 ‘1’ 试试

**Comment by linzehai0801** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/88591254/416dedaa-64ad-4deb-acd1-9bf8f018ddea)
<template>
  <a-layout style="min-height: 100vh">
    <a-layout-sider v-model:collapsed="collapsed" collapsible>
      <div class="logo"
           style="font-style: italic;text-align: center;font-size: 20px;color:#fff;margin: 10px 0;background-color: #333;line-height: 50px;font-family: 'Times New Roman'">
        <span> aaa</span>
      </div>
      <a-menu v-for="menu in menu_list" v-model:selectedKeys="selectedKeys" theme="dark" mode="inline">
        <a-menu-item v-if="menu.children.length===0" :key="menu.id">
          {{ menu.id }}
          <router-link :to="menu.menu_url">
            <template v-if="menu.icon === 'PieChartOutlined'">
              <PieChartOutlined/>
            </template>
            <template v-else-if="menu.icon === 'DesktopOutlined'">
              <DesktopOutlined/>
            </template>
            <template v-else-if="menu.icon === 'FieldTimeOutlined'">
              <FieldTimeOutlined/>
            </template>
            <span> {{ menu.title }}</span>
          </router-link>
        </a-menu-item>
      </a-menu>
    </a-layout-sider>
    <a-layout>
      <a-layout-header style="background: #fff; padding: 0;height: 60px">
        <div style="float: right;padding-right: 40px">
          <a-dropdown>
            <a class="ant-dropdown-link" @click.prevent>
              Hover me
              <DownOutlined/>
            </a>
            <template #overlay>
              <a-menu>
                <a-menu-item>
                  <a href="javascript:;">1st menu item</a>
                </a-menu-item>
                <a-menu-item>
                  <a href="javascript:;">2nd menu item</a>
                </a-menu-item>
                <a-menu-item>
                  <a href="javascript:;">3rd menu item</a>
                </a-menu-item>
              </a-menu>
            </template>
          </a-dropdown>
        </div>

        <div style="float: right;padding-right: 20px">
          <a-avatar :size="32">
            <template #icon>
              <UserOutlined/>
            </template>
          </a-avatar>
        </div>
      </a-layout-header>
      <a-layout-content style="margin: 0 16px">
        
        
        
        
        
        <a-breadcrumb style="margin: 16px 0">
          <a-breadcrumb-item>主页</a-breadcrumb-item>
          <template v-for="item in menu_list" :key="item.id">
            <a-breadcrumb-item v-if="item.id === selectedKeys[0]">{{ item.title }}</a-breadcrumb-item>
          </template>
        </a-breadcrumb>

        <div :style="{ padding: '24px', background: '#fff', minHeight: '360px' }">
          <router-view></router-view>
        </div>
      </a-layout-content>
      <a-layout-footer style="text-align: center">
        Ant Design ©2024 Created by Ant UED
      </a-layout-footer>
    </a-layout>
  </a-layout>
</template>
<script setup>

import {defineComponent, ref} from 'vue';
import {
  PieChartOutlined,
  DesktopOutlined,
  FieldTimeOutlined,
  UserOutlined,
  DownOutlined
} from '@ant-design/icons-vue'

const collapsed = ref(false);
const selectedKeys = ref(['1']);
const menu_list = ref([
  {
    id: 1, icon: 'PieChartOutlined', title: '展示中心', tube: '', 'menu_url': '/uric/show_center', children: []
  },
  {
    id: 2, icon: 'DesktopOutlined', title: '资产管理', 'menu_url': '/uric/host', children: []
  },
  {
    "id": 3, icon: 'bold', title: '批量任务', tube: '', menu_url: '/uric/workbench', children: [
      {id: 10, icon: 'mail', title: '执行任务', 'menu_url': '/uric/multi_exec'},
      {id: 11, icon: 'mail', title: '命令管理', 'menu_url': '/uric/template_manage'},
    ]
  },
  {
    id: 4, icon: 'highlight', title: '代码发布', tube: '', menu_url: '/uric/workbench', children: [
      {id: 12, title: '应用管理', menu_url: '/uric/release'},
      {id: 13, title: '发布申请', menu_url: '/uric/release'}
    ]
  },
  {id: 5, icon: 'FieldTimeOutlined', title: '定时计划', tube: '', menu_url: '/uric/workbench', children: []},
  {
    id: 6, icon: 'mail', title: '配置管理', tube: '', menu_url: '/uric/workbench', children: [
      {id: 14, title: '环境管理', 'menu_url': '/uric/environment'},
      {id: 15, title: '服务配置', 'menu_url': '/uric/workbench'},
      {id: 16, title: '应用配置', 'menu_url': '/uric/workbench'}
    ]
  },
])

</script>
<style scoped>
#components-layout-demo-side .logo {
  height: 32px;
  margin: 16px;
  background: rgba(255, 255, 255, 0.3);
}

.site-layout .site-layout-background {
  background: #fff;
}

[data-theme='dark'] .site-layout .site-layout-background {
  background: #141414;
}
</style>这是我的脚本麻烦帮忙看看

**Comment by qppq54s** [comment]
@linzehai0801 我的意思是，你的id是数字，但是selectKeys里的是字符串，这两个要保持统一，把你menu_list里的id:1改成id: '1'这样
