### ISSUE TITLE
a-alert通过v-show来控制显示隐藏的bug

### ISSUE THREAD

**Issue by yanyalin** [vueComponent/ant-design-vue#7492]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
win10、google：123版本、vue：3.4.15

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/devbox/vue-demo-rtjj7j?file=%2Fsrc%2FApp.vue%3A5%2C31)

### Steps to reproduce
连续点击按钮,a-alert组件，无法再次显示

### What is expected?
连续点击按钮,a-alert组件会根据v-show，显示和隐藏

### What is actually happening?
默认隐藏，只能通过v-show显示一次，后面就不在显示了

**Comment by tangjinzhou** [comment]
使用 vIf， alert 的设计就是不支持再次打开的
