### ISSUE TITLE
button组件图标样式有问题

### ISSUE THREAD

**Issue by ModernVocationalEducation** [vueComponent/ant-design-vue#7494]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
全部最新版本

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-fy7q3f?file=src%2FApp.vue](https://stackblitz.com/edit/vitejs-vite-fy7q3f?file=src%2FApp.vue)

### Steps to reproduce
在这里https://stackblitz.com/edit/vitejs-vite-fy7q3f?file=src%2FApp.vue

### What is expected?
希望按钮垂直居中

### What is actually happening?
按钮靠上

**Comment by fucktic** [comment]
为什么我的项目里图标靠下面

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/42da27be-cee9-4cb3-bd3a-15d2723b72fa)
`@ant-design/icons-vue`引入的图标是有样式的，自行导入svg需要自定义样式

**Comment by renjiangwei** [comment]
> 为什么我的项目里图标靠下面 ![screenshot-20240418-160932](https://private-user-images.githubusercontent.com/88186088/323520087-64867caa-774e-47f0-b164-d9795598f3f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjY4MjUsIm5iZiI6MTcxNzEyNjUyNSwicGF0aCI6Ii84ODE4NjA4OC8zMjM1MjAwODctNjQ4NjdjYWEtNzc0ZS00N2YwLWIxNjQtZDk3OTU1OThmM2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAzMzUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZmUzNDdhMmIxMGY2NGQyMmRhODcxYTc1MjdiOGY1OWExY2I2NDA4ZjEzNTlkOWNjMjM0MmFhZGY2MWI2MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kbNMxlvUdy3SdKuTSBw0ZuD7NiJkJ7pkOq8TV1t5Lt8) 强烈要求给出原因

看看有没有全局svg的样式，或者某些css框架的全局样式影响了，vertical-align
