### ISSUE TITLE
table API 'expandIcon' not working

### ISSUE THREAD

**Issue by oagsate** [vueComponent/ant-design-vue#750]
The doc says that adding the 'expandIcon' prop can change the expand icon, but it doesn't really work.
I've checked the components/table/interface.js, and there isn't 'expandIcon' in TableProps. When I added it('expandIcon: PropTypes.func') in , it worked.
So is it just forgotten or there is some other reason?

**Comment by wtyang** [comment]
虽然他没有按格式提，但是你们都不认真读一下这么短的文字么。 我查了很多资料，只有他提的这个问题解决了相关问题。
