### ISSUE TITLE
Modal.confirm中的content作为jsx时，表单元素Input的双向绑定无效

### ISSUE THREAD

**Issue by lovelyJason** [vueComponent/ant-design-vue#7501]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows10, chrome 123.0.6312.122（正式版本） （64 位）, Vue: 3.3.4， ant-design-vue: 4.0.2

### Reproduction link
[https://stackblitz.com/~/github.com/vbenjs/vue-vben-admin](https://stackblitz.com/~/github.com/vbenjs/vue-vben-admin)

### Steps to reproduce
1. 打开我提供的最小仓库，运行项目
2. 点击表格中【跳转】，弹出窗口，输入框输入内容， 如下图

![c](https://github.com/vueComponent/ant-design-vue/assets/50656459/2278cc18-5c5a-4fa9-a9e2-968e2f41be65)

### What is expected?
Modal.confirm中的content要求具有响应式

### What is actually happening?
表单元素输入的时候，值不被更新；实际上就是手动实现受控组件的时候，Input输不进去值

**Comment by lovelyJason** [comment]
> * [x]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### Version
> undefined
> 
> ### Environment
> windows10, chrome 123.0.6312.122（正式版本） （64 位）, Vue: 3.3.4， ant-design-vue: 4.0.2
> 
> ### Reproduction link
> https://stackblitz.com/~/github.com/vbenjs/vue-vben-admin
> 
> ### Steps to reproduce
> 1. 打开我提供的最小仓库，运行项目
> 2. 点击表格中【跳转】，弹出窗口，输入框输入内容， 如下图
> 
> ![c](https://private-user-images.githubusercontent.com/50656459/322359632-2278cc18-5c5a-4fa9-a9e2-968e2f41be65.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk5OTksIm5iZiI6MTcxMzE1OTY5OSwicGF0aCI6Ii81MDY1NjQ1OS8zMjIzNTk2MzItMjI3OGNjMTgtNWM1YS00ZmE5LWE5ZTItOTY4ZTJmNDFiZTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmM2NlMTM0NTI3NjEzYjVjODIzNjliYjYyZWE4YmQzYTIzZTcyNGZjNTY2ZDlhYmE3YWY2Mjc3YWY2MTBlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7qcg2Qgb81s6xElw9gNoPlD3-1Jpk5hS9RYMCU7gMU) [ ![c](https://private-user-images.githubusercontent.com/50656459/322359632-2278cc18-5c5a-4fa9-a9e2-968e2f41be65.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk5OTksIm5iZiI6MTcxMzE1OTY5OSwicGF0aCI6Ii81MDY1NjQ1OS8zMjIzNTk2MzItMjI3OGNjMTgtNWM1YS00ZmE5LWE5ZTItOTY4ZTJmNDFiZTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmM2NlMTM0NTI3NjEzYjVjODIzNjliYjYyZWE4YmQzYTIzZTcyNGZjNTY2ZDlhYmE3YWY2Mjc3YWY2MTBlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7qcg2Qgb81s6xElw9gNoPlD3-1Jpk5hS9RYMCU7gMU) ](https://private-user-images.githubusercontent.com/50656459/322359632-2278cc18-5c5a-4fa9-a9e2-968e2f41be65.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk5OTksIm5iZiI6MTcxMzE1OTY5OSwicGF0aCI6Ii81MDY1NjQ1OS8zMjIzNTk2MzItMjI3OGNjMTgtNWM1YS00ZmE5LWE5ZTItOTY4ZTJmNDFiZTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmM2NlMTM0NTI3NjEzYjVjODIzNjliYjYyZWE4YmQzYTIzZTcyNGZjNTY2ZDlhYmE3YWY2Mjc3YWY2MTBlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7qcg2Qgb81s6xElw9gNoPlD3-1Jpk5hS9RYMCU7gMU) [ ](https://private-user-images.githubusercontent.com/50656459/322359632-2278cc18-5c5a-4fa9-a9e2-968e2f41be65.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk5OTksIm5iZiI6MTcxMzE1OTY5OSwicGF0aCI6Ii81MDY1NjQ1OS8zMjIzNTk2MzItMjI3OGNjMTgtNWM1YS00ZmE5LWE5ZTItOTY4ZTJmNDFiZTY1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA1NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmM2NlMTM0NTI3NjEzYjVjODIzNjliYjYyZWE4YmQzYTIzZTcyNGZjNTY2ZDlhYmE3YWY2Mjc3YWY2MTBlY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v7qcg2Qgb81s6xElw9gNoPlD3-1Jpk5hS9RYMCU7gMU)
> 
> ### What is expected?
> Modal.confirm中的content要求具有响应式
> 
> ### What is actually happening?
> 表单元素输入的时候，值不被更新；实际上就是手动实现受控组件的时候，Input输不进去值

这种做法无效：
```js
<script setup>
    const userToken = ref('');
    const emit = defineEmits();

    const onJumpClick = (record) => {
      console.log(emit);
  
      const handleInput = (event) => {
        console.log(event.target.value);
        userToken.value = event.target.value;
        emit('update:modelValue', userToken.value);
      };
  
      modal.confirm({
        title: '请填写一个用户token',
        icon: h(ExclamationCircleOutlined),
        content: (
          <div>
            <Input
              value={userToken.value}
              onChange={handleInput} // 使用 handleInput 处理输入事件
            />
          </div>
        ),
        onOk() {
          console.log('OK');
        },
      });
    };
</script>
```

然而下面这个做法倒是还行
```js
  const emit = defineEmits();
  const userToken = ref('');

  const onJumpClick = (record) => {
    console.log(emit);

    const handleInput = (event) => {
      console.log(event.target.value);
      userToken.value = event.target.value;
      // emit('update:modelValue', userToken.value);
    };

    modal.confirm({
      title: '请填写一个用户token',
      icon: h(ExclamationCircleOutlined),
      content: () => (
        <div>
          <Input v-model={userToken.value} />
        </div>
      ),
      onOk() {
        console.log('OK');
      },
    });
  };
```

**Comment by fanxiaodan-ra** [comment]
<Input v-model={[userToken, 'value']} /> 你要不要试试这样

**Comment by lllianreg** [comment]
比较麻烦 需要update  因为不能响应式更新
`
const modalUpdate = (modal, e) => {
  userToken.value = e?.target?.value || ''
  modal.update({
    title: '请填写一个用户token',
    content: (
      <div>
        <Input
          value={ userToken.value }
          onChange={ e=> modalUpdate(modal, e) }
        />
      </div>
    )
  })
}
const modal = Modal.confirm({})
modalUpdate(modal)
`
