### ISSUE TITLE
modal如何实现高度100% 宽度任意

### ISSUE THREAD

**Issue by qinghechaoge** [vueComponent/ant-design-vue#7506]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
项目中经常用到modal高度为屏幕100% 宽度任意的情况。我尝试了一些 没有办法达到理想的效果
请问 modal如何实现高度100% 宽度任意的效果
### What does the proposed API look like?
项目中经常用到modal高度为屏幕100% 宽度任意的情况。我尝试了一些 没有办法达到理想的效果
请问 modal如何实现高度100% 宽度任意的效果

**Comment by lllianreg** [comment]
`
.ant-modal { width: auto !important }
.ant-modal-wrap .ant-modal .ant-modal-content {
  height: 100vh;
  display: flex;
  flex-direction: column;
  .ant-modal-body {
    flex: 1;
    max-height: auto;
  }
}
`
