### ISSUE TITLE
table API 'expandIcon' not working

### ISSUE THREAD

**Issue by oagsate** [vueComponent/ant-design-vue#751]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
windows10, chrome 73.0.3683.103, vue 2.6.6, ant-design-vue 1.3.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8xm14kxmq2?fontsize=14)

### Steps to reproduce
In App.vue, method 'expandIcon' never runs.

### What is expected?
change the expand icon

### What is actually happening?
The doc says that adding the 'expandIcon' prop can change the expand icon, but it doesn't really work.
I've checked the components/table/interface.js, and there isn't 'expandIcon' in TableProps. When I added it('expandIcon: PropTypes.func') in , it worked.
So is it just forgotten or there is some other reason?

**Comment by tangjinzhou** [comment]
You can submit pr directly.
Now you can use `slot="expandIcon" slot-scope="props"` instead it.

**Comment by PatrickJS** [comment]
I also need this.

**Comment by Shawn1** [comment]
Hello tangjinzhou,

I hava tried in Chrome with ant-design-vue 1.3.10, "expandIcon" still cannot work by use slot.

<a-table
    :columns="columns"
    :dataSource="data"   :rowSelection="rowSelection"
  >
<template slot="expandIcon">AAA</template>
</a-table>

Could you help me?
Thank you

**Comment by hex1984** [comment]
"expandIcon" still cannot work by use slot.

**Comment by EmiyaYang** [comment]
Workaround by JSX.

BTW, using 'children' as sub-table's dataSoure may cause weird behaviour and that's why I use 'children2' instead.

```js
const columns = [
  { title: "A", dataIndex: "A" },
  { title: "B", dataIndex: "B" },
  { title: "C", dataIndex: "C" }
];

const tableData = [
  {
    key: 1,
    A: 1,
    B: 321,
    C: 3,
    children2: [
      { key: 11, A: 1, B: 321, C: 3 },
      { key: 12, A: 1, B: 321, C: 3 }
    ]
  },
  {
    key: 2,
    A: 1,
    B: 321,
    C: 3,
    children2: []
  }
];

export default {
  data() {
    return {
      tableData,
      columns,
      /**UI control state */
      loading: false,
      expandedRowKeys: []
    };
  },
  methods: {
    handleExpandedRowsChange(val) {
      this.expandedRowKeys = val;
    },
    getExpandIcon({ expanded, record, onExpand }) {
      if (!record.children2 || !record.children2.length) return "";

      return (
        <a-icon
          type={expanded ? "minus-square" : "plus-square"}
          {...{
            on: {
              click: onExpand.bind(this, [expanded, record])
            }
          }}
        />
      );
    }
  },
  render() {
    return (
      <a-spin class="rpc-table" spinning={this.loading}>
        <a-table
          class="rpc-table__table"
          columns={this.columns}
          dataSource={this.tableData}
          expandedRowKeys={this.expandedRowKeys}
          scroll={{ x: true }}
          expandIcon={this.getExpandIcon}
          {...{
            on: {
              expandedRowsChange: this.handleExpandedRowsChange
            }
          }}
          scopedSlots={{
            expandedRowRender: record => {
              if (!record.children2 || !record.children2.length) return "";

              return (
                <a-table
                  columns={columns}
                  dataSource={record.children2}
                  pagination={false}
                ></a-table>
              );
            }
          }}
        ></a-table>
      </a-spin>
    );
  }
};
```
