### ISSUE TITLE
关于带搜索功能的a-select组件，点击右边icon只能够下拉不能回弹

### ISSUE THREAD

**Issue by wustzhaohui** [vueComponent/ant-design-vue#752]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.5

### Environment
macOs Mojave10.14.4, Chrome 74.0.3729.131, Vue 2.6.6

### Reproduction link
[https://vue.ant.design/components/select-cn/](https://vue.ant.design/components/select-cn/)

### Steps to reproduce
直接在你们式例中点击就会触发这个bug

### What is expected?
期望修复这个bug

### What is actually happening?
在有搜索功能的a-select且带下拉三角的组件中出现

---
请尽快修复

**Comment by tangjinzhou** [comment]
并没有复现 😓

**Comment by wustzhaohui** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    官方文档就有这个问题的，带搜索的select
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                little_hui
                            
                    
                        
                            
                                    little_hui@foxmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年05月14日 22:03，tangjinzhou<notifications@github.com> 写道： 


并没有复现 😓



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
