### ISSUE TITLE
input清空报错

### ISSUE THREAD

**Issue by hippo2cat** [vueComponent/ant-design-vue#7524]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.0

### Environment
chrome

### Reproduction link
[http://no-need.com](http://no-need.com)

### Steps to reproduce
antv site can reproduce

### What is expected?
no error

### What is actually happening?
error

**Comment by hippo2cat** [comment]
#7523

**Comment by zhangchenna** [comment]
赶紧合并吧，项目已经回退了

**Comment by wzsgtom** [comment]
果然是这里的问题，不回退了，等更新...

**Comment by selicens** [comment]
update to 4.2.1
