### ISSUE TITLE
输入框input 清除图标点击报错

### ISSUE THREAD

**Issue by 731ghyurt** [vueComponent/ant-design-vue#7527]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.0

### Environment
线上

### Reproduction link
[https://next.antdv.com/components/input-cn](https://next.antdv.com/components/input-cn)

### Steps to reproduce
输入框输入之后点击清除图标不能清除并且报错

### What is expected?
点击清除图片将内容清除

### What is actually happening?
点击清除图片内容没被清除

**Comment by 6LWa6ZKx** [comment]
回退到4.1.2

**Comment by 6LWa6ZKx** [comment]
> 回退是不行的

为啥我可以？闹鬼拉？

**Comment by 731ghyurt** [comment]
回退之后本地可以，部署之后就不行了

**Comment by 6LWa6ZKx** [comment]
> 回退之后本地可以，部署之后就不行了

看下 lock文件，我是删除了lock文件在build。

**Comment by rex-ll** [comment]
target.cloneNode is not a function

**Comment by selicens** [comment]
1.锁定ant-deisgn-vue版本
^：表示兼容性更新的范围限制，如4.1.x会升到4.2.x
~：表示小版本更新的范围限制，如4.1.1会升到4.1.2，但不会升到4.2.x
*：表示接收任意版本
不写符号：永远安装指定版本
2.本地可以，线上不行，部署口清除页面缓存

**Comment by selicens** [comment]
follow #7523

**Comment by selicens** [comment]
update to 4.2.1
