### ISSUE TITLE
当给sticky 的 table的每一列都设置width后，在宽度不够自适应的情况下，会出现表头和列对不齐的情况

### ISSUE THREAD

**Issue by nikojxie** [vueComponent/ant-design-vue#7528]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.2

### Environment
mac, chrome

### Reproduction link
[codesandbox](https://codesandbox.io/p/sandbox/dai-bian-kuang-ant-design-vue-4-1-2-forked-vckldh?file=%2Fpackage.json%3A8%2C31&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvdj8dfy00063b6lybtir4th%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvdj8dfx00023b6l72ugbvbs%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvdj8dfy00033b6lbo9d7tds%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvdj8dfy00053b6l74zaj97z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.30244988373247%252C55.69755011626753%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvdj8dfx00023b6l72ugbvbs%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvdj8dfx00013b6lqn7y9kez%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvdjhlm500023b6rleytlx77%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A31%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A31%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvdj8dfx00023b6l72ugbvbs%2522%252C%2522activeTabId%2522%253A%2522clvdjhlm500023b6rleytlx77%2522%257D%252C%2522clvdj8dfy00053b6l74zaj97z%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvdj8dfy00043b6lna31pkcb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvdj8dfy00053b6l74zaj97z%2522%252C%2522activeTabId%2522%253A%2522clvdj8dfy00043b6lna31pkcb%2522%257D%252C%2522clvdj8dfy00033b6lbo9d7tds%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvdj8dfy00033b6lbo9d7tds%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
![image](https://github.com/vueComponent/ant-design-vue/assets/35838595/7080caa0-18b1-4249-9a06-1bd7350bf88f)

### Steps to reproduce
当给sticky 的 table的每一列都设置width后，在宽度不够自适应的情况下，会出现表头和列对不齐的情况，发现是计算出的表头宽度是整数，而列宽会是小数，所以产生了差异

### What is expected?
对齐

### What is actually happening?
对不齐

**Comment by pavitra-infocusp** [comment]
I can confirm this behaviour too.

**Comment by Ttou** [comment]
3.0版本也有这个问题

**Comment by Ttou** [comment]
对于简单的表头可以把表格的 colgroup 元素从页面上删掉；如果有固定宽度的列，在 customHeaderCell 中设置同样的宽度即可

```js
function fixTableSticky() {
  const tableEl = document.querySelector('.custom-table')

  if (!tableEl) return

  const colgroupEl = tableEl.querySelector('colgroup')

  if(!colgroupEl) return

  colgroupEl.remove() 
}
```
