### ISSUE TITLE
steps 组件在没有设置v-model的时候能触发hover样式

### ISSUE THREAD

**Issue by Gary-Leee** [vueComponent/ant-design-vue#7529]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.0

### Environment
windows 10 chrome124.0.6367.60

### Reproduction link
[https://www.antdv.com/components/steps-cn#components-steps-demo-clickable](https://www.antdv.com/components/steps-cn#components-steps-demo-clickable)

### Steps to reproduce
官网示例 ant-design 2.X的版本，a-steps没有设置 v-model，就无法触发hover样式；ant-design 3.X及以后的版本，没有设置 v-model也能触发hover样式

### What is expected?
没有设置v-model就是不可点击样式

### What is actually happening?
ant-design 3.X及以后的版本，a-steps无论有没有设置 v-model，都能触发hover样式

---
我二开的解决方案是判断props['onUpdate:current']!==undefined，就加上point-event：auto，其他默认为none

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/a578599e-5485-42a2-90f0-ff8166c9aade)
这样式儿嘛

**Comment by Gary-Leee** [comment]
yep，没有绑定v-model:current的默认样式是能触发hover的，2.X没有这个问题，估计是升级的时候没处理这块
