### ISSUE TITLE
DatePicker 日期选择框的分隔符看起来有些不协调

### ISSUE THREAD

**Issue by xxxace** [vueComponent/ant-design-vue#7530]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
让组件看起来协调，美观。
ant-picker-separator是单边上箭头，不知道是不是我的问题，整体看起来就好像是向上的，不是水平的。
为什么不用之前的2.0的~或者是→呢？

### What does the proposed API look like?
可以放开让用户自定义吗？因为其它5个icon是可以自定义的，就这个分隔符没有

最新的v4
![image](https://github.com/vueComponent/ant-design-vue/assets/60084325/e69f4d21-e66f-4f08-ba3b-5e7299e9339a)
v2版本
![image](https://github.com/vueComponent/ant-design-vue/assets/60084325/4c6c3c8d-e665-4996-9654-fccf21cc3abd)

**Comment by nikojxie** [comment]
有个 separator

**Comment by xxxace** [comment]
> 有个 separator

非常的感谢，我没翻到最底下 XD
