### ISSUE TITLE
Bug - ConfigProvider 组件 设置了 prefixcls后 Modal  内 prefixcls 未更改 。4.2.1版本

### ISSUE THREAD

**Issue by changjiaqio** [vueComponent/ant-design-vue#7536]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue - 3.4.23  和  antd-desinger-vue - 4.2.0

### Reproduction link
[https://www.antdv.com/components/config-provider-cn](https://www.antdv.com/components/config-provider-cn)

### Steps to reproduce
main.ts内
ConfigProvider.config({
prefixCls: 'blr',
});
根节点内
ConfigProvider.config({
prefixCls: 'blr',
});
根据less-loader 修改 @ant-prefixCls 都无用

此时 打开谷歌 devtools 发现 prefixCls 还是 ant

### What is expected?
Modal prefixCls 应该为 blr

### What is actually happening?
此时 打开谷歌 devtools 发现 prefixCls 还是 ant

---
希望 antv 团队有时间看一下 ，辛苦各位老师们。
![image](https://github.com/vueComponent/ant-design-vue/assets/97518513/fd5f5381-9f50-4c1e-9cac-5661068c0bd7)

![image](https://github.com/vueComponent/ant-design-vue/assets/97518513/4ae3b898-40b3-4a39-8e4c-635d30b1814f)

**Comment by extclp** [comment]
参考 [ConfigProvider 全局化配置](https://ant-design.antgroup.com/components/config-provider-cn#configproviderconfig)

**Comment by changjiaqio** [comment]
antd-desinger-vue 与  antd-desinger config 配置有出入的。

**Comment by extclp** [comment]
用法功能一样, 文档那边没写清楚

**Comment by changjiaqio** [comment]
![f29b5333ee7d419e87333e71b5ad3303](https://github.com/vueComponent/ant-design-vue/assets/97518513/a6d27a7c-949a-4c9c-881c-7e3d2b53100f)
 从 源码 去看入参是和antd有出入的

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/449de983-d6ac-4bde-ac27-1804a8e35ca6)
https://www.antdv.com/components/config-provider-cn

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/fc6f72c5-9c90-4ee6-b07a-ccc51b69b4fc)
哪种能达到效果就先用哪种呗
