### ISSUE TITLE
a-select 虚拟滚动使用slot dropdownRender 时，增加超过一屏的选项时，重复打开选项时，列表出现空白【官方文档即可复现】

### ISSUE THREAD

**Issue by coder-virjay** [vueComponent/ant-design-vue#7539]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
Chrome/124

### Reproduction link
[https://www.antdv.com/components/select-cn#components-select-demo-custom-dropdown-menu](https://www.antdv.com/components/select-cn#components-select-demo-custom-dropdown-menu)

### Steps to reproduce
打开官方文档的select链接，定位到dropdownRender，打开下拉，点击多增加一些选项后（需要滚动到中间或底部）。重复关闭和打开下拉，此时出现空白

### What is expected?
使用 dropdownRender 时，选项过多重复打开不出现空白

### What is actually happening?
下拉菜单出现空白

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/ca77f7bf-a0d8-4ae2-a3da-6580877b3a5b)
没有复现，你大概增加了多少选项出现这个问题

**Comment by coder-virjay** [comment]
> 1.mp4 
> 没有复现，你大概增加了多少选项出现这个问题

要滚动到底部，再打开关闭才行，我的电脑是 macOS 14.4.1


https://github.com/vueComponent/ant-design-vue/assets/166351383/94b38aca-056d-4874-9686-717d034e19fc

**Comment by selicens** [comment]
我添加子项，然后滚动条拖至底部，反复展开/收起，还是没有复现，我的环境是win11，你可以多找几个电脑试下看看

**Comment by nikojxie** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/35838595/63959db9-bf0c-4c2f-9456-bfd59c2b7efc)
复现了

**Comment by coder-virjay** [comment]
> 我添加子项，然后滚动条拖至底部，反复展开/收起，还是没有复现，我的环境是win11，你可以多找几个电脑试下看看

虚拟机中：Windows11 23H2 ARM版 Edge 浏览器 124 复现了，但不是每次都复现。展开/收起后，滚动条位置错误（不是在最顶部，也不是记忆位置）就一直会出现


https://github.com/vueComponent/ant-design-vue/assets/166351383/2ec43faf-c22e-45ee-b041-137bc4be4dcb

**Comment by WebSWhite** [comment]
我也遇到了这个问题，目前发现只有在select有焦点的情况下且滚动条超过一页时点击select会出现这个问题

当前的解决方案是在select dropdown弹出框隐藏时手动触发失焦blur事件，能解决这个问题
