### ISSUE TITLE
分页改变每页显示条目数。不显示

### ISSUE THREAD

**Issue by liuyan68** [vueComponent/ant-design-vue#7547]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
vue3 vite

### Reproduction link
[https://antdv.com/components/pagination-cn](https://antdv.com/components/pagination-cn)

### Steps to reproduce
分页改变每页显示条目数。不显示

### What is expected?
分页改变每页显示条目数。不显示

### What is actually happening?
分页改变每页显示条目数。不显示

**Comment by liuyan68** [comment]
![Snipaste_2024-04-30_19-41-51](https://github.com/vueComponent/ant-design-vue/assets/66464375/88cf5d01-b419-4863-bb0e-aa642a350763)

**Comment by bsuooo** [comment]
官网的demo没有问题呀~
<img width="1238" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/91053541/b9935cd7-3e5d-4cab-8ac1-da1a40db96e6">

**Comment by cc-hearts** [comment]
能给一下复现的代码吗？

**Comment by liuyan68** [comment]
> 能给一下复现的代码吗？

![image](https://github.com/vueComponent/ant-design-vue/assets/66464375/f2e7733d-ca65-4905-b677-cd2ce9ed5d1a)

**Comment by cc-hearts** [comment]
```vue
<template>
  <div style="width:100%;height:100%">
    <a-pagination v-model:current="current1" show-quick-jumper :total="500" />
  </div>
</template>
<script lang="ts" setup>
import { ref } from 'vue';
const current1 = ref(1)
</script>
```
无法复现你的问题，能在基础上再添加一些信息吗？
