### ISSUE TITLE
tree组件 开启搜索  搜索不到字节点继续搜索  js会报错   导致程序都无法运行  即使删除搜索词也无法恢复树菜单

### ISSUE THREAD

**Issue by Brolly0204** [vueComponent/ant-design-vue#7549]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue 3.3.x

### Reproduction link
[https://3x.antdv.com/components/tree-cn](https://3x.antdv.com/components/tree-cn)

### Steps to reproduce
tree组件中进行搜索

### What is expected?
即使搜索不到 继续输入  也不应该报错 不会导致应用无法运行， 程序也能继续运行

### What is actually happening?
导致程序都无法运行  即使删除搜索词也无法恢复树菜单，更新vue到3.4.x不会报错，但是vue3.4.x中 ant desing vue modal组件会有无法关闭bug
<img width="623" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/16096724/0aa28ab6-43a3-4715-9ed1-01ac7c0d491f">

<img width="689" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/16096724/4c52ce32-e8cc-40e1-b7db-d2cf3ff46ef0">

删除搜索词后 也无法恢复
<img width="274" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/16096724/ef0a9274-ec4e-4a7b-b9b0-c8f050054e71">

```js
treeUtil.js:322 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parent')
at getTreeNodeProps (treeUtil.js:322:1)
at ReactiveEffect.eval [as fn] (TreeNode.js:49:1)
at ReactiveEffect.run (reactivity.esm-bundler.js:178:1)
at get value (reactivity.esm-bundler.js:1140:1)
at eval (TreeNode.js:62:1)
at Object.flush (eagerComputed.js:5:1)
```
---
这一行代码报错  parent: entity.parent,
```js
var treeNodeProps = {
eventKey: key,
expanded: expandedKeysSet.has(key),
selected: selectedKeysSet.has(key),
loaded: loadedKeysSet.has(key),
loading: loadingKeysSet.has(key),
checked: checkedKeysSet.has(key),
halfChecked: halfCheckedKeysSet.has(key),
pos: String(entity ? entity.pos : ''),
parent: entity.parent, // 报错
```
TypeError: Cannot read properties of undefined (reading 'parent')

**Comment by shiwanjun1995** [comment]
I have the same problem，would you fix it as soon as possible?
@selicens

**Comment by zouyujie** [comment]
a-tree组件只要使用了插槽，插槽内容就丢失了响应式，需要重新点一下组件，或者把绑定的数据对象整个重新赋值。

**Comment by mudoo** [comment]
一样的问题，VUE升到3.3后出现

**Comment by mudoo** [comment]
看了下Tree组件的源码，我的项目用`openAnimation`这个prop临时解决了该问题，希望对你们同样有帮助：
```
<ATree
  openAnimation={treeOpenAnimation}
  treeData={treeData.value}
  expandedKeys={treeExpandedKeys.value}
   ...
/>

const treeOpenAnimation = ref(true)
function filterTreeData () {
  // 筛选tree数据的时候，先禁用transition动画
  treeOpenAnimation.value = false
  // treeData.value = [...]
  // treeExpandedKeys.value} = [...]
  // ...
  nextTick(() => { treeOpenAnimation.value = true })
}
```

**Comment by mudoo** [comment]
> 看了下Tree组件的源码，我的项目用`openAnimation`这个prop临时解决了该问题，希望对你们同样有帮助：
> 
> ```
> <ATree
>   openAnimation={treeOpenAnimation}
>   treeData={treeData.value}
>   expandedKeys={treeExpandedKeys.value}
>    ...
> />
> 
> const treeOpenAnimation = ref(true)
> function filterTreeData () {
>   // 筛选tree数据的时候，先禁用transition动画
>   treeOpenAnimation.value = false
>   // treeData.value = [...]
>   // treeExpandedKeys.value} = [...]
>   // ...
>   nextTick(() => { treeOpenAnimation.value = true })
> }
> ```
> 
> @shiwanjun1995 @Brolly0204

这个prop并不是`Boolean`...会导致展开收缩动画失效- -

**Comment by mudoo** [comment]
看上去是动画引起的，找到了个`openAnimation` prop，以为是开关可以启用关闭动画，后面发现是`Object`，设置为空对象可以关闭动画，暂时这样解决上线...
