### ISSUE TITLE
Typography 排版 组件使用时 同时设置 copyable 跟 ellipsis 会出现警告 Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 

### ISSUE THREAD

**Issue by archiesong** [vueComponent/ant-design-vue#7552]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.1.0

### Environment
vue 3.4.23

### Reproduction link
[https://www.antdv.com/components/typography-cn#api](https://www.antdv.com/components/typography-cn#api)

### Steps to reproduce
在项目中使用Typography 组件         <TypographyText
:ellipsis="{ tooltip: '提示123232'}"
:copyable="{ tooltip: false, text: '1232'}"
content="ASD大苏打实打实大苏打实打实大苏打实打实的AS"
/>

### What is expected?
浏览器控制台没有  Vue   Warn 警告 提示

### What is actually happening?
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead.
at <ATooltip key="copy" title="" >
at <App>

![QQ截图20240505030728](https://github.com/vueComponent/ant-design-vue/assets/32739384/92d604ad-80b7-4219-87d6-daae93efbb0e)
![QQ截图20240505030752](https://github.com/vueComponent/ant-design-vue/assets/32739384/32928ad7-c850-4261-8e62-e8ed4614e10a)

**Comment by Jiachenglong2518** [comment]
同样遇到了，请问解决了吗

**Comment by archiesong** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/32739384/422637f7-461e-416d-8b6d-51c4a646c861)
检查Typography 组件 源码 发现在onMounted声明周期里面调用了 syncEllipsis 方法 这个方法中使用了slots  所以会报这个警告，注释掉这个方法就不会与警告， 而且功能正常，希望作者能在下个版本更新能修复这个问题

**Comment by cc-hearts** [comment]
能提供一些复现的代码吗？

**Comment by archiesong** [comment]
> 能提供一些复现代码吗？
    <a-typography-text
      style="width: 152px"
      :copyable="{ text: 'Ant Design Vue (default)', tooltip: false }"
      :ellipsis="{
        tooltip: 'Ant Design Vue (default)',
      }"
      content="Ant Design Vue (default)"
    />   就像这样使用

**Comment by archiesong** [comment]
<a-space direction="vertical">
    <a-typography-text
      style="width: 152px"
      :copyable="{ text: 'Ant Design Vue (default)', tooltip: false }"
      :ellipsis="{
        tooltip: 'Ant Design Vue (default)',
      }"
      content="Ant Design Vue (default)"
    />

**Comment by archiesong** [comment]
‘
  <a-space direction="vertical">
    <a-typography-text
      style="width: 152px"
      :copyable="{ text: 'Ant Design Vue (default)', tooltip: false }"
      :ellipsis="{
        tooltip: 'Ant Design Vue (default)',
      }"
      content="Ant Design Vue (default)"
    />

’

**Comment by archiesong** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/32739384/697d1213-b9ba-4076-80d0-a58e01f09f27)
这样使用 @cc-hearts
