### ISSUE TITLE
【qrcode】The size downloaded from qrcode is different from the size set

### ISSUE THREAD

**Issue by winnerwyy** [vueComponent/ant-design-vue#7569]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
"vue": "^3.2.13"

### Reproduction link
[https://antdv.com/components/qrcode-cn](https://antdv.com/components/qrcode-cn)

### Steps to reproduce
qrcode's default download click view size is different from the size on the page

### What is expected?
The display size is the same as the download size

### What is actually happening?
The display size does not match the download size

**Comment by Aaron-zon** [comment]
默认大小是160减去dom的边距和边框，二维码本身的尺寸是134，你下载下来的尺寸是多大

**Comment by winnerwyy** [comment]
![QRCode (17)](https://github.com/vueComponent/ant-design-vue/assets/23170335/6b7acc1c-77da-4888-b33d-9ca5acc1133d)
268

**Comment by Aaron-zon** [comment]
我在官网提供的示例里没有下载出尺寸异常的二维码，也许已经有人修改了，我觉得你可以更新一下版本或者写个最小复现案例出来
