### ISSUE TITLE
点击 table的筛选图标,位置发生偏移

### ISSUE THREAD

**Issue by amwu** [vueComponent/ant-design-vue#757]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win10 64 , Chrome 76 , Vue 2.6.10

### Reproduction link
[https://vue.ant.design/components/table-cn/](https://vue.ant.design/components/table-cn/)

### Steps to reproduce
点击table的筛选图标

### What is expected?
修复筛选图标位置偏移

### What is actually happening?
点击table的筛选图标,筛选图标位置发生偏移

**Comment by luoxiaoji** [comment]
这个问题 同样有，也一直很奇怪原因，之前用其他第三方组件没有这种问题。

补充点细节： 我这边发现出现位移大部分在图标，表单和按钮， 在F12 CSS里会发现字体大小或者位置出出现小数点一类的情况。比如字体 13.99999999 原来是14px，

大部分情况 把浏览器全屏能解决，貌似和分辨率有关系？
