### ISSUE TITLE
step组件 默认icon中的文字没有居中

### ISSUE THREAD

**Issue by LinTing-pl** [vueComponent/ant-design-vue#7578]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
浏览器版本、Vue版本

### Reproduction link
[https://3x.antdv.com/components/steps-cn](https://3x.antdv.com/components/steps-cn)

### Steps to reproduce
css样式问题，直接看官网就可以复现

### What is expected?
能直接居中，不需要使用者再去穿透改样式

### What is actually happening?
step组件的默认icon里的文字由span包裹，而span元素的父元素为div，该div的高度与行高一致，可见设计者是想让文字居中的，但是实际效果没有居中

**Comment by LinTing-pl** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/5b7b3a97-5e3b-4fee-a801-b0270b89dcca)
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/5815a652-8d67-4e77-8518-6c6e8d0b0f96)

**Comment by selicens** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/69418751/26fc8213-bd6f-4eaa-bcd5-e9958e634bab)

**Comment by LinTing-pl** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/8966bec2-5e26-4768-9bc8-a319d01c868a)
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/6377965f-9912-4a3d-abd9-caff32550411)

**Comment by selicens** [comment]
滚动是指先滚动到底部在回到顶部，步骤条内文字就不居中了嘛，这一步我没有复现，你可以试下4.x和其他浏览器、电脑之类的

**Comment by LinTing-pl** [comment]
一开始，我以为是广告插入导致的，但后面发现当页面缩放到一些比例，也可以引起文字不居中，而且firefox、edge也都有这个问题，这可能是字体的原因（我猜测），因为可以明显的看到span的上content区域大于下content区域，我尝试通过vertical-align更改span的基线，但无法解决这个问题
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/66282cdb-9d39-466e-95ff-078facf33e9f)
![image](https://github.com/vueComponent/ant-design-vue/assets/83224448/71748b39-b434-43a1-9d57-c5d874eb3676)

我需要加上这一段代码，去更改icon的样式
.ant-steps-item-icon {
      display: inline-flex;
      justify-content: center;
      align-items: center;
    }
