### ISSUE TITLE
带搜索框的Select，搜索中文未输入完成时，会跟placeholder重叠

### ISSUE THREAD

**Issue by nikojxie** [vueComponent/ant-design-vue#7590]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
  

![image](https://github.com/vueComponent/ant-design-vue/assets/35838595/55177ee5-d227-440d-a4e0-fb8e0d89329e)

antd不会发生重叠

![image](https://github.com/vueComponent/ant-design-vue/assets/35838595/0facd44c-81a0-4d83-aaa7-99bc8c72279b)

        
### Version
4.2.1

### Environment
mac, chrome

### Reproduction link
[https://antdv.com/components/select-cn#components-select-demo-search-box](https://antdv.com/components/select-cn#components-select-demo-search-box)

### Steps to reproduce
带搜索框的Select，搜索中文未输入完成时，会跟placeholder重叠

### What is expected?
placeholder消失

### What is actually happening?
与输入中的文字重叠了

**Comment by debbieLin33** [comment]
仓颉输入法也会发生一样的错误
<img width="461" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/20656828/1054463e-4d8b-4076-aa5d-b6c098047a1a">
