### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded 在table 组件中滑动滚动条，控制台报了上千个警告

### ISSUE THREAD

**Issue by xijinhua** [vueComponent/ant-design-vue#7592]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
"vue": "^3.4.27"

### Reproduction link
https://codesandbox.io/p/devbox/tender-violet-xj5j5f

### Steps to reproduce
先把浏览器控制台打开，滑动滚动条，滚到底部的过程中，控制台就会报上千个警告

### What is expected?
不要报错

### What is actually happening?
先把浏览器控制台打开，滑动滚动条，滚到底部的过程中，控制台就会报上千个警告

![image](https://github.com/vueComponent/ant-design-vue/assets/14870095/3faaae4b-108a-474f-ba3f-1d7d620f0a7f)

**Comment by xijinhua** [comment]
![Uploading 111.png…]()

**Comment by xijinhua** [comment]
暂时解决： vue 版本3.3.4 ，不要写^

**Comment by wsxe9988** [comment]
@selicens @tangjinzhou  看一下 vue 3.4.x下报这个错，紧急修复下吧

**Comment by cc-hearts** [comment]
3.4 对于 computed 进行了优化：https://github.com/vuejs/core/pull/5912

是否将 `eagerComputed` 切换回 `computed` ?

**Comment by orionna319** [comment]
I also encountered this problem, the version of vue is 3.4.21.

**Comment by orionna319** [comment]
Is there any way to solve this problem? For example, using `pnpm patch` is also a temporary solution.

**Comment by cc-hearts** [comment]
<img width="604" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/a3e0eb8f-bd10-4f7f-a40c-613e0ff17113">
Here's my patch (FYI)

**Comment by cc-hearts** [comment]
vue 3.5.0 will resolve

**Comment by hls-1992** [comment]
patch does not work

**Comment by qiuweikangdev** [comment]
+1

**Comment by ns265422** [comment]
+1
