### ISSUE TITLE
 Input box component show count attribute, select input box cursor position incorrect

### ISSUE THREAD

**Issue by songjinlin123** [vueComponent/ant-design-vue#7599]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
window

### Reproduction link
[https://www.antdv.com/components/input-cn](https://www.antdv.com/components/input-cn)

### Steps to reproduce
The show count property of the input box component loses focus and clicks on a text below the input box again. The cursor position is incorrect, and the text inside the input box suddenly changes, resulting in a positional error

### What is expected?
When there is a lot of text in the input box component with the show count attribute, when the focus is lost and a text is clicked again under the input box, the cursor position is incorrect, and the text inside the input box suddenly changes, resulting in an incorrect position

### What is actually happening?
The show count property of the input box component loses focus and clicks on a text below the input box again. The cursor position is incorrect, and the text inside the input box suddenly changes, resulting in a positional error

**Comment by cc-hearts** [comment]
Can you give a code that reproduces it? This will help us find the problem
