### ISSUE TITLE
table 更改数据源后重新刷新得问题 !

### ISSUE THREAD

**Issue by luoxiaoji** [vueComponent/ant-design-vue#760]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### Reproduction link
null

### Steps to reproduce
请教下，在设置了rowKey和 columns 得 dataIndex 都是唯一值 情况下，我更改了 绑定得数据源数组中某一个对象得一个值，但是table显示上没有重新渲染刷新值，只有重新把整个数据源换掉才会刷新，请问是啥原因？

**Comment by tangjinzhou** [comment]
数据源没有深度监听，太耗性能

**Comment by luoxiaoji** [comment]
> 数据源没有深度监听，太耗性能

替换数据源数组中得某个值也不支持吗？ 例： arr[0] = object
也没有监听到刷新

**Comment by FAKER-A** [comment]
@luoxiaoji  arr[0] = object 这样的更改数组内容， vue是监听不到的。
可以看下vue文档这部分，有详细的说明。
https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B

**Comment by luoxiaoji** [comment]
> @luoxiaoji arr[0] = object 这样的更改数组内容， vue是监听不到的。
> 可以看下vue文档这部分，有详细的说明。
> https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B

多谢，vue基础不够扎实。打扰各位了！
