### ISSUE TITLE
兄弟组件（A，B ）同时引用SVG图片，引用方式A在前B在后，如果A组件SVG图片display:none会导致B组件中的SVG图片也不展示

### ISSUE THREAD

**Issue by JuanJuanZhang123** [vueComponent/ant-design-vue#761]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
Chrome 73.0.3683.86

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jv54nk1vrw?fontsize=14)

### Steps to reproduce
同时引入A B组件作为兄弟组件，并且A，B组件都是用自定义SVG图片作为Icon

### What is expected?
A组件SVG图片的展示不影响B组件，两个组件中SVG图片的展示相互独立

### What is actually happening?
A组件SVG图片隐藏将导致B组件SVG图片不展示

**Comment by tangjinzhou** [comment]
麻烦给出能够正常运行的demo 谢谢
