### ISSUE TITLE
将页面全屏时Tooltip组件的提示文字可能并不会自动消失

### ISSUE THREAD

**Issue by czhlin** [vueComponent/ant-design-vue#7619]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
window10，edge，vue3

### Reproduction link
[Edit on CodeSandbox](https://codesandbox.io/p/devbox/zealous-grothendieck-q6n3kz-k4yfny?file=%2Fpackage.json)

### Steps to reproduce
1.将鼠标指针放在全屏按钮上等待tooltip弹出文字
2.点击全屏按钮进入全屏状态
3.将鼠标指针放在全屏按钮上等待tooltip弹出文字
4.点击全屏按钮取消全屏状态
5.会发现鼠标指针在tooltip外而tooltip的文字没有消失

### What is expected?
期望这种强制移动到tooltip边界的情况也可以让tooltip文字自动消失，

### What is actually happening?
实际结果是强制移动会导致鼠标指针移出到tooltip边界而tooltip文字没有自动消失
![image](https://github.com/vueComponent/ant-design-vue/assets/56159557/df830ede-b74c-44ad-bc8f-2a4fb136a973)
![image](https://github.com/vueComponent/ant-design-vue/assets/56159557/e7909b5a-cdac-4b9c-bd70-c1f47da6a609)

**Comment by webarn** [comment]
出现了同样的问题，没有办法消失，只有鼠标hover一次才可以

**Comment by czhlin** [comment]
> 出现了同样的问题，没有办法消失，只有鼠标hover一次才可以

是的我这个是全屏然后出现的问题

**Comment by cc-hearts** [comment]
试了 edge 
<img width="187" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/71313168/61cd2ad1-7099-43d5-baf4-03456501d749">
如果鼠标全屏前后都会停留在这块区域 （整块的范围都属于在hover的区域内），🤔 符合预期的情况

**Comment by GsjzTle** [comment]
我也遇到了同样的问题，但不知道怎么解决
