### ISSUE TITLE
table组件，设置列A为固定列在左侧，下次加载数据时，取消列A的固定列(fixed)属性。fixed层对应的HTML元素仍然显示在界面上，没有被正常隐藏或者取消

### ISSUE THREAD

**Issue by snryang** [vueComponent/ant-design-vue#762]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.2

### Environment
环境无关

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
1.设置table组件，第一列为固定列。 column.fixed='left'
2.table组件显现正确效果。
3.取消table组件，第一列的固定列属性。
4.table组件显现不正确，固定列对应的HTML元素仍然显示在界面上。

### What is expected?
document.getElementsByClassName('ant-table-fixed-left') 能正确隐藏或者取消

### What is actually happening?
document.getElementsByClassName('ant-table-fixed-left') DOM元素一直在界面上

---
暂时解决问题的兼容代码
this.$nextTick(()=>{
let fixed = document.getElementsByClassName('ant-table-fixed-left')
if(fixed.length > 0){
document.getElementsByClassName('ant-table-fixed-left')[0].style.display= this.filter.type =='0'?"none":""
}
})

**Comment by tangjinzhou** [comment]
给出有效的复现链接 谢谢
