### ISSUE TITLE
设置Tabs 的tabBarStyle样式borderBottom:'unset'，无法清掉选项卡组件底部灰色细线，此设置在vue2.6.12和ant-design-vue 1.7.8上验证有效

### ISSUE THREAD

**Issue by yzmb2023** [vueComponent/ant-design-vue#7625]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
os 版本 :win10, 浏览器版本:Google Chrome 125.0.6422.141,vue版本:3.4.27

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/still-frog-pmjjgw?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A16%2C10)

### Steps to reproduce
1、设置Tabs 的tabBarStyle样式borderBottom:'unset'
2、检查选项底部灰色细线

### What is expected?
选项卡组件底部灰色细线消除
![image](https://github.com/vueComponent/ant-design-vue/assets/142132677/96a6a528-f373-490d-9bdd-213c12b2d07b)

### What is actually happening?
选项卡组件底部灰色细线仍显示
![image](https://github.com/vueComponent/ant-design-vue/assets/142132677/fb93fb08-9278-42e5-b3d1-5645a281114b)

**Comment by selicens** [comment]
```css
div :deep(.ant-tabs-nav::before) {
  border-bottom: unset;
}
```

**Comment by yzmb2023** [comment]
> ```css
> div :deep(.ant-tabs-nav::before) {
>   border-bottom: unset;
> }
> ```

It works,thank you
