### ISSUE TITLE
Select 组件多选的情况下默认值展示bug

### ISSUE THREAD

**Issue by Cristianoying** [vueComponent/ant-design-vue#7629]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.1

### Environment
macos, chrome 125 vue:3.2.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/hungry-neumann-ndfm4h?file=%2Fsrc%2FApp.vue%3A38%2C17)

### Steps to reproduce
1. codesandbox中可以看到对应的情况

### What is expected?
1.select 组件展示placeholder？这个空tag应该不是正常的吧😂

### What is actually happening?
1.select中展示了一个空tag
2.在选项中还多加了一个空项,删除了空tag这一项就没有了

**Comment by Cristianoying** [comment]
#7633 debug了一下，问题应该是在convert2LabelValues 这个方法中toArray的时候里面只判断了undefined，修改里面的判断可以解决，这个也可以解决，不知道哪个更合理一点

**Comment by tangjinzhou** [comment]
只有 undefined 和 空数组 认为是无值
