### ISSUE TITLE
Select 和 Cascader 组件在带搜索的多选模式下时，当前输入的关键字被隐藏了

### ISSUE THREAD

**Issue by ankeycheng** [vueComponent/ant-design-vue#7640]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.2

### Environment
vue@3.4.27

### Reproduction link
[https://www.antdv.com/components/select-cn#components-select-demo-multiple](https://www.antdv.com/components/select-cn#components-select-demo-multiple)

### Steps to reproduce
[官网 Select demo 可重现](https://www.antdv.com/components/select-cn#components-select-demo-multiple)
[另外 Cascader 也存在同样状况](https://codesandbox.io/p/sandbox/duo-xuan-ant-design-vue-4-2-2-forked-3q7zkm?file=%2Fsrc%2Fdemo.vue%3A10%2C1)

### What is expected?
在输入框输入关键字时会被显示

### What is actually happening?
在输入框输入关键字时被隐藏了

---
_Originally posted by @ankeycheng in https://github.com/vueComponent/ant-design-vue/issues/7611#issuecomment-2154150472_

**Comment by cc-hearts** [comment]
我排查一下 抱歉
