### ISSUE TITLE
文件上传中多文件上传功能缺陷

### ISSUE THREAD

**Issue by AFTM7512** [vueComponent/ant-design-vue#765]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
使用场景： 多文件上传功能，文件需要保存到oss，同时需要调用后台接口，表示文件上传成功，
ui：选择完文件后，只需要出现loading，然后就开始上传文件；
当前问题： 监听change事件，选择多文件上传时，change事件会执行多次，数据不是一次性返回，这样没办法监听文件本地上传成功。

### What does the proposed API look like?
多文件上传，在before阶段，能一次性返回数据的结构。

**Comment by tangjinzhou** [comment]
根据状态来判断
