### ISSUE TITLE
Display issue when binding dynamic arrays to "Select" component "options"

### ISSUE THREAD

**Issue by Dylan-lijl** [vueComponent/ant-design-vue#7657]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
vue 3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/objective-sky-mptnkw?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxebkxb00006356jpif3j3lk%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxebkxb00002356jmvljxnni%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxebkxb00003356j0ksuhh7c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxebkxb00005356jqzpk9zl5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxebkxb00002356jmvljxnni%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxebkxaz0001356j9g66ysq7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxebmhe60002356kgl1pci42%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A1%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A116%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxebkxb00002356jmvljxnni%2522%252C%2522activeTabId%2522%253A%2522clxebmhe60002356kgl1pci42%2522%257D%252C%2522clxebkxb00005356jqzpk9zl5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxebkxb00004356jiwhmddas%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxebkxb00005356jqzpk9zl5%2522%252C%2522activeTabId%2522%253A%2522clxebkxb00004356jiwhmddas%2522%257D%252C%2522clxebkxb00003356j0ksuhh7c%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxebkxb00003356j0ksuhh7c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
使用selectItems正常能显示label,使用options则显示value

### What is expected?
显示label值

### What is actually happening?
显示value值

---
原因可能是没有监听更改后的options,导致查询对应的label为空从而导致显示value

**Comment by Dylan-lijl** [comment]
![1718463785455](https://github.com/vueComponent/ant-design-vue/assets/49663418/5fc3818d-e53e-4ac2-a89c-7a4b9064f262)

**Comment by Aaron-zon** [comment]
因为选中后你的options重新生成了，选中那条数据被删除自然就没有label了，这时value存在v-model的哪个变量里因此显示value，这不是组件的问题是写法问题

**Comment by Dylan-lijl** [comment]
> 因为选中后你的options重新生成了，选中那条数据被删除自然就没有label了，这时value存在v-model的哪个变量里因此显示value，这不是组件的问题是写法问题

该死的粗心大意

**Comment by Dylan-lijl** [comment]
null
