### ISSUE TITLE
input组件不支持v-model:value.trim

### ISSUE THREAD

**Issue by tetap** [vueComponent/ant-design-vue#7658]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
4.2.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-4-2-3-forked-7hlykz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxgcnot40006356j9nboj4xa%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxgcnot40002356j3sm2q3aq%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxgcnot40003356jfgxcqnm8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxgcnot40005356jchlhibtf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxgcnot40002356j3sm2q3aq%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxgcnot30001356jxpnv02oe%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clxgcpxvh0035356jmf789etd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fdemo.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxgcnot40002356j3sm2q3aq%2522%252C%2522activeTabId%2522%253A%2522clxgcpxvh0035356jmf789etd%2522%257D%252C%2522clxgcnot40005356jchlhibtf%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxgcnot40004356jbf7xvr31%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxgcnot40005356jchlhibtf%2522%252C%2522activeTabId%2522%253A%2522clxgcnot40004356jbf7xvr31%2522%257D%252C%2522clxgcnot40003356jfgxcqnm8%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxgcnot40003356jfgxcqnm8%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
input组件不支持v-model:value.trim

### What is expected?
支持指令

### What is actually happening?
input组件不支持v-model:value.trim

**Comment by kovsu** [comment]
https://github.com/vuejs/vue/issues/5847
https://github.com/ElemeFE/element/issues/9192

所以是不是只有原生 input 才能用 trim 🤔

**Comment by tetap** [comment]
> [vuejs/vue#5847](https://github.com/vuejs/vue/issues/5847) [ElemeFE/element#9192](https://github.com/ElemeFE/element/issues/9192)
> 
> 所以是不是只有原生 input 才能用 trim 🤔

https://github.com/vueComponent/ant-design-vue/issues/7658#issuecomment-2171750051

> [vuejs/vue#5847](https://github.com/vuejs/vue/issues/5847) [ElemeFE/element#9192](https://github.com/ElemeFE/element/issues/9192)
> 
> 所以是不是只有原生 input 才能用 trim 🤔

我在文档中看到是可以处理v-model修饰符的。不知道为什么不处理。
https://cn.vuejs.org/guide/components/v-model.html#component-v-model
