### ISSUE TITLE
select 组件隐藏已选择的数据

### ISSUE THREAD

**Issue by Dylan-lijl** [vueComponent/ant-design-vue#7666]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
由于下拉数据太多,已选中的数据隐藏对应的下拉选项(多个下拉选使用同一个下拉列表数据),达到可选项减少能优化操作;
该功能需求源于之前的错误bug---->https://github.com/vueComponent/ant-design-vue/issues/7657

### What does the proposed API look like?
select提供一个隐藏数组或者根据option的display来控制

**Comment by Aaron-zon** [comment]
![image](https://github.com/vueComponent/ant-design-vue/assets/47178158/529832c3-818f-4612-bad7-a18e1c9755e8)

**Comment by Dylan-lijl** [comment]
> ![image](https://private-user-images.githubusercontent.com/47178158/340497487-529832c3-818f-4612-bad7-a18e1c9755e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzQ5MzIsIm5iZiI6MTcxODY3NDYzMiwicGF0aCI6Ii80NzE3ODE1OC8zNDA0OTc0ODctNTI5ODMyYzMtODE4Zi00NjEyLWJhZDctYTE4ZTFjOTc1NWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAxMzcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMGY5ZWVhMjc4MmQxOTBiZWRmMmRjYzYxNmQ0ZmUxYjcxMTMxYWRmNGEyYjQ0NDNkMjg2YmZjNGNhODUxNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XhS7dTsGi-08sxBoIO3YX_8gf7H74QYJHJGvPGdk8K0)

不一样,你这个示例没有label属性,大部分场景显示label而不是value,当只有value值label就会失效,这又回到之前说的bug

**Comment by Aaron-zon** [comment]
哦哦，我懂了，那这个看起来确实不行。

**Comment by hdtopku** [comment]
确实是个 bug
```
 <a-select key="id" allow-clear v-model:value="selectedRoleIds" mode="multiple"
                  :options="filteredOptions" placeholder="请选择角色">
          <template #tagRender="{ value: val, label, closable, onClose, option }">
            <a-tag :closable="closable" style="margin-right: 3px" @close="onClose">
              {{ label }}/{{ val }}
            </a-tag>
          </template>
        </a-select>
```
选择前
<img width="488" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/14859466/78eba86a-dbbb-4067-bab8-3e05a235d749">
选择后
<img width="500" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/14859466/70b68b96-397f-4687-b5f9-cbf8874b3b6c">

template的 label 的值被设置为了value的值
