### ISSUE TITLE
3.0版本 的table组件 column列如何显示隐藏显影

### ISSUE THREAD

**Issue by zhangle1** [vueComponent/ant-design-vue#7667]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
windows

### Reproduction link
[ https://github.com/vueComponent/ant-design-vue/issues/new/choose]( https://github.com/vueComponent/ant-design-vue/issues/new/choose)

没有找到对应api

**Comment by selicens** [comment]
[AntDesignVue表格中列的自定义隐藏与展示](https://blog.csdn.net/Web_ChuXia/article/details/123421701)
