### ISSUE TITLE
Not work input

### ISSUE THREAD

**Issue by Danialdevs** [vueComponent/ant-design-vue#7668]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
windows, vue 3   inertia

### Steps to reproduce
<input/>

### What is expected?
Input

### What is actually happening?
input not style

**Comment by cc-hearts** [comment]
provide a minimal reproduction?
