### ISSUE TITLE
使用ATableColumn进行伸缩列的扩展的编码，但是鼠标拖拽border的时候的时候表头列宽并没有发生变化，而使用columns的方式却是正常的

### ISSUE THREAD

**Issue by heart-to-the-sea** [vueComponent/ant-design-vue#7669]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
archlinux and windows 11, chrome 126.0.6478.61，Vue 3.2.0

### Reproduction link

[地址](https://codesandbox.io/p/sandbox/vue-antd-template-forked-8vvfzg?file=%2Fsrc%2FApp.vue)

### Steps to reproduce
复制官网demo,将其中的表的列改为ATableColumn，并设置resizable属性，在ATable上设置resizeColumn事件监听，随后拖拽表头的列

### What is expected?
期望鼠标在表头border上拖拽的时候，列宽度跟随变化

### What is actually happening?
表头列宽度并没有发生变化

**Comment by heart-to-the-sea** [comment]
每次拖拽表头边框的时候,事件都响应到了
![image](https://github.com/vueComponent/ant-design-vue/assets/59409148/26bf92f6-3f57-4c5c-a3d8-0cbea31b2c66)
但是列宽就是没改变

**Comment by webvs2** [comment]
The problem will be viewed
