### ISSUE TITLE
在a-table中使用a-input光标会跳到最后去

### ISSUE THREAD

**Issue by wuerwawuerwa** [vueComponent/ant-design-vue#7671]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
chrome浏览器 Vue3

### Reproduction link
[https://www.antdv.com/components/table](https://www.antdv.com/components/table)

### Steps to reproduce
1.在form包裹的a-table中添加一条都是输入框构成的行数据
2.在表格的其中一项使用中文输入，光标有时会跳动到最后
3.输入法输入时不用键盘操作（比如按下空格或者1、2、3此类操作），使用鼠标去点击要输入的项时会输入不上去

### What is expected?
解决光标跳动问题和输入法用鼠标点击选择的问题

### What is actually happening?
1.在form包裹的a-table中添加一条都是输入框构成的行数据
2.在表格的其中一项使用中文输入，光标有时会跳动到最后
3.输入法输入时不用键盘操作（比如按下空格或者1、2、3此类操作），使用鼠标去点击要输入的项时会输入不上去

**Comment by webvs2** [comment]
Use the following link to start a minimal example
https://codesandbox.io/p/sandbox/basic-usage-ant-design-vue-4-2-3-c8kv6c
