### ISSUE TITLE
编译源码报错

### ISSUE THREAD

**Issue by hdygxsj** [vueComponent/ant-design-vue#7672]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
node 16 &&  mac m3

### Reproduction link
[https://github.com/hdygxsj/ant-design-vue.git](https://github.com/hdygxsj/ant-design-vue.git)

### Steps to reproduce
yarn install
yarn run dev 或者yarn run site

或者
npm install
npm run dev 或者npm run site

### What is expected?
源码编译成功

### What is actually happening?
✅  Token Meta has been written to components/version/token-meta.json
$ npm run routes && vite serve site

> ant-design-vue@4.2.3 routes
> node site/scripts/genrateRoutes.js

failed to load config from /Users/zhongyangyang/IdeaProjects/ant-design-vue/site/vite.config.ts
error when starting dev server:
TypeError: import_lru_cache.default is not a constructor
at Object.<anonymous> (/Users/zhongyangyang/IdeaProjects/ant-design-vue/site/vite.config.ts:515:13)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object._require.extensions.<computed> [as .js] (file:///Users/zhongyangyang/IdeaProjects/ant-design-vue/node_modules/vite/dist/node/chunks/dep-372dab03.js:63162:24)
at Module.load (node:internal/modules/cjs/loader:1076:32)
at Function.Module._load (node:internal/modules/cjs/loader:911:12)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at loadConfigFromBundledFile (file:///Users/zhongyangyang/IdeaProjects/ant-design-vue/node_modules/vite/dist/node/chunks/dep-372dab03.js:63170:21)
at loadConfigFromFile (file:///Users/zhongyangyang/IdeaProjects/ant-design-vue/node_modules/vite/dist/node/chunks/dep-372dab03.js:63028:34)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.

**Comment by hdygxsj** [comment]
用window可以编译，编译后dist放到nginx下打开白屏
![482bd61a80e47a05f08fbafb9334b078](https://github.com/vueComponent/ant-design-vue/assets/35210666/a15f3c89-83b6-47dd-978d-d6841638f4d9)

nginx配置
```conf
    server {
        listen       8080;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            try_files $uri $uri/ /index.html;
            index  index.html index.htm;
        }


```

**Comment by selicens** [comment]
npm install -f 或者 npm install --force，然后再执行npm run dev

**Comment by hdygxsj** [comment]
> 用window可以编译，编译后dist放到nginx下打开白屏 ![482bd61a80e47a05f08fbafb9334b078](https://private-user-images.githubusercontent.com/35210666/341613029-a15f3c89-83b6-47dd-978d-d6841638f4d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTI5ODQsIm5iZiI6MTcxODk1MjY4NCwicGF0aCI6Ii8zNTIxMDY2Ni8zNDE2MTMwMjktYTE1ZjNjODktODNiNi00N2RkLTk3OGQtZDY4NDE2MzhmNGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA2NTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxZGFmYzhkM2Q1OWNlNGE2NmMwMTUzMzRkNWNiMTRlMmI4ZTgzMjk0MTE0MGI0YWNlOTFmNjhlMWYyNTA1MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8H19CKQCM2CFJmQL4uWsUfruRfEVJu6C9w1qJFr6cc)
> 
> nginx配置
> 
> ```
>     server {
>         listen       8080;
>         server_name  localhost;
> 
>         #charset koi8-r;
> 
>         #access_log  logs/host.access.log  main;
> 
>         location / {
>             root   html;
>             try_files $uri $uri/ /index.html;
>             index  index.html index.htm;
>         }
> ```

<img width="1540" alt="image" src="https://github.com/vueComponent/ant-design-vue/assets/35210666/a4aaae22-347f-4a81-a11e-0f8769d0ce69">
这改成./可以解决li'xian离线部署时渲染白屏的问题
