### ISSUE TITLE
Slider prop `step` does not include `null` as possible type in TS

### ISSUE THREAD

**Issue by Owen-Tsai** [vueComponent/ant-design-vue#7673]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues) of this repository and believe (hopefully) that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
Vue 3.4.29, AntD 4.2.3

### Reproduction link
Not applicable

### Steps to reproduce
```txt
<ASlider
  :step="null"
  ^^^^^ 不能将 null 分配给 number | undefined
/>
```

### What is expected?
`null` should be included in `step` prop types.

### What is actually happening?
TS server throws an error when you trying to assign `null` to `step`.

**Comment by webvs2** [comment]
The problem will be viewed

**Comment by webvs2** [comment]
#bug
