### ISSUE TITLE
【兼容问题】【vivo pad3 pro】antd官网所有样式丢失 

### ISSUE THREAD

**Issue by jenkey2011** [vueComponent/ant-design-vue#7677]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
vivo pad3 pro 自带浏览器

### Reproduction link
[https://next.antdv.com/components/overview](https://next.antdv.com/components/overview)

### Steps to reproduce
vivo pad3 pro 自带浏览器，直接打开antd官网即可
3.x版本可以正常打开  但是4.x就完全错乱了

### What is expected?
希望查清楚原因，担心vivo自带浏览器都不行，我们用了不少antd组件~

### What is actually happening?
样式丢失

        
![332A3BC0D26CBCF48582727D9DB9F569](https://github.com/vueComponent/ant-design-vue/assets/20010737/7041f6dc-0cfe-441c-bbdc-564485a420da)
![332A3BC0D26CBCF48582727D9DB9F569](https://github.com/vueComponent/ant-design-vue/assets/20010737/9875491c-4943-45e4-8712-7b53c3a03fc1)
![E86C029592375D2DAB67072ABF176720](https://github.com/vueComponent/ant-design-vue/assets/20010737/96616907-6404-4848-a275-b26cb3801e9b)

**Comment by jenkey2011** [comment]
已定位原因，Ant Design Vue 的 CSS-in-JS 默认通过 :where 选择器，chrome87版本刚好卡着阈值不能用。
可以close了

**Comment by JingyuanZhang** [comment]
我也遇到了，可以通过编译配置 改吗？现在 官网提供的方法 需要将用到的组件统一封装，再加标记，开发方式不太友好  https://antdv.com/docs/vue/compatible-style-cn#where-%E9%80%89%E6%8B%A9%E5%99%A8
