### ISSUE TITLE
a-table希望能添加虚拟纵向滚动条-方便查看数据。

### ISSUE THREAD

**Issue by onlyscv** [vueComponent/ant-design-vue#7683]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
如果表格高度超过了当前屏幕的高度。
恰好我需要看第54条数据的，Y 滚动条后面的。
那我这时候不得不翻到表格最底下，横向滚动，然后再找到低54行的数据...。

这样的体验是非常不友好的。

### What does the proposed API look like?
横向滚动条能固定到屏蔽底部，方便随时左右滚动查看数据。
    

###图片说明
需要翻到最底下，才能左右滚动。
看其中某一条数据，就很不方便。
![2](https://github.com/vueComponent/ant-design-vue/assets/33649764/6f33c6fb-0168-47ad-b078-0b00b7681e6a)

**Comment by YX916** [comment]
按住Shift  滚动鼠标，，，，
