### ISSUE TITLE
当修改滚动条样式后，table组件表头有滚动列，导致样式异常

### ISSUE THREAD

**Issue by kangxiaoxiao** [vueComponent/ant-design-vue#7687]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
### Version
v3.2.20

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ke-zhan-kai-ant-design-vue-3-2-20-forked-5mrxsl?file=/src/demo.vue)

### Steps to reproduce
1、设置了scroll.y
2、设置了全局滚动条样式
3、表格的高度<最大可滚动高度

### What is expected?
表头中没有类型为ant-table-cell-scrollbar的th标签

### What is actually happening?
表头中有滚动列标签，视觉上表头最后一列与主体没有对齐

**Comment by ShaoNan028** [comment]
遇到了相同的问题

**Comment by LinZiqing2020** [comment]
遇到了相同的问题
