### ISSUE TITLE
[其他] 是否可以考虑再搞个flutter版本出来

### ISSUE THREAD

**Issue by gailiuziaa007** [vueComponent/ant-design-vue#7688]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在flutter版本急缺, 基本没有可选的flutter版本组件库

### What does the proposed API look like?
符合flutter风格

**Comment by selicens** [comment]
这个仓库也只是基于官方React版ant-design然后社区实现的vue版本，可能没法满足你的需求，你可以试着在[antd](https://github.com/ant-design/ant-design/issues)仓库下提issue，或者GitHub搜索下flutter-antd的关键词，目前还是能搜到一些仓库的，可以看下是否满足需求
