### ISSUE TITLE
a-image-preview-group多张图片预览时，怎么设置当前想要的预览的图片？

### ISSUE THREAD

**Issue by huangmingfu** [vueComponent/ant-design-vue#7690]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
a-image-preview-group多张图片预览时，怎么设置当前想要的预览的图片？

### What does the proposed API look like?
一个保存了图片路径的数组，n个，可以控制当前预览的图片

**Comment by Roywhite** [comment]
imgRef.value.$.provides[Object.getOwnPropertySymbols(imgRef.value.$.provides)[0]].setCurrent(index)，index是图片在数组里的顺序
