### ISSUE TITLE
config-provider组件在嵌套使用时，内层组件影响外层组件，内部影响外部

### ISSUE THREAD

**Issue by core-admin** [vueComponent/ant-design-vue#7708]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.

![image](https://github.com/vueComponent/ant-design-vue/assets/77573477/138c16d4-befa-4e5e-9da0-9e26620096a8)
        
        
### Version
4.2.3

### Environment
在线环境

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/zu-jian-chi-cun-ant-design-vue-4-2-3-forked-l5q2k9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cly4n67by00063b6k0metk4vg%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cly4n67bx00023b6khyvpxzwh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cly4n67bx00033b6k1unn1ykc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cly4n67bx00053b6kslqkwl1u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cly4n67bx00023b6khyvpxzwh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly4n67bx00013b6kixjc6dda%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522cly4n67bx00023b6khyvpxzwh%2522%252C%2522activeTabId%2522%253A%2522cly4n67bx00013b6kixjc6dda%2522%257D%252C%2522cly4n67bx00053b6kslqkwl1u%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cly4n67bx00043b6kkkjc9szv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cly4n67bx00053b6kslqkwl1u%2522%252C%2522activeTabId%2522%253A%2522cly4n67bx00043b6kkkjc9szv%2522%257D%252C%2522cly4n67bx00033b6k1unn1ykc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cly4n67bx00033b6k1unn1ykc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce
基于官方提供的主题章节中的代码codesandbox进行修改测试的。

### What is expected?
内部使用config-provider组件修改token，应该仅响应子组件，不应该对其父组件及其父组件的其他组件造成影响

### What is actually happening?
当把 button 组件 嵌套进 config-provider组件修改主题色后，config-provider外层的组件也同样被修改了主题色，受到了此组件的影响

**Comment by stone-liu3432** [comment]
没人处理这个问题吗 ？最近在做一个导航栏的定制主题（只修改导航栏主题），也遇到这个问题了。只针对导航栏做了configProvider的包裹，但是影响到全局的modal、message。

**Comment by tanhh326** [comment]
我也遇到了这个问题，在有几个路由页单独配置了主题，会影响到全局，最后只能条件判断处理它
