### ISSUE TITLE
Aside下的Menu在收起状态openKeys没有对应修改

### ISSUE THREAD

**Issue by Cyan-963852** [vueComponent/ant-design-vue#7710]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
Apple M1 Pro、Chrome 126.0.6478.127、Vue 3.4.31

### Reproduction link
[https://antdv.com/components/layout-cn#components-layout-demo-side](https://antdv.com/components/layout-cn#components-layout-demo-side)

### Steps to reproduce
在官方示例的侧边布局：Aside下的Menu在展开时选择了User菜单下子菜单，收起后选择Team菜单下子菜单，再展开会发现openKeys对应打开的还是User菜单。

### What is expected?
在收起选择了什么子菜单，展开后对应的SubMenu菜单应该被展开。

### What is actually happening?
在展开前打开的菜单，收起选择其他菜单后再展开还是最初选的。

**Comment by ruanzy** [comment]
the same  question
