### ISSUE TITLE
table单元格气泡显示

### ISSUE THREAD

**Issue by anna647** [vueComponent/ant-design-vue#7712]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
超过宽度将自动省略，hover显示气泡

### What does the proposed API look like?
table单元格气泡显示

        

你好，我翻看了文档column有ellipsis参数设置超过宽度将自动省略，通过插槽可以显示气泡。
但我们整个系统都是这样设计的，我看了每个气泡都是独立的。是否有类似surely table的属性不要重复渲染toolTip？
本打算写个tooltip然后通过open参数控制显隐达到重复利用的目的，但是定位又有点问题。
请问下是否有更好的方式解决这个问题？

**Comment by dwtom** [comment]
请问你如何实现ellipsis和tooltip共存的，我试了下ellipsis对自定义的列是不生效的

**Comment by anna647** [comment]
> 请问你如何实现ellipsis和tooltip共存的，我试了下ellipsis对自定义的列是不生效的

我写了个插槽，tooltip默认显示，用if控制的。

**Comment by Alkaidcc** [comment]
> 超过宽度将自动省略，hover显示气泡

这个咋实现的，能给个示例代码吗？
