### ISSUE TITLE
Select mode属性类型声明和文档不一致

### ISSUE THREAD

**Issue by hzlzsm** [vueComponent/ant-design-vue#7713]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
browser

### Reproduction link
[https://next.antdv.com/components/select-cn#api](https://next.antdv.com/components/select-cn#api)

### Steps to reproduce
文档中mode的属性值为'multiple' | 'tags' | 'combobox'，ts声明中为"multiple" | "tags" | "SECRET_COMBOBOX_MODE_DO_NOT_USE"

### What is expected?
ts正确

### What is actually happening?
ts报错了

![image](https://github.com/vueComponent/ant-design-vue/assets/73974273/97adbe2b-13c2-471c-a7dd-2166be604ba2)
![image](https://github.com/vueComponent/ant-design-vue/assets/73974273/62072c55-c049-4539-87f0-27abba2eb676)
![image](https://github.com/vueComponent/ant-design-vue/assets/73974273/c9f8de1b-9513-469d-8ebf-15dc143b0a33)

**Comment by cc-hearts** [comment]
🤔 目前 `combobox` 已经废弃了，可以使用 `AutoComplete` 组件替代。
