### ISSUE TITLE
table  数据量达到400条以上出现滑动条一直滑动页面会卡死

### ISSUE THREAD

**Issue by raobinhui** [vueComponent/ant-design-vue#7716]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
vue3  "ant-design-vue": "4.1.2",

### Reproduction link
[https://www.antdv.com/components/table-cn](https://www.antdv.com/components/table-cn)

### Steps to reproduce
table  数据量达到400条以上出现滑动条一直滑动页面会卡死

### What is expected?
不需要分页想加载所有数据

### What is actually happening?
table  数据量达到400条以上出现滑动条一直滑动页面会卡死

**Comment by helloword107** [comment]
一页显示100条也会卡死

**Comment by raobinhui** [comment]
> 一页显示100条也会卡死

有解决方法吗

**Comment by orionna319** [comment]
[Please see this solution](https://github.com/vueComponent/ant-design-vue/issues/7457#issuecomment-2224941966)

**Comment by typed-sigterm** [comment]
用 [surely vue table](https://www.surely.cool/)

**Comment by raobinhui** [comment]
> [请参阅此解决方案](https://github.com/vueComponent/ant-design-vue/issues/7457#issuecomment-2224941966)

感谢感谢

**Comment by raobinhui** [comment]
> 用 [surely vue table](https://www.surely.cool/)

这个好像收费下载后报一堆莫名其妙的错误

**Comment by anna647** [comment]
表头过长，页面也会卡死。真是崩溃，自己也解决不了。。。

**Comment by andyesfly** [comment]
可以试一下VXETABLE

**Comment by han1548772930** [comment]
建议 aggrid

**Comment by raobinhui** [comment]
> 建议 aggrid

这个是啥

**Comment by robertyclin** [comment]
这个官方会有优化吗

**Comment by typed-sigterm** [comment]
这个没法优化，优化就要完全重新设计（虚拟化），会破坏很多现有涉及 DOM 的用例
