### ISSUE TITLE
a-input 组件不受控

### ISSUE THREAD

**Issue by guaijie** [vueComponent/ant-design-vue#7720]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
vue: 3.x ; ant-design-vue: 4.2.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-shi-yong-ant-design-vue-4-2-3-forked-n6ch2s?file=%2Fsrc%2Fdemo.vue)

a-input 组件不受控

```vue
<template>
  <h1>{{ msg }}</h1>
  <a-input v-model:value="msg" @input="handleChange" />
  <!-- 非受控组件 -->
  <a-input :value="1" />
  <!-- 受控组件 -->
  <a-select style="width: 100%" :value="1" :options="options" />
</template>
<script lang="ts" setup>
import { ref } from "vue";
const msg = ref();
const options = [
  { label: 1, value: 1 },
  { label: 2, value: 2 },
];
const handleChange = () => {
  msg.value = "Hello";
};
</script>
```

### What is expected?
期待 a-input 组件与 a-select 组件一样，都是受控组件

### What is actually happening?
no response

**Comment by pangao66** [comment]
input的输入触发事件是 @input事件   跟html原生保持一致，  @change 是失焦的时候触发的

**Comment by guaijie** [comment]
> input的输入触发事件是 @input事件 跟html原生保持一致， @change 是失焦的时候触发的

那你改成 input 事件再尝试，我强调的是 a-input 组件不受控，而不在于用哪个事件去主动修改值

**Comment by jack-7788** [comment]
首先你为什么会有如此奇怪的想法， v-model:value , 是由 :value + @update:value  组成的语法糖，
你想 使用  const handleChange = () => msg.value = 'Hello'  生效，
那么就不用使用 v-model   ，应该这么写
<a-input :value="msg"  @update:value ="handleChange " />

**Comment by cc-hearts** [comment]
作者的意思应该是
```vue
<a-input :value="msg" /> 
```

如果 msg 为 `hello world` 的话，说明组件是受控的(意思由 value 控制组件的值),  由于没有进行 msg的值变更操作。 因此预期的情况是无论在输入框中输入任何内容，值始终是`hello world` 。

如有误，请指正

**Comment by guaijie** [comment]
> 首先你为什么会有如此奇怪的想法， v-model:value , 是由 :value + @update:value 组成的语法糖， 你想 使用 const handleChange = () => msg.value = 'Hello' 生效， 那么就不用使用 v-model ，应该这么写 <a-input :value="msg" @update:value ="handleChange " />

你先去 vue 官网自己去写个 demo, 链接也都给你了，你也可以自己去实操

**Comment by guaijie** [comment]
> 首先你为什么会有如此奇怪的想法， v-model:value , 是由 :value + @update:value 组成的语法糖， 你想 使用 const handleChange = () => msg.value = 'Hello' 生效， 那么就不用使用 v-model ，应该这么写 <a-input :value="msg" @update:value ="handleChange " />

那你就拆成以下这种写法去尝试，所有的事件都控制不了输入框的显示值
```vue
<template>
  <h1>{{ msg }}</h1>
  <a-input :value="msg" @update:value="handleChange" />
</template>
<script lang="ts" setup>
import { ref } from "vue";
1;
const msg = ref();
const handleChange = () => {
  msg.value = "Hello";
};
</script>
```

**Comment by guaijie** [comment]
> 作者的意思应该是
> 
> ```
> <a-input :value="msg" /> 
> ```
> 
> 如果 msg 为 `hello world` 的话，说明组件是受控的(意思由 value 控制组件的值), 由于没有进行 msg的值变更操作。 因此预期的情况是无论在输入框中输入任何内容，值始终是`hello world` 。
> 
> 如有误，请指正
像你所说的这样子组件完全受控，当然是最好的。但 vue3 官方并未提及受控组件的概念，不像 react 。因此组件受控需要交给组件库去实现。所以我并不清楚提出质疑的那位同志是否了解过这一概念。
所以，我也不说这组件能完全受控，但现在是任何一个事件居然都控制不了输入框的值，直接导致我无法控制字符类型、长度等等

**Comment by jack-7788** [comment]
> > 首先你为什么会有如此奇怪的想法， v-model:value , 是由 :value + @update:value 组成的语法糖， 你想 使用 const handleChange = () => msg.value = 'Hello' 生效， 那么就不用使用 v-model ，应该这么写 <a-input :value="msg" @update:value ="handleChange " />
> 
> 那你就拆成以下这种写法再去尝试嘛，所有的事件都控制不了输入框的显示值,。
> 
> ```
> <template>
>   <h1>{{ msg }}</h1>
>   <a-input :value="msg" @update:value="handleChange" />
> </template>
> <script lang="ts" setup>
> import { ref } from "vue";
> 1;
> const msg = ref();
> const handleChange = () => {
>   msg.value = "Hello";
> };
> </script>
> ```
> 
> 不管你是用 update:value 还是 change 还是 input 你首先得清楚这些事件的触发时机吧。 ![image](https://private-user-images.githubusercontent.com/30885718/353686528-e69af920-7226-4e0a-9128-e5f2439446ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTIzNTIsIm5iZiI6MTcyMjQxMjA1MiwicGF0aCI6Ii8zMDg4NTcxOC8zNTM2ODY1MjgtZTY5YWY5MjAtNzIyNi00ZTBhLTkxMjgtZTVmMjQzOTQ0NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA3NDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZGFmYmMyYjRjMGI2MjE4NDk1ZTQ3NTU4OTc0Zjg3N2M1MTM4MzFjMmVjZDA5ZmE1YTYyOTZhYzA5M2JlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WB8FQv5LTOLO0tQl4JkU0EtdFhBfZLj-ZeWYZwbM9w)

第一 ， msg.value = 'Hello'; 肯定你键盘怎么敲始终都是 Hello 呀，因为只有这里在赋值呀

第二， 如果你想拿到你想输入的值 ，  不管是update:value 事件，还是chang事件，还是input事件， 他都有回调参数的， 
> ```
> <template>
>   <h1>{{ msg }}</h1>
>   <a-input :value="msg" @update:value="handleChange" />
> </template>
> <script lang="ts" setup>
> import { ref } from "vue";
> 1;
> const msg = ref();
> const handleChange = (value) => {
> //value 是回调参数的值 ， 你可以根据此参数进行逻辑判断，在进行下一行的赋值逻辑
>   msg.value = "xxx";
> };
> </script>
> ```

**Comment by guaijie** [comment]
> > > 首先你为什么会有如此奇怪的想法， v-model:value , 是由 :value + @update:value 组成的语法糖， 你想 使用 const handleChange = () => msg.value = 'Hello' 生效， 那么就不用使用 v-model ，应该这么写 <a-input :value="msg" @update:value ="handleChange " />
> > 
> > 
> > 那你就拆成以下这种写法再去尝试嘛，所有的事件都控制不了输入框的显示值,。
> > ```
> > <template>
> >   <h1>{{ msg }}</h1>
> >   <a-input :value="msg" @update:value="handleChange" />
> > </template>
> > <script lang="ts" setup>
> > import { ref } from "vue";
> > 1;
> > const msg = ref();
> > const handleChange = () => {
> >   msg.value = "Hello";
> > };
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不管你是用 update:value 还是 change 还是 input 你首先得清楚这些事件的触发时机吧。 ![image](https://private-user-images.githubusercontent.com/30885718/353686528-e69af920-7226-4e0a-9128-e5f2439446ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTIzNTIsIm5iZiI6MTcyMjQxMjA1MiwicGF0aCI6Ii8zMDg4NTcxOC8zNTM2ODY1MjgtZTY5YWY5MjAtNzIyNi00ZTBhLTkxMjgtZTVmMjQzOTQ0NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA3NDczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZGFmYmMyYjRjMGI2MjE4NDk1ZTQ3NTU4OTc0Zjg3N2M1MTM4MzFjMmVjZDA5ZmE1YTYyOTZhYzA5M2JlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6WB8FQv5LTOLO0tQl4JkU0EtdFhBfZLj-ZeWYZwbM9w)
> 
> 第一 ， msg.value = 'Hello'; 肯定你键盘怎么敲始终都是 Hello 呀，因为只有这里在赋值呀
> 
> 第二， 如果你想拿到你想输入的值 ， 不管是update:value 事件，还是chang事件，还是input事件， 他都有回调参数的，
> 
> > ```
> > <template>
> >   <h1>{{ msg }}</h1>
> >   <a-input :value="msg" @update:value="handleChange" />
> > </template>
> > <script lang="ts" setup>
> > import { ref } from "vue";
> > 1;
> > const msg = ref();
> > const handleChange = (value) => {
> > //value 是回调参数的值 ， 你可以根据此参数进行逻辑判断，在进行下一行的赋值逻辑
> >   msg.value = "xxx";
> > };
> > </script>
> > ```

你到底有没有明白别人提这个 issue 的意思，你能不能自己先去理解别人的意思和先尝试再来表达自己的看法

**Comment by 23431** [comment]
今天也遇到这个问题了，试了下 elemnt-plus是正常的

**Comment by JonathanLiuc** [comment]
问题是有，具体原因可以看一下原生input dom的value逻辑，然后看下作者在setValue之后nextTick中回调的逻辑就能看出原因了，作者用的那个$forceUpdate应该是最终比对了属性一样没更新原生input的dom，临时解法是补一个nextTick，回调里通过外层ref取到input的dom节点，如果dom的value与传入给a-input的value不同，就赋值input的dom的value为外面的传入给a-input的value

**Comment by GuoOcean** [comment]
4.2.5版本还是没修改啊

**Comment by GuoOcean** [comment]
<a-input
                ref="feeInputRef"
                :value="formParams.fee"
                @update:value="onFeeInput($event)"
              >
                <template #addonAfter>
                  <a-select
                    style="width: 60px"
                    v-model:value="formParams.feeType"
                  >
                    <a-select-option :value="1">%</a-select-option>
                    <a-select-option :value="2">元</a-select-option>
                  </a-select>
                </template>
 </a-input>
 
 const onFeeInput = (e: any) => {
  nextTick(() => {
    if (formParams.value.feeType === 1) {
      feeInputRef.value.$el.querySelector("input").value = formatValue100(e);
      formParams.value.fee = formatValue100(e);
    } else {
      feeInputRef.value.$el.querySelector("input").value = formatDecimal(e);
      formParams.value.fee = formatDecimal(e);
    }
  });
};

临时解法
