### ISSUE TITLE
InputNumber组件使用 precision 时,在safari浏览器中且输入法为mac自带输入法的简体中文时（第三方输入法正常）,会自动填写小数点后面的值,小数点后值的长度为precision的值

### ISSUE THREAD

**Issue by cyole** [vueComponent/ant-design-vue#7723]
https://github.com/vueComponent/ant-design-vue/assets/44540278/33c018a7-9240-4e79-9abb-c332d5b982e2

- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
Safari    MacOS 系统默认简体中文输入法

### Reproduction link
[https://github.com/cyole/ant-design-vue-input-number](https://github.com/cyole/ant-design-vue-input-number)

### Steps to reproduce
使用input-number组件 并且使用precision属性  在safari浏览器中操作

### What is expected?
输入法为mac自带输入法的简体中文时（第三方输入法正常）,会自动填写小数点后面的值,小数点后值的长度为precision的值

### What is actually happening?
期望和其他英文输入法一样 不自动填写小数点后面的值，当前情况无法输入100 这类的值

**Comment by CatMiaogu** [comment]
遇上同样的问题了

**Comment by ljw-codeking** [comment]
我也遇到这个问题了

**Comment by cc-hearts** [comment]
safari下触发的事件 onKeyDown -> watchPostEffect -> onKeyUp

**Comment by cc-hearts** [comment]
🤔 原生的 `input` `keyDown` `keyUp` 事件的触发顺序在两个浏览器平台之间也有差异

[复现链接](https://play.vuejs.org/#eNqNUl1PwjAU/SvNfQESM0L0CTeCGh7QRI362MQs4zoGXdv0g48Q/ru3ZeBMCLqXbfecnp5z2h3caZ2sPMIQUluYSjtm0XnNRC7LjIOzHEZcclkoaR2b53Im8Am3M7WWLOv2shHbccnoCQQlMBGq7HYOPLbELQvMTu+Wy/0ZGdooY90e+1vG606v0fitMpXau3+oRF6jkfYPWWOy1GGtRe6Q/sJaxtIqao7ji0poCXBgY7ITQp2Apo4G8roNeE3jPimn/dY2cEXFksevqkwWVklqPxrnUKhaVwLNi3YVZeAwPEbikAuh1o9x5ozHq+O8mGOxPDNf2E2YcXg1aNGskMMJc7kpkdIEePL+jBv6PoG1mnlB7AvgG1K/Png80O59CGxavOh2WmtlXCXLDzvZOJT2GCoYDcx95HOgK/hwIfqP3evkJq6jc6QWP1dogiYVSEAyGMD+G/aP8G8=)

**Comment by cyole** [comment]
在使用自带的简体拼音输入法时存在差异，在使用英文输入法和第三方输入法表现正常
![image](https://github.com/user-attachments/assets/8fc50103-2e91-4930-b7e4-358e2a4d53af)
![image](https://github.com/user-attachments/assets/07e4804d-7ae5-4a05-a832-9f7765ec4bee)
![image](https://github.com/user-attachments/assets/d7807bf9-93ed-4339-bfeb-39b65a5f83b9)

**Comment by cyole** [comment]
> 🤔 原生的 `input` `keyDown` `keyUp` 事件的触发顺序在两个浏览器平台之间也有差异
> 
> [复现链接](https://play.vuejs.org/#eNqNUl1PwjAU/SvNfQESM0L0CTeCGh7QRI362MQs4zoGXdv0g48Q/ru3ZeBMCLqXbfecnp5z2h3caZ2sPMIQUluYSjtm0XnNRC7LjIOzHEZcclkoaR2b53Im8Am3M7WWLOv2shHbccnoCQQlMBGq7HYOPLbELQvMTu+Wy/0ZGdooY90e+1vG606v0fitMpXau3+oRF6jkfYPWWOy1GGtRe6Q/sJaxtIqao7ji0poCXBgY7ITQp2Apo4G8roNeE3jPimn/dY2cEXFksevqkwWVklqPxrnUKhaVwLNi3YVZeAwPEbikAuh1o9x5ozHq+O8mGOxPDNf2E2YcXg1aNGskMMJc7kpkdIEePL+jBv6PoG1mnlB7AvgG1K/Png80O59CGxavOh2WmtlXCXLDzvZOJT2GCoYDcx95HOgK/hwIfqP3evkJq6jc6QWP1dogiYVSEAyGMD+G/aP8G8=)

在使用自带的简体拼音输入法时存在差异，在使用英文输入法和第三方输入法表现正常
![image](https://github.com/user-attachments/assets/8fc50103-2e91-4930-b7e4-358e2a4d53af)
![image](https://github.com/user-attachments/assets/07e4804d-7ae5-4a05-a832-9f7765ec4bee)
![image](https://github.com/user-attachments/assets/d7807bf9-93ed-4339-bfeb-39b65a5f83b9)

**Comment by hengistchan** [comment]
有解决方案吗
