### ISSUE TITLE
Table组件的expandedRowRender插槽和columns中的fixed不能共用

### ISSUE THREAD

**Issue by tedyuen** [vueComponent/ant-design-vue#773]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
macos10.14.4 (18E226);vue 2.6.6;ant-design-vue 1.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1809y0pko3)

### Steps to reproduce
1. Table组件中使用expandedRowRender插槽
2. columns中fixed固定最后一列
3. 点开expanded的 号

### What is expected?
展开的内容高度和fixed的那一列的高度一致

### What is actually happening?
展开的内容高度和fixed的那一列的高度不一致

**Comment by wangxueliang** [comment]
ref #308
