### ISSUE TITLE
使用v-for动态创建timeline时，时间线不显示

### ISSUE THREAD

**Issue by ddyszw** [vueComponent/ant-design-vue#7730]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
undefined

### Environment
"vue": "^3.4.29",    "ant-design-vue": "^4.2.3",    "vite": "^5.3.1"

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
<a-timeline v-for="(item,index) in baseData.eventList">
<a-timeline-item  v-if="item.type=='login'"  style="">
![45275f5ee71545435662c68ba67f7e4b](https://github.com/user-attachments/assets/0f9dbc98-d952-4e30-8aed-636fa8f902cf)

<template #dot><UserOutlined   style="font-size: 16px"/></template>
登录111!&nbsp;&nbsp;&nbsp;{{item.datetime}}
</a-timeline-item>
</a-timeline>

### What is expected?
节点之间的连接线条正常显示

### What is actually happening?
只生成了节点，节点之间的线条没有显示

**Comment by selicens** [comment]
v-for移至a-timeline-item上（图一）或者使用v-show而不是v-if（图二）
![image](https://github.com/user-attachments/assets/18eec2a6-a279-4fbe-abc1-4f919b051ed3)
![image](https://github.com/user-attachments/assets/e7aded36-8f6a-4064-b27e-9aaaf0093b44)
