### ISSUE TITLE
组件中是否考虑增加一个颜色选择器(color-picker)？

### ISSUE THREAD

**Issue by Gaius-98** [vueComponent/ant-design-vue#7734]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
1. 用户修改系统主题样式
2. 部分业务下需要选择颜色

### What does the proposed API look like?
```
<a-color-picker v-model:color="bgColor" size="small">
</a-color-picker>
```

**Comment by index-xiao** [comment]
可以的话，取色器能够取值网页内所有的颜色，例如vuetifyjs中的那样

**Comment by tckxjzc** [comment]
确实需要一个
