### ISSUE TITLE
a-config-provider 补充cssVar参数

### ISSUE THREAD

**Issue by milo-xiaomeng** [vueComponent/ant-design-vue#7738]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在大多数情况下,需要在静态css文件中去使用css变量,故而无法使用 theme.useToken()来获取变量.目前大多数项目都需要自己去实现将 theme.useToken()的属性填充到root的css变量中,因此我建议组件本身支持这个功能。其实这个功能在antd中是已经存在的,如果antdv能够支持肯定是更好的

### What does the proposed API look like?
```vue
<a-config-provider
  :theme="{
    cssVar: true
  }"
></a-config-provider>
```

**Comment by QFifteen** [comment]
https://github.com/vueComponent/ant-design-vue/pull/7220

**Comment by milo-xiaomeng** [comment]
> #7220
好的 感谢
