### ISSUE TITLE
Select 选择器在数据不匹配时显示异常

### ISSUE THREAD

**Issue by yangfei4913438** [vueComponent/ant-design-vue#774]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
MAC10.14.4、Chrome 74.0.3729.131

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
```jsx
<a-select class="service-select" v-model="service_id">
<a-select-option v-for="item in service_list" :value="item.id" :key="item.id">{{item.name}}</a-select-option>
</a-select>
```
当service_id的值，不存在列表 service_list 中时，那么，select 选择器会显示service_id

### What is expected?
期望的结果是显示：服务名称（item.name），service_list 列表中 item.id === service_id, 然后显示 item.name。 如果不匹配，则显示空白。空白表示不存在的选项，而不是显示一条记录，会让用户误以为，这个属性是存在的。但是系统出错，显示了内容错误（service_id 是一长串字符，用户是无法识别的，会认为系统出错了）。

### What is actually happening?
实际结果，当 item.id 无法和 service_id 匹配，会显示 service_id。

---
service_id 不存在 service_list 中，那么就不能显示内容。否则会引起用户的认知错误。

**Comment by 540240126** [comment]
我也遇到了这个问题，目前能想到临时解决方案就是要么对select再封装一层，要么改源码

**Comment by axetroy** [comment]
确实是怎么回事。

组件应该提供这么一类属性 `:fallback-label="item.name"`，当不匹配的时候，显示名称，而不是显示 ID

**Comment by unique-vv** [comment]
回显时检查一下值在不在选项中，不在时把值置为空
`if (!option.some(o => o[formValue] === form.getFieldValue(name))) {
                form.setFieldsValue({[name]: ''})
              }`
