### ISSUE TITLE
分段控制器闪现问题

### ISSUE THREAD

**Issue by yuyingjie20** [vueComponent/ant-design-vue#7740]
https://github.com/user-attachments/assets/0ab7cf16-df2e-4914-af76-f718b98d4e04

- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
win10，Chrome121.0.6167.185，antV4.2.3

### Reproduction link
[https://www.antdv.com/components/segmented-cn](https://www.antdv.com/components/segmented-cn)

### Steps to reproduce
官网   分段控制器基础用法随意点击   分段控制器中的滑块会偶现闪现的问题

### What is expected?
解决这个闪现问题

### What is actually happening?
官网   分段控制器基础用法随意点击  分段控制器中的滑块会偶现闪现的问题

---
官网   分段控制器基础用法随意点击   分段控制器中的滑块会偶现闪现的问题

**Comment by cn-xufei** [comment]
确实会有这个问题，可以看下这个 [pr](https://github.com/vueComponent/ant-design-vue/pull/8045)
