### ISSUE TITLE
Modal组件渲染后控制台提示报错信息，"aria-hidden" 被使用到了可聚焦元素上

### ISSUE THREAD

**Issue by BingHua017** [vueComponent/ant-design-vue#7749]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
chrome版本 127.0.6533.73（正式版本）（64 位）

### Reproduction link
[https://www.antdv.com/components/modal-cn](https://www.antdv.com/components/modal-cn)

### Steps to reproduce
1. 使用chrome最新版本;
2. 打开antdv组件库的modal界面;
3. 打开console并触发页面的modal组件即可见到此报错信息；

### What is expected?
预期是没有此报错信息

### What is actually happening?
使用modal组件并调用后console显示如下报错信息：
Blocked aria-hidden on a `<div>` element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.

MDN文档关于[aria-hidden](https://developer.mozilla.org/zh-CN/docs/Web/Accessibility/ARIA/Attributes/aria-hidden)的说明中提到：不要在可以获得焦点的元素上使用 aria-hidden="true"。

**Comment by mfish-qf** [comment]
我也遇到了相同的问题，解决了吗？

**Comment by lv107w** [comment]
这个问题我观察了下，换个浏览器就不会报错，在出现报错的浏览器下打开ant design vue官网的modal仍会提示报错，应该和浏览器的版本更新相关

**Comment by FlyingTigerReally** [comment]
这是一个与可访问性相关的错误提示，说明你在一个 <div> 元素上使用了 aria-hidden 属性，而这个元素或其祖先元素刚刚接收了焦点。这会导致屏幕阅读器等辅助技术无法访问到这个元素，这样的做法是不可取的。

aria-hidden 属性通常用于隐藏不需要辅助技术访问的内容。然而，当一个元素被隐藏时，它不应该接收焦点，因为这会让使用辅助技术的用户无法与这个元素进行交互。

为了避免这个问题，你可以考虑使用 inert 属性。inert 属性不仅会隐藏元素，还会防止它接收焦点。

谁能更新？

**Comment by LiLongFei0** [comment]
我也碰见了 前段时间还没有，版本 3.2.20。

**Comment by xiyu97** [comment]
今天遇到的，更新下浏览器就好了

**Comment by wwtx666** [comment]
浏览器

**Comment by haokejie** [comment]
我这里同样遇到了 版本  4.2.1 ，这似乎和最近浏览器跟新的版本有关

**Comment by LiLongFei0** [comment]
浏览器也更新了 没有&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 下午2:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vueComponent/ant-design-vue] Modal组件渲染后控制台提示报错信息，&quot;aria-hidden&quot; 被使用到了可聚焦元素上 (Issue #7749)














 
我这里同样遇到了 版本  4.2.1 ，这似乎和最近浏览器跟新的版本有关

**Comment by SAKURA-CAT** [comment]
同样的问题🤔

**Comment by anyc100** [comment]
临时处理的话就先在全局把Modal中该属性的元素隐藏
.ant-modal div[aria-hidden="true"] {
  display: none !important;
}

**Comment by Tianci-blog** [comment]
官方啥时候把那行代码改一下呀。我浏览器没更新都没报，今天更新了就直接报了这个错。

**Comment by Tianci-blog** [comment]
> 临时处理的话就先在全局把Modal中该属性的元素隐藏 .ant-modal div[aria-hidden="true"] { display: none !important; }

大概看了一下，这个元素好像没啥用。不知道有没有我没发现的用处。  不管了先隐藏掉再说

**Comment by piggycute** [comment]
> 临时处理的话就先在全局把Modal中该属性的元素隐藏 .ant-modal div[aria-hidden="true"] { display: none !important; }

没用哎，控制台还是报错的

**Comment by anyc100** [comment]
> > 临时处理的事情就先在全局把 Modal 中该属性的元素隐藏 .ant-modal div[aria-hidden="true"] { display: none !important; }
> 
> 没用哎，控制台还是报错的



> > 临时处理的话就先在全局把Modal中该属性的元素隐藏 .ant-modal div[aria-hidden="true"] { display: none !important; }
> 
> 没用哎，控制台还是报错的

检查一下样式是否生效

**Comment by 378406712** [comment]
> > 临时处理的话就先在全局把Modal中该属性的元素隐藏 .ant-modal div[aria-hidden="true"] { display: none !important; }
> 
> 没用哎，控制台还是报错的

加在全局css试试，有用的

**Comment by atdun** [comment]
是不是修复了，我刚刚看控制台不报错了

**Comment by atdun** [comment]
> > 是不是修复了，我刚刚看控制台不报错了
> 
> 如果修复了这个issue会关闭的。现在官方文档那还能复现这个问题。

我现在用的版本事3.2.16前几天确实有这个问题，今天看已经没有了，不知道是怎么回事。

**Comment by QCDT** [comment]
现在依然存在这个问题，不过第二次或者刷新之后点击，错误会消失

**Comment by ajiua** [comment]
更新下浏览器好像好了     版本 127.0.6533.100（正式版本） （64 位）

**Comment by ajiua** [comment]
现在还有这个问题      版本 127.0.6533.100（正式版本） （64 位）

**Comment by szh18** [comment]
现在有解决方法吗 
![image](https://github.com/user-attachments/assets/578c0b6b-be7e-43a3-b20a-68acbdbde663)

**Comment by 285858315** [comment]
+1
![image](https://github.com/user-attachments/assets/9ce1cd02-d719-4664-88ce-d48fa4cefc12)

**Comment by yang-xianzhu** [comment]
> 这个问题我观察了下，换个浏览器就不会报错，在出现报错的浏览器下打开ant design vue官网的modal仍会提示报错，应该和浏览器的版本更新相关

chrome 127版本后就会

**Comment by Tianci-blog** [comment]
> 现在有解决方法吗 ![image](https://private-user-images.githubusercontent.com/74402781/356051045-578c0b6b-be7e-43a3-b20a-68acbdbde663.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxOTAzMDEsIm5iZiI6MTcyMzE5MDAwMSwicGF0aCI6Ii83NDQwMjc4MS8zNTYwNTEwNDUtNTc4YzBiNmItYmU3ZS00M2EzLWIyMGEtNjhhY2JkYmRlNjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA3NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyOTlmNWRiMzM0NzZlYWU0OTRkZWNhMGVkMWU3YTc5MzNlN2M2MDgzZjAxMjFiNDA1MTBjZmE5MzI4OGZhYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2NBxNYNQhPaGgPHm4aFdEWUR3KRZStdOCq2FUU78_1M)

你就直接全局加上面那位兄弟给的这个临时解决
div[aria-hidden="true"] {
display: none !important;
}

**Comment by gezichenshan** [comment]
这个问题好像也导致了我的select组件无法open？

**Comment by Jzow** [comment]
Ant Design官方已修复 [50170](https://github.com/ant-design/ant-design/issues/50170)

**Comment by jiafulu** [comment]
.ant-modal div[aria-hidden="true"] {
     display: none !important;
}
临时方案中的display: none !important;  
发现一个bug，弹窗内容中如果有a-tab组件切换时候内容显示不出来，改成visibility: hidden !important;后正常

**Comment by pzm666** [comment]
我ant-design-vue是4.2.3版本，Modal弹窗也报这个错误，谷歌最新的版本

**Comment by pzm666** [comment]
> 我ant-design-vue是4.2.3版本，Modal弹窗也报这个错误，谷歌最新的版本

我把keyboard属性设置为false，就好了

**Comment by wilding96** [comment]
这个问题我最近也遇到了，是在a-modal组件使用的时候出现的，但是在我排查后发现是组件内的表单项配置出了问题，修复表单项配置（可能是字段名，赋值逻辑有问题）后就没出现这个报错了。仅供给各位参考。
