### ISSUE TITLE
表格组件columns如果是computed，resizable设置拖拽不生效

### ISSUE THREAD

**Issue by sculiaojin** [vueComponent/ant-design-vue#7757]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
vue3，chrome

### Reproduction link
[https://next.antdv.com/components/table-cn#api](https://next.antdv.com/components/table-cn#api)

### Steps to reproduce
无

### What is expected?
设置resizable可以拖拽

### What is actually happening?
表格组件columns如果是computed，resizable设置拖拽不失效，handleResizeColumn方法中col丢失了响应式

**Comment by pavitra-infocusp** [comment]
True. The resize effect only comes into effect after some other action like sorting a column.
