### ISSUE TITLE
IE10 table组件行列表显示错位

### ISSUE THREAD

**Issue by zhangshengbiao** [vueComponent/ant-design-vue#776]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
IE10

### Reproduction link
[https://preview.pro.loacg.com/list/table-list  (注：把描述字段内容加长)](https://preview.pro.loacg.com/list/table-list  (注：把描述字段内容加长))

### Steps to reproduce
https://preview.pro.loacg.com/list/table-list  (注：把"描述"字段内容加长,IE10下无自动换行，且表格列出现错位)
如下：
https://github.com/zhangshengbiao/test/blob/master/table.png

### What is expected?
IE10描述字段内容多时会换行，表格不会错位

### What is actually happening?
出现错位

**Comment by sendya** [comment]
你可以尝试把 列宽 设定一下，然后利用 tooltip 等解决方案，把更多的内容隐藏起来，然后通过浮层显示
