### ISSUE TITLE
drawer 组件内部使用vue v-bind-in-css，样式不生效

### ISSUE THREAD

**Issue by nailuox** [vueComponent/ant-design-vue#7761]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
vue4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-4-2-3-forked-s66yfy?file=%2Fsrc%2Fdemo.vue%3A37%2C14)

### Steps to reproduce
1、在drawer外部使用v-bind-in-css, 样式生效
![image](https://github.com/user-attachments/assets/374d91f1-c2cf-4290-b273-7e14ed4f15f1)

2、在drawer内部使用v-bind-in-css, 样式不生效
![image](https://github.com/user-attachments/assets/261d6607-d658-4d56-b082-88b33db4ddce)

### What is expected?
使用v-bind-in-css, 样式生效

### What is actually happening?
vue没有生成内联样式

**Comment by selicens** [comment]
![image](https://github.com/user-attachments/assets/db2800df-7752-4c9d-8143-33a5924a64da)
可以用body-style的形式

**Comment by nailuox** [comment]
> ![image](https://private-user-images.githubusercontent.com/69418751/353769088-db2800df-7752-4c9d-8143-33a5924a64da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzU0NjYsIm5iZiI6MTcyMjQ3NTE2NiwicGF0aCI6Ii82OTQxODc1MS8zNTM3NjkwODgtZGIyODAwZGYtNzc1Mi00YzlkLTgxNDMtMzNhNTkyNGE2NGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxMTkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMDAxYTA3NTM3NGMxOGY2NzgwZmJiYzY0NTQ4YWI0MWQwMmNhYzIzYTdhYzBkM2YxODFkNzRlNWZiZjVkMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N4Pk9ekbjU3JSSPQCPCpiRHMRlgboUkCwWLlVPxotdM) 可以用body-style的形式

`body-style` 是根属性呀，如何 给`drawer` 内部的单个`div` 设置呢

**Comment by nailuox** [comment]
> ![image](https://private-user-images.githubusercontent.com/69418751/353769088-db2800df-7752-4c9d-8143-33a5924a64da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzYwMjcsIm5iZiI6MTcyMjQ3NTcyNywicGF0aCI6Ii82OTQxODc1MS8zNTM3NjkwODgtZGIyODAwZGYtNzc1Mi00YzlkLTgxNDMtMzNhNTkyNGE2NGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxMjg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5MmRkOTczZDJlODUzYmUzZDIxMDRkODA3N2JiMGNkZDVhMDhkNWU3YjViN2VkMDM0MWMyOTZjZTYyOTlkN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZhxMvKbVo6EGMdcwG8IFj8dhp6h-jCyWyiqNJM5kd9U) 可以用body-style的形式

你好，我主要想知道为什么在 `.ant-drawer-body` 内部的元素在 使用`v-bind`时，vue没有生成内联样式？
在官网文档中 写出 `antdv` 对 `drawer` `message` 等组件是通过 [Vue.render 重新渲染一个 Vue 根节点上，和主应用的 Vue 节点是脱离的](https://www.antdv.com/components/config-provider-cn#api)，是否是这里在处理方式导致的？

**Comment by nailuox** [comment]
> ![image](https://private-user-images.githubusercontent.com/69418751/353769088-db2800df-7752-4c9d-8143-33a5924a64da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NzY3ODUsIm5iZiI6MTcyMjQ3NjQ4NSwicGF0aCI6Ii82OTQxODc1MS8zNTM3NjkwODgtZGIyODAwZGYtNzc1Mi00YzlkLTgxNDMtMzNhNTkyNGE2NGRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDAxNDEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNTM4NzkyYTkzZWQ5NDMxYmMzNzViZTdmYTZkNTljMjRlNDNjNDkwOGI4MjcxY2ZjN2NiODYzYTdjNDQ0OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.437hYZKOIUKaItSUcbhOIVMdUreto832mIurmt91DZw) 可以用body-style的形式

https://codesandbox.io/p/sandbox/ji-ben-yong-fa-ant-design-vue-4-2-3-forked-s66yfy?file=%2Fsrc%2Fdemo.vue%3A34%2C3
加了截图中的代码，实际效果不太一样：
![image](https://github.com/user-attachments/assets/14caae70-7871-4434-be18-1d4880447214)

**Comment by selicens** [comment]
![image](https://github.com/user-attachments/assets/52f4d6bf-44a0-4840-a5c6-c94d8185beb3)
那就这样呗，绑定样式

**Comment by Yee1014** [comment]
> ![image](https://github.com/user-attachments/assets/52f4d6bf-44a0-4840-a5c6-c94d8185beb3) 那就这样呗，绑定样式

在`<style scope>`中使用`v-bind`写的样式怎么办？比如我有很多 `test-style`，用 `class` 的方式绑定就不行吗？
