### ISSUE TITLE
FloatButton 组件没有完全继承Button属性

### ISSUE THREAD

**Issue by Dylan-lijl** [vueComponent/ant-design-vue#7762]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当我把FloatButton 完全当成button使用时发现缺少很多Button组件的属性,导致我不得不自己去实现loading ,disabled等等这些属性

### What does the proposed API look like?
提供插槽覆盖原来的button,或者完全继承button的属性

**Comment by selicens** [comment]
FloatButton底部是原生button而非组件Button

**Comment by Dylan-lijl** [comment]
> FloatButton底部是原生button而非组件Button

但是我不想用原生的button而是想用组件button,如何解决

**Comment by selicens** [comment]
封装Button
