### ISSUE TITLE
在axios拦截器里使用message、notification等API，无法使用config provider定义的主题

### ISSUE THREAD

**Issue by jiangyong1998** [vueComponent/ant-design-vue#7768]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
"vue": "^3.4.29"

### Steps to reproduce
使用app组件包裹应用，基础用法和全局场景 (pinia 场景)都尝试过

### What is expected?
可以正常显示

### What is actually happening?
报错：useGlobalStore(...).message?.success is not a function

**Comment by twosoy** [comment]
遇到同样的问题，不确定是自己的写法有问题，还是框架自身有bug，跪求解决。

**Comment by jiangyong1998** [comment]
> 遇到同样的问题，不确定是自己的写法有问题，还是框架自身有bug，跪求解决。
![image](https://github.com/user-attachments/assets/937ecd72-992f-4052-81c1-f9ca8a127270)
![image](https://github.com/user-attachments/assets/3570d924-e773-477d-861e-6bf70a5c870d)

可以暂时先手动挂载到全局

**Comment by twosoy** [comment]
我试试，谢谢。

**Comment by gaokun** [comment]
https://antdv.com/components/message-cn#%E4%B8%BA%E4%BB%80%E4%B9%88-message-%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81pinia-%E7%9A%84%E5%86%85%E5%AE%B9%E5%92%8C-configprovider-%E7%9A%84-locale-prefixcls-theme-%E7%AD%89%E9%85%8D%E7%BD%AE%EF%BC%9F

文档中有提到
