### ISSUE TITLE
日历组件月份不显示中文

### ISSUE THREAD

**Issue by shenlanchenwei** [vueComponent/ant-design-vue#7770]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
MAC

### Reproduction link
[https://antdv.com/components/calendar-cn](https://antdv.com/components/calendar-cn)

### Steps to reproduce
安装最新版本的dayjs,设置中文后,日历月份选择不会显示中文,而是显示英文,年份正常
**我看官方引用的是"dayjs": "^1.10.5" 正常,但是如果安装的最新版本dayjs就会显示异常**

### What is expected?
安装最新版本dayjs,设置语言为中文后日历组件可以显示中文而不是英文

### What is actually happening?
安装最新版本dayjs,设置语言为中文后日历组件部分中文,部分英文

**Comment by holiy930561** [comment]
同问题，如何修复？

**Comment by shenlanchenwei** [comment]
day 组件退回"dayjs": "^1.10.5"  就可以了,不能用最新版本

**Comment by yinmang1215** [comment]
npm ls dayjs 查看dayjs版本，项目中dayjs需要与ant-design-vue中的保持一致

**Comment by wiexin** [comment]
同问 这个问题是否有修复计划啊

**Comment by Gluttonys** [comment]
https://www.antdv.com/components/config-provider-cn
