### ISSUE TITLE
InputNumber修改v-model的值，change事件不触发

### ISSUE THREAD

**Issue by AcWrong02** [vueComponent/ant-design-vue#7774]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
最新版

### Environment
Vue3.4.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-4-2-3-forked-kjq89g?file=/src/demo.vue)

### Steps to reproduce
通过上下的按钮拉改变v-model的数值

### What is expected?
希望触发change事件

### What is actually happening?
没触发change事件

**Comment by selicens** [comment]
![image](https://github.com/user-attachments/assets/d241153d-5993-4086-b9ec-477e5bcf6d75)
没有复现

**Comment by AcWrong02** [comment]
> ![image](https://private-user-images.githubusercontent.com/69418751/356524457-d241153d-5993-4086-b9ec-477e5bcf6d75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODIxOTYsIm5iZiI6MTcyMzI4MTg5NiwicGF0aCI6Ii82OTQxODc1MS8zNTY1MjQ0NTctZDI0MTE1M2QtNTk5My00MDg2LWI5ZWMtNDc3ZTViY2Y2ZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA5MjQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5Y2RhNWJjOGNmNGVkYjkyMWI3Yzk5Yzk0OGRhMzlmZGFlMTMzMDhkMGE2MTUzZDk1NTZlZDc3YTUxY2JiZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeV3gj4Fj9mqeQl4g8uxryRVsXarMn-S0P4pHz_bPJs) 没有复现

直接输入值是可以触发的，我点击上下的悬浮按钮不行 @selicens
