### ISSUE TITLE
文件上传的onSuccess方法会将后端返回的String类型数字转为Number造成精度丢失

### ISSUE THREAD

**Issue by dapeng0201** [vueComponent/ant-design-vue#7780]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
windows11 node20 antdv4.2.3

### Reproduction link
[https://www.antdv.com/components/upload-cn#customrequest-%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%EF%BC%9F](https://www.antdv.com/components/upload-cn#customrequest-%E6%80%8E%E4%B9%88%E4%BD%BF%E7%94%A8%EF%BC%9F)

### Steps to reproduce
使用自定义上传`customRequest`并且调用**onSuccess**方法  传入字符串(比如雪花ID)
```ts
async function customRequest(info: UploadRequestOption) {
info.onSucess('12345678901234567890')
}
```

### What is expected?
不被转换为Number  实际应该为String

### What is actually happening?
字符串被转换为Number类型  如果超过js安全数会丢失精度
源码位置：[https://github.com/vueComponent/ant-design-vue/blob/main/components/upload/Upload.tsx#L198](https://github.com/vueComponent/ant-design-vue/blob/main/components/upload/Upload.tsx#L198)

```ts
const onSuccess = (response: any, file: FileType, xhr: any) => {
try {
if (typeof response === 'string') {
response = JSON.parse(response);
}
} catch (e) {
/* do nothing */
}
...省略
};
```

传入为string会走`JSON.parse`逻辑  会将String转为Number

![8cec35f555713af3e26ad5567b7c10f](https://github.com/user-attachments/assets/af922241-8d22-40bf-8bda-cf670d4ad453)

**比如后端返回为雪花ID 超过js安全数会造成丢失精度问题**

**Comment by cc-hearts** [comment]
业务层的数据精度应该由业务层自行处理
