### ISSUE TITLE
希望在Table的colums属性中加一个设置colgroup标签的max-width、min-width的功能

### ISSUE THREAD

**Issue by kimchunhe** [vueComponent/ant-design-vue#7784]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
目前，表格字段都设置宽度后会等比放大，很不好看

### What does the proposed API look like?
```
{
title: 'shopName',
key: '卖场名',
dataIndex: 'shopName',
minWidth: 210, //让此属性在resizable:false时，设置<colgroup style="min-width:210;" />
},
```

**Comment by deepthan** [comment]
急切需要此功能，不过目前只能通过 patch方法实现了，有需要的人可以试下：
```
 const columns = [
  {
    'RC_TABLE_INTERNAL_COL_DEFINE': {
      style:{
        'min-Width': '500px',
      }
    }
  }
]
```

他会从 column里读取 key 为 `RC_TABLE_INTERNAL_COL_​​DEFINE` 的属性添加到 col 上

**Comment by mouse0w0** [comment]
同样需要此功能，不知为何无人采纳题主的pr。
