### ISSUE TITLE
全局a-config-provider设置的componentSize，在modal.confirm中没有生效

### ISSUE THREAD

**Issue by dubiping** [vueComponent/ant-design-vue#7785]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
调用modal.confirm时，全局设置的componentSize生效

### What does the proposed API look like?
全局a-config-provider设置的componentSize， 赋值到globalConfigForApi， 使其modal.confirm内部的定义a-config-provider也同步生效

**Comment by 15890182384** [comment]
因为Modal.confirm他是重新createApp创建的一个容器,没有兼容原有的appContext.
