### ISSUE TITLE
Form getFieldValue获取旧值问题

### ISSUE THREAD

**Issue by Mumusen** [vueComponent/ant-design-vue#779]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
macOS Mojave 10.14.4,Chrome,vue:2.6.10

### Reproduction link
[https://github.com/Mumusen/ant-form](https://github.com/Mumusen/ant-form)

### Steps to reproduce
点击CheckBox，通过getFieldValue得到的值为旧值

### What is expected?
获取实时的值，得以更新全选状态值

### What is actually happening?
获取旧值

---
from表单，多选功能

**Comment by tangjinzhou** [comment]
cleanChange执行时，form收集器里面的值还不是最新的，
你的场景直接从 change回调传递出来的就是最新值，没必要通过form的API再次获取
