### ISSUE TITLE
使用form表单，自定义校验（validator）时出现意外的警告。

### ISSUE THREAD

**Issue by xakxak007** [vueComponent/ant-design-vue#7796]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
mac os:14.5; chrome:127.0.6533.120; Vue:3.4.29

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nfmkxp)

### Steps to reproduce
使用form表单，在其添加一个input输入框，在校验规则中，使用自定义校验（validator），根据文档使用了callback。但是在控制台出现了警告 ：“Warning: `callback` is deprecated. Please return a promise instead.”

### What is expected?
代码无警告正常运行。

### What is actually happening?
出现了意外的警告：“Warning: `callback` is deprecated. Please return a promise instead.”

**Comment by alicemw** [comment]
我也遇到这个问题了

**Comment by alicemw** [comment]
好吧，是async_validator更新了，你这文档也更新一下啊
