### ISSUE TITLE
Popover位置异常

### ISSUE THREAD

**Issue by mano233** [vueComponent/ant-design-vue#780]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
macOS:10.14.5,Chrome:74.0.3729.131,Vue:2.6.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/14mookz05l?fontsize=14)

### Steps to reproduce
点击按钮

### What is expected?
刷新页面之后的第一次点击，Popover位置异常（使用的是居中对齐），位置向右偏离了一点。再次点击，位置计算正常

### What is actually happening?
应该出现按钮的正下方

---
当给Popover使用 左对齐 或者给一个title，位置计算正常，如下代码：<a-popover titile="title" placement="bottomLeft">

**Comment by mano233** [comment]
`<a-popover trigger="click" placement="bottomLeft">`或者`<a-popover trigger="click"  title="title" placement="bottom">`

**Comment by luoxiaoji** [comment]
同样使用Popover 时 位置时对时不对，用align 偏移矫正后  数据一更新又偏移了。

**Comment by tangjinzhou** [comment]
可以先给upload 赋值一个宽度，临时解决它
原因已经定位，https://github.com/react-component/upload/issues/187

**Comment by mano233** [comment]
**谢谢，已经解决**


添加如下样式：
![image](https://user-images.githubusercontent.com/29190675/58611796-ea803000-82e2-11e9-8d7e-0ea8ff2e72ff.png)


最终结果：
![image](https://user-images.githubusercontent.com/29190675/58611823-008df080-82e3-11e9-97be-fca48cc6bd7b.png)


符合预期效果

**Comment by GlodenBoy** [comment]
这个不在源码 彻底解决吗？
