### ISSUE TITLE
Pagination 更多分页省略号出现向下偏移

### ISSUE THREAD

**Issue by ranlu823** [vueComponent/ant-design-vue#7809]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
"vue": "^3.4.29",  "ant-design-vue": "^4.2.3",

### Reproduction link
[https://www.antdv.com/components/pagination-cn](https://www.antdv.com/components/pagination-cn)

### Steps to reproduce
<a-pagination current="10" pageSize="20" show-size-changer :total="500" />

### What is expected?
正常显示

### What is actually happening?
省略号出现向下偏移
![微信截图_20240828162500](https://github.com/user-attachments/assets/53fe3520-39cc-464c-93f7-9a4344cc26ef)
![微信截图_20240828162500](https://github.com/user-attachments/assets/b3c98d99-3fc9-4636-b3c3-64dc0349d7ef)

**Comment by txw2018** [comment]
好像重现不了

**Comment by lmorz** [comment]
破案了，按 vue 教程安装的项目，在 src/assets/main.css 中有 demo 的样式，去掉 a 的 padding 就好了。。。
