### ISSUE TITLE
modal maskClosable属性不生效

### ISSUE THREAD

**Issue by qinqian886** [vueComponent/ant-design-vue#781]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win8 谷歌7.4 vue:1.3.8

### Reproduction link
[http://10.61.121.49:8080/](http://10.61.121.49:8080/)

### Steps to reproduce
设置直接不生效

### What is expected?
希望可用

### What is actually happening?
很不开心

---
没有

**Comment by wangxueliang** [comment]
请参考这个demo（https://codesandbox.io/s/vue-antd-template-0uupo）
ps: 如果还有问题，麻烦提供有效链接

**Comment by enhezzz** [comment]
@wangxueliang  this is a minimum producible repo: https://codesandbox.io/s/nervous-sky-kzd65?file=/src/components/HelloWorld.vue:200-208
