### ISSUE TITLE
a-input添加allow-clear属性，点击删除图标报target.cloneNode is not a function

### ISSUE THREAD

**Issue by kwaynet** [vueComponent/ant-design-vue#7814]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.0

### Environment
vue:3.3.13

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
1、页面代码输入框
<a-form-item label="SKU" class="smart-query-form-item">
<a-input v-model:value="queryForm.sku" allow-clear/>
</a-form-item>

2、页面显示输入框，输入数据123，点删除图标时效

### What is expected?
能清除输入框里面的值

### What is actually happening?
不能清除输入框里面的数据，并且控制台弹出错误提示，错误提示如下
Uncaught TypeError: target.cloneNode is not a function
at resolveOnChange (ant-design-vue.js?v=8574f413:61480:34)
at handleReset (ant-design-vue.js?v=8574f413:61869:7)
at callWithErrorHandling (chunk-4SOU3IJP.js?v=8574f413:1581:18)
at callWithAsyncErrorHandling (chunk-4SOU3IJP.js?v=8574f413:1589:17)
at HTMLSpanElement.invoker (chunk-4SOU3IJP.js?v=8574f413:10068:5)

**Comment by kwaynet** [comment]
<a-form-item label="系统SKU" class="smart-query-form-item">
       <a-input v-model:value="queryForm.viomallSku" allow-clear/>
 </a-form-item>

**Comment by kwaynet** [comment]
`  <a-form-item label="系统SKU" class="smart-query-form-item">
            <a-input v-model:value="queryForm.viomallSku" allow-clear/>
</a-form-item>`

**Comment by cc-hearts** [comment]
ref #7523
