### ISSUE TITLE
针对谷歌浏览器升级的128内核对zoom的处理body  进行缩放偏移问题

### ISSUE THREAD

**Issue by lingfeng123z** [vueComponent/ant-design-vue#7816]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.14

### Environment
windows11，edge浏览器版本 128.0.2739.54 (正式版本) (64 位),vue3

### Reproduction link
[https://www.antdv.com/components/menu-cn](https://www.antdv.com/components/menu-cn)

### Steps to reproduce
浏览器最新版本更新了对css缩放属性的处理  未更新之前只缩放字体 但更新之后兼容了长度和高度的缩放。而且这种兼容ant desgin 5.0版本是没有这个问题的

### What is expected?
希望维护更新之后和ant desgin 5.0版本一样同时兼容128版本浏览器缩放

### What is actually happening?
浏览器版本更新

---
浏览器版本更新之后  发现body缩放之后  所有的悬浮出现的内容  都发生了偏移  包括菜单鼠标移上出现二级菜单的这种情况

        
<img width="1264" alt="浏览器128版本修改body缩放出现菜单偏移" src="https://github.com/user-attachments/assets/b1c13a1c-05e9-4a58-a290-67582acf48f3">
![Uploading ant design 5.0版本浏览器128版本修改body缩放未出现菜单偏移.png…]()

**Comment by canifindyou** [comment]
这个解决了吗

**Comment by studyisnotsimple** [comment]
希望官方能支持

**Comment by Eastboat** [comment]
这个问题解决了吗
