### ISSUE TITLE
一些组件(例如select组件onChange/onSearch)传递props绑定事件时使用时报警告[warning] Expected Function, got Array, 导致后续触发事件时报错, 因为组件内部props事件传递给子组件时将function处理成Array了

### ISSUE THREAD

**Issue by Hmap-Mr** [vueComponent/ant-design-vue#7818]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
分支标签4.2.3 直接下载download.zip

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
一些组件传递props绑定事件时使用时报警告[warning] Expected Function, got Array, 导致后续触发事件时报错, 因为组件内部props事件传递给子组件时将function处理成Array了, 相关组件包含但可能不限于(select: onChange/onSearch, modal: onClose, )等。复现步骤直接使用Select组件 绑定@change事件后会报警告,触发时对应事件时会报错

### What is expected?
修复此bug, 事件传递处理时正确传递事件, 而不是数组

### What is actually happening?
线上生产版本不会有此类情况

---
bug修复后, 希望可以回复一下此条提问

**Comment by Hmap-Mr** [comment]
![企业微信截图_17252725453737](https://github.com/user-attachments/assets/21e422ca-2722-4fd6-a19a-223e92abeec4)
![企业微信截图_17252726039927](https://github.com/user-attachments/assets/c0600d48-e55c-4fb6-b98c-284cc236438e)

**Comment by Hmap-Mr** [comment]
直接使用运行就已经报props的警告了
![企业微信截图_17252727644905](https://github.com/user-attachments/assets/791cb554-cd0a-49f6-aede-ad5e80b592f3)
此处传入onChange事件是function
![企业微信截图_17252726039927](https://github.com/user-attachments/assets/faa16c4a-61b8-47b1-95c4-bd7ba57e6fed)
但后续vc-select接收时确实Array
![企业微信截图_17252727347142](https://github.com/user-attachments/assets/a2b349d1-dcb9-40fa-a252-b3eb7e302a52)
后续触发对应事件将会报错
![企业微信截图_17252728559250](https://github.com/user-attachments/assets/c569d168-6087-4cd6-b490-f718b2fcc7b1)

**Comment by selicens** [comment]
https://github.com/vueComponent/ant-design-vue/blob/2666cb79abf9825872e37b55d6d9d4c1cf30e62a/components/vc-select/Select.tsx#L411-L416
应该是这里引起的

**Comment by shuipinhuajieyu** [comment]
vue的jsx好像是这样
如果写多个onChange就会合并成数组
