### ISSUE TITLE
官方不打算维护了？

### ISSUE THREAD

**Issue by hengistchan** [vueComponent/ant-design-vue#7820]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
官方不打算维护了？issue 两三个月没处理了，MR 提了一堆也没合并

### What does the proposed API look like?
无

**Comment by a81n9** [comment]
？

**Comment by softboy99** [comment]
同问

**Comment by yuantongkang** [comment]
同问
