### ISSUE TITLE
Table 组件的 Column customRender 参数，不支持同步/异步请求数据？

### ISSUE THREAD

**Issue by godcheese** [vueComponent/ant-design-vue#783]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
OS:MacOS 10.13.6、Browser:Google Chrome 74  x64、Vue:1.3.8

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-98wsl)

### Steps to reproduce
定义一个表格，从远程JSON 数据，在某个表格数据中的某个列中（如部门 ID列），定义一个customRender，将部门 id 重新（同步/异步）请求远程数据，然后将部门名从远程获取并在表格中渲染，渲染代码应写在 customRender 中。
主要代码如下：
```
customRender: async (text, row, index) => {
let department = await axiosRequestDepartmentNameByDepartmentId(text);
let departmentName = department.name
console.log(departmentName)
return departmentName
}
```

### What is expected?
customRender 能够正常渲染出从远程请求的部门名

### What is actually happening?
渲染结果是 undefined

**Comment by tangjinzhou** [comment]
不要再customRender中发起异步请求，
想象一下，一个100行的表格，要发100次请求？
