### ISSUE TITLE
Modal pops up with the following error message: Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus

### ISSUE THREAD

**Issue by lis216** [vueComponent/ant-design-vue#7838]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
win11, edge  128.0.2739.67,vue:3.5.4

### Reproduction link
[https://github.com/ant-design/ant-design/issues/50170](https://github.com/ant-design/ant-design/issues/50170)

### Steps to reproduce
引用a-modal组件。然后打开弹窗时，console报错

### What is expected?
不报错

### What is actually happening?
报错：Modal pops up with the following error message: Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus

**Comment by selicens** [comment]
Waiting for pr merge #7823
