### ISSUE TITLE
Promise state of formRef.value.validate() is always rejected, errorFields is 0, and outOfDate is true when using form component during form validation

### ISSUE THREAD

**Issue by wangshilin123** [vueComponent/ant-design-vue#7852]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.5

### Environment
win11,Chrome128.0.6613.138,vue@3.5.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/2wpk21kzvr)

### Steps to reproduce
<a-form
ref="formRef"
:model="formState"
:rules="formRules"
@submit.prevent="handleSubmit"
class="login-form"
>
<a-form-item name="username">
<a-input v-model:value="formState.username" size="large" placeholder="username">
<template #prefix>
<UserOutlined />
</template>
</a-input>
</a-form-item>
<a-form-item name="password">
<a-input-password v-model:value="formState.password" size="large" placeholder="password">
<template #prefix>
<LockOutlined />
</template>
</a-input-password>
</a-form-item>
<div class="login-options">
<a @click="handleForgetPassword" class="forget-password">forget-password</a>
</div>
<a-form-item>
<a-button type="primary" html-type="submit" :loading="loading" block size="large">
登录
</a-button>
</a-form-item>
</a-form>

import { reactive, ref } from 'vue'
const formRef = ref()
const formRules = {
username: [{ required: true, message: 'username', trigger: 'blur' }],
password: [{ required: true, message: 'password', trigger: 'blur' }],
}

const handleSubmit = async () => {
try {
await formRef.value.validate()
....}
catch (errors) {
console.error(errors)
}
}

### What is expected?
It should be "fulfilled" in the promise state to proceed with the next code execution.

### What is actually happening?
The promise state of formRef.value.validate() is always rejected, consistently caught by catch, causing the program to exit due to the error.

---
When I changed the component from a-form to Naive UI's n-form, the promise state was fulfilled, so I suspect it's a bug. Since I'm new to learning Vue, I don't know how to resolve it.

**Comment by gswy** [comment]
我也遇到了相同的问题，始终被catch捕获，并未执行then
