### ISSUE TITLE
a-tree 同一叶子节点下，缩进各不一样，导致页面凌乱不堪

### ISSUE THREAD

**Issue by 123LCQ** [vueComponent/ant-design-vue#7863]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
"vue": "^3.2.25",

### Reproduction link
[https://2x.antdv.com/components/tree-cn/#Tree-](https://2x.antdv.com/components/tree-cn/#Tree-)

### Steps to reproduce
<a-tree  同一叶子节点下，缩进各不一样，导致页面凌乱不堪。发下是设置:field-names="fieldNames" 导致的，
const fieldNames = {
children: 'children',
title: 'orgName',
key: 'orgId'
}

<a-tree
v-if="treeData.length && visible"
id="tree"
v-model:expandedKeys="expandedKeys"
v-model:checkedKeys="checkedKeys"
v-model:selectedKeys="selectedKeys"
:checkable="isMultiple"
:tree-data="treeData"
:field-names="fieldNames"
:checkStrictly="true"
@check="handleCheck"
@select="handleSelect"
>
<template #title="record">

<span v-if="isMultiple">
<Icon :orgType="record.orgType"></Icon>
{{ record.orgName }}
</span>

<span v-if="!isMultiple">
<Icon :orgType="record.orgType"></Icon>
<a-radio
:checked="selectedKeys.includes(record.orgId)"
v-if="record.orgType == orgType"
>
</a-radio
>{{ record.orgName }}
</span>
</template>
</a-tree>

### What is expected?
现象：
https://photo.harsonserver.com/1727337272463.png
https://photo.harsonserver.com/1727337313198.png

数据结构：https://photo.harsonserver.com/1727337537529.png
递归json 数据字段就是 关键三个： orgId/orgName/children

### What is actually happening?
实际上就是同一级下的叶子节点缩进各不一样，导致排版错乱，看起来都不方便

**Comment by 123LCQ** [comment]
<img width="806" alt="企业微信截图_374e479b-2dfa-476e-9f9b-ad362c8067b8" src="https://github.com/user-attachments/assets/84a3a060-8bdc-40ac-a65d-6faca2c2380b">
<img width="796" alt="企业微信截图_2520cd83-97f6-402c-91bf-5b3714966f1c" src="https://github.com/user-attachments/assets/db7d4baf-53ef-40c7-9a2e-405966ffa098">

**Comment by 123LCQ** [comment]
组件使用的相关代码：
<a-tree
            v-if="treeData.length && visible"
            id="tree"
            v-model:expandedKeys="expandedKeys"
            v-model:checkedKeys="checkedKeys"
            v-model:selectedKeys="selectedKeys"
            :checkable="isMultiple"
            :tree-data="treeData"
            :field-names="fieldNames"
            :checkStrictly="true"
            @check="handleCheck"
            @select="handleSelect"
          >
            <template #title="record">
              
              <span v-if="isMultiple">
                <Icon :orgType="record.orgType"></Icon>
                {{ record.orgName }}
              </span>
              
              <span v-if="!isMultiple">
                <Icon :orgType="record.orgType"></Icon>
                <a-radio
                  :checked="selectedKeys.includes(record.orgId)"
                  v-if="record.orgType == orgType"
                >
                </a-radio
                >{{ record.orgName }}
              </span>
            </template>
          </a-tree>

**Comment by 123LCQ** [comment]
<img width="567" alt="企业微信截图_04a6813b-9227-4d02-9e86-59efd1d9d6a4" src="https://github.com/user-attachments/assets/5db37651-cc3e-47c5-b5a0-8ccb5bd58764">

**Comment by 123LCQ** [comment]
递归树层级多了，显示就会有问题，比如七八层、十几层

**Comment by 123LCQ** [comment]
像官方示例数据量少的时候是完全没问题的；要数据量很多，而且递归树层级很深的时候，比如treeData能把json解析器卡住不动，几千甚至几万条数据的时候（例如一个中大型公司的人力系统） 就马上呈现布局问题了

**Comment by 123LCQ** [comment]
![Uploading 企业微信截图_49ff2063-0608-4e6c-b129-4fd0c31483c1.png…]()

**Comment by 123LCQ** [comment]
<img width="833" alt="企业微信截图_49ff2063-0608-4e6c-b129-4fd0c31483c1" src="https://github.com/user-attachments/assets/9c348731-17a0-4b16-b3fa-c22b835fca66">

**Comment by w569111843** [comment]
这种是不是考虑用远程加载呢😝

**Comment by XXXgb** [comment]
检查你的节点id，如果有相同的id，会以最后一个节点的缩进为准。
