### ISSUE TITLE
使用pinia封装message组件，不能正常使用

### ISSUE THREAD

**Issue by loongzhu** [vueComponent/ant-design-vue#7870]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.5

### Environment
Windows 11 专业工作站版  22631.4169, Chrome 129.0.6668.90，Vue 3.5.11

### Reproduction link
[https://stackblitz.com/edit/vitejs-vite-zzcl2j?file=README.md](https://stackblitz.com/edit/vitejs-vite-zzcl2j?file=README.md)

### Steps to reproduce
点击 `click` 按钮

### What is expected?
报错 `globalStore.message.success is not a function`
![image](https://github.com/user-attachments/assets/89c68b30-851e-42ca-8e78-21df7304a7d4)
### What is actually happening?
正确弹出 message 组件

**Comment by zcf0508** [comment]
It seems like a break change from https://github.com/vuejs/core/pull/11502 .

The `inject` get context from the current `instance` prototype before, and then now get context from `currentApp` first .

**Comment by zcf0508** [comment]
@loongzhu 

可以看下我的这个方案

[stackblitz](https://stackblitz.com/edit/vitejs-vite-vlbst2?file=src%2Fstore%2Fantdv-plugin.ts,src%2Fcomponents%2FAntdvAppContextProvider.vue,src%2FApp.vue,src%2Fmain.ts)
