### ISSUE TITLE
Form component Dynamic Form Item BUG

### ISSUE THREAD

**Issue by YuArtian** [vueComponent/ant-design-vue#788]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
mac、chrome74.0.3729.157、vue2.x

### Reproduction link
[https://vue.ant.design/components/form/#components-form-demo-dynamic-form-item](https://vue.ant.design/components/form/#components-form-demo-dynamic-form-item)

### Steps to reproduce
add first item -> add second item -> delete the second item -> input some text in the first item -> submit

### What is expected?
console.log('Received values of form: ', values);

### What is actually happening?
warning: async-validator: ["names[2] is required"]

---
dont use preserve: true

**Comment by sendya** [comment]
form item option 


options.preserve | 即便字段不再使用，也保留该字段的值 | boolean | false
-- | -- | -- | --

**Comment by tangjinzhou** [comment]
@sendya 不是这个问题，初步定位是我们的bug

**Comment by tangjinzhou** [comment]
> @sendya 不是这个问题，初步定位是我们的bug

搞错，这里没问题的
如 @sendya 所言，这里demo添加了 preserve
