### ISSUE TITLE
table组件列拖拽控制列宽的示例

### ISSUE THREAD

**Issue by Fzyfeng** [vueComponent/ant-design-vue#789]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
比如说列拖拽控制列宽这项功能vue的就没有，希望可以加入，

### What does the proposed API look like?
和react部分示例一样就好

**Comment by gerryli0214** [comment]
+1

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-qrdre  这里有个简单的，可参考下

**Comment by lhf1990729** [comment]
请问这个拖动列宽后面有开发支持的计划吗？

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/table/#components-table-demo-resizable-column
