### ISSUE TITLE
 [typography-paragraph]editable没有穿透传递onSave方法

### ISSUE THREAD

**Issue by aov2005** [vueComponent/ant-design-vue#7896]
![image](https://github.com/vueComponent/ant-design-vue/assets/82451257/d8eed138-ab18-4306-a51d-eb52cefa241c)

然后这里其实也只是传了一个 onSave 方法，实际并没有做什么操作

_Originally posted by @kovsu in https://github.com/vueComponent/ant-design-vue/issues/6887#issuecomment-1767550939_

https://github.com/vueComponent/ant-design-vue/blob/6c13c964c5a56a440cf47aba9a8484ebbb2f3a1f/components/typography/Editable.tsx#L116C13-L116C17

这里有执行了save方法吧，只是`typography-paragraph`组件没有把onSave传过来

**Comment by kovsu** [comment]
刚刚看了一下，他这里的 onSave，就是每次输入后的保存

https://github.com/vueComponent/ant-design-vue/blob/e46d537d45e7741aedef795e620ad7c82ed8d7f7/components/typography/Base.tsx#L476

**Comment by kovsu** [comment]
好像只有一个 `onEnd` 的 api

**Comment by aov2005** [comment]
> 好像只有一个 `onEnd` 的 api

是的，时间有点久远了，具体使用场景好像是按下回车和blur就保存内容到后端

**Comment by shiwanjun1995** [comment]
@kovsu 咋不对外暴露一个 onBlur 事件，用户在输入框失去焦点后即时保存，不用再键入一个 enter 按键

**Comment by shiwanjun1995** [comment]
> [@kovsu](https://github.com/kovsu) 咋不对外暴露一个 onBlur 事件，用户在输入框失去焦点后即时保存，不用再键入一个 enter 按键

Why not expose a event named "onBlur", the user saves the input box instantly after it loses focus, without typing an enter key.

**Comment by 274153705** [comment]
自己提交一个修改看看官方合不合吧

https://github.com/vueComponent/ant-design-vue/pull/8385
