### ISSUE TITLE
a-select 设置 mode="tags" 绑定数据绑定的数据值是null时，默认选择一个空的值

### ISSUE THREAD

**Issue by liuyanchen1994** [vueComponent/ant-design-vue#790]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
os:win10   Browser:Google Chrome 74 x64、Vue:2.5.2

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
~~~
<a-select mode="tags" placeholder="请输入用户" v-model="aa">
<a-select-option value="1">1</a-select-option>
<a-select-option value="2">2</a-select-option>
</a-select>

data() {
return {
aa:null
};
},
~~~
### What is expected?
默认没有选择

### What is actually happening?
实际有个一个选择出现

![image](https://user-images.githubusercontent.com/19524048/58153392-7968c900-7ca1-11e9-9e4f-aaad67bfe98e.png)

**Comment by wangxueliang** [comment]
默认选择空的话，赋值空数组[]

**Comment by liuyanchen1994** [comment]
这个api中没有说明，建议加上，或者为空不默认绑定，这样从接口获取数据，就不用每次都要加上判断是否没null来绑定数据了
