### ISSUE TITLE
日期选择器通过全局切换语言为中文，只有年的文案切换了，月份和星期还是英文

### ISSUE THREAD

**Issue by LoisLuo-c** [vueComponent/ant-design-vue#7915]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
"vue": "^3.3.11" ， "vue-i18n": "^9.10.2" ， "ant-design-vue": "^4.2.3"

### Reproduction link
[https://antdv.com/components/date-picker-cn#api](https://antdv.com/components/date-picker-cn#api)

### Steps to reproduce
无论是通过全局，还是日期组件的locale来配置中文，都会出现仅只有年切换为中文，月份和星期都还是英文

### What is expected?
全中文

### What is actually happening?
无论是通过全局，还是日期组件的locale来配置中文，都会出现仅只有年切换为中文，月份和星期都还是英文

**Comment by LoisLuo-c** [comment]
![screenshot-20241105-163321](https://github.com/user-attachments/assets/38f3da35-f526-4bbd-bfe5-a44518dda028)

**Comment by 15200596294git** [comment]
确实有这个问题，我同事也遇到了

**Comment by tangjinzhou** [comment]
https://antdv.com/docs/vue/i18n-cn

**Comment by kaiwen0627** [comment]
这个问题为什么关闭了，有解决方法了吗？

**Comment by kaiwen0627** [comment]
正确的做法是：项目是yarn和npm安装依赖的情况下，删除自己安装的dayjs或monent
