### ISSUE TITLE
tabs标签组件为什么一直闪动

### ISSUE THREAD

**Issue by workCleaner** [vueComponent/ant-design-vue#7916]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.7.7

### Environment
node v16.20、vue v2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/vue-antd-template-forked-gv2rrp)

### Steps to reproduce
当我设置tabs长度为50%，对应每个tabs之间有一定的margin就导致一直闪动

### What is expected?
我大致知道是组件内部做出的计算，导致margin意外触发了这个bug。我需要的是如何把tabs居中且占满全部的剩余宽度，有没有更好的办法

### What is actually happening?
界面展示正常但是会一直闪动

**Comment by selicens** [comment]
![image](https://github.com/user-attachments/assets/f1da9ea5-393c-4f38-923d-6f7632a3c7e2)

**Comment by workCleaner** [comment]
> ![图像](https://private-user-images.githubusercontent.com/69418751/384397034-f1da9ea5-393c-4f38-923d-6f7632a3c7e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyODY1NjYsIm5iZiI6MTczMTI4NjI2NiwicGF0aCI6Ii82OTQxODc1MS8zODQzOTcwMzQtZjFkYTllYTUtMzkzYy00ZjM4LTkyM2QtNmY3NjMyYTNjN2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDAwNTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwODFjODZmNDZjZTEyMjU5NWZkM2RkN2M1ODcwMDE2NWE2Mzg3MjQxMTAwMjI4ZjIwYzllZDZiNjVhMjNhMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aSOgzQFtt0YrzVFQFblo7jkybYU_mDAPuHLXo6RbP3g)

感谢
