### ISSUE TITLE
update上传组件defaultFileList改变后，列表数据不改变

### ISSUE THREAD

**Issue by hongzheng666** [vueComponent/ant-design-vue#792]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
update上传组件defaultFileList改变后，解决文件列表实时显示的问题

### What does the proposed API look like?
当请求后端数据改变defaultFileList后，列表数据渲染新的数据

**Comment by wangxueliang** [comment]
https://ant-design-vue.gitee.io/docs/vue/faq-cn/

**Comment by qm8956** [comment]
有什么好的实践可以解决吗？将upload组建进行二次封装后，数据是从外面传进来的，再加上异步数据问题，defaultFileList数据在界面渲染后才有可能出来，写死的数据意义不大，没有几个从一开始就知道自己的默认文件列表

**Comment by wangxueliang** [comment]
拿到默认列表再渲染组件？

**Comment by qm8956** [comment]
😔，这个貌似不太好吧，我最后自己观察defaultFileList,然后自己在watch中写了个`this.$refs.upload.sFileList = this.defaultFileList;`

**Comment by sendya** [comment]
用 defaultFileList 的用意是什么？ 为什么不用 fileList ?

**Comment by qm8956** [comment]
fileLists（受控），默认能上去，再进行上传和移除操作出现不能正常显示的问题，实时修改fileList 也不正常使用，不知道是不是我用错了，但是实时修改fileList总觉得有点问题

**Comment by mack-wang** [comment]
ant vue所有default只在首次渲染时有效，动态修改不会变化。所以针对这个问题，只要让这个组件再次渲染就可以。
```
<a-upload
 :key="key"
  :default-file-list="defaultFileList"
/>
```
当你的`defaultFileList`变化时，让key++，组件会重新渲染。
