### ISSUE TITLE
BackTop这个组件内容被注释了，希望管理者能验一下

### ISSUE THREAD

**Issue by wuanyang** [vueComponent/ant-design-vue#796]
### Version
1.3.8

### Environment
vue^2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues](https://github.com/vueComponent/ant-design-vue/issues)

### Steps to reproduce
正常的安装运行，页面中是

### What is expected?
希望单元测试更严谨些

### What is actually happening?
组件已经引入进来了，可以打印出来，然而页面中还是

---
希望单元测试更严谨些

**Comment by sendya** [comment]
没有任何异常，如果你还有疑问，可以提供复现代码

https://codesandbox.io/s/vue-antd-template-10vq5

**Comment by wuanyang** [comment]
是全局样式导致的问题，body设置了overflow-y: auto，然后监听不到滑动。麻烦了，🙏
