### ISSUE TITLE
Switch v-model (Reactive)

### ISSUE THREAD

**Issue by atilkan** [vueComponent/ant-design-vue#797]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Removes redundant change event. Better to be reactive rather than event based current api.

### What does the proposed API look like?
`<a-switch v-model="isOn"/>`

**Comment by tangjinzhou** [comment]
v-model already has it. You can try.

**Comment by atilkan** [comment]
@tangjinzhou Can you give me an example. There is none on the docs. I tried and did not work.

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-yjj50

**Comment by atilkan** [comment]
@tangjinzhou I actually did exactly the same but probably i must have did something wrong. Thank you.
