### ISSUE TITLE
某些浏览器在有表格的页面，弹窗会卡顿

### ISSUE THREAD

**Issue by ChenGitHub126** [vueComponent/ant-design-vue#799]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win10，2345或搜狗浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-zmu02)

### Steps to reproduce
1、在2345或搜狗浏览器打开链接
2、点击弹窗后再点取消

### What is expected?
弹窗流畅消失

### What is actually happening?
卡顿或停止响应

---
1、只在页面加载后首次操作会卡顿
2、如果把input的min、max、step删掉，或者减小table数据量，卡顿都会消失
3、在我的实际项目中只有不到60左右的数据量，却会使浏览器停止响应
4、有没有什么解决方案或替代方案

**Comment by ChenGitHub126** [comment]
盼回复。。。

**Comment by tangjinzhou** [comment]
1. 建议 form表单，和其它组件拆分成两个组件，因为每次输入都会重新 render form 所在的组件
2. 搜狗浏览器的卡顿现象尚未发现具体原因
