### ISSUE TITLE
a-form-item循环存在有“a-textarea”时，“textarea”下拉穿过其它“input”的bug

### ISSUE THREAD

**Issue by LiuLiuniuniu** [vueComponent/ant-design-vue#803]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
浏览器版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-zyqii)

## bug视图

![](https://upload-images.jianshu.io/upload_images/12353119-f75caeccdef6aa8a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 代码如下

1.components组件库
```html
<a-form-item
v-for="(item,index) of widgetFormInfo"
:key="index"
:label="item.name"
:label-col="item.l"
:wrapper-col="item.w"
>
<form-storage :config="item" v-model="formData[item.fields]"></form-storage>
</a-form-item>
```

2.data数据

> widgetFormInfo

```js
widgetFormInfo: [
{
type: "textArea", name: "是否必填：", fields: "lylx",
l: {span: 4},
w: {span: 20},
},
]
```
3.form-storage组件库
```html
<a-textarea
v-if="config.type=='textArea'"
v-model="val"
:disabled="config.disabled || false"
:defaultValue="config.defaultValue"
:placeholder="config.placeholder"
/>
```

### What is expected?
# 不穿过下方元素

![](https://upload-images.jianshu.io/upload_images/12353119-ba729f0fd6675705.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### What is actually happening?
test

---
都有

**Comment by tangjinzhou** [comment]
不要定死高度   height: 39.99999999px;
