### ISSUE TITLE
列拖拽和列隐藏

### ISSUE THREAD

**Issue by aleiliuwei** [vueComponent/ant-design-vue#807]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
当字段过长，有时想对字段进行左右拖拽，提高用户体验；每个人关注的字段不同，当表的字段过多时，有时想隐藏掉那些自己不关注的字段。

### What does the proposed API look like?
在a-table 上加入属性:enableResize="true"，可以所有的字段左右拖拽，在columns的单个字段上加入resizable: true，可以实现该字段的拖拽。在a-table 上加入属性:suppressVisiblePanel="true"，则在表格的左右侧显示一个设置的图标，点击则会下拉显示所有的前端字段，点击checkbox，选中的显示，未选中的隐藏，类似bootstrap table的展示效果，在columns的单个字段上加入hidden: true，可以单个隐藏显示一个字段。

**Comment by sendya** [comment]
目前还未支持，你可以参考一下这个的实现 自己试试能不能实现出来 https://github.com/vueComponent/ant-design-vue/blob/master/components/vc-table/demo/column-resize.js

**Comment by tangjinzhou** [comment]
https://www.antdv.com/components/table/#components-table-demo-resizable-column
