### ISSUE TITLE
a-form-item中的lable长度不一时，希望类似table那样能label对其，后面的input长度一致

### ISSUE THREAD

**Issue by aleiliuwei** [vueComponent/ant-design-vue#808]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
页面整齐

### What does the proposed API look like?
这个应该不需要特别的设置，应该文本标签的长度要一致

**Comment by sendya** [comment]
```
labelCol: {
        xs: { span: 24 },
        sm: { span: 7 }
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 13 }
      },
```

然后 label 设定某一个方向对齐，应该就符合了。

**Comment by aleiliuwei** [comment]
查询区域多列
<a-col :md="6" :sm="8"  :>
            <a-form-item label="订单日期" labelCol="labelCol"
                         :wrapperCol="wrapperCol">
              <a-input placeholder="请输入订单日期" v-model="queryParam.orderDate"></a-input>
            </a-form-item>
          </a-col>
          <a-col :md="6" :sm="8"  >
            <a-form-item label="订单金额" :labelCol="labelCol"
                         :wrapperCol="wrapperCol">
              <a-input placeholder="请输入订单金额" v-model="queryParam.orderMoney"></a-input>
            </a-form-item>
          </a-col>

**Comment by gaorubin1990** [comment]
非常需要label-width属性

**Comment by AprilLemon** [comment]
2020年了 加一个label-width 这么困难嘛

**Comment by wanpeng2008** [comment]
my way on 1.6.5
hack FormItem renderFormItem() with "return ( <a-row  type="flex" ..."

then you can use  FormItem like this way
        <a-form-item
          label="Form Layout"
          :label-col="{ flex: '500px' }"
          :wrapper-col="{ flex: 'auto' }"
        >

**Comment by ragnaroks** [comment]
work on 1.7.2
```javascript
<a-form-model ref="form" :model="searchModel" :rules="searchModelRules" :label-col="{span:1,style:'width:8rem'}" :wrapper-col="{span:1,style:'width:24rem'}" />
```
