### ISSUE TITLE
Menu 组件能否在item点击事件上，把当前点击项的整个或者指定的数据传递回来！！！

### ISSUE THREAD

**Issue by Fzyfeng** [vueComponent/ant-design-vue#810]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
不然的话我只能把东西隐藏在dom里，再从里面搞出来啊，一点也不人性化嘛！

### What does the proposed API look like?
@click 或 @select 返回参数多加一个字段即可

**Comment by luoxiaoji** [comment]
可以自己传参。

```
@click="e => handlerClick(e,参数)"

handlerClick(e,参数){ }
```

**Comment by Fzyfeng** [comment]
@GlodenBoy 
<a-menu
			  :defaultSelectedKeys="['1']"
			  :defaultOpenKeys="['2']"
			  mode="vertical"
			  theme="light"
			  @select="onMenuClick"
                          @click="onClickItem"
			  :selectedKeys="asideIndex"
		  >
			  <template v-for="item in rightMenu">
				  <a-menu-item v-if="item.children && item.children.length === 0" :key="item.id">
					  <span>{{item.name}}<span class="hidden-href">?{{item.href}}</span></span>
				  </a-menu-item>
				  <sub-menu v-else :menu-info="item" :key="item.id"/>
			  </template>
		  </a-menu>
来来来我说的是vue  这个点击事件绑定在了a-menu上的

**Comment by GlodenBoy** [comment]
@Fzyfeng 

onClickItem 和 onMenuClick 里 e 的参数 不够用的话
可以用我回复的那种办法 ，传入自己获取的参数。

**Comment by van-chin** [comment]
同样有这样的需求

**Comment by van-chin** [comment]
@Fzyfeng 
可以通过 自定义属性 attribute 绑定想要的数据
```
<a-menu-item   : customAttrs="customAttrs">
    ...
</a-menu-item>
```
然后在memu 的select 或者 click 事件获取到 自定义属性

**Comment by jxssz** [comment]
> @Fzyfeng
> 可以通过 自定义属性 attribute 绑定想要的数据
> 
> ```
> <a-menu-item   : customAttrs="customAttrs">
>     ...
> </a-menu-item>
> ```
> 
> 然后在memu 的select 或者 click 事件获取到 自定义属性

兄弟，怎么获取，能不能说出来
