### ISSUE TITLE
RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份不能选择同一月份

### ISSUE THREAD

**Issue by chenqifa** [vueComponent/ant-design-vue#820]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
火狐，谷歌  IE11

### Reproduction link
[https://vue.ant.design/docs/vue/introduce/](https://vue.ant.design/docs/vue/introduce/)

### Steps to reproduce
RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份不能选择同一月份

### What is expected?
RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份能选择同一月份

### What is actually happening?
RangePicker组件mode为['month', 'month']的情况下起始月份和结束月份不能选择同一月份

**Comment by zuley** [comment]
我也遇到这个问题了，求解决

**Comment by richardsmogodb** [comment]
我也遇到这个问题了，还有disabledDate的在['month', 'month']的情况下无效

**Comment by dengs-official** [comment]
> 我也遇到这个问题了，还有disabledDate的在['month', 'month']的情况下无效

这个问题现在官方有解决的计划吗？

**Comment by LOU980825622** [comment]
可以修改组件库源码
