### ISSUE TITLE
The library is importing all of the ant-design-icons

### ISSUE THREAD

**Issue by undervane** [vueComponent/ant-design-vue#821]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
MacOS 10.14.4, Chrome 74.0.3729.169, Vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-ixdig?fontsize=14)

### Steps to reproduce
1. Just import the message component and its styles from lib/message

### What is expected?
The bundle size to contain only the resources that are being used

### What is actually happening?
The bundle size includes all of the @ant-design/icons library, which is aprox. 521.72kb

---
Just as simple as importing, it comes with all of the ant design icons by default, no way to optimise the bundle

**Comment by yixiyimeng** [comment]
测试有效哦
添加icons.js 按需导出需要的icon  
类似 export {
  default as UserOutline
} from '@ant-design/icons/lib/outline/UserOutline';这样
然后在web.config.js 中 定义别名config.resolve.alias.set('@ant-design/icons/lib/dist$', resolve('src/icons.js'))
参考https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo

**Comment by undervane** [comment]
Hey, @yixiyimeng! Thank you for your answer, definitely that was the point 🖖
