### ISSUE TITLE
treeSelect多选 搜索后， 无法自动清空文本空的搜索文字

### ISSUE THREAD

**Issue by zongyan86** [vueComponent/ant-design-vue#823]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
vue 2.6.6

### Reproduction link
[https://segmentfault.com/q/1010000018117153?utm_source=tag-newest ](https://segmentfault.com/q/1010000018117153?utm_source=tag-newest )

### Steps to reproduce
参考 https://segmentfault.com/q/1010000018117153?utm_source=tag-newest 

### What is expected?
参考https://segmentfault.com/q/1010000018117153?utm_source=tag-newest 

### What is actually happening?
参考https://segmentfault.com/q/1010000018117153?utm_source=tag-newest

**Comment by tangjinzhou** [comment]
searchValue

**Comment by zongyan86** [comment]
> searchValue
能具体说下吗 怎么弄都不对啊。。

**Comment by weilephp** [comment]
请问解决了吗，没有失去焦点事件，searchValue在什么时候清空呢

**Comment by doramart** [comment]
同问
