### ISSUE TITLE
Extend type of 'content' attribute of Modal.method

### ISSUE THREAD

**Issue by Lukinoh** [vueComponent/ant-design-vue#824]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
As I user of ant-design-vue I would like to be able to use function(h) to define the content of a modal using the Modal.methods() function. The goal is to offer more elaborate content to display to the user.

Currently, we can only defined a string, however with Notification or Message component you can set function(h).

### What does the proposed API look like?
The idea would be to harmonize the APIs and add the possibility to use function(h).

Probably doing something like [this line](https://github.com/vueComponent/ant-design-vue/blob/master/components/message/index.js#L77) at [line 85 of ConfirmDialog.jsx](https://github.com/vueComponent/ant-design-vue/blob/master/components/modal/ConfirmDialog.jsx#L85) would be enough ?

**Comment by love4ever92** [comment]
唐老师，这个报错TypeError: this.$confirm is not a function，怎解决？

**Comment by sendya** [comment]
> 唐老师，这个报错TypeError: this.$confirm is not a function，怎解决？

https://github.com/vueComponent/ant-design-vue/blob/master/site/components.js#L64-L70

```
Vue.prototype.$message = message;
Vue.prototype.$notification = notification;
Vue.prototype.$info = Modal.info;
Vue.prototype.$success = Modal.success;
Vue.prototype.$error = Modal.error;
Vue.prototype.$warning = Modal.warning;
Vue.prototype.$confirm = Modal.confirm;
```
需要自己挂载。

另外，有问题请直接创建新的 Issue，不要在已经处理过的 issue 中回复

**Comment by love4ever92** [comment]
谢谢唐老师


| |
赵俊豪
|
|
935707638@163.com
|
签名由网易邮箱大师定制
On 9/18/2019 17:44，言肆<notifications@github.com> wrote：

唐老师，这个报错TypeError: this.$confirm is not a function，怎解决？

https://github.com/vueComponent/ant-design-vue/blob/master/site/components.js#L64-L70

Vue.prototype.$message = message;

Vue.prototype.$notification = notification;

Vue.prototype.$info = Modal.info;

Vue.prototype.$success = Modal.success;

Vue.prototype.$error = Modal.error;

Vue.prototype.$warning = Modal.warning;

Vue.prototype.$confirm = Modal.confirm;



需要自己挂载。

另外，有问题请直接创建新的 Issue，不要在已经处理过的 issue 中回复

**Comment by ximan** [comment]
不好意思再补充一下。
我想在Modal.method()用法里content支持html，文档例子虽然可以实现，但示例代码是错误的。
正确的jsx代码应该是这样的：
content: h => (<div style="color:red;">Some descriptions</div>),
