### ISSUE TITLE
Select组件下拉框模式为multiple时，showArrow为true时，showArrow不生效，但是ant react版本是生效的

### ISSUE THREAD

**Issue by jimmycarry** [vueComponent/ant-design-vue#825]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
Chrome latest verseion Vue2.6.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
1. select组件multiple模式
2. showArrow属性设置为true

### What is expected?
showArrow为true 箭头应该出现

### What is actually happening?
showArrow为true, 箭头没有出现

**Comment by jimmycarry** [comment]
```js
renderArrow(multiple) {
      const { showArrow, loading, prefixCls } = this.$props;
      const inputIcon = getComponentFromProp(this, 'inputIcon');
      if (!showArrow) {
        return null;
      }
      // if loading  have loading icon
      if (multiple && !loading) {
        return null;
      }
      const defaultIcon = loading ? (
        <i class={`${prefixCls}-arrow-loading`} />
      ) : (
        <i class={`${prefixCls}-arrow-icon`} />
      );
      return (
        <span
          key="arrow"
          class={`${prefixCls}-arrow`}
          style={UNSELECTABLE_STYLE}
          {...{ attrs: UNSELECTABLE_ATTRIBUTE }}
          onClick={this.onArrowClick}
        >
          {inputIcon || defaultIcon}
        </span>
      );
    },
```
我看到代码里面是这样的，当为multiple模式时，直接return了null

**Comment by neostfox** [comment]
I see the same issues. how did you resolved it?

**Comment by tangjinzhou** [comment]
1.4.0-beta.0 已经修复  可以直接使用

**Comment by chenyuhuan1** [comment]
有修复吗 我1.6.5还是没有显示箭头
