### ISSUE TITLE
表格某些列设置浮动时,当第一次进入页面,浮动的的列高度异常

### ISSUE THREAD

**Issue by liby** [vueComponent/ant-design-vue#827]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
Win10教育版1809.Google Chrome 版本 74.0.3729.169（正式版本）.Vue@2.6.10.

### Reproduction link
[https://wx4.sinaimg.cn/large/c9f8e52agy1g3kio3vreqg21fk0oke82.gif](https://wx4.sinaimg.cn/large/c9f8e52agy1g3kio3vreqg21fk0oke82.gif)

### Steps to reproduce
刷新网页,进入页面,会看到表格异常显示

### What is expected?
期待它的表格可以显示正常.

### What is actually happening?
当第一次进入页面时,浮动的列高度异常,会像是飘在表格上,下面还有它的影子,这时去往其他页面或者调整浏览器窗口大小,会恢复正常

---
我每一行都给了宽度,留一行自适应

**Comment by wangxueliang** [comment]
gif图打不开
ps： 最好提供复现链接

**Comment by liby** [comment]
@wangxueliang 
- 因为代码比较多我先给你贴个图,我用代码把它复现了,一定贴出来,先给你贴个图,麻烦您看一下是不是有类似的问题被解决过
![原图](https://user-images.githubusercontent.com/38807139/58744036-01ec2400-846f-11e9-8a02-5468d9623cc4.png)
![示例1](https://user-images.githubusercontent.com/38807139/58744037-031d5100-846f-11e9-9cf1-590c5df01b86.png)
- 表格内容也贴出来
```vue
                columns:[
                    { title:'镇（街道、功能区）',key:'unit_name',width:130, fixed:'left'},
                    { title:'基本情况',key:'situation',width:100, fixed:'left'},
                    { title:'下辖行政村（居）',key:'villages',width:100},
                    { title:'下属基层站所',key:'stations',width:100},
                    { title:'新时代文明实践点建设情况',key:'civilization',width:100},
                    { title:'党组织情况',key:'organization',width:100},
                    { title:'经济发展情况',key:'economy',width:100},
                    { title:'下辖经济薄弱村（居）',key:'poor_village',width:100},
                    { title:'辖区内企业',key:'enterprise',width:100},
                    { title:'单位受到表彰情况',key:'commend',width:100},
                    { title:'巡察报告',key:'zhengzhi_id5',width:100},
                    { title:'巡察整改报告',key:'zhengzhi_id4',width:100},
                    { title:'加强党内专题监督报告',key:'zhengzhi_id3',width:100},
                    { title:'信访反映',key:'letter_and_visit',width:100},
                    { title:'"四种形态"处理',key:'four_forms',width:100},
                    { title:'跟踪监督类型', key:'reason_title',width:200},
                    { title:'处置措施',key:'cuoshi'},
                    { title:'操作',key:'option',width:150,fixed: 'right' }
                ]
```
- scroll="{x:2500}"

**Comment by liby** [comment]
-来张更明显的
![对比](https://user-images.githubusercontent.com/38807139/58744069-a8d0c000-846f-11e9-9ee9-4da1b51ea216.png)

**Comment by liby** [comment]
![demo1](https://user-images.githubusercontent.com/38807139/58772322-f3c31280-85ea-11e9-9145-ce389b8b5c56.gif)

**Comment by qixin1991** [comment]
同样碰到这个问题,现在有解决方案了吗?

![image](https://user-images.githubusercontent.com/10718925/60634946-72f27300-9e43-11e9-969e-808e3853a2a1.png)

**Comment by liby** [comment]
@qixin1991 
- 去掉缓存试试,我是在页面来回切换的时候,发现的这个bug,应该是页面切换过来的时候,有缓存,高度没有给上,调整浏览器窗口,表格重新渲染就会正常

**Comment by qixin1991** [comment]
我这边清缓存无效, 目前通过修改样式解决了.

```scss
<style lang="scss" scoped>
::v-deep .ant-table-fixed-right, .ant-table-fixed-right table {
  border-radius: 0 4px 0 0;
  height: 100%;

  & .ant-table-body-outer {
    height: 100%;
    & .ant-table-body-inner table {
      height: 100%;
    }
  }
}
</style>
```

![image](https://user-images.githubusercontent.com/10718925/60636553-8b658c00-9e49-11e9-8c86-8a93210cef84.png)

**Comment by tangjinzhou** [comment]
目测样式文件没有加载完成

**Comment by qixin1991** [comment]
@tangjinzhou `F5`刷新了也不行，应该不是样式文件没有加载完成的问题。

**Comment by tangjinzhou** [comment]
我的意思是图表渲染的时候  样式还没加载完成 @qixin1991

**Comment by qixin1991** [comment]
> 我的意思是图表渲染的时候 样式还没加载完成 @qixin1991

有这个可能
