### ISSUE TITLE
The Table component don't support rowClick event and receive params like column's data?

### ISSUE THREAD

**Issue by Kuro-P** [vueComponent/ant-design-vue#834]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
About Table component, when i click row, i want to do sth with current column data;
I found 'customRow: onClick' event in document，but i can't get current column data on click event with params...

### What does the proposed API look like?
The React antDesign UI frame(https://ice.work/component/table): Table -> onRowClick event

**Comment by davidq2q** [comment]
Perhaps you can use slots. Then add record to the slot-scope so you have access to the full record of the iteration.

**Comment by Gavin-Gong** [comment]
use customRow prop
```html
<a-table :customRow="customRow"></a-table>
```
``` javascript
function customRow(record) {
      return {
        on: {
          click: event => {
            console.log(event, record);
          }
        }
      };
    }
```
