### ISSUE TITLE
是否能给 table 增加自动调整列宽?

### ISSUE THREAD

**Issue by x6ud** [vueComponent/ant-design-vue#839]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在的 table 简单地把列宽设在 colgroup 里就不管了, 于是开启固定表头之后特别容易出行列错位
而像隔壁 elementui 则是每 50ms 测一次 tbody 宽度重新算列宽, 于是不用费劲手动调每一列的 width 也不会出行这种错位问题, 表头右边也不会多出一个多余的纵向滚动条才能保持列对齐
类似于 → https://jsfiddle.net/6df5z9ao/ , 不过可能还需加上表头的单元格 overflow hidden

### What does the proposed API look like?
增加一个属性可选开启自动调整列宽

**Comment by obear997** [comment]
同求

**Comment by liuqingchao** [comment]
强烈要求

**Comment by chensimin09** [comment]
@tangjinzhou 
强烈要求，否则在一些有动态列需求的时候，固定列会有重复列出现；
不设定列宽的话，表头和内容就会错位
