### ISSUE TITLE
modal 点击蒙层关闭的事件建议使用单击而不是松开鼠标

### ISSUE THREAD

**Issue by bdoycn** [vueComponent/ant-design-vue#842]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
在选中 modal 中的内容时经常会大范围拖选内容 一单移动到蒙层中松开就会关闭弹窗 建议使用单击事件触发关闭(antd 也是单击事件)

### What does the proposed API look like?
使用单击事件关闭弹窗

**Comment by nickolboy** [comment]
对，误触几率很大，我已经把这个功能关了，但是还是希望有

**Comment by yumyrather** [comment]
似乎是mask的mouseUp事件会触发关闭，antd官方已经修复了这个问题：
https://github.com/react-component/dialog/commit/b4dc00b8ba7f8e988a8f58b0ebca51b2e22915fb
但是antd vue这个问题还存在

**Comment by tangjinzhou** [comment]
1.4.0版本修复   beta版本已发布

**Comment by zhizhongjian1** [comment]
> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 在选中 modal 中的内容时

> * [ ]  I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 在选中 modal 中的内容时经常会大范围拖选内容 一单移动到蒙层中松开就会关闭弹窗 建议使用单击事件触发关闭(antd 也是单击事件)
> 
> ### What does the proposed API look like?
> 使用单击事件关闭弹窗

大佬，请问这个问题怎样解决啊，我也遇到这个问题，现在不知道怎样解决

**Comment by zhizhongjian1** [comment]
> 对，误触几率很大，我已经把这个功能关了，但是还是希望有
大佬，请问这个问题怎样解决的啊，我也遇到这个问题，现在都不知道怎样解决
