### ISSUE TITLE
Carousel无效！！  除了div.ant-carousel 没渲染出任何子节点

### ISSUE THREAD

**Issue by xxbld** [vueComponent/ant-design-vue#845]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q956jn5wvw)

### Steps to reproduce
null

### What is expected?
null

### What is actually happening?
null

**Comment by xxbld** [comment]
好像是按需引入的bug，
import Carousel from 'ant-design-vue/es/carousel'; 
这样引入可以了，但是自定义箭头无效
 // slotScope: {
                        //     prevArrow: (props: any) => {
                        //         return (
                        //             <div class='custom-slick-arrow'
                        //                 style='left: 10px;zIndex: 1'>
                        //                 <Icon type='left-circle' />
                        //             </div>
                        //         );
                        //     },
                        //     nextArrow: (props: any) => {
                        //         return (
                        //             <div class='custom-slick-arrow'
                        //                 style='right: 10px;zIndex: 1'>
                        //                 <Icon type='right-circle' />
                        //             </div>
                        //         );
                        //     }
                        // }

**Comment by monotykamary** [comment]
Carousel works on version 1.3.8; seems like a bug on the newer version.

**Comment by xxbld** [comment]
> Carousel works on version 1.3.8; seems like a bug on the newer version.

agree! 1.3.8 is correct;
1.3.9 treeselect supprot **treeNode.dataRef.children** ,so updated version.
Unfortunately, Carousel not work

**Comment by tangjinzhou** [comment]
Please use import { Carousel } from 'ant-design-vue/es'
We will continue to locate the specific reasons why there is a problem with the files under `lib`.
