### ISSUE TITLE
配置了polyfill后在ie10报错 Set未定义 Iconfont.js(12,1)

### ISSUE THREAD

**Issue by CherishLyx** [vueComponent/ant-design-vue#847]
使用vuecli3搭建的，在babel.config.js中配置了
`module.exports = {
  
  presets: [
    ['@vue/app', {
        useBuiltIns: 'entry'
    }]
  ],
  plugins: [
    [
      "import",
      { libraryName: "ant-design-vue", libraryDirectory: "es", style: true }
    ]
  ]
}`
在main.js中也按照官方文档使用的
`import '@babel/polyfill' 
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import plugins from './utils/plugins'
import {Button} from 'ant-design-vue'

Vue.component(Button.name, Button)
Vue.use(plugins)
Vue.config.productionTip = false
// require('./utils/mock.js')
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount('#app')
`
但是在ie10 依旧报错 SCRIPT5009：“Set”未定义
IcontFont.js(12,1)

**Comment by atmjs** [comment]
@CherishLyx 怎么解决的？

**Comment by 60late** [comment]
@atmjs @CherishLyx 有解决方法吗

**Comment by MGsniper** [comment]
@CherishLyx @atmjs @60late →..→所以你们解决了嘛。我在全局引入的时候是没有问题的，但是一旦按需加载以后，它又出现兼容性问题了。

**Comment by MGsniper** [comment]
兄弟萌，babel按需polyfill我也折腾出来结果，不过全局引入是可以的。配置如下：
注意哈，babel 7+已经废弃@babel/polyfill，直接import core-js就成了。
T-T嘤嘤嘤，IE什么时候能消失，前端冷抖哭
main.js:
`import "core-js";`
babel.config:
`module.exports = {
  presets: [["@vue/cli-plugin-babel/preset", {
    useBuiltIns: "entry",
  }]],
  plugins: [
    [
      "import",
      { libraryName: "ant-design-vue", libraryDirectory: "es", style: true }
    ]
  ]
}`

**Comment by 491134648** [comment]
解决了吗？
