### ISSUE TITLE
求表格增加属性控制，禁止换行，超出显示省略号

### ISSUE THREAD

**Issue by nickolboy** [vueComponent/ant-design-vue#853]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
这个功能挺常用的，希望ad本身支持

### What does the proposed API look like?
nothing

**Comment by Amour1688** [comment]
https://www.antdv.com/components/table-cn/#components-table-demo-ellipsis-column
