### ISSUE TITLE
表格无数据 IE浏览器滚动条遮挡内容

### ISSUE THREAD

**Issue by loioce** [vueComponent/ant-design-vue#857]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
![image](https://user-images.githubusercontent.com/19600939/59413080-6d2fe180-8df1-11e9-86d0-f4c8c8809a75.png)

        
### Version
1.3.10

### Environment
1.3.10

### Reproduction link
[http://暂无线上网址](http://暂无线上网址)

### Steps to reproduce
所发生的

### What is expected?
不遮挡表头，且滚动条在无数据下展示

### What is actually happening?
ie11浏览器，无数据时滚动条在无数据布局上方，遮挡住了表头

**Comment by tangjinzhou** [comment]
可以自行设置高度
