### ISSUE TITLE
Allow scoped slot for Close button on upload component

### ISSUE THREAD

**Issue by sagarrabadiya** [vueComponent/ant-design-vue#859]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Currently I want to use popconfirm button instead of standard close icon for filelist, so user can confirm before deleting file, and currently I can replace the existing close button and its functionality it doesn't allow close button customization.

### What does the proposed API look like?
```vue
<template #closeButton="{remove}">
      <a-popconfirm title="Are you sure delete this task?" @confirm="remove" okText="Yes" cancelText="No">
                  <a href="#">Delete</a>
        </a-popconfirm>
</template>
```

So this template tag suggests to have closeButton or similarly named scope slot which provides remove argument as scoped slots and this way user can customize the ui of close button and when everything is done on confirm of popconfirm I can call the actual remove function exposed via scoped slot.

**Comment by wangxueliang** [comment]
![image](https://user-images.githubusercontent.com/4122593/59484569-e3d9e700-8ea4-11e9-9916-d1ef1fbae882.png)
?

**Comment by sagarrabadiya** [comment]
@wangxueliang I checked docs and this remove is only handler not a customization of ui element which is rendered as close button , this only allows control of the event handler and if the file should be removed or not, but what if I want to change the button itself? I don't want to display `close` as icon instead I want to display solid button so having slot can allow user to dynamically set what the content of close button should be.
