### ISSUE TITLE
table的嵌套子表格出现空白行

### ISSUE THREAD

**Issue by DinoRun** [vueComponent/ant-design-vue#863]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
vue2.5    Chrome75

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-2p3ms)

### Steps to reproduce
在使用嵌套子表格的时候出现;

### What is expected?
在没有子级数据的时候，希望不要出现号及空白行;

### What is actually happening?
在数据没有孩子这个子级数据的时候，出现号;点击加号出现了空白行;

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/vue-antd-template-vww8t
可以通过 rowClassName 来控制

**Comment by DinoRun** [comment]
谢谢唐老师！

**Comment by guxuelong** [comment]
选择框怎么办？选择这个版本要了命了
