### ISSUE TITLE
IE下点击RangePicker会闪一下关闭，openChange执行3次

### ISSUE THREAD

**Issue by YaomiHuang** [vueComponent/ant-design-vue#865]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
windows7,IE10,vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-u58dy)

### Steps to reproduce
使用日历控件，在IE下点击RangePicker展开后马上关闭
发现openChange执行了3次
后添加 placeholder 属性后，该BUG消失，openChange执行一次
请问能告知原因嘛？

### What is expected?
想知道原因。

### What is actually happening?
设置了defaultValue及defaultPickerValue
详情见以上代码

**Comment by sendya** [comment]
经过一系列的排查，暂时定位到的是 本地化 语言导致的，当我切换到 `en_US` 的本地化语言时，这个问题就不存在了。
切换到 `zh_CN 时，又复现了。

有可能是语言化处理的时候丢失了什么字段，目前还不好确定
这个问题还得继续跟踪才能找到真正原因。

**Comment by YaomiHuang** [comment]
> 经过一系列的排查，暂时定位到的是 本地化 语言导致的，当我切换到 `en_US` 的本地化语言时，这个问题就不存在了。
> 切换到 `zh_CN 时，又复现了。
> 
> 有可能是语言化处理的时候丢失了什么字段，目前还不好确定
> 这个问题还得继续跟踪才能找到真正原因。

那添加 placeholder 属性后，该BUG为什么就消失了？
这种BUG的话  我要关闭issue么？

**Comment by tangjinzhou** [comment]
不用关闭，方便进一步跟踪

**Comment by betgar** [comment]
#701 和这个应该是同一类问题

**Comment by betgar** [comment]
RangePicker在ie下有值的情况无法展开的问题，你和我说英文版没问题，我猜测和时间格式有关系，因为es5之前Date.parse行为诡异，而中文和英文版最重要的差异是这个，new Date('2019-01-01')和new Date('2019/01/01')初始化的time是不同的

**Comment by betgar** [comment]
@sendya @tangjinzhou 
我想我找到问题所在了，相关的issues这里提一下 #92， 和 https://github.com/vuejs/vue/issues/7138
![image](https://user-images.githubusercontent.com/15810150/60446042-13ce0c00-9c53-11e9-9149-0f23fa46831a.png)

而且我尝试把placeholder="['', '']"或者在中文模式下placeholder="['left', 'right']"修改为英文，这个bug就不会重现，看caniuse和https://github.com/vuejs/vue/issues/7138 这个属于IE的bug。

**Comment by tangjinzhou** [comment]
可以先把 placeholder 改成英文临时解决下，很快修复上线
