### ISSUE TITLE
table的expandIcon API使用插槽写法时不生效

### ISSUE THREAD

**Issue by DinoRun** [vueComponent/ant-design-vue#866]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
vue2.5    Chrome75

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-hsw6v)

### Steps to reproduce
<a-table :columns="columns" :dataSource="data" rowKey="key">
<a-icon slot="expandIcon" slot-scope="props" :type="[props.expanded ? 'down' :'up']"/>
</a-table>

### What is expected?
修复问题；

### What is actually happening?
table的expandIcon API使用插槽写法时并没有生效；

**Comment by svenjia** [comment]
i have the same question

**Comment by hex1984** [comment]
i have the same question

**Comment by xuminke** [comment]
i have the same question too
