### ISSUE TITLE
浏览器引入方式使用antd，树形控件使用treeData绑定数据渲染组件失败

### ISSUE THREAD

**Issue by wanyukang** [vueComponent/ant-design-vue#878]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
mac, chrome, vue@2.5.17, moment@2.22.1

### Reproduction link
[https://codepen.io/anon/pen/rELJmR?editors=1000](https://codepen.io/anon/pen/rELJmR?editors=1000)

### Steps to reproduce
1. 使用浏览器引入方式使用antd
2. 使用treeData绑定数据，渲染组件失败

### What is expected?
能正常使用treeData描述节点配置

### What is actually happening?
渲染失败，不显示组件

**Comment by tangjinzhou** [comment]
html 中不可以使用自闭和标签

**Comment by wanyukang** [comment]
跟自闭合标签不是同一个问题，`<a-tree :treeData="treeData"></a-tree>`没有渲染的组件是这行 @tangjinzhou

**Comment by tangjinzhou** [comment]
<a-tree :tree-data="treeData"></a-tree>
html中大小写敏感

**Comment by wanyukang** [comment]
懂了，感谢
