### ISSUE TITLE
Update Message and Notification documentation

### ISSUE THREAD

**Issue by rsrogers4** [vueComponent/ant-design-vue#879]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
I could not figure out how to make Message or Notification work until I realized that a) unlike all the other Vue components, Notification and Message need to use lower-case when importing (e.g., `import { message} from "ant-design-vue"`), and that b) setting the `Vue.prototype.$message` and `Vue.prototype.$notification` is mandatory (e.g., `Vue.prototype.$message = message;`).

PS: The same comments apply to modal.

### What does the proposed API look like?
It would be wonderful if the documentation explained these requirements so that beginners can more easily use Message and Notification.

**Comment by tangjinzhou** [comment]
We will improve the documentation. Of course, you can also directly pr.
