### ISSUE TITLE
建议增加 taginput 组件

### ISSUE THREAD

**Issue by shuperry** [vueComponent/ant-design-vue#885]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
快速添加标签，在输入完成后回车直接显示为标签

### What does the proposed API look like?
没有建议

**Comment by tangjinzhou** [comment]
暂不考虑 可以使用 input 和 tag 业务层面结合
