### ISSUE TITLE
级联下拉选择组件增加多选支持

### ISSUE THREAD

**Issue by shuperry** [vueComponent/ant-design-vue#886]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
需要使用级联下拉组件时偶尔需要多选

### What does the proposed API look like?
增加 multiple: true 属性即可，回显时也支持多个同时选中

**Comment by daoying1994** [comment]
i also need that.

**Comment by tangjinzhou** [comment]
不支持  带层级的多选建议使用 TreeSelect。

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/5026

**Comment by jiangxiaoyuboy** [comment]
I also need that
