### ISSUE TITLE
Datepicker组件增加选择年份功能

### ISSUE THREAD

**Issue by WingLL** [vueComponent/ant-design-vue#889]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
**弥补目前日期组件只能选择月，日，时间等功能，增加年份选择功能!**

### What does the proposed API look like?
**通过在Datepicker中设置type为'year'就能实现年份选择，另外一种选择是增加年year-picker组件直接能选择年份！**

**Comment by klniu** [comment]
这个是antd-react中是有mode=‘year'，可以用的，但在vue版本中好像无效

**Comment by Yse7en** [comment]
mode=‘year' 或 year-picker 啥时候能用啊

**Comment by WingLL** [comment]
希望得到大大们的回复！

**Comment by tangjinzhou** [comment]
1.4.0-beta.0 已经支持

**Comment by newlifebegins** [comment]
> 1.4.0-beta.0 已经支持

1.4.0什么时候发布了？

**Comment by leehf** [comment]
> 这个是antd-react中是有mode=‘year'，可以用的，但在vue版本中好像无效

**Comment by zkwolf** [comment]
@tangjinzhou 我之前尝试过用mode="year"来组合，但是其实交互上有点bug

**Comment by tangjinzhou** [comment]
https://github.com/vueComponent/ant-design-vue/blob/master/docs/vue/faq.zh-CN.md#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-datepickerrangepicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD%E6%9C%88%E4%BB%BD

@zkwolf 需要自己进行封装下 😓

**Comment by zkwolf** [comment]
@tangjinzhou 我可以再试试，之前1.4.0刚出的时候我看过这里的文章，按照里面说的试过，年可选，窗口内容也正常，但是好像有个交互上的问题，大概是某些情况下会没选会默认为当年？还有一个当前panel里总有一个是选中状态？然后就放弃了，乖乖用select写了一个

**Comment by zhangmrit** [comment]
> 1.4.0-beta.0 已经支持

react已经添加year-pick,vue什么时候也加一下呗

**Comment by luotingv1** [comment]
还没有支持么....不是1.4.0beat 就有了 现在1.6.2 里面也没有啊  希望 大大有空加一下 year 和季度

**Comment by heroes007** [comment]
a-date-picker中mode = year时，选择后不会关闭日期选择框，展示格式好像也有点问题

**Comment by uniquejava** [comment]
2.0 beta里好像没有找到
