### ISSUE TITLE
input没有清除功能

### ISSUE THREAD

**Issue by xiangyue520** [vueComponent/ant-design-vue#890]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
用户不需要自己去一点点清除,而是点击即可进行清除

### What does the proposed API look like?
新增一个allowClear属性,默认开启,来完成清除功能

**Comment by sendya** [comment]
1.4.x 会提供，具体关注 feat-1.4 分支
