### ISSUE TITLE
@keypress.enter not working on a-input inside a-auto-complete

### ISSUE THREAD

**Issue by JohnDeved** [vueComponent/ant-design-vue#891]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-t5lp6)

### Steps to reproduce
select input and press enter

### What is expected?
@keypress.enter should work like it does with a normal a-input

### What is actually happening?
when you press enter, nothing happens

**Comment by JohnDeved** [comment]
as a workarround @keyup.enter.native works

**Comment by zzxiexin** [comment]
> workaround: @keyup.enter.native works

why i do it by what you said and not use
