### ISSUE TITLE
tree组件的checkedKeys.halfChecked无效

### ISSUE THREAD

**Issue by kotoyo1516** [vueComponent/ant-design-vue#894]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
chrome   vue最新版

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-8qdx1)

### Steps to reproduce
设置checkedKeys.halfChecked为["0-0-0"]

### What is expected?
节点parent 1-0呈现半选状态

### What is actually happening?
节点parent 1-0完全没选中

**Comment by sendya** [comment]
（受控）选中复选框的树节点（注意：父子节点有关联，如果传入父节点key，则子节点自动选中；相应当子节点key都传入，父节点也自动选中。

**当设置 checkable 和 checkStrictly，它是一个有 checked 和 halfChecked 属性的对象，并且父子节点的选中与否不再关联**

> 设置 `halfChecked` 将回导致父节点与子节点不再关联

https://vue.ant.design/components/tree-cn/#Tree-props

**Comment by kotoyo1516** [comment]
我对树的理解出现偏差，感谢回复
