### ISSUE TITLE
图标 Icon-建议scriptUrl支持本地化

### ISSUE THREAD

**Issue by justin107** [vueComponent/ant-design-vue#895]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
实际要求是所有文件本地化，且图标重合度低，自带很少用，要独立引入，直接引入下载到本地的iconfont.js，无法使用antd vue提供的自定义ICON的myicon组件

### What does the proposed API look like?
createFromIconfontCN

**Comment by sendya** [comment]
由于 API 同步 React Ant Design 的缘故，其功能与原版尽量保持了一致。该功能由于官方也未有计划实行，**React Ant Design 给出的回复是 本地 ICON 使用 svg 直接引入，iconfont 是用于网络部署的。**

ref https://github.com/ant-design/ant-design/issues/16480
