### ISSUE TITLE
多页签模式下动态添加标签页

### ISSUE THREAD

**Issue by xiaochaoweb** [vueComponent/ant-design-vue#897]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
没办法动态添加标签页

### What does the proposed API look like?
vue版本

**Comment by sendya** [comment]
是不是发错地方了？如果是 antd pro 请发在对应 repo 。如果是 tabs 组件问题，请描述清楚
