### ISSUE TITLE
tree在异步加载数据后默认展开失效

### ISSUE THREAD

**Issue by DinoRun** [vueComponent/ant-design-vue#898]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
vue2.5    Chrome75

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-hsw6v)

### Steps to reproduce
。。。

### What is expected?
修复autoExpandParent、defaultExpandAll、defaultExpandedKeys、defaultExpandParent API 在异步加载数据后无法正常展开的bug

### What is actually happening?
无法正常展开

**Comment by yandixuan** [comment]
v-if="data.length>0" 试下

**Comment by qingyun1029** [comment]
谢谢帮助！




------------------ 原始邮件 ------------------
发件人: "yandixuan"<notifications@github.com>;
发送时间: 2019年6月22日(星期六) 晚上7:12
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] tree在异步加载数据后默认展开失效 (#898)




v-if="data.length>0" 试下

**Comment by DinoRun** [comment]
谢谢

**Comment by apei830** [comment]
解决了吗？

**Comment by tangjinzhou** [comment]
https://vue.ant.design/docs/vue/faq-cn/#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue,defaultOpenKeys,-initialValue%E7%AD%89defaultXxxx%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by DinoRun** [comment]
> 解决了吗？
用这个API expandedKeys解决了问题；
