### ISSUE TITLE
能不能考虑加个富文本编辑器

### ISSUE THREAD

**Issue by ShiliangLuo** [vueComponent/ant-design-vue#900]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
现在的UI框架没有富文本编辑器，如果用第三方的，风格会不一样

### What does the proposed API look like?
无

**Comment by tangjinzhou** [comment]
暂无计划，可以第三方更改个样式

**Comment by sendya** [comment]
https://github.com/sendya/ant-design-pro-vue/blob/master/src/components/Editor/QuillEditor.vue#L70
