### ISSUE TITLE
Select组件使用校验功能时，Option组件的Key不能为Number类型

### ISSUE THREAD

**Issue by MarbleShin** [vueComponent/ant-design-vue#902]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
系统版本：Windows 10 专业版，1809；浏览器版本：Chrome 74.0.3729.108（正式版本）（64 位）；ant-design-vue版本：v1.3.10，Vue.js版本：v2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-kytf4)

### Steps to reproduce
1. 使用`Select`组件和`Option`组件做成一选择器，`Select`组件加上了校验规则；
2. `Option`组件使用`v-for`的方式加载，`key`和`value`属性均传入`Number类型`数据；
3. 选择`Option`后显示报错，`value`需为`String类型`。
4. 将`value`显式转换为`String类型`或将校验规则删除，报错不出现。

### What is expected?
使用`Select`·和`Option`组件时，`Select`组件有校验规则时，`Option`的`value`可以传入`Number类型`数据。

### What is actually happening?
使用`Select`·和`Option`组件时，`Select`组件有校验规则时，`Option`的`value`传入`Number类型`数据，会导致报错现象。

**Comment by wensonsmith** [comment]
同求，不然还得toString，好麻烦

**Comment by nowdothat** [comment]
看了下 react antd，问题已关闭，不知是否已解决

**Comment by littlebox692** [comment]
> 看了下 react antd，问题已关闭，不知是否已解决

vue版本的并没有解决。

**Comment by yue-fei** [comment]
I spent half of a day, almost crazy...

**Comment by tangjinzhou** [comment]
更新 1.5 + 版本
