### ISSUE TITLE
在弹出框中使用选择器select，撑出滚动条后点击选择器并滚动页面，下拉框定位错误

### ISSUE THREAD

**Issue by loveFemi** [vueComponent/ant-design-vue#905]
步骤：
1. 创建弹出框modal
2. 在弹出框中添加表单，内容足够多时会撑出滚动条
3. 选中表单中的选择器select，显示下拉选项
4. 滚动页面，下拉框定位不会跟随select选择器，而是相对页面定位

另外发现页面触发resize后下拉框会重新定位至正确位置~

可能功能是不是类似于饿了么里面popper-append-to-body

**Comment by hasbug** [comment]
哥们，怎么解决了。API 中  getContainer  不知道是不是用于解决这个的，不知道怎么用

**Comment by loveFemi** [comment]
> 这么解决：在select组件那行添加：:getPopupContainer="trigger => trigger.parentNode"

嗯嗯  就是如果是表单  有好几个select  每个都添加代码有点累赘
