### ISSUE TITLE
input v-bind value can't be update by typing

### ISSUE THREAD

**Issue by mistkafka** [vueComponent/ant-design-vue#907]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-input-value-bind-njjd5)

### Steps to reproduce
https://codesandbox.io/s/vue-antd-input-value-bind-njjd5
As the above demo, a-input can't update the input value by typing.

### What is expected?
I hope a-input can update the value by typing, just like native input element.

### What is actually happening?
--

**Comment by qindj** [comment]
try using v-model

**Comment by mistkafka** [comment]
@qindj I know v-model, **BUT** I expect to change the bind variable value when the user press the "ENTER". I need to change the input element value in two ways:

1. the user typing 
2. bind variable changed, (v-bind:value, not v-model)

And the business logic is a search input:

1.the user typing search keyword, and press "ENTER", do search
2.the user click a recommended search keyword, update the search input value, and do search

**Comment by tangjinzhou** [comment]
v-model=“name”

**Comment by mistkafka** [comment]
hehe
