### ISSUE TITLE
popover 位置异常

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#908]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### Steps to reproduce
同#780 ，但是使用该方法仍然不能解决。

封装了一个图标选择 pop 代码：

![image](https://user-images.githubusercontent.com/2329528/60232602-abd49a00-98cf-11e9-87e8-e09cbb5fc752.png)

![image](https://user-images.githubusercontent.com/2329528/60232649-c6a70e80-98cf-11e9-94de-bd2e31d14847.png)

位置为上下的偏移太厉害，只能使用left,right位置系列才能解决
        
示例：

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-g4h1t?fontsize=14)

**Comment by tangjinzhou** [comment]
给个复现链接？

**Comment by GlodenBoy** [comment]
> 给个复现链接？

@tangjinzhou  多谢回复，已添加示例，辛苦~

**Comment by Yaaawn** [comment]
同遇到此问题
