### ISSUE TITLE
表单控件 updateFields API 文档中没有描述，在“表单数据存储于上层组件”示例中使用了。

### ISSUE THREAD

**Issue by Seven1979** [vueComponent/ant-design-vue#909]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
表单控件 updateFields API 文档中没有描述，在“表单数据存储于上层组件”示例中使用了。
ts代码里要使用这个api，定义文件中没有

### What does the proposed API look like?
如果是公开的api麻烦在文档里补充。

**Comment by NewAwesome** [comment]
Same question. 
Does  "updateFields" means SET a group of fields' value? just like "setFieldsValue" ???
Have you sovled it ? Plz
