### ISSUE TITLE
Select使用dropdownRender在自定义内容上添加一个checkbox控件实现全选，但是checkbox的change事件不触发或者偶尔能触发一次

### ISSUE THREAD

**Issue by AhJane** [vueComponent/ant-design-vue#911]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.7

### Environment
Windows 10, Chrome 73.0.3683.86, Vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/zr757w346x)

### Steps to reproduce

```javascript
<a-select
mode="multiple"
:defaultValue="checkedList"
@change="onChange"
style="width: 500px">
<div slot="dropdownRender" slot-scope="menu">
<div style="padding: 4px 8px; cursor: pointer;">
<a-checkbox
:indeterminate="indeterminate"
@change="onCheckAllChange"
:checked="checkAll"
>全选</a-checkbox>
</div>
<a-divider style="margin: 4px 0 0;" />
<v-nodes :vnodes="menu"/>
</div>
<a-select-option v-for="item in plainOptions" :key="item">{{item}}</a-select-option>
</a-select>
```

### What is expected?
点击checkbox时触发change事件，通过事件的e.target.checked的值实现全选或者取消全选

### What is actually happening?
checkbox事件不触发或者偶尔触发了一次

**Comment by yangj12138** [comment]
windows的吗 windows的 change改成mousedown事件能触发

**Comment by AhJane** [comment]
你好，改成mousedown是能触发，但是拿不到checkbox的checked状态呢

**Comment by yangj12138** [comment]
这个咋也不知道了   我是改成mousedown的时候他只能触发一次  自己怀疑是因为他点击的时候触发了select的关闭那个 可能是优先级更高   后来就自己写了一个下拉多选 没用用他这个了   找的时候react那面的也有这个问题 他们那个思路是在select那给点击阻止掉  但是我是没有试  怕出其他幺蛾子😂

**Comment by tangjinzhou** [comment]
ref https://github.com/ant-design/ant-design/issues/13448

**Comment by Fuxdlyn** [comment]
请问解决了吗？使用dropdownRender，自定义配合[radio、checkbox]的时候，点击[radio、checkbox]的时候，面板会收起，查阅相关，说是在外层添加一个div. @mousedown = e =>e.preventDefault() ，得到的结果是：面板其他地方点击被阻止了，[radio、checkbox]点击文字的时候，面板还是会收起。请问：怎么能真正完全阻止它的默认事件？
