### ISSUE TITLE
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

### ISSUE THREAD

**Issue by wumingstyle** [vueComponent/ant-design-vue#914]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

### Reproduction link
[https://vue.ant.design/components/menu-cn/](https://vue.ant.design/components/menu-cn/)

### Steps to reproduce
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

### What is expected?
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

### What is actually happening?
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

---
单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢

**Comment by tangjinzhou** [comment]
正常传啊  没任何区别  :fn="test(…)"

**Comment by wumingstyle** [comment]
------------------ 原始邮件 ------------------
发件人: "tangjinzhou"<notifications@github.com>;
发送时间: 2019年7月2日(星期二) 上午9:00
收件人: "vueComponent/ant-design-vue"<ant-design-vue@noreply.github.com>;
抄送: "无名"<877500821@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [vueComponent/ant-design-vue] 单页面函数式组件，子页面调用父页面方法，如何向父页面方法参数里边传参数值呢 (#914)




正常传啊  没任何区别  :fn="test(…)"

您好：

父页面这样写：

<template v-for="item in reportList">
  <a-menu-item v-if="!item.children" :key="item.id"  @click="add(item)">
    <span>{{item.name}}</span>
  </a-menu-item>
  <sub-menu v-else :menu-info="item" @click="add(...)" :key="item.id" />
</template>
子页面 
这个子页面里边的item的主键怎么写才能在传到父页面add方法的参数呢？请指教
