### ISSUE TITLE
为何自定义表单组件不能正常与Form合用

### ISSUE THREAD

**Issue by JonChanGit** [vueComponent/ant-design-vue#915]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Microsoft Edge is up to date Version 76.0.152.0 (Official build) dev (64-bit)

### Reproduction link
[https://vue.ant.design/components/form-cn/#components-form-demo-customized-form-controls](https://vue.ant.design/components/form-cn/#components-form-demo-customized-form-controls)

### Steps to reproduce
创建如下自定义表单
```
<script>
/**
   * CustomizedInput
   * @author Jon Chan
   * @date 2019/6/28 15:46
   */
export default {
  name: 'CustomizedInput',
  components: {},
  model: {
    prop: 'value',
    event: 'change'
  },
  props: {
    value: {
      type: [String, Number],
      default () {
        return 's'
      }
    }
  },
  data () {
    const val = this.value
    return {
      stateValue: val || ''
    }
  },
  watch: {
    value (val) {
      console.warn(val)
    }
  },
  computed: {},
  beforeCreate: function () {
  },
  mounted: function () {
  },
  methods: {
    triggerChange (e) {
      this.stateValue = e.target.value
      this.$emit('change', this.stateValue)
    },
    setFieldsValue () {
      console.log('xx')
    }
  },
  render () {
    return (
      <span class="customized-input">
        <a-input
          type="text"
          value={this.stateValue}
          style="width: 63%; margin-right: 2%;"
          placeholder="自定义组件"
          onChange="triggerChange"
        />
        <span style="width: 32%">自定义组件[{this.stateValue}]</span>
      </span>
    )
  }
}
</script>

<style lang="less" scoped>
  .customized-input {
  }
</style>

```
在控制台报错：
```
Warning: `getFieldDecorator` will override `value`, so please don't set `value and v-model` directly and use `setFieldsValue` to set it.     browser.js?e834:49
```
![image](https://user-images.githubusercontent.com/20020550/60331995-6a73e580-99c8-11e9-9e05-65804c4e57f1.png)

### What is expected?
应该要能正常使用不报错才对，看了半天官网没搞懂要怎么使得v-decorator正确控制自定义表单

### What is actually happening?
如上所述

---
希望能给个完整的示例

**Comment by sendya** [comment]
value 不要设置 default

**Comment by sendya** [comment]
正确的示例在官网已经有，https://vue.ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by tangjinzhou** [comment]
这个有待优化，理想状态下default应该可以有
