### ISSUE TITLE
建议table组件增加一个本页合计/统计的功能

### ISSUE THREAD

**Issue by wjxjasin** [vueComponent/ant-design-vue#917]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
很多ui框架的table表格都有合计的功能，很多需求会要求加上合计的功能。可以方便开发者调用使用该功能。

### What does the proposed API look like?
Windows10 ，谷歌最新版浏览器，antd版本1.3.10

**Comment by xiejunping** [comment]
支持，没有合计功能，其他功能比别的UI框架都好用一些

**Comment by LiuSuY** [comment]
1.4.11 这个版本上 目前有什么好的方法实现呢？

**Comment by zkwolf** [comment]
https://codesandbox.io/s/vue-antd-biaogemoweiheji-qfoqv?file=/src/App.vue   固定宽度的话可以自定义footer用table来模拟一下，不固定宽度的暂时没有啥想法
