### ISSUE TITLE
ant-modal-body的padding修改不生效

### ISSUE THREAD

**Issue by aleiliuwei** [vueComponent/ant-design-vue#919]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.8

### Environment
win10 chrom  vue版本2.5

### Reproduction link
[https://github.com/vueComponent/ant-design-vue](https://github.com/vueComponent/ant-design-vue)

### Steps to reproduce
vue组件的style 中 修改a-modal组件的ant-modal-body的padding 不生效，发现在vue的页面中去掉scope可以生效，但是我不想全局修改，
代码如下：
<style scoped>
.ant-modal-body { padding: 0 2px 0 1px !important; }
</style>

这段话没有生效不知道为什么，是否可以解答下怎么解决这个问题呢？

### What is expected?
<style scoped>
.ant-modal-body { padding: 0 2px 0 1px !important; }
</style>
可以在单个vue组件内修改modal组件的padding

### What is actually happening?
修改了ant-modal-body样式没有任何作用

---
我有一个弹出框使用了modal组件，希望能够去掉padding

**Comment by sendya** [comment]
请查阅 Vue 组件样式穿透

附：[组件样式覆盖.md](https://github.com/kokoroli/antd-awesome/blob/master/docs/%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E8%A6%86%E7%9B%96.md)
