### ISSUE TITLE
ie 11 下，表单校验功能，input 的 placeholder 如果包含中文，则自动校验

### ISSUE THREAD

**Issue by weifu2** [vueComponent/ant-design-vue#92]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
ie11

### Reproduction link
[https://codesandbox.io/s/v3x3q9mjwl](https://codesandbox.io/s/v3x3q9mjwl)

### Steps to reproduce
官网表单的任意示例，把 input 的 placeholder 改成中文， 在 ie 11 下运行

### What is expected?
操作以后再校验

### What is actually happening?
无任何操作，自动校验

**Comment by tangjinzhou** [comment]
这是ie的bug，vue已经在做兼容，看[PR状态](https://github.com/vuejs/vue/pull/8140)应该很快就会修复 

组件库暂时就不在做临时兼容了

**Comment by tangjinzhou** [comment]
update to 1.0.3
