### ISSUE TITLE
layout 官方文档示例问题

### ISSUE THREAD

**Issue by skybabydad** [vueComponent/ant-design-vue#920]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
chrome

### Reproduction link
[https://blog.csdn.net/atlasun/article/details/94380271](https://blog.csdn.net/atlasun/article/details/94380271)

### Steps to reproduce
https://blog.csdn.net/atlasun/article/details/94380271

### What is expected?
https://blog.csdn.net/atlasun/article/details/94380271

### What is actually happening?
https://blog.csdn.net/atlasun/article/details/94380271

---
希望文档更具指导性

**Comment by sendya** [comment]
Demo 提供了非常多的代码，请细心一点
![image](https://user-images.githubusercontent.com/5404542/60427598-980b9980-9c29-11e9-9aae-4626568890b8.png)

https://vue.ant.design/components/layout-cn/#components-layout-demo-basic-structure

**Comment by tangjinzhou** [comment]
需要更加仔细阅读文档

**Comment by skybabydad** [comment]
所以我的提议是“希望文档更具指导性”，如果楼上各位一定认为“<>”这样一个不起眼的代码切换图标就代表具备指导性和友好了，那我无语。
![image](https://user-images.githubusercontent.com/13517500/60475794-a4383b00-9cab-11e9-9cb3-5ec7229cff26.png)

**Comment by sendya** [comment]
@skybabydad 你可以去参考 iview, element ui  也是相同做法，而且这个做法非常通用
