### ISSUE TITLE
a-tree-select固定之后的问题

### ISSUE THREAD

**Issue by YaomiHuang** [vueComponent/ant-design-vue#922]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
windows7,google,vue2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-4i6vg?fontsize=14)

### Steps to reproduce
固定a-tree-select在顶部之后，出现2个问题
1、a-tree-select固定在顶部后，滑动页面在中间区域点击下拉框，出现的下拉选项没有随下拉框滚动（a-tree-select，a-select都有该问题）
2、滑动到下面黄色区域点击下拉框，页面直接回滚动到顶部（a-select没有该问题）
操作：红色区域点击显示下拉框后，页面下拉到黄色区域，点击显示下拉框，再上下滑动
期望：滚动到页面下面区域时，点击下拉就在该区域显示

### What is expected?
准备在页面滚动的时候，关闭/隐藏下拉选项：
看到有open属性，但所有事件操作都要去就改open属性；
看到有Select Methods   blur()，但是它只取消焦点，并不会关闭下拉选项；
直接JS修改display:none隐藏下拉选项，但是选项框处于打开状态，再次打开前，需要先点击关闭再点击才会是打开；
准备直接监听滚动，然后click（）下拉按钮，但是没法判断下拉选项展开关闭状态

### What is actually happening?
T T求解决方案。。

**Comment by tangjinzhou** [comment]
https://vue.ant.design/docs/vue/faq-cn/#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F

**Comment by YaomiHuang** [comment]
谢谢！！！
Select Dropdown DatePicker TimePicker Popover Popconfirm 会跟随滚动条上下移动？
使用 <a-select :getPopupContainer="trigger => trigger.parentNode"> 来将组件渲染到滚动区域内，或者使用其他的 getXxxxContainer 参数。
