### ISSUE TITLE
vue cli 3 使用 ant-design-vue 按需加载，定制样式 发现首页logo渲染会很慢，晚于<HelloWorld>

### ISSUE THREAD

**Issue by Lpbzzz** [vueComponent/ant-design-vue#927]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
chrome 75.0.3770.100（正式版本） （64 位）

### Reproduction link
[http://null](http://null)

### Steps to reproduce
1.初始化vue cli 3.0 ，此时在cli 里来回切换 首页和about 不会有任何迟滞
2.按需加载 （babel-plugin-import）并且定制了样式
3.此时在 首页和about页面来回切换 就会发现：首页中的logo图总是慢于<HelloWorld>渲染，先出现了HelloWorld中的内容，然后HelloWorld再向下移动，出现了log图

### What is expected?
应该是没有任何延迟的，首页上所有的元素一起出现

### What is actually happening?
logo图总是慢于<HelloWorld>渲染

**Comment by sendya** [comment]
请使用 codesandbox 提供复现用例

**Comment by tangjinzhou** [comment]
这个问题我很方 毫无头绪

**Comment by Lpbzzz** [comment]
> 这个问题我很方 毫无头绪

其实我也不知道这算不算问题。

**Comment by tangjinzhou** [comment]
好像知道你说的啥了，图片加载需要时间，你又没给图片设置高度，必然会出现你描述的现象 😓
