### ISSUE TITLE
use getFieldDecorator in jsx report an error (TypeError: Cannot read property 'value' of undefined)

### ISSUE THREAD

**Issue by drafish** [vueComponent/ant-design-vue#930]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
os version: macos 10.14.5、browser version: chrome75.0.3770.100、vue version: ^2.6.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-f977u)

### Steps to reproduce
use getFieldDecorator in jsx  like this
<FormItem>
{getFieldDecorator(name, options)(
<Input size="large" placeholder="用户名" />
)}
</FormItem>

### What is expected?
render FormItem

### What is actually happening?
report an error (TypeError: Cannot read property 'value' of undefined) and cannot render FormItem

**Comment by tangjinzhou** [comment]
如果用jsx的，form可以使用react 的方式，不需要传递 form={this.form}

**Comment by drafish** [comment]
> 如果用jsx的，form可以使用react 的方式，不需要传递 form={this.form}

谢谢唐老师指出错误，复现用例和ant-design-vue-pro中的Login组件中的form={this.form}我已经都删掉了。顺便夸一句，唐老师的办事效率好高啊，我这pr提了还没两天就处理了。element那边我也提了个pr，三个多月了还没处理。顺便再问下，这个issue是不是可以close掉了

**Comment by tangjinzhou** [comment]
关掉吧
