### ISSUE TITLE
在分离 layout 时，会将 content header 都渲染成 footer

### ISSUE THREAD

**Issue by MaleDeer** [vueComponent/ant-design-vue#933]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Win10，Chrome 75.0 ，Vue CLI 3

### Reproduction link
[https://github.com/MaleDeer/vue-ant.git](https://github.com/MaleDeer/vue-ant.git)

### Steps to reproduce
克隆代码 https://github.com/MaleDeer/vue-ant.git
启动起来以后，

可以在 App.vue 中发现我将 header，content，footer 重新封装了一层。
但是在启动以后 会出现三个 footer  而不是 header，content，footer

### What is expected?
希望可能实现在布局中能够进行 herader，content，footer 再次封装一层。

### What is actually happening?
布局分离时，出现重复渲染。

**Comment by MaleDeer** [comment]
我发现 layout 布局有很严重的bug，a-layout-content 和 a-layout-header 在同一层 a-layout-header 的内容也会被 渲染成 a-layout-content  的内容。

**Comment by MaleDeer** [comment]
我想将 布局分离成 4个不同 .vue 文件，会出现 内容渲染有很严重的问题，

**Comment by tangjinzhou** [comment]
你给的代码是正常的啊
![image](https://user-images.githubusercontent.com/6937879/63145688-f8646800-c02a-11e9-9d17-d9b7ce1a0642.png)

**Comment by MaleDeer** [comment]
> 你给的代码是正常的啊
> ![image](https://user-images.githubusercontent.com/6937879/63145688-f8646800-c02a-11e9-9d17-d9b7ce1a0642.png)

很久以前了，当时写了以后用 左右结构的时候，右边的  页头 中部 页尾 都会渲染成野味。后来重新引入新版本，就可以了。
