### ISSUE TITLE
table的rowSelection的selectedRowKeys无效，getCheckboxProps里更改disabled或checked的值无效

### ISSUE THREAD

**Issue by hackerkingql** [vueComponent/ant-design-vue#935]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
vue-cli3.0 ant-design-vue1.3.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-ilz2n)

### Steps to reproduce
rowSelection写了selectedRowKeys页面上就没有选中效果，selectedRowKeys为[]不起作用，

### What is expected?
要实现类似React版本的：https://codesandbox.io/embed/vigilant-kepler-d0is6这个效果，getCheckboxProps里更改disabled或checked的设置为变量时变量的值更改后不起作用

### What is actually happening?
缺乏完善

**Comment by hackerkingql** [comment]
@tangjinzhou

**Comment by tangjinzhou** [comment]
😓 可以参考官网demo
https://codesandbox.io/embed/vue-template-ilz2n

**Comment by luotingv1** [comment]
> 😓 可以参考官网demo
> https://codesandbox.io/embed/vue-template-ilz2n
我并不认为你这样是动态修改getCheckboxProps里更改disabled或checked  你只是把rowselection 置空
如我demo 并不能动态修改getCheckboxProps属性 只能在table上面修改key值
https://codesandbox.io/embed/vue-template-mlxni

**Comment by sendya** [comment]
> 如我demo 并不能动态修改getCheckboxProps属性 只能在table上面修改key值
> https://codesandbox.io/embed/vue-template-mlxni

https://codesandbox.io/embed/vue-template-yg66u

没什么毛病

**Comment by tangjinzhou** [comment]
```html
<template>
  <div>
    <div style="margin:20px;">
      <a-button type="primary" @click="startShow" :disabled="isShow">显示checkbox</a-button>&nbsp;
      <a-button type="primary" @click="endShow" :disabled="!isShow">清除已选中的checkbox后不显示checkbox</a-button>
      <span style="margin-left: 8px">
        <template v-if="hasSelected">{{`Selected ${selectedRowKeys.length} items`}}</template>
      </span>
    </div>
    <a-table :rowSelection="rowSelection" rowKey="id" :columns="columns" :dataSource="data" />
  </div>
</template>
<script>
const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
  },
  {
    title: 'Age',
    dataIndex: 'age',
  },
  {
    title: 'Address',
    dataIndex: 'address',
  },
];

const data = [];
for (let i = 0; i < 46; i++) {
  data.push({
    key: i,
    id: i,
    name: `Edward King ${i}`,
    age: 32,
    address: `London, Park Lane no. ${i}`,
  });
}

export default {
  data() {
    return {
      data,
      columns,
      selectedRowKeys: [], // Check here to configure the default column
      loading: false,
      isShow: false,
    };
  },
  computed: {
    hasSelected() {
      return this.selectedRowKeys.length > 0;
    },
    rowSelection() {
      const { selectedRowKeys } = this;
      return this.isShow
        ? {
            selectedRowKeys: selectedRowKeys,
            onChange: selectedRowKeys => {
              this.selectedRowKeys = selectedRowKeys;
            },
            getCheckboxProps: record => {
              return {
                props: {
                  checked: selectedRowKeys.includes(record.id),
                  disabled: !this.isShow,
                },
              };
            },
          }
        : undefined;
    },
  },
  methods: {
    startShow() {
      let self = this;
      self.isShow = true;
    },
    endShow() {
      this.selectedRowKeys = [];
      setTimeout(() => {
        this.isShow = false;
      }, 1000);
    },
  },
};
</script>

```

**Comment by DreFalPoetry** [comment]
![image](https://user-images.githubusercontent.com/21257916/76073878-4e075e80-5fd5-11ea-9c00-917e7bdae5f6.png)
像是这样的问题 无法得到解决

**Comment by xuminke** [comment]
@sendya 感谢，不过我又一个疑惑，如果不是根据record内部的某个值来动态改变checkbox的状态，为什么就不能够起作用呢？比如一个外层的data attr？

**Comment by glxe** [comment]
折腾了大半天，终于搞定自己想要的效果了。nice
