### ISSUE TITLE
form validator验证后，错误提示出现多个

### ISSUE THREAD

**Issue by Li-saltair** [vueComponent/ant-design-vue#942]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
win 10 x64 chrome 版本 75.0.3770.100 vue版本：2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-8wx17)

### Steps to reproduce
点击“提交”进行表单的验证

### What is expected?
对验证优先级进行说明

### What is actually happening?
在点击提交进行验证之后，第二个字段同时验证required和一个自定义validator会出现两个验证的提示信息，但是第一个字段同时验证type和required却不会出现这种情况，请问是否有验证信息提示的优先级一类的设置？还是只能在自定义设置里面单独进行空值的验证并返回无用的类似callback("")的验证？

**Comment by tangjinzhou** [comment]
`validateFirst: true,`

https://codesandbox.io/s/vue-template-gxmvm
