### ISSUE TITLE
表单获取日期组件值的格式需求

### ISSUE THREAD

**Issue by cyshigehaohaizi** [vueComponent/ant-design-vue#944]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
win10,ie

### Reproduction link
[https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-customized-range-picker](https://vue.ant.design/components/date-picker-cn/#components-date-picker-demo-customized-range-picker)

### Steps to reproduce
this.form.getFieldsValue()

### What is expected?
日期字符串

### What is actually happening?
moment格式的日期

---
日期组件建议,使用form.getFieldsValue方法获取到的值是moment格式的,要提交的话 要全部按照格式全部手动转一次,如果一个页面时间选择比较多的话,全部一个个转,特别麻烦,使用form.getFieldsValue 获取值的时候能否获取到直接的日期字符串而不是moment格式哦

**Comment by 53caiyu** [comment]
我也需求~~

**Comment by jessonxiang** [comment]
同样需求 希望,能初始化的时候值也是字符串方式,值也是字符串方式,现在这种情况跟后台交互都必须转换之后才能提交
