### ISSUE TITLE
菜单组件a-menu中,mode inline是inlineCollapsed=true不能合并

### ISSUE THREAD

**Issue by YingZzz** [vueComponent/ant-design-vue#949]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9
### Environment
2

### Reproduction link
[https://vue.ant.design/components/menu-cn/#API](https://vue.ant.design/components/menu-cn/#API)

### Steps to reproduce
```
<template>
    <div>
        <a-menu
            mode="inline"
            theme='dark'
            :defaultSelectedKeys="['1.1']"
            :defaultOpenKeys="['1']"
            :selectedKeys="currentPath"
            :openKeys="currentGroup"
            :inlineCollapsed="closeNav"
            @select="MenuItem"
            @openChange="onOpenChange"
        >
            <template v-for="item in routeData">
                <sub-menu v-if="item.childMenus.length > 0" :menu-info="item" :key="item.menuKey"/>
                <a-menu-item v-else :key="item.menuKey">
                    <a-icon v-if="item.icon" :type="item.icon"/>
                    <span>{{item.menuName}}</span>
                </a-menu-item>
            </template>
        </a-menu>
    </div>
</template>
```

- subMenu
```
<template>
    <a-sub-menu :key="menuInfo.menuKey" v-bind="$props" v-on="$listeners">
        <span slot="title">
            <a-icon v-if="menuInfo.icon" :type="menuInfo.icon"/>
            <span>{{menuInfo.menuName}}</span>
        </span>
        <template v-for="item in menuInfo.childMenus">
            <a-menu-item v-if="!item.childMenus.length > 0" :key="item.menuKey">
                <a-icon v-if="item.icon" :type="item.icon"/>
                <span>{{item.menuName}}</span>
            </a-menu-item>
            <sub-menu v-else :menu-info="item" :key="item.menuKey"/>
        </template>
    </a-sub-menu>
</template>
```

![image](https://user-images.githubusercontent.com/41365103/60946976-15b66000-a322-11e9-8533-c2848b6a2cd5.png)

### What is expected?
可以合并

### What is actually happening?
目前不能合并

- 代码目前复现不出来...因为放code上也是可以合并的..不知道问题出在哪里

**Comment by gadzan** [comment]
我估计你想说的是把侧边的宽菜单（显示图标加标题）变成窄菜单（只显示图标）的功能，如果是这样的话，文档说的不清不楚，我也翻了半天，其实需要是在menu的上级组件a-layout-sider里设置collapsible这个属性。

**Comment by sendya** [comment]
不能合并如果不能复现，能提供不能合并的时候界面是什么样的截图吗？

----

> 我估计你想说的是把侧边的宽菜单（显示图标加标题）变成窄菜单（只显示图标）的功能，如果是这样的话，文档说的不清不楚，我也翻了半天，其实需要是在menu的上级组件a-layout-sider里设置collapsible这个属性。

不放在 `a-layout-side` 也是可以的噢！demo: https://codesandbox.io/s/vue-antd-template-f8rbi

**Comment by seafronthu** [comment]
我今天试了下 当menu 放在组件layout-sider里面的时候需要配置组件的collapsed和collapsible的这两个属性，否则menu不会不会收起
