### ISSUE TITLE
在1.3.10中select组件扩展菜单无法监听事件

### ISSUE THREAD

**Issue by rat1991** [vueComponent/ant-design-vue#950]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
vue^2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-rxk3m)

### Steps to reproduce
在select组件添加扩展菜单，并监听扩展菜单中元素的click事件，触发click事件

### What is expected?
能监听到扩展菜单中元素的事件

### What is actually happening?
无法监听扩展菜单中元素的事件，下拉菜单自动收起

---
该问题在1.3.10出现，在之前1.3.8版本中没有问题

**Comment by yandixuan** [comment]
+1 刚好也用到了扩展菜单，遇到了相同的问题。

**Comment by sendya** [comment]
@rat1991 @yandixuan 
暂时未找到为什么不能触发 `onClick` 事件，但我可以为你提供临时的解决方案。
具体就是先用 `@mousedown.stop="handleClick"` 代替 `@click`，可看下方 demo

[![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/vue-antd-template-til1x)

**Comment by CiroMzy** [comment]
@sendya 谢谢。
