### ISSUE TITLE
table 列固定到左边，列内容太长不换行

### ISSUE THREAD

**Issue by NullXin** [vueComponent/ant-design-vue#951]
![image](https://user-images.githubusercontent.com/28614130/60951278-61b9d280-a32b-11e9-871c-e9a400c062d1.png)

**Comment by kangning1206** [comment]
这种测试本身是不合理的，内容超长，应该使用正常文本做列子，而不是连续的数字（是一个整体），默认连续的数字是不断词的，如果出现断词，那么是两个数字还是一个数字呢？
