### ISSUE TITLE
Affix 初进入页面时, affix会跑出容器,如果页面不滚动或者不刷新,再次来回切换也不会出来..

### ISSUE THREAD

**Issue by YingZzz** [vueComponent/ant-design-vue#952]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
vue

### Reproduction link
[https://vue.ant.design/components/affix-cn/](https://vue.ant.design/components/affix-cn/)

### Steps to reproduce
```
<template>
<a-affix :offsetTop="this.top">
    <div class="sysTree2">
        <div class="company_name">{{treeData ? treeData.menuName : ''}}</div>
        <a-tree
            defaultExpandAll
			autoExpandParent
			v-if="treeData.length"
            class="sysTree"
            :showLine="!checkable"
            :selectedKeys="selectedKeys"
            :treeData="treeData"
            :checkable="checkable"
            @select="onSelect"
        />
    </div>
</a-affix>
</template>
```
![image](https://user-images.githubusercontent.com/41365103/60954857-48685480-a332-11e9-9c6c-10fbf1cb0df1.png)

![image](https://user-images.githubusercontent.com/41365103/60954916-67ff7d00-a332-11e9-9ccd-4e8050a43580.png)

### What is expected?
初始的时候,该在哪在哪

### What is actually happening?
初始的时候,该在哪在哪

**Comment by emila-github** [comment]
也出现该问题，浮动后进行路由切换， 其他页面的该组件出现偏移并且 width: 0px;
    height: 0px;
