### ISSUE TITLE
table中 放置 可编辑的 input-number。通过 v-model、value绑定之后，不能修改

### ISSUE THREAD

**Issue by he0xff** [vueComponent/ant-design-vue#956]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.9

### Environment
chrome  75.0.3770.100

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/665 和 https://github.com/vueComponent/ant-design-vue/issues/229](https://github.com/vueComponent/ant-design-vue/issues/665 和 https://github.com/vueComponent/ant-design-vue/issues/229)

### Steps to reproduce
加上issue中 同样的问题链接：
（1）https://github.com/vueComponent/ant-design-vue/issues/665
（2）https://github.com/vueComponent/ant-design-vue/issues/229

<a-table-column title="采购量" width="10%" dataIndex="targetGoodsNumber" key="targetGoodsNumber">
<template slot-scope="text, record" >
<a-input-number size="small" :defaultValue="0" @blur="e=> changeTargetGoodsNumber(e, e.target.value, record.barcode)"></a-input-number>
</template>
</a-table-column>

### What is expected?
希望 （1） blur修改，（2）或者change 修改的时候 回调参数 有多个，key和 修改的值

### What is actually happening?
blur值 返回原来 data中的 值，不能改变

**Comment by he0xff** [comment]
问题已找到解决方式

**Comment by littleantsos** [comment]
@he0xff  具体怎么解决的，能提供下解决方案吗？

**Comment by he0xff** [comment]
我是表格中嵌套number框，不直接绑定属性值，而绑定text，然后通过事件触发去更新值。你可以借鉴下，看是否符合你的软件需求

littleantsos <notifications@github.com> 于 2019年8月12日 下午3:04写道：


@he0xff<https://github.com/he0xff> 具体怎么解决的，能提供下解决方案吗？

―
