### ISSUE TITLE
cascader级联选择功能的bug

### ISSUE THREAD

**Issue by horsecms** [vueComponent/ant-design-vue#958]
Version
1.3.16
1.4.5

Environment
官网也存在这个问题

Reproduction link
https://vue.ant.design/components/cascader-cn/

Steps to reproduce
cascader级联选择打开搜索功能时：
1、按键盘的上下进行内容选择时需要点击两下才能选中搜索内容的第一条【如输入“h”需要按两下键盘上的“下”键才能定位到第一个搜索结果】；
2、执行完第一步后，搜索框中的没有光标定位，即使按键盘“上”键也无法使光标定位到搜索框中；
3、建议新增“showSearch 为对象时”各个字段的使用方式，想要设置matchInputWidth这个为true，但是不知道应该怎么做:showSearch="{filter,matchInputWidth:true}"这样不对，在data中设置matchInputWidth:true也不对，不知道改如何使用【这个可能是我能力的问题，望大佬指教】

What is expected?
期望能和select的搜索功能相同

What is actually happening?
cascader级联选择打开搜索功能时：
1、按键盘的上下进行内容选择时需要点击两下才能选中搜索内容的第一条；
2、当通过键盘按键选中搜索内容时，搜索框中的没有光标定位，即使按键盘“上”键也无法使光标定位到搜索框中；
3、建议新增“showSearch 为对象时”各个字段的使用方式，想要设置matchInputWidth这个为true，但是不知道应该怎么做:showSearch="{filter,matchInputWidth:true}"这样不对，在data中设置matchInputWidth:true也不对，不知道改如何使用【这个可能是我能力的问题，望大佬指教】

**Comment by BrotherMa** [comment]
@tangjinzhou

**Comment by tangjinzhou** [comment]
一次失去焦点，一次选中
不过发现了新的问题：再次输入时，无法使用上下键盘

**Comment by BrotherMa** [comment]
> 一次失去焦点，一次选中
> 不过发现了新的问题：再次输入时，无法使用上下键盘

建议新增“showSearch 为对象时”各个字段的使用方式，想要设置matchInputWidth这个为true，但是不知道应该怎么做:showSearch="{filter,matchInputWidth:true}"这样不对，在data中设置matchInputWidth:true也不对，不知道改如何使用【这个可能是我能力的问题，望大佬指教】

**Comment by ocxco** [comment]
按键盘的上下进行内容选择时需要点击两下才能选中搜索内容的第一条

请教一下这个问题有计划修复吗，或者可以给出一些建议怎么处理吗
