### ISSUE TITLE
DatePicker默认值ms不起作用

### ISSUE THREAD

**Issue by liuqz** [vueComponent/ant-design-vue#96]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.1

### Environment
vue2.5.16

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
```
<a-date-picker :showTime="{defaultValue: moment({h:0, m:0, s:0, ms:0})}" format="YYYY-MM-DD HH:mm:ss.SSS" />
```

### What is expected?
期望毫秒值为0

### What is actually happening?
毫秒值没有初始化为0

**Comment by tangjinzhou** [comment]
没看明白你具体要干嘛  
麻烦给出详细的复现链接

**Comment by tangjinzhou** [comment]
麻烦给出详细 Reproduction link
还有 什么叫下一次的日期

**Comment by liuqz** [comment]
[link](https://codesandbox.io/s/p92vkmm0j7)

**Comment by liuqz** [comment]
你选同一天看看不就知道了

**Comment by tangjinzhou** [comment]
你的意思是两个日期选择器，毫秒值应该一样咯？

抱歉，我是做不到在同一ms时间选中两个选择器

**Comment by liuqz** [comment]
给你例子是两个，也就是说选中日期相同，时间戳应该相同，你现在不同。

**Comment by liuqz** [comment]
时分秒都能设置相同，为什么毫秒不能设置相同？

**Comment by liuqz** [comment]
你选日期的时候选时分秒了吗？没有，默认设置都是0，怎么毫秒就设置不成0呢？

**Comment by tangjinzhou** [comment]
没选为什么默认值就应该设置成0呢，如果有用户就是想要默认当前时间戳呢  

如果你想设置成0，可以在你业务层面去处理，`moment().format('X')+'000'`
https://codesandbox.io/s/n4pmvvk01j

**Comment by liuqz** [comment]
没选时分秒设置成0是因为 :showTime="{defaultValue: moment({h:0, m:0, s:0, ms:0})}" 这句，所以时分秒都是0，但是ms:0没起作用，毫秒没设置为0

**Comment by liuqz** [comment]
ms:0不是设置毫秒吗?

**Comment by liuqz** [comment]
难道只能:showTime="{defaultValue: moment({h:0, m:0, s:0})}"，只能设置到秒级，不能到毫秒级吗？

**Comment by tangjinzhou** [comment]
暂不支持毫秒
