### ISSUE TITLE
After many components are registered, they are applied to the page without showing

### ISSUE THREAD

**Issue by 1668766306** [vueComponent/ant-design-vue#960]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
VUE

### Reproduction link
[https://vue.ant.design/components/layout/](https://vue.ant.design/components/layout/)

### Steps to reproduce
Introducing import {Layout} from "ant-design-vue" Vue.component into main.js (Layout.name, Layout); uses layout components in the official document to enter the page in App.vue

### What is expected?
Be able to display normal

### What is actually happening?
After many components are registered, they are applied to the page without showing

**Comment by sendya** [comment]
please use `Vue.use(Layout)`
