### ISSUE TITLE
HTML页面 CDN引入CSS，JS后，使用表格时加载数据错误.

### ISSUE THREAD

**Issue by tony2y** [vueComponent/ant-design-vue#965]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
引入的表格组件和实现方式都是按照文档来进行的，但是我在获取到数据后，表格加载数据时却一直显示没有数据。
![image](https://user-images.githubusercontent.com/38598582/61167725-607be600-a575-11e9-976c-d30b51bf974f.png)
![image](https://user-images.githubusercontent.com/38598582/61167727-65409a00-a575-11e9-9713-f699b3fd6cc7.png)
![image](https://user-images.githubusercontent.com/38598582/61167729-696cb780-a575-11e9-9d65-8865b8014427.png)

### What does the proposed API look like?
帮忙看下这是什么原因照成的和怎么解决嘛，自己处理一天了，还是无法解决，谢谢啦！

**Comment by sendya** [comment]
你好，请提供可运行复现代码。例如使用 codesandbox 复现你的问题

**Comment by yurizhang** [comment]
CDN引入以后, DatePicker等时间组件都不能使用了

**Comment by tangjinzhou** [comment]
CDN 引入注意 大小写和标签自闭和问题
