### ISSUE TITLE
校验表单过多时（页面存在大量input和select），页面会很卡

### ISSUE THREAD

**Issue by QifanChan** [vueComponent/ant-design-vue#966]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
希望在最后提交时再做校验，而不是当时

### What does the proposed API look like?
检验时机那个api，仿佛没有起上作用，依旧很卡

**Comment by yi-huan** [comment]
我也发现表单多会卡， 输入等1-2秒才填进去

**Comment by QifanChan** [comment]
所以这个问题怎么解决，没人回复，非要换成react版本吗

**Comment by yi-huan** [comment]
暂时不知道，找找看有没有方案。

**Comment by yi-huan** [comment]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-x76h1)

弄了个例子，但是自己项目的表单数量比这个少，但是输入还比这个还卡点，不知道为何，删删减减 发现少了控件就不卡，也没什么特别的代码

**Comment by QifanChan** [comment]
不能删减需求啊。。。唉，感觉要换框架了。vue天生的不足

**Comment by yi-huan** [comment]
我看了我本地的，不过不是我写的。 
输入框卡顿，下拉的输入不卡，应该是某些绑定事件问题

**Comment by tangjinzhou** [comment]
拆分组件，不管是 react 还是 vue，都柔和在一个组件里，都会有性能问题
你只要输入，就会导致Form所在的组件重新 render

**Comment by yi-huan** [comment]
目前看了官方的例子，好像只有靠自己[自行处理表单数据](https://vue.ant.design/components/form-cn/#components-form-demo-handle-form-data-manually)，而不使用`Form.create`的，不过不要这个自己处理，那么多表单控件 好麻烦。

**Comment by QifanChan** [comment]
是的页面内大量表单的时候会很麻烦

**Comment by tangjinzhou** [comment]
ref #1049

**Comment by Tairy** [comment]
求问，这个问题有解决办法么，我们也遇到了，给元素加了 v-model 属性就变得特别卡。

**Comment by QifanChan** [comment]
很好奇，为什么官网的输入就不卡，我是分析过我的页面里有大量的select，在选择这些后，input输入就会变得很慢

**Comment by zkwolf** [comment]
有试过把Form放到单独组件里去吗，我试了一下，效果好很多

**Comment by nqsjd178559344** [comment]
我也遇见了这个问题....
