### ISSUE TITLE
Cascader :defaultValue默认值不能动态绑定

### ISSUE THREAD

**Issue by heye1109** [vueComponent/ant-design-vue#969]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
ant-design-vue 1.3.10

### Environment
最新，Chrome，vue2.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-template-kvp9u?fontsize=14)

### Steps to reproduce
1、改变switch，就改变对应的options和默认值
2、改变默认值并没有显示，始终只有第一次绑定的值显示，之后改变输入框都是显示为空

### What is expected?
默认值可以动态绑定

### What is actually happening?
改变之后，输入框显示为空

---
现在使用v-model代替defaultvalue显示，可以得到预期效果

**Comment by wangxueliang** [comment]
https://vue.ant.design/docs/vue/faq-cn/
