### ISSUE TITLE
分页器每页显示数量功能，选中样式下拉关闭时显示错误！

### ISSUE THREAD

**Issue by GlodenBoy** [vueComponent/ant-design-vue#970]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
win10,chrome 72.0.3626.119 ,vue 2.x

### What is expected?
官方示例也有这个问题。

如图显示：

![GIF](https://user-images.githubusercontent.com/2329528/61203008-bc806f00-a71b-11e9-88a6-2b40d2ca530f.gif)

当下拉框关闭时 选中的蓝色背景会自动跳转到第一项。

[![Edit antd-vue Temp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-vue-temp-3s7sf?fontsize=14)

**Comment by sendya** [comment]
请使用 codesandbox 进行复现

**Comment by GlodenBoy** [comment]
> 请使用 codesandbox 进行复现

已补充，官方示例 其实就有这个问题。
