### ISSUE TITLE
select options的value propType增加boolean类型

### ISSUE THREAD

**Issue by kotoyo1516** [vueComponent/ant-design-vue#971]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
chrome   vue最新版

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4j1vwzzj50)

### Steps to reproduce
将a-select的options设置为
[{ label: "是", value: true }, { label: "否", value: false }]

### What is expected?
不出现warning

### What is actually happening?
有waring提示：
[VueTypes warn]: oneOfType - value type should be one of "String", "Number", "Array", "Object"

**Comment by qq316107934** [comment]
same problem, expect to be merged

**Comment by tangjinzhou** [comment]
推荐使用 switch 组件
