### ISSUE TITLE
下拉菜单的Cascading menu 闪动

### ISSUE THREAD

**Issue by 767248371** [vueComponent/ant-design-vue#975]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
mac 谷歌

### Reproduction link
[https://ant-design-vue.gitee.io/components/dropdown/#components-dropdown-demo-cascading-menu](https://ant-design-vue.gitee.io/components/dropdown/#components-dropdown-demo-cascading-menu)

### Steps to reproduce
点击官网dropdrown页面，下拉菜单的Cascading menu 闪动

### What is expected?
不闪动

### What is actually happening?
闪动

**Comment by KyLeoHC** [comment]
同样有这个问题。

**Comment by 767248371** [comment]
请求修复
