### ISSUE TITLE
disabled Month of RangePicker

### ISSUE THREAD

**Issue by lronelove** [vueComponent/ant-design-vue#976]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
When I use the components, 'RangePicker', then I choose ['month', 'month'] as the mode. When I choose April as the start month, I cant not choose April as the end month. Maybe you would see, there is no problem. But we often do something in one month, so I would like to choose the same month as the start month and end month. It is better if it can support this featrue. Thanks!

### What does the proposed API look like?
A props which can support this featrue

**Comment by richardsmogodb** [comment]
I found the same sitiuation.
