### ISSUE TITLE
Select 分组就会报错

### ISSUE THREAD

**Issue by yurizhang** [vueComponent/ant-design-vue#977]
![image](https://user-images.githubusercontent.com/20555332/61366776-d0afa200-a8bc-11e9-8e16-d2d50f9b8b2d.png)
使用分组,且分组是循环的时候,不会有问题. 去掉分组就没有问题.
![image](https://user-images.githubusercontent.com/20555332/61366733-bc6ba500-a8bc-11e9-8e60-ddd96215006c.png)

**Comment by zhedream** [comment]
## 找到错误的原因和解决办法了
在 #981 回复了.
