### ISSUE TITLE
响应式设计 新增 visible API

### ISSUE THREAD

**Issue by greenhat616** [vueComponent/ant-design-vue#979]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
参考了 BS 对于响应式元素显示/不可见的类:
https://poychang.github.io/visible-and-hidden-in-bootstrap-4/
https://getbootstrap.com/docs/4.0/utilities/display/
这样可以不必在 less 里使用媒体查询来控制在响应式不同阶段的可见性。

### What does the proposed API look like?
类似这样 :sm={visible: false}
sm -> xl 阶段的元素设置为不可见， 除非另外定义了可见性

**Comment by sendya** [comment]
可以试试使用 `:sm="0"` 代替

**Comment by greenhat616** [comment]
@sendya 谢谢！ 已经解决
