### ISSUE TITLE
Select mode==tag使用分组功能,然后分组用v-for就会报错

### ISSUE THREAD

**Issue by yurizhang** [vueComponent/ant-design-vue#981]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
1.3.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue/issues/977](https://github.com/vueComponent/ant-design-vue/issues/977)

### Steps to reproduce
<a-select
mode="tags"
size="default"

placeholder="Please select Recipients"
style="max-height: 100px;overflow-y:auto"
v-decorator="['recipients', {initialValue: [], rules: [{ required: true, message: 'Please select Recipients' }]} ]"
@change="handleChangeRecipients1"
@select="handleSelectRecipients1"

:filterOption="false"
@search="fetchUser"
:open="open"
:notFoundContent="fetching ? undefined : null"
>
<a-spin v-if="fetching" slot="notFoundContent" size="small"/>

<a-select-option v-for="d in data_s" :key="d">{{d}}</a-select-option>

</a-select>

### What is expected?
fixed

### What is actually happening?
<a-select
mode="tags"
size="default"

placeholder="Please select Recipients"
style="max-height: 100px;overflow-y:auto"
v-decorator="['recipients', {initialValue: [], rules: [{ required: true, message: 'Please select Recipients' }]} ]"
@change="handleChangeRecipients1"
@select="handleSelectRecipients1"

:filterOption="false"
@search="fetchUser"
:open="open"
:notFoundContent="fetching ? undefined : null"
>
<a-spin v-if="fetching" slot="notFoundContent" size="small"/>

**Comment by yurizhang** [comment]
![image](https://user-images.githubusercontent.com/20555332/61426341-b32a1900-a94c-11e9-9b8d-7d0a93d043ea.png)

使用分组,且分组是循环的时候, 就会产生vue warning. 去掉分组就没有问题.
![image](https://user-images.githubusercontent.com/20555332/61426350-b9b89080-a94c-11e9-8aa6-b4f21a89021b.png)

**Comment by sendya** [comment]
请问可以提供完整的复现例子吗？ 否则无法复现你描述的问题

**Comment by yurizhang** [comment]
```
<a-select
            mode="tags"
            size="default"
            placeholder="Please select Recipients"
            style="max-height: 100px;overflow-y:auto"            
            v-decorator="['recipients', {initialValue: [], rules: [{ required: true, message: 'Please select Recipients' }]} ]"
            @change="handleChangeRecipients1"
            @select="handleSelectRecipients1"

            :filterOption="false"
            @search="fetchUser"
            :open="open"
            :notFoundContent="fetching ? undefined : null"
          >
            <a-spin v-if="fetching" slot="notFoundContent" size="small"/>
            
            <a-select-opt-group label="From account list">
                <a-select-option v-for="d in data_s" :key="d">{{d}}</a-select-option>
            </a-select-opt-group> 
           


         <a-select-opt-group label="From AD">
                <span slot="label"><a-icon type="user"/>From AD</span>
                 <a-select-option v-for="d in data_s" :key="d+'--'">{{d+'--'}}</a-select-option>
            </a-select-opt-group>
          </a-select>```

**Comment by ycw01** [comment]
我碰到了相同的问题，大神怎么解决的？

**Comment by zhedream** [comment]
我也遇到类似的错误.
使用的远程搜索 和 分组的功能的时候 , 出现了错误
https://antdv.com/components/select-cn/#components-select-demo-search-and-select-users (搜索用户) 
https://antdv.com/components/select-cn/#components-select-demo-option-group (分组)


我想配合 OptGroup 分组展示.
将OptGroup的代码,手动写在代码里(没有v-for), 是正常的
出现的场景: 
但是 配合 `v-for `后, `进行搜索完成后`. 就出现错误提示了.
不过幸运的是程序还能进行. 但是总是不完美的


```html
<a-select
mode="multiple"
:value="value"
labelInValue
placeholder="请选择"
style="width: 100%"
:filterOption="false"
@search="SearchChartList"
@change="handleChange"
:notFoundContent="fetching ? undefined : null"
>
    <a-spin v-if="fetching" slot="notFoundContent" size="small" />
    <!--  1. 正常的 -->
    <a-select-option v-for="d in data.Test" :key="d.ChartID">{{d.Name}}</a-select-option>
    <!-- 2. 也正常 -->
    <a-select-opt-group>
        <span slot="label"><a-icon type="user" />Manager</span>
        <a-select-option value="jack">Jack</a-select-option>
        <a-select-option value="lucy">Lucy</a-select-option>
    </a-select-opt-group>
    <a-select-opt-group label="Engineer">
        <a-select-option value="Yiminghe">yiminghe</a-select-option>
    </a-select-opt-group>
        <!-- 3. 报错额 -->
    <a-select-opt-group label="Engineer">
        <a-select-option v-for="d in data.Test" :key="d.ChartID">{{d.Name}}</a-select-option>
    </a-select-opt-group>
</a-select>
```

```js

   SearchChartList(e) {
      const search = e
        .split(" ") // 分词
        .filter(e => e) // 去假
        .slice(0, 2) // 限制 2 个
        .join(",");
      console.log("search Params", search);
      let params = { search };
      // let params = { search: "测试3,2020-02-28" };
      this.lastFetchId += 1;
      const fetchId = this.lastFetchId;
      this.data = [];
      this.fetching = true;
      SearchChartList(params).then(({ data }) => {
        if (fetchId !== this.lastFetchId) {
          // for fetch callback order
          return;
        }
        // let { Test, Formal } = data.data;
        console.log(111);
        console.log(111);
        this.fetching = false;
        this.data = data.data; // 因该到这里的是后出现的错误
        console.log(222);
        console.log(222);
      });
    },

```
![image](https://user-images.githubusercontent.com/32092082/75692609-c40f7b00-5ce0-11ea-9a1f-568476f1fa81.png)

**Comment by tangjinzhou** [comment]
抱歉，未能复现，请提供完整有效可运行的demo
完整有效可运行 完整有效可运行 完整有效可运行

**Comment by zhedream** [comment]
## 找到错误的原因和解决办法了

```html

</a-select-opt-group>
<!-- 异常报错 -->
<a-select-opt-group label="测试图谱">
  <a-select-option v-for="d in data.Test" :value="d.ChartID" :key="d.ChartID">{{d.Name}}</a-select-option>
</a-select-opt-group>
```


data.Test 是异步的, 就存在为空的情况, 没有 a-select-option 就会导致错误

```html
<!-- 这是导致 程序异常的原因 -->
<a-select-opt-group label="测试图谱">
</a-select-opt-group>
```

所以我们判断 data.Test 是否空,  使用 v-if 来进行控制 a-select-opt-group 是否渲染即可.

```html
<!-- 正确运行 -->
<a-select-opt-group v-if="data.Test.length>0" label="测试图谱">
  <a-select-option v-for="d in data.Test" :value="d.ChartID" :key="d.ChartID">{{d.Name}}</a-select-option>
```
