### ISSUE TITLE
Nested menu exception  TypeError: "child.componentOptions is undefined"

### ISSUE THREAD

**Issue by LeoQuote** [vueComponent/ant-design-vue#988]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Firefox 68.0 vue 2.5.17

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/vue-antd-template-enbgf)

### Steps to reproduce
I created a nested menu using the code given by document https://vue.ant.design/components/menu/#Single-file-recursive-menu
but it seems not working

### What is expected?
A menu shows

### What is actually happening?
nothing shows
exception: TypeError: "child.componentOptions is undefined"

---
~~I deleted the "key" in the menu list , using the name as key. I think it would be fine for vue~~
I added "key" property for each item , but the expecetion is still there.

**Comment by LeoQuote** [comment]
Could be associated with #604

**Comment by sendya** [comment]
`import SubMenu from ''` not `import { SubMenu } from ''`

**Comment by LeoQuote** [comment]
resolved

**Comment by hsl727261250** [comment]
解决方法无效.
