### ISSUE TITLE
badge offset属性不生效

### ISSUE THREAD

**Issue by nabaonan** [vueComponent/ant-design-vue#99]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.0.2

### Environment
windows10  chrome67.0.3396.99  vue2.5.16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xvlr0lq65p)

### Steps to reproduce
设置badge  offset属性，偏移不生效

### What is expected?
偏移生效，设置x，y偏移多少就相对元素偏移多少

### What is actually happening?
设置x，y偏移量，badge就是不移动

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/6vzq1lrj7k
使用字符串替代，下个版本会对数字进行兼容
