### ISSUE TITLE
表单最后提交时使用validateFields一直处于pending状态，拿不到值是为什么呢？？

### ISSUE THREAD

**Issue by wen-haoming** [vueComponent/ant-design-vue#990]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://ant-design-vue.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by wen-haoming** [comment]
真的好急求回答

**Comment by sendya** [comment]
请通过 issue 助手创建，或者详细说明你的环境。什么环境都不说，再急都得不到答复
