### ISSUE TITLE
按需引用全局引入之后Modal等挂载api不能使用

### ISSUE THREAD

**Issue by CheiZhei** [vueComponent/ant-design-vue#992]
比如我全局注册了Modal组件。调用this.$confirm报错。请问是这样注册不行吗？

**Comment by Syntax-J** [comment]
```javascript
import { Modal } from 'ant-design-vue'
Vue.prototype.$confirm = Modal.confirm
```

**Comment by rurounibatousai** [comment]
> ```js
> import Vue from 'vue'
> import { Modal } from 'ant-design-vue'
> Vue.prototype.$confirm = Modal.confirm
> ```
> 
> > https://ant.design/components/modal-cn/
> > 另外当需要一个简洁的确认框询问用户时，可以使用 Modal.confirm() 等语法糖方法。

3q so much!

**Comment by hueralin** [comment]
Modal.confirm 也不行，报以下错误：

[Vue warn]: Error in nextTick: "TypeError: Cannot create property 'isRootInsert' on string 'Do you Want to delete these items?'"

TypeError: Cannot create property 'isRootInsert' on string 'Do you Want to delete these items?'

使用的按需加载：

import { Model } from 'ant-design-vue'
Vue.use(Modal)
Vue.prototype.$confirm = Modal.confirm

package.json:

"dependencies": {
    "ant-design-vue": "^1.7.2",
    "core-js": "^3.6.5",
    "vue": "^2.6.11",
    "vue-class-component": "^7.2.3",
    "vue-property-decorator": "^8.4.2",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
