### ISSUE TITLE
1.3.11 不能引入 ant-design-vue/dist/antd.less

### ISSUE THREAD

**Issue by yi-huan** [vueComponent/ant-design-vue#995]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.11

### Environment
win10, chrome 75, vue 2.6.10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-antd-template-x76h1)

### Steps to reproduce
之前根据[文档](https://vue.ant.design/docs/vue/customize-theme-cn/#%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%EF%BC%9F)配置主题，引入 less 样式 `ant-design-vue/dist/antd.less` ，

我看了 `node_modules/ant-design-vue/dist/` 下， 1.3.11 版本并无此 `antd.less` 文件。所以引入报错。

### What is expected?
使用 `import 'ant-design-vue/dist/antd.less';` 能导入文件

### What is actually happening?
```
import 'ant-design-vue/dist/antd.less';
^
Can't resolve 'ant-design-vue/dist/antd.less' in 'D:\web\inetpub\workroot\*****\src-html\src'
```

**Comment by tangjinzhou** [comment]
update to 1.3.13
