### ISSUE TITLE
Error: Cannot find module 'node-emoji'

### ISSUE THREAD

**Issue by KyLeoHC** [vueComponent/ant-design-vue#997]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.13

### Environment
vue 2.5.10

### Reproduction link
[https://github.com/vueComponent/ant-design-vue.git](https://github.com/vueComponent/ant-design-vue.git)

### Steps to reproduce
安装过程

### What is expected?
安装模块依赖过程没有报错

### What is actually happening?
安装过程报Error: Cannot find module 'node-emoji'，我大概看了下postinstall.js这个脚本的代码，这里依赖了node-emoji库来输出一些emoji表情（看起来是想安装完成后弹出一些广告提示），但是package.json把这个node-emoji声明到了devDependencies。虽然不影响使用，但是安装过程报个错看着别扭，希望修复下。

**Comment by alen2018** [comment]
升级下本地npm版本就行
