### ISSUE TITLE
form表单校验时，中英切换，提示内容没有变更

### ISSUE THREAD

**Issue by xuanjinliang** [vueComponent/ant-design-vue#998]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
1.3.10

### Environment
Vue version 2.6.10

### Reproduction link
[https://vue.ant.design/components/form-cn/](https://vue.ant.design/components/form-cn/)

### Steps to reproduce
主要的是 v-decorator 当切换语言时，提示内容没有变更
代码如下:
```
<a-date-picker
        style="width: 100%"
        :showTime="showTime"
        :format="format"
        :placeholder="$t('startTip')"
        :disabledDate="startDisabledDate"
        v-decorator="['startTime', startRule]"
      />

computed: {
  startRule() {
      return {
        rules: [
          {
            required: true,
            message: () => this.$t('startTip')
          }
        ]
      }
    },
}
```

### What is expected?
Language can be switched

### What is actually happening?
Language can be switched

**Comment by sendya** [comment]
可以暂时试试这样使用 https://codesandbox.io/s/vue-antd-template-fbgue

**Comment by xuanjinliang** [comment]
@sendya 目前我是用这个方法解决的，暂时没有问题，谢谢，但希望后期可以修复
```
watch: {
    language: function(val, oldVal) {
      if (val) {
        this.value.validateFields(['startTime', 'endTime'], { force: true })
      }
    }
  }
```
